In [1]:
import pandas as pd
import glob

In [2]:
data = pd.read_csv(r"..\data\data_methaq(1.0).csv")
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan
...,...,...,...,...,...,...,...,...,...,...
1009599,LNGPCMXJ9PL305272,NaN,NaN,APULUO,APULUO AP200 4H,2023.0,Motorcycle,GCC,NaN,China
1009600,LURJAVBM8PA024843,STD,4.0,AIQAR,EQ 1,2023.0,COUPE,GCC,NaN,CHINA
1009601,7KGTC2C48NR003646,NaN,NaN,Electric Motion,ePure,2022.0,Motorcycle,GCC,NaN,AMERICA
1009602,LX6TK334XS2510023,NaN,NaN,CHANGHUA,CH150T-34,2025.0,Motorcycle,GCC,NaN,China
1009603,MI76734700,GL,4.0,MANITOU,MTX1740SLT,2015.0,HEAVY EQUIPMENT,GCC,NaN,Italy

In [3]:
import pandas as pd

data = pd.read_csv(r"../data/data_methaq(1.0).csv")

for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

       chassisNumber trim  cylinders    make    model    year  \
0  RKLBB9HE7F5115863   SE        4.0  TOYOTA  COROLLA  2015.0
1  JTFHX02POF0099797  GLX        4.0  TOYOTA    HIACE  2015.0
2  JTFHX02P7F0094323   DX        4.0  TOYOTA    HIACE  2015.0
3  JTFHXDGP7F0094373   DL        4.0  TOYOTA    HILUX  2015.0
4  4T1BG22K01U789089  XLI        4.0  TOYOTA    CAMRY  2001.0

             bodyType regionalSpec  noOfDoors  origin
0               SEDAN          GCC        4.0  TAIWAN
1  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
2  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
3  PICK UP DOUBLE CAB          GCC        4.0   JAPAN
4               SEDAN      NON-GCC        4.0   JAPAN

In [4]:
data = data[data["make"] == "HONDA"]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
561089,19XFB2649EE901537,EXI,4.0,HONDA,CIVIC,2014.0,SEDAN,GCC,4.0,JAPAN
561090,ME4KC09CCE8688364,DX,4.0,HONDA,ACCORD,2014.0,SEDAN,GCC,4.0,INDIA
561091,ME4KC20D1LA006195,NaN,NaN,HONDA,UNICORN 160,2020.0,MOTORCYCLE,GCC,NaN,INDIA
561092,1HGCT1B85EA002939,DX,4.0,HONDA,ACCORD,2014.0,SEDAN,GCC,4.0,UNITED STATES
561093,JHMFD16249S405906,EXI A/W,4.0,HONDA,CIVIC,2009.0,SEDAN,GCC,4.0,JAPAN
...,...,...,...,...,...,...,...,...,...,...
972949,LVHRM7881S5001834,EX,4.0,HONDA,CRV,2025.0,SUV,NON-GCC,NaN,NaN
972950,JHMFD16287S402620,EXI,4.0,HONDA,CIVIC,2007.0,SEDAN,GCC,NaN,NaN
972951,SMTA614K3STCC2795,NaN,NaN,HONDA,CBR125R,2025.0,MOTORCYCLE,GCC,NaN,THAILAND
972952,5J6RW6896JL701065,TOURING,4.0,HONDA,CRV,2018.0,SUV,GCC,NaN,NaN
972953,MAKGN2675R4100523,LX SPORT,4.0,HONDA,CITY,2024.0,SEDAN,GCC,NaN,NaN

In [5]:
data["WMI"] = data["chassisNumber"].str[0:3]
data["pos0"] = data["chassisNumber"].str[0]
data["pos1"] = data["chassisNumber"].str[1]
data["pos2"] = data["chassisNumber"].str[2]
data["pos4"] = data["chassisNumber"].str[3]
data["pos5"] = data["chassisNumber"].str[4]
data["pos6"] = data["chassisNumber"].str[5]
data["pos7"] = data["chassisNumber"].str[6]
data["pos8"] = data["chassisNumber"].str[7]
data["Model_Year"] = data["chassisNumber"].str[9]
data["Plant_Code"] = data["chassisNumber"].str[10]
data["Serial_Number"] = data["chassisNumber"].str[11:17]

In [6]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos1,pos2,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
561089,19XFB2649EE901537,EXI,4.0,HONDA,CIVIC,2014.0,SEDAN,GCC,4.0,JAPAN,...,9,X,F,B,2,6,4,E,E,901537
561090,ME4KC09CCE8688364,DX,4.0,HONDA,ACCORD,2014.0,SEDAN,GCC,4.0,INDIA,...,E,4,K,C,0,9,C,E,8,688364
561091,ME4KC20D1LA006195,NaN,NaN,HONDA,UNICORN 160,2020.0,MOTORCYCLE,GCC,NaN,INDIA,...,E,4,K,C,2,0,D,L,A,006195
561092,1HGCT1B85EA002939,DX,4.0,HONDA,ACCORD,2014.0,SEDAN,GCC,4.0,UNITED STATES,...,H,G,C,T,1,B,8,E,A,002939
561093,JHMFD16249S405906,EXI A/W,4.0,HONDA,CIVIC,2009.0,SEDAN,GCC,4.0,JAPAN,...,H,M,F,D,1,6,2,9,S,405906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972949,LVHRM7881S5001834,EX,4.0,HONDA,CRV,2025.0,SUV,NON-GCC,NaN,NaN,...,V,H,R,M,7,8,8,S,5,001834
972950,JHMFD16287S402620,EXI,4.0,HONDA,CIVIC,2007.0,SEDAN,GCC,NaN,NaN,...,H,M,F,D,1,6,2,7,S,402620
972951,SMTA614K3STCC2795,NaN,NaN,HONDA,CBR125R,2025.0,MOTORCYCLE,GCC,NaN,THAILAND,...,M,T,A,6,1,4,K,S,T,CC2795
972952,5J6RW6896JL701065,TOURING,4.0,HONDA,CRV,2018.0,SUV,GCC,NaN,NaN,...,J,6,R,W,6,8,9,J,L,701065
972953,MAKGN2675R4100523,LX SPORT,4.0,HONDA,CITY,2024.0,SEDAN,GCC,NaN,NaN,...,A,K,G,N,2,6,7,R,4,100523

In [7]:
data_pos4A = data[data["pos1"] == "H"]
data_pos4A

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos1,pos2,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
561092,1HGCT1B85EA002939,DX,4.0,HONDA,ACCORD,2014.0,SEDAN,GCC,4.0,UNITED STATES,...,H,G,C,T,1,B,8,E,A,002939
561093,JHMFD16249S405906,EXI A/W,4.0,HONDA,CIVIC,2009.0,SEDAN,GCC,4.0,JAPAN,...,H,M,F,D,1,6,2,9,S,405906
561094,JHMCM56584C409657,VTI E,4.0,HONDA,ACCORD,2004.0,SEDAN,GCC,4.0,JAPAN,...,H,M,C,M,5,6,5,4,C,409657
561097,JHMCP26399C403037,LX,4.0,HONDA,ACCORD,2009.0,SEDAN,GCC,4.0,JAPAN,...,H,M,C,P,2,6,3,9,C,403037
561099,JHMCM56563C409929,VTI E,4.0,HONDA,ACCORD,2003.0,SEDAN,GCC,4.0,JAPAN,...,H,M,C,M,5,6,5,3,C,409929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972942,JHMFD162X7S403316,EXI,4.0,HONDA,CIVIC,2007.0,SEDAN,GCC,NaN,NaN,...,H,M,F,D,1,6,2,7,S,403316
972944,JHMFD163X6S404814,LXI,4.0,HONDA,CIVIC,2006.0,SEDAN,GCC,NaN,NaN,...,H,M,F,D,1,6,3,6,S,404814
972945,JHMFD16219S408035,EXI A/W,4.0,HONDA,CIVIC,2009.0,SEDAN,GCC,NaN,NaN,...,H,M,F,D,1,6,2,9,S,408035
972948,JHMCP26788C421675,LXI,4.0,HONDA,ACCORD,2008.0,SEDAN,GCC,NaN,NaN,...,H,M,C,P,2,6,7,8,C,421675
972950,JHMFD16287S402620,EXI,4.0,HONDA,CIVIC,2007.0,SEDAN,GCC,NaN,NaN,...,H,M,F,D,1,6,2,7,S,402620

In [9]:
print(data['pos1'].unique())

['9' 'E' 'H' 'R' 'K' 'F' 'J' 'L' 'V' 'U' 'C' 'A' '3' '7' 'D' 'B' 'P' 'M'
 'X' 'Z' 'S' '6' 'Y' '5' '0' 'G' 'W' '1' '4' 'N' 'I' '2' '8']

In [10]:
print(data['trim'].nunique())

94

In [11]:
print(data['trim'].unique())

['EXI' 'DX' nan 'EXI A/W' 'VTI E' 'LXI' 'LX' 'STD' 'TOURING' 'VTI' 'RVI'
 'EX' 'REALM' 'EX (NON GCC)' 'SPORT' 'LS' 'TYPE R' 'LX SPORT' 'EXI SE'
 'EX-L' 'VTI L' 'EX PLUS' 'EXL' 'STD (NON GCC)' 'RVSI' 'LX LTD' 'EX SPORT'
 'BASE' 'RS' 'LX PLUS' 'S (NON GCC)' 'LTH' '1' 'ES' 'GL' 'DX PLUS'
 'EX NAVIGATION' 'EXV' 'EX-C' 'HEV SPORT' 'EX-D' 'VTI SR AIR BAG ABS'
 'HEV EXL' 'S' 'GH' 'COUPE' 'LAUNCH EDITION' 'LX ( NON GCC)' 'VTI LTH'
 'SPORT (NON GCC)' 'STANDARD' 'EXCLUSIVE' 'EX-L (NON GCC)'
 'TOURING (NON GCC)' 'SX' 'FD' 'SE' 'XLE (NON GCC)'
 'BLACK EDITION (NON GCC)' 'XLI' 'LOUNGE LTH SR AW' '1.5' 'GLI' 'CLOTH'
 'S T1' 'LX TURBO SPORT' 'CIVIC' 'SIR' 'G' 'SUV' 'PL' 'SALOON'
 'NAVIGATION' 'LE' 'TRIM' 'GL TOP' 'SV' 'SLT2' 'TERIM' 'COMBI L3' 'A' 'XT'
 'XL' 'STATION' 'YT' 'TURBO SPORT' 'TREND' 'VTX' 'E' 'SD' 'GLX' 'AMG'
 'EX LTH' 'ROADSTER' 'VTI E SE']

In [12]:
print(data['bodyType'].unique())

['SEDAN' 'MOTORCYCLE' 'SUV' 'PICKUP' 'HATCHBACK' 'MPV' 'COUPE' 'SALOON'
 'CONVERTIBLE' 'STATION' 'COUPE/CABRIOLET' 'VAN' 'PANEL VAN' 'CROSSOVER']

In [13]:
print(data['bodyType'].nunique())

14

In [14]:
print(data['WMI'].unique())

['19X' 'ME4' '1HG' 'JHM' 'MRH' 'RKT' '5FP' '5J6' 'JHL' 'MLH' 'JH2' '2HG'
 'LVH' 'LUC' 'THF' 'LCE' 'MEH' 'MRJ' 'NLA' '5FN' 'SC5' '5KB' 'SC4' 'MAK'
 'SC7' 'MF1' '536' 'DC5' 'PC4' '1HF' 'MEA' 'SHH' 'L7G' 'MET' 'LK1' 'RC9'
 'ZAP' '2HK' 'MD4' 'HLX' '9C2' 'MH1' 'VCE' 'THG' 'JB0' 'SC6' 'SC8' 'RH0'
 'LAL' 'SD1' '3CZ' 'JC6' '1H6' '1HD' 'LRR' 'JC9' '7KG' '57X' 'RD1' 'RP8'
 'HH4' '5HD' 'PC3' 'RH2' 'MC4' 'JHH' 'JMH' 'RH1' 'LF3' '19U' 'MD2' 'NC3'
 'SFN' 'WB1' 'LHG' 'IHF' 'JKA' 'HH3' 'LXE' 'CB6' 'RFC' 'JH4' 'LBB' 'RD0'
 'PP1' '9BS' 'LZB' 'IHG' 'SMT' 'MAH' 'JC7' 'NC4' 'NF0' 'WDB' '2H6' 'YV2'
 'SHS' '7FA' 'JS1' 'NEA' 'MF0' 'MD6' 'MBL' '56W' 'LHY' 'HY2' 'MC3' 'U5Y'
 'KF3' 'LRS' '0D8' 'MB1' 'RFG' 'JYA' 'JAM' 'CD7' '804' 'KC4' 'CPB' 'KF5'
 'HG6' '0HG' 'MH3' 'PF0' 'MA0' 'ML5' 'SC3' 'SC2' 'HGC' 'SD0' '3HG' 'JDA'
 'NA1' 'RM3' 'NHG' 'LSJ' 'RC8' '5JB' '2HJ' 'LXY' '4S6' 'LWB' '109' 'RC6'
 'R18' 'KF4' '3VW' '5K8' 'J1M' 'JM7' 'CJ4' 'SKB' 'JHE' 'UDK' 'JHC' 'RJ1'
 'VBK' '1HC' 'SHI' 'JHD' 'R6W' '1VC' 'E4K' 'CB1' 'KM4' '3GC' 'ZGU' '1HE'
 'SJ1' 'KC2' 'ML4' 'HMF' 'JNC' 'ZDC' 'SH0' '2X8' 'W0L' 'RLH' 'JA4' 'CB7'
 'JNK' 'ZHK' 'MZG' 'ME3' 'TH6' '2HH' '24G' 'KHG' '2L5' 'HA1' 'ER6' 'RC1'
 'P60' 'SJ6' 'PC6' 'JA7' 'SJN' '5Y2' 'NC5' 'RC4' 'SG7' 'LVC' 'HL4' 'WWW'
 'AAV' 'RC7' '2C3' 'DU1' 'JIL' 'ZFM' 'JHA' 'LZW' 'JMF' '123' 'MC1' '1H0'
 'VF7' 'RC0' 'DC2' '16X' 'LA4' 'GCP' 'JHN' 'KMH' 'H09' 'TC1' 'JF3' 'HA2'
 'MC2' 'MLT' '165' 'R3R' 'LX6' '56K' '2BX' 'SED' 'ZDM' 'H84' 'LLC' '157'
 'G21' 'ME1' 'LKI' 'ER0' 'L4H' 'L4U' 'RN6' 'JKB' 'RN5' 'RFB' 'ME6' 'MEG'
 'L6X' 'LZS' 'ZS1' 'MDH' 'LD3' 'QJ2' 'L8Y' 'ZCG']

In [15]:
print(data['WMI'].nunique())

260

In [16]:
filtered_data = data[data['pos1'] == 'N']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

         make  WMI pos0 pos1 pos2 origin             model
590076  HONDA  JNC    J    N    C    NaN            ACCORD
593434  HONDA  JNK    J    N    K  JAPAN            ACCORD
972037  HONDA  RN6    R    N    6  JAPAN  GOLD WING GL1800
972084  HONDA  RN5    R    N    5  JAPAN            CB125F

In [ ]:
filtered_data = data[data['pos1'] != 'N']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2 origin   model
241609  NISSAN  MDH    M    D    H  INDIA   SUNNY
241616  NISSAN  MDH    M    D    H  INDIA   SUNNY
241622  NISSAN  MDH    M    D    H  INDIA   SUNNY
241624  NISSAN  WGY    W    G    Y  JAPAN  PATROL
241627  NISSAN  MDH    M    D    H  INDIA   SUNNY
...        ...  ...  ...  ...  ...    ...     ...
905191  NISSAN  MDH    M    D    H    NaN   SUNNY
905194  NISSAN  T30    T    3    0    NaN  XTRAIL
905206  NISSAN  WGY    W    G    Y    NaN  PATROL
905212  NISSAN  MDH    M    D    H    NaN   SUNNY
905213  NISSAN  MDH    M    D    H    NaN   SUNNY

[22906 rows x 7 columns]

In [17]:
data[['make', 'pos0', 'origin']]

         make pos0         origin
561089  HONDA    1          JAPAN
561090  HONDA    M          INDIA
561091  HONDA    M          INDIA
561092  HONDA    1  UNITED STATES
561093  HONDA    J          JAPAN
...       ...  ...            ...
972949  HONDA    L            NaN
972950  HONDA    J            NaN
972951  HONDA    S       THAILAND
972952  HONDA    5            NaN
972953  HONDA    M            NaN

[52939 rows x 3 columns]

In [ ]:

origin_map = {
    '1': 'USA', '4': 'USA', '5': 'USA',
    '2': 'Canada',
    '3': 'Mexico',
    'J': 'Japan',
    'K': 'Korea',
    'S': 'UK',
    'W': 'Germany',
    'Z': 'Italy',
    'Y': 'Sweden/Finland',
    'L': 'China',
    'M': 'India',
    'V': 'France/Spain'
}
data =

SyntaxError: invalid syntax (4266525012.py, line 15)