In [1]:
import pandas as pd
import glob

In [2]:
data = pd.read_csv(r"..\data\data_methaq(1.0).csv")
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan
...,...,...,...,...,...,...,...,...,...,...
1009599,LNGPCMXJ9PL305272,NaN,NaN,APULUO,APULUO AP200 4H,2023.0,Motorcycle,GCC,NaN,China
1009600,LURJAVBM8PA024843,STD,4.0,AIQAR,EQ 1,2023.0,COUPE,GCC,NaN,CHINA
1009601,7KGTC2C48NR003646,NaN,NaN,Electric Motion,ePure,2022.0,Motorcycle,GCC,NaN,AMERICA
1009602,LX6TK334XS2510023,NaN,NaN,CHANGHUA,CH150T-34,2025.0,Motorcycle,GCC,NaN,China
1009603,MI76734700,GL,4.0,MANITOU,MTX1740SLT,2015.0,HEAVY EQUIPMENT,GCC,NaN,Italy

In [3]:
import pandas as pd

data = pd.read_csv(r"../data/data_methaq(1.0).csv")

for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

       chassisNumber trim  cylinders    make    model    year  \
0  RKLBB9HE7F5115863   SE        4.0  TOYOTA  COROLLA  2015.0
1  JTFHX02POF0099797  GLX        4.0  TOYOTA    HIACE  2015.0
2  JTFHX02P7F0094323   DX        4.0  TOYOTA    HIACE  2015.0
3  JTFHXDGP7F0094373   DL        4.0  TOYOTA    HILUX  2015.0
4  4T1BG22K01U789089  XLI        4.0  TOYOTA    CAMRY  2001.0

             bodyType regionalSpec  noOfDoors  origin
0               SEDAN          GCC        4.0  TAIWAN
1  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
2  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
3  PICK UP DOUBLE CAB          GCC        4.0   JAPAN
4               SEDAN      NON-GCC        4.0   JAPAN

In [4]:
data = data[data["make"] == "NISSAN"]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
241600,MNTBC2C93G6009278,S,4.0,NISSAN,TIIDA,2016.0,HATCHBACK,GCC,NaN,JAPAN
241601,JN1CC13C18T014955,S,4.0,NISSAN,TIIDA,2008.0,HATCHBACK,GCC,5.0,JAPAN
241602,5N1AA08C09N609536,LE,8.0,NISSAN,ARMADA,2009.0,SUV,GCC,5.0,USA
241603,JN8AY2NY3P9470119,LE PLATINUM CITY,8.0,NISSAN,PATROL,2023.0,SUV,GCC,5.0,JAPAN
241604,JN6BE6AS3G9004253,STD,4.0,NISSAN,URVAN,2016.0,PANELVAN WIDE BODY HIGH ROOF,GCC,4.0,JAPAN
...,...,...,...,...,...,...,...,...,...,...
905214,1N4BL4EV7PN359330,SV,4.0,NISSAN,ALTIMA,2023.0,SEDAN,NON-GCC,NaN,NaN
905215,JN1BF5MD3DT100814,SV,4.0,NISSAN,JUKE,2013.0,SUV,GCC,NaN,NaN
905216,JN8BY2NY6M9340738,SE PLATINUM CITY,6.0,NISSAN,PATROL,2021.0,SUV,GCC,NaN,NaN
905217,JN8AY2NEXH9701573,SL (NON GCC),8.0,NISSAN,ARMADA,2017.0,SUV,NON-GCC,NaN,NaN
905218,1N4AL3AP6DC209469,SL,4.0,NISSAN,ALTIMA,2013.0,SEDAN,NON-GCC,NaN,NaN

In [5]:
data["WMI"] = data["chassisNumber"].str[0:3]
data["pos0"] = data["chassisNumber"].str[0]
data["pos1"] = data["chassisNumber"].str[1]
data["pos2"] = data["chassisNumber"].str[2]
data["pos4"] = data["chassisNumber"].str[3]
data["pos5"] = data["chassisNumber"].str[4]
data["pos6"] = data["chassisNumber"].str[5]
data["pos7"] = data["chassisNumber"].str[6]
data["pos8"] = data["chassisNumber"].str[7]
data["Model_Year"] = data["chassisNumber"].str[9]
data["Plant_Code"] = data["chassisNumber"].str[10]
data["Serial_Number"] = data["chassisNumber"].str[11:17]

In [6]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos1,pos2,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
241600,MNTBC2C93G6009278,S,4.0,NISSAN,TIIDA,2016.0,HATCHBACK,GCC,NaN,JAPAN,...,N,T,B,C,2,C,9,G,6,009278
241601,JN1CC13C18T014955,S,4.0,NISSAN,TIIDA,2008.0,HATCHBACK,GCC,5.0,JAPAN,...,N,1,C,C,1,3,C,8,T,014955
241602,5N1AA08C09N609536,LE,8.0,NISSAN,ARMADA,2009.0,SUV,GCC,5.0,USA,...,N,1,A,A,0,8,C,9,N,609536
241603,JN8AY2NY3P9470119,LE PLATINUM CITY,8.0,NISSAN,PATROL,2023.0,SUV,GCC,5.0,JAPAN,...,N,8,A,Y,2,N,Y,P,9,470119
241604,JN6BE6AS3G9004253,STD,4.0,NISSAN,URVAN,2016.0,PANELVAN WIDE BODY HIGH ROOF,GCC,4.0,JAPAN,...,N,6,B,E,6,A,S,G,9,004253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905214,1N4BL4EV7PN359330,SV,4.0,NISSAN,ALTIMA,2023.0,SEDAN,NON-GCC,NaN,NaN,...,N,4,B,L,4,E,V,P,N,359330
905215,JN1BF5MD3DT100814,SV,4.0,NISSAN,JUKE,2013.0,SUV,GCC,NaN,NaN,...,N,1,B,F,5,M,D,D,T,100814
905216,JN8BY2NY6M9340738,SE PLATINUM CITY,6.0,NISSAN,PATROL,2021.0,SUV,GCC,NaN,NaN,...,N,8,B,Y,2,N,Y,M,9,340738
905217,JN8AY2NEXH9701573,SL (NON GCC),8.0,NISSAN,ARMADA,2017.0,SUV,NON-GCC,NaN,NaN,...,N,8,A,Y,2,N,E,H,9,701573
905218,1N4AL3AP6DC209469,SL,4.0,NISSAN,ALTIMA,2013.0,SEDAN,NON-GCC,NaN,NaN,...,N,4,A,L,3,A,P,D,C,209469

In [7]:
data_pos4A = data[data["pos1"] == "N"]
data_pos4A

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos1,pos2,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
241600,MNTBC2C93G6009278,S,4.0,NISSAN,TIIDA,2016.0,HATCHBACK,GCC,NaN,JAPAN,...,N,T,B,C,2,C,9,G,6,009278
241601,JN1CC13C18T014955,S,4.0,NISSAN,TIIDA,2008.0,HATCHBACK,GCC,5.0,JAPAN,...,N,1,C,C,1,3,C,8,T,014955
241602,5N1AA08C09N609536,LE,8.0,NISSAN,ARMADA,2009.0,SUV,GCC,5.0,USA,...,N,1,A,A,0,8,C,9,N,609536
241603,JN8AY2NY3P9470119,LE PLATINUM CITY,8.0,NISSAN,PATROL,2023.0,SUV,GCC,5.0,JAPAN,...,N,8,A,Y,2,N,Y,P,9,470119
241604,JN6BE6AS3G9004253,STD,4.0,NISSAN,URVAN,2016.0,PANELVAN WIDE BODY HIGH ROOF,GCC,4.0,JAPAN,...,N,6,B,E,6,A,S,G,9,004253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905214,1N4BL4EV7PN359330,SV,4.0,NISSAN,ALTIMA,2023.0,SEDAN,NON-GCC,NaN,NaN,...,N,4,B,L,4,E,V,P,N,359330
905215,JN1BF5MD3DT100814,SV,4.0,NISSAN,JUKE,2013.0,SUV,GCC,NaN,NaN,...,N,1,B,F,5,M,D,D,T,100814
905216,JN8BY2NY6M9340738,SE PLATINUM CITY,6.0,NISSAN,PATROL,2021.0,SUV,GCC,NaN,NaN,...,N,8,B,Y,2,N,Y,M,9,340738
905217,JN8AY2NEXH9701573,SL (NON GCC),8.0,NISSAN,ARMADA,2017.0,SUV,NON-GCC,NaN,NaN,...,N,8,A,Y,2,N,E,H,9,701573
905218,1N4AL3AP6DC209469,SL,4.0,NISSAN,ALTIMA,2013.0,SEDAN,NON-GCC,NaN,NaN,...,N,4,A,L,3,A,P,D,C,209469

In [8]:
print(data['pos1'].unique())

['N' 'D' 'G' 'J' 'S' '1' 'M' 'Y' 'A' '3' 'V' 'U' 'R' 'K' 'O' 'H' 'T' 'B'
 'Z' '0' 'P' 'E' 'C' 'I' 'F' '5' '4' '8' '7' 'W' 'L' 'X' '6' '2' '9' 'Q']

In [9]:
print(data['trim'].nunique())

320

In [10]:
print(data['trim'].unique())

['S' 'LE' 'LE PLATINUM CITY' 'STD' 'SL' 'XE 4WD' 'SV' 'LE TITANIUM'
 'STD (NON GCC)' 'SE PLATINUM CITY' 'SE T1' 'SAFARI' 'SL (NON GCC)'
 'SUPER SAFARI T1' 'CLASSIC EX  SALOON' 'SE' 'S T2 TOP' 'SUPER SAFARI'
 'SV (NON GCC)' 'CLASSIC EX' 'S T1' 'SGL' 'GLS MIDLINE' 'NISMO'
 'S (NON GCC)' 'LE T2' 'SE TITANIUM' 'LE T1 +' 'PE' 'TITANIUM' 'SL W/SR'
 'SE T2' 'HT GL' 'SE CSF' 'LE T1' 'SL ABS A/W' 'HT SAFARI' 'SR (NON GCC)'
 'XE 2WD' 'SUPER SAFARI T2' 'S ASF' 'S T2' 'BLACK EDITION' 'LE PLATINUM'
 'PLATINUM' 'XE' 'XE (NON GCC)' 'CTD' 'PLATINUM (NON GCC)' 'SR' 'SPORT'
 'SL NAVI' 'ST' 'SAFARI T1' 'SV PLUS' 'SE CPR' 'NAVIGATION'
 'HIGH ROOF WIDE BODY' 'SAFARI SW' '4' 'TOP' 'SL PLUS' '1' 'SV1'
 'SE T2 LEATHER' 'RVI' 'GLV' 'W' 'PRO 4X' nan 'LE PLATINUM CITY +'
 'CLASSIC SG' 'SV COMFORT' 'CLASSIC XE' 'CLASSIC' 'SUPER SAFARI HT'
 'BICK UP' 'GLE' 'LE TITANIUM +' 'S LIMITED EDITION' 'SV SPORT' 'MID'
 'SR MIDNIGHT' 'CREW CAB PICKUP' 'PERFORMANCE' 'SL TURBO' 'BASE'
 'S PWR OPTS' 'GXR' 'SUV' 'N-TREK' 'PREMIUM' 'PLUS' 'SL ABS' 'GL' 'X'
 'LE T3' 'XL' 'TX' 'GLI' 'SV4' 'SV+' 'GLX' 'EX' 'D' 'PICKUP' 'TRIM'
 'ROADSTER' 'COUPE' 'S P460E' 'ES' 'GT' 'VX' 'PRESIDENTIAL' 'SR2' 'SALOON'
 'STATION ' 'SRMT' 'HSE P400' 'SAT' 'L' 'PICK UP' 'XLI' ' SPORT' '210'
 'GLC' 'PRESTIGE' 'SL LTH' '1500' 'SL PWR+ABS' 'STANDARD' 'SU' 'TXY' 'DLX'
 'C' 'UVS' 'FD' 'FRONTIER' 'SPORT S/T' 'CAR TRIM' 'K' 'VXR' 'LSE' '2400'
 'SDT' 'TITAN' 'PREMIUM PLUS' 'STANDER' 'XLE' 'CSF' 'PROTO' 'SE T' 'UD'
 'FLEET' 'DX' 'SL 2.6L' 'NAVARA' 'T' 'GTI' 'G' 'SD' 'HGH' 'LWB' 'STE'
 'GLS' '1600' '2' 'E' '1.8' 'SIGNATURE' 'LX' 'A' 'TIIDA' 'EX DLX'
 'PICKUP ' 'HS' '0' 'PIKUP' 'AST' 'DFF' 'GTS' 'N' 'LIMITED' 'CSPF'
 'DFGRGRG' 'VAN CARGO' 'GXR FMST' 'SKN' 'AS' 'Z' 'S+' 'SV +' 'ABC' '22222'
 'VVIP' 'HACKBACK' 'STAION' 'SL PWR+S/R' 'SL+ NIM' '1500 CREWCAB SLE Z71'
 'LT' 'S PWR+ABS' 'SS' 'CAR TRIM ' 'NONE' 'GL SR' 'VAN' 'LUX'
 'MAX PREMIUM' 'X TRAIL' 'LS' 'HEAVY' 'TERIM' 'ATS' 'AVANTGARDE SPORTS'
 'STATION' 'TR' 'STANDERD' 'ZX280' 'ST+' 'SL PREMIUM' 'SPECIAL EDITION'
 'P' '1.5' 'GL 4.5L' 'GL TOP' 'SL PWR OPTS' 'HT SAFARI SR'
 'XDRIVE MASTERCLASS' '1000' 'LV4' 'OFF ROAD PACK' 'PIUK UP' 'GF' 'GX'
 'SEL' 'GL A/W' 'IH' 'NISSAN' 'SKYLINE' 'CIVILIAN' 'AXL ' 'SRT'
 'EXCLUSIVE' '123' 'BASW' 'V' 'STF' '6' 'ZX' 'CEDRICK' 'STAND'
 'PATROL GLV' 'GLS LOWLINE' 'DS' 'GLORIA' 'EX-L' 'W12'
 'LE T3 CITY 60TH ANNIVERSARY' 'CE (NON GCC)' 'SED' 'F' 'AUTOMATIC' 'HT'
 'NAVIGATION SPORT' 'S.E' 'EX (NON GCC)' 'ROYAL' 'TRACK' 'SC'
 'PATROL SAFARI' '90' 'STD ' 'AMG' 'PULSAR' 'JEEP' '0000' 'PALATNI'
 '4MATIC' 'GL MID' 'RB26DETT' 'SE PLATINUM CITY +' 'PATROL GL' 'LXI'
 'TIDA' 'NISSAN ' 'PATROL' 'SAFARA' '20' '2400 PICKUP' 'HE' 'MVP' 'GS'
 'PK21' 'SAFARI SW + GAZELLEX EDITION' 'PICK UP ' 'S PWR' '00' '130' 'TRX'
 'PASSANGER VAN' '2000' 'STATION1' 'XT' '917' 'PREMIER' 'SAHARA'
 'STANTDARD' '100' 'SUPER SAFARI T' 'STU' 'LI' 'SUPER SAFARI E WINCH' '5'
 'S OFF ROAD' 'GVH' 'H' '1.5TC I4 C 200' 'SEDAN'
 'SAFARI SW + GAZELLE EDITION' 'LE T3 W/O FES']

In [11]:
print(data['bodyType'].unique())

['HATCHBACK' 'SUV' 'PANELVAN WIDE BODY HIGH ROOF' 'SEDAN' 'PANEL VAN'
 'PICK UP' 'MPV' 'MINI BUS' 'PICK UP DOUBLE CAB' 'STATION' 'PICKUP'
 'COUPE' 'CARGO VAN' 'VAN' 'PICK UP SINGLE CAB' 'HALF PANEL VAN' 'SALOON'
 'LIGHT VEHICLE' 'BUS' 'TRUCK' 'REFRIGERATOR' 'PICKUP SINGLE CABIN'
 'CONVERTIBLE' 'PICKUP TRUCK' 'MOTORCYCLE' 'PICK-UP' 'TANKER' 'MINIVAN'
 'PICKUP DOUBLE CABIN' 'PICK UP DOUBLE CABIN' 'WINDOW VAN'
 'PICK UP DOUBLE C' 'PICKUP DOUBLE CAB' 'VAN CARGO' 'PICK-UP WITH CRANE'
 'TRUCK WITH CRANE' 'WATER TANK' 'SPORTS CAR' 'STATION LIGHT'
 'SEDAN LIGHT VEHICLE' 'MINI BUS LWB WIDE BODY HR' 'DIESEL TANKER']

In [12]:
print(data['bodyType'].nunique())

42

In [13]:
print(data['WMI'].unique())

['MNT' 'JN1' '5N1' 'JN8' 'JN6' '1N4' 'MDH' '3N1' 'WGY' 'KNM' 'SJN' 'JNB'
 'VSK' 'C11' 'PG7' 'SN1' 'KMF' 'KY6' 'B17' '3N6' 'GD2' 'MA3' '1N6' 'T30'
 'JNI' 'LVA' 'C12' 'NU4' 'HR3' 'WGC' 'L10' 'IN4' '3NI' '3N8' 'PKA' 'LGB'
 'MOH' 'VHX' 'JTB' 'YV2' 'WMA' 'INB' 'JH8' 'LJN' 'JHH' '0N4' 'ADN' 'JNS'
 'MB1' 'W1N' 'K13' 'LZZ' 'JY6' '000' 'NON' '010' 'TMB' 'XN8' 'WPO' '6N1'
 'WEF' '5N0' 'UN1' 'B18' 'LET' '2C3' 'NMA' 'WIK' '1GC' 'L3H' 'TN4' 'UN8'
 'RA6' '5NI' 'SNI' 'WDB' 'YS2' 'LA7' 'W09' 'ECR' 'RKM' 'WF0' 'UGY' '9BS'
 'V5K' 'UAE' 'G11' 'NBB' 'CMF' 'T32' '3N0' 'JNG' 'FK1' '5JN' 'MJC' 'JUN'
 'JT8' '5NT' '1FC' 'BNR' 'HGS' 'FZJ' 'JNC' 'WV2' '0D8' '3N3' 'KNA' 'LKL'
 'HCR' 'N4B' 'AS3' 'TB4' 'IN8' 'JPC' 'VR3' 'ENR' '180' '111' 'UNM' 'SNT'
 'AS4' 'JDA' 'TFA' 'MBA' 'CHE' 'YU4' 'KNC' 'JN0' 'JTD' 'BCN' 'ADT' 'LGW'
 'W10' 'FGD' 'DA1' '04P' 'JNA' 'JNT' 'KMH' 'LJ1' 'JM3' '57X' 'AS1' 'W00'
 'JD3' 'MET' 'B12' 'LFC' 'TZA' 'CN1' 'JT1' '343' '1NA' 'MM7' 'LA6' '1N1'
 'HNT' 'JBH' 'WPY' 'JN5' 'HGC' '5N3' 'TWA' 'UN6' '1FD' 'HLS' 'MAT' 'LXG'
 'G1P' 'JL5' 'KCR' '5BZ' 'SDY' 'GCZ' 'L14' 'JMY' 'L5E' 'WYY' '1BA' 'JTF'
 'HJ3' '3NB' '5GA' 'LC4' 'JCB' 'WG1' 'JKA' 'SAL' 'JNJ' 'MPH' 'UFG' 'QON'
 'KPA' 'AH2' 'KMC' 'IN1' 'ZCF' 'KNH' '5M1' 'JF2' '1GY' 'ZAP' 'MGH' 'YSM'
 '56K' 'JT3' 'LEF' 'VWA' 'WDF' 'N51' '3NA' 'WJM' '137' '6T1' 'M0H' 'HK3'
 'VF7' 'D12' '1V2' 'DR3' 'RAJ' 'ML0' 'JTK' 'MMB' 'WD3' 'BAJ' 'CPB' 'HLX'
 '2HN' 'GEF' 'DDD' 'VF3' 'RF5' '5NH' 'NNB' '1FT' 'JNR' 'CMA' '1GB' 'GGG'
 'JS1' 'ML5' 'ING' 'W54' 'ET1' '9KM' 'AMD' 'BEA' 'JTJ' '1NB' '3D7' 'K16'
 'KV6' 'JN3' 'URG' 'VRY' 'JE4' '31A' 'JM1' 'UGD' '2G2' 'Z8N' 'KHG' 'ZGU'
 'MR3' 'STA' '0FM' 'JMR' 'HL4' 'KY0' 'WGN' 'JNE' 'KMT' 'BCA' '2C4' 'WRG'
 'L68' 'LUX' '900' ' 1N' '3NT' 'NM3' 'S14' 'LF1' 'JA8' 'FD4' 'JKB' 'MD2'
 'ON1' 'H25' 'MN3' 'DHB' 'MRA' '171' 'PA3' 'YBL' 'L3A' 'KW3' 'GHL' '1HD'
 'T18' 'NV1' 'LX6' 'MC2' '6G1' 'KN3' 'VBK' '45D' 'MKB' 'HS1' 'CPC' 'RN6'
 'P01' 'WBS' '2FM' 'KRY' 'JH2' 'ZZE' '1C6' 'MDE' 'WB1' 'UNB' 'FE1' 'KEE'
 'S0N' 'WDD' 'NNN' 'DWH' 'ACV' 'P15' 'MLH' 'JAM' 'TDA' '2T2' 'RA5' '3NH'
 'SNL' 'CGY' 'UFY' 'D10' 'KNF' 'VF1' 'LS6' 'WWW' 'NMD' 'VF6' '7KG' 'JH1'
 'CAT' 'S15' 'MUH' 'KN4' 'A31' '55S' 'LWX' '1N8' 'R16' 'ZFA' 'ER3' 'JL6'
 'VRA' '5GR' 'YFH' 'JTG' 'WNY' 'JM5' 'INS' 'WCB' 'LLC' 'TWD' 'MDM' 'LHA'
 'LK6' 'FK4' 'GFD' '8JN' 'K11' 'TBA' 'SHT' 'JK6' 'CLF' 'XUG' 'GH2' '114'
 '190' 'ULG' 'KNR' 'WP0' 'SNJ' 'LWD' 'HDH' 'W0D' 'SC6' 'W45' 'K46' 'PKB'
 'L11' 'SAJ' 'WKF' 'UNI' 'WBA' 'CJR' '36N' 'LGP' 'GSL' 'XLE' 'ZD4' 'C21'
 'ZDM' 'LSK' 'LAK' 'JN4' '1GK' 'RNN' 'HGZ' 'GZ3' 'TEX' 'FHK' '091' 'GN8'
 'OY2' 'FE5' 'ZE1' ' MD' 'JSS' 'L6T' 'J32' 'GX7' 'ZFC' 'KA2' 'PGZ' 'LUN'
 'LN4' 'YWD' '513' 'TRA' 'YV3' 'EZC' 'UNG' 'F23' 'SNA' 'HZ3' 'S3N' 'MAF'
 'JNX' 'CDU' '2VS' 'JNL' 'HBH' 'JTH' 'LGX' '037' 'G1T' 'MD6' 'LZW' '2GC'
 'QD3' 'EX4' 'LBE' 'LDY' 'W11' 'KMJ' 'M0M' 'VQ3' 'SIN' 'SUN' 'N1C' 'GIT'
 'VK5' 'KMG' 'D11' 'RPS' 'JHD' 'NM0' '4WG' 'JJJ' 'GJ2' 'KG5' 'MA1' 'JAA'
 '1D7' 'JYA' '31C' 'INA' '358' '1C3' '5VP' ' JN' 'ANE' '1G1' '148' 'LZG'
 'LSC' 'RX1' 'FB1' 'HLC' 'MLG' 'RMR' 'CR3']

In [14]:
print(data['WMI'].nunique())

499

In [19]:
filtered_data = data[data['pos1'] == 'N']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2 origin   model
241600  NISSAN  MNT    M    N    T  JAPAN   TIIDA
241601  NISSAN  JN1    J    N    1  JAPAN   TIIDA
241602  NISSAN  5N1    5    N    1    USA  ARMADA
241603  NISSAN  JN8    J    N    8  JAPAN  PATROL
241604  NISSAN  JN6    J    N    6  JAPAN   URVAN
...        ...  ...  ...  ...  ...    ...     ...
905214  NISSAN  1N4    1    N    4    NaN  ALTIMA
905215  NISSAN  JN1    J    N    1    NaN    JUKE
905216  NISSAN  JN8    J    N    8    NaN  PATROL
905217  NISSAN  JN8    J    N    8    NaN  ARMADA
905218  NISSAN  1N4    1    N    4    NaN  ALTIMA

[189518 rows x 7 columns]

In [16]:
filtered_data = data[data['pos1'] != 'N']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2 origin   model
241609  NISSAN  MDH    M    D    H  INDIA   SUNNY
241616  NISSAN  MDH    M    D    H  INDIA   SUNNY
241622  NISSAN  MDH    M    D    H  INDIA   SUNNY
241624  NISSAN  WGY    W    G    Y  JAPAN  PATROL
241627  NISSAN  MDH    M    D    H  INDIA   SUNNY
...        ...  ...  ...  ...  ...    ...     ...
905191  NISSAN  MDH    M    D    H    NaN   SUNNY
905194  NISSAN  T30    T    3    0    NaN  XTRAIL
905206  NISSAN  WGY    W    G    Y    NaN  PATROL
905212  NISSAN  MDH    M    D    H    NaN   SUNNY
905213  NISSAN  MDH    M    D    H    NaN   SUNNY

[22906 rows x 7 columns]

In [20]:
data[['make', 'pos0', 'origin']]

          make pos0 origin
241600  NISSAN    M  JAPAN
241601  NISSAN    J  JAPAN
241602  NISSAN    5    USA
241603  NISSAN    J  JAPAN
241604  NISSAN    J  JAPAN
...        ...  ...    ...
905214  NISSAN    1    NaN
905215  NISSAN    J    NaN
905216  NISSAN    J    NaN
905217  NISSAN    J    NaN
905218  NISSAN    1    NaN

[212424 rows x 3 columns]

In [18]:

origin_map = {
    '1': 'USA', '4': 'USA', '5': 'USA',
    '2': 'Canada',
    '3': 'Mexico',
    'J': 'Japan',
    'K': 'Korea',
    'S': 'UK',
    'W': 'Germany',
    'Z': 'Italy',
    'Y': 'Sweden/Finland',
    'L': 'China',
    'M': 'India',
    'V': 'France/Spain'
}
data =

SyntaxError: invalid syntax (4266525012.py, line 15)