In [1]:
import pandas as pd
import glob

# Reading the csv file

In [2]:
data = pd.read_csv(r"..\data\data_methaq(1.0).csv")
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan
...,...,...,...,...,...,...,...,...,...,...
1009599,LNGPCMXJ9PL305272,NaN,NaN,APULUO,APULUO AP200 4H,2023.0,Motorcycle,GCC,NaN,China
1009600,LURJAVBM8PA024843,STD,4.0,AIQAR,EQ 1,2023.0,COUPE,GCC,NaN,CHINA
1009601,7KGTC2C48NR003646,NaN,NaN,Electric Motion,ePure,2022.0,Motorcycle,GCC,NaN,AMERICA
1009602,LX6TK334XS2510023,NaN,NaN,CHANGHUA,CH150T-34,2025.0,Motorcycle,GCC,NaN,China
1009603,MI76734700,GL,4.0,MANITOU,MTX1740SLT,2015.0,HEAVY EQUIPMENT,GCC,NaN,Italy

In [3]:
import pandas as pd

data = pd.read_csv(r"../data/data_methaq(1.0).csv")

for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

       chassisNumber trim  cylinders    make    model    year  \
0  RKLBB9HE7F5115863   SE        4.0  TOYOTA  COROLLA  2015.0
1  JTFHX02POF0099797  GLX        4.0  TOYOTA    HIACE  2015.0
2  JTFHX02P7F0094323   DX        4.0  TOYOTA    HIACE  2015.0
3  JTFHXDGP7F0094373   DL        4.0  TOYOTA    HILUX  2015.0
4  4T1BG22K01U789089  XLI        4.0  TOYOTA    CAMRY  2001.0

             bodyType regionalSpec  noOfDoors  origin
0               SEDAN          GCC        4.0  TAIWAN
1  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
2  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
3  PICK UP DOUBLE CAB          GCC        4.0   JAPAN
4               SEDAN      NON-GCC        4.0   JAPAN

In [4]:
data = data[data["make"] == "TOYOTA"]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN
...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN

# checking chassis number length and 10th pos

In [5]:
data["chassis_len"] = data["chassisNumber"].str.len()
data["pos10"] = data["chassisNumber"].str[9]

is_standard = (data["chassis_len"] == 17) & (~data["pos10"].isin(['I', 'O', 'Q', 'U', 'Z', '0']))
data = data[is_standard]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,chassis_len,pos10
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,17,F
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,17,F
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,17,F
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,17,F
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,17,1
...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,17,K
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,17,S
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,17,M
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,17,S
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,17,M

In [6]:
data["WMI"] = data["chassisNumber"].str[0:3]
data["pos0"] = data["chassisNumber"].str[0]
data["pos1"] = data["chassisNumber"].str[1]
data["pos2"] = data["chassisNumber"].str[2]
data["VDS"] = data["chassisNumber"].str[3:8]
data["pos4"] = data["chassisNumber"].str[3]
data["pos5"] = data["chassisNumber"].str[4]
data["pos6"] = data["chassisNumber"].str[5]
data["pos7"] = data["chassisNumber"].str[6]
data["pos8"] = data["chassisNumber"].str[7]
data["Model_Year"] = data["chassisNumber"].str[9]
data["Plant_Code"] = data["chassisNumber"].str[10]
data["Serial_Number"] = data["chassisNumber"].str[11:17]

C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["WMI"] = data["chassisNumber"].str[0:3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos0"] = data["chassisNumber"].str[0]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos1"] = data["chassisNumber"].str[1]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos2"] = data["chassisNumber"].str[2]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["VDS"] = data["chassisNumber"].str[3:8]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos4"] = data["chassisNumber"].str[3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos5"] = data["chassisNumber"].str[4]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos6"] = data["chassisNumber"].str[5]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos7"] = data["chassisNumber"].str[6]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos8"] = data["chassisNumber"].str[7]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Model_Year"] = data["chassisNumber"].str[9]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Plant_Code"] = data["chassisNumber"].str[10]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\2455094619.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Serial_Number"] = data["chassisNumber"].str[11:17]

In [7]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos2,VDS,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,L,BB9HE,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,F,HXDGP,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,1,BG22K,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,0,HU8CD,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,M,ABBBJ,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,M,HX01J,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,E,AACAJ,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,F,B29F3,B,2,9,F,3,M,2,123579

data[["pos1", "origin"]]

In [8]:
print(data['chassisNumber'].nunique())

239212

In [9]:
print(data['pos1'].unique())

['K' 'T' 'R' 'H' 'I' 'N' 'Z' 'V' 'M' 'D' 'Y' 'F' 'B' 'E' 'S' 'W' 'J' 'A'
 '0' 'G' '3' 'C' 'P' 'X' '1' '8' '7' 'L' '6' '2' '5' '9' 'U']

In [10]:
print(data['trim'].nunique())

353

In [11]:
print(data['trim'].unique())

['SE' 'GLX' 'DX' 'DL' 'XLI' 'VX' 'MID' 'DLX' 'VXR' 'FABRIC' 'E' 'TOP'
 'EXTREME' 'GL' 'BASE' 'S' 'FLEET' 'STD (NON GCC)' 'GXR' 'EXR'
 'SE+ ANNIVERSARY EDITION' 'GL2' 'SR5' 'STD' 'LE' 'XLI MID' 'LE (NON GCC)'
 'SE+' 'GLI' 'SR5 (NON GCC)' 'TX' 'LIMITED' 'XLE (NON GCC)'
 'SE TRD AERO PK' 'EX' 'ICONIC' 'VX MID' 'LE HEV' 'SGLX' 'PW CL' 'GX'
 'XLE' 'SPORT' 'G' 'GRANDE' 'GR' 'XLI TOP' 'S TRD SPORT PK' 'S+' 'PRO'
 'XLI RB' 'LIMITED PREMIUM' 'GLE' 'XLI EXECUTIVE' 'GLS' 'PLATINUM'
 'DLX TOP' 'TURBO G RA' 'LIMITED (NON GCC)' 'SR5 4X4' 'VXR HEV' 'GLE HEV'
 'SAFARI' 'LX' 'GXR TOP 60TH ANNIV. XTREME' 'CE (NON GCC)' 'GLI HEV'
 'PREMIUM' 'XLI EXECUTIVE MR' 'XL' 'GXR TOP' 'VXR BASE' 'LX AC PWR OPT'
 'LX WINCH' 'TX-L' 'XLE TOURING' 'GXR GT' 'DLS' 'VXR TOP' 'SC'
 'GLE-X HEV 40TH ANNIV' 'SALOON' nan 'ADVENTURE'
 'CREWMAX CAPSTONE (NON GCC)' 'LE STD' 'LIMITED MID' 'GX TOP' 'TX-L TOP'
 'GLI TOP' 'EXCLUSIVE' 'XSE (NON GCC)' 'BLACK EDITION' 'DX H/R W/B'
 'C (NON GCC)' 'XLI POWER OPT' 'GLX SPORT Z' 'S PLUS' 'VTX' 'GXL' 'HT SWB'
 'GXR MID' 'ECO' 'GX MID' 'GXR2' 'LWB HIGH ROOF' '1794 EDITION (NON GCC)'
 '40TH ANNIVERSARY EDITION' 'TOURING' 'HEV' 'GLI TOP LTH' 'PS PW CL'
 'LIMITED 4X4' 'GR SPORT' 'STD D' 'TXL1' 'LWB' 'DLS - STD ROOF' 'EXR HEV'
 'LSE' 'BE' 'GLE-X' 'GT' 'T' 'SWB' 'SE (NON GCC)' 'SR' 'GTX' 'TXL3'
 'GR TAN EDITION' 'ST' 'E PLUS HEV' '1.8' 'LIMITED 4X2' 'VX TOP LTH' 'VX2'
 'STANDARD' 'SV' 'SR5 4X2' 'VX1' 'GXR FMST' 'HEV GLI' 'GXR1' 'DYNAMIC'
 'XLI EXECUTIVE HEV' '1' 'GR-S' 'FJ STD' 'GR BLUE EDITION' 'TRD' 'YX'
 'GXR TOP DMST' 'LMV' 'CTD' 'HT VXR' 'LIMITED TRD SPORT PK' 'VXR TOP LTH'
 'TXR' 'XLE HEV' 'STD AC' 'XLT' 'COUPE' '1500' 'X' 'TRD OFF-ROAD' 'BUS'
 'GLE HEV BLACK EDITION' 'Y PLUS' 'SR (NON GCC)' 'STATION' 'PICK UP' 'TX1'
 'SEDAN' 'GXR SOD D/AC AW' 'TC (NON GCC)' 'LIMITED HEV' 'SL' 'XTREME'
 'TXL2' 'GXR4' 'GXR TOP FMST' 'GT SPORT' 'HARD TOP' 'HYBRID (NON GCC)'
 'GL TOP' 'XSE' 'GRD' 'L' 'SGL' 'SED' '2400' 'GRANDE HEV 40TH ANNIV' 'AIR'
 'TRD SPORT' 'STANDDARD' '0' 'AXL ' 'XLI - AW' 'TURBO G' 'GXR-V' 'STAN'
 'VT' 'GA' 'GXR+' '2.0L' '25HX' 'PREMIER' 'GXR3' '6' 'SE TRD SPORT PK'
 'AUTOMATIC' 'LUMIERE HEV' 'STANDER' 'TRIM' 'LEVIN' 'HILUX' 'EXI'
 'LAND CRUSIER' '4X4' 'XE 4WD' 'A' 'STATION1' 'GXR MID 60TH ANNIV. XTREME'
 'VXR MID' 'PICKUP' 'S ASF' 'GL DECKLESS' 'CRESSIDA' 'LS' 'HYBRID'
 'LUXURY' 'GF' 'HT SLWB' 'CABRIO' 'ADVENTTURE' 'STD CARGO' 'HYCROSS' 'GG'
 'STATION ' 'SLD' 'C' 'PRESTIGE' 'Y' 'LUMIERE 40TH ANNIV' 'GRANDE HEV'
 'PIKUP' 'PRADO' 'LTD HEV' '10TH VICTORY EDITION' 'ROYAL' 'GL LIMITED'
 'CE' 'LIMITED TRD AERO PK' 'SS' 'VX2 PLUS' 'FULL OPTION' 'VXR TOP XTREME'
 '4WD' 'GLI TOP LEATHER' '60TH' 'AT' 'GXL 1ST EDITION' 'USF'
 'DLS HIGH ROOF' '1500 CREWCAB SLE Z71' 'ORION' 'STANDERD' 'VX-L MID'
 'GGG' 'GLS TOP' 'COMFORT' 'MPV' 'VIP7' 'LTZ' '45' 'LIMITED TOP'
 'EXECUTIVE' 'STD  (NON GCC)' '4' 'PLATINUM LUXURY 4X4' 'N' 'NON GCC'
 'GLI MR HEV' 'SENA' 'CAR TRIM' 'LX WIDE TYRES' 'SPORTS' 'COASTER'
 'S T2 TOP' 'AMBIENTE' 'VX-L TOP' 'PICKUP ' 'LUXURY SPORT' 'GV'
 'ADVENTURE 1ST EDITION' 'ASD' 'AA' 'AMG' 'YA' 'TR' 'EXCELLENCE' 'SU'
 'GLX PREMIUM' 'ZX' 'TUNDRA' 'GLS LOWLINE' 'SUPER SAFARI T1' 'ABC'
 'DOUBLE CABIN ' 'GL LTH' 'DTD' 'ROYAL EDITION' '2' 'ASAD' 'LXI' '1.5'
 'GC' 'GXR MID XTREME' '90' 'TOP LTH' 'STEALTH' 'ALTIS (NON GCC)' 'H'
 'S TRD AERO PK' '40 TFSI S-LINE' 'SUV' 'SE T2' 'FR-S (NON GCC)' 'DC'
 'LE PLATINUM CITY' 'PICK' 'GXR MID 60TH ANNIVERSARY' 'SLT' 'SINGLE CABIN'
 'S T1' 'VTI' 'CARRERA GTS' 'EX MID' 'TRTIM' 'VAN' 'XLI ' 'TAXI' 'COM'
 'IM' 'GXR HEV' '1000' 'SPORTS BASIC' 'ADVENTURE 1ST EDITIO'
 '40TH ANNIVERSARY EDI' 'GXR TOP 60TH ANNIV. ' '1794 EDITION (NON GC'
 'XLI HEV' 'SE+ ANNIVERSARY EDIT' 'CREWMAX CAPSTONE (NO']

In [12]:
print(data['bodyType'].unique())

['SEDAN' 'MINI BUS HIGH ROOF' 'PICK UP DOUBLE CAB' 'SUV' 'HATCHBACK'
 'PICK UP SINGLE CAB' 'PANEL VAN' 'BUS' 'MPV' 'ESTATE' 'PICK UP' 'VAN'
 'MINI BUS' 'COUPE' 'SUV- CROSSOVER' 'PICKUP' 'SALOON'
 'PANEL VAN HIGH ROOF' 'STATION' 'HALF PANEL VAN' 'CONVERTIBLE'
 'CARGO VAN' 'MINIVAN' 'MINI BUS SEMI HIGH ROOF' 'CARAVAN' 'PICKUP TRUCK'
 'LIGHT VEHICLE' 'MOTORCYCLE' 'PICKUP SINGLE CABIN' 'TRUCK'
 'PICK UP DOUBLE CABIN' 'PICKUP DOUBLE CABIN' 'COUPE/CABRIOLET'
 'AMBULANCE' 'REGULAR CAB' 'PICKUP DOUBLE CAB' 'WINDOW VAN' 'WAGON'
 'PICK-UP']

In [13]:
print(data['bodyType'].nunique())

39

In [14]:
print(data['WMI'].unique())

['RKL' 'JTF' '4T1' 'JTM' 'JTD' 'MR0' 'JTE' 'MR2' '6T1' '5TF' 'MHF' 'JTN'
 'JTC' 'JTG' '5TD' '4TA' 'JIF' 'MHK' 'MRO' 'MR1' '1NX' '2T3' 'JT3' 'JT2'
 'WZ1' '2T1' 'LVG' 'NMT' 'WDB' '5YF' 'JT4' '4T4' 'JTB' 'LFM' '3TM' 'JF1'
 '5TB' '7MU' 'MBJ' '3MY' 'ANE' '1N4' '8T1' '4T3' '5TE' 'JTK' 'ZE1' 'KMF'
 'STB' 'ZSG' 'VNK' 'WWW' 'JD4' 'JT6' 'STF' 'SJK' '3TY' 'LFP' 'JAA' 'JMY'
 'JJ5' 'LA7' 'WV1' 'YV2' 'MHE' 'INX' 'JN8' 'JNB' 'JTV' 'D04' 'JHG' '1GC'
 'JN6' 'SYF' 'GTF' 'KN9' '137' '4TI' 'LZC' 'LVC' 'ZGE' '6TI' '2CN' 'JWT'
 'MB1' 'JM3' 'UP1' 'KNC' 'MM7' 'STD' 'YS2' 'JZA' 'LXG' 'ZAP' 'JCB' 'LHA'
 'MA1' '000' 'ME4' 'JHE' '4TT' '411' 'RP8' 'U8Q' 'ITG' 'LGW' 'JHH' 'RA6'
 'MMM' '5T1' 'MAF' 'JT0' 'TNX' 'LWL' 'LA6' 'MA3' 'WDD' '9BS' '2FU' 'KNF'
 'NNN' '5T8' 'MMB' 'WBW' '57W' 'MRI' 'LTA' 'LFV' 'JTH' 'ZRE' 'JHF' 'WMA'
 'JL6' 'LVA' 'MAT' 'LKL' 'LZW' 'AAP' '7SV' 'VF3' 'ACV' '5TT' 'KN3' '1FD'
 'KMH' 'MZB' 'JND' 'MET' '213' 'MRD' '5FP' 'MD2' 'ITN' '2C4' 'JN1' 'ZZE'
 'LTV' 'CLG' 'LRR' 'LJ1' '2GN' '1D7' 'JIM' 'LCF' 'L7X' 'JTS' 'FZJ' 'LEF'
 '2GC' 'LC0' 'KMJ' '1FT' '611' 'MLH' 'UAE' 'JAC' '3N6' 'WD4' 'LSK' '5HD'
 'IG1' 'WMW' 'JH4' 'KLA' 'GT1' 'MD6' 'NV1' 'MNT' 'LK1' 'KPD' 'STO' 'JTL'
 'JT8' 'RKM' 'SCR' 'WDA' 'LZZ' 'WYU' 'WCY' 'NSP' 'KL7' 'MMC' 'LM8' '00N'
 'NCP' '1GN' '1GD' 'LJN' 'GGG' 'JRN' 'KPB' '4T2' 'LET' 'WAU' 'KL3' 'KN4'
 'JT5' 'WME' 'UTG' '3N1' 'JL5' 'JL7' 'JHD' 'LCO' 'JTZ' 'LSC' 'SAL' 'MH3'
 'ZFC' 'LPS' 'N1N' 'JD2' 'JZS' '1GT' '1C6' 'VR3' 'MYN' '6TT' 'LS4' 'JJ7'
 'WD8' 'YV1' 'KLI' 'VS5' 'SXV' 'LVV' 'MFH' 'L3H' 'HJN' 'ZGU' 'JE3' '5XX'
 'JN2' 'L6T' 'J1G' 'WZI' 'LSG' 'JS1' 'JHM' '6TD' '2TI' '3GY' '1G6' '211'
 '9KM' 'MC1' 'AR2' 'JIN' 'JIG' '1HD' 'JA3' 'LGD' '1C4' '1ST' 'RN1' 'LVB'
 'JNC' 'LGF' 'MEJ' 'KNR' '123' '5NF' 'SMV' 'WBA' 'RK4' 'MDH' 'STE' 'LSJ'
 'KL1' '55S' 'LM6' 'FJ4' 'YN8' 'LSF' 'MBI' '471' 'EE1' 'MC2' 'MKH' 'JNK'
 'JTJ' '2HN' '454' '6T0' 'RKT' 'MV1' 'MK2' '1GJ' 'UTD' '5N1' 'RKE' 'LMX'
 '1G1' 'LK6' 'JTR' 'YAR' 'BT1' '4F4' '8LT' 'LA9' 'MPA' '671' '1TF' '1N6'
 'CTF' 'W1W' 'SXA' 'LSY' '1TG' '1N1' 'LHP' 'JAM' '3D7' 'MPJ' 'IN6' '5AL'
 'MP2' 'JM7' 'LZY' 'ITD' '1C8' 'LAZ' '090' 'INB' 'W11' 'CPB' '6TB' 'KNA'
 'JH2' 'STY' '074' '010' 'JS2' 'SMT' 'ST1' '5T0' 'LHG' 'WV2' 'UZS' 'VF1'
 'STM' '2D4' 'W01' 'JYM' 'EP9' '3TD' 'D02' 'J1D' 'L3A' 'VF7' 'MRU' 'JTU'
 'KL5' 'ZCF' 'K1K' 'ZT3' 'LFZ' '61L' 'AVV' 'JTA' 'JDT' 'FJ7' 'ITE' 'LS6'
 '5GT' 'M0F' 'AUS' '150' 'RF5' 'AT1' 'LVM' 'VZE' 'CM8' 'JT1' 'LBB' 'XWB'
 'L11' 'HJR' '4T0' '180' 'YBL' 'MHM' '1G0' 'WB1' '6TF' '1V2' '425' '1HG'
 '1G2' '111' 'WVG' 'A25' 'WVW' 'LVZ' '25T' 'LGJ' 'HA9' 'LFB' 'LNB' 'W1K'
 '474' '174' 'KNM' 'YSM' 'JED' '1LN' 'MB0' 'MBT' '5ZT' '3GN' 'WP0' 'CE1'
 'AS3' 'ET1' 'MFF' 'J10' '3T1' 'MHP' 'LFC' 'EL5' 'GX9' '1TM' 'AE1' 'HJ4'
 'BKL' 'K20' 'SKF' 'LDP' 'MRC' 'UTM' 'JNE']

In [15]:
print(data['WMI'].nunique())

451

In [16]:
filtered_data = data[data['pos1'] == 'T']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2 origin               model
1       TOYOTA  JTF    J    T    F  JAPAN               HIACE
2       TOYOTA  JTF    J    T    F  JAPAN               HIACE
3       TOYOTA  JTF    J    T    F  JAPAN               HILUX
4       TOYOTA  4T1    4    T    1  JAPAN               CAMRY
5       TOYOTA  JTM    J    T    M  JAPAN        LAND CRUISER
...        ...  ...  ...  ...  ...    ...                 ...
922347  TOYOTA  6T1    6    T    1    NaN        CAMRY HYBRID
922349  TOYOTA  6T1    6    T    1    NaN        CAMRY HYBRID
922351  TOYOTA  JTM    J    T    M    NaN        LAND CRUISER
922352  TOYOTA  JTM    J    T    M    NaN        LAND CRUISER
922353  TOYOTA  JTE    J    T    E    NaN  LAND CRUISER PRADO

[179111 rows x 7 columns]

In [17]:
filtered_data = data[data['pos1'] != 'T']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2    origin          model
0       TOYOTA  RKL    R    K    L    TAIWAN        COROLLA
7       TOYOTA  MR0    M    R    0  THAILAND          HILUX
11      TOYOTA  MR2    M    R    2  THAILAND          YARIS
15      TOYOTA  MR0    M    R    0  THAILAND          HILUX
17      TOYOTA  RKL    R    K    L    TAIWAN        COROLLA
...        ...  ...  ...  ...  ...       ...            ...
922339  TOYOTA  VNK    V    N    K       NaN          YARIS
922344  TOYOTA  RKL    R    K    L       NaN  COROLLA CROSS
922348  TOYOTA  MHK    M    H    K       NaN         AVANZA
922350  TOYOTA  MR0    M    R    0       NaN          HILUX
922354  TOYOTA  MHF    M    H    F       NaN          YARIS

[60103 rows x 7 columns]

In [18]:
data[['make', 'pos0', 'origin']]

          make pos0  origin
0       TOYOTA    R  TAIWAN
1       TOYOTA    J   JAPAN
2       TOYOTA    J   JAPAN
3       TOYOTA    J   JAPAN
4       TOYOTA    4   JAPAN
...        ...  ...     ...
922350  TOYOTA    M     NaN
922351  TOYOTA    J     NaN
922352  TOYOTA    J     NaN
922353  TOYOTA    J     NaN
922354  TOYOTA    M     NaN

[239214 rows x 3 columns]

In [19]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos2,VDS,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,L,BB9HE,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,F,HXDGP,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,1,BG22K,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,0,HU8CD,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,M,ABBBJ,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,M,HX01J,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,E,AACAJ,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,F,B29F3,B,2,9,F,3,M,2,123579

# Cutting out wrong data

In [20]:
data_pos0_1 = data[data['pos0'] == '1']
data_pos0_1[['make','pos0', 'WMI','origin']]

          make pos0  WMI         origin
96      TOYOTA    1  1NX        AMERICA
863     TOYOTA    1  1NX  UNITED STATES
956     TOYOTA    1  1NX            USA
1191    TOYOTA    1  1N4          JAPAN
1494    TOYOTA    1  1NX        AMERICA
...        ...  ...  ...            ...
919730  TOYOTA    1  1NX            NaN
920802  TOYOTA    1  1NX            NaN
920945  TOYOTA    1  1NX            NaN
921403  TOYOTA    1  1NX            NaN
921876  TOYOTA    1  1NX            NaN

[1334 rows x 4 columns]

In [21]:
print(data_pos0_1['origin'].unique())

['AMERICA' 'UNITED STATES' 'USA' 'JAPAN' 'PAKISTAN' 'CANADA'
 'UNITED KINGDOM' 'UAE' nan 'TAIWAN' 'THAILAND' 'SOUTH AMERICAN'
 'GUAM (USA)']

In [22]:
data_pos0_4 = data[data['pos0'] == '4']
data_pos0_4[['make','pos0', 'WMI','origin']]

          make pos0  WMI         origin
4       TOYOTA    4  4T1          JAPAN
26      TOYOTA    4  4T1  UNITED STATES
38      TOYOTA    4  4T1          JAPAN
57      TOYOTA    4  4T1          JAPAN
63      TOYOTA    4  4TA          JAPAN
...        ...  ...  ...            ...
922268  TOYOTA    4  4T1            NaN
922273  TOYOTA    4  4T1            NaN
922314  TOYOTA    4  4T1            NaN
922322  TOYOTA    4  4T1            NaN
922334  TOYOTA    4  4T1            NaN

[22374 rows x 4 columns]

In [23]:
print(data_pos0_4['origin'].unique())

['JAPAN' 'UNITED STATES' 'AUSTRALIA' 'USA' 'AMERICA' 'UNITED KINGDOM'
 'UAE' 'UNITED STATES VIRGIN ISLANDS' 'UNITED NATIONS' nan 'CANADA'
 'GUAM (USA)' 'AFGHANISTAN' 'UNITED ARAB EMIRATES' 'GERMANY' 'U.S.A'
 'MACAU' 'NON GCC' 'ITALY' 'USA MINOR OUTLYING ISLANDS' 'INDIA' 'AUSTRIA'
 'CAMEROON' 'AMERICAN' 'MAE' 'SOUTH KOREA' 'KOREA' 'GCC'
 'PAPUA NEW GUINEA' 'GUINEA' 'YEMEN' 'SPAIN' 'JAPANN' 'اليابان' 'RUSSIA'
 'CHINA' 'A' 'SOUTH AMERICAN' 'AMERICAN SAMOA' 'GREAT BRITAIN'
 'VIRGIN ISLANDS (USA)' 'JERSEY' 'UMM AL QUWAIN' 'GREECE' 'PAKISTAN'
 'KOREA SOUTH' 'ASIAN' 'EMIRATES']

In [24]:
data_pos0_5 = data[data['pos0'] == '5']
data_pos0_5[['make','pos0', 'WMI','origin']]

          make pos0  WMI         origin
25      TOYOTA    5  5TF        AMERICA
50      TOYOTA    5  5TD        AMERICA
61      TOYOTA    5  5TD        AMERICA
69      TOYOTA    5  5TD          JAPAN
112     TOYOTA    5  5TD  UNITED STATES
...        ...  ...  ...            ...
922272  TOYOTA    5  5TF            NaN
922289  TOYOTA    5  5TD            NaN
922302  TOYOTA    5  5TF            NaN
922313  TOYOTA    5  5TD            NaN
922337  TOYOTA    5  5TD            NaN

[14143 rows x 4 columns]

In [25]:
print(data_pos0_5['origin'].unique())

['AMERICA' 'JAPAN' 'UNITED STATES' 'USA' 'CANADA'
 'UNITED STATES VIRGIN ISLANDS' 'AMERICAN SAMOA' 'GUAM (USA)' 'CHINA'
 'UNITED STATES VIRGIN' 'UAE' 'UNITED KINGDOM' nan 'AUSTRALIA' 'GUINEA'
 'UNITED NATIONS' 'JAMERICA' 'US' 'NORTH AMERICA' 'AFGHANISTAN'
 'الولايات المتحدة' 'MEXICO' 'INDIA' 'USA MINOR OUTLYING ISLANDS'
 'N AMERICAN COUNTRIES' 'SOUTH KOREA' 'امريكا' 'EGYPT' 'GCC' 'THAILAND'
 'SLOVAKIA' 'SILVER' 'INDONESIA' 'UNITED ARAB EMIRATES' '000' '00'
 'AMERICA ' 'VIRGIN ISLANDS (USA)' 'GERMANY' 'JAPANE' 'GREAT BRITAIN'
 'TURKEY' 'BELGIUM' 'EMIRATES' 'KOREA' 'AMERICAN']

In [26]:
data_pos0_2 = data[data['pos0'] == '2']
data_pos0_2[['make','pos0', 'WMI','origin']]

          make pos0  WMI         origin
106     TOYOTA    2  2T3         CANADA
158     TOYOTA    2  2T3         CANADA
206     TOYOTA    2  2T1         CANADA
222     TOYOTA    2  2T1  UNITED STATES
293     TOYOTA    2  2T1          JAPAN
...        ...  ...  ...            ...
921738  TOYOTA    2  2T3            NaN
921772  TOYOTA    2  2T1            NaN
922102  TOYOTA    2  2T3            NaN
922176  TOYOTA    2  2T1            NaN
922227  TOYOTA    2  2T3            NaN

[4606 rows x 4 columns]

In [27]:
print(data_pos0_2['origin'].unique())

['CANADA' 'UNITED STATES' 'JAPAN' 'UNITED STATES VIRGIN' 'TAIWAN'
 'AMERICA' 'USA' 'OTHERS' 'GREECE' 'SOUTH KOREA' nan 'KENYA' 'CHINA'
 'BELGIUM' 'PAPUA NEW GUINEA' 'MOROCCO' 'UAE' 'CAPAN' 'GHANA'
 'UNITED KINGDOM' 'GERMANY' 'HUNGARY' 'UNITED ARAB EMIRATES' 'MYANMAR'
 'THAILAND' 'ITALY' 'JAE']

In [28]:
data_pos0_3 = data[data['pos0'] == '3']
data_pos0_3[['make','pos0', 'WMI','origin']]

          make pos0  WMI  origin
591     TOYOTA    3  3TM  MEXICO
1078    TOYOTA    3  3MY  MEXICO
2143    TOYOTA    3  3MY  MEXICO
3807    TOYOTA    3  3TY  MEXICO
5134    TOYOTA    3  3TM  MEXICO
...        ...  ...  ...     ...
919288  TOYOTA    3  3TM     NaN
920443  TOYOTA    3  3MY     NaN
920696  TOYOTA    3  3TY     NaN
921571  TOYOTA    3  3TM     NaN
921814  TOYOTA    3  3TM     NaN

[313 rows x 4 columns]

In [29]:
print(data_pos0_3['origin'].unique())

['MEXICO' 'AMERICA' 'JAPAN' 'UNITED STATES' 'USA' nan 'UAE'
 'UNITED ARAB EMIRATES']

In [30]:
data_pos0_J = data[data['pos0'] == 'J']
data_pos0_J[['make','pos0', 'WMI','origin']]

          make pos0  WMI origin
1       TOYOTA    J  JTF  JAPAN
2       TOYOTA    J  JTF  JAPAN
3       TOYOTA    J  JTF  JAPAN
5       TOYOTA    J  JTM  JAPAN
6       TOYOTA    J  JTD  JAPAN
...        ...  ...  ...    ...
922345  TOYOTA    J  JTN    NaN
922346  TOYOTA    J  JTM    NaN
922351  TOYOTA    J  JTM    NaN
922352  TOYOTA    J  JTM    NaN
922353  TOYOTA    J  JTE    NaN

[112811 rows x 4 columns]

In [31]:
print(data_pos0_J['origin'].unique())

['JAPAN' 'AMERICA' 'UNITED STATES' 'TAIWAN' 'THAILAND' 'YEMEN' 'USA' 'UAE'
 nan '000' 'IRAN' 'PAPUA NEW GUINEA' 'INDIA' 'SUDAN' 'GREECE' '00'
 'UNITED ARAB EMIRATES' 'AUSTRALIA' '0' 'EMIRATES' 'GCC' 'CANADA' 'INDIAN'
 'تركيا' 'GERMANY' 'CHINA' 'JPAN' 'SOUTH KOREA' 'اليابان' 'G' 'HUNGARY'
 'FRANCE' 'SAUDI ARABIA' 'A' 'آتيانیان' 'SYRIA' 'MEXICO' 'ITALY' '4'
 'ASIAN' 'INDONESIA' 'NEW GUINEA' 'EGYPT' 'KOREA' 'JAMAICA' 'SUD' 'الريان'
 'MYANMAR' 'UNITED KINGDOM' 'HAQUARI' 'TURKEY' 'SPAIN' 'ORIGIN'
 'LIGHT VEHICLE' 'TOYOTA' 'JAPA' '11' 'BELGIUM' 'EUROPEAN UNION'
 'HONDURAS' 'AUSTRIA' 'JORDAN' 'JARAN' 'PARAGUAY' 'NORTH KOREA' 'MOROCCO'
 'S' 'SAPAN' 'SLOVAKIA' 'AFGHANISTAN' 'AMERICAN' 'J. PAN' '1' 'NON GCC'
 'JAPANE' 'PAKISTAN' 'OMAN' '17750' 'KOSOVO' 'QATAR' 'الصين' 'MACAU']

In [32]:
data_pos0_K = data[data['pos0'] == 'K']
data_pos0_K[['make','pos0', 'WMI','origin']]

          make pos0  WMI       origin
2061    TOYOTA    K  KMF  SOUTH KOREA
9355    TOYOTA    K  KN9  SOUTH KOREA
12446   TOYOTA    K  KNC  SOUTH KOREA
25132   TOYOTA    K  KNF  SOUTH KOREA
29667   TOYOTA    K  KNC  SOUTH KOREA
...        ...  ...  ...          ...
205287  TOYOTA    K  KMF  SOUTH KOREA
231432  TOYOTA    K  KMJ  SOUTH KOREA
233212  TOYOTA    K  KMF  SOUTH KOREA
236789  TOYOTA    K  K20          NaN
241401  TOYOTA    K  KMJ  SOUTH KOREA

[86 rows x 4 columns]

In [33]:
print(data_pos0_K['origin'].unique())

['SOUTH KOREA' 'KOREA' 'REPUBLIC OF SOUTH KOREA' nan 'NORTH KOREA' 'JAPAN'
 'INDONESIA']

In [34]:
data_pos0_W = data[data['pos0']== 'W']
data_pos0_W[['make','pos0', 'WMI','origin']]

          make pos0  WMI   origin
196     TOYOTA    W  WZ1  AUSTRIA
284     TOYOTA    W  WDB  GERMANY
2183    TOYOTA    W  WZ1  AUSTRIA
2383    TOYOTA    W  WZ1  AUSTRIA
2923    TOYOTA    W  WWW    JAPAN
...        ...  ...  ...      ...
241240  TOYOTA    W  WDB  GERMANY
920066  TOYOTA    W  WZ1      NaN
920857  TOYOTA    W  WZ1      NaN
921262  TOYOTA    W  WZ1      NaN
921379  TOYOTA    W  WZ1      NaN

[271 rows x 4 columns]

In [35]:
print(data_pos0_W['origin'].unique())

['AUSTRIA' 'GERMANY' 'JAPAN' 'POLAND' 'SPAIN' nan 'AUSTRALIA'
 'UNITED KINGDOM' 'THAILAND' 'HUNGARY' 'PORTUGAL' 'CHINA']

In [36]:
data_pos0_Z = data[data['pos0'] == 'Z']
data_pos0_Z[['make','pos0', 'WMI','origin']]

          make pos0  WMI    origin
1492    TOYOTA    Z  ZE1     JAPAN
2269    TOYOTA    Z  ZSG     JAPAN
10881   TOYOTA    Z  ZGE     JAPAN
11133   TOYOTA    Z  ZE1     JAPAN
14652   TOYOTA    Z  ZE1     JAPAN
...        ...  ...  ...       ...
228289  TOYOTA    Z  ZZE       NaN
232256  TOYOTA    Z  ZZE       NaN
234403  TOYOTA    Z  ZE1       NaN
238233  TOYOTA    Z  ZFC  THAILAND
239884  TOYOTA    Z  ZE1       NaN

[99 rows x 4 columns]

In [37]:
print(data_pos0_Z['origin'].unique())

['JAPAN' 'ITALY' nan 'THE THAILAND' 'TURKEY' 'CHINA' 'CANADA' 'THAILAND']

In [38]:
data_pos0_S = data[data['pos0'] == 'S']
data_pos0_S[['make','pos0', 'WMI','origin']]

          make pos0  WMI          origin
2231    TOYOTA    S  STB         AMERICA
3299    TOYOTA    S  STF           JAPAN
3646    TOYOTA    S  SJK  UNITED KINGDOM
7636    TOYOTA    S  SYF   UNITED STATES
9917    TOYOTA    S  STF           JAPAN
...        ...  ...  ...             ...
236225  TOYOTA    S  STB         AMERICA
237637  TOYOTA    S  SKF  UNITED KINGDOM
238063  TOYOTA    S  STF   UNITED STATES
238671  TOYOTA    S  STF           JAPAN
241456  TOYOTA    S  STF           JAPAN

[123 rows x 4 columns]

In [39]:
print(data_pos0_S['origin'].unique())

['AMERICA' 'JAPAN' 'UNITED KINGDOM' 'UNITED STATES' 'UAE' 'GREAT BRITAIN'
 nan 'MEXICO' 'THAILAND' 'AMERICAN' 'AUSTRALIA']

In [40]:
data_pos0_Y = data[data['pos0'] == 'Y']
data_pos0_Y[['make','pos0', 'WMI','origin']]

          make pos0  WMI   origin
4945    TOYOTA    Y  YV2    JAPAN
11557   TOYOTA    Y  YV2   SWEDEN
11698   TOYOTA    Y  YV2    JAPAN
13534   TOYOTA    Y  YS2    JAPAN
18167   TOYOTA    Y  YV2    JAPAN
18319   TOYOTA    Y  YV2   SWEDEN
18376   TOYOTA    Y  YV2    JAPAN
18389   TOYOTA    Y  YV2    JAPAN
19006   TOYOTA    Y  YV2   SWEDEN
23311   TOYOTA    Y  YV2    JAPAN
27688   TOYOTA    Y  YV2    JAPAN
28833   TOYOTA    Y  YV2    JAPAN
31865   TOYOTA    Y  YV2    JAPAN
37605   TOYOTA    Y  YV2  AMERICA
37758   TOYOTA    Y  YV2    JAPAN
42401   TOYOTA    Y  YV2    JAPAN
50464   TOYOTA    Y  YV2      NaN
63530   TOYOTA    Y  YS2      NaN
79159   TOYOTA    Y  YV1   SWEDEN
111591  TOYOTA    Y  YN8      NaN
124736  TOYOTA    Y  YV2      NaN
124759  TOYOTA    Y  YAR   FRANCE
129628  TOYOTA    Y  YV2      NaN
132195  TOYOTA    Y  YV2   SWEDEN
143175  TOYOTA    Y  YV2      NaN
157480  TOYOTA    Y  YV2   SWEDEN
157788  TOYOTA    Y  YV2      NaN
167337  TOYOTA    Y  YV2      NaN
175270  TOYOTA    Y  YV2   SWEDEN
182035  TOYOTA    Y  YBL      NaN
182047  TOYOTA    Y  YV2   SWEDEN
186983  TOYOTA    Y  YN8    JAPAN
189346  TOYOTA    Y  YV2   SWEDEN
195340  TOYOTA    Y  YV2   SWEDEN
196137  TOYOTA    Y  YSM    CHINA
205707  TOYOTA    Y  YV2   SWEDEN
211362  TOYOTA    Y  YS2      NaN
220476  TOYOTA    Y  YV2      NaN
223178  TOYOTA    Y  YV2      NaN
232119  TOYOTA    Y  YV2      NaN
232964  TOYOTA    Y  YV2   SWEDEN
233035  TOYOTA    Y  YV2   SWEDEN
233511  TOYOTA    Y  YV2   SWEDEN
234943  TOYOTA    Y  YV2      NaN
235710  TOYOTA    Y  YV2      NaN
239332  TOYOTA    Y  YV2      NaN
239461  TOYOTA    Y  YV2      NaN
239603  TOYOTA    Y  YV2      NaN
240643  TOYOTA    Y  YV2   SWEDEN

In [41]:
print(data_pos0_Y['origin'].unique())

['JAPAN' 'SWEDEN' 'AMERICA' nan 'FRANCE' 'CHINA']

In [42]:
data_pos0_L = data[data['pos0'] == 'L']
data_pos0_L[['make','pos0', 'WMI','origin']]

          make pos0  WMI origin
241     TOYOTA    L  LVG  CHINA
573     TOYOTA    L  LVG  CHINA
589     TOYOTA    L  LFM  JAPAN
1034    TOYOTA    L  LFM  CHINA
1277    TOYOTA    L  LFM  CHINA
...        ...  ...  ...    ...
920294  TOYOTA    L  LFM    NaN
920401  TOYOTA    L  LVG    NaN
920948  TOYOTA    L  LVG    NaN
921427  TOYOTA    L  LVG    NaN
922291  TOYOTA    L  LFM    NaN

[744 rows x 4 columns]

In [43]:
data_pos0_L[['make','pos0', 'WMI','origin']]

          make pos0  WMI origin
241     TOYOTA    L  LVG  CHINA
573     TOYOTA    L  LVG  CHINA
589     TOYOTA    L  LFM  JAPAN
1034    TOYOTA    L  LFM  CHINA
1277    TOYOTA    L  LFM  CHINA
...        ...  ...  ...    ...
920294  TOYOTA    L  LFM    NaN
920401  TOYOTA    L  LVG    NaN
920948  TOYOTA    L  LVG    NaN
921427  TOYOTA    L  LVG    NaN
922291  TOYOTA    L  LFM    NaN

[744 rows x 4 columns]

In [44]:
data_pos0_M = data[data['pos0'] == 'M']
data_pos0_M[['make','pos0', 'WMI','origin']]

          make pos0  WMI    origin
7       TOYOTA    M  MR0  THAILAND
11      TOYOTA    M  MR2  THAILAND
15      TOYOTA    M  MR0  THAILAND
18      TOYOTA    M  MR0  THAILAND
28      TOYOTA    M  MHF     JAPAN
...        ...  ...  ...       ...
922307  TOYOTA    M  MR0       NaN
922328  TOYOTA    M  MR2       NaN
922348  TOYOTA    M  MHK       NaN
922350  TOYOTA    M  MR0       NaN
922354  TOYOTA    M  MHF       NaN

[37745 rows x 4 columns]

In [45]:
print(data_pos0_M['origin'].unique())

['THAILAND' 'JAPAN' 'INDONESIA' 'INDIA' 'TAIWAN' 'TAHITIAN' nan 'ANDORRA'
 'تايلاند' 'JINDONESIA' 'EMIRATES' 'UAE' 'تايلند' 'CHINA' 'UNKNOWN'
 'AFGHANISTAN' 'UNITED STATES' 'SOUTH KOREA' 'GCC' 'ANGUILLA' 'AMERICA'
 'PAKISTAN' 'AUSTRALIA' 'LIGHT VEHICLE' 'HAILAND' 'IRAN' 'OTHERS'
 'UNITED ARAB EMIRATES' '1' 'PHILIPPINES' 'GERMANY' 'SAUDI ARABIA'
 'BANGLADESH' '0' 'THALLAND' 'LIBYA' 'ANTIGUA AND BARBUDA'
 'FRANCE (EUROPEAN PROVINCE)' 'CAMBODIA' 'FIJI' 'EGYPT' 'تایلاند' 'ASIAN'
 'TURKEY' 'FINDONESIA' 'TAILAND' 'MALAYSIA']

In [46]:
data_pos0_V = data[data['pos0'] == 'V']
data_pos0_V[['make','pos0', 'WMI','origin']]

          make pos0  WMI   origin
2842    TOYOTA    V  VNK    JAPAN
5204    TOYOTA    V  VNK   FRANCE
5312    TOYOTA    V  VNK  AMERICA
5776    TOYOTA    V  VNK   FRANCE
8315    TOYOTA    V  VNK   FRANCE
...        ...  ...  ...      ...
917346  TOYOTA    V  VNK      NaN
917755  TOYOTA    V  VNK      NaN
920833  TOYOTA    V  VNK      NaN
921310  TOYOTA    V  VNK      NaN
922339  TOYOTA    V  VNK      NaN

[119 rows x 4 columns]

In [47]:
print(data_pos0_V['origin'].unique())

['JAPAN' 'FRANCE' 'AMERICA' 'UNITED STATES' 'SPAIN' nan 'INDIA']

In [48]:
data_pos0_T = data[data['pos0'] == 'T']
data_pos0_T[['make','pos0', 'WMI','origin']]

         make pos0  WMI         origin
23095  TOYOTA    T  TNX  UNITED STATES

In [49]:
print(data_pos0_T['origin'].unique())

['UNITED STATES']

In [50]:
data_pos0_R = data[data['pos0'] == 'R']
data_pos0_R[['make','pos0', 'WMI','origin']]

          make pos0  WMI  origin
0       TOYOTA    R  RKL  TAIWAN
17      TOYOTA    R  RKL  TAIWAN
52      TOYOTA    R  RKL   JAPAN
94      TOYOTA    R  RKL   JAPAN
103     TOYOTA    R  RKL  TAIWAN
...        ...  ...  ...     ...
922275  TOYOTA    R  RKL     NaN
922285  TOYOTA    R  RKL     NaN
922332  TOYOTA    R  RKL     NaN
922333  TOYOTA    R  RKL     NaN
922344  TOYOTA    R  RKL     NaN

[17103 rows x 4 columns]

In [51]:
print(data_pos0_R['origin'].unique())

['TAIWAN' 'JAPAN' 'UAE' 'THAILAND' nan 'UNITED ARAB EMIRATES' 'TALWAN'
 'GCC' 'TAIWAN (CHINESE TAIPEI FOR IOC)' 'JAPAN ' 'PAKISTAN' 'NAYON'
 'TABUN' 'AMERICA' 'LIGHT VEHICLE' 'EGYPT' 'UNKNOWN' 'DUBAI' 'INDIA'
 'BAIWAN' 'TAIWAN (CHINESE TAIPEI)' 'LIWAN' 'TAIWAN (PROVINCE OF CHINA)'
 'HUNGARY' 'TUVALU' 'INDONESIA' 'IRAN' 'TANZANIA' 'ASIAN' 'CHINA' 'MACAU'
 'LEBANON' 'JAPANE' 'RUSSIA' 'EMIRATES' 'SOUTH KOREA' 'SPAIN' 'TAI'
 'TAIMAN' 'AUSTRALIA' 'UNITED STATES' 'ETHIOPIA' 'TAINAN' 'JORDAN'
 'TURKEY' 'HINA' 'تايون' 'TNIYON' 'GERMANY' 'NORWAY']

In [52]:
data_pos0_9 = data[data['pos0'] == '9']
data_pos0_9[['make','pos0', 'WMI','origin']]

         make pos0  WMI     origin
24622  TOYOTA    9  9BS      JAPAN
31894  TOYOTA    9  9BS      JAPAN
92809  TOYOTA    9  9KM  AUSTRALIA

In [53]:
print(data_pos0_9['origin'].unique())

['JAPAN' 'AUSTRALIA']

In [54]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos2,VDS,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,L,BB9HE,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,F,HXDGP,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,1,BG22K,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,0,HU8CD,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,M,ABBBJ,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,M,HX01J,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,E,AACAJ,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,F,B29F3,B,2,9,F,3,M,2,123579

In [55]:
origin_mapping = {
    "1": "USA",
    "4": "USA",
    "5": "USA",
    "2": "CANADA",
    "3": "MEXICO",
    "J": "JAPAN",
    "K": "SOUTH KOREA",
    "W": "GERMANY",
    "Z": "ITALY",
    "S": "UNITED KINGDOM",
    "Y": "SWEDEN / FINLAND",
    "L": "CHINA",
    "M": "INDIA",
    "V": "FRANCE / SPAIN",
    "T": "SWITZERLAND",
    "R": "TAIWAN",
    "9": "BRAZIL"
}

In [56]:
data["origin"] = data["pos0"].map(origin_mapping).fillna(data["origin"])

C:\Users\Admin\AppData\Local\Temp\ipykernel_18148\1604850742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["origin"] = data["pos0"].map(origin_mapping).fillna(data["origin"])

In [57]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos2,VDS,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,L,BB9HE,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,F,HXDGP,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,USA,...,1,BG22K,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,INDIA,...,0,HU8CD,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,JAPAN,...,M,ABBBJ,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,JAPAN,...,M,HX01J,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,JAPAN,...,E,AACAJ,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,INDIA,...,F,B29F3,B,2,9,F,3,M,2,123579

In [58]:
data_pos0_V_updated = data[data['pos0'] == 'V']
data_pos0_V_updated[['make','pos0', 'WMI','origin']]

          make pos0  WMI          origin
2842    TOYOTA    V  VNK  FRANCE / SPAIN
5204    TOYOTA    V  VNK  FRANCE / SPAIN
5312    TOYOTA    V  VNK  FRANCE / SPAIN
5776    TOYOTA    V  VNK  FRANCE / SPAIN
8315    TOYOTA    V  VNK  FRANCE / SPAIN
...        ...  ...  ...             ...
917346  TOYOTA    V  VNK  FRANCE / SPAIN
917755  TOYOTA    V  VNK  FRANCE / SPAIN
920833  TOYOTA    V  VNK  FRANCE / SPAIN
921310  TOYOTA    V  VNK  FRANCE / SPAIN
922339  TOYOTA    V  VNK  FRANCE / SPAIN

[119 rows x 4 columns]

In [59]:
data[['make','pos1', 'WMI','origin']]

          make pos1  WMI  origin
0       TOYOTA    K  RKL  TAIWAN
1       TOYOTA    T  JTF   JAPAN
2       TOYOTA    T  JTF   JAPAN
3       TOYOTA    T  JTF   JAPAN
4       TOYOTA    T  4T1     USA
...        ...  ...  ...     ...
922350  TOYOTA    R  MR0   INDIA
922351  TOYOTA    T  JTM   JAPAN
922352  TOYOTA    T  JTM   JAPAN
922353  TOYOTA    T  JTE   JAPAN
922354  TOYOTA    H  MHF   INDIA

[239214 rows x 4 columns]

In [60]:
print(data['pos2'].unique())

['L' 'F' '1' 'M' 'D' '0' 'E' '2' 'N' 'C' 'G' 'A' 'K' 'O' 'X' '3' 'T' 'B'
 '4' 'U' 'J' 'Y' 'W' '6' 'P' '5' '7' '8' 'V' '9' 'I' 'Q' 'H' 'S' 'R' 'Z']

In [61]:
data[['make','pos2', 'WMI','bodyType']]

          make pos2  WMI            bodyType
0       TOYOTA    L  RKL               SEDAN
1       TOYOTA    F  JTF  MINI BUS HIGH ROOF
2       TOYOTA    F  JTF  MINI BUS HIGH ROOF
3       TOYOTA    F  JTF  PICK UP DOUBLE CAB
4       TOYOTA    1  4T1               SEDAN
...        ...  ...  ...                 ...
922350  TOYOTA    0  MR0              PICKUP
922351  TOYOTA    M  JTM                 SUV
922352  TOYOTA    M  JTM                 SUV
922353  TOYOTA    E  JTE                 SUV
922354  TOYOTA    F  MHF               SEDAN

[239214 rows x 4 columns]

In [62]:
print(data['bodyType'].unique())

['SEDAN' 'MINI BUS HIGH ROOF' 'PICK UP DOUBLE CAB' 'SUV' 'HATCHBACK'
 'PICK UP SINGLE CAB' 'PANEL VAN' 'BUS' 'MPV' 'ESTATE' 'PICK UP' 'VAN'
 'MINI BUS' 'COUPE' 'SUV- CROSSOVER' 'PICKUP' 'SALOON'
 'PANEL VAN HIGH ROOF' 'STATION' 'HALF PANEL VAN' 'CONVERTIBLE'
 'CARGO VAN' 'MINIVAN' 'MINI BUS SEMI HIGH ROOF' 'CARAVAN' 'PICKUP TRUCK'
 'LIGHT VEHICLE' 'MOTORCYCLE' 'PICKUP SINGLE CABIN' 'TRUCK'
 'PICK UP DOUBLE CABIN' 'PICKUP DOUBLE CABIN' 'COUPE/CABRIOLET'
 'AMBULANCE' 'REGULAR CAB' 'PICKUP DOUBLE CAB' 'WINDOW VAN' 'WAGON'
 'PICK-UP']

In [ ]:
from IPython.display import display

for pos_4 in data['pos4'].dropna().unique():

    # 1. Filter the DataFrame for the current pos4 value
    filtered_df = data.loc[
        data['pos4'] == pos_4,
        ['make', 'model', 'cylinders', 'bodyType', 'pos4', 'trim', 'WMI', 'regionalSpec', 'noOfDoors', 'VDS']
    ].reset_index(drop=True)

    # 2. Header for the current pos4 group
    print("\n" + "=" * 100)
    print(f"POS4: {pos_4}")
    print("=" * 100)

    # 3. Print unique values for all object columns (except pos4)
    print("--- Unique Values for Object Columns ---")
    object_cols = filtered_df.select_dtypes(include=['object']).columns
    
    for col in object_cols:
        if col != ['pos4', 'VDS']:
            unique_vals = filtered_df[col].dropna().unique()
            print(f"  {col}: {list(unique_vals)}")
            
    print("-" * 100)

    # 4. Display the filtered DataFrame
    display(filtered_df)

====================================================================================================
POS4: B
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'CAMRY', 'YARIS', 'FJ CRUISER', 'HILUX', 'AVALON', 'RAV4', 'PRADO', 'AURION', 'ECHO', 'FORTUNER', 'SEQUOIA', 'TOYOTA CAMRY', 'FJ', 'LAND CRUISER', '4RUNNER', 'COROLLA 1.6', 'TUNDRA', 'SIENNA', 'LITEACE', 'PRIUS', 'HIACE', 'LEVIN', 'TERCEL', 'LAND CRUISER PRADO', 'LAND CRUISER PICK UP', 'TOYOTA ALTIS', 'COROLLA 1.3', 'HIGHLANDER', 'TOYOTA COROLLA', 'LAND CRUISER PICKUP 70', 'COASTER', 'COROLLA 1.8', '26HX DC 4X4P2.7LAT', 'HD 4X4', 'COROLLA SEDAN', 'CROWN', 'COROLLA CROSS', '4 RUNNER', 'TOYOTA TUNDRA', 'RAV 4', 'VENZA', 'كورولا 1.8', 'TOYOTA COROLLA 1.6', 'PRADO GX', 'RUSH', 'TOYOTA PRADO', '25 HX DC 4X4 2.7LAT', 'GLX DA (PICK UP)', 'TANDRA', 'RUNNER', 'VIOS', 'TOYOTA', 'TOYOTA HILUX', 'SALOON', '25 HX DC 4X4P 2.7LAT', 'COROLLA LI', 'GLX RA (PICK UP)', 'TOYOTA 4RUNNER', 'CORONA', 'COROLLA 1.6/SEDAN', 'TOYOTA COROLLA 2.0', 'هايلوكس', 'كامرى', '25 HX DC 4X4 P .LAT', '26 HX DC 4X4 P 2.7LAT', 'LITE ACE', 'كورولا', '2023', 'برادو', '25 HX DC 4X4 PLAT GLX RA(PICK UP)', 'PARISIENNE BROUGHAM', 'TANDRA PICK UP DOUBLE CABIN', 'HILUX ADVENTURE', 'RAIZE', 'AVANZA', 'كامري', 'COROLLA ', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'HATCHBACK', 'SUV', 'PICK UP DOUBLE CAB', 'ESTATE', 'PICK UP SINGLE CAB', 'SALOON', 'STATION', 'PICKUP', 'MPV', 'PANEL VAN', 'VAN', 'MINI BUS', 'MINI BUS HIGH ROOF', 'PICK UP', 'CARGO VAN', 'BUS', 'LIGHT VEHICLE', 'SUV- CROSSOVER', 'PICK UP DOUBLE CABIN', 'PICKUP DOUBLE CABIN', 'COUPE', 'TRUCK', 'PICKUP DOUBLE CAB']
  trim: ['SE', 'XLI', 'MID', 'VXR', 'E', 'TOP', 'EXTREME', 'GL', 'BASE', 'S', 'SE+ ANNIVERSARY EDITION', 'STD (NON GCC)', 'LE', 'XLI MID', 'GLX', 'SE+', 'GLI', 'LIMITED', 'VX', 'VX MID', 'GXR', 'GX', 'XLE', 'SPORT', 'GRANDE', 'XLI TOP', 'S TRD SPORT PK', 'S+', 'XLI RB', 'LIMITED PREMIUM', 'GLE', 'XLI EXECUTIVE', 'DLX', 'FLEET', 'EXR', 'SR5 4X4', 'GLE HEV', 'STD', 'CE (NON GCC)', 'GLI HEV', 'TX-L', 'XLE TOURING', 'DLS', 'SALOON', 'LE STD', 'LIMITED MID', 'GX TOP', 'GLI TOP', 'XLE (NON GCC)', 'G', 'EXCLUSIVE', 'XSE (NON GCC)', 'TX', 'XLI POWER OPT', 'ADVENTURE', 'GLX SPORT Z', 'S PLUS', 'LE (NON GCC)', 'SR5 (NON GCC)', '40TH ANNIVERSARY EDITION', 'TOURING', 'GX MID', 'PS PW CL', 'PLATINUM', 'LIMITED 4X4', 'GLE-X HEV 40TH ANNIV', 'EXR HEV', 'TX-L TOP', 'LE HEV', '1.8', 'SR5 4X2', 'FJ STD', '1', 'YX', 'DX', 'GXR TOP', 'EX', 'LIMITED TRD SPORT PK', 'DL', 'XLE HEV', 'BE', 'X', 'STD AC', 'LX AC PWR OPT', 'Y PLUS', 'VX2', 'XTREME', 'T', 'TXL2', 'DLS - STD ROOF', 'L', 'SED', 'LWB', 'SEDAN', 'GXR SOD D/AC AW', 'SL', 'STANDARD', '2.0L', 'SE TRD AERO PK', 'XLI EXECUTIVE MR', 'LUMIERE HEV', 'STANDER', 'TRIM', 'LEVIN', 'GL2', '4X4', 'SR5', 'LS', 'HYBRID', 'TXL1', 'GLS', 'Y', 'LUMIERE 40TH ANNIV', 'GRANDE HEV', 'HYBRID (NON GCC)', 'LTD HEV', 'ROYAL', 'LIMITED TRD AERO PK', 'C', 'GLI TOP LTH', '60TH', 'ORION', 'TXL3', 'VX-L MID', 'A', 'GGG', 'COMFORT', 'VX1', 'STD  (NON GCC)', '4', 'XLI EXECUTIVE HEV', 'PW CL', 'SPORTS', 'GLE HEV BLACK EDITION', 'VX TOP LTH', 'PICKUP', 'GXR TOP 60TH ANNIV. XTREME', 'CAR TRIM', 'GL DECKLESS', 'TR', 'GLX PREMIUM', 'TUNDRA', 'XL', 'DOUBLE CABIN ', 'PICK UP', 'ROYAL EDITION', 'SGLX', '1.5', '2', '90', 'TOP LTH', 'ST', 'ALTIS (NON GCC)', '40 TFSI S-LINE', 'SUV', 'VTI', 'CARRERA GTS', 'GRANDE HEV 40TH ANNIV', 'TRTIM', 'LX', '0', 'SPORTS BASIC', '40TH ANNIVERSARY EDI', 'GR SPORT', 'SE+ ANNIVERSARY EDIT']
  WMI: ['RKL', '4T1', 'JTD', 'JTE', 'MR2', '6T1', 'MR0', 'JTN', 'JTM', 'MHF', '1NX', 'JT2', '2T1', '5YF', '5TD', '2T3', '4T4', '5TB', '1N4', '8T1', '5TF', 'JTK', 'MHK', 'LVG', 'JJ5', 'INX', 'JNB', 'SYF', 'MRO', '4TI', 'JT3', 'LVC', 'JN6', '6TI', '2CN', 'STD', 'MR1', '4T3', '4TT', '411', 'JTF', '5T1', 'TNX', 'WBW', 'JL6', '213', 'MRD', 'LTV', '611', 'NMT', 'GT1', 'LFM', 'JTH', '7MU', 'MNT', 'MHE', 'JRN', 'KPB', '3N1', 'JL5', 'JL7', 'LSC', 'STF', '6TT', 'MFH', 'JN2', 'JJ7', 'JTL', '6TD', '2TI', '211', '9KM', 'JIN', 'JTG', 'MBJ', 'STB', 'LGF', '5NF', 'MDH', 'STO', '471', 'JNK', '6T0', 'RKE', 'JTR', 'BT1', '671', '1N6', 'JM7', 'KNA', 'MRI', 'JN1', 'ST1', '5T0', '5N1', 'JN8', '3TD', '000', 'MRU', '61L', 'JDT', 'M0F', 'AUS', 'LVM', '4T0', 'MHM', '1G2', '474', 'JTJ', 'JED', '1LN', 'JTU', 'JTV', 'UTD', 'WP0', 'ET1', '3T1', 'BKL', 'JT0', 'UTM', 'JNE']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BB9HE', 'BG22K', 'BW923', 'BR23E', 'BU11F', 'BF9C3', 'BF9FK', 'BX8CD', 'BE32K', 'BZ42E', 'BK36B', 'BZ4HK', 'BK31V', 'BF3EK', 'BF9HK', 'B29F3', 'BT9F3', 'BE42K', 'BR42E', 'BL9HE', 'BF4FK', 'BR22E', 'B24HK', 'BF1FK', 'BU25J', 'BC42E', 'BW23E', 'BU4EE', 'BE33K', 'BL29J', 'BK1EB', 'BU3FJ', 'BF32K', 'BK3DB', 'BK42K', 'BW123', 'BT923', 'BU9FJ', 'BE30K', 'BURHE', 'BV42E', 'BA32K', 'BD31V', 'B29HK', 'BB0BE', 'BG12K', 'BK40K', 'BK33V', 'BE46K', 'BK4FK', 'BUSFS', 'B14HK', 'B13FV', 'BY64A', 'B30BE', 'BU40E', 'BF4HK', 'BU8FS', 'BB42E', 'BF4DV', 'BW133', 'B1RFV', 'BG28K', 'BX9FJ', 'BU&CD', 'BF28B', 'BR32E', 'BF38K', 'BW933', 'BB71J', 'BU5JR', 'BT441', 'BBOBE', 'BD1FK', 'BW22E', 'BY68A', 'BL40E', 'BKIEB', 'BU8CD', 'BV541', 'BK32V', 'B242E', 'BF9EV', 'B11HK', 'BL4A9', 'BF8C3', 'BR40E', 'BD33V', 'BA02E', 'BK46K', 'BK3EK', 'BR38E', 'BN95J', 'BDMHE', 'BA0BE', 'BA22C', 'BB0CE', 'BK22C', 'BT14R', 'BK1FK', 'BFREV', 'BZ1FB', 'BB13E', 'BB46K', 'BT123', 'BA13E', 'BM29J', 'BA23C', 'BPRBE', 'BD32V', 'BF31F', 'BF30K', 'BY80E', 'BF31V', 'B674K', 'B4MDE', 'BW3FV', 'B31HK', 'BF22K', 'BH9FJ', 'BUT1F', 'BV581', 'B2E6K', 'BPB9E', 'B19HK', 'BF28K', 'BU4BF', 'B30EE', 'BW9F3', 'BG23K', 'B21HK', 'BD35V', 'B519E', 'BR30E', 'BE36K', 'BU14R', 'BK4DV', 'BK23C', 'BJ53L', 'BY67A', 'BF33V', 'BRKEC', 'BPRHE', 'BJ13E', 'BW6F3', 'BZAHK', 'BX3FJ', 'BU253', 'BU11J', 'BACEK', 'BD1EB', 'B61HK', 'BA30K', 'BB02E', 'BA05E', 'BE4EE', 'BB3EK', 'B1DWA', 'BW5F1', 'BE6DS', 'BJ18U', 'BF46K', 'BE40K', 'BY5F1', 'BUIIF', 'B4B9E', 'BT4K3', 'BE6BS', 'BF12K', 'BR12E', 'BM99J', 'B1B0E', 'B6RFV', 'B21FB', 'BA01E', 'BT481', 'BV71J', 'BU71J', 'BT17R', 'BT903', 'BB12E', 'BR28E', 'BK34V', 'BF32V', 'BJE23', 'B19F3', 'BE3EK', 'BA03E', 'BBOCE', 'BK1E8', 'BK4SK', 'BU3AE', 'BR18E', 'BW5G1', 'BZ1HK', 'B0111', 'BE6AS', 'BW541', 'BT541', 'BCE6J', 'BK3EH', 'BE9B3', 'BT581', 'BU17R', 'BAOBE', 'BA8CD', 'BW023', 'BUTTF', 'BK368', 'BFIFK', 'BRZ3E', 'BL293', 'BY5G1', 'BC74K', 'BK35V', 'BR22F', 'BE42J', 'BY879', 'BZRFH', 'BT48A', 'BB9JE', 'BE85B', 'B4MBE', 'BK262', 'BAABG', 'BBRCH', 'BDOES', 'BZ4ZE', 'BE24K', 'BECEK', 'BU29J', 'BX8C0', 'BF5C2', 'BUBFS', 'BL42E', 'BF6C3', 'BH2AW', 'BLIHK', 'BK3BB', 'BE6CS', 'BA1HK', 'B2NWA', 'BUL1F', 'BE38K', 'BG21K', 'BC11E', 'B3J6P', 'BCE1J', 'BBN2A', 'B622K', 'BT44A', 'BT64A', 'BW9F4', 'BB03E', 'BF18B', 'BN30F', 'B89HE', 'BCELK', 'BK29J', 'BR43E', 'BE4GK', 'BPWDG', 'BG17K', 'BAMDE', 'BW12S', 'BXBCD', 'BC81S', 'BPMBE', 'BD317', 'BF9FR', 'B7A2J', 'BN441', 'BADBA', 'BU26J', 'BU01F', 'BLSHE', 'BD0FA', 'BW581', 'BUSFJ', 'BY11F', 'BF12B', 'B3E6P', 'B025J', 'BE9FK', 'BE23K', 'BF35V', 'BF31E', 'BB0BB', 'BV61E', 'BV426', 'BY809', 'BCE1K', 'BD0CT', 'B03FV', 'BT9K3', 'BZ9F3', 'BK326', 'BZ42F', 'BDF1J', 'BD23S', 'BE40E', 'BA244', 'BL0HE', 'BR406', 'BUJFJ', 'BF9JE', 'BF3FK', 'BVV13', 'BJI3E', 'B308E', 'BX9F1', 'BT2MW', 'BDIEB', 'BY30E', 'BY84A', 'BT3AB', 'BVV92', 'BD74K', 'BT05Y', 'BBSHE', 'B2NBA', 'B4RBE', 'BE44K', 'BL00E', 'BKRFH', 'BU3EJ', 'BUSCD', 'BC53L', 'BL9HF', 'BHJ6S', 'B031V', 'BJ335', 'BF23K', 'BBDEE', 'B910L', 'BYBDE', 'BURNE', 'BFTFK', 'B29M3', 'BC42R', 'BU8F5', 'BY32E', 'BT69Y', 'BA3BE', 'BT3AA', 'BJRBZ', 'B4MEE', 'B28F3', 'BA3BB', 'BD337', 'BM82F', 'BB08E', 'BAAAG', 'BU5IF', 'BF32X', 'BE9HE', 'B011F', 'BU258', 'BU250', 'BA2A9', 'BL8HE', 'BLGHE', 'BU11E', 'BH42K', 'BT223', 'BK35B', 'BB8CD', 'B3G6P', 'B046K', 'BBE32', 'BUTIF', 'BJ22K']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,B,SE,RKL,GCC,4.0,BB9HE
1,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,4T1,NON-GCC,4.0,BG22K
2,TOYOTA,YARIS,4.0,HATCHBACK,B,MID,JTD,GCC,5.0,BW923
3,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,JTD,GCC,4.0,BR23E
4,TOYOTA,FJ CRUISER,6.0,SUV,B,VXR,JTE,GCC,5.0,BU11F
...,...,...,...,...,...,...,...,...,...,...
118079,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,JTN,GCC,NaN,BZ4HK
118080,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,JTN,GCC,NaN,BZ4HK
118081,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,S,6T1,GCC,NaN,BF9FK
118082,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,GLI,6T1,GCC,NaN,BE32K
118083,TOYOTA,YARIS,4.0,SEDAN,B,E,MHF,GCC,NaN,B29F3

====================================================================================================
POS4: H
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'HILUX', 'LAND CRUISER', 'RAV4', 'TUNDRA', 'LAND CRUISE', 'PRADO', 'CAMRY', 'INNOVA', 'HIGHLANDER', 'RAV 4', 'COROLLA', 'LAND CRUISER VXR', '4RUNNER', 'استیشن', 'بيك اب كابينه مزدوجه', 'COASTER', 'FJ CRUISER', '2016', 'HIACE ', 'LAND CRUISER GXR', 'TOYOTA LAND CRUISER', 'LAND CRUISER 70', 'AVANZA']
  bodyType: ['MINI BUS HIGH ROOF', 'PICK UP DOUBLE CAB', 'SUV', 'PANEL VAN', 'VAN', 'MINI BUS', 'PICK UP SINGLE CAB', 'PANEL VAN HIGH ROOF', 'MPV', 'STATION', 'HALF PANEL VAN', 'SEDAN', 'BUS', 'MINIVAN', 'MINI BUS SEMI HIGH ROOF', 'PICKUP TRUCK', 'PICK UP', 'CARGO VAN', 'PICKUP', 'SALOON', 'LIGHT VEHICLE']
  trim: ['GLX', 'DX', 'DL', 'VX', 'FABRIC', 'GXR', 'GL', 'PW CL', 'DLX', 'GX', 'VXR', 'G', 'STD', 'GLS', 'SAFARI', 'GXR TOP 60TH ANNIV. XTREME', 'GXR TOP', 'VXR BASE', 'GXR GT', 'VXR TOP', 'STD (NON GCC)', 'EXR', 'LE', 'ADVENTURE', 'GLE-X', 'PREMIUM', 'DX H/R W/B', 'HEV', 'GXR FMST', 'GLE HEV', 'VXR TOP LTH', 'LIMITED', 'MID', 'SR5 (NON GCC)', 'DLS', 'SE+', '0', 'SE', 'GXR+', 'LWB', 'XTREME', 'XLI', 'DLS - STD ROOF', 'GXR MID 60TH ANNIV. XTREME', 'GXR TOP DMST', 'GXR TOP FMST', 'BASE', 'STANDER', 'LE HEV', 'GXR SOD D/AC AW', 'XLE', 'VXR TOP XTREME', 'HYBRID (NON GCC)', 'GXR MID', 'STANDARD', 'SR', 'VXR MID', 'GLS TOP', 'LS', '60TH', 'GRD', 'SS', 'DLS HIGH ROOF', 'XLI EXECUTIVE HEV', 'AA', 'ZX', 'S', 'ST', 'HT SWB', 'TRD', 'COM', 'XLI EXECUTIVE', '1000', 'SWB', '1']
  WMI: ['JTF', 'JTM', 'JTE', 'JT3', 'MR0', 'JTG', '5TF', '2T3', 'LFP', 'MRO', '5TD', 'JHE', '1GC', '5YF', 'KN3', 'JTN', 'JN1', 'JTS', 'KMJ', 'JN6', 'JTD', 'JTC', 'MMC', 'STF', 'WMA', 'KN4', 'JIF', 'JIM', 'LGD', '1C4', 'JT6', 'JTJ', '1TF', 'CTF', 'LSY', '1GJ', 'JMY', 'JTR', 'ITE', 'WVG', '1TM']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['HX02P', 'HXDGP', 'HT09J', 'HD20V', 'HU09J', 'HX09J', 'HT05J', 'HX01J', 'HH20V', 'HY05J', 'HJ09J', 'HX05J', 'HX8CD', 'HJ093', 'HJ01J', 'HU01J', 'HTO5J', 'HY02J', 'HY0SJ', 'HW5F1', 'HN9CP', 'HY5F1', 'HU8CD', 'H1RFV', 'HP10V', 'H4ACP', 'HU093', 'HV01J', 'H009J', 'HY03J', 'HXHX0', 'HT093', 'HY051', 'HZRBH', 'HTOSJ', 'H4BCP', 'HT053', 'HB8CD', 'HN86R', 'HB9CP', 'HXO2P', 'HJ59J', 'HY7AJ', 'HR33N', 'HV09J', 'HPRAE', 'HNP6N', 'HN87R', 'HJ85J', 'HX093', 'HJO9J', 'HZ14S', 'HAP53', 'HS02P', 'HD17F', 'HJ091', 'H109J', 'HD23S', 'HAP5J', 'HX0SJ', 'HT0SJ', 'HT523', 'HU5JR', 'HW2ZZ', 'HNW6N', 'HXO1J', 'HXO9J', 'HX0IJ', 'HT06J', 'HXD2P', 'HG17C', 'H0093', 'HNICP', 'HW21A', 'HB10V', 'H25ZZ', 'HX013', 'HEJ1F', 'HT051', 'HJXEN', 'HZ04S', 'HX02J', 'HUD9J', 'HF10U', 'HXBCD', 'HY053', 'HU08J', 'HDAAA', 'HG39K', 'HNP13', 'HX091', 'HYOSJ', 'HYO5J', 'HD21A', 'HJ05J', 'HJ0SJ', 'H3093', 'HU091', 'HJQ8J', 'HJ08J', 'HAP73', 'H545G', 'HUD3J', 'HXQ2P', 'H309J', 'HX07P', 'HG09G', 'HUOTJ', 'HY05I', 'HY0S0']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,H,GLX,JTF,GCC,4.0,HX02P
1,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,H,DX,JTF,GCC,4.0,HX02P
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DL,JTF,GCC,4.0,HXDGP
3,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,JTM,GCC,5.0,HT09J
4,TOYOTA,RAV4,4.0,SUV,H,FABRIC,JTE,GCC,5.0,HD20V
...,...,...,...,...,...,...,...,...,...,...
31711,TOYOTA,LAND CRUISER,8.0,SUV,H,VXR,JTM,GCC,NaN,HY05J
31712,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,JTM,GCC,NaN,HT09J
31713,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,JTM,GCC,NaN,HT09J
31714,TOYOTA,HILUX,6.0,PICKUP,H,GLX,MR0,GCC,NaN,HU8CD
31715,TOYOTA,LAND CRUISER,8.0,SUV,H,GXR,JTM,GCC,NaN,HX01J

====================================================================================================
POS4: E
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'COROLLA', 'RUSH', 'TUNDRA', 'FJ CRUISER', 'CAMRY', 'RAV4', 'LAND CRUISER 70', 'LAND CRUISER', 'كامري', 'YARIS', 'HIGHLANDER', 'COROLLA CROSS', 'URBAN CRUISER', 'PRADO', 'SCION', 'HIACE', 'SUPRA', 'FORTUNER', 'ECHO', 'SEQUOIA', 'COROLLA 1.8', '4RUNNER', 'NIO ES8', 'TOYOTA RUSH', 'SIENNA', 'LAND CRUISER PICK UP', 'CAMRY HYBRID']
  bodyType: ['PICK UP SINGLE CAB', 'SEDAN', 'SUV', 'PICK UP DOUBLE CAB', 'SALOON', 'PICK UP', 'ESTATE', 'PICKUP', 'HATCHBACK', 'SUV- CROSSOVER', 'VAN', 'STATION', 'PANEL VAN', 'MINI BUS HIGH ROOF', 'COUPE', 'PICKUP DOUBLE CABIN', 'MPV']
  trim: ['DLX', 'XLI MID', 'EX', 'XLI', 'STD (NON GCC)', 'EXTREME', 'GX', 'GLI', 'LE HEV', 'BASE', 'LE', 'STD', 'DLX TOP', 'HT SWB', 'GLS', 'GL', 'GLI TOP LTH', 'XLI TOP', 'GLI TOP', 'XLE (NON GCC)', 'XLI EXECUTIVE', 'SE+', 'HT VXR', 'GLI HEV', 'S', 'SR', 'VX', 'GXR TOP 60TH ANNIV. XTREME', 'SL', 'HYBRID (NON GCC)', 'GLX', 'PLATINUM', 'GXR', 'GLE', 'VXR', 'GLE HEV', 'MID', 'E', 'EXR', 'SE', 'GL2', 'GR BLUE EDITION', 'XLE', 'SPORT', 'DLS', '1', 'XLE HEV', 'ADVENTURE', 'LIMITED', 'LE (NON GCC)', 'LX AC PWR OPT', 'YA', 'TOP']
  WMI: ['MR0', 'JTD', 'MHK', 'MRO', 'JTF', '5TF', '6T1', '5YF', '4T3', 'JT4', 'JTE', 'JT2', '2T3', '5TB', 'JTG', 'LVG', 'RKL', '7MU', 'JTM', 'MZB', '5TD', 'MMM', '2GC', '4T1', '1FT', 'JTB', 'MHF', 'WME', 'LCO', 'JTZ', 'LPS', 'VR3', 'L3H', 'MC1', 'JN1', 'MPA', 'STF', '1N6', 'JTN', 'J1D', 'MRD', 'LS6', 'LGJ', 'SAL', 'LJ1', 'MMB', 'YSM', 'JT0', '3GN', 'MR2']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['EW12G', 'ER23E', 'EF8BF', 'EX12G', 'EX19G', 'EW23E', 'EG426', 'EW5F1', 'EG22K', 'EF8CF', 'EPMAE', 'E6RFV', 'EPRAE', 'EU73J', 'EM496', 'EZ426', 'EG23K', 'EM426', 'EAMDE', 'EZ496', 'EX126', 'EB13E', 'EBRBE', 'EFHCF', 'ET341', 'ES12G', 'EJ13E', 'EF9FK', 'EWRFV', 'EB73J', 'EV541', 'EW923', 'EY5F1', 'ES46A', 'EBOBE', 'EB0BE', 'EAAAG', 'EW21A', 'EB02E', 'EW41A', 'E2815', 'EB71J', 'EBRCH', 'EG425', 'EX120', 'EL33P', 'EF88F', 'EK19T', 'EF12K', 'EWIE5', 'EW44A', 'EC42E', 'EU11F', 'EF76A', 'EE426', 'EFBBF', 'EZ42E', 'ES41A', 'EX196', 'EW126', 'E29F3', 'EK31X', 'EJ5CD', 'EV73J', 'ED3KA', 'EX1E6', 'E1NFJ', 'ET9F3', 'ET923', 'EX22G', 'ECABA', 'ER22E', 'ER42E', 'EG21K', 'EM5F1', 'ED9HP', 'E4FDB', 'ES43A', 'EW1EP', 'EN61S', 'ER33P', 'EFBCF', 'EM42G', 'EY64A', 'ED1EK', 'EW22E', 'EF4HK', 'EDABB', 'EFSBF', 'EE9HE', 'EG12K', 'EV581', 'EFABF', 'ENE0R', 'ET381', 'EGCBB', 'EK12G', 'EU3FJ', 'E1EE0', 'EA6BX', 'EU5JR', 'E6A3U', 'ENKA5', 'EFAVS', 'EE32K', 'EX91G', 'EK12T', 'EZ3DC', 'EFBC3', 'EF8C3', 'ED31V']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,E,DLX,MR0,GCC,2.0,EW12G
1,TOYOTA,COROLLA,4.0,SEDAN,E,XLI MID,JTD,GCC,4.0,ER23E
2,TOYOTA,RUSH,4.0,SUV,E,EX,MHK,GCC,5.0,EF8BF
3,TOYOTA,RUSH,4.0,SUV,E,EX,MHK,GCC,5.0,EF8BF
4,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,E,DLX,MR0,GCC,4.0,EX12G
...,...,...,...,...,...,...,...,...,...,...
8310,TOYOTA,HILUX,4.0,PICKUP,E,DLX,MR0,GCC,NaN,EX19G
8311,TOYOTA,RUSH,4.0,SUV,E,EX,MHK,GCC,NaN,EF8BF
8312,TOYOTA,COROLLA,4.0,SEDAN,E,XLI,JTD,GCC,NaN,ER23E
8313,TOYOTA,HILUX,4.0,PICKUP,E,1,JTF,GCC,NaN,EM426
8314,TOYOTA,HILUX,4.0,PICKUP,E,1,MR0,GCC,NaN,EX12G

====================================================================================================
POS4: C
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'TACOMA', 'PRADO', 'COROLLA CROSS', 'CAMRY', 'SOLARA', 'INNOVA', 'RAV4', 'HIGHLANDER', 'TUNDRA', 'LAND CRUISER', 'FORTUNER', 'COROLLA', 'HIACE', 'COASTER', 'YARIS', 'TAKOMA', 'HILUX RE', 'TOYOTA', 'FRONTLANDER', 'YARIS HATCHBACK', '2024', 'SIENNA', 'CAMRY HYBRID', 'LAND CRUISER PRADO', 'AVALON']
  bodyType: ['PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'SUV', 'SUV- CROSSOVER', 'SEDAN', 'CONVERTIBLE', 'MPV', 'PICK UP', 'PANEL VAN', 'BUS', 'PICKUP', 'COUPE', 'PICKUP SINGLE CABIN', 'MINI BUS HIGH ROOF', 'HATCHBACK', 'SALOON', 'PICKUP DOUBLE CAB', 'PICKUP DOUBLE CABIN', 'STATION', 'PICK-UP']
  trim: ['GL', 'GL2', 'DLX', 'DLX TOP', 'GLX', 'SR5 (NON GCC)', 'GXR', 'GLS', 'LE', 'STD (NON GCC)', 'STD', 'LE HEV', 'SE', 'SGLX', 'EX', 'TX-L', 'DL', 'VXR', 'TRD', 'VX2', 'XLI', 'SE+', 'DX', 'TX-L TOP', 'SR', 'BUS', 'TX', 'XL', 'E', 'DLS', 'GLE-X HEV 40TH ANNIV', 'GRANDE HEV 40TH ANNIV', 'ADVENTURE', 'LIMITED', 'GRANDE', 'HEV', 'GLI', 'XLI TOP', 'VX', 'GF', 'XLE', 'XLE (NON GCC)', 'EXR', 'GX', 'S', 'GLE HEV', 'GXR TOP', 'GLI HEV', 'PICK UP', 'GLE', 'A', 'BASE', 'XLE HEV', 'LXI', 'CAR TRIM', 'GL TOP', '1500', 'EX MID', '60TH', 'XSE', '1']
  WMI: ['MR0', 'MRO', '3TM', 'JTE', '7MU', '4T1', 'LFM', '5TF', 'MHF', '2T3', 'LVG', 'SJK', 'JTM', '4TI', '3TY', 'LXG', 'JTG', 'LGW', 'LVA', 'LZW', '2GN', 'JTN', '2T1', 'LC0', 'JH4', 'RKM', 'KL1', 'LA9', 'JN1', '5TD', 'LHG', 'JHM', 'ZCF', 'JNK', '1HG', 'KNM', 'MRC']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['CW6CB', 'CX9CB', 'CW12G', 'CX19G', 'CX9CD', 'CZ5AN', 'CX8CD', 'CX12G', 'CW6CD', 'CX3FJ', 'CAAAG', 'CW9CD', 'C11AK', 'CU1BR', 'CX6CB', 'CA30P', 'CX8CB', 'CX8EM', 'C1RFV', 'C916Z', 'CAABG', 'CH5CP', 'CX9FJ', 'CY5F1', 'CY7AJ', 'CW8CD', 'CW126', 'CX6CD', 'CX8GS', 'CE38P', 'C618X', 'CPA50', 'CECB8', 'CW8CB', 'CA217', 'CK12G', 'CJE23', 'CGE23', 'CX126', 'C11BK', 'C2ZWB', 'C31AK', 'CBAGA', 'CAAGA', 'CS12G', 'CC1BR', 'C8E2H', 'CS18Z', 'C4RBE', 'CU09J', 'CF28P', 'CX196', 'CXBEM', 'CV541', 'CW6C8', 'C74C4', 'C4MBE', 'CL968', 'CJE73', 'CB09J', 'CA38P', 'CB3FV', 'CIRFV', 'C616Z', 'CP724', 'CP515', 'CJ6B1', 'CB337', 'CW8C8', 'CW9CB', 'CX8C8', 'CF22P', 'C08RW', 'CX9C8', 'CC13C', 'CW5F1', 'CZRAH', 'CG12K', 'CP450', 'CM565', 'CV12G', 'C25AN', 'CA50A', 'CW8BB', 'CA31A', 'CU923', 'CA21A', 'CX190', 'CC1CX', 'CV1F4', 'CU18R', 'CC42H', 'CXI9G', 'CE22P', 'CV52B', 'CX0CD', 'CX3DD', 'CRKEC', 'C21FB']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,GL,MR0,GCC,4.0,CW6CB
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,GL2,MR0,GCC,4.0,CX9CB
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,DLX,MR0,GCC,4.0,CW12G
3,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,C,DLX TOP,MR0,GCC,2.0,CW12G
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,C,DLX,MR0,GCC,2.0,CX19G
...,...,...,...,...,...,...,...,...,...,...
4669,TOYOTA,TACOMA,6.0,PICKUP,C,SR5 (NON GCC),3TM,NON-GCC,NaN,CZ5AN
4670,TOYOTA,HILUX,4.0,PICKUP,C,DLX TOP,MR0,GCC,NaN,CW12G
4671,TOYOTA,HILUX,4.0,PICKUP,C,1,MR0,GCC,NaN,CX12G
4672,TOYOTA,TACOMA,6.0,PICKUP,C,SR5 (NON GCC),3TM,NON-GCC,NaN,CZ5AN
4673,TOYOTA,LAND CRUISER PRADO,4.0,SUV,C,GXR,JTE,GCC,NaN,CX3FJ

====================================================================================================
POS4: P
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'TACOMA', 'TUNDRA', 'RAV4', 'HILUX', 'COROLLA', 'LAND CRUISER PICK UP', 'YARIS', 'CAMRY', 'COASTER', 'SY150T', 'AVALON', 'PRADO', 'TOYOTA HIACE', 'GL770ULTRA', '4RUNNER']
  bodyType: ['PANEL VAN', 'MINI BUS HIGH ROOF', 'VAN', 'MINI BUS', 'PANEL VAN HIGH ROOF', 'PICK UP', 'PICK UP DOUBLE CAB', 'HALF PANEL VAN', 'SUV', 'PICKUP', 'SEDAN', 'BUS', 'CARGO VAN', 'PICKUP TRUCK', 'MOTORCYCLE', 'TRUCK', 'PICK UP SINGLE CAB', 'MPV', 'HATCHBACK', 'MINIVAN']
  trim: ['GL', 'GLX', 'STD', 'GLS', 'DX', 'STD (NON GCC)', 'DX H/R W/B', 'DL', 'LE HEV', 'DLS', '1794 EDITION (NON GCC)', 'XLI EXECUTIVE', 'LX AC PWR OPT', 'E', 'DLX', 'XLI', 'GLI', 'CREWMAX CAPSTONE (NON GCC)', 'LWB', 'DLS - STD ROOF', 'XLE', 'SE', 'VX', 'SE+', 'S ASF', 'S', 'SS', 'LWB HIGH ROOF', 'TOP', 'MID', 'A', 'BASE', 'YA', 'EXR', 'GLI TOP', '1', 'X', 'GLE', 'CTD', 'ST', 'XLE (NON GCC)', 'GLI HEV', 'PICK', 'LIMITED', 'TRD', '1794 EDITION (NON GC', 'CREWMAX CAPSTONE (NO']
  WMI: ['JTF', '5TE', '5TF', 'JTV', '2T3', '1GC', 'JTE', 'MB1', '5YF', 'RA6', '4TA', '9BS', '6T1', 'JTM', 'MHF', 'MLH', 'KLA', 'JTD', 'LK1', 'WBA', 'MBI', 'MC2', 'STF', 'LHG', 'RKL', 'LBB', 'HJR', '4T1']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['PX22P', 'PX42N', 'PY5F1', 'P1RFV', 'PTDEK', 'PC5DB', 'PBEJA', 'P4RCE', 'PW5F1', 'PX4EN', 'PAEHD', 'PM62N', 'P6X40', 'PE32K', 'PG34L', 'PT9F3', 'PC569', 'PA69J', 'PCKL9', 'PAAWA', 'PBAJA', 'PBEHD', 'PY22P', 'PBEFD', 'PK5C5', 'PBEFA', 'P1HLT', 'P4MCE', 'PLM90', 'PH5C5', 'PBEWA', 'PV42E', 'P9900', 'PBGJB', 'PE30K', 'PW923', 'PU5JR', 'PN62N']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,PANEL VAN,P,GL,JTF,GCC,5.0,PX22P
1,TOYOTA,HIACE,4.0,PANEL VAN,P,GL,JTF,GCC,5.0,PX22P
2,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,P,GLX,JTF,GCC,4.0,PX22P
3,TOYOTA,HIACE,4.0,VAN,P,GLX,JTF,GCC,4.0,PX22P
4,TOYOTA,HIACE,4.0,MINI BUS,P,STD,JTF,GCC,4.0,PX22P
...,...,...,...,...,...,...,...,...,...,...
3135,TOYOTA,TUNDRA,8.0,PICKUP,P,STD (NON GCC),5TF,NON-GCC,NaN,PY5F1
3136,TOYOTA,TUNDRA,6.0,PICKUP,P,1794 EDITION (NON GC,5TF,NON-GCC,NaN,PC5DB
3137,TOYOTA,TACOMA,4.0,PICKUP,P,STD (NON GCC),5TE,NON-GCC,NaN,PX42N
3138,TOYOTA,TUNDRA,6.0,PICKUP,P,1794 EDITION (NON GC,5TF,GCC,NaN,PC5DB
3139,TOYOTA,TUNDRA,6.0,PICKUP,P,CREWMAX CAPSTONE (NO,5TF,GCC,NaN,PC5DB

====================================================================================================
POS4: K
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'SIENNA', 'PRIUS', 'HILUX', 'TUNDRA', 'COROLLA CROSS', 'C-HR', 'XA', 'FORTUNER', 'CAMRY', 'COROLLA', 'MATRIX', 'RAV4', 'LAND CRUISER', 'SCION', 'PREVIA', 'SEQUOIA', 'TACOMA', 'OTHERS', 'BZ4X', 'RAV 4', 'COROLLA 1.6', 'COROLLA 1.8', '4RUNNER', 'HIGHLANDER', 'HIACE', 'STATION', 'ECHO', 'GRANVIA', 'هاي لوكس', '25 HX DC 4X4D 2.4LAT', 'TANDRA', '1999', 'SIENNA VAN', 'AVANZA', 'SENA', 'SENA VAN PASSENGER', '2 HX DC 4X40', 'COROLLA SEDAN / HATCH', 'هايلوكس', 'HAI LUX', '26HX DC 4X4D2.4L AT', 'SIENA', '26 HX DC 4X4 2.4LAT', '26HX DC 4X4 D2.4LAT', 'CHR', '26 HX DC 4X4 D 2.4L AT', 'TOYOTA - 26 HX DC 4X4 D 2.4L AT', '25 HX DC 4X4', 'DLX FA (PICK UP)', 'HX DC 4X4 D 2.4L AT', '26 HX DC 4X4D', 'COROLLA 1.5L/HATCHBACK', 'INNOVA', 'TOYOTA COROLLA', 'RUSH', 'TOYOTA COROLLA 1.8', 'COROLLA 1.3', 'SOLARA', 'GXR RA(STATION WAGON)', 'LAND CRUISER SINGLE-CABIN PICK UP', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'MPV', 'HATCHBACK', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'SUV- CROSSOVER', 'SUV', 'PICKUP', 'SALOON', 'VAN', 'STATION', 'PANEL VAN', 'MINI BUS', 'PICK UP', 'MINI BUS HIGH ROOF', 'PICKUP DOUBLE CAB', 'PANEL VAN HIGH ROOF', 'CONVERTIBLE']
  trim: ['FLEET', 'LE (NON GCC)', 'SE TRD AERO PK', 'ICONIC', 'SE', 'BASE', 'SGLX', 'MID', 'E', 'STD (NON GCC)', 'XLE (NON GCC)', 'GLI', 'TOP', 'VX', 'S', 'LIMITED (NON GCC)', 'GL2', 'EXR', 'XL', 'GLX', 'GXR', 'GLE-X HEV 40TH ANNIV', 'CREWMAX CAPSTONE (NON GCC)', 'STD', 'LE', 'C (NON GCC)', 'DLX', 'ECO', 'VXR', 'STD D', 'LE HEV', 'GL', 'GX', 'EX', 'SE (NON GCC)', 'SPORT', 'VX1', 'VXR BASE', 'DYNAMIC', 'S+', 'STANDARD', 'GLE', 'GLI HEV', 'XLI', 'CE (NON GCC)', 'VX2', 'TC (NON GCC)', 'FABRIC', 'PLATINUM', 'DLS', '1', 'SR5 (NON GCC)', 'PRO', 'GLI TOP', 'GA', 'LIMITED', 'X', 'SE TRD SPORT PK', 'EXI', 'ADVENTURE', 'DL', 'DX', 'XLI MID', 'PREMIUM', 'SLD', 'GLE HEV BLACK EDITION', 'USF', 'XSE (NON GCC)', 'TRD', 'GLE HEV', 'GLS', 'SE+', 'SENA', 'XLI EXECUTIVE', '1794 EDITION (NON GCC)', 'ASD', 'COMFORT', 'TX', 'SU', 'MPV', 'ABC', '1500', 'SED', '2', 'G', 'TRIM', 'HYBRID (NON GCC)', 'GRANDE HEV 40TH ANNIV', 'IM', 'STATION', 'XLI TOP']
  WMI: ['JTD', '5TD', 'MR2', 'MR0', '5TF', 'RKL', 'NMT', 'MHF', '4T1', 'JTN', 'VNK', '2T1', 'STF', 'LFM', 'MR1', 'JT4', 'JTF', '2T3', 'ME4', 'JTM', '5TB', 'MRO', 'JTK', '3TY', 'JND', 'STD', '3TM', 'JTE', 'KPD', 'STO', 'JTL', 'JTG', 'WDA', 'KL3', 'ZGU', 'LSG', 'AR2', 'MHE', 'MK2', '5TE', '4F4', 'MP2', 'ITD', '1G6', 'MRI', 'JTU', 'L3A']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['KW923', 'KK3DC', 'KT9F3', 'KB3FU', 'K19F3', 'KW9F3', 'KB8CD', 'KW9D3', 'KY5F1', 'KN3DU', 'KZ3DC', 'KAAAG', 'KW903', 'KZ4BX', 'KUAAG', 'KT623', 'KDTB3', 'KU8FS', 'KABAG', 'KCBAG', 'KZ1AK', 'K4RBE', 'KB5DB', 'K61AK', 'KK4CC', 'KT923', 'K29F3', 'KV521', 'KTUD3', 'KARFU', 'KB20U', 'KT4K3', 'KUBAG', 'KR32E', 'KBRFU', 'KR30E', 'KX8CB', 'KN5BF', 'KUBFS', 'KZ626', 'K440F', 'KU4EE', 'KX9CB', 'KM626', 'K61BK', 'KA3DC', 'KT521', 'KX6CB', 'KW73J', 'KBBCD', 'KCAAG', 'KSKFC', 'KHMBX', 'K1RFV', 'KRKEC', 'KT9D3', 'KAMFU', 'KX8CD', 'KC20F', 'KT441', 'KF4DV', 'KU5BF', 'KU104', 'K4MBE', 'KARJE', 'KW5F1', 'KB8FS', 'KY5G1', 'KD5HN', 'KU40E', 'KAJDC', 'KP14T', 'KM5F1', 'KU72N', 'KV36F', 'KN3DP', 'KB5DA', 'KU5JR', 'KAMFP', 'KARFP', 'KDRBH', 'KT903', 'KFDNN', 'KT624', 'KE50E', 'KB9CP', 'KT123', 'KHCAA', 'K31AK', 'KN3D0', 'KYSFI', 'KC4BS', 'K6E6F', 'KDRAH', 'KAAAC', 'KC20D', 'KZ4DX', 'KBAAG', 'KN9CP', 'KZA00', 'KK4DV', 'KB54H', 'KC311', 'KB71J', 'KV30F', 'KT421', 'KB8CP', 'K5KFC', 'KU8F5', 'KKRFH', 'KX8C8', 'K83FU', 'K6T1Y', 'KU4HN', 'KB22U', 'KT9K3', 'KY1CD', 'KUSFS', 'KE52Y', 'KWS23', 'K8RFU', 'KV32F', 'KW71J', 'KARAH', 'KAAA6', 'KZABX', 'KC206', 'KFNM3', 'KBRCH', 'KK3EH', 'KW8D3', 'KR38E', 'K23DC', 'KB5AB', 'K820U', 'KT604', 'KC20G', 'KX8FS', 'KB200', 'KZRFH']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,YARIS,4.0,SEDAN,K,FLEET,JTD,GCC,4.0,KW923
1,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),5TD,NON-GCC,5.0,KK3DC
2,TOYOTA,YARIS,4.0,SEDAN,K,FLEET,JTD,GCC,4.0,KW923
3,TOYOTA,YARIS,4.0,HATCHBACK,K,FLEET,JTD,GCC,5.0,KW923
4,TOYOTA,YARIS,4.0,SEDAN,K,SE TRD AERO PK,MR2,GCC,4.0,KT9F3
...,...,...,...,...,...,...,...,...,...,...
18606,TOYOTA,PRIUS,4.0,SEDAN,K,STD (NON GCC),JTD,NON-GCC,NaN,KN3DU
18607,TOYOTA,YARIS,4.0,HATCHBACK,K,SE,MR2,GCC,NaN,K19F3
18608,TOYOTA,SIENNA,6.0,SUV,K,LE (NON GCC),5TD,NON-GCC,NaN,KK3DC
18609,TOYOTA,YARIS,4.0,HATCHBACK,K,SE+,VNK,NON-GCC,NaN,KTUD3
18610,TOYOTA,COROLLA CROSS,4.0,SUV,K,XL,RKL,GCC,NaN,KUBAG

====================================================================================================
POS4: M
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TUNDRA', 'AVANZA', 'LAND CRUISER PICK UP', 'CAMRY', 'CRESSIDA', 'COROLLA', 'TACOMA', 'SUPRA', 'RAV4', 'LAND CRUISER', 'TOYOTA TACOMA', 'JUSTIN BIEBER X VESPA 150 E5 GSO (SCOOTER)', 'COROLLA SEDAN', 'HILUX', 'AURION', 'TAKOMA', 'C-HR', 'FORTUNER', 'VESPA VXL 150', 'VESPA VXL', 'افنزا', '4RUNNER', 'AVALON', 'HIACE', 'CAMRY HYBRID']
  bodyType: ['PICK UP DOUBLE CAB', 'MPV', 'SUV', 'SEDAN', 'COUPE', 'PICKUP', 'PICK UP', 'PANEL VAN', 'MOTORCYCLE', 'STATION', 'VAN', 'MINI BUS']
  trim: ['STD (NON GCC)', 'SE', '1794 EDITION (NON GCC)', 'CREWMAX CAPSTONE (NON GCC)', 'LX AC PWR OPT', 'GLE HEV', 'STD', 'XLI', 'LE', 'COUPE', 'BASE', 'EXR', 'GXR FMST', 'SGL', 'STD AC', 'GLS', 'DLX', 'GLX', 'CRESSIDA', 'GLI', 'GLE', 'AXL ', 'STD CARGO', 'GRANDE', 'S', 'EX', 'LIMITED', 'E', 'SR', 'STANDARD', 'SPORT', 'PW CL', 'LUXURY SPORT', 'GV', '60TH', 'GR', 'SE+', 'GL', 'VX', 'DL', '1794 EDITION (NON GC', '1']
  WMI: ['5TF', 'MHK', '4T1', 'JT2', '3TM', 'ZAP', 'RP8', 'MMM', '57W', 'JTH', 'MET', 'JTM', '5TE', '4T3', 'JD2', 'JHH', 'JTE', 'JTD', 'LVZ', 'LNB', '2T3', 'LJN']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['MV521', 'MF53F', 'MC13F', 'MF5CF', 'MF5BF', 'MF52F', 'MC12F', 'MFSCF', 'MC5DB', 'MA5EC', 'MU4FN', 'M11AK', 'MX83E', 'MA71J', 'MD350', 'MA71L', 'M4571', 'M1111', 'MY5F1', 'ML2A6', 'MA360', 'MT09J', 'MD121', 'M8500', 'MFSBF', 'MWRFV', 'MA5DB', 'MU52N', 'MX73E', 'MA70J', 'MT521', 'ME53F', 'MF929', 'MD352', 'MD351', 'MCK3H', 'MU5JR', 'M4RCE', 'MN25B', 'MCUBK', 'MC5AB', 'MA70L', 'MFWBY']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,M,STD (NON GCC),5TF,GCC,4.0,MV521
1,TOYOTA,AVANZA,4.0,MPV,M,SE,MHK,GCC,NaN,MF53F
2,TOYOTA,AVANZA,4.0,MPV,M,SE,MHK,GCC,5.0,MC13F
3,TOYOTA,AVANZA,4.0,MPV,M,SE,MHK,GCC,5.0,MF53F
4,TOYOTA,AVANZA,4.0,MPV,M,SE,MHK,GCC,5.0,MF5CF
...,...,...,...,...,...,...,...,...,...,...
1652,TOYOTA,AVANZA,4.0,SUV,M,1,MHK,GCC,NaN,MC13F
1653,TOYOTA,AVANZA,4.0,SUV,M,SE,MHK,GCC,NaN,MF5BF
1654,TOYOTA,AVANZA,4.0,SUV,M,1,MHK,GCC,NaN,MC13F
1655,TOYOTA,AVANZA,4.0,SUV,M,SE,MHK,GCC,NaN,MC13F
1656,TOYOTA,AVANZA,4.0,SUV,M,SE,MHK,GCC,NaN,MF5CF

====================================================================================================
POS4: Y
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['FORTUNER', 'RAV4', 'SIENNA', 'GRANVIA', 'URBAN CRUISER', 'HIGHLANDER', 'SEQUOIA', '2009', 'RAV 4', 'FJ CRUISER', 'HILUX', 'COROLLA', 'LAND CRUISER', 'YARIS', 'TUNDRA', 'DYNA', 'TOYOTA', 'SIENNA(VAN)', 'H 530', 'VAN']
  bodyType: ['SUV', 'MPV', 'STATION', 'PICK UP DOUBLE CAB', 'VAN', 'SEDAN', 'PICK UP SINGLE CAB', 'TRUCK', 'LIGHT VEHICLE']
  trim: ['GXR', 'SR5', 'TOP', 'BASE', 'LE (NON GCC)', 'PLATINUM', 'FABRIC', 'EXR', 'XLE (NON GCC)', 'PREMIUM', 'GL', 'LIMITED (NON GCC)', 'GLX', 'STD', 'PW CL', 'SE (NON GCC)', 'STD (NON GCC)', 'SR5 (NON GCC)', 'VX', 'SPORT', 'EX', 'XSE', 'SR5 4X2', 'TRD SPORT', 'DLS', 'SR5 4X4', 'BE', 'LIMITED 4X4', 'XLE', 'GLI', 'GX', 'CE (NON GCC)', 'TX', 'T', 'SED', 'EXCLUSIVE', 'E', 'GLE HEV', 'SE', 'S', 'LE', 'DL', 'DLX', '1']
  WMI: ['MHF', 'MR1', '2T3', '5TD', 'JTN', 'JTE', 'MBJ', 'JT3', 'MHE', 'JTM', 'JTD', '5FP', 'STD', 'MRI', 'MEJ', 'JHH', '2HN', 'MPJ', '5TF', 'MAF', 'SAL', 'JHG', 'LSY', 'LET', 'JHF']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['YU59G', 'YX59G', 'YK4DV', 'YK4CC', 'YM8AP', 'YH20V', 'YK3DC', 'YM3AP', 'YMLA2', 'YZ3DC', 'YP10V', 'YARAH', 'YFREV', 'YY5G1', 'YF4DV', 'YX596', 'YF4EV', 'YKRFH', 'YX69G', 'YU596', 'YSKFC', 'YRKEC', 'YK1F7', 'Y23DC', 'YX59C', 'YH207', 'YZRAH', 'YF9EV', 'YX590', 'YXS9G', 'YK3F1', 'YMLAZ', 'YKACC', 'YCN1H', 'YD282', 'YU590', 'Y1RFV', 'YU5F1', 'YL2FV', 'YZRFH', 'YJ227', 'YBBCA', 'YFAG2', 'YX50G', 'YB20H']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,FORTUNER,6.0,SUV,Y,GXR,MHF,GCC,NaN,YU59G
1,TOYOTA,FORTUNER,4.0,SUV,Y,SR5,MHF,GCC,5.0,YX59G
2,TOYOTA,FORTUNER,4.0,SUV,Y,TOP,MR1,GCC,5.0,YU59G
3,TOYOTA,FORTUNER,4.0,SUV,Y,SR5,MHF,GCC,5.0,YX59G
4,TOYOTA,RAV4,4.0,SUV,Y,BASE,2T3,GCC,5.0,YK4DV
...,...,...,...,...,...,...,...,...,...,...
5067,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,MBJ,GCC,NaN,YMLA2
5068,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GL,MBJ,GCC,NaN,YMLA2
5069,TOYOTA,RAV4,4.0,SUV,Y,1,JTE,NON-GCC,NaN,YH20V
5070,TOYOTA,FORTUNER,4.0,SUV,Y,SR5,MHF,GCC,NaN,YX59G
5071,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,MBJ,GCC,NaN,YMLA2

====================================================================================================
POS4: D
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['FORTUNER', 'HILUX', 'SEQUOIA', 'RAV4', 'TUNDRA', 'SUPRA', 'BZ4X', 'SCION', 'LAND CRUISER', 'TACOMA', 'OTHERS', 'YARIS', 'SIENNA', 'COROLLA', 'ECHO', 'RAV 4', 'COROLLA CROSS', 'HIACE', 'CAMRY', 'HIGHLANDER', '2023', 'BZ3X', 'PICK UP', 'HAI LUX', 'C-HR', 'BZ 4', 'CELICA', '86', 'COASTER', 'AVALON', 'SELICA', 'LAND CRUISER GX', 'SUPRA COUPE', 'XA', '26HX DC 4X4 PLAT', '2 HX DC 4X4 P 2.7LAT', 'FJ CRUISER', 'H3', 'PRADO', 'هايلوكس', 'BZ46']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'PICK UP', 'COUPE', 'PICK UP SINGLE CAB', 'SEDAN', 'HATCHBACK', 'MPV', 'STATION', 'PICKUP', 'SUV- CROSSOVER', 'MINI BUS', 'MINI BUS HIGH ROOF', 'PICK UP DOUBLE CABIN', 'PANEL VAN', 'BUS', 'LIGHT VEHICLE', 'PICKUP DOUBLE CAB']
  trim: ['EXR', 'GL2', 'SR5 (NON GCC)', 'VXR', 'DLX', 'STD (NON GCC)', 'GR', 'PRO', 'EX', 'VXR HEV', 'DL', 'DLX TOP', 'GX', 'GL', 'GXR', 'G', 'XLI', 'SE', 'LE (NON GCC)', 'GLS', 'GLX', 'BE', 'XLI TOP', 'T', 'GXR TOP', 'LIMITED (NON GCC)', 'GR TAN EDITION', 'VX', 'DLS', 'VX2', 'SGLX', 'LE', 'SE (NON GCC)', 'BASE', 'DX', 'GR BLUE EDITION', 'GLI', 'GXR TOP DMST', 'LE HEV', 'XLE (NON GCC)', 'SE+', 'GXR FMST', 'GLE HEV', 'XLI MID', 'XLE HEV', 'STATION', 'GXR TOP 60TH ANNIV. XTREME', 'GT SPORT', 'AIR', 'HYBRID (NON GCC)', '25HX', 'GLE', 'XLE', 'STD', 'LIMITED 4X4', 'GL DECKLESS', 'XL', 'PLATINUM', 'LIMITED MID', 'E', 'CABRIO', 'XLI EXECUTIVE', 'ADVENTTURE', 'VX2 PLUS', 'TOP', 'GXR2', 'S', 'GLI HEV', 'MID', 'SR5 4X2', 'SWB', 'EXECUTIVE', 'GT', 'LWB', 'ADVENTURE', 'VX1', '1', 'A', 'STEALTH', 'GXR TOP 60TH ANNIV. ']
  WMI: ['MHF', 'MRO', '5TD', 'JTM', 'MR0', '5TF', 'WZ1', 'LVG', '3MY', '5TB', 'JT2', 'STB', 'JTF', '2T3', 'JTN', '3TY', 'MR1', 'JTD', '7MU', 'JN6', '6T1', '4T1', '5YF', 'JTB', 'WV1', 'STF', 'LWL', '5T8', 'MRI', '3TM', 'JTE', '3N6', 'JN1', 'MNT', 'RKM', 'JT4', 'JTK', 'ZFC', 'MYN', 'LVV', 'WZI', 'JT3', '1G6', 'JAC', 'KMH', 'JNK', 'STY', 'SMT', '4TI', 'JAA', 'STM', 'JYM', '5GT', '4T3', 'WVW', '25T', '5TE']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['DX8FS', 'DB9CD', 'DY5G1', 'DF4EV', 'DX22G', 'DW5F1', 'DB0E0', 'D3135', 'DW3FV', 'DY5F1', 'DV541', 'DF9EV', 'DX9CD', 'DLBZV', 'DU09J', 'DT441', 'DZ5BN', 'DP02T', 'DM5F1', 'DLBYV', 'DB0A0', 'DM626', 'DK3DC', 'DV581', 'DFREV', 'DX8CD', 'DBSCD', 'D4MBE', 'DJREV', 'DB4A0', 'DR32T', 'D156F', 'DX6CD', 'DX8F5', 'DAABG', 'DW5G1', 'DF4DV', 'DK4DV', 'DB4C0', 'DK4CC', 'DW12S', 'DZ3DC', 'DE32K', 'DT481', 'DBADK', 'DW541', 'DPRAE', 'DZRBH', 'DPMAE', 'DB12E', 'DW923', 'DAACK', 'DBZSV', 'DAR9K', 'DB2C0', 'DZRFH', 'DLBJV', 'DWSF1', 'D2DF6', 'DB8CD', 'DS43A', 'DZ626', 'DB9CB', 'DD21A', 'D3DF6', 'DWRFV', 'DD2EY', 'DT3MW', 'D1RFV', 'DB6CD', 'DD23S', 'DE626', 'DTPUK', 'DS41A', 'DE167', 'DX9CB', 'D541A', 'DB0G0', 'DB8FS', 'DZSBN', 'DKJA0', 'DL25R', 'DB0C0', 'DBWG3', 'DB24B', 'DB41S', 'DJ81W', 'DP21A', 'DW51E', 'DY32T', 'DH88W', 'DG61E', 'DE4EV', 'DD82A', 'D4RBE', 'DAAAG', 'DZ1FB', 'DBOE0', 'D13FV', 'DF4EB', 'DX226', 'DA1AB', 'DXBFS', 'DU09T', 'DH88X', 'DA31A', 'DB21B', 'DW11S', 'DX1H2', 'DL39M', 'DD22S', 'DB0AO', 'DT541', 'DX6CB', 'DF4EU', 'DBYSV', 'DXBCD', 'DB2A0', 'DN136', 'DN56A', 'D6RFV', 'DY38T', 'DSKFC', 'DH4CD', 'DYSF1', 'DK3EH', 'DZK23', 'DARTK', 'D23DC', 'DE82A', 'DCRFH', 'DGRFH', 'DFAEV', 'DV09J', 'D89CD', 'D258N']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,FORTUNER,4.0,SUV,D,EXR,MHF,GCC,5.0,DX8FS
1,TOYOTA,FORTUNER,4.0,SUV,D,EXR,MHF,GCC,5.0,DX8FS
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,D,GL2,MRO,GCC,4.0,DB9CD
3,TOYOTA,SEQUOIA,8.0,SUV,D,SR5 (NON GCC),5TD,GCC,5.0,DY5G1
4,TOYOTA,RAV4,4.0,SUV,D,VXR,JTM,GCC,5.0,DF4EV
...,...,...,...,...,...,...,...,...,...,...
6554,TOYOTA,COROLLA,4.0,SEDAN,D,STD (NON GCC),JTD,NON-GCC,NaN,DPRAE
6555,TOYOTA,RAV4,4.0,SUV,D,VXR,JTM,GCC,NaN,DF4EV
6556,TOYOTA,TUNDRA,8.0,PICKUP,D,STD (NON GCC),5TF,NON-GCC,NaN,DY5F1
6557,TOYOTA,RAV4,4.0,SUV,D,VXR,JTM,GCC,NaN,DF4EV
6558,TOYOTA,TUNDRA,8.0,PICKUP,D,STD (NON GCC),5TF,NON-GCC,NaN,DW5F1

====================================================================================================
POS4: A
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'TUNDRA', 'VELOZ', 'RAIZE', 'CAMRY', 'CROWN', 'COROLLA', 'HILUX', 'PRADO', 'DYNA', 'INNOVA', 'FORTUNER', 'HIACE', 'TOYOTA VELOZ', 'COROLLA 1.3', 'COROLLA CROSS', 'LAND CRUISER PRADO', 'AVALON', 'BZ4X', 'YARIS', 'بريفيا', 'PRIUS', 'TOYOTA PRIUS', 'COROLLA 1.6', 'RAV4', 'SEQUOIA', 'ALPHARD', 'FJ CRUISER', 'TACOMA', 'BZ 4', 'COASTER', 'TOYOTA COROLLA', 'HIGHLANDER', 'ALLION', 'DAINA', 'COROLLA 1.8', 'MODEL 2022', '25 CA SON P 2.5L AT', '26 YA HB P 1.6L AT TURBO GR RA(CAR)', 'ECHO', 'GXL RA (STATION WAGON)', '25PR 5 DR P 2.4L AT', 'WIGO', 'SIENNA', '4RUNNER', 'MIRAI', 'COROLLA SEDAN', 'CAMRY HYBRID']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'SEDAN', 'PICK UP SINGLE CAB', 'PICKUP', 'PICK UP', 'MPV', 'MINI BUS', 'STATION', 'SUV- CROSSOVER', 'HATCHBACK', 'VAN', 'PANEL VAN', 'SALOON', 'BUS', 'COUPE', 'WAGON', 'PANEL VAN HIGH ROOF']
  trim: ['GXR', 'VXR', 'STD (NON GCC)', 'EXR', 'GX', 'TURBO G RA', 'E', 'LIMITED', 'PREMIUM', 'XLI EXECUTIVE MR', 'XLE', 'DLX', 'VX', 'ADVENTURE', 'GLE HEV', 'BLACK EDITION', 'GLE', 'STD', 'GXL', 'PLATINUM', 'GX MID', 'GXR2', 'GLI', 'HEV', 'GR SPORT', 'TXL1', 'XLI', 'SE', 'TXL3', 'E PLUS HEV', 'TOP', 'XLI EXECUTIVE', 'DX', 'DLX TOP', 'HEV GLI', 'GLX', 'GXR1', 'XLI EXECUTIVE HEV', 'GR-S', 'GXR TOP', 'LE HEV', 'XLI MID', 'DL', 'XL', 'TXR', 'PRO', 'GRANDE', 'GR', 'TX1', 'SEDAN', 'LE', 'GXR SOD D/AC AW', 'LIMITED HEV', 'S', 'GXR4', 'XLI POWER OPT', 'GL', 'SE+', 'DLS', 'XLI - AW', 'TURBO G', 'GXR-V', 'XLI TOP', 'SPORT', 'G', 'BASE', 'LUMIERE HEV', 'SR5 (NON GCC)', 'TRIM', 'VXR BASE', 'HYBRID (NON GCC)', 'GLI TOP', 'LUXURY', 'HYCROSS', 'VX MID', '10TH VICTORY EDITION', 'GL LIMITED', 'SS', 'GXL 1ST EDITION', 'LE (NON GCC)', 'VIP7', '45', 'GXR3', 'GLI MR HEV', '1500', 'AMBIENTE', 'TRD', 'ADVENTURE 1ST EDITION', 'AMG', 'SL', 'LS', 'DTD', 'CTD', 'GLS', 'GXR FMST', 'GLI HEV', 'SGLX', 'MID', 'XLI ', 'SALOON', '1', 'ADVENTURE 1ST EDITIO', 'XLI HEV']
  WMI: ['JTM', '5TF', 'MHF', 'MHK', 'JTN', 'JTD', 'LFM', 'JTF', 'JTE', 'JT4', 'MR0', '4T1', 'YV2', 'JN8', 'JT2', 'JN6', 'MRO', 'GTF', '1NX', '7MU', '2T1', 'JT3', 'STF', '2T3', '7SV', '3TM', 'JHH', 'MD2', 'JIM', 'LEF', 'MB1', 'LET', 'JTG', 'LS4', 'YV1', 'JE3', 'ZFC', 'JA3', '123', 'LM6', 'LSF', 'MKH', '5N1', 'LK6', 'LMX', '1G6', '5TD', 'IN6', 'INB', 'LSJ', 'K1K', '6TF', 'A25', 'WVW', 'W1K', 'MBI', 'MBT', 'MFF', 'HJ4', 'JHG']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['AUBBJ', 'ABBBJ', 'AB7BJ', 'AY5F1', 'AUCBJ', 'AW5F1', 'AB1BY', 'AA1BA', 'AB1BA', 'AG4CK', 'ACABF', 'AAA0C', 'AFAAF', 'AM496', 'AM29J', 'AACAJ', 'A14CK', 'AU7BJ', 'ABCBJ', 'AG426', 'AY117', 'AU25J', 'AW12G', 'A1809', 'ABBAA', 'AACBJ', 'AABBJ', 'AAADC', 'A11AK', 'AL29J', 'A4DAA', 'AA9AJ', 'A180C', 'AZ496', 'AYT30', 'AC7BJ', 'AU88J', 'AE09V', 'AE54S', 'AAAAF', 'ABIBY', 'ASACK', 'A1ACC', 'AE00B', 'AXACC', 'A4DAC', 'A4B2A', 'AE52S', 'AL1CC', 'ARE0C', 'AX12G', 'AAAAG', 'AE09B', 'AAYAJ', 'AZ1FB', 'AAAAA', 'AA7BJ', 'AN95J', 'A4B3A', 'AG30A', 'A4DMA', 'AE04B', 'A4CFA', 'AF4E3', 'AC11R', 'ACAAU', 'AAABG', 'AP22C', 'A6426', 'AW126', 'ASG0A', 'AUTBJ', 'A1RFV', 'AAABA', 'AZ5CN', 'ACJ4H', 'ARE2C', 'AE00E', 'AEACH', 'A22EZ', 'AG20A', 'A4CEA', 'AFCG2', 'AE82G', 'APE2C', 'AE525', 'A818Y', 'AE09W', 'AG34L', 'AE2KP', 'AS14U', 'A878J', 'AE51S', 'AYACC', 'AP86C', 'AE09E', 'AECG2', 'AC22C', 'AE53S', 'AE1BY', 'A888J', 'AECB8', 'ASB3R', 'AS47H', 'AB36U', 'AE04E', 'AY86C', 'AU78J', 'A4MBE', 'AI4CK', 'AM450', 'AFZBG', 'A11CX', 'AM498', 'AN74K', 'AS12G', 'AECG3', 'ARCAJ', 'AS123', 'AC1DM', 'AF54K', 'AFABF', 'AM11H', 'ACAAJ', 'AB18Y', 'AAAOC', 'AE94K', 'AP90A', 'AY2NY', 'AEAA1', 'AKCB8', 'AT2MV', 'ADAE2', 'ASW0A', 'A14AF', 'AA5RX', 'AAAB5', 'A4B5A', 'AK54K', 'AE07B', 'A22NE', 'A16E3', 'AUZBJ', 'AX126', 'A11CY', 'AABAJ', 'AA18A', 'AS02A', 'AUF0A', 'AJ54K', 'AT123', 'AUBB3', 'AVV5F', 'AAN6E', 'AALAJ', 'AR05Y', 'A4RBE', 'AB7RJ', 'A4DF5', 'AX5GN', 'AX8CD', 'AAIBA', 'ABFAJ', 'AATBA', 'A0B98', 'AM2AH', 'AE94A', 'AF4CB', 'AA1AB', 'AR9AJ', 'AP54K', 'AS02D', 'AE1EY', 'AGACH', 'ABBDH', 'ACAB5', 'A4DBA', 'AAAA5', 'AF047']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,JTM,GCC,5.0,AUBBJ
1,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,JTM,GCC,5.0,ABBBJ
2,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,JTM,GCC,5.0,AB7BJ
3,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,JTM,GCC,5.0,AB7BJ
4,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,A,STD (NON GCC),5TF,GCC,4.0,AY5F1
...,...,...,...,...,...,...,...,...,...,...
11165,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,JTM,GCC,NaN,AB7BJ
11166,TOYOTA,LAND CRUISER,6.0,SUV,A,1,JTM,GCC,NaN,AACBJ
11167,TOYOTA,CAMRY HYBRID,4.0,SEDAN,A,XLE,JTN,GCC,NaN,A14CK
11168,TOYOTA,LAND CRUISER,6.0,SUV,A,1,JTM,GCC,NaN,ABBBJ
11169,TOYOTA,LAND CRUISER PRADO,4.0,SUV,A,GXL,JTE,GCC,NaN,AACAJ

====================================================================================================
POS4: F
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COASTER', 'HILUX', 'RAV4', 'LAND CRUISER', 'SOLARA', 'LAND CRUISER 70', 'HIACE', 'HIGHLANDER', 'TUNDRA', 'COROLLA', 'SIENNA', 'LAND CRUISER PICKUP 70', 'SEQUOIA', 'COROLLA CROSS', 'CAMRY', 'MR2', 'AVALON', 'LAND CRUISER / STATION', '4RUNNER', 'INNOVA', 'حافلة نقل خاص', 'TACOMA', 'RAV4 LE CAR', 'TOYOTA', 'CAMRY SOLARA']
  bodyType: ['BUS', 'PICK UP DOUBLE CAB', 'PICK UP', 'PICK UP SINGLE CAB', 'SUV', 'CONVERTIBLE', 'PICKUP', 'PANEL VAN', 'SEDAN', 'MINI BUS', 'MPV', 'SUV- CROSSOVER', 'COUPE', 'HATCHBACK', 'HALF PANEL VAN', 'STATION', 'MINI BUS HIGH ROOF']
  trim: ['STD', 'DLX', 'GLS', 'GL', 'DLX TOP', 'LE', 'GXR MID', 'LWB HIGH ROOF', 'LWB', 'LSE', 'SWB', 'HT SWB', 'VX', '1', 'GLX', 'PLATINUM', 'STD (NON GCC)', 'XLI EXECUTIVE', 'GXR FMST', 'DX', 'GXR2', 'EXR', 'GXR', 'GXR TOP DMST', 'BUS', 'LE (NON GCC)', 'LX', 'SR5 (NON GCC)', 'HT VXR', 'STAN', 'LE HEV', 'SPORT', 'PREMIUM', 'GLE HEV', 'LE STD', 'LIMITED', 'S', 'S PLUS', 'GLE-X HEV 40TH ANNIV', 'SE+', 'SE', 'A', 'STANDARD', 'DLS', 'GX', 'XLI TOP', 'BASE', 'COASTER', 'S T2 TOP', 'XSE (NON GCC)', 'XL', 'ADVENTURE', 'ST', 'DL', 'GXR TOP', 'DC', 'HYBRID (NON GCC)', '4']
  WMI: ['JTC', 'MR0', 'MRO', '2T3', 'JTE', 'JTG', '4T1', 'JT4', '137', '5TD', '5TF', 'JTD', 'JTM', 'JT3', 'JT6', 'JN6', '5TT', '7MU', 'L7X', 'LM8', '1GD', 'JAA', 'JHD', 'JTH', '3GY', 'L3H', 'WDD', 'KMH', 'VF1', '2D4', 'JTF', 'MB0', '1GC', '2T1']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['FZ418', 'FX22G', 'F1RFV', 'FU71J', 'FK418', 'FA38P', 'FK718', 'FX226', 'FK518', 'FG426', 'FB518', 'FR119', 'FU73J', 'FJ71J', 'FM518', 'FA903', 'FY418', 'FZRBH', 'FY5F1', 'FR22G', 'FPMAE', 'FA119', 'FJ60G', 'FX00G', 'FM418', 'FE52S', 'FBW41', 'FE718', 'FY5B1', 'FE53S', 'FBABG', 'FPEFF', 'FR320', 'F11AK', 'F31AK', 'FZ1FB', 'FPRAE', 'FU5JR', 'F7E69', 'FG15T', 'FP14F', 'FE54S', 'FE728', 'FD3HL', 'FX02P', 'FARAH', 'FK122', 'F11BK', 'FDABB', 'FR73J', 'FH3CB', 'FX22C', 'FF41C', 'F6RDM', 'FV47V', 'FR226', 'FDA88', 'FDAB8', 'FIRFV', 'FF719', 'FB718', 'F7D19', 'FW12G', 'FY5A1', 'FX22P', 'FJ60V', 'FG8JP', 'FC24H', 'FF22P', 'FE22P']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COASTER,6.0,BUS,F,STD,JTC,GCC,2.0,FZ418
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,F,DLX,MR0,GCC,4.0,FX22G
2,TOYOTA,HILUX,4.0,PICK UP,F,DLX,MR0,GCC,2.0,FX22G
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,F,DLX,MR0,GCC,4.0,FX22G
4,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,F,DLX,MR0,GCC,4.0,FX22G
...,...,...,...,...,...,...,...,...,...,...
3392,TOYOTA,HILUX,4.0,PICKUP,F,DLX,MR0,GCC,NaN,FX22G
3393,TOYOTA,HILUX,4.0,PICKUP,F,DLX,MR0,GCC,NaN,FX22G
3394,TOYOTA,HILUX,4.0,PICKUP,F,DLX,MR0,GCC,NaN,FX22G
3395,TOYOTA,HILUX,4.0,PICKUP,F,DLX,MR0,GCC,NaN,FR22G
3396,TOYOTA,HILUX,4.0,PICKUP,F,DLX TOP,MR0,GCC,NaN,FX22G

====================================================================================================
POS4: J
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'PRADO', 'YARIS', 'HILUX', 'IQ', 'ECHO', 'RAV4', 'TUNDRA', 'SIENNA', '4RUNNER', '86', 'ZELAS', 'SCION', 'LAND CRUISER', 'HIGHLANDER', 'CROWN KLUGER', 'SUPRA', 'LAND CRUISER PRADO', 'CAMRY', 'SEQUOIA', 'TACOMA', 'AVALON', 'PREVIA', 'INNOVA', 'TOYOTA', 'RAV 4', 'T 100', '2012', 'TAKOMA', 'TOYOTA SCION', 'PRIUS', 'TOYOTA IQ', 'TOYOTA SUPRA', 'TOYOTA SQUIN', '25 HX DC 4X2 P 27L AT GLX RA/PICK UP', 'T100', 'هايلوكس', 'COROLLA CROSS', 'BZ4X', 'COUPE', 'COROLLA', 'TOYOTA 86']
  bodyType: ['PANEL VAN', 'SUV', 'HATCHBACK', 'PICK UP SINGLE CAB', 'MINI BUS', 'SEDAN', 'HALF PANEL VAN', 'PICK UP DOUBLE CAB', 'MPV', 'MINI BUS HIGH ROOF', 'COUPE', 'VAN', 'BUS', 'PICKUP', 'STATION', 'MINI BUS SEMI HIGH ROOF', 'PICKUP DOUBLE CABIN', 'PANEL VAN HIGH ROOF', 'PICK UP', 'SUV- CROSSOVER']
  trim: ['GL', 'TX', 'STD', 'GLX', 'GXR', 'DX', 'STD (NON GCC)', 'XLI MID', 'FLEET', 'VXR', 'TX-L TOP', 'ADVENTURE', 'DX H/R W/B', 'TX-L', 'DLX', 'LE (NON GCC)', 'BASE', 'SR5 (NON GCC)', 'MID', 'GT', '1794 EDITION (NON GCC)', 'LIMITED (NON GCC)', 'TOP', 'EXR', 'VX TOP LTH', 'SE TRD AERO PK', 'SE', 'VX', 'LE HEV', 'EX', 'XLE (NON GCC)', 'SPORT', 'DL', 'GX', 'SE (NON GCC)', 'TC (NON GCC)', 'CREWMAX CAPSTONE (NON GCC)', 'XLE', 'STANDARD', 'GRD', '2400', 'PLATINUM', 'LIMITED 4X4', 'SE+', 'AUTOMATIC', 'GL TOP', 'A', 'VXR HEV', '1', 'GLS', 'C', 'EXR HEV', 'LTD HEV', 'S', 'FULL OPTION', 'DLS', 'LE', '4WD', '1500 CREWCAB SLE Z71', 'GL2', 'N', 'CAR TRIM', 'VX-L TOP', 'SR', 'PW CL', 'SGLX', 'GXR GT', '60TH', 'HYBRID (NON GCC)', 'SUPER SAFARI T1', 'FABRIC', 'GXL', '0', '4', 'SE T2', 'S T1', 'GLI', 'PRO', 'XLI', 'GXR TOP 60TH ANNIV. XTREME']
  WMI: ['JTG', 'JTE', 'JTD', 'MR0', 'JTN', 'JTM', '5TB', '5TD', 'LFM', 'JT6', 'JMY', '5TF', 'JTK', '2T3', 'VNK', 'ITG', 'JT2', 'MMB', 'MRO', 'KMH', '3TY', 'JTF', '4T1', '3TM', 'JT8', 'UTG', 'JT4', 'J1G', '5TE', 'JIG', '1ST', 'KMF', '3D7', 'YV2']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['JX02P', 'JU9FJ', 'JT923', 'JX9CD', 'JU3FJ', 'JJXB0', 'JT123', 'JT4K3', 'JX8CD', 'J13FV', 'JN321', 'JX8CB', 'JK4CC', 'JV36F', 'JS02P', 'JK3DC', 'JT903', 'JNP13', 'JA5AB', 'JF5C7', 'JF4DV', 'JTUD3', 'JU521', 'JJREV', 'JFREV', 'J44AF', 'JZ3DC', 'JA5DB', 'JA5EC', 'JX6CB', 'J440F', 'JC5DB', 'JV03J', 'JY5F1', 'JX9CB', 'JX6CD', 'JZRFH', 'JD7BN', 'JA82J', 'J1RFV', 'JNK62', 'JX6BB', 'JB6CD', 'JNK65', 'J34AF', 'JW30F', 'JT81E', 'JX4CN', 'JY5G1', 'JK4DV', 'JX8BB', 'JA5DA', 'JC5EC', 'JDAHN', 'JW5G1', 'JZ1FB', 'JV521', 'JU8FJ', 'JUNFJ', 'JA81L', 'JU4GN', 'JNK64', 'JA81J', 'JS8CD', 'JN5BF', 'JM11D', 'JY09J', 'JXOZP', 'JX9BB', 'JU321', 'JU62N', 'JX4GN', 'JBYP2', 'JA17B', 'JU03J', 'JRKEC', 'J23DC', 'JU9EJ', 'JV1ET', 'JT05J', 'JW3EH', 'JXQ2P', 'JJX80', 'JKRFH', 'JU9FI', 'J11BK', 'JU9F1', 'JNKG2', 'JK02P', 'JTU03', 'JM30D', 'JUGFJ', 'J4CMA', 'JT521', 'JR14T', 'JK3EH', 'JFSC7', 'JT9K3', 'J4CFC', 'JXO2P', 'JU09J', 'JB6CB']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,PANEL VAN,J,GL,JTG,GCC,5.0,JX02P
1,TOYOTA,PRADO,4.0,SUV,J,TX,JTE,GCC,3.0,JU9FJ
2,TOYOTA,YARIS,4.0,HATCHBACK,J,STD,JTD,GCC,3.0,JT923
3,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,J,GLX,MR0,GCC,2.0,JX9CD
4,TOYOTA,PRADO,4.0,SUV,J,GXR,JTE,GCC,3.0,JU3FJ
...,...,...,...,...,...,...,...,...,...,...
5813,TOYOTA,YARIS,4.0,HATCHBACK,J,TOP,JTD,NON-GCC,NaN,JT4K3
5814,TOYOTA,ZELAS,4.0,COUPE,J,MID,JTK,GCC,NaN,JF5C7
5815,TOYOTA,TUNDRA,8.0,PICKUP,J,STD (NON GCC),5TF,NON-GCC,NaN,JV521
5816,TOYOTA,RAV4,4.0,SUV,J,ADVENTURE,JTM,GCC,NaN,J13FV
5817,TOYOTA,LAND CRUISER PRADO,6.0,SUV,J,TX-L,JTE,GCC,NaN,JU9FJ

====================================================================================================
POS4: R
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'HIACE', 'TUNDRA', '4 RUNNER', 'TACOMA', 'LAND CRUISER', 'HILUX', 'YARIS', '4RUNNER', 'CAMRY', 'SIENNA', 'TANDRA', 'COROLLA', 'MT 03', 'COASTER', 'INNOVA', 'HAI LUX']
  bodyType: ['SUV', 'PANEL VAN', 'MINI BUS', 'PICK UP DOUBLE CAB', 'HALF PANEL VAN', 'PANEL VAN HIGH ROOF', 'MINI BUS SEMI HIGH ROOF', 'MINI BUS HIGH ROOF', 'STATION', 'PICKUP', 'VAN', 'HATCHBACK', 'SEDAN', 'MPV', 'PICK UP SINGLE CAB', 'BUS', 'MOTORCYCLE', 'AMBULANCE', 'SALOON', 'PICKUP DOUBLE CABIN']
  trim: ['GXR', 'EXR', 'GL', 'DX', 'GX', 'VX', 'XLE', 'STD (NON GCC)', 'LE HEV', 'GLS', 'GLX', 'DLX', 'BE', 'DLS - STD ROOF', 'CTD', 'BASE', 'SR5 (NON GCC)', '1500', 'GXR TOP DMST', 'GL2', 'STD', 'MID', 'DL', 'LIMITED', 'LE', 'GXR2', 'XLE (NON GCC)', 'HILUX', 'XLI', 'TOP', 'S', 'S TRD SPORT PK', 'GLI', 'STANDARD', 'VXR', 'DLS', 'EX', 'SE', 'ASAD', 'LWB HIGH ROOF', 'XLI MID', 'GR-S', 'BLACK EDITION', 'GXR FMST', 'SL', '1']
  WMI: ['JTM', 'JTF', 'JTG', '2T3', '5TF', '5TB', 'JTE', '3TY', 'JT4', 'MA1', 'MAF', '4T3', '4T1', '2C4', '1D7', 'RKL', 'JT6', 'MH3', '1C6', 'RKT', 'LKL', '1TG', '1C8', 'JH2', 'LA6', 'MR2', 'ZT3', 'MC2', 'JTD', '5TE', 'MR0', 'STF', 'STB']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['RF9EV', 'REREV', 'RMFAP', 'RX12P', 'RFREV', 'RFR3V', 'R6RFV', 'RWRFV', 'RY5F1', 'R1RFV', 'RT341', 'RW5F1', 'RM5F1', 'RJREV', 'R13FV', 'RU5JR', 'RK4DV', 'R43FV', 'RV541', 'RX5GN', 'RU71J', 'RN81A', 'RB71J', 'RD2VF', 'R03FV', 'R2061', 'RU341', 'RT541', 'RV71J', 'R11AK', 'RF4DV', 'RW3FV', 'RC1BG', 'RN50R', 'RV1GP', 'RV581', 'RU541', 'RN82P', 'RV42E', 'RZ5CN', 'RH21B', 'RD7KT', 'RL9HE', 'RMFAW', 'RN93P', 'RD483', 'R1CS9', 'RR7GT', 'RH223', 'R1DSB', 'RN01P', 'RT9F3', 'RT381', 'R3NLT', 'RB23E', 'RX56N', 'RN341', 'RX22G', 'RS12P', 'RMEAP']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,RAV4,4.0,SUV,R,GXR,JTM,GCC,5.0,RF9EV
1,TOYOTA,RAV4,4.0,SUV,R,GXR,JTM,GCC,5.0,RF9EV
2,TOYOTA,RAV4,4.0,SUV,R,EXR,JTM,GCC,5.0,REREV
3,TOYOTA,HIACE,4.0,PANEL VAN,R,GL,JTF,GCC,NaN,RMFAP
4,TOYOTA,HIACE,4.0,PANEL VAN,R,DX,JTG,GCC,5.0,RX12P
...,...,...,...,...,...,...,...,...,...,...
1510,TOYOTA,RAV4,4.0,SUV,R,1,JTM,GCC,NaN,R13FV
1511,TOYOTA,TUNDRA,8.0,PICKUP,R,STD (NON GCC),5TF,NON-GCC,NaN,RV541
1512,TOYOTA,RAV4,4.0,SUV,R,GXR,JTM,GCC,NaN,RF9EV
1513,TOYOTA,RAV4,4.0,SUV,R,XLE,4T3,NON-GCC,NaN,RWRFV
1514,TOYOTA,RAV4,4.0,SUV,R,GXR,JTM,GCC,NaN,RF9EV

====================================================================================================
POS4: X
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['INNOVA', 'SIENNA', 'RAV4', 'HILUX', 'HIACE', 'HIGHLANDER', 'FJ CRUISER', 'STATION', 'RAV 4']
  bodyType: ['MPV', 'SUV', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'STATION', 'MINI BUS', 'CONVERTIBLE', 'MINIVAN']
  trim: ['GL', 'SE', 'XLE (NON GCC)', 'LE (NON GCC)', 'DX', 'XLE', 'GXR', 'LIMITED (NON GCC)', 'SE (NON GCC)', 'STD', 'GL TOP', 'DLX', 'EXR', 'BASE', 'EX', 'GLI TOP LEATHER', 'GRD', 'GLS LOWLINE', 'STD (NON GCC)', 'GLE HEV', '1']
  WMI: ['MHF', '5TD', 'JT3', '1FD', '2T3', 'YAR', 'MHE', 'JTM', 'WV2', 'KMF', 'MFH']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['XX43G', 'XX42G', 'XZ3DC', 'XK3DC', 'XP10V', 'XX426', 'XE4FS', 'XX436', 'XK4DV', 'XRKEC', 'XU9HM', 'XX430', 'XBRCH', 'XAD2K', 'XKS7B', 'XX48G']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,INNOVA,4.0,MPV,X,GL,MHF,GCC,5.0,XX43G
1,TOYOTA,INNOVA,4.0,MPV,X,GL,MHF,GCC,5.0,XX43G
2,TOYOTA,INNOVA,4.0,MPV,X,GL,MHF,GCC,5.0,XX43G
3,TOYOTA,INNOVA,4.0,MPV,X,GL,MHF,GCC,5.0,XX43G
4,TOYOTA,INNOVA,4.0,MPV,X,GL,MHF,GCC,5.0,XX43G
...,...,...,...,...,...,...,...,...,...,...
2232,TOYOTA,INNOVA,4.0,SUV,X,GL,MHF,GCC,NaN,XX43G
2233,TOYOTA,INNOVA,4.0,SUV,X,GL,MHF,GCC,NaN,XX43G
2234,TOYOTA,INNOVA,4.0,SUV,X,GL,MHF,GCC,NaN,XX43G
2235,TOYOTA,INNOVA,4.0,SUV,X,SE,MHF,GCC,NaN,XX42G
2236,TOYOTA,INNOVA,4.0,SUV,X,DX,MHF,GCC,NaN,XX43G

====================================================================================================
POS4: Z
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['SIENNA', 'RAV4', 'HIACE', '86', '4RUNNER', 'FORTUNER', 'GR86', 'HILUX', 'PRIUS', 'SEQUOIA', 'FJ CRUISER', 'HIGHLANDER', 'LAND CRUISER', 'ALTIS', 'ZELAS', 'PRADO', 'ALPHARD', 'COROLLA', 'SICION', 'CAMRY', 'VENZA', 'TOYOTA 4RUNNER', 'RAV 4', '1998', 'RUSH', 'SPINA', 'PREVIA', 'SCION', 'AURION', 'FORERUNNER', 'HI ACE', 'TOYOTA 86']
  bodyType: ['MPV', 'SUV', 'PANEL VAN', 'COUPE', 'PICK UP DOUBLE CAB', 'HATCHBACK', 'STATION', 'SEDAN', 'MINI BUS HIGH ROOF', 'VAN', 'PICK UP SINGLE CAB', 'MINI BUS']
  trim: ['LE (NON GCC)', 'XLE (NON GCC)', 'EX', 'MID', 'STD', 'VX', 'CE (NON GCC)', 'STD (NON GCC)', 'EXR', 'VTX', 'BASE', 'SR5 (NON GCC)', 'LIMITED (NON GCC)', 'TOP', 'DLX', 'GTX', 'LIMITED 4X2', 'LE HEV', 'C (NON GCC)', 'GXR', 'SPORT', 'PLATINUM', 'GT', 'BE', 'GX', 'SR5 4X2', 'SE (NON GCC)', 'LIMITED', 'GL', 'SR5', '1', 'VT', 'GLE HEV', 'PW CL', 'ICONIC', 'EXR HEV', 'SAFARI', 'VXR', 'SE', 'DL', 'DYNAMIC', 'STATION ', 'GR SPORT', 'LIMITED 4X4', 'ADVENTURE', 'GLE HEV BLACK EDITION', 'GLE', 'CE', 'XLI', 'AT', 'XLE', 'G', 'PLATINUM LUXURY 4X4', 'TRIM', 'NON GCC', 'GLX', 'VX MID', 'SR5 4X4', 'DLS', '4X4', 'EXCELLENCE', 'MPV', 'S', 'LE', 'FR-S (NON GCC)', 'DX', 'VAN', 'EXTREME', 'HYBRID (NON GCC)']
  WMI: ['5TD', 'JTD', 'JTM', 'JT4', 'JF1', '2T3', 'JTE', 'MHF', 'WV1', 'U8Q', 'JT0', '2FU', 'JHH', 'STD', '4T3', 'WMW', 'MR1', 'KMF', 'JTL', 'WDD', 'KLI', 'JHM', '6TD', 'SMV', '1G1', 'JS2', 'L3A', 'JTA', '1GJ', '5T0']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['ZK22C', 'ZA23C', 'ZK23C', 'ZF9EV', 'ZK31V', 'Z13FV', 'ZA119', 'ZFREV', 'ZN11B', 'ZA22C', 'ZF4DV', 'ZN12B', 'ZR119', 'ZK3DC', 'ZNAA1', 'ZD33V', 'ZK4DV', 'ZU14R', 'ZX69G', 'ZNBB1', 'ZBB2K', 'ZD31V', 'ZN12A', 'ZN3EU', 'ZY68A', 'ZA29C', 'ZK33V', 'ZF33V', 'Z23FV', 'ZZRFH', 'ZZ3DC', 'ZN128', 'ZA230', 'ZA113', 'ZY67A', 'ZK34V', 'ZY64A', 'ZN11A', 'ZT14R', 'ZD32V', 'ZKRFH', 'ZCKF5', 'ZU5JR', 'ZN23B', 'ZNBC1', 'ZT38A', 'ZY0CC', 'ZCP2F', 'ZE32V', 'ZU11F', 'ZY5G1', 'ZNBF1', 'ZF13C', 'ZF31V', 'ZU17R', 'ZA3BB', 'ZZRAH', 'ZK29C', 'ZNBE1', 'ZC3C5', 'ZCK1H', 'ZF19C', 'ZF35V', 'ZNBG1', 'ZSZ7J', 'ZCP2H', 'ZE4FE', 'ZF4CB', 'ZARAH', 'ZD35V', 'ZA5CS', 'ZK32V', 'ZT17R', 'ZE287', 'ZCZ7J', 'ZER2D', 'ZU4BF', 'ZCS7J', 'ZCN1F', 'ZSZ7K', 'ZC5ST', 'ZK4CC', 'ZE9EV', 'ZE11A', 'ZT34A', 'ZNAE1', 'ZA3EH', 'ZC8B2', 'Z1CK3', 'ZBB7H', 'ZCL2H', 'Z78FG', 'Z4119', 'ZN23A', 'ZN12E', 'Z1RFV']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,SIENNA,6.0,MPV,Z,LE (NON GCC),5TD,GCC,5.0,ZK22C
1,TOYOTA,SIENNA,6.0,MPV,Z,XLE (NON GCC),5TD,GCC,5.0,ZA23C
2,TOYOTA,SIENNA,6.0,MPV,Z,XLE (NON GCC),5TD,GCC,5.0,ZA23C
3,TOYOTA,SIENNA,6.0,MPV,Z,LE (NON GCC),5TD,GCC,5.0,ZK23C
4,TOYOTA,RAV4,4.0,SUV,Z,EX,JTD,GCC,5.0,ZF9EV
...,...,...,...,...,...,...,...,...,...,...
6369,TOYOTA,SIENNA,6.0,SUV,Z,CE (NON GCC),5TD,NON-GCC,NaN,ZK23C
6370,TOYOTA,TOYOTA 86,4.0,COUPE,Z,GTX,JF1,GCC,NaN,ZN12A
6371,TOYOTA,SIENNA,6.0,SUV,Z,CE (NON GCC),5TD,NON-GCC,NaN,ZK23C
6372,TOYOTA,SIENNA,6.0,SUV,Z,1,5TD,NON-GCC,NaN,ZA23C
6373,TOYOTA,RAV4,4.0,SUV,Z,EX,JTD,GCC,NaN,Z13FV

====================================================================================================
POS4: W
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'RAV4', 'TUNDRA', 'HILUX', 'YARIS', 'HIACE', 'COROLLA', 'TAKOMA', 'SIERRA', 'CAMRY', 'TUNDRA (PICK UP)', 'TAKOMA PICK UP CARGO', 'SIENNA']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'PICK UP', 'PICK UP SINGLE CAB', 'SEDAN', 'PANEL VAN', 'PICKUP', 'COUPE/CABRIOLET', 'MPV', 'CARGO VAN', 'WINDOW VAN', 'HALF PANEL VAN', 'MINI BUS', 'COUPE', 'HATCHBACK']
  trim: ['SR5 (NON GCC)', 'LE HEV', 'LE', 'VX', 'EXR', 'EX', 'GX', 'SR', 'XLE', 'BE', 'STD (NON GCC)', 'DLX', 'MID', 'BASE', 'CREWMAX CAPSTONE (NON GCC)', '1794 EDITION (NON GCC)', 'E', 'GL', 'GLI', 'DL', 'DLS', 'GXR', 'STD', 'XLI', 'GLI TOP', 'A', 'DLS - STD ROOF', 'DX', 'GLX', 'ADVENTURE', 'PW CL', 'S', 'XLE (NON GCC)', 'S TRD AERO PK', 'SGLX']
  WMI: ['4TA', '2T3', 'JTD', 'WWW', 'JTM', '5TF', '5TE', 'KNC', 'JM3', 'KNF', 'LCF', 'WD4', 'KMH', 'LZZ', 'KMJ', 'LSJ', '55S', 'KMF', '1GT', 'WDD', '1GC', 'WV2', '1FD']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['WN72N', 'W1RFV', 'W13FV', 'WF9EV', 'WFREV', 'W8888', 'WA5DB', 'WJ272', 'WG725', 'WXZ74', 'WF4DV', 'WA5EC', 'W6FY1', 'WK4DV', 'WJZ74', 'WG3E1', 'WG81R', 'WADG4', 'WJZ76', 'WH813', 'WJX74', 'WA37R', 'WJX76', 'WC5DB', 'W74U3', 'WF8HB', 'WAH7J', 'WJ4W9', 'W8X7K', 'WE23E', 'WIRFV', 'W78CG', 'WM72N', 'W13EV', 'WF4CB', 'WGAFP', 'WBC7H', 'WC5EC', 'WE3FN', 'WJ276', 'WF4JB', 'WJZ72', 'W9235']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,W,SR5 (NON GCC),4TA,GCC,4.0,WN72N
1,TOYOTA,RAV4,4.0,SUV,W,LE HEV,2T3,GCC,5.0,W1RFV
2,TOYOTA,RAV4,4.0,SUV,W,LE,JTD,GCC,5.0,W13FV
3,TOYOTA,RAV4,4.0,SUV,W,VX,JTD,GCC,5.0,WF9EV
4,TOYOTA,RAV4,4.0,SUV,W,VX,JTD,GCC,5.0,WF9EV
...,...,...,...,...,...,...,...,...,...,...
948,TOYOTA,RAV4,4.0,SUV,W,VX,JTD,GCC,NaN,W13FV
949,TOYOTA,RAV4,4.0,SUV,W,GXR,JTD,GCC,NaN,W13FV
950,TOYOTA,RAV4,4.0,SUV,W,VX,JTD,GCC,NaN,WF9EV
951,TOYOTA,RAV4,4.0,SUV,W,VX,JTD,GCC,NaN,WF9EV
952,TOYOTA,RAV4,4.0,SUV,W,EX,JTD,GCC,NaN,W13FV

====================================================================================================
POS4: L
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER PICK UP', 'LAND CRUISER', 'LAND CRUISER PICKUP 70', 'HIACE', 'TACOMA', 'HIGHLANDER', 'TUNDRA', 'CAMRY', 'HILUX', 'TOYOTA LAND CRUISER', 'PRIUS', 'LAND CRUISER PICK UP CARGO', 'TOYOTA', '25 LP SC4X44.0L MT', 'TAKOMA', 'LAND CRUISER SINGLE-CABIN PICK', 'RAV4', '4RUNNER', 'INNOVA', 'لاند كروزر', '25 LP SC 4X4 P4.0 MT', 'PREVIA', 'C-HR', 'PICK UP CABIN', 'LAND CRUISER/PICK UP CARGO', 'TOYOTA TACOMA', 'CHR', 'LAND CRUISER/STD EX PICKUP', 'LAND CRUISER PICKUP', '26 LP SC 4X4 P4.0L AT', 'LAND CRUISER - PICK UP CARGO', 'PICKUP', 'PRADO', 'CAMRY HYBRID']
  bodyType: ['PICK UP DOUBLE CAB', 'PICK UP', 'SUV', 'PICK UP SINGLE CAB', 'PICKUP', 'MINI BUS HIGH ROOF', 'VAN', 'CARGO VAN', 'PANEL VAN', 'SEDAN', 'PANEL VAN HIGH ROOF', 'BUS', 'HATCHBACK', 'MPV', 'LIGHT VEHICLE', 'MINI BUS', 'STATION', 'PICK UP DOUBLE CABIN', 'REGULAR CAB']
  trim: ['GXR', 'STD', 'VX', 'LX', 'LX AC PWR OPT', 'LX WINCH', 'GL', 'GX', 'SC', 'VXR', 'GLS', 'EXR', 'DLS - STD ROOF', 'ST', 'CREWMAX CAPSTONE (NON GCC)', 'SR5 (NON GCC)', 'GXR TOP', '1794 EDITION (NON GCC)', 'GLX', 'SE', 'DLX', 'STD (NON GCC)', '1', 'STD AC', 'XLT', 'GXR FMST', 'GLE HEV BLACK EDITION', 'SR (NON GCC)', 'SR', 'SAFARI', 'GLE HEV', 'GXR TOP FMST', 'ECO', 'HARD TOP', '1500', 'G', 'GXR TOP DMST', 'X', '6', 'SPORT', 'LAND CRUSIER', 'XE 4WD', 'VXR TOP LTH', 'STATION1', 'VXR MID', 'LE HEV', 'PIKUP', 'GXR MID', 'PREMIUM', 'VXR BASE', 'PICKUP', 'GXR SOD D/AC AW', 'XTREME', 'AUTOMATIC', '60TH', 'DLS HIGH ROOF', '1500 CREWCAB SLE Z71', 'LTZ', 'DLS', 'LE (NON GCC)', 'A', 'LX WIDE TYRES', 'TRIM', 'PICKUP ', 'GXR GT', 'BASE', 'PICK UP', '4', 'STANDER', 'GLE', 'SEDAN', 'DLX TOP', '10TH VICTORY EDITION', 'GXR MID XTREME', 'EX', 'STANDARD', 'BLACK EDITION', 'SE T2', 'LE PLATINUM CITY', 'LIMITED', 'TX', 'GXR MID 60TH ANNIVERSARY', 'SLT', '2', 'GR-S', 'SGLX', 'DX', 'S', 'PREMIER', 'VXR TOP', 'TRD SPORT', 'CREWMAX CAPSTONE (NO', '1794 EDITION (NON GC']
  WMI: ['JIF', 'JTF', 'JTE', '5TE', '5TD', '5TF', '3TM', '4T1', 'JHH', 'JTD', '3TY', '4T3', 'SAL', 'NMT', 'JMY', 'VF3', 'JAM', 'STF', 'JTJ']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['LU73J', 'LJ73J', 'LJ71J', 'LMFCP', 'LV73J', 'LU42N', 'LB3CH', 'LU71J', 'LA5DB', 'LU4EN', 'LA5AB', 'L11AK', 'LMFCW', 'LB71J', 'LA3AH', 'LCN1F', 'LA5GD', 'LU521', 'L9RFU', 'LA5DA', 'LC5LN', 'LB5JN', 'LA5BC', 'LJ733', 'LM5F1', 'LR73J', 'LWRFV', 'LU5JR', 'LU5F1', 'L83CH', 'LSAAE', 'LU733', 'LT521', 'LA5EC', 'LY3FX', 'LMSF1', 'L9MFU', 'LDHAD', 'LYV65', 'LASDB', 'L35GY', 'LP345', 'LAAA4', 'LZRBH', 'LJ731', 'L373J', 'LV71J', 'LBACX', 'LV521']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP DOUBLE CAB,L,GXR,JIF,GCC,4.0,LU73J
1,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP,L,STD,JTF,GCC,2.0,LJ73J
2,TOYOTA,LAND CRUISER,6.0,SUV,L,VX,JTF,GCC,5.0,LJ71J
3,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP DOUBLE CAB,L,GXR,JTF,GCC,5.0,LU73J
4,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP DOUBLE CAB,L,GXR,JTF,GCC,4.0,LU73J
...,...,...,...,...,...,...,...,...,...,...
2562,TOYOTA,HIGHLANDER,4.0,SUV,L,VXR,5TD,GCC,NaN,LB3CH
2563,TOYOTA,HIGHLANDER,4.0,SUV,L,VXR,5TD,GCC,NaN,LB3CH
2564,TOYOTA,HIGHLANDER,4.0,SUV,L,VXR,5TD,GCC,NaN,LB3CH
2565,TOYOTA,HIGHLANDER,4.0,SUV,L,VXR,5TD,GCC,NaN,LB3CH
2566,TOYOTA,TUNDRA,6.0,PICKUP,L,1794 EDITION (NON GC,5TF,NON-GCC,NaN,LA5DB

====================================================================================================
POS4: 5
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'COROLLA', 'TERCEL', 'RAV4', 'YARIS', 'AVALON', 'HIACE', 'COROLLA 1.5', 'TOYOTA COROLLA', 'COROLLA 1.3', 'SIENNA', 'ALTIS', 'TACOMA', 'LAND CRUISER', 'كورولا 1.3', 'CROWN V', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'HATCHBACK', 'HALF PANEL VAN', 'MINI BUS', 'MPV', 'BUS', 'SALOON', 'PICK UP DOUBLE CAB', 'MINI BUS HIGH ROOF']
  trim: ['STD', 'XLI', 'XLI MID', 'EXR', 'BASE', 'LIMITED', 'GL', 'LE HEV', 'GXR', 'S', 'EX', 'GLI', 'LE', 'GLS', 'SR5 (NON GCC)', 'GLX', 'X', 'SE+', 'GXR HEV']
  WMI: ['6T1', 'ZE1', 'JTB', 'JTD', 'JWT', 'JCB', 'JT6', 'JTM', '2T3', 'ACV', '4T2', 'JT8', 'VS5', '454', 'UTD', '3TY', 'AVV', 'FJ7', 'WMA', 'CE1']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['53SK2', '51303', '53EEB', '53AEB', '53EL5', '5D3BV', '53AEA', '53XK2', '543BV', '53SK1', '51488', '59695', '51390', '5AFKG', '5X23P', '50954', '5C3AV', '5WRFV', '543AV', '53EEA', '51500', '51116', '535K2', '51067', '53XH1', '50012', '50189', '51113', '50258', '56N8U', '50602', '50185', '51611', '50524', '51622', '51211', '53AFB', '50470', '50237', '5DDDD', '51573', '534K2', '50975', '51908', '50637', '51102', '50333', '50018', '50812', '51426', '50287', '50531', '525AN', '51940', '51267', '53EE8', '50391', '50500', '50229', '50061', '56EZZ', '51680', '50617', '50671', '50873', '51149', '50017', '50504', '51382', '51452', '51189', '50501', '53JSF', '50296', '51658', '50090', '51972', '51109', '50479']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,CAMRY,4.0,SEDAN,5,STD,6T1,GCC,4.0,53SK2
1,TOYOTA,CAMRY,4.0,SEDAN,5,XLI,ZE1,NON-GCC,NaN,51303
2,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,JTB,GCC,4.0,53EEB
3,TOYOTA,CAMRY,4.0,SEDAN,5,STD,6T1,GCC,4.0,53SK2
4,TOYOTA,COROLLA,4.0,SEDAN,5,XLI MID,JTB,GCC,4.0,53AEB
...,...,...,...,...,...,...,...,...,...,...
623,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,JTB,NON-GCC,NaN,53AEB
624,TOYOTA,RAV4,4.0,SUV,5,EX,JTD,GCC,NaN,543BV
625,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,JTB,GCC,NaN,53EEB
626,TOYOTA,RAV4,4.0,SUV,5,EX,JTD,GCC,NaN,543BV
627,TOYOTA,CAMRY HYBRID,4.0,SEDAN,5,STD,6T1,GCC,NaN,53SK2

====================================================================================================
POS4: G
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['PREVIA', 'CAMRY', 'INNOVA', 'RAV4', 'HILUX', 'ALPHARD', 'HIGHLANDER', 'TUNDRA', 'COROLLA', 'TACOMA', 'FORTUNER', 'PRADO', '4RUNNER', 'AVALON', 'HIACE', 'LAND CRUISER', 'SIENNA', 'CAMRY HYBRID']
  bodyType: ['MPV', 'SEDAN', 'SUV', 'PICK UP DOUBLE CAB', 'MINI BUS HIGH ROOF', 'MINI BUS', 'PANEL VAN', 'STATION', 'PICK UP SINGLE CAB']
  trim: ['SE', 'DLX', 'GL', 'S', 'SE+', 'EX', 'PW CL', 'LIMITED', 'STD', 'GLE-X HEV 40TH ANNIV', 'XLE', 'STD (NON GCC)', 'GXR', 'XLI', 'FABRIC', 'SR5 (NON GCC)', 'GLE HEV', 'LE STD', 'LE HEV', 'LE', 'TOP', 'EXR', 'TOURING', 'GLE', 'BASE', 'DX', 'LE (NON GCC)', 'G', 'GLI', 'GLI TOP', 'GL LTH', 'GRANDE HEV 40TH ANNIV', 'VXR', 'TAXI', 'HEV']
  WMI: ['JTN', 'JTE', '4T1', 'MHF', 'KMF', 'JT3', '5TD', '5TF', 'YS2', 'JT2', 'MR0', 'ITN', '2T3', 'LSK', 'JTM', 'GGG', 'JD2', '5XX', 'JS1', '3TM', 'VF3', '1GJ', 'LMX', 'JMY', 'WDD', 'STD', 'MHP']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['GE52M', 'GD34M', 'GD52M', 'G11AK', 'GX8EM', 'GD32M', 'GE17F', 'GD54M', 'GH20V', 'GK3DH', 'GP10V', 'GZRBH', 'GW5F1', 'GD20V', 'G6X40', 'GBRCH', 'GK13E', 'GY5F1', 'GZ5AN', 'G11BK', 'GZ3DH', 'GK26H', 'GS54M', 'GX8CD', 'GN87R', 'GA17F', 'G1RFV', 'GP21A', 'G4AC1', 'GN86R', 'GZ1FB', 'GZRAH', 'G4X20', 'GGG56', 'GU09J', 'GJ211', 'G31AK', 'G5GC1', 'GU4L3', 'GX72A', 'GARAH', 'GBKFW', 'GG25K', 'GD21A', 'G14DA', 'G622K', 'GNP03', 'GK12E', 'GSKFC', 'G4BC1', 'GF4JB', 'GR4A6', 'GES2M', 'GA17E', 'GF46X', 'GJKFW', 'GA17H', 'GXSEM', 'GRKEC', 'G13FV']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,PREVIA,4.0,MPV,G,SE,JTN,GCC,5.0,GE52M
1,TOYOTA,PREVIA,4.0,MPV,G,DLX,JTE,GCC,5.0,GD34M
2,TOYOTA,PREVIA,4.0,MPV,G,DLX,JTN,GCC,5.0,GE52M
3,TOYOTA,PREVIA,6.0,MPV,G,GL,JTE,GCC,5.0,GD52M
4,TOYOTA,CAMRY,4.0,SEDAN,G,SE,4T1,GCC,4.0,G11AK
...,...,...,...,...,...,...,...,...,...,...
2545,TOYOTA,CAMRY HYBRID,4.0,SEDAN,G,SE,4T1,GCC,NaN,G11AK
2546,TOYOTA,PREVIA,4.0,SUV,G,DLX,JTE,GCC,NaN,GD52M
2547,TOYOTA,PREVIA,4.0,SUV,G,S,JTN,GCC,NaN,GE52M
2548,TOYOTA,PREVIA,4.0,SUV,G,SE,JTN,GCC,NaN,GE52M
2549,TOYOTA,PREVIA,4.0,SUV,G,GL,JTE,NON-GCC,NaN,GD52M

====================================================================================================
POS4: U
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'TUNDRA', 'HILUX', 'CAMRY', 'HIACE', 'LAND CRUISER', 'DAINA', '4RUNNER', 'DYNA', 'PRADO', 'COROLLA', 'COASTER', 'PICKUP', 'DYNA VAN CARGO', 'TAKOMA']
  bodyType: ['PICKUP', 'PICK UP DOUBLE CAB', 'PICK UP', 'PICK UP SINGLE CAB', 'CARAVAN', 'SEDAN', 'PANEL VAN', 'SUV', 'BUS', 'TRUCK', 'VAN']
  trim: ['STD', 'STD (NON GCC)', 'SR5 (NON GCC)', 'DLX', 'GL', 'GLX', 'GX', 'LIMITED', 'PICKUP', 'VX', 'DL', 'EXR', 'LWB', 'S', 'SR']
  WMI: ['5TF', '5TE', '4TA', 'JHG', 'STF', 'MM7', 'JHF', 'JHH', 'JD4', 'JAC', 'JTE', 'WCY', 'JNC', 'KL5', 'JTM', 'JT4']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['UX4EN', 'UY5F1', 'UW5F1', 'UU4EN', 'UX42N', 'UM5F1', 'UN53B', 'UF117', 'UR4DA', 'UN236', 'UL11H', 'UCN1H', 'UV182', 'UN202', 'UWSF1', 'UBS25', 'UYSF1', 'UU5JR', 'UU42N', 'U4545', 'UF11H', 'UY6F1', 'UAD1H', 'UZD1H', 'UCK1H', 'UFJ1H', 'UN246', 'UN346', 'UN316', 'UK42A', 'UN41B', 'UY0FJ', 'UN24D', 'UYSPI', 'UN206', 'UY5E1', 'UFJ17']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,TACOMA,6.0,PICKUP,U,STD,5TF,GCC,NaN,UX4EN
1,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,U,STD (NON GCC),5TF,GCC,4.0,UY5F1
2,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,U,STD (NON GCC),5TF,GCC,4.0,UY5F1
3,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,U,STD (NON GCC),5TF,GCC,4.0,UY5F1
4,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,U,STD (NON GCC),5TF,GCC,4.0,UW5F1
...,...,...,...,...,...,...,...,...,...,...
890,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),5TF,NON-GCC,NaN,UY5F1
891,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),5TF,NON-GCC,NaN,UY5F1
892,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),5TF,NON-GCC,NaN,UY5F1
893,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),5TF,NON-GCC,NaN,UY5F1
894,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),5TF,NON-GCC,NaN,UY5F1

====================================================================================================
POS4: 6
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'RAV4', 'COROLLA', 'PREVIA', 'HIACE', 'CELICA', 'YARIS', '4RUNNER', 'LAND CRUISER']
  bodyType: ['PICK UP SINGLE CAB', 'SUV', 'SEDAN', 'MPV', 'MINI BUS HIGH ROOF', 'PICK UP DOUBLE CAB', 'COUPE', 'PANEL VAN', 'MINI BUS', 'STATION']
  trim: ['DLX', 'PW CL', 'XLI', 'XLI MID', 'S', 'GL', 'XLI TOP', 'STD', 'FLEET', 'DLS - STD ROOF', 'LE', 'BASE', 'GX', 'E', 'LIMITED']
  WMI: ['WDB', 'JTE', 'JTB', 'JTN', 'LJ1', 'WD8', 'RK4', 'YN8', 'JTD', 'LFZ', 'JT3', 'VF3']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['65204', '6H20V', '64AEB', '6D32M', '6E52M', '65203', '6AE3C', '65553', '65213', '6D52M', '65620', '65933', '64STL', '61524', '65200', '65651', '60023', '65805', '65934', '6W923', '6D54M', '65610', '66B3D', '63AL5', '60019', '6N87R', '6JKFW', '63AL4', '64EEB', '65910', '62101']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,WDB,GCC,2.0,65204
1,TOYOTA,RAV4,4.0,SUV,6,PW CL,JTE,GCC,3.0,6H20V
2,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,JTB,GCC,4.0,64AEB
3,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,JTB,GCC,4.0,64AEB
4,TOYOTA,PREVIA,4.0,MPV,6,DLX,JTE,GCC,5.0,6D32M
5,TOYOTA,COROLLA,4.0,SEDAN,6,XLI MID,JTB,GCC,4.0,64AEB
6,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
7,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,WDB,GCC,2.0,65203
8,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
9,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,6,GL,LJ1,GCC,4.0,6AE3C
10,TOYOTA,COROLLA,4.0,SEDAN,6,XLI TOP,WDB,GCC,NaN,65553
11,TOYOTA,COROLLA,4.0,SEDAN,6,XLI MID,JTB,GCC,4.0,64AEB
12,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,6,DLX,WDB,GCC,4.0,65213
13,TOYOTA,PREVIA,4.0,MPV,6,DLX,JTE,GCC,5.0,6D52M
14,TOYOTA,PREVIA,4.0,MPV,6,STD,WDB,GCC,5.0,65620
15,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
16,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,6,DLX,WD8,GCC,4.0,65933
17,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
18,TOYOTA,CELICA,4.0,COUPE,6,STD,JTB,GCC,2.0,64STL
19,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,WDB,GCC,2.0,61524
20,TOYOTA,HIACE,4.0,PANEL VAN,6,STD,WDB,GCC,5.0,65200
21,TOYOTA,COROLLA,4.0,SEDAN,6,S,RK4,GCC,NaN,65651
22,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
23,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
24,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,YN8,GCC,NaN,60023
25,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,WDB,GCC,NaN,65805
26,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
27,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,WDB,GCC,2.0,65934
28,TOYOTA,YARIS,4.0,SEDAN,6,FLEET,JTD,GCC,4.0,6W923
29,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,JTB,GCC,4.0,64AEB
30,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
31,TOYOTA,RAV4,4.0,SUV,6,PW CL,JTE,GCC,3.0,6H20V
32,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,JTB,GCC,4.0,64AEB
33,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,JTB,GCC,4.0,64AEB
34,TOYOTA,PREVIA,6.0,MPV,6,GL,JTE,GCC,5.0,6D54M
35,TOYOTA,RAV4,4.0,SUV,6,STD,WDB,GCC,NaN,65610
36,TOYOTA,HIACE,4.0,MINI BUS,6,DLS - STD ROOF,LJ1,GCC,NaN,66B3D
37,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,JTB,GCC,4.0,64AEB
38,TOYOTA,RAV4,4.0,SUV,6,LE,LFZ,NON-GCC,5.0,63AL5
39,TOYOTA,RAV4,4.0,SUV,6,LE,LFZ,NON-GCC,5.0,63AL5
40,TOYOTA,PREVIA,4.0,MPV,6,DLX,JTE,GCC,5.0,6D32M
41,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,YN8,GCC,NaN,60019
42,TOYOTA,4RUNNER,6.0,SUV,6,STD,JT3,GCC,5.0,6N87R
43,TOYOTA,PREVIA,4.0,MPV,6,S,JTN,GCC,5.0,6E52M
44,TOYOTA,RAV4,4.0,SUV,6,BASE,VF3,GCC,5.0,6JKFW
45,TOYOTA,PREVIA,6.0,MPV,6,GL,JTN,GCC,5.0,6E52M
46,TOYOTA,PREVIA,4.0,STATION,6,DLX,JTE,GCC,NaN,6D52M
47,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,JTB,GCC,4.0,64AEB
48,TOYOTA,COROLLA,4.0,SEDAN,6,XLI TOP,WDB,NON-GCC,NaN,65553
49,TOYOTA,LAND CRUISER,6.0,SUV,6,GX,LFZ,GCC,NaN,63AL4
50,TOYOTA,YARIS,4.0,SEDAN,6,E,LJ1,GCC,NaN,66B3D
51,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,JTB,GCC,4.0,64EEB
52,TOYOTA,COROLLA,4.0,SEDAN,6,LIMITED,WDB,NON-GCC,NaN,65910
53,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,STD,WDB,GCC,NaN,62101

====================================================================================================
POS4: S
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'CAMRY', 'TACOMA', 'HILUX', 'COROLLA', 'TUNDRA', 'YARIS', 'LAND CRUISER 70', 'MR 2', 'RAV4', 'LAND CRUISER', 'U7']
  bodyType: ['MINI BUS', 'MINI BUS HIGH ROOF', 'SEDAN', 'HALF PANEL VAN', 'BUS', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'PANEL VAN HIGH ROOF', 'VAN', 'PICK UP SINGLE CAB', 'PICK UP', 'MINI BUS SEMI HIGH ROOF', 'SUV', 'COUPE', 'MPV', 'PICKUP']
  trim: ['GL', 'GLX', 'GLE HEV', 'DX', 'SE', 'SR5 (NON GCC)', 'DLX', 'GLE-X HEV 40TH ANNIV', 'STD (NON GCC)', 'STD', 'LE HEV', 'XLI EXECUTIVE', 'GLS', 'LE', 'DX H/R W/B', 'SE+', 'GLI HEV', 'DL', 'XLI', 'GLI', 'GRANDE HEV 40TH ANNIV', 'HT SLWB', 'GLE', 'GRD', 'S', 'MID', 'GL DECKLESS', 'BASE', 'DLS', 'LIMITED', 'GXR TOP', 'DLS - STD ROOF']
  WMI: ['JTG', 'JT2', '4T1', '5TF', '3TY', 'JM3', 'JTF', 'JTD', '4TA', '5YF', 'KNC', '5TE', 'KNF', '1FT', 'MHF', '1GN', 'KMH', 'LHP', 'WDB', '1C6', 'JH2', 'JHD', 'LKL', 'JMY', 'RF5', 'SKF']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['SX22P', 'SK12E', 'SX23P', 'S11AK', 'SZ5AN', 'SX5EN', 'SL35E', 'SMFAP', 'SK12W', 'S4MCE', 'SN92N', 'SE014', 'SM92N', 'S4RCE', 'SJZ74', 'SD35E', 'SS23P', 'SV541', 'STZ74', 'SS3EL', 'ST9F3', 'SK8KD', 'SK11E', 'SW21M', 'SE034', 'SD011', 'SHX74', 'SK12C', 'S31AK', 'S11BK', 'SJ8IV', 'SFABD', 'SK75F', 'SRFJT', 'SC87C', 'SD911', 'SS1EK', 'SS22P', 'SBAS3', 'SRCSL', 'S71T0', 'SK12F', 'SY5F1', 'SC79M', 'ST541', 'SJN3B']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,MINI BUS,S,GL,JTG,GCC,4.0,SX22P
1,TOYOTA,HIACE,4.0,MINI BUS,S,GL,JTG,GCC,5.0,SX22P
2,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,S,GLX,JTG,GCC,4.0,SX22P
3,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,S,GLX,JTG,GCC,4.0,SX22P
4,TOYOTA,CAMRY,4.0,SEDAN,S,GLE HEV,JT2,GCC,4.0,SK12E
...,...,...,...,...,...,...,...,...,...,...
658,TOYOTA,HIACE,4.0,MINI BUS,S,GL,JTG,GCC,4.0,SX23P
659,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,S,GLX,JTG,GCC,4.0,SX22P
660,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,S,GLX,JTG,GCC,4.0,SX22P
661,TOYOTA,TACOMA,6.0,PICKUP,S,SR5 (NON GCC),5TF,NON-GCC,NaN,SZ5AN
662,TOYOTA,COROLLA,4.0,SEDAN,S,STD (NON GCC),JTD,NON-GCC,NaN,S4MCE

====================================================================================================
POS4: 3
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'CAMRY', 'DAINA', 'COROLLA', 'HIACE', 'LAND CRUISER PICK UP', 'FORTUNER', 'DYNA', 'هايلوكس']
  bodyType: ['PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'SEDAN', 'PICKUP', 'PICK UP', 'MINI BUS', 'SUV']
  trim: ['DLX', 'STD', 'SE+', 'STANDDARD', '1500', 'GLX', 'XLI MID', 'MID', 'TOP', '1', 'XLI', 'BASE', 'GL', 'S', 'SED', 'GLI', 'LE', 'SE', 'LX']
  WMI: ['JTB', 'MAT', 'MD6', 'JTD', 'UAE', 'RN1', '010', '4T1', 'XWB', 'YBL', 'JT8', 'K20']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['31UNE', '33UNG', '33YN8', '33UNE', '31UJ7', '31YN8', '38122', '37418', '38132', '32BUM', '37DE7', '33RN8', '3R22E', '3S011', '35000', '31UNG', '31RN8', '303H6', '3G22K', '3K32E', '3546F', '38BS1', '3B007', '33RNA']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,JTB,GCC,2.0,31UNE
1,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,JTB,GCC,2.0,33UNG
2,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,STD,JTB,GCC,2.0,31UNE
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,JTB,GCC,4.0,33YN8
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,STD,JTB,GCC,2.0,33UNE
...,...,...,...,...,...,...,...,...,...,...
346,TOYOTA,HILUX,4.0,PICKUP,3,DLX,JTB,GCC,NaN,33UNE
347,TOYOTA,HILUX,4.0,PICKUP,3,STD,JTB,GCC,NaN,31UNE
348,TOYOTA,HILUX,4.0,PICKUP,3,STD,JTB,GCC,NaN,33RNA
349,TOYOTA,HILUX,4.0,PICKUP,3,DLX,JTB,GCC,NaN,31UNE
350,TOYOTA,LAND CRUISER PICK UP,4.0,PICKUP,3,LX,JTB,GCC,NaN,31UJ7

====================================================================================================
POS4: 7
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'COROLLA', 'CAMRY', 'HIACE', 'HILUX', 'RUSH', 'MR2', '900', 'COASTER', 'CAMRY HYBRID']
  bodyType: ['SUV', 'SEDAN', 'PANEL VAN', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'COUPE', 'WINDOW VAN', 'STATION', 'BUS']
  trim: ['GXR', 'XLI', 'STD', 'XLI MID', 'EX', 'GL', 'DL', 'LE', 'XLI TOP', 'DLX', 'GLI', 'DX', 'ST', 'STD (NON GCC)']
  WMI: ['JTB', '6T1', 'VF3', 'KL7', 'L6T', 'VF7', 'LFZ', 'CM8', 'JT1', 'MAT']
  regionalSpec: ['GCC']
  VDS: ['72SC1', '71SC1', '72AEB', '72EEB', '72SK2', '72SK1', '7JNFU', '7LHEP', '72AEA', '7FNFU', '7ENFU', '72EEA', '79END', '79YND', '7ANFU', '7CNFU', '73FM4', '7KE43', '75106']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,RAV4,4.0,SUV,7,GXR,JTB,GCC,5.0,72SC1
1,TOYOTA,RAV4,4.0,SUV,7,GXR,JTB,GCC,5.0,71SC1
2,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,JTB,GCC,4.0,72AEB
3,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,JTB,GCC,4.0,72AEB
4,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,JTB,GCC,4.0,72EEB
...,...,...,...,...,...,...,...,...,...,...
209,TOYOTA,RAV4,4.0,SUV,7,GXR,JTB,GCC,5.0,72SC1
210,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,JTB,GCC,4.0,72EEB
211,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,JTB,GCC,4.0,72AEB
212,TOYOTA,CAMRY,4.0,SEDAN,7,XLI,6T1,GCC,4.0,72SK2
213,TOYOTA,CAMRY HYBRID,4.0,SEDAN,7,STD,6T1,GCC,NaN,72SK2

====================================================================================================
POS4: 1
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'COROLLA', 'HILUX', 'RAV 4', 'T 300', 'TUNDRA', 'FLTRXS', 'AVALON', 'PRADO', 'YARIS', 'CAMRY', 'RUSH', 'CROWN', 'HIACE', 'WISH', 'RAV4', 'PREVIA', 'FLHTK', 'STANZA', 'KING LONG PASSENGER', 'VELOZ', 'INNOVA', '2008', 'LAND CRUISER PRADO']
  bodyType: ['SUV', 'SEDAN', 'PICK UP DOUBLE CAB', 'STATION', 'MOTORCYCLE', 'HATCHBACK', 'BUS', 'MPV', 'PANEL VAN', 'PANEL VAN HIGH ROOF', 'PICKUP', 'MINI BUS', 'PICK UP SINGLE CAB']
  trim: ['GXR', 'XLI MID', 'STD', 'XLI', 'GX', 'DLX', 'SV', 'ADVENTURE', 'VX', 'EXR', 'STD (NON GCC)', 'DLS', 'GLI', 'DL', 'PREMIER', 'LIMITED', 'LE', 'PRADO', 'GLX', 'GLE', 'AUTOMATIC', 'MPV', 'S', 'MID', 'SE', '1', 'GLS', 'GL2', 'DLX TOP', 'BASE', 'PICK UP', 'E', 'DX', 'EX', 'H', 'XLI TOP', 'XLT', 'GL TOP']
  WMI: ['JTB', 'ANE', 'ZSG', 'LA7', 'LZC', 'LHA', 'LTA', 'ZRE', 'LKL', 'ZZE', 'LJ1', '5HD', 'IG1', 'WYU', 'NSP', 'N1N', 'JZS', 'SXV', '1HD', 'LGF', 'KNR', 'LA6', 'SXA', '1N1', 'JT8', 'LAZ', 'NCP', 'W11', '6TB', 'WDB', 'UZS', 'W01', 'EP9', 'D02', 'VZE', 'L11', '111', 'LFB', 'STM']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['11UJ8', '12001', '11WJA', '10031', '11UJA', '1CUG3', '11600', '1215C', '12007', '1201D', '11VJ9', '12H2P', '14244', '1AAA6', '14270', '1KFCD', '1KBBC', '12006', '1KTP4', '14583', '14545', '15140', '1N1EN', '15100', '17100', '10701', '12005', '1YYK2', '1202F', '1HBJW', '12004', '1L1HE', '17255', '14252', '11UJ9', '1BAA3', '11005', '17257', '11111', '11AC1', '1CU83', '15070', '1E33K', '12402', '1KBBD', '10030', '1FHPC', '1779D', '15151', '1ZH15', '111S1', '1F009', '12000', '17256', '10730', '12003', '1111W', '1111S', '1AU93']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,JTB,GCC,5.0,11UJ8
1,TOYOTA,COROLLA,4.0,SEDAN,1,XLI MID,ANE,NON-GCC,NaN,12001
2,TOYOTA,LAND CRUISER,8.0,SUV,1,STD,JTB,GCC,5.0,11WJA
3,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,JTB,GCC,5.0,11UJ8
4,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,JTB,GCC,5.0,11UJ8
...,...,...,...,...,...,...,...,...,...,...
478,TOYOTA,LAND CRUISER,8.0,SUV,1,GX,JTB,NON-GCC,NaN,11WJA
479,TOYOTA,LAND CRUISER,8.0,SUV,1,GX,JTB,GCC,NaN,11WJA
480,TOYOTA,LAND CRUISER,8.0,SUV,1,1,JTB,GCC,NaN,11WJA
481,TOYOTA,LAND CRUISER,8.0,SUV,1,STD,JTB,GCC,NaN,11WJA
482,TOYOTA,LAND CRUISER PRADO,6.0,SUV,1,NaN,JTB,GCC,NaN,11VJ9

====================================================================================================
POS4: 8
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'COROLLA', 'LAND CRUISER', 'ECHO', 'YARIS', 'RAV4', 'SUPRA', 'PRADO', 'AVALON', 'FJ CRUISER', 'COROLLA 1.3', 'HIACE', 'SALOON', 'HILUX', '2009', 'COROLLA 1.6', 'TUNDRA', 'TERCEL', 'SEQUOIA', 'TOYOTA PRADO', 'LITEACE', 'AURION', 'SIENNA', 'COROLLA SEDAN', 'HILUX ADVENTURE', 'ORION', '1.8 XS', 'TOYOTA']
  bodyType: ['SEDAN', 'SUV', 'SALOON', 'COUPE', 'HATCHBACK', 'PANEL VAN HIGH ROOF', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'PICKUP', 'STATION', 'PANEL VAN', 'MPV']
  trim: ['XLI', 'XLI TOP', 'GX', 'PS PW CL', 'XLI MID', 'FLEET', 'MID', 'BASE', 'SE', 'S', 'GLI', 'STD', 'LE', 'VX', 'STD (NON GCC)', 'GL', 'T', 'SE+', 'SE TRD AERO PK', 'AXL ', 'VXR', 'TOP', 'GLS', 'STANDARD', 'GXR3', 'GLX SPORT Z', 'TX', 'EXCLUSIVE', 'XLE (NON GCC)', 'GLE', 'TOURING', 'GRANDE', 'DLS', 'GLE HEV', 'E', 'SPORT', 'GLI TOP', 'GLX', 'GXR', 'EXTREME', 'LIMITED', 'DLX', 'EXR', 'XLE', 'ADVENTURE', 'BE', 'STANDERD', 'LIMITED TOP', 'GLE-X', 'XLI EXECUTIVE', 'LE (NON GCC)', 'YA', '60TH', 'LIMITED MID', 'SV', 'XLE TOURING', 'SR5 (NON GCC)', 'ST', 'DL', 'LX']
  WMI: ['4T1', 'JTD', 'JTF', 'RKL', 'JT2', '6T1', 'JTM', 'JTN', '2T1', 'JZA', 'JTE', '4T4', 'MR2', 'MHF', 'CLG', 'FZJ', 'JTH', 'MR0', 'NV1', '5T1', 'JJ7', 'JM3', '5T8', '211', '5TD', '5TF', 'MHE', '5YF', 'MV1', 'JT0', 'MHK', 'LZZ', 'CPB', '471', '1NX', '150', 'AT1', 'JL7']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['8A32K', '8E32K', '8R23E', '8V71J', '8242E', '8W133', '889HE', '8V42E', '8F22K', '8F1FK', '8C42E', '8W923', '8D31V', '8F30K', '824HK', '8A13E', '811HK', '8A02E', '80001', '8K46K', '8L29J', '8D33V', '8E46K', '8846K', '8F9FK', '8K368', '8U4EE', '8T9F3', '8U11F', '8K36B', '8T923', '8U3FJ', '8F4HK', '8K3DB', '8622K', '8D1FK', '8K1FK', '8R22E', '8N95J', '80002', '8W23E', '8G22K', '8K3D8', '855HZ', '8R32E', '8F32K', '8F3EK', '80008', '829F3', '880CE', '819HK', '8URHE', '8X9FJ', '8U40E', '8J466', '8W933', '8F9HK', '8U8CD', '8K40K', '80233', '814HK', '8X8CD', '80473', '8B9HE', '8L9HE', '8K33V', '80328', '8R42E', '80345', '80850', '80430', '8E30K', '8E42K', '80000', '8F4FK', '80593', '80274', '88OCE', '8E33K', '80987', '8F4DV', '8CE1K', '8D35E', '80583', '8V541', '80413', '8K1E8', '8W123', '813FV', '8K3EK', '80943', '8FREV', '8J53L', '8RI2E', '8K32V', '8Z4HK', '80097', '8FIFK', '80636', '8Y64A', '81018', '80986', '8L0HE', '80893', '801FK', '80003', '80907', '80772', '829HK', '80063', '8K31V', '8F31F', '80015', '8F9C3', '80281', '8K4FK', '8A23C', '80125', '80042', '819F3', '8842E', '80533', '8CCVD', '87N07', '80350', '80532', '80876', '8Y5F1', '80459', '80548', '8W9F3', '80464', '80095', '8K22C', '87367', '811EB', '8BCE1', '8U5CD', '80767', '8F38K', '80251', '80761', '8U25J', '80951', '80078', '80407', '80839', '8F9EV', '8Y561', '8F28K', '80318', '80558', '80506', '80183', '8628K', '80950', '8808E', '8U71J', '8A08E', '80700', '80025', '80890']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,4T1,GCC,4.0,8A32K
1,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,JTD,GCC,4.0,8E32K
2,TOYOTA,COROLLA,4.0,SEDAN,8,XLI TOP,JTD,GCC,4.0,8R23E
3,TOYOTA,LAND CRUISER,6.0,SUV,8,GX,JTF,GCC,5.0,8V71J
4,TOYOTA,COROLLA,4.0,SEDAN,8,XLI,JTD,GCC,4.0,8242E
...,...,...,...,...,...,...,...,...,...,...
781,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,4T1,GCC,4.0,8E30K
782,TOYOTA,COROLLA,4.0,SEDAN,8,GLI,5YF,GCC,NaN,8URHE
783,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,4T1,GCC,4.0,8E32K
784,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,NV1,GCC,NaN,80890
785,TOYOTA,TOYOTA,4.0,SEDAN,8,LX,JTD,GCC,NaN,8W23E

====================================================================================================
POS4: N
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'TUNDRA', 'HILUX', 'HIACE', 'RAV4', 'TAKOMA', 'FORTUNER', 'LAND CRUISER PICK UP', 'RUMION', 'TOKOMA', '4RUNNER', 'LAND CRUISER', 'AVALON', 'COROLLA', 'تاكوما', 'CAMRY', 'SIENNA']
  bodyType: ['PICK UP DOUBLE CAB', 'PANEL VAN', 'PICK UP', 'PICK UP SINGLE CAB', 'SUV', 'PICKUP', 'MPV', 'SEDAN', 'STATION']
  trim: ['STD (NON GCC)', '1794 EDITION (NON GCC)', 'DLX', 'GL', 'STD', 'VX', 'LMV', 'CREWMAX CAPSTONE (NON GCC)', '1500', 'DL', 'EXR', 'EX', 'SR', '1', 'LE HEV', 'PRESTIGE', 'LIMITED', 'XLE', 'GXR TOP', 'C', 'S', 'TOP', 'BASE', 'SINGLE CABIN', 'SE', 'GLE', 'LE (NON GCC)', 'TRIM']
  WMI: ['5TE', '5TF', 'JAA', 'JT4', '4TA', 'JTM', 'MA3', 'LWL', 'NNN', '2T3', 'JTF', 'JTD', 'JTE', '1GT', 'HJN', '4T1', 'STE', 'GTF', 'WMA', 'LFC', '5TD']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['NX4CN', 'NC5DB', 'NHR55', 'NX22N', 'NG426', 'NL42N', 'NY5F1', 'NM92N', 'NFREV', 'NC2B1', 'NRRTX', 'N0000', 'ND22S', 'N1RFV', 'NX62N', 'NA5DB', 'NU5JR', 'N19EC', 'NADMG', 'NC5EC', 'NB1BB', 'NT08J', 'NE426', 'NU5F1', 'N0001', 'NPR66', 'NX037', 'N38ZZ', 'NZ1AK', 'NNG6P', 'NA3DC']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,N,STD (NON GCC),5TE,GCC,4.0,NX4CN
1,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,N,1794 EDITION (NON GCC),5TF,GCC,4.0,NC5DB
2,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,N,STD (NON GCC),5TF,GCC,4.0,NX4CN
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,N,DLX,JAA,GCC,4.0,NHR55
4,TOYOTA,HIACE,4.0,PANEL VAN,N,GL,5TE,GCC,5.0,NX22N
...,...,...,...,...,...,...,...,...,...,...
304,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,N,DLX,JTF,GCC,2.0,NG426
305,TOYOTA,RAV4,4.0,SUV,N,EX,JTM,GCC,5.0,NFREV
306,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,N,CREWMAX CAPSTONE (NON GCC),5TF,GCC,4.0,NA5DB
307,TOYOTA,TACOMA,4.0,PICKUP,N,STD (NON GCC),5TF,NON-GCC,NaN,NX4CN
308,TOYOTA,TACOMA,4.0,PICKUP,N,STD (NON GCC),5TE,NON-GCC,NaN,NX22N

====================================================================================================
POS4: V
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', '4RUNNER', 'TUNDRA', 'LAND CRUISER', 'COROLLA', 'RAV4', 'TACOMA', 'TERCEL', 'CAMRY', 'YARIS', '2022', 'INNOVA', 'FJ CRUISER', 'FORTUNER', 'TACOMA (PICK UP)', 'HIACE']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'SEDAN', 'PICKUP', 'PICK UP', 'CARAVAN', 'PICK UP SINGLE CAB', 'MPV', 'PANEL VAN']
  trim: ['GL', 'TRD OFF-ROAD', '1794 EDITION (NON GCC)', 'EXR', 'XLI EXECUTIVE', 'GLX', 'ADVENTURE', 'DLX', 'STD (NON GCC)', 'STD', 'XLI', 'CREWMAX CAPSTONE (NON GCC)', 'SE', 'GLI', 'GXR TOP', 'DLS', 'BASE', 'LIMITED', 'DX', 'GLI HEV', 'TRIM', 'GLE-X HEV 40TH ANNIV', 'SE+']
  WMI: ['JT4', 'JTE', '5TF', 'LFV', '5YF', 'AAP', '5TE', 'JTD', '4TA', 'LVA', '00N', 'MR2', 'JT5', 'LPS', 'LVB', 'W1W', '5AL', 'MHK', 'JT2']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['VD10A', 'VA5BR', 'VC5DB', 'VB9E7', 'VPMAE', 'V0291', 'VL52N', 'VB9E6', 'VPRAE', 'V2MW5', 'V1804', 'VP9F3', 'VN94T', 'VAEDE', 'VJ73J', 'VN52N', 'V4JBB', 'V2MWB', 'V0LEZ', 'VP286', 'VN61F', 'VN73K', 'VC31F', 'V3JBB', 'VN13G', 'VK13E', 'VD11E']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,V,GL,JT4,GCC,4.0,VD10A
1,TOYOTA,4RUNNER,4.0,SUV,V,TRD OFF-ROAD,JTE,GCC,5.0,VA5BR
2,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,V,1794 EDITION (NON GCC),5TF,GCC,4.0,VC5DB
3,TOYOTA,LAND CRUISER,6.0,SUV,V,EXR,LFV,GCC,5.0,VB9E7
4,TOYOTA,COROLLA,4.0,SEDAN,V,XLI EXECUTIVE,5YF,GCC,4.0,VPMAE
...,...,...,...,...,...,...,...,...,...,...
66,TOYOTA,CAMRY,4.0,SEDAN,V,GLE-X HEV 40TH ANNIV,JT2,GCC,4.0,VK13E
67,TOYOTA,COROLLA,4.0,SEDAN,V,SE+,JTD,GCC,4.0,VPRAE
68,TOYOTA,COROLLA,4.0,SEDAN,V,XLI EXECUTIVE,JTD,GCC,4.0,VPMAE
69,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,V,STD (NON GCC),5TF,GCC,4.0,VC5DB
70,TOYOTA,HILUX,6.0,PICKUP,V,DLX,JT4,NON-GCC,NaN,VD11E

====================================================================================================
POS4: T
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'TACOMA', 'HILUX', 'CAMRY', 'COROLLA', 'TUNDRA', 'URBAN CRUISER', 'SALOON', 'GRAND DELUX', 'RAV4', 'STREET TRIPLE', 'LAND CRUISER']
  bodyType: ['PANEL VAN', 'PICKUP', 'PICK UP DOUBLE CAB', 'SEDAN', 'PICK UP', 'SUV', 'PICK UP SINGLE CAB', 'MINI BUS', 'MOTORCYCLE', 'SALOON']
  trim: ['GL', 'STANDARD', 'GLE-X HEV 40TH ANNIV', 'PICK UP', 'STD (NON GCC)', 'GLE HEV', 'DLX', 'GLX', 'GLE', 'XLI', 'DLX TOP', 'BASE', 'SE', 'DLS', 'DL', 'S', 'STD', 'GLS', 'LIMITED HEV', 'GLI', 'GRANDE HEV 40TH ANNIV', 'EXR', 'TRD']
  WMI: ['JD4', '5TE', '5TF', '4T1', '5YF', 'MBJ', 'LRR', 'WMA', 'JTG', 'SCR', 'LJN', 'MHK', 'JT4', 'STE', 'LZY', 'SMT', '4TI', 'JTD', 'STF', '1V2', 'HA9']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['TV182', 'TX22N', 'TX4CN', 'T11AK', 'T4MCE', 'TV192', 'TMLA2', 'TEKP1', 'T48ZZ', 'TU4GN', 'TX02P', 'TEB3N', 'TFUC5', 'T4RCE', 'TW5F1', 'TFU2K', 'TGUB2', 'TC31E', 'TV092', 'TN12D', 'T36ZZ', 'T11BK', 'TDTD6', 'TU62N', 'TTL13', 'TLIAK', 'TY5F1', 'TR2CA', 'TV082', 'TX9A2', 'TU22N', 'T147Y', 'TN14D']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,PANEL VAN,T,GL,JD4,GCC,5.0,TV182
1,TOYOTA,TACOMA,4.0,PICKUP,T,STANDARD,5TE,GCC,NaN,TX22N
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,T,GL,5TF,GCC,4.0,TX4CN
3,TOYOTA,CAMRY,4.0,SEDAN,T,GLE-X HEV 40TH ANNIV,4T1,GCC,4.0,T11AK
4,TOYOTA,TACOMA,4.0,PICK UP DOUBLE CAB,T,PICK UP,5TE,GCC,2.0,TX4CN
...,...,...,...,...,...,...,...,...,...,...
103,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,T,GL,5TF,GCC,4.0,TX4CN
104,TOYOTA,CAMRY,4.0,SEDAN,T,S,4T1,GCC,4.0,T11AK
105,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,T,DLX TOP,5TF,GCC,2.0,TX4CN
106,TOYOTA,CAMRY,4.0,SEDAN,T,GLE HEV,4T1,GCC,4.0,T11AK
107,TOYOTA,TACOMA,6.0,PICKUP,T,TRD,JT4,NON-GCC,NaN,TN14D

====================================================================================================
POS4: 2
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['SIENNA', 'HIACE', 'FJ CRUISER', 'RAV4', 'AVALON', 'WISH', 'HILUX', 'COROLLA', 'AURION', 'SEQUOIA', 'RAV 4', 'LAND CRUISER', 'CAMRY', '4RUNNER', 'PRADO', 'FORTUNER', 'YARIS']
  bodyType: ['MPV', 'PANEL VAN', 'SUV', 'SEDAN', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'VAN', 'STATION', 'PICK UP SINGLE CAB']
  trim: ['LE (NON GCC)', 'GL', 'GXR', 'STD', 'XLE (NON GCC)', 'STD (NON GCC)', 'EXR', 'LIMITED PREMIUM', 'VX', 'ADVENTURE', 'XLI', 'MID', 'GG', 'EX', 'LIMITED 4X2', 'DLX', 'LIMITED MID', 'VXR', 'GX', 'GLI TOP', 'GLI', 'SR5 (NON GCC)', 'LIMITED', 'SE+', 'TX-L', 'BE', 'GLX', 'VX TOP LTH']
  WMI: ['5TD', 'D04', 'ZGE', 'JT4', 'JTM', 'WDD', 'JTB', 'JTD', 'UAE', '2T3', 'WV1', 'MC2', '8LT', 'MD6', 'JTE', 'WMA', '1G0', '174', '5ZT', 'AS3', 'J10']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['2A22C', '2K3DC', '2757D', '21610', '2A119', '2A23C', '2K23C', '2K31V', '2FREV', '22206', '21UHB', '2F9EV', '213FV', '21604', '2S012', '21606', '2K22C', '2K29C', '2Y68A', '2882K', '2F33V', '2Y64A', '21FCL', '2EFV4', '21UJ7', '2A29C', '26BG7', '21603', '2T14R', '21SZZ', '21608', '21605', '2HNAG', '21090', '2SBPB', '2U14R', '2K33V', '21602', '2S010', '2R119', '21AS3', '2T38A', '2S011', '22205']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,SIENNA,6.0,MPV,2,LE (NON GCC),5TD,GCC,5.0,2A22C
1,TOYOTA,SIENNA,6.0,MPV,2,LE (NON GCC),5TD,GCC,5.0,2K3DC
2,TOYOTA,HIACE,4.0,PANEL VAN,2,GL,D04,NON-GCC,NaN,2757D
3,TOYOTA,SIENNA,6.0,MPV,2,LE (NON GCC),5TD,GCC,5.0,2K3DC
4,TOYOTA,FJ CRUISER,6.0,SUV,2,GXR,ZGE,NON-GCC,NaN,21610
...,...,...,...,...,...,...,...,...,...,...
140,TOYOTA,HIACE,4.0,PANEL VAN,2,STD,JT4,GCC,5.0,2A119
141,TOYOTA,SIENNA,6.0,MPV,2,LE (NON GCC),5TD,GCC,5.0,2A23C
142,TOYOTA,RAV4,4.0,SUV,2,GX,2T3,GCC,5.0,2FREV
143,TOYOTA,RAV4,4.0,SUV,2,VX,JTM,GCC,5.0,2FREV
144,TOYOTA,CAMRY,4.0,SEDAN,2,GLI,WDD,GCC,4.0,22205

====================================================================================================
POS4: 4
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COASTER', 'HIACE', 'CAMRY', 'COROLLA', 'HILUX', 'TUNDRA', 'LAND CRUISER', 'SEQUOIA', 'PREVIA', 'AVALON']
  bodyType: ['BUS', 'PANEL VAN', 'SEDAN', 'PICK UP DOUBLE CAB', 'SUV', 'MINI BUS', 'MPV']
  trim: ['STD', 'LIMITED HEV', 'GL', 'SE', 'DL', 'XLI', 'STD (NON GCC)', 'GLI', 'GXR', 'DX H/R W/B', 'GLX', 'SR5 4X4', 'SAFARI', 'SWB', 'DLX', 'S', 'GLE', 'LIMITED']
  WMI: ['JTB', 'LA6', 'ACV', 'MAT', 'NCP', '090', '074', 'GGG', 'LDP']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['41UB5', '41UHB', '41CB8', '41502', '44925', '46405', '42014', '40503', '46470', '41500', '42015', '41503', '41501', '40500', '408B0', '472AX', '46475', '41BB4', '46407', '45612', '42010', '41E96', '42018']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COASTER,6.0,BUS,4,STD,JTB,GCC,2.0,41UB5
1,TOYOTA,HIACE,4.0,PANEL VAN,4,STD,JTB,GCC,5.0,41UHB
2,TOYOTA,CAMRY,4.0,SEDAN,4,LIMITED HEV,LA6,GCC,NaN,41CB8
3,TOYOTA,HIACE,4.0,PANEL VAN,4,STD,JTB,GCC,5.0,41UHB
4,TOYOTA,CAMRY,4.0,SEDAN,4,GL,ACV,GCC,NaN,41502
5,TOYOTA,COROLLA,4.0,SEDAN,4,SE,MAT,GCC,NaN,44925
6,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,4,DL,MAT,GCC,4.0,46405
7,TOYOTA,COROLLA,4.0,SEDAN,4,XLI,NCP,NON-GCC,NaN,42014
8,TOYOTA,CAMRY,4.0,SEDAN,4,GL,ACV,GCC,NaN,40503
9,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,4,STD (NON GCC),MAT,GCC,4.0,46470
10,TOYOTA,COASTER,6.0,BUS,4,DL,MAT,GCC,2.0,44925
11,TOYOTA,CAMRY,4.0,SEDAN,4,GLI,ACV,GCC,NaN,40503
12,TOYOTA,LAND CRUISER,8.0,SUV,4,GXR,MAT,GCC,NaN,44925
13,TOYOTA,CAMRY,4.0,SEDAN,4,GLI,ACV,NON-GCC,NaN,41500
14,TOYOTA,HIACE,3.0,MINI BUS,4,DX H/R W/B,NCP,NON-GCC,NaN,42015
15,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41503
16,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41501
17,TOYOTA,CAMRY,4.0,SEDAN,4,GLI,ACV,GCC,NaN,40500
18,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41501
19,TOYOTA,LAND CRUISER,8.0,SUV,4,GXR,090,GCC,5.0,408B0
20,TOYOTA,COROLLA,4.0,SEDAN,4,SE,MAT,GCC,NaN,46470
21,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41503
22,TOYOTA,SEQUOIA,8.0,SUV,4,SR5 4X4,074,GCC,5.0,472AX
23,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,GCC,NaN,40500
24,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41501
25,TOYOTA,LAND CRUISER,4.0,SUV,4,SAFARI,MAT,GCC,NaN,46475
26,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41502
27,TOYOTA,COASTER,6.0,BUS,4,STD,JTB,GCC,2.0,41BB4
28,TOYOTA,HIACE,4.0,PANEL VAN,4,STD,JTB,GCC,5.0,41UHB
29,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41501
30,TOYOTA,COASTER,4.0,BUS,4,SWB,MAT,GCC,NaN,44925
31,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,40500
32,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41501
33,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,ACV,NON-GCC,NaN,41503
34,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,4,DLX,MAT,GCC,NaN,46407
35,TOYOTA,HIACE,4.0,PANEL VAN,4,STD,JTB,GCC,5.0,41UHB
36,TOYOTA,CAMRY,4.0,SEDAN,4,XLI,ACV,NON-GCC,NaN,41500
37,TOYOTA,COROLLA,4.0,SEDAN,4,XLI,GGG,GCC,NaN,45612
38,TOYOTA,PREVIA,4.0,MPV,4,S,NCP,GCC,NaN,42010
39,TOYOTA,CAMRY,4.0,SEDAN,4,GLE,LDP,GCC,NaN,41E96
40,TOYOTA,AVALON,6.0,SEDAN,4,LIMITED,NCP,NON-GCC,NaN,42018

====================================================================================================
POS4: 0
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'PREVIA', 'YARIS', 'HIACE', 'COROLLA', 'KS01', 'CAMRY', 'LAND CRUISER', 'TUNDRA']
  bodyType: ['PICK UP DOUBLE CAB', 'MPV', 'HATCHBACK', 'MINI BUS', 'PICK UP SINGLE CAB', 'SEDAN', 'STATION', 'SUV']
  trim: ['DL', 'DLX', 'MID', 'DX', 'XLI', 'XLI TOP', 'EX', 'BASE', 'GLX', 'GX', 'GL2', 'VXR', 'FLEET', 'STD (NON GCC)', 'STD', 'S', 'XLI EXECUTIVE']
  WMI: ['KN9', 'UP1', '000', 'WMA', 'MR0', 'LHA', 'FJ4', 'EE1', 'MET', 'WB1', '425', 'STF', 'JMY', 'EL5', 'JTB', 'GX9', 'AE1']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['0J4MC', '00713', '00NCP', '06XZZ', '0X22G', '000NN', '00800', '022GD', '00260', '00612', '00856', '02290', '00404', '0000E', '0B9CB', '01111', '042TN', '000NC', '00943', '00898', '0YSF1', '00968', '01035', '0RV43', '03350', '00098', '01BUM', '06622', '01302', '0000J']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,0,DL,KN9,GCC,4.0,0J4MC
1,TOYOTA,PREVIA,4.0,MPV,0,DLX,UP1,NON-GCC,NaN,00713
2,TOYOTA,YARIS,4.0,HATCHBACK,0,MID,000,NON-GCC,NaN,00NCP
3,TOYOTA,HIACE,4.0,MINI BUS,0,DX,WMA,NON-GCC,NaN,06XZZ
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,0,DLX,MR0,GCC,2.0,0X22G
5,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,000,NON-GCC,NaN,000NN
6,TOYOTA,COROLLA,4.0,SEDAN,0,XLI TOP,UP1,NON-GCC,NaN,00800
7,TOYOTA,KS01,0.0,STATION,0,EX,LHA,GCC,NaN,022GD
8,TOYOTA,YARIS,4.0,SEDAN,0,BASE,UP1,NON-GCC,NaN,00260
9,TOYOTA,CAMRY,4.0,SEDAN,0,GLX,UP1,NON-GCC,NaN,00612
10,TOYOTA,YARIS,4.0,SEDAN,0,BASE,UP1,GCC,NaN,00856
11,TOYOTA,LAND CRUISER,6.0,STATION,0,GX,FJ4,GCC,NaN,02290
12,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,EE1,GCC,NaN,00404
13,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,MET,GCC,4.0,0000E
14,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,0,GL2,MR0,GCC,4.0,0B9CB
15,TOYOTA,CAMRY,4.0,SEDAN,0,GLX,WB1,NON-GCC,NaN,01111
16,TOYOTA,LAND CRUISER,6.0,SUV,0,VXR,425,GCC,NaN,042TN
17,TOYOTA,YARIS,4.0,SEDAN,0,FLEET,000,NON-GCC,NaN,000NC
18,TOYOTA,YARIS,4.0,HATCHBACK,0,BASE,UP1,GCC,NaN,00943
19,TOYOTA,YARIS,4.0,SEDAN,0,FLEET,UP1,GCC,NaN,00898
20,TOYOTA,TUNDRA,4.0,PICK UP DOUBLE CAB,0,STD (NON GCC),STF,GCC,NaN,0YSF1
21,TOYOTA,PREVIA,4.0,MPV,0,DLX,UP1,NON-GCC,NaN,00968
22,TOYOTA,YARIS,4.0,HATCHBACK,0,BASE,UP1,GCC,NaN,01035
23,TOYOTA,LAND CRUISER,6.0,SUV,0,GX,JMY,GCC,5.0,0RV43
24,TOYOTA,LAND CRUISER,8.0,SUV,0,GX,FJ4,GCC,NaN,03350
25,TOYOTA,CAMRY,4.0,SEDAN,0,STD,EL5,GCC,NaN,00098
26,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,0,STD,JTB,GCC,NaN,01BUM
27,TOYOTA,CAMRY,4.0,SEDAN,0,S,GX9,GCC,NaN,06622
28,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,AE1,GCC,NaN,01302
29,TOYOTA,COROLLA,4.0,SEDAN,0,XLI EXECUTIVE,MET,GCC,NaN,0000J
30,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,WMA,NON-GCC,NaN,06XZZ

====================================================================================================
POS4: I
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'LAND CRUISER', 'PRADO']
  bodyType: ['PANEL VAN', 'SUV']
  trim: ['STD', 'GX', 'TX-L']
  WMI: ['JTF', 'JTB', 'JTE']
  regionalSpec: ['GCC']
  VDS: ['IX02P', 'ITUJ8', 'IUSFI']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,PANEL VAN,I,STD,JTF,GCC,5.0,IX02P
1,TOYOTA,LAND CRUISER,6.0,SUV,I,GX,JTB,GCC,5.0,ITUJ8
2,TOYOTA,PRADO,4.0,SUV,I,TX-L,JTE,GCC,5.0,IUSFI

====================================================================================================
POS4: 9
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'COROLLA', 'CAMRY', 'HIACE', '2014', 'HILUX']
  bodyType: ['HATCHBACK', 'COUPE', 'SEDAN', 'PANEL VAN', 'PICK UP', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB']
  trim: ['BASE', 'XLI', 'XLI TOP', 'MID', 'GL', 'FLEET', 'DX', 'GC', 'DLX']
  WMI: ['NCP', 'WAU', 'WDB', 'MR2', '180']
  regionalSpec: ['NON-GCC', 'GCC']
  VDS: ['91901', '9FD8T', '91900', '91903', '91902', '94403', '91908', '90615', '9T9F3', '93220', '95021', '95403']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,NCP,NON-GCC,NaN,91901
1,TOYOTA,COROLLA,4.0,COUPE,9,XLI,WAU,GCC,2.0,9FD8T
2,TOYOTA,YARIS,4.0,SEDAN,9,BASE,NCP,NON-GCC,NaN,91900
3,TOYOTA,COROLLA,4.0,SEDAN,9,XLI TOP,NCP,GCC,NaN,91903
4,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,NCP,NON-GCC,NaN,91901
5,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,NCP,NON-GCC,NaN,91902
6,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,NCP,NON-GCC,NaN,91901
7,TOYOTA,CAMRY,4.0,SEDAN,9,GL,WDB,GCC,4.0,94403
8,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,NCP,NON-GCC,NaN,91903
9,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,NCP,NON-GCC,NaN,91908
10,TOYOTA,YARIS,4.0,SEDAN,9,FLEET,NCP,NON-GCC,NaN,91902
11,TOYOTA,HIACE,4.0,PANEL VAN,9,DX,WDB,GCC,NaN,90615
12,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,NCP,NON-GCC,NaN,91901
13,TOYOTA,YARIS,4.0,SEDAN,9,BASE,NCP,NON-GCC,NaN,91901
14,TOYOTA,2014,4.0,SEDAN,9,GC,MR2,GCC,NaN,9T9F3
15,TOYOTA,CAMRY,4.0,SEDAN,9,XLI,180,NON-GCC,NaN,93220
16,TOYOTA,HILUX,4.0,PICK UP,9,DLX,WDB,GCC,NaN,95021
17,TOYOTA,YARIS,4.0,SEDAN,9,FLEET,NCP,GCC,NaN,91902
18,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,9,DLX,WDB,GCC,NaN,95403
19,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,9,DLX,WDB,GCC,NaN,94403
20,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,9,DLX,WDB,GCC,NaN,94403
21,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,9,DLX,WDB,GCC,NaN,94403
22,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,WDB,NON-GCC,NaN,95403

In [64]:
print(data['pos5'].unique())

['B' 'X' 'G' 'T' 'W' 'R' 'U' 'D' 'F' 'E' 'Z' 'V' 'K' '2' 'L' 'N' 'A' '1'
 '3' 'C' 'J' 'H' 'Y' '5' 'M' '4' '6' 'P' '0' '8' '9' 'S' '7' 'I']

In [69]:
from IPython.display import display

for pos_5 in data['pos5'].dropna().unique():

    # 1. Filter the DataFrame for the current pos5 value
    filtered_df_pos5 = data.loc[
        data['pos5'] == pos_5,
        ['make', 'model', 'cylinders', 'bodyType', 'pos5', 'trim', 'WMI', 'regionalSpec', 'noOfDoors', 'VDS']
    ].reset_index(drop=True)

    # 2. Header for the current pos5 group
    print("\n" + "=" * 100)
    print(f"pos5: {pos_5}")
    print("=" * 100)

    # 3. Print unique values for all object columns (except pos5)
    print("--- Unique Values for Object Columns ---")
    object_cols = filtered_df_pos5.select_dtypes(include=['object']).columns
    
    for col in object_cols:
        if col != ['pos5', 'VDS']:
            unique_vals = filtered_df_pos5[col].dropna().unique()
            print(f"  {col}: {list(unique_vals)}")
            
    print("-" * 100)

    # 4. Display the filtered DataFrame
    display(filtered_df_pos5)

====================================================================================================
pos5: B
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'PRIUS', 'LAND CRUISER', 'HILUX', 'SUPRA', 'VELOZ', 'RAIZE', 'TUNDRA', 'HIGHLANDER', 'CAMRY', 'INNOVA', 'COASTER', 'TOYOTA VELOZ', 'HIACE', 'LAND CRUISER PICK UP', 'SIENNA', 'COROLLA 1.3', 'TOYOTA COROLLA', 'FORTUNER', 'RAV4', 'COROLLA 1.6', 'COROLLA CROSS', 'PICK UP', 'TACOMA', '25 HX DC 4X4D 2.4LAT', 'كورولا 1.8', 'TOYOTA COROLLA 1.6', '1999', 'AVALON', 'COROLLA SEDAN', 'YARIS', '4RUNNER', 'SUPRA COUPE', '2 HX DC 4X40', 'PRADO', '26HX DC 4X4D2.4L AT', '26 HX DC 4X4 2.4LAT', '26HX DC 4X4 D2.4LAT', '26 HX DC 4X4 D 2.4L AT', 'TOYOTA - 26 HX DC 4X4 D 2.4L AT', '25 HX DC 4X4', 'DLX FA (PICK UP)', 'KING LONG PASSENGER', 'HX DC 4X4 D 2.4L AT', '26 HX DC 4X4D', 'LAND CRUISER PICK UP CARGO', 'H 530', 'SOLARA', 'LAND CRUISER PICKUP 70', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'HATCHBACK', 'SUV', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'COUPE', 'PICKUP', 'MPV', 'BUS', 'STATION', 'MINI BUS', 'PICK UP', 'SALOON', 'PANEL VAN', 'SUV- CROSSOVER', 'MINI BUS HIGH ROOF', 'LIGHT VEHICLE', 'PICKUP DOUBLE CAB', 'CONVERTIBLE']
  pos5: ['B']
  trim: ['SE', 'ICONIC', 'GXR', 'GL2', 'SGLX', 'VXR', 'GR', 'XLI RB', 'XLI', 'GX', 'E', 'STD (NON GCC)', 'GLI HEV', 'GLX', 'GLI', 'CREWMAX CAPSTONE (NON GCC)', 'BLACK EDITION', 'DLX', 'ECO', 'GXR2', 'XLI MID', 'GL', 'HEV', 'GR SPORT', 'SWB', 'GR TAN EDITION', 'LWB', 'LE', 'SE+', 'GXR1', 'GR-S', 'GR BLUE EDITION', 'DX', 'STD', 'LIMITED TRD SPORT PK', 'VX', 'LE HEV', 'XLE', 'XLT', 'GXR TOP DMST', 'GXR TOP 60TH ANNIV. XTREME', 'GLE HEV BLACK EDITION', 'GXR TOP', 'XLE (NON GCC)', 'GT SPORT', 'LWB HIGH ROOF', 'EXR', 'DL', 'L', 'VX2', 'DLS', 'ADVENTURE', 'SEDAN', 'DYNAMIC', 'PLATINUM', 'GLE HEV', 'GXR-V', '2.0L', '25HX', 'SR5 (NON GCC)', 'LIMITED', 'S', 'VXR BASE', 'S TRD SPORT PK', 'HYCROSS', 'SLD', 'TURBO G RA', 'GLS', 'XL', 'EX', 'LIMITED TRD AERO PK', 'C', 'GLE', '60TH', 'USF', 'XLI EXECUTIVE', 'VIP7', 'XLI EXECUTIVE HEV', 'TRD', 'GLI TOP', '1794 EDITION (NON GCC)', 'MID', 'BASE', 'ASD', 'CAR TRIM', 'SL', '2', 'G', 'VX1', 'STANDARD', 'ST', 'FLEET', 'GXR FMST', 'LX', '1', 'GXR4']
  WMI: ['RKL', 'JTD', 'JTM', 'MRO', 'MR0', 'WZ1', 'MHF', 'MHK', 'JTE', '5TF', '5TD', 'JT2', 'JTN', '4T1', 'JTG', 'WV1', '1NX', '2T1', 'MB1', 'JTF', 'LFV', 'LZW', '5TT', '7MU', '3TM', 'JAC', 'NMT', 'JTZ', 'LSC', 'MYN', 'LVV', 'JE3', 'JN1', '3TY', 'WZI', 'LSG', 'RA6', 'JT3', 'JT4', '1ST', 'LGW', 'MBI', '471', 'VF3', 'JTR', 'LA6', 'WV2', 'LKL', 'JT6', 'JL7', 'LVM', 'HJR', 'LSY', 'JHF', 'JIN', 'MFF', 'HJ4', 'K20', 'JTJ']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BB9HE', 'KB3FU', 'ABBBJ', 'DB9CD', 'KB8CD', 'AB7BJ', 'DB0E0', 'BB0BE', 'AB1BY', 'AB1BA', 'BB42E', 'BB71J', 'BBOBE', 'KB5DB', 'ABCBJ', 'LB3CH', 'BB0CE', 'KB20U', 'BB13E', 'BB46K', 'DB0A0', 'ABBAA', 'KBRFU', 'DBSCD', 'DB4A0', 'FB518', 'ZBB2K', 'EB13E', 'EBRBE', 'DB4C0', 'ABIBY', 'KBBCD', 'BB02E', 'BB3EK', 'PBEJA', 'LB71J', 'DBADK', 'GBRCH', 'DB12E', 'RB71J', 'HB8CD', 'EB73J', 'BB12E', 'HB9CP', 'DBZSV', 'BBOCE', 'DB2C0', 'VB9E7', 'JB6CD', 'EBOBE', 'EB0BE', 'CBAGA', 'KB8FS', 'EB02E', 'FBW41', 'EB71J', 'EBRCH', 'DB8CD', 'FBABG', 'KB5DA', 'DB9CB', 'LB5JN', 'UBS25', 'VB9E6', 'BB9JE', 'DB6CD', 'BBRCH', '8B9HE', 'CB09J', 'KB9CP', 'DB0G0', 'DB8FS', 'BBN2A', 'PBAJA', 'KBAAG', 'DB0C0', 'DBWG3', 'BB03E', 'DB24B', 'CB3FV', 'AB36U', 'DB41S', 'KB54H', 'PBEHD', 'HB10V', 'KB71J', 'PBEFD', 'NB1BB', 'JBYP2', 'KB8CP', 'CB337', 'AB18Y', 'DBOE0', 'GBKFW', 'KB22U', 'BB0BB', '1BAA3', 'PBEFA', 'XBRCH', 'DB21B', 'WBC7H', 'PBEWA', 'DB0AO', 'BBSHE', 'SBAS3', 'ZBB7H', 'DBYSV', 'AB7RJ', '0B9CB', 'DB2A0', '8BCE1', 'BBDEE', 'PBGJB', 'ABFAJ', 'FB718', 'RB23E', 'KBRCH', 'YBBCA', 'BB08E', 'KB5AB', 'YB20H', 'BB8CD', 'ABBDH', 'KB200', '3B007', 'LBACX', 'BBE32', 'JB6CB']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,B,SE,RKL,GCC,4.0,BB9HE
1,TOYOTA,PRIUS,4.0,HATCHBACK,B,ICONIC,JTD,GCC,5.0,KB3FU
2,TOYOTA,LAND CRUISER,6.0,SUV,B,GXR,JTM,GCC,5.0,ABBBJ
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,B,GL2,MRO,GCC,4.0,DB9CD
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,B,SGLX,MR0,GCC,2.0,KB8CD
...,...,...,...,...,...,...,...,...,...,...
12368,TOYOTA,LAND CRUISER,6.0,SUV,B,VXR,JTM,GCC,NaN,AB7BJ
12369,TOYOTA,LAND CRUISER,6.0,SUV,B,VXR,JTM,GCC,NaN,AB7BJ
12370,TOYOTA,PRIUS,4.0,SEDAN,B,ICONIC,JTD,GCC,NaN,KB3FU
12371,TOYOTA,COROLLA,4.0,SEDAN,B,1,RKL,GCC,NaN,BB0BE
12372,TOYOTA,LAND CRUISER,6.0,SUV,B,1,JTM,GCC,NaN,ABBBJ

====================================================================================================
pos5: X
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'HILUX', 'FORTUNER', 'LAND CRUISER', 'INNOVA', 'TACOMA', 'PRADO', 'FJ CRUISER', 'TUNDRA', 'COROLLA', 'CRESSIDA', 'LAND CRUISER PICK UP', '2009', 'COASTER', '26HX DC 4X4P2.7LAT', 'RAV4', 'AURION', 'LAND CRUISER PRADO', 'CAMRY', 'هاي لوكس', 'TAKOMA', 'HILUX RE', 'TOKOMA', '25 HX DC 4X4 2.7LAT', 'GLX DA (PICK UP)', 'TOYOTA', 'TOYOTA HILUX', '25 HX DC 4X4P 2.7LAT', 'GLX RA (PICK UP)', 'TOYOTA HIACE', 'هايلوكس', '25 HX DC 4X2 P 27L AT GLX RA/PICK UP', '26HX DC 4X4 PLAT', '2 HX DC 4X4 P 2.7LAT', 'تاكوما', '25 HX DC 4X4 P .LAT', '26 HX DC 4X4 P 2.7LAT', '2024', '25 HX DC 4X4 PLAT GLX RA(PICK UP)', 'SIENNA', 'AVANZA']
  bodyType: ['MINI BUS HIGH ROOF', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'SUV', 'MPV', 'PICK UP', 'VAN', 'PICK UP SINGLE CAB', 'MINI BUS', 'PICKUP', 'PANEL VAN HIGH ROOF', 'HALF PANEL VAN', 'BUS', 'MINIVAN', 'MINI BUS SEMI HIGH ROOF', 'SEDAN', 'STATION', 'PICKUP TRUCK', 'CARGO VAN', 'PICKUP SINGLE CABIN', 'PICKUP DOUBLE CAB', 'PICKUP DOUBLE CABIN', 'CONVERTIBLE', 'PICK-UP']
  pos5: ['X']
  trim: ['GLX', 'DX', 'DL', 'GL', 'EXR', 'GL2', 'SR5', 'GXR', 'DLX', 'VXR', 'STD', 'GLS', 'DLX TOP', 'SE', 'SAFARI', 'EXTREME', 'TOP', 'DLS', 'SE+', 'STD (NON GCC)', 'DX H/R W/B', 'TX-L', 'TX', 'SGLX', 'TX-L TOP', 'ADVENTURE', 'PREMIUM', 'VX2', 'VX MID', 'STANDARD', 'SR5 (NON GCC)', 'SPORT', 'S', 'SR', 'LX AC PWR OPT', 'PICK UP', 'GL TOP', 'GRD', 'GLI', 'TRD SPORT', 'DLS - STD ROOF', 'GXR+', 'XTREME', 'LIMITED', 'EX', 'CRESSIDA', '1', 'ADVENTTURE', 'LE', 'VX', 'STANDER', 'PRESTIGE', 'VX2 PLUS', 'SS', 'GX', 'GLE', 'GLI TOP LEATHER', 'VX-L MID', 'A', 'VXR BASE', 'GGG', 'GXR GT', 'C', 'S T2 TOP', 'LUXURY SPORT', 'XLI', 'AA', 'PICKUP', 'GXR TOP 60TH ANNIV. XTREME', 'GXR SOD D/AC AW', 'VX1', 'X', 'GXR MID', 'CTD', 'ST', 'CAR TRIM', 'LE (NON GCC)', 'SINGLE CABIN', 'SE T2', 'TAXI', 'TRIM']
  WMI: ['JTF', 'MR0', 'MHF', 'JTG', 'JTM', 'MRO', '5TF', 'JTE', 'MR1', '5TE', 'JTV', 'JT6', 'LFM', '3TY', 'JT2', 'MHE', 'ITG', 'KNF', 'MRI', 'JTN', 'MRD', 'JT8', 'UTG', '1FT', 'JTH', 'J1G', 'JS1', 'JIG', 'JIF', '1TF', 'CTF', '1TG', 'STE', 'SMT', 'MRU', 'HA9', 'JT4', 'MFH', 'MHP', 'MRC']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['HX02P', 'HXDGP', 'BX8CD', 'PX22P', 'DX8FS', 'CX9CB', 'YX59G', 'JX02P', 'HX09J', 'XX43G', 'HX01J', 'FX22G', 'HX05J', 'EX12G', 'DX22G', 'JX9CD', 'HX8CD', 'UX4EN', 'EX19G', 'SX22P', 'CX19G', 'XX42G', 'CX9CD', 'BX9FJ', 'CX8CD', 'DX9CD', 'CX12G', 'JX8CD', 'GX8EM', 'CX3FJ', 'RX12P', 'PX42N', 'CX6CB', 'CX8CB', 'NX4CN', 'JX8CB', 'CX8EM', 'SX23P', 'KX8CB', 'FX226', 'DX8CD', 'ZX69G', 'UX42N', 'EX126', 'NX22N', 'KX9CB', 'CX9FJ', 'DX6CD', 'DX8F5', 'TX22N', 'KX6CB', 'HXHX0', 'BX3FJ', 'CX6CD', 'AXACC', 'CX8GS', 'SX5EN', 'XX426', 'TX4CN', 'JX6CB', 'AX12G', 'MX83E', 'RX5GN', 'KX8CD', 'JX9CB', 'YX596', 'JX6CD', 'PX4EN', '5X23P', 'FX00G', 'HXO2P', 'YX69G', 'WXZ74', 'JX6BB', 'CX126', 'IX02P', 'GX8CD', '0X22G', 'JX4CN', 'JX8BB', 'HX093', 'EX120', 'CX196', 'CXBEM', '8X9FJ', 'XX436', 'HX0SJ', '8X8CD', 'TX02P', 'NX62N', 'BX8C0', 'MX73E', 'YX59C', 'DX9CB', 'EX196', 'HXO1J', 'HXO9J', 'HX0IJ', 'EX1E6', 'FX02P', 'EX22G', 'HXD2P', 'YX590', 'YXS9G', 'JXOZP', 'JX9BB', 'GX72A', 'BXBCD', 'HX013', 'JX4GN', 'HX02J', 'KX8C8', 'CX8C8', 'HXBCD', 'FX22C', 'XX430', 'DX226', 'CX9C8', 'DXBFS', 'BX9F1', 'DX1H2', 'AX126', 'HX091', 'JXQ2P', 'DX6CB', 'DXBCD', 'AX5GN', 'AX8CD', 'CX190', 'TX9A2', 'HXQ2P', 'EX91G', 'HX07P', 'NX037', 'CXI9G', 'RX56N', 'YX50G', 'FX22P', 'XX48G', 'RX22G', 'GXSEM', 'CX0CD', 'CX3DD', 'KX8FS', 'JXO2P']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,X,GLX,JTF,GCC,4.0,HX02P
1,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,X,DX,JTF,GCC,4.0,HX02P
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,X,DL,JTF,GCC,4.0,HXDGP
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,X,GL,MR0,GCC,4.0,BX8CD
4,TOYOTA,HIACE,4.0,PANEL VAN,X,GL,JTF,GCC,5.0,PX22P
...,...,...,...,...,...,...,...,...,...,...
35094,TOYOTA,HILUX,4.0,PICKUP,X,DLX TOP,MR0,GCC,NaN,FX22G
35095,TOYOTA,LAND CRUISER,8.0,SUV,X,VXR,JTM,GCC,NaN,HX05J
35096,TOYOTA,LAND CRUISER PRADO,4.0,SUV,X,GXR,JTE,GCC,NaN,BX9FJ
35097,TOYOTA,HILUX,4.0,PICKUP,X,1,MR0,GCC,NaN,EX12G
35098,TOYOTA,LAND CRUISER,8.0,SUV,X,GXR,JTM,GCC,NaN,HX01J

====================================================================================================
pos5: G
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'HILUX', 'COROLLA', 'كامري', 'YARIS', 'RAV4', 'HIACE', 'FJ CRUISER', 'INNOVA', 'COASTER', '86', 'LAND CRUISER', 'SIENNA', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PICKUP', 'SUV', 'PANEL VAN', 'MPV', 'MINI BUS', 'HATCHBACK', 'BUS', 'SALOON', 'COUPE', 'CARGO VAN']
  pos5: ['G']
  trim: ['XLI', 'BASE', 'GLE', 'DLX', 'LIMITED', 'CE (NON GCC)', 'STD', 'LE', 'LSE', 'XLE (NON GCC)', 'XLI MID', 'E PLUS HEV', 'LE HEV', 'XLE', 'SL', 'SE', 'GLI', 'XLE HEV', 'GL', 'EX', 'ADVENTURE', 'LUMIERE HEV', 'E', 'LWB', 'VXR', 'DLS', 'S', 'MID', 'LE (NON GCC)', 'DLS - STD ROOF', 'SPORT', 'GLI HEV', 'GX', 'VTI', 'GLX', 'GXR', 'A', 'GLS', 'SWB', '1']
  WMI: ['4T1', '6T1', 'JT2', 'JTF', 'JTN', 'JT4', 'GTF', '4TI', 'YV2', 'JM3', 'LVG', 'RA6', 'WD4', 'KMH', 'MB1', '6TI', '1GD', 'GGG', 'KMJ', 'JN2', 'LJN', '1GJ', '1GC', 'L3H', 'MBI', 'MBT', 'JTE', '5TD', 'JHD']
  regionalSpec: ['NON-GCC', 'GCC']
  VDS: ['BG22K', 'BG12K', 'EG426', 'AG4CK', 'BG28K', 'EG22K', 'AG426', 'EG23K', 'FG426', 'BG23K', 'NG426', 'AG30A', 'WG725', 'CGE23', 'PG34L', 'EG425', 'AG20A', '8G22K', 'WG3E1', 'WG81R', 'AG34L', 'FG15T', 'GGG56', 'BG21K', 'HG17C', 'EG21K', 'BG17K', 'TGUB2', 'DG61E', 'GG25K', 'WGAFP', 'HG39K', 'CG12K', 'EG12K', '3G22K', 'EGCBB', 'HG09G', 'DGRFH', 'AGACH', 'FG8JP']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,CAMRY,4.0,SEDAN,G,XLI,4T1,NON-GCC,4.0,BG22K
1,TOYOTA,CAMRY,4.0,SEDAN,G,XLI,6T1,GCC,4.0,BG22K
2,TOYOTA,CAMRY,4.0,SEDAN,G,BASE,4T1,GCC,4.0,BG22K
3,TOYOTA,CAMRY,4.0,SEDAN,G,BASE,JT2,GCC,4.0,BG22K
4,TOYOTA,CAMRY,4.0,SEDAN,G,GLE,4T1,GCC,4.0,BG12K
...,...,...,...,...,...,...,...,...,...,...
4756,TOYOTA,CAMRY HYBRID,4.0,SEDAN,G,1,JT2,NON-GCC,NaN,BG22K
4757,TOYOTA,CAMRY HYBRID,4.0,SEDAN,G,CE (NON GCC),6T1,GCC,NaN,BG22K
4758,TOYOTA,CAMRY HYBRID,4.0,SEDAN,G,CE (NON GCC),6T1,GCC,NaN,BG22K
4759,TOYOTA,CAMRY HYBRID,4.0,SEDAN,G,XLI,6T1,GCC,NaN,BG22K
4760,TOYOTA,CAMRY HYBRID,4.0,SEDAN,G,GLE,JTN,GCC,NaN,AG4CK

====================================================================================================
pos5: T
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'YARIS', 'XA', 'ECHO', 'TUNDRA', '4RUNNER', 'COROLLA', 'PRIUS', 'FORTUNER', 'HILUX', 'LAND CRUISER VXR', 'SEQUOIA', 'استیشن', 'CAMRY', 'PRADO', 'TANDRA', '4 RUNNER', 'TOYOTA TUNDRA', 'LAND CRUISER PICK UP', 'RAV4', 'HIACE', 'STREET TRIPLE', '2014', 'PARISIENNE BROUGHAM', 'TANDRA PICK UP DOUBLE CABIN']
  bodyType: ['SUV', 'SEDAN', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'STATION', 'PICK UP SINGLE CAB', 'PICKUP', 'SALOON', 'PICK UP', 'PICK UP DOUBLE CABIN', 'PANEL VAN', 'MOTORCYCLE', 'TRUCK']
  pos5: ['T']
  trim: ['VX', 'SE', 'SE TRD AERO PK', 'STD', 'G', 'SE+', 'TOP', 'S+', 'S', 'BASE', 'VXR', 'XLI MID', 'FLEET', 'GX', 'VXR BASE', 'VXR TOP', 'E', 'STD (NON GCC)', 'MID', 'SAFARI', 'SR5 (NON GCC)', 'GLI TOP', 'XLI', 'SPORT', 'GXR TOP', 'GXR', 'DLS', 'GXR FMST', 'DLX', 'LIMITED', 'GL', 'GXR SOD D/AC AW', 'GXR TOP 60TH ANNIV. XTREME', 'GLI', '4X4', 'GXR MID 60TH ANNIV. XTREME', 'TRIM', 'GXR TOP DMST', 'GL DECKLESS', 'GLX', 'STATION ', 'SR5 4X2', 'ROYAL', 'VXR TOP XTREME', 'GXR MID', 'EXR', 'XLI TOP', 'VXR MID', 'PS PW CL', '4', 'PW CL', '1', 'SPORTS', 'PLATINUM', 'GLS', 'EXCELLENCE', 'TUNDRA', 'PICK UP', '60TH', 'ASAD', 'GC', '2', 'X', 'SL', '0']
  WMI: ['JTM', 'MR2', 'JTE', 'JTD', 'MHF', 'JT3', '5TB', 'VNK', '5TF', '1GC', '5TD', '5T8', 'JTH', 'KMH', 'JND', 'JN1', 'STD', 'KNF', 'JTK', 'JTF', 'RKM', 'JTB', 'MMC', 'MR1', 'MFH', 'MHE', '5N1', 'MP2', 'SMT', 'JN8', 'ITE', '1G2', 'STB']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['HT09J', 'BT9F3', 'HT05J', 'KT9F3', 'JT923', 'BT923', 'KT623', 'JT123', 'JT4K3', 'HTO5J', 'BT441', 'DT441', 'KT923', 'KTUD3', 'BT14R', 'KT4K3', 'BT123', 'JT903', 'RT341', 'JTUD3', 'KT521', 'PTDEK', 'HT093', 'HTOSJ', 'ET341', 'KT9D3', 'DT481', 'BT4K3', 'ZT14R', 'HT053', 'BT481', 'KT441', 'BT17R', 'BT903', '8T9F3', 'ZT38A', 'RT541', '8T923', 'MT09J', 'BT541', 'BT581', 'JT81E', 'PT9F3', 'DT3MW', 'BT48A', 'STZ74', 'KT903', 'HT0SJ', 'KT624', 'DTPUK', 'KT123', 'ITUJ8', 'HT523', 'ST9F3', 'MT521', 'BT44A', 'BT64A', 'HT06J', 'ET9F3', 'ET923', 'LT521', 'ZT17R', 'KT421', 'HT051', 'NT08J', 'AT2MV', 'KT9K3', 'BT9K3', 'ZT34A', 'TTL13', 'BT2MW', 'JT05J', '2T14R', 'BT3AB', 'BT05Y', 'AT123', 'DT541', 'RT9F3', 'JTU03', 'RT381', '9T9F3', 'ET381', 'BT69Y', 'BT3AA', 'JT521', 'KT604', 'ST541', '2T38A', 'BT223', 'JT9K3']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,LAND CRUISER,8.0,SUV,T,VX,JTM,GCC,5.0,HT09J
1,TOYOTA,YARIS,4.0,SEDAN,T,SE,MR2,GCC,NaN,BT9F3
2,TOYOTA,LAND CRUISER,8.0,SUV,T,VX,JTE,GCC,5.0,HT05J
3,TOYOTA,YARIS,4.0,SEDAN,T,SE TRD AERO PK,MR2,GCC,4.0,KT9F3
4,TOYOTA,LAND CRUISER,8.0,SUV,T,VX,JTM,GCC,5.0,HT05J
...,...,...,...,...,...,...,...,...,...,...
12088,TOYOTA,LAND CRUISER,8.0,SUV,T,VX,JTM,GCC,NaN,HT09J
12089,TOYOTA,LAND CRUISER,8.0,SUV,T,VX,JTM,GCC,NaN,HT05J
12090,TOYOTA,YARIS,4.0,HATCHBACK,T,SE+,VNK,NON-GCC,NaN,KTUD3
12091,TOYOTA,LAND CRUISER,8.0,SUV,T,VX,JTM,GCC,NaN,HT09J
12092,TOYOTA,LAND CRUISER,8.0,SUV,T,VX,JTM,GCC,NaN,HT09J

====================================================================================================
pos5: W
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'HILUX', 'COROLLA', 'TUNDRA', 'ECHO', 'RAV4', 'SEQUOIA', 'LAND CRUISER', 'HIACE', 'COROLLA 1.3', 'HIGHLANDER', 'CAMRY', 'RAV 4', 'PRADO', 'FJ CRUISER', 'MR 2', 'COASTER', 'XA', 'TOYOTA COROLLA', 'LAND CRUISER SINGLE-CABIN PICK UP', 'TOYOTA']
  bodyType: ['HATCHBACK', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'SEDAN', 'ESTATE', 'SUV', 'PICK UP', 'MINI BUS', 'SALOON', 'CARAVAN', 'STATION', 'COUPE', 'BUS', 'PICKUP', 'LIGHT VEHICLE']
  pos5: ['W']
  trim: ['MID', 'DLX', 'GL', 'FLEET', 'BASE', 'SE', 'XLI', 'STD (NON GCC)', 'XLI TOP', 'TOP', 'S', 'EX', 'DLX TOP', 'VXR HEV', 'XLI MID', 'STD', 'GLX', 'XLE', 'PS PW CL', 'GLI TOP', 'EXR HEV', 'LE HEV', 'DL', 'EXR', 'GLS', 'VXR BASE', 'DX', 'STANDARD', 'GLI TOP LTH', 'VX', 'SR', 'PLATINUM', 'HYBRID (NON GCC)', 'AXL ', 'LIMITED 4X4', 'SE TRD AERO PK', 'GXR', 'SE TRD SPORT PK', 'DLS', 'GX', 'LE', 'HYBRID', 'LIMITED MID', 'LWB', 'SWB', 'A', 'VXR', 'SE+', 'E', '1500', '1.5', 'ADVENTURE', 'LX', '1']
  WMI: ['JTD', 'MR0', 'MR2', '5TF', 'JTM', 'MRO', '2T3', '5TD', 'JT4', 'JN6', 'JTB', 'JTE', 'LFM', 'STF', '4T3', 'MHF', '1FT', 'WMA', 'JT2', '1G6', 'ITD', 'STM', '3TD', 'JTU', 'MB0', 'JT0']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BW923', 'EW12G', 'CW6CB', 'KW923', 'KW9F3', 'BW23E', 'KW9D3', 'DW5F1', 'BW123', 'KW903', 'EW23E', 'CW12G', 'DW3FV', 'AW5F1', 'BW133', 'EW5F1', 'BW933', 'CW6CD', 'CW9CD', 'HW5F1', 'UW5F1', 'BW22E', 'AW12G', 'RWRFV', '8W133', 'BW3FV', 'BW9F3', 'RW5F1', 'GW5F1', 'DW5G1', 'KW73J', 'BW6F3', 'DW12S', 'CW8CD', 'CW126', '8W923', 'BW5F1', 'DW541', 'PW5F1', 'DW923', 'EWRFV', 'CW8CB', 'BW5G1', 'EW923', '5WRFV', 'BW541', 'AW126', 'KW5F1', 'EW21A', 'JW30F', 'DWSF1', 'BW023', 'EW41A', '8W23E', 'RW3FV', 'JW5G1', 'UWSF1', 'CW6C8', 'EWIE5', 'DWRFV', '8W933', 'EW44A', 'MWRFV', 'EW126', 'LWRFV', 'HW2ZZ', 'TW5F1', 'SW21M', 'BW9F4', '8W123', 'HW21A', 'DW51E', 'BW12S', 'BW581', 'EW1EP', 'CW8C8', 'CW9CB', '6W923', 'CW5F1', 'DW11S', 'KWS23', 'EW22E', 'JW3EH', '8W9F3', 'KW71J', 'CW8BB', 'KW8D3', 'FW12G', 'PW923']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,YARIS,4.0,HATCHBACK,W,MID,JTD,GCC,5.0,BW923
1,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,W,DLX,MR0,GCC,2.0,EW12G
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,W,GL,MR0,GCC,4.0,CW6CB
3,TOYOTA,YARIS,4.0,SEDAN,W,FLEET,JTD,GCC,4.0,KW923
4,TOYOTA,YARIS,4.0,SEDAN,W,FLEET,JTD,GCC,4.0,KW923
...,...,...,...,...,...,...,...,...,...,...
20555,TOYOTA,YARIS,4.0,HATCHBACK,W,MID,JTD,GCC,NaN,KW923
20556,TOYOTA,TUNDRA,8.0,PICKUP,W,STD (NON GCC),5TF,NON-GCC,NaN,DW5F1
20557,TOYOTA,YARIS,4.0,SEDAN,W,MID,JTD,GCC,NaN,BW923
20558,TOYOTA,YARIS,4.0,HATCHBACK,W,MID,JTD,GCC,NaN,KW9D3
20559,TOYOTA,YARIS,4.0,HATCHBACK,W,BASE,JTD,GCC,NaN,KW9D3

====================================================================================================
pos5: R
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'HIACE', 'MATRIX', 'YARIS', 'ECHO', 'SIENNA', 'HILUX', 'CAMRY', 'MR2', 'LAND CRUISER PICKUP 70', 'CELICA', 'PRADO', 'LAND CRUISER', 'AVANZA', 'SELICA', 'COROLLA SEDAN', 'COROLLA 1.8', 'TOYOTA COROLLA', 'COROLLA 1.3', 'TOYOTA', 'COROLLA 1.6', '4RUNNER', 'BZ4X', 'INNOVA', 'COROLLA ']
  bodyType: ['SEDAN', 'SALOON', 'PANEL VAN', 'HATCHBACK', 'MPV', 'ESTATE', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PICK UP', 'MINI BUS', 'COUPE', 'STATION', 'VAN', 'SUV', 'BUS', 'PICKUP']
  pos5: ['R']
  trim: ['XLI', 'XLI MID', 'STD (NON GCC)', 'GLI TOP', 'STD', 'XLI TOP', 'GLI TOP LTH', '1.8', 'LE (NON GCC)', 'BASE', 'XLE (NON GCC)', 'GL', 'GLI', 'DLX', 'DL', 'DLS', 'SED', 'PREMIUM', 'LX', 'GXR', 'TX', 'GLX', 'TXL3', 'EXR', 'GLS', 'T', 'XLI EXECUTIVE', 'GT', 'STANDARD', 'SL', 'CAR TRIM', 'SE', '1', 'S', 'LE', 'GXR TOP', 'CE (NON GCC)', 'SR5 (NON GCC)', 'VX', 'DLX TOP', 'PRO', 'GX', 'HEV', 'XSE']
  WMI: ['JTD', 'JT4', '1NX', '2T1', 'JTC', '5TD', 'MM7', 'LFM', 'MRO', 'MR0', 'TNX', 'LWL', '1GC', 'INX', 'LTV', 'JTF', 'JTL', '2TI', '211', 'JTE', 'JT0', 'MPA', '1C8', '1C6', '5XX', 'J1D', 'JMY', 'JN8', 'JTA', 'JDT', 'STD', '1V2', 'JED', 'JTU', 'UTD']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BR23E', 'BR42E', 'BR22E', 'ER23E', 'BR32E', 'ZR119', 'BR40E', 'BR38E', '8R23E', 'KR32E', 'KR30E', 'DR32T', 'FR119', 'BR30E', 'BRKEC', 'KRKEC', 'UR4DA', 'ARE0C', 'FR22G', 'BR12E', 'BR28E', 'NRRTX', 'HR33N', 'BR18E', 'ARE2C', '8R22E', 'YRKEC', 'BRZ3E', '8R32E', 'FR320', 'BR22F', 'LR73J', '8R42E', '3R22E', 'ER22E', 'ER42E', 'XRKEC', 'BR43E', '8RI2E', 'ARCAJ', 'FR73J', 'JRKEC', 'ER33P', 'RR7GT', 'SRFJT', 'BR406', 'GR4A6', 'SRCSL', 'AR05Y', 'FR226', 'TR2CA', 'AR9AJ', 'KR38E', '2R119', 'JR14T', '0RV43', 'GRKEC', 'CRKEC']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,R,XLI,JTD,GCC,4.0,BR23E
1,TOYOTA,COROLLA,4.0,SEDAN,R,XLI MID,JTD,GCC,4.0,BR23E
2,TOYOTA,COROLLA,4.0,SEDAN,R,XLI,JTD,GCC,4.0,BR42E
3,TOYOTA,COROLLA,4.0,SEDAN,R,XLI,JTD,GCC,4.0,BR22E
4,TOYOTA,COROLLA,4.0,SEDAN,R,XLI MID,JTD,GCC,4.0,ER23E
...,...,...,...,...,...,...,...,...,...,...
10324,TOYOTA,COROLLA,4.0,SEDAN,R,XLI,JTD,GCC,NaN,ER23E
10325,TOYOTA,COROLLA,4.0,SEDAN,R,XLI,JTD,GCC,NaN,BR23E
10326,TOYOTA,COROLLA,4.0,SEDAN,R,XLI,JTD,GCC,NaN,BR23E
10327,TOYOTA,COROLLA,4.0,SEDAN,R,XLI,JTD,GCC,NaN,BR23E
10328,TOYOTA,COROLLA,4.0,SEDAN,R,XLI,JTD,GCC,NaN,BR23E

====================================================================================================
pos5: U
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['FJ CRUISER', 'LAND CRUISER', 'FORTUNER', 'PRADO', 'LAND CRUISER PICK UP', 'COROLLA', 'COROLLA CROSS', 'LAND CRUISER PICKUP 70', 'FJ', 'HILUX', '4RUNNER', 'TACOMA', 'LAND CRUISER 70', 'MATRIX', 'RAV4', 'TUNDRA', '4 RUNNER', 'TOYOTA LAND CRUISER', 'LAND CRUISER PRADO', 'SCION', 'TOYOTA ALTIS', 'TOYOTA TACOMA', 'بيك اب كابينه مزدوجه', 'LAND CRUISER PICK UP CARGO', '25 LP SC4X44.0L MT', 'HD 4X4', 'TAKOMA', 'LAND CRUISER / STATION', '25 LP SC 4X4 P4.0 MT', 'PREVIA', 'CAMRY', 'RUNNER', 'TOYOTA 4RUNNER', 'TOYOTA PRADO', 'YARIS', 'HIACE', 'LAND CRUISER GX', 'LAND CRUISER/PICK UP CARGO', 'HILUX ADVENTURE', 'COROLLA 1.8', 'FORERUNNER', '1.8 XS', 'لاند كروزر', '26 LP SC 4X4 P4.0L AT', 'LAND CRUISER - PICK UP CARGO', 'COROLLA 1.3', 'GXR RA(STATION WAGON)']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'SEDAN', 'SUV- CROSSOVER', 'PICK UP SINGLE CAB', 'STATION', 'PICK UP', 'PICKUP', 'HATCHBACK', 'LIGHT VEHICLE', 'MPV', 'PICKUP DOUBLE CABIN', 'PICK UP DOUBLE CABIN', 'MINI BUS', 'COUPE', 'BUS', 'PICKUP DOUBLE CAB']
  pos5: ['U']
  trim: ['VXR', 'TOP', 'EXTREME', 'BASE', 'GXR', 'TX', 'VX', 'XLI', 'VX MID', 'EXR', 'SR5', 'S TRD SPORT PK', 'SE', 'XLI EXECUTIVE', 'GLI', 'SE+', 'LX', 'GXR TOP 60TH ANNIV. XTREME', 'STD', 'GL', 'LX AC PWR OPT', 'LX WINCH', 'TX-L', 'LIMITED', 'SC', 'XLI TOP', 'GX TOP', 'STD (NON GCC)', 'DLS', 'TX-L TOP', 'G', 'LE', 'GLS', 'GX', 'ADVENTURE', 'SAFARI', 'HT SWB', 'GXR MID', 'GXR GT', 'XL', 'PLATINUM', 'SR5 (NON GCC)', 'STD D', 'GXR TOP', 'GX MID', 'GLX', 'VX TOP LTH', 'VX1', 'GXR2', 'FJ STD', 'GXR TOP DMST', 'CTD', 'HT VXR', '1', 'GXR1', 'STD AC', 'GXR FMST', 'EX', 'DX', 'VX2', 'GXR SOD D/AC AW', 'TC (NON GCC)', 'XTREME', 'T', 'TXL2', 'GXR4', 'HARD TOP', 'SGL', '0', 'X', 'DLX', 'TRIM', 'BLACK EDITION', 'GR SPORT', 'S', 'LS', 'LUXURY', 'GXR TOP FMST', 'TXL1', 'GXR-V', 'PIKUP', 'PREMIUM', 'VXR BASE', 'PICKUP', '4WD', '60TH', 'TXL3', 'TRD SPORT', 'TRD', 'GR-S', 'LTZ', 'GXR3', 'SPORT', 'NON GCC', 'A', '6', 'GLI TOP', 'STANDARD', 'E', 'STATION1', 'EXCLUSIVE', 'GRD', 'VX-L TOP', 'PICKUP ', 'PICK UP', 'STANDER', '1500 CREWCAB SLE Z71', 'GL DECKLESS', 'TR', 'DOUBLE CABIN ', 'SEDAN', 'DLX TOP', 'GXL', 'LXI', 'GXR MID XTREME', 'DC', 'GXR MID 60TH ANNIVERSARY', 'ST', 'SR', 'DL', 'SE T2', 'SGLX', 'LE PLATINUM CITY', 'STATION', 'VXR TOP', 'SPORTS BASIC', 'GXR TOP 60TH ANNIV. ']
  WMI: ['JTE', 'JTM', 'MHF', 'JIF', 'MR1', '1NX', '2T1', 'JTD', 'RKL', '5YF', 'JTF', 'MR0', 'LFM', '5TE', '5TF', 'MHE', '3TM', 'INX', 'SYF', 'MRO', 'JTK', '5TB', 'JIM', 'JTB', '5XX', '211', 'JTL', 'YAR', 'MRI', 'MAF', 'YV2', 'LVG', '1TM']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BU11F', 'HU09J', 'YU59G', 'AUBBJ', 'JU9FJ', 'LU73J', 'BU25J', 'BU4EE', 'BU3FJ', 'AUCBJ', 'JU3FJ', 'BU9FJ', 'BURHE', 'KUAAG', 'BUSFS', 'BU40E', 'BU8FS', 'KU8FS', 'BU&CD', 'HU01J', 'BU5JR', 'CU1BR', 'BU8CD', 'DU09J', 'AU7BJ', 'LU42N', 'HU8CD', 'EU73J', 'FU71J', 'UU4EN', 'AU25J', 'KUBAG', 'LU71J', 'ZU14R', 'KUBFS', 'BUT1F', 'HU093', 'KU4EE', 'BU4BF', 'LU4EN', 'BU14R', 'JU521', 'AU88J', 'FU73J', 'BU253', 'BU11J', 'RU5JR', 'MU4FN', 'BUIIF', 'RU71J', 'BU71J', 'ZU5JR', 'KU5BF', '8U4EE', 'LU521', '8U11F', 'YU596', 'KU104', 'RU341', 'BU3AE', '8U3FJ', 'ZU11F', 'AUTBJ', 'BU17R', 'KU40E', 'BUTTF', 'KU72N', 'ZU17R', 'CU09J', 'JU8FJ', 'JUNFJ', '8URHE', 'KU5JR', '8U40E', 'RU541', '8U8CD', 'TU4GN', 'UU5JR', 'JU4GN', 'UU42N', 'MU52N', 'EU11F', 'BU29J', 'BUBFS', 'FU5JR', 'HU5JR', 'LU5JR', 'LU5F1', 'BUL1F', 'LU733', 'GU09J', 'NU5JR', 'GU4L3', 'AU78J', 'JU321', 'JU62N', 'BU26J', 'KU8F5', 'BU01F', 'JU03J', 'ZU4BF', 'HUD9J', 'BUSFJ', 'KU4HN', 'XU9HM', 'JU9EJ', 'KUSFS', 'HU08J', 'YU590', 'DU09T', 'TU62N', 'BUJFJ', 'AUZBJ', 'YU5F1', 'AUF0A', 'AUBB3', 'MU5JR', 'BU3EJ', 'NU5F1', 'BUSCD', 'JU9FI', 'JU9F1', 'CU923', '8U5CD', 'HU091', 'BURNE', 'BU8F5', '8U25J', 'EU3FJ', 'CU18R', 'HUD3J', 'EU5JR', 'JUGFJ', 'BU5IF', 'TU22N', 'PU5JR', '2U14R', 'BU258', 'BU250', 'HUOTJ', 'BU11E', 'IUSFI', '8U71J', 'JU09J', 'BUTIF']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,FJ CRUISER,6.0,SUV,U,VXR,JTE,GCC,5.0,BU11F
1,TOYOTA,FJ CRUISER,6.0,SUV,U,TOP,JTE,GCC,NaN,BU11F
2,TOYOTA,FJ CRUISER,6.0,SUV,U,EXTREME,JTE,GCC,NaN,BU11F
3,TOYOTA,FJ CRUISER,6.0,SUV,U,BASE,JTE,GCC,5.0,BU11F
4,TOYOTA,FJ CRUISER,6.0,SUV,U,EXTREME,JTE,GCC,5.0,BU11F
...,...,...,...,...,...,...,...,...,...,...
23439,TOYOTA,FORTUNER,6.0,SUV,U,VXR,MHF,GCC,NaN,BU8FS
23440,TOYOTA,LAND CRUISER,6.0,SUV,U,VXR,JTM,GCC,NaN,AU7BJ
23441,TOYOTA,LAND CRUISER PRADO,6.0,SUV,U,GXR,JTE,GCC,NaN,BU3FJ
23442,TOYOTA,COROLLA CROSS,4.0,SUV,U,XL,RKL,GCC,NaN,KUBAG
23443,TOYOTA,HILUX,6.0,PICKUP,U,GLX,MR0,GCC,NaN,HU8CD

====================================================================================================
pos5: D
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'PREVIA', 'PRIUS', 'CAMRY', 'COROLLA', 'HILUX', 'AVALON', 'CROWN KLUGER', 'JUSTIN BIEBER X VESPA 150 E5 GSO (SCOOTER)', 'TACOMA', 'HIGHLANDER', 'RUMION', 'COASTER', 'RAV 4', 'SUPRA', 'VIOS', 'LAND CRUISER', 'MODEL 2022', 'HIACE', 'LAND CRUISER PICK UP', 'CAMRY HYBRID']
  bodyType: ['SUV', 'MPV', 'HATCHBACK', 'SEDAN', 'PICK UP DOUBLE CAB', 'BUS', 'PICK UP SINGLE CAB', 'COUPE', 'PANEL VAN', 'MINI BUS', 'PICK UP', 'STATION', 'PICKUP']
  pos5: ['D']
  trim: ['FABRIC', 'BASE', 'DLX', 'STD (NON GCC)', 'GL', 'S', 'MID', 'SE', 'GLI', 'EXR', 'PW CL', 'XLE', 'C (NON GCC)', 'LE', 'GL2', 'SE+', 'LIMITED PREMIUM', 'XLE TOURING', 'XLI', 'SR5 (NON GCC)', 'GLX SPORT Z', 'LWB', 'STD', 'GXR', 'DL', 'ECO', 'ICONIC', 'GLE', 'DYNAMIC', 'EX', 'GLE HEV BLACK EDITION', 'LIMITED', 'DLS', 'EXECUTIVE', 'STD  (NON GCC)', 'DX', 'LIMITED HEV', 'GL LTH', 'TOP', 'ADVENTURE', 'TOP LTH', 'GLX', '1']
  WMI: ['JTE', 'JTM', 'JTD', '4T1', 'JT4', 'ZAP', 'MA1', 'LFM', '3TY', 'KMJ', '3N6', 'JN6', 'JM3', '5TD', 'MNT', 'JHD', 'LPS', '1C6', 'KNC', 'VR3', 'L3H', 'JT2', 'MDH', '2HN', '454', 'RKT', 'SAL', 'UTD', 'LK6', '1N6', 'LSY', 'LZY', 'JJ7', 'LVG', 'JTV', 'UTM', 'JTN']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['HD20V', 'BD31V', 'GD34M', 'KDTB3', 'GD52M', 'BD1FK', 'BD33V', 'BDMHE', 'ZD33V', 'GD32M', 'GD54M', '5D3BV', 'BD32V', 'VD10A', 'ZD31V', 'BD35V', 'GD20V', 'BD1EB', '8D31V', '8D33V', 'MD350', 'RD2VF', 'JD7BN', 'ZD32V', '6D32M', 'MD121', '8D1FK', 'KD5HN', 'JDAHN', 'DD21A', 'ND22S', 'HD17F', 'DD2EY', 'HD23S', 'SD35E', 'KDRBH', 'DD23S', 'BDOES', '6D52M', 'KDRAH', 'FD3HL', 'ED3KA', 'RD7KT', 'SD011', '8D35E', 'ZD35V', 'ED9HP', 'MD352', 'MD351', 'FDABB', 'BD317', 'DD82A', 'BD0FA', 'YD282', '5DDDD', 'RD483', 'LDHAD', 'GD21A', 'ADAE2', 'BD0CT', 'HDAAA', 'ED1EK', 'TDTD6', 'BDF1J', 'BD23S', 'SD911', 'BDIEB', 'DD22S', '6D54M', 'EDABB', 'BD74K', 'HD21A', 'FDA88', 'FDAB8', 'BD337', 'ED31V', 'VD11E']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,RAV4,4.0,SUV,D,FABRIC,JTE,GCC,5.0,HD20V
1,TOYOTA,RAV4,4.0,SUV,D,BASE,JTM,GCC,5.0,BD31V
2,TOYOTA,RAV4,4.0,SUV,D,BASE,JTM,GCC,5.0,BD31V
3,TOYOTA,PREVIA,4.0,MPV,D,DLX,JTE,GCC,5.0,GD34M
4,TOYOTA,PRIUS,4.0,HATCHBACK,D,STD (NON GCC),JTD,GCC,5.0,KDTB3
...,...,...,...,...,...,...,...,...,...,...
4070,TOYOTA,RAV4,4.0,SUV,D,BASE,JTM,GCC,NaN,BD31V
4071,TOYOTA,RAV4,4.0,SUV,D,MID,JTM,GCC,NaN,BD33V
4072,TOYOTA,PREVIA,4.0,SUV,D,GL,JTE,NON-GCC,NaN,GD52M
4073,TOYOTA,CAMRY HYBRID,4.0,SEDAN,D,SE,4T1,GCC,NaN,BD1FK
4074,TOYOTA,RAV4,4.0,SUV,D,MID,JTM,GCC,NaN,BD33V

====================================================================================================
pos5: F
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'CAMRY', 'RAV4', 'RUSH', 'AVANZA', 'TOYOTA CAMRY', 'CROWN', 'AVALON', 'LITEACE', 'ZELAS', 'HILUX', 'SCION', 'RAV 4', 'SIENNA', 'SALOON', 'DAINA', 'HIACE', 'DYNA', 'HIGHLANDER', 'COROLLA', 'SUPRA', 'PRADO', 'C-HR', '1998', 'LAND CRUISER', 'FLHTK', '26 YA HB P 1.6L AT TURBO GR RA(CAR)', 'كامرى', 'SPINA', 'LITE ACE', 'PICKUP', 'TOYOTA RUSH', 'DYNA VAN CARGO', 'SOLARA', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'MPV', 'SALOON', 'PANEL VAN', 'VAN', 'COUPE', 'PICK UP DOUBLE CAB', 'HATCHBACK', 'CARGO VAN', 'PICK UP SINGLE CAB', 'PICKUP', 'STATION', 'COUPE/CABRIOLET', 'MOTORCYCLE', 'TRUCK', 'CONVERTIBLE']
  pos5: ['F']
  trim: ['E', 'GL', 'S', 'LE', 'GXR', 'SE+', 'SE', 'EX', 'VXR', 'GRANDE', 'LIMITED', 'VX', 'BASE', 'STD', 'GX', 'GLX', 'XLE', 'STD (NON GCC)', 'EXR', 'XLE (NON GCC)', 'G', 'GLX SPORT Z', 'PLATINUM', 'XLI', 'GLE', 'MID', 'BE', 'DLX', 'YX', 'GLI', 'SPORT', 'XLE HEV', 'T', 'Y PLUS', 'GR', 'TC (NON GCC)', 'GLS', 'LE (NON GCC)', 'STANDARD', 'DX', 'PICKUP', 'GLE HEV', 'GLI TOP', 'STD CARGO', 'DLS', 'GR BLUE EDITION', 'PW CL', 'GL DECKLESS', 'GLX PREMIUM', 'XL', 'EXCLUSIVE', 'MPV', 'S TRD AERO PK', 'SGLX', 'DL', 'TRIM', 'YA', '60TH', '1', 'Y']
  WMI: ['MR2', '6T1', '4T1', 'JTN', 'JTM', 'MHK', 'JTD', '2T3', '4T4', 'JT2', 'JTK', 'JHG', 'JT0', '213', '4T3', '2T1', 'LEF', 'KPD', 'LVG', 'JTH', 'LJN', 'WAU', '5T1', 'VF3', 'JHF', 'WDD', '6TT', 'JD2', '4TI', 'ZFC', 'LFM', '55S', 'LM6', 'JTJ', 'JHH', '671', '471', 'LHP', 'KMH', 'NMT', 'ST1', 'JYM', '5HD', 'ZT3', '611', 'L3A', '4T0', 'JTC', 'LFB', 'W1K', '474', 'YSM', 'LET']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BF9C3', 'BF9FK', 'BF3EK', 'BF9HK', 'RF9EV', 'BF4FK', 'BF1FK', 'EF8BF', 'MF53F', 'ZF9EV', 'DF4EV', 'BF32K', 'ZFREV', 'BF4HK', 'BF4DV', 'WF9EV', 'DF9EV', 'AFAAF', 'BF28B', 'BF38K', 'EF8CF', 'ZF4DV', 'RFREV', 'BF9EV', 'RFR3V', 'MF5CF', 'BF8C3', 'MF5BF', 'WFREV', 'BFREV', 'MF52F', 'YFREV', 'BF31F', 'BF30K', 'DFREV', 'BF31V', 'BF22K', 'BF28K', 'JF5C7', 'JF4DV', 'ZF33V', 'MFSCF', 'BF33V', 'UF117', 'DF4DV', 'EFHCF', 'NFREV', '8F22K', 'JFREV', '8F1FK', 'YF4DV', '8F30K', 'BF46K', 'BF12K', 'EF9FK', '8F9FK', 'YF4EV', 'KF4DV', 'AF4E3', 'BF32V', '2FREV', '8F4HK', 'WF4DV', '2F9EV', 'RF4DV', 'MFSBF', 'ZF13C', 'BFIFK', 'ZF31V', '8F32K', '8F3EK', 'CF28P', 'EF88F', 'AFCG2', 'EF12K', '8F9HK', 'KFDNN', 'ZF19C', 'EF76A', 'BF5C2', 'ZF35V', 'EFBBF', 'TFUC5', 'BF6C3', '9FD8T', '8F4FK', '7FNFU', 'UF11H', 'ZF4CB', '8F4DV', 'YF9EV', 'TFU2K', 'BF18B', 'MF929', '8FREV', 'AFZBG', 'BF9FR', '2F33V', '8FIFK', 'AF54K', 'WF8HB', 'AFABF', 'HF10U', 'BF12B', 'CF22P', 'DF4EB', 'BF35V', 'BF31E', '8F31F', '8F9C3', 'UFJ1H', 'EFBCF', 'SFABD', 'WF4CB', 'FF41C', 'BF9JE', 'BF3FK', 'EF4HK', 'GF4JB', '1FHPC', 'EFSBF', 'DF4EU', 'EFABF', 'KFNM3', 'BF23K', 'BFTFK', '8F38K', 'FF719', 'GF46X', '1F009', 'AF4CB', 'WF4JB', 'EFAVS', 'UFJ17', 'YFAG2', '8F9EV', 'BF32X', '8F28K', 'DFAEV', 'EFBC3', 'JFSC7', 'EF8C3', 'FF22P', 'MFWBY', 'AF047']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,YARIS,4.0,SEDAN,F,E,MR2,GCC,4.0,BF9C3
1,TOYOTA,CAMRY,4.0,SEDAN,F,GL,6T1,GCC,4.0,BF9FK
2,TOYOTA,CAMRY,4.0,SEDAN,F,S,6T1,GCC,4.0,BF9FK
3,TOYOTA,CAMRY,4.0,SEDAN,F,LE,4T1,GCC,4.0,BF3EK
4,TOYOTA,CAMRY,4.0,SEDAN,F,LE,JTN,GCC,4.0,BF9HK
...,...,...,...,...,...,...,...,...,...,...
22881,TOYOTA,CAMRY HYBRID,4.0,SEDAN,F,SE,6T1,GCC,NaN,BF9FK
22882,TOYOTA,CAMRY HYBRID,4.0,SEDAN,F,S,6T1,GCC,NaN,BF9FK
22883,TOYOTA,CAMRY HYBRID,4.0,SEDAN,F,SE,JTN,GCC,NaN,BF4HK
22884,TOYOTA,CAMRY HYBRID,4.0,SEDAN,F,S,6T1,GCC,NaN,BF9FK
22885,TOYOTA,AVANZA,4.0,SUV,F,SE,MHK,GCC,NaN,MF5CF

====================================================================================================
pos5: E
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'PREVIA', 'RAV4', 'HILUX', 'COROLLA', 'HIACE', 'AURION', 'COASTER', 'YARIS', 'ALPHARD', 'CROWN', 'LAND CRUISER', 'STATION', 'SALOON', 'SCION', 'SICION', 'VELOZ', 'AVANZA', 'TUNDRA', 'TACOMA', 'RAV 4', 'PRADO', 'VENZA', 'SIENNA', 'TOYOTA CAMRY', 'CELICA', 'CAMRY SOLARA', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'MPV', 'SUV', 'PICK UP DOUBLE CAB', 'MINI BUS', 'PANEL VAN', 'MINI BUS HIGH ROOF', 'BUS', 'CARGO VAN', 'PICK UP SINGLE CAB', 'STATION', 'COUPE', 'SALOON', 'PICKUP', 'PANEL VAN HIGH ROOF', 'WINDOW VAN', 'HATCHBACK']
  pos5: ['E']
  trim: ['XLI', 'GLX', 'LE', 'GLI', 'SE', 'GL', 'DLX', 'BASE', 'EXR', 'EX', 'S', 'XLI EXECUTIVE', 'DX', 'STD', 'MID', 'DL', 'X', 'BUS', 'XLE (NON GCC)', 'DLS - STD ROOF', 'YX', 'STD (NON GCC)', 'TOURING', 'SL', 'GLE', 'XLI TOP', 'PLATINUM', 'GRANDE', 'GXR', 'DLS', 'XLI EXECUTIVE MR', 'CABRIO', 'Y PLUS', 'GLS', 'GLI HEV', 'SR', 'BE', 'SR5 (NON GCC)', 'GLI TOP', 'EXCLUSIVE', 'VXR', 'ADVENTURE 1ST EDITION', 'LE HEV', 'A', 'GLX SPORT Z', 'ADVENTURE', '40 TFSI S-LINE', 'GLI TOP LTH', 'LIMITED', 'SV', 'EX MID', 'GX', 'LWB HIGH ROOF', '4', '1']
  WMI: ['6T1', '4T1', 'JTD', 'JTN', '4T4', 'JTM', '8T1', 'KMF', 'JNB', 'JT2', 'JN6', '1NX', '2T1', '6TI', 'LVG', '4TI', '4TT', '411', 'JTG', '5T1', 'KNC', 'MR2', '1FD', 'ITN', 'LRR', '611', 'GT1', 'JTF', 'LFM', 'JN8', 'JTL', 'SCR', 'JT4', 'JTK', 'LET', 'MHF', 'VF3', 'MHK', 'JHM', 'LGD', 'LEF', 'SMV', '6T0', '471', 'BT1', '8LT', '671', 'IN6', '4T3', '1G6', '6TB', 'RKL', 'ST1', 'ET1', '3T1']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BE32K', 'BE42K', 'BE33K', 'BE30K', 'GE52M', 'BE46K', 'REREV', '8E32K', 'GE17F', 'BE36K', 'AE09V', 'AE54S', 'AE00B', 'DE32K', 'BE4EE', 'BE6DS', 'BE40K', 'AE52S', 'CE38P', 'BE6BS', 'AE09B', '8E46K', 'CECB8', 'AE04B', 'BE3EK', 'ZE32V', 'BE6AS', 'PE32K', 'FE52S', 'SE014', 'BE9B3', 'FE718', 'XE4FS', '6E52M', 'AE00E', 'AEACH', 'FE53S', 'TEKP1', 'BE42J', 'AE82G', 'AE525', 'AE09W', 'DE626', 'BE85B', 'AE2KP', 'BE24K', 'KE50E', 'BECEK', 'AE51S', 'AE09E', 'TEB3N', 'EE426', 'DE167', 'AECG2', '8E30K', 'FE54S', 'BE6CS', '8E42K', 'AE53S', 'BE38K', 'FE728', 'SE034', 'ZE4FE', 'AE1BY', '8E33K', '7ENFU', 'AECB8', 'ME53F', 'AE04E', 'ZE287', 'BE4GK', 'HEJ1F', 'AECG3', 'DE4EV', 'ZER2D', 'WE23E', 'AE94K', 'BE9FK', 'AEAA1', 'BE23K', '2EFV4', 'ZE9EV', 'AE07B', 'ZE11A', 'KE52Y', '1E33K', 'BE40E', 'NE426', 'BE44K', 'GES2M', 'EE9HE', 'WE3FN', 'AE94A', 'PE30K', 'DE82A', 'EE32K', 'BE9HE', 'CE22P', 'AE1EY', 'FE22P']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,CAMRY,4.0,SEDAN,E,XLI,6T1,GCC,4.0,BE32K
1,TOYOTA,CAMRY,4.0,SEDAN,E,XLI,6T1,GCC,4.0,BE32K
2,TOYOTA,CAMRY,4.0,SEDAN,E,GLX,6T1,GCC,4.0,BE42K
3,TOYOTA,CAMRY,4.0,SEDAN,E,LE,4T1,GCC,4.0,BE32K
4,TOYOTA,CAMRY,4.0,SEDAN,E,GLI,6T1,GCC,4.0,BE42K
...,...,...,...,...,...,...,...,...,...,...
27662,TOYOTA,CAMRY HYBRID,4.0,SEDAN,E,GLX,6T1,GCC,NaN,BE42K
27663,TOYOTA,CAMRY HYBRID,4.0,SEDAN,E,GLI,6T1,GCC,NaN,BE42K
27664,TOYOTA,CAMRY HYBRID,4.0,SEDAN,E,XLI,4T1,GCC,NaN,BE32K
27665,TOYOTA,CAMRY HYBRID,4.0,SEDAN,E,1,6T1,GCC,NaN,BE32K
27666,TOYOTA,CAMRY HYBRID,4.0,SEDAN,E,GLI,6T1,GCC,NaN,BE32K

====================================================================================================
pos5: Z
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'CAMRY', 'COASTER', 'SIENNA', 'C-HR', 'TACOMA', 'TOYOTA CAMRY', 'AVALON', 'HILUX', 'HIGHLANDER', 'FJ CRUISER', 'ALPHARD', 'INNOVA', 'TUNDRA', 'HAI LUX', 'TAKOMA', 'SENA VAN PASSENGER', 'YARIS', 'COROLLA LI', 'COROLLA 1.6/SEDAN', 'FORTUNER', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'BUS', 'MPV', 'SUV', 'PICK UP DOUBLE CAB', 'SALOON', 'PICK UP SINGLE CAB', 'PICK UP', 'LIGHT VEHICLE', 'PICK UP DOUBLE CABIN', 'PICKUP', 'STATION']
  pos5: ['Z']
  trim: ['XLI', 'SE+ ANNIVERSARY EDITION', 'STD', 'SPORT', 'XLE (NON GCC)', 'VX', 'SR5 (NON GCC)', 'SE', 'GLE-X HEV 40TH ANNIV', 'LE STD', 'SE+', 'XSE (NON GCC)', 'S PLUS', 'S', 'LIMITED', 'XLE TOURING', '40TH ANNIVERSARY EDITION', 'DLX', 'LE', 'LE (NON GCC)', 'GX', 'XLE', 'GXR', 'GLE HEV', 'TRD', 'PLATINUM', 'LIMITED (NON GCC)', 'DLS', 'LE HEV', 'LUMIERE HEV', 'LIMITED PREMIUM', 'STANDER', 'GL', 'GLE', 'STD (NON GCC)', 'TOURING', 'GF', 'PICK UP', 'STANDARD', 'XLI TOP', 'E', 'CAR TRIM', 'A', 'MPV', 'GLI', '1500', 'EXR', 'GRANDE HEV 40TH ANNIV', 'VXR', '40TH ANNIVERSARY EDI', 'SE+ ANNIVERSARY EDIT']
  WMI: ['RKL', 'JTN', 'JTC', 'JTD', '5TD', 'NMT', '3TM', '4T1', '5TF', 'JTF', '3TY', 'JT4', 'JN1', 'JRN', 'ZGU', 'JNC', 'MHF', 'STY', '5HD', '25T', 'STD']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BZ42E', 'BZ4HK', 'FZ418', 'KZ3DC', 'KZ4BX', 'CZ5AN', 'XZ3DC', 'KZ1AK', 'DZ5BN', 'YZ3DC', 'BZ1FB', 'EZ426', 'KZ626', 'EZ496', 'AZ496', 'GZRBH', 'BZAHK', 'ZZRFH', 'SZ5AN', 'HZRBH', 'ZZ3DC', 'DZ3DC', 'JZ3DC', 'FZRBH', 'AZ1FB', 'DZRBH', 'JZRFH', 'GZ5AN', 'GZ3DH', 'BZ1HK', 'DZRFH', 'AZ5CN', 'DZ626', 'HZ14S', 'ZZRAH', 'JZ1FB', 'FZ1FB', 'BZRFH', 'BZ4ZE', 'RZ5CN', 'GZ1FB', 'GZRAH', 'EZ42E', 'YZRAH', 'DZSBN', 'KZ4DX', 'KZA00', '8Z4HK', 'HZ04S', 'UZD1H', 'DZ1FB', 'BZ9F3', 'BZ42F', 'CZRAH', 'YZRFH', 'KZABX', '1ZH15', 'LZRBH', 'DZK23', 'EZ3DC', 'NZ1AK', 'KZRFH']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,Z,XLI,RKL,GCC,4.0,BZ42E
1,TOYOTA,CAMRY,6.0,SEDAN,Z,SE+ ANNIVERSARY EDITION,JTN,GCC,4.0,BZ4HK
2,TOYOTA,COASTER,6.0,BUS,Z,STD,JTC,GCC,2.0,FZ418
3,TOYOTA,CAMRY,6.0,SEDAN,Z,SPORT,JTN,GCC,NaN,BZ4HK
4,TOYOTA,COROLLA,4.0,SEDAN,Z,XLI,JTD,GCC,4.0,BZ42E
...,...,...,...,...,...,...,...,...,...,...
7043,TOYOTA,CAMRY HYBRID,6.0,SEDAN,Z,SE,JTN,GCC,NaN,BZ4HK
7044,TOYOTA,CAMRY HYBRID,6.0,SEDAN,Z,SPORT,JTN,GCC,NaN,BZ4HK
7045,TOYOTA,CAMRY HYBRID,6.0,SEDAN,Z,SPORT,JTN,GCC,NaN,BZ4HK
7046,TOYOTA,CAMRY HYBRID,6.0,SEDAN,Z,SPORT,JTN,GCC,NaN,BZ4HK
7047,TOYOTA,CAMRY HYBRID,6.0,SEDAN,Z,SPORT,JTN,GCC,NaN,BZ4HK

====================================================================================================
pos5: V
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TUNDRA', 'COROLLA', 'COROLLA 1.6', 'LAND CRUISER PICKUP 70', 'LAND CRUISER', 'RAV4', 'HIACE', 'LAND CRUISER PICK UP', 'HILUX', 'RAV 4', 'CAMRY', 'YARIS']
  bodyType: ['PICK UP DOUBLE CAB', 'SEDAN', 'SALOON', 'PICK UP SINGLE CAB', 'SUV', 'PANEL VAN', 'PICK UP', 'STATION', 'PICKUP', 'AMBULANCE', 'COUPE', 'HATCHBACK']
  pos5: ['V']
  trim: ['STD (NON GCC)', 'XLI', 'XLI TOP', 'XLI MID', 'SALOON', 'SC', 'GX', 'BASE', 'GL', 'VXR', 'EXR', 'STD AC', 'VX', 'DLX', 'VXR TOP', 'SAFARI', 'SPORT', 'LX', 'GXR', 'GLI', 'FLEET', 'COMFORT', 'SU', 'GLI TOP', '10TH VICTORY EDITION', 'STD', 'GLE', 'PREMIUM', 'TRIM', 'MID', 'BLACK EDITION', 'SE T2', 'GR-S', 'GXR TOP DMST', '1']
  WMI: ['5TF', 'RKL', '5TB', 'JTF', 'STB', 'LFM', 'JD4', 'STF', 'JTM', '1D7', 'JTD', 'JTE', '5T8', '5NF', 'JNK', '3D7', '2D4', 'MRO', '1HG', 'ZCF']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['MV521', 'BV42E', 'DV541', 'BV541', 'LV73J', 'KV521', '8V71J', 'DV581', 'JV36F', 'TV182', 'BV581', 'HV01J', '8V42E', 'RV541', 'JV03J', 'BV71J', 'EV541', 'HV09J', 'RV71J', 'TV192', 'UV182', 'KV36F', 'JV521', 'RV1GP', 'RV581', 'CV541', 'SV541', 'RV42E', 'EV73J', '8V541', 'KV30F', 'TV092', 'BV61E', 'BV426', 'JV1ET', 'BVV13', 'KV32F', 'FV47V', 'BVV92', 'PV42E', 'CV12G', 'AVV5F', 'EV581', 'TV082', 'CV1F4', 'CV52B', 'LV71J', 'DV09J', 'LV521']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,V,STD (NON GCC),5TF,GCC,4.0,MV521
1,TOYOTA,COROLLA,4.0,SEDAN,V,XLI,RKL,GCC,4.0,BV42E
2,TOYOTA,COROLLA,4.0,SEDAN,V,XLI TOP,RKL,GCC,4.0,BV42E
3,TOYOTA,COROLLA,4.0,SEDAN,V,XLI MID,RKL,GCC,4.0,BV42E
4,TOYOTA,COROLLA,4.0,SEDAN,V,XLI,RKL,GCC,4.0,BV42E
...,...,...,...,...,...,...,...,...,...,...
3517,TOYOTA,TUNDRA,8.0,PICKUP,V,STD (NON GCC),5TB,NON-GCC,NaN,BV541
3518,TOYOTA,TUNDRA,8.0,PICKUP,V,STD (NON GCC),5TF,NON-GCC,NaN,KV521
3519,TOYOTA,TUNDRA,8.0,PICKUP,V,STD (NON GCC),5TF,NON-GCC,NaN,BV541
3520,TOYOTA,COROLLA,4.0,SEDAN,V,XLI TOP,RKL,GCC,NaN,BV42E
3521,TOYOTA,COROLLA,4.0,SEDAN,V,XLI TOP,RKL,GCC,NaN,BV42E

====================================================================================================
pos5: K
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['AVALON', 'RAV4', 'SIENNA', 'AURION', 'CAMRY', 'COASTER', 'ALPHARD', 'HIACE', 'HIGHLANDER', 'HILUX', 'PREVIA', 'COROLLA', 'LAND CRUISER', 'FORTUNER', '2009', 'FLTRXS', 'FJ CRUISER', 'PRADO', 'LAND CRUISER 70', 'VENZA', 'SCION', 'حافلة نقل خاص', 'SIENNA VAN', 'SENA', '4RUNNER', 'STATION', 'SIENNA(VAN)', 'MR2', 'ORION', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'MPV', 'BUS', 'MINI BUS', 'STATION', 'PICKUP', 'VAN', 'PICK UP DOUBLE CAB', 'MOTORCYCLE', 'SALOON', 'PANEL VAN', 'COUPE', 'PICK UP SINGLE CAB']
  pos5: ['K']
  trim: ['BASE', 'STD (NON GCC)', 'LE (NON GCC)', 'XLE', 'LIMITED', 'TOP', 'MID', 'LIMITED PREMIUM', 'LIMITED (NON GCC)', 'SPORT', 'XLE TOURING', 'XLE (NON GCC)', 'CE (NON GCC)', 'SE+', 'SE', 'EXCLUSIVE', 'LE', 'GL', 'LWB HIGH ROOF', 'GLE HEV', 'TOURING', 'GLX', 'LWB', 'SE (NON GCC)', 'GLI', 'SWB', 'GLS', 'GLE-X HEV 40TH ANNIV', 'STD', 'DX', 'LE HEV', 'GLI TOP', 'LE STD', '1', 'DLS', 'ADVENTURE', 'DL', 'X', 'EXR', 'DLX', 'SR5', 'GLX SPORT Z', 'VXR', 'VX', 'GRANDE HEV 40TH ANNIV', 'HT SLWB', 'GLE', 'XLI', 'HYBRID (NON GCC)', 'CE', 'S', 'GRANDE', 'ORION', 'STANDERD', 'SENA', 'TRIM', 'SR5 (NON GCC)', 'G', 'XL', 'STANDARD', 'MPV', 'GLS LOWLINE', 'SUPER SAFARI T1', 'XLI TOP', 'ROYAL EDITION', 'SED', 'STEALTH']
  WMI: ['4T1', 'JTM', '5TD', '2T3', '6T1', 'JTG', 'JT2', 'JTN', 'JT6', 'MR0', '5FP', 'STD', 'LJ1', '2GC', '5HD', 'JTH', '5T1', 'STO', '1GN', '4T3', 'WME', 'JTE', 'ZFC', '3GY', '6TD', 'WBA', 'LFM', 'WDB', 'JM7', '4TI', 'KL5', '61L', '611', 'JTF', 'CM8', 'XWB', 'KMF', '3GN', '5T0']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BK36B', 'BK31V', 'KK3DC', 'ZK22C', 'ZK23C', 'BK1EB', 'YK4DV', 'BK3DB', 'ZK31V', 'YK4CC', 'BK42K', 'BK40K', 'BK33V', 'BK4FK', 'YK3DC', 'XK3DC', 'KK4CC', 'BKIEB', 'BK32V', 'ZK3DC', 'BK46K', 'BK3EK', 'BK22C', 'ZK4DV', 'BK1FK', 'FK418', 'SK12E', 'JK4CC', 'DK3DC', 'FK718', 'JK3DC', 'FK518', '2K3DC', 'GK3DH', 'BK4DV', 'BK23C', 'ZK33V', 'DK4DV', 'DK4CC', 'RK4DV', 'SK12W', 'ZK34V', '2K23C', 'GK13E', '8K46K', '2K31V', '8K368', 'ZKRFH', 'YKRFH', 'BK34V', 'BK1E8', 'CK12G', 'BK4SK', '8K36B', 'GK26H', '8K3DB', 'BK3EH', '8K1FK', 'JK4DV', 'BK368', 'YK1F7', '8K3D8', '1KFCD', 'WK4DV', '1KBBC', 'BK35V', 'ZK29C', 'EK19T', '8K40K', '1KTP4', 'XK4DV', 'BK262', '8K33V', '2K22C', 'SK8KD', 'BK3BB', 'EK31X', '2K29C', 'SK11E', 'DKJA0', '8K1E8', 'KK4DV', 'ZK32V', 'BK29J', 'SK12C', '8K3EK', 'FK122', 'YK3F1', '8K32V', 'PK5C5', 'KKRFH', 'YKACC', 'AKCB8', '8K31V', 'ZK4CC', '8K4FK', 'AK54K', 'SK75F', 'GK12E', 'BK326', '1KBBD', 'BKRFH', 'JKRFH', 'UK42A', 'JK02P', '8K22C', '7KE43', '3K32E', 'EK12G', 'DK3EH', 'KK3EH', 'SK12F', 'XKS7B', 'EK12T', '2K33V', 'JK3EH', 'BK35B', 'VK13E']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,AVALON,6.0,SEDAN,K,BASE,4T1,GCC,4.0,BK36B
1,TOYOTA,RAV4,6.0,SUV,K,STD (NON GCC),JTM,GCC,5.0,BK31V
2,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),5TD,NON-GCC,5.0,KK3DC
3,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),5TD,GCC,5.0,ZK22C
4,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),5TD,GCC,5.0,ZK23C
...,...,...,...,...,...,...,...,...,...,...
10837,TOYOTA,SIENNA,6.0,SUV,K,CE (NON GCC),5TD,NON-GCC,NaN,ZK23C
10838,TOYOTA,AVALON,6.0,SEDAN,K,BASE,4T1,NON-GCC,NaN,BK36B
10839,TOYOTA,SIENNA,6.0,SUV,K,CE (NON GCC),5TD,NON-GCC,NaN,ZK23C
10840,TOYOTA,AVALON,6.0,SEDAN,K,LIMITED,4T1,GCC,NaN,BK1EB
10841,TOYOTA,SIENNA,6.0,SUV,K,LE (NON GCC),5TD,NON-GCC,NaN,KK3DC

====================================================================================================
pos5: 2
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'CAMRY', 'RAV4', 'COROLLA', 'HIACE', 'T 300', 'RAV 4', 'TUNDRA', 'AVALON', 'HILUX', 'COASTER', 'BZ3X', 'URBAN CRUISER', 'DAINA', 'SIENNA', 'KS01', 'WISH', 'LAND CRUISER', 'DYNA', 'TACOMA', '2008', 'PREVIA', 'INNOVA', 'CAMRY HYBRID']
  bodyType: ['HATCHBACK', 'SEDAN', 'SUV', 'PANEL VAN', 'STATION', 'PICK UP DOUBLE CAB', 'BUS', 'PICKUP', 'MPV', 'SALOON', 'MINI BUS HIGH ROOF', 'PICK UP SINGLE CAB', 'MINI BUS']
  pos5: ['2']
  trim: ['SE', 'LIMITED', 'E', 'LE', 'GXR', 'XLI', 'XLI MID', 'GLE', 'GLE-X HEV 40TH ANNIV', 'STD', 'S', 'EXR', 'GL', 'ADVENTURE', 'BASE', 'GRANDE', 'STD (NON GCC)', 'LIMITED PREMIUM', 'MID', 'GLE HEV', 'SE+', 'DLS', 'LWB', 'AIR', 'GLX', 'XLI - AW', '1500', 'DLX', 'XLE (NON GCC)', 'HYBRID', 'EX', 'Y', 'MPV', 'GLS', 'GX', 'DX H/R W/B', 'SPORT', 'XLI TOP', '1', 'SR5 (NON GCC)', 'GRANDE HEV', 'LE (NON GCC)', 'H', 'GL TOP', 'GLI', 'Y PLUS']
  WMI: ['MHF', 'JTN', 'JTB', 'JTD', 'ANE', 'MR2', 'JJ5', '4T1', 'RKL', '6T1', 'LZC', 'LHA', 'MAF', 'WDD', 'LTA', 'LVA', 'LVG', 'MZB', 'MD2', '5TD', 'MHE', 'LVC', 'NCP', 'JIN', 'WMA', 'FJ4', 'INB', 'WDB', '3TY', '3TM', 'M0F', 'MHM', '5TF']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['B29F3', 'B24HK', 'B29HK', '72SC1', 'B242E', '12001', 'K29F3', '8242E', 'B2E6K', '72AEB', 'B21HK', '72EEB', 'Z23FV', '72SK2', '1215C', '824HK', '12007', '1201D', '72SK1', 'B21FB', 'R2061', '22206', '12H2P', 'C2ZWB', 'D2DF6', 'E2815', 'A22EZ', '829F3', '12006', '32BUM', 'V2MW5', 'Y23DC', '72AEA', '022GD', 'E29F3', 'B2NWA', '72EEA', '12005', '42014', 'H25ZZ', '1202F', '12004', 'V2MWB', '02290', '829HK', '42015', 'J23DC', 'A22NE', '12402', '525AN', 'B2NBA', 'C25AN', 'B29M3', 'D23DC', 'B28F3', '12000', 'K23DC', '12003', '42010', 'D258N', '42018', '22205', '62101', 'C21FB']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,YARIS,4.0,HATCHBACK,2,SE,MHF,GCC,5.0,B29F3
1,TOYOTA,CAMRY,4.0,SEDAN,2,LIMITED,JTN,GCC,4.0,B24HK
2,TOYOTA,YARIS,4.0,SEDAN,2,E,MHF,GCC,4.0,B29F3
3,TOYOTA,YARIS,4.0,HATCHBACK,2,SE,MHF,GCC,5.0,B29F3
4,TOYOTA,YARIS,4.0,HATCHBACK,2,SE,MHF,GCC,5.0,B29F3
...,...,...,...,...,...,...,...,...,...,...
4186,TOYOTA,YARIS,4.0,SEDAN,2,E,MHF,GCC,NaN,B29F3
4187,TOYOTA,YARIS,4.0,SEDAN,2,SE,MHF,GCC,NaN,B29F3
4188,TOYOTA,YARIS,4.0,SEDAN,2,SE,MHF,GCC,NaN,B29F3
4189,TOYOTA,CAMRY HYBRID,4.0,SEDAN,2,LE,JTN,GCC,NaN,B29HK
4190,TOYOTA,YARIS,4.0,SEDAN,2,E,MHF,GCC,NaN,B29F3

====================================================================================================
pos5: L
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'PRADO', 'SCION', 'LAND CRUISER', 'YARIS', 'HILUX', 'LAND CRUISER PRADO', 'RAV4', 'CAMRY', 'TACOMA', 'TERCEL', 'TOYOTA COROLLA 2.0', 'COROLLA 1.3', 'كورولا']
  bodyType: ['SEDAN', 'SUV', 'HATCHBACK', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PICK UP', 'SALOON', 'PICKUP']
  pos5: ['L']
  trim: ['XLI', 'SE+', 'GX', 'SE', 'LIMITED', 'VX MID', 'STD (NON GCC)', 'EXR', 'GLI', 'GX TOP', 'DLX', 'VX', 'STD', 'LMV', 'SPORT', 'GLX', 'XLI EXECUTIVE', 'LIMITED TRD SPORT PK', 'GL', 'XLI MID', 'EX', 'E', 'XLI TOP', 'GLE', 'S TRD SPORT PK', 'S', 'YA', 'GXR', 'CAR TRIM', '60TH', 'TRIM', 'PLATINUM', '1', 'XLI HEV']
  WMI: ['RKL', 'JTE', 'JTD', '3MY', '1N4', '5TE', '4TA', 'JM3', 'LFM', '57W', 'JHF', 'MMM', 'JH4', 'KL7', '4TI', 'LVG', 'JTG', 'KNR', 'STE', 'LHG', 'JAA', 'SAL', '000', 'BKL']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BL9HE', 'BL29J', 'BL40E', 'DLBZV', 'BL4A9', 'DLBYV', 'AL29J', 'NL42N', 'SL35E', 'AL1CC', '8L29J', 'ML2A6', 'UL11H', 'DLBJV', 'VL52N', 'BL293', 'EL33P', 'CL968', '8L9HE', '7LHEP', 'BL42E', 'BLIHK', 'DL25R', 'RL9HE', '1L1HE', 'BLSHE', '8L0HE', 'BL0HE', 'PLM90', 'DL39M', 'TLIAK', 'YL2FV', 'BL00E', 'BL9HF', 'BL8HE', 'BLGHE']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,L,XLI,RKL,GCC,4.0,BL9HE
1,TOYOTA,COROLLA,4.0,SEDAN,L,SE+,RKL,GCC,4.0,BL9HE
2,TOYOTA,PRADO,4.0,SUV,L,GX,JTE,GCC,5.0,BL29J
3,TOYOTA,COROLLA,4.0,SEDAN,L,SE,RKL,GCC,4.0,BL9HE
4,TOYOTA,COROLLA,4.0,SEDAN,L,XLI,RKL,GCC,NaN,BL9HE
...,...,...,...,...,...,...,...,...,...,...
4926,TOYOTA,COROLLA,4.0,SEDAN,L,1,RKL,GCC,NaN,BL9HE
4927,TOYOTA,COROLLA,4.0,SEDAN,L,SE,RKL,GCC,NaN,BL9HE
4928,TOYOTA,COROLLA,4.0,SEDAN,L,SE,RKL,GCC,NaN,BL9HE
4929,TOYOTA,COROLLA,4.0,SEDAN,L,SE,RKL,GCC,NaN,BL9HE
4930,TOYOTA,COROLLA,4.0,SEDAN,L,SE,RKL,GCC,NaN,BL9HE

====================================================================================================
pos5: N
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'PRIUS', '86', 'HIACE', 'LAND CRUISER', 'TUNDRA', 'RAV4', 'HILUX', 'GR86', 'INNOVA', 'PRADO', '4RUNNER', 'ZELAS', 'CAMRY', 'TAKOMA', 'HIACE ', 'GRAND DELUX', 'ECHO', 'TACOMA (PICK UP)', 'PREVIA', 'TAKOMA PICK UP CARGO', 'SCION', 'H3', 'HAI LUX', 'TOYOTA 86']
  bodyType: ['PICK UP DOUBLE CAB', 'HATCHBACK', 'COUPE', 'PANEL VAN', 'SUV', 'PANEL VAN HIGH ROOF', 'MINI BUS HIGH ROOF', 'BUS', 'MINI BUS', 'MPV', 'PICK UP', 'PICKUP', 'STATION', 'PICK UP SINGLE CAB', 'CARAVAN', 'SEDAN', 'VAN', 'PICKUP DOUBLE CABIN', 'SALOON']
  pos5: ['N']
  trim: ['SR5 (NON GCC)', 'STD (NON GCC)', 'STD', 'GL', 'C (NON GCC)', 'VX', 'VTX', 'GLS', 'LE HEV', 'DLX', 'GTX', 'HEV', 'GLX', 'MID', 'GX', 'GXR TOP', 'GT', '1500', 'FABRIC', 'SPORT', 'VT', 'ICONIC', 'HILUX', 'LIMITED', 'DLS - STD ROOF', 'DYNAMIC', 'XLI', 'EX', 'ADVENTURE', 'TOP', 'LE', 'AT', '1500 CREWCAB SLE Z71', 'STANDARD', 'XLI MID', 'GLI', 'DLS HIGH ROOF', 'DX', 'GLE', 'S', 'FR-S (NON GCC)', 'TRD', '1']
  WMI: ['4TA', 'JTD', 'JF1', 'JTG', 'JTE', '5TB', 'LFM', 'JMY', 'JT3', '5TE', 'MM7', 'JT4', 'MMB', 'KN3', 'KN4', 'JT5', 'N1N', 'JTH', 'JA3', 'JN1', 'LS6', '5GT', 'LVG', 'LVZ', 'JT6', 'LFC', 'JNE']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['WN72N', 'KN3DU', 'ZN11B', 'ZN12B', 'HN9CP', 'BN95J', 'ZNAA1', 'JN321', 'KN5BF', 'JNP13', 'ZNBB1', 'ZN12A', 'ZN3EU', 'UN53B', 'ZN128', 'SN92N', 'ZN11A', 'UN236', 'RN81A', 'AN95J', 'ZN23B', 'HN86R', 'ZNBC1', 'JNK62', 'JNK65', 'GN87R', 'HNP6N', 'ZNBF1', 'HN87R', '8N95J', 'UN202', 'KN3DP', 'RN50R', 'ZNBE1', 'RN82P', 'GN86R', 'KN3D0', 'JNK64', 'ZNBG1', 'HNW6N', 'VN94T', '1N1EN', 'KN9CP', 'JN5BF', 'BN30F', 'HNICP', 'AN74K', 'VN52N', 'BN441', 'RN93P', 'TN12D', 'EN61S', 'UN246', 'GNP03', 'VN61F', 'ZNAE1', 'VN73K', 'HNP13', 'RN01P', 'UN346', 'UN316', 'UN41B', 'JNKG2', 'ENE0R', 'DN136', 'DN56A', 'UN24D', 'UN206', 'MN25B', 'ENKA5', '6N87R', 'VN13G', 'PN62N', 'RN341', 'NNG6P', 'ZN23A', 'ZN12E', 'TN14D']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,N,SR5 (NON GCC),4TA,GCC,4.0,WN72N
1,TOYOTA,PRIUS,4.0,HATCHBACK,N,STD (NON GCC),JTD,GCC,5.0,KN3DU
2,TOYOTA,86,4.0,COUPE,N,STD,JF1,GCC,NaN,ZN11B
3,TOYOTA,PRIUS,4.0,HATCHBACK,N,STD (NON GCC),JTD,GCC,5.0,KN3DU
4,TOYOTA,86,4.0,COUPE,N,STD,JF1,GCC,2.0,ZN12B
...,...,...,...,...,...,...,...,...,...,...
1836,TOYOTA,PRIUS,4.0,HATCHBACK,N,STD (NON GCC),JTD,NON-GCC,NaN,KN3DU
1837,TOYOTA,TOYOTA 86,4.0,COUPE,N,GT,JF1,GCC,NaN,ZN11A
1838,TOYOTA,TOYOTA 86,4.0,COUPE,N,STD,JF1,GCC,NaN,ZN12B
1839,TOYOTA,TOYOTA 86,4.0,COUPE,N,GTX,JF1,GCC,NaN,ZN12A
1840,TOYOTA,PRIUS,4.0,SEDAN,N,STD (NON GCC),JTD,NON-GCC,NaN,KN3DU

====================================================================================================
pos5: A
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['SIENNA', 'CAMRY', 'COROLLA CROSS', 'RAIZE', 'HIACE', 'COROLLA', 'PRADO', 'LAND CRUISER', 'SOLARA', 'PRIUS', 'HIGHLANDER', 'TUNDRA', 'CROWN', 'HILUX', 'COROLLA 1.6', 'COROLLA 1.3', 'LAND CRUISER PRADO', 'BZ4X', 'AVALON', 'SUPRA', '4RUNNER', 'YARIS', 'SEQUOIA', 'COROLLA 1.8', 'OTHERS', 'RAV4', 'SCION', 'FORTUNER', 'COASTER', 'TACOMA', '2022', 'TOYOTA COROLLA', 'VENZA', 'TOYOTA SUPRA', 'SIENA', 'ECHO', 'GXL RA (STATION WAGON)', '25PR 5 DR P 2.4L AT', 'MIRAI', 'TOYOTA COROLLA 1.8']
  bodyType: ['MPV', 'SEDAN', 'SUV- CROSSOVER', 'SUV', 'PANEL VAN', 'CONVERTIBLE', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'COUPE', 'PANEL VAN HIGH ROOF', 'SALOON', 'STATION', 'PICK UP SINGLE CAB', 'MINI BUS HIGH ROOF', 'VAN', 'BUS', 'WINDOW VAN', 'HALF PANEL VAN', 'WAGON', 'PICKUP']
  pos5: ['A']
  trim: ['XLE (NON GCC)', 'XLI', 'GLI', 'TURBO G RA', 'STD', 'XLI EXECUTIVE MR', 'XL', 'ADVENTURE', 'LE', 'LE (NON GCC)', 'E', 'SE', 'VXR', 'GXL', 'ICONIC', 'GXR', 'XLI MID', 'TXL1', 'STD (NON GCC)', '1794 EDITION (NON GCC)', 'XLE', 'SR', 'TXL3', 'CREWMAX CAPSTONE (NON GCC)', 'LIMITED (NON GCC)', 'PREMIUM', 'HEV GLI', 'DYNAMIC', 'XLI EXECUTIVE HEV', 'GLE', 'DLX', '1', 'LIMITED', 'VX', 'ECO', 'TXR', 'PRO', 'LE HEV', 'COUPE', 'XLE HEV', 'TRD OFF-ROAD', 'GLI HEV', 'SR (NON GCC)', 'TX1', 'DL', 'GLS', 'DLS', 'GXR2', 'SPORT', 'GLX', 'S', 'TURBO G', 'GA', 'TOP', 'GL', 'AUTOMATIC', 'G', 'EXR', 'EXI', 'HYBRID (NON GCC)', 'SR5 (NON GCC)', 'AXL ', 'C', 'LUMIERE 40TH ANNIV', 'SE+', 'GLE HEV BLACK EDITION', 'PLATINUM', 'SS', 'GXL 1ST EDITION', 'COMFORT', 'GLE HEV', 'TRIM', 'GLI MR HEV', 'DX', 'BASE', 'SALOON', 'XLI TOP', 'GR', 'DTD', 'CTD', 'ST', 'GRANDE', 'LWB', 'GR SPORT', 'ALTIS (NON GCC)', 'MID', 'SUV', '4', 'CARRERA GTS', 'TRTIM', 'IM', 'ADVENTURE 1ST EDITIO', '1794 EDITION (NON GC', 'CREWMAX CAPSTONE (NO']
  WMI: ['5TD', '4T1', 'RKL', 'MHK', 'JT4', 'LFM', 'JTE', '7MU', '1NX', 'JTD', 'JT2', 'JTM', '5TF', 'INX', '2T1', 'LVG', '137', 'JCB', 'JTC', 'LGW', 'RA6', 'LWL', 'JTN', 'STD', 'ZAP', 'LKL', 'LZW', '7SV', 'KMF', 'MR0', '4T3', 'KN3', 'LJ1', '4TI', 'KLA', 'MB1', 'LZZ', 'JTG', 'JT6', 'LPS', 'KLI', 'HJN', 'KMJ', 'JNC', 'MKH', 'RKE', '1G6', 'VF3', '6TD', 'JNK', 'KNA', 'STF', 'ZCF', 'K1K', 'SAL', 'WV2', 'WP0', 'LA7']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['ZA23C', 'BA32K', 'KAAAG', 'AA1BA', 'ZA119', 'AAA0C', 'KABAG', 'AACAJ', 'CAAAG', 'ZA22C', 'CA30P', 'BA02E', '8A32K', 'BA0BE', 'BA22C', 'KARFU', 'YARAH', 'BA13E', 'FA38P', 'BA23C', 'AACBJ', 'AABBJ', 'CAABG', 'EAMDE', 'AAADC', '2A22C', 'JA5AB', 'WA5DB', 'AA9AJ', 'LA5DB', 'KA3DC', 'LA5AB', 'ZA29C', 'DAABG', 'AAAAF', 'BACEK', 'FA903', 'BA30K', 'BA05E', 'JA5DB', 'ZA230', 'MA5EC', 'ZA113', 'KAMFU', 'JA5EC', '8A13E', 'LA3AH', '2A119', 'AAAAG', '2A23C', '8A02E', 'AAYAJ', 'AAAAA', 'MA71J', '5AFKG', 'MA71L', 'FA119', 'BA01E', 'AA7BJ', 'DAACK', 'VA5BR', 'JA82J', 'CA217', 'LA5GD', 'PAEHD', 'AAABG', 'BA03E', 'DAR9K', 'KARJE', 'MA360', 'EAAAG', '1AAA6', 'CAAGA', 'AAABA', 'GA17F', 'LA5DA', 'BAOBE', 'BA8CD', 'JA5DA', 'KAJDC', 'WA5EC', 'ZA3BB', 'HAP53', '6AE3C', 'KAMFP', 'JA81L', 'HAP5J', 'KARFP', 'PA69J', 'LA5BC', 'BAABG', 'PAAWA', 'MA5DB', 'NA5DB', 'WADG4', 'MA70J', 'CA38P', 'BA1HK', 'JA81J', 'KAAAC', 'ZARAH', 'FARAH', 'VAEDE', 'ZA5CS', 'NADMG', 'WA37R', 'BAMDE', 'GARAH', 'LA5EC', 'UAD1H', 'BADBA', 'JA17B', 'WAH7J', 'DAAAG', 'AAAOC', 'LASDB', '8A23C', 'AA5RX', 'AAAB5', '7ANFU', 'DA1AB', 'DA31A', '2A29C', 'BA244', 'ZA3EH', 'AABAJ', 'AA18A', 'KARAH', 'CA50A', 'AAN6E', 'KAAA6', 'AALAJ', 'CA31A', 'LAAA4', 'CA21A', 'HAP73', 'AAIBA', 'XAD2K', 'AATBA', 'GA17E', 'BA3BE', 'DARTK', 'EA6BX', 'AA1AB', 'BA3BB', 'BAAAG', 'GA17H', 'BA2A9', 'NA3DC', '8A08E', '1AU93', 'MA70L', 'AAAA5']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,SIENNA,6.0,MPV,A,XLE (NON GCC),5TD,GCC,5.0,ZA23C
1,TOYOTA,SIENNA,6.0,MPV,A,XLE (NON GCC),5TD,GCC,5.0,ZA23C
2,TOYOTA,CAMRY,4.0,SEDAN,A,XLI,4T1,GCC,4.0,BA32K
3,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,A,GLI,RKL,GCC,5.0,KAAAG
4,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,A,GLI,RKL,GCC,5.0,KAAAG
...,...,...,...,...,...,...,...,...,...,...
4952,TOYOTA,RAIZE,4.0,SUV,A,TURBO G RA,MHK,GCC,NaN,AA1BA
4953,TOYOTA,TUNDRA,6.0,PICKUP,A,1794 EDITION (NON GC,5TF,NON-GCC,NaN,LA5DB
4954,TOYOTA,LAND CRUISER,6.0,SUV,A,1,JTM,GCC,NaN,AACBJ
4955,TOYOTA,SIENNA,6.0,SUV,A,1,5TD,NON-GCC,NaN,ZA23C
4956,TOYOTA,LAND CRUISER PRADO,4.0,SUV,A,GXL,JTE,GCC,NaN,AACAJ

====================================================================================================
pos5: 1
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'RAV4', 'CAMRY', 'HILUX', 'LAND CRUISER', 'COROLLA', 'RAV 4', 'COASTER', 'HIACE', 'FJ CRUISER', 'COROLLA 1.6', 'WISH', 'PRADO', 'LAND CRUISER PICK UP', 'PREVIA', '25 CA SON P 2.5L AT', 'RAV4 LE CAR', 'RUSH', 'FORTUNER', 'TOYOTA COROLLA', 'COROLLA 1.8', 'AURION', 'VELOZ', 'COROLLA CROSS', 'هايلوكس', 'COROLLA SEDAN', 'CAMRY HYBRID', 'LAND CRUISER PRADO']
  bodyType: ['HATCHBACK', 'SUV', 'SEDAN', 'PICK UP SINGLE CAB', 'STATION', 'BUS', 'PICK UP DOUBLE CAB', 'MINI BUS', 'PANEL VAN', 'PICKUP', 'SALOON', 'VAN', 'PICK UP', 'PANEL VAN HIGH ROOF', 'MPV', 'SUV- CROSSOVER']
  pos5: ['1']
  trim: ['SE', 'LE HEV', 'E', 'EX', 'LE', 'EXR', 'GLE HEV', 'VX', 'DLX', 'S', 'GXR', 'ADVENTURE', 'STD', 'GLE', 'XLI', 'GLI', 'XLE', 'GX', 'T', 'GLE-X HEV 40TH ANNIV', 'SV', 'STD (NON GCC)', 'DX', 'LIMITED', 'XLI MID', 'XLI EXECUTIVE', 'BASE', 'LIMITED HEV', 'XLI POWER OPT', 'GLI HEV', 'GL', 'GRANDE HEV 40TH ANNIV', 'STANDDARD', 'PW CL', 'PREMIER', 'LE STD', 'GXR TOP', 'EXR HEV', 'VXR HEV', 'GG', 'PLATINUM', 'GRANDE HEV', 'PRADO', 'LTD HEV', 'DL', 'XLI TOP', 'SE+', 'GLI TOP', 'MID', 'GLE-X', 'GLX', 'TXR', 'DLS', 'FLEET', '1', 'GLS', 'DLX TOP', 'GL LIMITED', 'XLI EXECUTIVE MR', 'TX-L', 'SPORT', 'LWB HIGH ROOF', 'SALOON', 'XLT', 'LX']
  WMI: ['MR2', '2T3', 'JTD', 'JTN', 'JTM', 'JTB', '4T1', 'ZE1', 'LFM', 'LVG', 'ANE', 'LVC', 'ZGE', 'MMM', 'MHF', 'LA6', 'ACV', 'JTE', '00N', 'NCP', '1GT', 'VR3', 'WDB', 'AR2', 'MD2', 'NV1', 'MC2', 'LMX', 'LKL', 'SXA', '1N1', 'JT8', 'W11', 'LSJ', 'W01', 'WMA', 'L3A', 'AT1', 'JT1', 'L11', 'WB1', '111', 'LGJ', '174', 'UP1', 'AS3', 'SMT', 'J10', 'AE1', 'LDP']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['K19F3', 'W1RFV', 'Z13FV', 'W13FV', 'B14HK', 'B13FV', 'B1RFV', '31UNE', 'G11AK', '11UJ8', 'C11AK', 'A14CK', 'J13FV', 'B11HK', 'F1RFV', '51303', '11WJA', 'H1RFV', 'C1RFV', 'A1809', '11UJA', '71SC1', 'A11AK', 'D156F', 'R1RFV', 'B19HK', 'A180C', 'L11AK', 'P1RFV', 'S11AK', '41UB5', '11600', 'R13FV', 'A1ACC', 'K1RFV', 'B1DWA', '21610', '31UJ7', '51488', '811HK', 'M11AK', '51390', 'B1B0E', '41UHB', '11VJ9', 'T11AK', 'M1111', 'B19F3', 'G11BK', '31YN8', '41CB8', '21UHB', 'J1RFV', 'C11BK', 'A1RFV', '41502', 'R11AK', '213FV', 'G1RFV', 'N1RFV', '819HK', 'F11AK', '21604', 'H109J', 'D1RFV', '51500', '21606', '51116', '814HK', '51067', 'V1804', '91901', '51113', 'N19EC', 'E1NFJ', '91900', '91903', '813FV', '61524', 'F11BK', 'A11CX', '51611', '91902', '31UNG', '81018', '51622', '51211', '41500', '21FCL', 'D13FV', '11UJ9', '51573', '41503', '41501', 'G14DA', 'S11BK', 'W13EV', 'A14AF', '31RN8', 'R1CS9', 'P1HLT', '91908', '819F3', '11005', '11111', '21UJ7', 'T11BK', '51908', '51102', '11AC1', '51426', 'Y1RFV', 'R1DSB', 'A16E3', '21603', 'A11CY', '51940', '51267', '21SZZ', '21608', 'Z1CK3', '41BB4', 'J11BK', '51680', '811EB', '21605', '51149', '51382', '01111', '51452', '51189', '111S1', 'E1EE0', '21090', '51658', '01035', '21602', '51972', '21AS3', 'T147Y', '1111W', '1111S', '01BUM', '01302', '51109', 'G13FV', '41E96', 'Z1RFV']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,YARIS,4.0,HATCHBACK,1,SE,MR2,GCC,5.0,K19F3
1,TOYOTA,RAV4,4.0,SUV,1,LE HEV,2T3,GCC,5.0,W1RFV
2,TOYOTA,YARIS,4.0,HATCHBACK,1,E,MR2,GCC,5.0,K19F3
3,TOYOTA,RAV4,4.0,SUV,1,EX,JTD,GCC,5.0,Z13FV
4,TOYOTA,RAV4,4.0,SUV,1,EX,JTD,GCC,5.0,Z13FV
...,...,...,...,...,...,...,...,...,...,...
5902,TOYOTA,CAMRY HYBRID,4.0,SEDAN,1,GLE,JTN,GCC,NaN,A14CK
5903,TOYOTA,CAMRY HYBRID,4.0,SEDAN,1,GLE,JTN,GCC,NaN,A14CK
5904,TOYOTA,RAV4,4.0,SUV,1,EX,JTD,GCC,NaN,Z13FV
5905,TOYOTA,YARIS,4.0,HATCHBACK,1,SE,MR2,GCC,NaN,K19F3
5906,TOYOTA,CAMRY HYBRID,4.0,SEDAN,1,XLE,JTN,GCC,NaN,A14CK

====================================================================================================
pos5: 3
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'BZ4X', 'COROLLA', 'HILUX', 'TERCEL', '2023', 'RAV4', 'COROLLA 1.5', 'BZ3X', 'TOYOTA COROLLA', 'AVALON', 'HIACE', 'C-HR', 'BZ 4', 'COROLLA 1.3', 'RAV 4', 'COASTER', 'RUSH', 'LAND CRUISER', 'كورولا 1.3', 'CROWN V', 'TOYOTA LAND CRUISER', 'BZ46', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'STATION', 'SALOON', 'BUS', 'MINI BUS', 'PICKUP']
  pos5: ['3']
  trim: ['STD', 'PRO', 'XLI', 'DLX', 'XLI MID', 'S', 'GLI', 'STATION', 'SE', 'EX', 'GLE', 'LE STD', 'EXR', 'LE', 'XLI EXECUTIVE', 'S PLUS', 'GX', 'BASE', 'STD (NON GCC)', 'XLI EXECUTIVE MR', 'LWB', 'SE+', 'DL', 'GLE-X HEV 40TH ANNIV', 'XSE (NON GCC)', 'DX', 'GL', 'SPORT', '1', 'GLE HEV', 'X', 'GLI HEV', 'DLS', '2', 'SED']
  WMI: ['6T1', 'LVG', 'RKL', 'JTB', '4T1', 'LFM', '4T2', 'JL5', 'JT8', 'WMA', 'VF3', 'JJ5', 'LFZ', 'JTE', 'MC2', '180', 'LVB', 'JT3', 'JTF', 'FJ4']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['53SK2', 'D3135', 'B30BE', '33UNG', '33YN8', '53EEB', '53AEB', '33UNE', '53EL5', 'B31HK', '53AEA', '53XK2', 'B30EE', '53SK1', 'C31AK', 'J34AF', '53EEA', 'F31AK', 'D3DF6', '33RN8', '535K2', 'K31AK', '53XH1', 'B3J6P', 'G31AK', 'S31AK', '53AFB', 'B3E6P', '534K2', 'T36ZZ', 'L35GY', 'B308E', '53EE8', '73FM4', '63AL5', 'H3093', 'R3NLT', '93220', '53JSF', 'V3JBB', 'H309J', 'L373J', 'N38ZZ', '03350', '63AL4', 'B3G6P', '33RNA']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,CAMRY,4.0,SEDAN,3,STD,6T1,GCC,4.0,53SK2
1,TOYOTA,BZ4X,0.0,SUV,3,PRO,LVG,GCC,5.0,D3135
2,TOYOTA,COROLLA,4.0,SEDAN,3,XLI,RKL,GCC,4.0,B30BE
3,TOYOTA,BZ4X,0.0,SUV,3,PRO,LVG,GCC,5.0,D3135
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,JTB,GCC,2.0,33UNG
...,...,...,...,...,...,...,...,...,...,...
928,TOYOTA,COROLLA,4.0,SEDAN,3,XLI,RKL,GCC,NaN,B30BE
929,TOYOTA,COROLLA,4.0,SEDAN,3,XLI,RKL,GCC,NaN,B30BE
930,TOYOTA,COROLLA,4.0,SEDAN,3,XLI,RKL,GCC,NaN,B30BE
931,TOYOTA,COROLLA,4.0,SEDAN,3,1,RKL,GCC,NaN,B30BE
932,TOYOTA,COROLLA,4.0,SEDAN,3,XLI,RKL,GCC,NaN,B30BE

====================================================================================================
pos5: C
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'AVANZA', 'CROWN', 'COROLLA CROSS', 'TUNDRA', 'HILUX', 'LAND CRUISER', 'CAMRY', 'بريفيا', 'RAV4', 'PRIUS', 'HIACE', 'TOYOTA PRIUS', 'TACOMA', 'SIENNA', 'SY150T', 'GRANVIA', 'RUSH', 'ALLION', 'AVALON', 'FJ CRUISER', 'FORTUNER', 'YARIS', 'افنزا', 'CORONA', 'COROLLA 1.3', 'TUNDRA (PICK UP)', 'TERCEL', 'INNOVA', 'PRADO', 'HIGHLANDER', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'MPV', 'SUV- CROSSOVER', 'PICK UP DOUBLE CAB', 'SUV', 'STATION', 'VAN', 'PANEL VAN', 'MINI BUS HIGH ROOF', 'MOTORCYCLE', 'PICK UP SINGLE CAB', 'SALOON', 'PICKUP', 'HATCHBACK', 'PICK UP']
  pos5: ['C']
  trim: ['XLI', 'STD (NON GCC)', 'LE', 'SE', 'PREMIUM', 'XL', 'XLI MID', 'XLI POWER OPT', '1794 EDITION (NON GCC)', 'XLE', 'DLX', 'VXR', 'GLI', 'CREWMAX CAPSTONE (NON GCC)', 'GLE', 'GLX', 'STD', 'EXR', 'SEDAN', 'GL', 'S', 'DLS', 'SR5 (NON GCC)', 'XLE (NON GCC)', 'PLATINUM', 'E', 'GR SPORT', 'SAFARI', 'DL', 'GLI TOP', 'BASE', 'XLI TOP', 'SR', 'EX', 'GLS', '45', 'GXR', 'GLE HEV', 'GV', 'GL2', '60TH', 'DX', 'LE HEV', 'YA', 'PICK UP', 'ADVENTURE', '1', '1794 EDITION (NON GC', 'CREWMAX CAPSTONE (NO']
  WMI: ['RKL', 'MHK', 'JTD', 'JTK', '5TF', 'LA7', 'JTM', 'ME4', 'U8Q', 'JHH', 'JT3', 'MA3', 'JL6', '3TY', 'LFM', '2C4', 'LVG', 'MLH', 'WMW', 'LK1', '3N1', 'JL7', 'JJ7', 'L3H', 'MBJ', 'KMF', '1G1', 'JN1', 'LZZ', 'LAZ', 'JH2', 'JS2', 'VF7', 'JT2', 'LNB', 'KNM', '5TD', '1GC']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['BC42E', 'MC13F', 'ACABF', 'KCBAG', 'NC5DB', '1CUG3', 'MC12F', 'AC7BJ', '8C42E', 'KCAAG', 'PC5DB', 'MC5DB', 'JC5DB', 'KC20F', 'ZCKF5', 'VC5DB', 'LCN1F', 'AC11R', '5C3AV', 'ACAAU', 'NC2B1', 'ZCP2F', 'BCE6J', 'UCN1H', 'ACJ4H', 'LC5LN', 'JC5EC', 'CC1BR', 'RC1BG', 'BC74K', 'PC569', 'ZC3C5', 'ZCK1H', 'EC42E', 'PCKL9', 'KC4BS', 'AC22C', 'ZCP2H', 'BC11E', 'BCE1J', 'KC20D', '8CE1K', 'ECABA', 'BCELK', 'NC5EC', 'WC5DB', 'KC311', 'BC81S', 'TC31E', 'ZCZ7J', 'AC1DM', 'YCN1H', 'ZCS7J', 'ACAAJ', 'ZCN1F', 'UCK1H', 'ZC5ST', 'BCE1K', 'CC13C', 'MCK3H', '8CCVD', '1CU83', 'SC87C', 'VC31F', 'ZC8B2', '7CNFU', 'WC5EC', 'BC53L', 'KC206', 'CC1CX', 'BC42R', 'MCUBK', 'CC42H', 'ZCL2H', 'MC5AB', 'DCRFH', 'SC79M', 'KC20G', 'FC24H', 'ACAB5']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,C,XLI,RKL,GCC,NaN,BC42E
1,TOYOTA,COROLLA,4.0,SEDAN,C,STD (NON GCC),RKL,GCC,4.0,BC42E
2,TOYOTA,COROLLA,4.0,SEDAN,C,STD (NON GCC),RKL,GCC,4.0,BC42E
3,TOYOTA,COROLLA,4.0,SEDAN,C,LE,RKL,GCC,4.0,BC42E
4,TOYOTA,AVANZA,4.0,MPV,C,SE,MHK,GCC,5.0,MC13F
...,...,...,...,...,...,...,...,...,...,...
4199,TOYOTA,COROLLA,4.0,SEDAN,C,STD (NON GCC),RKL,GCC,NaN,BC42E
4200,TOYOTA,COROLLA,4.0,SEDAN,C,XLI,RKL,GCC,NaN,BC42E
4201,TOYOTA,COROLLA,4.0,SEDAN,C,XLI POWER OPT,RKL,GCC,NaN,BC42E
4202,TOYOTA,AVANZA,4.0,SUV,C,SE,MHK,GCC,NaN,MC13F
4203,TOYOTA,COROLLA,4.0,SEDAN,C,STD (NON GCC),RKL,GCC,NaN,BC42E

====================================================================================================
pos5: J
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER PICK UP', 'LAND CRUISER', 'IQ', 'LAND CRUISER PICKUP 70', 'PRADO', '4RUNNER', 'RAV4', '86', 'TERCEL', 'COROLLA', 'HILUX', 'TUNDRA', 'YARIS', 'SCION', 'CAMRY', 'TOYOTA', 'LAND CRUISER SINGLE-CABIN PICK', 'TOYOTA LAND CRUISER', 'لاند كروزر', '2012', 'SIENNA', 'TOYOTA SCION', 'PRIUS', 'TOYOTA IQ', 'ZELAS', 'PICK UP CABIN', 'AVALON', 'LAND CRUISER GXR', 'TOYOTA SQUIN', 'YARIS HATCHBACK', 'DYNA', 'RAIZE', 'LAND CRUISER/STD EX PICKUP', 'LAND CRUISER PICKUP', 'COUPE', 'PICKUP', 'CAMRY HYBRID', 'TOYOTA 86']
  bodyType: ['PICK UP', 'SUV', 'HATCHBACK', 'PICKUP', 'PICK UP SINGLE CAB', 'COUPE', 'SEDAN', 'PICK UP DOUBLE CAB', 'MPV', 'SALOON', 'STATION', 'TRUCK']
  pos5: ['J']
  trim: ['STD', 'GX', 'VX', 'STD (NON GCC)', 'GXR TOP', 'VXR BASE', 'GXR', 'LX', 'SR5 (NON GCC)', 'BE', 'GT', 'ST', 'LX AC PWR OPT', 'XLI MID', 'DLX', 'GLX', 'DL', 'VXR TOP LTH', 'GXR FMST', 'XLI', 'EXR', 'SE', 'SAFARI', 'GXR TOP DMST', 'GXR TOP FMST', 'E', 'EX', '2400', '1500', '6', 'GL', 'LAND CRUSIER', 'XE 4WD', 'STATION1', 'VXR MID', 'VXR TOP', 'GXR SOD D/AC AW', 'BASE', 'SC', 'FULL OPTION', 'STD AC', 'GXR2', 'DLS', 'AUTOMATIC', '1500 CREWCAB SLE Z71', 'LE (NON GCC)', 'S', 'GLS TOP', 'LS', 'N', 'MID', 'GLI', 'CAR TRIM', 'LX WIDE TYRES', '4', 'ZX', 'TRIM', 'DLX TOP', 'SGLX', 'LE PLATINUM CITY', 'SLT', 'STANDARD', 'PICKUP', 'S T1', 'GXR MID', '60TH', 'PREMIER', '1']
  WMI: ['JTF', 'JT3', 'JTE', 'JTN', 'JTG', 'JTM', 'JT2', 'KN9', '2CN', 'KNC', 'JHE', 'LVG', 'VF3', 'JTH', 'JTC', 'JIF', 'LCO', 'JD2', '1C4', 'KL1', 'LSJ', 'JT6', 'KMH', 'JTR', 'LFM', 'JHG', 'AUS', 'JTJ', 'JT4', 'SKF', '6T1']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['LJ73J', 'HJ09J', 'HJ093', 'JJXB0', 'LJ71J', 'HJ01J', 'DJREV', 'BJ53L', 'JJREV', 'BJ13E', 'FJ71J', 'RJREV', '0J4MC', 'BJ18U', 'WJ272', 'EJ13E', 'FJ60G', 'BJE23', 'HJ59J', 'CJE23', '7JNFU', 'HJ85J', 'HJO9J', 'WJZ74', '8J466', 'HJ091', 'SJZ74', 'CJE73', 'LJ733', 'WJZ76', 'EJ5CD', 'GJ211', 'WJX74', 'DJ81W', 'WJX76', 'VJ73J', '8J53L', 'HJXEN', 'CJ6B1', 'WJ4W9', 'SJ8IV', 'BJI3E', 'AJ54K', 'JJX80', 'HJ05J', 'HJ0SJ', 'YJ227', 'BJ335', 'HJQ8J', 'HJ08J', 'WJ276', 'WJZ72', 'BJRBZ', 'LJ731', 'GJKFW', '6JKFW', 'FJ60V', 'SJN3B', 'BJ22K']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP,J,STD,JTF,GCC,2.0,LJ73J
1,TOYOTA,LAND CRUISER,6.0,SUV,J,GX,JT3,GCC,5.0,HJ09J
2,TOYOTA,LAND CRUISER,8.0,SUV,J,VX,JTE,GCC,5.0,HJ09J
3,TOYOTA,LAND CRUISER,6.0,SUV,J,VX,JTE,GCC,5.0,HJ093
4,TOYOTA,LAND CRUISER,6.0,SUV,J,VX,JTE,GCC,5.0,HJ09J
...,...,...,...,...,...,...,...,...,...,...
5560,TOYOTA,LAND CRUISER,6.0,SUV,J,VX,JTE,GCC,NaN,HJ09J
5561,TOYOTA,LAND CRUISER,6.0,SUV,J,VX,JTE,GCC,NaN,HJ09J
5562,TOYOTA,LAND CRUISER,6.0,SUV,J,VX,JTE,GCC,NaN,HJ09J
5563,TOYOTA,LAND CRUISER,4.0,SUV,J,VX,JTE,GCC,NaN,HJ09J
5564,TOYOTA,LAND CRUISER,6.0,SUV,J,VX,JTE,GCC,NaN,HJ09J

====================================================================================================
pos5: H
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'PRADO', 'HILUX', 'C-HR', 'LAND CRUISER', 'MT 03', 'HIACE', 'CAMRY', 'CHR', 'SIENNA', 'COROLLA', 'YARIS', 'RUSH', 'CAMRY HYBRID']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'MOTORCYCLE', 'BUS', 'SEDAN', 'STATION', 'MPV', 'HATCHBACK']
  pos5: ['H']
  trim: ['PW CL', 'FABRIC', 'EX', 'VXR', 'DLX', 'GX', 'STD (NON GCC)', 'MID', 'XTREME', 'DL', 'GLX', 'BASE', 'EXR', 'GL', 'TX-L', 'GLI', 'ABC', 'LE (NON GCC)', 'TOP', '1', 'SE']
  WMI: ['JTE', 'SJK', 'JAA', 'JTN', 'NMT', 'JHE', 'WDA', 'KPB', 'MH3', 'JM3', 'KNC', 'JAC', 'LGF', 'WDD', 'JH2', 'WBA', 'JL5', '1G0', 'WVW', 'LVG']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['HH20V', 'YH20V', 'GH20V', 'CH5CP', 'BH9FJ', 'NHR55', 'KHMBX', '6H20V', 'KHCAA', 'YH207', 'BH2AW', 'RH21B', 'WH813', 'SHX74', 'DH88W', '1HBJW', 'FH3CB', 'DH88X', 'RH223', 'PH5C5', 'BHJ6S', '2HNAG', 'DH4CD', 'BH42K']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,RAV4,4.0,SUV,H,PW CL,JTE,GCC,3.0,HH20V
1,TOYOTA,RAV4,4.0,SUV,H,FABRIC,JTE,GCC,5.0,YH20V
2,TOYOTA,RAV4,4.0,SUV,H,PW CL,JTE,GCC,5.0,HH20V
3,TOYOTA,RAV4,4.0,SUV,H,FABRIC,JTE,GCC,5.0,HH20V
4,TOYOTA,RAV4,4.0,SUV,H,PW CL,JTE,GCC,3.0,HH20V
...,...,...,...,...,...,...,...,...,...,...
1136,TOYOTA,RAV4,4.0,SUV,H,FABRIC,JTE,GCC,NaN,YH20V
1137,TOYOTA,C-HR,4.0,SUV,H,GX,NMT,NON-GCC,NaN,KHMBX
1138,TOYOTA,C-HR,4.0,SUV,H,STD (NON GCC),NMT,NON-GCC,NaN,KHMBX
1139,TOYOTA,RAV4,4.0,SUV,H,1,JTE,NON-GCC,NaN,YH20V
1140,TOYOTA,C-HR,4.0,SUV,H,GX,NMT,NON-GCC,NaN,KHMBX

====================================================================================================
pos5: Y
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TUNDRA', 'LAND CRUISER', 'SEQUOIA', 'DYNA', 'LAND CRUISE', 'COROLLA', 'FORTUNER', 'COASTER', 'ALTIS', 'COROLLA SEDAN', '2016', 'HIACE', 'CAMRY', 'C-HR', 'FJ CRUISER', 'DAINA', 'HILUX', 'LEVIN', 'TANDRA', 'TOYOTA LAND CRUISER', 'CELICA', 'RAV4', 'CHR']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'PICKUP', 'STATION', 'SEDAN', 'PICK UP SINGLE CAB', 'BUS', 'SALOON', 'PANEL VAN', 'COUPE', 'MINI BUS', 'LIGHT VEHICLE']
  pos5: ['Y']
  trim: ['STD (NON GCC)', 'GXR', 'SR5 (NON GCC)', 'VXR', 'SR5 4X4', 'GXR GT', 'LIMITED MID', 'GXR TOP', 'STD', 'LIMITED 4X4', 'PLATINUM', 'EXR', 'LIMITED 4X2', 'TOP', 'SR5 4X2', 'GLX', 'LWB', 'GL', 'GLI', 'GX', 'LE', 'VX', 'LWB HIGH ROOF', 'SWB', 'SE', 'XLE', 'A', 'S', 'GXR SOD D/AC AW', 'DL', 'GLE', 'LIMITED TOP', 'XLI TOP', 'PLATINUM LUXURY 4X4', '1500', 'GXR MID', 'DLX', 'PREMIUM', 'SS', 'EX', 'SAFARI', 'XLI', 'HYBRID (NON GCC)', 'VXR BASE', 'VXR TOP', 'GXR TOP 60TH ANNIV. XTREME', '1']
  WMI: ['5TF', 'JTM', '5TD', 'JT4', 'LVG', 'JN8', 'JTG', 'STD', 'STF', '2FU', 'LFM', 'JIM', '6TD', 'JTF', 'JTD', '1HD', 'JTC', 'NMT', 'STO', 'JNK', 'JMY', '5TE', '4F4', '2T1', '5T0', '6TF']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['KY5F1', 'HY05J', 'DY5G1', 'AY5F1', 'UY5F1', 'BY64A', 'DY5F1', 'HY02J', 'HY0SJ', 'BY68A', 'HY5F1', 'AY117', 'PY5F1', 'BY80E', 'RY5F1', 'ZY68A', 'AYT30', 'CY5F1', 'BY67A', 'NY5F1', 'HY03J', 'YY5G1', 'HY051', 'CY7AJ', 'FY418', 'FY5F1', 'BY5F1', 'ZY67A', 'ZY64A', 'JY5F1', 'GY5F1', 'HY7AJ', 'ZY0CC', 'MY5F1', 'EY5F1', 'KY5G1', 'ZY5G1', 'FY5B1', 'JY5G1', 'BY5G1', 'BY879', 'UYSF1', 'AYACC', 'KYSFI', '2Y68A', 'UY6F1', 'JY09J', 'AY86C', 'PY22P', 'DY32T', '1YYK2', 'LY3FX', '8Y64A', '2Y64A', 'BY11F', 'AY2NY', 'LYV65', 'BY809', 'KY1CD', 'HY053', 'EY64A', '8Y5F1', 'BY30E', 'BY84A', 'HYOSJ', 'HYO5J', 'TY5F1', 'UY0FJ', 'UYSPI', 'DY38T', 'BYBDE', 'BY32E', 'UY5E1', 'DYSF1', '0YSF1', 'SY5F1', 'FY5A1', '8Y561', 'HY05I', 'HY0S0']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,Y,STD (NON GCC),5TF,GCC,4.0,KY5F1
1,TOYOTA,LAND CRUISER,6.0,SUV,Y,GXR,JTM,GCC,5.0,HY05J
2,TOYOTA,SEQUOIA,8.0,SUV,Y,SR5 (NON GCC),5TD,GCC,5.0,DY5G1
3,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,Y,STD (NON GCC),5TF,GCC,4.0,AY5F1
4,TOYOTA,LAND CRUISER,6.0,SUV,Y,GXR,JTM,GCC,5.0,HY05J
...,...,...,...,...,...,...,...,...,...,...
7251,TOYOTA,TUNDRA,8.0,PICKUP,Y,STD (NON GCC),5TF,NON-GCC,NaN,UY5F1
7252,TOYOTA,TUNDRA,8.0,PICKUP,Y,STD (NON GCC),5TF,NON-GCC,NaN,DY5F1
7253,TOYOTA,LAND CRUISER,8.0,SUV,Y,GXR,JTM,GCC,NaN,HY05J
7254,TOYOTA,TUNDRA,8.0,PICKUP,Y,STD (NON GCC),5TF,NON-GCC,NaN,AY5F1
7255,TOYOTA,LAND CRUISER,8.0,SUV,Y,VXR,JTM,GCC,NaN,HY05J

====================================================================================================
pos5: 5
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'LEVIN', 'HIACE', 'COROLLA', 'YARIS', 'HIGHLANDER', 'PREVIA', 'CAMRY', 'CROWN', 'FORTUNER', 'SIENNA', 'RAV4', 'COASTER']
  bodyType: ['PICK UP SINGLE CAB', 'SEDAN', 'PANEL VAN HIGH ROOF', 'PICK UP DOUBLE CAB', 'HATCHBACK', 'SUV', 'MPV', 'MINI BUS HIGH ROOF', 'PANEL VAN', 'BUS', 'PICK UP']
  pos5: ['5']
  trim: ['DLX', 'STD (NON GCC)', 'GLS', 'XLI TOP', 'LE', 'HYBRID (NON GCC)', 'STD', 'DX', 'AUTOMATIC', 'TOP', '1', 'S', 'XLI', 'SE', 'E', 'XLI MID', 'GLI', 'GLE', 'MID', 'LIMITED']
  WMI: ['WDB', 'LVG', 'CLG', 'NSP', 'JTE', 'JZS', 'WD8', 'LSK', 'RN1', '5TD', 'RK4', 'NCP', 'VZE', 'YBL', 'WVG', 'MAT', 'GGG']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['65204', 'B519E', '65203', '855HZ', '65553', '65213', '15140', 'D541A', '65620', '15100', '65933', 'G5GC1', '65200', '35000', 'K5KFC', '65651', '65805', '65934', '15070', '65610', '15151', '3546F', 'H545G', '75106', '95021', '45612', '95403', '65910']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,5,DLX,WDB,GCC,2.0,65204
1,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
2,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
3,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,5,DLX,WDB,GCC,2.0,65203
5,TOYOTA,HIACE,4.0,PANEL VAN HIGH ROOF,5,GLS,CLG,GCC,NaN,855HZ
6,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
7,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
8,TOYOTA,COROLLA,4.0,SEDAN,5,XLI TOP,WDB,GCC,NaN,65553
9,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,5,DLX,WDB,GCC,4.0,65213
10,TOYOTA,YARIS,4.0,HATCHBACK,5,LE,NSP,NaN,NaN,15140
11,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
12,TOYOTA,HIGHLANDER,6.0,SUV,5,HYBRID (NON GCC),JTE,GCC,5.0,D541A
13,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
14,TOYOTA,PREVIA,4.0,MPV,5,STD,WDB,GCC,5.0,65620
15,TOYOTA,CAMRY,4.0,SEDAN,5,STD,JZS,NON-GCC,NaN,15100
16,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,5,DLX,WD8,GCC,4.0,65933
17,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,5,DX,LSK,GCC,4.0,G5GC1
18,TOYOTA,HIACE,4.0,PANEL VAN,5,STD,WDB,GCC,5.0,65200
19,TOYOTA,CROWN,6.0,SEDAN,5,AUTOMATIC,JZS,NON-GCC,NaN,15100
20,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
21,TOYOTA,FORTUNER,4.0,SUV,5,TOP,RN1,GCC,NaN,35000
22,TOYOTA,SIENNA,6.0,MPV,5,1,5TD,GCC,NaN,K5KFC
23,TOYOTA,COROLLA,4.0,SEDAN,5,S,RK4,GCC,NaN,65651
24,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,WDB,GCC,NaN,65805
25,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,5,DLX,WDB,GCC,2.0,65934
26,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
27,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
28,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
29,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
30,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
31,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
32,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
33,TOYOTA,YARIS,4.0,SEDAN,5,SE,NCP,GCC,NaN,15070
34,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
35,TOYOTA,YARIS,4.0,SEDAN,5,SE,NCP,GCC,NaN,15070
36,TOYOTA,RAV4,4.0,SUV,5,STD,WDB,GCC,NaN,65610
37,TOYOTA,YARIS,4.0,HATCHBACK,5,SE,NSP,GCC,NaN,15140
38,TOYOTA,YARIS,4.0,SEDAN,5,E,NSP,NON-GCC,NaN,15140
39,TOYOTA,COROLLA,4.0,SEDAN,5,XLI MID,VZE,NON-GCC,NaN,15151
40,TOYOTA,COROLLA,4.0,SEDAN,5,S,YBL,GCC,NaN,3546F
41,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
42,TOYOTA,COROLLA,4.0,SEDAN,5,S,WVG,GCC,NaN,H545G
43,TOYOTA,COROLLA,4.0,SEDAN,5,GLI,LVG,GCC,4.0,B519E
44,TOYOTA,COROLLA,4.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
45,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
46,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
47,TOYOTA,COASTER,6.0,BUS,5,STD,MAT,GCC,NaN,75106
48,TOYOTA,HILUX,4.0,PICK UP,5,DLX,WDB,GCC,NaN,95021
49,TOYOTA,COROLLA,4.0,SEDAN,5,XLI TOP,WDB,NON-GCC,NaN,65553
50,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,GGG,GCC,NaN,45612
51,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,5,DLX,WDB,GCC,NaN,95403
52,TOYOTA,CAMRY,4.0,SEDAN,5,GLE,LVG,GCC,4.0,B519E
53,TOYOTA,LEVIN,3.0,SEDAN,5,STD (NON GCC),LVG,GCC,4.0,B519E
54,TOYOTA,YARIS,4.0,HATCHBACK,5,MID,WDB,NON-GCC,NaN,95403
55,TOYOTA,CAMRY,4.0,SEDAN,5,GLE,LVG,GCC,4.0,B519E
56,TOYOTA,COROLLA,4.0,SEDAN,5,LIMITED,WDB,NON-GCC,NaN,65910
57,TOYOTA,COROLLA,4.0,SEDAN,5,STD (NON GCC),LVG,NON-GCC,NaN,B519E

====================================================================================================
pos5: M
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['GRANVIA', 'HILUX', 'PRADO', 'HIACE', 'URBAN CRUISER', 'TUNDRA', 'COASTER', 'TAKOMA', 'SIENNA', 'TACOMA', 'COROLLA', 'INNOVA', 'T 100', 'LAND CRUISER', 'LAND CRUISER PICK UP', 'PRADO GX', 'TOYOTA PRADO', 'RAV4', 'YARIS', 'CAMRY', 'هايلوكس', 'HAI LUX', 'T100', 'برادو', 'VAN']
  bodyType: ['MPV', 'PICK UP DOUBLE CAB', 'SUV', 'MINI BUS HIGH ROOF', 'PANEL VAN', 'VAN', 'PICK UP SINGLE CAB', 'CARGO VAN', 'PICKUP', 'BUS', 'MINI BUS', 'PANEL VAN HIGH ROOF', 'PICK UP', 'TRUCK', 'SEDAN', 'STATION', 'LIGHT VEHICLE']
  pos5: ['M']
  trim: ['PLATINUM', 'DLX', 'VX', 'GL', 'PREMIUM', 'GLX', 'GLS', 'STD (NON GCC)', 'GX MID', 'DLS - STD ROOF', 'STD', '1', 'GX', '1500', 'BUS', 'LE (NON GCC)', 'DX', 'STAN', 'S ASF', 'GLI', 'S', 'A', 'STANDARD', 'DLS HIGH ROOF', 'DLS', 'COASTER', 'BASE', 'TRD', 'E', 'TX', 'ST', '0', '90', 'DL', 'GRANDE', 'PICK']
  WMI: ['JTN', 'JTF', 'JTE', 'MBJ', '5TF', '4TA', 'JTG', 'STF', '5TE', 'JT4', 'JT3', 'MEJ', 'LSF', 'MPJ', 'JHM', 'YV2', 'WVW', '1LN']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['YM8AP', 'AM496', 'AM29J', 'LMFCP', 'RMFAP', 'YM3AP', 'YMLA2', 'DM5F1', 'EM496', 'BM29J', 'DM626', 'EM426', 'UM5F1', 'KM626', 'RM5F1', 'NM92N', 'LMFCW', 'FM518', 'SMFAP', 'BM99J', 'PM62N', 'FM418', 'SM92N', 'KM5F1', 'TMLA2', 'LM5F1', 'JM11D', 'EM5F1', 'AM450', 'RMFAW', 'AM498', 'YMLAZ', 'LMSF1', 'AM11H', 'WM72N', 'EM42G', 'CM565', 'JM30D', 'AM2AH', 'BM82F', 'RMEAP']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,GRANVIA,6.0,MPV,M,PLATINUM,JTN,GCC,4.0,YM8AP
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,M,DLX,JTF,GCC,4.0,AM496
2,TOYOTA,PRADO,6.0,SUV,M,VX,JTE,GCC,5.0,AM29J
3,TOYOTA,HIACE,6.0,MINI BUS HIGH ROOF,M,GL,JTF,GCC,4.0,LMFCP
4,TOYOTA,HIACE,4.0,PANEL VAN,M,GL,JTF,GCC,NaN,RMFAP
...,...,...,...,...,...,...,...,...,...,...
1708,TOYOTA,URBAN CRUISER,4.0,SUV,M,GLX,MBJ,GCC,NaN,YMLA2
1709,TOYOTA,URBAN CRUISER,4.0,SUV,M,GLX,MBJ,GCC,NaN,YMLA2
1710,TOYOTA,URBAN CRUISER,4.0,SUV,M,GL,MBJ,GCC,NaN,YMLA2
1711,TOYOTA,URBAN CRUISER,4.0,SUV,M,GLX,MBJ,GCC,NaN,YMLA2
1712,TOYOTA,HILUX,4.0,PICKUP,M,1,JTF,GCC,NaN,EM426

====================================================================================================
pos5: 4
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'CAMRY', 'RAV4', 'HILUX', 'LEVIN', 'PRADO', 'AVALON', 'HIACE', 'CELICA', 'COASTER', 'LAND CRUISER', 'YARIS', 'COROLLA SEDAN / HATCH', 'STANZA', 'WIGO', 'COROLLA 1.5L/HATCHBACK', 'HI ACE']
  bodyType: ['SEDAN', 'SUV', 'PICK UP DOUBLE CAB', 'MINI BUS HIGH ROOF', 'COUPE', 'PANEL VAN', 'BUS', 'HATCHBACK', 'PICK UP SINGLE CAB', 'VAN', 'STATION', 'PICK UP']
  pos5: ['4']
  trim: ['SE', 'GLI', 'GLE-X', 'EX', 'XLI EXECUTIVE', 'XLI', 'EXR', 'STD (NON GCC)', 'DLX', 'XLI MID', 'LE HEV', 'GX', 'LIMITED', 'GRANDE', 'STD', 'GXR', 'SE+', 'GLI HEV', 'XLI EXECUTIVE MR', 'BASE', 'VX', 'GL', 'DL', 'DLS', 'MID', 'XLI EXECUTIVE HEV', 'XLI TOP', 'SE (NON GCC)', 'S', 'SWB', 'VXR', 'VAN', 'GLX', 'GXR HEV']
  WMI: ['JTN', '5YF', 'LFP', 'LFM', 'YV2', 'JTD', 'JTM', 'LVG', 'JTB', 'RP8', 'ZRE', 'MAT', 'ZZE', 'LSK', 'IG1', 'WMA', 'WYU', 'WCY', 'YS2', 'MC1', 'LVB', 'WDB', 'SYF', 'MHK', '425', 'JT4']
  regionalSpec: ['NON-GCC', 'GCC']
  VDS: ['K4RBE', 'B4MDE', 'D4MBE', 'H4ACP', 'K440F', 'A4DAA', '543BV', 'J44AF', 'A4DAC', 'A4B2A', 'R43FV', 'J440F', 'B4B9E', 'S4MCE', 'P4RCE', 'H4BCP', '64AEB', 'A4B3A', 'M4571', 'A4DMA', 'A4CFA', 'K4MBE', 'T4MCE', '14244', '543AV', '44925', 'S4RCE', 'A4CEA', '14270', 'C4RBE', 'G4AC1', '14583', 'C4MBE', 'T48ZZ', 'B4MBE', '14545', 'U4545', 'G4X20', 'T4RCE', 'A4MBE', '64STL', 'E4FDB', 'V4JBB', '94403', 'D4RBE', '14252', 'A4B5A', 'G4BC1', 'P4MCE', 'B4RBE', 'A4RBE', 'A4DF5', '042TN', 'M4RCE', 'B4MEE', 'J4CMA', 'Z4119', 'J4CFC', '64EEB', 'A4DBA']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,4,SE,JTN,NON-GCC,NaN,K4RBE
1,TOYOTA,COROLLA,4.0,SEDAN,4,GLI,5YF,GCC,4.0,B4MDE
2,TOYOTA,COROLLA,4.0,SEDAN,4,SE,JTN,GCC,4.0,D4MBE
3,TOYOTA,CAMRY,4.0,SEDAN,4,GLE-X,LFP,NON-GCC,4.0,H4ACP
4,TOYOTA,RAV4,4.0,SUV,4,EX,LFM,GCC,5.0,K440F
...,...,...,...,...,...,...,...,...,...,...
324,TOYOTA,COROLLA,4.0,SEDAN,4,XLI,LVG,NON-GCC,NaN,B4B9E
325,TOYOTA,RAV4,4.0,SUV,4,EX,JTD,GCC,NaN,543BV
326,TOYOTA,COROLLA,4.0,SEDAN,4,SE+,JTN,NON-GCC,NaN,K4RBE
327,TOYOTA,COROLLA,4.0,SEDAN,4,STD (NON GCC),JTD,NON-GCC,NaN,S4MCE
328,TOYOTA,RAV4,4.0,SUV,4,EX,JTD,GCC,NaN,543BV

====================================================================================================
pos5: 6
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'RAV4', 'COROLLA', 'HIACE', 'HILUX', 'YARIS', 'SIENNA', 'COROLLA CROSS', 'TUNDRA', 'LAND CRUISER', 'NIO ES8', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'MINI BUS', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'MPV', 'SUV- CROSSOVER', 'HALF PANEL VAN', 'MINI BUS HIGH ROOF']
  pos5: ['6']
  trim: ['GLE-X HEV 40TH ANNIV', 'EXR', 'LE HEV', 'GLE', 'SE', 'SPORT', 'S', 'XLI', 'EX', 'GLE HEV', 'DX', 'STD', 'BASE', 'LIMITED', 'E', 'DLX', 'LE', 'DL', 'STD (NON GCC)', 'XSE (NON GCC)', 'XLE', 'GLI TOP', 'SAFARI', 'GLX', 'DLS - STD ROOF', 'GL', 'GRANDE HEV 40TH ANNIV']
  WMI: ['4T1', '2T3', '4T3', 'LVG', 'YS2', '9BS', 'WMA', 'JT4', 'JTM', 'LCF', 'JTF', 'JT2', 'KL3', 'MAT', '6T1', 'VS5', 'MK2', 'MD6', 'VF1', 'LJ1', 'GX9']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['K61AK', 'R6RFV', 'E6RFV', 'B674K', 'K61BK', 'B61HK', 'G6X40', 'C618X', 'B6RFV', 'P6X40', '06XZZ', 'A6426', '8622K', 'W6FY1', 'K6E6F', '46405', 'B622K', '56N8U', 'C616Z', '46470', 'K6T1Y', 'G622K', '26BG7', '46475', 'F6RDM', '66B3D', '56EZZ', 'D6RFV', 'E6A3U', '46407', '06622', '8628K']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,CAMRY,4.0,SEDAN,6,GLE-X HEV 40TH ANNIV,4T1,GCC,4.0,K61AK
1,TOYOTA,RAV4,4.0,SUV,6,EXR,2T3,GCC,5.0,R6RFV
2,TOYOTA,RAV4,4.0,SUV,6,LE HEV,4T3,GCC,5.0,E6RFV
3,TOYOTA,CAMRY,4.0,SEDAN,6,GLE,LVG,GCC,4.0,B674K
4,TOYOTA,CAMRY,4.0,SEDAN,6,SE,4T1,GCC,4.0,K61AK
...,...,...,...,...,...,...,...,...,...,...
190,TOYOTA,CAMRY HYBRID,4.0,SEDAN,6,S,4T1,NON-GCC,NaN,K61AK
191,TOYOTA,CAMRY HYBRID,4.0,SEDAN,6,S,4T1,NON-GCC,NaN,B61HK
192,TOYOTA,CAMRY HYBRID,4.0,SEDAN,6,S,4T1,NON-GCC,NaN,B61HK
193,TOYOTA,CAMRY HYBRID,4.0,SEDAN,6,SE,4T1,NON-GCC,NaN,K61AK
194,TOYOTA,CAMRY HYBRID,4.0,SEDAN,6,S,4T1,NON-GCC,NaN,K61AK

====================================================================================================
pos5: P
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'OTHERS', 'RAV4', 'LEVIN', 'RAV 4', 'HIACE', 'BZ4X', 'FORTUNER', 'CAMRY', 'HILUX', 'YARIS', 'HIGHLANDER', 'COROLLA 1.8', 'LAND CRUISER', 'FJ CRUISER', 'COROLLA 1.6', 'COROLLA 1.3', 'AVALON']
  bodyType: ['SEDAN', 'COUPE', 'SUV', 'SALOON', 'STATION', 'PANEL VAN', 'PICK UP DOUBLE CAB', 'REGULAR CAB']
  pos5: ['P']
  trim: ['GLI', 'XLI', 'LE', 'STD', 'GXR', 'SE+', 'STD (NON GCC)', 'XLE', 'XLI EXECUTIVE', 'GLI HEV', 'DX', 'EXR', 'PRO', 'TOP', 'SPORT', 'S TRD SPORT PK', 'LEVIN', 'DLX', 'SE', 'DL', 'LIMITED', 'S', 'GL', 'PLATINUM', 'SED', 'AMBIENTE', 'GX', 'GLX', 'BASE', 'GLE', 'AMG', 'XLI ', 'COM', '1000', 'PW CL']
  WMI: ['5YF', 'JT2', 'JT3', 'LVG', 'JTD', 'LXG', 'LFM', '2T1', 'JTE', 'L7X', 'JTS', 'JAA', 'MR2', 'RKM', '9KM', 'JAM', '5AL', 'LHG']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['EPMAE', 'DP02T', 'EPRAE', 'HP10V', 'YP10V', 'BPRBE', 'BPB9E', 'XP10V', 'GP10V', 'BPRHE', 'FPMAE', 'CPA50', 'DPRAE', 'DPMAE', 'AP22C', 'HPRAE', 'VPMAE', 'KP14T', 'GP21A', 'FPEFF', 'APE2C', 'VPRAE', 'FPRAE', 'AP86C', 'FP14F', 'VP9F3', 'CP724', 'DP21A', 'BPWDG', 'CP515', 'BPMBE', 'AP90A', 'LP345', 'VP286', 'CP450', 'NPR66', 'AP54K']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,P,GLI,5YF,GCC,4.0,EPMAE
1,TOYOTA,OTHERS,0.0,COUPE,P,XLI,JT2,GCC,NaN,DP02T
2,TOYOTA,COROLLA,4.0,SEDAN,P,LE,5YF,GCC,4.0,EPRAE
3,TOYOTA,RAV4,4.0,SUV,P,STD,JT3,GCC,3.0,HP10V
4,TOYOTA,RAV4,4.0,SUV,P,GXR,JT3,GCC,5.0,YP10V
...,...,...,...,...,...,...,...,...,...,...
924,TOYOTA,COROLLA,4.0,SEDAN,P,XLI EXECUTIVE,JTD,NON-GCC,NaN,EPMAE
925,TOYOTA,COROLLA,4.0,SEDAN,P,LE,JTD,NON-GCC,NaN,EPRAE
926,TOYOTA,COROLLA,4.0,SEDAN,P,LE,5YF,NON-GCC,NaN,EPRAE
927,TOYOTA,COROLLA,4.0,SEDAN,P,STD (NON GCC),JTD,NON-GCC,NaN,DPRAE
928,TOYOTA,COROLLA,4.0,SEDAN,P,XLI EXECUTIVE,LFM,NON-GCC,NaN,AP22C

====================================================================================================
pos5: 0
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'LAND CRUISER', 'PREVIA', 'SUPRA', 'YARIS', 'RAV4', 'AVALON', 'FORTUNER', 'CAMRY', 'HILUX', 'PRADO', 'ALTIS', 'INNOVA', 'HIACE', 'FJ CRUISER']
  bodyType: ['SEDAN', 'SUV', 'MPV', 'COUPE', 'HATCHBACK', 'PICKUP', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PANEL VAN']
  pos5: ['0']
  trim: ['XLI', 'EXR', 'DLX', 'STD', 'MID', 'LE HEV', 'BASE', 'GLX', 'GXR3', 'GRANDE', 'XLI TOP', 'XLI MID', 'GX', 'GL', 'GLI', 'S', 'VX', 'GXR', 'DL', 'DX', 'LE', 'SE', 'GLE', 'FLEET', 'SE+', 'TOP', 'XLI EXECUTIVE']
  WMI: ['ZSG', 'JTM', 'UP1', 'JZA', '000', 'ZE1', 'NNN', 'WBW', 'AAP', 'FZJ', 'NV1', 'SXV', 'JTE', 'ACV', '4T1', 'YN8', 'EE1', 'MV1', 'LA9', 'W1W', 'WDB', '090', '010', 'MET', 'EP9', 'AVV', 'FJ7', 'A25', 'STM', 'CE1', 'EL5', '4TT']
  regionalSpec: ['NON-GCC', 'GCC']
  VDS: ['10031', 'H009J', '00713', '80001', '00NCP', 'R03FV', '50954', 'N0000', 'B0111', 'V0291', '80002', '80008', '80233', '000NN', '80473', '00800', '80328', '80345', '80850', '80430', '80000', '50012', '00260', '80593', '50189', '80274', '80987', '50258', '10701', '50602', '80583', 'H0093', '80413', '40503', '80943', '50185', '00612', '00856', '80097', '50524', '80636', '80986', '80893', '801FK', '80003', '80907', '60023', '00404', '50470', '80772', '50237', '80063', 'B025J', '40500', '80015', '80281', 'C08RW', '80125', '50975', '80042', 'V0LEZ', '90615', '80533', 'B03FV', '50637', '50333', '50018', '50812', '408B0', '80350', '50287', '50531', '80532', '80876', '303H6', '80459', '0000E', '10030', '80548', '80464', '50391', 'N0001', '50500', '80095', '50229', 'B031V', '50061', '50617', '50671', '50873', '80767', '50017', '50504', '80251', '80761', '80951', 'A0B98', '60019', '000NC', '80078', '50501', '50296', '00943', '80407', '80839', '00898', '10730', 'B011F', '00968', '50090', '80318', '80558', '80506', '80183', '00098', '80950', '80700', '0000J', '80025', 'B046K', '50479', '80890']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,ZSG,NON-GCC,NaN,10031
1,TOYOTA,LAND CRUISER,6.0,SUV,0,EXR,JTM,GCC,5.0,H009J
2,TOYOTA,PREVIA,4.0,MPV,0,DLX,UP1,NON-GCC,NaN,00713
3,TOYOTA,SUPRA,6.0,COUPE,0,STD,JZA,NON-GCC,NaN,80001
4,TOYOTA,YARIS,4.0,HATCHBACK,0,MID,000,NON-GCC,NaN,00NCP
...,...,...,...,...,...,...,...,...,...,...
132,TOYOTA,CAMRY,4.0,SEDAN,0,XLI,NV1,NON-GCC,NaN,80025
133,TOYOTA,CAMRY,4.0,SEDAN,0,GLX,4TT,GCC,NaN,B046K
134,TOYOTA,RAV4,4.0,SUV,0,BASE,JTM,GCC,5.0,B031V
135,TOYOTA,COROLLA,4.0,SEDAN,0,XLI MID,ZE1,GCC,NaN,50479
136,TOYOTA,CAMRY,4.0,SEDAN,0,XLI,NV1,GCC,NaN,80890

====================================================================================================
pos5: 8
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'COROLLA', 'CAMRY', 'COROLLA SEDAN', 'INNOVA', 'HILUX', 'VELOZ', 'LAND CRUISER', 'HIGHLANDER', 'COROLLA 1.6', 'HIACE', 'PRIUS', 'VESPA VXL 150', 'VESPA VXL']
  bodyType: ['SUV', 'SEDAN', 'MPV', 'PICK UP DOUBLE CAB', 'SALOON', 'PANEL VAN', 'HATCHBACK', 'MOTORCYCLE', 'STATION', 'PICK UP DOUBLE CABIN', 'PICKUP DOUBLE CAB']
  pos5: ['8']
  trim: ['EX', 'XLI', 'GL', 'SE+', 'LIMITED', 'GLI', 'DLX', 'GLX', 'VXR', 'GLE', 'GRANDE', 'GXR', '10TH VICTORY EDITION', 'AXL ', 'XLI EXECUTIVE', 'E', 'ECO', 'STD (NON GCC)', 'BLACK EDITION', '60TH', 'LE', 'SE']
  WMI: ['WWW', 'RKL', 'JTN', 'MAT', 'MET', 'LFM', 'MHF', 'JTM', '5TD', 'WV1', 'KMF', 'JTD', '4T1', 'MD6', 'MR0']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['W8888', '889HE', '8846K', '38122', 'M8500', 'C8E2H', '880CE', '38132', 'A818Y', 'A878J', 'L83CH', 'A888J', '88OCE', 'B89HE', '2882K', 'W8X7K', 'K83FU', '8842E', 'K8RFU', 'K820U', '38BS1', '8808E', 'D89CD']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,RAV4,4.0,SUV,8,EX,WWW,GCC,NaN,W8888
1,TOYOTA,COROLLA,4.0,SEDAN,8,XLI,RKL,GCC,NaN,889HE
2,TOYOTA,CAMRY,4.0,SEDAN,8,GL,JTN,GCC,4.0,8846K
3,TOYOTA,CAMRY,4.0,SEDAN,8,SE+,MAT,GCC,NaN,38122
4,TOYOTA,COROLLA SEDAN,0.0,SEDAN,8,XLI,MET,GCC,NaN,M8500
...,...,...,...,...,...,...,...,...,...,...
56,TOYOTA,COROLLA,4.0,SEDAN,8,GLI,RKL,GCC,NaN,889HE
57,TOYOTA,HILUX,4.0,PICK UP DOUBLE CABIN,8,GL,MR0,GCC,NaN,D89CD
58,TOYOTA,HILUX,4.0,PICKUP DOUBLE CAB,8,GL,MR0,GCC,NaN,D89CD
59,TOYOTA,CAMRY,4.0,SEDAN,8,LE,MET,GCC,NaN,M8500
60,TOYOTA,COROLLA,4.0,SEDAN,8,SE,RKL,GCC,NaN,889HE

====================================================================================================
pos5: 9
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIGHLANDER', 'YARIS', 'PRIUS', 'RAV4', 'COROLLA', 'FRONTLANDER', 'GL770ULTRA', '2023', '900']
  bodyType: ['SUV', 'HATCHBACK', 'SEDAN', 'MOTORCYCLE', 'STATION']
  pos5: ['9']
  trim: ['GXR', 'BASE', 'ECO', 'EX', 'LE (NON GCC)', 'GLI', 'STD', '2', 'MID']
  WMI: ['LVG', 'JWT', 'JTD', 'L6T', 'LBB']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['C916Z', '59695', 'L9RFU', '79END', '79YND', 'L9MFU', 'P9900', 'B910L', 'W9235']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,GCC,5.0,C916Z
1,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,JWT,NON-GCC,NaN,59695
2,TOYOTA,PRIUS,4.0,HATCHBACK,9,ECO,JTD,GCC,5.0,L9RFU
3,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,GCC,5.0,C916Z
4,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,GCC,5.0,C916Z
5,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,GCC,5.0,C916Z
6,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,GCC,5.0,C916Z
7,TOYOTA,RAV4,4.0,SUV,9,EX,L6T,GCC,5.0,79END
8,TOYOTA,RAV4,4.0,SUV,9,EX,L6T,GCC,5.0,79YND
9,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,GCC,5.0,C916Z
10,TOYOTA,PRIUS,4.0,HATCHBACK,9,LE (NON GCC),JTD,GCC,5.0,L9MFU
11,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,NON-GCC,5.0,C916Z
12,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,GCC,5.0,C916Z
13,TOYOTA,COROLLA,4.0,SEDAN,9,GLI,L6T,GCC,NaN,79END
14,TOYOTA,FRONTLANDER,4.0,SUV,9,STD,LVG,NON-GCC,5.0,C916Z
15,TOYOTA,GL770ULTRA,NaN,MOTORCYCLE,9,NaN,LBB,GCC,NaN,P9900
16,TOYOTA,2023,4.0,SEDAN,9,2,LVG,GCC,NaN,B910L
17,TOYOTA,900,4.0,STATION,9,EX,L6T,GCC,NaN,79END
18,TOYOTA,HIGHLANDER,4.0,SUV,9,GXR,LVG,GCC,5.0,C916Z
19,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,JTD,GCC,NaN,W9235

====================================================================================================
pos5: S
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'CAMRY', 'SIENNA', 'HILUX', 'HIGHLANDER', 'PREVIA', 'BZ 4', 'RAV4', 'LAND CRUISER', 'FORTUNER', 'INNOVA', 'COROLLA', 'PRADO', 'LAND CRUISER PICK UP']
  bodyType: ['PANEL VAN', 'SEDAN', 'MPV', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'MINI BUS HIGH ROOF', 'SUV', 'HALF PANEL VAN', 'STATION', 'MINI BUS', 'PICKUP', 'PANEL VAN HIGH ROOF', 'PICK UP']
  pos5: ['S']
  trim: ['STD', 'E PLUS HEV', 'LE (NON GCC)', 'DLX', 'GL', 'HYBRID (NON GCC)', 'XSE', 'XLI', 'GRANDE', 'XLE (NON GCC)', 'TRIM', 'XL', 'DX', 'MID', 'GR SPORT', 'GXR MID', 'DL', 'GL LIMITED', 'EXR', 'SPORT', 'GLX', 'SE+', 'LIMITED', 'GLS', 'VX TOP LTH', 'SE', 'LX AC PWR OPT', 'S', 'GXR']
  WMI: ['JT6', 'JTN', '5TD', 'MR0', 'JTG', 'LVG', 'JTE', 'YV2', 'JTF', '2GN', 'UAE', 'LFM', '1FT', 'KMF', 'SAL', 'LS4', 'YV1', '123', 'JHD', '5ZT']
  regionalSpec: ['GCC', 'NON-GCC']
  VDS: ['JS02P', 'ASACK', 'KSKFC', 'ES12G', 'ES46A', 'YSKFC', 'GS54M', 'ASG0A', 'CS12G', 'DS43A', 'HS02P', 'CS18Z', '2S012', 'SS23P', 'AS14U', 'DS41A', 'SS3EL', 'ES41A', 'ZSZ7J', '3S011', 'LSAAE', 'JS8CD', 'ASB3R', 'AS47H', 'AS12G', 'AS123', 'ES43A', 'ZSZ7K', 'ASW0A', 'GSKFC', 'SS1EK', 'AS02A', 'SS22P', 'DSKFC', '2SBPB', 'AS02D', '2S010', '2S011', 'RS12P']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,PANEL VAN,S,STD,JT6,GCC,4.0,JS02P
1,TOYOTA,CAMRY,4.0,SEDAN,S,E PLUS HEV,JTN,GCC,4.0,ASACK
2,TOYOTA,SIENNA,6.0,MPV,S,LE (NON GCC),5TD,GCC,5.0,KSKFC
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,S,DLX,MR0,GCC,4.0,ES12G
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,S,DLX,MR0,GCC,2.0,ES12G
...,...,...,...,...,...,...,...,...,...,...
113,TOYOTA,HIACE,4.0,MINI BUS,S,GL,JTG,GCC,5.0,JS02P
114,TOYOTA,PREVIA,6.0,MPV,S,GL,JTE,GCC,5.0,GS54M
115,TOYOTA,COROLLA,4.0,SEDAN,S,XLI,YV2,NON-GCC,NaN,AS02A
116,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,S,DLX,YV2,GCC,NaN,ASW0A
117,TOYOTA,HILUX,4.0,PICKUP,S,DLX,MR0,GCC,NaN,ES12G

====================================================================================================
pos5: 7
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'HILUX', 'INNOVA', 'CAMRY', 'RUSH', 'COROLLA', 'RAV4', 'SIERRA', 'SEQUOIA', 'U7']
  bodyType: ['PANEL VAN', 'PICK UP DOUBLE CAB', 'MPV', 'SEDAN', 'HATCHBACK', 'SUV', 'MINI BUS HIGH ROOF', 'MINI BUS']
  pos5: ['7']
  trim: ['GL', 'DLX', 'HEV', 'GLX', 'SE', 'STD', 'LE', 'STANDARD', 'S', 'EX', 'A', 'SR5 4X4', 'XLI', 'XLI MID', 'ADVENTURE', 'DX']
  WMI: ['D04', 'MAT', 'LC0', 'MD6', 'LM8', 'JZS', 'LGF', 'ZRE', 'LSJ', '1GT', 'CPB', '074', 'UZS', 'D02', '150', 'RF5', '1GJ']
  regionalSpec: ['NON-GCC', 'GCC']
  VDS: ['2757D', '37418', 'C74C4', '37DE7', 'F7E69', '17100', 'B7A2J', '17255', 'W74U3', 'W78CG', '17257', '87N07', '472AX', '1779D', '87367', 'S71T0', 'F7D19', 'Z78FG', '17256']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,HIACE,4.0,PANEL VAN,7,GL,D04,NON-GCC,NaN,2757D
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,7,DLX,MAT,GCC,4.0,37418
2,TOYOTA,INNOVA,4.0,MPV,7,HEV,LC0,GCC,5.0,C74C4
3,TOYOTA,CAMRY,4.0,SEDAN,7,GLX,MD6,GCC,4.0,37DE7
4,TOYOTA,NaN,4.0,HATCHBACK,7,SE,LM8,GCC,NaN,F7E69
5,TOYOTA,RUSH,4.0,SUV,7,STD,JZS,GCC,NaN,17100
6,TOYOTA,CAMRY,4.0,SEDAN,7,LE,JZS,NON-GCC,NaN,17100
7,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,7,STANDARD,LGF,GCC,4.0,B7A2J
8,TOYOTA,COROLLA,4.0,SEDAN,7,S,ZRE,GCC,NaN,17255
9,TOYOTA,RAV4,4.0,SUV,7,EX,LSJ,GCC,5.0,W74U3
10,TOYOTA,SIERRA,4.0,MPV,7,A,1GT,GCC,NaN,W78CG
11,TOYOTA,COROLLA,4.0,SEDAN,7,SE,ZRE,NON-GCC,NaN,17257
12,TOYOTA,COROLLA,4.0,SEDAN,7,S,ZRE,NON-GCC,NaN,17255
13,TOYOTA,CAMRY,4.0,SEDAN,7,S,CPB,GCC,NaN,87N07
14,TOYOTA,SEQUOIA,8.0,SUV,7,SR5 4X4,074,GCC,5.0,472AX
15,TOYOTA,CAMRY,8.0,SEDAN,7,STD,UZS,GCC,NaN,17100
16,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,D02,NON-GCC,NaN,1779D
17,TOYOTA,COROLLA,4.0,SEDAN,7,XLI MID,150,NON-GCC,NaN,87367
18,TOYOTA,U7,4.0,SEDAN,7,GLX,RF5,GCC,NaN,S71T0
19,TOYOTA,RAV4,4.0,SUV,7,ADVENTURE,LM8,GCC,NaN,F7D19
20,TOYOTA,HIACE,8.0,MINI BUS,7,DX,1GJ,GCC,NaN,Z78FG
21,TOYOTA,COROLLA,4.0,SEDAN,7,SE,ZRE,NON-GCC,NaN,17256

====================================================================================================
pos5: I
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'CAMRY']
  bodyType: ['SUV', 'SEDAN']
  pos5: ['I']
  trim: ['VX', 'XLE', 'LE HEV']
  WMI: ['JTM', 'JTN', '2T3']
  regionalSpec: ['GCC']
  VDS: ['CIRFV', 'AI4CK', 'WIRFV', 'FIRFV']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos5,trim,WMI,regionalSpec,noOfDoors,VDS
0,TOYOTA,RAV4,4.0,SUV,I,VX,JTM,GCC,5.0,CIRFV
1,TOYOTA,CAMRY,4.0,SEDAN,I,XLE,JTN,GCC,4.0,AI4CK
2,TOYOTA,RAV4,4.0,SUV,I,LE HEV,2T3,GCC,5.0,WIRFV
3,TOYOTA,RAV4,4.0,SUV,I,VX,JTM,GCC,5.0,FIRFV
4,TOYOTA,RAV4,4.0,SUV,I,VX,JTM,GCC,5.0,FIRFV
5,TOYOTA,RAV4,4.0,SUV,I,XLE,2T3,GCC,5.0,WIRFV
6,TOYOTA,RAV4,4.0,SUV,I,XLE,2T3,GCC,5.0,WIRFV