In [159]:
import pandas as pd
import glob

# Reading the csv file

In [160]:
data = pd.read_csv(r"..\data\data_methaq(1.0).csv")
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan
...,...,...,...,...,...,...,...,...,...,...
1009599,LNGPCMXJ9PL305272,NaN,NaN,APULUO,APULUO AP200 4H,2023.0,Motorcycle,GCC,NaN,China
1009600,LURJAVBM8PA024843,STD,4.0,AIQAR,EQ 1,2023.0,COUPE,GCC,NaN,CHINA
1009601,7KGTC2C48NR003646,NaN,NaN,Electric Motion,ePure,2022.0,Motorcycle,GCC,NaN,AMERICA
1009602,LX6TK334XS2510023,NaN,NaN,CHANGHUA,CH150T-34,2025.0,Motorcycle,GCC,NaN,China
1009603,MI76734700,GL,4.0,MANITOU,MTX1740SLT,2015.0,HEAVY EQUIPMENT,GCC,NaN,Italy

In [161]:
import pandas as pd

data = pd.read_csv(r"../data/data_methaq(1.0).csv")

for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

       chassisNumber trim  cylinders    make    model    year  \
0  RKLBB9HE7F5115863   SE        4.0  TOYOTA  COROLLA  2015.0
1  JTFHX02POF0099797  GLX        4.0  TOYOTA    HIACE  2015.0
2  JTFHX02P7F0094323   DX        4.0  TOYOTA    HIACE  2015.0
3  JTFHXDGP7F0094373   DL        4.0  TOYOTA    HILUX  2015.0
4  4T1BG22K01U789089  XLI        4.0  TOYOTA    CAMRY  2001.0

             bodyType regionalSpec  noOfDoors  origin
0               SEDAN          GCC        4.0  TAIWAN
1  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
2  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
3  PICK UP DOUBLE CAB          GCC        4.0   JAPAN
4               SEDAN      NON-GCC        4.0   JAPAN

In [162]:
data = data[data["make"] == "TOYOTA"]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN
...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN

# checking chassis number length and 10th pos

In [163]:
data["chassis_len"] = data["chassisNumber"].str.len()
data["pos10"] = data["chassisNumber"].str[9]

is_standard = (data["chassis_len"] == 17) & (~data["pos10"].isin(['I', 'O', 'Q', 'U', 'Z', '0']))
data = data[is_standard]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,chassis_len,pos10
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,17,F
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,17,F
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,17,F
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,17,F
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,17,1
...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,17,K
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,17,S
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,17,M
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,17,S
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,17,M

In [164]:
data["WMI"] = data["chassisNumber"].str[0:3]
data["pos0"] = data["chassisNumber"].str[0]
data["pos1"] = data["chassisNumber"].str[1]
data["pos2"] = data["chassisNumber"].str[2]
data["VDS"] = data["chassisNumber"].str[3:8]
data["pos4"] = data["chassisNumber"].str[3]
data["pos5"] = data["chassisNumber"].str[4]
data["pos6"] = data["chassisNumber"].str[5]
data["pos7"] = data["chassisNumber"].str[6]
data["pos8"] = data["chassisNumber"].str[7]
data["Model_Year"] = data["chassisNumber"].str[9]
data["Plant_Code"] = data["chassisNumber"].str[10]
data["Serial_Number"] = data["chassisNumber"].str[11:17]

C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["WMI"] = data["chassisNumber"].str[0:3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos0"] = data["chassisNumber"].str[0]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos1"] = data["chassisNumber"].str[1]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos2"] = data["chassisNumber"].str[2]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["VDS"] = data["chassisNumber"].str[3:8]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos4"] = data["chassisNumber"].str[3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos5"] = data["chassisNumber"].str[4]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos6"] = data["chassisNumber"].str[5]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos7"] = data["chassisNumber"].str[6]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos8"] = data["chassisNumber"].str[7]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Model_Year"] = data["chassisNumber"].str[9]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Plant_Code"] = data["chassisNumber"].str[10]
C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\2455094619.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Serial_Number"] = data["chassisNumber"].str[11:17]

In [165]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos2,VDS,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,L,BB9HE,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,F,HXDGP,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,1,BG22K,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,0,HU8CD,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,M,ABBBJ,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,M,HX01J,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,E,AACAJ,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,F,B29F3,B,2,9,F,3,M,2,123579

data[["pos1", "origin"]]

In [166]:
print(data['chassisNumber'].nunique())

239212

In [167]:
print(data['pos1'].unique())

['K' 'T' 'R' 'H' 'I' 'N' 'Z' 'V' 'M' 'D' 'Y' 'F' 'B' 'E' 'S' 'W' 'J' 'A'
 '0' 'G' '3' 'C' 'P' 'X' '1' '8' '7' 'L' '6' '2' '5' '9' 'U']

In [168]:
print(data['trim'].nunique())

353

In [169]:
print(data['trim'].unique())

['SE' 'GLX' 'DX' 'DL' 'XLI' 'VX' 'MID' 'DLX' 'VXR' 'FABRIC' 'E' 'TOP'
 'EXTREME' 'GL' 'BASE' 'S' 'FLEET' 'STD (NON GCC)' 'GXR' 'EXR'
 'SE+ ANNIVERSARY EDITION' 'GL2' 'SR5' 'STD' 'LE' 'XLI MID' 'LE (NON GCC)'
 'SE+' 'GLI' 'SR5 (NON GCC)' 'TX' 'LIMITED' 'XLE (NON GCC)'
 'SE TRD AERO PK' 'EX' 'ICONIC' 'VX MID' 'LE HEV' 'SGLX' 'PW CL' 'GX'
 'XLE' 'SPORT' 'G' 'GRANDE' 'GR' 'XLI TOP' 'S TRD SPORT PK' 'S+' 'PRO'
 'XLI RB' 'LIMITED PREMIUM' 'GLE' 'XLI EXECUTIVE' 'GLS' 'PLATINUM'
 'DLX TOP' 'TURBO G RA' 'LIMITED (NON GCC)' 'SR5 4X4' 'VXR HEV' 'GLE HEV'
 'SAFARI' 'LX' 'GXR TOP 60TH ANNIV. XTREME' 'CE (NON GCC)' 'GLI HEV'
 'PREMIUM' 'XLI EXECUTIVE MR' 'XL' 'GXR TOP' 'VXR BASE' 'LX AC PWR OPT'
 'LX WINCH' 'TX-L' 'XLE TOURING' 'GXR GT' 'DLS' 'VXR TOP' 'SC'
 'GLE-X HEV 40TH ANNIV' 'SALOON' nan 'ADVENTURE'
 'CREWMAX CAPSTONE (NON GCC)' 'LE STD' 'LIMITED MID' 'GX TOP' 'TX-L TOP'
 'GLI TOP' 'EXCLUSIVE' 'XSE (NON GCC)' 'BLACK EDITION' 'DX H/R W/B'
 'C (NON GCC)' 'XLI POWER OPT' 'GLX SPORT Z' 'S PLUS' 'VTX' 'GXL' 'HT SWB'
 'GXR MID' 'ECO' 'GX MID' 'GXR2' 'LWB HIGH ROOF' '1794 EDITION (NON GCC)'
 '40TH ANNIVERSARY EDITION' 'TOURING' 'HEV' 'GLI TOP LTH' 'PS PW CL'
 'LIMITED 4X4' 'GR SPORT' 'STD D' 'TXL1' 'LWB' 'DLS - STD ROOF' 'EXR HEV'
 'LSE' 'BE' 'GLE-X' 'GT' 'T' 'SWB' 'SE (NON GCC)' 'SR' 'GTX' 'TXL3'
 'GR TAN EDITION' 'ST' 'E PLUS HEV' '1.8' 'LIMITED 4X2' 'VX TOP LTH' 'VX2'
 'STANDARD' 'SV' 'SR5 4X2' 'VX1' 'GXR FMST' 'HEV GLI' 'GXR1' 'DYNAMIC'
 'XLI EXECUTIVE HEV' '1' 'GR-S' 'FJ STD' 'GR BLUE EDITION' 'TRD' 'YX'
 'GXR TOP DMST' 'LMV' 'CTD' 'HT VXR' 'LIMITED TRD SPORT PK' 'VXR TOP LTH'
 'TXR' 'XLE HEV' 'STD AC' 'XLT' 'COUPE' '1500' 'X' 'TRD OFF-ROAD' 'BUS'
 'GLE HEV BLACK EDITION' 'Y PLUS' 'SR (NON GCC)' 'STATION' 'PICK UP' 'TX1'
 'SEDAN' 'GXR SOD D/AC AW' 'TC (NON GCC)' 'LIMITED HEV' 'SL' 'XTREME'
 'TXL2' 'GXR4' 'GXR TOP FMST' 'GT SPORT' 'HARD TOP' 'HYBRID (NON GCC)'
 'GL TOP' 'XSE' 'GRD' 'L' 'SGL' 'SED' '2400' 'GRANDE HEV 40TH ANNIV' 'AIR'
 'TRD SPORT' 'STANDDARD' '0' 'AXL ' 'XLI - AW' 'TURBO G' 'GXR-V' 'STAN'
 'VT' 'GA' 'GXR+' '2.0L' '25HX' 'PREMIER' 'GXR3' '6' 'SE TRD SPORT PK'
 'AUTOMATIC' 'LUMIERE HEV' 'STANDER' 'TRIM' 'LEVIN' 'HILUX' 'EXI'
 'LAND CRUSIER' '4X4' 'XE 4WD' 'A' 'STATION1' 'GXR MID 60TH ANNIV. XTREME'
 'VXR MID' 'PICKUP' 'S ASF' 'GL DECKLESS' 'CRESSIDA' 'LS' 'HYBRID'
 'LUXURY' 'GF' 'HT SLWB' 'CABRIO' 'ADVENTTURE' 'STD CARGO' 'HYCROSS' 'GG'
 'STATION ' 'SLD' 'C' 'PRESTIGE' 'Y' 'LUMIERE 40TH ANNIV' 'GRANDE HEV'
 'PIKUP' 'PRADO' 'LTD HEV' '10TH VICTORY EDITION' 'ROYAL' 'GL LIMITED'
 'CE' 'LIMITED TRD AERO PK' 'SS' 'VX2 PLUS' 'FULL OPTION' 'VXR TOP XTREME'
 '4WD' 'GLI TOP LEATHER' '60TH' 'AT' 'GXL 1ST EDITION' 'USF'
 'DLS HIGH ROOF' '1500 CREWCAB SLE Z71' 'ORION' 'STANDERD' 'VX-L MID'
 'GGG' 'GLS TOP' 'COMFORT' 'MPV' 'VIP7' 'LTZ' '45' 'LIMITED TOP'
 'EXECUTIVE' 'STD  (NON GCC)' '4' 'PLATINUM LUXURY 4X4' 'N' 'NON GCC'
 'GLI MR HEV' 'SENA' 'CAR TRIM' 'LX WIDE TYRES' 'SPORTS' 'COASTER'
 'S T2 TOP' 'AMBIENTE' 'VX-L TOP' 'PICKUP ' 'LUXURY SPORT' 'GV'
 'ADVENTURE 1ST EDITION' 'ASD' 'AA' 'AMG' 'YA' 'TR' 'EXCELLENCE' 'SU'
 'GLX PREMIUM' 'ZX' 'TUNDRA' 'GLS LOWLINE' 'SUPER SAFARI T1' 'ABC'
 'DOUBLE CABIN ' 'GL LTH' 'DTD' 'ROYAL EDITION' '2' 'ASAD' 'LXI' '1.5'
 'GC' 'GXR MID XTREME' '90' 'TOP LTH' 'STEALTH' 'ALTIS (NON GCC)' 'H'
 'S TRD AERO PK' '40 TFSI S-LINE' 'SUV' 'SE T2' 'FR-S (NON GCC)' 'DC'
 'LE PLATINUM CITY' 'PICK' 'GXR MID 60TH ANNIVERSARY' 'SLT' 'SINGLE CABIN'
 'S T1' 'VTI' 'CARRERA GTS' 'EX MID' 'TRTIM' 'VAN' 'XLI ' 'TAXI' 'COM'
 'IM' 'GXR HEV' '1000' 'SPORTS BASIC' 'ADVENTURE 1ST EDITIO'
 '40TH ANNIVERSARY EDI' 'GXR TOP 60TH ANNIV. ' '1794 EDITION (NON GC'
 'XLI HEV' 'SE+ ANNIVERSARY EDIT' 'CREWMAX CAPSTONE (NO']

In [170]:
print(data['bodyType'].unique())

['SEDAN' 'MINI BUS HIGH ROOF' 'PICK UP DOUBLE CAB' 'SUV' 'HATCHBACK'
 'PICK UP SINGLE CAB' 'PANEL VAN' 'BUS' 'MPV' 'ESTATE' 'PICK UP' 'VAN'
 'MINI BUS' 'COUPE' 'SUV- CROSSOVER' 'PICKUP' 'SALOON'
 'PANEL VAN HIGH ROOF' 'STATION' 'HALF PANEL VAN' 'CONVERTIBLE'
 'CARGO VAN' 'MINIVAN' 'MINI BUS SEMI HIGH ROOF' 'CARAVAN' 'PICKUP TRUCK'
 'LIGHT VEHICLE' 'MOTORCYCLE' 'PICKUP SINGLE CABIN' 'TRUCK'
 'PICK UP DOUBLE CABIN' 'PICKUP DOUBLE CABIN' 'COUPE/CABRIOLET'
 'AMBULANCE' 'REGULAR CAB' 'PICKUP DOUBLE CAB' 'WINDOW VAN' 'WAGON'
 'PICK-UP']

In [171]:
print(data['bodyType'].nunique())

39

In [172]:
print(data['WMI'].unique())

['RKL' 'JTF' '4T1' 'JTM' 'JTD' 'MR0' 'JTE' 'MR2' '6T1' '5TF' 'MHF' 'JTN'
 'JTC' 'JTG' '5TD' '4TA' 'JIF' 'MHK' 'MRO' 'MR1' '1NX' '2T3' 'JT3' 'JT2'
 'WZ1' '2T1' 'LVG' 'NMT' 'WDB' '5YF' 'JT4' '4T4' 'JTB' 'LFM' '3TM' 'JF1'
 '5TB' '7MU' 'MBJ' '3MY' 'ANE' '1N4' '8T1' '4T3' '5TE' 'JTK' 'ZE1' 'KMF'
 'STB' 'ZSG' 'VNK' 'WWW' 'JD4' 'JT6' 'STF' 'SJK' '3TY' 'LFP' 'JAA' 'JMY'
 'JJ5' 'LA7' 'WV1' 'YV2' 'MHE' 'INX' 'JN8' 'JNB' 'JTV' 'D04' 'JHG' '1GC'
 'JN6' 'SYF' 'GTF' 'KN9' '137' '4TI' 'LZC' 'LVC' 'ZGE' '6TI' '2CN' 'JWT'
 'MB1' 'JM3' 'UP1' 'KNC' 'MM7' 'STD' 'YS2' 'JZA' 'LXG' 'ZAP' 'JCB' 'LHA'
 'MA1' '000' 'ME4' 'JHE' '4TT' '411' 'RP8' 'U8Q' 'ITG' 'LGW' 'JHH' 'RA6'
 'MMM' '5T1' 'MAF' 'JT0' 'TNX' 'LWL' 'LA6' 'MA3' 'WDD' '9BS' '2FU' 'KNF'
 'NNN' '5T8' 'MMB' 'WBW' '57W' 'MRI' 'LTA' 'LFV' 'JTH' 'ZRE' 'JHF' 'WMA'
 'JL6' 'LVA' 'MAT' 'LKL' 'LZW' 'AAP' '7SV' 'VF3' 'ACV' '5TT' 'KN3' '1FD'
 'KMH' 'MZB' 'JND' 'MET' '213' 'MRD' '5FP' 'MD2' 'ITN' '2C4' 'JN1' 'ZZE'
 'LTV' 'CLG' 'LRR' 'LJ1' '2GN' '1D7' 'JIM' 'LCF' 'L7X' 'JTS' 'FZJ' 'LEF'
 '2GC' 'LC0' 'KMJ' '1FT' '611' 'MLH' 'UAE' 'JAC' '3N6' 'WD4' 'LSK' '5HD'
 'IG1' 'WMW' 'JH4' 'KLA' 'GT1' 'MD6' 'NV1' 'MNT' 'LK1' 'KPD' 'STO' 'JTL'
 'JT8' 'RKM' 'SCR' 'WDA' 'LZZ' 'WYU' 'WCY' 'NSP' 'KL7' 'MMC' 'LM8' '00N'
 'NCP' '1GN' '1GD' 'LJN' 'GGG' 'JRN' 'KPB' '4T2' 'LET' 'WAU' 'KL3' 'KN4'
 'JT5' 'WME' 'UTG' '3N1' 'JL5' 'JL7' 'JHD' 'LCO' 'JTZ' 'LSC' 'SAL' 'MH3'
 'ZFC' 'LPS' 'N1N' 'JD2' 'JZS' '1GT' '1C6' 'VR3' 'MYN' '6TT' 'LS4' 'JJ7'
 'WD8' 'YV1' 'KLI' 'VS5' 'SXV' 'LVV' 'MFH' 'L3H' 'HJN' 'ZGU' 'JE3' '5XX'
 'JN2' 'L6T' 'J1G' 'WZI' 'LSG' 'JS1' 'JHM' '6TD' '2TI' '3GY' '1G6' '211'
 '9KM' 'MC1' 'AR2' 'JIN' 'JIG' '1HD' 'JA3' 'LGD' '1C4' '1ST' 'RN1' 'LVB'
 'JNC' 'LGF' 'MEJ' 'KNR' '123' '5NF' 'SMV' 'WBA' 'RK4' 'MDH' 'STE' 'LSJ'
 'KL1' '55S' 'LM6' 'FJ4' 'YN8' 'LSF' 'MBI' '471' 'EE1' 'MC2' 'MKH' 'JNK'
 'JTJ' '2HN' '454' '6T0' 'RKT' 'MV1' 'MK2' '1GJ' 'UTD' '5N1' 'RKE' 'LMX'
 '1G1' 'LK6' 'JTR' 'YAR' 'BT1' '4F4' '8LT' 'LA9' 'MPA' '671' '1TF' '1N6'
 'CTF' 'W1W' 'SXA' 'LSY' '1TG' '1N1' 'LHP' 'JAM' '3D7' 'MPJ' 'IN6' '5AL'
 'MP2' 'JM7' 'LZY' 'ITD' '1C8' 'LAZ' '090' 'INB' 'W11' 'CPB' '6TB' 'KNA'
 'JH2' 'STY' '074' '010' 'JS2' 'SMT' 'ST1' '5T0' 'LHG' 'WV2' 'UZS' 'VF1'
 'STM' '2D4' 'W01' 'JYM' 'EP9' '3TD' 'D02' 'J1D' 'L3A' 'VF7' 'MRU' 'JTU'
 'KL5' 'ZCF' 'K1K' 'ZT3' 'LFZ' '61L' 'AVV' 'JTA' 'JDT' 'FJ7' 'ITE' 'LS6'
 '5GT' 'M0F' 'AUS' '150' 'RF5' 'AT1' 'LVM' 'VZE' 'CM8' 'JT1' 'LBB' 'XWB'
 'L11' 'HJR' '4T0' '180' 'YBL' 'MHM' '1G0' 'WB1' '6TF' '1V2' '425' '1HG'
 '1G2' '111' 'WVG' 'A25' 'WVW' 'LVZ' '25T' 'LGJ' 'HA9' 'LFB' 'LNB' 'W1K'
 '474' '174' 'KNM' 'YSM' 'JED' '1LN' 'MB0' 'MBT' '5ZT' '3GN' 'WP0' 'CE1'
 'AS3' 'ET1' 'MFF' 'J10' '3T1' 'MHP' 'LFC' 'EL5' 'GX9' '1TM' 'AE1' 'HJ4'
 'BKL' 'K20' 'SKF' 'LDP' 'MRC' 'UTM' 'JNE']

In [173]:
print(data['WMI'].nunique())

451

In [174]:
filtered_data = data[data['pos1'] == 'T']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2 origin               model
1       TOYOTA  JTF    J    T    F  JAPAN               HIACE
2       TOYOTA  JTF    J    T    F  JAPAN               HIACE
3       TOYOTA  JTF    J    T    F  JAPAN               HILUX
4       TOYOTA  4T1    4    T    1  JAPAN               CAMRY
5       TOYOTA  JTM    J    T    M  JAPAN        LAND CRUISER
...        ...  ...  ...  ...  ...    ...                 ...
922347  TOYOTA  6T1    6    T    1    NaN        CAMRY HYBRID
922349  TOYOTA  6T1    6    T    1    NaN        CAMRY HYBRID
922351  TOYOTA  JTM    J    T    M    NaN        LAND CRUISER
922352  TOYOTA  JTM    J    T    M    NaN        LAND CRUISER
922353  TOYOTA  JTE    J    T    E    NaN  LAND CRUISER PRADO

[179111 rows x 7 columns]

In [175]:
filtered_data = data[data['pos1'] != 'T']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2    origin          model
0       TOYOTA  RKL    R    K    L    TAIWAN        COROLLA
7       TOYOTA  MR0    M    R    0  THAILAND          HILUX
11      TOYOTA  MR2    M    R    2  THAILAND          YARIS
15      TOYOTA  MR0    M    R    0  THAILAND          HILUX
17      TOYOTA  RKL    R    K    L    TAIWAN        COROLLA
...        ...  ...  ...  ...  ...       ...            ...
922339  TOYOTA  VNK    V    N    K       NaN          YARIS
922344  TOYOTA  RKL    R    K    L       NaN  COROLLA CROSS
922348  TOYOTA  MHK    M    H    K       NaN         AVANZA
922350  TOYOTA  MR0    M    R    0       NaN          HILUX
922354  TOYOTA  MHF    M    H    F       NaN          YARIS

[60103 rows x 7 columns]

In [176]:
data[['make', 'pos0', 'origin']]

          make pos0  origin
0       TOYOTA    R  TAIWAN
1       TOYOTA    J   JAPAN
2       TOYOTA    J   JAPAN
3       TOYOTA    J   JAPAN
4       TOYOTA    4   JAPAN
...        ...  ...     ...
922350  TOYOTA    M     NaN
922351  TOYOTA    J     NaN
922352  TOYOTA    J     NaN
922353  TOYOTA    J     NaN
922354  TOYOTA    M     NaN

[239214 rows x 3 columns]

In [177]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos2,VDS,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,L,BB9HE,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,F,HXDGP,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,1,BG22K,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,0,HU8CD,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,M,ABBBJ,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,M,HX01J,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,E,AACAJ,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,F,B29F3,B,2,9,F,3,M,2,123579

# Cutting out wrong data

In [178]:
data_pos0_1 = data[data['pos0'] == '1']
data_pos0_1[['make','pos0', 'WMI','origin']]

          make pos0  WMI         origin
96      TOYOTA    1  1NX        AMERICA
863     TOYOTA    1  1NX  UNITED STATES
956     TOYOTA    1  1NX            USA
1191    TOYOTA    1  1N4          JAPAN
1494    TOYOTA    1  1NX        AMERICA
...        ...  ...  ...            ...
919730  TOYOTA    1  1NX            NaN
920802  TOYOTA    1  1NX            NaN
920945  TOYOTA    1  1NX            NaN
921403  TOYOTA    1  1NX            NaN
921876  TOYOTA    1  1NX            NaN

[1334 rows x 4 columns]

In [179]:
print(data_pos0_1['origin'].unique())

['AMERICA' 'UNITED STATES' 'USA' 'JAPAN' 'PAKISTAN' 'CANADA'
 'UNITED KINGDOM' 'UAE' nan 'TAIWAN' 'THAILAND' 'SOUTH AMERICAN'
 'GUAM (USA)']

In [180]:
data_pos0_4 = data[data['pos0'] == '4']
data_pos0_4[['make','pos0', 'WMI','origin']]

          make pos0  WMI         origin
4       TOYOTA    4  4T1          JAPAN
26      TOYOTA    4  4T1  UNITED STATES
38      TOYOTA    4  4T1          JAPAN
57      TOYOTA    4  4T1          JAPAN
63      TOYOTA    4  4TA          JAPAN
...        ...  ...  ...            ...
922268  TOYOTA    4  4T1            NaN
922273  TOYOTA    4  4T1            NaN
922314  TOYOTA    4  4T1            NaN
922322  TOYOTA    4  4T1            NaN
922334  TOYOTA    4  4T1            NaN

[22374 rows x 4 columns]

In [181]:
print(data_pos0_4['origin'].unique())

['JAPAN' 'UNITED STATES' 'AUSTRALIA' 'USA' 'AMERICA' 'UNITED KINGDOM'
 'UAE' 'UNITED STATES VIRGIN ISLANDS' 'UNITED NATIONS' nan 'CANADA'
 'GUAM (USA)' 'AFGHANISTAN' 'UNITED ARAB EMIRATES' 'GERMANY' 'U.S.A'
 'MACAU' 'NON GCC' 'ITALY' 'USA MINOR OUTLYING ISLANDS' 'INDIA' 'AUSTRIA'
 'CAMEROON' 'AMERICAN' 'MAE' 'SOUTH KOREA' 'KOREA' 'GCC'
 'PAPUA NEW GUINEA' 'GUINEA' 'YEMEN' 'SPAIN' 'JAPANN' 'اليابان' 'RUSSIA'
 'CHINA' 'A' 'SOUTH AMERICAN' 'AMERICAN SAMOA' 'GREAT BRITAIN'
 'VIRGIN ISLANDS (USA)' 'JERSEY' 'UMM AL QUWAIN' 'GREECE' 'PAKISTAN'
 'KOREA SOUTH' 'ASIAN' 'EMIRATES']

In [182]:
data_pos0_5 = data[data['pos0'] == '5']
data_pos0_5[['make','pos0', 'WMI','origin']]

          make pos0  WMI         origin
25      TOYOTA    5  5TF        AMERICA
50      TOYOTA    5  5TD        AMERICA
61      TOYOTA    5  5TD        AMERICA
69      TOYOTA    5  5TD          JAPAN
112     TOYOTA    5  5TD  UNITED STATES
...        ...  ...  ...            ...
922272  TOYOTA    5  5TF            NaN
922289  TOYOTA    5  5TD            NaN
922302  TOYOTA    5  5TF            NaN
922313  TOYOTA    5  5TD            NaN
922337  TOYOTA    5  5TD            NaN

[14143 rows x 4 columns]

In [183]:
print(data_pos0_5['origin'].unique())

['AMERICA' 'JAPAN' 'UNITED STATES' 'USA' 'CANADA'
 'UNITED STATES VIRGIN ISLANDS' 'AMERICAN SAMOA' 'GUAM (USA)' 'CHINA'
 'UNITED STATES VIRGIN' 'UAE' 'UNITED KINGDOM' nan 'AUSTRALIA' 'GUINEA'
 'UNITED NATIONS' 'JAMERICA' 'US' 'NORTH AMERICA' 'AFGHANISTAN'
 'الولايات المتحدة' 'MEXICO' 'INDIA' 'USA MINOR OUTLYING ISLANDS'
 'N AMERICAN COUNTRIES' 'SOUTH KOREA' 'امريكا' 'EGYPT' 'GCC' 'THAILAND'
 'SLOVAKIA' 'SILVER' 'INDONESIA' 'UNITED ARAB EMIRATES' '000' '00'
 'AMERICA ' 'VIRGIN ISLANDS (USA)' 'GERMANY' 'JAPANE' 'GREAT BRITAIN'
 'TURKEY' 'BELGIUM' 'EMIRATES' 'KOREA' 'AMERICAN']

In [184]:
data_pos0_2 = data[data['pos0'] == '2']
data_pos0_2[['make','pos0', 'WMI','origin']]

          make pos0  WMI         origin
106     TOYOTA    2  2T3         CANADA
158     TOYOTA    2  2T3         CANADA
206     TOYOTA    2  2T1         CANADA
222     TOYOTA    2  2T1  UNITED STATES
293     TOYOTA    2  2T1          JAPAN
...        ...  ...  ...            ...
921738  TOYOTA    2  2T3            NaN
921772  TOYOTA    2  2T1            NaN
922102  TOYOTA    2  2T3            NaN
922176  TOYOTA    2  2T1            NaN
922227  TOYOTA    2  2T3            NaN

[4606 rows x 4 columns]

In [185]:
print(data_pos0_2['origin'].unique())

['CANADA' 'UNITED STATES' 'JAPAN' 'UNITED STATES VIRGIN' 'TAIWAN'
 'AMERICA' 'USA' 'OTHERS' 'GREECE' 'SOUTH KOREA' nan 'KENYA' 'CHINA'
 'BELGIUM' 'PAPUA NEW GUINEA' 'MOROCCO' 'UAE' 'CAPAN' 'GHANA'
 'UNITED KINGDOM' 'GERMANY' 'HUNGARY' 'UNITED ARAB EMIRATES' 'MYANMAR'
 'THAILAND' 'ITALY' 'JAE']

In [186]:
data_pos0_3 = data[data['pos0'] == '3']
data_pos0_3[['make','pos0', 'WMI','origin']]

          make pos0  WMI  origin
591     TOYOTA    3  3TM  MEXICO
1078    TOYOTA    3  3MY  MEXICO
2143    TOYOTA    3  3MY  MEXICO
3807    TOYOTA    3  3TY  MEXICO
5134    TOYOTA    3  3TM  MEXICO
...        ...  ...  ...     ...
919288  TOYOTA    3  3TM     NaN
920443  TOYOTA    3  3MY     NaN
920696  TOYOTA    3  3TY     NaN
921571  TOYOTA    3  3TM     NaN
921814  TOYOTA    3  3TM     NaN

[313 rows x 4 columns]

In [187]:
print(data_pos0_3['origin'].unique())

['MEXICO' 'AMERICA' 'JAPAN' 'UNITED STATES' 'USA' nan 'UAE'
 'UNITED ARAB EMIRATES']

In [188]:
data_pos0_J = data[data['pos0'] == 'J']
data_pos0_J[['make','pos0', 'WMI','origin']]

          make pos0  WMI origin
1       TOYOTA    J  JTF  JAPAN
2       TOYOTA    J  JTF  JAPAN
3       TOYOTA    J  JTF  JAPAN
5       TOYOTA    J  JTM  JAPAN
6       TOYOTA    J  JTD  JAPAN
...        ...  ...  ...    ...
922345  TOYOTA    J  JTN    NaN
922346  TOYOTA    J  JTM    NaN
922351  TOYOTA    J  JTM    NaN
922352  TOYOTA    J  JTM    NaN
922353  TOYOTA    J  JTE    NaN

[112811 rows x 4 columns]

In [189]:
print(data_pos0_J['origin'].unique())

['JAPAN' 'AMERICA' 'UNITED STATES' 'TAIWAN' 'THAILAND' 'YEMEN' 'USA' 'UAE'
 nan '000' 'IRAN' 'PAPUA NEW GUINEA' 'INDIA' 'SUDAN' 'GREECE' '00'
 'UNITED ARAB EMIRATES' 'AUSTRALIA' '0' 'EMIRATES' 'GCC' 'CANADA' 'INDIAN'
 'تركيا' 'GERMANY' 'CHINA' 'JPAN' 'SOUTH KOREA' 'اليابان' 'G' 'HUNGARY'
 'FRANCE' 'SAUDI ARABIA' 'A' 'آتيانیان' 'SYRIA' 'MEXICO' 'ITALY' '4'
 'ASIAN' 'INDONESIA' 'NEW GUINEA' 'EGYPT' 'KOREA' 'JAMAICA' 'SUD' 'الريان'
 'MYANMAR' 'UNITED KINGDOM' 'HAQUARI' 'TURKEY' 'SPAIN' 'ORIGIN'
 'LIGHT VEHICLE' 'TOYOTA' 'JAPA' '11' 'BELGIUM' 'EUROPEAN UNION'
 'HONDURAS' 'AUSTRIA' 'JORDAN' 'JARAN' 'PARAGUAY' 'NORTH KOREA' 'MOROCCO'
 'S' 'SAPAN' 'SLOVAKIA' 'AFGHANISTAN' 'AMERICAN' 'J. PAN' '1' 'NON GCC'
 'JAPANE' 'PAKISTAN' 'OMAN' '17750' 'KOSOVO' 'QATAR' 'الصين' 'MACAU']

In [190]:
data_pos0_K = data[data['pos0'] == 'K']
data_pos0_K[['make','pos0', 'WMI','origin']]

          make pos0  WMI       origin
2061    TOYOTA    K  KMF  SOUTH KOREA
9355    TOYOTA    K  KN9  SOUTH KOREA
12446   TOYOTA    K  KNC  SOUTH KOREA
25132   TOYOTA    K  KNF  SOUTH KOREA
29667   TOYOTA    K  KNC  SOUTH KOREA
...        ...  ...  ...          ...
205287  TOYOTA    K  KMF  SOUTH KOREA
231432  TOYOTA    K  KMJ  SOUTH KOREA
233212  TOYOTA    K  KMF  SOUTH KOREA
236789  TOYOTA    K  K20          NaN
241401  TOYOTA    K  KMJ  SOUTH KOREA

[86 rows x 4 columns]

In [191]:
print(data_pos0_K['origin'].unique())

['SOUTH KOREA' 'KOREA' 'REPUBLIC OF SOUTH KOREA' nan 'NORTH KOREA' 'JAPAN'
 'INDONESIA']

In [192]:
data_pos0_W = data[data['pos0']== 'W']
data_pos0_W[['make','pos0', 'WMI','origin']]

          make pos0  WMI   origin
196     TOYOTA    W  WZ1  AUSTRIA
284     TOYOTA    W  WDB  GERMANY
2183    TOYOTA    W  WZ1  AUSTRIA
2383    TOYOTA    W  WZ1  AUSTRIA
2923    TOYOTA    W  WWW    JAPAN
...        ...  ...  ...      ...
241240  TOYOTA    W  WDB  GERMANY
920066  TOYOTA    W  WZ1      NaN
920857  TOYOTA    W  WZ1      NaN
921262  TOYOTA    W  WZ1      NaN
921379  TOYOTA    W  WZ1      NaN

[271 rows x 4 columns]

In [193]:
print(data_pos0_W['origin'].unique())

['AUSTRIA' 'GERMANY' 'JAPAN' 'POLAND' 'SPAIN' nan 'AUSTRALIA'
 'UNITED KINGDOM' 'THAILAND' 'HUNGARY' 'PORTUGAL' 'CHINA']

In [194]:
data_pos0_Z = data[data['pos0'] == 'Z']
data_pos0_Z[['make','pos0', 'WMI','origin']]

          make pos0  WMI    origin
1492    TOYOTA    Z  ZE1     JAPAN
2269    TOYOTA    Z  ZSG     JAPAN
10881   TOYOTA    Z  ZGE     JAPAN
11133   TOYOTA    Z  ZE1     JAPAN
14652   TOYOTA    Z  ZE1     JAPAN
...        ...  ...  ...       ...
228289  TOYOTA    Z  ZZE       NaN
232256  TOYOTA    Z  ZZE       NaN
234403  TOYOTA    Z  ZE1       NaN
238233  TOYOTA    Z  ZFC  THAILAND
239884  TOYOTA    Z  ZE1       NaN

[99 rows x 4 columns]

In [195]:
print(data_pos0_Z['origin'].unique())

['JAPAN' 'ITALY' nan 'THE THAILAND' 'TURKEY' 'CHINA' 'CANADA' 'THAILAND']

In [196]:
data_pos0_S = data[data['pos0'] == 'S']
data_pos0_S[['make','pos0', 'WMI','origin']]

          make pos0  WMI          origin
2231    TOYOTA    S  STB         AMERICA
3299    TOYOTA    S  STF           JAPAN
3646    TOYOTA    S  SJK  UNITED KINGDOM
7636    TOYOTA    S  SYF   UNITED STATES
9917    TOYOTA    S  STF           JAPAN
...        ...  ...  ...             ...
236225  TOYOTA    S  STB         AMERICA
237637  TOYOTA    S  SKF  UNITED KINGDOM
238063  TOYOTA    S  STF   UNITED STATES
238671  TOYOTA    S  STF           JAPAN
241456  TOYOTA    S  STF           JAPAN

[123 rows x 4 columns]

In [197]:
print(data_pos0_S['origin'].unique())

['AMERICA' 'JAPAN' 'UNITED KINGDOM' 'UNITED STATES' 'UAE' 'GREAT BRITAIN'
 nan 'MEXICO' 'THAILAND' 'AMERICAN' 'AUSTRALIA']

In [198]:
data_pos0_Y = data[data['pos0'] == 'Y']
data_pos0_Y[['make','pos0', 'WMI','origin']]

          make pos0  WMI   origin
4945    TOYOTA    Y  YV2    JAPAN
11557   TOYOTA    Y  YV2   SWEDEN
11698   TOYOTA    Y  YV2    JAPAN
13534   TOYOTA    Y  YS2    JAPAN
18167   TOYOTA    Y  YV2    JAPAN
18319   TOYOTA    Y  YV2   SWEDEN
18376   TOYOTA    Y  YV2    JAPAN
18389   TOYOTA    Y  YV2    JAPAN
19006   TOYOTA    Y  YV2   SWEDEN
23311   TOYOTA    Y  YV2    JAPAN
27688   TOYOTA    Y  YV2    JAPAN
28833   TOYOTA    Y  YV2    JAPAN
31865   TOYOTA    Y  YV2    JAPAN
37605   TOYOTA    Y  YV2  AMERICA
37758   TOYOTA    Y  YV2    JAPAN
42401   TOYOTA    Y  YV2    JAPAN
50464   TOYOTA    Y  YV2      NaN
63530   TOYOTA    Y  YS2      NaN
79159   TOYOTA    Y  YV1   SWEDEN
111591  TOYOTA    Y  YN8      NaN
124736  TOYOTA    Y  YV2      NaN
124759  TOYOTA    Y  YAR   FRANCE
129628  TOYOTA    Y  YV2      NaN
132195  TOYOTA    Y  YV2   SWEDEN
143175  TOYOTA    Y  YV2      NaN
157480  TOYOTA    Y  YV2   SWEDEN
157788  TOYOTA    Y  YV2      NaN
167337  TOYOTA    Y  YV2      NaN
175270  TOYOTA    Y  YV2   SWEDEN
182035  TOYOTA    Y  YBL      NaN
182047  TOYOTA    Y  YV2   SWEDEN
186983  TOYOTA    Y  YN8    JAPAN
189346  TOYOTA    Y  YV2   SWEDEN
195340  TOYOTA    Y  YV2   SWEDEN
196137  TOYOTA    Y  YSM    CHINA
205707  TOYOTA    Y  YV2   SWEDEN
211362  TOYOTA    Y  YS2      NaN
220476  TOYOTA    Y  YV2      NaN
223178  TOYOTA    Y  YV2      NaN
232119  TOYOTA    Y  YV2      NaN
232964  TOYOTA    Y  YV2   SWEDEN
233035  TOYOTA    Y  YV2   SWEDEN
233511  TOYOTA    Y  YV2   SWEDEN
234943  TOYOTA    Y  YV2      NaN
235710  TOYOTA    Y  YV2      NaN
239332  TOYOTA    Y  YV2      NaN
239461  TOYOTA    Y  YV2      NaN
239603  TOYOTA    Y  YV2      NaN
240643  TOYOTA    Y  YV2   SWEDEN

In [199]:
print(data_pos0_Y['origin'].unique())

['JAPAN' 'SWEDEN' 'AMERICA' nan 'FRANCE' 'CHINA']

In [200]:
data_pos0_L = data[data['pos0'] == 'L']
data_pos0_L[['make','pos0', 'WMI','origin']]

          make pos0  WMI origin
241     TOYOTA    L  LVG  CHINA
573     TOYOTA    L  LVG  CHINA
589     TOYOTA    L  LFM  JAPAN
1034    TOYOTA    L  LFM  CHINA
1277    TOYOTA    L  LFM  CHINA
...        ...  ...  ...    ...
920294  TOYOTA    L  LFM    NaN
920401  TOYOTA    L  LVG    NaN
920948  TOYOTA    L  LVG    NaN
921427  TOYOTA    L  LVG    NaN
922291  TOYOTA    L  LFM    NaN

[744 rows x 4 columns]

In [201]:
data_pos0_L[['make','pos0', 'WMI','origin']]

          make pos0  WMI origin
241     TOYOTA    L  LVG  CHINA
573     TOYOTA    L  LVG  CHINA
589     TOYOTA    L  LFM  JAPAN
1034    TOYOTA    L  LFM  CHINA
1277    TOYOTA    L  LFM  CHINA
...        ...  ...  ...    ...
920294  TOYOTA    L  LFM    NaN
920401  TOYOTA    L  LVG    NaN
920948  TOYOTA    L  LVG    NaN
921427  TOYOTA    L  LVG    NaN
922291  TOYOTA    L  LFM    NaN

[744 rows x 4 columns]

In [202]:
data_pos0_M = data[data['pos0'] == 'M']
data_pos0_M[['make','pos0', 'WMI','origin']]

          make pos0  WMI    origin
7       TOYOTA    M  MR0  THAILAND
11      TOYOTA    M  MR2  THAILAND
15      TOYOTA    M  MR0  THAILAND
18      TOYOTA    M  MR0  THAILAND
28      TOYOTA    M  MHF     JAPAN
...        ...  ...  ...       ...
922307  TOYOTA    M  MR0       NaN
922328  TOYOTA    M  MR2       NaN
922348  TOYOTA    M  MHK       NaN
922350  TOYOTA    M  MR0       NaN
922354  TOYOTA    M  MHF       NaN

[37745 rows x 4 columns]

In [203]:
print(data_pos0_M['origin'].unique())

['THAILAND' 'JAPAN' 'INDONESIA' 'INDIA' 'TAIWAN' 'TAHITIAN' nan 'ANDORRA'
 'تايلاند' 'JINDONESIA' 'EMIRATES' 'UAE' 'تايلند' 'CHINA' 'UNKNOWN'
 'AFGHANISTAN' 'UNITED STATES' 'SOUTH KOREA' 'GCC' 'ANGUILLA' 'AMERICA'
 'PAKISTAN' 'AUSTRALIA' 'LIGHT VEHICLE' 'HAILAND' 'IRAN' 'OTHERS'
 'UNITED ARAB EMIRATES' '1' 'PHILIPPINES' 'GERMANY' 'SAUDI ARABIA'
 'BANGLADESH' '0' 'THALLAND' 'LIBYA' 'ANTIGUA AND BARBUDA'
 'FRANCE (EUROPEAN PROVINCE)' 'CAMBODIA' 'FIJI' 'EGYPT' 'تایلاند' 'ASIAN'
 'TURKEY' 'FINDONESIA' 'TAILAND' 'MALAYSIA']

In [204]:
data_pos0_V = data[data['pos0'] == 'V']
data_pos0_V[['make','pos0', 'WMI','origin']]

          make pos0  WMI   origin
2842    TOYOTA    V  VNK    JAPAN
5204    TOYOTA    V  VNK   FRANCE
5312    TOYOTA    V  VNK  AMERICA
5776    TOYOTA    V  VNK   FRANCE
8315    TOYOTA    V  VNK   FRANCE
...        ...  ...  ...      ...
917346  TOYOTA    V  VNK      NaN
917755  TOYOTA    V  VNK      NaN
920833  TOYOTA    V  VNK      NaN
921310  TOYOTA    V  VNK      NaN
922339  TOYOTA    V  VNK      NaN

[119 rows x 4 columns]

In [205]:
print(data_pos0_V['origin'].unique())

['JAPAN' 'FRANCE' 'AMERICA' 'UNITED STATES' 'SPAIN' nan 'INDIA']

In [206]:
data_pos0_T = data[data['pos0'] == 'T']
data_pos0_T[['make','pos0', 'WMI','origin']]

         make pos0  WMI         origin
23095  TOYOTA    T  TNX  UNITED STATES

In [207]:
print(data_pos0_T['origin'].unique())

['UNITED STATES']

In [208]:
data_pos0_R = data[data['pos0'] == 'R']
data_pos0_R[['make','pos0', 'WMI','origin']]

          make pos0  WMI  origin
0       TOYOTA    R  RKL  TAIWAN
17      TOYOTA    R  RKL  TAIWAN
52      TOYOTA    R  RKL   JAPAN
94      TOYOTA    R  RKL   JAPAN
103     TOYOTA    R  RKL  TAIWAN
...        ...  ...  ...     ...
922275  TOYOTA    R  RKL     NaN
922285  TOYOTA    R  RKL     NaN
922332  TOYOTA    R  RKL     NaN
922333  TOYOTA    R  RKL     NaN
922344  TOYOTA    R  RKL     NaN

[17103 rows x 4 columns]

In [209]:
print(data_pos0_R['origin'].unique())

['TAIWAN' 'JAPAN' 'UAE' 'THAILAND' nan 'UNITED ARAB EMIRATES' 'TALWAN'
 'GCC' 'TAIWAN (CHINESE TAIPEI FOR IOC)' 'JAPAN ' 'PAKISTAN' 'NAYON'
 'TABUN' 'AMERICA' 'LIGHT VEHICLE' 'EGYPT' 'UNKNOWN' 'DUBAI' 'INDIA'
 'BAIWAN' 'TAIWAN (CHINESE TAIPEI)' 'LIWAN' 'TAIWAN (PROVINCE OF CHINA)'
 'HUNGARY' 'TUVALU' 'INDONESIA' 'IRAN' 'TANZANIA' 'ASIAN' 'CHINA' 'MACAU'
 'LEBANON' 'JAPANE' 'RUSSIA' 'EMIRATES' 'SOUTH KOREA' 'SPAIN' 'TAI'
 'TAIMAN' 'AUSTRALIA' 'UNITED STATES' 'ETHIOPIA' 'TAINAN' 'JORDAN'
 'TURKEY' 'HINA' 'تايون' 'TNIYON' 'GERMANY' 'NORWAY']

In [210]:
data_pos0_9 = data[data['pos0'] == '9']
data_pos0_9[['make','pos0', 'WMI','origin']]

         make pos0  WMI     origin
24622  TOYOTA    9  9BS      JAPAN
31894  TOYOTA    9  9BS      JAPAN
92809  TOYOTA    9  9KM  AUSTRALIA

In [211]:
print(data_pos0_9['origin'].unique())

['JAPAN' 'AUSTRALIA']

In [212]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos2,VDS,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,L,BB9HE,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,F,HXDGP,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,1,BG22K,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,0,HU8CD,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,M,ABBBJ,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,M,HX01J,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,E,AACAJ,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,F,B29F3,B,2,9,F,3,M,2,123579

In [213]:
origin_mapping = {
    "1": "USA",
    "4": "USA",
    "5": "USA",
    "2": "CANADA",
    "3": "MEXICO",
    "J": "JAPAN",
    "K": "SOUTH KOREA",
    "W": "GERMANY",
    "Z": "ITALY",
    "S": "UNITED KINGDOM",
    "Y": "SWEDEN / FINLAND",
    "L": "CHINA",
    "M": "INDIA",
    "V": "FRANCE / SPAIN",
    "T": "SWITZERLAND",
    "R": "TAIWAN",
    "9": "BRAZIL"
}

In [214]:
data["origin"] = data["pos0"].map(origin_mapping).fillna(data["origin"])

C:\Users\Admin\AppData\Local\Temp\ipykernel_1240\1604850742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["origin"] = data["pos0"].map(origin_mapping).fillna(data["origin"])

In [215]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos2,VDS,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,L,BB9HE,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,F,HX02P,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,F,HXDGP,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,USA,...,1,BG22K,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,INDIA,...,0,HU8CD,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,JAPAN,...,M,ABBBJ,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,JAPAN,...,M,HX01J,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,JAPAN,...,E,AACAJ,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,INDIA,...,F,B29F3,B,2,9,F,3,M,2,123579

In [216]:
data_pos0_V_updated = data[data['pos0'] == 'V']
data_pos0_V_updated[['make','pos0', 'WMI','origin']]

          make pos0  WMI          origin
2842    TOYOTA    V  VNK  FRANCE / SPAIN
5204    TOYOTA    V  VNK  FRANCE / SPAIN
5312    TOYOTA    V  VNK  FRANCE / SPAIN
5776    TOYOTA    V  VNK  FRANCE / SPAIN
8315    TOYOTA    V  VNK  FRANCE / SPAIN
...        ...  ...  ...             ...
917346  TOYOTA    V  VNK  FRANCE / SPAIN
917755  TOYOTA    V  VNK  FRANCE / SPAIN
920833  TOYOTA    V  VNK  FRANCE / SPAIN
921310  TOYOTA    V  VNK  FRANCE / SPAIN
922339  TOYOTA    V  VNK  FRANCE / SPAIN

[119 rows x 4 columns]

In [217]:
data[['make','pos1', 'WMI','origin']]

          make pos1  WMI  origin
0       TOYOTA    K  RKL  TAIWAN
1       TOYOTA    T  JTF   JAPAN
2       TOYOTA    T  JTF   JAPAN
3       TOYOTA    T  JTF   JAPAN
4       TOYOTA    T  4T1     USA
...        ...  ...  ...     ...
922350  TOYOTA    R  MR0   INDIA
922351  TOYOTA    T  JTM   JAPAN
922352  TOYOTA    T  JTM   JAPAN
922353  TOYOTA    T  JTE   JAPAN
922354  TOYOTA    H  MHF   INDIA

[239214 rows x 4 columns]

In [218]:
print(data['pos2'].unique())

['L' 'F' '1' 'M' 'D' '0' 'E' '2' 'N' 'C' 'G' 'A' 'K' 'O' 'X' '3' 'T' 'B'
 '4' 'U' 'J' 'Y' 'W' '6' 'P' '5' '7' '8' 'V' '9' 'I' 'Q' 'H' 'S' 'R' 'Z']

In [219]:
data[['make','pos2', 'WMI','bodyType']]

          make pos2  WMI            bodyType
0       TOYOTA    L  RKL               SEDAN
1       TOYOTA    F  JTF  MINI BUS HIGH ROOF
2       TOYOTA    F  JTF  MINI BUS HIGH ROOF
3       TOYOTA    F  JTF  PICK UP DOUBLE CAB
4       TOYOTA    1  4T1               SEDAN
...        ...  ...  ...                 ...
922350  TOYOTA    0  MR0              PICKUP
922351  TOYOTA    M  JTM                 SUV
922352  TOYOTA    M  JTM                 SUV
922353  TOYOTA    E  JTE                 SUV
922354  TOYOTA    F  MHF               SEDAN

[239214 rows x 4 columns]

In [220]:
print(data['bodyType'].unique())

['SEDAN' 'MINI BUS HIGH ROOF' 'PICK UP DOUBLE CAB' 'SUV' 'HATCHBACK'
 'PICK UP SINGLE CAB' 'PANEL VAN' 'BUS' 'MPV' 'ESTATE' 'PICK UP' 'VAN'
 'MINI BUS' 'COUPE' 'SUV- CROSSOVER' 'PICKUP' 'SALOON'
 'PANEL VAN HIGH ROOF' 'STATION' 'HALF PANEL VAN' 'CONVERTIBLE'
 'CARGO VAN' 'MINIVAN' 'MINI BUS SEMI HIGH ROOF' 'CARAVAN' 'PICKUP TRUCK'
 'LIGHT VEHICLE' 'MOTORCYCLE' 'PICKUP SINGLE CABIN' 'TRUCK'
 'PICK UP DOUBLE CABIN' 'PICKUP DOUBLE CABIN' 'COUPE/CABRIOLET'
 'AMBULANCE' 'REGULAR CAB' 'PICKUP DOUBLE CAB' 'WINDOW VAN' 'WAGON'
 'PICK-UP']

In [221]:
from IPython.display import display

for body_type in data['bodyType'].dropna().unique():

    filtered_df = data.loc[
        data['bodyType'] == body_type,
        ['make', 'pos4', 'WMI', 'bodyType', 'VDS']
    ].reset_index(drop=True)

    print("\n" + "=" * 100)
    print(f"BODY TYPE: {body_type}")
    print("=" * 100)

    print("Unique POS4 Values:")
    print(filtered_df['pos4'].dropna().unique())

    display(filtered_df)

====================================================================================================
BODY TYPE: SEDAN
====================================================================================================
Unique POS4 Values:
['B' 'K' 'E' '5' 'A' 'J' 'G' 'C' 'D' '1' '8' 'S' 'H' '7' 'L' 'M' 'P' 'F'
 '6' 'T' '4' '2' 'Z' 'U' '3' 'V' 'R' 'W' '0' 'Y' '9' 'N']

          make pos4  WMI bodyType    VDS
0       TOYOTA    B  RKL    SEDAN  BB9HE
1       TOYOTA    B  4T1    SEDAN  BG22K
2       TOYOTA    B  JTD    SEDAN  BR23E
3       TOYOTA    B  MR2    SEDAN  BF9C3
4       TOYOTA    B  6T1    SEDAN  BF9FK
...        ...  ...  ...      ...    ...
108265  TOYOTA    B  JTN    SEDAN  BZ4HK
108266  TOYOTA    B  JTN    SEDAN  BZ4HK
108267  TOYOTA    B  6T1    SEDAN  BF9FK
108268  TOYOTA    B  6T1    SEDAN  BE32K
108269  TOYOTA    B  MHF    SEDAN  B29F3

[108270 rows x 5 columns]

====================================================================================================
BODY TYPE: MINI BUS HIGH ROOF
====================================================================================================
Unique POS4 Values:
['H' 'P' 'L' 'S' 'J' 'R' 'B' 'Z' 'D' '6' 'C' 'G' 'K' 'E' '5' 'F']

        make pos4  WMI            bodyType    VDS
0     TOYOTA    H  JTF  MINI BUS HIGH ROOF  HX02P
1     TOYOTA    H  JTF  MINI BUS HIGH ROOF  HX02P
2     TOYOTA    P  JTF  MINI BUS HIGH ROOF  PX22P
3     TOYOTA    P  JTF  MINI BUS HIGH ROOF  PX22P
4     TOYOTA    H  JTF  MINI BUS HIGH ROOF  HX02P
...      ...  ...  ...                 ...    ...
1402  TOYOTA    H  JTG  MINI BUS HIGH ROOF  HN9CP
1403  TOYOTA    H  JTF  MINI BUS HIGH ROOF  HX02P
1404  TOYOTA    S  JTG  MINI BUS HIGH ROOF  SX22P
1405  TOYOTA    S  JTG  MINI BUS HIGH ROOF  SX22P
1406  TOYOTA    P  JTF  MINI BUS HIGH ROOF  PX22P

[1407 rows x 5 columns]

====================================================================================================
BODY TYPE: PICK UP DOUBLE CAB
====================================================================================================
Unique POS4 Values:
['H' 'B' 'C' 'M' 'W' 'L' 'D' 'F' 'K' 'E' 'A' 'U' '3' 'J' 'N' 'G' 'P' 'V'
 'R' '1' 'Z' 'S' '0' 'T' 'X' 'Y' '8' '2' '6' '4' '7' '5' '9']

         make pos4  WMI            bodyType    VDS
0      TOYOTA    H  JTF  PICK UP DOUBLE CAB  HXDGP
1      TOYOTA    B  MR0  PICK UP DOUBLE CAB  BX8CD
2      TOYOTA    C  MR0  PICK UP DOUBLE CAB  CW6CB
3      TOYOTA    M  5TF  PICK UP DOUBLE CAB  MV521
4      TOYOTA    C  MR0  PICK UP DOUBLE CAB  CX9CB
...       ...  ...  ...                 ...    ...
13230  TOYOTA    V  5TF  PICK UP DOUBLE CAB  VC5DB
13231  TOYOTA    B  5TF  PICK UP DOUBLE CAB  BY5F1
13232  TOYOTA    H  MR0  PICK UP DOUBLE CAB  HX8CD
13233  TOYOTA    B  5TB  PICK UP DOUBLE CAB  BV541
13234  TOYOTA    A  5TF  PICK UP DOUBLE CAB  AW5F1

[13235 rows x 5 columns]

====================================================================================================
BODY TYPE: SUV
====================================================================================================
Unique POS4 Values:
['H' 'B' 'Y' 'D' 'A' 'R' 'J' 'E' 'W' 'Z' 'K' 'L' 'C' '7' '1' 'G' 'F' '5'
 '8' 'M' 'X' 'P' 'N' '2' '6' 'V' 'T' 'U' 'I' 'S' '3' '4' '0']

         make pos4  WMI bodyType    VDS
0      TOYOTA    H  JTM      SUV  HT09J
1      TOYOTA    B  JTE      SUV  BU11F
2      TOYOTA    H  JTE      SUV  HD20V
3      TOYOTA    B  JTE      SUV  BU11F
4      TOYOTA    B  JTE      SUV  BU11F
...       ...  ...  ...      ...    ...
67103  TOYOTA    H  JTM      SUV  HT09J
67104  TOYOTA    M  MHK      SUV  MF5CF
67105  TOYOTA    A  JTM      SUV  ABBBJ
67106  TOYOTA    H  JTM      SUV  HX01J
67107  TOYOTA    A  JTE      SUV  AACAJ

[67108 rows x 5 columns]

====================================================================================================
BODY TYPE: HATCHBACK
====================================================================================================
Unique POS4 Values:
['B' 'K' 'J' 'D' 'Z' '5' '0' 'A' 'R' 'L' 'E' '8' '2' '1' 'F' '9' 'C' 'P'
 'W']

         make pos4  WMI   bodyType    VDS
0      TOYOTA    B  JTD  HATCHBACK  BW923
1      TOYOTA    B  MHF  HATCHBACK  B29F3
2      TOYOTA    K  JTD  HATCHBACK  KW923
3      TOYOTA    B  JTD  HATCHBACK  BW923
4      TOYOTA    K  JTD  HATCHBACK  KB3FU
...       ...  ...  ...        ...    ...
13540  TOYOTA    K  MR2  HATCHBACK  KT9F3
13541  TOYOTA    K  JTD  HATCHBACK  KW9D3
13542  TOYOTA    K  JTD  HATCHBACK  KW9D3
13543  TOYOTA    K  MR2  HATCHBACK  K19F3
13544  TOYOTA    K  VNK  HATCHBACK  KTUD3

[13545 rows x 5 columns]

====================================================================================================
BODY TYPE: PICK UP SINGLE CAB
====================================================================================================
Unique POS4 Values:
['E' 'K' 'J' 'D' 'B' '6' 'H' 'F' 'C' 'L' '3' 'A' 'N' 'U' 'W' 'S' '0' 'R'
 'T' '8' 'P' 'Z' 'V' 'Y' '7' 'G' '1' '2' '9']

        make pos4  WMI            bodyType    VDS
0     TOYOTA    E  MR0  PICK UP SINGLE CAB  EW12G
1     TOYOTA    K  MR0  PICK UP SINGLE CAB  KB8CD
2     TOYOTA    J  MR0  PICK UP SINGLE CAB  JX9CD
3     TOYOTA    K  MR0  PICK UP SINGLE CAB  KB8CD
4     TOYOTA    D  MR0  PICK UP SINGLE CAB  DX22G
...      ...  ...  ...                 ...    ...
7992  TOYOTA    F  MR0  PICK UP SINGLE CAB  FX22G
7993  TOYOTA    A  MR0  PICK UP SINGLE CAB  AW12G
7994  TOYOTA    L  JTF  PICK UP SINGLE CAB  LJ73J
7995  TOYOTA    F  MR0  PICK UP SINGLE CAB  FX22G
7996  TOYOTA    E  MR0  PICK UP SINGLE CAB  EX12G

[7997 rows x 5 columns]

====================================================================================================
BODY TYPE: PANEL VAN
====================================================================================================
Unique POS4 Values:
['P' 'J' 'H' 'Z' 'R' 'B' 'T' 'L' 'N' 'F' '2' 'S' 'C' '4' 'I' 'U' 'A' 'W'
 'K' '7' 'E' 'X' 'M' '6' 'D' 'G' '8' '1' '9' 'V']

        make pos4  WMI   bodyType    VDS
0     TOYOTA    P  JTF  PANEL VAN  PX22P
1     TOYOTA    P  JTF  PANEL VAN  PX22P
2     TOYOTA    J  JTG  PANEL VAN  JX02P
3     TOYOTA    H  JTF  PANEL VAN  HX02P
4     TOYOTA    J  JTG  PANEL VAN  JX02P
...      ...  ...  ...        ...    ...
4024  TOYOTA    H  JTF  PANEL VAN  HX02P
4025  TOYOTA    J  JTG  PANEL VAN  JX02P
4026  TOYOTA    H  JTF  PANEL VAN  HX02P
4027  TOYOTA    P  JTF  PANEL VAN  PX22P
4028  TOYOTA    H  JTG  PANEL VAN  HN9CP

[4029 rows x 5 columns]

====================================================================================================
BODY TYPE: BUS
====================================================================================================
Unique POS4 Values:
['F' 'S' 'H' '4' 'L' 'C' 'P' 'B' 'J' 'R' 'A' '5' 'D' '1' 'U' '7']

       make pos4  WMI bodyType    VDS
0    TOYOTA    F  JTC      BUS  FZ418
1    TOYOTA    F  JTG      BUS  FK418
2    TOYOTA    F  JTG      BUS  FK718
3    TOYOTA    S  JTG      BUS  SX23P
4    TOYOTA    F  JTG      BUS  FK518
..      ...  ...  ...      ...    ...
576  TOYOTA    F  JTG      BUS  FK518
577  TOYOTA    F  JTG      BUS  FK518
578  TOYOTA    F  JTG      BUS  FB518
579  TOYOTA    F  JTG      BUS  FK518
580  TOYOTA    H  KMJ      BUS  HG17C

[581 rows x 5 columns]

====================================================================================================
BODY TYPE: MPV
====================================================================================================
Unique POS4 Values:
['X' 'K' 'Z' 'M' 'Y' 'G' 'H' 'B' 'C' 'A' 'J' 'D' '2' '0' 'F' '6' 'R' 'N'
 'L' '5' 'S' 'P' '1' 'W' '8' 'V' 'E' '4']

         make pos4  WMI bodyType    VDS
0      TOYOTA    X  MHF      MPV  XX43G
1      TOYOTA    K  5TD      MPV  KK3DC
2      TOYOTA    X  MHF      MPV  XX43G
3      TOYOTA    Z  5TD      MPV  ZK22C
4      TOYOTA    Z  5TD      MPV  ZA23C
...       ...  ...  ...      ...    ...
12895  TOYOTA    X  MHF      MPV  XX43G
12896  TOYOTA    X  MHF      MPV  XX43G
12897  TOYOTA    X  MHF      MPV  XX43G
12898  TOYOTA    K  5TD      MPV  KK3DC
12899  TOYOTA    Z  5TD      MPV  ZK23C

[12900 rows x 5 columns]

====================================================================================================
BODY TYPE: ESTATE
====================================================================================================
Unique POS4 Values:
['B' 'E']

      make pos4  WMI bodyType    VDS
0   TOYOTA    B  JTD   ESTATE  BW23E
1   TOYOTA    E  JTD   ESTATE  EW23E
2   TOYOTA    B  JTD   ESTATE  BW23E
3   TOYOTA    B  JTD   ESTATE  BR23E
4   TOYOTA    B  JTD   ESTATE  BR23E
5   TOYOTA    B  JTD   ESTATE  BR22E
6   TOYOTA    B  JTD   ESTATE  BW23E
7   TOYOTA    B  JTD   ESTATE  BW23E
8   TOYOTA    B  JTD   ESTATE  BW23E
9   TOYOTA    B  2T1   ESTATE  BR38E
10  TOYOTA    B  2T1   ESTATE  BR32E
11  TOYOTA    E  JTD   ESTATE  ER22E
12  TOYOTA    B  JTD   ESTATE  BR32E
13  TOYOTA    B  2T1   ESTATE  BR38E
14  TOYOTA    B  JTD   ESTATE  BR23E
15  TOYOTA    E  JTD   ESTATE  EW23E
16  TOYOTA    E  JTD   ESTATE  EW23E
17  TOYOTA    B  JTD   ESTATE  BR32E
18  TOYOTA    B  JTD   ESTATE  BR23E

====================================================================================================
BODY TYPE: PICK UP
====================================================================================================
Unique POS4 Values:
['L' 'F' 'D' 'P' 'E' 'A' 'U' 'N' 'C' 'W' 'B' 'T' 'S' 'V' 'M' 'H' '3' 'K'
 'J' '9']

       make pos4  WMI bodyType    VDS
0    TOYOTA    L  JTF  PICK UP  LJ73J
1    TOYOTA    F  MR0  PICK UP  FX22G
2    TOYOTA    D  MRO  PICK UP  DX22G
3    TOYOTA    D  MR0  PICK UP  DX22G
4    TOYOTA    L  JTF  PICK UP  LU73J
..      ...  ...  ...      ...    ...
977  TOYOTA    L  JTF  PICK UP  LJ73J
978  TOYOTA    M  5TF  PICK UP  MU4FN
979  TOYOTA    L  JTF  PICK UP  LJ73J
980  TOYOTA    L  JTF  PICK UP  LU73J
981  TOYOTA    L  JTF  PICK UP  LU73J

[982 rows x 5 columns]

====================================================================================================
BODY TYPE: VAN
====================================================================================================
Unique POS4 Values:
['H' 'P' 'L' 'B' 'J' 'R' 'A' 'S' 'K' 'Z' 'E' '2' 'Y' 'M' 'U']

       make pos4  WMI bodyType    VDS
0    TOYOTA    H  JTF      VAN  HX02P
1    TOYOTA    P  JTF      VAN  PX22P
2    TOYOTA    P  JTF      VAN  PX22P
3    TOYOTA    H  JTF      VAN  HX02P
4    TOYOTA    P  JTF      VAN  PX22P
..      ...  ...  ...      ...    ...
337  TOYOTA    Z  5TD      VAN  ZK23C
338  TOYOTA    H  JTF      VAN  HX02P
339  TOYOTA    P  JTF      VAN  PX22P
340  TOYOTA    P  JTF      VAN  PX22P
341  TOYOTA    B  MHK      VAN  BF31F

[342 rows x 5 columns]

====================================================================================================
BODY TYPE: MINI BUS
====================================================================================================
Unique POS4 Values:
['J' 'H' 'S' 'P' 'R' 'A' 'D' 'B' 'F' '0' 'T' 'G' 'K' '5' '3' 'L' '4' 'X'
 'W' '6' '1' 'M' 'Z']

        make pos4  WMI  bodyType    VDS
0     TOYOTA    J  JTG  MINI BUS  JX02P
1     TOYOTA    H  JTF  MINI BUS  HX02P
2     TOYOTA    H  JTF  MINI BUS  HX02P
3     TOYOTA    S  JTG  MINI BUS  SX22P
4     TOYOTA    P  JTF  MINI BUS  PX22P
...      ...  ...  ...       ...    ...
4970  TOYOTA    J  JTG  MINI BUS  JX02P
4971  TOYOTA    J  JTG  MINI BUS  JX02P
4972  TOYOTA    J  JTG  MINI BUS  JX02P
4973  TOYOTA    J  JTG  MINI BUS  JX02P
4974  TOYOTA    J  JTG  MINI BUS  JX02P

[4975 rows x 5 columns]

====================================================================================================
BODY TYPE: COUPE
====================================================================================================
Unique POS4 Values:
['D' 'Z' 'J' '8' 'M' 'C' 'F' '9' 'S' '6' 'E' 'B' 'A' '7' 'W']

       make pos4  WMI bodyType    VDS
0    TOYOTA    D  WZ1    COUPE  DB0E0
1    TOYOTA    Z  JF1    COUPE  ZN11B
2    TOYOTA    Z  JF1    COUPE  ZN12B
3    TOYOTA    D  JT2    COUPE  DP02T
4    TOYOTA    Z  JF1    COUPE  ZN11B
..      ...  ...  ...      ...    ...
641  TOYOTA    J  JTK    COUPE  JF5C7
642  TOYOTA    D  JTD    COUPE  DR32T
643  TOYOTA    Z  JF1    COUPE  ZN11A
644  TOYOTA    Z  JF1    COUPE  ZN12B
645  TOYOTA    Z  JF1    COUPE  ZN12A

[646 rows x 5 columns]

====================================================================================================
BODY TYPE: SUV- CROSSOVER
====================================================================================================
Unique POS4 Values:
['K' 'C' 'D' 'A' 'E' 'F' 'B' 'J']

       make pos4  WMI        bodyType    VDS
0    TOYOTA    K  RKL  SUV- CROSSOVER  KAAAG
1    TOYOTA    K  RKL  SUV- CROSSOVER  KAAAG
2    TOYOTA    K  RKL  SUV- CROSSOVER  KUAAG
3    TOYOTA    K  RKL  SUV- CROSSOVER  KAAAG
4    TOYOTA    K  RKL  SUV- CROSSOVER  KABAG
..      ...  ...  ...             ...    ...
807  TOYOTA    K  RKL  SUV- CROSSOVER  KAAAG
808  TOYOTA    K  RKL  SUV- CROSSOVER  KUBAG
809  TOYOTA    K  RKL  SUV- CROSSOVER  KAAAG
810  TOYOTA    K  RKL  SUV- CROSSOVER  KUBAG
811  TOYOTA    K  RKL  SUV- CROSSOVER  KAAAG

[812 rows x 5 columns]

====================================================================================================
BODY TYPE: PICKUP
====================================================================================================
Unique POS4 Values:
['U' 'B' 'L' 'A' 'F' 'K' 'D' 'T' 'P' 'E' 'R' 'N' 'C' 'M' 'V' '3' 'J' 'H'
 '8' 'W' '1' 'S']

       make pos4  WMI bodyType    VDS
0    TOYOTA    U  5TF   PICKUP  UX4EN
1    TOYOTA    B  JTE   PICKUP  BB71J
2    TOYOTA    L  JTF   PICKUP  LJ73J
3    TOYOTA    L  JTF   PICKUP  LJ73J
4    TOYOTA    L  JTF   PICKUP  LU73J
..      ...  ...  ...      ...    ...
900  TOYOTA    F  MR0   PICKUP  FX22G
901  TOYOTA    D  5TF   PICKUP  DW5F1
902  TOYOTA    E  JTF   PICKUP  EM426
903  TOYOTA    E  MR0   PICKUP  EX12G
904  TOYOTA    H  MR0   PICKUP  HU8CD

[905 rows x 5 columns]

====================================================================================================
BODY TYPE: SALOON
====================================================================================================
Unique POS4 Values:
['E' 'B' '8' 'K' 'A' 'C' '5' 'H' 'R' 'T']

       make pos4  WMI bodyType    VDS
0    TOYOTA    E  JTD   SALOON  ER23E
1    TOYOTA    B  JTN   SALOON  BF4HK
2    TOYOTA    B  RKL   SALOON  BV42E
3    TOYOTA    B  JTN   SALOON  BZ4HK
4    TOYOTA    B  1NX   SALOON  BR38E
..      ...  ...  ...      ...    ...
109  TOYOTA    E  JTD   SALOON  ER23E
110  TOYOTA    B  JTD   SALOON  BR32E
111  TOYOTA    B  1NX   SALOON  BR32E
112  TOYOTA    B  1NX   SALOON  BR32E
113  TOYOTA    K  JTD   SALOON  KARFU

[114 rows x 5 columns]

====================================================================================================
BODY TYPE: PANEL VAN HIGH ROOF
====================================================================================================
Unique POS4 Values:
['H' 'P' 'R' 'L' 'S' '8' '1' 'J' 'A' 'K']

       make pos4  WMI             bodyType    VDS
0    TOYOTA    H  JTF  PANEL VAN HIGH ROOF  HX02P
1    TOYOTA    P  JTF  PANEL VAN HIGH ROOF  PX22P
2    TOYOTA    H  JTG  PANEL VAN HIGH ROOF  HN9CP
3    TOYOTA    P  JTF  PANEL VAN HIGH ROOF  PX22P
4    TOYOTA    R  JTG  PANEL VAN HIGH ROOF  RX12P
..      ...  ...  ...                  ...    ...
334  TOYOTA    P  JTF  PANEL VAN HIGH ROOF  PX22P
335  TOYOTA    P  JTF  PANEL VAN HIGH ROOF  PX22P
336  TOYOTA    P  JTF  PANEL VAN HIGH ROOF  PX22P
337  TOYOTA    L  JTF  PANEL VAN HIGH ROOF  LMFCP
338  TOYOTA    P  JTF  PANEL VAN HIGH ROOF  PX22P

[339 rows x 5 columns]

====================================================================================================
BODY TYPE: STATION
====================================================================================================
Unique POS4 Values:
['B' 'H' 'D' '1' 'A' 'R' 'Z' 'Y' 'K' 'E' 'J' '2' '0' 'X' 'L' '8' 'G' 'M'
 'N' 'F' 'C' '7' '6']

       make pos4  WMI bodyType    VDS
0    TOYOTA    B  JTE  STATION  BU11F
1    TOYOTA    H  JTM  STATION  HY05J
2    TOYOTA    D  LVG  STATION  D156F
3    TOYOTA    1  JTB  STATION  11UJ8
4    TOYOTA    A  MHF  STATION  ABIBY
..      ...  ...  ...      ...    ...
169  TOYOTA    1  JTB  STATION  11VJ9
170  TOYOTA    1  JT8  STATION  11UJ8
171  TOYOTA    H  JT3  STATION  HP10V
172  TOYOTA    1  JTB  STATION  11UJ8
173  TOYOTA    B  JT3  STATION  BM99J

[174 rows x 5 columns]

====================================================================================================
BODY TYPE: HALF PANEL VAN
====================================================================================================
Unique POS4 Values:
['J' 'H' 'S' 'P' 'R' '5' 'W' 'F']

       make pos4  WMI        bodyType    VDS
0    TOYOTA    J  JTG  HALF PANEL VAN  JX02P
1    TOYOTA    J  JTG  HALF PANEL VAN  JX02P
2    TOYOTA    H  JTF  HALF PANEL VAN  HX02P
3    TOYOTA    S  JTG  HALF PANEL VAN  SX22P
4    TOYOTA    J  JTG  HALF PANEL VAN  JX02P
..      ...  ...  ...             ...    ...
680  TOYOTA    J  JTG  HALF PANEL VAN  JX02P
681  TOYOTA    H  JTF  HALF PANEL VAN  HX02P
682  TOYOTA    J  JT6  HALF PANEL VAN  JX02P
683  TOYOTA    J  JTG  HALF PANEL VAN  JX02P
684  TOYOTA    H  JTF  HALF PANEL VAN  HX02P

[685 rows x 5 columns]

====================================================================================================
BODY TYPE: CONVERTIBLE
====================================================================================================
Unique POS4 Values:
['C' 'F' 'X' 'K']

      make pos4  WMI     bodyType    VDS
0   TOYOTA    C  4T1  CONVERTIBLE  CA30P
1   TOYOTA    F  4T1  CONVERTIBLE  FA38P
2   TOYOTA    F  4T1  CONVERTIBLE  FA38P
3   TOYOTA    F  4T1  CONVERTIBLE  FA38P
4   TOYOTA    F  4T1  CONVERTIBLE  FA38P
5   TOYOTA    F  4T1  CONVERTIBLE  FA38P
6   TOYOTA    F  4T1  CONVERTIBLE  FA38P
7   TOYOTA    F  4T1  CONVERTIBLE  FA38P
8   TOYOTA    F  4T1  CONVERTIBLE  FA38P
9   TOYOTA    F  4T1  CONVERTIBLE  FA38P
10  TOYOTA    F  4T1  CONVERTIBLE  FA38P
11  TOYOTA    F  4T1  CONVERTIBLE  FA38P
12  TOYOTA    X  MHF  CONVERTIBLE  XX43G
13  TOYOTA    F  4T1  CONVERTIBLE  FA38P
14  TOYOTA    F  4T1  CONVERTIBLE  FA38P
15  TOYOTA    F  4T1  CONVERTIBLE  FA38P
16  TOYOTA    F  4T1  CONVERTIBLE  FA38P
17  TOYOTA    C  4T1  CONVERTIBLE  CA30P
18  TOYOTA    F  4T1  CONVERTIBLE  FA38P
19  TOYOTA    F  4T1  CONVERTIBLE  FA38P
20  TOYOTA    F  4T1  CONVERTIBLE  FA38P
21  TOYOTA    F  4T1  CONVERTIBLE  FA38P
22  TOYOTA    K  JTD  CONVERTIBLE  KB200
23  TOYOTA    F  2T1  CONVERTIBLE  FF22P

====================================================================================================
BODY TYPE: CARGO VAN
====================================================================================================
Unique POS4 Values:
['L' 'B' 'P' 'H' 'W']

      make pos4  WMI   bodyType    VDS
0   TOYOTA    L  JTF  CARGO VAN  LMFCP
1   TOYOTA    B  MHK  CARGO VAN  BF31F
2   TOYOTA    B  JN6  CARGO VAN  BE6BS
3   TOYOTA    B  MHK  CARGO VAN  BF31F
4   TOYOTA    P  JTF  CARGO VAN  PX22P
5   TOYOTA    B  MHK  CARGO VAN  BF31F
6   TOYOTA    B  MHK  CARGO VAN  BF31F
7   TOYOTA    H  JTF  CARGO VAN  HX02P
8   TOYOTA    B  MHK  CARGO VAN  BF31F
9   TOYOTA    B  MHK  CARGO VAN  BF31F
10  TOYOTA    B  MHK  CARGO VAN  BF31F
11  TOYOTA    B  MHK  CARGO VAN  BF31F
12  TOYOTA    B  MHK  CARGO VAN  BF31F
13  TOYOTA    P  JTF  CARGO VAN  PX22P
14  TOYOTA    B  MHK  CARGO VAN  BF31F
15  TOYOTA    B  MHK  CARGO VAN  BF31F
16  TOYOTA    B  MHK  CARGO VAN  BF31F
17  TOYOTA    B  MHK  CARGO VAN  BF31F
18  TOYOTA    B  MHK  CARGO VAN  BF31F
19  TOYOTA    B  MHK  CARGO VAN  BF31F
20  TOYOTA    B  MHK  CARGO VAN  BF31F
21  TOYOTA    B  MHK  CARGO VAN  BF31F
22  TOYOTA    W  1GC  CARGO VAN  WGAFP
23  TOYOTA    B  MHK  CARGO VAN  BF31F
24  TOYOTA    B  MHK  CARGO VAN  BF31F
25  TOYOTA    B  MHK  CARGO VAN  BF31F
26  TOYOTA    B  MHK  CARGO VAN  BF31F
27  TOYOTA    B  MHK  CARGO VAN  BF31F
28  TOYOTA    B  MHK  CARGO VAN  BF31F
29  TOYOTA    B  MHK  CARGO VAN  BF31F
30  TOYOTA    B  MHK  CARGO VAN  BF31F
31  TOYOTA    B  MHK  CARGO VAN  BF31F
32  TOYOTA    B  MHK  CARGO VAN  BF31F
33  TOYOTA    B  MHK  CARGO VAN  BF31F
34  TOYOTA    B  MHK  CARGO VAN  BF31F
35  TOYOTA    B  MHK  CARGO VAN  BF31F

====================================================================================================
BODY TYPE: MINIVAN
====================================================================================================
Unique POS4 Values:
['H' 'X' 'P']

     make pos4  WMI bodyType    VDS
0  TOYOTA    H  JTF  MINIVAN  HX02P
1  TOYOTA    H  JTF  MINIVAN  HX02P
2  TOYOTA    H  JTF  MINIVAN  HX02P
3  TOYOTA    X  MHF  MINIVAN  XX43G
4  TOYOTA    P  JTF  MINIVAN  PX22P
5  TOYOTA    H  JTF  MINIVAN  HX02P

====================================================================================================
BODY TYPE: MINI BUS SEMI HIGH ROOF
====================================================================================================
Unique POS4 Values:
['R' 'H' 'S' 'J']

      make pos4  WMI                 bodyType    VDS
0   TOYOTA    R  JTG  MINI BUS SEMI HIGH ROOF  RX12P
1   TOYOTA    R  JTG  MINI BUS SEMI HIGH ROOF  RX12P
2   TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
3   TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
4   TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
5   TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
6   TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
7   TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
8   TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
9   TOYOTA    R  JTG  MINI BUS SEMI HIGH ROOF  RX12P
10  TOYOTA    S  JTG  MINI BUS SEMI HIGH ROOF  SX23P
11  TOYOTA    J  JTG  MINI BUS SEMI HIGH ROOF  JX02P
12  TOYOTA    S  JTG  MINI BUS SEMI HIGH ROOF  SX23P
13  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
14  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
15  TOYOTA    R  JTG  MINI BUS SEMI HIGH ROOF  RX12P
16  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
17  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
18  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
19  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
20  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
21  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
22  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
23  TOYOTA    R  JTG  MINI BUS SEMI HIGH ROOF  RX12P
24  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
25  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
26  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
27  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
28  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
29  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
30  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
31  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P
32  TOYOTA    R  JTG  MINI BUS SEMI HIGH ROOF  RX12P
33  TOYOTA    H  JTF  MINI BUS SEMI HIGH ROOF  HX02P

====================================================================================================
BODY TYPE: CARAVAN
====================================================================================================
Unique POS4 Values:
['U' 'V']

     make pos4  WMI bodyType    VDS
0  TOYOTA    U  5TF  CARAVAN  UW5F1
1  TOYOTA    V  JT5  CARAVAN  VN94T

====================================================================================================
BODY TYPE: PICKUP TRUCK
====================================================================================================
Unique POS4 Values:
['H' 'P']

     make pos4  WMI      bodyType    VDS
0  TOYOTA    H  JTF  PICKUP TRUCK  HX02P
1  TOYOTA    P  JTF  PICKUP TRUCK  PX22P

====================================================================================================
BODY TYPE: LIGHT VEHICLE
====================================================================================================
Unique POS4 Values:
['B' 'L' 'D' 'Y' 'H']

     make pos4  WMI       bodyType    VDS
0  TOYOTA    B  JTN  LIGHT VEHICLE  BZ4HK
1  TOYOTA    L  JTF  LIGHT VEHICLE  LU733
2  TOYOTA    D  WZI  LIGHT VEHICLE  DB4A0
3  TOYOTA    Y  JTN  LIGHT VEHICLE  YM3AP
4  TOYOTA    H  JTM  LIGHT VEHICLE  HY05J
5  TOYOTA    B  JTD  LIGHT VEHICLE  BW923

====================================================================================================
BODY TYPE: MOTORCYCLE
====================================================================================================
Unique POS4 Values:
['1' 'P' 'R' 'T' 'M']

     make pos4  WMI    bodyType    VDS
0  TOYOTA    1  5HD  MOTORCYCLE  1KTP4
1  TOYOTA    P  LK1  MOTORCYCLE  PCKL9
2  TOYOTA    R  MH3  MOTORCYCLE  RH21B
3  TOYOTA    T  SMT  MOTORCYCLE  TTL13
4  TOYOTA    M  MET  MOTORCYCLE  M8500
5  TOYOTA    M  MET  MOTORCYCLE  M8500
6  TOYOTA    1  5HD  MOTORCYCLE  1FHPC
7  TOYOTA    M  MET  MOTORCYCLE  M8500
8  TOYOTA    P  LBB  MOTORCYCLE  P9900

====================================================================================================
BODY TYPE: PICKUP SINGLE CABIN
====================================================================================================
Unique POS4 Values:
['C']

     make pos4  WMI             bodyType    VDS
0  TOYOTA    C  MRO  PICKUP SINGLE CABIN  CX9CB

====================================================================================================
BODY TYPE: TRUCK
====================================================================================================
Unique POS4 Values:
['P' 'Y' 'U' 'B']

     make pos4  WMI bodyType    VDS
0  TOYOTA    P  5TE    TRUCK  PM62N
1  TOYOTA    Y  JHG    TRUCK  YJ227
2  TOYOTA    U  JHG    TRUCK  UF117
3  TOYOTA    B  5TB    TRUCK  BT441

====================================================================================================
BODY TYPE: PICK UP DOUBLE CABIN
====================================================================================================
Unique POS4 Values:
['D' 'B' 'L']

     make pos4  WMI              bodyType    VDS
0  TOYOTA    D  JTF  PICK UP DOUBLE CABIN  DZ626
1  TOYOTA    B  5TB  PICK UP DOUBLE CABIN  BT441
2  TOYOTA    L  5TF  PICK UP DOUBLE CABIN  LU4EN
3  TOYOTA    D  MR0  PICK UP DOUBLE CABIN  D89CD

====================================================================================================
BODY TYPE: PICKUP DOUBLE CABIN
====================================================================================================
Unique POS4 Values:
['J' 'B' 'E' 'C' 'R']

     make pos4  WMI             bodyType    VDS
0  TOYOTA    J  5TE  PICKUP DOUBLE CABIN  JU62N
1  TOYOTA    B  5TB  PICKUP DOUBLE CABIN  BN441
2  TOYOTA    E  MRO  PICKUP DOUBLE CABIN  EX19G
3  TOYOTA    C  MRO  PICKUP DOUBLE CABIN  CX9CD
4  TOYOTA    R  MR0  PICKUP DOUBLE CABIN  RX22G

====================================================================================================
BODY TYPE: COUPE/CABRIOLET
====================================================================================================
Unique POS4 Values:
['W']

     make pos4  WMI         bodyType    VDS
0  TOYOTA    W  55S  COUPE/CABRIOLET  WF8HB

====================================================================================================
BODY TYPE: AMBULANCE
====================================================================================================
Unique POS4 Values:
['R']

     make pos4  WMI   bodyType    VDS
0  TOYOTA    R  JTF  AMBULANCE  RV71J
1  TOYOTA    R  JTF  AMBULANCE  RV71J

====================================================================================================
BODY TYPE: REGULAR CAB
====================================================================================================
Unique POS4 Values:
['L']

     make pos4  WMI     bodyType    VDS
0  TOYOTA    L  JAM  REGULAR CAB  LP345

====================================================================================================
BODY TYPE: PICKUP DOUBLE CAB
====================================================================================================
Unique POS4 Values:
['C' 'K' 'B' 'D']

     make pos4  WMI           bodyType    VDS
0  TOYOTA    C  MRO  PICKUP DOUBLE CAB  CX9CD
1  TOYOTA    K  MRO  PICKUP DOUBLE CAB  KB8CD
2  TOYOTA    C  MR0  PICKUP DOUBLE CAB  CX9CD
3  TOYOTA    B  JTF  PICKUP DOUBLE CAB  BU71J
4  TOYOTA    D  MR0  PICKUP DOUBLE CAB  D89CD

====================================================================================================
BODY TYPE: WINDOW VAN
====================================================================================================
Unique POS4 Values:
['W' '7']

     make pos4  WMI    bodyType    VDS
0  TOYOTA    W  KMJ  WINDOW VAN  WA37R
1  TOYOTA    W  KMJ  WINDOW VAN  WA37R
2  TOYOTA    7  VF3  WINDOW VAN  7ENFU
3  TOYOTA    W  KMJ  WINDOW VAN  WA37R

====================================================================================================
BODY TYPE: WAGON
====================================================================================================
Unique POS4 Values:
['A']

     make pos4  WMI bodyType    VDS
0  TOYOTA    A  JTE    WAGON  AALAJ

====================================================================================================
BODY TYPE: PICK-UP
====================================================================================================
Unique POS4 Values:
['C']

     make pos4  WMI bodyType    VDS
0  TOYOTA    C  MRO  PICK-UP  CX8CB
1  TOYOTA    C  MRO  PICK-UP  CX8CB