In [135]:
import pandas as pd
import glob

# Reading the csv file

In [136]:
data = pd.read_csv(r"..\data\data_methaq(1.0).csv")
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan
...,...,...,...,...,...,...,...,...,...,...
1009599,LNGPCMXJ9PL305272,NaN,NaN,APULUO,APULUO AP200 4H,2023.0,Motorcycle,GCC,NaN,China
1009600,LURJAVBM8PA024843,STD,4.0,AIQAR,EQ 1,2023.0,COUPE,GCC,NaN,CHINA
1009601,7KGTC2C48NR003646,NaN,NaN,Electric Motion,ePure,2022.0,Motorcycle,GCC,NaN,AMERICA
1009602,LX6TK334XS2510023,NaN,NaN,CHANGHUA,CH150T-34,2025.0,Motorcycle,GCC,NaN,China
1009603,MI76734700,GL,4.0,MANITOU,MTX1740SLT,2015.0,HEAVY EQUIPMENT,GCC,NaN,Italy

In [137]:
import pandas as pd

data = pd.read_csv(r"../data/data_methaq(1.0).csv")

for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

       chassisNumber trim  cylinders    make    model    year  \
0  RKLBB9HE7F5115863   SE        4.0  TOYOTA  COROLLA  2015.0
1  JTFHX02POF0099797  GLX        4.0  TOYOTA    HIACE  2015.0
2  JTFHX02P7F0094323   DX        4.0  TOYOTA    HIACE  2015.0
3  JTFHXDGP7F0094373   DL        4.0  TOYOTA    HILUX  2015.0
4  4T1BG22K01U789089  XLI        4.0  TOYOTA    CAMRY  2001.0

             bodyType regionalSpec  noOfDoors  origin
0               SEDAN          GCC        4.0  TAIWAN
1  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
2  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
3  PICK UP DOUBLE CAB          GCC        4.0   JAPAN
4               SEDAN      NON-GCC        4.0   JAPAN

In [138]:
data = data[data["make"] == "TOYOTA"]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN
...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN

# checking chassis number length and 10th pos

In [139]:
data["chassis_len"] = data["chassisNumber"].str.len()
data["pos10"] = data["chassisNumber"].str[9]

is_standard = (data["chassis_len"] == 17) & (~data["pos10"].isin(['I', 'O', 'Q', 'U', 'Z', '0']))
data = data[is_standard]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,chassis_len,pos10
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,17,F
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,17,F
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,17,F
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,17,F
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,17,1
...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,17,K
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,17,S
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,17,M
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,17,S
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,17,M

In [140]:
# 1. World Manufacturer Identifier (WMI)
data["WMI"] = data["chassisNumber"].str[0:3]
data["pos1"] = data["chassisNumber"].str[0]
data["pos2"] = data["chassisNumber"].str[1]
data["pos3"] = data["chassisNumber"].str[2]

# 2. Vehicle Descriptor Section (VDS)
data["VDS"] = data["chassisNumber"].str[3:9]  # Standard VIN uses positions 4-9 (index 3:9)
data["pos4"] = data["chassisNumber"].str[3]
data["pos5"] = data["chassisNumber"].str[4]
data["pos6"] = data["chassisNumber"].str[5]
data["pos7"] = data["chassisNumber"].str[6]
data["pos8"] = data["chassisNumber"].str[7]
data["pos9"] = data["chassisNumber"].str[8]  # Check Digit

# 3. Vehicle Identifier Section (VIS)
data["VIS"] = data["chassisNumber"].str[9:17]  # Standard VIN uses positions 10-17 (index 9:17)
data["Model_Year"] = data["chassisNumber"].str[9]  # Model Year
data["Plant_Code"] = data["chassisNumber"].str[10]  # Plant Code

# 4. Production Serial Number (Last 6 digits of VIS)
data["Serial_Number"] = data["chassisNumber"].str[11:17]  # Positions 12-17 (index 11:17)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["WMI"] = data["chassisNumber"].str[0:3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos1"] = data["chassisNumber"].str[0]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos2"] = data["chassisNumber"].str[1]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos3"] = data["chassisNumber"].str[2]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["VDS"] = data["chassisNumber"].str[3:9]  # Standard VIN uses positions 4-9 (index 3:9)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos4"] = data["chassisNumber"].str[3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos5"] = data["chassisNumber"].str[4]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos6"] = data["chassisNumber"].str[5]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos7"] = data["chassisNumber"].str[6]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos8"] = data["chassisNumber"].str[7]
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos9"] = data["chassisNumber"].str[8]  # Check Digit
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["VIS"] = data["chassisNumber"].str[9:17]  # Standard VIN uses positions 10-17 (index 9:17)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Model_Year"] = data["chassisNumber"].str[9]  # Model Year
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Plant_Code"] = data["chassisNumber"].str[10]  # Plant Code
C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\2276515768.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Serial_Number"] = data["chassisNumber"].str[11:17]  # Positions 12-17 (index 11:17)

In [141]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos4,pos5,pos6,pos7,pos8,pos9,VIS,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,B,B,9,H,E,7,F5115863,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,H,X,0,2,P,O,F0099797,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,H,X,0,2,P,7,F0094323,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,H,X,D,G,P,7,F0094373,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,B,G,2,2,K,0,1U789089,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,H,U,8,C,D,X,K0071134,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,A,B,B,B,J,6,S4188504,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,H,X,0,1,J,3,M4222343,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,A,A,C,A,J,1,S5008118,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,B,2,9,F,3,4,M2123579,M,2,123579

data[["pos1", "origin"]]

In [142]:
print(data['chassisNumber'].nunique())

239212

In [143]:
print(data['pos1'].unique())

['R' 'J' '4' 'M' '6' '5' '1' '2' 'W' 'L' 'N' '3' '7' 'A' '8' 'Z' 'K' 'S'
 'V' 'Y' 'I' 'D' 'G' 'U' '0' 'T' '9' 'C' 'F' 'H' 'E' 'B' 'X']

In [144]:
print(data['trim'].nunique())

353

In [145]:
print(data['trim'].unique())

['SE' 'GLX' 'DX' 'DL' 'XLI' 'VX' 'MID' 'DLX' 'VXR' 'FABRIC' 'E' 'TOP'
 'EXTREME' 'GL' 'BASE' 'S' 'FLEET' 'STD (NON GCC)' 'GXR' 'EXR'
 'SE+ ANNIVERSARY EDITION' 'GL2' 'SR5' 'STD' 'LE' 'XLI MID' 'LE (NON GCC)'
 'SE+' 'GLI' 'SR5 (NON GCC)' 'TX' 'LIMITED' 'XLE (NON GCC)'
 'SE TRD AERO PK' 'EX' 'ICONIC' 'VX MID' 'LE HEV' 'SGLX' 'PW CL' 'GX'
 'XLE' 'SPORT' 'G' 'GRANDE' 'GR' 'XLI TOP' 'S TRD SPORT PK' 'S+' 'PRO'
 'XLI RB' 'LIMITED PREMIUM' 'GLE' 'XLI EXECUTIVE' 'GLS' 'PLATINUM'
 'DLX TOP' 'TURBO G RA' 'LIMITED (NON GCC)' 'SR5 4X4' 'VXR HEV' 'GLE HEV'
 'SAFARI' 'LX' 'GXR TOP 60TH ANNIV. XTREME' 'CE (NON GCC)' 'GLI HEV'
 'PREMIUM' 'XLI EXECUTIVE MR' 'XL' 'GXR TOP' 'VXR BASE' 'LX AC PWR OPT'
 'LX WINCH' 'TX-L' 'XLE TOURING' 'GXR GT' 'DLS' 'VXR TOP' 'SC'
 'GLE-X HEV 40TH ANNIV' 'SALOON' nan 'ADVENTURE'
 'CREWMAX CAPSTONE (NON GCC)' 'LE STD' 'LIMITED MID' 'GX TOP' 'TX-L TOP'
 'GLI TOP' 'EXCLUSIVE' 'XSE (NON GCC)' 'BLACK EDITION' 'DX H/R W/B'
 'C (NON GCC)' 'XLI POWER OPT' 'GLX SPORT Z' 'S PLUS' 'VTX' 'GXL' 'HT SWB'
 'GXR MID' 'ECO' 'GX MID' 'GXR2' 'LWB HIGH ROOF' '1794 EDITION (NON GCC)'
 '40TH ANNIVERSARY EDITION' 'TOURING' 'HEV' 'GLI TOP LTH' 'PS PW CL'
 'LIMITED 4X4' 'GR SPORT' 'STD D' 'TXL1' 'LWB' 'DLS - STD ROOF' 'EXR HEV'
 'LSE' 'BE' 'GLE-X' 'GT' 'T' 'SWB' 'SE (NON GCC)' 'SR' 'GTX' 'TXL3'
 'GR TAN EDITION' 'ST' 'E PLUS HEV' '1.8' 'LIMITED 4X2' 'VX TOP LTH' 'VX2'
 'STANDARD' 'SV' 'SR5 4X2' 'VX1' 'GXR FMST' 'HEV GLI' 'GXR1' 'DYNAMIC'
 'XLI EXECUTIVE HEV' '1' 'GR-S' 'FJ STD' 'GR BLUE EDITION' 'TRD' 'YX'
 'GXR TOP DMST' 'LMV' 'CTD' 'HT VXR' 'LIMITED TRD SPORT PK' 'VXR TOP LTH'
 'TXR' 'XLE HEV' 'STD AC' 'XLT' 'COUPE' '1500' 'X' 'TRD OFF-ROAD' 'BUS'
 'GLE HEV BLACK EDITION' 'Y PLUS' 'SR (NON GCC)' 'STATION' 'PICK UP' 'TX1'
 'SEDAN' 'GXR SOD D/AC AW' 'TC (NON GCC)' 'LIMITED HEV' 'SL' 'XTREME'
 'TXL2' 'GXR4' 'GXR TOP FMST' 'GT SPORT' 'HARD TOP' 'HYBRID (NON GCC)'
 'GL TOP' 'XSE' 'GRD' 'L' 'SGL' 'SED' '2400' 'GRANDE HEV 40TH ANNIV' 'AIR'
 'TRD SPORT' 'STANDDARD' '0' 'AXL ' 'XLI - AW' 'TURBO G' 'GXR-V' 'STAN'
 'VT' 'GA' 'GXR+' '2.0L' '25HX' 'PREMIER' 'GXR3' '6' 'SE TRD SPORT PK'
 'AUTOMATIC' 'LUMIERE HEV' 'STANDER' 'TRIM' 'LEVIN' 'HILUX' 'EXI'
 'LAND CRUSIER' '4X4' 'XE 4WD' 'A' 'STATION1' 'GXR MID 60TH ANNIV. XTREME'
 'VXR MID' 'PICKUP' 'S ASF' 'GL DECKLESS' 'CRESSIDA' 'LS' 'HYBRID'
 'LUXURY' 'GF' 'HT SLWB' 'CABRIO' 'ADVENTTURE' 'STD CARGO' 'HYCROSS' 'GG'
 'STATION ' 'SLD' 'C' 'PRESTIGE' 'Y' 'LUMIERE 40TH ANNIV' 'GRANDE HEV'
 'PIKUP' 'PRADO' 'LTD HEV' '10TH VICTORY EDITION' 'ROYAL' 'GL LIMITED'
 'CE' 'LIMITED TRD AERO PK' 'SS' 'VX2 PLUS' 'FULL OPTION' 'VXR TOP XTREME'
 '4WD' 'GLI TOP LEATHER' '60TH' 'AT' 'GXL 1ST EDITION' 'USF'
 'DLS HIGH ROOF' '1500 CREWCAB SLE Z71' 'ORION' 'STANDERD' 'VX-L MID'
 'GGG' 'GLS TOP' 'COMFORT' 'MPV' 'VIP7' 'LTZ' '45' 'LIMITED TOP'
 'EXECUTIVE' 'STD  (NON GCC)' '4' 'PLATINUM LUXURY 4X4' 'N' 'NON GCC'
 'GLI MR HEV' 'SENA' 'CAR TRIM' 'LX WIDE TYRES' 'SPORTS' 'COASTER'
 'S T2 TOP' 'AMBIENTE' 'VX-L TOP' 'PICKUP ' 'LUXURY SPORT' 'GV'
 'ADVENTURE 1ST EDITION' 'ASD' 'AA' 'AMG' 'YA' 'TR' 'EXCELLENCE' 'SU'
 'GLX PREMIUM' 'ZX' 'TUNDRA' 'GLS LOWLINE' 'SUPER SAFARI T1' 'ABC'
 'DOUBLE CABIN ' 'GL LTH' 'DTD' 'ROYAL EDITION' '2' 'ASAD' 'LXI' '1.5'
 'GC' 'GXR MID XTREME' '90' 'TOP LTH' 'STEALTH' 'ALTIS (NON GCC)' 'H'
 'S TRD AERO PK' '40 TFSI S-LINE' 'SUV' 'SE T2' 'FR-S (NON GCC)' 'DC'
 'LE PLATINUM CITY' 'PICK' 'GXR MID 60TH ANNIVERSARY' 'SLT' 'SINGLE CABIN'
 'S T1' 'VTI' 'CARRERA GTS' 'EX MID' 'TRTIM' 'VAN' 'XLI ' 'TAXI' 'COM'
 'IM' 'GXR HEV' '1000' 'SPORTS BASIC' 'ADVENTURE 1ST EDITIO'
 '40TH ANNIVERSARY EDI' 'GXR TOP 60TH ANNIV. ' '1794 EDITION (NON GC'
 'XLI HEV' 'SE+ ANNIVERSARY EDIT' 'CREWMAX CAPSTONE (NO']

In [146]:
print(data['bodyType'].unique())

['SEDAN' 'MINI BUS HIGH ROOF' 'PICK UP DOUBLE CAB' 'SUV' 'HATCHBACK'
 'PICK UP SINGLE CAB' 'PANEL VAN' 'BUS' 'MPV' 'ESTATE' 'PICK UP' 'VAN'
 'MINI BUS' 'COUPE' 'SUV- CROSSOVER' 'PICKUP' 'SALOON'
 'PANEL VAN HIGH ROOF' 'STATION' 'HALF PANEL VAN' 'CONVERTIBLE'
 'CARGO VAN' 'MINIVAN' 'MINI BUS SEMI HIGH ROOF' 'CARAVAN' 'PICKUP TRUCK'
 'LIGHT VEHICLE' 'MOTORCYCLE' 'PICKUP SINGLE CABIN' 'TRUCK'
 'PICK UP DOUBLE CABIN' 'PICKUP DOUBLE CABIN' 'COUPE/CABRIOLET'
 'AMBULANCE' 'REGULAR CAB' 'PICKUP DOUBLE CAB' 'WINDOW VAN' 'WAGON'
 'PICK-UP']

In [147]:
print(data['bodyType'].nunique())

39

In [148]:
print(data['WMI'].unique())

['RKL' 'JTF' '4T1' 'JTM' 'JTD' 'MR0' 'JTE' 'MR2' '6T1' '5TF' 'MHF' 'JTN'
 'JTC' 'JTG' '5TD' '4TA' 'JIF' 'MHK' 'MRO' 'MR1' '1NX' '2T3' 'JT3' 'JT2'
 'WZ1' '2T1' 'LVG' 'NMT' 'WDB' '5YF' 'JT4' '4T4' 'JTB' 'LFM' '3TM' 'JF1'
 '5TB' '7MU' 'MBJ' '3MY' 'ANE' '1N4' '8T1' '4T3' '5TE' 'JTK' 'ZE1' 'KMF'
 'STB' 'ZSG' 'VNK' 'WWW' 'JD4' 'JT6' 'STF' 'SJK' '3TY' 'LFP' 'JAA' 'JMY'
 'JJ5' 'LA7' 'WV1' 'YV2' 'MHE' 'INX' 'JN8' 'JNB' 'JTV' 'D04' 'JHG' '1GC'
 'JN6' 'SYF' 'GTF' 'KN9' '137' '4TI' 'LZC' 'LVC' 'ZGE' '6TI' '2CN' 'JWT'
 'MB1' 'JM3' 'UP1' 'KNC' 'MM7' 'STD' 'YS2' 'JZA' 'LXG' 'ZAP' 'JCB' 'LHA'
 'MA1' '000' 'ME4' 'JHE' '4TT' '411' 'RP8' 'U8Q' 'ITG' 'LGW' 'JHH' 'RA6'
 'MMM' '5T1' 'MAF' 'JT0' 'TNX' 'LWL' 'LA6' 'MA3' 'WDD' '9BS' '2FU' 'KNF'
 'NNN' '5T8' 'MMB' 'WBW' '57W' 'MRI' 'LTA' 'LFV' 'JTH' 'ZRE' 'JHF' 'WMA'
 'JL6' 'LVA' 'MAT' 'LKL' 'LZW' 'AAP' '7SV' 'VF3' 'ACV' '5TT' 'KN3' '1FD'
 'KMH' 'MZB' 'JND' 'MET' '213' 'MRD' '5FP' 'MD2' 'ITN' '2C4' 'JN1' 'ZZE'
 'LTV' 'CLG' 'LRR' 'LJ1' '2GN' '1D7' 'JIM' 'LCF' 'L7X' 'JTS' 'FZJ' 'LEF'
 '2GC' 'LC0' 'KMJ' '1FT' '611' 'MLH' 'UAE' 'JAC' '3N6' 'WD4' 'LSK' '5HD'
 'IG1' 'WMW' 'JH4' 'KLA' 'GT1' 'MD6' 'NV1' 'MNT' 'LK1' 'KPD' 'STO' 'JTL'
 'JT8' 'RKM' 'SCR' 'WDA' 'LZZ' 'WYU' 'WCY' 'NSP' 'KL7' 'MMC' 'LM8' '00N'
 'NCP' '1GN' '1GD' 'LJN' 'GGG' 'JRN' 'KPB' '4T2' 'LET' 'WAU' 'KL3' 'KN4'
 'JT5' 'WME' 'UTG' '3N1' 'JL5' 'JL7' 'JHD' 'LCO' 'JTZ' 'LSC' 'SAL' 'MH3'
 'ZFC' 'LPS' 'N1N' 'JD2' 'JZS' '1GT' '1C6' 'VR3' 'MYN' '6TT' 'LS4' 'JJ7'
 'WD8' 'YV1' 'KLI' 'VS5' 'SXV' 'LVV' 'MFH' 'L3H' 'HJN' 'ZGU' 'JE3' '5XX'
 'JN2' 'L6T' 'J1G' 'WZI' 'LSG' 'JS1' 'JHM' '6TD' '2TI' '3GY' '1G6' '211'
 '9KM' 'MC1' 'AR2' 'JIN' 'JIG' '1HD' 'JA3' 'LGD' '1C4' '1ST' 'RN1' 'LVB'
 'JNC' 'LGF' 'MEJ' 'KNR' '123' '5NF' 'SMV' 'WBA' 'RK4' 'MDH' 'STE' 'LSJ'
 'KL1' '55S' 'LM6' 'FJ4' 'YN8' 'LSF' 'MBI' '471' 'EE1' 'MC2' 'MKH' 'JNK'
 'JTJ' '2HN' '454' '6T0' 'RKT' 'MV1' 'MK2' '1GJ' 'UTD' '5N1' 'RKE' 'LMX'
 '1G1' 'LK6' 'JTR' 'YAR' 'BT1' '4F4' '8LT' 'LA9' 'MPA' '671' '1TF' '1N6'
 'CTF' 'W1W' 'SXA' 'LSY' '1TG' '1N1' 'LHP' 'JAM' '3D7' 'MPJ' 'IN6' '5AL'
 'MP2' 'JM7' 'LZY' 'ITD' '1C8' 'LAZ' '090' 'INB' 'W11' 'CPB' '6TB' 'KNA'
 'JH2' 'STY' '074' '010' 'JS2' 'SMT' 'ST1' '5T0' 'LHG' 'WV2' 'UZS' 'VF1'
 'STM' '2D4' 'W01' 'JYM' 'EP9' '3TD' 'D02' 'J1D' 'L3A' 'VF7' 'MRU' 'JTU'
 'KL5' 'ZCF' 'K1K' 'ZT3' 'LFZ' '61L' 'AVV' 'JTA' 'JDT' 'FJ7' 'ITE' 'LS6'
 '5GT' 'M0F' 'AUS' '150' 'RF5' 'AT1' 'LVM' 'VZE' 'CM8' 'JT1' 'LBB' 'XWB'
 'L11' 'HJR' '4T0' '180' 'YBL' 'MHM' '1G0' 'WB1' '6TF' '1V2' '425' '1HG'
 '1G2' '111' 'WVG' 'A25' 'WVW' 'LVZ' '25T' 'LGJ' 'HA9' 'LFB' 'LNB' 'W1K'
 '474' '174' 'KNM' 'YSM' 'JED' '1LN' 'MB0' 'MBT' '5ZT' '3GN' 'WP0' 'CE1'
 'AS3' 'ET1' 'MFF' 'J10' '3T1' 'MHP' 'LFC' 'EL5' 'GX9' '1TM' 'AE1' 'HJ4'
 'BKL' 'K20' 'SKF' 'LDP' 'MRC' 'UTM' 'JNE']

In [149]:
print(data['WMI'].nunique())

451

In [150]:
filtered_data = data[data['pos2'] == 'T']
filtered_data[['make', 'WMI', 'pos1','pos2', 'pos3', 'origin', 'model']]

          make  WMI pos1 pos2 pos3 origin               model
1       TOYOTA  JTF    J    T    F  JAPAN               HIACE
2       TOYOTA  JTF    J    T    F  JAPAN               HIACE
3       TOYOTA  JTF    J    T    F  JAPAN               HILUX
4       TOYOTA  4T1    4    T    1  JAPAN               CAMRY
5       TOYOTA  JTM    J    T    M  JAPAN        LAND CRUISER
...        ...  ...  ...  ...  ...    ...                 ...
922347  TOYOTA  6T1    6    T    1    NaN        CAMRY HYBRID
922349  TOYOTA  6T1    6    T    1    NaN        CAMRY HYBRID
922351  TOYOTA  JTM    J    T    M    NaN        LAND CRUISER
922352  TOYOTA  JTM    J    T    M    NaN        LAND CRUISER
922353  TOYOTA  JTE    J    T    E    NaN  LAND CRUISER PRADO

[179111 rows x 7 columns]

In [151]:
filtered_data = data[data['pos2'] != 'T']
filtered_data[['make', 'WMI', 'pos1','pos2', 'pos3', 'origin', 'model']]

          make  WMI pos1 pos2 pos3    origin          model
0       TOYOTA  RKL    R    K    L    TAIWAN        COROLLA
7       TOYOTA  MR0    M    R    0  THAILAND          HILUX
11      TOYOTA  MR2    M    R    2  THAILAND          YARIS
15      TOYOTA  MR0    M    R    0  THAILAND          HILUX
17      TOYOTA  RKL    R    K    L    TAIWAN        COROLLA
...        ...  ...  ...  ...  ...       ...            ...
922339  TOYOTA  VNK    V    N    K       NaN          YARIS
922344  TOYOTA  RKL    R    K    L       NaN  COROLLA CROSS
922348  TOYOTA  MHK    M    H    K       NaN         AVANZA
922350  TOYOTA  MR0    M    R    0       NaN          HILUX
922354  TOYOTA  MHF    M    H    F       NaN          YARIS

[60103 rows x 7 columns]

In [152]:
data[['make', 'pos1', 'origin']]

          make pos1  origin
0       TOYOTA    R  TAIWAN
1       TOYOTA    J   JAPAN
2       TOYOTA    J   JAPAN
3       TOYOTA    J   JAPAN
4       TOYOTA    4   JAPAN
...        ...  ...     ...
922350  TOYOTA    M     NaN
922351  TOYOTA    J     NaN
922352  TOYOTA    J     NaN
922353  TOYOTA    J     NaN
922354  TOYOTA    M     NaN

[239214 rows x 3 columns]

In [153]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos4,pos5,pos6,pos7,pos8,pos9,VIS,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,B,B,9,H,E,7,F5115863,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,H,X,0,2,P,O,F0099797,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,H,X,0,2,P,7,F0094323,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,H,X,D,G,P,7,F0094373,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,B,G,2,2,K,0,1U789089,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,H,U,8,C,D,X,K0071134,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,A,B,B,B,J,6,S4188504,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,H,X,0,1,J,3,M4222343,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,A,A,C,A,J,1,S5008118,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,B,2,9,F,3,4,M2123579,M,2,123579

# Cutting out wrong data

In [154]:
data_pos0_1 = data[data['pos1'] == '1']
data_pos0_1[['make','pos1', 'WMI','origin']]

          make pos1  WMI         origin
96      TOYOTA    1  1NX        AMERICA
863     TOYOTA    1  1NX  UNITED STATES
956     TOYOTA    1  1NX            USA
1191    TOYOTA    1  1N4          JAPAN
1494    TOYOTA    1  1NX        AMERICA
...        ...  ...  ...            ...
919730  TOYOTA    1  1NX            NaN
920802  TOYOTA    1  1NX            NaN
920945  TOYOTA    1  1NX            NaN
921403  TOYOTA    1  1NX            NaN
921876  TOYOTA    1  1NX            NaN

[1334 rows x 4 columns]

In [155]:
print(data_pos0_1['origin'].unique())

['AMERICA' 'UNITED STATES' 'USA' 'JAPAN' 'PAKISTAN' 'CANADA'
 'UNITED KINGDOM' 'UAE' nan 'TAIWAN' 'THAILAND' 'SOUTH AMERICAN'
 'GUAM (USA)']

In [156]:
data_pos0_4 = data[data['pos1'] == '4']
data_pos0_4[['make','pos1', 'WMI','origin']]

          make pos1  WMI         origin
4       TOYOTA    4  4T1          JAPAN
26      TOYOTA    4  4T1  UNITED STATES
38      TOYOTA    4  4T1          JAPAN
57      TOYOTA    4  4T1          JAPAN
63      TOYOTA    4  4TA          JAPAN
...        ...  ...  ...            ...
922268  TOYOTA    4  4T1            NaN
922273  TOYOTA    4  4T1            NaN
922314  TOYOTA    4  4T1            NaN
922322  TOYOTA    4  4T1            NaN
922334  TOYOTA    4  4T1            NaN

[22374 rows x 4 columns]

In [157]:
print(data_pos0_4['origin'].unique())

['JAPAN' 'UNITED STATES' 'AUSTRALIA' 'USA' 'AMERICA' 'UNITED KINGDOM'
 'UAE' 'UNITED STATES VIRGIN ISLANDS' 'UNITED NATIONS' nan 'CANADA'
 'GUAM (USA)' 'AFGHANISTAN' 'UNITED ARAB EMIRATES' 'GERMANY' 'U.S.A'
 'MACAU' 'NON GCC' 'ITALY' 'USA MINOR OUTLYING ISLANDS' 'INDIA' 'AUSTRIA'
 'CAMEROON' 'AMERICAN' 'MAE' 'SOUTH KOREA' 'KOREA' 'GCC'
 'PAPUA NEW GUINEA' 'GUINEA' 'YEMEN' 'SPAIN' 'JAPANN' 'اليابان' 'RUSSIA'
 'CHINA' 'A' 'SOUTH AMERICAN' 'AMERICAN SAMOA' 'GREAT BRITAIN'
 'VIRGIN ISLANDS (USA)' 'JERSEY' 'UMM AL QUWAIN' 'GREECE' 'PAKISTAN'
 'KOREA SOUTH' 'ASIAN' 'EMIRATES']

In [158]:
data_pos0_5 = data[data['pos1'] == '5']
data_pos0_5[['make','pos1', 'WMI','origin']]

          make pos1  WMI         origin
25      TOYOTA    5  5TF        AMERICA
50      TOYOTA    5  5TD        AMERICA
61      TOYOTA    5  5TD        AMERICA
69      TOYOTA    5  5TD          JAPAN
112     TOYOTA    5  5TD  UNITED STATES
...        ...  ...  ...            ...
922272  TOYOTA    5  5TF            NaN
922289  TOYOTA    5  5TD            NaN
922302  TOYOTA    5  5TF            NaN
922313  TOYOTA    5  5TD            NaN
922337  TOYOTA    5  5TD            NaN

[14143 rows x 4 columns]

In [159]:
print(data_pos0_5['origin'].unique())

['AMERICA' 'JAPAN' 'UNITED STATES' 'USA' 'CANADA'
 'UNITED STATES VIRGIN ISLANDS' 'AMERICAN SAMOA' 'GUAM (USA)' 'CHINA'
 'UNITED STATES VIRGIN' 'UAE' 'UNITED KINGDOM' nan 'AUSTRALIA' 'GUINEA'
 'UNITED NATIONS' 'JAMERICA' 'US' 'NORTH AMERICA' 'AFGHANISTAN'
 'الولايات المتحدة' 'MEXICO' 'INDIA' 'USA MINOR OUTLYING ISLANDS'
 'N AMERICAN COUNTRIES' 'SOUTH KOREA' 'امريكا' 'EGYPT' 'GCC' 'THAILAND'
 'SLOVAKIA' 'SILVER' 'INDONESIA' 'UNITED ARAB EMIRATES' '000' '00'
 'AMERICA ' 'VIRGIN ISLANDS (USA)' 'GERMANY' 'JAPANE' 'GREAT BRITAIN'
 'TURKEY' 'BELGIUM' 'EMIRATES' 'KOREA' 'AMERICAN']

In [160]:
data_pos0_2 = data[data['pos1'] == '2']
data_pos0_2[['make','pos1', 'WMI','origin']]

          make pos1  WMI         origin
106     TOYOTA    2  2T3         CANADA
158     TOYOTA    2  2T3         CANADA
206     TOYOTA    2  2T1         CANADA
222     TOYOTA    2  2T1  UNITED STATES
293     TOYOTA    2  2T1          JAPAN
...        ...  ...  ...            ...
921738  TOYOTA    2  2T3            NaN
921772  TOYOTA    2  2T1            NaN
922102  TOYOTA    2  2T3            NaN
922176  TOYOTA    2  2T1            NaN
922227  TOYOTA    2  2T3            NaN

[4606 rows x 4 columns]

In [161]:
print(data_pos0_2['origin'].unique())

['CANADA' 'UNITED STATES' 'JAPAN' 'UNITED STATES VIRGIN' 'TAIWAN'
 'AMERICA' 'USA' 'OTHERS' 'GREECE' 'SOUTH KOREA' nan 'KENYA' 'CHINA'
 'BELGIUM' 'PAPUA NEW GUINEA' 'MOROCCO' 'UAE' 'CAPAN' 'GHANA'
 'UNITED KINGDOM' 'GERMANY' 'HUNGARY' 'UNITED ARAB EMIRATES' 'MYANMAR'
 'THAILAND' 'ITALY' 'JAE']

In [162]:
data_pos0_3 = data[data['pos1'] == '3']
data_pos0_3[['make','pos1', 'WMI','origin']]

          make pos1  WMI  origin
591     TOYOTA    3  3TM  MEXICO
1078    TOYOTA    3  3MY  MEXICO
2143    TOYOTA    3  3MY  MEXICO
3807    TOYOTA    3  3TY  MEXICO
5134    TOYOTA    3  3TM  MEXICO
...        ...  ...  ...     ...
919288  TOYOTA    3  3TM     NaN
920443  TOYOTA    3  3MY     NaN
920696  TOYOTA    3  3TY     NaN
921571  TOYOTA    3  3TM     NaN
921814  TOYOTA    3  3TM     NaN

[313 rows x 4 columns]

In [163]:
print(data_pos0_3['origin'].unique())

['MEXICO' 'AMERICA' 'JAPAN' 'UNITED STATES' 'USA' nan 'UAE'
 'UNITED ARAB EMIRATES']

In [164]:
data_pos0_J = data[data['pos1'] == 'J']
data_pos0_J[['make','pos1', 'WMI','origin']]

          make pos1  WMI origin
1       TOYOTA    J  JTF  JAPAN
2       TOYOTA    J  JTF  JAPAN
3       TOYOTA    J  JTF  JAPAN
5       TOYOTA    J  JTM  JAPAN
6       TOYOTA    J  JTD  JAPAN
...        ...  ...  ...    ...
922345  TOYOTA    J  JTN    NaN
922346  TOYOTA    J  JTM    NaN
922351  TOYOTA    J  JTM    NaN
922352  TOYOTA    J  JTM    NaN
922353  TOYOTA    J  JTE    NaN

[112811 rows x 4 columns]

In [165]:
print(data_pos0_J['origin'].unique())

['JAPAN' 'AMERICA' 'UNITED STATES' 'TAIWAN' 'THAILAND' 'YEMEN' 'USA' 'UAE'
 nan '000' 'IRAN' 'PAPUA NEW GUINEA' 'INDIA' 'SUDAN' 'GREECE' '00'
 'UNITED ARAB EMIRATES' 'AUSTRALIA' '0' 'EMIRATES' 'GCC' 'CANADA' 'INDIAN'
 'تركيا' 'GERMANY' 'CHINA' 'JPAN' 'SOUTH KOREA' 'اليابان' 'G' 'HUNGARY'
 'FRANCE' 'SAUDI ARABIA' 'A' 'آتيانیان' 'SYRIA' 'MEXICO' 'ITALY' '4'
 'ASIAN' 'INDONESIA' 'NEW GUINEA' 'EGYPT' 'KOREA' 'JAMAICA' 'SUD' 'الريان'
 'MYANMAR' 'UNITED KINGDOM' 'HAQUARI' 'TURKEY' 'SPAIN' 'ORIGIN'
 'LIGHT VEHICLE' 'TOYOTA' 'JAPA' '11' 'BELGIUM' 'EUROPEAN UNION'
 'HONDURAS' 'AUSTRIA' 'JORDAN' 'JARAN' 'PARAGUAY' 'NORTH KOREA' 'MOROCCO'
 'S' 'SAPAN' 'SLOVAKIA' 'AFGHANISTAN' 'AMERICAN' 'J. PAN' '1' 'NON GCC'
 'JAPANE' 'PAKISTAN' 'OMAN' '17750' 'KOSOVO' 'QATAR' 'الصين' 'MACAU']

In [166]:
data_pos0_K = data[data['pos1'] == 'K']
data_pos0_K[['make','pos1', 'WMI','origin']]

          make pos1  WMI       origin
2061    TOYOTA    K  KMF  SOUTH KOREA
9355    TOYOTA    K  KN9  SOUTH KOREA
12446   TOYOTA    K  KNC  SOUTH KOREA
25132   TOYOTA    K  KNF  SOUTH KOREA
29667   TOYOTA    K  KNC  SOUTH KOREA
...        ...  ...  ...          ...
205287  TOYOTA    K  KMF  SOUTH KOREA
231432  TOYOTA    K  KMJ  SOUTH KOREA
233212  TOYOTA    K  KMF  SOUTH KOREA
236789  TOYOTA    K  K20          NaN
241401  TOYOTA    K  KMJ  SOUTH KOREA

[86 rows x 4 columns]

In [167]:
print(data_pos0_K['origin'].unique())

['SOUTH KOREA' 'KOREA' 'REPUBLIC OF SOUTH KOREA' nan 'NORTH KOREA' 'JAPAN'
 'INDONESIA']

In [168]:
data_pos0_W = data[data['pos1']== 'W']
data_pos0_W[['make','pos1', 'WMI','origin']]

          make pos1  WMI   origin
196     TOYOTA    W  WZ1  AUSTRIA
284     TOYOTA    W  WDB  GERMANY
2183    TOYOTA    W  WZ1  AUSTRIA
2383    TOYOTA    W  WZ1  AUSTRIA
2923    TOYOTA    W  WWW    JAPAN
...        ...  ...  ...      ...
241240  TOYOTA    W  WDB  GERMANY
920066  TOYOTA    W  WZ1      NaN
920857  TOYOTA    W  WZ1      NaN
921262  TOYOTA    W  WZ1      NaN
921379  TOYOTA    W  WZ1      NaN

[271 rows x 4 columns]

In [169]:
print(data_pos0_W['origin'].unique())

['AUSTRIA' 'GERMANY' 'JAPAN' 'POLAND' 'SPAIN' nan 'AUSTRALIA'
 'UNITED KINGDOM' 'THAILAND' 'HUNGARY' 'PORTUGAL' 'CHINA']

In [170]:
data_pos0_Z = data[data['pos1'] == 'Z']
data_pos0_Z[['make','pos1', 'WMI','origin']]

          make pos1  WMI    origin
1492    TOYOTA    Z  ZE1     JAPAN
2269    TOYOTA    Z  ZSG     JAPAN
10881   TOYOTA    Z  ZGE     JAPAN
11133   TOYOTA    Z  ZE1     JAPAN
14652   TOYOTA    Z  ZE1     JAPAN
...        ...  ...  ...       ...
228289  TOYOTA    Z  ZZE       NaN
232256  TOYOTA    Z  ZZE       NaN
234403  TOYOTA    Z  ZE1       NaN
238233  TOYOTA    Z  ZFC  THAILAND
239884  TOYOTA    Z  ZE1       NaN

[99 rows x 4 columns]

In [171]:
print(data_pos0_Z['origin'].unique())

['JAPAN' 'ITALY' nan 'THE THAILAND' 'TURKEY' 'CHINA' 'CANADA' 'THAILAND']

In [172]:
data_pos0_S = data[data['pos1'] == 'S']
data_pos0_S[['make','pos1', 'WMI','origin']]

          make pos1  WMI          origin
2231    TOYOTA    S  STB         AMERICA
3299    TOYOTA    S  STF           JAPAN
3646    TOYOTA    S  SJK  UNITED KINGDOM
7636    TOYOTA    S  SYF   UNITED STATES
9917    TOYOTA    S  STF           JAPAN
...        ...  ...  ...             ...
236225  TOYOTA    S  STB         AMERICA
237637  TOYOTA    S  SKF  UNITED KINGDOM
238063  TOYOTA    S  STF   UNITED STATES
238671  TOYOTA    S  STF           JAPAN
241456  TOYOTA    S  STF           JAPAN

[123 rows x 4 columns]

In [173]:
print(data_pos0_S['origin'].unique())

['AMERICA' 'JAPAN' 'UNITED KINGDOM' 'UNITED STATES' 'UAE' 'GREAT BRITAIN'
 nan 'MEXICO' 'THAILAND' 'AMERICAN' 'AUSTRALIA']

In [174]:
data_pos0_Y = data[data['pos1'] == 'Y']
data_pos0_Y[['make','pos1', 'WMI','origin']]

          make pos1  WMI   origin
4945    TOYOTA    Y  YV2    JAPAN
11557   TOYOTA    Y  YV2   SWEDEN
11698   TOYOTA    Y  YV2    JAPAN
13534   TOYOTA    Y  YS2    JAPAN
18167   TOYOTA    Y  YV2    JAPAN
18319   TOYOTA    Y  YV2   SWEDEN
18376   TOYOTA    Y  YV2    JAPAN
18389   TOYOTA    Y  YV2    JAPAN
19006   TOYOTA    Y  YV2   SWEDEN
23311   TOYOTA    Y  YV2    JAPAN
27688   TOYOTA    Y  YV2    JAPAN
28833   TOYOTA    Y  YV2    JAPAN
31865   TOYOTA    Y  YV2    JAPAN
37605   TOYOTA    Y  YV2  AMERICA
37758   TOYOTA    Y  YV2    JAPAN
42401   TOYOTA    Y  YV2    JAPAN
50464   TOYOTA    Y  YV2      NaN
63530   TOYOTA    Y  YS2      NaN
79159   TOYOTA    Y  YV1   SWEDEN
111591  TOYOTA    Y  YN8      NaN
124736  TOYOTA    Y  YV2      NaN
124759  TOYOTA    Y  YAR   FRANCE
129628  TOYOTA    Y  YV2      NaN
132195  TOYOTA    Y  YV2   SWEDEN
143175  TOYOTA    Y  YV2      NaN
157480  TOYOTA    Y  YV2   SWEDEN
157788  TOYOTA    Y  YV2      NaN
167337  TOYOTA    Y  YV2      NaN
175270  TOYOTA    Y  YV2   SWEDEN
182035  TOYOTA    Y  YBL      NaN
182047  TOYOTA    Y  YV2   SWEDEN
186983  TOYOTA    Y  YN8    JAPAN
189346  TOYOTA    Y  YV2   SWEDEN
195340  TOYOTA    Y  YV2   SWEDEN
196137  TOYOTA    Y  YSM    CHINA
205707  TOYOTA    Y  YV2   SWEDEN
211362  TOYOTA    Y  YS2      NaN
220476  TOYOTA    Y  YV2      NaN
223178  TOYOTA    Y  YV2      NaN
232119  TOYOTA    Y  YV2      NaN
232964  TOYOTA    Y  YV2   SWEDEN
233035  TOYOTA    Y  YV2   SWEDEN
233511  TOYOTA    Y  YV2   SWEDEN
234943  TOYOTA    Y  YV2      NaN
235710  TOYOTA    Y  YV2      NaN
239332  TOYOTA    Y  YV2      NaN
239461  TOYOTA    Y  YV2      NaN
239603  TOYOTA    Y  YV2      NaN
240643  TOYOTA    Y  YV2   SWEDEN

In [175]:
print(data_pos0_Y['origin'].unique())

['JAPAN' 'SWEDEN' 'AMERICA' nan 'FRANCE' 'CHINA']

In [176]:
data_pos0_L = data[data['pos1'] == 'L']
data_pos0_L[['make','pos1', 'WMI','origin']]

          make pos1  WMI origin
241     TOYOTA    L  LVG  CHINA
573     TOYOTA    L  LVG  CHINA
589     TOYOTA    L  LFM  JAPAN
1034    TOYOTA    L  LFM  CHINA
1277    TOYOTA    L  LFM  CHINA
...        ...  ...  ...    ...
920294  TOYOTA    L  LFM    NaN
920401  TOYOTA    L  LVG    NaN
920948  TOYOTA    L  LVG    NaN
921427  TOYOTA    L  LVG    NaN
922291  TOYOTA    L  LFM    NaN

[744 rows x 4 columns]

In [177]:
data_pos0_L[['make','pos1', 'WMI','origin']]

          make pos1  WMI origin
241     TOYOTA    L  LVG  CHINA
573     TOYOTA    L  LVG  CHINA
589     TOYOTA    L  LFM  JAPAN
1034    TOYOTA    L  LFM  CHINA
1277    TOYOTA    L  LFM  CHINA
...        ...  ...  ...    ...
920294  TOYOTA    L  LFM    NaN
920401  TOYOTA    L  LVG    NaN
920948  TOYOTA    L  LVG    NaN
921427  TOYOTA    L  LVG    NaN
922291  TOYOTA    L  LFM    NaN

[744 rows x 4 columns]

In [178]:
data_pos0_M = data[data['pos1'] == 'M']
data_pos0_M[['make','pos1', 'WMI','origin']]

          make pos1  WMI    origin
7       TOYOTA    M  MR0  THAILAND
11      TOYOTA    M  MR2  THAILAND
15      TOYOTA    M  MR0  THAILAND
18      TOYOTA    M  MR0  THAILAND
28      TOYOTA    M  MHF     JAPAN
...        ...  ...  ...       ...
922307  TOYOTA    M  MR0       NaN
922328  TOYOTA    M  MR2       NaN
922348  TOYOTA    M  MHK       NaN
922350  TOYOTA    M  MR0       NaN
922354  TOYOTA    M  MHF       NaN

[37745 rows x 4 columns]

In [179]:
print(data_pos0_M['origin'].unique())

['THAILAND' 'JAPAN' 'INDONESIA' 'INDIA' 'TAIWAN' 'TAHITIAN' nan 'ANDORRA'
 'تايلاند' 'JINDONESIA' 'EMIRATES' 'UAE' 'تايلند' 'CHINA' 'UNKNOWN'
 'AFGHANISTAN' 'UNITED STATES' 'SOUTH KOREA' 'GCC' 'ANGUILLA' 'AMERICA'
 'PAKISTAN' 'AUSTRALIA' 'LIGHT VEHICLE' 'HAILAND' 'IRAN' 'OTHERS'
 'UNITED ARAB EMIRATES' '1' 'PHILIPPINES' 'GERMANY' 'SAUDI ARABIA'
 'BANGLADESH' '0' 'THALLAND' 'LIBYA' 'ANTIGUA AND BARBUDA'
 'FRANCE (EUROPEAN PROVINCE)' 'CAMBODIA' 'FIJI' 'EGYPT' 'تایلاند' 'ASIAN'
 'TURKEY' 'FINDONESIA' 'TAILAND' 'MALAYSIA']

In [180]:
data_pos0_V = data[data['pos1'] == 'V']
data_pos0_V[['make','pos1', 'WMI','origin']]

          make pos1  WMI   origin
2842    TOYOTA    V  VNK    JAPAN
5204    TOYOTA    V  VNK   FRANCE
5312    TOYOTA    V  VNK  AMERICA
5776    TOYOTA    V  VNK   FRANCE
8315    TOYOTA    V  VNK   FRANCE
...        ...  ...  ...      ...
917346  TOYOTA    V  VNK      NaN
917755  TOYOTA    V  VNK      NaN
920833  TOYOTA    V  VNK      NaN
921310  TOYOTA    V  VNK      NaN
922339  TOYOTA    V  VNK      NaN

[119 rows x 4 columns]

In [181]:
print(data_pos0_V['origin'].unique())

['JAPAN' 'FRANCE' 'AMERICA' 'UNITED STATES' 'SPAIN' nan 'INDIA']

In [182]:
data_pos0_T = data[data['pos1'] == 'T']
data_pos0_T[['make','pos1', 'WMI','origin']]

         make pos1  WMI         origin
23095  TOYOTA    T  TNX  UNITED STATES

In [183]:
print(data_pos0_T['origin'].unique())

['UNITED STATES']

In [184]:
data_pos0_R = data[data['pos1'] == 'R']
data_pos0_R[['make','pos1', 'WMI','origin']]

          make pos1  WMI  origin
0       TOYOTA    R  RKL  TAIWAN
17      TOYOTA    R  RKL  TAIWAN
52      TOYOTA    R  RKL   JAPAN
94      TOYOTA    R  RKL   JAPAN
103     TOYOTA    R  RKL  TAIWAN
...        ...  ...  ...     ...
922275  TOYOTA    R  RKL     NaN
922285  TOYOTA    R  RKL     NaN
922332  TOYOTA    R  RKL     NaN
922333  TOYOTA    R  RKL     NaN
922344  TOYOTA    R  RKL     NaN

[17103 rows x 4 columns]

In [185]:
print(data_pos0_R['origin'].unique())

['TAIWAN' 'JAPAN' 'UAE' 'THAILAND' nan 'UNITED ARAB EMIRATES' 'TALWAN'
 'GCC' 'TAIWAN (CHINESE TAIPEI FOR IOC)' 'JAPAN ' 'PAKISTAN' 'NAYON'
 'TABUN' 'AMERICA' 'LIGHT VEHICLE' 'EGYPT' 'UNKNOWN' 'DUBAI' 'INDIA'
 'BAIWAN' 'TAIWAN (CHINESE TAIPEI)' 'LIWAN' 'TAIWAN (PROVINCE OF CHINA)'
 'HUNGARY' 'TUVALU' 'INDONESIA' 'IRAN' 'TANZANIA' 'ASIAN' 'CHINA' 'MACAU'
 'LEBANON' 'JAPANE' 'RUSSIA' 'EMIRATES' 'SOUTH KOREA' 'SPAIN' 'TAI'
 'TAIMAN' 'AUSTRALIA' 'UNITED STATES' 'ETHIOPIA' 'TAINAN' 'JORDAN'
 'TURKEY' 'HINA' 'تايون' 'TNIYON' 'GERMANY' 'NORWAY']

In [186]:
data_pos0_9 = data[data['pos1'] == '9']
data_pos0_9[['make','pos1', 'WMI','origin']]

         make pos1  WMI     origin
24622  TOYOTA    9  9BS      JAPAN
31894  TOYOTA    9  9BS      JAPAN
92809  TOYOTA    9  9KM  AUSTRALIA

In [187]:
print(data_pos0_9['origin'].unique())

['JAPAN' 'AUSTRALIA']

In [188]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos4,pos5,pos6,pos7,pos8,pos9,VIS,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,B,B,9,H,E,7,F5115863,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,H,X,0,2,P,O,F0099797,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,H,X,0,2,P,7,F0094323,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,H,X,D,G,P,7,F0094373,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,B,G,2,2,K,0,1U789089,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,H,U,8,C,D,X,K0071134,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,A,B,B,B,J,6,S4188504,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,H,X,0,1,J,3,M4222343,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,A,A,C,A,J,1,S5008118,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,B,2,9,F,3,4,M2123579,M,2,123579

In [189]:
origin_mapping = {
    "1": "USA",
    "4": "USA",
    "5": "USA",
    "2": "CANADA",
    "3": "MEXICO",
    "J": "JAPAN",
    "K": "SOUTH KOREA",
    "W": "GERMANY",
    "Z": "ITALY",
    "S": "UNITED KINGDOM",
    "Y": "SWEDEN / FINLAND",
    "L": "CHINA",
    "M": "INDIA",
    "V": "FRANCE / SPAIN",
    "T": "SWITZERLAND",
    "R": "TAIWAN",
    "9": "BRAZIL"
}

In [190]:
data["origin"] = data["pos1"].map(origin_mapping).fillna(data["origin"])

C:\Users\Admin\AppData\Local\Temp\ipykernel_19460\3808071572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["origin"] = data["pos1"].map(origin_mapping).fillna(data["origin"])

In [191]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos4,pos5,pos6,pos7,pos8,pos9,VIS,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,B,B,9,H,E,7,F5115863,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,H,X,0,2,P,O,F0099797,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,H,X,0,2,P,7,F0094323,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,H,X,D,G,P,7,F0094373,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,USA,...,B,G,2,2,K,0,1U789089,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,INDIA,...,H,U,8,C,D,X,K0071134,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,JAPAN,...,A,B,B,B,J,6,S4188504,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,JAPAN,...,H,X,0,1,J,3,M4222343,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,JAPAN,...,A,A,C,A,J,1,S5008118,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,INDIA,...,B,2,9,F,3,4,M2123579,M,2,123579

In [192]:
data_pos0_V_updated = data[data['pos1'] == 'V']
data_pos0_V_updated[['make','pos1', 'WMI','origin']]

          make pos1  WMI          origin
2842    TOYOTA    V  VNK  FRANCE / SPAIN
5204    TOYOTA    V  VNK  FRANCE / SPAIN
5312    TOYOTA    V  VNK  FRANCE / SPAIN
5776    TOYOTA    V  VNK  FRANCE / SPAIN
8315    TOYOTA    V  VNK  FRANCE / SPAIN
...        ...  ...  ...             ...
917346  TOYOTA    V  VNK  FRANCE / SPAIN
917755  TOYOTA    V  VNK  FRANCE / SPAIN
920833  TOYOTA    V  VNK  FRANCE / SPAIN
921310  TOYOTA    V  VNK  FRANCE / SPAIN
922339  TOYOTA    V  VNK  FRANCE / SPAIN

[119 rows x 4 columns]

In [193]:
data[['make','pos2', 'WMI','origin']]

          make pos2  WMI  origin
0       TOYOTA    K  RKL  TAIWAN
1       TOYOTA    T  JTF   JAPAN
2       TOYOTA    T  JTF   JAPAN
3       TOYOTA    T  JTF   JAPAN
4       TOYOTA    T  4T1     USA
...        ...  ...  ...     ...
922350  TOYOTA    R  MR0   INDIA
922351  TOYOTA    T  JTM   JAPAN
922352  TOYOTA    T  JTM   JAPAN
922353  TOYOTA    T  JTE   JAPAN
922354  TOYOTA    H  MHF   INDIA

[239214 rows x 4 columns]

In [194]:
print(data['pos3'].unique())

['L' 'F' '1' 'M' 'D' '0' 'E' '2' 'N' 'C' 'G' 'A' 'K' 'O' 'X' '3' 'T' 'B'
 '4' 'U' 'J' 'Y' 'W' '6' 'P' '5' '7' '8' 'V' '9' 'I' 'Q' 'H' 'S' 'R' 'Z']

In [195]:
data[['make','pos3', 'WMI','bodyType']]

          make pos3  WMI            bodyType
0       TOYOTA    L  RKL               SEDAN
1       TOYOTA    F  JTF  MINI BUS HIGH ROOF
2       TOYOTA    F  JTF  MINI BUS HIGH ROOF
3       TOYOTA    F  JTF  PICK UP DOUBLE CAB
4       TOYOTA    1  4T1               SEDAN
...        ...  ...  ...                 ...
922350  TOYOTA    0  MR0              PICKUP
922351  TOYOTA    M  JTM                 SUV
922352  TOYOTA    M  JTM                 SUV
922353  TOYOTA    E  JTE                 SUV
922354  TOYOTA    F  MHF               SEDAN

[239214 rows x 4 columns]

In [196]:
print(data['bodyType'].unique())

['SEDAN' 'MINI BUS HIGH ROOF' 'PICK UP DOUBLE CAB' 'SUV' 'HATCHBACK'
 'PICK UP SINGLE CAB' 'PANEL VAN' 'BUS' 'MPV' 'ESTATE' 'PICK UP' 'VAN'
 'MINI BUS' 'COUPE' 'SUV- CROSSOVER' 'PICKUP' 'SALOON'
 'PANEL VAN HIGH ROOF' 'STATION' 'HALF PANEL VAN' 'CONVERTIBLE'
 'CARGO VAN' 'MINIVAN' 'MINI BUS SEMI HIGH ROOF' 'CARAVAN' 'PICKUP TRUCK'
 'LIGHT VEHICLE' 'MOTORCYCLE' 'PICKUP SINGLE CABIN' 'TRUCK'
 'PICK UP DOUBLE CABIN' 'PICKUP DOUBLE CABIN' 'COUPE/CABRIOLET'
 'AMBULANCE' 'REGULAR CAB' 'PICKUP DOUBLE CAB' 'WINDOW VAN' 'WAGON'
 'PICK-UP']

In [197]:
from IPython.display import display

for pos_4 in data['pos4'].dropna().unique():

    # 1. Filter the DataFrame for the current pos4 value
    filtered_df = data.loc[
        data['pos4'] == pos_4,
        ['make', 'model', 'cylinders', 'bodyType', 'pos4', 'trim',  'regionalSpec', 'noOfDoors','WMI', 'VDS', 'Model_Year', 'Plant_Code','Serial_Number']
    ].reset_index(drop=True)

    # 2. Header for the current pos4 group
    print("\n" + "=" * 100)
    print(f"POS4: {pos_4}")
    print("=" * 100)

    # 3. Print unique values for all object columns (except pos4)
    print("--- Unique Values for Object Columns ---")
    object_cols = filtered_df.select_dtypes(include=['object']).columns
    
    for col in object_cols:
        if col != ['pos4', 'Serial_Number']:
            unique_vals = filtered_df[col].dropna().unique()
            print(f"  {col}: {list(unique_vals)}")
            
    print("-" * 100)

    # 4. Display the filtered DataFrame
    display(filtered_df)

====================================================================================================
POS4: B
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'CAMRY', 'YARIS', 'FJ CRUISER', 'HILUX', 'AVALON', 'RAV4', 'PRADO', 'AURION', 'ECHO', 'FORTUNER', 'SEQUOIA', 'TOYOTA CAMRY', 'FJ', 'LAND CRUISER', '4RUNNER', 'COROLLA 1.6', 'TUNDRA', 'SIENNA', 'LITEACE', 'PRIUS', 'HIACE', 'LEVIN', 'TERCEL', 'LAND CRUISER PRADO', 'LAND CRUISER PICK UP', 'TOYOTA ALTIS', 'COROLLA 1.3', 'HIGHLANDER', 'TOYOTA COROLLA', 'LAND CRUISER PICKUP 70', 'COASTER', 'COROLLA 1.8', '26HX DC 4X4P2.7LAT', 'HD 4X4', 'COROLLA SEDAN', 'CROWN', 'COROLLA CROSS', '4 RUNNER', 'TOYOTA TUNDRA', 'RAV 4', 'VENZA', 'كورولا 1.8', 'TOYOTA COROLLA 1.6', 'PRADO GX', 'RUSH', 'TOYOTA PRADO', '25 HX DC 4X4 2.7LAT', 'GLX DA (PICK UP)', 'TANDRA', 'RUNNER', 'VIOS', 'TOYOTA', 'TOYOTA HILUX', 'SALOON', '25 HX DC 4X4P 2.7LAT', 'COROLLA LI', 'GLX RA (PICK UP)', 'TOYOTA 4RUNNER', 'CORONA', 'COROLLA 1.6/SEDAN', 'TOYOTA COROLLA 2.0', 'هايلوكس', 'كامرى', '25 HX DC 4X4 P .LAT', '26 HX DC 4X4 P 2.7LAT', 'LITE ACE', 'كورولا', '2023', 'برادو', '25 HX DC 4X4 PLAT GLX RA(PICK UP)', 'PARISIENNE BROUGHAM', 'TANDRA PICK UP DOUBLE CABIN', 'HILUX ADVENTURE', 'RAIZE', 'AVANZA', 'كامري', 'COROLLA ', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'HATCHBACK', 'SUV', 'PICK UP DOUBLE CAB', 'ESTATE', 'PICK UP SINGLE CAB', 'SALOON', 'STATION', 'PICKUP', 'MPV', 'PANEL VAN', 'VAN', 'MINI BUS', 'MINI BUS HIGH ROOF', 'PICK UP', 'CARGO VAN', 'BUS', 'LIGHT VEHICLE', 'SUV- CROSSOVER', 'PICK UP DOUBLE CABIN', 'PICKUP DOUBLE CABIN', 'COUPE', 'TRUCK', 'PICKUP DOUBLE CAB']
  pos4: ['B']
  trim: ['SE', 'XLI', 'MID', 'VXR', 'E', 'TOP', 'EXTREME', 'GL', 'BASE', 'S', 'SE+ ANNIVERSARY EDITION', 'STD (NON GCC)', 'LE', 'XLI MID', 'GLX', 'SE+', 'GLI', 'LIMITED', 'VX', 'VX MID', 'GXR', 'GX', 'XLE', 'SPORT', 'GRANDE', 'XLI TOP', 'S TRD SPORT PK', 'S+', 'XLI RB', 'LIMITED PREMIUM', 'GLE', 'XLI EXECUTIVE', 'DLX', 'FLEET', 'EXR', 'SR5 4X4', 'GLE HEV', 'STD', 'CE (NON GCC)', 'GLI HEV', 'TX-L', 'XLE TOURING', 'DLS', 'SALOON', 'LE STD', 'LIMITED MID', 'GX TOP', 'GLI TOP', 'XLE (NON GCC)', 'G', 'EXCLUSIVE', 'XSE (NON GCC)', 'TX', 'XLI POWER OPT', 'ADVENTURE', 'GLX SPORT Z', 'S PLUS', 'LE (NON GCC)', 'SR5 (NON GCC)', '40TH ANNIVERSARY EDITION', 'TOURING', 'GX MID', 'PS PW CL', 'PLATINUM', 'LIMITED 4X4', 'GLE-X HEV 40TH ANNIV', 'EXR HEV', 'TX-L TOP', 'LE HEV', '1.8', 'SR5 4X2', 'FJ STD', '1', 'YX', 'DX', 'GXR TOP', 'EX', 'LIMITED TRD SPORT PK', 'DL', 'XLE HEV', 'BE', 'X', 'STD AC', 'LX AC PWR OPT', 'Y PLUS', 'VX2', 'XTREME', 'T', 'TXL2', 'DLS - STD ROOF', 'L', 'SED', 'LWB', 'SEDAN', 'GXR SOD D/AC AW', 'SL', 'STANDARD', '2.0L', 'SE TRD AERO PK', 'XLI EXECUTIVE MR', 'LUMIERE HEV', 'STANDER', 'TRIM', 'LEVIN', 'GL2', '4X4', 'SR5', 'LS', 'HYBRID', 'TXL1', 'GLS', 'Y', 'LUMIERE 40TH ANNIV', 'GRANDE HEV', 'HYBRID (NON GCC)', 'LTD HEV', 'ROYAL', 'LIMITED TRD AERO PK', 'C', 'GLI TOP LTH', '60TH', 'ORION', 'TXL3', 'VX-L MID', 'A', 'GGG', 'COMFORT', 'VX1', 'STD  (NON GCC)', '4', 'XLI EXECUTIVE HEV', 'PW CL', 'SPORTS', 'GLE HEV BLACK EDITION', 'VX TOP LTH', 'PICKUP', 'GXR TOP 60TH ANNIV. XTREME', 'CAR TRIM', 'GL DECKLESS', 'TR', 'GLX PREMIUM', 'TUNDRA', 'XL', 'DOUBLE CABIN ', 'PICK UP', 'ROYAL EDITION', 'SGLX', '1.5', '2', '90', 'TOP LTH', 'ST', 'ALTIS (NON GCC)', '40 TFSI S-LINE', 'SUV', 'VTI', 'CARRERA GTS', 'GRANDE HEV 40TH ANNIV', 'TRTIM', 'LX', '0', 'SPORTS BASIC', '40TH ANNIVERSARY EDI', 'GR SPORT', 'SE+ ANNIVERSARY EDIT']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['RKL', '4T1', 'JTD', 'JTE', 'MR2', '6T1', 'MR0', 'JTN', 'JTM', 'MHF', '1NX', 'JT2', '2T1', '5YF', '5TD', '2T3', '4T4', '5TB', '1N4', '8T1', '5TF', 'JTK', 'MHK', 'LVG', 'JJ5', 'INX', 'JNB', 'SYF', 'MRO', '4TI', 'JT3', 'LVC', 'JN6', '6TI', '2CN', 'STD', 'MR1', '4T3', '4TT', '411', 'JTF', '5T1', 'TNX', 'WBW', 'JL6', '213', 'MRD', 'LTV', '611', 'NMT', 'GT1', 'LFM', 'JTH', '7MU', 'MNT', 'MHE', 'JRN', 'KPB', '3N1', 'JL5', 'JL7', 'LSC', 'STF', '6TT', 'MFH', 'JN2', 'JJ7', 'JTL', '6TD', '2TI', '211', '9KM', 'JIN', 'JTG', 'MBJ', 'STB', 'LGF', '5NF', 'MDH', 'STO', '471', 'JNK', '6T0', 'RKE', 'JTR', 'BT1', '671', '1N6', 'JM7', 'KNA', 'MRI', 'JN1', 'ST1', '5T0', '5N1', 'JN8', '3TD', '000', 'MRU', '61L', 'JDT', 'M0F', 'AUS', 'LVM', '4T0', 'MHM', '1G2', '474', 'JTJ', 'JED', '1LN', 'JTU', 'JTV', 'UTD', 'WP0', 'ET1', '3T1', 'BKL', 'JT0', 'UTM', 'JNE']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,4.0,RKL,BB9HE7,F,5,115863
1,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,NON-GCC,4.0,4T1,BG22K0,1,U,789089
2,TOYOTA,YARIS,4.0,HATCHBACK,B,MID,GCC,5.0,JTD,BW9230,B,L,006031
3,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,JTD,BR23E6,6,0,248294
4,TOYOTA,FJ CRUISER,6.0,SUV,B,VXR,GCC,5.0,JTE,BU11F8,E,K,180180
...,...,...,...,...,...,...,...,...,...,...,...,...,...
118079,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK2,R,3,034380
118080,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK1,P,3,026798
118081,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,S,GCC,NaN,6T1,BF9FK4,D,X,474261
118082,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,GLI,GCC,NaN,6T1,BE32K8,6,X,538813
118083,TOYOTA,YARIS,4.0,SEDAN,B,E,GCC,NaN,MHF,B29F34,M,2,123579

====================================================================================================
POS4: H
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'HILUX', 'LAND CRUISER', 'RAV4', 'TUNDRA', 'LAND CRUISE', 'PRADO', 'CAMRY', 'INNOVA', 'HIGHLANDER', 'RAV 4', 'COROLLA', 'LAND CRUISER VXR', '4RUNNER', 'استیشن', 'بيك اب كابينه مزدوجه', 'COASTER', 'FJ CRUISER', '2016', 'HIACE ', 'LAND CRUISER GXR', 'TOYOTA LAND CRUISER', 'LAND CRUISER 70', 'AVANZA']
  bodyType: ['MINI BUS HIGH ROOF', 'PICK UP DOUBLE CAB', 'SUV', 'PANEL VAN', 'VAN', 'MINI BUS', 'PICK UP SINGLE CAB', 'PANEL VAN HIGH ROOF', 'MPV', 'STATION', 'HALF PANEL VAN', 'SEDAN', 'BUS', 'MINIVAN', 'MINI BUS SEMI HIGH ROOF', 'PICKUP TRUCK', 'PICK UP', 'CARGO VAN', 'PICKUP', 'SALOON', 'LIGHT VEHICLE']
  pos4: ['H']
  trim: ['GLX', 'DX', 'DL', 'VX', 'FABRIC', 'GXR', 'GL', 'PW CL', 'DLX', 'GX', 'VXR', 'G', 'STD', 'GLS', 'SAFARI', 'GXR TOP 60TH ANNIV. XTREME', 'GXR TOP', 'VXR BASE', 'GXR GT', 'VXR TOP', 'STD (NON GCC)', 'EXR', 'LE', 'ADVENTURE', 'GLE-X', 'PREMIUM', 'DX H/R W/B', 'HEV', 'GXR FMST', 'GLE HEV', 'VXR TOP LTH', 'LIMITED', 'MID', 'SR5 (NON GCC)', 'DLS', 'SE+', '0', 'SE', 'GXR+', 'LWB', 'XTREME', 'XLI', 'DLS - STD ROOF', 'GXR MID 60TH ANNIV. XTREME', 'GXR TOP DMST', 'GXR TOP FMST', 'BASE', 'STANDER', 'LE HEV', 'GXR SOD D/AC AW', 'XLE', 'VXR TOP XTREME', 'HYBRID (NON GCC)', 'GXR MID', 'STANDARD', 'SR', 'VXR MID', 'GLS TOP', 'LS', '60TH', 'GRD', 'SS', 'DLS HIGH ROOF', 'XLI EXECUTIVE HEV', 'AA', 'ZX', 'S', 'ST', 'HT SWB', 'TRD', 'COM', 'XLI EXECUTIVE', '1000', 'SWB', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTF', 'JTM', 'JTE', 'JT3', 'MR0', 'JTG', '5TF', '2T3', 'LFP', 'MRO', '5TD', 'JHE', '1GC', '5YF', 'KN3', 'JTN', 'JN1', 'JTS', 'KMJ', 'JN6', 'JTD', 'JTC', 'MMC', 'STF', 'WMA', 'KN4', 'JIF', 'JIM', 'LGD', '1C4', 'JT6', 'JTJ', '1TF', 'CTF', 'LSY', '1GJ', 'JMY', 'JTR', 'ITE', 'WVG', '1TM']
  VDS: ['HX02PO', 'HX02P7', 'HXDGP7', 'HT09J7', 'HD20V5', 'HU09J4', 'HX02P1', 'HX09J2', 'HT05J3', 'HT05J9', 'HX01JX', 'HH20V4', 'HX09J5', 'HX01J2', 'HX02P5', 'HU09JX', 'HT05J8', 'HY05J7', 'HJ09J7', 'HX05J9', 'HT05J1', 'HY05J2', 'HX05J2', 'HX8CD5', 'HX02P4', 'HJ0936', 'HX09J1', 'HY05J6', 'HT09J5', 'HJ09JX', 'HX09J7', 'HU09J9', 'HT09J9', 'HX09J6', 'HX01J8', 'HJ09J1', 'HX01J9', 'HX8CD4', 'HJ09J6', 'HT05J0', 'HT09J6', 'HX05JX', 'HY05J1', 'HT05J4', 'HT05JX', 'HJ09J4', 'HU09J1', 'HX8CD6', 'HU09J6', 'HX02PX', 'HY05J3', 'HX09J4', 'HU09J7', 'HX01J7', 'HX02P6', 'HT09J4', 'HJ09J9', 'HX05J6', 'HX02P8', 'HY05J5', 'HX05J4', 'HU09J0', 'HY05JX', 'HH20VX', 'HX8CDX', 'HJ01J1', 'HU01J4', 'HH20V5', 'HTO5J8', 'HY05J4', 'HY02J8', 'HX02P2', 'HX8CD7', 'HX8CD3', 'HH20V1', 'HT05J7', 'HY0SJX', 'HY05J8', 'HJ09J5', 'HX8CD2', 'HX01J0', 'HT05J5', 'HW5F15', 'HX05J3', 'HT09JX', 'HT09J2', 'HX02P0', 'HT09J8', 'HX8CD0', 'HJ09J3', 'HW5F10', 'HX09J9', 'HY02JX', 'HX05J7', 'HX01J5', 'HU09J2', 'HT05J2', 'HX8CD8', 'HY05J0', 'HX09J3', 'HH20V8', 'HN9CP1', 'HJ09J2', 'HY5F17', 'HT05J6', 'HT09J3', 'HX01J3', 'HU01JX', 'HX02P3', 'HU8CD0', 'HU01J5', 'HJ09J8', 'H1RFV5', 'HN9CP2', 'HU09J5', 'HU01J1', 'HU09J8', 'HP10V2', 'HX02P9', 'HY5F10', 'HX05J0', 'HX09J8', 'HY05J9', 'HX05J1', 'HU8CD1', 'HU01J6', 'H1RFV7', 'HU01J8', 'HU01J0', 'HJ09J0', 'HJ01J9', 'HN9CP9', 'HH20V7', 'HT09J0', 'HP10V5', 'HD20V4', 'HX01J4', 'HH20V9', 'HH20V0', 'HX8CD1', 'HU01J2', 'HP10V4', 'HX09JX', 'HX01J1', 'HJ0932', 'HN9CPO', 'H1RFV6', 'HU01J7', 'HD20V0', 'HT09J1', 'HN9CP7', 'H4ACP0', 'HU01J3', 'HU09J3', 'HU0935', 'HX09J0', 'HX05J8', 'HX01JO', 'HN9CP6', 'HP10V6', 'HX05J5', 'HJ01J5', 'HY5F19', 'HD20V3', 'HX01J6', 'HJ0939', 'HY05JO', 'HV01J3', 'H009J1', 'HN9CP8', 'HY03JX', 'HH20V6', 'HP10V3', 'HXHX01', 'HJ01J3', 'HT0937', 'HY0518', 'HX8CDO', 'HN9CP3', 'HZRBH1', 'HTOSJX', 'HP10V8', 'HH20V2', 'HP10V7', 'HX02PS', 'HY5F18', 'H1RFV3', 'HU0932', 'HN9CP5', 'HU8CD4', 'HJ01J8', 'HJ01J7', 'HU01J9', 'HY5F14', 'HW5F13', 'H1RFV9', 'HP10V9', 'HY5F13', 'H4BCP3', 'HY5F11', 'HU0938', 'HW5F1X', 'HD20V8', 'H1RFVX', 'HY02J9', 'HT0537', 'HP10V0', 'HX8CD9', 'HB8CD2', 'HD20V6', 'HN9CPX', 'HW5F16', 'HY02J0', 'HW5F14', 'HJ01J6', 'HY5F15', 'HW5F18', 'HP10VX', 'HTO5J6', 'HN86R7', 'HJ01JX', 'HB9CP5', 'HXO2PX', 'HV01J2', 'HY02J7', 'HU0936', 'HJ01J2', 'HY5F16', 'HY0SJ5', 'HJ59J1', 'HW5F11', 'HH20V3', 'HY7AJ3', 'HW5F19', 'HR33NX', 'HJ01J0', 'HV09J8', 'HU8CD7', 'HN9CP0', 'HJ01J4', 'HY5F12', 'HPRAE2', 'HN86R1', 'HD20V9', 'HTO5J1', 'H1RFV1', 'HU8CD3', 'HV09J2', 'HNP6N3', 'HV09J0', 'HN87R7', 'H1RFV8', 'H1RFV4', 'HJ85J4', 'HV01J4', 'HB9CP1', 'HX0937', 'HY02J2', 'HT0530', 'HJO9J0', 'HV09JX', 'HZ14S6', 'HAP53E', 'HS02P6', 'HU8CD6', 'HU01JO', 'HT0934', 'H1RFV0', 'HP10V1', 'HY02J6', 'HTO5J9', 'HD17F2', 'HY02J5', 'HN86R5', 'HJ0915', 'HT05JO', 'HU0939', 'H109J9', 'HX0936', 'HD23S2', 'HAP5J1', 'HN9CP4', 'HT0535', 'HX0SJS', 'HY0515', 'HY02J1', 'HU0930', 'HPRAEX', 'HX09JO', 'HV01J9', 'HT0533', 'HT0SJ3', 'HV01J5', 'HV01J0', 'HN86R8', 'HJ0934', 'HV09J3', 'HU8CDX', 'HD20VX', 'HW5F17', 'HT5236', 'HX05JO', 'HU5JR1', 'HN9CPI', 'HW2ZZ4', 'HNW6NK', 'HJ0931', 'HX0931', 'HJ0938', 'HD20V1', 'HPRAE1', 'HY5F1X', 'HB9CP2', 'HY02J4', 'HXO1J1', 'HV01J1', 'HXO9J8', 'HX0IJ3', 'HY02J3', 'H1RFV2', 'HN86RX', 'HT06J3', 'HT0539', 'HXD2P9', 'HG17C8', 'H00936', 'HV01J6', 'HV01J7', 'HG17CX', 'HNICPO', 'HU09JO', 'HW21A0', 'HV01JX', 'HD17FP', 'HTO5J4', 'HJ85J3', 'HJ0937', 'HB10V4', 'HN87R1', 'HS02P8', 'H25ZZZ', 'HTO5J5', 'HX0139', 'HEJ1F0', 'HV09J1', 'HT0514', 'HJXEN7', 'HTO5J3', 'HZ04S2', 'HT0512', 'HU0937', 'HX02J2', 'HB8CD9', 'HX0934', 'HJ85J2', 'HX02PI', 'HZRBH0', 'HPRAE8', 'HXO2P7', 'HD17F6', 'HJ0935', 'HUD9J8', 'HD20V7', 'HW5F12', 'HF10U7', 'HT0518', 'HY0SJ8', 'HU8CD2', 'HB8CD5', 'HXBCDB', 'HT09JO', 'HN87R5', 'HD17F9', 'HD17FX', 'HD20V2', 'HJ0912', 'HY0532', 'HX0131', 'HU08J0', 'HB8CD3', 'HJO9J4', 'HB9CP8', 'HPRAE0', 'HJ0933', 'HDAAA1', 'HU0933', 'H009J3', 'HJ0919', 'HN87R3', 'HX0935', 'H4ACP2', 'HY7AJ4', 'HG39K3', 'HT0SJ0', 'H009JX', 'HD17F5', 'HNP13W', 'HT09JL', 'HB8CD6', 'HX0919', 'HV09J7', 'H009J6', 'HYOSJS', 'HU0931', 'HU09JI', 'HT05JI', 'HU8CD9', 'HYO5JX', 'HTO5J0', 'HJ85J5', 'HD21A8', 'HJ05J6', 'HJ0SJ9', 'HN86R3', 'HXO2P6', 'HT0935', 'HX02PB', 'HT0538', 'HT0531', 'H30934', 'HY0535', 'HX02PU', 'HU0912', 'HJQ8JS', 'HJ08J1', 'HAP732', 'HU0917', 'HU0914', 'HAP53C', 'HT05JB', 'HY7AJ6', 'HW2ZZ3', 'HY0534', 'H545G5', 'HN86R2', 'HUD3J2', 'HXQ2P9', 'HS02PX', 'HXO2P1', 'H309JX', 'HY0531', 'HX02J8', 'HJO9J9', 'HT0938', 'HXO2P0', 'HXO2PG', 'HX07P1', 'HJ85JX', 'HXO2P9', 'HG09G2', 'HY7AJX', 'HU8CD8', 'HY0533', 'HUD9J6', 'HV09J9', 'HYO5J3', 'HU8CD5', 'HT0534', 'HY7AJ0', 'HV01J8', 'HUOTJI', 'HT0536', 'HY05I1', 'HJ08J8', 'HV09J6', 'HD17F1', 'HX0939', 'HS02P3', 'HJ85J0', 'HTO5J2', 'HPRAE5', 'HY0S0S', 'HJ08J9', 'HT0SJ2', 'HJ85J6', 'HTO5J7', 'HU0919', 'HG17C1', 'HTOSJ3', 'HY7AJ5']
  Model_Year: ['F', 'A', '5', 'N', 'E', '6', '9', 'G', 'L', '2', 'B', 'H', '4', 'Y', 'J', '3', '7', 'D', 'C', 'K', '8', 'M', 'X', '1', 'P', 'S', 'T', 'R', 'W', 'V']
  Plant_Code: ['0', '5', '4', '2', '6', '1', '8', '7', 'X', 'C', '3', 'B', 'W', 'D', 'S', '9', 'J', 'P', 'K', 'G', 'M', 'O', 'A']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,H,GLX,GCC,4.0,JTF,HX02PO,F,0,099797
1,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,H,DX,GCC,4.0,JTF,HX02P7,F,0,094323
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DL,GCC,4.0,JTF,HXDGP7,F,0,094373
3,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTM,HT09J7,A,5,049335
4,TOYOTA,RAV4,4.0,SUV,H,FABRIC,GCC,5.0,JTE,HD20V5,5,0,062401
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31711,TOYOTA,LAND CRUISER,8.0,SUV,H,VXR,GCC,NaN,JTM,HY05J0,M,4,095767
31712,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTM,HT09J6,9,5,038189
31713,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTM,HT09J0,A,5,079700
31714,TOYOTA,HILUX,6.0,PICKUP,H,GLX,GCC,NaN,MR0,HU8CDX,K,0,071134
31715,TOYOTA,LAND CRUISER,8.0,SUV,H,GXR,GCC,NaN,JTM,HX01J3,M,4,222343

====================================================================================================
POS4: E
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'COROLLA', 'RUSH', 'TUNDRA', 'FJ CRUISER', 'CAMRY', 'RAV4', 'LAND CRUISER 70', 'LAND CRUISER', 'كامري', 'YARIS', 'HIGHLANDER', 'COROLLA CROSS', 'URBAN CRUISER', 'PRADO', 'SCION', 'HIACE', 'SUPRA', 'FORTUNER', 'ECHO', 'SEQUOIA', 'COROLLA 1.8', '4RUNNER', 'NIO ES8', 'TOYOTA RUSH', 'SIENNA', 'LAND CRUISER PICK UP', 'CAMRY HYBRID']
  bodyType: ['PICK UP SINGLE CAB', 'SEDAN', 'SUV', 'PICK UP DOUBLE CAB', 'SALOON', 'PICK UP', 'ESTATE', 'PICKUP', 'HATCHBACK', 'SUV- CROSSOVER', 'VAN', 'STATION', 'PANEL VAN', 'MINI BUS HIGH ROOF', 'COUPE', 'PICKUP DOUBLE CABIN', 'MPV']
  pos4: ['E']
  trim: ['DLX', 'XLI MID', 'EX', 'XLI', 'STD (NON GCC)', 'EXTREME', 'GX', 'GLI', 'LE HEV', 'BASE', 'LE', 'STD', 'DLX TOP', 'HT SWB', 'GLS', 'GL', 'GLI TOP LTH', 'XLI TOP', 'GLI TOP', 'XLE (NON GCC)', 'XLI EXECUTIVE', 'SE+', 'HT VXR', 'GLI HEV', 'S', 'SR', 'VX', 'GXR TOP 60TH ANNIV. XTREME', 'SL', 'HYBRID (NON GCC)', 'GLX', 'PLATINUM', 'GXR', 'GLE', 'VXR', 'GLE HEV', 'MID', 'E', 'EXR', 'SE', 'GL2', 'GR BLUE EDITION', 'XLE', 'SPORT', 'DLS', '1', 'XLE HEV', 'ADVENTURE', 'LIMITED', 'LE (NON GCC)', 'LX AC PWR OPT', 'YA', 'TOP']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MR0', 'JTD', 'MHK', 'MRO', 'JTF', '5TF', '6T1', '5YF', '4T3', 'JT4', 'JTE', 'JT2', '2T3', '5TB', 'JTG', 'LVG', 'RKL', '7MU', 'JTM', 'MZB', '5TD', 'MMM', '2GC', '4T1', '1FT', 'JTB', 'MHF', 'WME', 'LCO', 'JTZ', 'LPS', 'VR3', 'L3H', 'MC1', 'JN1', 'MPA', 'STF', '1N6', 'JTN', 'J1D', 'MRD', 'LS6', 'LGJ', 'SAL', 'LJ1', 'MMB', 'YSM', 'JT0', '3GN', 'MR2']
  VDS: ['EW12G0', 'ER23E0', 'EF8BF4', 'EF8BF2', 'EX12G5', 'EF8BF5', 'EX12GX', 'EX19G3', 'EF8BF8', 'EW23E2', 'ER23EX', 'EG4265', 'EF8BF3', 'ER23E2', 'EW5F19', 'EX19G8', 'EX19GX', 'EG22K1', 'EX12G2', 'EG22K5', 'EW23E9', 'EF8CF1', 'EW12G5', 'EF8CF7', 'EX12G4', 'EX19G0', 'EW23E4', 'EPMAE0', 'EX12G0', 'EF8BF1', 'E6RFV0', 'EF8BF9', 'EW12G6', 'EW23E0', 'EX12G6', 'EX19G4', 'ER23E4', 'EPRAE9', 'EF8BFX', 'EX19G1', 'EG4261', 'EU73J6', 'EG4264', 'EX12G8', 'EG22K8', 'EX19G6', 'EM4963', 'ER23E8', 'EF8CF2', 'EX12G7', 'EZ4261', 'EW23E7', 'EG4260', 'EW12G1', 'EG23K8', 'EM4260', 'EW23E8', 'EG4263', 'EG4269', 'EW23E1', 'ER23E7', 'EW12G3', 'EX12G9', 'EW12G9', 'EAMDE4', 'EW12G8', 'ER23E6', 'EF8CFX', 'EF8CF8', 'EF8BF7', 'EW12GX', 'EX19G2', 'ER23E9', 'ER23E5', 'EG22K3', 'EF8BF6', 'EX12G1', 'EG22K9', 'EF8BF0', 'EPRAE5', 'EW23E5', 'EZ4969', 'EG22K6', 'EX1269', 'EPRAE8', 'EPMAE2', 'EW12G7', 'EG4267', 'EW23E3', 'EG23K3', 'ER23E1', 'EX19G7', 'EB13E1', 'E6RFVX', 'EX12G3', 'ER23E3', 'EPRAEX', 'EBRBE3', 'EG22K0', 'EF8CF3', 'EG22K7', 'EF8CF4', 'EW23EX', 'EPMAE4', 'EM4261', 'EF8CF9', 'EG22K2', 'EFHCF1', 'EPRAE7', 'EW12G2', 'EBRBE1', 'EW12G4', 'EX19G9', 'EF8BFO', 'EG4268', 'ET3419', 'EM4966', 'EF8CF0', 'EU73J2', 'EM496X', 'EM4269', 'ES12G0', 'EM4969', 'EG22KX', 'EM4964', 'EPMAE3', 'EW23E6', 'EG22K4', 'EW12GO', 'EM4965', 'EM4264', 'EJ13EX', 'EX1266', 'EM4268', 'EF9FK8', 'EPMAE7', 'EF8CF6', 'EM4968', 'EG426X', 'EF8BFZ', 'EWRFV7', 'EPRAE1', 'EF8CF5', 'EJ13E8', 'ES12G6', 'EPMAE1', 'EPMAEX', 'EB73J5', 'EB73J9', 'EX19G5', 'EU73J5', 'EM4961', 'EV5418', 'EBRBE7', 'EPMAE5', 'EM4960', 'EPRAE4', 'EX1268', 'EW5F15', 'EJ13E3', 'EPRAE6', 'EG23K5', 'EZ4967', 'EZ4963', 'EW9236', 'EY5F11', 'EX1263', 'EZ4962', 'EY5F1X', 'ES46A1', 'EM4266', 'EBOBEO', 'EB0BE0', 'EAAAGX', 'EG23K9', 'EW21A5', 'EAMDE0', 'EAMDEX', 'EB02E2', 'EZ4267', 'ET3417', 'EPRAE3', 'E6RFV4', 'EPRAE2', 'EW41A7', 'E2815A', 'EZ4966', 'EB71J9', 'ES12G8', 'EBRCH5', 'EG4258', 'EBRBE4', 'EB13EX', 'EF8BFI', 'EX1209', 'EBRBE5', 'EG4262', 'EU73JX', 'EBRBE2', 'EL33P9', 'EJ13E5', 'EF88F5', 'EX1261', 'EK19T1', 'EF8CFO', 'EPMAE8', 'EF12K3', 'EWIE58', 'EZ4269', 'EM4267', 'EB73J4', 'EJ13E2', 'EV5415', 'EW44A6', 'EM4263', 'EB02E1', 'EZ4960', 'EC42E3', 'EB13E5', 'EB13E3', 'EPMAE6', 'EX1265', 'EM4265', 'EY5F16', 'EU11F1', 'EF76A0', 'EG4266', 'EV5411', 'EE4263', 'EM4967', 'EFBBF7', 'EZ42E9', 'EU73J0', 'ES41A2', 'EX1969', 'EY5F12', 'EW1261', 'EW44A1', 'EZ4964', 'EW1265', 'E29F37', 'ES12G5', 'EK31X6', 'EPMAE9', 'EPRAE0', 'EJ5CDX', 'EV73JX', 'EB13E4', 'ED3KA5', 'EX1E63', 'ES12GX', 'E1NFJX', 'EAMDE3', 'EW5F11', 'ET9F33', 'ET9231', 'ES12G1', 'EX22G0', 'EE4261', 'EW1260', 'ECABA0', 'ER22E1', 'EJ13E7', 'EB13E0', 'ER42E2', 'EG21K3', 'EM5F18', 'EAMDE7', 'ED9HP2', 'EZ4968', 'ES12G7', 'EJ13E6', 'EF88F2', 'EY5F19', 'EW1266', 'E4FDB8', 'EJ13E0', 'EM5F14', 'EB02E3', 'EE4260', 'EM4962', 'EBRBEX', 'E6RFV9', 'ET3413', 'EM4262', 'EPRAES', 'EF88F0', 'EW44A3', 'E6RFV3', 'EJ13E4', 'EF9FK1', 'EX1964', 'ES43A6', 'EPRAEO', 'EX1267', 'EX1262', 'EW1EP2', 'EAMDE2', 'EBRBE8', 'EZ496X', 'ES12G3', 'EG23KX', 'EF76A1', 'ET3416', 'EB13E7', 'EN61S2', 'ES12G9', 'EAMDE6', 'EZ4965', 'ER33P0', 'EU11F0', 'EG23K2', 'EFBCF8', 'EM42G3', 'EAMDE8', 'EY64A4', 'EF8CFS', 'EM426X', 'ED1EK2', 'ER22E6', 'EFBCF1', 'EAMDE1', 'EWRFV1', 'E6RFV6', 'ET3410', 'ET3418', 'EZ4961', 'EB13E8', 'EFBBF4', 'EW22E6', 'EX126X', 'EF4HKD', 'EDABB3', 'EBRBE6', 'EF9FK7', 'EFSBF6', 'EF9FK6', 'EC42E5', 'EE9HE6', 'EV73J1', 'EF12K7', 'EFBBF5', 'EG12K0', 'EV5819', 'EY5F15', 'EF88F3', 'EG12K5', 'EX12GO', 'EFABF0', 'EX1963', 'EM5F1X', 'ENE0R2', 'EM5F13', 'ET3815', 'EX1965', 'ET3411', 'EM5F10', 'EF8BFS', 'EGCBB3', 'ET9F32', 'EK12G8', 'EY5F14', 'EJ13E1', 'EU3FJ1', 'EW923X', 'E1EE03', 'ET3816', 'EX1260', 'EA6BX2', 'EU5JR1', 'EAMDE9', 'E6A3U3', 'ENKA50', 'EDABB8', 'EFAVS3', 'EE32K0', 'EF88F7', 'EX91G3', 'EW5F10', 'EZ4262', 'EF88F9', 'EX22G4', 'ES12G4', 'EW21A3', 'EV5815', 'EBRBEB', 'EK12TX', 'EY5F13', 'EFSBF9', 'EPMAEO', 'ES43A8', 'E29F3E', 'ET3412', 'EW44A8', 'EJ13E9', 'EX22G1', 'EG23K0', 'EZ3DC6', 'EFBBF3', 'ET3817', 'EFBC38', 'EW1268', 'EG23K6', 'ER42E9', 'EE32KX', 'EE4269', 'EX22G8', 'EF8C31', 'EV5419', 'EU73J9', 'ET9F36', 'ED31V4', 'EAMDE5', 'EB13E6', 'EBRCHX', 'ES12G2', 'EM5F19']
  Model_Year: ['8', '6', 'P', 'B', '7', 'M', '3', '1', 'L', 'H', 'D', '9', 'Y', 'A', '2', 'N', 'E', 'K', '5', 'C', '4', 'X', 'F', 'T', 'S', 'G', 'R', 'J']
  Plant_Code: ['3', 'K', '2', '0', 'X', 'P', 'U', '4', 'J', 'W', 'S', 'F', '9', '1', 'G', 'V', 'E', 'H', '7', 'L', '6', 'A', 'N', '5', 'M', 'D']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,E,DLX,GCC,2.0,MR0,EW12G0,8,3,009992
1,TOYOTA,COROLLA,4.0,SEDAN,E,XLI MID,GCC,4.0,JTD,ER23E0,6,3,187410
2,TOYOTA,RUSH,4.0,SUV,E,EX,GCC,5.0,MHK,EF8BF4,P,K,035407
3,TOYOTA,RUSH,4.0,SUV,E,EX,GCC,5.0,MHK,EF8BF2,P,K,050133
4,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,E,DLX,GCC,4.0,MR0,EX12G5,B,2,049320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8310,TOYOTA,HILUX,4.0,PICKUP,E,DLX,GCC,NaN,MR0,EX19G2,8,3,409698
8311,TOYOTA,RUSH,4.0,SUV,E,EX,GCC,NaN,MHK,EF8BF0,N,K,026216
8312,TOYOTA,COROLLA,4.0,SEDAN,E,XLI,GCC,NaN,JTD,ER23E2,5,0,181656
8313,TOYOTA,HILUX,4.0,PICKUP,E,1,GCC,NaN,JTF,EM4266,4,0,136343
8314,TOYOTA,HILUX,4.0,PICKUP,E,1,GCC,NaN,MR0,EX12G3,B,2,053186

====================================================================================================
POS4: C
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'TACOMA', 'PRADO', 'COROLLA CROSS', 'CAMRY', 'SOLARA', 'INNOVA', 'RAV4', 'HIGHLANDER', 'TUNDRA', 'LAND CRUISER', 'FORTUNER', 'COROLLA', 'HIACE', 'COASTER', 'YARIS', 'TAKOMA', 'HILUX RE', 'TOYOTA', 'FRONTLANDER', 'YARIS HATCHBACK', '2024', 'SIENNA', 'CAMRY HYBRID', 'LAND CRUISER PRADO', 'AVALON']
  bodyType: ['PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'SUV', 'SUV- CROSSOVER', 'SEDAN', 'CONVERTIBLE', 'MPV', 'PICK UP', 'PANEL VAN', 'BUS', 'PICKUP', 'COUPE', 'PICKUP SINGLE CABIN', 'MINI BUS HIGH ROOF', 'HATCHBACK', 'SALOON', 'PICKUP DOUBLE CAB', 'PICKUP DOUBLE CABIN', 'STATION', 'PICK-UP']
  pos4: ['C']
  trim: ['GL', 'GL2', 'DLX', 'DLX TOP', 'GLX', 'SR5 (NON GCC)', 'GXR', 'GLS', 'LE', 'STD (NON GCC)', 'STD', 'LE HEV', 'SE', 'SGLX', 'EX', 'TX-L', 'DL', 'VXR', 'TRD', 'VX2', 'XLI', 'SE+', 'DX', 'TX-L TOP', 'SR', 'BUS', 'TX', 'XL', 'E', 'DLS', 'GLE-X HEV 40TH ANNIV', 'GRANDE HEV 40TH ANNIV', 'ADVENTURE', 'LIMITED', 'GRANDE', 'HEV', 'GLI', 'XLI TOP', 'VX', 'GF', 'XLE', 'XLE (NON GCC)', 'EXR', 'GX', 'S', 'GLE HEV', 'GXR TOP', 'GLI HEV', 'PICK UP', 'GLE', 'A', 'BASE', 'XLE HEV', 'LXI', 'CAR TRIM', 'GL TOP', '1500', 'EX MID', '60TH', 'XSE', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MR0', 'MRO', '3TM', 'JTE', '7MU', '4T1', 'LFM', '5TF', 'MHF', '2T3', 'LVG', 'SJK', 'JTM', '4TI', '3TY', 'LXG', 'JTG', 'LGW', 'LVA', 'LZW', '2GN', 'JTN', '2T1', 'LC0', 'JH4', 'RKM', 'KL1', 'LA9', 'JN1', '5TD', 'LHG', 'JHM', 'ZCF', 'JNK', '1HG', 'KNM', 'MRC']
  VDS: ['CW6CB9', 'CX9CB1', 'CW12G0', 'CW12G8', 'CX19GX', 'CW12G4', 'CX9CB0', 'CX9CDO', 'CX19G8', 'CX9CD4', 'CZ5AN5', 'CX8CD6', 'CX19G7', 'CX12G5', 'CX19G4', 'CX9CB6', 'CW6CD1', 'CX3FJ4', 'CAAAGO', 'CW9CDX', 'CX12G7', 'CAAAG0', 'CX19G0', 'C11AK2', 'CU1BR6', 'CZ5AN1', 'CX9CB7', 'CX19G5', 'CW12G1', 'CX6CB3', 'CA30P2', 'CX3FJ9', 'CX8CB9', 'CW12G5', 'CX12G4', 'CW12G7', 'CX9CB5', 'CX9CD8', 'CX8EM1', 'CW12G6', 'C11AK1', 'C1RFV8', 'CX12G8', 'CX12G1', 'C916Z7', 'CX8EM5', 'CX9CB8', 'CX12GX', 'CW12G3', 'CX8EM3', 'CAABG0', 'CX9CB2', 'CX9CDX', 'CH5CP0', 'CX8EM9', 'CX19G1', 'CX9CB9', 'CW12G2', 'CAAAG7', 'CX8EMO', 'CX12G9', 'CX3FJX', 'CX9FJ8', 'CX12G6', 'CZ5AN4', 'CX3FJ3', 'CX8EM0', 'CX9CBX', 'CX19G9', 'CX12G0', 'CX9CD9', 'CX6CBX', 'CX3FJ0', 'CY5F16', 'CU1BR1', 'CX8EM8', 'CX8EM7', 'CX8CD3', 'CX19G6', 'CX8EMX', 'CX9CD6', 'CX9CD5', 'CX8EM4', 'CZ5AN8', 'CX8EM6', 'CX3FJ5', 'CX9CB4', 'C11AK0', 'CY7AJ4', 'CW8CD9', 'CX19G2', 'CW1262', 'CW12G9', 'CX8EM2', 'CX6CD9', 'CW12GX', 'CX9FJ6', 'CX6CB4', 'CX6CD8', 'CX3FJ2', 'CX8GS9', 'CX6CB7', 'CX12G3', 'CY7AJ8', 'CW1260', 'CX12G2', 'CX6CDX', 'CX3FJ8', 'CX9CD3', 'CW6CB5', 'CX19G3', 'CW6CD6', 'CE38P0', 'CX8CB5', 'C618X8', 'CX9CD1', 'CPA509', 'CW6CB7', 'CW6CB3', 'CX9CD2', 'CX9FJ7', 'CX8CB6', 'CW6CB1', 'CU1BR0', 'CX9FJ1', 'CX8CD8', 'C11AK5', 'CECB89', 'CX9FJ0', 'CX6CB6', 'CW6CD8', 'CX9CB3', 'CW8CB7', 'CA2174', 'CU1BR4', 'CX3FJ1', 'CU1BRX', 'CW8CB3', 'CK12G4', 'CY7AJ2', 'CU1BR3', 'CX9CD0', 'CX6CB0', 'CX8CD9', 'CJE237', 'CW6CB4', 'CX9FJ5', 'CZ5AN3', 'CX6CD6', 'CGE234', 'C11AKX', 'CX8CB1', 'CX1267', 'CX8CD5', 'CX8CB0', 'C11BK9', 'C2ZWB5', 'C31AK2', 'CX3FJ7', 'CAABG9', 'CBAGA2', 'CW1265', 'CW1263', 'CX8CD1', 'CAAGAX', 'C11AK8', 'CX9FJ2', 'CX8CBX', 'CX8CB8', 'CX6CD2', 'C916Z4', 'C11AK9', 'C11AK6', 'CX8CB3', 'CW8CD7', 'CU1BR2', 'CX9FJ9', 'CX6CD4', 'CS12G7', 'CX3FJ6', 'CECB85', 'CU1BR5', 'CW6CD3', 'CX6CD0', 'CX8GS6', 'CC1BR5', 'CS12G8', 'CW6CD5', 'CZ5AN9', 'CW8CB9', 'C2ZWB0', 'C8E2H4', 'CW8CDX', 'CX1263', 'CS18Z3', 'CX9CD7', 'CX9FJ4', 'C4RBE1', 'CU09JX', 'C11AK7', 'CF28P3', 'CX1966', 'CXBEM0', 'CU1BR9', 'CU1BR8', 'CZ5AN7', 'CW6CD0', 'CW8CB0', 'CV5414', 'CW6C88', 'C74C40', 'CW6CB8', 'CW6CDO', 'CX6CB1', 'CZ5AN6', 'CS12G4', 'C4MBE1', 'C11AK3', 'CX6CD5', 'CX8CD0', 'CW8CD2', 'CL9683', 'CAABG8', 'CX8CD4', 'C31AK6', 'CC1BR7', 'CZ5ANX', 'CE38P9', 'CX8CD2', 'CC1BR0', 'CX6CD7', 'CAABGX', 'CJE735', 'CV5412', 'C4RBE6', 'CY5F14', 'CAABG1', 'CX8CB4', 'CW8CB6', 'CX6CD1', 'C31AK7', 'C1RFV7', 'CX8CDX', 'CB09J3', 'CW9CD6', 'CY7AJ9', 'C11AK4', 'CY7AJ3', 'CBAGA6', 'CW6CD2', 'CX6CB9', 'C11AKO', 'CGE231', 'C1RFVX', 'CX6CD3', 'C2ZWB6', 'CW12GO', 'CA38P8', 'CW1269', 'CU1BR7', 'CZ5ANO', 'CZ5AN0', 'CW6CB0', 'CX1266', 'CC1BR9', 'CAAAG3', 'CW6CB6', 'C916Z0', 'CW6CD7', 'CU09J7', 'C916ZO', 'CW1261', 'CY7AJ0', 'CX1265', 'CB09J1', 'CC1BR6', 'CX8CB2', 'C916Z9', 'C11AKS', 'CV5416', 'CB3FV8', 'CX8CD7', 'C11BK0', 'C1RFV5', 'CIRFV7', 'C31AK3', 'CX9FJ3', 'CX1264', 'C616Z8', 'CP7241', 'CX8CB7', 'CW6CB2', 'C2ZWB9', 'CW8CD4', 'CB09J2', 'CW8CB8', 'CX12GO', 'CX6CB2', 'CECB81', 'CW8CB4', 'CP5154', 'CP5156', 'C916Z6', 'CW6CD9', 'C4MBE4', 'CV5417', 'CW9CD5', 'CX6CB8', 'CW8CB5', 'CZ5AN2', 'CJ6B15', 'C1RFV1', 'CW6CBX', 'CB3377', 'CB3379', 'CW8C86', 'CW9CB8', 'CX8GS0', 'C916Z8', 'CW6C86', 'CY5F13', 'CX8C80', 'CAAAGX', 'CX8GS5', 'CF22PX', 'CA2171', 'CY7AJ6', 'CY7AJ5', 'CS12G5', 'C31AK8', 'CX9CBO', 'CW8CB1', 'C08RW6', 'CX9C88', 'CC13C6', 'C1RFV2', 'CX1261', 'CV5415', 'CF28P8', 'CW8CBX', 'CW5F12', 'CW1267', 'CY7AJ1', 'C1RFV0', 'CZRAH7', 'CC1BR2', 'C916ZX', 'CX1268', 'CW6CDX', 'C31AK4', 'CC1BR8', 'CG12K9', 'CP4500', 'CE38P1', 'CV5418', 'CM5657', 'CC1BR4', 'CAABGO', 'CV12G9', 'CAABG7', 'CW1264', 'C25AN3', 'CW6CBO', 'CW126X', 'CB09JX', 'CW1268', 'CA50A0', 'CW8BB9', 'CJE232', 'CA31A7', 'CU9237', 'CA21A7', 'CY5F18', 'CX1904', 'CC1CX2', 'CA30P7', 'CX8EMI', 'C31AK5', 'CW8CD0', 'CA38P9', 'CV1F40', 'CW6CD4', 'CW9CB2', 'CU18R8', 'CX1269', 'CX126X', 'CJE235', 'CC42H9', 'CX8GS2', 'CY5F11', 'C31AKX', 'CX9CBI', 'CV5411', 'CY5F17', 'C4MBEX', 'C1RFV9', 'CXI9G4', 'CU09J8', 'CY5F19', 'CE22P4', 'CAAAG5', 'CW8CB2', 'CW5F1X', 'CECB82', 'CW8CD6', 'CW9CB4', 'CV52B4', 'CW5F17', 'CX19GO', 'CU09J5', 'CV541X', 'C11BK2', 'CC1BR3', 'CZRAH0', 'CX8GSX', 'CW8CD1', 'C616ZX', 'CW5F14', 'CV5410', 'CY5F10', 'CX0CD4', 'CW1266', 'CX3DD5', 'CJE234', 'CX190X', 'CY5F12', 'CRKEC4', 'CJE730', 'CB09J7', 'C11BK7', 'C21FB1']
  Model_Year: ['G', 'P', '9', 'E', 'F', 'N', 'B', 'M', 'L', 'J', '6', 'S', 'A', 'K', '8', 'H', '7', 'R', 'D', 'C', 'T', 'Y', '4', '5', '1', '3', '2']
  Plant_Code: ['0', '3', '2', '4', 'M', '5', 'V', '1', 'U', 'X', 'W', 'G', 'A', 'T', '6', 'B', 'S', 'C', 'D', 'J', 'Y', 'K', 'P', 'O']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,GL,GCC,4.0,MR0,CW6CB9,G,0,001803
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,GL2,GCC,4.0,MR0,CX9CB1,P,3,962120
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,DLX,GCC,4.0,MR0,CW12G0,9,0,014345
3,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,C,DLX TOP,GCC,2.0,MR0,CW12G8,E,0,033400
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,C,DLX,GCC,2.0,MR0,CX19GX,9,2,603118
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4669,TOYOTA,TACOMA,6.0,PICKUP,C,SR5 (NON GCC),NON-GCC,NaN,3TM,CZ5AN7,H,M,079346
4670,TOYOTA,HILUX,4.0,PICKUP,C,DLX TOP,GCC,NaN,MR0,CW12G7,D,0,029031
4671,TOYOTA,HILUX,4.0,PICKUP,C,1,GCC,NaN,MR0,CX12G1,A,0,057366
4672,TOYOTA,TACOMA,6.0,PICKUP,C,SR5 (NON GCC),NON-GCC,NaN,3TM,CZ5AN9,K,M,257507
4673,TOYOTA,LAND CRUISER PRADO,4.0,SUV,C,GXR,GCC,NaN,JTE,CX3FJ6,K,5,007286

====================================================================================================
POS4: P
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'TACOMA', 'TUNDRA', 'RAV4', 'HILUX', 'COROLLA', 'LAND CRUISER PICK UP', 'YARIS', 'CAMRY', 'COASTER', 'SY150T', 'AVALON', 'PRADO', 'TOYOTA HIACE', 'GL770ULTRA', '4RUNNER']
  bodyType: ['PANEL VAN', 'MINI BUS HIGH ROOF', 'VAN', 'MINI BUS', 'PANEL VAN HIGH ROOF', 'PICK UP', 'PICK UP DOUBLE CAB', 'HALF PANEL VAN', 'SUV', 'PICKUP', 'SEDAN', 'BUS', 'CARGO VAN', 'PICKUP TRUCK', 'MOTORCYCLE', 'TRUCK', 'PICK UP SINGLE CAB', 'MPV', 'HATCHBACK', 'MINIVAN']
  pos4: ['P']
  trim: ['GL', 'GLX', 'STD', 'GLS', 'DX', 'STD (NON GCC)', 'DX H/R W/B', 'DL', 'LE HEV', 'DLS', '1794 EDITION (NON GCC)', 'XLI EXECUTIVE', 'LX AC PWR OPT', 'E', 'DLX', 'XLI', 'GLI', 'CREWMAX CAPSTONE (NON GCC)', 'LWB', 'DLS - STD ROOF', 'XLE', 'SE', 'VX', 'SE+', 'S ASF', 'S', 'SS', 'LWB HIGH ROOF', 'TOP', 'MID', 'A', 'BASE', 'YA', 'EXR', 'GLI TOP', '1', 'X', 'GLE', 'CTD', 'ST', 'XLE (NON GCC)', 'GLI HEV', 'PICK', 'LIMITED', 'TRD', '1794 EDITION (NON GC', 'CREWMAX CAPSTONE (NO']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTF', '5TE', '5TF', 'JTV', '2T3', '1GC', 'JTE', 'MB1', '5YF', 'RA6', '4TA', '9BS', '6T1', 'JTM', 'MHF', 'MLH', 'KLA', 'JTD', 'LK1', 'WBA', 'MBI', 'MC2', 'STF', 'LHG', 'RKL', 'LBB', 'HJR', '4T1']
  VDS: ['PX22P7', 'PX22P6', 'PX22P8', 'PX22P0', 'PX22PX', 'PX22P4', 'PX22P1', 'PX22P3', 'PX22P9', 'PX22P2', 'PX22P5', 'PX42N6', 'PY5F19', 'P1RFVX', 'PTDEK3', 'PX22PO', 'PC5DB9', 'PBEJA1', 'P4RCE7', 'PW5F13', 'PX4EN2', 'PAEHD1', 'PM62NX', 'P1RFV3', 'P1RFV1', 'PX42N3', 'P6X400', 'PAEHD5', 'PE32K6', 'PC5DB8', 'PG34L5', 'PBEJA3', 'PT9F39', 'PX4EN3', 'PX4EN6', 'P1RFV7', 'PBEJA5', 'PC5DB0', 'PY5F17', 'P1RFV8', 'PC5691', 'PM62N2', 'PA69JD', 'PY5F11', 'PM62N7', 'P4RCE3', 'PCKL98', 'PAAWA2', 'PX22PI', 'PY5F13', 'PM62N3', 'PBEJA0', 'PW5F10', 'PY5F16', 'PBAJA9', 'P1RFV0', 'PX4EN0', 'P1RFV6', 'PBAJA1', 'PBEJA4', 'PY5F14', 'PY5F10', 'PC5DB6', 'P1RFV5', 'PBEHD5', 'PY22P6', 'PBEFD5', 'PM62N1', 'PX4ENX', 'PC5DB7', 'PK5C54', 'PBEJA6', 'PC5DB1', 'PY5F12', 'PBEFA6', 'PG34L8', 'P1HLT8', 'PM62N4', 'P4RCE4', 'PM62N8', 'PC5DB2', 'PX42N5', 'P1RFV9', 'P4MCE1', 'PLM90S', 'PH5C57', 'PX4EN8', 'P4MCE8', 'PAAWA5', 'PX4EN5', 'PBEWA6', 'PV42E2', 'PBEHD9', 'P1RFV2', 'PC5DB5', 'PBAJA7', 'PCKL9X', 'PBEFA8', 'P4RCE0', 'PBEJAX', 'PBEJA8', 'P4RCE1', 'PX42N2', 'PAEHD8', 'PX42N4', 'P99006', 'PY5F18', 'PBGJB2', 'PE30K1', 'PM62N5', 'P4MCE7', 'P4RCE9', 'PM62N0', 'PC5DB4', 'PW9236', 'PU5JR6', 'P4MCE6', 'PX4EN4', 'PN62N5', 'P4RCE2', 'PY5F1X', 'PU5JRX', 'P1RFV4', 'PU5JR3', 'PX4EN7', 'P4RCEX', 'PX22PZ', 'PBEJA2']
  Model_Year: ['A', 'D', 'F', 'H', 'R', 'E', 'L', 'M', 'C', 'N', 'P', 'J', '8', 'B', 'K', '9', 'G', '7', '6', '5', 'T', 'Y', 'S', '4', '3', '2', 'X', 'W', '1', 'V']
  Plant_Code: ['0', 'Z', 'X', 'C', '1', '2', 'P', 'U', '3', 'J', '6', 'W', '4', 'D', '5', 'B', 'E', 'H', 'A', 'O', '9']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,PANEL VAN,P,GL,GCC,5.0,JTF,PX22P7,A,0,017757
1,TOYOTA,HIACE,4.0,PANEL VAN,P,GL,GCC,5.0,JTF,PX22P6,D,0,037731
2,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,P,GLX,GCC,4.0,JTF,PX22P8,F,0,060916
3,TOYOTA,HIACE,4.0,VAN,P,GLX,GCC,4.0,JTF,PX22P0,H,0,079124
4,TOYOTA,HIACE,4.0,MINI BUS,P,STD,GCC,4.0,JTF,PX22P8,F,0,060141
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3135,TOYOTA,TUNDRA,8.0,PICKUP,P,STD (NON GCC),NON-GCC,NaN,5TF,PY5F19,E,X,387781
3136,TOYOTA,TUNDRA,6.0,PICKUP,P,1794 EDITION (NON GC,NON-GCC,NaN,5TF,PC5DB1,P,X,015204
3137,TOYOTA,TACOMA,4.0,PICKUP,P,STD (NON GCC),NON-GCC,NaN,5TE,PX42N4,9,Z,656676
3138,TOYOTA,TUNDRA,6.0,PICKUP,P,1794 EDITION (NON GC,GCC,NaN,5TF,PC5DB1,P,X,022864
3139,TOYOTA,TUNDRA,6.0,PICKUP,P,CREWMAX CAPSTONE (NO,GCC,NaN,5TF,PC5DB8,R,X,055122

====================================================================================================
POS4: K
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'SIENNA', 'PRIUS', 'HILUX', 'TUNDRA', 'COROLLA CROSS', 'C-HR', 'XA', 'FORTUNER', 'CAMRY', 'COROLLA', 'MATRIX', 'RAV4', 'LAND CRUISER', 'SCION', 'PREVIA', 'SEQUOIA', 'TACOMA', 'OTHERS', 'BZ4X', 'RAV 4', 'COROLLA 1.6', 'COROLLA 1.8', '4RUNNER', 'HIGHLANDER', 'HIACE', 'STATION', 'ECHO', 'GRANVIA', 'هاي لوكس', '25 HX DC 4X4D 2.4LAT', 'TANDRA', '1999', 'SIENNA VAN', 'AVANZA', 'SENA', 'SENA VAN PASSENGER', '2 HX DC 4X40', 'COROLLA SEDAN / HATCH', 'هايلوكس', 'HAI LUX', '26HX DC 4X4D2.4L AT', 'SIENA', '26 HX DC 4X4 2.4LAT', '26HX DC 4X4 D2.4LAT', 'CHR', '26 HX DC 4X4 D 2.4L AT', 'TOYOTA - 26 HX DC 4X4 D 2.4L AT', '25 HX DC 4X4', 'DLX FA (PICK UP)', 'HX DC 4X4 D 2.4L AT', '26 HX DC 4X4D', 'COROLLA 1.5L/HATCHBACK', 'INNOVA', 'TOYOTA COROLLA', 'RUSH', 'TOYOTA COROLLA 1.8', 'COROLLA 1.3', 'SOLARA', 'GXR RA(STATION WAGON)', 'LAND CRUISER SINGLE-CABIN PICK UP', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'MPV', 'HATCHBACK', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'SUV- CROSSOVER', 'SUV', 'PICKUP', 'SALOON', 'VAN', 'STATION', 'PANEL VAN', 'MINI BUS', 'PICK UP', 'MINI BUS HIGH ROOF', 'PICKUP DOUBLE CAB', 'PANEL VAN HIGH ROOF', 'CONVERTIBLE']
  pos4: ['K']
  trim: ['FLEET', 'LE (NON GCC)', 'SE TRD AERO PK', 'ICONIC', 'SE', 'BASE', 'SGLX', 'MID', 'E', 'STD (NON GCC)', 'XLE (NON GCC)', 'GLI', 'TOP', 'VX', 'S', 'LIMITED (NON GCC)', 'GL2', 'EXR', 'XL', 'GLX', 'GXR', 'GLE-X HEV 40TH ANNIV', 'CREWMAX CAPSTONE (NON GCC)', 'STD', 'LE', 'C (NON GCC)', 'DLX', 'ECO', 'VXR', 'STD D', 'LE HEV', 'GL', 'GX', 'EX', 'SE (NON GCC)', 'SPORT', 'VX1', 'VXR BASE', 'DYNAMIC', 'S+', 'STANDARD', 'GLE', 'GLI HEV', 'XLI', 'CE (NON GCC)', 'VX2', 'TC (NON GCC)', 'FABRIC', 'PLATINUM', 'DLS', '1', 'SR5 (NON GCC)', 'PRO', 'GLI TOP', 'GA', 'LIMITED', 'X', 'SE TRD SPORT PK', 'EXI', 'ADVENTURE', 'DL', 'DX', 'XLI MID', 'PREMIUM', 'SLD', 'GLE HEV BLACK EDITION', 'USF', 'XSE (NON GCC)', 'TRD', 'GLE HEV', 'GLS', 'SE+', 'SENA', 'XLI EXECUTIVE', '1794 EDITION (NON GCC)', 'ASD', 'COMFORT', 'TX', 'SU', 'MPV', 'ABC', '1500', 'SED', '2', 'G', 'TRIM', 'HYBRID (NON GCC)', 'GRANDE HEV 40TH ANNIV', 'IM', 'STATION', 'XLI TOP']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTD', '5TD', 'MR2', 'MR0', '5TF', 'RKL', 'NMT', 'MHF', '4T1', 'JTN', 'VNK', '2T1', 'STF', 'LFM', 'MR1', 'JT4', 'JTF', '2T3', 'ME4', 'JTM', '5TB', 'MRO', 'JTK', '3TY', 'JND', 'STD', '3TM', 'JTE', 'KPD', 'STO', 'JTL', 'JTG', 'WDA', 'KL3', 'ZGU', 'LSG', 'AR2', 'MHE', 'MK2', '5TE', '4F4', 'MP2', 'ITD', '1G6', 'MRI', 'JTU', 'L3A']
  VDS: ['KW9239', 'KK3DC1', 'KW9236', 'KT9F38', 'KB3FUO', 'K19F35', 'KW9F31', 'KW9238', 'KB8CD7', 'KB3FU0', 'KW9231', 'KW9232', 'K19F32', 'KW9D38', 'KW923X', 'KY5F19', 'KW9D35', 'KK3DC9', 'KW9D33', 'KW9D34', 'KN3DU2', 'KK3DC2', 'KB8CD0', 'KW9D36', 'KY5F16', 'KZ3DC2', 'KAAAG0', 'KW9D39', 'KW9036', 'KZ4BX5', 'KW9D30', 'KW9234', 'KW9D31', 'KUAAG7', 'KT9F31', 'KT6235', 'KDTB35', 'KAAAG9', 'KK3DC5', 'KW9D3X', 'KB8CD4', 'KU8FSX', 'KW9F32', 'KABAGX', 'KZ4BX7', 'KB8CD2', 'KW9237', 'KCBAG1', 'KT9F30', 'KZ1AK9', 'K19F31', 'KW9235', 'K19F39', 'KW9039', 'K4RBE5', 'KB5DB5', 'KU8FS7', 'KB8CD8', 'K61AK9', 'K19F30', 'KZ4BX3', 'K19F38', 'KK4CC3', 'KN3DU9', 'KK4CC2', 'KN3DU1', 'KY5F17', 'KW9233', 'KW9230', 'KT9236', 'KB8CD3', 'KZ4BX9', 'KZ4BX0', 'KK3DC8', 'KT9F33', 'KY5F1X', 'KZ4BX6', 'KZ4BX8', 'KU8FS8', 'KUAAG6', 'KK4CC5', 'KN3DU3', 'KAAAG8', 'KT9231', 'K29F33', 'KV5212', 'KT9F36', 'KK3DCX', 'KK3DC0', 'KW9F33', 'KW9F30', 'KW9F37', 'KN3DU8', 'KTUD36', 'KW9D37', 'KARFU1', 'KT9230', 'KB8CD5', 'KZ1AK2', 'K29F36', 'KB3FU5', 'KAAAG3', 'KT9F37', 'KN3DU6', 'KAAAG4', 'KB20U3', 'KU8FS9', 'KT9F35', 'K19F3X', 'KT4K39', 'KN3DU0', 'KDTB30', 'KUBAG5', 'KB8CDX', 'KT6234', 'KT6239', 'KK4CC8', 'K19F34', 'KK4CCX', 'KTUD32', 'KB20U7', 'KK4CC1', 'KW9D32', 'KTUD31', 'KU8FS1', 'KW9F39', 'K19F37', 'KT9235', 'KU8FS2', 'KN3DUX', 'KR32EX', 'KBRFU2', 'KY5F13', 'KR32E6', 'KW9F3X', 'KV5210', 'KU8FSO', 'KAAAG2', 'KK4CC7', 'KR30E1', 'KB3FUX', 'KX8CBX', 'KW9F38', 'KZ3DC4', 'KN5BF7', 'KUBFS2', 'KX8CB4', 'KT6236', 'KAAAG6', 'KB3FU3', 'KZ6265', 'KZ3DC1', 'KK4CC4', 'KK4CC0', 'KW9F35', 'K61AK7', 'KU8FS4', 'KUBAGX', 'KN3DU7', 'KTUD39', 'K440F1', 'KB8CD9', 'KK3DC7', 'KAAAG5', 'KZ4BX1', 'KT6233', 'KY5F18', 'KU4EE7', 'KB3FU9', 'KZ4BX2', 'KB20U4', 'KN3DU4', 'KUBAG6', 'KX9CBX', 'KK3DC6', 'KY5F14', 'KK3DC3', 'KM6261', 'KK3DC4', 'KTUD37', 'KZ3DC9', 'KN3DU5', 'K19F33', 'K61BK0', 'KY5F10', 'KT6231', 'KA3DC5', 'KB3FU2', 'KX8CB2', 'KUBAG1', 'KU8FS0', 'KT5219', 'KT9F32', 'KX6CB1', 'K61AK1', 'KUBAG4', 'KB8CD1', 'KT6237', 'KW73J1', 'KA3DC7', 'KU8FS3', 'KB20U9', 'KU8FS5', 'KTUD35', 'KB8CD6', 'KB3FU6', 'KUBAG2', 'KT9F3X', 'KT9232', 'KB3FU1', 'KBBCD8', 'KZ3DC0', 'KA3DC9', 'KU8FS6', 'KX8CB1', 'KCAAG8', 'KAAAGO', 'KSKFC3', 'KHMBX3', 'KR32E8', 'K29F37', 'K1RFV8', 'KZ3DC8', 'KRKEC5', 'KB20U5', 'KDTB38', 'KTUD30', 'KT9D38', 'KT923X', 'KT9F34', 'KT9F39', 'KABAG0', 'KK4CC6', 'KX8CB7', 'KUBAG7', 'KT6232', 'KAMFU5', 'KAAAG7', 'KTUD3X', 'KR32E9', 'KM6262', 'KT9D34', 'KTUD38', 'KAAAG1', 'KHMBXX', 'KTUD34', 'KDTB37', 'KX9CB7', 'KR32E7', 'KCAAG5', 'KABAG9', 'KW9F34', 'K19F36', 'KV5213', 'KZ3DC6', 'KT9D36', 'KW9F36', 'KX8CB8', 'KX8CB3', 'KTUD33', 'KX6CB2', 'KT623X', 'KA3DC3', 'KX8CD0', 'KCBAG0', 'KAAAGX', 'KV5215', 'KX6CB4', 'KABAG1', 'KZ4BX4', 'KUBAG9', 'KHMBX7', 'KB3FU7', 'KT6230', 'KCBAG3', 'KB20UX', 'KC20F7', 'KDTB34', 'KX9CB4', 'KDTB31', 'KT9D32', 'K1RFVX', 'KT441X', 'KT9237', 'KX9CB8', 'KABAG5', 'KF4DV3', 'KR32E2', 'K61AK0', 'KU5BF6', 'KZ3DC7', 'KU5BF5', 'KT9234', 'KX6CB6', 'KDTB32', 'KDTB33', 'KK4CC9', 'KV5211', 'KA3DC0', 'KX9CB0', 'KX9CB6', 'KDTB39', 'KY5F11', 'K1RFV4', 'KU104X', 'KX8CB5', 'KRKEC9', 'K4MBE8', 'K29F3X', 'KHMBX2', 'KZ4BXX', 'KT6238', 'KX9CB5', 'KV5217', 'KZ3DC3', 'KBRFU9', 'KARFU6', 'KV521X', 'KT9D31', 'KARJE0', 'KA3DC4', 'K61AKX', 'KV5214', 'KARFU2', 'KN5BFX', 'KT5218', 'KX9CB1', 'K29F38', 'K29F31', 'KW5F16', 'KARFUX', 'K1RFV7', 'KARJE4', 'KB8FS0', 'KY5G18', 'KUBAG0', 'KHMBX5', 'KT5212', 'KARFU0', 'KW9032', 'KX6CB3', 'KX9CB3', 'KDTB3X', 'KX6CB7', 'KCAAG9', 'KD5HN5', 'KB20U2', 'KARFU5', 'KA3DC8', 'KX8CB0', 'KN5BF2', 'KT521X', 'KARJEX', 'KT9D39', 'KU40E3', 'KB3FU8', 'KABAG6', 'KABAGO', 'KT9D3X', 'KT9238', 'KY5F15', 'KB3FU4', 'KARFU7', 'KAJDC9', 'KT4K31', 'KP14T0', 'KM5F15', 'K29F30', 'K61AK3', 'KT4K35', 'KU72N2', 'KP14TX', 'KV36F1', 'KCBAG9', 'KN3DP1', 'KCAAGX', 'KARJE5', 'KT9239', 'KU4EE8', 'KB5DA2', 'KBRFU8', 'KZ6268', 'KW903X', 'KA3DCO', 'KZ1AK5', 'KAMFU9', 'KUBAGO', 'KUBAG8', 'KT9D35', 'KCAAG0', 'KARFU4', 'K29F35', 'KT4K36', 'KABAG7', 'KABAG2', 'KBRFU6', 'KY5G1X', 'KARJE2', 'KCBAG4', 'KU5JR3', 'KAMFPX', 'K1RFV3', 'KZ3DC5', 'KHMBX9', 'KHMBX8', 'KHMBX0', 'KR32E1', 'KW73J7', 'KY5F12', 'KX9CB2', 'K29F34', 'KX8CB9', 'KARJE3', 'KARFP6', 'KUAAG1', 'KDRBH2', 'KA3DC1', 'KARFU3', 'KUBAG3', 'KBRFU4', 'KUAAG3', 'KZ1AK3', 'KUAAGB', 'K61AK8', 'KA3DC2', 'KW9F3G', 'K61BK6', 'KT9031', 'KT9032', 'KY5G16', 'KN5BF0', 'KN3DUS', 'KDTB36', 'KW5F11', 'KT4K38', 'KFDNN1', 'KK3DCG', 'KT624X', 'KABAG8', 'K29F32', 'KX6CBX', 'KE50E2', 'K440F2', 'KB5DA7', 'KX8CB6', 'KABAG4', 'KCBAG8', 'KB9CP0', 'KN3DP7', 'KT1230', 'KU40E4', 'KT5217', 'KCAAG6', 'KHCAA7', 'K31AK7', 'KCBAG2', 'KN3D00', 'KB20U6', 'KYSFIX', 'KHMBX1', 'KC4BS8', 'KT9D30', 'KX6CB5', 'KARFP2', 'KT9D33', 'KW5F18', 'KBRFU7', 'K4RBE4', 'KRKEC3', 'K6E6F1', 'KARFP3', 'KBRFU5', 'KARFU8', 'KHCAAX', 'KBRFU1', 'KCAAG4', 'KB20U8', 'KDRAH6', 'KZ3DCX', 'KZ6264', 'KAAAC7', 'KM5F10', 'KC20D3', 'KN3DUO', 'KARJE1', 'KW9031', 'K61AK4', 'KCAAG3', 'KZ4DX1', 'KT9D37', 'KV5216', 'KT9030', 'KX6CB8', 'KBAAGX', 'KN9CP5', 'KUAAG9', 'K61BK4', 'KABAG3', 'KU5BF9', 'KARJE7', 'KR32E3', 'KT6249', 'KHMBX6', 'KCBAGX', 'KRKEC1', 'KZA006', 'KT4K30', 'KV5218', 'K4RBEX', 'KT4410', 'KDRAHO', 'KK4DV3', 'KN5BF6', 'KZ6262', 'KB20U1', 'KK3DCO', 'KB8CDO', 'KN3DP6', 'KY5G17', 'KB54H1', 'KX6CB9', 'K61AK5', 'KC311A', 'KARJE6', 'KARFU9', 'K4RBE2', 'KT9233', 'KB71J6', 'KB20U0', 'KW5F14', 'KV30F8', 'KUAAG8', 'KR30E6', 'KUAAG4', 'KW73J3', 'KA3DCX', 'K440F8', 'KT4217', 'K4RBE8', 'KX6CB0', 'KV30F7', 'KAMFU8', 'KY5G13', 'KZ6263', 'KC20FX', 'KZ4BXO', 'KB8CP8', 'K5KFCX', 'KU8F52', 'KT6242', 'KRKECX', 'KUAAGX', 'KN5BF1', 'KU5BF0', 'KV5219', 'KHMBX4', 'KF4DVX', 'KKRFHX', 'K4RBE7', 'KRKEC8', 'KX8C85', 'KAAAGB', 'KR32E0', 'KDRBH8', 'KAMFP0', 'K61AK6', 'KK3DCI', 'K83FU8', 'K440F5', 'K29F39', 'KBRFU3', 'K83FU9', 'K6T1Y6', 'KU4HN3', 'KB22U1', 'KU4EE5', 'K31AK0', 'KB3FUB', 'KN9CP8', 'KN3D02', 'KU40EX', 'KT9K38', 'KB5DB8', 'K4RBE0', 'KY1CDX', 'KUSFST', 'KCBAG7', 'KARFP5', 'KV30F3', 'KRKEC2', 'KCAAG7', 'KW9D3S', 'KZ6260', 'KARJE8', 'KF4DV6', 'KP14T5', 'KUBFS9', 'KAMFUX', 'KV30F9', 'KU5JR4', 'KUAAG5', 'KW5F13', 'KR32E4', 'K1RFV6', 'K1RFV5', 'KF4DV1', 'KW9033', 'KARJE9', 'KE52YX', 'KZ6266', 'KBBCDS', 'KCAAGO', 'KWS236', 'KKRFH0', 'K8RFU5', 'KN5BF5', 'K83FU3', 'K83FU0', 'KB3FUS', 'K4RBE3', 'KN3DP3', 'KX9CB9', 'KV32F9', 'KB5DB9', 'KCAAG2', 'K4RBE1', 'KARFP4', 'KV30F2', 'KN3DP9', 'KV30F1', 'KV30FX', 'KT4418', 'KU8FSG', 'KW71J6', 'KUBFS5', 'KARAH2', 'KT5215', 'KW73JX', 'KAAA60', 'KKRFH7', 'KU8F58', 'KZABX8', 'KM6260', 'KARFP8', 'K61AK2', 'KM6268', 'KC206X', 'KARFP7', 'KFNM3X', 'KHCAA1', 'KAMFP7', 'KF4DV5', 'KN5BF3', 'KM5F13', 'KU8F5X', 'KZ1AK4', 'KF4DV8', 'KT5214', 'KAMFU0', 'KDRBH6', 'K4MBE7', 'KAMFP1', 'KW73J8', 'KA3DC6', 'KX9CBO', 'KBRCH0', 'KB5DA5', 'KN3DP0', 'KCBAG5', 'KSKFC7', 'KK3EH0', 'KU40E7', 'KK3EHO', 'KW8D37', 'KU5BF8', 'KARFP1', 'KR38E0', 'K23DC3', 'KW5F10', 'KT6245', 'KX8CD6', 'KSKFC1', 'KU8F55', 'KBRFUX', 'KT5213', 'K1RFV9', 'KB5AB0', 'K820U9', 'KAMFP2', 'KB5DB2', 'KM5F17', 'KT6045', 'KDRAH9', 'KBRFU0', 'KDRAH8', 'KX8CD4', 'K440F4', 'K4RBE6', 'KN3DP2', 'KC20G4', 'KN9CPX', 'KRKEC7', 'KRKEC0', 'KM6269', 'K4RBE9', 'KU4EE9', 'K23DC7', 'KW5F1X', 'KN3DP5', 'KZ626X', 'KX8CDX', 'KX8FS7', 'KB2000', 'KDRAH3', 'KM5F14', 'KUBFSX', 'KT1231', 'KW73J0', 'KV30F0', 'KZRFH4', 'KT6041', 'KX8CD5']
  Model_Year: ['8', 'D', 'B', 'F', 'H', 'K', '6', 'R', 'L', 'E', 'A', 'C', 'M', 'S', 'G', 'P', '7', 'N', 'T', 'J', '9', '4', '5', 'X', '1', '3', '2', 'Y', 'V']
  Plant_Code: ['5', 'S', '1', '3', 'D', 'X', '0', 'R', 'U', '2', 'A', 'C', '7', 'W', 'J', 'T', 'M', '8', 'O', 'P', '6', 'L', 'K', 'V', 'N', '9', 'Y']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,YARIS,4.0,SEDAN,K,FLEET,GCC,4.0,JTD,KW9239,8,5,108974
1,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),NON-GCC,5.0,5TD,KK3DC1,D,S,389260
2,TOYOTA,YARIS,4.0,SEDAN,K,FLEET,GCC,4.0,JTD,KW9236,8,5,106552
3,TOYOTA,YARIS,4.0,HATCHBACK,K,FLEET,GCC,5.0,JTD,KW9236,B,5,189066
4,TOYOTA,YARIS,4.0,SEDAN,K,SE TRD AERO PK,GCC,4.0,MR2,KT9F38,F,1,143683
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18606,TOYOTA,PRIUS,4.0,SEDAN,K,STD (NON GCC),NON-GCC,NaN,JTD,KN3DU9,A,0,058716
18607,TOYOTA,YARIS,4.0,HATCHBACK,K,SE,GCC,NaN,MR2,K19F39,H,1,021875
18608,TOYOTA,SIENNA,6.0,SUV,K,LE (NON GCC),NON-GCC,NaN,5TD,KK3DC7,G,S,742721
18609,TOYOTA,YARIS,4.0,HATCHBACK,K,SE+,NON-GCC,NaN,VNK,KTUD38,F,A,040994
18610,TOYOTA,COROLLA CROSS,4.0,SUV,K,XL,GCC,NaN,RKL,KUBAG0,R,0,504648

====================================================================================================
POS4: M
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TUNDRA', 'AVANZA', 'LAND CRUISER PICK UP', 'CAMRY', 'CRESSIDA', 'COROLLA', 'TACOMA', 'SUPRA', 'RAV4', 'LAND CRUISER', 'TOYOTA TACOMA', 'JUSTIN BIEBER X VESPA 150 E5 GSO (SCOOTER)', 'COROLLA SEDAN', 'HILUX', 'AURION', 'TAKOMA', 'C-HR', 'FORTUNER', 'VESPA VXL 150', 'VESPA VXL', 'افنزا', '4RUNNER', 'AVALON', 'HIACE', 'CAMRY HYBRID']
  bodyType: ['PICK UP DOUBLE CAB', 'MPV', 'SUV', 'SEDAN', 'COUPE', 'PICKUP', 'PICK UP', 'PANEL VAN', 'MOTORCYCLE', 'STATION', 'VAN', 'MINI BUS']
  pos4: ['M']
  trim: ['STD (NON GCC)', 'SE', '1794 EDITION (NON GCC)', 'CREWMAX CAPSTONE (NON GCC)', 'LX AC PWR OPT', 'GLE HEV', 'STD', 'XLI', 'LE', 'COUPE', 'BASE', 'EXR', 'GXR FMST', 'SGL', 'STD AC', 'GLS', 'DLX', 'GLX', 'CRESSIDA', 'GLI', 'GLE', 'AXL ', 'STD CARGO', 'GRANDE', 'S', 'EX', 'LIMITED', 'E', 'SR', 'STANDARD', 'SPORT', 'PW CL', 'LUXURY SPORT', 'GV', '60TH', 'GR', 'SE+', 'GL', 'VX', 'DL', '1794 EDITION (NON GC', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TF', 'MHK', '4T1', 'JT2', '3TM', 'ZAP', 'RP8', 'MMM', '57W', 'JTH', 'MET', 'JTM', '5TE', '4T3', 'JD2', 'JHH', 'JTE', 'JTD', 'LVZ', 'LNB', '2T3', 'LJN']
  VDS: ['MV5215', 'MF53F3', 'MC13FX', 'MF53F1', 'MF5CF1', 'MF5BF7', 'MC13F7', 'MF53F8', 'MF53F4', 'MF52F5', 'MF53F5', 'MF5BF4', 'MF53F9', 'MC13F6', 'MC13F5', 'MC13F9', 'MC13F3', 'MC13F4', 'MF5BF5', 'MC13F8', 'MF52F0', 'MF53F2', 'MF52F2', 'MF53F7', 'MF5CF3', 'MC13F1', 'MF5CF2', 'MC12F6', 'MC12F3', 'MF5CF9', 'MFSCF3', 'MC13F0', 'MF53F0', 'MF5BFX', 'MF5CF5', 'MF53F6', 'MF5BF3', 'MC5DB6', 'MF5CF4', 'MF5BF9', 'MA5EC2', 'MF52F4', 'MU4FNX', 'MF52F8', 'MF5CF7', 'MC5DB8', 'M11AK7', 'MC13F2', 'MX83EX', 'MA71J2', 'MU4FN1', 'MD3502', 'MU4FN3', 'MF5CFX', 'MF5BF2', 'MF53FO', 'MF5CF0', 'MA71L5', 'MC5DB4', 'M45711', 'MFSCF0', 'MF5BF0', 'MF5BF1', 'M1111M', 'MV5219', 'MY5F13', 'MF53FX', 'MC12F5', 'MF5CF6', 'MC12F4', 'ML2A69', 'MA3603', 'MF52F7', 'MT09J8', 'MC12F9', 'MF52F3', 'MC12F2', 'MF52F9', 'MU4FN8', 'MF5CF8', 'MD1218', 'MF5BF6', 'MC12F1', 'MF52FX', 'M85002', 'M85007', 'MFSBF7', 'MFSCF6', 'MF5CFO', 'M11AK8', 'MC5DB5', 'MC12F0', 'MV5214', 'MWRFV3', 'MU4FN5', 'MC5DB1', 'MF52F6', 'MV521X', 'MV5212', 'MA5DB9', 'MU52N0', 'M11AK6', 'MX83E7', 'M85004', 'MX73E3', 'MWRFV2', 'MX73E9', 'M85008', 'MA70J6', 'MT5215', 'MC12FX', 'M8500X', 'MF53FI', 'MC12F8', 'MA5DB8', 'MU52N8', 'MF5BFO', 'MA5DBX', 'ME53F3', 'MD3501', 'MU52N9', 'MF52F1', 'MU52N4', 'MF9290', 'MA5ECO', 'MA5EC0', 'MF5BF8', 'MD3524', 'MD3512', 'MA5DB4', 'M85003', 'MC12F7', 'MA5DB0', 'MFSCF7', 'MF9291', 'MA5DB5', 'MCK3H2', 'MU4FN9', 'MA5DB6', 'MU4FN7', 'M11AK0', 'MC5DB9', 'MV5211', 'MA5DB7', 'MF5BFI', 'MU5JR8', 'M85000', 'M11AK4', 'MA71J6', 'MF5CFI', 'MU4FN2', 'MT5213', 'M4RCE5', 'MD1212', 'MN25B5', 'MA71J9', 'MCUBK9', 'MA5EC3', 'MD3517', 'MA71L3', 'MT5218', 'MWRFV0', 'M11AK2', 'MC5AB5', 'MCK3H3', 'MU4FN6', 'MWRFV7', 'MF9297', 'MV5213', 'MA70L6', 'MFWBY5', 'MA5DB3', 'MU5JR5', 'MV5216', 'MA5DB1', 'MA70L5', 'M11AK5', 'MA71J0', 'MX83E0']
  Model_Year: ['9', 'H', 'F', 'J', 'G', 'L', 'K', 'P', 'R', 'C', 'M', 'A', 'T', 'B', '8', 'E', 'V', 'N', '7', '6', 'S', 'D', '5', '1', 'X']
  Plant_Code: ['X', 'K', 'U', '0', 'M', 'P', 'V', '5', '3', 'D', 'Z', '1', 'H', 'J', 'A', 'T', 'W', 'N']
  Serial_Number: ['094001', '015126', '019527', '022219', '002087', '000071', '019906', '008218', '019816', '000899', '017623', '001780', '024276', '021819', '018455', '013442', '014027', '015125', '018793', '018514', '017241', '001299', '019736', '001961', '017238', '000441', '010347', '000406', '018711', '018139', '013387', '003704', '000761', '008451', '000085', '008355', '019222', '000657', '000653', '011624', '013053', '015865', '006420', '010503', '025528', '025087', '008721', '008676', '020055', '001010', '002560', '001121', '015046', '005205', '001752', '019896', '016817', '000200', '013971', '025663', '015056', '019547', '014651', '006524', '004999', '019309', '004806', '002659', '010492', '013658', '002039', '011341', '016389', '001788', '022407', '015054', '000828', '019678', '004696', '014579', '015000', '006212', '005645', '004654', '005900', '017941', '008248', '017957', '041191', '014024', '385568', '009370', '015877', '002673', '019878', '001609', '017188', '014158', '002600', '071921', '006544', '101971', '006130', '008160', '017281', '006943', '018389', '006465', '001029', '016722', '035714', '003871', '023817', '007872', '020513', '001891', '015072', '008693', '018813', '015834', '003714', '012175', '039476', '019968', '040619', '018866', '019813', '014307', '005553', '002865', '000434', '020004', '003569', '019480', '003495', '001405', '019771', '009964', '025176', '003113', '000129', '014081', '024840', '015041', '019659', '008319', '019929', '015511', '014263', '008400', '003447', 'M11111', '002871', '003161', '000481', '018693', '019125', '004572', '013887', '019837', '018109', '002781', '003594', '023456', '076910', '015249', '010606', '018859', '009345', '018816', '000893', '006940', '019646', '010467', '019916', '018889', '102067', '010045', '018783', '023126', '004318', '020734', '001356', '009376', '012378', '018665', '022074', '002966', '010026', '008710', '101508', '007283', '019998', '018635', '001088', '600831', '000306', '002563', '023806', '010635', '019099', '017968', '006191', '003353', '014262', '014441', 'O16718', '011158', '014376', '001876', '011120', '000495', '003095', '008572', '001827', '007538', '018826', '015388', '001892', '000858', '021852', '012394', '000212', '038707', '019930', '005098', '001023', '003143', '014006', '016926', '001593', '002090', '018150', '019079', '001805', '007543', '014587', '001146', '009291', '002949', '024113', '001717', '012851', '003018', '004708', '014985', '019759', '001066', '012152', '017107', '003489', '005605', '019337', '008403', '000878', '033007', '002942', '008657', '019949', '000722', '003746', '013194', '003712', '019991', '001725', '016596', '025435', '007806', '025992', '016658', '000456', '000898', '003307', '015462', '014192', '013414', '013719', '000719', '012377', '018968', '016942', '015311', '007337', '019204', '016352', '006853', '015557', '005956', '004466', '005706', '013332', '013736', '001246', '003123', '003748', '018925', '001769', '011188', '002017', '011149', '007537', '017398', '001438', '350151', '001378', '005758', '020052', '002408', '007189', '004523', '014878', '006894', '015683', '016230', '018501', '019377', '016476', '000537', '002549', '000934', '025471', '001786', '022259', '000505', '006834', '014940', '017297', '013075', '019158', '001480', '035023', '000759', '012171', '081254', '019922', '002688', '017999', '006184', '010273', '020499', '007631', '001322', '001281', '011144', '019591', '158825', '014239', '011208', '019911', '001520', '001648', '018641', '007117', '016652', '004587', '018796', '005975', '005380', '020034', '000565', '043915', '015810', '006464', '011820', '001682', '025629', '017165', '004446', '025728', '018047', '010880', '010297', '014427', '005899', '007488', '019993', '014269', '009448', '003044', '021718', '015918', '009699', '003818', '027790', '010588', '111963', '016645', '017121', '003201', '012703', '022152', '019920', '004241', '018616', '001766', '215866', '001726', '015433', '006946', '000531', '869974', '019496', '005678', '001072', '006385', '008617', '001422', '002917', '090489', '006930', '016953', '002282', '003646', '010036', '008208', '000848', '007406', '110462', '011387', '000780', '006418', '004622', '018278', '071999', '019610', '007982', '009562', '010355', '002695', '006461', '007240', '077028', '007876', '000220', '019400', '003259', '009443', '020082', '002879', '017980', '003411', '015745', '000956', '000185', '001367', '060238', '020902', '013434', '009660', '019040', '003130', '001236', '020926', '010080', '005455', '008172', '008848', '001637', '008615', '016376', '001716', '003800', '017073', '001014', '015792', '016278', '010134', '001068', '013475', '014293', '003280', '010067', '008357', '019321', '001336', '000400', '003321', '001162', '010482', '017324', '001308', '005819', '020244', '010327', '019777', '019627', '001274', '000377', '013686', '018412', '003552', '019632', '001657', '050795', '022697', '018924', '082231', '012885', '008325', '006241', '009339', '022469', '002679', '020216', '003464', '010597', '019056', '001984', '025544', '011655', '014302', '016603', '019936', '015443', '015421', '006583', '019575', '001436', '019090', '015624', '025691', '001897', '025480', '182740', '019987', '021050', '021946', '005088', '001140', '007843', '000762', '019598', '000578', '000529', '013604', '018901', '019630', '025864', '001325', '007634', '011301', '019963', '019446', '001024', '006657', '010564', '009176', '014944', '006786', '009230', '000741', '001084', '016553', '002667', '021100', '015639', '019904', '009595', '001363', '006662', '008191', '020075', '024506', '013935', '002402', '005290', '010353', '018521', '019808', '014557', '010611', '010003', '061758', '003152', '002882', '001536', '006908', '010059', '001037', '016258', '015448', '015902', '002910', '000603', '004058', '011176', '012701', '003510', '001861', '010447', '005611', '016397', '013006', '003436', '001444', '006809', '311426', '011524', '013750', '009772', '011092', '000900', '022403', '019978', '018387', '003399', '099047', '007797', '000205', '013653', '010393', '004284', '010699', '017667', '001920', '013725', '020608', '007914', '017844', '019564', '000180', '000674', '019307', '000907', '588198', '011792', '018242', '015100', '011817', '001379', '012450', '013458', '008492', '000637', '018422', '002922', '008406', '018253', '002488', '002407', '025031', '023653', '000023', '006578', '006318', '009378', '025664', '001070', '001035', '004594', '019381', '002955', '003628', '016673', '011357', '009704', '020163', '005102', '001003', '002722', '003900', '015802', '000673', '001007', '003031', '002689', '003632', '014663', '017790', '019394', '006825', '000724', '001877', '012795', '014125', '015960', '025884', '001787', '018326', '104390', '001433', '018018', '000626', '019319', '010089', '000633', '010040', '014143', '000695', '000922', '001812', '018945', '000799', '003413', '013895', '011827', '003579', '010582', '030530', '007701', '000757', '014266', '086608', '016561', '001645', '023956', '018913', '017092', '018172', '006035', '000760', '017502', '011591', '016172', '013121', '010386', '016505', '017478', '001734', '032291', '000670', '018557', '001747', '038647', '000997', '001077', '002696', '013811', '019349', '001944', '025007', '013681', '013779', '014857', '014232', '023136', '025332', '020086', '006135', '018155', '003422', '019893', '019956', '014634', '019836', '014398', '013232', '000315', '016558', '016293', '014571', '017078', '017099', '009744', '018861', '001790', '002886', '006489', '013239', '001440', '023253', '002847', '007459', '008525', '066322', '007122', '007418', '019514', '003467', '013645', '010330', '025763', '018917', '014685', '011812', '013413', '018185', '015742', '001903', '003660', '014955', '005109', '019217', '025964', '015675', '009659', '003453', '018475', '015003', '014253', '025933', '005657', '005699', '014236', '017488', '003015', '003958', '000682', '008030', '025636', '012849', '011650', '003629', '009323', '002552', '000432', '000223', '017917', '019703', '010863', '014941', '017911', '010519', '019693', '000422', '018948', '005118', '007800', '008415', '017274', '009867', '000706', '025778', '012151', '021119', '010439', '000453', '012873', '005147', '001862', '012400', '023224', '002948', '001841', '015517', '018963', '003644', '014541', '001473', '019068', '014368', '019850', '001835', '019541', '013924', '010428', '014813', '018535', '009267', '001410', '007530', '012705', '019243', '016912', '003029', '012191', '001195', '011915', '013673', '004225', '012608', '019225', '019059', '001219', '008407', '001863', '000561', '003032', '001345', '016167', '008526', '006667', '010552', '016390', '022677', '020224', '004630', '014963', '019932', '009619', '010009', '025560', '016404', '010435', '015790', '008052', '012098', '004712', '013835', '010541', '017264', '006404', '013208', '015350', '001025', '013668', '018054', '010848', '001124', '012777', '014544', '001267', '000053', '022739', '127041', '019979', '015058', '011896', '012132', '025196', '001821', '024941', '018713', '019782', '018567', '019651', '019648', '013990', '018746', '000521', '003439', '006936', '012936', '019871', '005267', '005673', '068379', '010674', '017404', '009917', '019807', '001309', '018154', '000839', '001856', '013996', '000672', '019226', '007622', '004445', '002495', '015777', '019860', '001360', '139447', '001710', '007819', '001692', '016154', '015233', '007219', '002487', '002518', '020332', '022649', '001626', '001125', '010250', '018858', '001666', '001579', '010379', '001526', '009921', '017652', '022686', '018696', '000635', '010487', '009532', '010510', '014565', '023349', '001729', '001819', '014897', '005782', '012142', '019984', '017818', '019664', '008263', '013545', '013553', '014109', '014972', '001103', '000229', '000418', '005105', '017443', '015906', '001396', '015863', '015728', '004083', '004431', '015392', '019028', '014011', '001587', '017600', '001172', '019590', '937735', '019303', '000179', '018509', '014291', '013261', '016269', '012712', '013572', '000478', '004489', '018158', '002070', '016153', '003019', '019461', '019540', '018252', '014280', '001075', '056323', '015690', '017471', '003269', '003039', '019551', '011287', '001465', '018833', '051759', '014515', '003693', '007341', '009288', '012447', '001318', '011481', '001076', '001845', '000348', '012021', '014682', '014025', '023472', '003432', '009976', '005807', '017894', '010107', '020704', '015283', '003251', '018806', '000383', '019811', '012149', '661686', '025297', '016208', '011637', '011608', '011775', '001614', '006079', '014257', '003103', '016347', '011113', '017284', '012956', '002547', '000410', '012533', '024571', '016200', '018307', '016306', '001851', '000003', '012038', '029050', '005763', '005951', '005498', '018051', '019760', '024791', '011797', '001798', '001456', '005831', '009368', '000408', '015492', '009478', '020073', '019899', '015530', '017269', '013939', '004657', '018227', '019353', '001392', '019833', '001119', '010529', '003388', '006490', '941863', '001697', '016515', '009977', '000122', '987988', '003004', '016741', '000886', '014572', '158338', '013220', '002572', '005519', '015599', '000475', '000686', '020158', '003965', '003276', '024269', '013186', '018404', '002934', '019035', '023154', '010514', '007108', '018497', '006452', '002898', '016601', '002140', '028845', '006282', '013986', '012669', '001205', '009582', '010115', '015765', '008012', '002987', '013228', '002897', '018740', '016655', '000772', '001402', '013871', '009516', '016210', '007785', '013710', '025826', '018625', '019799', '011412', '015227', '001867', '012604', '001641', '001619', '017295', '016664', '022428', '010101', '017339', '002628', '017463', '019267', '000215', '014187', '005653', '006253', '019747', '015349', '011195', '019115', '002012', '014400', '010452', '016683', '015534', '017058', '014758', '019176', '013454', '014321', '025731', '018449', '003000', '303287', '002820', '004475', '012700', '001547', '021912', '009776', '001489', '013650', '018371', '003472', '005663', '019889', '020077', '014420', '010644', '004209', '007211', '014480', '004813', '017571', '016042', '014256', '014873', '023707', '019909', '019278', '010047', '011716', '008370', '015803', '002717', '023317', '007729', '005085', '001022', '015736', '004853', '003600', '025773', '000746', '006689', '000906', '008610', '018856', '015002', '036850', '001034', '001327', '000226', '003225', '001468', '527631', '018428', '019011', '001226', '001390', '017965', '100560', '001175', '006736', '000882', '018570', '105934', '006617', '015775', '016039', '019616', '010033', '001417', '009677', '010484', '171316', '008343', '019001', '019967', '019528', '019287', '005542', '000734', '007275', '019306', '010610', '002062', '009787', '009502', '009561', '015345', '008482', '005546', '000970', '082486', '019812', '023862', '012173', '021143', '001004', '019220', '019535', '008503', '018084', '001578', '001808', '012192', '122606', '017278', '015634', '019531', '004326', '012286', '011190', '004448', '005489', '005152', '013760', '003617', '001917', '006213', '005997', '003099', '023938', '007435', '016843', '001287', '002145', '003732', '001782', '018554', '002941', '014855', '018840', '016644', '004321', '019614', '010640', '003497', '000188', '025523', '000797', '012789', '000476', '017833', '005195', '019705', '001815', '011738', '009509', '014974', '007861', '002931', '010566', '010565', '015763', '019019', '000798', '019562', '005548', '016246', '141780', '010054', '005332', '015071', '000755', '019239', '002763', '014344', '014463', '016430', '090119', '988380', '002933', '017695', '019941', '001777', '012856', '007353', '015723', '013570', '007429', '013451', '003187', '014747', '017338', '001166', '025170', '001804', '014992', '007248', '019961', '025716', '019458', '001067', '012157', '006799', '014366', '019717', '018572', '019042', '003083', '014320', '019308', '022610', '013726', '018205', '000461', '003277', '000708', '019712', '021177', '019593', '019686', '015011', '009224', '003720', '016906', '009452', '015459', '010592', '015658', '014491', '013090', '016690', '015482', '016753', '000880', '012375', '007614', '000326', '000869', '017024', '001120', '019299', '001353', '001186', '001832', '003159', '019047', '008292', '015774', '003584', '004328', '000558', '013647', '018492', '008591', '002895', '001168', '006735', '019675', '016554', '014206', '001019', '017319', '016387', '033634', '006997', '025717', '001179', '018288', '008830', '004601', '004803', '013732', '023976', '001942', '015031', '008564', '006413', '008260', '002530', '014364', '017902', '002602', '018576', '002666', '005436', '012147', '000216', '001082', '019231', '016607', '001872', '019102', '001644', '014946', '011628', '014920', '019640', '000827', '008388', '018705', '023756', '101987', '013384', '004671', '013417', '388057', '019223', '025932', '015682', '018821', '006919', '018381', '018754', '000483', '000770', '004834', '000966', '017531', '018864', '020812', '013685', '015127', '018494', '020009', '196061', '013988', '010495', '001100', '013638', '014231', '006058', '019390', '011068', '022330', '015581', '018970', '011810', '014411', '019654', '001601', '048472', '000943', '016480', '025452', '009144', '020038', '016363', '015382', '043697', '010001', '413452', '181980', '019004', '020660', '003635', '019098', '000618', '014939', '862800', '019339', '011843', '000076', '013423', '014217', '018159', '019089', '000549', '061037', '001030', '023469', '003022', '009458', '013379', '005172', '012598', '001111', '000547', '001915', '015913', '021607', '000354', '075837', '045747', '017342', '017905', '016068', '021883', '993864', '001649', '007989', '018506', '007125', '016977', '087102', '074276', '001332', '010548', '018202', '009064', '018628', '009941']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,M,STD (NON GCC),GCC,4.0,5TF,MV5215,9,X,094001
1,TOYOTA,AVANZA,4.0,MPV,M,SE,GCC,NaN,MHK,MF53F3,H,K,015126
2,TOYOTA,AVANZA,4.0,MPV,M,SE,GCC,5.0,MHK,MC13FX,F,K,019527
3,TOYOTA,AVANZA,4.0,MPV,M,SE,GCC,5.0,MHK,MF53F1,H,K,022219
4,TOYOTA,AVANZA,4.0,MPV,M,SE,GCC,5.0,MHK,MF5CF1,J,K,002087
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1652,TOYOTA,AVANZA,4.0,SUV,M,1,GCC,NaN,MHK,MC13FX,F,K,018202
1653,TOYOTA,AVANZA,4.0,SUV,M,SE,GCC,NaN,MHK,MF5BF3,L,K,001396
1654,TOYOTA,AVANZA,4.0,SUV,M,1,GCC,NaN,MHK,MC13F1,F,K,009064
1655,TOYOTA,AVANZA,4.0,SUV,M,SE,GCC,NaN,MHK,MC13F0,F,K,018628
1656,TOYOTA,AVANZA,4.0,SUV,M,SE,GCC,NaN,MHK,MF5CF0,L,K,009941

====================================================================================================
POS4: Y
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['FORTUNER', 'RAV4', 'SIENNA', 'GRANVIA', 'URBAN CRUISER', 'HIGHLANDER', 'SEQUOIA', '2009', 'RAV 4', 'FJ CRUISER', 'HILUX', 'COROLLA', 'LAND CRUISER', 'YARIS', 'TUNDRA', 'DYNA', 'TOYOTA', 'SIENNA(VAN)', 'H 530', 'VAN']
  bodyType: ['SUV', 'MPV', 'STATION', 'PICK UP DOUBLE CAB', 'VAN', 'SEDAN', 'PICK UP SINGLE CAB', 'TRUCK', 'LIGHT VEHICLE']
  pos4: ['Y']
  trim: ['GXR', 'SR5', 'TOP', 'BASE', 'LE (NON GCC)', 'PLATINUM', 'FABRIC', 'EXR', 'XLE (NON GCC)', 'PREMIUM', 'GL', 'LIMITED (NON GCC)', 'GLX', 'STD', 'PW CL', 'SE (NON GCC)', 'STD (NON GCC)', 'SR5 (NON GCC)', 'VX', 'SPORT', 'EX', 'XSE', 'SR5 4X2', 'TRD SPORT', 'DLS', 'SR5 4X4', 'BE', 'LIMITED 4X4', 'XLE', 'GLI', 'GX', 'CE (NON GCC)', 'TX', 'T', 'SED', 'EXCLUSIVE', 'E', 'GLE HEV', 'SE', 'S', 'LE', 'DL', 'DLX', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MHF', 'MR1', '2T3', '5TD', 'JTN', 'JTE', 'MBJ', 'JT3', 'MHE', 'JTM', 'JTD', '5FP', 'STD', 'MRI', 'MEJ', 'JHH', '2HN', 'MPJ', '5TF', 'MAF', 'SAL', 'JHG', 'LSY', 'LET', 'JHF']
  VDS: ['YU59G6', 'YX59G9', 'YX59G2', 'YK4DV0', 'YU59G2', 'YK4CC6', 'YU59G7', 'YM8AP0', 'YU59G0', 'YU59GX', 'YX59G3', 'YH20V1', 'YX59GX', 'YK3DC6', 'YX59G8', 'YK3DC4', 'YM3AP3', 'YMLA22', 'YK3DC7', 'YK3DC3', 'YMLA24', 'YX59G1', 'YX59G0', 'YK3DC8', 'YK3DC5', 'YX59G6', 'YU59G9', 'YMLA21', 'YZ3DC4', 'YK3DC9', 'YX59G4', 'YK3DC0', 'YZ3DCX', 'YM3AP8', 'YP10V8', 'YARAH6', 'YMLA28', 'YP10V3', 'YH20V2', 'YK4DV8', 'YZ3DC1', 'YZ3DC9', 'YFREVX', 'YU59G5', 'YU59G3', 'YX59G7', 'YMLA29', 'YMLA20', 'YK3DC1', 'YK4CC1', 'YZ3DC6', 'YK3DCX', 'YH20V7', 'YU59G8', 'YU59G1', 'YM3AP6', 'YM3AP2', 'YK4DV5', 'YH20V8', 'YK4CC0', 'YK4CC5', 'YP10V6', 'YK3DC2', 'YMLA27', 'YY5G1X', 'YU59G4', 'YFREV3', 'YH20V6', 'YMLA26', 'YH20VX', 'YF4DV7', 'YX59G5', 'YK4CC8', 'YK4CC2', 'YFREV2', 'YK4CC3', 'YP10V0', 'YMLA23', 'YZ3DC7', 'YFREV5', 'YM8AP5', 'YK4DV6', 'YK4DV3', 'YX5968', 'YH20V0', 'YP10V1', 'YF4EV3', 'YH20V5', 'YMLA2X', 'YKRFH8', 'YZ3DC0', 'YZ3DC5', 'YK4CCX', 'YP10VX', 'YFREV6', 'YK3DCO', 'YM3APX', 'YF4EV4', 'YX69GX', 'YU5965', 'YK4CC9', 'YFREV1', 'YZ3DC2', 'YH20V4', 'YFREV0', 'YMLA25', 'YSKFC5', 'YY5G18', 'YF4DV9', 'YFREV8', 'YM3AP5', 'YRKEC9', 'YM3AP9', 'YM8AP2', 'YZ3DC3', 'YH20V9', 'YK1F7X', 'YH20V3', 'YM3AP4', 'YM3AP1', 'YY5G15', 'YP10V4', 'YK4CC7', 'YSKFC3', 'YZ3DC8', 'YU5963', 'YU5967', 'YK4DV4', 'Y23DC1', 'YK4DV7', 'YP10V9', 'YX59C7', 'YM3AP0', 'YF4DV2', 'YH2076', 'YM3AP7', 'YF4EV8', 'YP10V7', 'YK4CC4', 'YZRAH5', 'YX5966', 'YX5960', 'YM8AP7', 'YFREV4', 'YF9EV1', 'YF9EVX', 'YFREV7', 'YX5906', 'YM8AP3', 'YXS9G3', 'YK3F13', 'YX5964', 'YX5969', 'YU5964', 'YX5963', 'YMLAZ7', 'YF4EV5', 'YKACC0', 'YF4DVX', 'YCN1HX', 'YP10V5', 'YF4DV1', 'YD2828', 'YRKEC2', 'YP10V2', 'YFREV9', 'YM3APO', 'YK4DVX', 'YX59GZ', 'YRKEC0', 'YU5908', 'YARAH7', 'YM8AP8', 'YRKEC4', 'Y1RFV6', 'YU5F17', 'YL2FV5', 'YU5969', 'YZRFH1', 'YJ2274', 'YF4DV5', 'YX5965', 'YU5968', 'YBBCA5', 'YK4DV1', 'YK4CCB', 'YK3DCI', 'YX59GI', 'YFAG20', 'YZRFH0', 'YX5962', 'YX50G0', 'YB20H2', 'YF4DV0', 'YX5967', 'YX59CX', 'YX59GE', 'YK4DV9']
  Model_Year: ['F', 'D', '6', '9', 'B', 'A', '7', 'L', '5', 'C', '8', 'E', 'P', 'R', 'S', 'H', 'W', 'X', '1', 'K', 'G', 'T', 'N', '2', '3', 'J', '4', 'Y', 'M', 'V']
  Plant_Code: ['7', '8', '0', 'W', 'S', '5', '3', 'T', 'J', 'D', 'B', 'K', 'H', 'C', 'X', 'A', '1', 'V']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,FORTUNER,6.0,SUV,Y,GXR,GCC,NaN,MHF,YU59G6,F,7,038129
1,TOYOTA,FORTUNER,4.0,SUV,Y,SR5,GCC,5.0,MHF,YX59G9,D,8,048149
2,TOYOTA,FORTUNER,4.0,SUV,Y,TOP,GCC,5.0,MR1,YU59G6,6,0,006069
3,TOYOTA,FORTUNER,4.0,SUV,Y,SR5,GCC,5.0,MHF,YX59G2,9,8,017459
4,TOYOTA,RAV4,4.0,SUV,Y,BASE,GCC,5.0,2T3,YK4DV0,B,W,013369
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5067,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA21,R,T,107359
5068,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GL,GCC,NaN,MBJ,YMLA29,R,T,106881
5069,TOYOTA,RAV4,4.0,SUV,Y,1,NON-GCC,NaN,JTE,YH20V1,4,0,058526
5070,TOYOTA,FORTUNER,4.0,SUV,Y,SR5,GCC,NaN,MHF,YX59G5,8,8,009418
5071,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA23,R,T,107248

====================================================================================================
POS4: D
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['FORTUNER', 'HILUX', 'SEQUOIA', 'RAV4', 'TUNDRA', 'SUPRA', 'BZ4X', 'SCION', 'LAND CRUISER', 'TACOMA', 'OTHERS', 'YARIS', 'SIENNA', 'COROLLA', 'ECHO', 'RAV 4', 'COROLLA CROSS', 'HIACE', 'CAMRY', 'HIGHLANDER', '2023', 'BZ3X', 'PICK UP', 'HAI LUX', 'C-HR', 'BZ 4', 'CELICA', '86', 'COASTER', 'AVALON', 'SELICA', 'LAND CRUISER GX', 'SUPRA COUPE', 'XA', '26HX DC 4X4 PLAT', '2 HX DC 4X4 P 2.7LAT', 'FJ CRUISER', 'H3', 'PRADO', 'هايلوكس', 'BZ46']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'PICK UP', 'COUPE', 'PICK UP SINGLE CAB', 'SEDAN', 'HATCHBACK', 'MPV', 'STATION', 'PICKUP', 'SUV- CROSSOVER', 'MINI BUS', 'MINI BUS HIGH ROOF', 'PICK UP DOUBLE CABIN', 'PANEL VAN', 'BUS', 'LIGHT VEHICLE', 'PICKUP DOUBLE CAB']
  pos4: ['D']
  trim: ['EXR', 'GL2', 'SR5 (NON GCC)', 'VXR', 'DLX', 'STD (NON GCC)', 'GR', 'PRO', 'EX', 'VXR HEV', 'DL', 'DLX TOP', 'GX', 'GL', 'GXR', 'G', 'XLI', 'SE', 'LE (NON GCC)', 'GLS', 'GLX', 'BE', 'XLI TOP', 'T', 'GXR TOP', 'LIMITED (NON GCC)', 'GR TAN EDITION', 'VX', 'DLS', 'VX2', 'SGLX', 'LE', 'SE (NON GCC)', 'BASE', 'DX', 'GR BLUE EDITION', 'GLI', 'GXR TOP DMST', 'LE HEV', 'XLE (NON GCC)', 'SE+', 'GXR FMST', 'GLE HEV', 'XLI MID', 'XLE HEV', 'STATION', 'GXR TOP 60TH ANNIV. XTREME', 'GT SPORT', 'AIR', 'HYBRID (NON GCC)', '25HX', 'GLE', 'XLE', 'STD', 'LIMITED 4X4', 'GL DECKLESS', 'XL', 'PLATINUM', 'LIMITED MID', 'E', 'CABRIO', 'XLI EXECUTIVE', 'ADVENTTURE', 'VX2 PLUS', 'TOP', 'GXR2', 'S', 'GLI HEV', 'MID', 'SR5 4X2', 'SWB', 'EXECUTIVE', 'GT', 'LWB', 'ADVENTURE', 'VX1', '1', 'A', 'STEALTH', 'GXR TOP 60TH ANNIV. ']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MHF', 'MRO', '5TD', 'JTM', 'MR0', '5TF', 'WZ1', 'LVG', '3MY', '5TB', 'JT2', 'STB', 'JTF', '2T3', 'JTN', '3TY', 'MR1', 'JTD', '7MU', 'JN6', '6T1', '4T1', '5YF', 'JTB', 'WV1', 'STF', 'LWL', '5T8', 'MRI', '3TM', 'JTE', '3N6', 'JN1', 'MNT', 'RKM', 'JT4', 'JTK', 'ZFC', 'MYN', 'LVV', 'WZI', 'JT3', '1G6', 'JAC', 'KMH', 'JNK', 'STY', 'SMT', '4TI', 'JAA', 'STM', 'JYM', '5GT', '4T3', 'WVW', '25T', '5TE']
  VDS: ['DX8FS9', 'DX8FS2', 'DB9CD3', 'DY5G1X', 'DF4EV3', 'DX22G9', 'DW5F14', 'DB0E04', 'DX22G3', 'DX8FS5', 'D31351', 'DW3FV1', 'DX8FS3', 'DW3FV3', 'DY5F14', 'DX22G8', 'DV5415', 'DX22G1', 'D31359', 'DF9EV0', 'DX9CD0', 'DY5F15', 'DF9EV2', 'DX22G6', 'DX8FS1', 'DF9EV3', 'DW3FV4', 'DY5F16', 'DLBZV4', 'DY5F13', 'DF9EV8', 'DU09J6', 'DX8FS8', 'DF9EVX', 'DT4416', 'DU09J3', 'DX8FSX', 'DZ5BN6', 'DX8FS4', 'DY5F12', 'DV5419', 'DU09J9', 'DZ5BN2', 'DP02T1', 'DF9EV6', 'DW5F1X', 'DT4412', 'DF4EV8', 'DW3FV7', 'DM5F11', 'DX8FS6', 'DLBYV1', 'DB0E05', 'DV5416', 'DB0A07', 'DT4413', 'DY5F10', 'DM6264', 'DK3DC6', 'DX22G4', 'DF4EV5', 'DF4EV4', 'DV5815', 'DY5F17', 'DF4EV7', 'DX9CD2', 'DFREV7', 'DFREVX', 'DX9CD4', 'DF4EV6', 'DX22G0', 'DV5412', 'DB9CD6', 'DB0E03', 'DX8CD5', 'DX9CDX', 'DBSCD6', 'DX22GX', 'DX8CD4', 'D31355', 'DF4EV1', 'DF4EV9', 'D4MBE8', 'DZ5BNX', 'DX9CD5', 'DJREV9', 'DB4A05', 'DR32T9', 'DF9EV5', 'D156F5', 'DX8CD1', 'DX9CD3', 'DX8CD7', 'DX22G2', 'DW5F12', 'DX22G5', 'DF4EVX', 'DU09J5', 'DW3FV9', 'DK3DC7', 'DV5816', 'DB0E08', 'DB0E01', 'DFREV9', 'DK3DC2', 'DX6CDX', 'DY5F18', 'DK3DC0', 'DX8FS7', 'DFREV5', 'DFREV6', 'DX9CD1', 'DX8F58', 'DX6CD9', 'DB9CD7', 'DFREV2', 'DY5F1X', 'DW5F11', 'DAABGX', 'DLBYV8', 'DW5G1X', 'DT4417', 'DK3DC3', 'DF4EV0', 'DFREV4', 'DY5F19', 'DF4DV7', 'DK4DV0', 'DB4C04', 'DK4CC9', 'DX8FS0', 'DF4EV2', 'DX8CD6', 'DT4411', 'DV541X', 'DU09JX', 'DK4DV6', 'DX22G7', 'DW12S1', 'DV5417', 'DB0E07', 'DB4C07', 'DU09J0', 'DLBYV2', 'DZ3DC1', 'DE32K0', 'DX9CD6', 'DLBYV0', 'DW5F17', 'DF9EV1', 'DT4415', 'D4MBE2', 'DB4A09', 'DLBZV0', 'DF9EV4', 'DF9EV9', 'DB9CDO', 'DT4814', 'DB9CD0', 'DT481X', 'DW5F18', 'DLBYVX', 'DF4DVX', 'DW3FVO', 'DFREV1', 'DB9CD8', 'DF9EV7', 'DB9CD9', 'DK4DV9', 'DB0E09', 'DBADK5', 'DV5818', 'DW5F16', 'DW5F13', 'DLBYV7', 'DW5417', 'DK4DV2', 'DPRAE8', 'DX8CD2', 'DZRBH8', 'DY5F11', 'DPMAE9', 'DB12E9', 'DW9235', 'DU09J2', 'DB9CD5', 'DB0A04', 'DK3DC9', 'DZ5BN9', 'DX9CD8', 'DW5F15', 'DT4418', 'DK4CC5', 'DB4A04', 'DAACK6', 'DPRAEO', 'DPRAE0', 'DB0A03', 'DV5817', 'DB0E06', 'DK4DV5', 'DW3FV0', 'DV581X', 'DLBYV6', 'DW3FV5', 'D31357', 'D31356', 'DW3FV6', 'DBZSV3', 'DK3DCX', 'DW3FV2', 'DX8F5X', 'DB9CD2', 'DM6262', 'DAR9K9', 'DV5813', 'DW5F10', 'DF4DV4', 'DB2C03', 'DV5811', 'DLBYV9', 'DX9CD9', 'DX6CD6', 'DV5810', 'DU09J8', 'DW5F19', 'DZRFH9', 'DV5418', 'DZ5BN4', 'DLBYV3', 'DB0E0X', 'DF4DV1', 'DLBYV5', 'DLBJV3', 'DLBJVX', 'DB4A08', 'DK3DC8', 'DFREV0', 'DAACK3', 'DB9CDX', 'DK4DV8', 'DX6CD8', 'DF4DV8', 'DWSF11', 'DW541X', 'DW3FVX', 'DX8CDX', 'DT4414', 'DX8FSO', 'DT4817', 'DK4DV3', 'DX6CD2', 'DK3DC5', 'D2DF62', 'DB4A01', 'DM6261', 'DX8CD9', 'DB8CD2', 'DB9CD4', 'DF4DV6', 'DS43A2', 'DZ3DC4', 'DZ6266', 'DW3FV8', 'DB0E02', 'DM6266', 'DX8CD8', 'DZ3DC2', 'DX9CD7', 'DB0A06', 'DF4DV9', 'DT4410', 'DW5413', 'DZ3DCX', 'DF9EVO', 'DK4DV4', 'DB8CD0', 'DK4DV7', 'DB9CB0', 'DU09J1', 'DD21A7', 'DK4DVX', 'DU09J4', 'DF4DV0', 'D3DF60', 'DZ3DC9', 'DK4DV1', 'DF4DV2', 'DWRFV8', 'DZRBH7', 'DB0E00', 'D31353', 'DD2EY5', 'DT3MW5', 'D1RFV8', 'DV5413', 'D3DF64', 'DZ3DC8', 'DB6CD5', 'DD23S0', 'DE6261', 'DLBZV1', 'DV5414', 'DF4DV3', 'DFREV8', 'DW5G10', 'DWSF10', 'DB4C03', 'DX6CD3', 'DZ5BN1', 'DB9CB2', 'DTPUKX', 'DS41A0', 'DT4813', 'DX8CD0', 'DB4A03', 'DWRFV2', 'D31352', 'DY5G14', 'DY5G10', 'DZ3DC5', 'DZ6262', 'DE626X', 'DK3DC4', 'DE1675', 'DX9CB3', 'D541A0', 'DPRAE2', 'DB0A09', 'DB9CB6', 'DB9CBX', 'DW5G19', 'DE6269', 'D4MBE1', 'DB0G02', 'DB9CB5', 'DB9CB9', 'DB9CD1', 'DX8CD3', 'DT4816', 'DB8FS6', 'DB8FS4', 'DV5819', 'DM6268', 'DB0A0X', 'DB6CD2', 'DZ5BN0', 'DZSBNO', 'DFREV3', 'D31354', 'DM6265', 'DKJA05', 'DT4815', 'DB4A0X', 'DL25R5', 'DB0G03', 'DB0C03', 'DW5G17', 'DM6263', 'DBWG30', 'DLBYV4', 'DB12E4', 'DV5410', 'DR32T0', 'DB24B1', 'DWRFV0', 'DX8F52', 'DAABG0', 'DPMAE7', 'DK4CC2', 'DB41S7', 'DPRAE1', 'DT4819', 'DU09J7', 'DB0E0S', 'DW5G15', 'DJ81W4', 'D4MBE3', 'DX6CD4', 'DM6260', 'DLBJV8', 'DX6CD7', 'DB4A07', 'DAABG9', 'DW5G11', 'DP21A2', 'DW51E8', 'DM6269', 'DB12E3', 'DV5812', 'DZ6260', 'DY32T7', 'DF4EVO', 'DB4A06', 'DX8FSB', 'DY5G13', 'DH88W4', 'DBZSV4', 'DPRAE7', 'DG61E8', 'DE4EV6', 'DY5G16', 'DW12S6', 'DZ5BN3', 'DB0A05', 'DPMAE4', 'DT4419', 'DW5416', 'DJ81W1', 'DD82A3', 'DX6CD0', 'DW5G13', 'DAACK8', 'DX6CD5', 'D4RBE2', 'D4MBE0', 'DZ5BN5', 'DK3DC1', 'DAAAG2', 'DZ1FB1', 'D4MBE9', 'DB0A08', 'DY5G18', 'DX8F55', 'DW5410', 'DLBJV7', 'DBOE08', 'DK4CC1', 'D13FV4', 'DF4EB5', 'DY5G15', 'DR32T1', 'DB8CD8', 'DZ3DC7', 'DX2266', 'DAACK7', 'DB4A00', 'DX8F59', 'DFREVO', 'D31350', 'DM5F18', 'DPRAE5', 'DB0A00', 'DA1AB2', 'DXBFS8', 'DU09T3', 'DV5411', 'DH88X7', 'DX6CD1', 'DB0C09', 'D3135X', 'DZ626X', 'DB12E5', 'DZ6269', 'DZ6263', 'DX8CDO', 'DA31A8', 'DB0C00', 'DB21B2', 'DAACK2', 'DW11S8', 'DPMAE1', 'DX22GO', 'DZRBH4', 'DK4CC0', 'DK3DCO', 'DM626X', 'DJ81W2', 'DX1H24', 'DB12E2', 'DX8F51', 'DL39M9', 'DD22S5', 'DX2269', 'DX2267', 'DPMAE0', 'DLBZV3', 'DR32T8', 'DB0AOX', 'DB8CDX', 'DW12SX', 'DT5417', 'DX6CBX', 'DF4EUX', 'DF9EVI', 'DT4812', 'DX6CDO', 'DBYSVX', 'DXBCD6', 'DF4DV5', 'DX9CDB', 'DM5F16', 'DLBZV8', 'DB2A07', 'D4MBEX', 'DB4C00', 'DN1363', 'DLBJV4', 'DB4C08', 'DN56A0', 'DB2A09', 'D6RFV5', 'DY38T0', 'DW5G14', 'DW12S5', 'DSKFCX', 'DB8FS7', 'DH4CDX', 'DYSF18', 'DK3EH7', 'D4MBE6', 'DLBZV7', 'DZK23C', 'DJREV1', 'DLBZVX', 'DK4CC4', 'DARTK7', 'DZ3DC3', 'DYSF10', 'DXBFS5', 'DZ5BN7', 'DWRFV9', 'DX8F50', 'D4MBE7', 'D23DC5', 'DE82A0', 'DB4A02', 'DP21A5', 'DV5814', 'DBYSV3', 'D4MBE4', 'DX9CDS', 'DB8CD7', 'DT4810', 'DN1366', 'DX8F57', 'DAABG4', 'DB9CB7', 'DZ5BN8', 'DM6267', 'DT4811', 'DK4CC3', 'DCRFH0', 'DB0A01', 'DT441X', 'DX9CB2', 'DGRFH6', 'DW11S0', 'DBZSV5', 'D4RBE9', 'DB8CD6', 'DK4CC6', 'D4MBE5', 'DFAEV9', 'DW12S4', 'DV09J4', 'DBZSV9', 'DAACK0', 'DB2C05', 'DY5G19', 'DYSF1X', 'DB8CD9', 'DLBJVO', 'DLBJV0', 'DLBJV1', 'D89CD7', 'D89CD3', 'D258N8', 'DB21BX', 'DB12E0', 'DKJA01', 'D23DC2', 'DK3EH1', 'DB9CB1', 'DR32T4']
  Model_Year: ['L', 'M', 'R', 'K', 'J', 'C', 'H', 'S', '7', 'P', 'N', 'D', 'E', '8', 'F', 'G', '9', 'A', 'B', '5', 'X', '6', 'T', '3', 'Y', '2', '1', '4', 'W', 'V']
  Plant_Code: ['0', '5', 'S', 'D', 'X', 'W', 'G', '2', 'Y', '4', '8', 'J', '3', 'T', 'V', 'Z', 'U', 'P', 'H', 'L', 'M', 'O', 'K', '6', '9', 'R', '7', '1']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,FORTUNER,4.0,SUV,D,EXR,GCC,5.0,MHF,DX8FS9,L,0,103088
1,TOYOTA,FORTUNER,4.0,SUV,D,EXR,GCC,5.0,MHF,DX8FS2,M,0,111888
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,D,GL2,GCC,4.0,MRO,DB9CD3,R,5,014183
3,TOYOTA,SEQUOIA,8.0,SUV,D,SR5 (NON GCC),GCC,5.0,5TD,DY5G1X,K,S,166905
4,TOYOTA,RAV4,4.0,SUV,D,VXR,GCC,5.0,JTM,DF4EV3,J,D,234929
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6554,TOYOTA,COROLLA,4.0,SEDAN,D,STD (NON GCC),NON-GCC,NaN,JTD,DPRAE2,L,J,080895
6555,TOYOTA,RAV4,4.0,SUV,D,VXR,GCC,NaN,JTM,DF4EV3,J,J,210907
6556,TOYOTA,TUNDRA,8.0,PICKUP,D,STD (NON GCC),NON-GCC,NaN,5TF,DY5F19,F,X,431119
6557,TOYOTA,RAV4,4.0,SUV,D,VXR,GCC,NaN,JTM,DF4EV0,J,J,194584
6558,TOYOTA,TUNDRA,8.0,PICKUP,D,STD (NON GCC),NON-GCC,NaN,5TF,DW5F1X,H,X,624341

====================================================================================================
POS4: A
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'TUNDRA', 'VELOZ', 'RAIZE', 'CAMRY', 'CROWN', 'COROLLA', 'HILUX', 'PRADO', 'DYNA', 'INNOVA', 'FORTUNER', 'HIACE', 'TOYOTA VELOZ', 'COROLLA 1.3', 'COROLLA CROSS', 'LAND CRUISER PRADO', 'AVALON', 'BZ4X', 'YARIS', 'بريفيا', 'PRIUS', 'TOYOTA PRIUS', 'COROLLA 1.6', 'RAV4', 'SEQUOIA', 'ALPHARD', 'FJ CRUISER', 'TACOMA', 'BZ 4', 'COASTER', 'TOYOTA COROLLA', 'HIGHLANDER', 'ALLION', 'DAINA', 'COROLLA 1.8', 'MODEL 2022', '25 CA SON P 2.5L AT', '26 YA HB P 1.6L AT TURBO GR RA(CAR)', 'ECHO', 'GXL RA (STATION WAGON)', '25PR 5 DR P 2.4L AT', 'WIGO', 'SIENNA', '4RUNNER', 'MIRAI', 'COROLLA SEDAN', 'CAMRY HYBRID']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'SEDAN', 'PICK UP SINGLE CAB', 'PICKUP', 'PICK UP', 'MPV', 'MINI BUS', 'STATION', 'SUV- CROSSOVER', 'HATCHBACK', 'VAN', 'PANEL VAN', 'SALOON', 'BUS', 'COUPE', 'WAGON', 'PANEL VAN HIGH ROOF']
  pos4: ['A']
  trim: ['GXR', 'VXR', 'STD (NON GCC)', 'EXR', 'GX', 'TURBO G RA', 'E', 'LIMITED', 'PREMIUM', 'XLI EXECUTIVE MR', 'XLE', 'DLX', 'VX', 'ADVENTURE', 'GLE HEV', 'BLACK EDITION', 'GLE', 'STD', 'GXL', 'PLATINUM', 'GX MID', 'GXR2', 'GLI', 'HEV', 'GR SPORT', 'TXL1', 'XLI', 'SE', 'TXL3', 'E PLUS HEV', 'TOP', 'XLI EXECUTIVE', 'DX', 'DLX TOP', 'HEV GLI', 'GLX', 'GXR1', 'XLI EXECUTIVE HEV', 'GR-S', 'GXR TOP', 'LE HEV', 'XLI MID', 'DL', 'XL', 'TXR', 'PRO', 'GRANDE', 'GR', 'TX1', 'SEDAN', 'LE', 'GXR SOD D/AC AW', 'LIMITED HEV', 'S', 'GXR4', 'XLI POWER OPT', 'GL', 'SE+', 'DLS', 'XLI - AW', 'TURBO G', 'GXR-V', 'XLI TOP', 'SPORT', 'G', 'BASE', 'LUMIERE HEV', 'SR5 (NON GCC)', 'TRIM', 'VXR BASE', 'HYBRID (NON GCC)', 'GLI TOP', 'LUXURY', 'HYCROSS', 'VX MID', '10TH VICTORY EDITION', 'GL LIMITED', 'SS', 'GXL 1ST EDITION', 'LE (NON GCC)', 'VIP7', '45', 'GXR3', 'GLI MR HEV', '1500', 'AMBIENTE', 'TRD', 'ADVENTURE 1ST EDITION', 'AMG', 'SL', 'LS', 'DTD', 'CTD', 'GLS', 'GXR FMST', 'GLI HEV', 'SGLX', 'MID', 'XLI ', 'SALOON', '1', 'ADVENTURE 1ST EDITIO', 'XLI HEV']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTM', '5TF', 'MHF', 'MHK', 'JTN', 'JTD', 'LFM', 'JTF', 'JTE', 'JT4', 'MR0', '4T1', 'YV2', 'JN8', 'JT2', 'JN6', 'MRO', 'GTF', '1NX', '7MU', '2T1', 'JT3', 'STF', '2T3', '7SV', '3TM', 'JHH', 'MD2', 'JIM', 'LEF', 'MB1', 'LET', 'JTG', 'LS4', 'YV1', 'JE3', 'ZFC', 'JA3', '123', 'LM6', 'LSF', 'MKH', '5N1', 'LK6', 'LMX', '1G6', '5TD', 'IN6', 'INB', 'LSJ', 'K1K', '6TF', 'A25', 'WVW', 'W1K', 'MBI', 'MBT', 'MFF', 'HJ4', 'JHG']
  VDS: ['AUBBJ1', 'ABBBJ0', 'AB7BJ0', 'AB7BJX', 'AY5F17', 'AUCBJ2', 'AUCBJ0', 'ABBBJ3', 'AUCBJX', 'AUCBJ6', 'AB7BJ6', 'AUCBJ8', 'AW5F13', 'AB1BY2', 'AA1BA4', 'AA1BA1', 'AB1BAX', 'AG4CK1', 'AUCBJO', 'ACABF5', 'AAA0C7', 'AFAAF1', 'AB7BJ7', 'AM4968', 'AB1BA5', 'AUCBJ7', 'AM29J2', 'AB1BY1', 'AY5F19', 'AY5F11', 'AB7BJ5', 'AUCBJ9', 'AY5F14', 'AACAJ8', 'AB7BJ3', 'AB7BJ4', 'AUBBJ2', 'ABBBJ6', 'AW5F11', 'A14CK1', 'AUBBJ0', 'AA1BA8', 'AU7BJ7', 'ABBBJX', 'ABBBJ9', 'ABCBJ8', 'A14CK7', 'AACAJ6', 'AU7BJ4', 'AG4262', 'ABBBJ2', 'AY5F1X', 'AB1BA9', 'AY1179', 'AUBBJ4', 'AA1BA6', 'AB1BY3', 'AACAJ3', 'AB7BJ2', 'AU7BJ0', 'AFAAF0', 'AM29J8', 'ABBBJ7', 'AU7BJX', 'AU25J2', 'ABCBJX', 'AW12G5', 'AB1BY5', 'ACABF6', 'AUBBJ7', 'AA1BA2', 'AU25J6', 'A18097', 'AB7BJ8', 'ABBAAX', 'ABBBJ1', 'ACABFX', 'AB7BJ9', 'AG4261', 'AAA0C5', 'AACBJ1', 'AUBBJ3', 'AABBJ0', 'AB1BY0', 'AU25J7', 'AG4266', 'AUBBJ5', 'AA1BA5', 'AB1BY6', 'A14CK3', 'AACAJ4', 'AW5F16', 'AG4264', 'AM4960', 'AUCBJ3', 'AUCBJ1', 'AB1BY4', 'AUBBJ6', 'AAADC3', 'A11AK9', 'AU25J5', 'ABBBJ4', 'AG4263', 'ABCBJ1', 'AABBJ7', 'AB1BA4', 'AACAJ0', 'AB1BA2', 'ABBBJ8', 'A14CK4', 'AACAJ9', 'AU25JX', 'AW5F19', 'ABBBJ5', 'AA1BA7', 'AL29J3', 'AA1BA3', 'AY5F10', 'AB1BA6', 'AU7BJ9', 'AU25J1', 'A4DAA6', 'AA9AJ6', 'AU7BJ1', 'AB1BY9', 'A180C1', 'AY5F18', 'AB7BJ1', 'AA1BA0', 'AA9AJ0', 'AG4CK5', 'AG4CK0', 'AU7BJ8', 'AFAAF4', 'AG4268', 'AZ4966', 'A14CK5', 'AM496X', 'AYT30L', 'AW12G9', 'AAA0CX', 'AG4CK3', 'A14CKX', 'AG4CK6', 'A14CK9', 'AU7BJO', 'AU7BJ2', 'AUCBJ5', 'AUBBJ9', 'AU25J9', 'AC7BJ4', 'AUCBJ4', 'AAA0C6', 'AU88JX', 'A14CK0', 'AE09V9', 'AL29J8', 'AY5F16', 'AW12G2', 'AE54S5', 'AAAAF7', 'AB7BJS', 'AABBJ3', 'AG4265', 'AU25J4', 'AU7BJ5', 'AAA0C9', 'AB1BY8', 'AUBBJ8', 'A14CK2', 'ABIBY7', 'AB1BY7', 'AG4269', 'AA1BA9', 'ASACK7', 'AM29J5', 'A14CK6', 'AU7BJ6', 'AACAJX', 'AABBJX', 'AFAAF7', 'AM4966', 'A1ACC6', 'AA1BAX', 'AA9AJ3', 'AB1BA3', 'ABCBJ3', 'AU7BJ3', 'AE00B6', 'ABCBJ4', 'AFAAF6', 'AB1BA1', 'AXACC2', 'AW12G4', 'ACABF2', 'AUBBJX', 'AG4CK2', 'AM4967', 'A4DAC2', 'A4B2A2', 'AAA0C8', 'ABCBJ5', 'AG4CK9', 'AE52SX', 'AY5F13', 'AABBJ6', 'AU25J3', 'AL1CCX', 'AM29J4', 'AFAAF5', 'AM29J0', 'AG4CKO', 'A14CK8', 'AACAJ2', 'AE00B7', 'ARE0C6', 'AG426X', 'AX12G8', 'AAA0C4', 'AX12GX', 'AAAAG3', 'AY5F15', 'AM4964', 'AE09B3', 'AL1CC9', 'AA9AJO', 'AACAJ5', 'AAYAJO', 'AZ1FBX', 'AAAAA9', 'AAA0C2', 'AW5F1X', 'AAAAG2', 'ABBBJO', 'AB1BYX', 'AAAAG9', 'AACAJ1', 'AY5F12', 'AG4CK4', 'AM4963', 'AW5F12', 'AU25J0', 'AW12G8', 'AX12G0', 'AG4CK7', 'ABBAA6', 'A1ACC2', 'AG4CKX', 'AB1BA0', 'AG4CK8', 'AL1CC6', 'AL1CC4', 'AL29J2', 'AA7BJ1', 'ABBAA7', 'AN95J8', 'A4B3A9', 'AG30AX', 'A4DMA4', 'A4B2A6', 'ABBAA8', 'AB1BA8', 'ABCBJ7', 'AM29J3', 'AE04B7', 'A4CFA7', 'ACABF9', 'AAA0C1', 'AG4267', 'AXACC6', 'AF4E31', 'AXACC0', 'AC11R8', 'AACAJ7', 'ABBBJI', 'ACAAU6', 'A1ACC0', 'AAABG0', 'AACBJ3', 'AL29J1', 'AM29J6', 'AACBJX', 'AE09V6', 'AE09B5', 'AG4260', 'A4B3A5', 'AAA0C3', 'A180C2', 'AP22C1', 'AX12G1', 'AE09B7', 'ACAAUX', 'AB1BYO', 'AX12G7', 'AL29J5', 'ABBAA5', 'AABBJ2', 'AG4CKI', 'AE04B3', 'AE04B2', 'ACABF0', 'AU25J8', 'AM29J7', 'AUBBJO', 'AE04B8', 'AAAAFO', 'AW5F17', 'AAABG9', 'AM4961', 'ABBAA9', 'AA9AJ7', 'A64261', 'A4B3AX', 'AL29J4', 'AL29J0', 'A1ACCO', 'AE09B0', 'AL29J6', 'AW1269', 'AE09B4', 'AW5F15', 'ASG0A9', 'A180C3', 'ABCBJ6', 'AUTBJ4', 'A1RFV4', 'AW12GX', 'ABCBJ0', 'AA9AJ2', 'AAABA7', 'AE52S1', 'A1ACC5', 'AW5F18', 'AE09B2', 'AZ5CN7', 'AZ4961', 'ACJ4H1', 'A14CKO', 'AACBJ9', 'ARE2C0', 'AE00E5', 'AE04B9', 'AE04B4', 'AEACH7', 'ABCBJ2', 'AFAAF2', 'AAAAF4', 'AW12G7', 'ABBAA2', 'AM4969', 'AA9AJ4', 'A22EZ3', 'AAA0C0', 'AG20A8', 'A4CEA2', 'AACBJ2', 'AX12G2', 'AFAAF9', 'AL1CC5', 'AP22CX', 'AB1BA7', 'AACAJO', 'AE00B1', 'AM4962', 'AE04B6', 'AXACC5', 'AX12G9', 'AUCBJG', 'A1RFV2', 'ABBAA1', 'AX12G6', 'AX12G5', 'AA9AJ9', 'AE04B0', 'AFCG23', 'A4B3A8', 'A180C0', 'AC7BJ7', 'ACABF1', 'AE00EX', 'ABCBJ9', 'A1ACC1', 'AACBJ7', 'AE82G3', 'AN95J9', 'AE04B1', 'AW5F10', 'APE2C8', 'AAAAA2', 'AABBJ1', 'AACBJ8', 'AB7BJO', 'AE52S6', 'AE5256', 'AL29J7', 'AFAAF8', 'A818Y7', 'AUCBJS', 'AACBJ0', 'AA7BJO', 'AA7BJ0', 'A64264', 'A4CFA5', 'AABBJ9', 'AE09W0', 'AABBJ5', 'AG34L4', 'AA1BAO', 'AE2KP8', 'AL29JX', 'AW12G1', 'AZ5CN2', 'AA7BJ2', 'AS14U0', 'A1ACC3', 'A878J9', 'ABBAA0', 'ACABF7', 'A1RFVX', 'AE09BX', 'AL29J9', 'AAAAF2', 'AE51S4', 'AE09V4', 'ABBAA4', 'AYACC6', 'AAABA9', 'AE00E6', 'AAABA2', 'AP86C4', 'ABBAA3', 'AE09EX', 'AP86C7', 'AX12G4', 'AW12G6', 'ARE0C9', 'AE54S0', 'AFAAF3', 'AU88J0', 'AE09B8', 'ACABF8', 'AE09E2', 'AE54S7', 'AE04B5', 'AABBJ4', 'AC7BJ3', 'A14CKB', 'AM4965', 'AABBJ8', 'A180C8', 'AECG27', 'AZ4964', 'AC22C6', 'AE53S2', 'AAABG5', 'AW5F14', 'A1RFV5', 'A180C6', 'AFCG24', 'AAAAG4', 'AL1CC2', 'AE1BYE', 'AA9AJ1', 'AYACC9', 'AL1CC3', 'AE09B6', 'A888J6', 'AZ496X', 'AE09V3', 'AECB83', 'AA7BJ9', 'AYACC3', 'AACBJ5', 'ASB3R9', 'AS47HB', 'AAABG2', 'AP22C2', 'AX12G3', 'AE09V0', 'AE09V7', 'AZ5CN8', 'AB36U5', 'AE04E8', 'ARE2C6', 'AU7BJI', 'AAABA6', 'AE52S0', 'AY86C7', 'ACABF3', 'AE09B9', 'A180C5', 'AU78J8', 'AE00B5', 'AXACC9', 'A4MBE6', 'AFAAFX', 'AG34L8', 'AP86C3', 'AECB80', 'AC22C2', 'A180CX', 'AXACCO', 'AACBJ4', 'AI4CK5', 'AM4501', 'AA9AJ5', 'AXACC7', 'AE04E1', 'AE09W2', 'AFZBG2', 'A11CX7', 'AM4981', 'AN74K3', 'AE09V2', 'AAABA3', 'AS12G0', 'AB1BAO', 'AZ1FB2', 'AL1CC7', 'AAABA4', 'AECG33', 'AE00B3', 'A1RFV6', 'AP86C6', 'ARCAJ3', 'AE09W8', 'AAABGX', 'AS1232', 'AC1DM8', 'AF54K3', 'AM29J1', 'ARE0C3', 'AW12G0', 'AA9AJX', 'AYACC7', 'AB1BYB', 'AE52S5', 'AFABF9', 'AL1CC8', 'AAAAFX', 'AUBBJS', 'AG34L2', 'ACABF4', 'AACAJA', 'AM11H6', 'AE00E3', 'ARE2C4', 'ACAAJ4', 'AB18Y8', 'AAAOC8', 'A878J5', 'AE09E6', 'AE04E9', 'AA7BJ7', 'AE94K3', 'AZ4965', 'AE09E9', 'AAABA5', 'AA7BJX', 'AY1173', 'AG426U', 'AC7BJ0', 'AP90A2', 'AY2NY7', 'AEAA16', 'AKCB80', 'AE09B1', 'AA7BJ5', 'AU88J2', 'AW1267', 'AT2MVX', 'AP86C0', 'ADAE2X', 'AECB89', 'ASW0AX', 'ARE2C5', 'AZ1FB9', 'AECB82', 'A14AFX', 'AE51S0', 'AA5RX7', 'AE52S3', 'AAAB58', 'A4B5A4', 'AM11H1', 'AE09W3', 'AK54K5', 'AAAAG7', 'AE04BX', 'AEACH0', 'AE07B9', 'AAAAG6', 'AXACC3', 'AAAAF5', 'AE09E4', 'A22NE1', 'AZ4968', 'A180C4', 'AG34L7', 'AE52S7', 'A888J9', 'A818Y5', 'AP22C4', 'A16E36', 'AUZBJ7', 'AXACCX', 'AA9AJ8', 'AY117X', 'AX1269', 'AE00E1', 'AE09W5', 'AAAAG1', 'A1RFV9', 'A11CY2', 'ARE0C2', 'AABAJO', 'ARE2C2', 'AA18A8', 'AS02A5', 'AUF0A9', 'AZ4967', 'AJ54K5', 'AE09VX', 'AT1237', 'AUBB38', 'AC7BJ6', 'AF4E34', 'AACAJI', 'AVV5F1', 'AAN6E8', 'A11CX6', 'A11CX0', 'AC22C4', 'AAABAX', 'AZ4963', 'AALAJA', 'AR05Y8', 'AW12G3', 'A4RBE2', 'AB7RJ4', 'AP86C8', 'A1ACC9', 'AE00E7', 'A4DF5F', 'ASB3R8', 'A1RFV0', 'AYACC8', 'AX5GNX', 'A11CX1', 'AF4E36', 'AX8CD9', 'AU78JX', 'AAIBA6', 'ACABFO', 'AU88J9', 'ABFAJ7', 'A4DAA2', 'AA7BJ6', 'AATBA9', 'AZ4969', 'A0B982', 'AFAAFO', 'AM2AH8', 'AL1CC0', 'AE94A8', 'AU7BJT', 'ARE0C4', 'AA7BJ3', 'AA18A6', 'AN95J2', 'AAAAF8', 'AZ4960', 'A4CFA2', 'AUBBJB', 'AF4CB8', 'AA1AB4', 'AN95JX', 'ABCBJO', 'AB7BJZ', 'AR9AJ2', 'ARE0C1', 'A64265', 'AC7BJ9', 'AG34L1', 'AG34LI', 'AC1DM7', 'AG34L3', 'AM29J9', 'ABBBJB', 'AX1268', 'AE54S1', 'AE09E7', 'ABFAJ0', 'AFCG28', 'AP54K3', 'AZ5CNO', 'AE04E6', 'AZ5CN0', 'ACAAU7', 'AUBBJN', 'AX5GN8', 'AS02D0', 'AP54K2', 'AA1BAB', 'AN95J6', 'AAAAF1', 'AB7BJB', 'AS12G9', 'AXACC4', 'AG34L9', 'AU88J6', 'AUCBJA', 'AECB85', 'AECB84', 'AAAAF0', 'AE1EYX', 'A4DAA9', 'AP22C5', 'AS02D8', 'AE04BZ', 'A180C7', 'AC22CX', 'A878J7', 'AGACH8', 'AU7BJS', 'A64266', 'A4DAA3', 'A4CEA8', 'AS02A4', 'A4B3A2', 'ABBDH7', 'A4DAAX', 'AZ5CN5', 'AE09WX', 'ACAB52', 'AS02A2', 'A4DBAX', 'A4CFA3', 'AE09V8', 'AAAA55', 'A1RFV8', 'ACAAU3', 'AA9AJZ', 'ASW0A9', 'AF047X', 'AP86C2', 'ARE0C0']
  Model_Year: ['R', 'N', 'J', 'P', 'S', 'E', 'T', '5', '3', 'G', 'H', 'F', '2', 'Y', '4', 'C', 'K', '9', 'L', '7', '8', '6', 'M', 'X', '1', 'D', 'V', 'A', 'B', 'W']
  Plant_Code: ['4', 'X', '3', 'J', '0', 'K', 'U', 'B', 'W', '5', 'Z', 'V', 'C', 'A', '1', 'M', '8', '2', 'H', 'D', 'R', '9', '6', 'G', 'Y', 'S', 'F', 'N']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,AUBBJ1,R,4,057596
1,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,ABBBJ0,N,4,038683
2,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,5.0,JTM,AB7BJ0,N,4,012534
3,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,5.0,JTM,AB7BJX,N,4,056539
4,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,A,STD (NON GCC),GCC,4.0,5TF,AY5F17,J,X,712542
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11165,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AB7BJ0,P,4,084921
11166,TOYOTA,LAND CRUISER,6.0,SUV,A,1,GCC,NaN,JTM,AACBJ8,N,4,009599
11167,TOYOTA,CAMRY HYBRID,4.0,SEDAN,A,XLE,GCC,NaN,JTN,A14CK5,S,3,029562
11168,TOYOTA,LAND CRUISER,6.0,SUV,A,1,GCC,NaN,JTM,ABBBJ6,S,4,188504
11169,TOYOTA,LAND CRUISER PRADO,4.0,SUV,A,GXL,GCC,NaN,JTE,AACAJ1,S,5,008118

====================================================================================================
POS4: F
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COASTER', 'HILUX', 'RAV4', 'LAND CRUISER', 'SOLARA', 'LAND CRUISER 70', 'HIACE', 'HIGHLANDER', 'TUNDRA', 'COROLLA', 'SIENNA', 'LAND CRUISER PICKUP 70', 'SEQUOIA', 'COROLLA CROSS', 'CAMRY', 'MR2', 'AVALON', 'LAND CRUISER / STATION', '4RUNNER', 'INNOVA', 'حافلة نقل خاص', 'TACOMA', 'RAV4 LE CAR', 'TOYOTA', 'CAMRY SOLARA']
  bodyType: ['BUS', 'PICK UP DOUBLE CAB', 'PICK UP', 'PICK UP SINGLE CAB', 'SUV', 'CONVERTIBLE', 'PICKUP', 'PANEL VAN', 'SEDAN', 'MINI BUS', 'MPV', 'SUV- CROSSOVER', 'COUPE', 'HATCHBACK', 'HALF PANEL VAN', 'STATION', 'MINI BUS HIGH ROOF']
  pos4: ['F']
  trim: ['STD', 'DLX', 'GLS', 'GL', 'DLX TOP', 'LE', 'GXR MID', 'LWB HIGH ROOF', 'LWB', 'LSE', 'SWB', 'HT SWB', 'VX', '1', 'GLX', 'PLATINUM', 'STD (NON GCC)', 'XLI EXECUTIVE', 'GXR FMST', 'DX', 'GXR2', 'EXR', 'GXR', 'GXR TOP DMST', 'BUS', 'LE (NON GCC)', 'LX', 'SR5 (NON GCC)', 'HT VXR', 'STAN', 'LE HEV', 'SPORT', 'PREMIUM', 'GLE HEV', 'LE STD', 'LIMITED', 'S', 'S PLUS', 'GLE-X HEV 40TH ANNIV', 'SE+', 'SE', 'A', 'STANDARD', 'DLS', 'GX', 'XLI TOP', 'BASE', 'COASTER', 'S T2 TOP', 'XSE (NON GCC)', 'XL', 'ADVENTURE', 'ST', 'DL', 'GXR TOP', 'DC', 'HYBRID (NON GCC)', '4']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTC', 'MR0', 'MRO', '2T3', 'JTE', 'JTG', '4T1', 'JT4', '137', '5TD', '5TF', 'JTD', 'JTM', 'JT3', 'JT6', 'JN6', '5TT', '7MU', 'L7X', 'LM8', '1GD', 'JAA', 'JHD', 'JTH', '3GY', 'L3H', 'WDD', 'KMH', 'VF1', '2D4', 'JTF', 'MB0', '1GC', '2T1']
  VDS: ['FZ4182', 'FX22G1', 'FX22G3', 'FX22G8', 'FX22G2', 'FX22G5', 'FX22GX', 'FX22G7', 'FX22G6', 'FX22G4', 'FX22G0', 'F1RFV7', 'FU71J2', 'FX22G9', 'FK4180', 'FA38P8', 'FK7180', 'FX2260', 'FK5188', 'FG4265', 'FK4181', 'FB5188', 'FU71J8', 'FU71J7', 'FB5185', 'FR1197', 'FA38P3', 'FK5181', 'FK7183', 'FU71J3', 'FU73J5', 'FJ71JX', 'FM5189', 'FA9035', 'FB5181', 'FA38P5', 'FY4184', 'FK518X', 'FZRBH4', 'FY5F13', 'FK5187', 'FY4188', 'FK4185', 'FY4185', 'FB5187', 'FR22G0', 'FPMAE5', 'FY418X', 'FK5186', 'FR22GX', 'FJ71J2', 'F1RFV0', 'FR22G2', 'FK5180', 'FK418X', 'FK5185', 'FK4184', 'FA1196', 'FU71J1', 'FU73J3', 'FK4182', 'FJ60G2', 'FX00G6', 'FR22G4', 'FK4187', 'FK5189', 'FK4188', 'FR22G7', 'FK4186', 'FJ60G4', 'FB5182', 'FK5182', 'FK5183', 'FB5183', 'FM5182', 'FU73J6', 'FM4185', 'FB518X', 'FU71J4', 'FM4189', 'FM5188', 'FM5183', 'FE52S4', 'FK4189', 'FX2265', 'FM418X', 'FY4181', 'FR22G5', 'F1RFV4', 'FR22G6', 'FA38PX', 'FU71J5', 'FB5184', 'FBW415', 'FU71J6', 'FE7187', 'FY5B18', 'FK7187', 'FY4189', 'FE53S5', 'FK7182', 'FM5187', 'FK4183', 'FBABG3', 'FA1193', 'FR22G8', 'FR1193', 'FR1192', 'FX2262', 'FU71J0', 'FPEFFV', 'FX2269', 'FR3206', 'FM4184', 'F1RFV5', 'F11AK7', 'FB5180', 'F31AK7', 'FJ60G5', 'F1RFV8', 'FX2261', 'FX2266', 'FZ1FB4', 'FU73J1', 'FY4183', 'FY4186', 'FK5184', 'FU73JX', 'F11AK4', 'FM4187', 'FY4182', 'FK7188', 'FA38P9', 'FU71J9', 'FU73J2', 'FPRAE3', 'FB5186', 'FR119X', 'FM4182', 'FY5F12', 'FU5JR5', 'F7E692', 'FA119X', 'F1RFV3', 'FG15T7', 'FM4183', 'F1RFVX', 'FP14F3', 'FU73J9', 'FE54S4', 'FM4188', 'FM5181', 'FR22G1', 'FE7280', 'FD3HLS', 'FB5189', 'FM4181', 'FX02P3', 'FARAH4', 'FA1194', 'F1RFV6', 'FU5JR1', 'FJ71J1', 'FJ71J6', 'FJ71J0', 'FU73J8', 'F11AK6', 'FR3204', 'FX2264', 'FR22G9', 'FR22G3', 'FR1198', 'FK1221', 'FU71JX', 'F11BK2', 'FDABB8', 'F1RFV2', 'FA1191', 'FX226X', 'FR1190', 'FU73J4', 'F1RFV1', 'FE53S2', 'FJ71J4', 'F1RFV9', 'FZ1FB5', 'FE7189', 'FJ71J9', 'FR73J7', 'FY4180', 'FR1194', 'FH3CB1', 'FJ71J7', 'F31AK5', 'FM4180', 'FE52S8', 'FA38P7', 'FX2263', 'FM5185', 'FM5184', 'FA1198', 'FX22C2', 'FE52S5', 'F31AKX', 'FE52S6', 'FX22C3', 'F31AK3', 'FX2267', 'FK718X', 'FK7186', 'FU73J7', 'FF41CB', 'FM4186', 'FE52SX', 'FJ60G0', 'FK7185', 'F11AK0', 'FY5F10', 'FA1195', 'FE54S3', 'F6RDM1', 'FBABG2', 'FV47V6', 'FA1190', 'FX2268', 'FA38P1', 'FU73J0', 'FM5180', 'FJ60G8', 'FZRBH2', 'FR2266', 'FY5F17', 'FDA882', 'FDAB82', 'FIRFVO', 'FIRFV0', 'FF7193', 'FB7180', 'FZRBH5', 'FK7184', 'F7D196', 'FR2268', 'FW12G1', 'FJ71J8', 'FJ60GX', 'FY5A18', 'FX22GO', 'FX22P9', 'FJ71J3', 'FA1197', 'FZ1FB3', 'FJ60V8', 'F11AK8', 'FE7284', 'FK7189', 'FR1196', 'FG8JP7', 'FC24H0', 'FF22P8', 'FE22P3', 'FE7186', 'FBABG6']
  Model_Year: ['X', '8', 'C', '6', 'B', 'F', '7', 'D', '9', 'A', 'N', 'E', 'K', 'Y', '4', 'L', 'G', 'S', 'M', '5', 'J', 'H', '1', '2', 'R', '3', 'P', 'W', 'T']
  Plant_Code: ['0', '1', 'C', '4', 'U', '6', '7', 'F', 'E', '2', 'S', 'X', 'J', 'D', '3', 'W', 'V', '5', 'A', 'G', 'B', 'H', 'I']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COASTER,6.0,BUS,F,STD,GCC,2.0,JTC,FZ4182,X,0,005419
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,F,DLX,GCC,4.0,MR0,FX22G1,8,1,309219
2,TOYOTA,HILUX,4.0,PICK UP,F,DLX,GCC,2.0,MR0,FX22G3,C,1,343848
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,F,DLX,GCC,4.0,MR0,FX22G8,6,1,002465
4,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,F,DLX,GCC,4.0,MR0,FX22G2,B,1,065541
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3392,TOYOTA,HILUX,4.0,PICKUP,F,DLX,GCC,NaN,MR0,FX22G9,8,1,307332
3393,TOYOTA,HILUX,4.0,PICKUP,F,DLX,GCC,NaN,MR0,FX22G9,E,1,112696
3394,TOYOTA,HILUX,4.0,PICKUP,F,DLX,GCC,NaN,MR0,FX22G9,C,1,070219
3395,TOYOTA,HILUX,4.0,PICKUP,F,DLX,GCC,NaN,MR0,FR22G5,6,0,506472
3396,TOYOTA,HILUX,4.0,PICKUP,F,DLX TOP,GCC,NaN,MR0,FX22GX,D,1,360776

====================================================================================================
POS4: J
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'PRADO', 'YARIS', 'HILUX', 'IQ', 'ECHO', 'RAV4', 'TUNDRA', 'SIENNA', '4RUNNER', '86', 'ZELAS', 'SCION', 'LAND CRUISER', 'HIGHLANDER', 'CROWN KLUGER', 'SUPRA', 'LAND CRUISER PRADO', 'CAMRY', 'SEQUOIA', 'TACOMA', 'AVALON', 'PREVIA', 'INNOVA', 'TOYOTA', 'RAV 4', 'T 100', '2012', 'TAKOMA', 'TOYOTA SCION', 'PRIUS', 'TOYOTA IQ', 'TOYOTA SUPRA', 'TOYOTA SQUIN', '25 HX DC 4X2 P 27L AT GLX RA/PICK UP', 'T100', 'هايلوكس', 'COROLLA CROSS', 'BZ4X', 'COUPE', 'COROLLA', 'TOYOTA 86']
  bodyType: ['PANEL VAN', 'SUV', 'HATCHBACK', 'PICK UP SINGLE CAB', 'MINI BUS', 'SEDAN', 'HALF PANEL VAN', 'PICK UP DOUBLE CAB', 'MPV', 'MINI BUS HIGH ROOF', 'COUPE', 'VAN', 'BUS', 'PICKUP', 'STATION', 'MINI BUS SEMI HIGH ROOF', 'PICKUP DOUBLE CABIN', 'PANEL VAN HIGH ROOF', 'PICK UP', 'SUV- CROSSOVER']
  pos4: ['J']
  trim: ['GL', 'TX', 'STD', 'GLX', 'GXR', 'DX', 'STD (NON GCC)', 'XLI MID', 'FLEET', 'VXR', 'TX-L TOP', 'ADVENTURE', 'DX H/R W/B', 'TX-L', 'DLX', 'LE (NON GCC)', 'BASE', 'SR5 (NON GCC)', 'MID', 'GT', '1794 EDITION (NON GCC)', 'LIMITED (NON GCC)', 'TOP', 'EXR', 'VX TOP LTH', 'SE TRD AERO PK', 'SE', 'VX', 'LE HEV', 'EX', 'XLE (NON GCC)', 'SPORT', 'DL', 'GX', 'SE (NON GCC)', 'TC (NON GCC)', 'CREWMAX CAPSTONE (NON GCC)', 'XLE', 'STANDARD', 'GRD', '2400', 'PLATINUM', 'LIMITED 4X4', 'SE+', 'AUTOMATIC', 'GL TOP', 'A', 'VXR HEV', '1', 'GLS', 'C', 'EXR HEV', 'LTD HEV', 'S', 'FULL OPTION', 'DLS', 'LE', '4WD', '1500 CREWCAB SLE Z71', 'GL2', 'N', 'CAR TRIM', 'VX-L TOP', 'SR', 'PW CL', 'SGLX', 'GXR GT', '60TH', 'HYBRID (NON GCC)', 'SUPER SAFARI T1', 'FABRIC', 'GXL', '0', '4', 'SE T2', 'S T1', 'GLI', 'PRO', 'XLI', 'GXR TOP 60TH ANNIV. XTREME']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTG', 'JTE', 'JTD', 'MR0', 'JTN', 'JTM', '5TB', '5TD', 'LFM', 'JT6', 'JMY', '5TF', 'JTK', '2T3', 'VNK', 'ITG', 'JT2', 'MMB', 'MRO', 'KMH', '3TY', 'JTF', '4T1', '3TM', 'JT8', 'UTG', 'JT4', 'J1G', '5TE', 'JIG', '1ST', 'KMF', '3D7', 'YV2']
  VDS: ['JX02P1', 'JU9FJ1', 'JT923X', 'JX9CD1', 'JU3FJ3', 'JX02P4', 'JX02P9', 'JX02P8', 'JJXB01', 'JX02P6', 'JT1236', 'JX02P3', 'JT4K3X', 'JX8CD5', 'JU9FJ4', 'JU3FJ2', 'JX02P7', 'J13FVX', 'JX02P5', 'JU9FJ9', 'JX02P2', 'JX8CD8', 'JX02P0', 'JJXB03', 'JU9FJ8', 'J13FVO', 'JX8CD3', 'JU3FJ6', 'JX02PX', 'JU9FJ6', 'JU9FJX', 'JN3214', 'JX8CB7', 'JU9FJ5', 'J13FV3', 'JX8CD4', 'JX8CD1', 'JX8CD9', 'J13FV0', 'JX8CD2', 'JK4CC5', 'JJXB09', 'J13FV1', 'JU3FJX', 'JV36F2', 'JS02P8', 'JJXB05', 'JK3DCX', 'JT9037', 'JU3FJ9', 'JJXB06', 'JU9FJ7', 'JU3FJ1', 'JNP13V', 'JA5ABX', 'JK3DC0', 'JT4K36', 'JU9FJ0', 'JF5C71', 'JX8CD7', 'JJXB04', 'JX8CD0', 'J13FV5', 'JX9CD4', 'JF4DV5', 'JU3FJ4', 'JTUD34', 'JT9237', 'JF4DV0', 'JU5213', 'JTUD32', 'JJREV4', 'JT9232', 'JX8CD6', 'JU9FJ3', 'JU9FJ2', 'JF5C7X', 'JTUD38', 'JFREV5', 'JJREV6', 'J44AF1', 'J13FV9', 'JZ3DC2', 'JA5DB5', 'JK3DC3', 'JK3DC6', 'JU3FJ5', 'JF5C77', 'JU3FJ7', 'JF5C74', 'JT9030', 'JA5EC1', 'J13FV8', 'JX6CB8', 'J440F4', 'JV36FX', 'JX9CD7', 'J13FV6', 'JC5DB7', 'JJXB0X', 'JK3DC4', 'JV03J9', 'JTUD35', 'JX8CDX', 'JT1234', 'JTUD3X', 'JF5C78', 'JY5F13', 'JF5C75', 'JX9CB7', 'JX6CB4', 'JTUD33', 'JT903X', 'JZ3DC6', 'JX8CB8', 'JX6CD6', 'JJXB02', 'JX9CD5', 'JZRFHX', 'JU3FJ8', 'JT9239', 'JX6CB2', 'J13FV2', 'JD7BN2', 'JA5DB8', 'JX02PO', 'JK3DC7', 'JA82J0', 'JTUD36', 'J13FV7', 'JK3DC1', 'JZ3DC0', 'JF5C79', 'JT4K37', 'JS02P1', 'JZ3DC4', 'JF5C76', 'J13FV4', 'JU3FJ0', 'JT9233', 'JA5DB7', 'JZ3DC1', 'JT4K35', 'J1RFV8', 'JNK620', 'JF5C70', 'JX6BB0', 'JB6CD8', 'JV03J7', 'JNK650', 'JS02P6', 'JU3FJO', 'JX9CDX', 'JFREV0', 'J34AF2', 'JW30F9', 'JA5DBX', 'JJXB07', 'JW30F1', 'JX6CB9', 'JT81E2', 'JX4CN3', 'JY5G15', 'JK4DV3', 'JX8BB2', 'JJXB00', 'JT4K38', 'JA5DA3', 'JC5ECX', 'JX6CB3', 'JDAHNX', 'JX8BB9', 'JT9238', 'JX6CD1', 'J1RFV9', 'JU9FJO', 'JS02P4', 'JW5G11', 'JX02PB', 'JZ1FB8', 'JX9CD3', 'JV5217', 'JK4CC3', 'JK3DC9', 'JV5214', 'JU8FJ2', 'JUNFJ4', 'JX8CB3', 'JA81LX', 'JTUD37', 'JF5C72', 'JW30F8', 'JT4K33', 'JX8CB4', 'JA5EC5', 'JX8BB4', 'JX6CDX', 'JJXB08', 'JY5G1X', 'JX6CD4', 'JX9CD6', 'JY5G16', 'JU4GN1', 'JX6BB5', 'JW5G1X', 'JZ3DC7', 'JX9CD9', 'JX6BB6', 'J44AF0', 'J34AF6', 'J34AF7', 'JZ1FB4', 'JX9CD8', 'J1RFV2', 'JZRFH1', 'JU3FJS', 'JA82J1', 'JNK640', 'JX02PV', 'JZ3DCX', 'JZRFH2', 'JV5210', 'JX4CN1', 'JW30F6', 'JK3DC8', 'JK3DC2', 'JK3DC5', 'JC5DB5', 'JA81J7', 'JU5212', 'JY5G19', 'JU9FJB', 'JU9FJS', 'JV03J0', 'JW30F7', 'JS8CD5', 'JX6CD2', 'JC5DB0', 'J34AFX', 'JT4K30', 'JK4CC4', 'JFREV1', 'JV03JX', 'JN5BF6', 'JM11D9', 'JY09J2', 'JF5C73', 'JT9234', 'JW30F3', 'JXOZP1', 'JF4DVX', 'JX9BBX', 'JA5DA1', 'JN5BF9', 'JU3211', 'J34AFI', 'J34AF1', 'JU62N9', 'JX6CD7', 'JD7BN5', 'JT9033', 'JT4K34', 'JX9CB8', 'JN321X', 'JX6CB6', 'J1RFV4', 'JX9CB2', 'JT9235', 'JX8BB5', 'JX4GN3', 'JX9CD0', 'JBYP2X', 'JX9CB1', 'JX6CD0', 'JA81L5', 'JX8BB1', 'JA81L9', 'JA17B3', 'JX9CB9', 'JF4DV7', 'JU03J2', 'JX6CD8', 'JFREV6', 'JZ3DC9', 'JU03J3', 'JX9CB6', 'JA82J8', 'JV03J5', 'JX8BB7', 'JRKEC1', 'JW30F2', 'JTUD31', 'JC5EC3', 'JV5219', 'JK4CC1', 'JS02P2', 'JT9230', 'JX6CB7', 'JX6CD9', 'JA5DA9', 'JU3FJB', 'J23DC7', 'JRKEC5', 'JV03J8', 'JU9EJ4', 'JX8CB2', 'J13FVI', 'JX9CBX', 'JC5DB1', 'JV1ET2', 'JX6BB2', 'JX6CB0', 'JX9CD2', 'JX6CD3', 'JW5G18', 'JU9FJI', 'JU5219', 'JX9CB4', 'JFREV3', 'JX8BB0', 'JA5DB6', 'JA5DB3', 'JV5218', 'JY5G18', 'JT05J0', 'JA82J9', 'JW5G14', 'JT9236', 'JK4CC2', 'JA5DA7', 'JA82J5', 'JT9036', 'JW3EH0', 'JN3216', 'JJREV2', 'JXQ2P1', 'JT1233', 'JT9032', 'JW5G10', 'JZ3DC3', 'JD7BN8', 'JJX801', 'JS02PX', 'JC5DB4', 'JKRFH5', 'JU9FI0', 'JV5216', 'JA82J3', 'JTUD30', 'JT9034', 'J11BK7', 'JU9F10', 'JNKG2Q', 'JU03J7', 'JK02P2', 'JTU031', 'JZ1FB3', 'JM30D3', 'JC5DB9', 'JM11D3', 'JX8CB5', 'JA5DB4', 'JT9231', 'JU03J5', 'JY5G11', 'JF4DV1', 'JA5DB1', 'JV5213', 'JA5EC8', 'JUGFJ3', 'JK4CC0', 'JX6BB7', 'J4CMA4', 'JA5EC6', 'JF4DV3', 'JU3218', 'JT5218', 'JX8CB0', 'JK4DV0', 'JV5211', 'JX6CBX', 'J34AF8', 'JU62NX', 'JX6CB5', 'JF4DV6', 'JX6BB8', 'JU9EJ2', 'JU03J6', 'JR14T8', 'JX8BB3', 'JK3EH1', 'JC5DB8', 'J1RFV1', 'JA5EC4', 'JX8BBX', 'JA81J8', 'JFSC78', 'JS02P9', 'JT9K39', 'J4CFC7', 'JX8CB9', 'JXO2P1', 'JU09J0', 'JU03J0', 'JV521X', 'JA5DAX', 'JA81L7', 'JB6CB4', 'JA81J1', 'JW30F5']
  Model_Year: ['C', 'D', '8', 'K', 'F', 'A', 'B', '7', '9', '5', 'N', 'E', 'S', '6', 'H', 'G', '3', 'J', 'P', 'R', 'L', 'M', '4', 'X', 'T', '1', 'Y', 'V']
  Plant_Code: ['0', 'K', '5', '4', 'J', '3', 'D', 'S', 'A', 'X', 'W', '2', 'C', '1', 'U', 'T', 'M', 'Z', 'G', 'Q', 'B', '9']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,PANEL VAN,J,GL,GCC,5.0,JTG,JX02P1,C,0,041237
1,TOYOTA,PRADO,4.0,SUV,J,TX,GCC,3.0,JTE,JU9FJ1,D,K,050098
2,TOYOTA,YARIS,4.0,HATCHBACK,J,STD,GCC,3.0,JTD,JT923X,8,5,148324
3,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,J,GLX,GCC,2.0,MR0,JX9CD1,K,4,200384
4,TOYOTA,PRADO,4.0,SUV,J,GXR,GCC,3.0,JTE,JU3FJ3,F,K,080283
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5813,TOYOTA,YARIS,4.0,HATCHBACK,J,TOP,NON-GCC,NaN,JTD,JT4K38,A,5,308094
5814,TOYOTA,ZELAS,4.0,COUPE,J,MID,GCC,NaN,JTK,JF5C76,B,3,016366
5815,TOYOTA,TUNDRA,8.0,PICKUP,J,STD (NON GCC),NON-GCC,NaN,5TF,JV5219,8,X,003104
5816,TOYOTA,RAV4,4.0,SUV,J,ADVENTURE,GCC,NaN,JTM,J13FVX,M,D,083943
5817,TOYOTA,LAND CRUISER PRADO,6.0,SUV,J,TX-L,GCC,NaN,JTE,JU9FJ5,D,5,044609

====================================================================================================
POS4: R
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'HIACE', 'TUNDRA', '4 RUNNER', 'TACOMA', 'LAND CRUISER', 'HILUX', 'YARIS', '4RUNNER', 'CAMRY', 'SIENNA', 'TANDRA', 'COROLLA', 'MT 03', 'COASTER', 'INNOVA', 'HAI LUX']
  bodyType: ['SUV', 'PANEL VAN', 'MINI BUS', 'PICK UP DOUBLE CAB', 'HALF PANEL VAN', 'PANEL VAN HIGH ROOF', 'MINI BUS SEMI HIGH ROOF', 'MINI BUS HIGH ROOF', 'STATION', 'PICKUP', 'VAN', 'HATCHBACK', 'SEDAN', 'MPV', 'PICK UP SINGLE CAB', 'BUS', 'MOTORCYCLE', 'AMBULANCE', 'SALOON', 'PICKUP DOUBLE CABIN']
  pos4: ['R']
  trim: ['GXR', 'EXR', 'GL', 'DX', 'GX', 'VX', 'XLE', 'STD (NON GCC)', 'LE HEV', 'GLS', 'GLX', 'DLX', 'BE', 'DLS - STD ROOF', 'CTD', 'BASE', 'SR5 (NON GCC)', '1500', 'GXR TOP DMST', 'GL2', 'STD', 'MID', 'DL', 'LIMITED', 'LE', 'GXR2', 'XLE (NON GCC)', 'HILUX', 'XLI', 'TOP', 'S', 'S TRD SPORT PK', 'GLI', 'STANDARD', 'VXR', 'DLS', 'EX', 'SE', 'ASAD', 'LWB HIGH ROOF', 'XLI MID', 'GR-S', 'BLACK EDITION', 'GXR FMST', 'SL', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTM', 'JTF', 'JTG', '2T3', '5TF', '5TB', 'JTE', '3TY', 'JT4', 'MA1', 'MAF', '4T3', '4T1', '2C4', '1D7', 'RKL', 'JT6', 'MH3', '1C6', 'RKT', 'LKL', '1TG', '1C8', 'JH2', 'LA6', 'MR2', 'ZT3', 'MC2', 'JTD', '5TE', 'MR0', 'STF', 'STB']
  VDS: ['RF9EV1', 'RF9EV5', 'REREV2', 'RMFAP7', 'RX12P6', 'RFREV8', 'RFR3V8', 'R6RFV9', 'RMFAPX', 'RF9EV9', 'RFREVX', 'RX12P5', 'RX12P7', 'RF9EV8', 'RF9EV3', 'RF9EV2', 'RF9EVX', 'RWRFV4', 'RX12P2', 'RMFAP9', 'RY5F14', 'RMFAP6', 'RWRFV0', 'R1RFV4', 'RX12P4', 'RX12PX', 'RMFAPO', 'RT3412', 'RX12P9', 'RX12P1', 'RW5F14', 'RX12P3', 'RM5F18', 'RY5F13', 'RFREV1', 'RJREV6', 'R13FV1', 'RMFAP4', 'RY5F1X', 'RFREV9', 'RFREV4', 'RM5F14', 'RX12P0', 'RFREV5', 'RU5JR9', 'RX12PO', 'RF9EV4', 'RX12P8', 'RFREV3', 'RFREV2', 'RK4DV4', 'RJREV4', 'R43FV3', 'RJREV2', 'R13FVO', 'RK4DV0', 'RV5417', 'RK4DV5', 'RX5GN2', 'RU71J9', 'RF9EV7', 'RM5F15', 'RFREVI', 'RMFAP5', 'R13FV0', 'RFREV6', 'RN81A5', 'RK4DVX', 'RB71J7', 'RD2VF2', 'RMFAP1', 'RX5GNX', 'R03FV0', 'RMFAP8', 'RY5F16', 'RY5F12', 'RWRFV8', 'RFREV0', 'R13FV2', 'RM5F12', 'R20612', 'RU3417', 'R13FV3', 'RT5412', 'RV71J6', 'RT5416', 'RX5GN7', 'RM5F19', 'RMFAP2', 'RK4DV2', 'RV5415', 'RU71J5', 'RU5JR7', 'R1RFVX', 'RWRFV7', 'R43FV4', 'R11AK8', 'RF4DV5', 'RFREV7', 'RV5413', 'RW3FV2', 'RM5F17', 'RB71J0', 'RC1BG6', 'RB71JO', 'RF9EV0', 'RN50R2', 'RV1GP9', 'RX5GN6', 'RJREV1', 'RW3FV0', 'RV5814', 'R6RFV0', 'RB71J6', 'RU5410', 'R43FV5', 'R1RFV8', 'RN82P6', 'RV5418', 'RF4DVX', 'RU3413', 'RB71J9', 'RW3FVX', 'RJREV0', 'RT3416', 'RB71J8', 'RMFAP3', 'RWRFVX', 'RK4DV3', 'R13FV8', 'R13FV6', 'RV42E5', 'RT3413', 'RK4DV1', 'R13FV9', 'RN81A2', 'RF4DV7', 'RMFAPS', 'RF9EVO', 'RZ5CN0', 'RF4DV6', 'R13FVX', 'RW3FV1', 'RY5F19', 'RWRFV1', 'RWRFV6', 'RW3FV5', 'RW3FV3', 'RB71J2', 'RH21B2', 'RT541X', 'RD7KT4', 'RW3FV7', 'R13FV5', 'RMFAP0', 'RK4DV8', 'RM5F13', 'R11AK6', 'RY5F18', 'RM5F1X', 'RL9HE9', 'RWRFV9', 'RF4DV3', 'RU3419', 'RV5815', 'RT3415', 'R1RFV9', 'RY5F15', 'RV71JX', 'RY5F11', 'R13FV4', 'RW3FV8', 'R1RFV6', 'RF9EV6', 'R11AK7', 'RW3FV9', 'RMFAW7', 'R1RFV0', 'RN93P8', 'RWRFV5', 'RJREVX', 'R13FV7', 'RX5GN9', 'RWRFV2', 'RK4DV7', 'RV71J4', 'RV5416', 'RM5F11', 'RK4DV6', 'RD4830', 'RU5JR0', 'RW3FV4', 'RJREV8', 'RT3417', 'RV5414', 'R6RFV2', 'R1CS94', 'RWRFV3', 'RJREV9', 'RT5415', 'RT3410', 'RR7GT2', 'R1RFV5', 'RF4DV0', 'R1RFV7', 'RH2237', 'R1DSBX', 'RX5GN0', 'RK4DV9', 'R1RFV1', 'RU3418', 'RN01P3', 'RY5F10', 'RV5411', 'R1RFV2', 'RX5GN5', 'RT9F3X', 'R03FV2', 'RX5GNO', 'RV71J1', 'RU541X', 'R6RFV7', 'RB71J5', 'RT3813', 'RV5819', 'RF4DV1', 'RU71J3', 'RV5412', 'R3NLT1', 'RJREVO', 'R1CS96', 'RY5F17', 'R43FVX', 'R6RFV8', 'RB23E2', 'RT3419', 'RX5GN3', 'RW3FV6', 'RB71J3', 'RT5410', 'RV541X', 'RV5813', 'RU3416', 'RV71J9', 'RX56N3', 'RV71J5', 'R6RFV3', 'RJREV3', 'RB71J4', 'RC1BG7', 'RN3414', 'RV5419', 'RX22G4', 'RW5F10', 'RT3814', 'RX22G7', 'R1CS93', 'RS12P4', 'RN81A7', 'RM5F10', 'RT341X', 'RU71J8', 'RT381X', 'R43FV0', 'RV5410', 'RMEAP7', 'RW5F17', 'RV71J0']
  Model_Year: ['H', 'E', 'M', 'D', 'N', 'G', '9', 'A', 'L', '8', 'S', 'K', 'P', 'B', 'F', '3', 'J', 'C', 'R', '7', '6', '2', '1', '5', 'Y', 'T', '4']
  Plant_Code: ['D', 'J', '8', 'W', 'X', 'C', 'S', '5', '6', 'T', 'F', '7', '2', 'U', 'R', '4', 'K', 'A', 'B', '1', '3', '0']
  Serial_Number: ['203336', '155695', '094929', '004491', '040937', '117244', '004756', '005894', '070065', '676624', '014531', '019055', '185254', '190877', '160580', '154879', '175541', '093943', '009625', '009494', '271233', '221493', '008842', '001451', '007574', '561392', '243194', '024927', '045278', '216187', '047375', '003469', '335273', '182723', '041354', '010121', '214222', '040409', '046625', '046060', '129136', '043562', '163348', '047140', '723013', '003891', '041487', '093155', '009407', '037232', '016733', '076788', '015922', '001013', '046226', '125404', '232549', '037271', '179295', '723250', '069393', '045620', '023989', '041649', '001037', '006003', '028649', '217557', '029442', '042439', '035786', '186703', '009399', '660975', '013543', '033831', '086884', '215861', '046254', '199447', '061543', '012442', '515600', '042834', '028206', '115319', '514662', '009068', '151122', '093136', '455162', '693001', '034114', '017629', '179996', '070452', '002558', '043770', '026968', '052261', '059289', '032921', '031292', '003805', '040899', '744928', '132998', '702129', '001523', '189121', '216422', '179795', '096075', '003454', '037382', '037067', '214060', '002195', '028269', '004731', '157353', '087694', '572376', '093617', '057640', '009065', '003841', '034381', '034343', '256538', '006866', '046290', '153128', '035791', '290218', '155494', '048298', '753927', '016013', '047376', '082451', '006163', '002689', '009578', '001005', '045126', '594309', '035386', '045542', '211121', '711474', '479919', '517975', '038154', '034652', '200050', '043527', '013882', '038290', '192858', '005990', '216181', '047103', '014338', '046406', '017791', '038029', '001732', '161859', '046242', '043927', '001839', '047605', '049393', '007436', '114090', '033169', '045008', '043992', '099731', '010681', '016254', '816938', '454056', '005933', '039385', '046561', '184914', '088584', '003103', '154674', '153412', '045088', '689740', '038078', '046404', '450655', '124461', '744637', '043163', '801298', '006244', '045919', '047189', '274942', '229923', '034243', '146340', '041593', '063662', '044382', '044196', '006113', '052782', '031249', '006543', '760573', '004525', '003013', '041483', '006505', '002842', '240874', '189274', '046264', '035797', '135299', '049873', '014983', '005293', '005355', '004074', '008912', '037885', '028756', '006711', '002065', '042637', '035998', '044775', '133906', '510384', '039112', '079212', '032783', '448612', '015309', '258398', '592149', '035773', '071105', '145548', '044858', '048626', '119173', '167762', '017377', '042529', '000323', '033194', '112111', '032963', '083771', '046999', '015459', '041151', '002808', '044660', '036230', '452536', '043334', '009227', '020762', '017115', '740796', '014477', '014125', '022413', '044834', '045853', '043899', '553759', '128448', '010851', '037433', '048589', '160044', '043948', '004541', '028559', '061185', '463873', '136964', '073702', '013961', '241639', '637892', '452688', '062944', '784677', '217511', '044774', '476600', '023541', '036946', '847692', '704002', '020755', '095922', '162098', '015347', '045991', '044175', '133199', '048642', '040195', '042551', '130648', '033163', '033131', '040741', '040718', '003219', '006593', '009765', '011623', '055961', '028447', '022604', '743326', '047086', '001023', '512710', '354887', '006423', '309317', '013815', '709386', '004589', '003166', '040636', '035181', '030190', '016093', '046070', '437633', '045179', '025007', '477006', '103593', '513381', '200196', '257014', '855464', '027790', '676632', '019010', '039223', '047596', '084862', '001142', '040290', '027859', '045191', '823714', '160507', '004943', '214781', '033434', '043815', '041386', '046320', '003540', '064690', '016381', '097137', '041569', '220639', '045857', '127824', '005711', '816081', '004957', '005317', '005199', '003346', '005626', '140133', '046228', '026922', '004564', '080916', '457102', '007674', '025777', '121976', '137316', '044138', '511244', '215864', '014698', '023002', '705609', '005413', '046793', '275358', '278746', '004164', '162259', '040252', '119271', '046711', '002792', '043258', '003182', '060285', '009585', '042048', '036853', '022892', '177295', '043961', '165342', '018165', '122629', '112617', '063212', '029511', '015488', '143415', '029105', '033469', '039943', '188628', '102041', '037082', '504211', '040895', '005776', '032848', '257604', '035828', '214484', '042607', '043889', '002165', '184282', '042631', '032864', '044030', '482626', '044512', '189360', '204827', '009194', '453072', '079052', '011766', '173442', '023572', '200537', '797716', '123397', '224559', '015280', '128127', '021834', '007567', '099780', '070330', '006476', '177438', '024978', '010085', '018806', '001056', '053141', '010227', '086127', '069657', '081174', '424439', '065885', '037983', '035038', '042345', '031083', '486628', '439059', '037266', '051187', '025414', '044734', '015639', '231212', '471333', '477144', '076425', '280082', '086202', '110928', '245348', '191546', '009044', '026300', '071998', '145599', '009212', '207652', '056787', '021743', '180355', '045422', '007673', '115376', '121768', '047071', '042271', '481011', '039590', '028368', '474445', '004762', '840077', '011614', '009667', '455063', '245352', '229060', '400203', '258524', '045903', '045415', '113242', '333216', '005927', '117025', '080695', '123654', '154293', '029777', '260653', '038005', '009960', '003845', '047105', '002328', '019056', '061676', '009352', '039886', '033963', '006638', '744305', '041654', '008179', '052775', '003120', '043628', '159991', '129272', '116161', '026898', '210990', '187085', '132117', '185021', '045470', '046903', '003642', '592498', '021340', '048211', '086683', '009078', '771559', '006328', '043481', '038325', '138613', '053126', '027042', '038199', '046634', '259622', '181815', '033125', '010138', '158806', '037038', '044436', '499459', '046704', '046157', '034401', '096142', '177845', '009546', '155042', '022125', '023926', '042126', '160075', '017237', '126795', '266969', '838349', '003600', '420050', '189618', '006130', '085492', '077962', '470578', '250900', '122878', '392795', '063187', '041661', '113111', '317509', '040112', '003406', '583028', '099589', '004011', '037962', '047675', '156051', '025388', '001833', '014847', '043377', '067066', '005668', '034678', '275683', '021411', '013473', '047942', '020268', '153492', '006181', '002846', '037068', '214254', '089791', '053974', '037931', '038961', '019159', '119662', '112743', '116795', '018083', '148237', '016668', '346645', '159694', '283034', '068801', '054653', '003230', '005249', '014955', '700498', '042262', '045662', '594180', '039437', '041337', '184949', '101806', '132987', '075701', '054232', '043254', '152834', '044325', '707297', '655293', '042499', '046600', '098401', '005192', '044285', '046437', '693812', '040665', '003051', '518287', '047059', '047479', '015915', '045581', '282261', '046078', '182350', '005896', '002637', '087362', '060408', '039448', '034639', '014846', '001826', '104495', '004975', '047298', '006728', '014175', '045332', '047344', '004054', '119028', '041698', '722056', '119679', '041493', '041768', '006631', '009117', '023062', '148672', '043878', '215957', '003516', '003053', '107698', '040305', '001026', '130136', '001902', '175992', '155169', '048739', '009272', '044581', '456948', '041260', '043431', '111317', '024874', '719959', '045288', '024890', '146895', '160568', '474374', '241168', '047906', '043574', '037116', '198933', '034628', '039455', '021650', '010344', '003078', '045019', '003665', '014898', '230495', '173935', '005572', '039439', '042111', '040706', '040588', '863097', '065381', '020152', '026766', '285365', '469449', '516896', '125777', '004555', '651575', '119369', '047346', '057101', '231258', '028218', '114597', '001567', '702936', '044044', '039464', '053599', '095103', '005766', '044107', '001882', '511775', '181626', '005253', '047268', '182966', '724629', '451312', '037454', '047789', '043622', '019065', '014414', '420385', '153449', '019390', '288503', '105973', '047070', '090780', '511479', '056658', '062718', '066876', '193206', '030195', '340081', '083470', '005751', '092230', '150274', '042456', '019466', '008921', '003746', '009358', '094087', '047781', '040212', '215748', '323852', '216015', '086345', '092400', '018089', '235607', '035473', '183785', '001479', '149367', '513464', '047708', '442335', '114845', '485312', '009977', '090807', '002895', '009236', '330585', '045481', '009276', '230081', '009380', '005296', '456972', '181408', '213762', '004963', '046551', '269371', '113989', '100003', '003351', '114386', '180151', '737679', '228570', '200023', '043075', '132210', '027217', '022023', '201798', '003367', '055020', '030551', '012480', '046981', '047116', '045559', '054473', '041603', '046566', '549355', '073550', '067764', '034855', '033948', '154814', '156417', '037838', '045145', '061202', '003301', '044919', '054672', '028240', '450203', '259266', '188945', '204920', '047624', '014649', '109799', '052866', '045083', '342533', '034423', '005633', '009366', '476215', '003157', '041605', '001416', '164685', '018497', '006204', '226460', '023941', '108823', '047663', '246428', '510969', '027986', '042716', '150960', '019777', '005749', '041789', '512169', '154352', '106016', '007593', '009672', '041581', '217983', '585312', '029228', '009991', '136614', '208156', '041633', '100925', '034760', '062162', '266291', '042799', '045140', '710191', '108259', '045687', '121059', '051383', '029982', '001391', '004152', '033215', '004032', '034212', '480442', '375012', '028389', '278379', '005613', '010404', '067604', '119776', '676010', '004015', '009545', '264951', '047917', '217411', '034842', '097434', '045811', '294595', '052640', '180595', '235176', '002166', '053160', '005976', '113800', '042304', '009652', '216120', '009685', '045595', '009694', '211697', '084920', '009671', '016907', '009660', '250599', '043976', '012245', '052777', '045272', '068974', '003715', '014854', '029722', '128920', '017913', '009200', '047280', '159859', '009005', '040166', '006182', '017572', '026469', '051684', '191717', '022581', '050106', '028052', '567832', '0348SS', '184459', '219882', '010270', '045992', '287033', '006413', '066312', '046674', '029090', '046511', '232308', '183145', '045168', '190197', '033898', '230690', '515392', '002882', '035514', '041663', '024977', '241219', '230949', '511769', '086460', '207158', '003688', '019565', '038369', '017488', '179581', '042648', '003989', '024837', '009257', '014968', '003075', '007925', '121187', '296272', '007969', '071661', '013604', '002981', '035590', '035627', '509196', '039396', '039145', '249247', '005596', '046457', '720181', '214829', '469678', '002777', '073748', '036973', '065666', '127204', '540053', '105854', '038401', '122900', '023719', '009228', '051260', '039661', '166735', '017066', '305390', '039518', '150465', '002442', '207532', '204341', '044699', '498604', '561349', '434024', '046176', '262283', '413101', '034123', '031426', '018632', '565733', '039847', '003071', '043300', '018881', '131506', '002867', '076143', '044055', '267818', '022570', '321179', '018558', '047297', '041256', '178383', '045103', '001247', '609892', '016726', '004085', '206040', '102051', '034683', '731272', '035538', '430297', '148820', '008308', '038638', '026253', '215854', '582944', '419722', '022235', '022255', '009466', '064055', '142767', '026891', '001491', '115346', '436872', '002742', '048202', '044718', '080594', '042075', '005829', '045017', '046197', '033177', '046985', '049394', '064675', '154074', '042352', '108554', '108331', '043786', '006079', '800743', '216760', '008889', '161104', '008546', '044067', '040357', '501588', '021544', '537024', '013852', '003368', '473699', '026232', '004954', '033954', '047195', '023315', '051667', '203310', '128433', '214911', '443153', '094331', '042555', '255227', '003875', '003336', '255343', '152894', '006818', '009434', '029697', '258803', '044328', '047944', '190578', '472919', '047488', '511885', '021455', '155485', '736789', '005415', '028430', '006602', '005949', '033202', '024957', '047403', '133124', '017027', '044974', '003993', '076563', '160464', '046807', '109881', '039858', '097258', '084884', '039057', '033199', '140073', '036088', '027544', '047277', '704878', '005391', '078820', '098893', '475034', '020903', '037452', '003947', '024482', '004969', '005055', '216017', '029070', '732934', '213077', '028182', '016799', '170490', '039679', '029085', '047169', '214482', '040194', '033431', '701694', '507779', '029031', '223504', '099406', '236558', '178444', '023549', '005448', '045653', '479204', '039853', '005900', '005378', '028534', '260055', '003310', '013968', '236598', '236661', '217413', '076985', '154246', '044081', '000041', '741434', '125384', '597996', '398627', '018208', '033734', '042921', '015042', '006446', '560943', '154460', '362887', '084163', '449148', '004788', '006172', '006190', '006191', '471709', '099002', '006148', '047754', '266242', '047763', '212047', '084969', '044337', '008559', '167355', '056800', '039176', '002934', '025738', '237738', '700955', '484197', '037318', '009785', '039300', '031662', '012790', '027112', '041820', '030685', '199547', '003887', '040172', '080835', '034228', '069304', '212138', '841592', '047780', '047787', '188810', '002587', '030575', '044282', '342692', '126325', '045041', '003187', '202390', '212492', '043461', '016958', '046059', '002228', '049611', '041898', '213039', '003985', '034422', '042730', '048761', '024906', '003092', '035239', '203630', '039178', '659118', '147822', '098142', '003026', '041207', '010183', '002835', '112393', '082706', '214788', '042586', '435564', '045412', '019079', '033479', '201639', '054616', '290112', '164905', '010341', '029598', '476910', '006324', '207299', '016313', '046833', '040058', '044287', '071044', '036925', '050395', '129734', '414722', '171755', '043809', '542594', '183201', '032903', '001642', '079145', '287417', '047326', '396015', '088387', '158685', '225376', '108204', '112070', '018843', '451277', '042301', '002017', '235217', '476722', '786174', '047798', '128232', '047991', '040575', '186726', '095744', '550054', '045289', '013874', '094301', '075616', '045452', '163254', '330565', '008177', '155033', '552050', '043185', '828734', '004006', '512053', '806784', '545261', '097055', '027733', '008024', '200649', '027399', '027479', '207439', '006353', '131411', '027373', '003817', '027319', '044392', '027320', '003495', '006177', '037654', '173555', '132809', '097858', '015869', '068799', '377633', '134942', '041821', '176279', '038627', '013904', '004781', '267341', '160052', '230316', '016408', '181427', '030785', '102111', '038802', '216119', '066977', '131225']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,RAV4,4.0,SUV,R,GXR,GCC,5.0,JTM,RF9EV1,H,D,203336
1,TOYOTA,RAV4,4.0,SUV,R,GXR,GCC,5.0,JTM,RF9EV5,H,J,155695
2,TOYOTA,RAV4,4.0,SUV,R,EXR,GCC,5.0,JTM,REREV2,E,D,094929
3,TOYOTA,HIACE,4.0,PANEL VAN,R,GL,GCC,NaN,JTF,RMFAP7,M,8,004491
4,TOYOTA,HIACE,4.0,PANEL VAN,R,DX,GCC,5.0,JTG,RX12P6,E,8,040937
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1510,TOYOTA,RAV4,4.0,SUV,R,1,GCC,NaN,JTM,R13FV8,P,D,102111
1511,TOYOTA,TUNDRA,8.0,PICKUP,R,STD (NON GCC),NON-GCC,NaN,5TF,RV541X,8,X,038802
1512,TOYOTA,RAV4,4.0,SUV,R,GXR,GCC,NaN,JTM,RF9EV3,H,D,216119
1513,TOYOTA,RAV4,4.0,SUV,R,XLE,NON-GCC,NaN,4T3,RWRFV3,N,U,066977
1514,TOYOTA,RAV4,4.0,SUV,R,GXR,GCC,NaN,JTM,RF9EV2,H,J,131225

====================================================================================================
POS4: X
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['INNOVA', 'SIENNA', 'RAV4', 'HILUX', 'HIACE', 'HIGHLANDER', 'FJ CRUISER', 'STATION', 'RAV 4']
  bodyType: ['MPV', 'SUV', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'STATION', 'MINI BUS', 'CONVERTIBLE', 'MINIVAN']
  pos4: ['X']
  trim: ['GL', 'SE', 'XLE (NON GCC)', 'LE (NON GCC)', 'DX', 'XLE', 'GXR', 'LIMITED (NON GCC)', 'SE (NON GCC)', 'STD', 'GL TOP', 'DLX', 'EXR', 'BASE', 'EX', 'GLI TOP LEATHER', 'GRD', 'GLS LOWLINE', 'STD (NON GCC)', 'GLE HEV', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MHF', '5TD', 'JT3', '1FD', '2T3', 'YAR', 'MHE', 'JTM', 'WV2', 'KMF', 'MFH']
  VDS: ['XX43G3', 'XX43G7', 'XX43G1', 'XX43GX', 'XX43G0', 'XX42G2', 'XX42GX', 'XZ3DC8', 'XK3DC7', 'XK3DC6', 'XK3DC4', 'XX43G9', 'XK3DCX', 'XX43G4', 'XK3DC2', 'XX43G8', 'XX43G5', 'XX42G5', 'XX43G2', 'XX42G1', 'XK3DC0', 'XX42G4', 'XX42G3', 'XX42G6', 'XX42G9', 'XP10V7', 'XX43G6', 'XX42G0', 'XX42G8', 'XK3DC3', 'XX42G7', 'XP10V6', 'XK3DC1', 'XX4262', 'XK3DC9', 'XK3DC5', 'XP10V2', 'XK3DC8', 'XZ3DCT', 'XE4FS9', 'XP10V1', 'XP10V9', 'XX43GI', 'XZ3DC2', 'XX4367', 'XP10V8', 'XK4DV4', 'XX4266', 'XX42GO', 'XP10V3', 'XX4366', 'XP10V4', 'XX4264', 'XP10VX', 'XX4362', 'XX4360', 'XE4FSX', 'XX4369', 'XRKEC0', 'XZ3DCX', 'XZ3DC4', 'XX4263', 'XZ3DC7', 'XP10V0', 'XU9HM0', 'XX42GB', 'XX4308', 'XZ3DC0', 'XX436X', 'XRKEC7', 'XBRCH7', 'XP10V5', 'XX426X', 'XK4DV3', 'XAD2K0', 'XZ3DC9', 'XBRCH1', 'XKS7BP', 'XX4364', 'XX48G8', 'XK3DCD', 'XX4303', 'XX4361']
  Model_Year: ['7', '6', 'B', '8', 'F', 'E', 'H', 'A', '9', 'C', 'D', 'T', 'V', 'G', 'W', 'J', 'X', 'M', 'K', 'P', 'N', '1']
  Plant_Code: ['0', '5', 'S', 'D', 'W', 'Z', 'X', 'U']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,INNOVA,4.0,MPV,X,GL,GCC,5.0,MHF,XX43G3,7,0,009557
1,TOYOTA,INNOVA,4.0,MPV,X,GL,GCC,5.0,MHF,XX43G7,6,0,004621
2,TOYOTA,INNOVA,4.0,MPV,X,GL,GCC,5.0,MHF,XX43G1,B,0,031159
3,TOYOTA,INNOVA,4.0,MPV,X,GL,GCC,5.0,MHF,XX43GX,7,0,011130
4,TOYOTA,INNOVA,4.0,MPV,X,GL,GCC,5.0,MHF,XX43G0,8,0,016368
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2232,TOYOTA,INNOVA,4.0,SUV,X,GL,GCC,NaN,MHF,XX43GX,A,0,023706
2233,TOYOTA,INNOVA,4.0,SUV,X,GL,GCC,NaN,MHF,XX43G9,B,0,029921
2234,TOYOTA,INNOVA,4.0,SUV,X,GL,GCC,NaN,MHF,XX43G6,6,0,004996
2235,TOYOTA,INNOVA,4.0,SUV,X,SE,GCC,NaN,MHF,XX42G1,F,5,030328
2236,TOYOTA,INNOVA,4.0,SUV,X,DX,GCC,NaN,MHF,XX43G3,D,0,046667

====================================================================================================
POS4: Z
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['SIENNA', 'RAV4', 'HIACE', '86', '4RUNNER', 'FORTUNER', 'GR86', 'HILUX', 'PRIUS', 'SEQUOIA', 'FJ CRUISER', 'HIGHLANDER', 'LAND CRUISER', 'ALTIS', 'ZELAS', 'PRADO', 'ALPHARD', 'COROLLA', 'SICION', 'CAMRY', 'VENZA', 'TOYOTA 4RUNNER', 'RAV 4', '1998', 'RUSH', 'SPINA', 'PREVIA', 'SCION', 'AURION', 'FORERUNNER', 'HI ACE', 'TOYOTA 86']
  bodyType: ['MPV', 'SUV', 'PANEL VAN', 'COUPE', 'PICK UP DOUBLE CAB', 'HATCHBACK', 'STATION', 'SEDAN', 'MINI BUS HIGH ROOF', 'VAN', 'PICK UP SINGLE CAB', 'MINI BUS']
  pos4: ['Z']
  trim: ['LE (NON GCC)', 'XLE (NON GCC)', 'EX', 'MID', 'STD', 'VX', 'CE (NON GCC)', 'STD (NON GCC)', 'EXR', 'VTX', 'BASE', 'SR5 (NON GCC)', 'LIMITED (NON GCC)', 'TOP', 'DLX', 'GTX', 'LIMITED 4X2', 'LE HEV', 'C (NON GCC)', 'GXR', 'SPORT', 'PLATINUM', 'GT', 'BE', 'GX', 'SR5 4X2', 'SE (NON GCC)', 'LIMITED', 'GL', 'SR5', '1', 'VT', 'GLE HEV', 'PW CL', 'ICONIC', 'EXR HEV', 'SAFARI', 'VXR', 'SE', 'DL', 'DYNAMIC', 'STATION ', 'GR SPORT', 'LIMITED 4X4', 'ADVENTURE', 'GLE HEV BLACK EDITION', 'GLE', 'CE', 'XLI', 'AT', 'XLE', 'G', 'PLATINUM LUXURY 4X4', 'TRIM', 'NON GCC', 'GLX', 'VX MID', 'SR5 4X4', 'DLS', '4X4', 'EXCELLENCE', 'MPV', 'S', 'LE', 'FR-S (NON GCC)', 'DX', 'VAN', 'EXTREME', 'HYBRID (NON GCC)']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TD', 'JTD', 'JTM', 'JT4', 'JF1', '2T3', 'JTE', 'MHF', 'WV1', 'U8Q', 'JT0', '2FU', 'JHH', 'STD', '4T3', 'WMW', 'MR1', 'KMF', 'JTL', 'WDD', 'KLI', 'JHM', '6TD', 'SMV', '1G1', 'JS2', 'L3A', 'JTA', '1GJ', '5T0']
  VDS: ['ZK22C2', 'ZA23CX', 'ZA23C6', 'ZK23C8', 'ZF9EV4', 'ZK31V1', 'Z13FV3', 'Z13FV8', 'ZA23C8', 'Z13FV7', 'ZA1190', 'ZFREV8', 'ZK23CX', 'ZA23C0', 'Z13FV9', 'ZN11B9', 'Z13FV5', 'Z13FV0', 'Z13FV4', 'ZFREV4', 'ZK23C4', 'ZF9EV6', 'ZA22C9', 'ZK22C5', 'ZK23C5', 'ZA23C3', 'ZF4DV3', 'ZN12B6', 'ZA22C6', 'ZR1198', 'ZK3DC8', 'ZK3DC0', 'ZA23C5', 'ZN11B7', 'ZA22C8', 'ZNAA12', 'Z13FV1', 'ZD33V1', 'ZK23C7', 'ZK4DV2', 'ZA22C2', 'ZK22C4', 'ZN12B4', 'Z13FVX', 'ZK23C6', 'ZK22C8', 'ZK23C1', 'ZK23C0', 'ZA23C2', 'ZK22C1', 'ZA1197', 'ZU14R4', 'ZK3DC4', 'ZFREV9', 'ZK3DC6', 'ZK22C0', 'Z13FV6', 'ZF9EV8', 'ZX69G8', 'ZA23C1', 'ZA23C9', 'ZF9EV5', 'ZA23C7', 'ZA22C1', 'ZNBB18', 'ZA22C3', 'ZD33V3', 'ZA22C7', 'ZBB2K2', 'ZD31V7', 'ZN12A6', 'ZA22CX', 'ZK31V8', 'ZK23C3', 'ZU14R7', 'ZK3DC3', 'ZK31V9', 'ZF9EV3', 'ZF9EV9', 'ZK22C3', 'ZN3EU8', 'ZF9EVX', 'ZK22C6', 'ZF9EV0', 'ZY68A4', 'ZF9EV7', 'ZA22C0', 'ZN12B2', 'ZA22C4', 'Z13FV2', 'ZK22C7', 'ZN12A1', 'ZK22C9', 'ZA29C5', 'ZD33V0', 'ZK33V7', 'ZK23C9', 'ZF33V6', 'ZN3EU3', 'ZN3EU1', 'Z23FV4', 'ZK33V0', 'ZK3DCX', 'ZF33V4', 'ZZRFH2', 'ZU14R8', 'ZU14R1', 'ZK31V5', 'ZA22C5', 'ZA1191', 'ZF9EVO', 'ZN12B8', 'ZK23C2', 'ZN3EU7', 'ZZ3DC5', 'ZN12B3', 'ZN1286', 'ZA1195', 'ZA2301', 'ZN3EU0', 'ZK22CX', 'ZF9EV2', 'ZK3DC1', 'ZU14R5', 'ZF4DV8', 'ZA29C9', 'ZA1135', 'ZR1199', 'ZN12A0', 'ZN12B9', 'ZY67AX', 'ZA23C4', 'ZK34V4', 'ZFREV5', 'ZA29C1', 'ZFREV6', 'ZX69G7', 'ZY64A9', 'ZNAA13', 'ZN12B5', 'ZX69G3', 'ZD33V4', 'ZN11A3', 'ZF9EV1', 'ZK31V6', 'ZN12B1', 'ZT14R2', 'ZY68A2', 'ZK3DC9', 'ZA1192', 'ZY68A1', 'ZFREVX', 'ZD32V9', 'ZA29C3', 'ZKRFH7', 'ZR119X', 'ZCKF5Q', 'ZT14R0', 'ZU5JR7', 'ZU5JR4', 'ZF4DV5', 'ZFREV7', 'ZN3EU4', 'ZD32V2', 'ZN23B4', 'ZFREV3', 'ZNAA15', 'ZFREV2', 'ZFREV0', 'ZN3EUX', 'ZF4DVX', 'ZK31V3', 'ZK3DC2', 'ZNAA10', 'ZY64A6', 'ZF4DV4', 'ZR1193', 'ZNBC13', 'ZD33V7', 'ZT38A3', 'ZF4DV7', 'ZF4DV0', 'ZY0CCL', 'ZCP2F6', 'Z13FVO', 'ZD33V8', 'ZE32V2', 'ZK31V7', 'ZX69G6', 'ZR1196', 'ZF33V1', 'ZU11F1', 'ZN11A4', 'ZU14R6', 'ZK3DC7', 'ZD32V6', 'ZY68A9', 'ZU14RX', 'ZN1284', 'ZD31V9', 'ZA29C0', 'ZY67A5', 'ZZ3DCX', 'ZF4DV6', 'ZN11A2', 'ZY5G17', 'ZD33V5', 'ZNBF12', 'ZX69G4', 'ZNBB17', 'ZR1192', 'ZK3DC5', 'ZN11AX', 'ZA29C8', 'ZU14R2', 'ZF13C8', 'ZR1191', 'ZX69G1', 'ZD32V8', 'ZF31V6', 'ZNAA14', 'ZU17R2', 'ZFREV1', 'ZA3BB4', 'ZZRAH4', 'ZU11F2', 'ZN3EU6', 'ZU5JR3', 'ZY64A2', 'ZFREVO', 'ZY67A8', 'ZK29C7', 'ZA29C7', 'ZK29C6', 'ZNBE12', 'ZU11FX', 'ZU5JR9', 'ZF4DV1', 'ZN12B7', 'ZY67A9', 'ZA119X', 'ZNBC19', 'ZY5G19', 'ZY68A7', 'ZZ3DC4', 'ZA1193', 'ZX69G9', 'ZK29C1', 'ZN11A5', 'ZN11A1', 'ZZRAHX', 'ZA29C2', 'ZC3C52', 'ZNBE14', 'ZD33V2', 'ZF4DV9', 'ZX69GX', 'ZU5JR0', 'ZN12A9', 'ZU11F3', 'ZY67A7', 'ZCK1H2', 'ZNAA19', 'ZD33V6', 'ZN3EU9', 'ZK31V4', 'ZF4DV2', 'ZU5JR6', 'ZNBF14', 'ZZRFH1', 'ZD31V5', 'ZF19C6', 'ZY64A5', 'ZR1190', 'ZF9EVS', 'ZF13C3', 'ZNAA16', 'ZA1198', 'ZF33V5', 'ZU14R0', 'ZF35V1', 'ZCK1H9', 'ZY68AX', 'ZU14R3', 'ZR1194', 'ZA29CX', 'ZD31V2', 'ZT14R1', 'ZX69G0', 'ZNBG14', 'ZK29C9', 'ZA1194', 'ZN3EU2', 'ZT14R5', 'ZSZ7JA', 'ZK29C2', 'ZY5G1X', 'ZR1195', 'ZN12BX', 'ZCP2H5', 'ZE32V7', 'ZU17R0', 'ZX69G2', 'ZNBF11', 'ZE32V0', 'ZD33VX', 'ZE4FE1', 'ZZ3DC3', 'ZF4CBX', 'ZK29C8', 'ZARAH3', 'ZK31V2', 'ZF33V2', 'ZU17R8', 'ZZRFH0', 'ZD35V4', 'ZA5CS4', 'ZE32V3', 'ZN12B0', 'ZZ3DC6', 'ZN12A7', 'ZA29C6', 'ZK31VX', 'ZK31V0', 'ZY68A0', 'ZY64A0', 'ZZ3DC2', 'ZK32V3', 'ZT17R1', 'ZF33V9', 'ZY5G14', 'ZN23B6', 'ZD31V3', 'ZE2870', 'ZBB2K7', 'ZN23B9', 'ZR1197', 'ZZRFH7', 'ZA3BB8', 'ZF19C5', 'ZF19C9', 'ZD33V9', 'ZY68A8', 'ZU5JR5', 'ZT14R6', 'ZU17R9', 'ZN12A4', 'ZZ3DC0', 'ZCZ7JA', 'ZN11A0', 'ZY64A3', 'ZER2DG', 'ZF9EVG', 'ZA1199', 'ZY5G18', 'ZN11A6', 'ZU4BF5', 'ZK32V4', 'ZU11F9', 'ZF35V4', 'ZCS7JP', 'ZU5JR2', 'ZD31VX', 'ZCN1FX', 'ZSZ7KB', 'Z23FV9', 'ZCP2F5', 'ZD32V0', 'ZU17R3', 'ZC5ST2', 'ZN12A5', 'ZK4CCX', 'ZA1196', 'ZK32V8', 'ZNAA1X', 'ZA29C4', 'ZF13C2', 'ZF31V2', 'ZF13C0', 'ZE9EV1', 'ZE11A4', 'ZY68A5', 'Z23FV0', 'Z23FVO', 'ZNAA17', 'ZY68A3', 'ZX69G5', 'ZT34A3', 'ZK32V7', 'ZNAE17', 'ZY64AX', 'ZU17R6', 'ZK29C0', 'ZF13C4', 'ZCP2HX', 'ZU14R9', 'ZA3EH2', 'ZC8B20', 'ZT34A7', 'ZY68A6', 'ZN11A9', 'ZK33VX', 'Z13FVB', 'ZT17R4', 'ZT34A4', 'ZF13C1', 'ZN11A8', 'ZY64A7', 'Z1CK33', 'ZD35V3', 'ZN11B0', 'ZBB7H0', 'ZF13CX', 'ZY5G10', 'ZY5G13', 'ZD31V0', 'ZU11F5', 'ZK32V9', 'ZFREVI', 'ZZRAH5', 'ZD31V6', 'ZN12A2', 'ZZ3DC7', 'ZZ3DC1', 'ZE4FE7', 'ZF31V9', 'ZA119S', 'ZZRAH9', 'ZY67A4', 'ZK29C3', 'ZK32V6', 'ZF33V8', 'ZF9EVI', 'ZT14R8', 'ZE4FEX', 'ZK33V6', 'ZCL2H9', 'ZCP2F2', 'ZU11F7', 'Z23FV1', 'ZN1287', 'ZNAA18', 'ZN12A8', 'Z78FG6', 'ZZ3DC9', 'ZD32VX', 'ZNBF15', 'ZBB2KX', 'ZNBC1X', 'ZBB2K9', 'ZBB2K0', 'ZK33V5', 'ZF31V0', 'ZY64A8', 'ZY67A0', 'ZCN1F0', 'ZNBE15', 'Z41197', 'ZT38A8', 'ZY67A2', 'ZZ3DC8', 'ZN23A5', 'ZFREVS', 'ZN3EU5', 'ZN12E7', 'ZF33VX', 'ZU5JR8', 'ZN12AX', 'ZK29C4', 'ZF13C7', 'Z1RFV2', 'ZN11A7', 'ZN12A3']
  Model_Year: ['9', '5', '7', 'J', 'M', 'R', 'P', 'X', 'N', 'D', 'G', '8', '4', '6', 'A', '3', 'L', 'C', 'E', 'F', 'S', 'B', 'H', 'Y', 'K', '2', '1', 'W']
  Plant_Code: ['S', 'J', '5', 'D', '0', 'G', 'W', '7', '8', '9', '6', 'X', '3', '2', 'K', 'U', 'C', 'A', 'B', '1', 'F', 'Y', 'H']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,SIENNA,6.0,MPV,Z,LE (NON GCC),GCC,5.0,5TD,ZK22C2,9,S,228371
1,TOYOTA,SIENNA,6.0,MPV,Z,XLE (NON GCC),GCC,5.0,5TD,ZA23CX,5,S,307623
2,TOYOTA,SIENNA,6.0,MPV,Z,XLE (NON GCC),GCC,5.0,5TD,ZA23C6,5,S,370007
3,TOYOTA,SIENNA,6.0,MPV,Z,LE (NON GCC),GCC,5.0,5TD,ZK23C8,7,S,005411
4,TOYOTA,RAV4,4.0,SUV,Z,EX,GCC,5.0,JTD,ZF9EV4,J,J,171845
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6369,TOYOTA,SIENNA,6.0,SUV,Z,CE (NON GCC),NON-GCC,NaN,5TD,ZK23C4,9,S,283581
6370,TOYOTA,TOYOTA 86,4.0,COUPE,Z,GTX,GCC,NaN,JF1,ZN12A3,G,G,025017
6371,TOYOTA,SIENNA,6.0,SUV,Z,CE (NON GCC),NON-GCC,NaN,5TD,ZK23C3,9,S,268229
6372,TOYOTA,SIENNA,6.0,SUV,Z,1,NON-GCC,NaN,5TD,ZA23C8,6,S,423033
6373,TOYOTA,RAV4,4.0,SUV,Z,EX,GCC,NaN,JTD,Z13FV0,N,D,093269

====================================================================================================
POS4: W
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'RAV4', 'TUNDRA', 'HILUX', 'YARIS', 'HIACE', 'COROLLA', 'TAKOMA', 'SIERRA', 'CAMRY', 'TUNDRA (PICK UP)', 'TAKOMA PICK UP CARGO', 'SIENNA']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'PICK UP', 'PICK UP SINGLE CAB', 'SEDAN', 'PANEL VAN', 'PICKUP', 'COUPE/CABRIOLET', 'MPV', 'CARGO VAN', 'WINDOW VAN', 'HALF PANEL VAN', 'MINI BUS', 'COUPE', 'HATCHBACK']
  pos4: ['W']
  trim: ['SR5 (NON GCC)', 'LE HEV', 'LE', 'VX', 'EXR', 'EX', 'GX', 'SR', 'XLE', 'BE', 'STD (NON GCC)', 'DLX', 'MID', 'BASE', 'CREWMAX CAPSTONE (NON GCC)', '1794 EDITION (NON GCC)', 'E', 'GL', 'GLI', 'DL', 'DLS', 'GXR', 'STD', 'XLI', 'GLI TOP', 'A', 'DLS - STD ROOF', 'DX', 'GLX', 'ADVENTURE', 'PW CL', 'S', 'XLE (NON GCC)', 'S TRD AERO PK', 'SGLX']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['4TA', '2T3', 'JTD', 'WWW', 'JTM', '5TF', '5TE', 'KNC', 'JM3', 'KNF', 'LCF', 'WD4', 'KMH', 'LZZ', 'KMJ', 'LSJ', '55S', 'KMF', '1GT', 'WDD', '1GC', 'WV2', '1FD']
  VDS: ['WN72N6', 'W1RFV6', 'W13FVX', 'WF9EV2', 'WF9EV7', 'W13FV2', 'WFREV0', 'W13FV8', 'W13FV9', 'WF9EV6', 'WFREVX', 'W88888', 'WF9EV0', 'WF9EV4', 'WF9EV9', 'WFREV6', 'W13FV1', 'W13FV7', 'WA5DB2', 'WF9EV1', 'W13FV4', 'W1RFV9', 'W13FV0', 'WFREV3', 'W13FV5', 'WF9EV8', 'WF9EV5', 'WFREV7', 'WFREV5', 'WN72N2', 'WJ2728', 'W13FV3', 'WF9EV3', 'W1RFV7', 'WFREV2', 'WFREV1', 'WF9EVX', 'W13FV6', 'WFREV4', 'W1RFV3', 'WG7255', 'WXZ74A', 'WF4DV6', 'WFREV8', 'WFREV9', 'W1RFVX', 'WA5EC3', 'WA5DB1', 'W13FVO', 'WF9EVO', 'W6FY16', 'WK4DVX', 'WJZ74A', 'WG3E13', 'WG81R1', 'WF4DVX', 'WFREVS', 'WADG49', 'W1RFVO', 'W1RFV0', 'WA5DB0', 'W1RFV4', 'W1RFV1', 'WJZ76A', 'WFREVO', 'WH8139', 'WN72N5', 'WJX74A', 'WA37R1', 'WF4DV9', 'WJX76A', 'WG725X', 'WC5DB0', 'WN72N9', 'W74U33', 'WF8HB3', 'W1RFV5', 'WAH7JP', 'WF4DV7', 'WJ4W96', 'W8X7K8', 'WE23EX', 'WIRFV6', 'W78CG1', 'WG81R3', 'W1RFV2', 'WM72N4', 'WC5DB9', 'W13EV6', 'WF4CB8', 'WF4DV8', 'WGAFP8', 'WA37R7', 'WBC7H5', 'WA37RX', 'WM72NX', 'WF4DV2', 'WA5DB5', 'WC5EC5', 'WG81R8', 'WE3FN2', 'WN72N4', 'WA5DB4', 'WJ2764', 'WK4DV1', 'WF4JB1', 'WJ2727', 'WJZ72A', 'WF9EVB', 'WA5DB9', 'WC5DBX', 'W9235A', 'W1RFVI', 'WIRFVX', 'WN72N0', 'WA5DB3', 'WIRFVI', 'WG7258']
  Model_Year: ['T', 'M', 'L', 'H', 'G', 'R', 'E', 'S', 'D', '8', 'J', 'P', 'K', '4', 'N', 'F', 'A', 'W', 'B', 'C', '3', '9', 'X', 'V', '5', 'Y', '2', '1']
  Plant_Code: ['Z', 'C', 'D', 'J', 'W', '8', 'X', '7', '0', 'K', '3', 'U', 'T', 'G', '1', 'R', '5', 'H']
  Serial_Number: ['159758', '135629', '058352', '103765', '096859', '121985', '108235', '115933', '142323', '084752', '005838', '888888', '111462', '084134', '145559', '179674', '099636', '113261', '125899', '287576', '085260', '098967', '117606', '124869', '099021', '713735', '107371', '066210', '118813', '022606', '120768', '090940', '040205', '133355', '116179', '060324', '142435', '096833', '023307', '126570', '118228', '099764', '095094', '749505', '190259', '310878', '161411', '089628', '095136', '204467', '430222', '030357', '117239', '115030', '088287', '169404', '093145', '093213', '410068', '308154', '112986', '089906', '151399', '152150', '095145', '151483', '099756', '169935', '085151', '178298', '011562', '215307', '061825', '139489', '091232', '093042', '025664', '221008', '120151', '099145', '111653', '015862', '109193', '263081', '257694', '107678', '092634', '453668', '605591', '177837', '095116', '097529', '093240', '028424', '590918', '263696', '091558', '105625', '093941', '105795', '181912', '120749', '124340', '146411', '362391', '729393', '106950', '712635', '085188', '133117', '142383', '089082', '257943', '088189', '184631', '050786', '002390', '108042', '096316', '094558', '493117', '087599', '127751', '118727', '085005', '077689', '061361', '267624', '121240', '088231', '104898', '094788', '118705', '010813', '277651', '089991', '377522', '020996', '259557', '510064', '091807', '118873', '333042', '140671', '120273', '116512', '124806', 'Z01349', '010163', '110571', '062069', '293526', '159414', '086911', '059519', '539943', '152238', '125069', '141848', '223208', '408304', '094743', '090834', '069682', '124709', '739104', '124397', '126811', '043823', '568775', '092796', '736476', '118087', '136567', '750277', '091463', '105658', '255174', '244757', '413835', '060522', '443258', '145044', '065684', '238086', '116692', '152521', '027306', '131168', '137718', '102374', '166723', '103917', '110752', '091855', '014542', '137358', '186358', '121138', '096221', '318085', '145403', '090559', '046984', '118547', '012516', '126269', '103510', '089533', '169774', '099497', '124642', '125549', '076827', '501381', '115776', '107086', '095733', '185832', '257994', '034763', '120831', '126672', '102342', '099678', '016019', '168149', '100928', '186486', '126241', '221859', '130052', '151975', '138121', '121021', '016904', '105244', '131147', '099617', '133313', '462593', '180912', '186689', '147011', '368503', '123259', '215203', '089324', '051654', '182284', '021781', '418568', '118427', '133005', '133212', '037823', '388846', '104030', '108093', '007212', '101195', '170709', '110482', '107753', '100443', '020902', '095907', '148413', '100978', '151723', '086002', '702805', '094308', '732413', '021868', '127641', '124870', '389298', '008042', '171188', '105967', '018188', '090005', '092044', '287130', '120879', '005252', '140013', '094588', '417925', '030696', '099824', '411927', '109510', '011835', '007460', '542474', '077566', '504051', '155451', '022041', '094469', '123951', '064625', '183820', '042696', '895526', '099619', '140227', '059195', '438600', '197676', '045638', '170105', '099488', '090965', '728511', '604985', '013156', '103608', '116689', '087663', '108450', '095326', '019036', '127635', '113112', '061025', '122470', '178080', '277766', '460588', '081648', '098526', '116084', '020788', '117170', '182202', '120500', '196765', '031945', '060201', '511346', '114013', '074767', '367584', '090397', '061326', '102308', '010402', '110949', '159741', '714188', '476189', '171404', '080877', '127233', '090790', '016158', '121234', '184026', '141164', '041746', '138255', '059239', '113572', '103627', '129140', '125036', '212796', '096030', '006778', '121837', '023164', '185978', '123106', '123461', '143496', '409674', '085443', '233048', '363394', '268510', '097619', '124254', '103453', '098058', '125916', '051615', '193457', '099051', '437146', '185191', '029542', '027811', '097409', '010747', '115898', '092175', '137894', '098465', '115893', '385963', '734613', '124375', '131768', '238116', '023306', '193979', '022318', '099074', '014893', '122925', '210078', '089944', '009868', '124044', '093257', '469842', '133568', '095790', '733795', '052845', '091058', '608066', '509347', '123901', '333620', '082212', '089209', '118480', '510098', '181220', '099519', '194110', '087243', '131092', '107929', '099912', '131369', '092397', '103658', '367727', '002228', '488772', '019276', '101624', '736576', '093194', '011813', '123387', '107676', '097742', '126273', '097604', '099572', '082819', '174903', '357501', '349779', '118421', '172298', '077027', '183952', '095805', '062657', '027630', '104138', '089854', '307921', '414282', '125585', '103312', '101439', '144435', '021357', '126567', '080719', '105959', '015514', '129334', '122105', '192900', '120049', '084940', '096209', '099507', '073214', '127696', '126458', '138792', '128877', '106470', '139270', '130847', '009961', '182802', '099849', '014663', '122224', '472757', '093392', '287811', '010597', '017494', '124513', '117155', '006691', '017345', '421242', '123882', '107213', '278848', '030217', '185769', '099168', '513866', '099508', '103258', '725065', '109467', '102834', '125311', '127801', '202791', '097932', '083266', '108964', '161658', '106508', '007125', '261887', '165943', '100429', '259579', '084799', '176457', '154334', '520051', '025818', '667866', '111026', '084231', '182655', '105620', '091359', '105369', '035444', '113271', '015736', '010645', '168238', '084245', '084713', '138839', '159435', '149829', '178862', '107779', '206913', '123643', '185828', '099471', '896417', '120348', '102871', '135587', '001338', '117398', '006458', '513517', '133429', '008587', '009033', '096387', '254607', '084461', '386947', '382044', '645103', '267075', '089435', '099333', '017311', '223287', '431304', '007692', '184250', '096967', '347057', '126674', '117305', '099309', '142701', '125710', '103357', '113910', '103561', '118539', '014788', '128425', '041077', '458005', '085069', '101204', '179142', '091010', '159933', '126790', '129977', '107060', '125614', '054870', '249775', '120361', '091660', '145220', '087771', '112244', '105779', '514170', '161189', '101216', '083778', '143851', '276760', '099028', '096466', '115330', '105535', '124447', '091579', '010394', '073999', '067458', '079462', '104692', '094979', '126852', '011744', '017496', '059301', '090249', '089344', '458836', '098638', '128145', '733855', '092537', '195201', '110726', '323110', '182395', '179457', '140558', '010529', '116565', '213228', '059384', '108394', '119196', '088847', '142174', '309838', '718923', 'C16640', '072848', '125308', '696693', '090911', '116638', '173573', '027216', '141448', '518846', '002317', '890938', '101120', '011024', '091402', '111975', '089457', '124887', '087935', '097267', '128207', '017281', '087678', '130640', '082449', '509634', '190404', '100200', '120374', '087041', '061036', '226546', '080520', '523235', '510594', '025344', '283450', '128613', '081133', '103349', '087061', '144834', '102457', '351566', '406395', '089731', '109317', '085879', '148451', '093679', '007991', '100069', '414178', '067060', '132698', '130615', '102802', '050236', '171624', '508969', '126400', '178569', '096046', '104752', '113071', '094933', '521180', '100980', '118845', '094835', '773013', '815446', '007276', '144565', '139436', '094477', '029321', '171615', '103890', '021464', '125242', '013492', '048542', '393103', '175995', '129365', '127884', '116181', '101629', '582587', '139154', '010851', '028224', '125917', '514068', '007783', '283913', '077095', '009169', '138186', '028269', '114085', '187722', '118122', '311615', '097881', '017790', '099932', '118874', '220121', '052422', '180662', '125904', '197357', '092040', '099257', '126747', '128714', '124557', '169944', '059707', '128492', '011374', '094670', '013351', '122257', '095058', '051603', '043008', '115325', '019144', '300813', '281326', '123988', '088105', '118307', '177872', '074017', '857090', '091554', '080548', '110866', '181513', '067010', '097104', '503339', '032311', '133436', '099705', '115196', '019721', '033865', '226690', '127971', '180595', '098904', '129782', '127369', '125204', '714581', '098633', '111527', '008775', '097969', '409683', '124823', '113739', '039359', '087397', '143534', '467918', '011752', '091594', '105342', '145528', '159411', '038952', '115467', '090798', '111971', '111808', '105764', '127687', '100763', '037919', '109362', '015213', '175365', '080946', '117588', '116964', '134688', '089690', '191767', '253355', '272343', '092296', '101018', '095787', '129402', '178381', '118826', '127147', '050476', '125338', '095674', '506852', '133284', '130582', '128197', '194172', '399934', '307682', '105564', '047391', '073462', '035332', '128550', '020941', '091043', '171006', '104617', '134386', '053512', '124159', '114067', '080502', '607868', '108820', '088769', '130721', '016345', '104056', '108212', '090091', '112806', '180290', '112618', '098487', '110663', '091178', '119768', '103244', '155673', '094487', '015732', '109489', '166331', '007426', '101937', '013149', '409760', '101845', '117747', '121517', '126718', '124737', '025695', '023710', '126051', '108362', '119153', '024852', '091103', '120810', '007313']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,W,SR5 (NON GCC),GCC,4.0,4TA,WN72N6,T,Z,159758
1,TOYOTA,RAV4,4.0,SUV,W,LE HEV,GCC,5.0,2T3,W1RFV6,M,C,135629
2,TOYOTA,RAV4,4.0,SUV,W,LE,GCC,5.0,JTD,W13FVX,L,D,058352
3,TOYOTA,RAV4,4.0,SUV,W,VX,GCC,5.0,JTD,WF9EV2,H,D,103765
4,TOYOTA,RAV4,4.0,SUV,W,VX,GCC,5.0,JTD,WF9EV7,G,J,096859
...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,TOYOTA,RAV4,4.0,SUV,W,VX,GCC,NaN,JTD,W13FV2,R,D,119153
949,TOYOTA,RAV4,4.0,SUV,W,GXR,GCC,NaN,JTD,W13FV5,K,D,024852
950,TOYOTA,RAV4,4.0,SUV,W,VX,GCC,NaN,JTD,WF9EV4,G,J,091103
951,TOYOTA,RAV4,4.0,SUV,W,VX,GCC,NaN,JTD,WF9EV3,J,D,120810
952,TOYOTA,RAV4,4.0,SUV,W,EX,GCC,NaN,JTD,W13FV9,K,J,007313

====================================================================================================
POS4: L
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER PICK UP', 'LAND CRUISER', 'LAND CRUISER PICKUP 70', 'HIACE', 'TACOMA', 'HIGHLANDER', 'TUNDRA', 'CAMRY', 'HILUX', 'TOYOTA LAND CRUISER', 'PRIUS', 'LAND CRUISER PICK UP CARGO', 'TOYOTA', '25 LP SC4X44.0L MT', 'TAKOMA', 'LAND CRUISER SINGLE-CABIN PICK', 'RAV4', '4RUNNER', 'INNOVA', 'لاند كروزر', '25 LP SC 4X4 P4.0 MT', 'PREVIA', 'C-HR', 'PICK UP CABIN', 'LAND CRUISER/PICK UP CARGO', 'TOYOTA TACOMA', 'CHR', 'LAND CRUISER/STD EX PICKUP', 'LAND CRUISER PICKUP', '26 LP SC 4X4 P4.0L AT', 'LAND CRUISER - PICK UP CARGO', 'PICKUP', 'PRADO', 'CAMRY HYBRID']
  bodyType: ['PICK UP DOUBLE CAB', 'PICK UP', 'SUV', 'PICK UP SINGLE CAB', 'PICKUP', 'MINI BUS HIGH ROOF', 'VAN', 'CARGO VAN', 'PANEL VAN', 'SEDAN', 'PANEL VAN HIGH ROOF', 'BUS', 'HATCHBACK', 'MPV', 'LIGHT VEHICLE', 'MINI BUS', 'STATION', 'PICK UP DOUBLE CABIN', 'REGULAR CAB']
  pos4: ['L']
  trim: ['GXR', 'STD', 'VX', 'LX', 'LX AC PWR OPT', 'LX WINCH', 'GL', 'GX', 'SC', 'VXR', 'GLS', 'EXR', 'DLS - STD ROOF', 'ST', 'CREWMAX CAPSTONE (NON GCC)', 'SR5 (NON GCC)', 'GXR TOP', '1794 EDITION (NON GCC)', 'GLX', 'SE', 'DLX', 'STD (NON GCC)', '1', 'STD AC', 'XLT', 'GXR FMST', 'GLE HEV BLACK EDITION', 'SR (NON GCC)', 'SR', 'SAFARI', 'GLE HEV', 'GXR TOP FMST', 'ECO', 'HARD TOP', '1500', 'G', 'GXR TOP DMST', 'X', '6', 'SPORT', 'LAND CRUSIER', 'XE 4WD', 'VXR TOP LTH', 'STATION1', 'VXR MID', 'LE HEV', 'PIKUP', 'GXR MID', 'PREMIUM', 'VXR BASE', 'PICKUP', 'GXR SOD D/AC AW', 'XTREME', 'AUTOMATIC', '60TH', 'DLS HIGH ROOF', '1500 CREWCAB SLE Z71', 'LTZ', 'DLS', 'LE (NON GCC)', 'A', 'LX WIDE TYRES', 'TRIM', 'PICKUP ', 'GXR GT', 'BASE', 'PICK UP', '4', 'STANDER', 'GLE', 'SEDAN', 'DLX TOP', '10TH VICTORY EDITION', 'GXR MID XTREME', 'EX', 'STANDARD', 'BLACK EDITION', 'SE T2', 'LE PLATINUM CITY', 'LIMITED', 'TX', 'GXR MID 60TH ANNIVERSARY', 'SLT', '2', 'GR-S', 'SGLX', 'DX', 'S', 'PREMIER', 'VXR TOP', 'TRD SPORT', 'CREWMAX CAPSTONE (NO', '1794 EDITION (NON GC']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JIF', 'JTF', 'JTE', '5TE', '5TD', '5TF', '3TM', '4T1', 'JHH', 'JTD', '3TY', '4T3', 'SAL', 'NMT', 'JMY', 'VF3', 'JAM', 'STF', 'JTJ']
  VDS: ['LU73J7', 'LJ73J1', 'LJ71J9', 'LU73J5', 'LU73J4', 'LU73J9', 'LU73JX', 'LJ73J7', 'LMFCP4', 'LU73J2', 'LJ73J9', 'LV73J7', 'LU73J1', 'LMFCP5', 'LJ73J8', 'LU42N7', 'LU73J0', 'LB3CH8', 'LMFCP8', 'LU73J6', 'LU73J3', 'LB3CHX', 'LB3CH0', 'LJ73J4', 'LJ73J5', 'LJ73JX', 'LB3CH5', 'LU71JX', 'LMFCPO', 'LMFCP2', 'LJ71JX', 'LJ73J2', 'LA5DB6', 'LU4ENX', 'LU71J1', 'LB3CH1', 'LJ73J3', 'LJ73J0', 'LA5AB6', 'LMFCP9', 'L11AK3', 'LB3CH9', 'LU73J8', 'LJ71J7', 'LB3CH6', 'LA5AB4', 'LMFCW1', 'LJ71J3', 'LJ73J6', 'LB3CH3', 'LJ71J2', 'LMFCP3', 'LMFCP7', 'LB71J3', 'LB3CH2', 'LMFCPI', 'LA3AH3', 'LMFCP6', 'LMFCP0', 'LMFCW8', 'LJ71J0', 'LU71J4', 'LA5DB5', 'LMFCPX', 'LB71J5', 'LU4EN4', 'LU71J8', 'LCN1F1', 'LA5GD0', 'LU71J6', 'LU5212', 'LJ71J5', 'LU71J3', 'LA3AH6', 'LB71J8', 'LB3CH7', 'LU4EN9', 'L9RFU8', 'LB3CH4', 'LA5DB0', 'LA5DB3', 'LA5DA2', 'LA5DB4', 'LC5LN2', 'LU42N2', 'LU5218', 'LB71J4', 'LJ71J1', 'LMFCP1', 'LB5JN8', 'LU71J2', 'LA3AH0', 'LJ71J4', 'LV73J9', 'LU4EN7', 'LA5BC7', 'LA3AHX', 'LJ7336', 'LU71J9', 'LU521X', 'LB3CHO', 'LU71J5', 'LM5F10', 'LA5DA8', 'LA5DB1', 'LR73J0', 'LWRFV8', 'LU5JR8', 'LU5F16', 'LB5JN2', 'L83CH1', 'LU71J7', 'LSAAE4', 'LR73JX', 'LB5JN6', 'LU7331', 'LA5DB2', 'LT521X', 'LU4EN2', 'LJ71J6', 'LA3AH4', 'LB5JN9', 'LA5DAX', 'LU5216', 'LA5DA7', 'LU71J0', 'LV73J1', 'LA5DBX', 'LMFCW4', 'LA5EC9', 'LY3FX5', 'LU4EN1', 'LU42N5', 'LA3AH1', 'LMSF17', 'LA5DB8', 'L9MFU9', 'LDHAD8', 'LA5DA9', 'LA5DB9', 'LYV65V', 'LASDB9', 'LV73J6', 'L11AK9', 'LU42NX', 'L35GY8', 'LA5DA5', 'LP345X', 'LJ71J8', 'LU4EN0', 'LA5DA0', 'LA3AHO', 'LA5AB5', 'LA5DB7', 'LB71J0', 'L83CH3', 'LB71J2', 'LA3AH7', 'LV73J5', 'LA3AH2', 'LV73JX', 'LU42N6', 'LV73J4', 'LU5213', 'LU5F18', 'LAAA44', 'LA5EC5', 'LZRBHX', 'LY3FXX', 'LY3FX4', 'LU42N9', 'LJ731X', 'LV73J8', 'LV73JO', 'LU5JR5', 'LU73JO', 'LR73JO', 'LB5JN3', 'LU4EN8', 'LB5JN0', 'LB3CHI', 'L373J0', 'LT5219', 'LU7334', 'LV71J9', 'LU4EN3', 'LU5F14', 'LBACX1', 'LU4EN5', 'LV5211', 'LA3AH5', 'LJ7335', 'LB5JN7', 'LT5216', 'L11AK8', 'L11AK1', 'LA5DA4']
  Model_Year: ['K', '1', '3', 'N', 'H', 'S', 'E', 'F', '9', 'T', '7', 'M', '8', 'A', 'G', 'L', 'C', 'R', 'Y', '2', 'J', 'P', '6', 'D', '4', '5', 'B', 'X']
  Plant_Code: ['B', '6', '8', '7', '4', 'Z', 'S', 'X', 'M', 'U', 'K', '3', 'T', '0', '5', 'A', 'R', 'J']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP DOUBLE CAB,L,GXR,GCC,4.0,JIF,LU73J7,K,B,011123
1,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP,L,STD,GCC,2.0,JTF,LJ73J1,1,6,005284
2,TOYOTA,LAND CRUISER,6.0,SUV,L,VX,GCC,5.0,JTF,LJ71J9,3,8,005799
3,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP DOUBLE CAB,L,GXR,GCC,5.0,JTF,LU73J5,N,B,057621
4,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP DOUBLE CAB,L,GXR,GCC,4.0,JTF,LU73J4,H,7,052241
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2562,TOYOTA,HIGHLANDER,4.0,SUV,L,VXR,GCC,NaN,5TD,LB3CHX,P,S,596722
2563,TOYOTA,HIGHLANDER,4.0,SUV,L,VXR,GCC,NaN,5TD,LB3CH0,P,S,599872
2564,TOYOTA,HIGHLANDER,4.0,SUV,L,VXR,GCC,NaN,5TD,LB3CH0,L,S,003105
2565,TOYOTA,HIGHLANDER,4.0,SUV,L,VXR,GCC,NaN,5TD,LB3CH3,N,S,100947
2566,TOYOTA,TUNDRA,6.0,PICKUP,L,1794 EDITION (NON GC,NON-GCC,NaN,5TF,LA5DB7,P,X,061169

====================================================================================================
POS4: 5
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'COROLLA', 'TERCEL', 'RAV4', 'YARIS', 'AVALON', 'HIACE', 'COROLLA 1.5', 'TOYOTA COROLLA', 'COROLLA 1.3', 'SIENNA', 'ALTIS', 'TACOMA', 'LAND CRUISER', 'كورولا 1.3', 'CROWN V', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'HATCHBACK', 'HALF PANEL VAN', 'MINI BUS', 'MPV', 'BUS', 'SALOON', 'PICK UP DOUBLE CAB', 'MINI BUS HIGH ROOF']
  pos4: ['5']
  trim: ['STD', 'XLI', 'XLI MID', 'EXR', 'BASE', 'LIMITED', 'GL', 'LE HEV', 'GXR', 'S', 'EX', 'GLI', 'LE', 'GLS', 'SR5 (NON GCC)', 'GLX', 'X', 'SE+', 'GXR HEV']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['6T1', 'ZE1', 'JTB', 'JTD', 'JWT', 'JCB', 'JT6', 'JTM', '2T3', 'ACV', '4T2', 'JT8', 'VS5', '454', 'UTD', '3TY', 'AVV', 'FJ7', 'WMA', 'CE1']
  VDS: ['53SK20', '513033', '53EEB0', '53AEB1', '53EL50', '5D3BV4', '53AEA1', '53XK20', '543BV7', '53SK10', '53AEB2', '514884', '596950', '513902', '5AFKGT', '53AEBI', '5X23P5', '509542', '5C3AV4', '5WRFV2', '543AV4', '5D3BV9', '53EEA0', '515001', '511161', '535K20', '510670', '5D3BV7', '53XH10', '53EEBO', '500127', '5X23P9', '501891', '511131', '502581', '56N8U6', '506028', '543AV3', '5X23P1', '501857', '516117', '543AVX', '5D3BV2', '505243', '516227', '512110', '53AFB1', '504705', '5C3AV7', '502370', '5DDDDD', '543BV2', '515739', '5D3BV8', '5C3AV6', '534K20', '509750', '543AV5', '519081', '506377', '511028', '503335', '500188', '508121', '514263', '502877', '505313', '5D3BV5', '500185', '509751', '525AN5', '519401', '512671', '53EE80', '503914', '505003', '5X23PX', '502294', '500617', '56EZZ5', '516804', '506174', '506713', '508736', '511497', '500176', '505046', '513821', '514528', '511890', '505015', '53JSF5', '502968', '516589', '500903', '519729', '511096', '504797', '543BV9', '543BV8', '543BV4']
  Model_Year: ['W', '1', 'X', 'T', 'V', '5', '4', 'G', 'A', '3', 'R', '7', '9', '8', 'L', 'J', '6', 'D', '2', 'M', 'E']
  Plant_Code: ['X', '0', '3', 'D', '9', '2', '6', 'W', ' ', 'N', '5', '1', 'T', '4', 'M', '7']
  Serial_Number: ['350893', '000000', '004584', '342144', '062137', '063188', '067448', '301758', '357877', '342520', '336865', '191808', '651486', '053542', '339444', '003737', '054407', '010636', '168801', '170412', '016620', '000720', '353495', '606456', '345863', '061613', '064463', '184134', '198620', '356515', '004891', '184195', '057259', '020182', '168855', '004413', '006520', '022924', '001596', '085007', '351174', '013052', '013842', '020530', '018617', '019123', '193850', '343780', '038096', '309525', '001075', '342926', '035150', '067863', '339106', '196617', '337751', '342771', '036052', '036142', '337671', '349735', '343532', '197959', '241224', '040775', '194482', '004023', '041885', '302212', '198416', '001651', '068376', '062556', '197053', '016226', '019945', '048155', '062419', '361276', '022044', '033808', '338546', '000974', '348662', '033004', '352729', '016206', '060304', '063397', '009234', '339288', '002092', '056496', '342737', '021700', '010064', '188933', '007033', '196486', '359028', '031070', '356852', '173989', '017868', '200000', '194285', '349223', '057643', '337396', '054053', '360078', '047983', '003022', '339407', '004047', '015135', '354768', '348167', '001664', '349086', '190788', '336628', '061595', '031037', '000963', '174102', '344811', '337151', '336969', '013716', '006954', '361122', '348858', '300314', '060850', '036416', '003619', '339783', '019463', '001139', '000273', '361885', '358560', '171163', '059492', '358743', '188746', '035288', '003616', '166214', '073892', '009721', '020414', '355388', '056565', '022257', '027962', '353329', '001103', '169343', '027269', '029727', '346198', '022041', '353620', '050288', '052235', '652312', '185039', '      ', '346788', '013093', '337164', '035287', '338120', '021113', '055725', '352857', '071279', '014922', '050499', '022680', '032526', '037056', '024438', '359233', 'E9FFA8', '001223', '001419', '009410', '340056', '191373', '067132', '356724', '360267', '017711', '191997', '192278', '028330', '058691', '194826', '346974', '177292', '354765', '064372', '000533', '196223', '035588', '078119', '337057', '174187', '002124', '019235', '342184', '016394', '342106', '347240', '337447', '000455', '190533', '053963', '037120', '195887', '071574', '017040', '348313', '350480', '027949', '049262', '351683', '005632', '067589', '053889', '008581', '065221', '001593', '002096', '301421', '019459', '340246', '052317', '013237', '024449', '034796', '006740', '346625', '339354', '011423', '652405', '336227', '052486', '005040', '071843', '357632', '194176', '062480', '066558', '001021', '025726', '360793', '049765', '171804', '000898', '006545', '339803', '018707', '073074', '007189', '001727', '008467', '349951', '361147', '068163', '003446', '361113', '171604', '066952', '066962', '666666', '058214', '302942', '338654', '051565', '340279', '358447', 'DDDDDD', '068255', '344323', '056392', '035719', '001491', '360461', '346263', '036393', '302198', '022807', '168187', '344704', '183139', '304309', '303595', '351831', '033745', '001115', '170766', '018096', '052649', '056234', '336906', '189651', '002064', '000131', '014344', '048123', '036137', '341629', '000692', '019016', '339539', '337758', '060404', '353422', '002890', '065936', '015722', '004301', '055982', '358642', '023367', '012244', '185978', '975631', '001263', '342706', '360926', '347670', '171759', '196075', '196834', '337874', '052916', '194228', '057593', '177088', '198543', '111111', '346299', '004486', '066055', '357918', '357584', '005924', '336063', '361558', '349714', '019806', '006708', '301624', '195769', '017591', '340414', '356625', '035931', '337047', '358144', '063895', '064270', '002380', '351414', '018586', '010065', '348341', '190298', '048283', '350663', '176362', '044723', '001043', '349555', '359522', '361483', '361051', '054474', '065232', '171962', '032380', '025427', '001152', '336761', '002600', '001694', '004852', '004400', '002585', '360764', '019903', '057519', '056975', '004979', '359019', '056001', '341407', '345833', '350788', '177651', '016575', '655554', '036559', '347705', '342747', '150424', '359383', '343224', '001883', '355640', '019336', '035708', '939639', '359786', '062496', '067815', '348358', '360732', '345325', '337026', '191156', '059606', '064882', '041946', '197683', '190426', '330000', '198214', '062850', '847864', '027440', '344074', '015353', '042384', '336703', '348864', '064220', '012835', '700000', '022151', '168202', '017793', '357250', '050212', '064041', '358246', '134854', '001603', '002929', '030814', '001046', '194937', '197944', '341726', '002616', '048231', '056509', '001244', '187174', '014008', '350533', '068486', '357306', '024850', '013096', '049815', '339292', '001726', '057004', '190783', '042266', '344006', '172304', '355519', '034556', '344744', '166743', '359936', '018567', '011685', '001589', '006534', '017687', '337595', '340545', '196918', '063574', '350375', '346024', '054849', '030181', '019959', '336591', '001011', '350213', '351148', '053208', '349178', '000501', '057694', '170619', '001762', '061763', '077798', '340582', '035486', '000436', '017448', '196543', '349439', '066864', '359607', '028650', '341793', '064829', '346936', '183027', '337769', '347696', '361964', '068167', '001579', '036350', '060327', '018290', '051058', '001766', '348076', '357359', '036242', '348804', '338060', '356572', '001030', '002077', '041577', '347601', '360907', '012267', '166715', '057712', '350669', '064316', '347855', '358563', '338249', '064723', '001604', '001470', '349690', '064895', '019720', '036469', '062187', '043683', '187583', '056909', '168911', '348599', '353232', '055621', '018333', '348585', '166735', '001203', '354816', '000872', '012821', '000782', '002145', '001136', '341036']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,5,STD,GCC,4.0,6T1,53SK20,W,X,350893
1,TOYOTA,CAMRY,4.0,SEDAN,5,XLI,NON-GCC,NaN,ZE1,513033,1,0,000000
2,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,GCC,4.0,JTB,53EEB0,W,0,004584
3,TOYOTA,CAMRY,4.0,SEDAN,5,STD,GCC,4.0,6T1,53SK20,W,X,342144
4,TOYOTA,COROLLA,4.0,SEDAN,5,XLI MID,GCC,4.0,JTB,53AEB1,X,3,062137
...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,NON-GCC,NaN,JTB,53AEB1,W,0,012821
624,TOYOTA,RAV4,4.0,SUV,5,EX,GCC,NaN,JTD,543BV8,T,D,000782
625,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,GCC,NaN,JTB,53EEB0,W,3,002145
626,TOYOTA,RAV4,4.0,SUV,5,EX,GCC,NaN,JTD,543BV4,T,D,001136
627,TOYOTA,CAMRY HYBRID,4.0,SEDAN,5,STD,GCC,NaN,6T1,53SK20,W,X,341036

====================================================================================================
POS4: G
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['PREVIA', 'CAMRY', 'INNOVA', 'RAV4', 'HILUX', 'ALPHARD', 'HIGHLANDER', 'TUNDRA', 'COROLLA', 'TACOMA', 'FORTUNER', 'PRADO', '4RUNNER', 'AVALON', 'HIACE', 'LAND CRUISER', 'SIENNA', 'CAMRY HYBRID']
  bodyType: ['MPV', 'SEDAN', 'SUV', 'PICK UP DOUBLE CAB', 'MINI BUS HIGH ROOF', 'MINI BUS', 'PANEL VAN', 'STATION', 'PICK UP SINGLE CAB']
  pos4: ['G']
  trim: ['SE', 'DLX', 'GL', 'S', 'SE+', 'EX', 'PW CL', 'LIMITED', 'STD', 'GLE-X HEV 40TH ANNIV', 'XLE', 'STD (NON GCC)', 'GXR', 'XLI', 'FABRIC', 'SR5 (NON GCC)', 'GLE HEV', 'LE STD', 'LE HEV', 'LE', 'TOP', 'EXR', 'TOURING', 'GLE', 'BASE', 'DX', 'LE (NON GCC)', 'G', 'GLI', 'GLI TOP', 'GL LTH', 'GRANDE HEV 40TH ANNIV', 'VXR', 'TAXI', 'HEV']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTN', 'JTE', '4T1', 'MHF', 'KMF', 'JT3', '5TD', '5TF', 'YS2', 'JT2', 'MR0', 'ITN', '2T3', 'LSK', 'JTM', 'GGG', 'JD2', '5XX', 'JS1', '3TM', 'VF3', '1GJ', 'LMX', 'JMY', 'WDD', 'STD', 'MHP']
  VDS: ['GE52M3', 'GD34M6', 'GE52M7', 'GD52M9', 'G11AK4', 'G11AK7', 'GX8EM3', 'GD34M0', 'GE52M0', 'GD52M2', 'G11AK0', 'GD52M8', 'GE52M6', 'GE52MX', 'GD32M5', 'G11AK9', 'GE17FX', 'GD52M4', 'GD54M8', 'GD32M1', 'GD32M7', 'GE52M5', 'GE52M2', 'GD54M6', 'GH20V5', 'GD54M9', 'GD52MX', 'GH20V4', 'GD32MX', 'GD54M1', 'GE52M4', 'GE52M1', 'GE52M8', 'GD34M2', 'GD54M5', 'GK3DH4', 'GP10V2', 'G11AKX', 'GZRBH0', 'GD52M6', 'G11AK8', 'GW5F18', 'GP10V1', 'GP10V9', 'GH20V9', 'GD20V5', 'GE52M9', 'GD52M0', 'GP10V8', 'GH20V8', 'GD54MX', 'GX8EM9', 'GD32M8', 'G11AK2', 'GH20V7', 'GD52M3', 'GD32M4', 'GD34M4', 'G6X400', 'GD32M2', 'GX8EMX', 'GBRCH3', 'GK13E8', 'GP10V0', 'GX8EM1', 'GD20V2', 'GD32M6', 'GX8EM5', 'GD52M1', 'GD34M9', 'GH20V6', 'GY5F17', 'GP10VX', 'GD20V1', 'GZ5AN4', 'GX8EM2', 'GD54M7', 'GD54M0', 'G11AK6', 'G11BK8', 'GD32M3', 'GW5F14', 'GD20V8', 'GE52MO', 'GZ3DHX', 'GD54M3', 'GH20V3', 'GY5F18', 'GD34M3', 'GX8EMI', 'GD54M4', 'GP10V3', 'GD20V7', 'GD52M7', 'GK26H6', 'GS54M3', 'G11AK5', 'GX8CD9', 'GN87R6', 'GS54M0', 'GK13E9', 'GA17FP', 'GD34M8', 'GZRBH1', 'GD34M1', 'G11AK3', 'GD52M5', 'GS54M5', 'GX8EM0', 'GX8EMO', 'GD54M2', 'GH20V2', 'GX8EM7', 'GD20V9', 'GP10V6', 'G1RFV9', 'GP21A2', 'GBRCH8', 'GD32M9', 'GD34MX', 'GD32M0', 'GH20VX', 'GD20V0', 'G4AC10', 'GP10V5', 'GD20V3', 'G1RFV6', 'G1RFV7', 'G1RFV4', 'GX8EM8', 'GN86R6', 'GS54M1', 'GZRBH6', 'G11BK7', 'GZ1FB0', 'GA17F3', 'GD34M7', 'GZRAH6', 'G4X205', 'GA17F4', 'GGG565', 'GP10V4', 'GS54M6', 'GP10V7', 'GA17FX', 'GY5F19', 'GZRAH4', 'GS54M8', 'GX8EM6', 'GS54M4', 'GY5F1X', 'GX8EM4', 'GU09J9', 'GJ2110', 'GK13E7', 'GK26H2', 'G31AK0', 'G5GC14', 'GU4L3X', 'G11AK1', 'G1RFV1', 'GU09JX', 'GX72AX', 'GD20VX', 'GZ5AN6', 'GD20V6', 'G11AKO', 'GS54M9', 'GZRAH9', 'GS54MX', 'GZ5AN2', 'GZ3DH5', 'G31AK5', 'GZRBH9', 'GARAH7', 'GBRCH2', 'G11BK6', 'GS54M2', 'GW5F17', 'GZRBH4', 'GD34M5', 'GZ3DH4', 'G1RFV2', 'GK26H1', 'GBKFWB', 'GG25K7', 'GD21A3', 'G14DAO', 'GZ3DH6', 'GK26H4', 'GN87R2', 'GBRCH7', 'GBRCH5', 'G11BK2', 'G622K5', 'G11BK4', 'GNP03V', 'GK12E8', 'GA17F5', 'G31AKX', 'GH20V1', 'GSKFC5', 'GH20V0', 'GZRBH2', 'GZRBH8', 'GY5F14', 'G1RFV0', 'G4BC13', 'GD20V4', 'GK26H3', 'GZ5AN3', 'GF4JB6', 'GX8CD6', 'GR4A69', 'GZ3DH2', 'GES2M2', 'G11BK1', 'GK3DH9', 'GY5F13', 'GX8CD3', 'G1RFV3', 'GA17EP', 'GF46X1', 'GN86R8', 'GJKFWC', 'G11BK3', 'GZ5AN8', 'G11BK5', 'GZ3DH3', 'G11BKX', 'GA17HP', 'GE52MB', 'G4X20X', 'GE52MI', 'GES2M5', 'GZRBH3', 'GXSEM0', 'GRKEC7', 'GN86R9', 'GY5F10', 'GZRBHX', 'G31AK6', 'GK26HX', 'G13FV7', 'GP21A3', 'GX8CD0', 'GU09J1']
  Model_Year: ['J', '5', 'B', '8', 'L', 'M', 'K', 'D', '3', 'H', 'E', '7', 'F', '2', 'A', 'C', '6', 'G', '4', 'Y', 'P', 'N', '9', 'X', 'W', 'S', 'V', 'R', 'T', '1']
  Plant_Code: ['7', '0', 'A', 'U', 'C', '8', 'S', 'X', '5', '2', '6', 'D', 'W', '4', '1', 'G', 'M', 'J', 'Z', 'F', 'N']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,PREVIA,4.0,MPV,G,SE,GCC,5.0,JTN,GE52M3,J,7,167860
1,TOYOTA,PREVIA,4.0,MPV,G,DLX,GCC,5.0,JTE,GD34M6,5,0,301201
2,TOYOTA,PREVIA,4.0,MPV,G,DLX,GCC,5.0,JTN,GE52M7,B,A,027606
3,TOYOTA,PREVIA,6.0,MPV,G,GL,GCC,5.0,JTE,GD52M9,8,A,008695
4,TOYOTA,CAMRY,4.0,SEDAN,G,SE,GCC,4.0,4T1,G11AK4,L,U,917808
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2545,TOYOTA,CAMRY HYBRID,4.0,SEDAN,G,SE,GCC,NaN,4T1,G11AK3,L,U,889533
2546,TOYOTA,PREVIA,4.0,SUV,G,DLX,GCC,NaN,JTE,GD52M4,A,A,018511
2547,TOYOTA,PREVIA,4.0,SUV,G,S,GCC,NaN,JTN,GE52M8,G,A,051212
2548,TOYOTA,PREVIA,4.0,SUV,G,SE,GCC,NaN,JTN,GE52M2,E,7,124181
2549,TOYOTA,PREVIA,4.0,SUV,G,GL,NON-GCC,NaN,JTE,GD52M5,7,0,027880

====================================================================================================
POS4: U
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'TUNDRA', 'HILUX', 'CAMRY', 'HIACE', 'LAND CRUISER', 'DAINA', '4RUNNER', 'DYNA', 'PRADO', 'COROLLA', 'COASTER', 'PICKUP', 'DYNA VAN CARGO', 'TAKOMA']
  bodyType: ['PICKUP', 'PICK UP DOUBLE CAB', 'PICK UP', 'PICK UP SINGLE CAB', 'CARAVAN', 'SEDAN', 'PANEL VAN', 'SUV', 'BUS', 'TRUCK', 'VAN']
  pos4: ['U']
  trim: ['STD', 'STD (NON GCC)', 'SR5 (NON GCC)', 'DLX', 'GL', 'GLX', 'GX', 'LIMITED', 'PICKUP', 'VX', 'DL', 'EXR', 'LWB', 'S', 'SR']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TF', '5TE', '4TA', 'JHG', 'STF', 'MM7', 'JHF', 'JHH', 'JD4', 'JAC', 'JTE', 'WCY', 'JNC', 'KL5', 'JTM', 'JT4']
  VDS: ['UX4EN4', 'UY5F12', 'UY5F14', 'UY5F18', 'UW5F17', 'UY5F15', 'UU4EN4', 'UY5F13', 'UW5F1X', 'UY5F11', 'UY5F1X', 'UX42NX', 'UM5F16', 'UY5F10', 'UW5F11', 'UW5F12', 'UN53B2', 'UF1170', 'UM5F19', 'UM5F15', 'UW5F10', 'UR4DA1', 'UW5F18', 'UY5F19', 'UN236X', 'UY5F17', 'UW5F14', 'UW5F19', 'UY5F16', 'UW5F15', 'UL11H5', 'UCN1H5', 'UM5F12', 'UM5F17', 'UU4EN3', 'UV1822', 'UU4EN0', 'UN2020', 'UWSF16', 'UM5F13', 'UBS25G', 'UYSF14', 'UW5F13', 'UF117X', 'UU5JRX', 'UU42NX', 'U45454', 'UF1171', 'UN2364', 'UW5F16', 'UM5F18', 'UM5F11', 'UF11H3', 'UF11H6', 'UY6F14', 'UYSF18', 'UN53B8', 'UN2362', 'UAD1H1', 'UX4ENX', 'UU4EN1', 'UZD1H4', 'UV1825', 'UM5F10', 'UCK1H0', 'UU4EN5', 'UM5F1X', 'UCK1H5', 'UFJ1H4', 'UN2467', 'UU4ENG', 'UU5JR3', 'UF1176', 'UU4EN6', 'UF11H0', 'UN3463', 'UU42N1', 'UN3163', 'UK42AE', 'UN41B9', 'UYSF11', 'UF1179', 'UY0FJX', 'UN24D9', 'UYSPII', 'UYSF10', 'UM5F14', 'UU5JR5', 'UN2068', 'UY5E14', 'UN24D2', 'UV1826', 'UU4ENX', 'UFJ173', 'UFJ175', 'UX4EN5', 'UU42N9', 'UN2367', 'UX4EN2']
  Model_Year: ['C', 'M', 'A', 'F', 'B', 'E', 'J', 'H', 'G', '5', 'S', 'L', '6', 'D', 'K', '8', 'Y', '2', '7', 'P', '9', '4', 'T', '1', 'V']
  Plant_Code: ['X', 'Z', 'K', 'W', '1', '7', '6', '4', '0', 'A', 'U', '5']
  Serial_Number: ['011426', '994736', '108461', '464287', '118598', '155272', '019453', '381400', '428325', '716950', '594455', '337678', '409473', '157794', '571312', '633017', '705626', '045273', '078097', '554888', '450614', '125546', '098425', '445918', '067075', '374202', '969496', '002338', '128323', '071445', '001124', '625191', '250848', '198693', '085129', '603301', '589502', '098603', '143350', '509156', '176781', '666932', '986554', '401659', '695443', '378789', '108658', '384675', '387569', '173371', '994113', '197653', '005736', '102097', '530334', '012167', '552882', '990376', '264993', '164001', '106697', '761918', '007112', '137691', '196107', '402246', '141277', '127805', '574606', '308140', '161696', '483961', '476079', '122606', '514406', '134976', '546650', '324393', '003508', '507404', '187137', '146653', '112479', '449585', '350469', '029296', '407938', '053607', '095285', '264376', '910894', '909566', '358022', '206180', '475710', '910768', '227873', '275227', '532513', '377133', '744742', '952342', '818813', '638710', '606739', '339203', '632093', '025877', '101002', '076200', '009104', '080943', '319710', '095126', '374298', '113233', '119938', '769362', '247881', '479055', '708029', '791120', '493678', '248405', '477178', '418558', '683192', '335539', '451299', '123707', '381632', '622648', '245325', '011313', '331793', '143254', '584883', '704349', '100394', '279138', '026617', '662666', '459446', '040106', '374986', '100461', '281693', '337651', '339278', '615398', '166127', '272590', '514262', '677558', '099739', '697322', '367385', '361647', '428304', '576022', '444538', '379806', '337290', '001146', '036056', '142105', '323533', '111934', '725877', '359229', '406593', '343201', '533479', '192624', '687774', '001884', '259048', '131958', '189500', '609257', '047935', '442341', '861138', '223725', '235145', '110192', '121217', '904950', '854970', '667089', '545656', '001912', '129381', '417291', '851612', '681994', '917881', '335701', '430224', '117097', '318857', '246520', '559030', '098584', '119440', '971021', '321061', '673939', '746300', '382207', '127918', '458001', '006978', '115533', '183159', '669491', '164257', '097985', '326244', '534149', '111344', '138147', '168263', '334500', '440428', '224486', '381529', '047697', '470472', '638763', '069958', '202668', '442073', '384487', '004857', '214275', '784808', '257749', '480900', '001983', '215835', '692703', '154886', '465805', '732466', '551492', '195621', '498661', '502495', '394968', '633795', '945742', '728573', '909316', '560044', '494912', '553490', '429200', '095380', '529696', '102152', '098733', '201602', '101885', '374875', '098131', '488394', '547440', '085127', '281070', '097495', '340963', '427447', '606590', '078016', '038856', '333648', '127512', '464516', '112765', '821287', '164082', '810295', '767434', '491775', '495603', '721936', '332433', '503333', '958309', '363784', '452164', '198666', '161507', '046000', '428630', '193764', '109757', '285869', '268646', '360922', '790694', '528192', '193079', '589347', '645516', '236658', '454268', '433703', '294515', '375793', '808718', '741201', '405611', '124074', '384512', '790283', '430641', '610681', '184110', '209605', '524744', '450837', '420137', '510200', '158872', '118981', '032611', '101845', '274655', '142889', '312481', '819172', '503414', '429614', '114490', '173249', '610219', '464651', '903707', '424116', '424661', '545040', '307305', '141580', '510831', '039974', '223946', '075932', '475004', '490665', '325111', '845394', '468148', '232131', '100629', '390248', '507956', '149254', '104406', '605808', '009888', '461935', '469452', '516416', '005263', '183839', '514971', '029106', '142788', '907714', '148998', '504850', '339490', '718178', '527276', '114146', '597633', '707604', '335829', '945988', '194624', '285052', '384895', '617260', '692906', '106153', '288272', '002799', '013606', '352625', '875084', '618520', '313910', '368641', '008252', '173791', '452317', '109687', '529914', '525599', '466385', '140239', '685660', '169015', '101401', '190137', '329494', '185708', '230011', '428850', '408298', '060870', '005256', '368595', '674501', '110013', '305344', '986517', '139273', '426266', '481339', '329822', '074300', '498973', '196581', '216499', '271215', '803375', '359371', '685151', '377935', '676550', '687400', '392591', '352915', '677306', '202788', '386531', '406744', '793042', '643728', '127697', '630918', '161326', '999441', '567840', '530799', '904894', '000740', '231858', '645107', '794805', '448068', '469413', '222855', '923846', '257820', '580042', '390741', '281464', '065000', '763831', '118554', '275115', '348486', '481272', '461576', '138728', '994132', '835881', '493076', '501633', '002286', '655281', '121405', '283902', '355036', '157272', '771027', '491280', '463629', '862735', '439173', '135366', '697966', '045697', '676318', '099837', '664164', '367696', '355132', '385393', '625375', '284331', '452625', '801440', '075351', '419417', '626548', '044021', '606494', '710180', '518550', '483582', '372586', '171096', '446852', '222738', '872334', '788287', '742969', '117642', '081017', '462086', '492189', '080894', '377292', '001727', '273611', '262703', '113988', '050027', '735019', '144079', '804431', '323655', '441983', '790986', '157097', '680579', '653631', '360653', '378514', '007540', '355237', '179942', '094611', '280145', '372315', '537139', '451147', '499432', '892538', '119825', '420152', '355444', '709088', '250482', '115449', '079252', '491152', '000164', '156839', '105334', '109809', '452463', '044224', '122149', '770742', '350230', '351949', '252083', '026147', '032428', '237800', '170803', '447489', '095577', '043918', '465512', '095187', '056208', '618930', '534427', '596326', '032453', '152923', '160994', '134296', '511236', '402017', '190604', '329479', '367375', '112300', '171756', '530644', '190225', '501901', '828372', '848543', '553239', '195201', '299279', '044035', '506272', '917175', '001222', '447357', '204234', '112989', '480072', '371271', '149046', '807681', '525731', '601846', '149439', '687702', '097366', '073397', '071015', '568458', '193740', '290618', '756209', '784330', '339027', '045105', '708189', '732641', '229168', '543779', '833708', '127888', '293485', '384303', '225264', '385477', '016848', '238277', '100835', '690299', '462983', '433110', '104261', '190015', '333489', '283671', '026322', '005885', '004803', '463937', '107461', '167890', '158674', '972507', '893152', '118266', '997360', '025098', '114190', '468506', '248925', '652734', '827445', '188467', '336308', '956000', '723733', '798209', '107315', '211595', '102020', '693407', '795462', '467716', '875381', '109038', '619453', '127548', '227811', '437534', '752020', '105647', '041465', '099607', '128494', '836597', '055830', '500883', '452786', '328507', '826325', '113413', '148582', '510738', '761589', '158227', '666467', '469338', '329718', '004799', '410074', '515720', '253570', '120676', '442259', '654508', '515487', '045446', '024808', '173664', '165862', '198395', '531881', '163600', '018578', '680152', '338114', '613447', '109292', '894378', '246832', '159494', '176712', '792640', '534421', '035191', '760007', '385588', '689331', '177789', '403969', '755329', '235774', '023051', '393440', '499118', '530302', '221641', '658271', '098418', '464333', '503271', '890727', '474822', '527148', '048750', '631595', '368919', '322793', '067099', '342389', '876379', '821544', '046981', '519611', '626406', '757326', '151049', '504765', '281761', '530007', '383915', '641337', '753011', '107737', '188941', '206426', '632594', '931611', '744468', '675575', '894438', '118083', '256487', '835055', '463960', '527263', '852601', '337650', '681161', '081843', '111494', '332899', '255277', '351911', '839986', '171102', '383804', '668320', '365783', '243663', '518066', '178435', '222239', '226066', '386727', '123178', '64I337', '901311', '540457', '136293', '440189', '431105', '114195', '730691', '266415', '628341', '485008', '337980', '432816', '041125', '158495', '190002', '995982', '343863', '343918', '419759', '343732', '605208', '606208', '754598', '445370', '504429', '568092', '753592', '356416', '464277', '802042', '603928', '927267', '187268', '097800', '437848', '010350', '405817', '177328', '237158', '173335', '101252', '390802', '641885', '099744', '133543', '200297', '129912', '653718', '332479', '267935', '172016', '223360', '157567', '669004', '215412', '176494', '192612', '128372', '539035', '615883', '069704', '410827', '495234', '205639', '428531', '255638', '469667', '883195', '836920', '388906', '685558', '344907', '172347', '307092', '696947', '637269', '678446', '081268', '004506', '411793', '640550', '177517', '903593', '507593', '326997']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TACOMA,6.0,PICKUP,U,STD,GCC,NaN,5TF,UX4EN4,C,X,011426
1,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,U,STD (NON GCC),GCC,4.0,5TF,UY5F12,M,X,994736
2,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,U,STD (NON GCC),GCC,4.0,5TF,UY5F14,A,X,108461
3,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,U,STD (NON GCC),GCC,4.0,5TF,UY5F18,F,X,464287
4,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,U,STD (NON GCC),GCC,4.0,5TF,UW5F17,A,X,118598
...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),NON-GCC,NaN,5TF,UY5F18,H,X,640550
891,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),NON-GCC,NaN,5TF,UY5F17,B,X,177517
892,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),NON-GCC,NaN,5TF,UY5F14,L,X,903593
893,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),NON-GCC,NaN,5TF,UY5F1X,G,X,507593
894,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),NON-GCC,NaN,5TF,UY5F19,E,X,326997

====================================================================================================
POS4: 6
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'RAV4', 'COROLLA', 'PREVIA', 'HIACE', 'CELICA', 'YARIS', '4RUNNER', 'LAND CRUISER']
  bodyType: ['PICK UP SINGLE CAB', 'SUV', 'SEDAN', 'MPV', 'MINI BUS HIGH ROOF', 'PICK UP DOUBLE CAB', 'COUPE', 'PANEL VAN', 'MINI BUS', 'STATION']
  pos4: ['6']
  trim: ['DLX', 'PW CL', 'XLI', 'XLI MID', 'S', 'GL', 'XLI TOP', 'STD', 'FLEET', 'DLS - STD ROOF', 'LE', 'BASE', 'GX', 'E', 'LIMITED']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['WDB', 'JTE', 'JTB', 'JTN', 'LJ1', 'WD8', 'RK4', 'YN8', 'JTD', 'LFZ', 'JT3', 'VF3']
  VDS: ['652047', '6H20V7', '64AEB2', '6D32M9', '6E52M1', '652037', '6E52M0', '6AE3C6', '655532', '652136', '6D52M5', '656205', '6E52M2', '659338', '6E52M4', '64STL3', '615242', '652004', '656516', '6E52M3', '600238', '658050', '659343', '6W9230', '6H20V3', '6D54M7', '656109', '66B3D9', '63AL59', '63AL55', '6D32M1', '600198', '6N87R6', '6E52M8', '6JKFWC', '6E52M7', '6D52M2', '655533', '63AL46', '66B3D4', '64EEB0', '659101', '621017']
  Model_Year: ['1', '2', 'W', 'X', '5', 'F', 'D', 'E', '8', 'V', 'H', '7', 'S', 'P', '6', 'R']
  Plant_Code: ['5', '0', '7', 'A', '2', 'K', '1', 'D', 'J', '3']
  Serial_Number: ['738892', '069779', '001360', '001716', '013232', '004284', '048196', '589064', '038076', '000828', '167104', '003934', '526845', '053839', '233036', '118641', '723047', '033821', '121778', '273901', '285802', '000000', '038967', '136084', '001359', '123208', '281420', '038707', '001033', '149584', '027964', '001056', '001011', '012273', '228603', '254778', '001155', '058438', '058419', '030896', '111111', '052649', '048275', '033852', '023913', '011048', '001127', '047355', '113886', '250373', '000282', '287759', '277331']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,2.0,WDB,652047,1,5,738892
1,TOYOTA,RAV4,4.0,SUV,6,PW CL,GCC,3.0,JTE,6H20V7,2,0,069779
2,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,4.0,JTB,64AEB2,W,0,001360
3,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,4.0,JTB,64AEB2,X,0,001716
4,TOYOTA,PREVIA,4.0,MPV,6,DLX,GCC,5.0,JTE,6D32M9,5,7,013232
5,TOYOTA,COROLLA,4.0,SEDAN,6,XLI MID,GCC,4.0,JTB,64AEB2,X,0,004284
6,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M1,F,A,048196
7,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,2.0,WDB,652037,1,5,589064
8,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M0,D,A,038076
9,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,6,GL,GCC,4.0,LJ1,6AE3C6,E,2,000828
10,TOYOTA,COROLLA,4.0,SEDAN,6,XLI TOP,GCC,NaN,WDB,655532,1,K,167104
11,TOYOTA,COROLLA,4.0,SEDAN,6,XLI MID,GCC,4.0,JTB,64AEB2,X,0,003934
12,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,6,DLX,GCC,4.0,WDB,652136,1,5,526845
13,TOYOTA,PREVIA,4.0,MPV,6,DLX,GCC,5.0,JTE,6D52M5,8,7,053839
14,TOYOTA,PREVIA,4.0,MPV,6,STD,GCC,5.0,WDB,656205,1,K,233036
15,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M2,E,7,118641
16,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,6,DLX,GCC,4.0,WD8,659338,1,5,723047
17,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M4,D,A,033821
18,TOYOTA,CELICA,4.0,COUPE,6,STD,GCC,2.0,JTB,64STL3,V,0,121778
19,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,2.0,WDB,615242,1,5,273901
20,TOYOTA,HIACE,4.0,PANEL VAN,6,STD,GCC,5.0,WDB,652004,1,K,285802
21,TOYOTA,COROLLA,4.0,SEDAN,6,S,GCC,NaN,RK4,656516,1,0,000000
22,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M0,E,A,038967
23,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M3,H,7,136084
24,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,NaN,YN8,600238,2,7,000000
25,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,NaN,WDB,658050,1,K,001359
26,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M2,E,7,123208
27,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,2.0,WDB,659343,1,K,281420
28,TOYOTA,YARIS,4.0,SEDAN,6,FLEET,GCC,4.0,JTD,6W9230,7,1,038707
29,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,4.0,JTB,64AEB2,W,0,001033
30,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M0,H,7,149584
31,TOYOTA,RAV4,4.0,SUV,6,PW CL,GCC,3.0,JTE,6H20V3,1,0,027964
32,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,4.0,JTB,64AEB2,W,0,001056
33,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,4.0,JTB,64AEB2,W,0,001011
34,TOYOTA,PREVIA,6.0,MPV,6,GL,GCC,5.0,JTE,6D54M7,8,A,012273
35,TOYOTA,RAV4,4.0,SUV,6,STD,GCC,NaN,WDB,656109,1,K,228603
36,TOYOTA,HIACE,4.0,MINI BUS,6,DLS - STD ROOF,GCC,NaN,LJ1,66B3D9,S,2,254778
37,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,4.0,JTB,64AEB2,W,0,001155
38,TOYOTA,RAV4,4.0,SUV,6,LE,NON-GCC,5.0,LFZ,63AL59,P,D,058438
39,TOYOTA,RAV4,4.0,SUV,6,LE,NON-GCC,5.0,LFZ,63AL55,P,D,058419
40,TOYOTA,PREVIA,4.0,MPV,6,DLX,GCC,5.0,JTE,6D32M1,5,7,030896
41,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,NaN,YN8,600198,6,1,111111
42,TOYOTA,4RUNNER,6.0,SUV,6,STD,GCC,5.0,JT3,6N87R6,V,0,052649
43,TOYOTA,PREVIA,4.0,MPV,6,S,GCC,5.0,JTN,6E52M8,F,A,048275
44,TOYOTA,RAV4,4.0,SUV,6,BASE,GCC,5.0,VF3,6JKFWC,8,J,033852
45,TOYOTA,PREVIA,6.0,MPV,6,GL,GCC,5.0,JTN,6E52M7,8,A,023913
46,TOYOTA,PREVIA,4.0,STATION,6,DLX,GCC,NaN,JTE,6D52M2,8,A,011048
47,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,4.0,JTB,64AEB2,W,0,001127
48,TOYOTA,COROLLA,4.0,SEDAN,6,XLI TOP,NON-GCC,NaN,WDB,655533,1,K,047355
49,TOYOTA,LAND CRUISER,6.0,SUV,6,GX,GCC,NaN,LFZ,63AL46,P,D,113886
50,TOYOTA,YARIS,4.0,SEDAN,6,E,GCC,NaN,LJ1,66B3D4,R,2,250373
51,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,4.0,JTB,64EEB0,W,3,000282
52,TOYOTA,COROLLA,4.0,SEDAN,6,LIMITED,NON-GCC,NaN,WDB,659101,1,K,287759
53,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,STD,GCC,NaN,WDB,621017,1,5,277331

====================================================================================================
POS4: S
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'CAMRY', 'TACOMA', 'HILUX', 'COROLLA', 'TUNDRA', 'YARIS', 'LAND CRUISER 70', 'MR 2', 'RAV4', 'LAND CRUISER', 'U7']
  bodyType: ['MINI BUS', 'MINI BUS HIGH ROOF', 'SEDAN', 'HALF PANEL VAN', 'BUS', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'PANEL VAN HIGH ROOF', 'VAN', 'PICK UP SINGLE CAB', 'PICK UP', 'MINI BUS SEMI HIGH ROOF', 'SUV', 'COUPE', 'MPV', 'PICKUP']
  pos4: ['S']
  trim: ['GL', 'GLX', 'GLE HEV', 'DX', 'SE', 'SR5 (NON GCC)', 'DLX', 'GLE-X HEV 40TH ANNIV', 'STD (NON GCC)', 'STD', 'LE HEV', 'XLI EXECUTIVE', 'GLS', 'LE', 'DX H/R W/B', 'SE+', 'GLI HEV', 'DL', 'XLI', 'GLI', 'GRANDE HEV 40TH ANNIV', 'HT SLWB', 'GLE', 'GRD', 'S', 'MID', 'GL DECKLESS', 'BASE', 'DLS', 'LIMITED', 'GXR TOP', 'DLS - STD ROOF']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTG', 'JT2', '4T1', '5TF', '3TY', 'JM3', 'JTF', 'JTD', '4TA', '5YF', 'KNC', '5TE', 'KNF', '1FT', 'MHF', '1GN', 'KMH', 'LHP', 'WDB', '1C6', 'JH2', 'JHD', 'LKL', 'JMY', 'RF5', 'SKF']
  VDS: ['SX22P6', 'SX22PX', 'SX22P2', 'SX22P3', 'SK12E4', 'SX22P1', 'SX22P8', 'SX23P1', 'SX23P5', 'SX23P3', 'SX22P4', 'SX23PX', 'SX23P9', 'SX23P6', 'SX23P7', 'S11AK0', 'SZ5AN1', 'SX23P2', 'SX22P7', 'SX5EN1', 'SL35E6', 'SMFAP6', 'SK12W1', 'S4MCE7', 'SX22P5', 'SN92N6', 'SMFAP7', 'SX23P0', 'SX22P0', 'SX23P8', 'SK12E7', 'SMFAP1', 'S4MCEX', 'S4MCE1', 'SX22P9', 'SX23P4', 'SMFAP9', 'SK12E2', 'SL35E2', 'SMFAP3', 'SK12W4', 'SE0142', 'SN92N8', 'SK12E0', 'SM92NO', 'S4MCE9', 'S4MCE4', 'SL35E4', 'S4RCE4', 'S4RCE9', 'S4RCE1', 'S4RCEI', 'S4MCE3', 'S4RCE2', 'SZ5ANX', 'SJZ74A', 'SD35E5', 'S11AK7', 'S4MCE5', 'SS23P1', 'SV541X', 'STZ74A', 'S4RCE8', 'SMFAP0', 'SK12E5', 'S4MCE2', 'SK12E8', 'SS3EL5', 'ST9F36', 'SK8KD7', 'SK12W3', 'SK12E9', 'SK11E2', 'SW21M8', 'SE0342', 'SK12EX', 'SD0110', 'SMFAP4', 'SHX74C', 'SD35E9', 'SK12CX', 'S4MCE6', 'S31AK5', 'S4RCEX', 'SM92N0', 'S4RCE5', 'SV5413', 'SZ5AN8', 'SD35E4', 'SN92N2', 'S4RCE7', 'SX23PO', 'SK12E6', 'SX22PO', 'SK12W6', 'SMFAPX', 'S11BK2', 'SK12W8', 'SJ8IVP', 'SFABD9', 'SK75F3', 'SX5EN7', 'SMFAP2', 'SRFJT9', 'S4MCE0', 'SC87C2', 'SD911X', 'SX5EN4', 'S4RCE6', 'SX5EN0', 'SS1EK5', 'SS1EK7', 'SZ5AN5', 'SS22P2', 'SBAS3X', 'SZ5AN6', 'SZ5AN9', 'S4RCE3', 'SRCSLA', 'SMFAP5', 'SMFAPO', 'SK12W9', 'S71T02', 'S4RCE0', 'SK12W0', 'SK12FX', 'S11AK9', 'SY5F15', 'SC79M9', 'SZ5AN0', 'ST5415', 'SZ5AN3', 'SN92N0', 'SZ5ANZ', 'SK12E1', 'SS23PX', 'SMFAP8', 'SJN3BC']
  Model_Year: ['8', 'K', 'J', 'N', 'A', 'G', 'D', 'C', 'E', 'F', 'P', 'L', 'H', 'M', '6', '7', 'X', '9', 'S', 'B', '5', '1', 'W', 'R', '4', 'T', 'Y']
  Plant_Code: ['6', '0', 'U', 'X', 'T', '8', 'J', 'Z', 'P', 'K', 'D', 'R', '3', '7', 'G', 'F', 'N', '1', 'B', 'S']
  Serial_Number: ['032750', '204656', '199659', '192350', '014971', '077424', '200006', '167454', '128426', '125328', '202996', '137428', '127649', '146788', '189780', '024408', '198050', '160443', '108158', '232253', '092007', '149824', '203659', '202562', '157105', '162584', '198079', '115900', '182155', '010047', '120553', '129688', '029705', '187426', '004208', '322994', '079355', '188159', '181163', '012869', '186219', '548979', '050401', '005661', '143545', '203336', '197434', '158491', '188069', '146039', '877710', '185130', '164994', '009944', '148272', '062909', '150969', '088952', '142331', '128221', '143809', '197939', '124219', '003195', '192183', '117979', '181098', '140855', '192266', '184884', '177418', '065209', '314780', '117952', '053285', '199908', '139946', '095701', '112340', '118267', '117759', '192873', '172747', '179220', '006955', '167731', '022792', '180233', '395266', '197876', '823302', '141009', '122274', '889455', '179241', '012281', '147730', '547619', '131498', '144028', '152164', '064792', '162306', '201642', '119904', '024367', '113030', '161957', '187780', '139226', '025762', '158394', '017683', '084781', '117192', '186914', '178230', '203477', '001275', '009180', '181899', '178708', '124627', '187497', '185887', '184856', '144554', '155507', '191645', '193382', '187141', '010977', '142228', '115691', '150258', '025910', '181349', '187266', '165313', '165273', '136217', '049851', '182875', '177996', '109504', '185532', '009902', '204827', '527028', '199939', '199486', '106253', '685380', '173799', '001696', '082240', '110050', '202210', '004018', '187012', '159022', '154940', '198041', '441558', '006983', '049191', '146999', '191335', '100598', '006430', '050208', '192772', '181062', '143976', '162586', '201072', '179343', '149731', '142556', '163801', '402602', '190333', '179300', '119971', '185174', '067352', '068751', '193383', '312841', '136658', '188078', '178736', '023801', '151936', '189496', 'A15620', '029678', '179719', '188153', '133396', '094598', '183712', '154368', '007074', '461124', '179604', '118845', '871696', '167315', '157984', '155904', '193004', '201164', '143863', '024294', '179623', '137078', '508147', '139593', '307903', '153944', '069655', '129285', '003548', '072254', '198392', '006437', '143816', '338090', '177668', '151496', '116565', '152700', '154536', '234511', '125037', '142881', '381668', '199021', '991674', '021636', '069239', '155716', '181219', '011737', '147041', '186786', '043209', '181080', '192756', '136845', '141519', '006789', '146433', '183950', '150179', '003753', '647407', '146880', '156527', '491460', '107843', '176799', '193418', '146179', '022492', '112811', '851393', '137353', '401430', '128138', '062907', '172781', '180520', '156370', '005386', '080197', '136922', '004701', '145520', '156677', '054561', '005988', '202131', '563061', '039895', '559673', '032759', '182199', '121888', '184481', '051853', '031538', '023180', '161881', '003566', '145594', '180842', '100369', '120588', '198270', '182483', '187362', '069831', '124898', '134734', '004783', '180177', '194548', '180516', '102310', '200364', '121148', '463917', '159487', '170410', '187795', '055725', '093250', '004272', '190621', '186364', '011178', '027865', '010377', '106894', '200069', '169435', '130867', '054264', '203270', '161417', '124168', '592786', '179451', '130475', '201974', '201505', '075973', '201898', '162059', '059932', '033416', '204207', '132926', '112937', '292730', '178642', '860604', '182563', '118969', '142487', '178395', '203233', '145789', '154421', '141060', '114896', '129213', '006464', '318021', '040911', '180398', '148055', '152209', '115995', '190454', '154318', '183368', '044760', '186179', '006340', '038172', '204650', '041863', '162491', '173349', '065628', '460129', '143004', '144951', '051318', '098175', '144730', '000186', '139281', '125619', '195645', '008104', '029346', '200433', '197134', '323752', '200150', '181590', '006841', '204307', '199972', '139262', '088957', '200640', '052220', '009659', '154735', '142494', '158967', '195260', '200053', '480553', '200123', '136140', '070029', '009051', '178438', '050521', '211855', '190336', '522215', '193556', '183256', '188416', '100003', '004280', '850898', '160623', '099660', '049212', '105735', '180458', '180215', '867193', '102652', '191109', '188183', '190081', '201012', '013942', '134024', '144185', '077293', '141291', '004299', '168477', '182452', '004735', '154260', '009656', '147413', '070656', '062110', '003024', '192673', '097722', '188590', 'S10498', 'S10499', '200320', '230149', '142849', '167121', '168174', '018586', '086533', '600067', '857498', '097639', '131752', '120230', '146105', '028656', '004166', '162834', '502383', '137541', '136212', '204392', '201311', '180714', '016801', '125625', '171376', '006519', '036400', '203493', '034256', '705366', '183600', '170270', '167050', '193212', '006522', '009663', '613094', '069723', '171059', '020825', '171078', '190985', '055802', '167745', '003572', '138198', '451833', '188489', '157404', '000008', '136023', '147165', '176850', '188002', '188473', '183269', '197647', '047830', '143436', '178453', '203276', '248468', '107909', '199060', '113500', '197857', '013752', '178132', '140834', '188673', '202149', '178188', '635589', '204384', '036251', '006534', '048843', '131565', '198600', '119621', '179620', '153518', '004119', '132421', '159146', '150221', '179357', '185347', '098354', '125107', '183644', '191161', '180067', '180247', '006532', '130053', '090914', '121689', '181847', '118663', '204334', '100948', '037301', '071066', '011960', '119127', '112559', '143188', '183342', '154553', '178891', '201242', '137071', '152529', '164594', '160171', '198448', '194266', '146508', '004112', '271145', '055391', '185150', '075387', '141960', '094679', '120215', '192029', '034705', '190507', '700158', '188423', '202687', '201870', '181705', '024036', '200702', '135921', '002938', '141942', 'S10584', '135794', '001128', '179494', '189427', '195999', '180808', '852107', '196735', '181568', '085893', '188187', '006862', '196313', '119843', '121772', '158035', '193095', '004325', '764424', '038191', '080759', '142701', '139042', '186114', '124604', '130718', '876794', '134856', '003914', '135219', '005516', '201102', '155128', '176726', '132187', '171163', '162210', '002974', '201495', '335924', '198790', '148332', '122788', '215321', '008154', '186419', '071506', '171225', '131090', '199428', '037106', '003705', '103759', '069733', '140345', '156318', '161934', '193420', '178493', '025175', '098941']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,MINI BUS,S,GL,GCC,4.0,JTG,SX22P6,8,6,032750
1,TOYOTA,HIACE,4.0,MINI BUS,S,GL,GCC,5.0,JTG,SX22PX,K,6,204656
2,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,S,GLX,GCC,4.0,JTG,SX22P2,J,6,199659
3,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,S,GLX,GCC,4.0,JTG,SX22P3,J,6,192350
4,TOYOTA,CAMRY,4.0,SEDAN,S,GLE HEV,GCC,4.0,JT2,SK12E4,N,0,014971
...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,TOYOTA,HIACE,4.0,MINI BUS,S,GL,GCC,4.0,JTG,SX23P9,F,6,161934
659,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,S,GLX,GCC,4.0,JTG,SX22P3,J,6,193420
660,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,S,GLX,GCC,4.0,JTG,SX22P7,H,6,178493
661,TOYOTA,TACOMA,6.0,PICKUP,S,SR5 (NON GCC),NON-GCC,NaN,5TF,SZ5AN5,G,X,025175
662,TOYOTA,COROLLA,4.0,SEDAN,S,STD (NON GCC),NON-GCC,NaN,JTD,S4MCE3,N,J,098941

====================================================================================================
POS4: 3
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'CAMRY', 'DAINA', 'COROLLA', 'HIACE', 'LAND CRUISER PICK UP', 'FORTUNER', 'DYNA', 'هايلوكس']
  bodyType: ['PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'SEDAN', 'PICKUP', 'PICK UP', 'MINI BUS', 'SUV']
  pos4: ['3']
  trim: ['DLX', 'STD', 'SE+', 'STANDDARD', '1500', 'GLX', 'XLI MID', 'MID', 'TOP', '1', 'XLI', 'BASE', 'GL', 'S', 'SED', 'GLI', 'LE', 'SE', 'LX']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTB', 'MAT', 'MD6', 'JTD', 'UAE', 'RN1', '010', '4T1', 'XWB', 'YBL', 'JT8', 'K20']
  VDS: ['31UNE6', '33UNG0', '33YN87', '33UNE0', '33UNE6', '31UJ75', '31UNE0', '31YN87', '381228', '374185', '381324', '32BUM1', '37DE71', '33RN85', '3R22E7', '31UNE2', '3S0113', '350007', '31UNG0', '31YN81', '33UNGO', '31RN85', '303H66', '3G22K7', '3K32ED', '3546FG', '38BS17', '33UNEQ', '3B0075', '33RNA4']
  Model_Year: ['W', 'X', 'V', 'G', '8', '6', 'S', '7', 'A', '1', '5', 'R']
  Plant_Code: ['0', '1', '3', '7', '9', '6', '2', '5', 'U', 'A', '4']
  Serial_Number: ['001590', '001175', '009889', '012745', '033800', '009228', '007650', '004931', '009252', '001831', '012006', '002939', '000995', '003243', '025763', '010248', '011385', '006059', '008953', '005157', '011745', '011130', '033348', '039204', '005282', '001512', '009387', '002641', '010424', '009240', '005355', '002357', '006733', '006790', '002388', '009981', 'L00083', '014006', '007138', '011578', '005028', '009334', '005958', '005045', 'L02558', '002871', '013128', '009253', '003421', '007482', '000169', '006908', '012227', '035874', '008395', '009268', 'L00536', '004459', '014911', '007644', '004117', '008460', '000319', '002266', '000311', '011375', 'B00102', '002747', '005491', '003546', '169272', '020315', '002600', '006469', '006973', '167621', '010411', '008231', '004109', '010013', '007585', '201034', '002931', '001871', '013824', '012327', '012323', '009103', '006696', '23919 ', '024793', '025394', '008569', '004563', '005869', '010183', '011424', '003430', '001149', '010177', '001092', '012973', '007821', '003332', '005016', '000991', '012828', '003517', '001867', '011645', '007594', '005073', '011823', '012502', '011107', '007183', '001471', '009923', '002179', '009197', '002190', '006931', '006135', '003363', '012361', '009564', '007351', '035426', '011169', '003195', '012372', '009760', '010288', '211111', '014082', '007438', '032154', '012080', '009844', '012760', '001854', '004324', '006177', '001039', '007150', '008714', '002352', '009766', '003860', '010225', '004476', '006247', '014553', '012281', '005811', '009429', '009243', '007207', '003291', '008902', '007195', '008726', '021732', '013406', '001917', '009885', '003846', '009518', '007409', '001605', '007425', '167702', '012878', '005010', '001629', '011692', '008139', '013511', '013394', '000784', '001064', '001957', '010176', '173829', '011773', '009280', '000277', '012153', '025290', '005543', '002741', '012865', '012951', '025174', '036092', '013203', '111111', '009817', '010270', '008859', '010105', '001748', '010796', '014013', '029665', '004381', '003066', '002705', '014482', '003327', '009955', '001358', '003302', '001498', '013480', '010243', '002231', '007166', '011800', '001242', '001114', '008999', '005056', '012105', '012352', '002206', '002769', '013612', '166685', '007100', '008348', '012035', '012305', '011663', '001086', '010766', '001899', '009350', '011990', '003244', '012983', '045876', '001146', '007626', '454645', '001890', '009321', '012290', '012240', '010583', '011969', '008930', '010730', '005653', '004052', '008835', '001046', '002126', '010200', '010609', '001476', '003628', '012343', '006645', '011041', '003201', '006842', '008220', '006774', '011944', '012704', '003940', '008383', '008000', '010844', '006277', '004418', '001836', '011828', '038982', '011254', '007593', '003878', '011206', '169465', '034174', '008473', '014062', '167872', '001779', 'A20031', '034485', '011920', '011066', '011686', '006702', '003412', '009534', '011103', '014835', '014836', '029783', '006622', '013561', '005451', '014842', '009474', '002458', '004579', '001925', '007439', '003029', '011361', '006921', '010223', '010187', '011483', '013727', '008868', '025431', '012331', '002219', '001321', '008447', '003935', '010689', '000947', '167344', '008260', '029538', '009239', '035684', '007193', '013537', '000000', '014991', '005059', '003922', '015777', '001227', '034008', '008785', '009158', '004435', '000646']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,GCC,2.0,JTB,31UNE6,W,0,001590
1,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,GCC,2.0,JTB,33UNG0,W,0,001175
2,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,STD,GCC,2.0,JTB,31UNE6,X,0,009889
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,012745
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,STD,GCC,2.0,JTB,33UNE0,X,0,033800
...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,TOYOTA,HILUX,4.0,PICKUP,3,DLX,GCC,NaN,JTB,33UNE0,X,0,034008
347,TOYOTA,HILUX,4.0,PICKUP,3,STD,GCC,NaN,JTB,31UNE6,X,0,008785
348,TOYOTA,HILUX,4.0,PICKUP,3,STD,GCC,NaN,JTB,33RNA4,V,0,009158
349,TOYOTA,HILUX,4.0,PICKUP,3,DLX,GCC,NaN,JTB,31UNE6,W,0,004435
350,TOYOTA,LAND CRUISER PICK UP,4.0,PICKUP,3,LX,GCC,NaN,JTB,31UJ75,V,3,000646

====================================================================================================
POS4: 7
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'COROLLA', 'CAMRY', 'HIACE', 'HILUX', 'RUSH', 'MR2', '900', 'COASTER', 'CAMRY HYBRID']
  bodyType: ['SUV', 'SEDAN', 'PANEL VAN', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'COUPE', 'WINDOW VAN', 'STATION', 'BUS']
  pos4: ['7']
  trim: ['GXR', 'XLI', 'STD', 'XLI MID', 'EX', 'GL', 'DL', 'LE', 'XLI TOP', 'DLX', 'GLI', 'DX', 'ST', 'STD (NON GCC)']
  regionalSpec: ['GCC']
  WMI: ['JTB', '6T1', 'VF3', 'KL7', 'L6T', 'VF7', 'LFZ', 'CM8', 'JT1', 'MAT']
  VDS: ['72SC11', '71SC10', '72AEB2', '72EEB0', '72SK20', '72SK10', '7JNFU6', '7LHEP2', '72AEA1', '7FNFU8', '7ENFUZ', '72EEA0', '79END0', '79YND1', '7ANFU0', '72EEBO', '79END6', '7ENFU8', '7CNFU6', '73FM49', '7ANFUC', '7KE438', '71SC18', '7ENFU9', '79END5', '751068']
  Model_Year: ['W', 'X', 'V', 'F', 'S', 'K', '3', 'E', 'P', '1', '8']
  Plant_Code: ['0', '4', 'X', '9', 'J', 'C', '7', 'T', 'D', '3', 'F']
  Serial_Number: ['191691', '176291', '000935', '001118', '000342', '171684', '910160', '000834', '164485', '910264', '166403', '174596', '176471', '187285', '179882', '357463', '910875', '173120', '165117', '001655', '910045', '198995', '357337', '192134', '001005', '910451', '192982', '515922', '000675', '161643', '910080', '000936', '153573', '193041', '156576', '001262', '000530', '172154', '156089', '156645', '001586', '177011', '357043', '910726', '001226', '000547', '000464', '175522', '910705', '910482', '181319', '067417', '910130', '083496', '000672', '190900', '507185', '172046', '001512', '001164', '515786', '019131', '085783', '180954', '186353', '192737', '000670', '198792', '178466', '000386', '001559', '239077', '169278', '000781', '250817', '193637', '187687', '001487', '001117', '910343', '017416', '174979', '001097', '358370', '180424', '001113', '001273', '000444', '001008', '000348', '188770', '169512', '174900', '184430', '187742', '000137', '001400', '357121', '000416', '000211', '082874', '176570', '179536', '000894', '091047', '910521', '358185', '000953', '181933', '001697', '910354', '177762', '357512', '000059', '000053', '509520', '181222', '910173', '173189', '001106', '001743', '000829', '088977', '910952', '248866', '910232', '001546', '001150', '000392', '192149', '910437', '171306', '357759', '193396', '910340', '018385', '515828', '172909', '910165', '910330', '910657', '357379', '000776', '000231', '000877', '600802', '193191', '910969', '357437', '001185', '014270', '172780', '910359', '001198', '001734', '183648', '001366', '910478', '165565', '506556', '193277', '001156', '174702', '314568', '910680', '014237', '000357', '096280', '503560', '000178', '175174', '000968', '184921', '001098', '080275', '174457', '180192', '000825', '237504', '001173', '001128', '189665', '001000', '910175', '179034', '179204', '000385', '000352', '000866', '167069', '158349', '000569', '168222', '175081', '185146', 'L00010', '191765', '357861', '175109', '910047', '910368', '001069', '173247', '001086', '157912', '001727', '000607', '910679', '910137']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,RAV4,4.0,SUV,7,GXR,GCC,5.0,JTB,72SC11,W,0,191691
1,TOYOTA,RAV4,4.0,SUV,7,GXR,GCC,5.0,JTB,71SC10,W,0,176291
2,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,GCC,4.0,JTB,72AEB2,X,4,000935
3,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,GCC,4.0,JTB,72AEB2,X,4,001118
4,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,GCC,4.0,JTB,72EEB0,W,4,000342
...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,TOYOTA,RAV4,4.0,SUV,7,GXR,GCC,5.0,JTB,72SC11,W,0,157912
210,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,GCC,4.0,JTB,72EEB0,X,4,001727
211,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,GCC,4.0,JTB,72AEB2,W,4,000607
212,TOYOTA,CAMRY,4.0,SEDAN,7,XLI,GCC,4.0,6T1,72SK20,X,X,910679
213,TOYOTA,CAMRY HYBRID,4.0,SEDAN,7,STD,GCC,NaN,6T1,72SK20,W,X,910137

====================================================================================================
POS4: 1
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'COROLLA', 'HILUX', 'RAV 4', 'T 300', 'TUNDRA', 'FLTRXS', 'AVALON', 'PRADO', 'YARIS', 'CAMRY', 'RUSH', 'CROWN', 'HIACE', 'WISH', 'RAV4', 'PREVIA', 'FLHTK', 'STANZA', 'KING LONG PASSENGER', 'VELOZ', 'INNOVA', '2008', 'LAND CRUISER PRADO']
  bodyType: ['SUV', 'SEDAN', 'PICK UP DOUBLE CAB', 'STATION', 'MOTORCYCLE', 'HATCHBACK', 'BUS', 'MPV', 'PANEL VAN', 'PANEL VAN HIGH ROOF', 'PICKUP', 'MINI BUS', 'PICK UP SINGLE CAB']
  pos4: ['1']
  trim: ['GXR', 'XLI MID', 'STD', 'XLI', 'GX', 'DLX', 'SV', 'ADVENTURE', 'VX', 'EXR', 'STD (NON GCC)', 'DLS', 'GLI', 'DL', 'PREMIER', 'LIMITED', 'LE', 'PRADO', 'GLX', 'GLE', 'AUTOMATIC', 'MPV', 'S', 'MID', 'SE', '1', 'GLS', 'GL2', 'DLX TOP', 'BASE', 'PICK UP', 'E', 'DX', 'EX', 'H', 'XLI TOP', 'XLT', 'GL TOP']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTB', 'ANE', 'ZSG', 'LA7', 'LZC', 'LHA', 'LTA', 'ZRE', 'LKL', 'ZZE', 'LJ1', '5HD', 'IG1', 'WYU', 'NSP', 'N1N', 'JZS', 'SXV', '1HD', 'LGF', 'KNR', 'LA6', 'SXA', '1N1', 'JT8', 'LAZ', 'NCP', 'W11', '6TB', 'WDB', 'UZS', 'W01', 'EP9', 'D02', 'VZE', 'L11', '111', 'LFB', 'STM']
  VDS: ['11UJ83', '120010', '11WJA0', '11UJ80', '100319', '11UJA0', '1CUG30', '116000', '1215CX', '11WJAO', '120076', '1201DX', '11VJ95', '11UJAO', '12H2P3', '142442', '1AAA66', '142700', '11VJ90', '1KFCD3', '1KBBC1', '120066', '1KTP45', '145839', '142704', '11WJAD', '142440', '145457', '151407', '1N1ENV', '151005', '171000', '107013', '120055', '1201D7', '120077', '171007', '1YYK27', '151004', '1202F7', '1HBJW0', '120049', '1L1HEA', '142443', '172554', '142523', '142524', '11UJ94', '1BAA33', '110053', '172570', '111111', '172551', '11AC10', '1CU837', '150702', '1E33K0', '124022', '1KBBD4', '150700', '1CU835', '100305', '1FHPC6', '1779DX', '151403', '142703', '1BAA34', '151517', '1BAA38', '1ZH159', '111S11', '1F0091', '1BAA37', '1201D2', '120009', '172561', '107305', '120039', '1111W1', '1111S1', '120053', '1AU933', '120030']
  Model_Year: ['V', '7', 'W', '6', 'P', '9', 'X', 'K', '8', 'S', '2', 'N', 'E', 'L', 'G', '4', '1', '5', '3', 'D', 'Y', 'R', 'B', 'F']
  Plant_Code: ['5', '9', '8', '6', '0', 'A', '2', '3', '1', 'B', 'U', '7', '4', 'F', 'T', 'X', 'C', 'S']
  Serial_Number: ['005601', '900000', '000035', '003099', '006173', '007109', '400000', '006444', '059581', '010081', '006744', '008626', '002630', '006649', '008563', '3     ', '000385', '000390', '003337', '001046', '000006', '004765', '004546', '003920', '008646', '000092', '9     ', '005743', '005643', '006489', '052160', '005312', '002148', '001912', '002683', '011773', '005503', '005422', '009961', '006808', '006374', '006022', '005795', '001660', '006099', '002907', '320000', '007885', '804011', '005662', '006847', '002541', '009645', '007271', '000700', '003811', '002036', '005760', '002508', '005224', '008968', '005931', '990000', '003674', '116113', '500778', '001427', '003012', '007382', '004913', '029873', '004916', '627186', '110618', '006522', '002321', '000225', '160000', '006348', '004404', '001263', '009268', '006285', '004902', '001481', '001307', '004735', '003128', '301111', '008396', '003281', '005697', '000508', '009838', '009336', '487487', '003975', '35    ', '008035', '002190', '010497', '004374', '005324', '006298', '041644', '013438', '005709', '001036', '004489', '002352', '003739', '013850', '006869', '001089', '003467', '030897', '026662', '001735', '004703', '250000', '000811', '036155', '810000', '002006', '005314', '003678', '000000', '001989', '013974', '011513', '008532', '000280', '001902', '004243', '002351', '007376', '001941', '000966', '006011', '012199', '007828', '004837', '000993', '003549', '004561', '001521', '004406', '004356', '003044', '200000', '002842', '000488', '017869', '006874', '006034', '980111', '069758', '002267', '970000', '008247', '007858', '002393', '005602', '005675', '004673', '008930', '000708', '003067', '001067', '006693', '006012', '006795', '000674', '001465', '006520', '165018', '7XXXXX', '004095', '001848', '390000', '450000', '005935', '003719', '001354', '007328', '010743', '003018', '004163', '008593', '005977', '005627', '002338', '009423', '009496', '004221', '006789', '007054', '004853', '761111', '010930', '910000', '590000', '006057', '005265', '006343', '008695', '006576', '006180', '032041', '006067', '003645', '003530', '006268', '045680', '005354', '001141', '002774', '006442', '001182', '514345', '521111', '023163', '007951', '004958', '004014', '005044', '048420', '006956', '008611', '002125', '700000', '151111', '000788', '003705', '111111', '006787', '005379', '001381', '003375', '004281', '312997', '004139', '005804', '001673', '920000', '150686', '311111', '447871', '011203', '073505', '003433', '009813', '006541', '006731', '006141', '011123', '000486', '410000', '002069', '236525', '003954', '010083', '252132', '000180', '036455', '045716', '175417', '004726', '003419', '008156', '003655', '304444', '150847', '600201', '019673', '004035', '003554', '006439', '009218', '002437', '006784', '005648', '006086', '002475', '004781', '011908', '001250', '820000', '046523', '001845', '003691', '048309', '005124', '596541', '046417', '052937', '004814', '000903', '002364', '002447', '003560', '005162', '009365', '007055', '001030', '020266', '002004', '003795', '003188', '000068', '009638', '880000', '002703', '502350', '000718', '016095', '052947', '020695', '004749', '037543', '006043', '006514', '004942', '047390', '521RF1', '016264', '010325', '004036', '007938', '505963', '001812', '007999', '313103', '003402', '004662', '002296', '006372', '003073', '002367', 'A81700', '514333', '006510', '000090', '008451', '000252', '008241', '006719', '024280', '005996', '007400', '000935', '010190', '001041', '000644', '000145', '511111', '009524', '003446', '003251', '002670', '005008', '010143', '000746', '001985', '004397', '010133', '033295', '006187', '006903', '003687', '007917', '005974', '001970', '005916', '000248', '006636', '614221', '005930', '003659', '004660', '500000', '006734', '011392', '007224', '007849', '002291', '006690', '007910', '006069', '004809', '008084', '003094', '780000', '027875', '000080', '006584', '006047', '005097', '011507', '051705', '005038', '002736', '006197', '002931', '004065', '005872', '031105', '911111', '005050', '006904', '800000', '000302', '001629', '005504', '005799', '033412', '009543', '600000', '010042', '006895', '000873', '002588', '045964', '003039', '005245', '006574', '630082', '001523', '007393', '000637', '008027', '006279', '003453', '008674', '038445', '003261', '004604', '006085', '004524', '006429', '004128']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11UJ83,V,5,005601
1,TOYOTA,COROLLA,4.0,SEDAN,1,XLI MID,NON-GCC,NaN,ANE,120010,7,9,900000
2,TOYOTA,LAND CRUISER,8.0,SUV,1,STD,GCC,5.0,JTB,11WJA0,W,8,000035
3,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11UJ80,V,6,003099
4,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11UJ80,V,6,006173
...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,TOYOTA,LAND CRUISER,8.0,SUV,1,GX,NON-GCC,NaN,JTB,11WJA0,W,8,004604
479,TOYOTA,LAND CRUISER,8.0,SUV,1,GX,GCC,NaN,JTB,11WJA0,W,8,006085
480,TOYOTA,LAND CRUISER,8.0,SUV,1,1,GCC,NaN,JTB,11WJA0,W,8,004524
481,TOYOTA,LAND CRUISER,8.0,SUV,1,STD,GCC,NaN,JTB,11WJA0,W,8,006429
482,TOYOTA,LAND CRUISER PRADO,6.0,SUV,1,NaN,GCC,NaN,JTB,11VJ90,X,0,004128

====================================================================================================
POS4: 8
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'COROLLA', 'LAND CRUISER', 'ECHO', 'YARIS', 'RAV4', 'SUPRA', 'PRADO', 'AVALON', 'FJ CRUISER', 'COROLLA 1.3', 'HIACE', 'SALOON', 'HILUX', '2009', 'COROLLA 1.6', 'TUNDRA', 'TERCEL', 'SEQUOIA', 'TOYOTA PRADO', 'LITEACE', 'AURION', 'SIENNA', 'COROLLA SEDAN', 'HILUX ADVENTURE', 'ORION', '1.8 XS', 'TOYOTA']
  bodyType: ['SEDAN', 'SUV', 'SALOON', 'COUPE', 'HATCHBACK', 'PANEL VAN HIGH ROOF', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'PICKUP', 'STATION', 'PANEL VAN', 'MPV']
  pos4: ['8']
  trim: ['XLI', 'XLI TOP', 'GX', 'PS PW CL', 'XLI MID', 'FLEET', 'MID', 'BASE', 'SE', 'S', 'GLI', 'STD', 'LE', 'VX', 'STD (NON GCC)', 'GL', 'T', 'SE+', 'SE TRD AERO PK', 'AXL ', 'VXR', 'TOP', 'GLS', 'STANDARD', 'GXR3', 'GLX SPORT Z', 'TX', 'EXCLUSIVE', 'XLE (NON GCC)', 'GLE', 'TOURING', 'GRANDE', 'DLS', 'GLE HEV', 'E', 'SPORT', 'GLI TOP', 'GLX', 'GXR', 'EXTREME', 'LIMITED', 'DLX', 'EXR', 'XLE', 'ADVENTURE', 'BE', 'STANDERD', 'LIMITED TOP', 'GLE-X', 'XLI EXECUTIVE', 'LE (NON GCC)', 'YA', '60TH', 'LIMITED MID', 'SV', 'XLE TOURING', 'SR5 (NON GCC)', 'ST', 'DL', 'LX']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['4T1', 'JTD', 'JTF', 'RKL', 'JT2', '6T1', 'JTM', 'JTN', '2T1', 'JZA', 'JTE', '4T4', 'MR2', 'MHF', 'CLG', 'FZJ', 'JTH', 'MR0', 'NV1', '5T1', 'JJ7', 'JM3', '5T8', '211', '5TD', '5TF', 'MHE', '5YF', 'MV1', 'JT0', 'MHK', 'LZZ', 'CPB', '471', '1NX', '150', 'AT1', 'JL7']
  VDS: ['8A32KX', '8E32K9', '8R23E5', '8V71J4', '8242E7', '8W1339', '889HE9', '8V42E6', '8F22K4', '8R23EX', '8F1FK0', '8C42E1', '8W9237', '8E32KX', '8D31V8', '8F30K1', '824HK7', '8242E6', '8V42EX', '8A13E6', '811HK2', '8A02E6', '800014', '8E32K3', '8F1FK3', '8K46K6', '8L29J0', '8D33V2', '8E46K7', '8846K0', '8C42E7', '8F9FK4', '8K3687', '8V42E9', '8E32K6', '8F9FK7', '8U4EE6', '8D31V4', '8F1FKX', '8T9F32', '8L29J3', '8U11F6', '8K46K0', '8K36B8', '8T9237', '8U3FJ4', '8242E8', '8W9234', '8F4HKX', '8F1FK7', '8K3DBX', '8T9F31', '8622K0', '8622K1', '8U4EE4', '8F1FK2', '8V42E8', '8E32K7', '8E32K1', '8T9F3X', '8D1FK5', '8K1FK3', '8C42E5', '8R22E9', '8W923X', '8N95J3', '800025', '8K3685', '8W23E6', '8T9F33', '8K36B5', '8F4HK7', '8U3FJ8', '8G22K9', '8E32K8', '8K3D89', '855HZK', '8V42E0', '8R32EX', '8F32K6', '8F9FKX', '824HK5', '8F3EK1', '8W9231', '800083', '829F36', '8D31V3', '8D31V7', '880CE2', '819HK1', '8URHE9', '8X9FJ1', '8U40E6', '8J4665', '8D31V1', '8U4EE7', '8W9331', '8F9HK9', '8K3681', '8U8CD2', '8K40K6', '8F9FK9', '8R23E6', '8U4EEX', '8R32E1', '8F1FK9', '8E32K4', '8C42E8', '802339', '811HK6', '814HK4', '8W9239', '8X8CD8', '811HK5', '8V42E4', '804733', '8N95J2', '8V42E2', '8W9238', '829F3X', '8B9HE9', '8L9HE9', '8E32K5', '8W1332', '8K33V9', '8V42E7', '8242E4', '8A13EX', '8L9HE7', '8T9233', '889HEX', '8T9F35', '8W9233', '829F38', '829F30', '8622K6', '803285', '824HK6', '8622K5', '8R42E5', '803454', '8D33V0', '808508', '8622K7', '804307', '8E30K9', '8W9232', '8F3EKX', '8E42K5', '8C42E0', '800005', '8F4FKX', '8W1334', '8U11F9', '8F3EK3', '8L9HE8', '805931', '8E30K7', '8W1338', '8D31V5', '8F4HK9', '802744', '8F3EK8', '8622K4', '88OCEX', '880CEX', '8E33K1', '809870', '8E30K3', '8E42KX', '8U3FJ3', '8R23E2', '8F4DV0', '8U11F2', '8F32K7', '8CE1K7', '8D31V0', '8D35E5', '8E46K2', '8D31V9', '8W23E4', '8T9F36', '8U3FJX', '8R23E9', '8622K2', '805832', '8C42EX', '8V5414', '8F30KX', '8D33V7', '8K3684', '804134', '8D33VX', '8K1E85', '8622K8', '8E32K2', '800004', '8W1233', '8U11F7', '8F30K7', '8U11F1', '813FV9', '8622K3', '8U8CD9', '8K3EK1', '809434', '8FREV1', '8F9FK0', '8J53L3', '8F9HK4', '8F3EK7', '8K1E87', '8F9FK8', '8E32K0', '8E42K3', '8RI2E0', '8T9F37', '8K32V5', '8L9HE2', '8Z4HK3', '829F32', '8F9HK2', '8F9HKX', '8E42K0', '8F9FK6', '8C42E9', '8X9FJ0', '800971', '8FIFK9', '8F9FK2', '8E42K1', '806367', '8Y64A2', '8U11F8', '810187', '8V5418', '8C42E6', '8622K9', '809867', '8L0HE3', '8W1331', '808931', '8E46K6', '801FKA', '800030', '814HK8', '809072', '8L29J1', '8V42E5', '8622KX', '8242E3', '8F9FK5', '824HKX', '8U3FJ6', '8E46K3', '807726', '8L9HEX', '8F30K0', '8L29J7', '829HK4', '8U4EE9', '8U4EE2', '800631', '8242E1', '8E46K0', '8E33K2', '8E46K9', '8Y64A5', '8242E9', '8K31V3', '8R42E2', '8U11F0', '8F31FX', '800157', '8F1FK5', '8F9C30', '8F1FK4', '802811', '8K4FK9', '8A23C0', '8R22E4', '8D31VX', '801259', '800426', '8E30K2', '8Z4HK2', '819F32', '8W23EI', '8D31V2', '8842E9', '8U11FX', '805336', '8F9FK1', '8CCVD0', '8R23E0', '8E46KX', '8R22E7', '8F3EK4', '8W133X', '824HK2', '87N071', '803505', '8D31V6', '8242EX', '805326', '808764', '8V42E1', '8K31V9', '8G22K1', '8Y5F16', '8E42K6', '8U11F3', '804598', '8E33K6', '8842E4', '8K33V0', '8W1335', '8C42E3', '8CCVD9', '8R22E2', '829F31', '8846K5', '8F9FK3', '814HKX', '8U3FJ1', '8T9F34', '8T9F39', '805485', '8R23E8', '8W9F3X', '889HE2', '8E30K6', '889HE6', '8E42K8', '8F1FK6', '8W9230', '8CE1K3', '8B9HEX', '804646', '8R32E6', '824HK3', '800957', '8F4FK8', '8T9F38', '8W9236', '8F3EK0', '8F9C35', '8K22C0', '87367Z', '811EB7', '8BCE1J', '8U5CD1', '8L9HE3', '807674', '829F35', '8K40K3', '8X9FJ8', '8E42K9', '8F38K0', '802510', '8L9HE5', '8W9235', '807611', '8U25JX', '809514', '8E42K7', '800788', '8F30K4', '8L9HE6', '814HK5', '8D33V6', '8A02EX', '8U3FJ5', '8U11F4', '8R23E1', '804077', '808390', '8FREV7', '8F1FK1', '8R22E3', '8F9EV4', '8V5416', '8842E6', '8T9F30', '8842E8', '8242E0', '8E30K4', '8Y5619', '8E42K4', '8F28K8', '803180', '8Y64A4', '8K3680', '805587', '829F34', '8V5412', '8F3EK6', '8U3FJ9', '8E30KX', '8T9238', '805065', '811HK4', '8F9EV0', '801838', '8U4EE5', '8842EX', '8F4HK0', '8628KX', '829HKX', '809506', '8E42K2', '8U40E4', '8808E2', '8U71J6', '8V42E3', '8E30K0', '8A08E1', '8U4EE0', '807007', '8R22E6', '8D33V8', '800253', '8K3686', '8J53LX', '8D1FK2', '889HE5', '8E30K8', '8URHE5', '808905', '8W23E5']
  Model_Year: ['5', '6', 'N', 'A', '3', 'D', 'X', '4', '8', '9', '2', 'K', 'C', 'Y', 'J', 'T', 'H', '7', 'F', 'E', 'B', '1', 'L', 'W', 'M', 'R', 'P', 'S', 'V', 'G']
  Plant_Code: ['U', '3', '8', 'J', '0', '5', '4', 'X', 'C', '1', 'R', 'K', '9', '6', 'L', '2', 'D', 'P', '7', 'A', 'S', 'W']
  Serial_Number: ['047666', '057332', '112865', '049375', '045334', '040309', '144265', '655341', '211075', '082521', '201143', '301128', '065003', '018325', '522529', '218728', '020968', '010825', '011766', '441256', '101789', '010199', '112245', '600000', '976201', '726098', '075564', '077158', '083028', '122122', '023530', '518155', '710929', '413036', '616663', '495457', '655618', '099655', '192126', '511952', '211359', '105154', '003469', '043761', '011670', '254969', '179366', '048824', '426197', '073959', '018008', '024082', '002824', '597369', '410148', '747024', '126062', '457825', '017404', '780773', '992860', '957184', '440400', '578848', '520832', '039064', '047903', '511616', '502839', '068075', '067759', '077085', '3     ', '301214', '255904', '101658', '025135', '010430', '022445', '189225', '268881', '477508', '391687', '718998', '467124', '468962', '032354', '164304', '494659', '019248', '214981', '012498', '100000', '092591', '268359', '286168', '318917', '001709', '138629', '088054', '037779', '164985', '273256', '334766', '002022', '688645', '509867', '000951', '026126', '085795', '074674', '133190', '920831', '377863', '016951', '482430', '586445', '243269', '046056', '827455', '310022', '000000', '110123', '076439', '203996', '733677', '496563', '024305', '845516', '185316', '405836', '478893', '679254', '350506', '093151', '248923', '191304', '301186', '267408', '410145', '027701', '043990', '155549', '036876', '205508', '264510', '689850', '063112', '628420', '061146', '475544', '005019', '029586', '738219', '094443', '255071', '034093', '220356', '132625', '028657', '136125', '088293', '625817', '553521', '032342', '839475', '018967', '414053', '271572', '034611', '663516', '111111', '602173', '410220', '593625', '030285', '150357', '571567', '506331', '448325', '135563', '611111', '674394', '425052', '040606', '241319', '116484', '521748', '710973', '258014', '876541', '987799', '502261', '126873', '074941', '291711', '003429', '418836', '551947', '508533', '553789', '984948', '013290', '459544', '086081', '534111', '120112', '169168', '028234', '104708', '039612', '574371', '005322', '120694', '424965', '479374', '113687', '017995', '107201', '057544', '124856', '429201', '155205', '186257', '593129', '301276', '300690', '011028', '523307', '079973', '301586', '650801', '212234', '034869', '270428', '140724', '497831', '412958', '855555', '065483', '221176', '009856', '352419', '077620', '053314', '046678', '287942', '050824', '867090', '069865', '808987', '101725', '613735', '448375', '493027', '743956', '503319', '019644', '094662', '537453', '010785', '096006', '581072', '009262', '537245', '228122', '068051', '513094', '018624', '246221', '037209', '512449', '866285', '130245', '021355', '063083', '235809', '250121', '284517', '576100', '033898', '473209', '506950', '490434', '085036', '050337', '018769', '005686', '455336', '456540', '308134', '039263', '246929', '204828', '512596', '407028', '580668', '028120', '472492', '641028', '489690', '068356', '248411', '814745', '021240', '308494', '517641', '282855', '011185', '215052', '039590', '561165', '157832', '988756', '118155', '229553', '659774', '695870', '509848', '862544', '053127', '053399', '059185', '614893', '497383', '023049', '014197', '140069', '193129', '545678', '004127', '194070', '362058', '223262', '623836', '122761', '057151', '440406', '060620', '655016', '926018', '222043', '032753', '302965', '971074', '311676', '476658', '24678G', '077161', '130743', '372995', '275362', '022522', '380761', '163504', '035980', '641592', '010308', '027609', '186409', '000586', '478731', '509225', '095948', '022233', '618315', '216945', '609170', '066449', '637393', '960471', '018580', '003580', '063080', '433849', '411331', '191420', '186587', '575525', '532326', '246582', '022479', '018161', '620321', 'Q06269', '115916', '117154', '514846', '941919', '007618', '015475', '020100', '059768', '379560', '061914', '636369', '090105', '416206', '098165', '135552', '507568', '329016', '228562', '085298', '416454', '204631', '413541', '027696', '509229', '572035', '051469', '083597', '009255', '069322', '063881', '271691', '027541', '010783', '000112', '003527', '930860', '518425', '444444', '228435', '140093', '052389', '181385', '012533', '344029', '443785', '400948', '020348', '578998', '271165', '099639', '071456', '445375', '147794', '005802', '537271', '005887', '571122', '042317', '060705', '513615', '254249', '457289', '636368', '190928', '514941', '312310', '063065', '406083', '474505', '488736', '919038', '121910', '235976', '044527', '017610', '105976', '938888', '441333', '264445', '013760', '551928', '248886', '039892', '240148', '207082', '110825', '434252', '059578', '477501', '100355', '065559', 'R12345', '255392', '036248', '537021', '004516', '240473', '577188', '494365', '095608', '035091', '550396', '047277', '325842', '206230', '001323', '570803', '538108', '00B9B7', '013795', '577541', '413619', '221605', '089882', '249099', '114278', '006404', '682009', '179016', '309227', '410721', '058595', '695560', '033125', '341230', '054738', '024332', '222222', '101129', '360970', '556788', '064100', '080750', '151802', '019689', '542210', '029675', '616872', '150568', '067189', '574734', '529412', '502162', '125781', '023794', '162546', 'K02371', '094147', '502445', '195572', '216217', '723442', '516974', '065768', '905135', '252601', '055464', '105449', '538456', '919706', '104711', '586946', '079241', '963559', '233780', '221868', '142324', '027469', '496088', '039392', '091023', '645456', '467600', '605124', '143305', '391600', '983234', '156318', '213020', '480567', '481590', '003857', '016530', '104648', '077344', '020314', '103220', '236753', '329332', '204896', '534252', '047559', '156116', '288748', '539008', '451873', '542560', '839769', '109174', '147112', '062004', '360372', '074907', '238532', '363130', '745874', '025492', '052459', '122178', '063161', '236072', '045451', '534702', '300712', '013110', '029823', '388050', '722464', '413265', '203662', '129652', '243058', '589091', '500646', '265114', '193482', '087137', '307789', '033090', '490351', '560521', '007508', '192695', '079823', '305153', '213102', '011192', '316226', '552235', '528239', '496887', '084186', '212580', '448943', '460916', '050621', '030341', '004739', '451872', '716145', '224952', '069199', '274106', '114340', '049708', '005942', '086324', '199907', '074580', '125269', '722956', '691785', '025126', '175796', '703577', '687705', '177775', '056480', '542287', '165595', '113363', '529490', 'SSSSSS', '112739', '599090', '104681', '009161', '569819', '683563', '523429', '392236', '101000', '022225', '768996', '020939', '047320', '058967', '118440', '069468', '273305', '613054', '461226', '023574', '507562', '020415', '216194', '157995', '187456', '091717', '059033', '098693', '727093', '097041', '302765', '469200', '386516', '102521', '460172', '001905', '220169', '302397', '036630', '084921', '110227', '724389', '060154', '059824', '972372', '017740', '204142', '008549', '521739', '353095', '494808', '642490', '116353', '455495', '006238', '034577', '133264', '625312', '300980', '339820', '002714', '606545', '648880', '074890', '171765', '628354', '054522', '001241', '012212', '028033', '013542', '154870', '029846', '082797', '025806', '548060', '102634', '036983', '451235', '060357', '165286', '774561', '007740', '123323', '002385']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,GCC,4.0,4T1,8A32KX,5,U,047666
1,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,GCC,4.0,JTD,8E32K9,6,3,057332
2,TOYOTA,COROLLA,4.0,SEDAN,8,XLI TOP,GCC,4.0,JTD,8R23E5,5,3,112865
3,TOYOTA,LAND CRUISER,6.0,SUV,8,GX,GCC,5.0,JTF,8V71J4,N,8,049375
4,TOYOTA,COROLLA,4.0,SEDAN,8,XLI,GCC,4.0,JTD,8242E7,A,J,045334
...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,GCC,4.0,4T1,8E30K8,6,U,165286
782,TOYOTA,COROLLA,4.0,SEDAN,8,GLI,GCC,NaN,5YF,8URHE5,J,P,774561
783,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,GCC,4.0,4T1,8E32KX,5,U,007740
784,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,GCC,NaN,NV1,808905,7,W,123323
785,TOYOTA,TOYOTA,4.0,SEDAN,8,LX,GCC,NaN,JTD,8W23E5,1,0,002385

====================================================================================================
POS4: N
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'TUNDRA', 'HILUX', 'HIACE', 'RAV4', 'TAKOMA', 'FORTUNER', 'LAND CRUISER PICK UP', 'RUMION', 'TOKOMA', '4RUNNER', 'LAND CRUISER', 'AVALON', 'COROLLA', 'تاكوما', 'CAMRY', 'SIENNA']
  bodyType: ['PICK UP DOUBLE CAB', 'PANEL VAN', 'PICK UP', 'PICK UP SINGLE CAB', 'SUV', 'PICKUP', 'MPV', 'SEDAN', 'STATION']
  pos4: ['N']
  trim: ['STD (NON GCC)', '1794 EDITION (NON GCC)', 'DLX', 'GL', 'STD', 'VX', 'LMV', 'CREWMAX CAPSTONE (NON GCC)', '1500', 'DL', 'EXR', 'EX', 'SR', '1', 'LE HEV', 'PRESTIGE', 'LIMITED', 'XLE', 'GXR TOP', 'C', 'S', 'TOP', 'BASE', 'SINGLE CABIN', 'SE', 'GLE', 'LE (NON GCC)', 'TRIM']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TE', '5TF', 'JAA', 'JT4', '4TA', 'JTM', 'MA3', 'LWL', 'NNN', '2T3', 'JTF', 'JTD', 'JTE', '1GT', 'HJN', '4T1', 'STE', 'GTF', 'WMA', 'LFC', '5TD']
  VDS: ['NX4CN9', 'NC5DBX', 'NX4CN8', 'NHR55E', 'NX22N1', 'NX22N3', 'NG4268', 'NL42N7', 'NX4CN6', 'NL42N6', 'NY5F12', 'NL42N1', 'NM92NX', 'NFREVX', 'NX4CN4', 'NC5DB9', 'NX4CN2', 'NL42N2', 'NX4CN3', 'NX22N0', 'NM92N8', 'NL42NX', 'NX4CNX', 'NC2B16', 'NX4CN5', 'NRRTX4', 'N00001', 'NFREV6', 'NFREV7', 'NG4269', 'NX4CN0', 'NG4263', 'NFREV8', 'NX22N2', 'NG4262', 'NL42N8', 'ND22S0', 'NM92N6', 'N1RFV8', 'NL42N9', 'NX22N5', 'NFREV4', 'NC5DB0', 'NX62N0', 'NA5DB3', 'NX22N9', 'NG4265', 'NX22N8', 'NX4CN1', 'NY5F14', 'NL42N5', 'N1RFV9', 'NX22N7', 'NG426X', 'NM92N4', 'NU5JR3', 'N19EC0', 'NU5JR2', 'NX22N4', 'NADMG2', 'NL42N3', 'NG4260', 'NC5EC1', 'NU5JR9', 'NB1BB2', 'NL42N4', 'N1RFV7', 'NX22NX', 'NX4CN7', 'NY5F17', 'NG4266', 'NT08J2', 'NFREV5', 'NFREV1', 'NA5DB2', 'NFREV9', 'NG4264', 'ND22S2', 'NE4261', 'NM92N5', 'NA5DB6', 'NX22N6', 'NU5F10', 'N00011', 'NU5JR1', 'N1RFV6', 'NL42N0', 'NPR66P', 'NC5DB3', 'NX0375', 'N38ZZ6', 'NC5DB6', 'NG4267', 'NZ1AK4', 'NNG6P5', 'NFREV2', 'NM92N2', 'NA3DCS', 'NA5DBX', 'NA5DB1', 'NA5DB7']
  Model_Year: ['A', 'P', 'B', 'W', '8', '6', 'Y', '4', 'F', 'X', 'G', 'C', '3', 'R', 'D', '2', 'E', '7', '1', 'M', 'K', 'J', '5', 'H', 'T', 'S', '9', 'N', 'L', 'V']
  Plant_Code: ['Z', 'X', '7', '0', 'J', 'A', 'L', '1', 'W', 'C', '6', '5', 'D', 'U', '2', 'Y', '8']
  Serial_Number: ['673290', '016486', '008261', '100214', '586001', '277949', '002746', '410118', '735728', '108832', '181114', '519881', '583106', '003814', '073846', '013118', '190761', '548513', '045125', '005114', '025788', '135542', '139673', '037431', '437187', '801221', '123188', '033869', '027641', '293754', '592365', '016572', '030933', '011236', '512515', '111111', '066585', '486574', '006579', '003972', '007806', '055920', '734865', '001181', '005182', '722321', '222165', '314581', '004263', '195807', '450675', '404576', '005379', '603877', '003169', '020343', '623195', '024218', '168179', '666165', '288320', '002650', '002132', '236957', '050066', '724175', '217254', '409168', '023382', '288554', '625242', '271403', '005099', '135353', '013834', '005098', '037028', '023381', '194061', '161454', '029439', '177281', '140351', '386948', '002819', '517421', '005729', '009492', '578013', '019343', '371035', '011537', '035026', '550374', '003142', '256734', '045292', '171894', '873564', '578359', '889194', '087932', '043219', '059085', '104057', '610149', '003483', '004262', '040059', '554935', '485818', '001234', '004568', '353269', '039191', '295811', '004891', '127569', '034541', '089378', '002380', '718142', '206916', '686057', '368292', '280626', '573683', '076653', '006453', '010268', '715483', '753257', '219598', '003285', '035197', '040309', '004265', '036761', '692632', '215803', '004774', '351994', '027574', '587718', '307941', '025059', '021036', '030778', '422656', '095687', '405915', '364674', '195693', '345128', '033394', '620498', '735744', '643493', '097724', '463374', '031454', '705527', '731133', '018195', '002130', '734839', '573993', '603816', '845237', '594313', '003987', '277035', '114382', '250242', '030348', '003242', '002531', '002508', '002243', '314422', '476921', '001431', '626233', '739038', '125893', '653990', '016653', '626203', '146369', '528351', '039549', '042358', '006303', '192464', '562965', '024636', '052741', '578356', '053297', '021228', '439431', '005113', '031433', '007241', '355266', '005626', '424999', '136488', '245038', '078016', '671786', '123829', '374676', '088394', '036852', '040480', '002514', '745010', '020521', '359675', '824983', '004548', '003857', '550366', '413769', '100207', '025386', '031833', '040306', '141083', '026331', '087648', '276641', '012894', '244011', '004717', '004745', '036930', '005100', '065981', '001759', '002565', '417501', '086310', '028900', '006317', '033458', '110305', '017038', '374053', '020050', '003869', '231082', '581011', '004899', '610481', '571040', '120611', '235811', '034152', '029070', '004929', '328365', '032375', '606075', '029363', '009275', '003719', '097143', '066966', '014480', '040452', '183785', '004714', '767895', '270346', '394757', '003924', '871234', '297706', '045713', '590866', '004730', '493529', '038182', '004569', '060768', '258443', '742151', '003200', '341553', '004396', '158501', '520403', '107358', '313158', '022301', '295292', '005124', '205356', '130230', '021799', '619506']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,N,STD (NON GCC),GCC,4.0,5TE,NX4CN9,A,Z,673290
1,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,N,1794 EDITION (NON GCC),GCC,4.0,5TF,NC5DBX,P,X,016486
2,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,N,STD (NON GCC),GCC,4.0,5TF,NX4CN8,B,X,008261
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,N,DLX,GCC,4.0,JAA,NHR55E,W,7,100214
4,TOYOTA,HIACE,4.0,PANEL VAN,N,GL,GCC,5.0,5TE,NX22N1,8,Z,586001
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,N,DLX,GCC,2.0,JTF,NG4260,3,0,005124
305,TOYOTA,RAV4,4.0,SUV,N,EX,GCC,5.0,JTM,NFREV9,J,J,205356
306,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,N,CREWMAX CAPSTONE (NON GCC),GCC,4.0,5TF,NA5DB7,R,X,130230
307,TOYOTA,TACOMA,4.0,PICKUP,N,STD (NON GCC),NON-GCC,NaN,5TF,NX4CN4,D,X,021799
308,TOYOTA,TACOMA,4.0,PICKUP,N,STD (NON GCC),NON-GCC,NaN,5TE,NX22N9,9,Z,619506

====================================================================================================
POS4: V
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', '4RUNNER', 'TUNDRA', 'LAND CRUISER', 'COROLLA', 'RAV4', 'TACOMA', 'TERCEL', 'CAMRY', 'YARIS', '2022', 'INNOVA', 'FJ CRUISER', 'FORTUNER', 'TACOMA (PICK UP)', 'HIACE']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'SEDAN', 'PICKUP', 'PICK UP', 'CARAVAN', 'PICK UP SINGLE CAB', 'MPV', 'PANEL VAN']
  pos4: ['V']
  trim: ['GL', 'TRD OFF-ROAD', '1794 EDITION (NON GCC)', 'EXR', 'XLI EXECUTIVE', 'GLX', 'ADVENTURE', 'DLX', 'STD (NON GCC)', 'STD', 'XLI', 'CREWMAX CAPSTONE (NON GCC)', 'SE', 'GLI', 'GXR TOP', 'DLS', 'BASE', 'LIMITED', 'DX', 'GLI HEV', 'TRIM', 'GLE-X HEV 40TH ANNIV', 'SE+']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JT4', 'JTE', '5TF', 'LFV', '5YF', 'AAP', '5TE', 'JTD', '4TA', 'LVA', '00N', 'MR2', 'JT5', 'LPS', 'LVB', 'W1W', '5AL', 'MHK', 'JT2']
  VDS: ['VD10A2', 'VA5BR3', 'VC5DB8', 'VB9E72', 'VPMAE4', 'V02912', 'VB9E79', 'VL52N2', 'VL52NX', 'VPMAE9', 'VB9E67', 'VPRAE0', 'VPMAE2', 'VC5DB7', 'V2MW50', 'VL52N6', 'VB9E60', 'V18044', 'VC5DB1', 'VP9F32', 'VN94T5', 'VAEDE1', 'VPMAE1', 'VD10A4', 'VJ73J1', 'VN52NX', 'V4JBB9', 'V2MWB7', 'VL52N7', 'VC5DB3', 'V0LEZ3', 'VP2863', 'V0LEZ4', 'VB9E61', 'VN61F2', 'VC5DB9', 'VN73K1', 'VC31F0', 'VB9E69', 'VC5DB2', 'VB9E73', 'VPMAE6', 'VL52N0', 'VN52N5', 'V3JBB3', 'VPMAE5', 'VC5DB6', 'VL52N5', 'VC5DB4', 'VN13G4', 'V4JBB7', 'VPMAE3', 'VK13E6', 'VPRAE8', 'VPMAE8', 'VD11E8']
  Model_Year: ['P', 'S', 'N', 'M', '6', '1', '4', 'X', 'L', 'R', '5', '7', 'E', '2', 'V', 'D', '3', 'F', 'W']
  Plant_Code: ['0', '5', 'X', 'P', 'Z', 'J', 'A', '1', 'L', 'Y', 'C', '3', 'H', 'K']
  Serial_Number: ['003744', '014259', '033917', '165724', '267978', '583414', '111254', '861491', '384409', '151597', '475255', '027684', '086534', '121129', '065804', '013819', '009977', '567897', '024639', '712345', '045006', '064184', '028282', '008259', '010474', '166983', '177094', '014843', '001138', '326951', '048704', '001429', '027363', '023795', '937952', '131435', '782513', '740401', '016940', '016708', '022007', '003402', '603399', '530874', '031833', '026017', '010188', '024694', '165814', '309858', '295012', '226661', '002171', '126265', '045690', '158639', '179560', '015237', '445628', '035444', '046764', '086171', '024755', '006113', '429090', '140157', '194999', '079805', '175342', '008043', '005251']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,V,GL,GCC,4.0,JT4,VD10A2,P,0,003744
1,TOYOTA,4RUNNER,4.0,SUV,V,TRD OFF-ROAD,GCC,5.0,JTE,VA5BR3,S,5,014259
2,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,V,1794 EDITION (NON GCC),GCC,4.0,5TF,VC5DB8,P,X,033917
3,TOYOTA,LAND CRUISER,6.0,SUV,V,EXR,GCC,5.0,LFV,VB9E72,N,5,165724
4,TOYOTA,COROLLA,4.0,SEDAN,V,XLI EXECUTIVE,GCC,4.0,5YF,VPMAE4,M,P,267978
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,TOYOTA,CAMRY,4.0,SEDAN,V,GLE-X HEV 40TH ANNIV,GCC,4.0,JT2,VK13E6,P,0,194999
67,TOYOTA,COROLLA,4.0,SEDAN,V,SE+,GCC,4.0,JTD,VPRAE8,L,J,079805
68,TOYOTA,COROLLA,4.0,SEDAN,V,XLI EXECUTIVE,GCC,4.0,JTD,VPMAE8,M,J,175342
69,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,V,STD (NON GCC),GCC,4.0,5TF,VC5DB6,N,X,008043
70,TOYOTA,HILUX,6.0,PICKUP,V,DLX,NON-GCC,NaN,JT4,VD11E8,S,0,005251

====================================================================================================
POS4: T
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'TACOMA', 'HILUX', 'CAMRY', 'COROLLA', 'TUNDRA', 'URBAN CRUISER', 'SALOON', 'GRAND DELUX', 'RAV4', 'STREET TRIPLE', 'LAND CRUISER']
  bodyType: ['PANEL VAN', 'PICKUP', 'PICK UP DOUBLE CAB', 'SEDAN', 'PICK UP', 'SUV', 'PICK UP SINGLE CAB', 'MINI BUS', 'MOTORCYCLE', 'SALOON']
  pos4: ['T']
  trim: ['GL', 'STANDARD', 'GLE-X HEV 40TH ANNIV', 'PICK UP', 'STD (NON GCC)', 'GLE HEV', 'DLX', 'GLX', 'GLE', 'XLI', 'DLX TOP', 'BASE', 'SE', 'DLS', 'DL', 'S', 'STD', 'GLS', 'LIMITED HEV', 'GLI', 'GRANDE HEV 40TH ANNIV', 'EXR', 'TRD']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JD4', '5TE', '5TF', '4T1', '5YF', 'MBJ', 'LRR', 'WMA', 'JTG', 'SCR', 'LJN', 'MHK', 'JT4', 'STE', 'LZY', 'SMT', '4TI', 'JTD', 'STF', '1V2', 'HA9']
  VDS: ['TV1828', 'TX22NX', 'TX4CN0', 'T11AK5', 'TX4CN5', 'T4MCEX', 'T11AK9', 'TX4CN7', 'TX22N0', 'TV1929', 'TMLA21', 'TEKP1X', 'TX22N1', 'T48ZZZ', 'TU4GN7', 'TX02P8', 'TX4CNX', 'TX22N7', 'TEB3NX', 'TFUC57', 'TFUC51', 'T11AK2', 'TFUC5X', 'TFUC50', 'T4RCE9', 'TW5F16', 'TX4CN4', 'TX22N3', 'TFU2K0', 'TX4CN2', 'TGUB23', 'TC31E9', 'TV092X', 'T11AK1', 'TN12DX', 'TC31E1', 'T11AKX', 'TX22N9', 'TX4CN1', 'TX4CN6', 'T36ZZZ', 'TX4CN8', 'TX22N8', 'T11BK9', 'TDTD69', 'T11AK4', 'TU62N8', 'TTL136', 'T11AK7', 'TLIAK4', 'T4MCE3', 'T4MCE8', 'TX4CN9', 'TY5F16', 'T4MCE1', 'T11AK3', 'T4RCE7', 'TY5F14', 'T11BK8', 'TX22N6', 'TR2CA1', 'TV0823', 'TX9A21', 'TU22N1', 'TY5F11', 'T147Y6', 'TX22N2', 'T4MCE5', 'TX4CN3', 'T11AK8', 'TN14DX']
  Model_Year: ['8', '9', 'F', 'P', 'A', 'R', 'N', '6', '7', '1', 'C', 'D', 'V', 'M', 'L', 'H', 'B', 'G', 'T', 'Y', 'S', 'E', '5', 'K', 'X']
  Plant_Code: ['1', 'Z', 'X', 'U', 'P', 'T', '6', 'M', '0', 'C', 'N', 'K', 'E', '3', 'J']
  Serial_Number: ['075693', '611583', '064112', '730114', '702713', '065227', '212343', '037480', '152566', '052426', '341678', '009755', '112027', '000037', '492126', '032795', '012214', '324595', '742357', '014835', '012675', '574944', '032691', '087512', '332554', '331903', '604613', '331916', '332430', '006886', '009510', '002331', '025584', '347779', '100592', '701343', '008280', '020918', '026177', '007958', '439539', '024895', '026786', '796139', '448678', '056231', '165200', '060310', '565857', '284991', '021200', '532986', '364030', '080539', '000084', '179561', '565877', '322148', '617240', '672827', '143435', '220886', '048981', '504981', '115189', '062620', '008149', '140526', '849623', '696357', '050427', '003716', '008409', '027651', '136539', '025571', '060590', '059537', '551024', '006631', 'MAN060', '810872', '048963', '201746', '744242', '010022', '019883', '511793', '872205', '295902', '006613', '055172', '057796', '555347', '427839', 'CS1882', '390896', '179404', '155112', '006756', '056120', '490911', '022775', '067251', '016079']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,PANEL VAN,T,GL,GCC,5.0,JD4,TV1828,8,1,075693
1,TOYOTA,TACOMA,4.0,PICKUP,T,STANDARD,GCC,NaN,5TE,TX22NX,9,Z,611583
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,T,GL,GCC,4.0,5TF,TX4CN0,F,X,064112
3,TOYOTA,CAMRY,4.0,SEDAN,T,GLE-X HEV 40TH ANNIV,GCC,4.0,4T1,T11AK5,P,U,730114
4,TOYOTA,TACOMA,4.0,PICK UP DOUBLE CAB,T,PICK UP,GCC,2.0,5TE,TX4CN5,A,Z,702713
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,T,GL,GCC,4.0,5TF,TX4CN3,F,X,056120
104,TOYOTA,CAMRY,4.0,SEDAN,T,S,GCC,4.0,4T1,T11AK8,M,U,490911
105,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,T,DLX TOP,GCC,2.0,5TF,TX4CN7,D,X,022775
106,TOYOTA,CAMRY,4.0,SEDAN,T,GLE HEV,GCC,4.0,4T1,T11AK1,N,U,067251
107,TOYOTA,TACOMA,6.0,PICKUP,T,TRD,NON-GCC,NaN,JT4,TN14DX,T,0,016079

====================================================================================================
POS4: 2
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['SIENNA', 'HIACE', 'FJ CRUISER', 'RAV4', 'AVALON', 'WISH', 'HILUX', 'COROLLA', 'AURION', 'SEQUOIA', 'RAV 4', 'LAND CRUISER', 'CAMRY', '4RUNNER', 'PRADO', 'FORTUNER', 'YARIS']
  bodyType: ['MPV', 'PANEL VAN', 'SUV', 'SEDAN', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'VAN', 'STATION', 'PICK UP SINGLE CAB']
  pos4: ['2']
  trim: ['LE (NON GCC)', 'GL', 'GXR', 'STD', 'XLE (NON GCC)', 'STD (NON GCC)', 'EXR', 'LIMITED PREMIUM', 'VX', 'ADVENTURE', 'XLI', 'MID', 'GG', 'EX', 'LIMITED 4X2', 'DLX', 'LIMITED MID', 'VXR', 'GX', 'GLI TOP', 'GLI', 'SR5 (NON GCC)', 'LIMITED', 'SE+', 'TX-L', 'BE', 'GLX', 'VX TOP LTH']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TD', 'D04', 'ZGE', 'JT4', 'JTM', 'WDD', 'JTB', 'JTD', 'UAE', '2T3', 'WV1', 'MC2', '8LT', 'MD6', 'JTE', 'WMA', '1G0', '174', '5ZT', 'AS3', 'J10']
  VDS: ['2A22C1', '2K3DC3', '2757DX', '216106', '2A1190', '2A23CX', '2K23C0', '2K23C3', '2K31V6', '2FREV0', '222066', '21UHB3', '2A23C8', '2A22C9', '2F9EV5', '2F9EV4', '2K23CX', '2A22C3', '213FV5', '216049', '2K3DC4', '2S0125', '2K23C9', '216067', '2K23C2', '2K23C4', '2K31V4', '2K22C9', '2F9EV9', '2A22C8', '213FV1', '2K29C6', '2A22C5', '2K31V7', '2F9EV1', '2Y68A4', '2K23C1', '216041', '2A23C7', '2FREV8', '2882K7', '2A23C6', '2F33V5', '213FV9', '2K22CX', '2Y64AX', '21FCL5', '2K31V1', '2K23C8', '2EFV4M', '2K23C6', '2A23C5', '21UJ70', '2A29C2', '213FV8', '26BG7X', '216035', '2T14R7', '2F9EV7', '21SZZ5', '216086', '216088', '2A23C3', '2K23C5', '2A1197', '2FREV2', '216081', '216054', '2F9EV6', '2HNAG2', '2K22C6', '210906', '216087', '2A22CX', '2K22C3', '2SBPB2', '2A23C2', '2U14RX', '2K33V7', '216023', '2S0107', '2A29C5', '2F9EV0', '2R1197', '21AS32', '2K23C7', '2T38A8', '2FREV9', '2S0117', '213FV3', '2K29C4', '2A1192', '2FREV7', '222058']
  Model_Year: ['4', 'D', 'B', '9', 'X', '5', '7', '8', 'E', '1', 'V', 'W', 'H', 'J', 'L', 'C', 'A', 'F', '3', 'P', '6', 'N', 'G', 'R', 'Y']
  Plant_Code: ['5', '0', 'S', 'J', 'A', 'D', '4', '2', '8', 'W', 'X', '1', '3', '6', '7', 'L', '9']
  Serial_Number: ['142383', '395754', '000000', '011111', '032139', '235287', '269158', '014727', '018546', '003643', '342404', '024164', '029657', '029845', '036327', '148360', '027802', '174972', '127708', '172029', '210487', '258459', '051306', '556789', '184559', '108490', '187259', '027480', '278344', '600000', '167732', '025953', '107578', '021770', '289186', '003801', '029854', '307105', '500000', '111927', '010307', '578138', '001987', '103594', '285927', '018796', '026913', '015479', '025493', '278306', '284480', '511111', '026662', '009562', '381909', '001271', '210742', '003237', '128211', '093153', '039458', '029498', '026308', '142791', '007307', '231466', 'BVTASY', '396843', '187761', '278537', '181942', '389620', '002876', '280053', '491994', '095075', 'AB3026', '800000', '014718', '017228', '071869', '300000', '400000', '440838', '185917', '004191', '453970', '420236', '275298', '213181', '198858', '534912', '023918', '070991', '6HGKKA', '349296', '032494', '322693', '025474', '184725', '525646', '200000', '235999', '133400', '035796', '029869', '086159', '026889', '010869', '034110', '519757', '055663', '268073', '027180', '011492', 'S22323', '109339', '080562', '016882', '168239', '002457', '037390', '129113', '116191', '035948', '012808', '121816', '422881']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,SIENNA,6.0,MPV,2,LE (NON GCC),GCC,5.0,5TD,2A22C1,4,5,142383
1,TOYOTA,SIENNA,6.0,MPV,2,LE (NON GCC),GCC,5.0,5TD,2K3DC3,D,5,395754
2,TOYOTA,HIACE,4.0,PANEL VAN,2,GL,NON-GCC,NaN,D04,2757DX,B,0,000000
3,TOYOTA,SIENNA,6.0,MPV,2,LE (NON GCC),GCC,5.0,5TD,2K3DC3,D,S,395754
4,TOYOTA,FJ CRUISER,6.0,SUV,2,GXR,NON-GCC,NaN,ZGE,216106,9,0,011111
...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,TOYOTA,HIACE,4.0,PANEL VAN,2,STD,GCC,5.0,JT4,2A1192,Y,0,035948
141,TOYOTA,SIENNA,6.0,MPV,2,LE (NON GCC),GCC,5.0,5TD,2A23C2,4,S,086159
142,TOYOTA,RAV4,4.0,SUV,2,GX,GCC,5.0,2T3,2FREV7,D,W,012808
143,TOYOTA,RAV4,4.0,SUV,2,VX,GCC,5.0,JTM,2FREV8,H,J,121816
144,TOYOTA,CAMRY,4.0,SEDAN,2,GLI,GCC,4.0,WDD,222058,1,A,422881

====================================================================================================
POS4: 4
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COASTER', 'HIACE', 'CAMRY', 'COROLLA', 'HILUX', 'TUNDRA', 'LAND CRUISER', 'SEQUOIA', 'PREVIA', 'AVALON']
  bodyType: ['BUS', 'PANEL VAN', 'SEDAN', 'PICK UP DOUBLE CAB', 'SUV', 'MINI BUS', 'MPV']
  pos4: ['4']
  trim: ['STD', 'LIMITED HEV', 'GL', 'SE', 'DL', 'XLI', 'STD (NON GCC)', 'GLI', 'GXR', 'DX H/R W/B', 'GLX', 'SR5 4X4', 'SAFARI', 'SWB', 'DLX', 'S', 'GLE', 'LIMITED']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTB', 'LA6', 'ACV', 'MAT', 'NCP', '090', '074', 'GGG', 'LDP']
  VDS: ['41UB50', '41UHB5', '41CB81', '415020', '449253', '464054', '420141', '405038', '464703', '449252', '405034', '415002', '420156', '415036', '415014', '405002', '415013', '408B06', '415033', '472AXD', '405006', '415010', '464753', '415029', '41BB42', '415017', '405009', '415030', '464072', '415001', '456123', '420101', '41E969', '420184']
  Model_Year: ['W', 'T', '7', 'G', 'D', '5', '6', 'H', '2', '9', '8', 'S', '4', '3', 'B']
  Plant_Code: ['7', '0', 'B', '5', 'S', '1', '4', '2', '6', '3', '8', '9', 'D']
  Serial_Number: ['000125', '004974', '400120', '004250', '4     ', 'L02040', 'L01527', '000000', 'L00428', 'L02068', '300000', 'L01132', '400000', '811111', '6W0000', '111111', '0448PN', 'L00163', '4TDBY5', '600000', '011111', 'L01292', '000351', '005862', 'L01068', '900000', '100000', '211111', 'L01334', '005657', '555555', '792000', '117893']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COASTER,6.0,BUS,4,STD,GCC,2.0,JTB,41UB50,W,7,000125
1,TOYOTA,HIACE,4.0,PANEL VAN,4,STD,GCC,5.0,JTB,41UHB5,W,0,004974
2,TOYOTA,CAMRY,4.0,SEDAN,4,LIMITED HEV,GCC,NaN,LA6,41CB81,T,B,400120
3,TOYOTA,HIACE,4.0,PANEL VAN,4,STD,GCC,5.0,JTB,41UHB5,W,0,004250
4,TOYOTA,CAMRY,4.0,SEDAN,4,GL,GCC,NaN,ACV,415020,7,5,4
5,TOYOTA,COROLLA,4.0,SEDAN,4,SE,GCC,NaN,MAT,449253,G,0,L02040
6,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,4,DL,GCC,4.0,MAT,464054,D,S,L01527
7,TOYOTA,COROLLA,4.0,SEDAN,4,XLI,NON-GCC,NaN,NCP,420141,7,7,000000
8,TOYOTA,CAMRY,4.0,SEDAN,4,GL,GCC,NaN,ACV,405038,5,1,000000
9,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,4,STD (NON GCC),GCC,4.0,MAT,464703,G,S,L00428
10,TOYOTA,COASTER,6.0,BUS,4,DL,GCC,2.0,MAT,449252,G,0,L02068
11,TOYOTA,CAMRY,4.0,SEDAN,4,GLI,GCC,NaN,ACV,405034,6,5,300000
12,TOYOTA,LAND CRUISER,8.0,SUV,4,GXR,GCC,NaN,MAT,449252,H,0,L01132
13,TOYOTA,CAMRY,4.0,SEDAN,4,GLI,NON-GCC,NaN,ACV,415002,2,1,400000
14,TOYOTA,HIACE,3.0,MINI BUS,4,DX H/R W/B,NON-GCC,NaN,NCP,420156,7,4,300000
15,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415036,9,2,811111
16,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415014,8,4,400000
17,TOYOTA,CAMRY,4.0,SEDAN,4,GLI,GCC,NaN,ACV,405002,2,1,6W0000
18,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415013,9,6,111111
19,TOYOTA,LAND CRUISER,8.0,SUV,4,GXR,GCC,5.0,090,408B06,5,7,0448PN
20,TOYOTA,COROLLA,4.0,SEDAN,4,SE,GCC,NaN,MAT,464703,G,S,L00163
21,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415033,6,1,300000
22,TOYOTA,SEQUOIA,8.0,SUV,4,SR5 4X4,GCC,5.0,074,472AXD,S,6,4TDBY5
23,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,GCC,NaN,ACV,405006,7,3,600000
24,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415010,4,8,011111
25,TOYOTA,LAND CRUISER,4.0,SUV,4,SAFARI,GCC,NaN,MAT,464753,H,S,L01292
26,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415029,4,9,000000
27,TOYOTA,COASTER,6.0,BUS,4,STD,GCC,2.0,JTB,41BB42,W,5,000351
28,TOYOTA,HIACE,4.0,PANEL VAN,4,STD,GCC,5.0,JTB,41UHB5,W,0,005862
29,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415017,6,3,600000
30,TOYOTA,COASTER,4.0,BUS,4,SWB,GCC,NaN,MAT,449252,H,0,L01068
31,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,405009,3,2,900000
32,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415014,9,4,100000
33,TOYOTA,CAMRY,4.0,SEDAN,4,GLX,NON-GCC,NaN,ACV,415030,8,1,211111
34,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,4,DLX,GCC,NaN,MAT,464072,B,S,L01334
35,TOYOTA,HIACE,4.0,PANEL VAN,4,STD,GCC,5.0,JTB,41UHB5,W,0,005657
36,TOYOTA,CAMRY,4.0,SEDAN,4,XLI,NON-GCC,NaN,ACV,415001,5,8,900000
37,TOYOTA,COROLLA,4.0,SEDAN,4,XLI,GCC,NaN,GGG,456123,6,5,555555
38,TOYOTA,PREVIA,4.0,MPV,4,S,GCC,NaN,NCP,420101,6,1,792000
39,TOYOTA,CAMRY,4.0,SEDAN,4,GLE,GCC,NaN,LDP,41E969,T,D,117893
40,TOYOTA,AVALON,6.0,SEDAN,4,LIMITED,NON-GCC,NaN,NCP,420184,5,9,011111

====================================================================================================
POS4: 0
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'PREVIA', 'YARIS', 'HIACE', 'COROLLA', 'KS01', 'CAMRY', 'LAND CRUISER', 'TUNDRA']
  bodyType: ['PICK UP DOUBLE CAB', 'MPV', 'HATCHBACK', 'MINI BUS', 'PICK UP SINGLE CAB', 'SEDAN', 'STATION', 'SUV']
  pos4: ['0']
  trim: ['DL', 'DLX', 'MID', 'DX', 'XLI', 'XLI TOP', 'EX', 'BASE', 'GLX', 'GX', 'GL2', 'VXR', 'FLEET', 'STD (NON GCC)', 'STD', 'S', 'XLI EXECUTIVE']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['KN9', 'UP1', '000', 'WMA', 'MR0', 'LHA', 'FJ4', 'EE1', 'MET', 'WB1', '425', 'STF', 'JMY', 'EL5', 'JTB', 'GX9', 'AE1']
  VDS: ['0J4MCD', '007130', '00NCP9', '06XZZ1', '0X22G9', '000NNN', '008004', '022GD1', '002606', '006121', '008567', '022906', '004046', '0000EA', '0B9CB0', '011111', '042TN9', '000NCP', '009432', '008983', '0YSF10', '009687', '010356', '0RV430', '033500', '000983', '01BUM1', '066223', '013026', '0000JA', '06XZZX']
  Model_Year: ['E', '4', '1', 'A', 'B', 'N', '3', 'R', '9', '8', 'W', 'P', 'L', '2', '5', 'H', '7', 'X']
  Plant_Code: ['K', '0', '9', 'P', 'N', 'B', '5', '4', '3', '7', 'J', '1', '8', 'X', '6', '2', 'A', 'W']
  Serial_Number: ['Z00064', '000000', '097501', '020763', '008234', '111111', '007135', '565555', 'WTHJUN', '154789', '200000', '021915', '971081', 'NTGUCY', '900255', '585855', '654703', '003154', '234567', 'RTUK14', '500035', '024461', '127148']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,0,DL,GCC,4.0,KN9,0J4MCD,E,K,Z00064
1,TOYOTA,PREVIA,4.0,MPV,0,DLX,NON-GCC,NaN,UP1,007130,4,0,000000
2,TOYOTA,YARIS,4.0,HATCHBACK,0,MID,NON-GCC,NaN,000,00NCP9,1,9,097501
3,TOYOTA,HIACE,4.0,MINI BUS,0,DX,NON-GCC,NaN,WMA,06XZZ1,A,P,020763
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,0,DLX,GCC,2.0,MR0,0X22G9,B,0,008234
5,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,NON-GCC,NaN,000,000NNN,N,N,111111
6,TOYOTA,COROLLA,4.0,SEDAN,0,XLI TOP,NON-GCC,NaN,UP1,008004,3,0,000000
7,TOYOTA,KS01,0.0,STATION,0,EX,GCC,NaN,LHA,022GD1,R,B,007135
8,TOYOTA,YARIS,4.0,SEDAN,0,BASE,NON-GCC,NaN,UP1,002606,9,0,000000
9,TOYOTA,CAMRY,4.0,SEDAN,0,GLX,NON-GCC,NaN,UP1,006121,4,5,565555
10,TOYOTA,YARIS,4.0,SEDAN,0,BASE,GCC,NaN,UP1,008567,8,4,WTHJUN
11,TOYOTA,LAND CRUISER,6.0,STATION,0,GX,GCC,NaN,FJ4,022906,3,3,154789
12,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,GCC,NaN,EE1,004046,9,7,200000
13,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,GCC,4.0,MET,0000EA,W,J,021915
14,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,0,GL2,GCC,4.0,MR0,0B9CB0,P,4,971081
15,TOYOTA,CAMRY,4.0,SEDAN,0,GLX,NON-GCC,NaN,WB1,011111,1,1,111111
16,TOYOTA,LAND CRUISER,6.0,SUV,0,VXR,GCC,NaN,425,042TN9,L,J,NTGUCY
17,TOYOTA,YARIS,4.0,SEDAN,0,FLEET,NON-GCC,NaN,000,000NCP,9,1,900255
18,TOYOTA,YARIS,4.0,HATCHBACK,0,BASE,GCC,NaN,UP1,009432,2,1,111111
19,TOYOTA,YARIS,4.0,SEDAN,0,FLEET,GCC,NaN,UP1,008983,5,8,585855
20,TOYOTA,TUNDRA,4.0,PICK UP DOUBLE CAB,0,STD (NON GCC),GCC,NaN,STF,0YSF10,H,X,654703
21,TOYOTA,PREVIA,4.0,MPV,0,DLX,NON-GCC,NaN,UP1,009687,2,0,000000
22,TOYOTA,YARIS,4.0,HATCHBACK,0,BASE,GCC,NaN,UP1,010356,7,0,000000
23,TOYOTA,LAND CRUISER,6.0,SUV,0,GX,GCC,5.0,JMY,0RV430,X,J,003154
24,TOYOTA,LAND CRUISER,8.0,SUV,0,GX,GCC,NaN,FJ4,033500,2,1,234567
25,TOYOTA,CAMRY,4.0,SEDAN,0,STD,GCC,NaN,EL5,000983,9,3,RTUK14
26,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,0,STD,GCC,NaN,JTB,01BUM1,W,6,500035
27,TOYOTA,CAMRY,4.0,SEDAN,0,S,GCC,NaN,GX9,066223,8,1,000000
28,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,GCC,NaN,AE1,013026,9,2,200000
29,TOYOTA,COROLLA,4.0,SEDAN,0,XLI EXECUTIVE,GCC,NaN,MET,0000JA,5,A,024461
30,TOYOTA,COROLLA,4.0,SEDAN,0,XLI,NON-GCC,NaN,WMA,06XZZX,9,W,127148

====================================================================================================
POS4: I
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'LAND CRUISER', 'PRADO']
  bodyType: ['PANEL VAN', 'SUV']
  pos4: ['I']
  trim: ['STD', 'GX', 'TX-L']
  regionalSpec: ['GCC']
  WMI: ['JTF', 'JTB', 'JTE']
  VDS: ['IX02P5', 'ITUJ80', 'IUSFI6']
  Model_Year: ['5', 'V', 'C']
  Plant_Code: ['0', '6', 'S']
  Serial_Number: ['002107', '008396', '032693']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,PANEL VAN,I,STD,GCC,5.0,JTF,IX02P5,5,0,002107
1,TOYOTA,LAND CRUISER,6.0,SUV,I,GX,GCC,5.0,JTB,ITUJ80,V,6,008396
2,TOYOTA,PRADO,4.0,SUV,I,TX-L,GCC,5.0,JTE,IUSFI6,C,S,032693

====================================================================================================
POS4: 9
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'COROLLA', 'CAMRY', 'HIACE', '2014', 'HILUX']
  bodyType: ['HATCHBACK', 'COUPE', 'SEDAN', 'PANEL VAN', 'PICK UP', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB']
  pos4: ['9']
  trim: ['BASE', 'XLI', 'XLI TOP', 'MID', 'GL', 'FLEET', 'DX', 'GC', 'DLX']
  regionalSpec: ['NON-GCC', 'GCC']
  WMI: ['NCP', 'WAU', 'WDB', 'MR2', '180']
  VDS: ['919017', '9FD8TX', '919002', '919032', '919021', '919014', '944032', '919035', '919085', '906155', '919012', '9T9F34', '93220N', '950213', '919023', '954033', '954032']
  Model_Year: ['7', 'A', '8', '1', '5', '9', 'V', '4']
  Plant_Code: ['5', 'A', '7', '4', '3', 'K', 'N', '0', '8', '1', '2', 'L']
  Serial_Number: ['465181', '067905', '300000', '455555', '900000', '500000', '869849', '411111', '327369', '600000', '092606', '000000', '262691', '811111', '752850', '006204', '009490', '133452', '402549']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,NON-GCC,NaN,NCP,919017,7,5,465181
1,TOYOTA,COROLLA,4.0,COUPE,9,XLI,GCC,2.0,WAU,9FD8TX,A,A,067905
2,TOYOTA,YARIS,4.0,SEDAN,9,BASE,NON-GCC,NaN,NCP,919002,8,7,300000
3,TOYOTA,COROLLA,4.0,SEDAN,9,XLI TOP,GCC,NaN,NCP,919032,1,4,455555
4,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,NON-GCC,NaN,NCP,919017,7,5,900000
5,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,NON-GCC,NaN,NCP,919021,5,3,500000
6,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,NON-GCC,NaN,NCP,919014,8,4,500000
7,TOYOTA,CAMRY,4.0,SEDAN,9,GL,GCC,4.0,WDB,944032,1,K,869849
8,TOYOTA,YARIS,4.0,HATCHBACK,9,BASE,NON-GCC,NaN,NCP,919035,1,7,411111
9,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,NON-GCC,NaN,NCP,919085,5,3,411111
10,TOYOTA,YARIS,4.0,SEDAN,9,FLEET,NON-GCC,NaN,NCP,919021,7,3,500000
11,TOYOTA,HIACE,4.0,PANEL VAN,9,DX,GCC,NaN,WDB,906155,1,N,327369
12,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,NON-GCC,NaN,NCP,919012,9,0,600000
13,TOYOTA,YARIS,4.0,SEDAN,9,BASE,NON-GCC,NaN,NCP,919017,5,8,900000
14,TOYOTA,2014,4.0,SEDAN,9,GC,GCC,NaN,MR2,9T9F34,8,1,092606
15,TOYOTA,CAMRY,4.0,SEDAN,9,XLI,NON-GCC,NaN,180,93220N,V,0,000000
16,TOYOTA,HILUX,4.0,PICK UP,9,DLX,GCC,NaN,WDB,950213,1,K,262691
17,TOYOTA,YARIS,4.0,SEDAN,9,FLEET,GCC,NaN,NCP,919023,4,2,811111
18,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,9,DLX,GCC,NaN,WDB,954033,1,K,752850
19,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,9,DLX,GCC,NaN,WDB,944032,1,L,006204
20,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,9,DLX,GCC,NaN,WDB,944032,1,L,009490
21,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,9,DLX,GCC,NaN,WDB,944032,1,L,133452
22,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,NON-GCC,NaN,WDB,954032,1,K,402549

In [198]:
print(data['pos5'].unique())

['B' 'X' 'G' 'T' 'W' 'R' 'U' 'D' 'F' 'E' 'Z' 'V' 'K' '2' 'L' 'N' 'A' '1'
 '3' 'C' 'J' 'H' 'Y' '5' 'M' '4' '6' 'P' '0' '8' '9' 'S' '7' 'I']

In [199]:
from IPython.display import display

for pos_5 in data['pos5'].dropna().unique():

    # 1. Filter the DataFrame for the current pos5 value
    filtered_df_pos5 = data.loc[
        data['pos5'] == pos_5,
        ['make', 'model', 'cylinders', 'bodyType', 'pos4', 'trim',  'regionalSpec', 'noOfDoors','WMI', 'VDS', 'Model_Year', 'Plant_Code','Serial_Number']
    ].reset_index(drop=True)

    # 2. Header for the current pos5 group
    print("\n" + "=" * 100)
    print(f"pos5: {pos_5}")
    print("=" * 100)

    # 3. Print unique values for all object columns (except pos5)
    print("--- Unique Values for Object Columns ---")
    object_cols = filtered_df_pos5.select_dtypes(include=['object']).columns
    
    for col in object_cols:
        if col != ['pos5', 'VDS']:
            unique_vals = filtered_df_pos5[col].dropna().unique()
            print(f"  {col}: {list(unique_vals)}")
            
    print("-" * 100)

    # 4. Display the filtered DataFrame
    display(filtered_df_pos5)

====================================================================================================
pos5: B
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'PRIUS', 'LAND CRUISER', 'HILUX', 'SUPRA', 'VELOZ', 'RAIZE', 'TUNDRA', 'HIGHLANDER', 'CAMRY', 'INNOVA', 'COASTER', 'TOYOTA VELOZ', 'HIACE', 'LAND CRUISER PICK UP', 'SIENNA', 'COROLLA 1.3', 'TOYOTA COROLLA', 'FORTUNER', 'RAV4', 'COROLLA 1.6', 'COROLLA CROSS', 'PICK UP', 'TACOMA', '25 HX DC 4X4D 2.4LAT', 'كورولا 1.8', 'TOYOTA COROLLA 1.6', '1999', 'AVALON', 'COROLLA SEDAN', 'YARIS', '4RUNNER', 'SUPRA COUPE', '2 HX DC 4X40', 'PRADO', '26HX DC 4X4D2.4L AT', '26 HX DC 4X4 2.4LAT', '26HX DC 4X4 D2.4LAT', '26 HX DC 4X4 D 2.4L AT', 'TOYOTA - 26 HX DC 4X4 D 2.4L AT', '25 HX DC 4X4', 'DLX FA (PICK UP)', 'KING LONG PASSENGER', 'HX DC 4X4 D 2.4L AT', '26 HX DC 4X4D', 'LAND CRUISER PICK UP CARGO', 'H 530', 'SOLARA', 'LAND CRUISER PICKUP 70', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'HATCHBACK', 'SUV', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'COUPE', 'PICKUP', 'MPV', 'BUS', 'STATION', 'MINI BUS', 'PICK UP', 'SALOON', 'PANEL VAN', 'SUV- CROSSOVER', 'MINI BUS HIGH ROOF', 'LIGHT VEHICLE', 'PICKUP DOUBLE CAB', 'CONVERTIBLE']
  pos4: ['B', 'K', 'A', 'D', 'L', 'F', 'Z', 'E', 'P', 'G', 'R', 'H', 'V', 'J', 'C', 'U', '8', 'N', '1', 'X', 'W', 'S', '0', 'Y', '3']
  trim: ['SE', 'ICONIC', 'GXR', 'GL2', 'SGLX', 'VXR', 'GR', 'XLI RB', 'XLI', 'GX', 'E', 'STD (NON GCC)', 'GLI HEV', 'GLX', 'GLI', 'CREWMAX CAPSTONE (NON GCC)', 'BLACK EDITION', 'DLX', 'ECO', 'GXR2', 'XLI MID', 'GL', 'HEV', 'GR SPORT', 'SWB', 'GR TAN EDITION', 'LWB', 'LE', 'SE+', 'GXR1', 'GR-S', 'GR BLUE EDITION', 'DX', 'STD', 'LIMITED TRD SPORT PK', 'VX', 'LE HEV', 'XLE', 'XLT', 'GXR TOP DMST', 'GXR TOP 60TH ANNIV. XTREME', 'GLE HEV BLACK EDITION', 'GXR TOP', 'XLE (NON GCC)', 'GT SPORT', 'LWB HIGH ROOF', 'EXR', 'DL', 'L', 'VX2', 'DLS', 'ADVENTURE', 'SEDAN', 'DYNAMIC', 'PLATINUM', 'GLE HEV', 'GXR-V', '2.0L', '25HX', 'SR5 (NON GCC)', 'LIMITED', 'S', 'VXR BASE', 'S TRD SPORT PK', 'HYCROSS', 'SLD', 'TURBO G RA', 'GLS', 'XL', 'EX', 'LIMITED TRD AERO PK', 'C', 'GLE', '60TH', 'USF', 'XLI EXECUTIVE', 'VIP7', 'XLI EXECUTIVE HEV', 'TRD', 'GLI TOP', '1794 EDITION (NON GCC)', 'MID', 'BASE', 'ASD', 'CAR TRIM', 'SL', '2', 'G', 'VX1', 'STANDARD', 'ST', 'FLEET', 'GXR FMST', 'LX', '1', 'GXR4']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['RKL', 'JTD', 'JTM', 'MRO', 'MR0', 'WZ1', 'MHF', 'MHK', 'JTE', '5TF', '5TD', 'JT2', 'JTN', '4T1', 'JTG', 'WV1', '1NX', '2T1', 'MB1', 'JTF', 'LFV', 'LZW', '5TT', '7MU', '3TM', 'JAC', 'NMT', 'JTZ', 'LSC', 'MYN', 'LVV', 'JE3', 'JN1', '3TY', 'WZI', 'LSG', 'RA6', 'JT3', 'JT4', '1ST', 'LGW', 'MBI', '471', 'VF3', 'JTR', 'LA6', 'WV2', 'LKL', 'JT6', 'JL7', 'LVM', 'HJR', 'LSY', 'JHF', 'JIN', 'MFF', 'HJ4', 'K20', 'JTJ']
  VDS: ['BB9HE7', 'KB3FUO', 'ABBBJ0', 'DB9CD3', 'KB8CD7', 'KB3FU0', 'BB9HE9', 'AB7BJ0', 'AB7BJX', 'KB8CD0', 'DB0E04', 'ABBBJ3', 'BB0BE5', 'AB7BJ6', 'BB9HE2', 'AB1BY2', 'BB9HE4', 'KB8CD4', 'BB9HE0', 'BB0BE3', 'AB1BAX', 'BB42E6', 'BB0BE2', 'BB9HE8', 'BB0BE6', 'KB8CD2', 'AB7BJ7', 'BB0BE0', 'BB9HE6', 'AB1BA5', 'AB1BY1', 'BB71J0', 'BB42E4', 'AB7BJ5', 'BBOBE8', 'AB7BJ3', 'BB9HE5', 'KB5DB5', 'AB7BJ4', 'KB8CD8', 'ABBBJ6', 'BB9HEX', 'BB42E0', 'KB8CD3', 'BB0BE7', 'ABBBJX', 'ABBBJ9', 'ABCBJ8', 'LB3CH8', 'ABBBJ2', 'AB1BA9', 'BB9HE1', 'BB0CE3', 'AB1BY3', 'AB7BJ2', 'KB8CD5', 'LB3CHX', 'KB3FU5', 'LB3CH0', 'BB9HE3', 'ABBBJ7', 'DB0E05', 'KB20U3', 'ABCBJX', 'BB13E5', 'BB46K2', 'AB1BY5', 'DB0A07', 'BB0BE8', 'AB7BJ8', 'ABBAAX', 'KB8CDX', 'ABBBJ1', 'AB7BJ9', 'LB3CH5', 'KB20U7', 'BB0BEX', 'BB42E9', 'AB1BY0', 'KBRFU2', 'AB1BY6', 'BBOBE1', 'BB42E1', 'BB0CE2', 'BB42EX', 'KB3FUX', 'AB1BY4', 'DB9CD6', 'DB0E03', 'DBSCD6', 'ABBBJ4', 'ABCBJ1', 'BB46K0', 'AB1BA4', 'BB42E2', 'BB46K5', 'BB42E8', 'DB4A05', 'KB3FU3', 'AB1BA2', 'BB0BE1', 'ABBBJ8', 'KB8CD9', 'ABBBJ5', 'FB5188', 'BB46K1', 'ZBB2K2', 'KB3FU9', 'KB20U4', 'AB1BA6', 'DB0E08', 'DB0E01', 'AB1BY9', 'BB0CE6', 'AB7BJ1', 'BBOBE9', 'EB13E1', 'FB5185', 'LB3CH1', 'BB42E7', 'KB3FU2', 'EBRBE3', 'DB9CD7', 'BB0BEO', 'LB3CH9', 'BB0BE4', 'BB46K9', 'KB8CD1', 'AB7BJS', 'BB0CE7', 'LB3CH6', 'KB20U9', 'AB1BY8', 'BB46KX', 'DB4C04', 'BB0CEX', 'ABIBY7', 'AB1BY7', 'KB8CD6', 'KB3FU6', 'KB3FU1', 'KBBCD8', 'EBRBE1', 'LB3CH3', 'BB0BEG', 'DB0E07', 'BB0BE9', 'BB0CE9', 'DB4C07', 'AB1BA3', 'ABCBJ3', 'FB5181', 'BB02E1', 'BB42E3', 'BB0CE1', 'ABCBJ4', 'BB02E4', 'AB1BA1', 'BB0CE8', 'KB20U5', 'BB3EKX', 'BB0CE0', 'BB02E3', 'DB4A09', 'BB02E9', 'BB46K3', 'DB9CDO', 'PBEJA1', 'DB9CD0', 'BB46K4', 'LB71J3', 'ABCBJ5', 'LB3CH2', 'FB5187', 'BBOBEI', 'DB9CD8', 'DB9CD9', 'DB0E09', 'BB42E5', 'DBADK5', 'GBRCH3', 'BB46K8', 'ABBBJO', 'AB1BYX', 'BB3EK1', 'BB46K6', 'BB46K7', 'LB71J5', 'ABBAA6', 'DB12E9', 'DB9CD5', 'DB0A04', 'KB3FU7', 'AB1BA0', 'RB71J7', 'KB20UX', 'BB02E8', 'BB02E7', 'HB8CD2', 'ABBAA7', 'DB4A04', 'ABBAA8', 'AB1BA8', 'ABCBJ7', 'EB73J5', 'EB73J9', 'DB0A03', 'BB9HEO', 'BB12E6', 'DB0E06', 'BB02E2', 'EBRBE7', 'BB0CE5', 'HB9CP5', 'BB02EX', 'DBZSV3', 'ABBBJI', 'DB9CD2', 'BBOCEO', 'LB71J8', 'BB0CE4', 'LB3CH7', 'AB1BYO', 'ABBAA5', 'KBRFU9', 'BB12E7', 'DB2C03', 'BB02E5', 'FB5182', 'LB3CH4', 'FB5183', 'ABBAA9', 'BB0BET', 'VB9E72', 'JB6CD8', 'EBOBEO', 'EB0BE0', 'FB518X', 'ABCBJ6', 'DB0E0X', 'CBAGA2', 'KB8FS0', 'DB4A08', 'ABCBJ0', 'BBOCE8', 'VB9E79', 'DB9CDX', 'BBOBE7', 'EB02E2', 'FB5184', 'FBW415', 'BB3EK6', 'BB3EK5', 'PBEJA3', 'BBOCE7', 'KB20U2', 'DB4A01', 'EB71J9', 'EBRCH5', 'BB12E5', 'DB8CD2', 'DB9CD4', 'EBRBE4', 'ABCBJ2', 'EB13EX', 'KB3FU8', 'KB3FU4', 'HB9CP1', 'ABBAA2', 'BB13E3', 'EBRBE5', 'DB0E02', 'RB71J0', 'FBABG3', 'RB71JO', 'LB71J4', 'DB0A06', 'AB1BA7', 'KB5DA2', 'KBRFU8', 'BBOBE6', 'BB3EK0', 'GBRCH8', 'BB3EKO', 'PBEJA5', 'EBRBE2', 'DB8CD0', 'BBOBE2', 'ABBAA1', 'DB9CB0', 'BB02E0', 'BB0BES', 'LB5JN8', 'KBRFU6', 'FB5180', 'BB9HES', 'ABCBJ9', 'RB71J6', 'DB0E00', 'EB73J4', 'UBS25G', 'VB9E67', 'AB7BJO', 'RB71J9', 'BB9JE6', 'KBRFU4', 'DB6CD5', 'RB71J8', 'EB02E1', 'EB13E5', 'BBRCH7', 'BB02E6', 'EB13E3', 'ABBAA0', 'BBOBE4', '8B9HE9', 'CB09J3', 'BB3EK2', 'KB5DA7', 'DB4C03', 'ABBAA4', 'DB9CB2', 'LB3CHO', 'KB9CP0', 'BBOBE5', 'PBEJA0', 'FB5186', 'ABBAA3', 'DB4A03', 'CBAGA6', 'VB9E60', 'BB3EK8', 'KB20U6', 'BB9HEI', 'DB0A09', 'DB9CB6', 'DB9CBX', 'KBRFU7', 'BB13E2', 'BBOBE3', 'LB5JN2', 'DB0G02', 'KBRFU5', 'DB9CB5', 'DB9CB9', 'DB9CD1', 'KBRFU1', 'DB8FS6', 'DB8FS4', 'KB20U8', 'DB0A0X', 'DB6CD2', 'EB13E4', 'RB71J2', 'HB9CP2', 'BBN2A2', 'LB5JN6', 'PBAJA9', 'FB5189', 'BB12E9', 'BB3EK3', 'DB4A0X', 'BB13EX', 'DB0G03', 'KBAAGX', 'DB0C03', 'BB3EK9', 'DBWG30', 'CB09J1', 'BBOBEO', 'BBOBEX', 'PBAJA1', 'BB03E7', 'DB12E4', 'PBEJA4', 'DB24B1', 'CB3FV8', 'AB36U5', 'DB41S7', 'EB13E0', 'LB5JN9', 'BB13E0', 'DB0E0S', 'KB20U1', 'KB8CDO', 'DB4A07', 'KB54H1', 'PBEHD5', 'ZBB2K7', 'HB10V4', 'KB71J6', 'KB20U0', 'CB09J2', 'PBEFD5', 'DB12E3', 'NB1BB2', 'BBOCE3', 'EB02E3', 'BB12E8', 'BB03E8', 'EBRBEX', 'DB4A06', 'AB1BAO', 'JBYP2X', 'DBZSV4', 'GBRCH2', 'DB0A05', 'KB8CP8', 'HB8CD9', 'AB1BYB', 'BB0BEB', 'CB3377', 'PBEJA6', 'CB3379', 'EBRBE8', 'AB18Y8', 'DB0A08', 'KBRFU3', 'BB9HET', 'DBOE08', 'GBKFWB', 'KB22U1', 'HB8CD5', 'BBRCH6', 'KB3FUB', 'BB0BBE', 'EB13E7', 'DB8CD8', '1BAA33', 'BB3EK7', 'PBEFA6', 'KB5DB8', 'GBRCH7', 'GBRCH5', 'BB13E7', 'DB4A00', 'HB8CD3', 'BB12E0', 'HB9CP8', 'DB0A00', 'DB0C09', 'BBOCE1', 'DB12E5', 'BB3EK4', 'VB9E61', 'XBRCH7', 'DB0C00', 'DB21B2', 'KBBCDS', 'KB3FUS', 'LB71J0', 'DB12E2', 'KB5DB9', 'EB13E8', 'WBC7H5', 'HB8CD6', 'FBABG2', 'BBRCH4', 'BBOCE6', 'PBEWA6', 'EBRBE6', 'DB0AOX', 'LB71J2', 'BBSHE4', 'DB8CDX', 'VB9E69', 'PBEHD9', 'SBAS3X', 'CB09JX', 'ZBB7H0', '8B9HEX', 'BB13E9', 'PBAJA7', 'DBYSVX', 'PBEFA8', 'PBEJAX', 'RB71J5', 'PBEJA8', 'AB7RJ4', '0B9CB0', 'DB2A07', 'BB12E4', '1BAA34', 'DB4C00', 'DB4C08', 'BBOCE2', 'DB2A09', '8BCE1J', 'BBDEE4', 'PBGJB2', 'BBSHEX', 'ABFAJ7', '1BAA38', 'BBOBEG', 'DB8FS7', 'VB9E73', '1BAA37', 'FB7180', 'RB23E2', 'KBRCH0', 'YBBCA5', 'KB5DA5', 'ABCBJO', 'RB71J3', 'AB7BJZ', 'DB4A02', 'DBYSV3', 'ABBBJB', 'BB08E3', 'ABFAJ0', 'DB8CD7', 'XBRCH1', 'LB5JN3', 'DB9CB7', 'LB5JN0', 'LB3CHI', 'KBRFUX', 'EBRBEB', 'KB5AB0', 'DB0A01', 'ZBB2KX', 'KB5DB2', 'AB7BJB', 'ZBB2K9', 'ZBB2K0', 'RB71J4', 'YB20H2', 'KBRFU0', 'DBZSV5', 'DB8CD6', 'DBZSV9', 'BB8CD7', 'DB2C05', 'BBRCH1', 'ABBDH7', 'KB2000', 'DB8CD9', 'PBEJA2', 'DB21BX', '3B0075', 'EB13E6', 'DB12E0', 'LBACX1', 'BBE32K', 'EBRCHX', 'DB9CB1', 'JB6CB4', 'CB09J7', 'FBABG6', 'LB5JN7']
  Model_Year: ['F', 'H', 'N', 'R', 'P', 'S', 'E', 'K', 'J', 'M', 'A', 'T', 'G', 'L', '8', 'Y', '7', '6', 'C', '9', 'X', '3', '1', 'V', 'B', '5', '2', 'D', '4']
  Plant_Code: ['5', '3', '4', '1', 'W', '0', 'J', '8', 'B', 'X', 'S', 'U', '7', 'Z', 'C', '2', '9', '6', 'H', 'F', 'V', 'M', 'R', 'G', 'A', 'D', 'T', 'O', 'P', 'E', 'K', 'N']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,4.0,RKL,BB9HE7,F,5,115863
1,TOYOTA,PRIUS,4.0,HATCHBACK,K,ICONIC,GCC,5.0,JTD,KB3FUO,H,3,577510
2,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,ABBBJ0,N,4,038683
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,D,GL2,GCC,4.0,MRO,DB9CD3,R,5,014183
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,K,SGLX,GCC,2.0,MR0,KB8CD7,R,1,220373
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12368,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AB7BJ5,P,4,060145
12369,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AB7BJ0,P,4,084921
12370,TOYOTA,PRIUS,4.0,SEDAN,K,ICONIC,GCC,NaN,JTD,KB3FU0,J,3,596046
12371,TOYOTA,COROLLA,4.0,SEDAN,B,1,GCC,NaN,RKL,BB0BE2,L,0,021418
12372,TOYOTA,LAND CRUISER,6.0,SUV,A,1,GCC,NaN,JTM,ABBBJ6,S,4,188504

====================================================================================================
pos5: X
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'HILUX', 'FORTUNER', 'LAND CRUISER', 'INNOVA', 'TACOMA', 'PRADO', 'FJ CRUISER', 'TUNDRA', 'COROLLA', 'CRESSIDA', 'LAND CRUISER PICK UP', '2009', 'COASTER', '26HX DC 4X4P2.7LAT', 'RAV4', 'AURION', 'LAND CRUISER PRADO', 'CAMRY', 'هاي لوكس', 'TAKOMA', 'HILUX RE', 'TOKOMA', '25 HX DC 4X4 2.7LAT', 'GLX DA (PICK UP)', 'TOYOTA', 'TOYOTA HILUX', '25 HX DC 4X4P 2.7LAT', 'GLX RA (PICK UP)', 'TOYOTA HIACE', 'هايلوكس', '25 HX DC 4X2 P 27L AT GLX RA/PICK UP', '26HX DC 4X4 PLAT', '2 HX DC 4X4 P 2.7LAT', 'تاكوما', '25 HX DC 4X4 P .LAT', '26 HX DC 4X4 P 2.7LAT', '2024', '25 HX DC 4X4 PLAT GLX RA(PICK UP)', 'SIENNA', 'AVANZA']
  bodyType: ['MINI BUS HIGH ROOF', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'SUV', 'MPV', 'PICK UP', 'VAN', 'PICK UP SINGLE CAB', 'MINI BUS', 'PICKUP', 'PANEL VAN HIGH ROOF', 'HALF PANEL VAN', 'BUS', 'MINIVAN', 'MINI BUS SEMI HIGH ROOF', 'SEDAN', 'STATION', 'PICKUP TRUCK', 'CARGO VAN', 'PICKUP SINGLE CABIN', 'PICKUP DOUBLE CAB', 'PICKUP DOUBLE CABIN', 'CONVERTIBLE', 'PICK-UP']
  pos4: ['H', 'B', 'P', 'D', 'C', 'Y', 'J', 'X', 'F', 'E', 'U', 'S', 'G', 'R', 'N', 'K', 'Z', 'T', 'A', 'M', '5', 'W', 'I', '0', '8']
  trim: ['GLX', 'DX', 'DL', 'GL', 'EXR', 'GL2', 'SR5', 'GXR', 'DLX', 'VXR', 'STD', 'GLS', 'DLX TOP', 'SE', 'SAFARI', 'EXTREME', 'TOP', 'DLS', 'SE+', 'STD (NON GCC)', 'DX H/R W/B', 'TX-L', 'TX', 'SGLX', 'TX-L TOP', 'ADVENTURE', 'PREMIUM', 'VX2', 'VX MID', 'STANDARD', 'SR5 (NON GCC)', 'SPORT', 'S', 'SR', 'LX AC PWR OPT', 'PICK UP', 'GL TOP', 'GRD', 'GLI', 'TRD SPORT', 'DLS - STD ROOF', 'GXR+', 'XTREME', 'LIMITED', 'EX', 'CRESSIDA', '1', 'ADVENTTURE', 'LE', 'VX', 'STANDER', 'PRESTIGE', 'VX2 PLUS', 'SS', 'GX', 'GLE', 'GLI TOP LEATHER', 'VX-L MID', 'A', 'VXR BASE', 'GGG', 'GXR GT', 'C', 'S T2 TOP', 'LUXURY SPORT', 'XLI', 'AA', 'PICKUP', 'GXR TOP 60TH ANNIV. XTREME', 'GXR SOD D/AC AW', 'VX1', 'X', 'GXR MID', 'CTD', 'ST', 'CAR TRIM', 'LE (NON GCC)', 'SINGLE CABIN', 'SE T2', 'TAXI', 'TRIM']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTF', 'MR0', 'MHF', 'JTG', 'JTM', 'MRO', '5TF', 'JTE', 'MR1', '5TE', 'JTV', 'JT6', 'LFM', '3TY', 'JT2', 'MHE', 'ITG', 'KNF', 'MRI', 'JTN', 'MRD', 'JT8', 'UTG', '1FT', 'JTH', 'J1G', 'JS1', 'JIG', 'JIF', '1TF', 'CTF', '1TG', 'STE', 'SMT', 'MRU', 'HA9', 'JT4', 'MFH', 'MHP', 'MRC']
  VDS: ['HX02PO', 'HX02P7', 'HXDGP7', 'BX8CD3', 'PX22P7', 'DX8FS9', 'CX9CB1', 'PX22P6', 'YX59G9', 'JX02P1', 'HX02P1', 'HX09J2', 'XX43G3', 'XX43G7', 'DX8FS2', 'HX01JX', 'YX59G2', 'FX22G1', 'HX09J5', 'FX22G3', 'HX01J2', 'HX02P5', 'FX22G8', 'HX05J9', 'EX12G5', 'DX22G9', 'HX05J2', 'JX9CD1', 'HX8CD5', 'JX02P4', 'DX22G3', 'HX02P4', 'PX22P8', 'DX8FS5', 'HX09J1', 'EX12GX', 'UX4EN4', 'HX09J7', 'EX19G3', 'PX22P0', 'HX09J6', 'HX01J8', 'BX8CD8', 'FX22G2', 'FX22G5', 'BX8CDX', 'HX01J9', 'HX8CD4', 'JX02P9', 'BX8CD2', 'SX22P6', 'DX8FS3', 'HX05JX', 'YX59G3', 'JX02P8', 'XX43G1', 'HX8CD6', 'CX19GX', 'HX02PX', 'CX9CB0', 'HX09J4', 'HX01J7', 'HX02P6', 'XX43GX', 'FX22GX', 'XX43G0', 'XX42G2', 'DX22G8', 'XX42GX', 'HX05J6', 'HX02P8', 'CX9CDO', 'JX02P6', 'HX05J4', 'DX22G1', 'CX19G8', 'YX59GX', 'PX22PX', 'CX9CD4', 'BX9FJ6', 'EX19G8', 'EX19GX', 'PX22P4', 'HX8CDX', 'JX02P3', 'CX8CD6', 'PX22P1', 'DX9CD0', 'EX12G2', 'CX19G7', 'HX02P2', 'HX8CD7', 'CX12G5', 'HX8CD3', 'YX59G8', 'FX22G7', 'CX19G4', 'BX8CD1', 'JX8CD5', 'CX9CB6', 'PX22P3', 'GX8EM3', 'CX3FJ4', 'DX22G6', 'DX8FS1', 'HX8CD2', 'HX01J0', 'FX22G6', 'CX12G7', 'HX05J3', 'HX02P0', 'HX8CD0', 'JX02P7', 'PX22P9', 'EX12G4', 'CX19G0', 'PX22P2', 'EX19G0', 'PX22P5', 'HX09J9', 'XX43G9', 'RX12P6', 'SX22PX', 'HX05J7', 'HX01J5', 'CX9CB7', 'DX8FS8', 'HX8CD8', 'YX59G1', 'YX59G0', 'CX19G5', 'JX02P5', 'HX09J3', 'DX8FSX', 'EX12G0', 'JX02P2', 'FX22G4', 'PX42N6', 'HX01J3', 'RX12P5', 'FX22G0', 'DX8FS4', 'HX02P3', 'CX6CB3', 'YX59G6', 'JX8CD8', 'JX02P0', 'EX12G6', 'SX22P2', 'EX19G4', 'JX8CD3', 'JX02PX', 'CX3FJ9', 'CX8CB9', 'RX12P7', 'NX4CN9', 'CX12G4', 'EX19G1', 'BX9FJ7', 'BX8CD7', 'XX43G4', 'YX59G4', 'HX02P9', 'CX9CB5', 'SX22P3', 'FX22G9', 'HX05J0', 'EX12G8', 'HX09J8', 'DX8FS6', 'JX8CB7', 'HX05J1', 'BX9FJ9', 'CX9CD8', 'EX19G6', 'XX43G8', 'CX8EM1', 'BX8CD6', 'XX43G5', 'JX8CD4', 'XX42G5', 'JX8CD1', 'JX8CD9', 'XX43G2', 'EX12G7', 'BX9FJX', 'JX8CD2', 'SX22P1', 'BX9FJ8', 'CX12G8', 'HX01J4', 'CX12G1', 'DX22G4', 'XX42G1', 'YX59G7', 'BX9FJ0', 'CX8EM5', 'CX9CB8', 'DX9CD2', 'HX8CD1', 'RX12P2', 'CX12GX', 'SX22P8', 'BX8CD9', 'SX23P1', 'CX8EM3', 'DX9CD4', 'HX09JX', 'EX12G9', 'HX01J1', 'DX22G0', 'KX8CBX', 'FX2260', 'CX9CB2', 'DX8CD5', 'DX9CDX', 'CX9CDX', 'DX22GX', 'DX8CD4', 'ZX69G8', 'SX23P5', 'SX23P3', 'DX9CD5', 'EX19G2', 'KX8CB4', 'NX4CN8', 'BX8CD4', 'SX22P4', 'XX42G4', 'CX8EM9', 'XX42G3', 'SX23PX', 'CX19G1', 'CX9CB9', 'EX12G1', 'DX8CD1', 'UX42NX', 'XX42G6', 'HX09J0', 'HX05J8', 'HX01JO', 'DX9CD3', 'DX8CD7', 'RX12P4', 'DX22G2', 'DX22G5', 'CX8EMO', 'BX8CD0', 'EX1269', 'XX42G9', 'RX12PX', 'JX8CD7', 'NX22N1', 'KX9CBX', 'HX05J5', 'SX23P9', 'BX8CD5', 'CX12G9', 'CX3FJX', 'CX9FJ8', 'JX8CD0', 'DX6CDX', 'CX12G6', 'CX3FJ3', 'BX9FJ5', 'CX8EM0', 'EX19G7', 'HX01J6', 'JX9CD4', 'SX23P6', 'CX9CBX', 'DX8FS7', 'NX22N3', 'BX9FJ1', 'RX12P9', 'CX19G9', 'CX12G0', 'CX9CD9', 'EX12G3', 'CX6CBX', 'RX12P1', 'XX43G6', 'RX12P3', 'DX9CD1', 'KX8CB2', 'DX8F58', 'CX3FJ0', 'DX6CD9', 'XX42G0', 'CX8EM8', 'TX22NX', 'CX8EM7', 'CX8CD3', 'CX19G6', 'KX6CB1', 'NX4CN6', 'BX9FJ2', 'CX8EMX', 'XX42G8', 'SX23P7', 'CX9CD6', 'HXHX01', 'JX8CD6', 'CX9CD5', 'CX8EM4', 'CX8EM6', 'CX3FJ5', 'XX42G7', 'BX3FJ5', 'CX9CB4', 'DX8FS0', 'HX8CDO', 'DX8CD6', 'PX22PO', 'DX22G7', 'BX3FJ0', 'BX3FJO', 'KX8CB1', 'NX4CN4', 'CX19G2', 'YX59G5', 'CX8EM2', 'BX9FJ3', 'HX02PS', 'BX3FJ7', 'CX6CD9', 'CX9FJ6', 'EX19G9', 'GX8EM9', 'RX12P0', 'CX6CB4', 'DX9CD6', 'CX6CD8', 'SX23P2', 'AXACC2', 'CX3FJ2', 'CX8GS9', 'RX12PO', 'CX6CB7', 'SX22P7', 'SX5EN1', 'CX12G3', 'RX12P8', 'KX8CB7', 'XX4262', 'TX4CN0', 'BX3FJ9', 'CX12G2', 'CX6CDX', 'CX3FJ8', 'CX9CD3', 'NX4CN2', 'JX6CB8', 'BX9FJ4', 'CX19G3', 'AX12G8', 'KX9CB7', 'AX12GX', 'ZX69G7', 'JX9CD7', 'CX8CB5', 'GX8EMX', 'CX9CD1', 'KX8CB8', 'SX22P5', 'MX83EX', 'ZX69G3', 'KX8CB3', 'GX8EM1', 'JX8CDX', 'KX6CB2', 'RX5GN2', 'EX1266', 'KX8CD0', 'BX9FJO', 'CX9CD2', 'CX9FJ7', 'AX12G0', 'CX8CB6', 'GX8EM5', 'SX23P0', 'SX22P0', 'DX8CD2', 'KX6CB4', 'JX9CB7', 'JX6CB4', 'CX9FJ1', 'CX8CD8', 'SX23P8', 'YX5968', 'DX9CD8', 'JX8CB8', 'JX6CD6', 'JX9CD5', 'HX8CD9', 'KX9CB4', 'JX6CB2', 'RX5GNX', 'PX4EN2', '5X23P5', 'NX4CN3', 'CX9FJ0', 'JX02PO', 'EX19G5', 'CX6CB6', 'KX9CB8', 'CX9CB3', 'FX00G6', 'AXACC6', 'KX6CB6', 'AXACC0', 'NX22N0', 'GX8EM2', 'TX4CN5', 'CX3FJ1', 'HXO2PX', 'KX9CB0', 'EX1268', 'KX9CB6', 'DX8F5X', 'SX22P9', 'YX69GX', 'SX23P4', 'KX8CB5', 'NX4CNX', 'AX12G1', 'CX9CD0', 'AX12G7', 'KX9CB5', 'NX4CN5', 'PX42N3', 'CX6CB0', 'CX8CD9', 'WXZ74A', 'EX1263', 'CX9FJ5', 'GX8EMI', 'DX9CD9', 'DX6CD6', 'ZX69G6', 'CX6CD6', 'JX6BB0', 'CX8CB1', 'CX1267', 'CX8CD5', 'RX5GN7', 'KX9CB1', 'CX8CB0', 'IX02P5', 'CX3FJ7', 'GX8CD9', 'CX8CD1', 'TX4CN7', 'FX2265', 'TX22N0', 'NX4CN0', 'CX9FJ2', 'JX9CDX', 'BX3FJ1', 'CX8CBX', 'CX8CB8', 'CX6CD2', 'DX6CD8', 'DX8CDX', 'CX8CB3', 'KX6CB3', 'DX8FSO', 'ZX69G4', 'KX9CB3', '0X22G9', 'JX6CB9', 'DX6CD2', 'KX6CB7', 'CX9FJ9', 'CX6CD4', 'GX8EM0', 'GX8EMO', 'JX4CN3', 'DX8CD9', 'JX8BB2', 'KX8CB0', 'CX3FJ6', 'BX3FJ2', 'BX3FJ3', 'NX22N2', 'GX8EM7', 'CX6CD0', 'JX6CB3', 'CX8GS6', 'HX0937', 'JX8BB9', 'EX1209', 'XX43GI', 'DX8CD8', 'ZX69G1', 'JX6CD1', 'AX12G2', 'DX9CD7', 'PX4EN3', 'PX4EN6', 'JX02PB', 'JX9CD3', 'CX1263', 'AXACC5', 'AX12G9', 'CX9CD7', 'CX9FJ4', 'FX2262', 'FX2269', 'AX12G6', 'AX12G5', 'CX1966', 'RX5GN6', 'CXBEM0', 'TX22N1', 'JX8CB3', 'EX1261', '8X9FJ1', 'XX4367', 'FX2261', 'BX3FJ6', 'NX22N5', 'FX2266', 'ZX69G9', 'CX6CB1', 'KX9CB2', 'KX8CB9', 'HX0936', 'CX6CD5', 'CX8CD0', 'CX8CD4', 'JX8CB4', 'HX0SJS', 'ZX69GX', 'CX8CD2', 'JX8BB4', 'CX6CD7', 'JX6CDX', '8X8CD8', 'HX09JO', 'JX6CD4', 'GX8EM8', 'JX9CD6', 'TX02P8', 'XX4266', 'JX6BB5', 'BX3FJ8', 'EX1265', 'CX8CB4', 'CX6CD1', 'TX4CNX', 'CX8CDX', 'PX22PI', 'KX6CBX', 'JX9CD9', 'JX6BB6', 'DX6CD3', 'KX8CB6', 'MX83E7', 'NX62N0', 'BX8CDO', 'BX8C05', 'MX73E3', 'DX8CD0', 'TX22N7', 'AX12G4', 'YX59C7', 'NX22N9', 'JX9CD8', 'XX42GO', 'MX73E9', 'KX6CB5', 'XX4366', 'HX05JO', 'DX9CB3', 'EX1969', 'NX22N8', 'JX02PV', 'CX6CB9', 'ZX69G0', 'CX6CD3', 'JX4CN1', 'XX4264', 'NX4CN1', 'NX22N7', 'CX1266', 'HX0931', 'DX8CD3', 'YX5966', 'YX5960', '5X23P9', 'ZX69G2', 'XX4362', 'TX4CN4', 'GX8EM6', 'HXO1J1', 'HXO9J8', 'HX0IJ3', 'GX8EM4', 'EX1E63', 'TX22N3', 'KX6CB8', 'PX4EN0', 'CX1265', 'NX22N4', 'FX02P3', 'CX8CB2', 'JX6CD2', 'EX22G0', 'BX3FJ4', 'XX4360', 'HXD2P9', 'CX8CD7', 'AX12G3', 'DX8F52', 'CX9FJ3', 'YX5906', '5X23P1', 'YXS9G3', 'CX1264', 'JXOZP1', 'JX9BBX', 'AXACC9', 'DX6CD4', 'BX8CDE', 'FX2264', 'JX6CD7', 'DX6CD7', 'KX6CB9', 'GX72AX', 'XX4369', 'CX8CB7', 'AXACCO', 'JX9CB8', 'YX5964', 'CX12GO', 'BXBCD6', 'AXACC7', 'CX6CB2', 'JX6CB6', 'TX4CN2', 'YX5969', 'JX9CB2', 'HX0139', 'JX8BB5', 'DX8FSB', 'FX226X', 'JX4GN3', 'KX6CB0', 'JX9CD0', 'JX9CB1', 'JX6CD0', 'NX22NX', 'NX4CN7', 'JX8BB1', 'UX4ENX', '8X9FJ0', 'PX4ENX', 'HX02J2', 'CX6CB8', 'YX5963', 'JX9CB9', 'TX22N9', 'EX1964', 'DX6CD0', 'HX0934', 'JX6CD8', 'DX6CD5', 'EX1267', 'TX4CN1', 'HX02PI', 'JX9CB6', 'HXO2P7', 'KX8C85', 'EX1262', 'RX5GN9', 'BXBCD5', 'JX8BB7', 'SX23PO', 'CX8GS0', 'TX4CN6', 'CX8C80', 'DX8F55', 'CX8GS5', 'FX2263', 'SX22PO', 'XX4263', 'HXBCDB', 'JX6CB7', 'JX6CD9', 'FX22C2', 'CX9CBO', 'YX59GZ', 'XX42GB', 'XX4308', 'FX22C3', 'JX8CB2', 'DX2266', 'HX0131', 'DX8F59', 'FX2267', 'CX9C88', 'XX436X', 'DXBFS8', 'JX9CBX', 'CX1261', 'TX4CN8', 'DX6CD1', 'TX22N8', 'JX6BB2', 'JX6CB0', 'SX5EN7', 'JX9CD2', 'JX6CD3', 'DX8CDO', 'PX42N5', 'AXACC3', 'ZX69G5', 'HX0935', 'JX9CB4', 'DX22GO', 'RX5GN0', 'SX5EN4', 'CX1268', 'AXACCX', 'JX8BB0', 'BX9F13', 'DX1H24', 'KX9CB9', 'DX8F51', 'DX2269', 'AX1269', 'SX5EN0', 'PX4EN8', 'EX126X', 'DX2267', 'HX0919', 'GX8CD6', 'PX4EN5', 'JXQ2P1', 'XX426X', 'RX5GN5', 'NX22N6', 'DX6CBX', 'TX4CN9', 'RX5GNO', 'DX6CDO', 'DXBCD6', 'DX9CDB', 'PX42N2', 'FX2268', '5X23PX', 'EX12GO', 'HXO2P6', 'EX1963', 'HX02PB', 'AX5GNX', 'PX42N4', 'HX02PU', 'AX8CD9', 'JX8CB5', 'GX8CD3', 'CX1904', 'EX1965', '8X9FJ8', 'TX22N6', 'CX8EMI', 'BX9FJS', 'BXBCD7', 'YX5965', 'TX9A21', 'EX1260', 'CX1269', 'KX9CBO', 'HXQ2P9', 'RX5GN3', 'CX126X', 'HXO2P1', 'DXBFS5', 'DX8F50', 'CX8GS2', 'HX02J8', 'JX6BB7', 'DX9CDS', 'CX9CBI', 'AX1268', 'YX59GI', 'JX8CB0', 'EX91G3', 'HXO2P0', 'HXO2PG', 'HX07P1', 'NX0375', 'DX8F57', 'KX8CD6', 'HXO2P9', 'EX22G4', 'AX5GN8', 'JX6CBX', 'PX4EN4', 'CXI9G4', 'XX4364', 'RX56N3', 'JX6CB5', 'BX8CDI', 'UX4EN5', 'AXACC4', 'YX5962', 'FX22GO', 'YX50G0', 'DX9CB2', 'FX22P9', 'XX48G8', 'EX22G1', 'CX19GO', 'JX6BB8', 'KX8CD4', 'YX5967', 'YX59CX', 'CX8GSX', 'JX8BB3', 'TX22N2', 'RX22G4', 'XX4303', 'RX22G7', 'GXSEM0', 'CX0CD4', 'JX8BBX', 'TX4CN3', 'EX22G8', 'HX0939', 'CX3DD5', 'PX4EN7', 'KX8CDX', 'KX8FS7', 'PX22PZ', 'JX8CB9', 'YX59GE', 'JXO2P1', 'CX190X', 'GX8CD0', 'XX4361', 'MX83E0', 'UX4EN2', 'KX8CD5']
  Model_Year: ['F', 'N', 'A', 'L', 'P', 'D', 'C', 'E', '7', '6', 'M', 'G', '9', '8', 'B', 'H', 'K', 'J', 'R', '5', 'S', 'T', '3', '1', '2', 'X']
  Plant_Code: ['0', '2', '3', '8', '4', '1', '5', 'X', '6', 'K', 'Z', '7', 'T', '9', 'S', 'O', 'G', 'J', 'F', 'C', 'Q', 'D', 'I']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,H,GLX,GCC,4.0,JTF,HX02PO,F,0,099797
1,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,H,DX,GCC,4.0,JTF,HX02P7,F,0,094323
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DL,GCC,4.0,JTF,HXDGP7,F,0,094373
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,B,GL,GCC,4.0,MR0,BX8CD3,N,2,843057
4,TOYOTA,HIACE,4.0,PANEL VAN,P,GL,GCC,5.0,JTF,PX22P7,A,0,017757
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35094,TOYOTA,HILUX,4.0,PICKUP,F,DLX TOP,GCC,NaN,MR0,FX22GX,D,1,360776
35095,TOYOTA,LAND CRUISER,8.0,SUV,H,VXR,GCC,NaN,JTM,HX05J6,J,4,164606
35096,TOYOTA,LAND CRUISER PRADO,4.0,SUV,B,GXR,GCC,NaN,JTE,BX9FJ0,K,K,315814
35097,TOYOTA,HILUX,4.0,PICKUP,E,1,GCC,NaN,MR0,EX12G3,B,2,053186
35098,TOYOTA,LAND CRUISER,8.0,SUV,H,GXR,GCC,NaN,JTM,HX01J3,M,4,222343

====================================================================================================
pos5: G
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'HILUX', 'COROLLA', 'كامري', 'YARIS', 'RAV4', 'HIACE', 'FJ CRUISER', 'INNOVA', 'COASTER', '86', 'LAND CRUISER', 'SIENNA', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PICKUP', 'SUV', 'PANEL VAN', 'MPV', 'MINI BUS', 'HATCHBACK', 'BUS', 'SALOON', 'COUPE', 'CARGO VAN']
  pos4: ['B', 'E', 'A', 'F', 'N', 'W', 'C', 'P', '8', 'G', 'H', 'T', 'D', '3']
  trim: ['XLI', 'BASE', 'GLE', 'DLX', 'LIMITED', 'CE (NON GCC)', 'STD', 'LE', 'LSE', 'XLE (NON GCC)', 'XLI MID', 'E PLUS HEV', 'LE HEV', 'XLE', 'SL', 'SE', 'GLI', 'XLE HEV', 'GL', 'EX', 'ADVENTURE', 'LUMIERE HEV', 'E', 'LWB', 'VXR', 'DLS', 'S', 'MID', 'LE (NON GCC)', 'DLS - STD ROOF', 'SPORT', 'GLI HEV', 'GX', 'VTI', 'GLX', 'GXR', 'A', 'GLS', 'SWB', '1']
  regionalSpec: ['NON-GCC', 'GCC']
  WMI: ['4T1', '6T1', 'JT2', 'JTF', 'JTN', 'JT4', 'GTF', '4TI', 'YV2', 'JM3', 'LVG', 'RA6', 'WD4', 'KMH', 'MB1', '6TI', '1GD', 'GGG', 'KMJ', 'JN2', 'LJN', '1GJ', '1GC', 'L3H', 'MBI', 'MBT', 'JTE', '5TD', 'JHD']
  VDS: ['BG22K0', 'BG22K1', 'BG22KX', 'BG12KX', 'EG4265', 'AG4CK1', 'BG22K9', 'BG22K4', 'BG28K0', 'BG22K3', 'EG22K1', 'BG22K7', 'BG22K5', 'EG22K5', 'BG22K8', 'BG22K2', 'BG28K6', 'AG4262', 'EG4261', 'EG4264', 'EG22K8', 'BG28K7', 'BG22K6', 'EG4260', 'AG4261', 'EG23K8', 'EG4263', 'EG4269', 'AG4266', 'AG4264', 'AG4263', 'FG4265', 'EG22K3', 'EG22K9', 'BG28K5', 'EG22K6', 'EG4267', 'EG23K3', 'BG23K3', 'AG4CK5', 'AG4CK0', 'AG4268', 'AG4CK3', 'NG4268', 'BG28K8', 'AG4CK6', 'EG22K0', 'EG22K7', 'AG4265', 'EG22K2', 'AG4269', 'EG4268', 'AG4CK2', 'AG4CK9', 'AG4CKO', 'BG28K4', 'AG426X', 'EG22KX', 'EG22K4', 'BG12K0', 'AG4CK4', 'AG4CK7', 'EG426X', 'AG4CKX', 'BG23K1', 'AG4CK8', 'BG28K9', 'AG30AX', 'AG4267', 'BG28K1', 'AG4260', 'WG7255', 'BG22KO', 'EG23K5', 'AG4CKI', 'BG28K2', 'BG23K0', 'CGE234', 'BG23K9', 'NG4269', 'EG23K9', 'BG28KS', 'PG34L5', 'BG12K1', 'NG4263', 'BG28KX', 'BG12K9', 'EG4258', 'NG4262', 'AG20A8', 'EG4262', 'BG28K3', '8G22K9', 'WG3E13', 'WG81R1', 'AG34L4', 'EG4266', 'BG12K3', 'NG4265', 'FG15T7', 'GGG565', 'CGE231', 'NG426X', 'BG21K1', 'BG23K2', 'BG23K8', 'BG12K7', 'HG17C8', 'BG12K6', 'NG4260', 'EG21K3', 'HG17CX', 'AG34L8', 'BG23K4', 'WG725X', 'BG17K2', 'BG12K5', 'TGUB23', 'DG61E8', 'BG23K6', 'BG23K5', 'NG4266', 'AG34L2', 'EG23KX', 'AG426U', 'GG25K7', 'WG81R3', 'PG34L8', 'EG23K2', 'NG4264', 'BG23KX', 'AG34L7', 'WGAFP8', 'HG39K3', '8G22K1', 'CG12K9', 'BG12K4', 'EG12K0', 'WG81R8', 'EG12K5', '3G22K7', 'EGCBB3', 'AG34L1', 'AG34LI', 'AG34L3', 'BG21K8', 'HG09G2', 'BG21KX', 'AG34L9', 'DGRFH6', 'EG23K0', 'NG4267', 'BG22KB', 'EG23K6', 'AGACH8', 'FG8JP7', 'HG17C1', 'WG7258', 'BG21K9']
  Model_Year: ['1', 'X', 'T', '3', 'S', 'Y', '2', 'W', '4', 'V', 'C', '5', 'E', 'R', 'A', 'K', 'G', 'N', 'M', 'D', '8', 'P', '9', 'B', 'H', 'J']
  Plant_Code: ['U', 'X', '0', '3', 'B', 'G', 'R', '1', '2', 'C', 'N', 'A', '5', 'S', '4', '8', '7']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,NON-GCC,4.0,4T1,BG22K0,1,U,789089
1,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,GCC,4.0,6T1,BG22K1,X,X,372186
2,TOYOTA,CAMRY,4.0,SEDAN,B,BASE,GCC,4.0,4T1,BG22K1,1,U,817403
3,TOYOTA,CAMRY,4.0,SEDAN,B,BASE,GCC,4.0,JT2,BG22KX,1,0,563873
4,TOYOTA,CAMRY,4.0,SEDAN,B,GLE,GCC,4.0,4T1,BG12KX,T,U,818658
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4756,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,1,NON-GCC,NaN,JT2,BG22K5,1,0,556233
4757,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,CE (NON GCC),GCC,NaN,6T1,BG22K4,Y,X,401780
4758,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,CE (NON GCC),GCC,NaN,6T1,BG22K7,1,X,443303
4759,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,XLI,GCC,NaN,6T1,BG22K2,Y,X,381092
4760,TOYOTA,CAMRY HYBRID,4.0,SEDAN,A,GLE,GCC,NaN,JTN,AG4CK3,S,3,022074

====================================================================================================
pos5: T
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'YARIS', 'XA', 'ECHO', 'TUNDRA', '4RUNNER', 'COROLLA', 'PRIUS', 'FORTUNER', 'HILUX', 'LAND CRUISER VXR', 'SEQUOIA', 'استیشن', 'CAMRY', 'PRADO', 'TANDRA', '4 RUNNER', 'TOYOTA TUNDRA', 'LAND CRUISER PICK UP', 'RAV4', 'HIACE', 'STREET TRIPLE', '2014', 'PARISIENNE BROUGHAM', 'TANDRA PICK UP DOUBLE CABIN']
  bodyType: ['SUV', 'SEDAN', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'STATION', 'PICK UP SINGLE CAB', 'PICKUP', 'SALOON', 'PICK UP', 'PICK UP DOUBLE CABIN', 'PANEL VAN', 'MOTORCYCLE', 'TRUCK']
  pos4: ['H', 'B', 'K', 'J', 'D', 'R', 'P', 'E', 'Z', '8', 'M', 'S', 'I', 'L', 'N', 'A', 'T', '2', '9']
  trim: ['VX', 'SE', 'SE TRD AERO PK', 'STD', 'G', 'SE+', 'TOP', 'S+', 'S', 'BASE', 'VXR', 'XLI MID', 'FLEET', 'GX', 'VXR BASE', 'VXR TOP', 'E', 'STD (NON GCC)', 'MID', 'SAFARI', 'SR5 (NON GCC)', 'GLI TOP', 'XLI', 'SPORT', 'GXR TOP', 'GXR', 'DLS', 'GXR FMST', 'DLX', 'LIMITED', 'GL', 'GXR SOD D/AC AW', 'GXR TOP 60TH ANNIV. XTREME', 'GLI', '4X4', 'GXR MID 60TH ANNIV. XTREME', 'TRIM', 'GXR TOP DMST', 'GL DECKLESS', 'GLX', 'STATION ', 'SR5 4X2', 'ROYAL', 'VXR TOP XTREME', 'GXR MID', 'EXR', 'XLI TOP', 'VXR MID', 'PS PW CL', '4', 'PW CL', '1', 'SPORTS', 'PLATINUM', 'GLS', 'EXCELLENCE', 'TUNDRA', 'PICK UP', '60TH', 'ASAD', 'GC', '2', 'X', 'SL', '0']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTM', 'MR2', 'JTE', 'JTD', 'MHF', 'JT3', '5TB', 'VNK', '5TF', '1GC', '5TD', '5T8', 'JTH', 'KMH', 'JND', 'JN1', 'STD', 'KNF', 'JTK', 'JTF', 'RKM', 'JTB', 'MMC', 'MR1', 'MFH', 'MHE', '5N1', 'MP2', 'SMT', 'JN8', 'ITE', '1G2', 'STB']
  VDS: ['HT09J7', 'BT9F38', 'HT05J3', 'KT9F38', 'HT05J9', 'JT923X', 'HT05J8', 'HT05J1', 'BT9F39', 'BT9230', 'BT9F32', 'HT09J5', 'BT9F36', 'BT9F35', 'HT09J9', 'KT9F31', 'KT6235', 'HT05J0', 'HT09J6', 'HT05J4', 'HT05JX', 'HT09J4', 'JT1236', 'JT4K3X', 'HTO5J8', 'HT05J7', 'KT9F30', 'BT4419', 'HT05J5', 'HT09JX', 'HT09J2', 'HT09J8', 'HT05J2', 'DT4416', 'KT9236', 'HT05J6', 'KT9F33', 'HT09J3', 'KT9231', 'BT9F3X', 'BT9F33', 'KT9F36', 'DT4412', 'BT9F31', 'KTUD36', 'KT9230', 'BT923X', 'BT14R4', 'KT9F37', 'KT9F35', 'KT4K39', 'BT9235', 'DT4413', 'BT1230', 'BT9236', 'HT09J0', 'KT6234', 'KT6239', 'KTUD32', 'KTUD31', 'KT9235', 'BT9231', 'JT9037', 'BT9239', 'BT9F37', 'KT6236', 'HT09J1', 'BT9232', 'KTUD39', 'JT4K36', 'KT6233', 'BT9F34', 'BT14R9', 'RT3412', 'KTUD37', 'BT9F30', 'JTUD34', 'KT6231', 'JT9237', 'KT5219', 'KT9F32', 'JTUD32', 'DT4417', 'KT6237', 'PTDEK3', 'JT9232', 'BT9234', 'HT0937', 'KTUD35', 'BT4414', 'KT9F3X', 'DT4411', 'KT9232', 'JTUD38', 'HTOSJX', 'ET3419', 'KTUD30', 'DT4415', 'BT9238', 'KT9D38', 'KT923X', 'KT9F34', 'KT9F39', 'DT4814', 'DT481X', 'KT6232', 'KTUD3X', 'JT9030', 'KT9D34', 'KTUD38', 'KTUD34', 'BT4K39', 'BT9233', 'KT9D36', 'JTUD35', 'KTUD33', 'JT1234', 'JTUD3X', 'KT623X', 'BT9237', 'ZT14R2', 'JTUD33', 'JT903X', 'HT0537', 'KT6230', 'DT4418', 'JT9239', 'BT4810', 'KT9D32', 'KT441X', 'ZT14R0', 'KT9237', 'BT17R4', 'BT9033', 'BT4417', 'JTUD36', 'KT9234', 'HTO5J6', '8T9F32', 'BT14RX', 'JT4K37', 'ZT38A3', 'JT9233', 'KT6238', 'JT4K35', 'KT9D31', 'RT5412', '8T9237', 'RT5416', 'KT5218', 'MT09J8', 'BT5410', '8T9F31', 'HTO5J1', 'BT5418', 'BT4418', 'BT17R1', 'BT5816', 'BT4411', 'KT5212', 'ET3417', 'DT4414', '8T9F3X', 'DT4817', 'BT441X', 'JT81E2', 'JT4K38', 'KT521X', 'BT4K31', 'KT9D39', 'BT4410', 'KT9D3X', 'KT9238', 'BT9F3I', 'PT9F39', '8T9F33', 'BT14R2', 'KT4K31', 'JT9238', 'KT4K35', 'BT4416', 'HT0530', 'KT9239', 'DT4410', 'KT9D35', 'BT17RX', 'KT4K36', 'HT0934', 'BT4K36', 'HTO5J9', 'JTUD37', 'HT05JO', 'DT3MW5', 'HT0535', 'BT48A9', 'BT5416', 'JT4K33', 'BT541X', 'RT3416', 'STZ74A', 'KT9031', 'KT9032', 'KT4K38', 'HT0533', 'HT0SJ3', 'KT624X', 'RT3413', 'BT17R6', 'BT4817', 'DTPUKX', 'KT1230', 'DT4813', 'KT5217', '8T9233', '8T9F35', 'BT4814', 'KT9D30', 'BT48A7', 'ITUJ80', 'BT4K38', 'HT5236', 'ST9F36', 'BT17R2', 'KT9D33', 'BT14R0', 'ZT14R1', 'MT5215', 'BT5411', 'ZT14R5', 'BT9030', 'DT4816', 'BT4819', 'BT4812', 'BT9037', 'BT4412', 'BT4K34', 'KT9D37', 'DT4815', 'RT541X', 'BT44A4', 'BT64A1', 'KT9030', 'BT17R8', 'HT06J3', 'ET9F33', 'ET9231', 'LT521X', 'HT0539', '8T9F36', 'JT4K30', 'KT6249', 'BT14R8', 'KT4K30', 'JT9234', 'DT4819', 'KT4410', 'BT4818', 'ZT17R1', 'RT3415', 'BT4K32', 'BT9036', 'HTO5J4', 'KT9233', 'JT9033', 'BT1234', 'JT4K34', 'HTO5J5', 'JT9235', '8T9F37', 'KT4217', 'BT4415', 'ZT14R6', 'ET3413', 'HT0514', 'HTO5J3', 'BT5415', 'BT17R9', 'HT0512', 'BT1233', 'DT4419', 'KT6242', 'BT4K3X', 'BT4413', 'BT44A2', 'BT4811', 'NT08J2', 'JTUD31', 'HT0518', 'BT4K30', 'BT17R7', 'JT9230', 'BT48A0', 'BT14R5', 'ET3416', 'AT2MVX', 'RT3417', 'BT17R0', 'HT09JO', 'KT9K38', 'BT4K35', 'RT5415', 'RT3410', 'BT9K3X', 'ZT34A3', 'BT9034', 'ET3410', 'BT481X', 'HT0SJ0', 'ET3418', 'ZT34A7', 'TTL136', 'BT2MW1', 'JT05J0', 'JT9236', 'HT09JL', 'BT9038', 'BT4813', 'JT9036', '2T14R7', 'ZT17R4', 'BT3AB3', 'ZT34A4', '8T9F34', 'JT1233', 'JT9032', 'BT5413', 'BT05Y4', '8T9F39', 'KT4418', 'BT5412', 'AT1237', 'DT5417', 'HT05JI', 'BT9F3S', 'KT5215', 'RT9F3X', 'DT4812', 'HTO5J0', 'JTUD30', 'JT9034', 'JTU031', 'RT3813', 'BT9K35', 'HT0935', 'HT0538', '8T9F38', 'HT0531', '9T9F34', 'BT48A4', 'ET3815', 'MT5213', 'BT44A9', 'ET3411', 'JT9231', 'BT4815', 'HT05JB', 'KT5214', 'ET9F32', 'BT5419', 'BT69Y4', 'ET3816', 'BT4K33', 'RT3419', 'BT3AA3', 'RT5410', 'ZT14R8', 'MT5218', 'HT0938', 'JT5218', 'DT4810', 'BT123X', 'KT6245', 'DT4811', 'KT5213', 'LT5219', '8T9F30', 'DT441X', 'KT6045', 'ST5415', 'HT0534', 'ET3412', 'BT5417', 'HT0536', '2T38A8', 'ZT38A8', 'ET3817', 'BT2233', '8T9238', 'RT3814', 'BT903X', 'BT4K37', 'HTO5J2', 'JT9K39', 'ET9F36', 'RT341X', 'HT0SJ2', 'RT381X', 'KT1231', 'HTO5J7', 'HTOSJ3', 'BT14R3', 'KT6041', 'LT5216']
  Model_Year: ['A', 'E', '6', 'F', '9', '8', '4', 'B', 'G', '7', '5', 'Y', '3', 'X', '1', 'D', '2', 'C', 'K', 'P', 'J', 'H', 'W', 'R', 'V', 'S']
  Plant_Code: ['5', '1', '2', '4', '6', '0', 'S', 'D', 'A', '8', 'X', 'U', 'L', 'W', 'K', 'H', 'C', 'E']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTM,HT09J7,A,5,049335
1,TOYOTA,YARIS,4.0,SEDAN,B,SE,GCC,NaN,MR2,BT9F38,E,1,079739
2,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTE,HT05J3,6,2,092774
3,TOYOTA,YARIS,4.0,SEDAN,K,SE TRD AERO PK,GCC,4.0,MR2,KT9F38,F,1,143683
4,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTM,HT05J9,9,4,028705
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12088,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTM,HT09J0,A,5,061424
12089,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTM,HT05J0,A,4,034400
12090,TOYOTA,YARIS,4.0,HATCHBACK,K,SE+,NON-GCC,NaN,VNK,KTUD38,F,A,040994
12091,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTM,HT09J6,9,5,038189
12092,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTM,HT09J0,A,5,079700

====================================================================================================
pos5: W
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'HILUX', 'COROLLA', 'TUNDRA', 'ECHO', 'RAV4', 'SEQUOIA', 'LAND CRUISER', 'HIACE', 'COROLLA 1.3', 'HIGHLANDER', 'CAMRY', 'RAV 4', 'PRADO', 'FJ CRUISER', 'MR 2', 'COASTER', 'XA', 'TOYOTA COROLLA', 'LAND CRUISER SINGLE-CABIN PICK UP', 'TOYOTA']
  bodyType: ['HATCHBACK', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'SEDAN', 'ESTATE', 'SUV', 'PICK UP', 'MINI BUS', 'SALOON', 'CARAVAN', 'STATION', 'COUPE', 'BUS', 'PICKUP', 'LIGHT VEHICLE']
  pos4: ['B', 'E', 'C', 'K', 'D', 'A', 'H', 'U', 'R', '8', 'G', 'P', '5', 'J', 'M', 'L', 'T', 'S', '6', 'F']
  trim: ['MID', 'DLX', 'GL', 'FLEET', 'BASE', 'SE', 'XLI', 'STD (NON GCC)', 'XLI TOP', 'TOP', 'S', 'EX', 'DLX TOP', 'VXR HEV', 'XLI MID', 'STD', 'GLX', 'XLE', 'PS PW CL', 'GLI TOP', 'EXR HEV', 'LE HEV', 'DL', 'EXR', 'GLS', 'VXR BASE', 'DX', 'STANDARD', 'GLI TOP LTH', 'VX', 'SR', 'PLATINUM', 'HYBRID (NON GCC)', 'AXL ', 'LIMITED 4X4', 'SE TRD AERO PK', 'GXR', 'SE TRD SPORT PK', 'DLS', 'GX', 'LE', 'HYBRID', 'LIMITED MID', 'LWB', 'SWB', 'A', 'VXR', 'SE+', 'E', '1500', '1.5', 'ADVENTURE', 'LX', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTD', 'MR0', 'MR2', '5TF', 'JTM', 'MRO', '2T3', '5TD', 'JT4', 'JN6', 'JTB', 'JTE', 'LFM', 'STF', '4T3', 'MHF', '1FT', 'WMA', 'JT2', '1G6', 'ITD', 'STM', '3TD', 'JTU', 'MB0', 'JT0']
  VDS: ['BW9230', 'EW12G0', 'CW6CB9', 'KW9239', 'KW9236', 'BW9233', 'KW9F31', 'KW9238', 'BW23E0', 'KW9231', 'KW9232', 'KW9D38', 'KW923X', 'KW9D35', 'KW9D33', 'KW9D34', 'DW5F14', 'BW1235', 'KW9D36', 'BW9234', 'KW9D39', 'KW9036', 'EW23E2', 'CW12G0', 'KW9D30', 'KW9234', 'KW9D31', 'DW3FV1', 'AW5F13', 'BW23E3', 'CW12G8', 'BW9232', 'KW9D3X', 'CW12G4', 'BW9238', 'DW3FV3', 'BW1336', 'KW9F32', 'EW5F19', 'KW9237', 'BW1337', 'BW9339', 'BW9237', 'BW9235', 'CW6CD1', 'CW9CDX', 'KW9235', 'KW9039', 'HW5F15', 'UW5F17', 'EW23E9', 'BW23E4', 'BW22E3', 'HW5F10', 'EW12G5', 'DW3FV4', 'BW9236', 'AW5F11', 'EW23E4', 'BW9330', 'BW1335', 'KW9233', 'KW9230', 'BW23E8', 'CW12G1', 'BW22EX', 'BW23E6', 'EW12G6', 'EW23E0', 'DW5F1X', 'BW9231', 'CW12G5', 'KW9F33', 'KW9F30', 'KW9F37', 'KW9D37', 'CW12G7', 'BW23E1', 'DW3FV7', 'BW923X', 'BW1331', 'BW22E4', 'BW1231', 'CW12G6', 'AW12G5', 'BW1332', 'BW23E9', 'EW23E7', 'BW22E1', 'EW12G1', 'RWRFV4', 'KW9D32', 'BW933X', 'KW9F39', 'EW23E8', 'CW12G3', 'BW1330', 'EW23E1', 'EW12G3', 'KW9F3X', 'AW5F16', 'EW12G9', 'UW5F1X', 'KW9F38', 'EW12G8', '8W1339', 'BW9239', 'EW12GX', 'BW3FVO', 'BW23E7', 'RWRFV0', 'KW9F35', 'CW12G2', 'DW5F12', 'EW23E5', 'AW5F19', 'BW9334', 'EW12G7', 'DW3FV9', 'EW23E3', 'BW9F38', 'BW3FV7', 'BW23E2', 'BW9333', 'BW1339', 'BW22E9', 'UW5F11', 'AW12G9', 'RW5F14', 'BW1334', 'UW5F12', 'BW23E5', 'DW5F11', 'BW23EX', 'GW5F18', 'DW5G1X', 'EW23EX', 'AW12G2', 'KW73J1', 'BW22E7', 'BW6F35', 'BW133X', 'BW3FV1', 'BW9F37', 'BW1338', 'BW22E2', 'EW12G2', 'BW9331', 'BW1333', 'DW12S1', 'CW8CD9', 'BW9F39', 'CW1262', 'CW12G9', '8W9237', 'EW12G4', 'CW12GX', 'BW1230', 'BW9337', 'BW9338', 'DW5F17', 'BW9F34', 'BW9335', 'BW9332', 'BW5F17', 'UW5F10', 'BW3FV6', 'AW12G4', 'BW3FV8', 'BW3FV9', 'BW9336', 'DW5F18', 'CW1260', 'BW9F32', 'DW3FVO', 'CW6CB5', 'BW1237', 'CW6CD6', 'BW1238', 'BW1236', 'BW22E0', 'KW9F34', 'EW23E6', 'HW5F13', 'KW9F36', 'EW12GO', 'DW5F16', 'DW5F13', 'AW5F1X', 'DW5417', 'BW22E8', 'BW3FV5', 'UW5F18', 'CW6CB7', 'CW6CB3', 'HW5F1X', 'PW5F13', 'AW5F12', 'AW12G8', 'BW6F36', 'CW6CB1', 'DW9235', 'BW6F31', 'BW5F18', 'EWRFV7', 'DW5F15', 'BW3FVX', 'BW3FV2', 'HW5F16', 'BW22E6', 'CW6CD8', 'UW5F14', 'CW8CB7', 'HW5F14', 'DW3FV0', 'HW5F18', 'RWRFV8', 'DW3FV5', 'DW3FV6', 'UW5F19', 'BW1233', 'DW3FV2', 'EW5F15', 'GW5F14', 'CW8CB3', 'DW5F10', 'HW5F11', 'BW5F11', 'HW5F19', 'BW5G18', 'EW9236', 'UW5F15', 'CW6CB4', '5WRFV2', 'AW5F17', 'BW22E5', 'BW5418', '8W9234', 'DW5F19', 'AW1269', 'BW5412', 'KW5F16', 'AW5F15', 'CW1265', 'AW12GX', 'CW1263', 'EW21A5', 'BW5F16', 'BW9F3X', 'JW30F9', 'DWSF11', 'DW541X', 'AW5F18', 'KW9032', 'JW30F1', 'DW3FVX', 'CW8CD7', 'BW123X', 'RWRFV7', 'BW0236', 'BW6F32', 'BW6F3X', 'EW41A7', '8W923X', 'BW9F36', 'CW6CD3', 'AW12G7', '8W23E6', 'RW3FV2', 'DW3FV8', 'CW6CD5', 'CW8CB9', 'DW5413', 'JW5G11', 'CW8CDX', 'KW903X', 'UWSF16', 'BW1232', 'BW5G15', '8W9231', 'BW9F30', 'RW3FV0', 'BW3FV4', 'CW6CD0', 'CW8CB0', 'CW6C88', 'AW5F10', 'CW6CB8', 'CW6CDO', 'EWIE58', 'DWRFV8', '8W9331', 'KW73J7', 'BW1234', 'EW44A6', 'BW9F31', 'MWRFV3', 'CW8CD2', 'BW9F33', 'RW3FVX', 'JW30F8', 'BW6F38', 'UW5F13', 'BW6F33', '8W9239', 'KW9F3G', 'AW12G1', 'RWRFVX', 'KW5F11', 'JW5G1X', 'CW8CB6', '8W9238', 'DW5G10', 'DWSF10', '8W1332', 'CW9CD6', 'DWRFV2', 'MWRFV2', 'AW12G6', 'BW1239', 'PW5F10', 'BW6F30', '8W9233', 'HW5F17', 'RW3FV1', 'CW6CD2', 'KW5F18', 'EW1261', 'EW44A1', 'LWRFV8', 'RWRFV1', 'DW5G19', 'EW1265', 'CW12GO', 'HW2ZZ4', 'UW5F16', 'BW5F1X', 'CW1269', 'JW30F6', '8W9232', 'CW6CB0', 'AW5F14', '8W1334', 'RWRFV6', 'RW3FV5', 'CW6CB6', 'TW5F16', 'SW21M8', 'RW3FV3', 'CW6CD7', 'KW9031', '8W1338', 'CW1261', 'JW30F7', 'BW5G16', 'DW5G17', 'BW9F43', 'EW5F11', 'RW3FV7', '8W23E4', 'BW3FV0', 'DWRFV0', 'EW1260', 'BW5F13', 'BW9F35', 'RWRFV9', 'JW30F3', '8W1233', 'DW5G15', 'BW5411', 'HW21A0', 'DW5G11', 'EW1266', 'CW6CB2', 'DW51E8', 'CW8CD4', 'RW3FV8', 'KW5F14', 'CW8CB8', 'BW12S0', 'RW3FV9', 'CW8CB4', 'KW73J3', 'CW6CD9', 'DW12S6', 'CW9CD5', 'DW5416', 'EW44A3', 'CW8CB5', 'AW12G0', 'DW5G13', 'GW5F17', 'BW3FV3', '8W1331', 'RWRFV5', 'BW5815', 'CW6CBX', 'EW1EP2', 'CW8C86', 'RWRFV2', 'CW9CB8', 'HW5F12', 'JW30F2', 'CW6C86', 'DW5410', 'BW5G17', 'RW3FV4', 'BW5F15', 'BW5413', 'AW1267', '6W9230', 'CW8CB1', 'KW9D3S', 'RWRFV3', '8W23EI', 'KW5F13', 'CW8CBX', 'CW5F12', 'CW1267', 'JW5G18', 'KW9033', 'BW6F39', 'EWRFV1', '8W133X', 'DW11S8', 'KWS236', 'BW23EA', 'CW6CDX', '8W1335', 'JW5G14', 'EW22E6', 'JW3EH0', 'BW12S8', 'JW5G10', 'BW5417', 'DW12SX', 'CW1264', '8W9F3X', 'CW6CBO', 'CW126X', 'KW71J6', '8W9230', 'CW1268', 'KW73JX', 'BW5414', 'AW12G3', 'CW8BB9', '8W9236', 'BW6F34', 'BW12S6', 'DW5G14', 'DW12S5', 'CW8CD0', 'BW5G14', '8W9235', 'HW2ZZ3', 'CW6CD4', 'EW923X', 'CW9CB2', 'KW73J8', 'RW3FV6', 'DWRFV9', 'KW8D37', 'FW12G1', 'EW5F10', 'KW5F10', 'MWRFV0', 'BW5G10', 'PW9236', 'EW21A3', 'CW8CB2', 'CW5F1X', 'CW8CD6', 'CW9CB4', 'DW11S0', 'EW44A8', 'CW5F17', 'BW5419', 'DW12S4', 'CW8CD1', 'RW5F10', 'EW1268', 'BW5F10', 'CW5F14', 'CW1266', 'MWRFV7', 'KW5F1X', 'KW73J0', 'RW5F17', '8W23E5', 'JW30F5', 'BW5G12']
  Model_Year: ['B', '8', 'G', '7', 'F', '6', '1', 'E', 'D', 'C', 'H', 'Y', '3', '9', 'A', 'N', '5', 'S', '2', 'L', '4', 'P', 'R', 'K', 'M', 'X', 'J']
  Plant_Code: ['L', '3', '0', '5', '1', 'D', 'X', '4', '2', 'W', 'S', 'Z', 'J', 'U', 'K', 'M', 'R', '9', 'P', '6']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,YARIS,4.0,HATCHBACK,B,MID,GCC,5.0,JTD,BW9230,B,L,006031
1,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,E,DLX,GCC,2.0,MR0,EW12G0,8,3,009992
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,GL,GCC,4.0,MR0,CW6CB9,G,0,001803
3,TOYOTA,YARIS,4.0,SEDAN,K,FLEET,GCC,4.0,JTD,KW9239,8,5,108974
4,TOYOTA,YARIS,4.0,SEDAN,K,FLEET,GCC,4.0,JTD,KW9236,8,5,106552
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20555,TOYOTA,YARIS,4.0,HATCHBACK,K,MID,GCC,NaN,JTD,KW9231,B,5,179240
20556,TOYOTA,TUNDRA,8.0,PICKUP,D,STD (NON GCC),NON-GCC,NaN,5TF,DW5F1X,H,X,624341
20557,TOYOTA,YARIS,4.0,SEDAN,B,MID,GCC,NaN,JTD,BW9237,C,1,225842
20558,TOYOTA,YARIS,4.0,HATCHBACK,K,MID,GCC,NaN,JTD,KW9D38,C,D,516958
20559,TOYOTA,YARIS,4.0,HATCHBACK,K,BASE,GCC,NaN,JTD,KW9D32,D,D,529593

====================================================================================================
pos5: R
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'HIACE', 'MATRIX', 'YARIS', 'ECHO', 'SIENNA', 'HILUX', 'CAMRY', 'MR2', 'LAND CRUISER PICKUP 70', 'CELICA', 'PRADO', 'LAND CRUISER', 'AVANZA', 'SELICA', 'COROLLA SEDAN', 'COROLLA 1.8', 'TOYOTA COROLLA', 'COROLLA 1.3', 'TOYOTA', 'COROLLA 1.6', '4RUNNER', 'BZ4X', 'INNOVA', 'COROLLA ']
  bodyType: ['SEDAN', 'SALOON', 'PANEL VAN', 'HATCHBACK', 'MPV', 'ESTATE', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PICK UP', 'MINI BUS', 'COUPE', 'STATION', 'VAN', 'SUV', 'BUS', 'PICKUP']
  pos4: ['B', 'E', 'Z', '8', 'K', 'D', 'F', 'U', 'A', 'N', 'H', 'Y', 'L', '3', 'X', 'J', 'R', 'S', 'G', 'T', '2', '0', 'C']
  trim: ['XLI', 'XLI MID', 'STD (NON GCC)', 'GLI TOP', 'STD', 'XLI TOP', 'GLI TOP LTH', '1.8', 'LE (NON GCC)', 'BASE', 'XLE (NON GCC)', 'GL', 'GLI', 'DLX', 'DL', 'DLS', 'SED', 'PREMIUM', 'LX', 'GXR', 'TX', 'GLX', 'TXL3', 'EXR', 'GLS', 'T', 'XLI EXECUTIVE', 'GT', 'STANDARD', 'SL', 'CAR TRIM', 'SE', '1', 'S', 'LE', 'GXR TOP', 'CE (NON GCC)', 'SR5 (NON GCC)', 'VX', 'DLX TOP', 'PRO', 'GX', 'HEV', 'XSE']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTD', 'JT4', '1NX', '2T1', 'JTC', '5TD', 'MM7', 'LFM', 'MRO', 'MR0', 'TNX', 'LWL', '1GC', 'INX', 'LTV', 'JTF', 'JTL', '2TI', '211', 'JTE', 'JT0', 'MPA', '1C8', '1C6', '5XX', 'J1D', 'JMY', 'JN8', 'JTA', 'JDT', 'STD', '1V2', 'JED', 'JTU', 'UTD']
  VDS: ['BR23E6', 'BR23E0', 'BR42E6', 'BR22E6', 'ER23E0', 'BR42E1', 'BR42E0', 'BR22E4', 'ER23EX', 'BR22E2', 'BR42EX', 'ER23E2', 'BR22E9', 'BR32EX', 'BR22E0', 'BR42E4', 'BR22E5', 'BR22E7', 'BR42E7', 'BR23E2', 'BR23E9', 'BR22E8', 'ZR1198', 'BR40E9', 'BR23E5', 'BR23E8', 'BR22E3', 'BR42E2', 'BR38E6', 'ER23E4', 'BR32E4', 'BR42E9', 'BR23E3', 'BR40E8', 'BR23EX', 'BR22E1', 'BR32E0', 'BR32E3', 'BR32E9', 'BR42E3', 'BR40E7', 'BR22EX', '8R23E5', 'ER23E8', 'BR42E5', 'BR23E4', 'BR32E2', 'BR38E8', 'BR23E7', 'BR38E0', 'BR40E4', 'BR32E7', 'KR32EX', 'ER23E7', 'KR32E6', 'KR30E1', 'ER23E6', 'ER23E9', 'ER23E5', 'DR32T9', 'BR42E8', 'BR32E8', 'BR32E6', 'BR40EX', 'BR38EX', 'ER23E1', 'BR23E1', 'FR1197', 'ER23E3', 'BR30E5', 'BR40E6', 'BRKEC5', 'BR32E5', 'BR40E3', 'BR40E2', '8R23EX', 'KR32E8', 'KRKEC5', 'BR40E1', 'ZR1199', 'KR32E9', 'UR4DA1', 'ARE0C6', 'FR22G0', 'KR32E7', 'BR32E1', 'BR12E8', 'FR22GX', 'BR30E4', 'FR22G2', 'ZR119X', 'KR32E2', 'BR28E1', 'BR30E8', 'FR22G4', 'BR38E1', 'ZR1193', 'BR40E5', 'FR22G7', 'KRKEC9', 'BR40E0', 'NRRTX4', 'HR33NX', 'BR30E1', 'BR18E5', 'BR12EX', 'ZR1196', 'BR12E5', 'BR30E7', 'FR22G5', 'FR22G6', 'BR30E3', 'ZR1192', 'ARE2C0', '8R22E9', 'YRKEC9', 'BR12E2', 'ZR1191', 'BRZ3E7', 'BR12E1', 'FR22G8', 'FR1193', 'FR1192', '8R32EX', 'BR38E3', 'FR3206', 'BR22F5', 'KR32E1', '8R23E6', '8R32E1', 'BR12E7', 'BR12E3', 'BR12E6', 'BR12E4', 'BR18E8', 'ZR1190', 'BR30E9', 'FR119X', 'BR38E2', 'ARE0C9', 'ZR1194', 'LR73J0', '8R42E5', '3R22E7', 'BR30E0', 'KRKEC3', 'FR22G1', 'ZR1195', 'LR73JX', 'BR12E0', '8R23E2', 'DR32T0', '8R23E9', 'KR32E3', 'KRKEC1', 'ER22E1', 'ARE2C6', 'ER42E2', 'FR3204', 'BR30E2', 'BR12E9', 'FR22G9', 'FR22G3', 'FR1198', 'XRKEC0', 'BR43E9', 'ZR1197', 'KR30E6', '8RI2E0', 'FR1190', 'BRKEC8', 'ARCAJ3', 'KRKECX', 'ARE0C3', 'BR30EX', 'FR73J7', 'FR1194', 'KRKEC8', 'KR32E0', 'ARE2C4', 'JRKEC1', 'BR38E9', 'YRKEC2', 'DR32T1', 'BRKEC6', '8R42E2', 'ARE2C5', 'JRKEC5', 'KRKEC2', 'ER33P0', 'YRKEC0', '8R22E4', 'BR38E5', 'XRKEC7', 'KR32E4', '8R23E0', 'ER22E6', '8R22E7', 'RR7GT2', 'YRKEC4', 'SRFJT9', 'BR4068', '8R22E2', 'DR32T8', 'ARE0C2', 'ARE2C2', 'GR4A69', '8R23E8', 'BR38E7', 'BR30E6', 'SRCSLA', '8R32E6', 'AR05Y8', 'BR23ES', 'FR2266', 'TR2CA1', 'ARE0C4', 'AR9AJ2', 'ARE0C1', 'FR2268', '8R23E1', 'KR38E0', 'LR73JO', '8R22E3', '2R1197', 'JR14T8', 'KRKEC7', '0RV430', 'KRKEC0', 'ER42E9', 'GRKEC7', 'FR1196', '8R22E6', 'CRKEC4', 'ARE0C0', 'DR32T4']
  Model_Year: ['6', '4', '9', '7', '8', '1', '3', '5', '2', 'Y', 'M', 'N', 'L', 'A', 'F', 'X', 'C', 'K', 'W', 'E', 'B', 'R', 'S', 'G', 'P', 'D']
  Plant_Code: ['0', '3', 'J', '9', '2', '7', 'Z', 'C', 'S', 'W', '5', 'L', 'B', 'O', 'K', 'F', 'H', 'N', '1', 'G', 'U']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,JTD,BR23E6,6,0,248294
1,TOYOTA,COROLLA,4.0,SEDAN,B,XLI MID,GCC,4.0,JTD,BR23E0,4,3,095410
2,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,JTD,BR42E6,9,J,007251
3,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,JTD,BR22E6,7,3,199406
4,TOYOTA,COROLLA,4.0,SEDAN,E,XLI MID,GCC,4.0,JTD,ER23E0,6,3,187410
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10324,TOYOTA,COROLLA,4.0,SEDAN,E,XLI,GCC,NaN,JTD,ER23E2,5,0,181656
10325,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,JTD,BR23EX,1,0,029184
10326,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,JTD,BR23E4,6,3,166451
10327,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,JTD,BR23E5,2,0,081369
10328,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,JTD,BR23E8,6,3,180837

====================================================================================================
pos5: U
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['FJ CRUISER', 'LAND CRUISER', 'FORTUNER', 'PRADO', 'LAND CRUISER PICK UP', 'COROLLA', 'COROLLA CROSS', 'LAND CRUISER PICKUP 70', 'FJ', 'HILUX', '4RUNNER', 'TACOMA', 'LAND CRUISER 70', 'MATRIX', 'RAV4', 'TUNDRA', '4 RUNNER', 'TOYOTA LAND CRUISER', 'LAND CRUISER PRADO', 'SCION', 'TOYOTA ALTIS', 'TOYOTA TACOMA', 'بيك اب كابينه مزدوجه', 'LAND CRUISER PICK UP CARGO', '25 LP SC4X44.0L MT', 'HD 4X4', 'TAKOMA', 'LAND CRUISER / STATION', '25 LP SC 4X4 P4.0 MT', 'PREVIA', 'CAMRY', 'RUNNER', 'TOYOTA 4RUNNER', 'TOYOTA PRADO', 'YARIS', 'HIACE', 'LAND CRUISER GX', 'LAND CRUISER/PICK UP CARGO', 'HILUX ADVENTURE', 'COROLLA 1.8', 'FORERUNNER', '1.8 XS', 'لاند كروزر', '26 LP SC 4X4 P4.0L AT', 'LAND CRUISER - PICK UP CARGO', 'COROLLA 1.3', 'GXR RA(STATION WAGON)']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'SEDAN', 'SUV- CROSSOVER', 'PICK UP SINGLE CAB', 'STATION', 'PICK UP', 'PICKUP', 'HATCHBACK', 'LIGHT VEHICLE', 'MPV', 'PICKUP DOUBLE CABIN', 'PICK UP DOUBLE CABIN', 'MINI BUS', 'COUPE', 'BUS', 'PICKUP DOUBLE CAB']
  pos4: ['B', 'H', 'Y', 'A', 'J', 'L', 'K', 'C', 'D', 'E', 'F', 'U', 'Z', 'R', 'M', '8', 'T', 'G', 'N', 'X', 'P', '2', 'I']
  trim: ['VXR', 'TOP', 'EXTREME', 'BASE', 'GXR', 'TX', 'VX', 'XLI', 'VX MID', 'EXR', 'SR5', 'S TRD SPORT PK', 'SE', 'XLI EXECUTIVE', 'GLI', 'SE+', 'LX', 'GXR TOP 60TH ANNIV. XTREME', 'STD', 'GL', 'LX AC PWR OPT', 'LX WINCH', 'TX-L', 'LIMITED', 'SC', 'XLI TOP', 'GX TOP', 'STD (NON GCC)', 'DLS', 'TX-L TOP', 'G', 'LE', 'GLS', 'GX', 'ADVENTURE', 'SAFARI', 'HT SWB', 'GXR MID', 'GXR GT', 'XL', 'PLATINUM', 'SR5 (NON GCC)', 'STD D', 'GXR TOP', 'GX MID', 'GLX', 'VX TOP LTH', 'VX1', 'GXR2', 'FJ STD', 'GXR TOP DMST', 'CTD', 'HT VXR', '1', 'GXR1', 'STD AC', 'GXR FMST', 'EX', 'DX', 'VX2', 'GXR SOD D/AC AW', 'TC (NON GCC)', 'XTREME', 'T', 'TXL2', 'GXR4', 'HARD TOP', 'SGL', '0', 'X', 'DLX', 'TRIM', 'BLACK EDITION', 'GR SPORT', 'S', 'LS', 'LUXURY', 'GXR TOP FMST', 'TXL1', 'GXR-V', 'PIKUP', 'PREMIUM', 'VXR BASE', 'PICKUP', '4WD', '60TH', 'TXL3', 'TRD SPORT', 'TRD', 'GR-S', 'LTZ', 'GXR3', 'SPORT', 'NON GCC', 'A', '6', 'GLI TOP', 'STANDARD', 'E', 'STATION1', 'EXCLUSIVE', 'GRD', 'VX-L TOP', 'PICKUP ', 'PICK UP', 'STANDER', '1500 CREWCAB SLE Z71', 'GL DECKLESS', 'TR', 'DOUBLE CABIN ', 'SEDAN', 'DLX TOP', 'GXL', 'LXI', 'GXR MID XTREME', 'DC', 'GXR MID 60TH ANNIVERSARY', 'ST', 'SR', 'DL', 'SE T2', 'SGLX', 'LE PLATINUM CITY', 'STATION', 'VXR TOP', 'SPORTS BASIC', 'GXR TOP 60TH ANNIV. ']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTE', 'JTM', 'MHF', 'JIF', 'MR1', '1NX', '2T1', 'JTD', 'RKL', '5YF', 'JTF', 'MR0', 'LFM', '5TE', '5TF', 'MHE', '3TM', 'INX', 'SYF', 'MRO', 'JTK', '5TB', 'JIM', 'JTB', '5XX', '211', 'JTL', 'YAR', 'MRI', 'MAF', 'YV2', 'LVG', '1TM']
  VDS: ['BU11F8', 'BU11F2', 'BU11F5', 'BU11FO', 'HU09J4', 'YU59G6', 'AUBBJ1', 'JU9FJ1', 'LU73J7', 'BU25J9', 'BU4EEX', 'BU25J0', 'HU09JX', 'BU11F1', 'BU3FJ5', 'YU59G2', 'AUCBJ2', 'JU3FJ3', 'BU4EE7', 'YU59G7', 'BU9FJ2', 'AUCBJ0', 'BURHE2', 'AUCBJX', 'BU4EE0', 'AUCBJ6', 'HU09J9', 'BU25J5', 'BURHE9', 'BU11F7', 'AUCBJ8', 'KUAAG7', 'BURHE1', 'YU59G0', 'BU3FJX', 'YU59GX', 'BURHE8', 'HU09J1', 'BU11F9', 'BUSFS1', 'HU09J6', 'BU11F0', 'BU4EE1', 'HU09J7', 'BU40E7', 'LU73J5', 'BU8FS1', 'KU8FSX', 'LU73J4', 'LU73J9', 'HU09J0', 'AUCBJO', 'BU&CD4', 'BU3FJ6', 'BU25J2', 'LU73JX', 'HU01J4', 'AUCBJ7', 'BU5JR8', 'BU9FJ5', 'BURHE5', 'LU73J2', 'AUCBJ9', 'BU3FJ0', 'JU9FJ4', 'BU4EE3', 'KU8FS7', 'JU3FJ2', 'BU11FX', 'AUBBJ2', 'CU1BR6', 'BU3FJ9', 'BU8CD2', 'BU25J6', 'BURHE0', 'HU09J2', 'BU4EE4', 'LU73J1', 'AUBBJ0', 'DU09J6', 'BU9FJ6', 'BU3FJ4', 'DU09J3', 'AU7BJ7', 'BU3FJ1', 'JU9FJ9', 'BU11F4', 'BU9FJ3', 'BU3FJ3', 'HU01JX', 'LU42N7', 'AU7BJ4', 'BU8FS5', 'KU8FS8', 'LU73J0', 'BU5JR0', 'BU11F6', 'KUAAG6', 'HU8CD0', 'HU01J5', 'JU9FJ8', 'BU8FS2', 'BU25J1', 'DU09J9', 'YU59G9', 'BU25J4', 'JU3FJ6', 'BU4EE2', 'AUBBJ4', 'BU25JX', 'LU73J6', 'JU9FJ6', 'HU09J5', 'HU01J1', 'HU09J8', 'BU25J8', 'EU73J6', 'LU73J3', 'FU71J2', 'AU7BJ0', 'BU9FJ1', 'BU5JR2', 'JU9FJX', 'BU8CD0', 'UU4EN4', 'BURHE7', 'AU7BJX', 'HU8CD1', 'AU25J2', 'HU01J6', 'JU9FJ5', 'BU25J3', 'KU8FS9', 'HU01J8', 'HU01J0', 'BURHE3', 'BU9FJ9', 'BU11F3', 'AUBBJ7', 'AU25J6', 'BU8FS3', 'KUBAG5', 'BU40E5', 'BU3FJ7', 'YU59G5', 'BU3FJ8', 'BURHE4', 'LU71JX', 'BU40E8', 'YU59G3', 'JU3FJX', 'KU8FS1', 'BURHE6', 'AUBBJ3', 'AU25J7', 'ZU14R4', 'KU8FS2', 'HU01J2', 'AUBBJ5', 'KU8FSO', 'AUCBJ3', 'BU9FJ7', 'AUCBJ1', 'BU4EE8', 'BU4EE9', 'AUBBJ6', 'AU25J5', 'HU01J7', 'KUBFS2', 'JU3FJ9', 'BU3FJ2', 'BUT1F9', 'BU9FJX', 'JU9FJ7', 'HU01J3', 'JU3FJ1', 'HU09J3', 'BU4EE5', 'HU0935', 'KU8FS4', 'KUBAGX', 'AU25JX', 'BU4EE6', 'FU71J8', 'JU9FJ0', 'KU4EE7', 'DU09J5', 'YU59G8', 'ZU14R7', 'BU4BF2', 'AU7BJ9', 'KUBAG6', 'BU8FS8', 'YU59G1', 'AU25J1', 'AU7BJ1', 'BU40E0', 'FU71J7', 'BU8CD4', 'BURHEO', 'BU40E2', 'BU25J7', 'AU7BJ8', 'LU4ENX', 'BU8CD5', 'LU71J1', 'BU8CD6', 'BU9FJ8', 'JU3FJ4', 'BU5JR4', 'AU7BJO', 'BURHEX', 'AU7BJ2', 'CU1BR1', 'BU14RX', 'AUCBJ5', 'BU8CD7', 'KUBAG1', 'FU71J3', 'KU8FS0', 'JU5213', 'BU40E9', 'AUBBJ9', 'AU25J9', 'BU40E4', 'LU73J8', 'AUCBJ4', 'BU8FSX', 'AU88JX', 'KUBAG4', 'BU8FS9', 'FU73J5', 'AU25J4', 'AU7BJ5', 'BU8CD1', 'KU8FS3', 'KU8FS5', 'ZU14R8', 'ZU14R1', 'AUBBJ8', 'JU9FJ3', 'YU59G4', 'JU9FJ2', 'KUBAG2', 'BU2539', 'BU5JR9', 'DU09JX', 'BU11JX', 'BU40E6', 'KU8FS6', 'AU7BJ6', 'BU8CDO', 'BU9FJ0', 'DU09J0', 'BU8FS0', 'AU7BJ3', 'BU4BF8', 'BU8CD9', 'HU0932', 'JU3FJ5', 'RU5JR9', 'AUBBJX', 'HU8CD4', 'EU73J2', 'BU9FJ4', 'ZU14R5', 'KUBAG7', 'JU3FJ7', 'MU4FNX', 'AU25J3', 'BU4BF0', 'BU8FS4', 'BU40E3', 'BUIIF9', 'BU8FS7', 'HU01J9', 'HU0938', 'RU71J9', 'BU4BF9', 'MU4FN1', 'MU4FN3', 'AU25J0', 'LU71J4', 'CU1BR0', 'KUBAG9', 'DU09J2', 'BU5JR3', 'BU3FJO', 'BU9FJO', 'BU4BF6', 'JU3FJ8', 'FU71J1', 'BU8CDX', 'LU4EN4', 'FU73J3', 'BU4BF1', 'LU71J8', 'BU71JX', 'ZU5JR7', 'ZU5JR4', 'EU73J5', 'KU5BF6', '8U4EE6', 'KU5BF5', 'LU71J6', 'BUSFS9', 'CU1BR4', 'BU40EX', 'LU5212', 'BU71J4', '8U11F6', 'CU1BRX', 'HU0936', 'LU71J3', 'YU5965', 'JU3FJ0', 'KU104X', 'BU5JRX', 'CU1BR3', 'RU3417', 'BU3AE5', 'BU4BF7', 'LU4EN9', 'BU2532', 'AU25J8', 'AUBBJO', 'HU8CD7', '8U3FJ4', 'BU14R0', 'BU40E1', 'FU73J6', 'DU09J8', 'BURHET', 'ZU11F1', 'ZU14R6', 'BU5JR7', 'FU71J4', 'BU8CD3', 'AUTBJ4', 'ZU14RX', 'BU4BF4', 'JU3FJO', 'HU8CD3', 'MU4FN8', 'KUBAG0', '8U4EE4', 'BU71J6', 'BU17R1', 'BU71J1', 'FU71J5', 'RU71J5', 'RU5JR7', 'FU71J6', 'CU1BR2', 'BU8FSO', 'BU8FS6', 'KU40E3', 'CU1BR5', 'BUTTF4', 'ZU14R2', 'UU4EN3', 'LU42N2', 'LU5218', 'BU2538', 'UU4EN0', '8U3FJ8', 'KU72N2', 'JU9FJO', 'ZU17R2', 'KU4EE8', 'ZU11F2', 'ZU5JR3', 'EU73JX', 'BUSFS7', 'AUCBJG', 'KUBAGO', 'KUBAG8', 'FU71J0', 'HU8CD6', 'CU09JX', 'DU09J1', 'JU8FJ2', 'HU01JO', 'JUNFJ4', 'LU71J2', 'CU1BR9', 'BU4EET', 'DU09J4', '8URHE9', 'CU1BR8', 'KU5JR3', 'ZU11FX', '8U40E6', 'BUTTF1', 'BU71J7', 'ZU5JR9', 'RU5410', '8U4EE7', 'BU8CD8', 'HU0939', '8U8CD2', '8U4EEX', 'RU3413', 'BUSFS4', 'KUAAG1', 'MU4FN5', 'AUCBJS', 'LU4EN7', 'KUBAG3', 'KUAAG3', 'KUAAGB', 'HU0930', 'ZU5JR0', 'FU73J1', 'TU4GN7', 'YU5963', 'YU5967', 'ZU11F3', 'UU5JRX', 'JU4GN1', 'UU42NX', 'FU73JX', 'LU71J9', 'BU14R9', 'LU521X', 'ZU5JR6', 'MU52N0', 'EU11F1', 'FU71J9', 'FU73J2', 'BU29J0', 'KU40E4', 'BU4BF5', 'LU71J5', 'BU14R1', 'BU17R8', 'BUBFSX', 'HU8CDX', 'FU5JR5', 'ZU14R0', 'AU88J0', 'JU3FJS', 'BU5JR5', 'ZU14R3', 'BU14R3', 'EU73J0', 'HU5JR1', 'BU2535', 'BU14R8', 'LU5JR8', 'FU73J9', 'CU1BR7', 'LU5F16', 'BUL1F1', '8U11F9', 'BU5JR6', 'MU52N8', 'JU5212', 'ZU17R0', 'LU71J7', 'LU7331', 'BUBFS4', 'CU09J7', 'JU9FJB', 'JU9FJS', 'BU14R4', 'GU09J9', 'NU5JR3', 'NU5JR2', '8U3FJ3', 'ZU17R8', 'FU5JR1', 'KUAAG9', '8U11F2', 'LU4EN2', '8U3FJX', 'KU5BF9', 'BU3FJI', 'BU71J5', 'AU7BJI', 'FU73J8', 'GU4L3X', 'DU09J7', 'RU3419', 'MU52N9', 'AU78J8', 'JU3211', '8U11F7', '8U11F1', 'HU09JO', 'JU62N9', 'MU52N4', '8U8CD9', 'GU09JX', 'BU71J2', 'BU71J0', 'BU2534', 'LU5216', 'FU71JX', 'NU5JR9', 'BU4BFX', 'LU71J0', 'KUAAG8', 'KUAAG4', 'BU5JR1', 'YU5964', 'ZU5JR5', 'BU14R2', 'FU73J4', 'ZU17R9', 'HU0937', 'BU4BF3', 'BUSFSX', 'UU4EN1', 'BU26J7', 'KU8F52', 'LU4EN1', 'LU42N5', 'BU01F7', 'BU4EEJ', '8U11F8', 'KUAAGX', 'JU03J2', 'BUSFS5', 'KU5BF0', 'BUSFS6', 'JU03J3', 'AUBBJS', 'ZU4BF5', 'HUD9J8', 'ZU11F9', 'ZU5JR2', 'BUSFJS', 'BUBFSB', '8U3FJ6', 'BUBFS9', 'BUSFS8', '8U4EE9', '8U4EE2', 'HU8CD2', 'RU5JR0', 'KU4HN3', 'AU88J2', 'KU4EE5', 'BU3FJS', 'ZU17R3', '8U11F0', 'UU4EN5', 'KU40EX', 'JU3FJB', 'XU9HM0', 'JU9EJ4', 'KUSFST', 'LU42NX', 'HU08J0', 'EU11F0', 'YU5908', 'UU4ENG', 'KUBFS9', 'KU5JR4', 'DU09T3', 'KUAAG5', '8U11FX', 'HU0933', 'BU11FG', 'FU73J7', 'BU4EES', 'BU17R7', 'LU4EN0', 'MU4FN9', 'JU9FJI', 'UU5JR3', 'JU5219', 'BUBFS1', 'TU62N8', 'BUJFJ7', 'MU4FN7', 'ZU17R6', 'BU17R0', 'ZU14R9', 'BU2536', 'UU4EN6', 'AUZBJ7', '8U11F3', 'RU3418', 'YU5F17', 'BU25JT', 'BU14R6', 'UU42N1', '8U3FJ1', 'AUF0A9', 'BU71J9', 'AUBB38', 'HU0931', 'BU11FS', 'KU8FSG', 'HU09JI', 'BUSFJ7', 'KUBFS5', 'HU8CD9', 'MU5JR8', 'BU3EJ5', 'NU5F10', 'BUSCD1', 'JU9FI0', 'YU5969', 'RU541X', 'LU42N6', 'KU8F58', 'JU9F10', 'JU03J7', 'BU14R7', 'LU5213', 'BU17R4', 'FU73J0', 'NU5JR1', 'ZU11F5', 'MU4FN2', 'CU9237', 'RU71J3', 'LU5F18', '8U5CD1', 'HU0912', 'KU8F5X', 'AU78JX', 'HU0917', 'BU5JRO', 'HU0914', 'UU5JR5', 'BURNE3', 'BU11FB', 'JU03J5', 'AU88J9', 'BURHES', 'BU8F59', 'BUTTF7', '8U25JX', 'EU3FJ1', 'YU5968', 'AU7BJT', 'CU18R8', 'HUD3J2', 'AUBBJB', 'EU5JR1', 'UU4ENX', 'KU40E7', 'LU42N9', 'JUGFJ3', 'KU5BF8', '8U3FJ5', '8U11F4', 'BUSFJ4', 'ZU11F7', 'BU11FV', 'JU3218', 'BU5IFB', 'RU3416', 'LU5JR5', 'LU73JO', 'AUBBJN', 'LU4EN8', 'TU22N1', 'KU8F55', 'PU5JR6', '2U14RX', 'JU62NX', 'HU8CD8', 'BU2589', 'BU2509', 'CU09J8', 'BU3FJB', 'HUD9J6', 'HU8CD5', 'LU7334', 'AU88J6', 'AUCBJA', 'UU42N9', 'HUOTJI', 'MU4FN6', 'JU9EJ2', 'JU03J6', 'PU5JRX', 'CU09J5', 'BU11E6', 'BU9FJS', 'IUSFI6', '8U3FJ9', 'BUJFJ4', 'LU4EN3', 'AU7BJS', 'PU5JR3', 'BUSFS2', 'BU4EED', '8U4EE5', 'KU4EE9', 'LU5F14', 'BU9FJJ', 'EU73J9', '8U40E4', '8U71J6', 'RU71J8', '8U4EE0', 'ZU5JR8', 'KUBFSX', 'LU4EN5', 'JU09J0', 'JU03J0', 'MU5JR5', 'BUTIFI', 'HU0919', '8URHE5', 'GU09J1']
  Model_Year: ['E', 'C', '8', 'A', 'F', 'R', 'D', 'K', '4', '6', '7', '9', 'B', 'G', 'J', 'P', 'S', 'H', 'N', 'M', 'L', 'T', '3', '5', '1']
  Plant_Code: ['K', '5', '7', '4', 'B', '0', 'Z', 'C', 'J', 'P', '8', 'X', '9', 'M', 'F', '6', '3', 'S', '2', 'O', 'G', 'A']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,FJ CRUISER,6.0,SUV,B,VXR,GCC,5.0,JTE,BU11F8,E,K,180180
1,TOYOTA,FJ CRUISER,6.0,SUV,B,TOP,GCC,NaN,JTE,BU11F8,E,K,195990
2,TOYOTA,FJ CRUISER,6.0,SUV,B,EXTREME,GCC,NaN,JTE,BU11F2,C,K,126452
3,TOYOTA,FJ CRUISER,6.0,SUV,B,BASE,GCC,5.0,JTE,BU11F5,8,K,045095
4,TOYOTA,FJ CRUISER,6.0,SUV,B,EXTREME,GCC,5.0,JTE,BU11FO,C,K,146845
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23439,TOYOTA,FORTUNER,6.0,SUV,B,VXR,GCC,NaN,MHF,BU8FS2,R,0,039310
23440,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AU7BJ9,P,4,030611
23441,TOYOTA,LAND CRUISER PRADO,6.0,SUV,B,GXR,GCC,NaN,JTE,BU3FJ6,G,5,072697
23442,TOYOTA,COROLLA CROSS,4.0,SUV,K,XL,GCC,NaN,RKL,KUBAG0,R,0,504648
23443,TOYOTA,HILUX,6.0,PICKUP,H,GLX,GCC,NaN,MR0,HU8CDX,K,0,071134

====================================================================================================
pos5: D
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'PREVIA', 'PRIUS', 'CAMRY', 'COROLLA', 'HILUX', 'AVALON', 'CROWN KLUGER', 'JUSTIN BIEBER X VESPA 150 E5 GSO (SCOOTER)', 'TACOMA', 'HIGHLANDER', 'RUMION', 'COASTER', 'RAV 4', 'SUPRA', 'VIOS', 'LAND CRUISER', 'MODEL 2022', 'HIACE', 'LAND CRUISER PICK UP', 'CAMRY HYBRID']
  bodyType: ['SUV', 'MPV', 'HATCHBACK', 'SEDAN', 'PICK UP DOUBLE CAB', 'BUS', 'PICK UP SINGLE CAB', 'COUPE', 'PANEL VAN', 'MINI BUS', 'PICK UP', 'STATION', 'PICKUP']
  pos4: ['H', 'B', 'G', 'K', 'Z', '5', 'V', '8', 'M', 'R', 'J', '6', 'D', 'N', 'S', 'F', 'E', 'Y', 'L', 'A', 'T']
  trim: ['FABRIC', 'BASE', 'DLX', 'STD (NON GCC)', 'GL', 'S', 'MID', 'SE', 'GLI', 'EXR', 'PW CL', 'XLE', 'C (NON GCC)', 'LE', 'GL2', 'SE+', 'LIMITED PREMIUM', 'XLE TOURING', 'XLI', 'SR5 (NON GCC)', 'GLX SPORT Z', 'LWB', 'STD', 'GXR', 'DL', 'ECO', 'ICONIC', 'GLE', 'DYNAMIC', 'EX', 'GLE HEV BLACK EDITION', 'LIMITED', 'DLS', 'EXECUTIVE', 'STD  (NON GCC)', 'DX', 'LIMITED HEV', 'GL LTH', 'TOP', 'ADVENTURE', 'TOP LTH', 'GLX', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTE', 'JTM', 'JTD', '4T1', 'JT4', 'ZAP', 'MA1', 'LFM', '3TY', 'KMJ', '3N6', 'JN6', 'JM3', '5TD', 'MNT', 'JHD', 'LPS', '1C6', 'KNC', 'VR3', 'L3H', 'JT2', 'MDH', '2HN', '454', 'RKT', 'SAL', 'UTD', 'LK6', '1N6', 'LSY', 'LZY', 'JJ7', 'LVG', 'JTV', 'UTM', 'JTN']
  VDS: ['HD20V5', 'BD31V3', 'BD31V4', 'GD34M6', 'KDTB35', 'GD52M9', 'BD31V6', 'BD1FK0', 'BD31V5', 'BD1FK4', 'BD31V2', 'GD34M0', 'BD31V7', 'BD33V1', 'GD52M2', 'BD1FK8', 'GD52M8', 'BDMHE2', 'BD33V4', 'ZD33V1', 'BD31VX', 'GD32M5', 'BD33V8', 'BD33V3', 'BD31V0', 'GD52M4', 'GD54M8', 'BD33V0', '5D3BV4', 'BD1FK6', 'KDTB30', 'BD31V1', 'HD20V4', 'GD32M1', 'GD32M7', 'BD32V9', 'VD10A2', 'BD33V9', 'GD54M6', 'BD1FK9', 'GD54M9', 'GD52MX', 'HD20V0', 'BD31V8', 'GD32MX', 'BD31V9', 'GD54M1', 'ZD33V3', 'ZD31V7', 'GD34M2', 'BD33V6', 'GD54M5', 'HD20V3', 'BD33V5', 'BD1FK7', 'BD35V1', 'GD52M6', 'ZD33V0', 'BD1FK2', 'GD20V5', 'GD52M0', 'BD1FK5', 'BD1EB6', 'BD1EB9', 'GD54MX', '8D31V8', 'BD1EB2', 'KDTB38', 'GD32M8', 'GD52M3', 'GD32M4', 'GD34M4', 'KDTB37', 'GD32M2', 'ZD33V4', 'BD35V4', 'GD20V2', 'BD33V2', '8D33V2', 'MD3502', 'GD32M6', 'HD20V8', 'RD2VF2', 'KDTB34', 'GD52M1', 'KDTB31', 'GD34M9', 'HD20V6', 'JD7BN2', 'ZD32V9', 'ZD32V2', 'GD20V1', 'BD1FKX', 'BD1FK1', '8D31V4', 'KDTB32', 'KDTB33', 'GD54M7', 'GD54M0', 'GD32M3', 'BD33VX', 'KDTB39', 'BD35V2', 'ZD33V7', 'BD1FK3', 'BD1EB4', 'GD20V8', 'GD54M3', 'BD35V9', 'GD34M3', 'ZD33V8', 'BD33V7', 'GD54M4', 'GD20V7', 'GD52M7', 'BD1EB7', '5D3BV9', 'ZD32V6', 'HD20V9', 'ZD31V9', '6D32M9', 'MD1218', 'GD34M8', 'GD34M1', 'ZD33V5', 'GD52M5', '8D1FK5', 'KDTB3X', 'KD5HN5', 'GD54M2', 'BD1EB3', 'JDAHNX', 'GD20V9', 'ZD32V8', 'DD21A7', 'ND22S0', '8D31V3', '8D31V7', 'GD32M9', 'GD34MX', 'GD32M0', '8D31V1', 'HD17F2', 'DD2EY5', 'GD20V0', 'HD23S2', 'BD32V2', 'ZD33V2', 'SD35E5', 'GD20V3', 'BD1EB8', 'KDRBH2', 'DD23S0', 'ZD33V6', 'KDTB36', 'BDOES4', 'ZD31V5', '6D52M5', 'BD1EB1', 'BD32V5', 'GD34M7', 'BD1FKO', 'BD1EB5', 'HD20VX', '5D3BV7', 'ZD31V2', '8D33V0', 'KDRAH6', 'HD20V1', 'FD3HLS', 'ZD33VX', '8D31V5', 'ED3KA5', 'BD32V6', 'RD7KT4', 'SD0110', '8D31V0', '8D35E5', 'ZD35V4', '8D31V9', 'MD3501', '8D33V7', 'BD1EB0', 'BD1EBO', '8D33VX', 'SD35E9', 'KDRAHO', 'VD10A4', 'ED9HP2', 'ZD31V3', 'HD17FP', 'JD7BN5', 'GD20VX', 'GD20V6', 'MD3524', 'MD3512', 'FDABB8', 'BD3173', 'ZD33V9', '5D3BV2', 'BD35V6', 'SD35E4', 'DD82A3', 'BD0FA4', 'GD34M5', 'HD17F6', 'BD1EBX', 'KDRBH8', 'BD1FKA', 'HD20V7', 'ZD31VX', 'YD2828', '5DDDDD', 'RD4830', 'LDHAD8', 'ZD32V0', 'GD21A3', '5D3BV8', 'BD32VX', 'ADAE2X', 'HD17F9', 'HD17FX', 'HD20V2', '8D31VX', 'BD0CT6', '8D31V2', 'HDAAA1', 'ND22S2', 'ED1EK2', 'TDTD69', 'BDF1J0', 'BD23S3', '8D31V6', 'SD911X', 'BD32V1', '5D3BV5', 'BDIEBX', 'HD17F5', 'GD20V4', 'DD22S5', '6D54M7', 'EDABB3', 'BD74K6', 'JD7BN8', 'ZD35V3', 'HD21A8', 'BD3175', 'BD32V4', 'ZD31V0', 'ZD31V6', 'BD35V0', '6D32M1', 'FDA882', 'FDAB82', 'KDRBH6', 'MD1212', 'BD31VK', 'MD3517', '8D33V6', 'EDABB8', 'BD3371', 'ZD32VX', '6D52M2', 'BD32V8', 'KDRAH9', 'KDRAH8', 'BD32V7', 'BD32V3', 'HD17F1', 'KDRAH3', 'ED31V4', '8D33V8', '8D1FK2', 'BD1FKI', 'VD11E8']
  Model_Year: ['5', 'C', '8', '7', 'H', '3', '9', 'S', '2', '6', 'A', 'B', 'T', 'E', 'P', '4', 'D', 'G', 'F', 'J', 'X', 'W', 'K', 'L', 'N', 'R', 'V', '1']
  Plant_Code: ['0', '5', '1', 'A', 'U', '7', '3', 'D', '6', 'P', '2', 'T', 'J', 'C', 'K', 'X', 'S', 'L', 'G', 'H', 'F', 'B', 'N']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,RAV4,4.0,SUV,H,FABRIC,GCC,5.0,JTE,HD20V5,5,0,062401
1,TOYOTA,RAV4,4.0,SUV,B,BASE,GCC,5.0,JTM,BD31V3,C,5,287141
2,TOYOTA,RAV4,4.0,SUV,B,BASE,GCC,5.0,JTM,BD31V4,8,5,125820
3,TOYOTA,PREVIA,4.0,MPV,G,DLX,GCC,5.0,JTE,GD34M6,5,0,301201
4,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),GCC,5.0,JTD,KDTB35,C,1,503530
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4070,TOYOTA,RAV4,4.0,SUV,B,BASE,GCC,NaN,JTM,BD31V8,6,5,020601
4071,TOYOTA,RAV4,4.0,SUV,B,MID,GCC,NaN,JTM,BD33V0,9,5,230613
4072,TOYOTA,PREVIA,4.0,SUV,G,GL,NON-GCC,NaN,JTE,GD52M5,7,0,027880
4073,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,SE,GCC,NaN,4T1,BD1FK1,H,U,222848
4074,TOYOTA,RAV4,4.0,SUV,B,MID,GCC,NaN,JTM,BD33V9,9,5,216807

====================================================================================================
pos5: F
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'CAMRY', 'RAV4', 'RUSH', 'AVANZA', 'TOYOTA CAMRY', 'CROWN', 'AVALON', 'LITEACE', 'ZELAS', 'HILUX', 'SCION', 'RAV 4', 'SIENNA', 'SALOON', 'DAINA', 'HIACE', 'DYNA', 'HIGHLANDER', 'COROLLA', 'SUPRA', 'PRADO', 'C-HR', '1998', 'LAND CRUISER', 'FLHTK', '26 YA HB P 1.6L AT TURBO GR RA(CAR)', 'كامرى', 'SPINA', 'LITE ACE', 'PICKUP', 'TOYOTA RUSH', 'DYNA VAN CARGO', 'SOLARA', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'MPV', 'SALOON', 'PANEL VAN', 'VAN', 'COUPE', 'PICK UP DOUBLE CAB', 'HATCHBACK', 'CARGO VAN', 'PICK UP SINGLE CAB', 'PICKUP', 'STATION', 'COUPE/CABRIOLET', 'MOTORCYCLE', 'TRUCK', 'CONVERTIBLE']
  pos4: ['B', 'R', 'E', 'M', 'Z', 'D', 'W', 'A', 'Y', 'J', 'U', 'N', '8', 'K', '2', 'C', 'T', '9', '7', 'H', 'S', 'F', 'G', '1']
  trim: ['E', 'GL', 'S', 'LE', 'GXR', 'SE+', 'SE', 'EX', 'VXR', 'GRANDE', 'LIMITED', 'VX', 'BASE', 'STD', 'GX', 'GLX', 'XLE', 'STD (NON GCC)', 'EXR', 'XLE (NON GCC)', 'G', 'GLX SPORT Z', 'PLATINUM', 'XLI', 'GLE', 'MID', 'BE', 'DLX', 'YX', 'GLI', 'SPORT', 'XLE HEV', 'T', 'Y PLUS', 'GR', 'TC (NON GCC)', 'GLS', 'LE (NON GCC)', 'STANDARD', 'DX', 'PICKUP', 'GLE HEV', 'GLI TOP', 'STD CARGO', 'DLS', 'GR BLUE EDITION', 'PW CL', 'GL DECKLESS', 'GLX PREMIUM', 'XL', 'EXCLUSIVE', 'MPV', 'S TRD AERO PK', 'SGLX', 'DL', 'TRIM', 'YA', '60TH', '1', 'Y']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MR2', '6T1', '4T1', 'JTN', 'JTM', 'MHK', 'JTD', '2T3', '4T4', 'JT2', 'JTK', 'JHG', 'JT0', '213', '4T3', '2T1', 'LEF', 'KPD', 'LVG', 'JTH', 'LJN', 'WAU', '5T1', 'VF3', 'JHF', 'WDD', '6TT', 'JD2', '4TI', 'ZFC', 'LFM', '55S', 'LM6', 'JTJ', 'JHH', '671', '471', 'LHP', 'KMH', 'NMT', 'ST1', 'JYM', '5HD', 'ZT3', '611', 'L3A', '4T0', 'JTC', 'LFB', 'W1K', '474', 'YSM', 'LET']
  VDS: ['BF9C35', 'BF9FK1', 'BF9FK9', 'BF3EK0', 'BF9HK0', 'RF9EV1', 'BF4FK3', 'BF1FK2', 'EF8BF4', 'MF53F3', 'BF1FK6', 'ZF9EV4', 'EF8BF2', 'BF3EK8', 'DF4EV3', 'BF32K5', 'EF8BF5', 'EF8BF8', 'BF32K2', 'BF9FK3', 'BF9FK7', 'BF3EK7', 'BF4FK8', 'BF9FK6', 'BF9FK0', 'ZFREV8', 'BF9FK4', 'BF1FK9', 'BF4HK2', 'BF4DVX', 'WF9EV2', 'EF8BF3', 'BF4HK8', 'BF1FK3', 'BF4HK7', 'DF9EV0', 'AFAAF1', 'BF9FKX', 'BF28B6', 'BF4HK1', 'BF1FKX', 'BF32K1', 'BF38K9', 'BF3EK5', 'RF9EV5', 'ZFREV4', 'DF9EV2', 'BF9FK2', 'ZF9EV6', 'BF1FK0', 'EF8CF1', 'DF9EV3', 'EF8CF7', 'BF9FK5', 'BF4FKX', 'MF53F1', 'ZF4DV3', 'RFREV8', 'BF9EV9', 'RFR3V8', 'BF1FK7', 'DF9EV8', 'MF5CF1', 'BF3EK2', 'DF9EVX', 'BF8C30', 'BF9FK8', 'WF9EV7', 'BF9EV2', 'EF8BF1', 'BF9C34', 'RF9EV9', 'BF3EK9', 'RFREVX', 'EF8BF9', 'BF9EV5', 'MF5BF7', 'MF53F8', 'BF4FK2', 'DF9EV6', 'BF1FK1', 'BF4FK7', 'BF9HK9', 'BF4DV6', 'EF8BFX', 'MF53F4', 'BF32K3', 'DF4EV8', 'WFREV0', 'BF9HK5', 'BF4FK9', 'BF4FK4', 'BF4FK1', 'AFAAF0', 'BF32K9', 'RF9EV8', 'BFREV3', 'RF9EV3', 'RF9EV2', 'BF9HK8', 'WF9EV6', 'BF9C32', 'MF52F5', 'EF8CF2', 'BF4FK5', 'BF32K8', 'MF53F5', 'BF1FK5', 'WFREVX', 'RF9EVX', 'MF5BF4', 'BF28B9', 'BF32K7', 'BF1FK4', 'YFREVX', 'BF4DV3', 'BF4HK6', 'MF53F9', 'BF32K4', 'BF4DV9', 'BF9C31', 'DF4EV5', 'DF4EV4', 'BF31F9', 'BF9EV3', 'BF30K8', 'DF4EV7', 'BF31F3', 'BF9EV0', 'BF3EK1', 'DFREV7', 'DFREVX', 'WF9EV0', 'BF31V8', 'BF31F8', 'ZFREV9', 'WF9EV4', 'WF9EV9', 'DF4EV6', 'BF38K2', 'WFREV6', 'BF3EK4', 'EF8CFX', 'ZF9EV8', 'BF30KX', 'BF9HK4', 'BF4FK6', 'BF38K5', 'EF8CF8', 'EF8BF7', 'DF4EV1', 'DF4EV9', 'MF5BF5', 'MF52F0', 'MF53F2', 'BF9C30', 'ZF9EV5', 'MF52F2', 'BF9EV7', 'BF22K8', 'EF8BF6', 'DF9EV5', 'BF4HK4', 'MF53F7', 'BF28B0', 'MF5CF3', 'BF1FK8', 'BF4HKX', 'EF8BF0', 'BF22K6', 'BF4DV5', 'BF8C3X', 'MF5CF2', 'BF28KX', 'WF9EV1', 'JF5C71', 'DF4EVX', 'BF9C33', 'BF9HK7', 'ZF9EV3', 'ZF9EV9', 'DFREV9', 'BF30K6', 'ZF9EVX', 'BF4DV4', 'BF4HK3', 'BF22K5', 'BF31F4', 'BF9C3X', 'BF9C39', 'AFAAF4', 'BF4FK0', 'BF3EK3', 'ZF9EV0', 'BF9HKX', 'BF8C39', 'JF4DV5', 'BF9HK6', 'BF8C34', 'DFREV5', 'BF3EKX', 'DFREV6', 'ZF9EV7', 'BF9C36', 'MF5CF9', 'DFREV2', 'EF8CF3', 'JF4DV0', 'BF30K0', 'BF9HK2', 'BF30K4', 'EF8CF4', 'BF8C37', 'BF32K6', 'BF38K7', 'ZF33V6', 'MFSCF3', 'BF4HK5', 'BF4HK0', 'BF33V9', 'UF1170', 'BF3EK6', 'BF9EV8', 'ZF33V4', 'EF8CF9', 'DF4EV0', 'DFREV4', 'RFREV1', 'BFREV1', 'DF4DV7', 'EFHCF1', 'WFREV3', 'MF53F0', 'BF30K1', 'MF5BFX', 'JF5C7X', 'DF4EV2', 'MF5CF5', 'MF53F6', 'BF4DV8', 'YFREV3', 'NFREVX', 'WF9EV8', '8F22K4', 'BF22K3', 'ZF9EVO', 'MF5BF3', 'BF28B4', 'JFREV5', '8F1FK0', 'BF8C35', 'AFAAF7', 'BF32KX', 'BFREV8', 'YF4DV7', 'RFREV9', 'BF38K3', 'BF9EV6', 'BF38K0', 'RFREV4', 'WF9EV5', 'EF8BFO', 'WFREV7', 'AFAAF6', 'RFREV5', 'BFREV9', 'BF30K7', 'WFREV5', 'EF8CF0', '8F30K1', 'DF9EV1', 'BF4DV1', 'MF5CF4', 'BF9FKB', 'BF9EV1', 'BF31F7', 'JF5C77', 'BF9EVI', 'DF9EV4', 'BF9FKO', 'BF9C37', 'RF9EV4', 'BF46KX', 'DF9EV9', 'MF5BF9', 'RFREV3', 'ZF9EV2', 'ZF4DV8', 'RFREV2', 'BF31FX', 'MF52F4', 'BF38K6', 'JF5C74', 'BF4HKO', 'BF28B7', 'BF22K1', 'DF4DVX', 'BF8C31', 'MF52F8', 'AFAAF5', 'BF30K9', 'BF9HKO', 'BF4DV7', 'MF5CF7', 'YFREV2', 'BF31F6', 'WF9EV3', 'DFREV1', 'ZFREV5', 'BF38KX', 'BF38K4', 'ZFREV6', 'DF9EV7', 'BF22K9', 'BF9EVX', 'BF12K4', 'BFREVX', 'BFREV4', '8F1FK3', 'BF28B3', 'WFREV2', 'ZF9EV1', 'BFREV7', 'YFREV5', 'RF9EV7', 'BF38K8', 'JF5C78', 'BF8C36', 'BF9EV4', 'WFREV1', 'MF5CFX', 'JF5C75', 'BF8C32', 'EF9FK8', 'BF30K2', 'MF5BF2', 'EF8CF6', 'MF53FO', 'BF28K5', 'BF30K3', 'RFREVI', '8F9FK4', 'MF5CF0', 'BF33V7', 'RFREV6', 'EF8BFZ', 'WF9EVX', 'BF4HKB', 'BF30K5', 'BF8C33', 'YF4EV3', 'EF8CF5', 'BFREV6', 'BF28B5', 'ZFREVX', 'MFSCF0', 'MF5BF0', 'BF8C38', 'MF5BF1', 'BF9C38', 'ZF4DV5', 'ZFREV7', 'BF4HK9', 'ZFREV3', 'KF4DV3', '8F9FK7', 'AF4E31', 'ZFREV2', 'BF31F1', 'YFREV6', 'ZFREV0', 'RFREV0', 'BF9HKS', 'WFREV4', '8F1FKX', 'ZF4DVX', 'BF32V0', 'BF3EKO', 'JF5C79', 'BF9HK3', '2FREV0', 'BF22K0', 'JF5C76', 'ZF4DV4', 'YF4EV4', 'BFREV5', 'ZF4DV7', 'BF32K0', 'ZF4DV0', 'YFREV1', 'DF4DV4', 'MF53FX', 'BF28K8', 'MF5CF6', 'BF38K1', 'JF5C70', 'YFREV0', 'NFREV6', 'ZF33V1', 'MF52F7', 'BF4DV2', 'NFREV7', '8F4HKX', '8F1FK7', 'WF4DV6', 'WFREV8', 'MF52F3', 'WFREV9', 'DF4DV1', 'MF52F9', 'ZF4DV6', 'JFREV0', 'DFREV0', '8F1FK2', 'MF5CF8', 'BFREV2', 'DF4DV8', 'BF9HKB', 'BF33V6', 'YF4DV9', 'BF1FKO', 'NFREV8', '2F9EV5', 'MF5BF6', 'BF31F5', 'BF4DV0', 'BF9HK1', 'BF28BX', 'BFREVO', 'YFREV8', 'BF28B8', 'MF52FX', 'RF4DV5', '2F9EV4', 'RFREV7', 'AFAAF2', 'DF4DV6', 'MFSBF7', 'EF8BFI', 'ZF13C8', 'BF22K7', 'BFIFK3', '8F4HK7', 'BF28K2', 'AFAAF9', 'ZF31V6', 'RF9EV0', 'DF4DV9', 'MFSCF6', 'ZFREV1', 'BF31V2', 'MF5CFO', 'DF9EVO', 'BF28K1', 'BF33V0', 'BF28K9', 'WF9EVO', '8F32K6', '8F9FKX', 'ZFREVO', 'BF12K0', '8F3EK1', 'CF28P3', 'EF88F5', 'AFCG23', 'DF4DV0', 'BF22K4', 'BF3EKS', 'ZF4DV1', 'EF8CFO', 'DF4DV2', 'BF22K2', 'BF33V4', 'EF12K3', '8F9HK9', 'NFREV4', '8F9FK9', 'JF5C72', 'AFAAF8', 'BF31F2', 'RF4DVX', 'BF33V1', 'ZF4DV9', '8F1FK9', 'UF117X', 'BF28K7', 'MF52F6', 'WF4DVX', 'WFREVS', 'DF4DV3', 'ZF4DV2', 'KFDNN1', 'BF33V2', 'DFREV8', 'BF28B2', 'BF28B1', 'ZF19C6', 'EF76A0', 'RF4DV7', 'RF9EVO', 'BF4HKC', 'ZF9EVS', 'ZF13C3', 'RF4DV6', 'BF5C29', 'UF1171', 'AFAAF3', 'ZF33V5', 'BF3EKB', 'YF4DV2', 'ZF35V1', 'EFBBF7', '2F9EV9', 'TFUC57', 'BF6C3X', 'TFUC51', 'TFUC5X', 'TFUC50', 'YF4EV8', '9FD8TX', '8F3EKX', 'MF53FI', '8F4FKX', 'BF33VX', 'BF28K4', 'AFCG24', 'BFREVI', '8F3EK3', '7FNFU8', 'WFREVO', 'YFREV4', 'MF5BFO', 'DFREV3', 'UF11H3', 'BFREV0', '8F4HK9', 'UF11H6', 'BF4FKO', '8F3EK8', 'ZF4CBX', '2F9EV1', 'BF31F0', '8F4DV0', 'ZF33V2', 'YF9EV1', '8F32K7', 'YF9EVX', 'YFREV7', 'JFREV1', '8F30KX', 'TFU2K0', 'RF4DV3', 'BF18B6', 'JF5C73', 'JF4DVX', 'ZF33V9', 'MF52F1', '8F30K7', 'AFAAFX', 'WF4DV9', '2FREV8', 'MF9290', 'EF88F2', '8FREV1', '8F9FK0', '8F9HK4', 'MF5BF8', 'RF9EV6', '8F3EK7', 'ZF19C5', 'AFZBG2', 'ZF19C9', 'DF4EVO', '8F9FK8', 'BF9FRX', 'BFIFKI', '8F9HK2', '8F9HKX', '8F9FK6', 'EF88F0', '2F33V5', '8FIFK9', '8F9FK2', 'AF54K3', 'EF9FK1', 'ZF9EVG', 'BF32V2', 'JF4DV7', 'YF4EV5', 'BF31V9', 'KF4DVX', 'WF8HB3', 'JFREV6', 'AFABF9', 'YF4DVX', 'ZF35V4', 'WF4DV7', 'BF22KX', 'HF10U7', 'BF12B1', 'YF4DV1', '8F9FK5', 'NFREV5', '8F30K0', 'CF22PX', 'BF31V7', 'NFREV1', 'DF4EB5', 'BF28K6', 'BF28K0', 'MFSCF7', 'EF76A1', 'BF35V5', 'BF31E6', 'YFREV9', '8F31FX', '8F1FK5', '8F9C30', '8F1FK4', 'MF9291', 'BF33V5', 'UFJ1H4', 'DFREVO', 'NFREV9', 'KF4DV6', 'BF9EVO', 'EFBCF8', 'BF28K3', 'BF33V3', 'SFABD9', 'ZF13C2', '8F9FK1', 'ZF31V2', 'CF28P8', 'EF8CFS', 'ZF13C0', 'KF4DV1', 'WF4CB8', 'FF41CB', 'EFBCF1', 'BF31V5', 'BF31FO', 'BF12K5', '8F3EK4', 'WF4DV8', 'RF4DV0', 'UF1176', 'BF9JE8', 'BF3FK3', 'ZF13C4', 'JFREV3', 'BF18B8', 'BF31EX', 'UF11H0', 'BF9FKZ', 'BF9FKG', 'EFBBF4', 'BF12B7', '8F9FK3', '2F9EV7', 'EF4HKD', 'ZF13C1', 'GF4JB6', '1FHPC6', 'EF9FK7', 'EFSBF6', 'EF9FK6', 'BF1FKI', 'WF4DV2', 'MF5BFI', 'AF4E34', '8F1FK6', 'DF4EUX', 'ZF13CX', 'DF9EVI', 'BF33V8', 'EF12K7', 'EFBBF5', 'BF12B4', 'DF4DV5', 'EF88F3', '2FREV2', 'EFABF0', '8F4FK8', 'YF4DV5', 'BF31E9', 'KFNM3X', 'BF18B7', '8F3EK0', 'UF1179', '8F9C35', 'RF4DV1', 'MF5CFI', 'ZFREVI', 'KF4DV5', 'BF23K7', 'AF4E36', 'BFTFK0', 'KF4DV8', '8F38K0', '2F9EV6', 'ZF31V9', 'EF8BFS', 'FF7193', 'JF4DV1', 'AFAAFO', 'GF46X1', '1F0091', 'ZF33V8', 'BF31V1', 'ZF9EVI', 'AF4CB8', '8F30K4', 'WF4JB1', 'EFAVS3', 'BF35V4', 'UFJ173', 'EF88F7', 'UFJ175', 'JF4DV3', 'BF1FKS', 'AFCG28', 'WF9EVB', 'YFAG20', '8FREV7', 'EF88F9', '8F1FK1', 'BF9FKI', '8F9EV4', 'BF32X6', 'EFSBF9', '2F9EV0', 'ZF31V0', '8F28K8', 'JF4DV6', 'YF4DV0', 'BF18B5', 'DFAEV9', 'EFBBF3', '8F3EK6', '2FREV9', 'EFBC38', 'BF1FKZ', '8F9EV0', 'NFREV2', '8F4HK0', 'MF9297', 'ZFREVS', 'JFSC78', 'EF8C31', 'FF22P8', 'ZF33VX', 'BF4DVS', 'MFWBY5', '2FREV7', 'ZF13C7', 'AF047X', 'BF23K9']
  Model_Year: ['T', 'H', 'D', 'B', 'K', 'G', 'P', 'F', 'J', '3', 'M', 'E', 'C', 'L', 'A', 'N', '1', '2', '4', '5', '6', 'R', '9', 'V', 'Y', 'W', 'X', '8', 'S', '7']
  Plant_Code: ['0', 'X', 'U', '3', 'D', 'K', 'J', 'W', 'R', '5', 'A', 'V', 'C', 'H', '1', 'P', 'G', 'N', '6', 'S', '9', 'Z', '8', 'Y', 'F', '2', 'L']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,YARIS,4.0,SEDAN,B,E,GCC,4.0,MR2,BF9C35,T,0,094830
1,TOYOTA,CAMRY,4.0,SEDAN,B,GL,GCC,4.0,6T1,BF9FK1,H,X,678621
2,TOYOTA,CAMRY,4.0,SEDAN,B,S,GCC,4.0,6T1,BF9FK9,D,X,449176
3,TOYOTA,CAMRY,4.0,SEDAN,B,LE,GCC,4.0,4T1,BF3EK0,B,U,749116
4,TOYOTA,CAMRY,4.0,SEDAN,B,LE,GCC,4.0,JTN,BF9HK0,K,3,022031
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22881,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,SE,GCC,NaN,6T1,BF9FK9,G,X,644859
22882,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,S,GCC,NaN,6T1,BF9FK5,D,X,425747
22883,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,SE,GCC,NaN,JTN,BF4HK6,J,3,014100
22884,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,S,GCC,NaN,6T1,BF9FK4,D,X,474261
22885,TOYOTA,AVANZA,4.0,SUV,M,SE,GCC,NaN,MHK,MF5CF0,L,K,009941

====================================================================================================
pos5: E
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'PREVIA', 'RAV4', 'HILUX', 'COROLLA', 'HIACE', 'AURION', 'COASTER', 'YARIS', 'ALPHARD', 'CROWN', 'LAND CRUISER', 'STATION', 'SALOON', 'SCION', 'SICION', 'VELOZ', 'AVANZA', 'TUNDRA', 'TACOMA', 'RAV 4', 'PRADO', 'VENZA', 'SIENNA', 'TOYOTA CAMRY', 'CELICA', 'CAMRY SOLARA', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'MPV', 'SUV', 'PICK UP DOUBLE CAB', 'MINI BUS', 'PANEL VAN', 'MINI BUS HIGH ROOF', 'BUS', 'CARGO VAN', 'PICK UP SINGLE CAB', 'STATION', 'COUPE', 'SALOON', 'PICKUP', 'PANEL VAN HIGH ROOF', 'WINDOW VAN', 'HATCHBACK']
  pos4: ['B', 'G', 'R', '8', 'A', 'D', 'C', 'Z', 'P', 'F', 'S', 'X', '6', 'T', 'K', 'E', '7', 'M', 'H', 'W', '2', '1', 'N']
  trim: ['XLI', 'GLX', 'LE', 'GLI', 'SE', 'GL', 'DLX', 'BASE', 'EXR', 'EX', 'S', 'XLI EXECUTIVE', 'DX', 'STD', 'MID', 'DL', 'X', 'BUS', 'XLE (NON GCC)', 'DLS - STD ROOF', 'YX', 'STD (NON GCC)', 'TOURING', 'SL', 'GLE', 'XLI TOP', 'PLATINUM', 'GRANDE', 'GXR', 'DLS', 'XLI EXECUTIVE MR', 'CABRIO', 'Y PLUS', 'GLS', 'GLI HEV', 'SR', 'BE', 'SR5 (NON GCC)', 'GLI TOP', 'EXCLUSIVE', 'VXR', 'ADVENTURE 1ST EDITION', 'LE HEV', 'A', 'GLX SPORT Z', 'ADVENTURE', '40 TFSI S-LINE', 'GLI TOP LTH', 'LIMITED', 'SV', 'EX MID', 'GX', 'LWB HIGH ROOF', '4', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['6T1', '4T1', 'JTD', 'JTN', '4T4', 'JTM', '8T1', 'KMF', 'JNB', 'JT2', 'JN6', '1NX', '2T1', '6TI', 'LVG', '4TI', '4TT', '411', 'JTG', '5T1', 'KNC', 'MR2', '1FD', 'ITN', 'LRR', '611', 'GT1', 'JTF', 'LFM', 'JN8', 'JTL', 'SCR', 'JT4', 'JTK', 'LET', 'MHF', 'VF3', 'MHK', 'JHM', 'LGD', 'LEF', 'SMV', '6T0', '471', 'BT1', '8LT', '671', 'IN6', '4T3', '1G6', '6TB', 'RKL', 'ST1', 'ET1', '3T1']
  VDS: ['BE32K4', 'BE42K7', 'BE32KX', 'BE42K3', 'BE32K3', 'BE42K8', 'BE42K6', 'BE42K0', 'BE42K9', 'BE33K8', 'BE32K9', 'BE32K1', 'BE30K8', 'GE52M3', 'BE42K1', 'BE42K4', 'GE52M7', 'BE46K5', 'BE32K0', 'BE33K5', 'BE42K2', 'BE46K4', 'BE33K6', 'BE32K7', 'BE46K2', 'BE42KX', 'BE46K6', 'BE32K8', 'BE46K9', 'REREV2', 'BE42K5', 'BE32K5', 'BE30K6', 'BE32K2', 'GE52M0', 'BE30K4', 'BE30K0', 'BE30KX', 'BE46K7', 'BE33K4', 'BE46K8', 'BE46KX', 'BE32K6', 'BE33K0', 'BE46K0', 'GE52M6', 'GE52MX', '8E32K9', 'GE17FX', 'BE30K2', 'BE30K5', 'GE52M5', 'GE52M2', 'BE46K3', 'BE33K9', 'BE30K1', 'BE30K3', 'GE52M4', 'BE30K7', 'GE52M1', 'GE52M8', 'BE33K1', 'BE46K1', 'BE36KX', 'BE33K3', 'AE09V9', 'BE33K2', 'AE54S5', 'GE52M9', '8E32KX', 'AE00B6', 'DE32K0', 'BE4EE1', 'BE30K9', 'BE6DS9', 'BE40K1', 'AE52SX', 'AE00B7', 'CE38P0', 'BE33K7', 'BE6BS3', 'AE09B3', '8E32K3', '8E46K7', 'BE6BS4', 'BE6BS8', 'CECB89', 'AE04B7', 'BE4EE0', '8E32K6', 'BE3EK9', 'AE09V6', 'AE09B5', 'GE52MO', 'AE09B7', 'BE6BS9', 'AE04B3', 'AE04B2', 'BE33KX', 'ZE32V2', 'AE04B8', 'BE6AS2', 'AE09B0', 'AE09B4', 'PE32K6', 'BE6BS6', 'FE52S4', 'SE0142', 'BE9B30', '8E32K7', 'AE52S1', 'AE09B2', 'FE7187', '8E32K1', 'XE4FS9', '6E52M1', 'AE00E5', 'AE04B9', 'AE04B4', 'AEACH7', 'CECB85', 'FE53S5', '6E52M0', '8E32K8', 'AE00B1', 'BE40K2', 'TEKP1X', 'AE04B6', 'BE6DS4', 'AE04B0', 'AE00EX', 'BE42J8', 'AE82G3', 'AE04B1', 'BE6DSX', 'BE42KB', 'AE52S6', 'AE5256', 'BE42KO', 'CE38P9', '8E32K4', 'BE6DS6', 'AE09W0', 'DE6261', 'BE85B9', 'AE2KP8', 'AE09BX', 'BE24K8', 'KE50E2', '8E32K5', 'BECEK7', 'AE51S4', 'AE09V4', 'AE00E6', 'AE09EX', 'TEB3NX', 'EE4263', 'AE54S0', 'DE626X', 'AE09B8', 'AE09E2', 'AE54S7', 'DE1675', 'AE04B5', 'DE6269', 'AECG27', 'BE40K3', '8E30K9', 'FE54S4', 'BE6CS7', '8E42K5', 'AE53S2', 'BE38K1', 'FE7280', 'ZE32V7', '8E30K7', 'SE0342', 'ZE32V0', 'ZE4FE1', 'AE1BYE', 'BE6BSX', 'AE09B6', 'AE09V3', 'BE6DS2', '8E33K1', '8E30K3', '8E42KX', '7ENFUZ', '6E52M2', 'AECB83', '8E46K2', 'ME53F3', 'BE32KG', 'EE4261', 'ZE32V3', '6E52M4', 'BE42KS', 'XE4FSX', 'BE6AS5', 'AE09V0', 'AE09V7', 'AE04E8', '8E32K2', 'AE52S0', 'AE09B9', 'AE00B5', 'BE3EK7', 'BE3EK5', 'AECB80', 'BE6DS3', 'ZE2870', 'BE4GK3', 'BE6DS5', 'AE04E1', 'AE09W2', 'CECB81', 'EE4260', 'AE09V2', 'HEJ1F0', '8E32K0', '8E42K3', 'AECG33', 'BE6DS7', 'AE00B3', 'DE4EV6', 'FE53S2', '8E42K0', 'AE09W8', '8E42K1', 'ZER2DG', 'BE6BS2', 'BE42KT', 'FE7189', 'BE32KS', 'AE52S5', '8E46K6', '6E52M3', 'AE00E3', 'BE6DS0', 'AE09E6', 'AE04E9', 'WE23EX', 'AE94K3', 'BE32KT', '8E46K3', 'AE09E9', 'FE52S8', '8E46K0', '8E33K2', '8E46K9', 'BE9FK9', 'AEAA16', 'AE09B1', 'BE6BS7', 'BE23K4', 'FE52S5', 'AECB89', 'FE52S6', 'BE6DS8', '2EFV4M', 'AECB82', 'AE51S0', 'AE52S3', 'BE6DS1', '8E30K2', 'AE09W3', 'AE04BX', 'AEACH0', 'ZE9EV1', 'AE07B9', 'BE3EK3', 'ZE11A4', '8E46KX', 'FE52SX', 'BE3EKX', 'AE09E4', 'KE52YX', '1E33K0', 'BE40E8', 'NE4261', 'BE9FK7', 'AE52S7', 'BE32KO', '8E42K6', '8E33K6', 'CE38P1', 'FE54S3', 'AE00E1', 'AE09W5', '7ENFU8', 'AE09VX', 'BE44K1', 'BE42KZ', '8E30K6', 'BE6BS5', 'GES2M2', '8E42K8', 'EE9HE6', 'BE9FK0', 'BE23K3', 'AE00E7', 'WE3FN2', '7ENFU9', '8E42K9', 'ZE4FE7', 'BE23K5', '8E42K7', 'AE94A8', 'BE9B33', 'PE30K1', 'ZE4FEX', 'DE82A0', 'BE40E4', '6E52M8', 'BE23K8', 'EE32K0', 'AE54S1', 'AE09E7', 'BE6AS6', '6E52M7', 'AE04E6', 'BE9HEX', 'GE52MB', 'CE22P4', '8E30K4', 'GE52MI', 'GES2M5', '8E42K4', 'CECB82', 'AECB85', 'BE40EX', 'AECB84', 'AE1EYX', '8E30KX', 'AE04BZ', 'EE32KX', 'FE7284', 'EE4269', '8E42K2', '8E30K0', 'FE22P3', 'FE7186', 'AE09WX', 'AE09V8', 'BE3EKZ', '8E30K8']
  Model_Year: ['5', '6', '8', 'A', '4', 'B', '3', 'J', '9', '7', '2', 'E', 'D', 'H', 'F', 'K', 'C', 'G', 'L', 'R', 'S', 'M', 'P', 'T', 'V', '1', 'X', 'N']
  Plant_Code: ['X', 'U', '0', '7', 'A', 'R', 'D', '3', 'C', 'Z', '9', 'G', '6', '5', 'K', '8', '2', 'W', '1', 'H', 'J', 'S', '4', 'V']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,GCC,4.0,6T1,BE32K4,5,X,483890
1,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,GCC,4.0,6T1,BE32K4,6,X,532054
2,TOYOTA,CAMRY,4.0,SEDAN,B,GLX,GCC,4.0,6T1,BE42K7,8,X,485384
3,TOYOTA,CAMRY,4.0,SEDAN,B,LE,GCC,4.0,4T1,BE32KX,5,U,099822
4,TOYOTA,CAMRY,4.0,SEDAN,B,GLI,GCC,4.0,6T1,BE42K3,A,X,627686
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27662,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,GLX,GCC,NaN,6T1,BE42K1,8,X,469665
27663,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,GLI,GCC,NaN,6T1,BE42K1,B,X,679514
27664,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,XLI,GCC,NaN,4T1,BE32K8,6,U,721335
27665,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,1,GCC,NaN,6T1,BE32K7,6,X,544408
27666,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,GLI,GCC,NaN,6T1,BE32K8,6,X,538813

====================================================================================================
pos5: Z
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'CAMRY', 'COASTER', 'SIENNA', 'C-HR', 'TACOMA', 'TOYOTA CAMRY', 'AVALON', 'HILUX', 'HIGHLANDER', 'FJ CRUISER', 'ALPHARD', 'INNOVA', 'TUNDRA', 'HAI LUX', 'TAKOMA', 'SENA VAN PASSENGER', 'YARIS', 'COROLLA LI', 'COROLLA 1.6/SEDAN', 'FORTUNER', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'BUS', 'MPV', 'SUV', 'PICK UP DOUBLE CAB', 'SALOON', 'PICK UP SINGLE CAB', 'PICK UP', 'LIGHT VEHICLE', 'PICK UP DOUBLE CABIN', 'PICKUP', 'STATION']
  pos4: ['B', 'F', 'K', 'C', 'X', 'D', 'Y', 'E', 'A', 'G', 'Z', 'S', 'H', 'J', 'R', '8', 'U', '1', 'L', 'N']
  trim: ['XLI', 'SE+ ANNIVERSARY EDITION', 'STD', 'SPORT', 'XLE (NON GCC)', 'VX', 'SR5 (NON GCC)', 'SE', 'GLE-X HEV 40TH ANNIV', 'LE STD', 'SE+', 'XSE (NON GCC)', 'S PLUS', 'S', 'LIMITED', 'XLE TOURING', '40TH ANNIVERSARY EDITION', 'DLX', 'LE', 'LE (NON GCC)', 'GX', 'XLE', 'GXR', 'GLE HEV', 'TRD', 'PLATINUM', 'LIMITED (NON GCC)', 'DLS', 'LE HEV', 'LUMIERE HEV', 'LIMITED PREMIUM', 'STANDER', 'GL', 'GLE', 'STD (NON GCC)', 'TOURING', 'GF', 'PICK UP', 'STANDARD', 'XLI TOP', 'E', 'CAR TRIM', 'A', 'MPV', 'GLI', '1500', 'EXR', 'GRANDE HEV 40TH ANNIV', 'VXR', '40TH ANNIVERSARY EDI', 'SE+ ANNIVERSARY EDIT']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['RKL', 'JTN', 'JTC', 'JTD', '5TD', 'NMT', '3TM', '4T1', '5TF', 'JTF', '3TY', 'JT4', 'JN1', 'JRN', 'ZGU', 'JNC', 'MHF', 'STY', '5HD', '25T', 'STD']
  VDS: ['BZ42E7', 'BZ4HK6', 'FZ4182', 'BZ4HK8', 'BZ42E0', 'BZ42EX', 'KZ3DC2', 'KZ4BX5', 'BZ42E9', 'BZ4HK7', 'CZ5AN5', 'KZ4BX7', 'BZ42E6', 'BZ4HKX', 'XZ3DC8', 'BZ4HK9', 'BZ42E4', 'KZ1AK9', 'BZ42E3', 'BZ4HK5', 'BZ4HK1', 'KZ4BX3', 'CZ5AN1', 'BZ42E8', 'BZ4HK4', 'BZ4HK0', 'BZ42E5', 'KZ4BX9', 'KZ4BX0', 'DZ5BN6', 'KZ4BX6', 'KZ4BX8', 'DZ5BN2', 'YZ3DC4', 'BZ4HK2', 'KZ1AK2', 'YZ3DCX', 'BZ42E1', 'BZ1FB3', 'BZ42E2', 'BZ1FBO', 'BZ4HK3', 'YZ3DC1', 'YZ3DC9', 'EZ4261', 'BZ1FB5', 'BZ4HKO', 'KZ3DC4', 'YZ3DC6', 'DZ5BNX', 'BZ1FB0', 'KZ6265', 'KZ3DC1', 'BZ1FB1', 'EZ4969', 'KZ4BX1', 'KZ4BX2', 'CZ5AN4', 'KZ3DC9', 'AZ4966', 'BZ1FBX', 'GZRBH0', 'BZAHKX', 'CZ5AN8', 'BZ1FB7', 'ZZRFH2', 'SZ5AN1', 'HZRBH1', 'KZ3DC0', 'ZZ3DC5', 'BZ1FB2', 'KZ3DC8', 'DZ3DC1', 'BZ1FB8', 'JZ3DC2', 'BZ1FB9', 'FZRBH4', 'AZ1FBX', 'KZ3DC6', 'BZ1FB4', 'BZ1FBS', 'YZ3DC7', 'DZRBH8', 'KZ4BX4', 'DZ5BN9', 'JZ3DC6', 'JZRFHX', 'BZAHK1', 'YZ3DC0', 'YZ3DC5', 'BZ1FB6', 'GZ5AN4', 'KZ3DC7', 'JZ3DC0', 'JZ3DC4', 'GZ3DHX', 'KZ4BXX', 'KZ3DC3', 'JZ3DC1', 'EZ4967', 'YZ3DC2', 'EZ4963', 'BZ1HK0', 'EZ4962', 'CZ5AN3', 'XZ3DCT', 'BZ1HK6', 'DZRFH9', 'DZ5BN4', 'ZZ3DCX', 'GZRBH1', 'AZ5CN7', 'EZ4267', 'AZ4961', 'EZ4966', 'YZ3DC3', 'BZAHK4', 'DZ3DC4', 'DZ6266', 'DZ3DC2', 'CZ5AN9', 'HZ14S6', 'DZ3DCX', 'ZZRAH4', 'KZ6268', 'JZ1FB8', 'XZ3DC2', 'KZ1AK5', 'BZ1HK7', 'CZ5AN7', 'DZ3DC9', 'KZ3DC5', 'BZAHK0', 'DZRBH7', 'EZ4269', 'ZZ3DC4', 'SZ5ANX', 'CZ5AN6', 'ZZRAHX', 'FZ1FB4', 'BZRFH6', 'DZ3DC8', 'CZ5ANX', 'YZ3DC8', 'KZ1AK3', 'EZ4960', 'AZ5CN2', 'GZRBH6', 'BZ4ZEX', 'ZZRFH1', 'JZ3DC7', 'DZ5BN1', 'RZ5CN0', 'GZ1FB0', 'JZ1FB4', 'GZRAH6', 'DZ3DC5', 'DZ6262', 'JZRFH1', 'EZ42E9', 'JZ3DCX', 'JZRFH2', 'EZ4964', 'AZ4964', 'CZ5ANO', 'CZ5AN0', 'YZRAH5', 'KZ3DCX', 'KZ6264', 'DZ5BN0', 'DZSBNO', 'GZRAH4', 'KZ4DX1', 'ZZ3DC3', 'AZ496X', 'ZZRFH0', 'ZZ3DC6', 'AZ5CN8', 'KZA006', 'ZZ3DC2', 'KZ6262', 'EZ4968', 'GZ5AN6', 'XZ3DCX', 'BZ42EZ', 'ZZRFH7', 'GZRAH9', 'DZ6260', 'BZAHK9', 'GZ5AN2', 'AZ1FB2', '8Z4HK3', 'BZAHK7', 'GZ3DH5', 'KZ6263', 'HZ04S2', 'GZRBH9', 'ZZ3DC0', 'SZ5AN8', 'KZ4BXO', 'BZAHK2', 'DZ5BN3', 'XZ3DC4', 'FZ1FB5', 'CZ5AN2', 'GZRBH4', 'JZ3DC9', 'HZRBH0', 'UZD1H4', 'GZ3DH4', 'DZ5BN5', 'EZ496X', 'DZ1FB1', 'AZ4965', 'XZ3DC7', 'DZ3DC7', 'GZ3DH6', 'AZ1FB9', 'XZ3DC0', 'EZ4965', 'KZ6260', '8Z4HK2', 'DZ626X', 'DZ6269', 'DZ6263', 'BZ9F3X', 'BZ1HK5', 'BZ42F1', 'KZ6266', 'AZ4968', 'CZRAH7', 'GZRBH2', 'GZRBH8', 'DZRBH4', 'BZ1HK4', 'EZ4961', 'GZ5AN3', 'SZ5AN5', 'AZ4967', 'JZ3DC3', 'GZ3DH2', 'SZ5AN6', 'SZ5AN9', 'YZRFH1', 'KZABX8', 'BZ1HK1', 'AZ4963', 'JZ1FB3', 'ZZRAH5', 'BZ1HKX', 'ZZ3DC7', 'ZZ3DC1', 'FZRBH2', 'KZ1AK4', 'ZZRAH9', '1ZH159', 'LZRBHX', 'AZ4969', 'DZK23C', 'AZ4960', 'XZ3DC9', 'FZRBH5', 'DZ3DC3', 'DZ5BN7', 'BZ1HK3', 'BZ1HK2', 'GZ5AN8', 'EZ4262', 'AZ5CNO', 'AZ5CN0', 'ZZ3DC9', 'GZ3DH3', 'BZ4HKS', 'DZ5BN8', 'YZRFH0', 'SZ5AN0', 'BZ4HKB', 'SZ5AN3', 'EZ3DC6', 'GZRBH3', 'CZRAH0', 'SZ5ANZ', 'NZ1AK4', 'FZ1FB3', 'ZZ3DC8', 'KZ626X', 'GZRBHX', 'AZ5CN5', 'KZRFH4']
  Model_Year: ['A', 'R', 'X', 'K', '8', 'L', 'M', 'P', '9', 'H', 'N', '1', 'J', 'Y', 'G', 'E', 'D', '3']
  Plant_Code: ['7', '3', '0', '9', 'J', 'S', 'R', 'M', 'U', 'X', 'T', '2', '8', '5', 'A']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,RKL,BZ42E7,A,7,502840
1,TOYOTA,CAMRY,6.0,SEDAN,B,SE+ ANNIVERSARY EDITION,GCC,4.0,JTN,BZ4HK6,R,3,035774
2,TOYOTA,COASTER,6.0,BUS,F,STD,GCC,2.0,JTC,FZ4182,X,0,005419
3,TOYOTA,CAMRY,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK8,K,3,010509
4,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,JTD,BZ42E0,8,9,002479
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7043,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SE,GCC,NaN,JTN,BZ4HKX,R,3,035003
7044,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK1,K,3,007600
7045,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK0,P,3,029451
7046,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK2,R,3,034380
7047,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK1,P,3,026798

====================================================================================================
pos5: V
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TUNDRA', 'COROLLA', 'COROLLA 1.6', 'LAND CRUISER PICKUP 70', 'LAND CRUISER', 'RAV4', 'HIACE', 'LAND CRUISER PICK UP', 'HILUX', 'RAV 4', 'CAMRY', 'YARIS']
  bodyType: ['PICK UP DOUBLE CAB', 'SEDAN', 'SALOON', 'PICK UP SINGLE CAB', 'SUV', 'PANEL VAN', 'PICK UP', 'STATION', 'PICKUP', 'AMBULANCE', 'COUPE', 'HATCHBACK']
  pos4: ['M', 'B', 'D', 'L', 'K', '8', 'J', 'T', 'H', 'R', 'E', 'U', 'C', 'S', 'F', 'P', 'A']
  trim: ['STD (NON GCC)', 'XLI', 'XLI TOP', 'XLI MID', 'SALOON', 'SC', 'GX', 'BASE', 'GL', 'VXR', 'EXR', 'STD AC', 'VX', 'DLX', 'VXR TOP', 'SAFARI', 'SPORT', 'LX', 'GXR', 'GLI', 'FLEET', 'COMFORT', 'SU', 'GLI TOP', '10TH VICTORY EDITION', 'STD', 'GLE', 'PREMIUM', 'TRIM', 'MID', 'BLACK EDITION', 'SE T2', 'GR-S', 'GXR TOP DMST', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TF', 'RKL', '5TB', 'JTF', 'STB', 'LFM', 'JD4', 'STF', 'JTM', '1D7', 'JTD', 'JTE', '5T8', '5NF', 'JNK', '3D7', '2D4', 'MRO', '1HG', 'ZCF']
  VDS: ['MV5215', 'BV42E8', 'BV42E6', 'BV42E1', 'BV42E7', 'BV42E0', 'DV5415', 'BV42E3', 'BV42E5', 'BV5416', 'LV73J7', 'BV42E2', 'BV5412', 'DV5419', 'BV42E9', 'BV42EX', 'BV5410', 'BV5417', 'KV5212', 'DV5416', '8V71J4', 'BV42E4', 'DV5815', 'JV36F2', 'TV1828', 'KV5210', 'DV5412', 'BV5818', 'DV5816', 'BV5819', 'BV5419', 'HV01J3', '8V42E6', 'BV5814', 'DV541X', 'DV5417', '8V42EX', 'BV5414', 'JV36FX', 'RV5417', 'KV5213', 'BV5418', 'BV5415', 'JV03J9', 'DV5818', 'BV5411', 'KV5215', '8V42E9', 'BV71J0', 'DV5817', 'EV5418', 'BV541X', 'DV581X', 'KV5211', 'HV01J2', 'BV5413', 'MV5219', 'DV5813', 'KV5217', 'KV521X', 'DV5811', 'HV09J8', 'RV71J6', 'KV5214', 'DV5810', 'JV03J7', 'DV5418', 'RV5415', 'TV1929', '8V42E8', 'HV09J2', 'HV09J0', 'HV01J4', 'UV1822', 'RV5413', 'KV36F1', 'HV09JX', 'JV5217', '8V42E0', 'RV1GP9', 'JV5214', 'BV42ES', 'BV5810', 'RV5814', 'BV5813', 'CV5414', 'LV73J9', 'MV5214', 'EV5415', 'RV5418', 'DV5413', 'BV5816', 'SV541X', 'BV581X', 'BV5812', 'BV5811', 'DV5414', 'BV71J9', '8V42E4', 'CV5412', 'HV01J9', 'MV521X', 'MV5212', 'HV01J5', 'RV42E5', '8V42E2', 'HV01J0', '8V42E7', 'EV5411', 'HV09J3', 'BV42EI', 'JV5210', 'BV71J8', 'BV71J1', 'DV5819', 'EV73JX', 'HV01J1', 'BV5815', 'JV03J0', 'KV5216', 'DV5410', 'CV5416', 'HV01J6', '8V5414', 'JV03JX', 'BV5817', 'HV01J7', 'KV5218', 'RV5815', 'RV71JX', 'HV01JX', 'KV30F8', 'DV5812', 'LV73J1', 'HV09J1', 'KV30F7', 'TV092X', 'CV5417', 'SV5413', '8V5418', 'KV5219', 'UV1825', 'JV03J5', '8V42E5', 'RV71J4', 'JV5219', 'RV5416', 'BV42EO', 'RV5414', 'BV61E5', 'BV4260', 'JV03J8', 'LV73J6', 'KV30F3', 'KV30F9', 'DV5411', 'CV5415', 'JV1ET2', 'BVV133', '8V42E1', 'JV5218', 'KV32F9', 'CV5418', 'MV5211', 'RV5411', 'KV30F2', 'FV47V6', 'BVV923', 'KV30F1', 'PV42E2', 'KV30FX', 'HV09J7', 'CV12G9', 'LV73J5', 'LV73JX', 'RV71J1', 'AVV5F1', 'EV73J1', 'JV5216', 'EV5819', 'LV73J4', 'RV5819', 'RV5412', 'TV0823', 'CV1F40', 'UV1826', 'JV5213', 'RV541X', 'DV5814', 'LV73J8', 'RV5813', 'LV73JO', 'CV5411', 'RV71J9', 'JV5211', 'EV5815', '8V5416', 'RV71J5', 'HV09J9', 'CV52B4', 'HV01J8', 'CV541X', 'RV5419', '8V5412', 'LV71J9', 'BV71J4', 'BV71JX', 'DV09J4', 'HV09J6', 'CV5410', 'EV5419', '8V42E3', 'MV5213', 'RV5410', 'LV5211', 'JV521X', 'KV30F0', 'MV5216', 'RV71J0']
  Model_Year: ['9', 'C', 'B', '8', 'D', '7', 'N', 'K', 'H', 'M', 'R', '1', 'E', 'A', 'P', 'G', 'L', 'J', 'F', '5', '3', 'X']
  Plant_Code: ['X', '4', 'S', 'B', '8', '0', '1', '5', '7', 'F', '9', 'M', 'G', 'J', 'H', 'A']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,M,STD (NON GCC),GCC,4.0,5TF,MV5215,9,X,094001
1,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,RKL,BV42E8,C,4,437349
2,TOYOTA,COROLLA,4.0,SEDAN,B,XLI TOP,GCC,4.0,RKL,BV42E6,B,4,413386
3,TOYOTA,COROLLA,4.0,SEDAN,B,XLI MID,GCC,4.0,RKL,BV42E1,B,4,415062
4,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,RKL,BV42E7,C,4,449864
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3517,TOYOTA,TUNDRA,8.0,PICKUP,B,STD (NON GCC),NON-GCC,NaN,5TB,BV5411,8,S,494560
3518,TOYOTA,TUNDRA,8.0,PICKUP,K,STD (NON GCC),NON-GCC,NaN,5TF,KV5217,7,X,001595
3519,TOYOTA,TUNDRA,8.0,PICKUP,B,STD (NON GCC),NON-GCC,NaN,5TF,BV5411,7,X,012962
3520,TOYOTA,COROLLA,4.0,SEDAN,B,XLI TOP,GCC,NaN,RKL,BV42E8,C,4,440610
3521,TOYOTA,COROLLA,4.0,SEDAN,B,XLI TOP,GCC,NaN,RKL,BV42EX,B,4,412371

====================================================================================================
pos5: K
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['AVALON', 'RAV4', 'SIENNA', 'AURION', 'CAMRY', 'COASTER', 'ALPHARD', 'HIACE', 'HIGHLANDER', 'HILUX', 'PREVIA', 'COROLLA', 'LAND CRUISER', 'FORTUNER', '2009', 'FLTRXS', 'FJ CRUISER', 'PRADO', 'LAND CRUISER 70', 'VENZA', 'SCION', 'حافلة نقل خاص', 'SIENNA VAN', 'SENA', '4RUNNER', 'STATION', 'SIENNA(VAN)', 'MR2', 'ORION', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'MPV', 'BUS', 'MINI BUS', 'STATION', 'PICKUP', 'VAN', 'PICK UP DOUBLE CAB', 'MOTORCYCLE', 'SALOON', 'PANEL VAN', 'COUPE', 'PICK UP SINGLE CAB']
  pos4: ['B', 'K', 'Z', 'Y', 'X', 'F', 'S', 'J', 'D', '2', 'G', 'R', '8', 'C', '1', 'W', 'E', 'P', 'A', 'U', '7', '3', 'V']
  trim: ['BASE', 'STD (NON GCC)', 'LE (NON GCC)', 'XLE', 'LIMITED', 'TOP', 'MID', 'LIMITED PREMIUM', 'LIMITED (NON GCC)', 'SPORT', 'XLE TOURING', 'XLE (NON GCC)', 'CE (NON GCC)', 'SE+', 'SE', 'EXCLUSIVE', 'LE', 'GL', 'LWB HIGH ROOF', 'GLE HEV', 'TOURING', 'GLX', 'LWB', 'SE (NON GCC)', 'GLI', 'SWB', 'GLS', 'GLE-X HEV 40TH ANNIV', 'STD', 'DX', 'LE HEV', 'GLI TOP', 'LE STD', '1', 'DLS', 'ADVENTURE', 'DL', 'X', 'EXR', 'DLX', 'SR5', 'GLX SPORT Z', 'VXR', 'VX', 'GRANDE HEV 40TH ANNIV', 'HT SLWB', 'GLE', 'XLI', 'HYBRID (NON GCC)', 'CE', 'S', 'GRANDE', 'ORION', 'STANDERD', 'SENA', 'TRIM', 'SR5 (NON GCC)', 'G', 'XL', 'STANDARD', 'MPV', 'GLS LOWLINE', 'SUPER SAFARI T1', 'XLI TOP', 'ROYAL EDITION', 'SED', 'STEALTH']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['4T1', 'JTM', '5TD', '2T3', '6T1', 'JTG', 'JT2', 'JTN', 'JT6', 'MR0', '5FP', 'STD', 'LJ1', '2GC', '5HD', 'JTH', '5T1', 'STO', '1GN', '4T3', 'WME', 'JTE', 'ZFC', '3GY', '6TD', 'WBA', 'LFM', 'WDB', 'JM7', '4TI', 'KL5', '61L', '611', 'JTF', 'CM8', 'XWB', 'KMF', '3GN', '5T0']
  VDS: ['BK36B6', 'BK31V3', 'KK3DC1', 'ZK22C2', 'ZK23C8', 'KK3DC9', 'BK1EB5', 'BK1EB8', 'BK1EB6', 'YK4DV0', 'KK3DC2', 'BK3DB9', 'ZK31V1', 'YK4CC6', 'BK42K2', 'BK36B7', 'BK1EB3', 'KK3DC5', 'BK40K7', 'BK33V0', 'BK4FK0', 'BK36B4', 'BK31V5', 'ZK23CX', 'BK36B0', 'YK3DC6', 'BK42K9', 'BK40K5', 'BK40K1', 'ZK23C4', 'BK36B9', 'BK1EB9', 'BK3DB0', 'XK3DC7', 'YK3DC4', 'XK3DC6', 'XK3DC4', 'ZK22C5', 'ZK23C5', 'BK3DB5', 'BK3DB3', 'BK36B5', 'KK4CC3', 'BKIEB8', 'KK4CC2', 'BK32V3', 'BK36B3', 'BK3DB6', 'YK3DC7', 'YK3DC3', 'BK36B2', 'YK3DC8', 'KK3DC8', 'BK1EB1', 'BK1EB4', 'ZK3DC8', 'YK3DC5', 'ZK3DC0', 'KK4CC5', 'BK1EB2', 'BK42KX', 'XK3DCX', 'BK3DB7', 'BK46K0', 'BK36B1', 'BK3EK8', 'KK3DCX', 'KK3DC0', 'YK3DC9', 'BK3DB2', 'YK3DC0', 'BK42K3', 'ZK23C7', 'BK22C8', 'XK3DC2', 'ZK4DV2', 'BK1FK4', 'ZK22C4', 'BK3DB8', 'BK3DB4', 'FK4180', 'BK40K4', 'YK4DV8', 'ZK23C6', 'SK12E4', 'BK1EB0', 'ZK22C8', 'ZK23C1', 'BK36BX', 'JK4CC5', 'ZK23C0', 'DK3DC6', 'BK40K8', 'KK4CC8', 'KK4CCX', 'ZK22C1', 'FK7180', 'KK4CC1', 'BK46K7', 'BK40K9', 'ZK3DC4', 'BK3DB1', 'BK42K0', 'KK4CC7', 'BK3DBX', 'BK1EBO', 'ZK3DC6', 'YK3DC1', 'ZK22C0', 'JK3DCX', 'YK4CC1', 'FK5188', 'BK1EBX', 'BK3EK4', 'XK3DC0', 'BK40KX', 'BK1EB7', 'YK3DCX', 'KK4CC4', 'KK4CC0', 'BK40K3', 'FK4181', 'JK3DC0', 'KK3DC7', '2K3DC3', 'ZK31V8', 'ZK23C3', 'ZK3DC3', 'ZK31V9', 'DK3DC7', 'KK3DC6', 'KK3DC3', 'ZK22C3', 'DK3DC2', 'GK3DH4', 'KK3DC4', 'BK22C1', 'ZK22C6', 'BK42K6', 'BK22CX', 'BK32V6', 'DK3DC0', 'BK36B8', 'BK40K0', 'BK31V9', 'BK1FK9', 'BK4FK2', 'YK4DV5', 'BK46K3', 'ZK22C7', 'BK4DV4', 'ZK22C9', 'FK5181', 'BK31V6', 'FK7183', 'BK23C0', 'BK4FK1', 'YK4CC0', 'YK4CC5', 'ZK33V7', 'ZK23C9', 'YK3DC2', 'ZK33V0', 'DK3DC3', 'ZK3DCX', 'XK3DC3', 'DK4DV0', 'ZK31V5', 'DK4CC9', 'BK32V5', 'DK4DV6', 'ZK23C2', 'BK1FK6', 'BK4FK8', 'BK46KX', 'BK40K6', 'BK42K7', 'XK3DC1', 'BK42K8', 'BK1FK2', 'BK42K5', 'JK3DC3', 'BK32V4', 'YK4CC8', 'JK3DC6', 'YK4CC2', 'BK40K2', 'FK518X', 'BK1FK3', 'ZK22CX', 'KK4CC6', 'ZK3DC1', 'FK5187', 'FK4185', 'RK4DV4', 'BK33VX', 'BK22C9', 'BK4FK3', 'SK12W1', 'YK4CC3', 'ZK34V4', 'BK32V8', 'RK4DV0', 'XK3DC9', 'BK1FK7', '2K23C0', 'DK4DV9', 'JK3DC4', 'GK13E8', '2K23C3', 'BK46K5', 'FK5186', 'RK4DV5', 'BK46K6', '8K46K6', 'BK46K4', 'BK4FK4', 'ZK31V6', 'DK4DV2', 'BK3EK6', '2K31V6', 'YK4DV6', 'BK4FK7', 'BK3EK7', 'FK5180', 'FK418X', 'FK5185', 'DK3DC9', 'YK4DV3', 'FK4184', 'BK46K9', 'RK4DVX', 'ZK3DC9', 'BK22C0', 'DK4CC5', '8K3687', 'FK4182', 'ZKRFH7', 'SK12E7', 'YKRFH8', 'BK31V7', 'XK3DC5', 'JK3DC7', 'YK4CCX', 'BK23C1', 'DK4DV5', 'JK3DC1', 'BK1FKX', 'YK3DCO', 'BK31V8', 'BK33V1', 'KK4CC9', 'FK4187', 'BK34V4', 'BK4FKX', 'ZK31V3', 'FK5189', 'DK3DCX', 'ZK3DC2', 'FK4188', 'BK31V4', 'BK1E82', 'CK12G4', 'BK4SK4', 'FK4186', 'YK4CC9', 'BK4DV0', 'BK31V0', 'BK33V6', '8K46K0', 'BK33V3', 'BK34V5', 'BK4FK9', '8K36B8', 'FK5182', 'ZK31V7', 'FK5183', 'BK42K4', 'BK22C7', 'XK3DC8', 'SK12E2', 'BK42K1', 'BK4DV9', 'ZK3DC7', 'GK26H6', '8K3DBX', 'SK12W4', 'BK4FK5', 'BK4DV3', 'BK46K8', 'BK3EH0', 'FK4189', 'RK4DV2', 'BK4FK6', 'BK33V4', 'DK3DC8', 'GK13E9', 'SK12E0', 'DK4DV8', 'BK46K2', 'BK46K1', 'BK31VX', 'FK7187', 'DK4DV3', 'DK3DC5', '8K1FK3', 'ZK3DC5', 'BK31V2', 'BK1E89', 'JK4DV3', 'BK34V2', 'BK3685', '8K3685', 'YK1F7X', '2K23CX', '8K36B5', 'FK7182', 'FK4183', '8K3D89', 'BK32V7', 'DK4DV4', '1KFCD3', 'JK4CC3', 'JK3DC9', 'DK4DV7', 'WK4DVX', '1KBBC1', 'BK1FK1', 'BK35V1', 'ZK29C7', 'DK4DVX', 'ZK29C6', 'BK32VX', 'EK19T1', 'DK4DV1', 'BK32V9', '8K3681', '2K3DC4', 'BK3EK3', 'ZK29C1', 'BK33V8', '8K40K6', '1KTP45', 'BK33V7', 'YK4CC7', 'BK23C2', 'BK1FK0', 'BK35V2', 'BK23C6', '2K23C9', 'XK4DV4', 'BK2625', '2K23C2', 'BK33V9', 'RK4DV3', 'FK5184', 'BK1FK5', 'ZK31V4', 'KK3DCG', 'RK4DV1', 'BK22C6', 'BK32V0', 'FK7188', '2K23C4', 'BK35V9', 'SK12E5', '8K33V9', 'BK22C2', '2K31V4', 'YK4DV4', 'BK22C5', 'YK4DV7', 'SK12E8', 'BK3EK1', '2K22C9', 'DK3DC4', 'SK8KD7', 'BK4DV1', 'SK12W3', 'ZK29C9', 'SK12E9', 'BK3BB1', 'JK3DC8', 'JK3DC2', 'JK3DC5', 'BK33V5', 'ZK29C2', 'YK4CC4', 'BK23C3', 'EK31X6', '2K29C6', 'SK11E2', 'BK22C3', 'BK22C4', 'BK3EHX', 'BK34VX', '2K31V7', 'DKJA05', 'BK4DV5', 'SK12EX', 'ZK29C8', 'BK31V1', 'ZK31V2', 'RK4DV8', 'GK13E7', 'JK4CC4', '2K23C1', 'GK26H2', 'BK23C4', '8K3684', 'BK1E88', 'DK4CC2', 'ZK31VX', 'ZK31V0', '8K1E85', 'BK3EK5', 'BK32V1', 'KK4DV3', 'ZK32V3', 'KK3DCO', 'BK32V2', 'BK29J6', 'SK12CX', '8K3EK1', 'FK1221', 'YK3F13', 'BK33V2', '8K1E87', 'BK3EH5', 'BK23C7', 'BK4DV8', '8K32V5', 'BK34V8', 'BK35V8', '2K22CX', 'BK3EK0', 'BK1EBS', 'PK5C54', 'KKRFHX', 'YKACC0', 'ZK32V4', 'DK3DC1', 'RK4DV7', 'KK3DCI', 'SK12E6', 'BK36BN', 'RK4DV6', 'JK4CC1', 'BK1FK8', 'GK26H1', 'DK4CC1', 'BK23C9', 'AKCB80', '2K31V1', '8K31V3', 'YK4DVX', 'SK12W6', '2K23C8', 'GK26H4', 'ZK4CCX', 'ZK32V8', '8K4FK9', 'SK12W8', 'FK718X', 'BK3EKX', '2K23C6', 'BK3EH1', 'AK54K5', 'FK7186', 'SK75F3', 'GK12E8', 'BK3267', 'BK3DBO', 'ZK32V7', 'FK7185', 'KKRFH0', 'ZK29C0', 'BK3681', 'RK4DV9', 'BK23C8', '8K31V9', 'DK4CC0', 'DK3DCO', '8K33V0', 'ZK33VX', 'BK35V7', '1KBBD4', 'JK4CC2', 'GK26H3', 'BK3EK9', 'BKIEBI', 'BKRFH1', 'JKRFH5', 'UK42AE', 'KKRFH7', 'XK4DV3', '2K23C5', 'JK02P2', 'BK1E80', 'ZK32V9', 'SK12W9', '8K22C0', 'GK3DH9', '7KE438', '3K32ED', '8K40K3', 'BK3EK2', '2K22C6', 'EK12G8', 'ZK29C3', 'ZK32V6', 'SK12W0', 'DK3EH7', 'WK4DV1', 'DK4CC4', 'FK7184', 'KK3EH0', 'KK3EHO', 'YK4DV1', 'ZK33V6', 'JK4CC0', 'YK4CCB', 'BK4DV2', 'YK3DCI', 'SK12FX', '2K22C3', 'JK4DV0', 'XKS7BP', 'BK4DV7', 'DK4CC3', 'EK12TX', '2K33V7', 'BKIEBS', 'ZK33V5', 'BK3686', 'XK3DCD', '8K3680', '2K23C7', 'DK4CC6', 'BK34V3', 'JK3EH1', 'SK12E1', 'BK35VX', 'BK35B7', 'FK7189', 'VK13E6', '2K29C4', 'GK26HX', '8K3686', 'DKJA01', 'BKRFH5', 'DK3EH1', 'BK4FKO', 'ZK29C4', 'YK4DV9']
  Model_Year: ['7', '8', 'D', '9', 'F', 'G', 'B', 'C', 'A', 'J', 'E', 'H', '5', 'N', 'K', '6', 'L', 'P', 'S', 'R', '4', 'T', 'M', '1']
  Plant_Code: ['U', '5', 'S', 'W', 'X', 'D', '4', '0', '6', '8', '3', 'B', '1', '2', 'R', 'K', '9', 'G', 'A', 'F', 'L', 'J']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,AVALON,6.0,SEDAN,B,BASE,GCC,4.0,4T1,BK36B6,7,U,203308
1,TOYOTA,RAV4,6.0,SUV,B,STD (NON GCC),GCC,5.0,JTM,BK31V3,8,5,065132
2,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),NON-GCC,5.0,5TD,KK3DC1,D,S,389260
3,TOYOTA,SIENNA,6.0,MPV,Z,LE (NON GCC),GCC,5.0,5TD,ZK22C2,9,S,228371
4,TOYOTA,SIENNA,6.0,MPV,Z,LE (NON GCC),GCC,5.0,5TD,ZK23C8,7,S,005411
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10837,TOYOTA,SIENNA,6.0,SUV,Z,CE (NON GCC),NON-GCC,NaN,5TD,ZK23C4,9,S,283581
10838,TOYOTA,AVALON,6.0,SEDAN,B,BASE,NON-GCC,NaN,4T1,BK36B5,8,U,294086
10839,TOYOTA,SIENNA,6.0,SUV,Z,CE (NON GCC),NON-GCC,NaN,5TD,ZK23C3,9,S,268229
10840,TOYOTA,AVALON,6.0,SEDAN,B,LIMITED,GCC,NaN,4T1,BK1EB4,F,U,172449
10841,TOYOTA,SIENNA,6.0,SUV,K,LE (NON GCC),NON-GCC,NaN,5TD,KK3DC7,G,S,742721

====================================================================================================
pos5: 2
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'CAMRY', 'RAV4', 'COROLLA', 'HIACE', 'T 300', 'RAV 4', 'TUNDRA', 'AVALON', 'HILUX', 'COASTER', 'BZ3X', 'URBAN CRUISER', 'DAINA', 'SIENNA', 'KS01', 'WISH', 'LAND CRUISER', 'DYNA', 'TACOMA', '2008', 'PREVIA', 'INNOVA', 'CAMRY HYBRID']
  bodyType: ['HATCHBACK', 'SEDAN', 'SUV', 'PANEL VAN', 'STATION', 'PICK UP DOUBLE CAB', 'BUS', 'PICKUP', 'MPV', 'SALOON', 'MINI BUS HIGH ROOF', 'PICK UP SINGLE CAB', 'MINI BUS']
  pos4: ['B', '7', '1', 'K', '8', 'Z', 'R', '2', 'C', 'D', 'E', 'A', '3', 'V', 'Y', '0', '4', 'H', 'J', '5', '6']
  trim: ['SE', 'LIMITED', 'E', 'LE', 'GXR', 'XLI', 'XLI MID', 'GLE', 'GLE-X HEV 40TH ANNIV', 'STD', 'S', 'EXR', 'GL', 'ADVENTURE', 'BASE', 'GRANDE', 'STD (NON GCC)', 'LIMITED PREMIUM', 'MID', 'GLE HEV', 'SE+', 'DLS', 'LWB', 'AIR', 'GLX', 'XLI - AW', '1500', 'DLX', 'XLE (NON GCC)', 'HYBRID', 'EX', 'Y', 'MPV', 'GLS', 'GX', 'DX H/R W/B', 'SPORT', 'XLI TOP', '1', 'SR5 (NON GCC)', 'GRANDE HEV', 'LE (NON GCC)', 'H', 'GL TOP', 'GLI', 'Y PLUS']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MHF', 'JTN', 'JTB', 'JTD', 'ANE', 'MR2', 'JJ5', '4T1', 'RKL', '6T1', 'LZC', 'LHA', 'MAF', 'WDD', 'LTA', 'LVA', 'LVG', 'MZB', 'MD2', '5TD', 'MHE', 'LVC', 'NCP', 'JIN', 'WMA', 'FJ4', 'INB', 'WDB', '3TY', '3TM', 'M0F', 'MHM', '5TF']
  VDS: ['B29F32', 'B24HKX', 'B29F35', 'B29F30', 'B29F31', 'B29F39', 'B24HK0', 'B24HKO', 'B29HK6', 'B24HK7', 'B29F38', 'B29F37', 'B24HK2', 'B24HK5', 'B29F34', '72SC11', 'B29F33', 'B242E4', '120010', 'B29F36', 'B29HK0', 'B29HK7', 'K29F33', 'K29F36', 'B29HK2', 'B29HK1', 'B29F3X', '8242E7', 'B242E7', 'B29HK4', 'B24HK6', 'B24HK3', 'B29HK3', 'B24HK4', 'B2E6KX', 'B29HK8', 'B242E2', '72AEB2', 'B29HKX', 'B29HK5', 'B21HK5', '72EEB0', 'B29HK9', 'B242E8', 'Z23FV4', '72SK20', 'K29F37', 'B24HK9', '1215CX', '824HK7', 'B242E6', '8242E6', 'B24HK1', '120076', 'B242E5', '1201DX', '72SK10', 'B21FB6', 'B242E1', 'R20612', 'K29F3X', '222066', 'B21FB2', '8242E8', '12H2P3', 'K29F38', 'K29F31', 'C2ZWB5', 'B24HK8', 'B29HKO', 'B2E6K5', 'B21FB0', 'B21FBO', 'D2DF62', 'E2815A', 'A22EZ3', 'K29F30', 'C2ZWB0', 'B242E9', '824HK5', 'K29F35', '829F36', '120066', 'K29F34', '32BUM1', 'B21FB3', '829F3X', 'K29F32', 'V2MW50', 'Y23DC1', '8242E4', '829F38', '829F30', '824HK6', '72AEA1', 'C2ZWB6', '022GD1', 'E29F37', 'B2NWA8', 'B2E6K9', '72EEA0', '120055', '420141', 'C2ZWB9', '1201D7', '120077', 'H25ZZZ', '1202F7', '829F32', '120049', 'B21HK7', 'V2MWB7', '022906', '8242E3', '824HKX', 'K29F39', 'Z23FV9', '829HK4', '8242E1', '420156', '8242E9', 'B21HK0', 'B242E0', 'J23DC7', 'B242E3', '72EEBO', 'Z23FV0', 'Z23FVO', 'A22NE1', '824HK2', '8242EX', '124022', '829F31', '525AN5', 'B21HK2', 'B2NBA9', 'C25AN3', '824HK3', 'B21FB8', 'B29HKE', '829F35', 'B21FB1', 'B29M31', 'B21HK4', 'B21HK1', 'B29HKB', '1201D2', 'D23DC5', 'B28F32', '120009', 'Z23FV1', 'K23DC3', 'B21HK8', '120039', '8242E0', 'B21HK6', 'E29F3E', '829F34', '120053', '420101', 'K23DC7', '829HKX', 'D258N8', 'D23DC2', '420184', '120030', '222058', '621017', 'C21FB1']
  Model_Year: ['L', 'J', 'N', 'K', 'M', 'P', 'R', 'H', 'W', 'A', '7', '1', '9', 'X', '8', '6', 'V', '2', 'S', 'E', '5', '3', '4']
  Plant_Code: ['2', '3', '0', '9', '1', 'J', 'P', '4', 'U', '7', 'D', 'X', '8', 'A', 'S', 'G', 'E', 'C', '6', '5', 'B', 'M', 'T']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,YARIS,4.0,HATCHBACK,B,SE,GCC,5.0,MHF,B29F32,L,2,101921
1,TOYOTA,CAMRY,4.0,SEDAN,B,LIMITED,GCC,4.0,JTN,B24HKX,J,3,011311
2,TOYOTA,YARIS,4.0,SEDAN,B,E,GCC,4.0,MHF,B29F35,N,2,179936
3,TOYOTA,YARIS,4.0,HATCHBACK,B,SE,GCC,5.0,MHF,B29F30,K,2,073342
4,TOYOTA,YARIS,4.0,HATCHBACK,B,SE,GCC,5.0,MHF,B29F31,K,2,042438
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4186,TOYOTA,YARIS,4.0,SEDAN,B,E,GCC,NaN,MHF,B29F33,K,2,052520
4187,TOYOTA,YARIS,4.0,SEDAN,B,SE,GCC,NaN,MHF,B29F33,L,2,111535
4188,TOYOTA,YARIS,4.0,SEDAN,B,SE,GCC,NaN,MHF,B29F30,K,2,035660
4189,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,LE,GCC,NaN,JTN,B29HK3,J,3,008456
4190,TOYOTA,YARIS,4.0,SEDAN,B,E,GCC,NaN,MHF,B29F34,M,2,123579

====================================================================================================
pos5: L
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'PRADO', 'SCION', 'LAND CRUISER', 'YARIS', 'HILUX', 'LAND CRUISER PRADO', 'RAV4', 'CAMRY', 'TACOMA', 'TERCEL', 'TOYOTA COROLLA 2.0', 'COROLLA 1.3', 'كورولا']
  bodyType: ['SEDAN', 'SUV', 'HATCHBACK', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PICK UP', 'SALOON', 'PICKUP']
  pos4: ['B', 'D', 'A', 'N', 'S', '8', 'M', 'U', 'V', 'E', 'C', '7', 'R', '1', 'P', 'T', 'Y']
  trim: ['XLI', 'SE+', 'GX', 'SE', 'LIMITED', 'VX MID', 'STD (NON GCC)', 'EXR', 'GLI', 'GX TOP', 'DLX', 'VX', 'STD', 'LMV', 'SPORT', 'GLX', 'XLI EXECUTIVE', 'LIMITED TRD SPORT PK', 'GL', 'XLI MID', 'EX', 'E', 'XLI TOP', 'GLE', 'S TRD SPORT PK', 'S', 'YA', 'GXR', 'CAR TRIM', '60TH', 'TRIM', 'PLATINUM', '1', 'XLI HEV']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['RKL', 'JTE', 'JTD', '3MY', '1N4', '5TE', '4TA', 'JM3', 'LFM', '57W', 'JHF', 'MMM', 'JH4', 'KL7', '4TI', 'LVG', 'JTG', 'KNR', 'STE', 'LHG', 'JAA', 'SAL', '000', 'BKL']
  VDS: ['BL9HE1', 'BL9HE3', 'BL29J2', 'BL9HE5', 'BL9HE7', 'BL29J3', 'BL9HE9', 'BL9HE4', 'BL9HE2', 'BL9HEX', 'BL29J5', 'BL9HE8', 'BL9HE0', 'BL40E0', 'DLBZV4', 'BL4A96', 'BL29J4', 'BL9HE6', 'BL29J1', 'BL29J9', 'DLBYV1', 'BL29J6', 'BL29J7', 'AL29J3', 'BL40E8', 'BL29JX', 'NL42N7', 'DLBYV8', 'AL29J8', 'BL40E5', 'NL42N6', 'NL42N1', 'BL40E2', 'BL29J8', 'BL40E9', 'DLBYV2', 'DLBYV0', 'BL40E3', 'DLBZV0', 'SL35E6', 'DLBYVX', 'AL1CCX', 'BL29J0', 'AL1CC9', 'DLBYV7', '8L29J0', 'NL42N2', 'AL1CC6', 'AL1CC4', 'AL29J2', 'BL40E6', 'DLBYV6', '8L29J3', 'NL42NX', 'BL40EX', 'AL29J1', 'BL9HEC', 'AL29J5', 'DLBYV9', 'ML2A69', 'UL11H5', 'SL35E2', 'AL29J4', 'AL29J0', 'AL29J6', 'DLBYV3', 'DLBYV5', 'DLBJV3', 'DLBJVX', 'VL52N2', 'BL9HEO', 'BL40E1', 'VL52NX', 'BL40E4', 'SL35E4', 'AL1CC5', 'BL2934', 'NL42N8', 'EL33P9', 'BL2937', 'NL42N9', 'AL29J7', 'CL9683', 'BL40E7', 'DLBZV1', 'BL2936', 'AL29JX', 'BL2939', 'AL29J9', '8L9HE9', 'VL52N6', '8L9HE7', '7LHEP2', 'BL42E6', 'BLIHKI', 'NL42N5', '8L9HE8', 'AL1CC2', 'AL1CC3', 'DL25R5', 'DLBYV4', 'RL9HE9', 'NL42N3', 'DLBJV8', 'NL42N4', 'AL1CC7', '8L9HE2', '1L1HEA', 'BLSHE7', 'BL2930', '8L0HE3', 'AL1CC8', 'BL2931', '8L29J1', '8L9HEX', '8L29J7', 'DLBJV7', 'BLSHE1', 'VL52N7', 'BL0HE9', 'PLM90S', 'DL39M9', 'TLIAK4', 'DLBZV3', 'BLSHEG', 'YL2FV5', 'BL00E0', 'BL9HF3', 'DLBZV8', 'DLBJV4', '8L9HE3', 'NL42N0', '8L9HE5', 'AL1CC0', 'DLBZV7', 'BLSHE5', 'VL52N0', 'DLBZVX', '8L9HE6', 'VL52N5', 'BL9HEE', 'BL42E1', 'BL8HE3', 'BLGHE1', 'DLBJVO', 'DLBJV0', 'DLBJV1']
  Model_Year: ['J', 'F', '8', 'G', '9', 'E', 'H', 'K', 'L', '7', '6', '4', '5', 'W', 'X', '3', 'N', '2', 'B', '1', 'M', 'Y', 'T', 'S', 'R', 'P', 'D']
  Plant_Code: ['5', 'K', '9', 'Y', 'C', '0', 'J', 'Z', 'M', 'H', 'U', 'G', 'T', '3', '7', '6', 'A', 'S', '2']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,RKL,BL9HE1,J,5,264498
1,TOYOTA,COROLLA,4.0,SEDAN,B,SE+,GCC,4.0,RKL,BL9HE3,F,5,234717
2,TOYOTA,PRADO,4.0,SUV,B,GX,GCC,5.0,JTE,BL29J2,8,5,116561
3,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,4.0,RKL,BL9HE5,G,5,249186
4,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,RKL,BL9HE7,F,5,233893
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4926,TOYOTA,COROLLA,4.0,SEDAN,B,1,GCC,NaN,RKL,BL9HE4,F,5,228201
4927,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,NaN,RKL,BL9HEX,E,5,210929
4928,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,NaN,RKL,BL9HE5,E,5,207419
4929,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,NaN,RKL,BL9HE9,J,5,264779
4930,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,NaN,RKL,BL9HE4,F,5,235018

====================================================================================================
pos5: N
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'PRIUS', '86', 'HIACE', 'LAND CRUISER', 'TUNDRA', 'RAV4', 'HILUX', 'GR86', 'INNOVA', 'PRADO', '4RUNNER', 'ZELAS', 'CAMRY', 'TAKOMA', 'HIACE ', 'GRAND DELUX', 'ECHO', 'TACOMA (PICK UP)', 'PREVIA', 'TAKOMA PICK UP CARGO', 'SCION', 'H3', 'HAI LUX', 'TOYOTA 86']
  bodyType: ['PICK UP DOUBLE CAB', 'HATCHBACK', 'COUPE', 'PANEL VAN', 'SUV', 'PANEL VAN HIGH ROOF', 'MINI BUS HIGH ROOF', 'BUS', 'MINI BUS', 'MPV', 'PICK UP', 'PICKUP', 'STATION', 'PICK UP SINGLE CAB', 'CARAVAN', 'SEDAN', 'VAN', 'PICKUP DOUBLE CABIN', 'SALOON']
  pos4: ['W', 'K', 'Z', 'H', 'B', 'J', 'U', 'S', 'R', 'A', 'G', '8', 'V', '1', 'T', 'E', 'D', 'M', '6', 'P', 'N']
  trim: ['SR5 (NON GCC)', 'STD (NON GCC)', 'STD', 'GL', 'C (NON GCC)', 'VX', 'VTX', 'GLS', 'LE HEV', 'DLX', 'GTX', 'HEV', 'GLX', 'MID', 'GX', 'GXR TOP', 'GT', '1500', 'FABRIC', 'SPORT', 'VT', 'ICONIC', 'HILUX', 'LIMITED', 'DLS - STD ROOF', 'DYNAMIC', 'XLI', 'EX', 'ADVENTURE', 'TOP', 'LE', 'AT', '1500 CREWCAB SLE Z71', 'STANDARD', 'XLI MID', 'GLI', 'DLS HIGH ROOF', 'DX', 'GLE', 'S', 'FR-S (NON GCC)', 'TRD', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['4TA', 'JTD', 'JF1', 'JTG', 'JTE', '5TB', 'LFM', 'JMY', 'JT3', '5TE', 'MM7', 'JT4', 'MMB', 'KN3', 'KN4', 'JT5', 'N1N', 'JTH', 'JA3', 'JN1', 'LS6', '5GT', 'LVG', 'LVZ', 'JT6', 'LFC', 'JNE']
  VDS: ['WN72N6', 'KN3DU2', 'ZN11B9', 'KN3DU9', 'ZN12B6', 'KN3DU1', 'HN9CP1', 'KN3DU3', 'BN95J7', 'ZN11B7', 'HN9CP2', 'KN3DU8', 'ZNAA12', 'JN3214', 'ZN12B4', 'KN3DU6', 'KN3DU0', 'HN9CP9', 'KN3DUX', 'HN9CPO', 'KN5BF7', 'HN9CP7', 'JNP13V', 'ZNBB18', 'KN3DU7', 'HN9CP6', 'ZN12A6', 'KN3DU4', 'ZN3EU8', 'KN3DU5', 'ZN12B2', 'ZN12A1', 'UN53B2', 'BN95J3', 'HN9CP8', 'ZN3EU3', 'ZN3EU1', 'HN9CP3', 'BN95J2', 'ZN12B8', 'ZN3EU7', 'ZN12B3', 'ZN1286', 'BN95J1', 'WN72N2', 'HN9CP5', 'ZN3EU0', 'BN95J8', 'ZN12A0', 'ZN12B9', 'BN95J0', 'ZNAA13', 'ZN12B5', 'SN92N6', 'ZN11A3', 'ZN12B1', 'UN236X', 'RN81A5', 'AN95J8', 'HN9CPX', 'ZN3EU4', 'ZN23B4', 'ZNAA15', 'ZN3EUX', 'HN86R7', 'ZNAA10', 'ZNBC13', 'JNK620', 'HN9CP0', 'KN5BFX', 'ZN11A4', 'HN86R1', 'JNK650', 'ZN1284', 'GN87R6', 'SN92N8', 'ZN11A2', 'HNP6N3', 'ZNBF12', 'ZNBB17', 'ZN11AX', 'HN87R7', 'BN95J6', 'KN5BF2', '8N95J3', 'BN95J4', 'BN95JX', 'UN2020', 'KN3DP1', 'ZNAA14', 'RN50R2', 'ZN3EU6', 'ZNBE12', 'ZN12B7', 'AN95J9', 'ZNBC19', 'HN86R5', 'ZN11A5', 'ZN11A1', 'RN82P6', 'HN9CP4', 'ZNBE14', 'ZN12A9', 'ZNAA19', 'BN95J5', 'GN86R6', 'ZN3EU9', 'KN5BF0', 'KN3DUS', '8N95J2', 'RN81A2', 'ZNBF14', 'HN86R8', 'KN3DP7', 'ZNAA16', 'UN2364', 'KN3D00', 'JNK640', 'HN9CPI', 'ZNBG14', 'ZN3EU2', 'HNW6NK', 'VN94T5', 'ZN12BX', 'KN3DUO', 'ZNBF11', '1N1ENV', 'HN86RX', 'KN9CP5', 'WN72N5', 'ZN12B0', 'JN5BF6', 'ZN12A7', 'BN30F4', 'UN53B8', 'HNICPO', 'KN5BF6', 'JN5BF9', 'KN3DP6', 'ZN23B6', 'ZN23B9', 'HN87R1', 'JN321X', 'WN72N9', 'AN74K3', 'VN52NX', 'UN2362', 'ZN12A4', 'BN4414', 'RN93P8', 'TN12DX', 'ZN11A0', 'KN5BF1', 'SN92N2', 'ZN11A6', 'KN9CP8', 'EN61S2', 'HN87R5', 'KN3D02', 'ZN12A5', 'GN87R2', 'UN2467', 'ZNAA1X', 'GNP03V', 'ZNAA17', 'HN87R3', 'VN61F2', 'BN95J9', 'ZNAE17', 'KN5BF5', 'VN73K1', 'KN3DP3', 'ZN11A9', 'HNP13W', 'RN01P3', 'UN3463', 'JN3216', 'KN3DP9', 'ZN11A8', 'ZN11B0', 'UN3163', 'UN41B9', 'JNKG2Q', 'HN86R3', 'ENE0R2', 'DN1363', 'DN56A0', 'KN5BF3', 'ZN12A2', 'WN72N4', 'UN24D9', 'UN2068', 'HN86R2', 'MN25B5', 'UN24D2', 'AN95J2', 'VN52N5', 'GN86R8', 'AN95JX', 'KN3DP0', 'ENKA50', '6N87R6', 'ZN1287', 'ZNAA18', 'ZN12A8', 'DN1366', 'ZNBF15', 'VN13G4', 'AN95J6', 'PN62N5', 'ZNBC1X', 'RN3414', 'ZNBE15', 'SN92N0', 'KN3DP2', 'KN9CPX', 'WN72N0', 'NNG6P5', 'UN2367', 'RN81A7', 'ZN23A5', 'GN86R9', 'KN3DP5', 'ZN3EU5', 'ZN12E7', 'ZN12AX', 'BN4416', 'TN14DX', 'ZN11A7', 'ZN12A3']
  Model_Year: ['T', 'F', 'D', 'M', 'E', '1', 'P', 'A', '3', 'B', 'N', 'C', 'S', '5', 'R', 'L', 'K', 'G', 'X', '4', '2', 'H', 'Y', '6', '7', 'W', 'J', '8', 'V']
  Plant_Code: ['Z', '0', 'G', '2', '5', '6', '1', '8', 'S', 'B', '3', 'A', '9', 'J', 'W', 'D', 'K', 'Y', 'C', '7']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,W,SR5 (NON GCC),GCC,4.0,4TA,WN72N6,T,Z,159758
1,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),GCC,5.0,JTD,KN3DU2,F,0,434986
2,TOYOTA,86,4.0,COUPE,Z,STD,GCC,NaN,JF1,ZN11B9,D,G,013783
3,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),GCC,5.0,JTD,KN3DU9,F,2,002478
4,TOYOTA,86,4.0,COUPE,Z,STD,GCC,2.0,JF1,ZN12B6,D,G,014047
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1836,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),NON-GCC,NaN,JTD,KN3DU9,A,5,009468
1837,TOYOTA,TOYOTA 86,4.0,COUPE,Z,GT,GCC,NaN,JF1,ZN11A7,E,G,016089
1838,TOYOTA,TOYOTA 86,4.0,COUPE,Z,STD,GCC,NaN,JF1,ZN12B4,D,G,010420
1839,TOYOTA,TOYOTA 86,4.0,COUPE,Z,GTX,GCC,NaN,JF1,ZN12A3,G,G,025017
1840,TOYOTA,PRIUS,4.0,SEDAN,K,STD (NON GCC),NON-GCC,NaN,JTD,KN3DU9,A,0,058716

====================================================================================================
pos5: A
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['SIENNA', 'CAMRY', 'COROLLA CROSS', 'RAIZE', 'HIACE', 'COROLLA', 'PRADO', 'LAND CRUISER', 'SOLARA', 'PRIUS', 'HIGHLANDER', 'TUNDRA', 'CROWN', 'HILUX', 'COROLLA 1.6', 'COROLLA 1.3', 'LAND CRUISER PRADO', 'BZ4X', 'AVALON', 'SUPRA', '4RUNNER', 'YARIS', 'SEQUOIA', 'COROLLA 1.8', 'OTHERS', 'RAV4', 'SCION', 'FORTUNER', 'COASTER', 'TACOMA', '2022', 'TOYOTA COROLLA', 'VENZA', 'TOYOTA SUPRA', 'SIENA', 'ECHO', 'GXL RA (STATION WAGON)', '25PR 5 DR P 2.4L AT', 'MIRAI', 'TOYOTA COROLLA 1.8']
  bodyType: ['MPV', 'SEDAN', 'SUV- CROSSOVER', 'SUV', 'PANEL VAN', 'CONVERTIBLE', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'COUPE', 'PANEL VAN HIGH ROOF', 'SALOON', 'STATION', 'PICK UP SINGLE CAB', 'MINI BUS HIGH ROOF', 'VAN', 'BUS', 'WINDOW VAN', 'HALF PANEL VAN', 'WAGON', 'PICKUP']
  pos4: ['Z', 'B', 'K', 'A', 'C', '8', 'Y', 'F', 'E', '2', 'J', 'W', 'L', 'D', 'M', '5', 'V', 'P', '1', 'G', 'H', '6', 'N', 'U', '7', 'X']
  trim: ['XLE (NON GCC)', 'XLI', 'GLI', 'TURBO G RA', 'STD', 'XLI EXECUTIVE MR', 'XL', 'ADVENTURE', 'LE', 'LE (NON GCC)', 'E', 'SE', 'VXR', 'GXL', 'ICONIC', 'GXR', 'XLI MID', 'TXL1', 'STD (NON GCC)', '1794 EDITION (NON GCC)', 'XLE', 'SR', 'TXL3', 'CREWMAX CAPSTONE (NON GCC)', 'LIMITED (NON GCC)', 'PREMIUM', 'HEV GLI', 'DYNAMIC', 'XLI EXECUTIVE HEV', 'GLE', 'DLX', '1', 'LIMITED', 'VX', 'ECO', 'TXR', 'PRO', 'LE HEV', 'COUPE', 'XLE HEV', 'TRD OFF-ROAD', 'GLI HEV', 'SR (NON GCC)', 'TX1', 'DL', 'GLS', 'DLS', 'GXR2', 'SPORT', 'GLX', 'S', 'TURBO G', 'GA', 'TOP', 'GL', 'AUTOMATIC', 'G', 'EXR', 'EXI', 'HYBRID (NON GCC)', 'SR5 (NON GCC)', 'AXL ', 'C', 'LUMIERE 40TH ANNIV', 'SE+', 'GLE HEV BLACK EDITION', 'PLATINUM', 'SS', 'GXL 1ST EDITION', 'COMFORT', 'GLE HEV', 'TRIM', 'GLI MR HEV', 'DX', 'BASE', 'SALOON', 'XLI TOP', 'GR', 'DTD', 'CTD', 'ST', 'GRANDE', 'LWB', 'GR SPORT', 'ALTIS (NON GCC)', 'MID', 'SUV', '4', 'CARRERA GTS', 'TRTIM', 'IM', 'ADVENTURE 1ST EDITIO', '1794 EDITION (NON GC', 'CREWMAX CAPSTONE (NO']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TD', '4T1', 'RKL', 'MHK', 'JT4', 'LFM', 'JTE', '7MU', '1NX', 'JTD', 'JT2', 'JTM', '5TF', 'INX', '2T1', 'LVG', '137', 'JCB', 'JTC', 'LGW', 'RA6', 'LWL', 'JTN', 'STD', 'ZAP', 'LKL', 'LZW', '7SV', 'KMF', 'MR0', '4T3', 'KN3', 'LJ1', '4TI', 'KLA', 'MB1', 'LZZ', 'JTG', 'JT6', 'LPS', 'KLI', 'HJN', 'KMJ', 'JNC', 'MKH', 'RKE', '1G6', 'VF3', '6TD', 'JNK', 'KNA', 'STF', 'ZCF', 'K1K', 'SAL', 'WV2', 'WP0', 'LA7']
  VDS: ['ZA23CX', 'ZA23C6', 'BA32K0', 'KAAAG0', 'ZA23C8', 'KAAAG9', 'AA1BA4', 'ZA1190', 'AA1BA1', 'ZA23C0', 'AAA0C7', 'KABAGX', 'AACAJ8', 'CAAAGO', 'ZA22C9', 'CAAAG0', 'ZA23C3', 'ZA22C6', 'AA1BA8', 'BA32KX', 'AACAJ6', 'CA30P2', 'BA02E3', '8A32KX', 'KAAAG8', 'ZA23C5', 'BA0BE8', 'AA1BA6', 'BA22C3', 'BA0BEX', 'ZA22C8', 'AACAJ3', 'KARFU1', 'KAAAG3', 'YARAH6', 'ZA22C2', 'KAAAG4', 'AA1BA2', 'BA13E8', 'FA38P8', 'BA32K8', 'BA0BEO', 'BA23C4', 'ZA23C2', 'ZA1197', 'AAA0C5', 'AACBJ1', 'BA13E3', 'AABBJ0', 'CAABG0', 'AA1BA5', 'AACAJ4', 'BA0BE5', 'KAAAG2', 'EAMDE4', 'BA13EX', 'AAADC3', 'AABBJ7', 'ZA23C1', 'ZA23C9', 'BA0BE3', 'KAAAG6', 'AACAJ0', 'ZA23C7', '2A22C1', 'ZA22C1', 'JA5ABX', 'ZA22C3', 'CAAAG7', 'ZA22C7', 'AACAJ9', 'BA02EX', 'AA1BA7', 'KAAAG5', 'WA5DB2', 'AA1BA3', 'ZA22CX', 'BA22C6', 'AA9AJ6', 'AA1BA0', 'AA9AJ0', 'LA5DB6', 'BA02E8', 'AAA0CX', 'ZA22C0', 'KA3DC5', 'FA38P3', 'ZA22C4', 'BA02E6', 'LA5AB6', 'ZA29C5', 'BA0BE4', 'BA0BE1', 'DAABGX', 'BA02E7', 'AAA0C6', 'BA13E7', 'AAAAF7', 'AABBJ3', 'KA3DC7', 'BA13E5', 'AAA0C9', 'BA22C1', 'LA5AB4', 'AA1BA9', 'ZA22C5', 'ZA1191', 'BA0BE9', 'KA3DC9', 'BACEKX', 'AACAJX', 'AABBJX', 'KAAAGO', 'BA0BE0', 'AA1BAX', 'BA13E9', 'BA0BE2', 'BA22C2', 'FA9035', 'AA9AJ3', 'BA23C6', 'BA30K4', 'BA05E8', 'ZA1195', 'JA5DB5', 'ZA2301', 'FA38P5', 'BA0BE6', 'KABAG0', 'MA5EC2', 'BA02E2', 'ZA29C9', 'ZA1135', 'KAMFU5', 'AAA0C8', 'KAAAG7', 'AABBJ6', 'JA5EC1', 'KAAAG1', 'BA13E6', '8A13E6', 'AACAJ2', 'LA3AH3', 'ZA23C4', 'BA22C7', '2A1190', 'AAA0C4', 'AAAAG3', 'ZA29C1', 'KABAG9', 'BA32K9', '2A23CX', 'AA9AJO', '8A02E6', 'AACAJ5', 'AAYAJO', 'AAAAA9', 'BA13E0', 'AAA0C2', 'AAAAG2', 'MA71J2', 'AAAAG9', 'AACAJ1', 'KA3DC3', 'KAAAGX', '5AFKGT', 'LA5DB5', 'KABAG1', 'MA71L5', 'BA13E2', 'FA1196', 'BA01E9', 'BA32K5', 'AA7BJ1', 'ZA1192', 'DAACK6', 'VA5BR3', 'BA13E1', 'ZA29C3', 'BA22C9', 'JA5DB8', 'AAA0C1', 'BA32K7', 'KABAG5', 'JA82J0', 'CA2174', 'LA5GD0', 'PAEHD1', 'BA02E0', 'BA02E4', 'BA02E9', 'KA3DC0', 'BA0BE7', 'AACAJ7', 'AAABG0', 'AACBJ3', 'AACBJX', 'BA03E8', 'BA02E1', 'LA3AH6', 'AAA0C3', 'DAR9K9', 'JA5DB7', 'AABBJ2', 'PAEHD5', 'KARFU6', 'KARJE0', 'KA3DC4', 'AAAAFO', '2A23C8', 'KARFU2', 'AAABG9', 'MA3603', 'AA9AJ7', 'EAAAGX', 'KARFUX', 'BA05E1', 'KARJE4', 'BA23C2', '1AAA66', 'CAABG9', 'ZA29C0', 'CAAGAX', 'AA9AJ2', '2A22C9', 'BA23C9', 'AAABA7', 'DAACK3', 'GA17FP', 'EAMDE0', 'KARFU0', 'LA5DB0', 'FA38PX', 'JA5DBX', 'LA5DB3', 'EAMDEX', 'LA5DA2', 'BAOBE3', 'AACBJ9', 'BA8CD4', 'BA22C4', 'LA5DB4', 'BA32K1', 'KARFU5', 'KA3DC8', 'BA02E5', 'JA5DA3', 'KARJEX', 'ZA29C8', 'KABAG6', 'KABAGO', 'AAAAF4', 'KARFU7', 'AA9AJ4', 'KAJDC9', 'AAA0C0', 'AACBJ2', '2A22C3', 'BAOBE7', 'AACAJO', 'KARJE5', 'WA5EC3', 'FA1193', 'ZA3BB4', 'BA23C3', 'HAP53E', 'WA5DB1', 'BA32K6', 'KA3DCO', '6AE3C6', 'KAMFU9', 'BA8CD7', 'BA32K3', 'KARFU4', 'AA9AJ9', 'KABAG7', 'KABAG2', 'BA23C7', 'ZA29C7', 'BA22C0', 'KARJE2', 'LA3AH0', 'KAMFPX', 'BA22CX', 'AACBJ7', 'ZA119X', 'JA81LX', 'AAAAA2', 'AABBJ1', 'ZA1193', 'AACBJ8', 'ZA29C2', 'KARJE3', 'BA22C8', 'HAP5J1', 'KARFP6', 'CAABG8', 'PA69JD', 'BA23CX', 'KA3DC1', 'AACBJ0', 'AA7BJO', 'AA7BJ0', 'KARFU3', 'BA23C5', 'AABBJ9', 'JA5EC5', 'KA3DC2', 'AABBJ5', 'CAABGX', 'LA5BC7', 'AA1BAO', 'BAABG8', 'LA3AHX', 'BA32K2', 'AA7BJ2', 'PAAWA2', 'MA5DB9', 'BAOBE8', 'CAABG1', 'KABAG8', 'BA13E4', 'AAAAF2', 'BA03E6', 'FA38P9', 'AAABA9', 'KABAG4', 'BA30K9', '8A13EX', 'AAABA2', 'NA5DB3', 'GA17F3', 'ZA1198', 'WADG49', 'LA5DA8', 'LA5DB1', 'ZA29CX', 'KARFP2', 'JA82J1', 'MA70J6', 'FA119X', 'GA17F4', 'AABBJ4', '2A22C8', 'BA30K5', 'WA5DB0', 'BAABG5', 'AABBJ8', 'CA38P8', 'ZA1194', 'BA03E0', 'KARFP3', 'KARFU8', 'BA1HK0', 'AAABG5', 'JA81J7', 'BAABG6', 'MA5DB8', 'BA23C1', 'AAAAG4', 'CAAAG3', 'BACEK8', 'KAAAC7', 'BA01E6', 'GA17FX', 'BA01E2', 'BA02EO', 'KARJE1', 'BA8CD8', 'MA5DBX', '2A22C5', 'AA9AJ1', 'BAOBE2', 'ZARAH3', 'EAMDE3', 'FARAH4', 'FA1194', 'AA7BJ9', 'LA5DB2', 'AACBJ5', 'VAEDE1', 'ZA5CS4', 'BA30K7', 'AAABG2', 'KABAG3', 'KARJE7', 'NADMG2', 'DAABG0', 'LA3AH4', 'ZA29C6', 'LA5DAX', 'AAABA6', 'EAMDE7', 'JA5DA1', 'BA8CD3', 'WA37R1', 'BA22C5', '2A23C7', 'DAABG9', 'MA5ECO', 'MA5EC0', 'KARJE6', 'KARFU9', 'BA32K4', 'AACBJ4', 'BAMDE8', 'LA5DA7', 'AA9AJ5', 'ZA3BB8', 'AAABA3', 'LA5DBX', 'KA3DCX', 'BAABG0', 'FA1191', 'MA5DB4', 'BA30K3', 'AAABA4', 'KAMFU8', '2A23C6', 'GARAH7', 'JA81L5', 'LA5EC9', 'UAD1H1', 'BADBA0', 'JA81L9', 'JA17B3', 'AAABGX', 'MA5DB0', 'BA30K2', 'LA3AH1', 'AA9AJX', 'DAACK8', 'ZA1199', 'AAAAFX', 'JA82J8', 'WAH7JP', 'LA5DB8', 'KAAAGB', 'AACAJA', 'KAMFP0', 'EAMDE2', 'BA01E1', 'DAAAG2', 'AAAOC8', 'AA7BJ7', 'BA0BES', 'BA30K8', 'AAABA5', 'AA7BJX', 'CAAAGX', 'FA38P7', 'CA2171', 'LA5DA9', 'LA5DB9', 'AA7BJ5', 'FA1198', 'JA5DA9', 'LASDB9', 'ZA1196', 'KARFP5', 'DAACK7', 'EAMDE6', 'BA23C0', '8A23C0', 'KARJE8', 'NA5DB2', 'AA5RX7', 'AAAB58', '7ANFU0', 'MA5DB5', 'KAMFUX', '2A23C5', 'ZA29C4', 'EAMDE8', 'DA1AB2', 'LA5DA5', 'AAAAG7', 'BA05E0', 'YARAH7', 'BA8CD1', 'AAAAG6', 'LA5DA0', 'GA17F5', 'LA3AHO', 'DA31A8', 'BA01E3', '2A29C2', 'BA03E5', 'EAMDE1', 'AAAAF5', 'KARJE9', 'MA5DB6', 'BA03E9', 'LA5AB5', 'DAACK2', 'BA05E3', 'LA5DB7', 'BA2443', 'WA37R7', 'BA0BEB', 'ZA3EH2', 'FA1195', 'JA5DB6', 'JA5DB3', 'AA9AJ8', 'JA82J9', 'JA5DA7', 'JA82J5', 'KARFP4', 'AAAAG1', 'WA37RX', 'PAAWA5', 'AABAJO', 'BA01E7', 'AA18A8', 'CAABGO', 'LA3AH7', 'MA5DB7', 'CAABG7', 'NA5DB6', 'FA1190', 'LA3AH2', 'KARAH2', 'BA05E4', 'AACAJI', 'WA5DB5', '2A23C3', 'CA50A0', 'AAN6E8', 'MA71J6', 'JA82J3', 'KAAA60', 'BAOBE5', 'AAABAX', 'BA01E8', 'AALAJA', 'BA01EX', 'KARFP8', '2A1197', 'FA38P1', '7ANFUC', 'CA31A7', 'PAEHD8', 'KARFP7', 'KAMFP7', 'LAAA44', 'CA21A7', 'JA5DB4', 'BAOBE1', 'LA5EC5', 'HAP732', 'AAIBA6', 'CA30P7', 'XAD2K0', 'HAP53C', 'AA7BJ6', 'WA5DB4', 'KAMFU0', 'ZA119S', 'CA38P9', 'BAOBEX', 'AATBA9', 'GA17EP', 'MA71J9', 'AA7BJ3', 'AA18A6', 'BA3BE9', 'KAMFP1', 'AAAAF8', 'DARTK7', 'KA3DC6', 'JA5DB1', 'EA6BX2', 'AA1AB4', 'MA5EC3', 'JA5EC8', 'EAMDE9', 'MA71L3', 'BA3BB0', '8A02EX', 'KARFP1', 'BA03E1', 'JA5EC6', '2A22CX', 'BAAAG7', 'WA5DB9', 'DAABG4', 'GA17HP', '2A23C2', 'AA1BAB', 'KAMFP2', 'AAAAF1', '2A29C5', 'BA2A93', 'BA03E4', 'CAAAG5', 'AAAAF0', 'FA1197', 'JA5EC4', 'BA8CD9', 'DAACK0', 'NA3DCS', 'JA81J8', 'BA30K0', 'WA5DB3', 'NA5DBX', '8A08E1', 'EAMDE5', '1AU933', 'MA70L6', 'MA5DB3', '2A1192', 'JA5DAX', 'LA3AH5', 'NA5DB1', 'AAAA55', 'AA9AJZ', 'NA5DB7', 'JA81L7', 'MA5DB1', 'MA70L5', 'JA81J1', 'MA71J0', 'LA5DA4']
  Model_Year: ['5', '6', 'M', 'R', 'P', 'X', 'S', 'N', '4', 'V', 'L', 'T', 'H', 'Y', '7', 'B', '8', 'C', 'G', '2', '1', 'K', 'J', 'A', 'E', 'D', 'F', '9']
  Plant_Code: ['S', 'U', '0', 'J', 'K', 'V', 'Z', '5', '1', '3', '4', 'X', 'C', 'G', 'E', '2', '7', 'A', 'B', 'L', 'T', '8']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,SIENNA,6.0,MPV,Z,XLE (NON GCC),GCC,5.0,5TD,ZA23CX,5,S,307623
1,TOYOTA,SIENNA,6.0,MPV,Z,XLE (NON GCC),GCC,5.0,5TD,ZA23C6,5,S,370007
2,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,GCC,4.0,4T1,BA32K0,6,U,091516
3,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,K,GLI,GCC,5.0,RKL,KAAAG0,M,0,500885
4,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,K,GLI,GCC,5.0,RKL,KAAAG0,R,0,518858
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4952,TOYOTA,RAIZE,4.0,SUV,A,TURBO G RA,GCC,NaN,MHK,AA1BA6,R,J,112571
4953,TOYOTA,TUNDRA,6.0,PICKUP,L,1794 EDITION (NON GC,NON-GCC,NaN,5TF,LA5DB7,P,X,061169
4954,TOYOTA,LAND CRUISER,6.0,SUV,A,1,GCC,NaN,JTM,AACBJ8,N,4,009599
4955,TOYOTA,SIENNA,6.0,SUV,Z,1,NON-GCC,NaN,5TD,ZA23C8,6,S,423033
4956,TOYOTA,LAND CRUISER PRADO,4.0,SUV,A,GXL,GCC,NaN,JTE,AACAJ1,S,5,008118

====================================================================================================
pos5: 1
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'RAV4', 'CAMRY', 'HILUX', 'LAND CRUISER', 'COROLLA', 'RAV 4', 'COASTER', 'HIACE', 'FJ CRUISER', 'COROLLA 1.6', 'WISH', 'PRADO', 'LAND CRUISER PICK UP', 'PREVIA', '25 CA SON P 2.5L AT', 'RAV4 LE CAR', 'RUSH', 'FORTUNER', 'TOYOTA COROLLA', 'COROLLA 1.8', 'AURION', 'VELOZ', 'COROLLA CROSS', 'هايلوكس', 'COROLLA SEDAN', 'CAMRY HYBRID', 'LAND CRUISER PRADO']
  bodyType: ['HATCHBACK', 'SUV', 'SEDAN', 'PICK UP SINGLE CAB', 'STATION', 'BUS', 'PICK UP DOUBLE CAB', 'MINI BUS', 'PANEL VAN', 'PICKUP', 'SALOON', 'VAN', 'PICK UP', 'PANEL VAN HIGH ROOF', 'MPV', 'SUV- CROSSOVER']
  pos4: ['K', 'W', 'Z', 'B', '3', 'G', '1', 'C', 'A', 'J', 'F', '5', 'H', '7', 'D', 'R', 'L', 'P', 'S', '4', '2', '8', 'M', 'T', 'N', 'V', '9', 'E', '6', 'Y', '0']
  trim: ['SE', 'LE HEV', 'E', 'EX', 'LE', 'EXR', 'GLE HEV', 'VX', 'DLX', 'S', 'GXR', 'ADVENTURE', 'STD', 'GLE', 'XLI', 'GLI', 'XLE', 'GX', 'T', 'GLE-X HEV 40TH ANNIV', 'SV', 'STD (NON GCC)', 'DX', 'LIMITED', 'XLI MID', 'XLI EXECUTIVE', 'BASE', 'LIMITED HEV', 'XLI POWER OPT', 'GLI HEV', 'GL', 'GRANDE HEV 40TH ANNIV', 'STANDDARD', 'PW CL', 'PREMIER', 'LE STD', 'GXR TOP', 'EXR HEV', 'VXR HEV', 'GG', 'PLATINUM', 'GRANDE HEV', 'PRADO', 'LTD HEV', 'DL', 'XLI TOP', 'SE+', 'GLI TOP', 'MID', 'GLE-X', 'GLX', 'TXR', 'DLS', 'FLEET', '1', 'GLS', 'DLX TOP', 'GL LIMITED', 'XLI EXECUTIVE MR', 'TX-L', 'SPORT', 'LWB HIGH ROOF', 'SALOON', 'XLT', 'LX']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MR2', '2T3', 'JTD', 'JTN', 'JTM', 'JTB', '4T1', 'ZE1', 'LFM', 'LVG', 'ANE', 'LVC', 'ZGE', 'MMM', 'MHF', 'LA6', 'ACV', 'JTE', '00N', 'NCP', '1GT', 'VR3', 'WDB', 'AR2', 'MD2', 'NV1', 'MC2', 'LMX', 'LKL', 'SXA', '1N1', 'JT8', 'W11', 'LSJ', 'W01', 'WMA', 'L3A', 'AT1', 'JT1', 'L11', 'WB1', '111', 'LGJ', '174', 'UP1', 'AS3', 'SMT', 'J10', 'AE1', 'LDP']
  VDS: ['K19F35', 'W1RFV6', 'K19F32', 'Z13FV3', 'Z13FV8', 'Z13FV7', 'W13FVX', 'B14HKX', 'B13FV7', 'B1RFV5', '31UNE6', 'G11AK4', 'Z13FV9', 'Z13FV5', 'Z13FV0', 'Z13FV4', 'G11AK7', 'K19F31', 'K19F39', 'B14HK2', '11UJ83', 'K19F30', 'C11AK2', 'K19F38', 'A14CK1', 'B14HK3', 'J13FVX', 'B11HK9', 'A14CK7', 'B11HK4', 'B14HK7', 'W13FV2', 'F1RFV7', '513033', 'B14HK5', '11WJA0', 'J13FVO', '11UJ80', 'B11HKX', 'G11AK0', 'H1RFV5', 'B14HK4', 'Z13FV1', 'W13FV8', 'G11AK9', 'J13FV3', 'Z13FVX', 'H1RFV7', 'W13FV9', 'K19F3X', 'C11AK1', 'J13FV0', 'C1RFV8', 'A18097', 'B11HK3', 'J13FV1', 'K19F34', 'K19F37', '11UJA0', '71SC10', 'A14CK3', 'Z13FV6', 'A11AK9', 'H1RFV6', 'B14HK8', 'W13FV1', 'D156F5', 'R1RFV4', 'A14CK4', 'W13FV7', 'B19HKO', 'B11HK2', 'B11HK5', 'A180C1', 'W13FV4', 'J13FV5', 'G11AKX', 'A14CK5', 'K19F33', 'B14HK0', 'A14CKX', 'A14CK9', 'B19HK4', 'W1RFV9', 'Z13FV2', 'L11AK3', 'P1RFVX', 'G11AK8', 'A14CK0', 'S11AK0', 'B19HK7', 'B19HK9', 'W13FV0', 'B11HK1', 'B13FV9', 'B14HK9', 'A14CK2', 'B14HK1', 'B14HK6', 'C11AK0', 'W13FV5', '41UB50', 'B14HKO', '116000', 'A14CK6', 'B11HKO', 'B11HK0', 'R13FV1', 'A1ACC6', 'J13FV9', 'B11HK8', 'K1RFV8', 'H1RFV3', 'B13FV6', 'B1DWA7', '11WJAO', '216106', '31UJ75', 'G11AK2', '514884', 'B13FV4', 'J13FV8', 'W13FV3', 'A14CK8', 'W1RFV7', '811HK2', 'R13FVO', 'B11HK6', 'M11AK7', 'J13FV6', 'B11HK7', 'K19F36', 'H1RFV9', '31UNE0', '513902', 'F1RFV0', 'B19HK8', 'H1RFVX', 'B1B0E9', 'A1ACC2', 'C11AK5', 'R13FV0', '41UHB5', 'W13FV6', 'J13FV2', 'K1RFVX', '11VJ95', 'T11AK5', '11UJAO', 'B13FV2', 'J13FV7', 'R13FV2', 'M1111M', 'B19F33', 'G11AK6', 'G11BK8', 'W1RFV3', 'A1ACC0', '31YN87', 'J13FV4', 'K1RFV4', 'B19HK3', 'B19HKX', '41CB81', 'A180C2', 'P1RFV3', 'P1RFV1', 'B19HK1', '21UHB3', 'R13FV3', 'Z13FVO', 'J1RFV8', 'B19HK2', 'C11AKX', 'T11AK9', 'C11BK9', 'A1ACCO', 'G11AK5', 'K1RFV7', 'A180C3', 'B19F30', 'B13FV8', 'B13FV5', 'A1RFV4', 'B1B0E2', 'H1RFV1', 'B13FV0', 'C11AK8', 'F1RFV4', 'C11AK9', 'A1ACC5', '415020', 'C11AK6', 'G11AK3', 'B1RFV3', 'R1RFVX', 'A14CKO', 'H1RFV8', 'R11AK8', 'H1RFV4', 'W1RFVX', 'B1B0E5', 'B19HK0', 'J1RFV9', '213FV5', '11VJ90', 'G1RFV9', 'W13FVO', 'P1RFV7', 'B19HK6', 'A1RFV2', 'B19HK5', 'M11AK8', 'C11AK7', 'P1RFV8', 'B13FV1', 'A180C0', 'B13FV3', 'H1RFV0', 'N1RFV8', '819HK1', 'B1B0E8', 'F1RFV5', 'F11AK7', 'F1RFV8', 'A1ACC1', 'K1RFV3', 'B19F34', '216049', 'R1RFV8', 'H109J9', 'D1RFV8', 'C11AK3', 'S11AK7', '515001', '811HK6', '216067', '511161', 'G1RFV6', '814HK4', 'G1RFV7', 'G1RFV4', '811HK5', 'B1B0EX', 'R13FV8', 'A1ACC3', 'F11AK4', 'R13FV6', 'A1RFVX', 'C1RFV7', '11WJAD', 'R13FV9', 'M11AK6', 'C11AK4', 'G11BK7', 'R13FVX', '510670', 'J1RFV2', 'W1RFVO', 'W1RFV0', 'B1B0E0', 'V18044', '919017', 'F1RFV3', 'F1RFVX', 'A14CKB', 'T11AK2', 'C11AKO', 'B1B0E7', 'C1RFVX', 'A180C8', '213FV1', '31UNE2', 'N1RFV9', 'B13FVX', 'B19F38', 'W1RFV4', 'W1RFV1', 'A1RFV5', 'A180C6', 'P1RFV0', '511131', 'H1RFV2', 'N19EC0', 'E1NFJX', 'P1RFV6', 'F1RFV6', 'R13FV5', '919002', 'C11AKS', '919032', 'C11BK0', 'C1RFV5', 'R11AK6', '216041', 'F11AK6', 'G11AK1', 'A180C5', 'G1RFV1', 'R1RFV9', 'P1RFV5', '813FV9', 'B19F37', 'B19F35', 'B1B0E4', 'A180CX', 'R13FV4', 'G11AKO', '615242', 'R1RFV6', 'R11AK7', 'F11BK2', 'A11CX7', 'J1RFV4', 'B13FVO', '516117', 'F1RFV2', '919021', 'R1RFV0', 'B1RFV0', 'F1RFV1', 'N1RFV7', 'A1RFV6', 'F1RFV9', '31UNG0', 'G11BK6', 'T11AK1', '213FV9', '919014', 'T11AKX', '810187', '516227', '512110', 'C1RFV1', '415002', 'R13FV7', 'W1RFV5', 'B1RFV9', '814HK8', 'G1RFV2', '21FCL5', 'D13FV4', '31YN81', '11UJ94', '515739', 'B19F39', 'W1RFV2', '415036', '415014', 'G14DAO', 'G11BK2', 'L11AK9', 'S11BK2', '415013', '919035', 'W13EV6', 'B19F32', 'A14AFX', 'J13FVI', '31RN85', 'R1CS94', 'P1HLT8', 'B11HKI', '919085', 'B19F31', '819F32', '110053', 'G11BK4', '111111', 'C1RFV2', '21UJ70', 'T11BK9', '519081', 'K1RFV6', 'K1RFV5', '511028', 'B1B0E3', '11AC10', 'T11AK4', 'A180C4', '514263', 'R1RFV5', 'B1RFV1', 'C1RFV0', '213FV8', 'F11AK0', 'R1RFV7', 'Y1RFV6', 'R1DSBX', '415033', 'A16E36', 'P1RFV9', 'R1RFV1', 'M11AK0', 'G1RFV0', 'T11AK7', '415010', '216035', 'Z13FVB', 'A1RFV9', 'A11CY2', '814HKX', '519401', '512671', '21SZZ5', '216086', '216088', 'Z1CK33', 'R1RFV2', 'P1RFV2', 'M11AK4', '415029', 'A11CX6', 'A11CX0', 'B1B0E1', '41BB42', 'J11BK7', 'A1ACC9', 'G11BK1', '919012', 'T11AK3', '216081', '516804', '415017', 'N1RFV6', 'A1RFV0', 'T11BK8', 'A11CX1', '811EB7', '71SC18', '216054', '511497', 'R1CS96', '513821', '011111', '514528', '511890', 'G1RFV3', '111S11', 'E1EE03', '814HK5', '210906', 'G11BK3', '516589', '216087', 'B1RFV8', 'S11AK9', 'G11BK5', 'B1B0E6', 'G11BKX', 'M11AK2', 'B19F36', '415030', 'C1RFV9', '010356', 'K1RFV9', '216023', 'B1RFV6', '519729', '21AS32', 'W1RFVI', 'T147Y6', '415001', 'C11BK2', 'J1RFV1', '1111W1', '213FV3', '919023', 'A180C7', '1111S1', '811HK4', 'R1CS93', 'P1RFV4', 'F11AK8', '01BUM1', 'T11AK8', '013026', '511096', 'G13FV7', '41E969', 'A1RFV8', 'Z1RFV2', 'M11AK5', 'C11BK7', 'L11AK8', 'L11AK1', 'B19F3X']
  Model_Year: ['K', 'M', 'L', 'R', 'P', 'W', 'N', 'J', 'H', 'V', 'S', 'X', '1', 'T', '7', 'C', '9', '5', '4', '8', '3', 'F', '6', '2', 'B', 'E', 'Y', 'D', 'G']
  Plant_Code: ['1', 'C', 'D', '3', '0', 'U', '5', '8', '6', 'W', 'J', '9', 'G', '7', 'B', 'M', '2', '4', ' ', 'Z', 'A', 'L', 'Y', 'T']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,YARIS,4.0,HATCHBACK,K,SE,GCC,5.0,MR2,K19F35,K,1,042956
1,TOYOTA,RAV4,4.0,SUV,W,LE HEV,GCC,5.0,2T3,W1RFV6,M,C,135629
2,TOYOTA,YARIS,4.0,HATCHBACK,K,E,GCC,5.0,MR2,K19F32,L,1,062387
3,TOYOTA,RAV4,4.0,SUV,Z,EX,GCC,5.0,JTD,Z13FV3,M,D,080739
4,TOYOTA,RAV4,4.0,SUV,Z,EX,GCC,5.0,JTD,Z13FV8,R,D,126380
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5902,TOYOTA,CAMRY HYBRID,4.0,SEDAN,A,GLE,GCC,NaN,JTN,A14CK0,S,3,023751
5903,TOYOTA,CAMRY HYBRID,4.0,SEDAN,A,GLE,GCC,NaN,JTN,A14CK8,T,3,072343
5904,TOYOTA,RAV4,4.0,SUV,Z,EX,GCC,NaN,JTD,Z13FV0,N,D,093269
5905,TOYOTA,YARIS,4.0,HATCHBACK,K,SE,GCC,NaN,MR2,K19F39,H,1,021875
5906,TOYOTA,CAMRY HYBRID,4.0,SEDAN,A,XLE,GCC,NaN,JTN,A14CK5,S,3,029562

====================================================================================================
pos5: 3
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'BZ4X', 'COROLLA', 'HILUX', 'TERCEL', '2023', 'RAV4', 'COROLLA 1.5', 'BZ3X', 'TOYOTA COROLLA', 'AVALON', 'HIACE', 'C-HR', 'BZ 4', 'COROLLA 1.3', 'RAV 4', 'COASTER', 'RUSH', 'LAND CRUISER', 'كورولا 1.3', 'CROWN V', 'TOYOTA LAND CRUISER', 'BZ46', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'STATION', 'SALOON', 'BUS', 'MINI BUS', 'PICKUP']
  pos4: ['5', 'D', 'B', '3', 'C', 'J', 'F', 'K', 'G', 'S', 'T', 'L', '7', '6', 'H', 'R', '9', 'V', 'N', '0']
  trim: ['STD', 'PRO', 'XLI', 'DLX', 'XLI MID', 'S', 'GLI', 'STATION', 'SE', 'EX', 'GLE', 'LE STD', 'EXR', 'LE', 'XLI EXECUTIVE', 'S PLUS', 'GX', 'BASE', 'STD (NON GCC)', 'XLI EXECUTIVE MR', 'LWB', 'SE+', 'DL', 'GLE-X HEV 40TH ANNIV', 'XSE (NON GCC)', 'DX', 'GL', 'SPORT', '1', 'GLE HEV', 'X', 'GLI HEV', 'DLS', '2', 'SED']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['6T1', 'LVG', 'RKL', 'JTB', '4T1', 'LFM', '4T2', 'JL5', 'JT8', 'WMA', 'VF3', 'JJ5', 'LFZ', 'JTE', 'MC2', '180', 'LVB', 'JT3', 'JTF', 'FJ4']
  VDS: ['53SK20', 'D31351', 'B30BE6', 'D31359', '33UNG0', 'B30BE7', '33YN87', '53EEB0', '53AEB1', 'B30BE0', '33UNE0', '53EL50', 'B30BEX', 'D31355', 'B31HKX', '53AEA1', '53XK20', 'B30EE9', 'B30BE8', '33UNE6', '53SK10', 'B30BE4', '53AEB2', 'B30BE9', '53AEBI', 'D31357', 'D31356', 'B30BE1', 'B30EE0', 'C31AK2', 'J34AF2', '53EEA0', 'B30BE2', 'B30EE4', 'F31AK7', 'D3DF60', 'D31353', 'D3DF64', 'C31AK6', 'B30BE3', '33RN85', 'C31AK7', 'B30BE5', 'J34AF6', 'J34AF7', 'B31HK9', 'D31352', '535K20', 'K31AK7', '53XH10', '53EEBO', 'B3J6P2', 'D31354', 'J34AFX', 'C31AK3', 'G31AK0', 'B30EE3', 'J34AFI', 'J34AF1', 'B3J6P0', 'B31HK7', 'S31AK5', 'G31AK5', 'B30EE7', '53AFB1', 'B30EE8', 'B31HK1', 'F31AK5', 'B3E6P5', 'K31AK0', 'B3J6P3', 'C31AK8', 'F31AKX', '534K20', 'F31AK3', '33UNGO', 'D31350', 'T36ZZZ', 'L35GY8', 'D3135X', 'B3J6P7', 'B30EE2', 'G31AKX', 'B308EX', 'C31AK4', 'B30EE1', 'B3J6P6', 'B30EE6', 'B3E6P4', '53EE80', '73FM49', '63AL59', '63AL55', 'H30934', 'B30EE5', 'B3E6P3', 'R3NLT1', 'B31HK0', 'C31AK5', '93220N', '53JSF5', 'V3JBB3', 'H309JX', 'C31AKX', 'J34AF8', 'L373J0', 'B31HK4', 'N38ZZ6', 'B31HK5', 'B30EEX', 'B308E3', '33UNEQ', 'B3J6P5', '033500', '63AL46', 'B3G6P3', 'G31AK6', 'B31HK8', '33RNA4']
  Model_Year: ['W', 'P', 'L', 'V', 'X', 'M', 'J', 'R', 'N', 'S', 'G', 'T', 'E', '4', 'F', 'H', 'D', '6', 'Y', '2', '3', '8', 'B', 'K', '9', 'C']
  Plant_Code: ['X', 'G', '0', '1', '3', 'U', '9', '5', 'P', 'R', '4', 'M', 'S', 'D', 'K', 'J', '6', 'Y']
  Serial_Number: ['350893', '006216', '003632', '006786', '001175', '003106', '012745', '004584', '342144', '062137', '005541', '033800', '063188', '067448', '357877', '001687', '006204', '342520', '336865', '502113', '191808', '651486', '011437', '053542', '339444', '054407', '010636', '003519', '002361', '004216', '004931', '168801', '170412', '001831', '016620', '004195', '000720', '353495', '005926', '345863', '061613', '064463', '184134', '003352', '006468', '198620', '004891', '184195', '057259', '006059', '020182', '003477', '168855', '004413', '006186', '006520', '022924', '001596', '351174', '013052', '013842', '020530', '033348', '005164', '005918', '004165', '018617', '019123', '193850', '343780', '038096', '001075', '342926', '035150', '067863', '339106', '196617', '337751', '001297', '342771', '002260', '003981', '036052', '012970', '036142', '337671', '349735', '343532', '197959', '040775', '194482', '026933', '001723', '041885', '014006', '540341', '007138', '198416', '001651', '005028', '068376', '062556', '091431', '197053', '005958', '005045', '001633', '016226', '019945', '004192', '048155', '062419', '009253', '361276', '022044', '033808', '338546', '000974', '003243', '348662', '005964', '003591', '033004', '035874', '352729', '016206', '004574', '060304', '006854', '063397', '005404', '045678', '009017', '001087', '006051', '009234', '073455', '002592', '339288', '002092', '056496', '342737', '021700', '010064', '188933', '001881', '007033', '196486', '017836', '003136', '003245', '359028', '031070', '003881', '356852', '173989', '002501', '017868', '006128', '603124', '019395', '194285', '002946', '003460', '003307', '349223', '057643', '337396', '003890', '054053', '550359', '360078', '047983', '003022', '339407', '004047', '015135', '354768', '169272', '020315', '348167', '001664', '349086', '190788', '002867', '001539', '522143', '002090', '004173', '006973', '336628', '167621', '002552', '061595', '031037', '000963', '044495', '174102', '062875', '008231', '003397', '003903', '012965', '344811', '337151', '336969', '587044', '004134', '013716', '023842', '006954', '361122', '348858', '060850', '036416', '010013', '003619', '006158', '339783', '019463', '001139', '000273', '361885', '358560', '002931', '171163', '005123', '059492', '358743', '188746', '035288', '003616', '166214', '003718', '073892', '009721', '006361', '020414', '355388', '056565', '022257', '027962', '353329', '002234', '001103', '169343', '027269', '346198', '003759', 'D01004', '022041', '353620', '004005', '006218', '067504', '050288', '002887', '025394', '052235', '652312', '185039', '346788', '013093', '337164', '035287', '338120', '004563', '021113', '055725', '003746', '004462', '352857', '071279', '014922', '050499', '003626', '022680', '032526', '037056', '024438', '359233', '008753', '025901', '116335', '001092', '009410', '340056', '562785', '191373', '067132', '356724', '360267', '017711', '191997', '531817', '006905', '011645', '013003', '028330', '006021', '058691', '194826', '013927', '007594', '346974', '177292', '354765', '064372', '001471', '000533', '009923', '196223', '035588', '078119', '337057', '174187', '039012', '024506', '002124', '019235', '342184', '002190', '016394', 'L10639', '001778', '342106', '347240', '337447', '006135', '000455', '003363', '190533', '053963', '037120', '002509', '195887', '027588', '071574', '017040', '348313', '007351', '507334', '350480', '006488', '027949', '049262', '351683', '001514', '005632', '067589', '053889', '003939', '008581', '563061', '065221', '001593', '003599', '019459', '340246', '000904', '052317', '013237', '024449', '034796', '002643', '546914', '009004', '006740', '346625', '339354', '014082', '004068', '032154', '002845', '011423', '652405', '002751', '001174', '336227', '052486', '005327', '003986', '022274', '005040', '071843', '357632', '194176', '001854', '062480', '006182', '066558', '004489', '001021', '025726', '360793', '004981', '049765', '171804', '026274', '000898', '005706', '006177', '001039', '007150', '003455', '010562', '002791', '006545', '505384', '339803', '009766', '018707', '073074', '007189', '001727', '004241', '006247', '014553', '008467', '349951', '005651', '001672', '361147', '068163', '003446', '361113', '171604', '066952', '066962', '593230', '058214', '001076', '012889', '009429', '338654', '051565', '340279', 'D01441', '358447', '017863', 'P20607', '068255', '344323', '001311', '056392', '035719', '360461', '346263', '005521', '036393', '013406', '002664', '004866', '022807', '604314', '168187', 'D00850', '018751', '344704', '183139', '522957', '351831', '033745', '010306', '004059', '005591', '001115', '170766', '018096', '554067', '052649', 'D03600', '056234', '003846', '336906', '189651', '005488', '007425', '002064', '012878', '000131', '014344', '048123', '036137', '011174', '005924', '006084', '341629', '019016', '339539', '337758', '284991', '003987', '013394', '060404', '001717', '353422', '002890', '065936', '015722', '004301', '055982', '358642', '005370', '023367', '006372', '185978', '010176', '001263', '173829', '011773', '342706', '360926', '522160', '009280', 'C00385', '025190', '347670', '020626', '171759', '196075', '196834', '016468', '337874', '052916', '530657', '025290', '194228', '057593', '177088', '198543', '001517', '003416', '346299', '012951', '004486', '066055', '357918', '036092', '013203', '533608', '357584', '002968', '336063', '003018', '001694', '361558', '001729', '349714', '001469', 'D00136', '019806', '542396', '001969', '006708', '195769', '003783', '005633', '002091', '010162', '010105', '012260', 'F02393', '017591', '002256', '004381', '340414', '002495', '005840', 'J10030', '356625', '035931', '004758', '337047', '358144', '063895', '016514', '003327', '001358', '010321', '006522', '064270', '002380', '351414', '010065', '348341', '190298', '048283', '002231', '018463', '350663', '001691', '004181', '176362', '044723', '001043', '349555', '359522', '002455', '361483', '361051', '054474', '001242', '065232', '171962', '002291', '032380', '025427', '001152', '336761', '008999', '005056', '002600', '004852', '004400', '002585', '005144', '360764', '019903', '014270', '057519', '004199', '002494', '058438', '166685', '058419', '003370', '056975', '004979', '005942', '359019', '056001', '341407', '345833', '350788', '002787', '177651', '016575', '006896', '036559', '347705', '342747', '010001', '003872', '359383', '012305', '011663', '343224', '001883', '355640', '019336', '035708', '359786', '062496', '005986', '156576', '067815', '348358', '003689', '003917', '020670', '360732', '345325', 'J10021', '337026', '191156', '059606', '001396', '003244', '064882', '065666', '007565', '041946', '197683', '190426', '003708', '538521', '000000', '198214', '062850', '027440', '012975', '344074', '012290', 'M10163', '015353', '042384', '336703', '348864', '064220', '010583', '001567', '012835', '010762', '022151', '168202', '515812', '017793', '357250', '050212', '064041', '358246', '134854', '001603', '010609', '002171', '002929', '023698', '001896', '030814', '001046', '012343', '194937', '197944', '580430', '341726', '002616', '048231', '008220', '056509', '001244', '187174', '009794', '014008', '350533', '068486', '002189', '011944', '357306', '024850', '002811', '012704', '013096', '049815', '003409', '339292', '001726', '002269', '057004', '190783', '042266', '344006', '172304', '355519', '005245', '034556', '344744', '001836', '166743', '359936', '018567', '011685', '003354', '001589', '003242', '078729', '006534', '008966', '017687', '337595', '001269', '340545', '196918', '011206', '034174', '063574', '052365', '007215', '005026', '002388', '350375', '346024', '054849', '030181', '014062', '019959', '336591', '001201', '167872', '235811', '001011', '350213', '351148', '015563', '053208', '527017', '025391', '006332', '005467', '349178', '057694', '170619', '001762', '061763', '077798', '340582', '035486', '000436', '017448', '503770', '010234', '029783', '196543', '349439', '001149', '066864', '359607', '028650', '341793', '064829', '346936', '004010', '183027', '002375', '004223', '337769', '347696', '003820', '361964', '068167', '001579', '036350', '060327', '018290', '003671', '004579', '008378', 'K00815', '051058', '001766', '348076', '357359', '006163', '036242', '552257', '348804', '016323', '338060', '010635', '356572', '001030', '002077', '011483', '003777', '041577', '234567', '006753', '004081', '113886', '347601', '360907', '025431', '003311', '012267', '166715', '057712', '350669', '002285', '005559', '005381', '064316', '347855', '358563', '338249', '004088', '064723', '012360', '001604', '006491', '005882', '002677', '000983', 'L10105', '349690', '064895', '003911', '003970', '009239', '019720', '548493', '036469', '062187', '043683', '187583', '005577', '056909', '014991', '168911', '003473', '348599', '353232', '055621', '002970', '018333', '348585', '166735', '001203', '009095', '501655', '003362', '354816', '034008', '002235', '516025', '012821', '011806', '001452', '006680', '009158', '002145', '024001', '003227', '004037', '000228', '341036', '001703', '007149', '016247', '002883', '005682']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,5,STD,GCC,4.0,6T1,53SK20,W,X,350893
1,TOYOTA,BZ4X,0.0,SUV,D,PRO,GCC,5.0,LVG,D31351,P,G,006216
2,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,RKL,B30BE6,L,0,003632
3,TOYOTA,BZ4X,0.0,SUV,D,PRO,GCC,5.0,LVG,D31359,P,G,006786
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,GCC,2.0,JTB,33UNG0,W,0,001175
...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,RKL,B30BE4,L,0,001703
929,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,RKL,B30BE8,N,0,007149
930,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,RKL,B30BE5,P,0,016247
931,TOYOTA,COROLLA,4.0,SEDAN,B,1,GCC,NaN,RKL,B30BE4,L,0,002883
932,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,RKL,B30BE7,M,0,005682

====================================================================================================
pos5: C
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'AVANZA', 'CROWN', 'COROLLA CROSS', 'TUNDRA', 'HILUX', 'LAND CRUISER', 'CAMRY', 'بريفيا', 'RAV4', 'PRIUS', 'HIACE', 'TOYOTA PRIUS', 'TACOMA', 'SIENNA', 'SY150T', 'GRANVIA', 'RUSH', 'ALLION', 'AVALON', 'FJ CRUISER', 'FORTUNER', 'YARIS', 'افنزا', 'CORONA', 'COROLLA 1.3', 'TUNDRA (PICK UP)', 'TERCEL', 'INNOVA', 'PRADO', 'HIGHLANDER', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'MPV', 'SUV- CROSSOVER', 'PICK UP DOUBLE CAB', 'SUV', 'STATION', 'VAN', 'PANEL VAN', 'MINI BUS HIGH ROOF', 'MOTORCYCLE', 'PICK UP SINGLE CAB', 'SALOON', 'PICKUP', 'HATCHBACK', 'PICK UP']
  pos4: ['B', 'M', 'A', 'K', 'N', '1', '8', 'P', 'J', 'Z', 'V', 'L', '5', 'U', 'C', 'R', 'E', 'W', 'T', 'Y', 'S', '7', 'D', 'F']
  trim: ['XLI', 'STD (NON GCC)', 'LE', 'SE', 'PREMIUM', 'XL', 'XLI MID', 'XLI POWER OPT', '1794 EDITION (NON GCC)', 'XLE', 'DLX', 'VXR', 'GLI', 'CREWMAX CAPSTONE (NON GCC)', 'GLE', 'GLX', 'STD', 'EXR', 'SEDAN', 'GL', 'S', 'DLS', 'SR5 (NON GCC)', 'XLE (NON GCC)', 'PLATINUM', 'E', 'GR SPORT', 'SAFARI', 'DL', 'GLI TOP', 'BASE', 'XLI TOP', 'SR', 'EX', 'GLS', '45', 'GXR', 'GLE HEV', 'GV', 'GL2', '60TH', 'DX', 'LE HEV', 'YA', 'PICK UP', 'ADVENTURE', '1', '1794 EDITION (NON GC', 'CREWMAX CAPSTONE (NO']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['RKL', 'MHK', 'JTD', 'JTK', '5TF', 'LA7', 'JTM', 'ME4', 'U8Q', 'JHH', 'JT3', 'MA3', 'JL6', '3TY', 'LFM', '2C4', 'LVG', 'MLH', 'WMW', 'LK1', '3N1', 'JL7', 'JJ7', 'L3H', 'MBJ', 'KMF', '1G1', 'JN1', 'LZZ', 'LAZ', 'JH2', 'JS2', 'VF7', 'JT2', 'LNB', 'KNM', '5TD', '1GC']
  VDS: ['BC42E8', 'BC42E2', 'BC42E0', 'MC13FX', 'BC42E7', 'ACABF5', 'KCBAG1', 'BC42E9', 'BC42E5', 'BC42E1', 'BC42E6', 'MC13F7', 'NC5DBX', 'ACABF6', 'BC42E4', 'ACABFX', 'MC13F6', 'MC13F5', 'MC13F9', 'BC42EX', 'MC13F3', 'MC13F4', 'MC13F8', 'BC42E3', '1CUG30', 'MC13F1', 'MC12F6', 'MC12F3', 'AC7BJ4', 'MC13F0', '8C42E1', 'KCAAG8', 'PC5DB9', 'MC5DB6', 'ACABF2', 'NC5DB9', 'MC5DB8', 'KCAAG5', 'JC5DB7', 'MC13F2', 'KCBAG0', '8C42E7', 'MC5DB4', 'KCBAG3', 'KC20F7', 'ZCKF5Q', 'ACABF9', 'VC5DB8', 'LCN1F1', 'AC11R8', '5C3AV4', 'ACAAU6', 'NC2B16', 'ACAAUX', 'ZCP2F6', 'MC12F5', 'ACABF0', 'MC12F4', 'BCE6J3', 'MC12F9', 'MC12F2', 'PC5DB8', 'UCN1H5', 'ACJ4H1', 'KCAAG9', '8C42E5', 'MC12F1', 'LC5LN2', 'JC5ECX', 'CC1BR5', 'RC1BG6', 'KCBAG9', 'KCAAGX', 'BC74K2', 'KCAAG0', 'PC5DB0', 'AC7BJ7', 'ACABF1', 'KCBAG4', 'MC5DB5', 'MC12F0', 'PC5691', 'ZC3C52', 'CC1BR7', '8C42E8', 'MC5DB1', 'CC1BR0', 'NC5DB0', 'ZCK1H2', 'EC42E3', 'PCKL98', 'ACABF7', 'VC5DB7', 'KCBAG8', 'KCAAG6', 'KCBAG2', 'KC4BS8', 'ZCK1H9', 'ACABF8', 'AC7BJ3', 'MC12FX', 'AC22C6', '8C42E0', 'JC5DB5', 'MC12F8', 'VC5DB1', 'CC1BR9', 'KCAAG4', 'ZCP2H5', 'BC11E4', 'BCE1J7', 'KC20D3', 'KCAAG3', 'CC1BR6', '8CE1K7', 'JC5DB0', '8C42EX', 'ECABA0', 'KCBAGX', 'PC5DB6', 'ACABF3', 'BCELK4', 'NC5EC1', 'AC22C2', 'WC5DB0', 'KC311A', 'BC81S7', 'TC31E9', 'KC20FX', '8C42E9', 'ZCZ7JA', 'TC31E1', 'MC12F7', 'AC1DM8', 'PC5DB7', '8C42E6', 'ACABF4', 'YCN1HX', 'ZCS7JP', 'ACAAJ4', 'ZCN1FX', '5C3AV7', 'JC5EC3', 'UCK1H0', 'PC5DB1', 'ZCP2F5', 'AC7BJ0', 'ZC5ST2', '5C3AV6', 'UCK1H5', 'WC5DB9', 'KCBAG7', 'BCE1KX', 'KCAAG7', 'VC5DB3', 'CC13C6', 'JC5DB1', 'MCK3H2', '8CCVD0', 'PC5DB2', 'BCE1J1', '1CU837', 'VC5DB9', 'KCAAGO', 'SC87C2', 'ZCP2HX', 'VC31F0', 'CC1BR2', 'ZC8B20', 'CC1BR8', '8C42E3', '8CCVD9', 'MC5DB9', 'KCAAG2', 'CC1BR4', '1CU835', '7CNFU6', 'AC7BJ6', 'EC42E5', '8CE1K3', 'JC5DB4', 'PC5DB5', 'PCKL9X', 'WC5EC5', 'AC22C4', 'BC53L3', 'KC206X', 'VC5DB2', 'JC5DB9', 'BC42EB', 'CC1CX2', 'ACABFO', 'BC42R5', 'MCUBK9', 'KCBAG5', 'CC42H9', 'AC7BJ9', 'AC1DM7', 'ZCL2H9', 'ZCP2F2', 'BCE1J0', 'VC5DB6', 'NC5DB3', 'PC5DB4', 'ACAAU7', 'VC5DB4', 'MC5AB5', 'DCRFH0', 'WC5DBX', 'SC79M9', 'MCK3H3', 'RC1BG7', 'NC5DB6', 'ZCN1F0', 'CC1BR3', 'KC20G4', 'BC42EJ', 'JC5DB8', 'AC22CX', 'FC24H0', 'ACAB52', 'ACAAU3', 'BC74K7']
  Model_Year: ['B', 'F', 'P', 'D', 'S', 'C', 'R', '8', 'N', 'T', 'M', '7', 'K', 'J', 'E', 'H', 'G', 'L', '2', '6', 'A', '5', '9', 'Y', 'W']
  Plant_Code: ['4', 'K', '3', '5', '0', 'X', 'A', 'W', '1', 'D', 'T', 'R', 'G', 'L', '8', 'E', 'U', 'F', 'C', '6', 'H', 'J', 'P', 'S']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,RKL,BC42E8,B,4,580533
1,TOYOTA,COROLLA,4.0,SEDAN,B,STD (NON GCC),GCC,4.0,RKL,BC42E2,B,4,507898
2,TOYOTA,COROLLA,4.0,SEDAN,B,STD (NON GCC),GCC,4.0,RKL,BC42E0,B,4,500979
3,TOYOTA,COROLLA,4.0,SEDAN,B,LE,GCC,4.0,RKL,BC42E2,B,4,503382
4,TOYOTA,AVANZA,4.0,MPV,M,SE,GCC,5.0,MHK,MC13FX,F,K,019527
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4199,TOYOTA,COROLLA,4.0,SEDAN,B,STD (NON GCC),GCC,NaN,RKL,BC42E0,B,4,501095
4200,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,RKL,BC42E6,D,4,590075
4201,TOYOTA,COROLLA,4.0,SEDAN,B,XLI POWER OPT,GCC,NaN,RKL,BC42E7,C,4,516193
4202,TOYOTA,AVANZA,4.0,SUV,M,SE,GCC,NaN,MHK,MC13F0,F,K,018628
4203,TOYOTA,COROLLA,4.0,SEDAN,B,STD (NON GCC),GCC,NaN,RKL,BC42E4,B,4,501973

====================================================================================================
pos5: J
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER PICK UP', 'LAND CRUISER', 'IQ', 'LAND CRUISER PICKUP 70', 'PRADO', '4RUNNER', 'RAV4', '86', 'TERCEL', 'COROLLA', 'HILUX', 'TUNDRA', 'YARIS', 'SCION', 'CAMRY', 'TOYOTA', 'LAND CRUISER SINGLE-CABIN PICK', 'TOYOTA LAND CRUISER', 'لاند كروزر', '2012', 'SIENNA', 'TOYOTA SCION', 'PRIUS', 'TOYOTA IQ', 'ZELAS', 'PICK UP CABIN', 'AVALON', 'LAND CRUISER GXR', 'TOYOTA SQUIN', 'YARIS HATCHBACK', 'DYNA', 'RAIZE', 'LAND CRUISER/STD EX PICKUP', 'LAND CRUISER PICKUP', 'COUPE', 'PICKUP', 'CAMRY HYBRID', 'TOYOTA 86']
  bodyType: ['PICK UP', 'SUV', 'HATCHBACK', 'PICKUP', 'PICK UP SINGLE CAB', 'COUPE', 'SEDAN', 'PICK UP DOUBLE CAB', 'MPV', 'SALOON', 'STATION', 'TRUCK']
  pos4: ['L', 'H', 'J', 'D', 'B', 'F', 'R', '0', 'W', 'E', 'C', '7', '8', 'S', 'G', 'V', 'A', 'Y', '6']
  trim: ['STD', 'GX', 'VX', 'STD (NON GCC)', 'GXR TOP', 'VXR BASE', 'GXR', 'LX', 'SR5 (NON GCC)', 'BE', 'GT', 'ST', 'LX AC PWR OPT', 'XLI MID', 'DLX', 'GLX', 'DL', 'VXR TOP LTH', 'GXR FMST', 'XLI', 'EXR', 'SE', 'SAFARI', 'GXR TOP DMST', 'GXR TOP FMST', 'E', 'EX', '2400', '1500', '6', 'GL', 'LAND CRUSIER', 'XE 4WD', 'STATION1', 'VXR MID', 'VXR TOP', 'GXR SOD D/AC AW', 'BASE', 'SC', 'FULL OPTION', 'STD AC', 'GXR2', 'DLS', 'AUTOMATIC', '1500 CREWCAB SLE Z71', 'LE (NON GCC)', 'S', 'GLS TOP', 'LS', 'N', 'MID', 'GLI', 'CAR TRIM', 'LX WIDE TYRES', '4', 'ZX', 'TRIM', 'DLX TOP', 'SGLX', 'LE PLATINUM CITY', 'SLT', 'STANDARD', 'PICKUP', 'S T1', 'GXR MID', '60TH', 'PREMIER', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTF', 'JT3', 'JTE', 'JTN', 'JTG', 'JTM', 'JT2', 'KN9', '2CN', 'KNC', 'JHE', 'LVG', 'VF3', 'JTH', 'JTC', 'JIF', 'LCO', 'JD2', '1C4', 'KL1', 'LSJ', 'JT6', 'KMH', 'JTR', 'LFM', 'JHG', 'AUS', 'JTJ', 'JT4', 'SKF', '6T1']
  VDS: ['LJ73J1', 'HJ09J7', 'HJ0936', 'HJ09JX', 'HJ09J1', 'HJ09J6', 'HJ09J4', 'JJXB01', 'LJ71J9', 'HJ09J9', 'HJ01J1', 'LJ73J7', 'HJ09J5', 'HJ09J3', 'LJ73J9', 'HJ09J2', 'LJ73J8', 'JJXB03', 'HJ09J8', 'LJ73J4', 'LJ73J5', 'HJ09J0', 'HJ01J9', 'JJXB09', 'LJ73JX', 'JJXB05', 'HJ0932', 'DJREV9', 'JJXB06', 'LJ71JX', 'LJ73J2', 'JJXB04', 'HJ01J5', 'HJ0939', 'LJ73J3', 'LJ73J0', 'BJ53L8', 'LJ71J7', 'JJREV4', 'HJ01J3', 'BJ13E0', 'FJ71JX', 'BJ13E1', 'RJREV6', 'LJ71J3', 'LJ73J6', 'BJ53L2', 'JJREV6', '0J4MCD', 'LJ71J2', 'BJ18U8', 'BJ53LX', 'HJ01J8', 'RJREV4', 'RJREV2', 'WJ2728', 'HJ01J7', 'JJXB0X', 'FJ71J2', 'EJ13EX', 'BJ13E5', 'LJ71J0', 'JJXB02', 'EJ13E8', 'FJ60G2', 'HJ01J6', 'HJ01JX', 'BJE239', 'LJ71J5', 'HJ01J2', 'HJ59J1', 'EJ13E3', 'FJ60G4', 'BJ13E9', 'HJ01J0', 'CJE237', 'BJ53L4', 'HJ01J4', 'BJ13E4', '7JNFU6', 'JJXB07', 'BJ53L9', 'JJXB00', 'HJ85J4', 'HJO9J0', 'LJ71J1', 'EJ13E5', 'RJREV1', 'WJZ74A', 'FJ60G5', 'LJ71J4', '8J4665', 'HJ0915', 'EJ13E2', 'SJZ74A', 'RJREV0', 'JJXB08', 'CJE735', 'LJ7336', 'BJ13E7', 'HJ0934', 'BJ13E6', 'HJ0931', 'BJ53L1', 'WJZ76A', 'BJ13E8', 'HJ0938', 'EJ5CDX', 'BJ53L6', 'BJ53L3', 'GJ2110', 'FJ71J1', 'LJ71J6', 'FJ71J6', 'WJX74A', 'EJ13E7', 'FJ71J0', 'DJ81W4', 'EJ13E6', 'WJX76A', 'BJ53L7', 'VJ73J1', 'HJ85J3', 'HJ0937', '8J53L3', 'EJ13E0', 'HJXEN7', 'FJ71J4', 'EJ13E4', 'FJ71J9', 'DJ81W1', 'CJ6B15', 'HJ85J2', 'RJREVX', 'FJ71J7', 'HJ0935', 'WJ4W96', 'BJ53L5', 'BJ13E3', 'RJREV8', 'BJ13E2', 'HJ0912', 'HJO9J4', 'RJREV9', 'HJ0933', 'SJ8IVP', 'BJ53L0', 'HJ0919', 'LJ71J8', 'FJ60G0', 'BJI3E9', 'DJ81W2', 'JJREV2', 'AJ54K5', 'JJX801', 'HJ85J5', 'HJ05J6', 'HJ0SJ9', 'CJE232', 'YJ2274', 'FJ60G8', 'BJ3355', 'HJQ8JS', 'HJ08J1', 'BJ13EX', 'RJREVO', 'EJ13E1', 'WJ2764', 'DJREV1', 'CJE235', 'WJ2727', 'WJZ72A', 'BJRBZ9', 'LJ731X', 'GJKFWC', 'HJO9J9', '6JKFWC', 'HJ85JX', 'FJ71J8', 'FJ60GX', 'RJREV3', 'FJ71J3', 'EJ13E9', 'HJ08J8', 'FJ60V8', 'CJE234', 'HJ85J0', 'HJ08J9', 'SJN3BC', '8J53LX', 'HJ85J6', 'LJ7335', 'BJ22K6', 'CJE730']
  Model_Year: ['1', 'Y', '6', '3', '2', 'D', '7', '5', '9', '8', 'C', '4', 'X', 'E', 'J', 'H', 'G', 'P', 'A', 'L', 'F', 'T', 'B', 'K', 'S', 'V', 'M', 'R', 'N']
  Plant_Code: ['6', '0', '5', 'J', '8', '7', '1', '3', 'D', 'K', '4', 'G', '2', 'W', 'C', 'Z', 'U', 'S', 'L', 'N', 'T', 'X']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP,L,STD,GCC,2.0,JTF,LJ73J1,1,6,005284
1,TOYOTA,LAND CRUISER,6.0,SUV,H,GX,GCC,5.0,JT3,HJ09J7,Y,0,033721
2,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTE,HJ09J7,6,5,143496
3,TOYOTA,LAND CRUISER,6.0,SUV,H,VX,GCC,5.0,JTE,HJ0936,3,5,071850
4,TOYOTA,LAND CRUISER,6.0,SUV,H,VX,GCC,5.0,JTE,HJ09JX,2,5,026389
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,TOYOTA,LAND CRUISER,6.0,SUV,H,VX,GCC,NaN,JTE,HJ09J6,7,5,165233
5561,TOYOTA,LAND CRUISER,6.0,SUV,H,VX,GCC,NaN,JTE,HJ09J3,5,5,118643
5562,TOYOTA,LAND CRUISER,6.0,SUV,H,VX,GCC,NaN,JTE,HJ09J9,7,5,178011
5563,TOYOTA,LAND CRUISER,4.0,SUV,H,VX,GCC,NaN,JTE,HJ09J7,4,5,100242
5564,TOYOTA,LAND CRUISER,6.0,SUV,H,VX,GCC,NaN,JTE,HJ09J2,7,5,179064

====================================================================================================
pos5: H
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'PRADO', 'HILUX', 'C-HR', 'LAND CRUISER', 'MT 03', 'HIACE', 'CAMRY', 'CHR', 'SIENNA', 'COROLLA', 'YARIS', 'RUSH', 'CAMRY HYBRID']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'MOTORCYCLE', 'BUS', 'SEDAN', 'STATION', 'MPV', 'HATCHBACK']
  pos4: ['H', 'Y', 'G', 'C', 'B', 'N', 'K', '6', 'R', 'W', 'S', 'D', '1', 'F', 'P', '2']
  trim: ['PW CL', 'FABRIC', 'EX', 'VXR', 'DLX', 'GX', 'STD (NON GCC)', 'MID', 'XTREME', 'DL', 'GLX', 'BASE', 'EXR', 'GL', 'TX-L', 'GLI', 'ABC', 'LE (NON GCC)', 'TOP', '1', 'SE']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTE', 'SJK', 'JAA', 'JTN', 'NMT', 'JHE', 'WDA', 'KPB', 'MH3', 'JM3', 'KNC', 'JAC', 'LGF', 'WDD', 'JH2', 'WBA', 'JL5', '1G0', 'WVW', 'LVG']
  VDS: ['HH20V4', 'YH20V1', 'HH20VX', 'HH20V5', 'HH20V1', 'HH20V8', 'YH20V2', 'HH20V7', 'HH20V9', 'HH20V0', 'GH20V5', 'CH5CP0', 'GH20V4', 'BH9FJ9', 'NHR55E', 'YH20V7', 'YH20V8', 'GH20V9', 'HH20V6', 'YH20V6', 'GH20V8', 'YH20VX', 'KHMBX3', 'HH20V2', 'GH20V7', '6H20V7', 'KHMBXX', 'KHMBX7', 'YH20V0', 'GH20V6', 'YH20V5', 'KHMBX2', 'GH20V3', 'HH20V3', 'YH20V4', 'KHMBX5', 'YH20V9', 'GH20V2', 'YH20V3', 'KHMBX9', 'KHMBX8', 'GH20VX', 'KHMBX0', 'KHCAA7', 'KHMBX1', 'YH2076', 'BH2AW1', 'KHCAAX', 'RH21B2', 'WH8139', 'KHMBX6', 'SHX74C', 'DH88W4', '1HBJW0', 'KHMBX4', 'FH3CB1', 'DH88X7', '6H20V3', 'GH20V1', 'RH2237', 'GH20V0', 'PH5C57', 'BHJ6S3', 'KHCAA1', '2HNAG2', 'DH4CDX', 'BH42K5', 'BH42K2']
  Model_Year: ['2', '5', '4', '3', '1', 'J', 'K', 'W', 'L', 'M', '8', 'G', 'F', 'P', 'A', 'X', 'D', 'N', 'T', 'B', 'S', '6', '7']
  Plant_Code: ['6', '5', '0', 'A', '7', '1', 'R', 'L', 'P', 'K', 'F', 'J', 'S', 'W', 'G']
  Serial_Number: ['039141', '007287', '264198', '302728', '232402', '065614', '199318', '226257', '011064', '305114', '014005', '161089', '060120', '080666', '049543', '226744', '093698', '103876', '100214', '018367', '142054', '064090', '302327', '020768', '046533', '044878', '043889', '036665', '032613', '258226', '091154', '271424', '254842', '068501', '045774', '021449', '094594', '305615', '055470', '266325', '048916', '000703', '079144', '061642', '140253', '235600', '303090', '069779', '031078', '265008', '241578', '142297', '211798', '076478', '051575', '154602', '065774', '209005', '009489', '192349', '212319', '017323', '013578', '008900', '057228', '013757', '108409', '087978', '156044', '026218', '022886', '143396', '014710', '032965', '001816', '306512', '001330', '304132', '088941', '055760', '177313', '039284', '029727', '090421', '003895', '216396', '166369', '112746', '189161', '174206', '049208', '264332', '269326', '122632', '136443', '030534', '039737', '084235', '006874', '099041', '078028', '304665', '095192', '156794', '217176', '156803', '019287', '074504', '040069', '009834', '273991', '033629', '004916', '086242', '181307', '061157', '137006', '259067', '107776', '025577', '135545', '203353', '278745', '070879', '064742', '151181', '033705', '231710', '204018', '202973', '215709', '125305', '016091', '305168', '008624', '012311', '012236', '209480', '105969', '239429', '014545', '273716', '265685', '303679', '154725', '219442', '031236', '007556', '279227', '003930', '259295', '007129', '065286', '020635', '226286', '179027', '021073', '001286', '268937', '009602', '263592', '105766', '052973', '000683', '092476', '305185', '088596', '176609', '044963', '104830', '197239', '018025', '173861', '069167', '048433', '054697', '015588', '143770', '011347', '010370', '207411', '146495', '025463', '224109', '028354', '283841', '001168', '066104', '020636', '164451', '004022', '305104', '019042', '281540', '042657', '194607', '281671', '302299', '279669', '020367', '053320', '117929', '021695', '095216', '049229', '263767', '006464', '095012', '016810', '067166', '266509', '026715', '032124', '137434', '048911', '261153', '003515', '285405', '000636', '299471', '071883', '254710', '036392', '303401', '281282', '005454', '265412', '050640', '277151', '048225', '281577', '279690', '255666', '245901', '303395', '202186', '273912', '189823', '103639', '080753', '020924', '239406', '046369', '221954', '015194', '053527', '049147', '238087', '300649', '050634', '033774', '217422', '008693', '281109', '214804', '095284', '015697', '235737', '255518', '093996', '002809', '259564', '051824', '150339', '029487', '245809', '062887', '062824', '070304', '156363', '220738', '039979', '023550', '068180', '027960', '007638', '298542', '050707', '017693', '016275', '099651', '002525', '098197', '129410', '121995', '063894', '147184', '043764', '041578', '134149', '250108', '156490', '070782', '081326', '045803', '328796', '272278', '142629', '033371', '017790', '014887', '114575', '006703', '165469', '043025', '054667', '042935', '067779', '068653', '264656', '026362', '009674', '268559', '053788', '062925', '024272', '000531', '054693', '252857', '292270', '073171', '237824', '041832', '230305', '013498', '039752', '020812', '041288', '047449', '283050', '194387', '043062', '269906', '131263', '110220', '029236', '047163', '087798', '137406', '202709', '907312', '031590', '002218', '160623', '210254', '002333', '053682', '239222', '110952', '130834', '040323', '148319', '042732', '139750', '002165', '055895', '100443', '154549', '059602', '043538', '270266', '068592', '029212', '020254', '066142', '000377', '041224', '012621', '005721', '209110', '073801', '069529', '067645', '081532', '095135', '045883', '015883', '243676', '275892', '058614', '016012', '275372', '057543', '053925', '080947', '201729', '043367', '020692', '018969', '020680', '248966', '047281', '112637', '055962', '306142', '125315', '208386', '016961', '040484', '279283', '270623', '053457', '491460', '141664', '146944', '047143', '196968', '150833', '002939', '206677', '026864', '051851', '018809', '046281', '059212', '303530', '307291', '293072', '270773', '035194', '028004', '045971', '049305', '250570', '248514', '059575', '153525', '062755', '063059', '228573', '146062', '042259', '161302', '061724', '278967', '181084', '302629', '123171', '263953', '166515', '005688', '040914', '093396', '256115', '027906', '196880', '121368', '136259', '029913', '027793', '089840', '057615', '021304', '058779', '061567', '192782', '306338', '000382', '096633', 'G00038', '016236', '255931', '105758', '018196', '056336', '041522', '018813', '240729', '018151', '143221', '019828', '011498', '092934', '140944', '141626', '030150', '165018', '250325', '212897', '014550', '264024', '090557', '254348', '044738', '002716', '150672', '305938', '120062', '036008', '246861', '305300', '096249', '216483', '173992', '017310', '014742', '058215', '138964', '049782', '055890', '011978', '284052', '281175', '017576', '132285', '175006', '265408', '090569', '044727', '241103', '265717', '169673', '063217', '016175', '542534', '286065', '031809', '012302', '148988', '007572', '002225', '007519', '033711', '225435', '041373', '302039', '211721', '054669', '260863', '029837', '140097', '268904', '008405', '068238', '007483', '150440', '217140', '304912', '002642', '270792', '300121', '064069', '075573', '043715', '299355', '104469', '267023', '006780', '089590', '056293', '213168', '075892', '016626', '288449', '122209', '000238', '270353', '072807', '200041', '299867', '040590', '032646', '284434', '129316', '028187', '106992', '040831', '077302', '019360', '236997', '238240', '029217', '032196', '023625', '302167', '140667', '030672', '151128', '304750', '061113', '271083', '056947', '019135', '028057', '009758', '260317', '089980', '062601', '167229', '018982', '236817', '084861', '266016', '013528', '026121', '044375', '031612', '027942', '275870', '219746', '118196', '030232', '002547', '092088', '218841', '048614', '263717', '279765', '254322', '098769', '204824', '149418', '004907', '001396', '264647', '043461', '004473', 'G00490', '267242', '092125', '032413', '192316', '014533', '260565', '051051', '065309', '015944', '044617', '215724', '012139', '004597', '048350', '154957', '148272', '008517', '203241', '094845', '061709', '197223', '036632', '043065', '234005', '001524', '040806', '023557', '020585', '261079', '300162', '276824', '275582', '044856', '284914', '014727', '027964', '051714', '006478', '304269', '058612', '037129', '272651', '027838', '019351', '278800', '140828', '020338', '078174', '051930', '043158', '036295', '161119', '042043', '100003', '118810', '020780', '258546', '055358', '084225', '106113', '002121', '018049', '001415', '200015', '143343', '157356', '007381', '192533', '061158', '191722', '059444', '019674', '052513', '304773', '142332', '018264', '020691', '061732', '142027', '192839', '268448', '097133', '065690', '055505', '190348', '104580', '254877', '123953', '037585', '053499', '051620', '005357', '053437', '007564', '154617', '014091', '147845', '000888', '032107', '088100', '102920', '278962', '160250', '002847', '217339', '442389', '012121', '303259', '274570', '000158', '020178', '267719', '063084', '293238', '063312', '077819', '055402', '269373', '195148', '298337', '177295', '033561', '193028', '219051', '057259', '110178', '223918', '135293', '247562', '177011', '162830', '281589', '020164', '000198', '253119', '082859', '029933', '209487', '294327', '084326', '076460', '131802', '000155', '108566', '017900', '159000', '051859', '271342', '134440', '046148', '080857', '085697', '307288', '237973', '021390', '045867', '057169', '000825', '193463', '239218', '102126', '047463', '264059', '192544', '035483', '247991', '020035', '021495', '046840', '030615', '046017', '042737', '065946', '167550', '087339', 'P25182', '048088', '005090', '034417', '218537', '274804', '200092', '002669', '156331', '083361', '051654', '266097', '316708', '054995', '299024', '202420', '062599', '012282', '007384', '062136', '002168', '007461', '069051', '066093', '056980', '154669', '033213', '019232', '122680', '018095', '005373', '012758', '014359', '060303', '007686', '016501', '047819', '175346', '101372', '280272', '009595', '174803', '130625', '034062', '023321', '265482', '275210', '6HGKKA', '013340', '051622', '270118', '143233', '279585', '212400', '032148', '181937', '265681', '266581', '036770', '005135', '046742', '285035', '252643', '002289', '092238', '051721', '124428', '215110', '283335', '146071', '084194', '116888', '061631', '126830', '191977', '033844', '195133', '025534', '281248', '215576', '102970', '256063', '194296', '020067', '080065', '223728', '282877', '033083', '272743', '003233', '008665', '306010', '276354', '287345', '054378', '179640', '058646', '000226', '000396', '216755', '302917', '006617', '002869', '264748', '016339', '142325', '062686', '012050', '283645', '031166', '303919', '009229', '001578', '051955', '007097', '006491', '190941', '096444', '002059', '209714', '040376', '026707', '156305', '193430', '014398', '223870', '165333', '122957', '005269', '002196', '000688', '117743', '171771', '156879', '171103', '054442', '126422', '088187', '006152', '170775', '018437', '046511', '031530', '072172', '210119', '077803', '204509', '116260', '258639', '205057', '061604', '068912', '054973', '266850', '072404', '163583', '024177', '058759', '026509', '146025', '135228', '055387', '304088', '118104', '052012', '215767', '150885', '248799', '089011', '306875', '040514', '103465', '001281', '131545', '201329', '252510', '098940', '056836', '061910', '273736', '221754', '004467', '040029', '056780', '147417', '259044', '305394', '026235', '019576', '041647', '190441', '194142', '117605', '051211', '217726', '080874', '182003', '194669', '030498', '271566', '010119', '302449', '031225', '138431', '209840', '015375', '276097', '253366', '006276', '020720', '274643', '043096', '281819', '006762', '283391', '023740', '179998', '007437', '077441', '235223', '043957', '042830', '142790', '284003', '040154', '007537', '275056', '091057', '023391', '029434', '253711', '015359', '029131', '062482', '203407', '011729', '023734', '039174', '062958', '057938', '292064', '073891', '190023', '021410', '149003', '098407', '270807', '027121', '107521', '301538', '059566', '303687', '063121', '040534', '054954', '012912', '193597', '266260', '001036', '256736', '061779', '099628', '076718', '005580', '302147', '021091', '188961', '020954', '039658', '002909', '194576', '055269', '302470', '273209', '062272', '006234', '059295', '004833', '265495', '070170', '276740', '214985', '299733', '146665', '173076', '009631', '192293', '057538', '136050', '171255', '194755', '050028', '002943', '028108', '042435', '057840', '062791', '107208', '019585', '005187', '047040', '154082', '007319', '223601', '014406', '134758', '156778', '018288', '014591', '010226', '046848', '051691', '275702', '146327', '271204', '270494', '001318', '063227', '072538', '007151', '236502', '204132', '305466', '042583', '002894', '273059', '205354', '075231', '117273', '069348', '019342', '006384', '176485', '008244', '132018', '267717', '029404', '125443', '015881', '153561', '063166', '103930', '040596', '058526', '131535']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,RAV4,4.0,SUV,H,PW CL,GCC,3.0,JTE,HH20V4,2,6,039141
1,TOYOTA,RAV4,4.0,SUV,Y,FABRIC,GCC,5.0,JTE,YH20V1,5,5,007287
2,TOYOTA,RAV4,4.0,SUV,H,PW CL,GCC,5.0,JTE,HH20VX,4,0,264198
3,TOYOTA,RAV4,4.0,SUV,H,FABRIC,GCC,5.0,JTE,HH20V5,5,0,302728
4,TOYOTA,RAV4,4.0,SUV,H,PW CL,GCC,3.0,JTE,HH20V1,3,0,232402
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,TOYOTA,RAV4,4.0,SUV,Y,FABRIC,GCC,NaN,JTE,YH20V9,5,0,063166
1137,TOYOTA,C-HR,4.0,SUV,K,GX,NON-GCC,NaN,NMT,KHMBX6,L,R,103930
1138,TOYOTA,C-HR,4.0,SUV,K,STD (NON GCC),NON-GCC,NaN,NMT,KHMBX4,J,R,040596
1139,TOYOTA,RAV4,4.0,SUV,Y,1,NON-GCC,NaN,JTE,YH20V1,4,0,058526
1140,TOYOTA,C-HR,4.0,SUV,K,GX,NON-GCC,NaN,NMT,KHMBX6,M,R,131535

====================================================================================================
pos5: Y
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TUNDRA', 'LAND CRUISER', 'SEQUOIA', 'DYNA', 'LAND CRUISE', 'COROLLA', 'FORTUNER', 'COASTER', 'ALTIS', 'COROLLA SEDAN', '2016', 'HIACE', 'CAMRY', 'C-HR', 'FJ CRUISER', 'DAINA', 'HILUX', 'LEVIN', 'TANDRA', 'TOYOTA LAND CRUISER', 'CELICA', 'RAV4', 'CHR']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'PICKUP', 'STATION', 'SEDAN', 'PICK UP SINGLE CAB', 'BUS', 'SALOON', 'PANEL VAN', 'COUPE', 'MINI BUS', 'LIGHT VEHICLE']
  pos4: ['K', 'H', 'D', 'A', 'U', 'B', 'P', 'R', 'Z', 'C', 'N', 'Y', 'F', 'J', 'G', 'M', 'E', '2', '1', 'L', '8', 'T', '0', 'S']
  trim: ['STD (NON GCC)', 'GXR', 'SR5 (NON GCC)', 'VXR', 'SR5 4X4', 'GXR GT', 'LIMITED MID', 'GXR TOP', 'STD', 'LIMITED 4X4', 'PLATINUM', 'EXR', 'LIMITED 4X2', 'TOP', 'SR5 4X2', 'GLX', 'LWB', 'GL', 'GLI', 'GX', 'LE', 'VX', 'LWB HIGH ROOF', 'SWB', 'SE', 'XLE', 'A', 'S', 'GXR SOD D/AC AW', 'DL', 'GLE', 'LIMITED TOP', 'XLI TOP', 'PLATINUM LUXURY 4X4', '1500', 'GXR MID', 'DLX', 'PREMIUM', 'SS', 'EX', 'SAFARI', 'XLI', 'HYBRID (NON GCC)', 'VXR BASE', 'VXR TOP', 'GXR TOP 60TH ANNIV. XTREME', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TF', 'JTM', '5TD', 'JT4', 'LVG', 'JN8', 'JTG', 'STD', 'STF', '2FU', 'LFM', 'JIM', '6TD', 'JTF', 'JTD', '1HD', 'JTC', 'NMT', 'STO', 'JNK', 'JMY', '5TE', '4F4', '2T1', '5T0', '6TF']
  VDS: ['KY5F19', 'HY05J7', 'DY5G1X', 'AY5F17', 'HY05J2', 'KY5F16', 'HY05J6', 'UY5F12', 'HY05J1', 'BY64A6', 'HY05J3', 'DY5F14', 'HY05J5', 'UY5F14', 'BY64A7', 'HY05JX', 'UY5F18', 'HY05J4', 'DY5F15', 'HY02J8', 'AY5F19', 'HY0SJX', 'HY05J8', 'AY5F11', 'AY5F14', 'BY68A5', 'DY5F16', 'HY02JX', 'BY64A3', 'DY5F13', 'KY5F17', 'HY05J0', 'HY5F17', 'KY5F1X', 'DY5F12', 'AY5F1X', 'UY5F15', 'AY1179', 'HY5F10', 'HY05J9', 'UY5F13', 'PY5F19', 'DY5F10', 'DY5F17', 'BY68A8', 'BY80E2', 'BY68A7', 'BY64AX', 'KY5F13', 'RY5F14', 'UY5F11', 'UY5F1X', 'KY5F18', 'AY5F10', 'BY64A1', 'KY5F14', 'UY5F10', 'HY5F19', 'DY5F18', 'AY5F18', 'BY64A4', 'ZY68A4', 'AYT30L', 'KY5F10', 'HY05JO', 'BY68A9', 'CY5F16', 'DY5F1X', 'BY67AX', 'NY5F12', 'HY03JX', 'AY5F16', 'YY5G1X', 'RY5F13', 'HY0518', 'BY68A3', 'BY68A6', 'BY64A5', 'DY5F19', 'BY64A8', 'BY68A1', 'CY7AJ4', 'BY64A2', 'RY5F1X', 'HY5F18', 'BY68A0', 'FY4184', 'FY5F13', 'FY4188', 'CY7AJ8', 'AY5F13', 'FY4185', 'BY68A4', 'BY5F17', 'BY5F12', 'ZY67AX', 'BY80E1', 'HY5F14', 'BY80E9', 'AY5F15', 'FY418X', 'ZY64A9', 'HY5F13', 'BY5F13', 'HY5F11', 'BY64A9', 'AY5F12', 'UY5F19', 'JY5F13', 'DY5F11', 'HY02J9', 'ZY68A2', 'BY68AX', 'BY5F11', 'UY5F17', 'ZY68A1', 'GY5F17', 'HY02J0', 'RY5F16', 'BY64A0', 'RY5F12', 'BY5F1X', 'HY5F15', 'BY80E0', 'BY68A2', 'BY67A6', 'BY80E6', 'HY02J7', 'ZY64A6', 'HY5F16', 'KY5F11', 'HY0SJ5', 'CY7AJ2', 'BY5F15', 'HY7AJ3', 'ZY0CCL', 'MY5F13', 'UY5F16', 'GY5F18', 'EY5F11', 'HY5F12', 'EY5F1X', 'ZY68A9', 'YY5G18', 'ZY67A5', 'KY5G18', 'FY4181', 'ZY5G17', 'FY5B18', 'BY80E3', 'BY67A4', 'JY5G15', 'FY4189', 'KY5F15', 'HY02J2', 'BY80E4', 'YY5G15', 'BY5G14', 'ZY64A2', 'BY67A3', 'ZY67A8', 'PY5F17', 'KY5G1X', 'ZY67A9', 'HY02J6', 'BY80EX', 'ZY5G19', 'ZY68A7', 'HY02J5', 'KY5F12', 'BY5G10', 'BY8799', 'UYSF14', 'PY5F11', 'HY0515', 'HY02J1', 'FY4183', 'FY4186', 'ZY67A7', 'JY5G1X', 'KY5G16', 'JY5G16', 'BY5F19', 'BY5G19', 'CY5F14', 'BY5G13', 'BY5G12', 'EY5F16', 'FY4182', 'ZY64A5', 'PY5F13', 'AYACC6', 'CY7AJ9', 'CY7AJ3', 'DY5G14', 'DY5G10', 'FY5F12', 'KYSFIX', 'ZY68AX', 'EY5F12', 'RY5F19', 'PY5F16', 'NY5F14', 'BY67A5', 'ZY5G1X', 'HY5F1X', 'GY5F19', 'BY5F10', 'JY5G19', 'HY02J4', 'CY7AJ0', 'AYACC9', 'BY5F14', 'GY5F1X', 'HY02J3', 'BY5G11', 'AYACC3', 'BY67A7', '2Y68A4', 'BY5F18', 'PY5F14', 'BY80E8', 'PY5F10', 'UY6F14', 'RY5F18', 'JY09J2', 'UYSF18', 'ZY68A0', 'ZY64A0', 'AY86C7', 'ZY5G14', 'RY5F15', 'RY5F11', 'KY5G17', 'PY22P6', 'EY5F19', 'BY67A0', 'DY32T7', '1YYK27', 'BY5G18', 'ZY68A8', 'DY5G13', 'KY5G13', 'DY5G16', 'LY3FX5', 'ZY64A3', '8Y64A2', 'NY5F17', 'BY67A8', '2Y64AX', 'AYACC7', 'FY4180', 'BY5G15', 'ZY5G18', 'BY64AB', 'BY11F4', 'BY5F16', 'CY5F13', 'DY5G18', 'AY1173', 'HY0SJ8', 'CY7AJ6', 'AY2NY7', '8Y64A5', 'DY5G15', 'LYV65V', 'PY5F12', 'CY7AJ5', 'BY8092', 'KY1CDX', 'HY0532', 'EY64A4', 'ZY68A5', 'ZY68A3', 'BY67A1', 'CY7AJ1', 'BY67A9', 'ZY64AX', 'HY7AJ4', 'FY5F10', '8Y5F16', 'GY5F14', 'ZY68A6', 'JY5G18', 'BY30E8', 'BY84A4', 'RY5F10', 'AY117X', 'BY84A5', 'BY80E7', 'ZY64A7', 'HYOSJS', 'HYO5JX', 'BY5G16', 'UYSF11', 'TY5F16', 'ZY5G10', 'EY5F15', 'ZY5G13', 'HY0535', 'AYACC8', 'TY5F14', 'GY5F13', 'UY0FJX', 'CY5F18', 'PY5F18', 'UYSPII', 'DY38T0', 'UYSF10', 'BYBDE1', 'RY5F17', 'FY5F17', 'HY7AJ6', 'ZY67A4', 'BY32E5', 'HY0534', 'EY5F14', 'JY5G11', 'UY5E14', 'DYSF18', 'LY3FXX', 'LY3FX4', 'DYSF10', 'CY5F11', 'HY0531', 'BY67A2', 'BY8798', '0YSF10', 'CY5F17', 'SY5F15', 'HY7AJX', 'TY5F11', 'EY5F13', 'HY0533', 'BY68AS', 'CY5F19', 'FY5A18', 'HYO5J3', '8Y5619', 'HY7AJ0', 'ZY64A8', 'ZY67A0', '8Y64A4', 'PY5F1X', 'ZY67A2', 'HY05I1', 'CY5F10', 'DY5G19', 'GY5F10', 'DYSF1X', 'HY0S0S', 'CY5F12', 'HY7AJ5']
  Model_Year: ['A', 'H', 'K', 'J', 'F', 'C', 'G', 'M', 'B', 'E', 'L', 'D', 'Y', '9', '7', '3', '8', '5', 'N', 'R', '6', '4', 'P', 'X', '2', '1']
  Plant_Code: ['X', '5', 'S', '4', '0', 'G', 'W', '2', '8', 'B', 'R', 'M', '9', 'J', 'P', 'C']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,K,STD (NON GCC),GCC,4.0,5TF,KY5F19,A,X,004345
1,TOYOTA,LAND CRUISER,6.0,SUV,H,GXR,GCC,5.0,JTM,HY05J7,H,5,025652
2,TOYOTA,SEQUOIA,8.0,SUV,D,SR5 (NON GCC),GCC,5.0,5TD,DY5G1X,K,S,166905
3,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,A,STD (NON GCC),GCC,4.0,5TF,AY5F17,J,X,712542
4,TOYOTA,LAND CRUISER,6.0,SUV,H,GXR,GCC,5.0,JTM,HY05J2,F,5,019335
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7251,TOYOTA,TUNDRA,8.0,PICKUP,U,STD (NON GCC),NON-GCC,NaN,5TF,UY5F19,E,X,326997
7252,TOYOTA,TUNDRA,8.0,PICKUP,D,STD (NON GCC),NON-GCC,NaN,5TF,DY5F19,F,X,431119
7253,TOYOTA,LAND CRUISER,8.0,SUV,H,GXR,GCC,NaN,JTM,HY05J9,H,5,024597
7254,TOYOTA,TUNDRA,8.0,PICKUP,A,STD (NON GCC),NON-GCC,NaN,5TF,AY5F17,M,X,977224
7255,TOYOTA,LAND CRUISER,8.0,SUV,H,VXR,GCC,NaN,JTM,HY05J0,M,4,095767

====================================================================================================
pos5: 5
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'LEVIN', 'HIACE', 'COROLLA', 'YARIS', 'HIGHLANDER', 'PREVIA', 'CAMRY', 'CROWN', 'FORTUNER', 'SIENNA', 'RAV4', 'COASTER']
  bodyType: ['PICK UP SINGLE CAB', 'SEDAN', 'PANEL VAN HIGH ROOF', 'PICK UP DOUBLE CAB', 'HATCHBACK', 'SUV', 'MPV', 'MINI BUS HIGH ROOF', 'PANEL VAN', 'BUS', 'PICK UP']
  pos4: ['6', 'B', '8', '1', 'D', 'G', '3', 'K', 'H', '7', '9', '4']
  trim: ['DLX', 'STD (NON GCC)', 'GLS', 'XLI TOP', 'LE', 'HYBRID (NON GCC)', 'STD', 'DX', 'AUTOMATIC', 'TOP', '1', 'S', 'XLI', 'SE', 'E', 'XLI MID', 'GLI', 'GLE', 'MID', 'LIMITED']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['WDB', 'LVG', 'CLG', 'NSP', 'JTE', 'JZS', 'WD8', 'LSK', 'RN1', '5TD', 'RK4', 'NCP', 'VZE', 'YBL', 'WVG', 'MAT', 'GGG']
  VDS: ['652047', 'B519E4', 'B519E0', 'B519E9', '652037', '855HZK', 'B519E1', 'B519E5', '655532', '652136', '151407', 'B519E7', 'D541A0', 'B519E6', '656205', '151005', '659338', 'G5GC14', '652004', '151004', 'B519E3', '350007', 'K5KFCX', '656516', '658050', '659343', 'B519E8', 'B519EX', '150702', '150700', '656109', '151403', '151517', '3546FG', 'H545G5', 'B519E2', '751068', '950213', '655533', '456123', '954033', '954032', '659101']
  Model_Year: ['1', 'N', 'M', '4', '8', '5', 'F', '7', '6', '9', 'P']
  Plant_Code: ['5', 'G', 'L', 'K', '4', '2', '6', 'A', '3', 'S', '0', '7', '9', '8', '1', 'F']
  Serial_Number: ['738892', '700176', '516982', '516897', '589064', '718998', '516991', '516914', '167104', '526845', '35    ', '517031', '067106', '700258', '233036', '250000', '723047', '210045', '285802', '970000', '013867', '211111', '062221', '000000', '001359', '281420', '012512', '517023', '006118', '011758', '517242', '517027', '516940', '311111', '012961', '304444', '228603', '820000', '810000', '521RF1', '454645', '517221', '544545', '012870', '700310', '011771', '520155', 'L00010', '262691', '047355', '555555', '752850', '700209', '006125', '402549', '520620', '287759', '011714']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,2.0,WDB,652047,1,5,738892
1,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E4,N,G,700176
2,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E0,M,G,516982
3,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E9,M,G,516897
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,2.0,WDB,652037,1,5,589064
5,TOYOTA,HIACE,4.0,PANEL VAN HIGH ROOF,8,GLS,GCC,NaN,CLG,855HZK,M,L,718998
6,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E1,M,G,516991
7,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E5,M,G,516914
8,TOYOTA,COROLLA,4.0,SEDAN,6,XLI TOP,GCC,NaN,WDB,655532,1,K,167104
9,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,6,DLX,GCC,4.0,WDB,652136,1,5,526845
10,TOYOTA,YARIS,4.0,HATCHBACK,1,LE,NaN,NaN,NSP,151407,4,4,35
11,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E7,M,G,517031
12,TOYOTA,HIGHLANDER,6.0,SUV,D,HYBRID (NON GCC),GCC,5.0,JTE,D541A0,8,2,067106
13,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E6,N,G,700258
14,TOYOTA,PREVIA,4.0,MPV,6,STD,GCC,5.0,WDB,656205,1,K,233036
15,TOYOTA,CAMRY,4.0,SEDAN,1,STD,NON-GCC,NaN,JZS,151005,5,6,250000
16,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,6,DLX,GCC,4.0,WD8,659338,1,5,723047
17,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,G,DX,GCC,4.0,LSK,G5GC14,F,A,210045
18,TOYOTA,HIACE,4.0,PANEL VAN,6,STD,GCC,5.0,WDB,652004,1,K,285802
19,TOYOTA,CROWN,6.0,SEDAN,1,AUTOMATIC,NON-GCC,NaN,JZS,151004,1,4,970000
20,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E3,N,G,013867
21,TOYOTA,FORTUNER,4.0,SUV,3,TOP,GCC,NaN,RN1,350007,7,3,211111
22,TOYOTA,SIENNA,6.0,MPV,K,1,GCC,NaN,5TD,K5KFCX,N,S,062221
23,TOYOTA,COROLLA,4.0,SEDAN,6,S,GCC,NaN,RK4,656516,1,0,000000
24,TOYOTA,COROLLA,4.0,SEDAN,6,XLI,GCC,NaN,WDB,658050,1,K,001359
25,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,6,DLX,GCC,2.0,WDB,659343,1,K,281420
26,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E5,N,G,012512
27,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E8,M,G,517023
28,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E6,M,G,006118
29,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519EX,N,G,011758
30,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E9,M,G,517242
31,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E5,M,G,517027
32,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E6,M,G,516940
33,TOYOTA,YARIS,4.0,SEDAN,1,SE,GCC,NaN,NCP,150702,6,7,311111
34,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E1,N,G,012961
35,TOYOTA,YARIS,4.0,SEDAN,1,SE,GCC,NaN,NCP,150700,9,0,304444
36,TOYOTA,RAV4,4.0,SUV,6,STD,GCC,NaN,WDB,656109,1,K,228603
37,TOYOTA,YARIS,4.0,HATCHBACK,1,SE,GCC,NaN,NSP,151403,7,9,820000
38,TOYOTA,YARIS,4.0,SEDAN,1,E,NON-GCC,NaN,NSP,151407,7,8,810000
39,TOYOTA,COROLLA,4.0,SEDAN,1,XLI MID,NON-GCC,NaN,VZE,151517,1,1,521RF1
40,TOYOTA,COROLLA,4.0,SEDAN,3,S,GCC,NaN,YBL,3546FG,5,4,454645
41,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E1,M,G,517221
42,TOYOTA,COROLLA,4.0,SEDAN,H,S,GCC,NaN,WVG,H545G5,4,G,544545
43,TOYOTA,COROLLA,4.0,SEDAN,B,GLI,GCC,4.0,LVG,B519E9,N,G,012870
44,TOYOTA,COROLLA,4.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E4,N,G,700310
45,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E2,N,G,011771
46,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E5,N,G,520155
47,TOYOTA,COASTER,6.0,BUS,7,STD,GCC,NaN,MAT,751068,P,F,L00010
48,TOYOTA,HILUX,4.0,PICK UP,9,DLX,GCC,NaN,WDB,950213,1,K,262691
49,TOYOTA,COROLLA,4.0,SEDAN,6,XLI TOP,NON-GCC,NaN,WDB,655533,1,K,047355
50,TOYOTA,COROLLA,4.0,SEDAN,4,XLI,GCC,NaN,GGG,456123,6,5,555555
51,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,9,DLX,GCC,NaN,WDB,954033,1,K,752850
52,TOYOTA,CAMRY,4.0,SEDAN,B,GLE,GCC,4.0,LVG,B519E4,N,G,700209
53,TOYOTA,LEVIN,3.0,SEDAN,B,STD (NON GCC),GCC,4.0,LVG,B519E3,M,G,006125
54,TOYOTA,YARIS,4.0,HATCHBACK,9,MID,NON-GCC,NaN,WDB,954032,1,K,402549
55,TOYOTA,CAMRY,4.0,SEDAN,B,GLE,GCC,4.0,LVG,B519E6,N,G,520620
56,TOYOTA,COROLLA,4.0,SEDAN,6,LIMITED,NON-GCC,NaN,WDB,659101,1,K,287759
57,TOYOTA,COROLLA,4.0,SEDAN,B,STD (NON GCC),NON-GCC,NaN,LVG,B519E1,N,G,011714

====================================================================================================
pos5: M
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['GRANVIA', 'HILUX', 'PRADO', 'HIACE', 'URBAN CRUISER', 'TUNDRA', 'COASTER', 'TAKOMA', 'SIENNA', 'TACOMA', 'COROLLA', 'INNOVA', 'T 100', 'LAND CRUISER', 'LAND CRUISER PICK UP', 'PRADO GX', 'TOYOTA PRADO', 'RAV4', 'YARIS', 'CAMRY', 'هايلوكس', 'HAI LUX', 'T100', 'برادو', 'VAN']
  bodyType: ['MPV', 'PICK UP DOUBLE CAB', 'SUV', 'MINI BUS HIGH ROOF', 'PANEL VAN', 'VAN', 'PICK UP SINGLE CAB', 'CARGO VAN', 'PICKUP', 'BUS', 'MINI BUS', 'PANEL VAN HIGH ROOF', 'PICK UP', 'TRUCK', 'SEDAN', 'STATION', 'LIGHT VEHICLE']
  pos4: ['Y', 'A', 'L', 'R', 'D', 'E', 'B', 'U', 'K', 'N', 'F', 'S', 'P', 'T', 'J', 'W', 'C']
  trim: ['PLATINUM', 'DLX', 'VX', 'GL', 'PREMIUM', 'GLX', 'GLS', 'STD (NON GCC)', 'GX MID', 'DLS - STD ROOF', 'STD', '1', 'GX', '1500', 'BUS', 'LE (NON GCC)', 'DX', 'STAN', 'S ASF', 'GLI', 'S', 'A', 'STANDARD', 'DLS HIGH ROOF', 'DLS', 'COASTER', 'BASE', 'TRD', 'E', 'TX', 'ST', '0', '90', 'DL', 'GRANDE', 'PICK']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTN', 'JTF', 'JTE', 'MBJ', '5TF', '4TA', 'JTG', 'STF', '5TE', 'JT4', 'JT3', 'MEJ', 'LSF', 'MPJ', 'JHM', 'YV2', 'WVW', '1LN']
  VDS: ['YM8AP0', 'AM4968', 'AM29J2', 'LMFCP4', 'RMFAP7', 'YM3AP3', 'YMLA22', 'YMLA24', 'LMFCP5', 'RMFAPX', 'LMFCP8', 'YMLA21', 'DM5F11', 'YM3AP8', 'AM29J8', 'YMLA28', 'EM4963', 'BM29J5', 'DM6264', 'EM4260', 'RMFAP9', 'YMLA29', 'LMFCPO', 'YMLA20', 'AM4960', 'BM29J6', 'RMFAP6', 'LMFCP2', 'UM5F16', 'RMFAPO', 'KM6261', 'YM3AP6', 'AM496X', 'YM3AP2', 'LMFCP9', 'RM5F18', 'YMLA27', 'EM4261', 'NM92NX', 'LMFCW1', 'AM29J5', 'FM5189', 'YMLA26', 'AM4966', 'RMFAP4', 'BM29J1', 'UM5F19', 'RM5F14', 'EM4966', 'UM5F15', 'LMFCP3', 'LMFCP7', 'EM496X', 'AM4967', 'EM4269', 'KM6262', 'AM29J4', 'AM29J0', 'LMFCPI', 'SMFAP6', 'EM4969', 'LMFCP6', 'EM4964', 'AM4964', 'LMFCP0', 'EM4965', 'EM4264', 'YMLA23', 'LMFCW8', 'RM5F15', 'AM4963', 'YM8AP5', 'EM4268', 'BM99J3', 'SMFAP7', 'LMFCPX', 'EM4968', 'RMFAP5', 'BM99J6', 'RMFAP1', 'AM29J3', 'RMFAP8', 'YMLA2X', 'EM4961', 'SMFAP1', 'PM62NX', 'EM4960', 'RM5F12', 'BM29J0', 'NM92N8', 'YM3APX', 'AM29J6', 'DM6262', 'BM29J8', 'SMFAP9', 'BM29JX', 'AM29J7', 'FM5182', 'AM4961', 'BM29J2', 'BM99J2', 'YMLA25', 'FM4185', 'EM4266', 'RM5F19', 'SMFAP3', 'FM4189', 'RMFAP2', 'FM5188', 'FM5183', 'FM418X', 'UM5F12', 'BM29J3', 'SM92NO', 'DM6261', 'YM3AP5', 'YM3AP9', 'YM8AP2', 'UM5F17', 'AM4969', 'KM5F15', 'RM5F17', 'DM6266', 'FM5187', 'TMLA21', 'YM3AP4', 'AM4962', 'YM3AP1', 'BM29J4', 'BM99J4', 'LMFCP1', 'FM4184', 'NM92N6', 'UM5F13', 'BM29J7', 'EM4267', 'PM62N2', 'EM4263', 'BM99J8', 'PM62N7', 'RMFAP3', 'SMFAP0', 'EM4265', 'FM4187', 'PM62N3', 'RMFAPS', 'LM5F10', 'YM3AP0', 'FM4182', 'EM4967', 'YM3AP7', 'FM4183', 'AM4965', 'UM5F18', 'FM4188', 'FM5181', 'UM5F11', 'DM6268', 'YM8AP7', 'KM5F10', 'DM6265', 'NM92N4', 'FM4181', 'BM99J5', 'DM6263', 'RMFAP0', 'RM5F13', 'SMFAP4', 'RM5F1X', 'YM8AP3', 'JM11D9', 'BM99J7', 'EM5F18', 'DM6260', 'BM99J1', 'DM6269', 'EM5F14', 'AM4501', 'RMFAW7', 'AM4981', 'EM4962', 'BM99J0', 'LMFCW4', 'SM92N0', 'PM62N1', 'EM4262', 'AM29J1', 'YMLAZ7', 'LMSF17', 'AM11H6', 'FM4180', 'UM5F10', 'RM5F11', 'FM5185', 'FM5184', 'YM3APO', 'UM5F1X', 'WM72N4', 'SMFAPX', 'DM5F18', 'AM11H1', 'EM42G3', 'PM62N4', 'PM62N8', 'SMFAP2', 'EM426X', 'FM4186', 'YM8AP8', 'DM626X', 'NM92N5', 'CM5657', 'WM72NX', 'BM99J9', 'BM29J9', 'KM6260', 'SMFAP5', 'DM5F16', 'EM5F1X', 'KM6268', 'FM5180', 'JM30D3', 'SMFAPO', 'EM5F13', 'JM11D3', 'KM5F13', 'UM5F14', 'EM5F10', 'AM2AH8', 'PM62N5', 'BM82F8', 'AM29J9', 'PM62N0', 'DM6267', 'KM5F17', 'KM6269', 'NM92N2', 'RM5F10', 'SMFAP8', 'KM5F14', 'RMEAP7', 'EM5F19']
  Model_Year: ['L', '5', '3', 'T', 'M', 'P', 'R', 'S', 'N', 'G', '4', '2', 'K', 'J', 'Y', '6', 'H', 'E', 'A', 'D', '1', 'X', 'B', '7', 'C', 'F', 'W', 'V']
  Plant_Code: ['8', '0', '6', 'T', 'X', 'Z', '4', '3', 'A', 'C', 'V', 'Y']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,GRANVIA,6.0,MPV,Y,PLATINUM,GCC,4.0,JTN,YM8AP0,L,8,001152
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,A,DLX,GCC,4.0,JTF,AM4968,5,0,171178
2,TOYOTA,PRADO,6.0,SUV,A,VX,GCC,5.0,JTE,AM29J2,3,0,002011
3,TOYOTA,HIACE,6.0,MINI BUS HIGH ROOF,L,GL,GCC,4.0,JTF,LMFCP4,T,6,014263
4,TOYOTA,HIACE,4.0,PANEL VAN,R,GL,GCC,NaN,JTF,RMFAP7,M,8,004491
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1708,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA25,S,T,121688
1709,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA21,R,T,107359
1710,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GL,GCC,NaN,MBJ,YMLA29,R,T,106881
1711,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA23,R,T,107248
1712,TOYOTA,HILUX,4.0,PICKUP,E,1,GCC,NaN,JTF,EM4266,4,0,136343

====================================================================================================
pos5: 4
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'CAMRY', 'RAV4', 'HILUX', 'LEVIN', 'PRADO', 'AVALON', 'HIACE', 'CELICA', 'COASTER', 'LAND CRUISER', 'YARIS', 'COROLLA SEDAN / HATCH', 'STANZA', 'WIGO', 'COROLLA 1.5L/HATCHBACK', 'HI ACE']
  bodyType: ['SEDAN', 'SUV', 'PICK UP DOUBLE CAB', 'MINI BUS HIGH ROOF', 'COUPE', 'PANEL VAN', 'BUS', 'HATCHBACK', 'PICK UP SINGLE CAB', 'VAN', 'STATION', 'PICK UP']
  pos4: ['K', 'B', 'D', 'H', 'A', '5', 'J', 'R', 'S', 'P', '6', 'M', 'T', '1', '4', 'C', 'G', 'U', 'E', 'V', '9', '0', 'Z']
  trim: ['SE', 'GLI', 'GLE-X', 'EX', 'XLI EXECUTIVE', 'XLI', 'EXR', 'STD (NON GCC)', 'DLX', 'XLI MID', 'LE HEV', 'GX', 'LIMITED', 'GRANDE', 'STD', 'GXR', 'SE+', 'GLI HEV', 'XLI EXECUTIVE MR', 'BASE', 'VX', 'GL', 'DL', 'DLS', 'MID', 'XLI EXECUTIVE HEV', 'XLI TOP', 'SE (NON GCC)', 'S', 'SWB', 'VXR', 'VAN', 'GLX', 'GXR HEV']
  regionalSpec: ['NON-GCC', 'GCC']
  WMI: ['JTN', '5YF', 'LFP', 'LFM', 'YV2', 'JTD', 'JTM', 'LVG', 'JTB', 'RP8', 'ZRE', 'MAT', 'ZZE', 'LSK', 'IG1', 'WMA', 'WYU', 'WCY', 'YS2', 'MC1', 'LVB', 'WDB', 'SYF', 'MHK', '425', 'JT4']
  VDS: ['K4RBE5', 'B4MDE1', 'D4MBE8', 'H4ACP0', 'K440F1', 'B4MDE0', 'A4DAA6', '543BV7', 'J44AF1', 'B4MDE3', 'D4MBE2', 'A4DAC2', 'A4B2A2', 'R43FV3', 'J440F4', 'B4B9EX', 'S4MCE7', 'P4RCE7', 'H4BCP3', '64AEB2', 'B4B9E2', 'A4B3A9', 'M45711', 'A4DMA4', 'A4B2A6', 'A4CFA7', 'S4MCEX', 'S4MCE1', 'A4B3A5', 'K4MBE8', 'T4MCEX', '142442', '543AV4', 'A4B3AX', 'B4B9E8', 'B4B9E1', 'R43FV4', '449253', 'S4MCE9', 'S4MCE4', 'S4RCE4', 'A4CEA2', 'S4RCE9', '142700', 'S4RCE1', 'S4RCEI', 'S4MCE3', 'C4RBE1', 'A4B3A8', 'B4MDE4', 'S4RCE2', 'R43FV5', 'B4B9E6', 'G4AC10', '145839', 'C4MBE1', 'S4MCE5', '142704', 'A4CFA5', 'T48ZZZ', 'B4B9E0', 'B4MDE2', 'B4MBE1', 'P4RCE3', 'S4RCE8', 'C4RBE6', 'K440F2', '142440', 'J44AF0', 'B4MBE8', 'S4MCE2', 'B4MDE7', '145457', 'U45454', 'G4X205', 'K4RBE4', 'D4MBE1', 'T4RCE9', 'B4MBE9', 'B4MDE9', '543AV3', 'B4B9E9', 'K4RBEX', 'D4MBE3', 'A4MBE6', 'B4MBEX', '64STL3', 'K4RBE2', 'E4FDB8', 'B4B9E7', 'B4MDEX', '449252', 'S4MCE6', '543AVX', 'S4RCEX', 'K440F8', 'B4MDEI', 'K4RBE8', 'C4MBE4', 'S4RCE5', 'V4JBB9', 'B4MDE8', '142443', '944032', 'B4B9E3', 'B4B9E4', 'S4RCE7', 'K4RBE7', 'D4RBE2', 'D4MBE0', 'D4MBE9', 'K440F5', '142523', '142524', '543BV2', 'B4B9E5', 'K4RBE0', 'A4B5A4', '543AV5', 'P4RCE4', 'H4ACP2', 'S4MCE0', 'K4RBE3', 'G4BC13', 'S4RCE6', 'P4MCE1', 'K4RBE1', 'P4MCE8', 'B4MBE7', 'B4RBE9', 'T4MCE3', 'B4RBE3', 'T4MCE8', 'B4MBE5', '142703', 'S4RCE3', 'T4MCE1', 'P4RCE0', 'P4RCE1', 'A4RBE2', 'D4MBEX', 'A4DF5F', 'T4RCE7', 'S4RCE0', 'A4DAA2', '042TN9', 'M4RCE5', 'B4MDE5', 'R43FVX', 'K4MBE7', 'B4RBE6', 'D4MBE6', 'A4CFA2', 'D4MBE7', 'B4MEE8', 'J4CMA4', 'P4MCE7', 'D4MBE4', 'B4MBE6', 'P4RCE9', 'B4RBE4', 'C4MBEX', 'P4MCE6', 'G4X20X', 'P4RCE2', 'D4RBE9', 'A4DAA9', 'Z41197', 'K440F4', 'V4JBB7', 'D4MBE5', 'K4RBE6', 'T4MCE5', 'K4RBE9', 'A4DAA3', 'A4CEA8', 'P4RCEX', 'A4B3A2', 'J4CFC7', 'A4DAAX', '64EEB0', 'R43FV0', 'A4DBAX', 'A4CFA3', '543BV9', '543BV8', '543BV4']
  Model_Year: ['K', 'P', 'M', 'R', 'J', 'X', 'T', 'E', 'V', 'D', 'L', 'W', '1', '4', 'N', '8', 'S', 'G', '5', '2', 'H', 'F', '6', '3', '7', '9', 'Y']
  Plant_Code: ['3', 'P', '2', 'B', 'D', 'G', 'J', '0', '1', 'V', 'A', 'U', 'M', '7', '4', '5', 'Y', 'K', '8', '6', '9', 'L']
  Serial_Number: ['008148', '052974', '114141', 'A39732', '406844', '179153', '233361', '003737', '039525', '148561', '105418', '234539', '171750', '061543', '010827', '040747', '079355', '016608', 'L01896', '001360', '042296', '822605', '000434', '277006', '184601', '583652', '001716', '088952', '143809', '212289', '165230', '212343', '320000', '004023', '204476', '059734', '065391', '143502', '004284', '044196', 'L02040', '064792', '162306', '024367', '396543', '025762', '990000', '058424', '017683', '084781', '102758', '181911', '046635', '049851', '037433', '003934', '482993', '109460', '073702', '110618', '208037', '173799', '082240', '088990', '160000', '364912', '324595', '064023', '147448', '093636', '002984', '049191', '146999', '100598', '102514', '050208', '192772', '148293', '301111', '028712', '116797', '067352', '068751', '143721', '196554', '487487', '545656', '094598', '724983', '017665', '235154', '044981', '006886', '508147', '056198', '072254', '110538', '040162', '069239', '043209', '238387', '154445', '001419', '407167', '063361', '013622', '206567', '155176', '105221', '480856', '121778', '040183', '193535', '225224', '061534', '005243', '005386', '085338', '026051', '000204', '182279', 'L02068', '202131', '002096', '039895', '221878', '075736', '046157', '183731', '006734', '196367', '051853', '023180', '048704', '145594', '177233', '091886', '390000', '869849', '078421', 'L01132', '416736', '416110', '055725', '056121', '104989', '011178', '027865', '030586', '094609', '484579', '010377', '187134', '124032', '761111', '102193', '182079', '033416', '910000', '590000', '001491', '095075', '040911', '419043', '015130', '521111', '053739', '001033', '041863', '043231', '173349', '175259', '442810', '000692', '429291', '029346', '195687', '236702', '033239', '070029', '920000', 'A01516', '050521', '522215', '206128', '039279', '042943', '001056', '055047', '410000', '001011', '153000', '042373', '097488', '040611', '013942', '193821', '144185', '077293', '141291', '518919', '095662', '070656', '062110', '089822', '480254', '177966', '005668', '220886', '046992', '182904', '504981', '424785', '418265', '076127', '596541', '001155', '029405', '036400', '187508', '034256', '140526', '255685', '034002', '032853', '092605', '069723', '880000', '166078', '006136', '003716', '102814', 'L01068', '047830', '248468', '202180', '114522', 'NTGUCY', '036850', '248229', '076143', '133657', '001819', '036251', '113103', '062930', '382656', '047451', '132421', '135367', '191314', '026694', '179662', '012902', '393919', '107478', '197975', '006532', '160995', '090914', '056664', '026392', '052319', '442399', '032745', '246841', '108120', '112953', '094679', '109853', '034705', '001127', '757323', '000501', '165471', '009241', '038113', '053632', '780000', '480599', '302844', '125459', '099998', '060699', '265822', '007674', '119843', '415084', '006113', '106966', '049727', '028301', '155112', '006445', '800000', '013045', '030567', '239533', '028039', '159838', '001254', '222317', '600000', '006204', '009490', '327398', '021723', '164633', '001470', '580199', '177199', '133452', '267322', '000282', '037106', '075616', '148071', '283962', '399045', '105863', '000872', '180471', '052369', '464515', '000782', '098923', '098941', '001136']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,K,SE,NON-GCC,NaN,JTN,K4RBE5,K,3,008148
1,TOYOTA,COROLLA,4.0,SEDAN,B,GLI,GCC,4.0,5YF,B4MDE1,P,P,052974
2,TOYOTA,COROLLA,4.0,SEDAN,D,SE,GCC,4.0,JTN,D4MBE8,M,3,114141
3,TOYOTA,CAMRY,4.0,SEDAN,H,GLE-X,NON-GCC,4.0,LFP,H4ACP0,R,2,A39732
4,TOYOTA,RAV4,4.0,SUV,K,EX,GCC,5.0,LFM,K440F1,J,3,406844
...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,NON-GCC,NaN,LVG,B4B9E3,M,G,464515
325,TOYOTA,RAV4,4.0,SUV,5,EX,GCC,NaN,JTD,543BV8,T,D,000782
326,TOYOTA,COROLLA,4.0,SEDAN,K,SE+,NON-GCC,NaN,JTN,K4RBE7,L,3,098923
327,TOYOTA,COROLLA,4.0,SEDAN,S,STD (NON GCC),NON-GCC,NaN,JTD,S4MCE3,N,J,098941
328,TOYOTA,RAV4,4.0,SUV,5,EX,GCC,NaN,JTD,543BV4,T,D,001136

====================================================================================================
pos5: 6
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'RAV4', 'COROLLA', 'HIACE', 'HILUX', 'YARIS', 'SIENNA', 'COROLLA CROSS', 'TUNDRA', 'LAND CRUISER', 'NIO ES8', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'MINI BUS', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'MPV', 'SUV- CROSSOVER', 'HALF PANEL VAN', 'MINI BUS HIGH ROOF']
  pos4: ['K', 'R', 'E', 'B', 'G', 'C', 'P', '0', 'A', '8', 'W', '4', '5', '2', 'F', '6', 'D']
  trim: ['GLE-X HEV 40TH ANNIV', 'EXR', 'LE HEV', 'GLE', 'SE', 'SPORT', 'S', 'XLI', 'EX', 'GLE HEV', 'DX', 'STD', 'BASE', 'LIMITED', 'E', 'DLX', 'LE', 'DL', 'STD (NON GCC)', 'XSE (NON GCC)', 'XLE', 'GLI TOP', 'SAFARI', 'GLX', 'DLS - STD ROOF', 'GL', 'GRANDE HEV 40TH ANNIV']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['4T1', '2T3', '4T3', 'LVG', 'YS2', '9BS', 'WMA', 'JT4', 'JTM', 'LCF', 'JTF', 'JT2', 'KL3', 'MAT', '6T1', 'VS5', 'MK2', 'MD6', 'VF1', 'LJ1', 'GX9']
  VDS: ['K61AK9', 'R6RFV9', 'E6RFV0', 'B674K8', 'K61AK7', 'E6RFVX', 'K61BK0', 'K61AK1', 'B61HK1', 'G6X400', 'C618X8', 'B61HK6', 'B6RFV7', 'K61AK0', 'B61HK8', 'P6X400', 'K61AKX', '06XZZ1', 'A64261', '8622K0', '8622K1', 'E6RFV4', 'B61HK9', 'B61HK4', 'K61AK3', 'W6FY16', 'R6RFV0', 'A64264', 'B6RFV4', 'K61AK8', 'K61BK6', 'B61HKX', '8622K6', '8622K5', '8622K7', 'K6E6F1', 'B61HK7', 'K61AK4', 'B61HK2', '464054', 'B622K7', '8622K4', 'B622K3', 'K61BK4', 'B61HK0', '56N8U6', '8622K2', '8622K8', 'C616Z8', '8622K3', '464703', 'K61AK5', 'B622K6', 'E6RFV9', 'B622K1', 'E6RFV3', '8622K9', 'B61HK3', 'K61AK6', '8622KX', 'K6T1Y6', 'B622K5', 'R6RFV2', 'G622K5', 'B61HK5', 'B622K8', 'E6RFV6', '26BG7X', '464753', 'F6RDM1', '66B3D9', 'R6RFV7', 'K61AK2', '56EZZ5', 'D6RFV5', 'R6RFV8', 'E6A3U3', 'A64265', '464072', 'R6RFV3', 'B6RFV2', 'B622K9', 'C616ZX', 'A64266', '66B3D4', '066223', '8628KX', 'B61HKO', '06XZZX']
  Model_Year: ['P', 'M', 'L', 'N', 'J', 'D', 'K', '5', 'A', 'X', '1', '7', 'T', '4', 'S', 'W', 'Y', '9', '2', 'R', 'V', 'G', 'H', '3', 'B', '8']
  Plant_Code: ['U', 'W', 'G', '5', '3', 'P', '0', 'J', 'D', 'K', 'S', 'X', 'N', '2', 'B', 'M', '1']
  Serial_Number: ['084041', '004756', '038325', '767573', '986004', '031092', '077770', '332096', '318169', '095659', '316388', '014322', '228942', '660083', '050006', '301338', '604316', '422760', '229956', '557989', '886673', '020763', '014721', '457825', '780773', '602629', '008033', '238018', '040497', '091833', '909730', 'Z01349', '014477', '150994', '049322', '153135', '882962', '008947', '285414', '131641', '255806', '753783', '553521', '286773', '839475', '188744', '663516', '000728', '717425', '020447', '617140', '349264', '097890', 'L01527', '486105', '553789', '465011', '035338', '012707', 'E9FFA8', '442234', '193389', '593129', '497831', '081609', '867090', '808987', '585744', 'L00428', '104642', '537453', '316501', '794707', '444835', '001594', '008819', '074711', '470286', '026783', '967868', '762714', '814745', '517641', '746582', '792909', '988756', '838887', '439239', '806613', '235412', '022094', '314342', '862544', '050734', '497383', '429137', '181872', '000869', '275362', '400380', '421004', '162057', '750634', '014898', '126042', '028235', '514846', '807592', '550109', '117080', '441303', '216930', '507568', '114002', 'L00163', '294913', '422091', '062368', '014606', '578998', '330165', 'AB3026', 'L01292', '406083', '035346', '295536', '592480', '809347', '254778', '996437', '114278', '029722', '778988', '542373', '939639', '032223', '304866', '071298', '886417', '148674', '963559', '005688', '539968', '022570', '330230', '584139', '534252', '293892', '906049', '207179', '839769', '046671', '125164', '271488', '363130', '104128', '445089', '305153', '569819', '365861', 'L01334', '460916', '181705', '013968', '069914', '017351', '399616', '034899', '683563', '768996', '512621', '507562', '063075', '266148', '012740', '250373', '000000', '749552', '972372', '190592', '383967', '289993', '209376', '127148', '846489', '493582', '065739', '018016', '926210', '519116']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,K,GLE-X HEV 40TH ANNIV,GCC,4.0,4T1,K61AK9,P,U,084041
1,TOYOTA,RAV4,4.0,SUV,R,EXR,GCC,5.0,2T3,R6RFV9,M,W,004756
2,TOYOTA,RAV4,4.0,SUV,E,LE HEV,GCC,5.0,4T3,E6RFV0,M,U,038325
3,TOYOTA,CAMRY,4.0,SEDAN,B,GLE,GCC,4.0,LVG,B674K8,P,G,767573
4,TOYOTA,CAMRY,4.0,SEDAN,K,SE,GCC,4.0,4T1,K61AK7,L,U,986004
...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,TOYOTA,CAMRY HYBRID,4.0,SEDAN,K,S,NON-GCC,NaN,4T1,K61AK1,M,U,493582
191,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,S,NON-GCC,NaN,4T1,B61HK3,J,U,065739
192,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,S,NON-GCC,NaN,4T1,B61HK3,J,U,018016
193,TOYOTA,CAMRY HYBRID,4.0,SEDAN,K,SE,NON-GCC,NaN,4T1,K61AK7,L,U,926210
194,TOYOTA,CAMRY HYBRID,4.0,SEDAN,K,S,NON-GCC,NaN,4T1,K61AK5,M,U,519116

====================================================================================================
pos5: P
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'OTHERS', 'RAV4', 'LEVIN', 'RAV 4', 'HIACE', 'BZ4X', 'FORTUNER', 'CAMRY', 'HILUX', 'YARIS', 'HIGHLANDER', 'COROLLA 1.8', 'LAND CRUISER', 'FJ CRUISER', 'COROLLA 1.6', 'COROLLA 1.3', 'AVALON']
  bodyType: ['SEDAN', 'COUPE', 'SUV', 'SALOON', 'STATION', 'PANEL VAN', 'PICK UP DOUBLE CAB', 'REGULAR CAB']
  pos4: ['E', 'D', 'H', 'Y', 'B', 'X', 'G', 'F', 'C', 'A', 'V', 'K', 'L', 'N']
  trim: ['GLI', 'XLI', 'LE', 'STD', 'GXR', 'SE+', 'STD (NON GCC)', 'XLE', 'XLI EXECUTIVE', 'GLI HEV', 'DX', 'EXR', 'PRO', 'TOP', 'SPORT', 'S TRD SPORT PK', 'LEVIN', 'DLX', 'SE', 'DL', 'LIMITED', 'S', 'GL', 'PLATINUM', 'SED', 'AMBIENTE', 'GX', 'GLX', 'BASE', 'GLE', 'AMG', 'XLI ', 'COM', '1000', 'PW CL']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5YF', 'JT2', 'JT3', 'LVG', 'JTD', 'LXG', 'LFM', '2T1', 'JTE', 'L7X', 'JTS', 'JAA', 'MR2', 'RKM', '9KM', 'JAM', '5AL', 'LHG']
  VDS: ['EPMAE0', 'DP02T1', 'EPRAE9', 'HP10V2', 'YP10V8', 'YP10V3', 'HP10V5', 'BPRBE3', 'HP10V4', 'BPB9EX', 'EPRAE5', 'HP10V6', 'EPRAE8', 'EPMAE2', 'XP10V7', 'GP10V2', 'EPRAEX', 'YP10V6', 'GP10V1', 'EPMAE4', 'GP10V9', 'HP10V3', 'BPRHE5', 'GP10V8', 'EPRAE7', 'XP10V6', 'HP10V8', 'HP10V7', 'BPRBE7', 'EPMAE3', 'YP10V0', 'FPMAE5', 'HP10V9', 'GP10V0', 'CPA509', 'DPRAE8', 'EPMAE7', 'DPMAE9', 'EPRAE1', 'YP10V1', 'HP10V0', 'BPRBE2', 'EPMAE1', 'DPRAEO', 'DPRAE0', 'EPMAEX', 'GP10VX', 'BPRHE4', 'YP10VX', 'HP10VX', 'EPMAE5', 'EPRAE4', 'BPB9E1', 'XP10V2', 'AP22C1', 'BPRBE6', 'EPRAE6', 'HPRAE2', 'GP10V3', 'VPMAE4', 'EPRAE3', 'XP10V1', 'EPRAE2', 'BPRHE1', 'XP10V9', 'KP14T0', 'GP10V6', 'KP14TX', 'AP22CX', 'GP21A2', 'FPEFFV', 'VPMAE9', 'HP10V1', 'YP10V4', 'BPRHE3', 'EPMAE8', 'BPRHE7', 'APE2C8', 'BPB9E0', 'BPB9E2', 'BPB9EO', 'XP10V8', 'GP10V5', 'BPB9E4', 'VPRAE0', 'HPRAEX', 'EPMAE6', 'VPMAE2', 'BPRHE2', 'FPRAE3', 'AP86C4', 'YP10V9', 'AP86C7', 'XP10V3', 'DPRAE2', 'XP10V4', 'BPRHE6', 'FP14F3', 'YP10V7', 'GP10V4', 'VP9F32', 'XP10VX', 'GP10V7', 'HPRAE1', 'EPMAE9', 'EPRAE0', 'VPMAE1', 'AP22C2', 'BPRHE0', 'BPRHEO', 'DPMAE7', 'DPRAE1', 'BPRHEX', 'CP7241', 'AP86C3', 'DP21A2', 'BPRBE0', 'BPWDG2', 'CP5154', 'BPMBE0', 'CP5156', 'BPB9E3', 'DPRAE7', 'AP86C6', 'EPRAES', 'DPMAE4', 'EPRAEO', 'HPRAE8', 'YP10V5', 'YP10V2', 'AP90A2', 'XP10V0', 'AP86C0', 'HPRAE0', 'KP14T5', 'DPRAE5', 'LP345X', 'VP2863', 'BPRHE9', 'DPMAE1', 'AP22C4', 'CP4500', 'XP10V5', 'DPMAE0', 'BPRBE9', 'BPRHE8', 'BPRBE8', 'AP86C8', 'BPB9E5', 'BPMBE1', 'NPR66P', 'VPMAE6', 'DP21A5', 'VPMAE5', 'AP54K3', 'AP54K2', 'EPMAEO', 'AP22C5', 'VPMAE3', 'HPRAE5', 'VPRAE8', 'GP21A3', 'VPMAE8', 'AP86C2']
  Model_Year: ['M', 'X', 'L', 'W', 'Y', 'N', 'P', 'T', 'G', 'V', 'E', 'R', '7', 'H', 'F', 'J', '4', 'D', '5', 'S', 'K', 'A', 'C', '6']
  Plant_Code: ['P', '0', 'G', '7', '3', 'J', 'A', 'C', 'D', '1', 'Y', 'L', 'H', 'K', 'S', 'V']
  Serial_Number: ['184032', '132577', '085236', '211425', '171429', '212115', '226082', '139390', '232357', '293169', '189580', '762880', '120418', '221357', '045441', '273151', '001313', '168705', '068688', '033901', '080398', '170618', '067133', '042707', '224414', '061410', '171207', '052390', '126763', '567538', '085573', '020974', '106881', '213788', '044089', '007414', '006275', '041193', '207766', '153613', '019091', '202258', '327791', '055039', '302947', '215880', '130041', '102045', '158262', '225029', '018836', '109807', '007590', '049761', '215051', '018663', '040390', '067964', '109808', '117336', '156580', '053045', '126436', '050040', '022498', '124551', '087259', '189503', '267065', '050276', '304507', '241272', '203501', '027713', '035204', '116570', '205053', '052933', '185574', '159899', '226949', '138764', '152757', '028916', '152435', '778338', '009856', '108802', '123887', '763736', '004808', '054207', '617688', '076469', '204604', '010954', '170401', '054701', '195733', '017468', '013316', '037471', '267978', '232764', '080783', '185467', '212413', '218282', '204190', '223868', '208839', '084728', '089930', '036339', '005263', '028327', '116242', '217098', '356443', '234351', '137656', '062870', '150579', '125863', '029384', '002401', '008756', '123671', '129417', '063684', '348195', '007245', '147672', '001691', '597338', '006927', '044775', '224602', '759829', '035881', '027271', '137394', '212337', '230427', '205370', '050989', '329031', '055849', 'ELTZ4B', '151597', '201368', '136803', '103478', '120837', '209215', '237113', '148179', '197172', '071432', '159567', '211525', '142647', '146151', '458531', '024401', '014871', '112870', '776287', '249268', '347330', '066623', '238657', '011546', '149147', '214783', '041847', '011762', '031381', '076391', '073730', '100780', '041658', '122713', '769680', '008022', '086534', '030179', '197003', '231481', '063930', '194590', '029868', '141307', '009703', '348808', '014267', '136572', '008495', '002526', '137829', '114527', '128142', '203382', '121129', '183743', '000622', '215727', '195776', '003930', '124880', '082776', '032076', '001181', '006232', '354828', '197104', '342737', '121121', '234290', '222652', '362026', '032081', '011470', '237693', '012717', '233660', '200837', '167354', '053403', '058298', '007332', '168153', '230181', 'H00063', '221827', '054277', '231420', '102927', '210162', '173317', '070524', '013784', '204442', '064184', '031155', '103316', '238929', '006671', '214613', '042845', '016560', '039590', '208266', '218233', '059614', '183957', '197368', '101475', '089881', '207430', '200108', '184086', '531329', '021542', '109766', '061404', '162199', '151424', '005658', '153117', '008028', '134035', '241793', '061296', '127956', '061505', '018594', '001742', '115283', '164530', '215718', '021055', '166983', '197978', '036317', '034415', '136531', '200867', '215695', '177068', '501090', '279784', '228481', '053930', '118471', '579905', '093631', '194432', '154309', '227307', '019008', '267272', '010917', '074526', '114047', '061355', '170270', '023952', '052568', '116101', '132562', '286294', '177094', '094886', '224204', '458749', '043809', '196933', '200820', '112393', '105133', '199907', '006857', '035841', '165389', '725820', '223337', '032156', '193262', '050869', '214059', '090903', '144428', '008552', '231752', '049582', '214447', '116485', '152255', '259126', '253000', '033751', '005888', '132473', '149223', 'RYHD3R', '200536', '091138', '271506', '014765', '138608', '348351', '135934', '042249', '112307', '213877', '020223', '043742', '156169', '071593', '157213', '013984', '224829', '224213', '138155', '108699', '091930', '089147', '103994', '211871', '162058', '125980', '131344', '219064', '359787', '081184', '214234', '221219', '325881', '148437', '201822', '165866', '075985', '215094', '168093', '130043', '064250', '194866', '216084', '210523', '021765', '015340', '202539', '013767', '182630', '223708', '231955', '042902', '089176', '217147', '184289', '229717', '082571', '080880', '124440', '226999', '172684', '064763', '046568', '216877', '123515', '169490', '216779', '211547', '028331', '010339', '048063', '011220', '337232', '809442', '008392', '054731', '449771', '262966', '008708', '093176', '104835', '376354', '214947', '137751', '053149', '207918', '002561', '036643', '053159', '211555', '180944', '087003', '041048', '151954', '020320', '041458', '145036', '225476', '116540', '006007', '237566', '223496', '083383', '135023', '013088', '079554', '064676', '029454', '109709', '075261', '240618', '043526', '169948', '213762', '066318', '063677', '117293', '144553', '202480', '203700', '014882', '038221', '421379', '111979', '103856', '005758', '069654', '306477', '010391', '719165', '154988', '227219', '074591', '130884', '214017', '153371', '032149', '112055', '201751', '046711', '181057', '224128', '045492', '224503', '118637', '065529', '190737', '109337', '149265', '108092', '032857', '195031', '007290', '133958', '145581', '104022', '008424', '241608', '005116', '392219', '241316', '106901', '177905', '012113', '048102', '011720', '228657', '108611', 'P15378', '138559', '012644', '131435', '119892', '117237', '157523', '089200', '117370', '178198', '782513', '017638', '060988', '296665', '213914', '077253', '249398', '117786', '617563', '207796', '138226', '018310', '054337', '148324', '014562', '049170', '113855', '008623', '036588', '106370', '002613', '756936', '111914', '206458', '135244', '205118', '170826', '030465', '024420', '220507', '141525', '218377', '203670', '332631', '012302', '057035', '164848', '080088', '149090', '130149', '220932', '009000', '058833', '078399', '102282', '221296', '005179', '207944', '087876', '120153', '188223', '122065', '117050', '046559', '045338', '190935', 'AE0205', '170488', '014754', '211629', '224350', '011777', '123356', '231894', '012234', '021903', '038832', '184130', '221954', '274701', '240457', '076453', '241034', '153392', '089398', '050004', '015987', '040969', '005716', '155016', '052691', '099564', '187370', '003674', '017127', '003685', '188038', '222529', '226956', '223778', '003140', '161766', '163327', '111103', '168995', '018069', '146795', '183183', '005100', '203283', '157753', '073946', '220772', '116670', '174695', '001681', '119160', '119732', '004537', '771113', '224321', '082104', '075326', '191399', '084901', '075797', '237641', '133348', '176535', '350281', '032368', '007253', '224908', '066781', '466269', '003121', '211167', '101400', '139383', '035223', '109201', '190080', '015481', '204481', '073409', '001071', '026731', '116102', '043283', '138309', '006784', '059326', '001084', '007139', '332657', '096184', '044857', '133880', '274720', '152189', '046750', '045463', '134981', '154751', '006431', '205238', '756102', '088082', '047830', '041238', '006361', '032760', '172013', '077003', '274379', '045022', '165787', '334455', '050962', '108764', '336163', '039759', '116123', '097745', '060785', '049403', '067948', '004735', '145672', '100207', '309858', '198941', '115794', '198180', '023687', '107482', '003370', '040274', '201113', '382035', '298334', '212016', '151212', '138427', '005595', '228575', '151142', '143897', '111913', '222618', '014961', '127739', '234341', '121233', '015515', '179347', '062693', '174754', '112133', '154929', '239673', '243365', '116251', '158639', '135302', '127414', '227917', '179560', '149689', '212352', '012942', '214634', '047164', '236439', '105532', '174421', '123910', '234066', '323968', '015042', '200298', '121498', '168826', '163882', '200979', '038180', '240870', '092558', '108590', '184619', '045438', '138606', '156706', '207961', '010351', '207653', '192977', '154027', '009589', '225843', '155979', '085284', '161624', '054004', '041263', '212407', '008164', '209183', '127875', '228227', '045853', '195245', '108165', '057139', '214555', '258197', '229134', '086903', '062399', '036675', '172841', '107858', '006390', '077503', '007677', '191408', '225240', '201667', '111137', '215549', '124508', '214306', '060276', '096243', '271576', '147567', '003034', '007679', '163306', '183030', '243135', '112969', '239002', '065188', '085257', '015317', '207201', '217342', '342158', '180439', '035034', '212931', '152561', '216023', '239494', '196823', '286140', '581145', '200121', '144296', '224826', '217589', '042887', '178463', '200851', '107435', '162950', '002181', '015324', '016133', '001366', '002634', '140157', '232675', '096455', '201595', '221836', '181461', '097530', '092767', '005518', '073362', '195019', '005702', '171342', '137043', '027213', '012643', '081186', '277572', '234088', '080940', '064389', '105731', '014385', '130838', '103404', '227064', '025160', '225644', '111343', '170906', '079805', '008962', '053584', '566754', '118666', '132394', '149949', '146665', '128358', '007765', '110240', '055665', '123378', '007817', '018691', '214264', '100496', '017675', '020502', '175342', '176756', '018001', '041150', '175396', '001562', '018795', '187914', '191166', '231529', '101958', '214542', '333822', '138236', '013415', '005243', '306562', '213859', '328449', '022364', '017136', '033762', '080895', '756181']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,E,GLI,GCC,4.0,5YF,EPMAE0,M,P,184032
1,TOYOTA,OTHERS,0.0,COUPE,D,XLI,GCC,NaN,JT2,DP02T1,X,0,132577
2,TOYOTA,COROLLA,4.0,SEDAN,E,LE,GCC,4.0,5YF,EPRAE9,L,P,085236
3,TOYOTA,RAV4,4.0,SUV,H,STD,GCC,3.0,JT3,HP10V2,X,0,211425
4,TOYOTA,RAV4,4.0,SUV,Y,GXR,GCC,5.0,JT3,YP10V8,W,0,171429
...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,TOYOTA,COROLLA,4.0,SEDAN,E,XLI EXECUTIVE,NON-GCC,NaN,JTD,EPMAE2,N,3,022364
925,TOYOTA,COROLLA,4.0,SEDAN,E,LE,NON-GCC,NaN,JTD,EPRAE0,L,J,017136
926,TOYOTA,COROLLA,4.0,SEDAN,E,LE,NON-GCC,NaN,5YF,EPRAE1,L,P,033762
927,TOYOTA,COROLLA,4.0,SEDAN,D,STD (NON GCC),NON-GCC,NaN,JTD,DPRAE2,L,J,080895
928,TOYOTA,COROLLA,4.0,SEDAN,A,XLI EXECUTIVE,NON-GCC,NaN,LFM,AP22C2,G,0,756181

====================================================================================================
pos5: 0
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'LAND CRUISER', 'PREVIA', 'SUPRA', 'YARIS', 'RAV4', 'AVALON', 'FORTUNER', 'CAMRY', 'HILUX', 'PRADO', 'ALTIS', 'INNOVA', 'HIACE', 'FJ CRUISER']
  bodyType: ['SEDAN', 'SUV', 'MPV', 'COUPE', 'HATCHBACK', 'PICKUP', 'PICK UP SINGLE CAB', 'PICK UP DOUBLE CAB', 'PANEL VAN']
  pos4: ['1', 'H', '0', '8', 'R', '5', 'N', 'B', 'V', '4', '6', 'C', '9', '3', 'A']
  trim: ['XLI', 'EXR', 'DLX', 'STD', 'MID', 'LE HEV', 'BASE', 'GLX', 'GXR3', 'GRANDE', 'XLI TOP', 'XLI MID', 'GX', 'GL', 'GLI', 'S', 'VX', 'GXR', 'DL', 'DX', 'LE', 'SE', 'GLE', 'FLEET', 'SE+', 'TOP', 'XLI EXECUTIVE']
  regionalSpec: ['NON-GCC', 'GCC']
  WMI: ['ZSG', 'JTM', 'UP1', 'JZA', '000', 'ZE1', 'NNN', 'WBW', 'AAP', 'FZJ', 'NV1', 'SXV', 'JTE', 'ACV', '4T1', 'YN8', 'EE1', 'MV1', 'LA9', 'W1W', 'WDB', '090', '010', 'MET', 'EP9', 'AVV', 'FJ7', 'A25', 'STM', 'CE1', 'EL5', '4TT']
  VDS: ['100319', 'H009J1', '007130', '800014', '00NCP9', 'R03FV0', '509542', 'N00001', 'B01111', 'V02912', '800025', '800083', '802339', '000NNN', '804733', '008004', '803285', '803454', '808508', '804307', '800005', '500127', '002606', '805931', '501891', '802744', '809870', '502581', '107013', '506028', '805832', 'H00936', '804134', '800004', '405038', '809434', '501857', '006121', '008567', '405034', '800971', '505243', '806367', '809867', '808931', '801FKA', '800030', '809072', '600238', '004046', '504705', '807726', '502370', '800631', 'B025J8', '405002', '800157', '802811', 'C08RW6', '801259', '509750', '800426', 'V0LEZ3', '906155', '805336', 'H009J3', 'B03FVX', '506377', '503335', 'V0LEZ4', '500188', '508121', '408B06', '803505', '502877', '505313', '805326', '808764', '303H66', '804598', 'H009JX', '405006', '500185', '509751', '0000EA', '100305', 'H009J6', '805485', 'R03FV2', '804646', '503914', 'N00011', '505003', '800957', '502294', 'B031V6', '500617', '506174', '506713', '508736', '807674', '500176', '505046', '802510', '807611', '809514', 'A0B982', '600198', '000NCP', '800788', '505015', '405009', '502968', '009432', '804077', '808390', '008983', '107305', 'B011F6', '009687', '500903', '803180', '805587', '805065', '801838', '000983', '809506', '807007', '0000JA', '800253', 'B046K9', 'B031V5', '504797', '808905']
  Model_Year: ['6', 'D', '4', '9', '1', 'P', '3', '2', 'N', '7', '8', '5', 'F', 'E', 'S', 'L', 'W', 'R', 'A', 'B']
  Plant_Code: ['0', '5', '1', '9', 'D', 'N', '3', ' ', '4', 'U', '7', '6', 'B', 'J', 'A', '2', '8', 'K', 'W']
  Serial_Number: ['400000', '065001', '000000', '600000', '097501', '572376', '111111', '583414', '3     ', '100000', '679254', '611111', '876541', '900000', '001223', '131047', '855555', '      ', '565555', 'WTHJUN', '300000', '157832', '200000', '666666', '021274', '6W0000', 'JXK069', '937952', '327369', '101522', '287503', '975631', '740401', '0448PN', '444444', '114060', '021915', '101669', 'R12345', '235176', '655554', '222222', '247231', '330000', '645456', '582683', '900255', '700000', '745874', '585855', '190447', 'SSSSSS', '101000', 'RTUK14', '024461', '001241', '012212', '910077', '018482', '123323']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,1,XLI,NON-GCC,NaN,ZSG,100319,6,0,400000
1,TOYOTA,LAND CRUISER,6.0,SUV,H,EXR,GCC,5.0,JTM,H009J1,D,5,065001
2,TOYOTA,PREVIA,4.0,MPV,0,DLX,NON-GCC,NaN,UP1,007130,4,0,000000
3,TOYOTA,SUPRA,6.0,COUPE,8,STD,NON-GCC,NaN,JZA,800014,9,1,600000
4,TOYOTA,YARIS,4.0,HATCHBACK,0,MID,NON-GCC,NaN,000,00NCP9,1,9,097501
...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,NON-GCC,NaN,NV1,800253,9,0,012212
133,TOYOTA,CAMRY,4.0,SEDAN,B,GLX,GCC,NaN,4TT,B046K9,9,U,910077
134,TOYOTA,RAV4,4.0,SUV,B,BASE,GCC,5.0,JTM,B031V5,B,D,018482
135,TOYOTA,COROLLA,4.0,SEDAN,5,XLI MID,GCC,NaN,ZE1,504797,3,0,000000
136,TOYOTA,CAMRY,4.0,SEDAN,8,XLI,GCC,NaN,NV1,808905,7,W,123323

====================================================================================================
pos5: 8
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'COROLLA', 'CAMRY', 'COROLLA SEDAN', 'INNOVA', 'HILUX', 'VELOZ', 'LAND CRUISER', 'HIGHLANDER', 'COROLLA 1.6', 'HIACE', 'PRIUS', 'VESPA VXL 150', 'VESPA VXL']
  bodyType: ['SUV', 'SEDAN', 'MPV', 'PICK UP DOUBLE CAB', 'SALOON', 'PANEL VAN', 'HATCHBACK', 'MOTORCYCLE', 'STATION', 'PICK UP DOUBLE CABIN', 'PICKUP DOUBLE CAB']
  pos4: ['W', '8', '3', 'M', 'C', 'A', 'L', 'B', '2', 'K', 'D']
  trim: ['EX', 'XLI', 'GL', 'SE+', 'LIMITED', 'GLI', 'DLX', 'GLX', 'VXR', 'GLE', 'GRANDE', 'GXR', '10TH VICTORY EDITION', 'AXL ', 'XLI EXECUTIVE', 'E', 'ECO', 'STD (NON GCC)', 'BLACK EDITION', '60TH', 'LE', 'SE']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['WWW', 'RKL', 'JTN', 'MAT', 'MET', 'LFM', 'MHF', 'JTM', '5TD', 'WV1', 'KMF', 'JTD', '4T1', 'MD6', 'MR0']
  VDS: ['W88888', '889HE9', '8846K0', '381228', 'M85002', 'M85007', 'C8E2H4', '880CE2', '381324', 'A818Y7', 'A878J9', 'M85004', '889HEX', 'M85008', 'M8500X', 'L83CH1', 'A888J6', '88OCEX', '880CEX', 'B89HE2', '2882K7', 'M85003', 'W8X7K8', 'A878J5', 'K83FU8', 'K83FU9', '8842E9', 'K8RFU5', 'A888J9', 'A818Y5', 'K83FU3', 'K83FU0', '8842E4', '8846K5', 'L83CH3', '889HE2', '889HE6', 'M85000', '8842E6', 'B89HE0', 'K820U9', '38BS17', '8842E8', 'A878J7', '8842EX', '8808E2', 'D89CD7', 'D89CD3', '889HE5']
  Model_Year: ['8', '6', '7', 'G', 'V', 'H', 'R', 'P', 'S', 'J', 'L', '5', 'E', 'C', 'N', 'K', 'A', 'F', '9']
  Plant_Code: ['8', '5', '3', '7', '0', '4', 'X', 'U', '1']
  Serial_Number: ['888888', '144265', '023530', 'L00083', '003746', '003712', '309873', '001709', 'L00536', '112687', '097697', '003646', '220356', '003259', '003280', '011715', '160597', '013290', '025521', '001271', '003413', '469842', '028941', '595016', '084402', '007618', '015475', '003439', '001803', '045101', '122005', '589687', '585287', '005887', '003019', '121910', '105976', '003432', '009917', '240473', '206230', '003388', '001697', '003276', '100927', '004739', '010273', '455852', 'A20031', '005942', '003159', '107742', '001905', '110227', '006238', '133264', '020512', '019082', '003635', '036983']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,RAV4,4.0,SUV,W,EX,GCC,NaN,WWW,W88888,8,8,888888
1,TOYOTA,COROLLA,4.0,SEDAN,8,XLI,GCC,NaN,RKL,889HE9,6,5,144265
2,TOYOTA,CAMRY,4.0,SEDAN,8,GL,GCC,4.0,JTN,8846K0,7,3,023530
3,TOYOTA,CAMRY,4.0,SEDAN,3,SE+,GCC,NaN,MAT,381228,G,7,L00083
4,TOYOTA,COROLLA SEDAN,0.0,SEDAN,M,XLI,GCC,NaN,MET,M85002,V,3,003746
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,TOYOTA,COROLLA,4.0,SEDAN,8,GLI,GCC,NaN,RKL,889HE9,F,5,133264
57,TOYOTA,HILUX,4.0,PICK UP DOUBLE CABIN,D,GL,GCC,NaN,MR0,D89CD7,5,5,020512
58,TOYOTA,HILUX,4.0,PICKUP DOUBLE CAB,D,GL,GCC,NaN,MR0,D89CD3,5,5,019082
59,TOYOTA,CAMRY,4.0,SEDAN,M,LE,GCC,NaN,MET,M8500X,S,3,003635
60,TOYOTA,COROLLA,4.0,SEDAN,8,SE,GCC,NaN,RKL,889HE5,F,5,036983

====================================================================================================
pos5: 9
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIGHLANDER', 'YARIS', 'PRIUS', 'RAV4', 'COROLLA', 'FRONTLANDER', 'GL770ULTRA', '2023', '900']
  bodyType: ['SUV', 'HATCHBACK', 'SEDAN', 'MOTORCYCLE', 'STATION']
  pos4: ['C', '5', 'L', '7', 'P', 'B', 'W']
  trim: ['GXR', 'BASE', 'ECO', 'EX', 'LE (NON GCC)', 'GLI', 'STD', '2', 'MID']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['LVG', 'JWT', 'JTD', 'L6T', 'LBB']
  VDS: ['C916Z7', '596950', 'L9RFU8', 'C916Z4', 'C916Z0', 'C916ZO', 'C916Z9', '79END0', '79YND1', 'C916Z6', 'L9MFU9', 'C916Z8', '79END6', 'C916ZX', 'P99006', 'B910L5', '79END5', 'W9235A']
  Model_Year: ['P', '4', 'K', 'S', 'T', 'M', 'R', '1']
  Plant_Code: ['G', '0', '3', 'T', 'B', '1']
  Serial_Number: ['034031', '606456', '009662', '119045', '122508', '127529', '239077', '250817', '114414', '026069', '073343', '105644', '248866', '119552', 'F55801', '003716', '237504', '073592', '857090']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,GCC,5.0,LVG,C916Z7,P,G,034031
1,TOYOTA,YARIS,4.0,HATCHBACK,5,BASE,NON-GCC,NaN,JWT,596950,4,0,606456
2,TOYOTA,PRIUS,4.0,HATCHBACK,L,ECO,GCC,5.0,JTD,L9RFU8,K,3,009662
3,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,GCC,5.0,LVG,C916Z4,S,G,119045
4,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,GCC,5.0,LVG,C916Z0,S,G,122508
5,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,GCC,5.0,LVG,C916ZO,S,G,122508
6,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,GCC,5.0,LVG,C916Z9,T,G,127529
7,TOYOTA,RAV4,4.0,SUV,7,EX,GCC,5.0,L6T,79END0,S,T,239077
8,TOYOTA,RAV4,4.0,SUV,7,EX,GCC,5.0,L6T,79YND1,S,T,250817
9,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,GCC,5.0,LVG,C916Z6,S,G,114414
10,TOYOTA,PRIUS,4.0,HATCHBACK,L,LE (NON GCC),GCC,5.0,JTD,L9MFU9,M,3,026069
11,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,NON-GCC,5.0,LVG,C916Z8,R,G,073343
12,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,GCC,5.0,LVG,C916Z0,S,G,105644
13,TOYOTA,COROLLA,4.0,SEDAN,7,GLI,GCC,NaN,L6T,79END6,S,T,248866
14,TOYOTA,FRONTLANDER,4.0,SUV,C,STD,NON-GCC,5.0,LVG,C916ZX,S,G,119552
15,TOYOTA,GL770ULTRA,NaN,MOTORCYCLE,P,NaN,GCC,NaN,LBB,P99006,P,B,F55801
16,TOYOTA,2023,4.0,SEDAN,B,2,GCC,NaN,LVG,B910L5,P,G,003716
17,TOYOTA,900,4.0,STATION,7,EX,GCC,NaN,L6T,79END5,S,T,237504
18,TOYOTA,HIGHLANDER,4.0,SUV,C,GXR,GCC,5.0,LVG,C916Z7,R,G,073592
19,TOYOTA,YARIS,4.0,HATCHBACK,W,MID,GCC,NaN,JTD,W9235A,1,1,857090

====================================================================================================
pos5: S
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'CAMRY', 'SIENNA', 'HILUX', 'HIGHLANDER', 'PREVIA', 'BZ 4', 'RAV4', 'LAND CRUISER', 'FORTUNER', 'INNOVA', 'COROLLA', 'PRADO', 'LAND CRUISER PICK UP']
  bodyType: ['PANEL VAN', 'SEDAN', 'MPV', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'MINI BUS HIGH ROOF', 'SUV', 'HALF PANEL VAN', 'STATION', 'MINI BUS', 'PICKUP', 'PANEL VAN HIGH ROOF', 'PICK UP']
  pos4: ['J', 'A', 'K', 'E', 'Y', 'G', 'C', 'D', 'H', '2', 'S', 'Z', '3', 'L', 'R']
  trim: ['STD', 'E PLUS HEV', 'LE (NON GCC)', 'DLX', 'GL', 'HYBRID (NON GCC)', 'XSE', 'XLI', 'GRANDE', 'XLE (NON GCC)', 'TRIM', 'XL', 'DX', 'MID', 'GR SPORT', 'GXR MID', 'DL', 'GL LIMITED', 'EXR', 'SPORT', 'GLX', 'SE+', 'LIMITED', 'GLS', 'VX TOP LTH', 'SE', 'LX AC PWR OPT', 'S', 'GXR']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JT6', 'JTN', '5TD', 'MR0', 'JTG', 'LVG', 'JTE', 'YV2', 'JTF', '2GN', 'UAE', 'LFM', '1FT', 'KMF', 'SAL', 'LS4', 'YV1', '123', 'JHD', '5ZT']
  VDS: ['JS02P8', 'ASACK7', 'KSKFC3', 'ES12G0', 'ES12G6', 'JS02P1', 'ES46A1', 'YSKFC5', 'GS54M3', 'ASG0A9', 'JS02P6', 'GS54M0', 'GS54M5', 'CS12G7', 'ES12G8', 'DS43A2', 'CS12G8', 'JS02P4', 'HS02P6', 'CS18Z3', '2S0125', 'CS12G4', 'YSKFC3', 'SS23P1', 'GS54M1', 'AS14U0', 'DS41A0', 'SS3EL5', 'ES41A2', 'ZSZ7JA', 'GS54M6', 'ES12G5', '3S0113', 'LSAAE4', 'GS54M8', 'GS54M4', 'ES12GX', 'JS8CD5', 'ASB3R9', 'ES12G1', 'AS47HB', 'ES12G7', 'GS54M9', 'HS02P8', 'AS12G0', 'GS54MX', 'GS54M2', 'AS1232', 'ES43A6', 'ES12G3', 'ZSZ7KB', 'JS02P2', 'CS12G5', 'ASW0AX', 'ES12G9', 'GSKFC5', 'SS1EK5', 'SS1EK7', 'AS02A5', 'SS22P2', 'JS02PX', 'ASB3R8', 'DSKFCX', 'HS02PX', 'KSKFC7', '2SBPB2', 'KSKFC1', 'ES12G4', 'AS02D0', '2S0107', 'AS12G9', 'ES43A8', 'AS02D8', '2S0117', 'RS12P4', 'SS23PX', 'HS02P3', 'AS02A4', 'JS02P9', 'AS02A2', 'ASW0A9', 'ES12G2']
  Model_Year: ['7', '5', 'M', '8', 'E', 'R', 'C', '9', 'A', '6', 'P', 'H', 'F', '3', 'L', 'D', 'N', 'G', 'B']
  Plant_Code: ['0', '3', 'S', '5', 'G', 'A', 'B', '7', '2', 'D', 'U', '1']
  Serial_Number: ['010233', '049875', '002800', '304683', '310905', '046125', '307449', '004180', '118758', '000190', '538364', '046119', '003585', '011785', '068074', '028890', '078543', '046471', '046981', '304294', '024262', '115562', '108490', '108621', '076538', '202210', '000107', '010018', '046056', '067106', '015756', 'A15620', '115525', '034290', '769564', '000345', '307457', '23919 ', '246591', '004001', '003329', '308183', '340382', '153840', '016296', '178204', '000122', '018358', '000176', '003886', '028310', '101956', '302083', '003829', '004016', '001629', '000312', '231233', '145178', '000431', '000327', '800209', '003484', '307408', '752164', '032269', '003899', '000464', '047481', '428963', '015025', '027533', '000524', '040180', '046121', 'S10498', 'S10499', '433644', '013045', '162834', '046138', '153845', '004701', '013082', '010031', '026174', '024555', '021351', '001099', '035796', '069235', '306566', '651055', '034110', '003764', '036758', 'S10584', '013377', '140693', '007163', '301924', '000330', '014081', '003859', '035737', '003914', '651675', '022230', '037390', '033479', '162210', '103227', '645653', '032351', '003827', '434069', '434530', '035997']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,PANEL VAN,J,STD,GCC,4.0,JT6,JS02P8,7,0,010233
1,TOYOTA,CAMRY,4.0,SEDAN,A,E PLUS HEV,GCC,4.0,JTN,ASACK7,5,3,049875
2,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),GCC,5.0,5TD,KSKFC3,M,S,002800
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,E,DLX,GCC,4.0,MR0,ES12G0,8,3,304683
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,E,DLX,GCC,2.0,MR0,ES12G6,E,3,310905
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,TOYOTA,HIACE,4.0,MINI BUS,J,GL,GCC,5.0,JTG,JS02P9,D,0,032351
114,TOYOTA,PREVIA,6.0,MPV,G,GL,GCC,5.0,JTE,GS54M9,7,0,003827
115,TOYOTA,COROLLA,4.0,SEDAN,A,XLI,NON-GCC,NaN,YV2,AS02A2,6,B,434069
116,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,A,DLX,GCC,NaN,YV2,ASW0A9,6,B,434530
117,TOYOTA,HILUX,4.0,PICKUP,E,DLX,GCC,NaN,MR0,ES12G2,C,3,035997

====================================================================================================
pos5: 7
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'HILUX', 'INNOVA', 'CAMRY', 'RUSH', 'COROLLA', 'RAV4', 'SIERRA', 'SEQUOIA', 'U7']
  bodyType: ['PANEL VAN', 'PICK UP DOUBLE CAB', 'MPV', 'SEDAN', 'HATCHBACK', 'SUV', 'MINI BUS HIGH ROOF', 'MINI BUS']
  pos4: ['2', '3', 'C', 'F', '1', 'B', 'W', '8', '4', 'S', 'Z']
  trim: ['GL', 'DLX', 'HEV', 'GLX', 'SE', 'STD', 'LE', 'STANDARD', 'S', 'EX', 'A', 'SR5 4X4', 'XLI', 'XLI MID', 'ADVENTURE', 'DX']
  regionalSpec: ['NON-GCC', 'GCC']
  WMI: ['D04', 'MAT', 'LC0', 'MD6', 'LM8', 'JZS', 'LGF', 'ZRE', 'LSJ', '1GT', 'CPB', '074', 'UZS', 'D02', '150', 'RF5', '1GJ']
  VDS: ['2757DX', '374185', 'C74C40', '37DE71', 'F7E692', '171000', '171007', 'B7A2J4', '172554', 'W74U33', 'W78CG1', '172570', '172551', '87N071', '472AXD', '1779DX', '87367Z', 'S71T02', 'F7D196', 'Z78FG6', '172561']
  Model_Year: ['B', '8', 'S', 'N', '1', '3', 'R', '6', 'H', 'C', '5', '7', '4', 'E', 'F', 'P']
  Plant_Code: ['0', '9', '4', '2', 'A', '6', '1', 'C', '5', 'G', '3', '8', 'S']
  Serial_Number: ['000000', 'L02558', '618046', 'B00102', '041147', '810000', '980111', '102050', '450000', '233048', '181220', '151111', '000112', '4TDBY5', '175417', '111111', '000008', '000511', '111987', '614221']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,PANEL VAN,2,GL,NON-GCC,NaN,D04,2757DX,B,0,000000
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,DLX,GCC,4.0,MAT,374185,8,9,L02558
2,TOYOTA,INNOVA,4.0,MPV,C,HEV,GCC,5.0,LC0,C74C40,S,4,618046
3,TOYOTA,CAMRY,4.0,SEDAN,3,GLX,GCC,4.0,MD6,37DE71,S,2,B00102
4,TOYOTA,NaN,4.0,HATCHBACK,F,SE,GCC,NaN,LM8,F7E692,N,A,041147
5,TOYOTA,RUSH,4.0,SUV,1,STD,GCC,NaN,JZS,171000,1,6,810000
6,TOYOTA,CAMRY,4.0,SEDAN,1,LE,NON-GCC,NaN,JZS,171007,3,1,980111
7,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,B,STANDARD,GCC,4.0,LGF,B7A2J4,R,C,102050
8,TOYOTA,COROLLA,4.0,SEDAN,1,S,GCC,NaN,ZRE,172554,6,5,450000
9,TOYOTA,RAV4,4.0,SUV,W,EX,GCC,5.0,LSJ,W74U33,H,G,233048
10,TOYOTA,SIERRA,4.0,MPV,W,A,GCC,NaN,1GT,W78CG1,C,1,181220
11,TOYOTA,COROLLA,4.0,SEDAN,1,SE,NON-GCC,NaN,ZRE,172570,5,3,151111
12,TOYOTA,COROLLA,4.0,SEDAN,1,S,NON-GCC,NaN,ZRE,172551,7,8,450000
13,TOYOTA,CAMRY,4.0,SEDAN,8,S,GCC,NaN,CPB,87N071,6,6,000112
14,TOYOTA,SEQUOIA,8.0,SUV,4,SR5 4X4,GCC,5.0,074,472AXD,S,6,4TDBY5
15,TOYOTA,CAMRY,8.0,SEDAN,1,STD,GCC,NaN,UZS,171000,4,8,175417
16,TOYOTA,COROLLA,4.0,SEDAN,1,XLI,NON-GCC,NaN,D02,1779DX,B,0,000000
17,TOYOTA,COROLLA,4.0,SEDAN,8,XLI MID,NON-GCC,NaN,150,87367Z,E,1,111111
18,TOYOTA,U7,4.0,SEDAN,S,GLX,GCC,NaN,RF5,S71T02,F,S,000008
19,TOYOTA,RAV4,4.0,SUV,F,ADVENTURE,GCC,NaN,LM8,F7D196,P,A,000511
20,TOYOTA,HIACE,8.0,MINI BUS,Z,DX,GCC,NaN,1GJ,Z78FG6,C,1,111987
21,TOYOTA,COROLLA,4.0,SEDAN,1,SE,NON-GCC,NaN,ZRE,172561,6,3,614221

====================================================================================================
pos5: I
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'CAMRY']
  bodyType: ['SUV', 'SEDAN']
  pos4: ['C', 'A', 'W', 'F']
  trim: ['VX', 'XLE', 'LE HEV']
  regionalSpec: ['GCC']
  WMI: ['JTM', 'JTN', '2T3']
  VDS: ['CIRFV7', 'AI4CK5', 'WIRFV6', 'FIRFVO', 'FIRFV0', 'WIRFVX', 'WIRFVI']
  Model_Year: ['K', 'S', 'R', 'M']
  Plant_Code: ['J', '3', 'W', 'D', 'C']
  Serial_Number: ['015013', '029853', '333620', '045983', '111527', '129334']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,RAV4,4.0,SUV,C,VX,GCC,5.0,JTM,CIRFV7,K,J,015013
1,TOYOTA,CAMRY,4.0,SEDAN,A,XLE,GCC,4.0,JTN,AI4CK5,S,3,029853
2,TOYOTA,RAV4,4.0,SUV,W,LE HEV,GCC,5.0,2T3,WIRFV6,R,W,333620
3,TOYOTA,RAV4,4.0,SUV,F,VX,GCC,5.0,JTM,FIRFVO,K,D,045983
4,TOYOTA,RAV4,4.0,SUV,F,VX,GCC,5.0,JTM,FIRFV0,K,D,045983
5,TOYOTA,RAV4,4.0,SUV,W,XLE,GCC,5.0,2T3,WIRFVX,M,C,111527
6,TOYOTA,RAV4,4.0,SUV,W,XLE,GCC,5.0,2T3,WIRFVI,M,C,129334

In [200]:
from IPython.display import display

for pos_6 in data['pos6'].dropna().unique():

    # 1. Filter the DataFrame for the current pos6 value
    filtered_df_pos6 = data.loc[
        data['pos6'] == pos_6,
        ['make', 'model', 'cylinders', 'bodyType', 'pos4', 'trim',  'regionalSpec', 'noOfDoors','WMI', 'VDS', 'Model_Year', 'Plant_Code','Serial_Number']
    ].reset_index(drop=True)

    # 2. Header for the current pos6 group
    print("\n" + "=" * 100)
    print(f"pos6: {pos_6}")
    print("=" * 100)

    # 3. Print unique values for all object columns (except pos6)
    print("--- Unique Values for Object Columns ---")
    object_cols = filtered_df_pos6.select_dtypes(include=['object']).columns
    
    for col in object_cols:
        if col != ['pos6', 'VDS']:
            unique_vals = filtered_df_pos6[col].dropna().unique()
            print(f"  {col}: {list(unique_vals)}")
            
    print("-" * 100)

    # 4. Display the filtered DataFrame
    display(filtered_df_pos6)

====================================================================================================
pos6: 9
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'YARIS', 'CAMRY', 'HILUX', 'RAV4', 'PRADO', 'HIACE', 'LAND CRUISER', 'PRIUS', 'INNOVA', 'AVALON', 'TAKOMA', 'TACOMA', 'SALOON', 'PICK UP', 'LAND CRUISER PRADO', 'HILUX RE', 'RAV 4', 'PRADO GX', 'COASTER', 'TOYOTA PRADO', 'HIACE ', 'TOYOTA', 'ALTIS', '4RUNNER', 'COROLLA 1.6', 'TOYOTA COROLLA 2.0', 'COROLLA 1.3', '26HX DC 4X4 PLAT', '2 HX DC 4X4 P 2.7LAT', 'كامرى', 'TOYOTA COROLLA', '2024', 'كورولا', '2014', 'GL770ULTRA', 'برادو', 'PREVIA', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'SUV', 'PICK UP SINGLE CAB', 'PANEL VAN', 'PANEL VAN HIGH ROOF', 'MINI BUS HIGH ROOF', 'BUS', 'MINI BUS', 'PICKUP', 'MPV', 'STATION', 'PICK UP', 'PICKUP SINGLE CABIN', 'SALOON', 'CARAVAN', 'VAN', 'PICKUP DOUBLE CAB', 'PICKUP DOUBLE CABIN', 'MOTORCYCLE', 'LIGHT VEHICLE', 'PICK UP DOUBLE CABIN']
  pos4: ['B', 'K', 'C', 'R', 'J', 'D', 'Z', 'W', 'H', 'A', '8', 'N', 'F', 'S', 'E', '5', 'V', '2', '4', 'P', '9', 'Y', '6', 'M', 'X', '0', 'T']
  trim: ['SE', 'MID', 'E', 'GL', 'S', 'FLEET', 'GL2', 'LE', 'GXR', 'XLI', 'TX', 'SE TRD AERO PK', 'BASE', 'STD', 'SE+', 'EX', 'GLX', 'LIMITED', 'TOP', 'S+', 'VX', 'GX', 'TX-L', 'TX-L TOP', 'EXR', 'GLI', 'GLS', 'STD (NON GCC)', 'SGLX', 'VXR', 'TXL3', 'SPORT', 'DLX', 'VX TOP LTH', 'DLS', 'VX MID', 'LE HEV', 'HEV', 'G', 'GLE', 'YX', 'GXR TOP', 'STANDARD', 'LIMITED TRD SPORT PK', 'GRANDE', 'TXR', 'GLE-X HEV 40TH ANNIV', 'T', 'Y PLUS', 'GLX SPORT Z', '1500', 'GLE HEV', 'BE', 'ADVENTURE', 'GLI TOP', '25HX', 'SE TRD SPORT PK', 'LE STD', 'GXL', 'XLI MID', 'S TRD SPORT PK', 'DLS - STD ROOF', 'HYBRID', 'ADVENTTURE', 'Y', 'DL', 'XLI TOP', 'LIMITED TRD AERO PK', 'XLI EXECUTIVE', '60TH', 'GXL 1ST EDITION', 'VX-L MID', 'PW CL', 'GRD', 'VX-L TOP', 'DLS HIGH ROOF', 'PLATINUM', 'GXR TOP 60TH ANNIV. XTREME', 'GRANDE HEV', 'XL', 'SL', 'CAR TRIM', 'A', 'LXI', 'GC', 'SWB', '90', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['RKL', 'JTD', 'MR2', '6T1', 'MR0', 'JTN', 'MHF', 'JTM', 'JTE', 'MRO', 'JTG', '4TA', '137', 'JT3', 'JTB', 'ZE1', '5TE', 'JT0', 'LFV', 'MAT', 'JH4', 'NMT', 'MHE', 'NCP', 'JT5', 'MR1', '1GT', 'NV1', '6TT', 'WD8', 'MFH', 'VR3', 'JD2', 'AR2', 'JIN', 'JT4', 'JT2', 'WDB', 'LFM', 'YAR', '671', 'MP2', 'ITD', 'KNC', 'ST1', 'JTU', '611', 'M0F', 'LVG', 'LBB', 'MHM', '1NX', 'HA9', 'UP1', 'JT6', 'BKL', 'JNE']
  VDS: ['BB9HE7', 'BW9230', 'BF9C35', 'BF9FK1', 'BF9FK9', 'KW9239', 'CX9CB1', 'BF9HK0', 'B29F32', 'BT9F38', 'RF9EV1', 'KW9236', 'BL9HE1', 'JU9FJ1', 'B29F35', 'KT9F38', 'BW9233', 'K19F35', 'JT923X', 'KW9F31', 'KW9238', 'DB9CD3', 'BL9HE3', 'B29F30', 'KW9231', 'KW9232', 'ZF9EV4', 'K19F32', 'KW9D38', 'KW923X', 'B29F31', 'BB9HE9', 'KW9D35', 'B29F39', 'BL9HE5', 'BL9HE7', 'KW9D33', 'JX9CD1', 'KW9D34', 'BT9F39', 'BT9230', 'KW9D36', 'BU9FJ2', 'BT9F32', 'B29HK6', 'BW9234', 'BT9F36', 'KW9D39', 'BT9F35', 'KW9036', 'BL9HE9', 'KW9D30', 'KW9234', 'KW9D31', 'BB9HE2', 'KT9F31', 'BF9FK3', 'BF9FK7', 'BW9232', 'BB9HE4', 'KW9D3X', 'BF9FK6', 'BF9FK0', 'BB9HE0', 'BW9238', 'BF9FK4', 'BL9HE4', 'B29F38', 'CX9CB0', 'B29F37', 'BL9HE2', 'WF9EV2', 'CX9CDO', 'BL9HEX', 'KW9F32', 'BB9HE8', 'CX9CD4', 'BX9FJ6', 'DF9EV0', 'BF9FKX', 'B29F34', 'KW9237', 'DX9CD0', 'BB9HE6', 'BW9339', 'BL9HE8', 'RF9EV5', 'BW9237', 'DF9EV2', 'BF9FK2', 'BW9235', 'BU9FJ5', 'CX9CB6', 'KT9F30', 'ZF9EV6', 'K19F31', 'CW9CDX', 'KW9235', 'K19F39', 'KW9039', 'BB9HE5', 'JU9FJ4', 'DF9EV3', 'K19F30', 'BF9FK5', 'BL9HE0', 'K19F38', 'BW9236', 'BB9HEX', 'B29F33', 'BF9EV9', 'B29F36', 'DF9EV8', 'BW9330', 'CX9CB7', 'B29HK0', 'BU9FJ6', 'DF9EVX', 'KW9233', 'KW9230', 'BL9HE6', 'KT9236', 'HN9CP1', 'JU9FJ9', 'BF9FK8', 'WF9EV7', 'BU9FJ3', 'BF9EV2', 'BF9C34', 'KT9F33', 'RF9EV9', 'B29HK7', 'BF9EV5', 'JU9FJ8', 'KT9231', 'BT9F3X', 'K29F33', 'BT9F33', 'DF9EV6', 'BW9231', 'BF9HK9', 'KT9F36', 'BN95J7', 'KW9F33', 'BB9HE1', 'KW9F30', 'KW9F37', 'JU9FJ6', 'BX9FJ7', 'HN9CP2', 'BT9F31', 'KW9D37', 'BF9HK5', 'KT9230', 'BT923X', 'CX9CB5', 'BU9FJ1', 'JU9FJX', 'K29F36', 'RF9EV8', 'BW923X', 'BB9HE3', 'KT9F37', 'BX9FJ9', 'JU9FJ5', 'CX9CD8', 'RF9EV3', 'RF9EV2', 'KT9F35', 'B29HK2', 'BF9HK8', 'WF9EV6', 'BF9C32', 'K19F3X', 'BT9235', 'BU9FJ9', 'RF9EVX', 'BX9FJX', 'BT9236', 'HN9CP9', 'BX9FJ8', 'B29HK1', 'B29F3X', 'BF9C31', 'K19F34', 'BF9EV3', 'BX9FJ0', 'KW9D32', 'CX9CB8', 'BW933X', 'DX9CD2', 'KW9F39', 'BF9EV0', 'K19F37', 'KT9235', 'B29HK4', 'WF9EV0', 'DX9CD4', 'KW9F3X', 'WF9EV4', 'WF9EV9', 'BU9FJ7', 'KW9F38', 'DB9CD6', 'HN9CPO', 'BT9231', 'CX9CB2', 'DX9CDX', 'ZF9EV8', 'BF9HK4', 'CX9CDX', 'JT9037', 'B29HK3', 'BW9239', 'BT9239', 'DX9CD5', 'BT9F37', 'BF9C30', 'ZF9EV5', 'BF9EV7', 'BH9FJ9', 'HN9CP7', 'BU9FJX', 'JU9FJ7', 'DF9EV5', 'KW9F35', 'CX9CB9', 'B29HK8', 'BT9232', 'DX9CD3', 'HN9CP6', 'B19HKO', 'B29HKX', 'BW9334', 'JU9FJ0', 'BT9F34', 'WF9EV1', 'BF9C33', 'KX9CBX', 'AA9AJ6', 'BF9HK7', 'ZF9EV3', 'ZF9EV9', 'BW9F38', 'B29HK5', 'CX9FJ8', 'ZF9EVX', 'BW9333', 'BX9FJ5', 'AA9AJ0', 'BF9C3X', 'BF9C39', 'JX9CD4', '889HE9', 'ZF9EV0', 'CX9CBX', 'BF9HKX', 'BX9FJ1', 'BF9HK6', 'CX9CD9', 'BU9FJ8', 'K19F33', 'BT9F30', 'ZF9EV7', 'BF9C36', 'DX9CD1', 'B19HK4', 'JT9237', 'DB9CD7', 'BN95J3', 'BF9HK2', 'KT9F32', 'B29HK9', 'HN9CP8', 'BX9FJ2', 'JT9232', 'CX9CD6', 'NM92NX', 'B19HK7', 'BT9234', 'B19HK9', 'CX9CD5', 'BF9EV8', 'JU9FJ3', 'CX9CB4', 'JU9FJ2', 'BW9F37', 'WF9EV8', 'KT9F3X', 'KT9232', 'BW9331', 'HN9CP3', 'ZF9EVO', 'BN95J2', 'BW9F39', 'FA9035', 'BU9FJ0', 'K29F37', 'AA9AJ3', '8W9237', 'BX9FJ3', 'BF9EV6', 'CX9FJ6', 'BW9337', 'WF9EV5', 'BN95J1', 'DX9CD6', 'BW9338', 'BW9F34', 'BW9335', 'BW9332', 'DF9EV1', 'BF9FKB', 'HN9CP5', 'BT9238', 'KT9D38', 'KT923X', 'KT9F34', 'BF9EV1', 'BU9FJ4', 'KT9F39', 'BF9EVI', 'DF9EV4', 'BF9FKO', 'BF9C37', 'RF9EV4', 'BW9336', 'DF9EV9', 'DB9CDO', 'ZF9EV2', 'DB9CD0', 'BN95J8', 'BW9F32', 'JT9030', 'KT9D34', 'CX9CD3', 'BF9HKO', 'BX9FJ4', 'WF9EV3', 'BN95J0', 'KX9CB7', 'DB9CD8', 'DF9EV7', 'JX9CD7', 'BT9233', 'BF9EVX', 'KW9F34', 'K19F36', 'AA9AJO', 'DB9CD9', 'CX9CD1', 'KT9D36', 'KW9F36', 'SN92N6', 'ZF9EV1', 'BX9FJO', 'RF9EV7', 'BF9EV4', 'BM99J3', 'CX9CD2', 'EF9FK8', 'CX9FJ7', 'B19HK8', 'JX9CB7', 'DW9235', 'CX9FJ1', 'BT9237', '8F9FK4', 'DB9CD5', 'JT903X', 'DX9CD8', 'WF9EVX', 'BM99J6', 'BU9FJO', 'JX9CD5', 'JT9239', 'AN95J8', 'KX9CB4', 'KT9D32', 'HN9CPX', 'CX9FJ0', 'BF9C38', 'KT9237', 'BT9033', 'BB9HEO', 'KX9CB8', '509542', 'CX9CB3', '8F9FK7', 'KT9234', 'BF9HKS', 'HB9CP5', '8T9F32', 'B19F33', 'NM92N8', 'BF9HK3', 'KX9CB0', 'KX9CB6', 'BL9HEC', 'DB9CD2', 'B19HK3', 'B19HKX', 'K29F3X', 'JT9233', 'CX9CD0', 'B19HK1', 'KX9CB5', 'KT9D31', 'EW9236', '8T9237', 'CX9FJ5', 'HN9CP0', 'DX9CD9', 'B19HK2', 'BM99J2', 'AA9AJ7', 'VB9E72', '8W9234', 'KX9CB1', 'K29F38', 'K29F31', 'B19F30', '8T9F31', 'BE9B30', 'SN92N8', 'AA9AJ2', 'CX9FJ2', 'JX9CDX', 'VB9E79', 'BW9F3X', 'B29HKO', 'DB9CDX', 'BF9HKB', 'BL9HEO', 'KW9032', 'SM92NO', '2F9EV5', '8T9F3X', 'KX9CB3', 'BF9HK1', 'CX9FJ9', '449253', '8W923X', 'BW9F36', 'BN95J6', 'DB9CD4', '8N95J3', '2F9EV4', 'BN95J4', 'KT9D39', 'KT9D3X', 'KT9238', 'BT9F3I', 'HB9CP1', 'PT9F39', 'AA9AJ4', '8T9F33', 'JT9238', 'BN95JX', 'K29F30', 'B19HK0', 'DX9CD7', 'JU9FJO', 'RF9EV0', 'KT9239', 'JX9CD3', 'DF9EVO', 'KW903X', 'B19HK6', 'WF9EVO', 'BM99J4', 'CX9CD7', 'CX9FJ4', '8F9FKX', 'B19HK5', 'KT9D35', 'DB9CB0', 'AA9AJ9', 'K29F35', '8W9231', '829F36', 'NM92N6', 'BW9F30', '819HK1', '8X9FJ1', 'BB9HES', 'AN95J9', 'B19F34', '8W9331', '8F9HK9', 'KX9CB2', 'K29F34', '8F9FK9', 'VB9E67', 'BW9F31', 'HN9CP4', 'CL9683', 'BW9F33', 'BB9JE6', 'BM99J8', '8W9239', 'KW9F3G', 'JX9CD6', 'BN95J5', 'KT9031', 'KT9032', '8N95J2', '8W9238', '829F3X', 'K29F32', '8B9HE9', '8L9HE9', 'JX9CD9', 'CW9CD6', 'DB9CB2', 'KB9CP0', 'RF9EVO', '8L9HE7', '8T9233', 'ZF9EVS', '889HEX', 'VB9E60', '8T9F35', 'JX9CD8', '8W9233', '829F38', '829F30', 'KT9D30', 'BB9HEI', 'ST9F36', '919017', 'KT9D33', 'DX9CB3', '2F9EV9', 'DB9CB6', 'DB9CBX', 'HN9CPI', '8W9232', 'BT9030', 'B19F38', 'DB9CB5', 'DB9CB9', 'DB9CD1', 'E29F37', 'VP9F32', 'VN94T5', '8L9HE8', 'HB9CP2', 'KW9031', 'BT9037', 'AA9AJ1', 'NM92N4', 'JU9FJB', 'JU9FJS', 'KT9D37', 'KT9030', 'BM99J5', '2F9EV1', 'N19EC0', '809870', 'BW9F43', 'ET9F33', 'KN9CP5', '919002', 'ET9231', 'YF9EV1', '659338', '8T9F36', '919032', 'YF9EVX', 'CX9FJ3', 'RL9HE9', 'BW9F35', 'BM99J7', 'B89HE2', 'JT9234', 'JX9BBX', 'ED9HP2', 'B19F37', 'B19F35', '809434', 'BT9036', 'MF9290', '8F9FK0', 'KT9233', 'JT9033', 'BM99J1', '8F9HK4', 'JX9CB8', 'RF9EV6', 'AA9AJ5', '449252', '8F9FK8', 'JX9CB2', '919021', 'BM99J0', 'JT9235', 'SM92N0', 'BF9FRX', '8T9F37', '8L9HE2', 'JX9CD0', 'JX9CB1', '829F32', '8F9HK2', '8F9HKX', '8F9FK6', '8X9FJ0', 'CW9CD5', 'RN93P8', '8F9FK2', '919014', 'EF9FK1', 'ZF9EVG', 'JX9CB9', 'SN92N2', '809867', 'AA9AJX', 'JX9CB6', '809072', 'CW9CB8', '8F9FK5', 'AE94K3', '8L9HEX', 'K29F39', '829HK4', 'BB9HET', '659343', 'AP90A2', 'BE9FK9', 'JT9230', 'B19F39', '6W9230', 'KN9CP8', 'CX9CBO', 'XU9HM0', '8F9C30', 'KT9K38', 'MF9291', 'JU9EJ4', '919035', 'KW9D3S', 'B19F32', 'HB9CP8', '509750', 'CX9C88', '919085', 'BF9EVO', 'B19F31', '819F32', 'JX9CBX', '8F9FK1', '519081', 'BT9K3X', 'JX9CD2', 'ZE9EV1', 'BZ9F3X', 'KW9033', 'VB9E61', 'JU9FJI', 'BN95J9', 'BT9034', 'JX9CB4', 'BE9FK7', 'BF9JE8', 'SD911X', 'BX9F13', 'AA9AJ8', 'KX9CB9', 'BF9FKZ', 'BF9FKG', 'NM92N5', 'JT9236', 'BT9038', '829F31', 'JT9036', '8F9FK3', '509751', '2F9EV7', '519401', '8T9F34', 'JT9032', '8T9F39', 'EF9FK7', '8W9F3X', '889HE2', 'EF9FK6', 'VB9E69', '889HE6', 'BT9F3S', '8W9230', '8B9HEX', 'RT9F3X', 'DF9EVI', 'BM99J9', 'EE9HE6', 'BE9FK0', 'JU9FI0', 'JT9034', 'JU9F10', 'DX9CDB', '0B9CB0', 'BL9HF3', '919012', 'BT9K35', 'B29HKE', '8T9F38', '8W9236', '8F9C35', 'CU9237', '9T9F34', 'P99006', '8L9HE3', '829F35', '8X9FJ8', 'JT9231', 'BX9FJS', '2F9EV6', 'B29M31', '8L9HE5', '8W9235', 'ET9F32', '809514', 'EW923X', 'VB9E73', 'CW9CB2', 'AE94A8', 'BE9B33', 'TX9A21', 'AN95J2', 'B29HKB', 'ZF9EVI', 'KX9CBO', '8L9HE6', 'AN95JX', 'AR9AJ2', 'DX9CDS', 'CX9CBI', '009432', 'EX91G3', 'WF9EVB', 'BF9FKI', 'DB9CB7', 'BL9HEE', '8F9EV4', 'PW9236', 'B19F36', 'BE9HEX', '009687', 'B89HE0', 'AN95J6', '8T9F30', '2F9EV0', '519729', 'DX9CB2', 'E29F3E', 'CW9CB4', 'JU9EJ2', 'BU9FJS', '829F34', 'SN92N0', '8T9238', 'KN9CPX', '919023', '8F9EV0', 'BT903X', 'NM92N2', 'BU9FJJ', 'MF9297', '829HKX', '809506', 'JT9K39', 'ET9F36', 'D89CD7', 'D89CD3', '889HE5', '659101', 'DB9CB1', 'AA9AJZ', 'B19F3X']
  Model_Year: ['F', 'B', 'T', 'H', 'D', '8', 'P', 'K', 'L', 'E', 'J', 'N', '7', '6', 'R', 'M', 'G', 'C', 'A', '9', 'S', '1', 'Y', '4', 'X', '2', '3', '5']
  Plant_Code: ['5', 'L', '0', 'X', '3', '2', '1', 'D', 'K', 'J', '4', '6', 'B', 'Z', 'E', 'C', 'R', '8', '7', '9', 'S', 'G']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,4.0,RKL,BB9HE7,F,5,115863
1,TOYOTA,YARIS,4.0,HATCHBACK,B,MID,GCC,5.0,JTD,BW9230,B,L,006031
2,TOYOTA,YARIS,4.0,SEDAN,B,E,GCC,4.0,MR2,BF9C35,T,0,094830
3,TOYOTA,CAMRY,4.0,SEDAN,B,GL,GCC,4.0,6T1,BF9FK1,H,X,678621
4,TOYOTA,CAMRY,4.0,SEDAN,B,S,GCC,4.0,6T1,BF9FK9,D,X,449176
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43596,TOYOTA,YARIS,4.0,HATCHBACK,K,SE,GCC,NaN,MR2,K19F39,H,1,021875
43597,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,S,GCC,NaN,6T1,BF9FK5,D,X,425747
43598,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,NaN,RKL,BL9HE4,F,5,235018
43599,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,S,GCC,NaN,6T1,BF9FK4,D,X,474261
43600,TOYOTA,YARIS,4.0,SEDAN,B,E,GCC,NaN,MHF,B29F34,M,2,123579

====================================================================================================
pos6: 0
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'LAND CRUISER', 'SUPRA', 'COROLLA', 'OTHERS', 'LAND CRUISE', 'PRADO', 'HILUX', 'COROLLA 1.6', 'RAV 4', 'LAND CRUISER VXR', 'TUNDRA', 'YARIS', 'ALTIS', 'COROLLA 1.3', 'FORTUNER', 'استیشن', 'INNOVA', 'كورولا 1.8', 'CAMRY', '2016', 'WISH', 'FJ CRUISER', 'VIOS', 'TOYOTA COROLLA', 'COROLLA SEDAN', 'RAV4', 'LAND CRUISER GX', 'LAND CRUISER GXR', 'TOYOTA LAND CRUISER', '2008', 'LAND CRUISER 70', 'PREVIA', 'AVANZA', 'AVALON', 'DAINA']
  bodyType: ['MINI BUS HIGH ROOF', 'SUV', 'PANEL VAN', 'VAN', 'MINI BUS', 'COUPE', 'SEDAN', 'PANEL VAN HIGH ROOF', 'MPV', 'HALF PANEL VAN', 'STATION', 'MINIVAN', 'PICK UP DOUBLE CAB', 'MINI BUS SEMI HIGH ROOF', 'SALOON', 'HATCHBACK', 'PICKUP TRUCK', 'BUS', 'CARGO VAN', 'PICKUP', 'PICK UP SINGLE CAB', 'LIGHT VEHICLE', 'PICK UP']
  pos4: ['H', 'J', 'D', 'B', '1', 'A', '8', 'F', 'R', 'Z', 'N', 'M', 'E', 'I', 'S', 'C', '2', '0', 'T', '5', '3', 'G', '4', '6', 'U', '9']
  trim: ['GLX', 'DX', 'VX', 'GXR', 'GL', 'DLX', 'GX', 'VXR', 'G', 'GR', 'STD', 'XLI RB', 'XLI', 'GLS', 'STD (NON GCC)', 'SAFARI', 'GXR TOP 60TH ANNIV. XTREME', 'GLI HEV', 'GXR TOP', 'VXR BASE', 'GLI', 'GXR GT', 'VXR TOP', 'EXR', 'XLI MID', 'DX H/R W/B', 'DL', 'GR TAN EDITION', 'PREMIUM', 'SE+', 'XLI EXECUTIVE', 'GXR FMST', 'GR BLUE EDITION', '1', 'GXR TOP DMST', 'VXR TOP LTH', 'MID', 'STANDARD', 'GRD', 'SPORT', 'XLI TOP', 'GXR+', 'GXR3', 'XTREME', 'GL TOP', 'DLS - STD ROOF', 'S', 'GXR MID 60TH ANNIV. XTREME', 'XLI EXECUTIVE MR', 'GXR TOP FMST', 'STANDER', 'GXR SOD D/AC AW', 'SE', 'LIMITED', 'AXL ', 'GT SPORT', 'C', 'VXR TOP XTREME', 'GXR MID', 'VXR MID', 'COMFORT', 'TOP', 'GRANDE', 'MPV', 'STD  (NON GCC)', 'XLI EXECUTIVE HEV', '60TH', 'LE', 'SS', 'AA', 'SALOON', 'CAR TRIM', 'ZX', 'SEDAN', 'ST', 'EX', 'FLEET', 'H', 'BASE', 'HT SWB', 'VX TOP LTH', 'TRTIM', 'GXR TOP 60TH ANNIV. ']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTF', 'JTM', 'JTG', 'JTE', 'JT3', 'WZ1', 'RKL', 'ANE', '1NX', 'JT2', 'ZSG', 'JT6', 'INX', '2T1', 'JZA', 'LHA', 'JHE', 'ITG', 'MR0', 'MAF', '2FU', 'NNN', 'JTH', 'KNC', 'JTD', 'JTN', 'FZJ', 'UAE', '000', 'JTC', 'JT8', 'ZE1', 'JIF', 'UTG', 'WZI', 'NCP', 'JIM', 'JIG', 'LTA', 'JD4', 'RN1', 'JN1', 'NV1', 'MDH', 'YN8', 'MV1', 'RKE', '1TF', '1N6', 'CTF', 'SXA', 'JTR', 'JT4', 'MET', 'YV2', 'JN8', 'EP9', 'FJ7', 'ITE', 'LFB', '174', 'UP1', 'CE1', 'WDB', 'EL5', '1TM', 'K20', 'JHG']
  VDS: ['HX02PO', 'HX02P7', 'HT09J7', 'HU09J4', 'JX02P1', 'HX02P1', 'HX09J2', 'HT05J3', 'HT05J9', 'HX01JX', 'HX09J5', 'HX01J2', 'HX02P5', 'HU09JX', 'HT05J8', 'HY05J7', 'HJ09J7', 'HX05J9', 'HT05J1', 'HY05J2', 'HX05J2', 'JX02P4', 'DB0E04', 'HX02P4', 'HJ0936', 'HX09J1', 'HY05J6', 'HT09J5', 'HJ09JX', 'BB0BE5', 'HX09J7', 'HU09J9', 'HT09J9', 'HX09J6', 'HX01J8', 'HJ09J1', 'HX01J9', 'HJ09J6', 'JX02P9', 'HT05J0', 'HT09J6', 'HX05JX', 'HY05J1', 'JX02P8', 'HT05J4', 'HT05JX', 'HJ09J4', 'HU09J1', 'HU09J6', 'HX02PX', 'BB0BE3', 'B30BE6', 'HY05J3', 'HX09J4', 'HU09J7', 'HX01J7', 'HX02P6', 'HT09J4', 'HJ09J9', 'HX05J6', 'HX02P8', 'JX02P6', 'HY05J5', 'BB0BE2', 'HX05J4', 'HU09J0', 'BB0BE6', 'HY05JX', 'HJ01J1', 'HU01J4', 'JX02P3', 'BB0BE0', 'HY05J4', 'HY02J8', 'HX02P2', 'B30BE7', 'HT05J7', 'HY0SJX', 'HY05J8', 'HJ09J5', 'HX01J0', 'HT05J5', 'HX05J3', 'HT09JX', 'HT09J2', 'HX02P0', 'HT09J8', 'HJ09J3', 'JX02P7', 'HX09J9', 'HY02JX', 'HX05J7', '120010', 'HX01J5', 'HU09J2', 'HT05J2', 'DU09J6', 'HY05J0', 'JX02P5', 'HX09J3', 'DU09J3', 'BB0BE7', 'HJ09J2', 'JX02P2', 'HT05J6', 'HT09J3', 'HX01J3', 'HU01JX', 'HX02P3', 'JX02P0', 'BA02E3', 'HU01J5', 'DU09J9', 'DP02T1', 'JX02PX', 'HJ09J8', 'BA0BE8', 'BA0BEX', 'BB0CE3', 'HU09J5', 'HU01J1', 'HU09J8', 'HX02P9', 'B30BE0', 'HX05J0', 'HX09J8', 'HY05J9', 'HX05J1', 'HU01J6', 'DB0E05', '100319', 'HU01J8', 'HU01J0', 'DB0A07', 'HJ09J0', 'HJ01J9', 'BB0BE8', 'HT09J0', 'BA0BEO', 'HX01J4', 'B30BEX', 'BB0BEX', 'JS02P8', 'HU01J2', 'HX09JX', 'BB0CE2', 'HX01J1', 'BA0BE5', 'HJ0932', 'DB0E03', 'HU01J7', 'BA0BE3', 'HT09J1', 'HU01J3', 'HU09J3', 'HU0935', 'BB0BE1', 'HX09J0', 'HX05J8', 'HX01JO', 'BA02EX', 'DU09J5', 'HX05J5', 'DB0E08', 'DB0E01', 'B30EE9', 'BB0CE6', 'HJ01J5', 'HX01J6', 'BA02E8', 'HJ0939', 'HY05JO', 'BA02E6', 'HV01J3', 'BB0BEO', 'BA0BE4', 'H009J1', 'BA0BE1', 'BA02E7', 'BB0BE4', 'AE09V9', 'HY03JX', 'BB0CE7', 'HJ01J3', 'HT0937', 'HY0518', 'BB0CEX', 'B30BE8', 'BA0BE9', 'DU09JX', 'BB0BEG', 'BA0BE0', 'DB0E07', 'BB0BE9', 'BA0BE2', 'BB0CE9', 'DU09J0', 'HX02PS', 'BB02E1', 'BB0CE1', 'AE00B6', 'B30BE4', 'BA05E8', 'BB02E4', 'HU0932', 'BB0CE8', 'BA0BE6', 'BB0CE0', 'BB02E3', 'BB02E9', 'BA02E2', 'HJ01J8', 'B30BE9', 'HJ01J7', 'AE00B7', 'HU01J9', 'AE09B3', '8A02E6', '800014', 'DB0E09', '120076', 'JV03J9', 'HU0938', 'HY02J9', 'DU09J2', 'DB0A04', '1201DX', 'HT0537', 'BA01E9', 'BB02E8', 'BB02E7', 'HY02J0', 'AE04B7', 'JX02PO', 'DB0A03', 'DB0E06', 'FX00G6', 'HJ01J6', 'BB02E2', 'BA02E0', 'BA02E4', 'BA02E9', 'BB0CE5', 'HJ01JX', 'BB02EX', 'HV01J2', 'HY02J7', 'BA0BE7', 'R20612', 'JS02P1', 'HU0936', 'HJ01J2', 'BA03E8', 'HY0SJ5', 'BA02E1', 'AE09V6', 'AE09B5', 'BB0CE4', 'AE09B7', 'B30BE1', 'ZY0CCL', 'BB02E5', 'AE04B3', 'AE04B2', 'N00001', 'HJ01J0', 'HV09J8', 'AE04B8', 'HJ01J4', 'BB0BET', 'DU09J8', 'MT09J8', 'JV03J7', 'EB0BE0', 'AE09B0', 'B30EE0', 'AE09B4', 'IX02P5', 'BA05E1', 'DB0E0X', 'SE0142', 'JS02P6', 'HV09J2', 'EB02E2', 'AE09B2', 'HV09J0', 'BW0236', 'AE00E5', 'AE04B9', 'AE04B4', 'BA02E5', '800025', 'HV01J4', 'HX0937', 'HY02J2', 'DB0E02', 'HT0530', 'DB0A06', 'HV09JX', 'JS02P4', 'AE00B1', 'JX02PB', 'HS02P6', 'AE04B6', 'B30BE2', 'CU09JX', 'B30EE4', 'DU09J1', 'BB02E0', 'BB0BES', 'AE04B0', 'HU01JO', '800083', 'HT0934', 'DU09J4', '880CE2', 'AE00EX', 'HY02J6', 'AE04B1', '120066', 'HY02J5', 'DB0E00', 'HJ0915', 'HT05JO', 'HU0939', '2S0125', 'H109J9', 'HX0936', 'HT0535', 'HX0SJS', 'HY0515', 'B30BE3', 'HY02J1', 'HU0930', '000NNN', 'AE09W0', 'HX09JO', 'EB02E1', 'TX02P8', 'BB02E6', 'HV01J9', 'HT0533', 'HT0SJ3', 'HV01J5', 'HV01J0', 'AE09BX', 'B30BE5', 'CB09J3', 'AE09V4', 'BA03E6', 'HJ0934', 'AE00E6', 'AE09EX', 'HV09J3', '510670', 'AE09B8', 'AE09E2', 'HX05JO', 'AE04B5', 'JX02PV', 'DB0A09', 'BA03E0', 'DB0G02', '800005', 'HJ0931', 'HX0931', '500127', 'HJ0938', 'DB0A0X', 'BA01E6', '3S0113', 'BA01E2', 'BA02EO', 'SE0342', 'HY02J4', 'HV01J1', 'CU09J7', 'HX0IJ3', 'AE09B6', 'HY02J3', 'JV03J0', 'GU09J9', 'AE09V3', 'DB0G03', '880CEX', 'SD0110', 'DB0C03', 'FX02P3', 'HT06J3', 'CB09J1', 'BB03E7', 'HT0539', '120055', 'H00936', 'HV01J6', 'JV03JX', 'AE09V0', 'AE09V7', 'JY09J2', 'AE04E8', 'HV01J7', 'B30EE3', '800004', 'DU09J7', 'AE09B9', 'DB0E0S', 'AE00B5', '420141', 'HU09JO', 'HV01JX', 'GU09JX', 'HJ0937', '1201D7', '120077', 'HS02P8', 'CB09J2', 'AE04E1', 'AE09W2', 'EB02E3', 'BB03E8', 'HX0139', 'AE09V2', '1202F7', 'HV09J1', 'TV092X', 'HT0514', 'AE00B3', '350007', 'HZ04S2', 'HT0512', '800971', 'AE09W8', 'DB0A05', 'HU0937', 'HX02J2', '120049', 'BU01F7', 'B30EE7', '810187', 'JU03J2', '8L0HE3', 'BD0FA4', 'HX0934', 'B30EE8', 'HX02PI', '800030', 'JU03J3', 'BB0BEB', 'NT08J2', 'JV03J5', 'HJ0935', '600238', 'AE00E3', 'BA01E1', 'DB0A08', 'AE09E6', 'AE04E9', 'BA0BES', 'HT0518', 'AE09E9', '800631', 'JS02P2', 'HY0SJ8', '420156', 'AE09B1', 'BB0BBE', 'HT09JO', '800157', 'JV03J8', 'HJ0912', 'HY0532', 'HX0131', 'HU08J0', 'HJ0933', '800426', 'BD0CT6', 'DB0A00', '110053', 'AE09W3', 'DU09T3', 'HU0933', 'H009J3', 'HJ0919', 'BA05E0', 'DB0C09', 'AE04BX', 'AE07B9', 'B30EE2', 'BA01E3', 'BA03E5', '500188', 'DB0C00', 'BA03E9', 'AE09E4', 'HX0935', '150702', 'BA05E3', 'BL0HE9', 'BA0BEB', 'HT0SJ0', 'B308EX', 'H009JX', 'JT05J0', 'B30EE1', 'HT09JL', 'B30EE6', 'RN01P3', '500185', 'AE00E1', 'AE09W5', 'HX0919', 'BA01E7', '0000EA', 'AS02A5', 'DB0AOX', '150700', 'BT05Y4', 'AE09VX', '100305', 'HV09J7', 'H009J6', 'HU0931', 'BL00E0', 'HU09JI', 'HT05JI', 'CB09JX', 'BA05E4', 'JS02PX', 'N00011', 'BA01E8', 'BA01EX', 'AR05Y8', 'HJ05J6', 'JU03J7', 'HJ0SJ9', '800957', 'JK02P2', 'HT0935', 'AE00E7', '500617', 'HX02PB', 'HT0538', 'HT0531', 'H30934', 'HY0535', 'B30EE5', 'HX02PU', 'HU0912', 'UY0FJX', 'HJ08J1', 'HU0917', 'HU0914', '500176', 'JU03J5', 'HT05JB', 'TV0823', 'HY0534', '600198', '1F0091', '000NCP', '800788', 'HS02PX', '1201D2', 'H309JX', '210906', 'HY0531', 'HX02J8', '8A02EX', '120009', 'BA03E1', 'HT0938', 'AE09E7', 'BB08E3', 'AE04E6', 'HX07P1', 'NX0375', 'HG09G2', 'AS02D0', '010356', 'DB0A01', '120039', 'B30EEX', '2S0107', 'CU09J8', 'HY0533', 'HV09J9', 'BA03E4', '500903', 'HT0534', 'B308E3', 'HV01J8', '950213', 'JU03J6', 'CU09J5', 'HT0536', 'AS02D8', '2S0117', 'HY05I1', 'AE04BZ', 'DV09J4', 'HJ08J8', 'HV09J6', '120053', 'CX0CD4', '420101', '000983', 'HX0939', 'HS02P3', 'AS02A4', 'JS02P9', 'HY0S0S', '8808E2', 'HJ08J9', 'HT0SJ2', '8A08E1', '3B0075', '0000JA', '800253', 'AE09WX', 'JU09J0', 'JU03J0', '420184', 'AS02A2', 'HU0919', 'AE09V8', '120030', 'AF047X', 'CB09J7', 'GU09J1']
  Model_Year: ['F', 'A', 'C', 'N', 'E', '6', '9', 'G', 'L', 'B', 'H', '4', 'Y', 'S', 'J', '3', '2', '7', 'D', '8', 'M', '5', 'R', 'K', 'X', '1', 'V', 'P', 'T', 'W']
  Plant_Code: ['0', '5', '4', '2', 'W', '8', '7', '1', '9', 'Z', '3', 'C', 'A', 'K', 'G', 'N', 'O', 'X', 'P', 'S', 'V', 'J', 'B', 'D', '6']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,H,GLX,GCC,4.0,JTF,HX02PO,F,0,099797
1,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,H,DX,GCC,4.0,JTF,HX02P7,F,0,094323
2,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTM,HT09J7,A,5,049335
3,TOYOTA,LAND CRUISER,6.0,SUV,H,GXR,GCC,5.0,JTM,HU09J4,A,5,038810
4,TOYOTA,HIACE,4.0,PANEL VAN,J,GL,GCC,5.0,JTG,JX02P1,C,0,041237
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34410,TOYOTA,COROLLA,4.0,SEDAN,B,1,GCC,NaN,RKL,BB0BE2,L,0,021418
34411,TOYOTA,LAND CRUISER,8.0,SUV,H,VXR,GCC,NaN,JTM,HY05J0,M,4,095767
34412,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTM,HT09J6,9,5,038189
34413,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTM,HT09J0,A,5,079700
34414,TOYOTA,LAND CRUISER,8.0,SUV,H,GXR,GCC,NaN,JTM,HX01J3,M,4,222343

====================================================================================================
pos6: D
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'COROLLA', 'HIACE', 'CAMRY', 'BZ3X', 'RAV4', 'TACOMA', 'LAND CRUISER', 'YARIS', 'WIGO']
  bodyType: ['PICK UP DOUBLE CAB', 'SEDAN', 'MINI BUS', 'SUV', 'PANEL VAN', 'COUPE', 'HATCHBACK']
  pos4: ['H', 'A', 'P', 'B', 'D', '3', 'K', 'W', '9', 'N', 'U', '5', 'R', 'X', 'F']
  trim: ['DL', 'XLI', 'DLS', 'DX', 'DLX', 'GRANDE', 'AIR', 'EXR', 'STD', 'GLX', 'SR5 (NON GCC)', 'VX', 'GL', 'E', 'GXR', 'S', 'EX', 'ADVENTURE', 'MID', 'XLI TOP']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTF', 'YV2', '1GC', 'LVC', 'LVG', 'MD6', 'KPD', 'LZZ', 'WAU', 'JTE', 'HJN', 'JNC', 'RKL', 'JTM', '454', 'LA6', 'MHK', 'LVM', 'WV2', 'LM8']
  VDS: ['HXDGP7', 'A4DAA6', 'PTDEK3', 'B1DWA7', 'A4DAC2', 'A4DMA4', 'D2DF62', 'D3DF60', 'D3DF64', '37DE71', 'KFDNN1', 'WADG49', '9FD8TX', 'HXD2P9', 'NADMG2', 'UAD1H1', 'BADBA0', 'UZD1H4', 'HUD9J8', '5DDDDD', 'R1DSBX', 'A4DF5F', 'BBDEE4', 'XAD2K0', 'A4DAA2', 'HUD3J2', 'F7D196', 'HUD9J6', 'A4DAA9', 'A4DAA3', 'A4DAAX', 'A4DBAX']
  Model_Year: ['F', 'X', 'P', 'C', '1', 'S', 'E', 'A', '7', 'R', 'D', 'H', 'T', 'Y']
  Plant_Code: ['0', 'B', '1', 'G', '2', 'P', 'T', 'A', '4', 'D', 'J', 'H', 'X']
  Serial_Number: ['094373', '233361', '150115', '011727', '234539', '277006', '030817', '002592', '002501', 'B00102', '070249', '501381', '067905', '023366', '104057', '510200', '152484', '510831', '108676', 'DDDDDD', '200023', '006136', '023716', '001017', '202180', '057803', '000511', '054161', '265822', '222317', '267322', '283962']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DL,GCC,4.0,JTF,HXDGP7,F,0,094373
1,TOYOTA,COROLLA,4.0,SEDAN,A,XLI,NON-GCC,NaN,YV2,A4DAA6,X,B,233361
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,P,DLS,GCC,4.0,1GC,PTDEK3,P,1,150115
3,TOYOTA,HIACE,4.0,MINI BUS,B,DX,GCC,4.0,LVC,B1DWA7,C,B,011727
4,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,A,DLX,GCC,4.0,YV2,A4DAC2,X,B,234539
5,TOYOTA,CAMRY,6.0,SEDAN,A,GRANDE,NON-GCC,NaN,YV2,A4DMA4,1,B,277006
6,TOYOTA,BZ3X,0.0,SUV,D,AIR,GCC,5.0,LVG,D2DF62,S,G,030817
7,TOYOTA,RAV4,4.0,SUV,D,EXR,GCC,5.0,LVG,D3DF60,S,G,002592
8,TOYOTA,BZ3X,0.0,SUV,D,STD,GCC,NaN,LVG,D3DF64,S,G,002501
9,TOYOTA,CAMRY,4.0,SEDAN,3,GLX,GCC,4.0,MD6,37DE71,S,2,B00102
10,TOYOTA,HIACE,4.0,PANEL VAN,K,DX,GCC,5.0,KPD,KFDNN1,E,P,070249
11,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,W,SR5 (NON GCC),GCC,4.0,LZZ,WADG49,S,T,501381
12,TOYOTA,COROLLA,4.0,COUPE,9,XLI,GCC,2.0,WAU,9FD8TX,A,A,067905
13,TOYOTA,HIACE,4.0,PANEL VAN,H,STD,GCC,4.0,JTE,HXD2P9,7,0,023366
14,TOYOTA,LAND CRUISER,8.0,SUV,N,VX,GCC,NaN,HJN,NADMG2,R,A,104057
15,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,U,GL,GCC,4.0,JNC,UAD1H1,7,A,510200
16,TOYOTA,YARIS,4.0,SEDAN,B,E,GCC,4.0,RKL,BADBA0,R,4,152484
17,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,U,DLX,GCC,4.0,JNC,UZD1H4,A,A,510831
18,TOYOTA,LAND CRUISER,6.0,SUV,H,GXR,GCC,NaN,JTM,HUD9J8,F,4,108676
19,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,GCC,NaN,454,5DDDDD,D,D,DDDDDD
20,TOYOTA,LAND CRUISER,6.0,SUV,R,EXR,GCC,NaN,LA6,R1DSBX,D,B,200023
21,TOYOTA,WIGO,4.0,HATCHBACK,A,S,GCC,NaN,MHK,A4DF5F,H,J,006136
22,TOYOTA,RAV4,4.0,SUV,B,EX,GCC,NaN,LVM,BBDEE4,T,H,023716
23,TOYOTA,HIACE,4.0,PANEL VAN,X,GL,GCC,5.0,WV2,XAD2K0,C,X,001017
24,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,A,DLX,GCC,NaN,YV2,A4DAA2,Y,1,202180
25,TOYOTA,LAND CRUISER,6.0,SUV,H,EXR,GCC,NaN,JTM,HUD3J2,C,4,057803
26,TOYOTA,RAV4,4.0,SUV,F,ADVENTURE,GCC,NaN,LM8,F7D196,P,A,000511
27,TOYOTA,LAND CRUISER,8.0,SUV,H,GXR,GCC,5.0,JTM,HUD9J6,C,4,054161
28,TOYOTA,YARIS,4.0,HATCHBACK,A,MID,GCC,NaN,YV2,A4DAA9,Y,B,265822
29,TOYOTA,YARIS,4.0,HATCHBACK,A,MID,NON-GCC,NaN,YV2,A4DAA3,X,B,222317
30,TOYOTA,CAMRY,4.0,SEDAN,A,XLI,NON-GCC,NaN,YV2,A4DAAX,Y,B,267322
31,TOYOTA,COROLLA,4.0,SEDAN,A,XLI TOP,NON-GCC,NaN,YV2,A4DBAX,1,B,283962

====================================================================================================
pos6: 2
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'COROLLA', 'RAV4', 'HIACE', 'SIENNA', 'PRADO', 'HILUX', 'AVALON', 'PRIUS', 'TACOMA', 'LAND CRUISER PRADO', 'GR86', 'كامري', 'SUPRA', 'COROLLA 1.3', 'ALPHARD', 'COASTER', 'HIGHLANDER', 'TUNDRA', 'LAND CRUISER PICK UP', 'FORTUNER', 'LAND CRUISER', 'RUMION', 'AURION', 'FJ CRUISER', 'KS01', 'YARIS', 'MR 2', 'MT 03', 'TAKOMA', 'COROLLA SEDAN', 'COROLLA 1.6', 'SEQUOIA', 'TOYOTA HIACE', 'TOYOTA COROLLA', 'COROLLA 1.8', 'STANZA', 'تاكوما', 'DYNA', 'هايلوكس', 'TOYOTA', 'SOLARA', 'CAMRY SOLARA', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'PANEL VAN', 'MPV', 'ESTATE', 'PICK UP DOUBLE CAB', 'PICK UP', 'PICK UP SINGLE CAB', 'MINI BUS HIGH ROOF', 'VAN', 'SALOON', 'MINI BUS', 'PANEL VAN HIGH ROOF', 'HATCHBACK', 'HALF PANEL VAN', 'BUS', 'PICKUP', 'COUPE', 'STATION', 'CARGO VAN', 'PICKUP TRUCK', 'MINI BUS SEMI HIGH ROOF', 'MOTORCYCLE', 'TRUCK', 'PICKUP DOUBLE CABIN', 'MINIVAN', 'CONVERTIBLE']
  pos4: ['B', 'H', 'P', 'E', 'Z', 'F', 'D', '6', 'S', 'Y', 'A', 'K', '8', 'G', '2', 'N', 'T', 'W', 'U', 'R', '5', 'C', 'M', '1', 'V', '0', '3', '4', '9']
  trim: ['XLI', 'FABRIC', 'GL', 'XLI MID', 'LE (NON GCC)', 'XLE (NON GCC)', 'VX', 'VX MID', 'DLX', 'BASE', 'PW CL', 'GX', 'GLX', 'GLS', 'STD', 'DL', 'DLX TOP', 'CE (NON GCC)', 'DX', 'GX TOP', 'GLI TOP', 'XLI TOP', 'DX H/R W/B', 'GX MID', 'STD (NON GCC)', 'GLI TOP LTH', 'LE', '1.8', 'STANDARD', 'GL2', 'GLE', 'MID', 'GLI', 'SL', 'LIMITED PREMIUM', 'GT SPORT', 'EXR', 'LIMITED', 'HYBRID (NON GCC)', 'DLS - STD ROOF', 'AXL ', 'XLI - AW', 'TOP', 'GRANDE', 'GXR', 'TX-L', 'XTREME', 'EX', 'GR', 'GRD', 'CE', 'SS', 'ECO', 'S', 'AT', 'SE', 'ADVENTURE', 'TRIM', 'C', 'XLI EXECUTIVE', 'S T2 TOP', 'DLS', 'G', 'AMG', 'SR5 4X4', '1', 'CAR TRIM', 'X', 'MPV', 'E', 'TX-L TOP', '1.5', 'ST', 'VXR', 'FLEET', 'SINGLE CABIN', 'XLE HEV', 'VTI', 'CARRERA GTS', 'EX MID', 'XLI ', 'A', '4', 'LX']
  regionalSpec: ['NON-GCC', 'GCC']
  WMI: ['4T1', 'JTD', 'JTE', 'JTF', '5TD', '6T1', 'MR0', 'JT2', 'MRO', 'WDB', 'JTG', '5TE', 'JTV', '4TI', 'KNC', 'MM7', 'MA1', 'ME4', 'JT6', 'JF1', 'LGW', 'LFM', 'MA3', 'WDD', 'WZ1', 'STD', '57W', 'ZRE', 'JTN', 'AAP', 'JHE', 'MD2', 'YV2', 'ZZE', 'LTV', '2T1', '3N6', 'JN6', 'NV1', 'MNT', 'JN8', 'JTH', '6TI', 'KPB', 'WMA', 'LHA', 'UP1', 'MH3', 'JD2', 'LVG', 'ZE1', 'LVV', 'JN2', 'JTL', 'JHM', '6TD', 'FJ4', '2HN', 'JT0', '1GJ', '5N1', '471', 'STE', '5AL', 'INB', 'KNA', 'JH2', '074', 'JN1', '3TD', 'J1D', 'SAL', 'JHG', 'JT4', '180', '1V2', '425', 'WVW', 'LVZ', 'WP0', 'JHF', '1GC', '5T0']
  VDS: ['BG22K0', 'BR23E6', 'HD20V5', 'PX22P7', 'PX22P6', 'BR23E0', 'BR22E6', 'ER23E0', 'ZK22C2', 'ZA23CX', 'BU25J9', 'BG22K1', 'BW23E0', 'BU25J0', 'FX22G1', 'ZA23C6', 'ZK23C8', 'HH20V4', 'FX22G3', 'FX22G8', 'BL29J2', 'BG22KX', 'DX22G9', 'DX22G3', 'PX22P8', 'BL29J3', 'PX22P0', 'EW23E2', 'BR22E4', 'BU25J5', '652047', 'ER23EX', 'FX22G2', 'FX22G5', 'ZA23C8', 'BW23E3', 'SX22P6', 'BR22E2', 'FX22GX', 'DX22G8', 'BG22K9', 'ZK23CX', 'ZA23C0', 'ER23E2', 'YH20V1', 'DX22G1', 'BG22K4', 'PX22PX', 'BG28K0', 'BG22K3', 'BR22E9', 'PX22P4', 'HH20VX', 'BU25J2', 'BF28B6', 'EG22K1', 'HH20V5', 'BG22K7', 'PX22P1', 'BG22K5', 'BR22E0', 'BL29J5', 'AM29J2', 'HH20V1', 'FX22G7', 'ZK23C4', 'EG22K5', 'PX22P3', 'BR22E5', 'DX22G6', 'ZA22C9', 'FX22G6', 'ZK22C5', 'ZK23C5', 'BR22E7', 'ZA23C3', 'EW23E9', 'BW23E4', 'BW22E3', 'PX22P9', 'PX22P2', 'PX22P5', 'BR23E2', 'BU25J6', 'BR23E9', 'SX22PX', 'EW23E4', 'BR22E8', 'ZA22C6', 'BL29J4', 'BG22K8', 'BW23E8', 'HH20V8', 'BR23E5', 'BG22K2', 'BG28K6', 'BW22EX', 'BW23E6', 'FX22G4', 'FX22G0', 'BR23E8', 'EW23E0', 'SX22P2', 'BL29J1', 'BU25J1', 'ZA23C5', 'BU25J4', 'BR22E3', 'ER23E4', 'BL29J9', 'BU25JX', 'BA22C3', 'BR23E3', 'ZA22C8', 'BU25J8', 'BW23E1', 'BR23EX', 'BR22E1', 'SX22P3', 'FX22G9', 'ZK23C7', 'BK22C8', 'AM29J8', 'ZA22C2', 'ZK22C4', 'AU25J2', 'BW22E4', 'EG22K8', 'YH20V2', 'KB20U3', 'BL29J6', 'BU25J3', 'ZK23C6', 'BR22EX', 'BW23E9', 'BG28K7', '8R23E5', 'ER23E8', 'BG22K6', 'AU25J6', 'ZK22C8', 'BR23E4', 'ZK23C1', 'BF28B9', 'HH20V7', 'SX22P1', 'EW23E7', 'BM29J5', 'BW22E1', 'BA23C4', 'HD20V4', 'ZK23C0', 'DX22G4', 'HH20V9', 'KB20U7', 'ZA23C2', 'ZK22C1', 'EG23K8', 'BR23E7', 'HH20V0', 'EW23E8', 'SX22P8', 'GH20V5', 'AU25J7', 'SX23P1', 'EW23E1', 'ER23E7', 'DX22G0', 'BM29J6', 'FX2260', 'ZK22C0', 'BL29J7', 'ER23E6', 'DX22GX', 'AU25J5', 'ZA23C1', 'GH20V4', 'SX23P5', 'SX23P3', 'ZA23C9', 'HD20V0', 'ER23E9', 'BW23E7', 'ER23E5', 'BF22K8', 'EG22K3', 'SX22P4', 'SX23PX', 'ZA23C7', '2A22C1', 'BF28B0', 'ZA22C1', 'ZA22C3', 'EG22K9', 'BG28K5', 'ZA22C7', 'DX22G2', 'BF22K6', 'EW23E5', 'AU25JX', 'DX22G5', 'EG22K6', 'AL29J3', 'BF28KX', 'KB20U4', 'YH20V7', 'ZA22CX', 'BA22C6', 'ZK23C3', 'NX22N1', 'AU25J1', 'EW23E3', 'SX23P9', 'ZK22C3', 'EG23K3', 'BG23K3', 'ER23E1', 'BW23E2', 'BF22K5', 'BK22C1', 'HD20V3', 'ZK22C6', 'BU25J7', 'BR23E1', 'BK22CX', 'SX23P6', 'BW22E9', 'NX22N3', 'ZA22C0', 'ER23E3', 'BG28K8', 'ZA22C4', 'EG22K0', 'ZK22C7', 'ZK22C9', 'ZA29C5', 'BW23E5', 'BK23C0', 'YH20V8', 'TX22NX', 'EG22K7', 'BW23EX', 'ZK23C9', 'BL29JX', 'AU25J9', 'EW23EX', 'AL29J8', 'GH20V9', 'HH20V6', 'GD20V5', 'SX23P7', 'BW22E7', 'AU25J4', 'KB20U9', 'EG22K2', 'BA22C1', 'BL29J8', 'ZA22C5', 'BU2539', 'AM29J5', 'YH20V6', 'PX22PO', 'BW22E2', '8F22K4', 'BF22K3', 'GH20V8', 'BF28B4', 'DX22G7', '8R23EX', 'ZK23C2', 'YH20VX', 'BM29J1', 'BA22C2', 'BA23C6', 'HH20V2', 'ZA2301', 'SX23P2', 'KB20U5', 'GH20V7', 'SX22P7', '6H20V7', 'ZK22CX', 'ZA29C9', 'BF28B7', 'BF22K1', 'AU25J3', 'BK22C9', 'AM29J4', 'WJ2728', 'AM29J0', 'BG28K4', 'BL29J0', 'ZA23C4', 'BA22C7', 'FR22G0', 'EG22KX', 'ZA29C1', 'BF22K9', 'BW22E0', '2A23CX', '2K23C0', 'EW23E6', 'EG22K4', 'SX22P5', '2K23C3', 'FR22GX', 'BF28B3', 'BW22E8', 'GD20V2', '8L29J0', 'AU25J0', 'HD20V8', 'SX23P0', 'SX22P0', 'UN236X', 'BF28K5', 'FR22G2', 'SX23P8', 'RD2VF2', 'YH20V0', 'BG23K1', 'AL29J2', 'KB20UX', 'BK22C0', 'KC20F7', 'BG28K9', 'HD20V6', 'BF28B5', 'GH20V6', 'YH20V5', 'AM29J3', '5X23P5', 'ZA29C3', 'BA22C9', 'BW22E6', 'GD20V1', 'ZN23B4', 'BK23C1', 'CA2174', 'BR28E1', 'NX22N0', 'BG28K1', 'FR22G4', 'BM29J0', '8L29J3', 'BF22K0', 'AL29J1', 'AM29J6', 'SX22P9', 'BM29J8', 'SX23P4', 'FR22G7', 'BG22KO', 'AP22C1', 'NC2B16', 'GD20V8', '222066', 'EG23K5', 'GH20V3', 'HH20V3', 'AL29J5', 'BG28K2', 'DB2C03', 'BM29JX', 'BU2532', 'BF28K8', 'YH20V4', 'AU25J8', 'AM29J7', '2A23C8', 'ML2A69', 'BK22C7', 'BW22E5', 'BG23K0', 'BM29J2', '142442', 'BG23K9', 'AL29J4', 'GD20V7', 'AL29J0', 'GK26H6', 'AL29J6', 'EG23K9', 'HD20V9', 'BA23C2', 'ZA29C0', 'EW21A5', '8622K0', 'BG28KS', 'FX2265', 'TX22N0', '2A22C9', '8622K1', 'V02912', 'BA23C9', 'FR22G5', 'BM29J3', 'FR22G6', '0X22G9', 'BF28BX', 'BA22C4', 'KB20U2', '8R22E9', 'BG28KX', 'BF28B8', 'YH20V9', 'GH20V2', 'ZA29C8', 'NX22N2', '652037', 'GD20V9', 'BF22K7', '2K23CX', '8W23E6', 'A22EZ3', 'BU2538', 'AG20A8', '2A22C3', 'BG28K3', '8G22K9', 'UN2020', 'BF28K2', 'YH20V3', 'AP22CX', '142700', 'GP21A2', 'BA23C3', 'BM29J4', 'BL2934', 'BF28K1', 'FR22G8', 'BF28K9', 'FX2262', 'FX2269', 'DD21A7', 'CF28P3', 'ZK29C7', 'ND22S0', 'BA23C7', 'TX22N1', 'ZA29C7', 'ZK29C6', 'BA22C0', 'BL2937', 'BF22K4', 'BR22F5', 'FX2261', 'BA22CX', 'NX22N5', 'BF22K2', 'BM29J7', 'GH20VX', 'FX2266', 'ZK29C1', 'DD2EY5', 'GD20V0', 'ZA29C2', 'HD23S2', '8R23E6', 'BA22C8', 'AL29J7', 'BK23C2', 'GD20V3', '652136', 'BA23CX', 'SS23P1', '142704', 'BK23C6', 'BA23C5', '802339', '2K23C9', 'DD23S0', 'BF28K7', 'AE2KP8', 'BL2936', 'BK2625', '2K23C2', 'AL29JX', 'PX22PI', 'BF28B2', 'BL2939', 'BK22C6', 'AL29J9', 'BE24K8', 'BF28B1', '142440', '2K23C4', 'BK22C2', 'BU29J0', 'BK22C5', 'TX22N7', 'NX22N9', 'UN2364', 'KB20U6', 'HD20VX', '2K22C9', '8622K6', '8622K5', 'ZA29CX', 'YH2076', 'BU2535', 'NX22N8', '3R22E7', '2A22C8', 'BH2AW1', 'ZK29C9', '8622K7', 'HW2ZZ4', '022GD1', 'AC22C6', 'NX22N7', 'FR22G1', 'ZK29C2', 'BF28K4', 'BK23C3', 'KB20U8', 'BA23C1', '2K29C6', 'HD20V1', 'BG21K1', '5X23P9', 'BK22C3', '002606', 'KC20D3', 'BK22C4', 'SW21M8', 'BG23K2', 'RH21B2', '2A22C5', '802744', 'B622K7', '8622K4', 'GJ2110', 'ZK29C8', 'TX22N3', 'DL25R5', 'NX22N4', 'BG23K8', '8R23E2', '502581', 'B622K3', 'EX22G0', '8W23E4', '8R23E9', 'DB24B1', '8622K2', 'AP22C2', '2K23C1', 'GK26H2', 'BK23C4', 'ER22E1', 'ZA29C6', '5X23P1', '8622K8', 'EG21K3', 'KB20U1', 'FX2264', '8622K3', 'ZN23B6', 'FR22G9', 'BK29J6', 'HW21A0', 'BG23K4', 'FR22G3', 'BA22C5', 'AC22C2', '2A23C7', 'ZE2870', 'BU2534', 'DP21A2', 'PY22P6', 'GD20VX', 'ZN23B9', 'GD20V6', 'B622K6', 'KB20U0', '652004', 'BK23C7', 'FX226X', 'UN2362', '2A23C6', 'NX22NX', 'KC20FX', 'BU26J7', 'B622K1', '142443', 'AM29J1', '172554', 'BL2930', '8622K9', '2K22CX', 'TX22N9', 'BG23K6', '512110', 'BG23K5', '022906', 'BL2931', '8L29J1', 'HD20V7', 'SX23PO', '8622KX', 'BF22KX', 'WE23EX', 'YD2828', '502370', '8L29J7', 'EG23KX', '142523', '142524', 'CF22PX', 'GK26H1', 'B025J8', 'FX2263', 'CA2171', 'BK23C9', 'SX22PO', 'GG25K7', 'GD21A3', 'AY2NY7', 'BF28K6', 'KB22U1', 'BF28K0', 'BE23K4', 'AT2MVX', 'B622K5', 'FX22C2', '2K23C8', 'GK26H4', 'HD20V2', 'FX22C3', 'DX2266', '802811', 'UN2467', 'BA23C0', '8A23C0', 'EG23K2', '8R22E4', 'G622K5', 'FX2267', 'BF28K3', '2K23C6', '2A23C5', 'ZA29C4', '8W23EI', '172570', 'ND22S2', 'TX22N8', 'CF28P8', 'BG23KX', '8R23E0', 'B622K8', 'VP2863', '172551', 'ER22E6', '8R22E7', '2A29C2', '6H20V3', 'GH20V1', 'DB21B2', 'A22NE1', 'BD23S3', 'BA2443', '502877', 'BW23EA', 'RH2237', 'GH20V0', 'DX22GO', 'ZK29C0', 'AP22C4', 'BK23C8', '472AXD', 'BU2536', '8G22K1', 'BT2MW1', 'BU25JT', '8R22E2', 'GD20V4', 'DD22S5', 'DX2269', 'EW22E6', 'GK26H3', 'DX2267', '512671', '8R23E8', 'YL2FV5', 'SS22P2', 'NX22N6', '142703', '2A23C3', 'BM29J9', 'AC22C4', 'HD21A8', 'BE23K3', '2K23C5', 'FX2268', '5X23PX', '502294', 'DB2A07', 'YJ2274', 'KC206X', 'DB2A09', 'BR23ES', 'BF23K7', '8K22C0', '3G22K7', 'CA21A7', 'UN24D9', 'TX22N6', 'FR2266', '93220N', '802510', 'UN2068', 'TR2CA1', '2K22C6', '042TN9', 'HW2ZZ3', 'BE23K5', 'ZK29C3', '8U25JX', 'WJ2764', 'AM2AH8', 'MN25B5', 'UN24D2', 'RB23E2', 'WJ2727', 'DP21A5', 'FR2268', '502968', 'BE23K8', 'AM29J9', '8R23E1', '2A22CX', '2K22C3', 'BG21K8', 'EX22G4', '8R22E3', '172561', 'EW21A3', 'TU22N1', '2A23C2', 'K820U9', 'BU2589', 'BU2509', 'BG21KX', '2A29C5', 'BA2A93', 'CE22P4', 'FX22GO', 'W9235A', 'FX22P9', 'YB20H2', '8F28K8', 'EX22G1', 'EG23K0', '2K23C7', 'B622K9', 'AP22C5', 'TX22N2', 'KC20G4', 'BT2233', 'BG22KB', 'RX22G4', 'RX22G7', 'EG23K6', 'AC22CX', 'UN2367', 'EX22G8', 'ZN23A5', 'SS23PX', 'DB2C05', 'FC24H0', '8628KX', 'PX22PZ', 'KB2000', 'FF22P8', '2K29C4', 'GK26HX', 'DB21BX', 'FE22P3', '8R22E6', 'GP21A3', 'ZK29C4', '222058', '8W23E5', 'BJ22K6', 'BG21K9', 'BF23K9']
  Model_Year: ['1', '6', '5', 'A', 'D', '4', '7', '9', 'X', '8', '2', 'C', 'F', 'H', '3', 'B', 'R', 'E', 'Y', 'W', 'L', 'M', 'N', 'P', 'J', 'K', 'G', 'V', 'S', 'T']
  Plant_Code: ['U', '0', '3', 'S', 'X', '5', '1', '6', 'K', '7', 'Z', 'W', '2', 'A', 'G', 'B', 'M', '8', 'C', 'J', '9', 'P', 'O', 'D', 'H', 'T', 'V', 'I', '4', 'F']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,NON-GCC,4.0,4T1,BG22K0,1,U,789089
1,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,JTD,BR23E6,6,0,248294
2,TOYOTA,RAV4,4.0,SUV,H,FABRIC,GCC,5.0,JTE,HD20V5,5,0,062401
3,TOYOTA,HIACE,4.0,PANEL VAN,P,GL,GCC,5.0,JTF,PX22P7,A,0,017757
4,TOYOTA,HIACE,4.0,PANEL VAN,P,GL,GCC,5.0,JTF,PX22P6,D,0,037731
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27908,TOYOTA,SIENNA,6.0,SUV,Z,1,NON-GCC,NaN,5TD,ZA23C8,6,S,423033
27909,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,JTD,BR23EX,1,0,029184
27910,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,JTD,BR23E4,6,3,166451
27911,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,JTD,BR23E5,2,0,081369
27912,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,NaN,JTD,BR23E8,6,3,180837

====================================================================================================
pos6: 1
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'FJ CRUISER', 'CAMRY', 'AVALON', 'ECHO', 'BZ4X', 'AVANZA', 'VELOZ', 'RAIZE', 'HIACE', 'FJ', '86', 'COROLLA CROSS', 'DYNA', 'RAV4', '4RUNNER', 'COROLLA', 'HIGHLANDER', 'FORTUNER', 'LEVIN', 'RAV 4', 'T 300', '2023', 'بريفيا', 'SCION', 'ZELAS', 'JUSTIN BIEBER X VESPA 150 E5 GSO (SCOOTER)', 'SIENNA', 'LAND CRUISER', 'COASTER', 'PRADO', 'DAINA', 'BZ 4', '4 RUNNER', 'YARIS', 'INNOVA', 'C-HR', 'RUSH', 'T 100', 'CROWN', 'RUNNER', 'GRAND DELUX', 'ALLION', 'COROLLA 1.3', '1998', 'VENZA', 'XA', 'FRONTLANDER', 'TOYOTA 4RUNNER', 'افنزا', 'SPINA', 'U7', 'T100', 'AURION', 'H3', 'FORERUNNER', 'TOYOTA VELOZ', 'HI ACE', 'LAND CRUISER PICK UP', 'BZ46', 'CAMRY HYBRID', 'TACOMA', 'TOYOTA 86']
  bodyType: ['PICK UP SINGLE CAB', 'SUV', 'SEDAN', 'PICK UP DOUBLE CAB', 'MPV', 'PANEL VAN', 'STATION', 'COUPE', 'MINI BUS', 'PICK UP', 'PICKUP', 'HALF PANEL VAN', 'PANEL VAN HIGH ROOF', 'MINI BUS SEMI HIGH ROOF', 'MINI BUS HIGH ROOF', 'VAN', 'SUV- CROSSOVER', 'HATCHBACK', 'BUS', 'SALOON', 'PICKUP DOUBLE CABIN', 'TRUCK']
  pos4: ['E', 'B', 'D', 'C', 'M', 'A', 'Z', 'J', 'G', 'K', 'R', 'H', 'Y', 'S', 'V', 'T', '8', 'X', 'F', 'L', 'U', '1', '2', '3', '5', 'N', '0', '7', '6']
  trim: ['DLX', 'VXR', 'TOP', 'EXTREME', 'BASE', 'SE', 'GXR', 'XLE', 'LIMITED', 'XLI TOP', 'PRO', 'LIMITED PREMIUM', 'GLE', 'GX', 'DLX TOP', 'TURBO G RA', 'STD', 'GL', 'S', 'E', 'XLI MID', 'GLE-X HEV 40TH ANNIV', 'GLS', 'LE', 'STD (NON GCC)', 'DX', 'GLE HEV', 'SR5 (NON GCC)', 'XLE TOURING', 'GLI TOP', 'PS PW CL', 'SE+', 'XLI', 'VTX', 'GTX', 'DL', 'GLX', 'SPORT', 'EXR', 'FJ STD', 'MID', 'ADVENTURE', 'GLI', 'EX', 'XLE HEV', 'GT', 'SR', 'LE HEV', 'STATION', 'XL', 'TC (NON GCC)', 'XTREME', '1', 'L', 'LE STD', 'GRANDE HEV 40TH ANNIV', 'XLI EXECUTIVE', 'LE (NON GCC)', 'DLS', 'TURBO G', 'GXR SOD D/AC AW', 'XLE (NON GCC)', 'GRANDE', 'GLX SPORT Z', 'G', 'LWB', 'STANDER', 'VX', 'S PLUS', 'TRIM', 'SR5', 'PICKUP', 'TOURING', 'LS', 'CABRIO', 'STATION ', 'ROYAL', 'STANDARD', 'XSE (NON GCC)', 'STANDERD', 'AUTOMATIC', 'SWB', '45', 'VT', '1500', 'SED', 'SPORTS', 'TRD', 'VX MID', '60TH', 'TR', 'GLX PREMIUM', 'ROYAL EDITION', '0', '2', 'A', 'MPV', 'ST', 'VAN', 'LX AC PWR OPT', 'COM', '1000', 'XLI HEV']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MR0', 'JTE', '4T1', 'JTD', 'MRO', 'LVG', 'MHK', 'MHF', 'JT4', '4T4', 'JF1', 'LFM', 'JTG', 'JT3', 'KMF', 'JT2', 'JD4', 'JTN', 'JTC', 'JHG', 'JN6', 'LZC', '2CN', '2T1', 'MMM', 'JTK', '1NX', 'WBW', 'JHF', 'MAT', 'ZAP', '4T3', '5FP', '2C4', 'JN1', '2GN', '1D7', 'JTS', '2GC', 'KMJ', 'ZE1', 'JTB', 'JT6', 'NSP', '1GD', 'JAA', '3N1', 'JTZ', 'N1N', '1FT', 'JZS', '4TI', '3GY', 'MD2', 'KNR', '123', 'LSF', 'MKH', 'JNK', 'JTJ', 'JTF', '4F4', 'NV1', '1TG', '1N1', '3D7', '1N6', 'W11', 'SMT', 'UZS', 'W01', 'JHD', 'MRD', 'JTA', '5GT', 'RF5', 'AT1', 'VZE', 'L11', 'WB1', '1HG', '111', '474', 'MB0', '3GN', 'MFF', 'MRC', 'WDB']
  VDS: ['EW12G0', 'BU11F8', 'BU11F2', 'BU11F5', 'BU11FO', 'BF1FK2', 'BF1FK6', 'BU11F1', 'BK1EB5', 'EX12G5', 'BK1EB8', 'BK1EB6', 'BW1235', 'EX12GX', 'D31351', 'EX19G3', 'BK1EB3', 'BG12KX', 'CW12G0', 'MC13FX', 'BU11F7', 'AB1BY2', 'CW12G8', 'AA1BA4', 'ZA1190', 'BU11F9', 'CX19GX', 'CW12G4', 'BU11F0', 'BF1FK9', 'AA1BA1', 'AB1BAX', 'BW1336', 'BF1FK3', 'CX19G8', 'JT1236', 'G11AK4', 'D31359', 'EX19G8', 'EX19GX', 'ZN11B9', 'BF1FKX', 'EX12G2', 'CX19G7', 'AB1BA5', 'BW1337', 'CX12G5', 'AB1BY1', 'CX19G4', 'G11AK7', 'KZ1AK9', 'BK1EB9', 'BD1FK0', 'CX12G7', 'BF1FK0', 'BU11FX', 'K61AK9', 'EW12G5', 'EX12G4', 'BD1FK4', 'CX19G0', 'EX19G0', 'C11AK2', 'CU1BR6', 'RX12P6', 'ZN12B6', 'BF1FK7', 'BW1335', 'B11HK9', 'AA1BA8', 'CX19G5', 'ZR1198', 'EX12G0', 'BU11F4', 'BK1EB1', 'BK1EB4', 'CW12G1', 'B11HK4', 'RX12P5', 'EW12G6', 'BU11F6', 'EX12G6', 'MC13F7', 'BK1EB2', 'EX19G4', 'AB1BA9', 'AY1179', 'BF1FK1', 'RX12P7', 'B11HKX', 'G11AK0', 'CW12G5', 'BD1FK8', 'ZN11B7', 'CX12G4', 'AA1BA6', 'EX19G1', 'AB1BY3', 'HP10V2', 'CW12G7', 'KZ1AK2', 'YP10V8', 'G11AK9', 'EX12G8', 'BT14R4', 'GE17FX', 'BK1FK4', 'BW1331', 'BW1231', 'ZN12B4', 'BZ1FB3', 'YP10V3', 'EX19G6', 'CW12G6', 'BZ1FBO', 'AW12G5', 'BB13E5', 'BW1332', 'AB1BY5', 'BD1FK6', 'C11AK1', 'BU11F3', 'SK12E4', 'BK1EB0', 'AA1BA2', 'BF1FK5', 'EX12G7', 'BT1230', 'BA13E8', 'BF1FK4', 'HP10V5', 'B11HK3', 'CX12G8', 'CX12G1', 'EW12G1', 'VD10A2', 'MC13F6', 'C916Z7', 'ZA1197', 'MC13F5', 'BZ1FB5', 'RX12P2', 'CX12GX', 'BA13E3', 'TV1828', 'CW12G3', 'AB1BY0', 'BW1330', 'ZU14R4', 'BD1FK9', 'EW12G3', 'AA1BA5', 'AB1BY6', 'HP10V4', 'EX12G9', 'MC13F9', 'EW12G9', 'BK1EBO', 'MC13F3', 'AB1BY4', 'MC13F4', 'EW12G8', '8W1339', 'BA13EX', 'A11AK9', 'D31355', 'EW12GX', 'BK1EBX', 'MC13F8', 'EX19G2', 'AB1BA4', 'BZ1FB0', 'B31HKX', 'BK1EB7', 'CX19G1', 'BZ1FB1', 'AB1BA2', 'K61AK7', 'EX12G1', 'BF1FK8', 'CW12G2', 'RX12P4', 'MC13F1', 'AA1BA7', 'EX1269', 'AA1BA3', 'HP10V6', 'RX12PX', 'BT14R9', 'ZN12A6', 'B11HK2', 'MC12F6', 'ZU14R7', 'AB1BA6', 'EW12G7', 'B11HK5', 'CX12G9', 'AB1BY9', 'CX12G6', 'XP10V7', 'B21HK5', 'AA1BA0', 'EX19G7', 'BW1339', 'GP10V2', 'G11AKX', 'EB13E1', 'RX12P9', 'CX19G9', 'CX12G0', 'EX12G3', 'BD1FK7', 'BZ1FBX', 'BK1FK9', 'AW12G9', 'RX12P1', 'K61BK0', 'ZN12B2', 'FR1197', 'MC12F3', 'RX12P3', 'B519E4', 'BW1334', 'CU1BR1', 'BU14RX', 'ZN12A1', 'B519E0', 'L11AK3', 'YP10V6', 'G11AK8', 'CX19G6', 'K61AK1', 'BD1FK2', 'GP10V1', 'GP10V9', 'BA13E7', 'UF1170', 'HP10V3', 'AW12G2', 'S11AK0', 'MC13F0', 'B11HK1', 'BJ13E0', 'BA13E5', 'BZ1FB7', 'AB1BY8', 'BW133X', 'ZU14R8', 'ZU14R1', 'GP10V8', 'BD1FK5', 'BJ13E1', 'AB1BY7', 'C11AK0', 'AA1BA9', 'BW1338', 'ZA1191', 'EW12G2', 'BU11JX', 'ZN12B8', 'XP10V6', 'BW1333', 'DW12S1', 'BD1EB6', 'BD1EB9', '8F1FK0', 'B11HKO', 'B11HK0', 'BK1FK6', 'CX19G2', 'CW1262', 'HP10V8', 'AA1BAX', 'BA13E9', 'ZN12B3', 'CW12G9', 'B11HK8', 'AB1BA3', 'BZ1FB2', 'B61HK1', 'HP10V7', 'EW12G4', 'CW12GX', 'BW1230', 'EX19G9', 'BK1FK2', 'BZ1FB8', 'ZN1286', '1215CX', 'BD1EB2', 'RX12P0', 'AB1BA1', 'ZA1195', 'BZ1FB9', 'AW12G4', 'G11AK2', 'RX12PO', 'CX12G3', 'BJ18U8', 'RX12P8', 'BK1FK3', 'ZU14R5', 'ZA1135', 'ZR1199', 'CW1260', 'ZN12A0', 'ZN12B9', 'CX12G2', 'AL1CCX', 'ES12G0', 'BA13E6', '8A13E6', 'SK12W1', 'CX19G3', 'BW1237', '2A1190', '811HK2', 'AX12G8', 'AX12GX', 'B11HK6', 'M11AK7', 'BW1238', 'BK1FK7', 'BW1236', 'C618X8', 'B11HK7', 'AL1CC9', 'BF12K4', 'YP10V0', 'AZ1FBX', 'MC13F2', 'HP10V9', 'BA13E0', 'ZN12B5', 'EW12GO', 'BR12E8', 'GK13E8', 'BZ1FB4', 'BZ1FBS', '8F1FK3', 'GP10V0', 'ZN11A3', 'AB1BYX', 'JT1234', 'EJ13EX', 'EX1266', 'BG12K0', 'ZN12B1', 'BJ13E5', 'AW12G8', 'AX12G0', 'CU1BR0', 'DB12E9', 'B61HK6', 'ZT14R2', 'C11AK5', 'BA13E2', 'AB1BA0', 'FA1196', 'B21FB6', 'AL1CC6', 'AL1CC4', 'YP10V1', 'HP10V0', 'ZA1192', 'EJ13E8', 'ES12G6', 'AB1BA8', 'BA13E1', 'ZR119X', 'SK12E7', 'BZ1FB6', 'EX19G5', 'ZT14R0', 'BT17R4', 'T11AK5', 'BB12E6', 'GP10VX', 'YP10VX', 'K61AK0', 'BD1FKX', 'BK1FKX', 'HP10VX', 'BD1FK1', 'M1111M', 'D31357', '8F1FKX', 'D31356', 'CU1BR4', 'AC11R8', 'BT14RX', 'G11AK6', '8U11F6', 'CU1BRX', 'G11BK8', 'EX1268', 'BW1233', 'XP10V2', 'ZR1193', 'KU104X', 'BK1E82', 'CK12G4', 'BD1FK3', 'BD1EB4', 'AX12G1', 'EJ13E3', 'B61HK8', 'CU1BR3', 'AB1BYO', 'AX12G7', 'BJ13E9', 'BB12E7', 'BR18E5', 'MC12F5', 'BZ1HK0', 'BR12EX', 'B21FB2', 'EX1263', 'K61AKX', 'MC12F4', 'BU14R0', 'B01111', 'ZR1196', 'C11AKX', 'SK12E2', 'CX1267', 'ZU11F1', 'ZN11A4', 'T11AK9', 'GP10V3', 'UL11H5', 'ZU14R6', 'BZ1HK6', 'C11BK9', '8F1FK7', 'BJ13E4', 'AW1269', 'BD1EB7', 'SK12W4', 'G11AK5', 'MC12F9', 'BR12E5', '381228', 'C31AK2', 'ZU14RX', 'ZN1284', 'CW1265', 'AW12GX', 'CW1263', 'MC12F2', 'BT17R1', 'C11AK8', 'ZN11A2', 'GK13E9', '8F1FK2', 'TV1929', 'SK12E0', 'GA17FP', 'MD1218', 'BU17R1', 'C916Z4', 'C11AK9', 'C11AK6', 'B21FB0', 'BG12K1', 'B21FBO', 'BF1FKO', 'G11AK3', '8D1FK5', 'BW123X', 'CU1BR2', 'XP10V1', 'ZR1192', '8K1FK3', 'ZN11AX', 'B61HK9', 'MC12F1', 'CS12G7', 'ES12G8', 'R11AK8', 'BK1E89', 'BG12K9', 'BB12E5', 'BD1EB3', 'EB13EX', 'B519E9', 'CU1BR5', 'XP10V9', 'ZU14R2', 'BR12E2', 'ZF13C8', 'UV1822', 'YK1F7X', 'AW12G7', 'EX1209', 'BT14R2', 'ZR1191', 'BB13E3', 'KP14T0', 'CC1BR5', 'B61HK4', 'GP10V6', 'K61AK3', 'KP14TX', 'RC1BG6', 'CS12G8', 'AX12G2', 'AL1CC5', 'HZ14S6', 'AB1BA7', 'ZU17R2', 'FA1193', 'ZU11F2', 'JZ1FB8', 'BR12E1', 'CX1263', 'B519E1', 'CS18Z3', 'B519E5', 'AX12G9', 'RV1GP9', 'FR1193', 'KZ1AK5', 'FR1192', 'EJ13E5', 'BZ1HK7', 'M11AK8', 'BW1232', 'BT17RX', 'AX12G6', 'BF12K0', 'C11AK7', 'AX12G5', 'BK1FK1', 'CX1966', 'CU1BR9', 'HP10V1', 'EX1261', 'F11AK7', 'CU1BR8', 'F31AK7', 'ZU11FX', '381324', 'YP10V4', 'EK19T1', 'ZN12B7', 'ZA119X', 'HD17F2', 'EF12K3', 'MC12F0', 'ZA1193', 'ZN11A5', 'ZN11A1', 'D31353', 'EJ13E2', 'BW1234', 'XP10V8', 'CS12G4', 'FZ1FB4', 'C11AK3', 'BK1FK0', 'GP10V5', 'S11AK7', 'C31AK6', 'CC1BR7', '8F1FK9', 'A818Y7', 'BD1EB8', 'BR12E7', 'BR12E3', '811HK6', 'KZ1AK3', '511161', 'K61AK8', 'CC1BR0', 'UF117X', 'ZN12A9', 'AA1BAO', 'ZU11F3', 'BR12E6', '811HK5', 'K61BK6', 'AW12G1', 'BR12E4', 'EB13E5', 'AS14U0', 'BK1FK5', 'BR18E8', 'BJ13E7', 'B21FB3', 'EB13E3', 'F11AK4', 'EX1265', 'BU14R9', 'C31AK7', 'B61HKX', 'ZF19C6', 'EU11F1', 'BA13E4', 'M11AK6', '8W1332', 'ZR1190', 'BD1EB1', 'BG12K3', 'SK12E5', 'BT17R6', 'C11AK4', 'G11BK7', 'KT1230', '8A13EX', 'FR119X', 'B31HK9', 'YP10V9', 'GZ1FB0', 'ZF13C3', 'D31352', 'AX12G4', 'SK12E8', 'AW12G6', 'GA17F3', 'BW1239', 'BU14R1', 'BD1FKO', 'BU17R8', 'JZ1FB4', 'ZA1198', 'K31AK7', 'UF1171', 'BD1EB5', '151407', 'ZU14R0', 'XP10V3', 'B519E7', 'ZU14R3', 'ZR1194', 'BT17R2', 'BU14R3', 'BT14R0', 'DE1675', 'ZT14R1', 'FA119X', 'FG15T7', 'EX1969', 'GA17F4', 'EW1261', 'XP10V4', 'FP14F3', 'T11AK2', 'C11AKO', 'BU14R8', 'BB13E2', 'SK12W3', 'MC12FX', 'EW1265', 'B519E6', 'BJ13E6', 'CW12GO', 'ZA1194', 'SK12E9', 'CW1269', 'CU1BR7', 'ZT14R5', 'YP10V7', 'GP10V4', 'B61HK7', 'CX1266', 'MC12F8', 'BA1HK0', 'BJ13E8', 'ES12G5', '8W1334', 'CC1BR9', '8U11F9', 'ZR1195', 'XP10VX', 'ZN12BX', 'SK11E2', 'GP10V7', 'BC11E4', 'ZU17R0', 'GA17FX', 'AL1CC2', 'C916Z0', 'EB13E4', 'D31354', 'K61AK4', 'UF11H3', '8W1338', 'AE1BYE', '501891', 'C916ZO', 'CW1261', 'UF11H6', '1N1ENV', 'B61HK2', 'AL1CC3', '511131', 'BB12E9', 'EX1E63', 'BR12E0', 'SK12EX', 'BU14R4', 'ES12GX', 'BB13EX', '151005', 'CX1265', 'BT17R8', 'FA1194', 'ZU17R8', 'CC1BR6', '8U11F2', 'K61BK4', 'ES12G1', 'DB12E4', 'GK13E7', 'B61HK0', '171000', 'C916Z9', 'C11AKS', 'BG12K7', 'HG17C8', 'EW1260', 'C11BK0', 'C31AK3', 'R11AK6', 'AX12G3', 'ZN12B0', 'ZN12A7', 'G31AK0', 'BT14R8', 'JM11D9', 'BD1EB0', 'BD1EBO', 'EJ13E7', 'BK1E88', 'BG12K6', 'BF18B6', 'EB13E0', '8K1E85', 'F11AK6', 'CX1264', 'HG17CX', 'BB13E0', 'ZT17R1', 'G11AK1', '8W1233', 'C616Z8', 'BR12E9', '8U11F7', 'VD10A4', '8U11F1', 'ES12G7', 'EJ13E6', 'SK12CX', 'HD17FP', 'FR1198', 'K61AK5', 'FK1221', 'EW1266', 'G11AKO', 'BT1234', 'HB10V4', '501857', 'BG17K2', 'EJ13E0', 'ZR1197', 'BW12S0', 'CX12GO', 'DB12E3', 'NB1BB2', 'B31HK7', 'R11AK7', 'F11BK2', 'ZF19C5', 'ZF19C9', 'A11CX7', '171007', '8K1E87', 'BB12E8', 'BG12K5', '151004', 'S31AK5', 'C916Z6', 'B519E3', 'AS12G0', 'FA1191', 'AB1BAO', 'AZ1FB2', 'AL1CC7', 'BU14R2', 'FR1190', 'ZT14R6', 'ZU17R9', 'ZN12A4', 'G31AK5', 'BT17R9', 'DW12S6', 'G11BK6', 'T11AK1', 'BT1233', 'TN12DX', 'JA17B3', 'MC12F7', 'ZN11A0', 'B21HK7', '1L1HEA', 'T11AKX', 'AS1232', 'EJ13E4', 'AC1DM8', 'FZ1FB5', '8U11F8', 'AW12G0', 'BK1EBS', 'EX1964', 'B61HK3', 'AB1BYB', 'EX1267', '8W1331', 'ZA1199', 'FR1194', '801FKA', 'AL1CC8', 'UV1825', 'B31HK1', 'ZN11A6', 'EX1262', 'HD17F6', 'BD1EBX', 'EW1EP2', 'AM11H6', 'ZU11F9', 'BD1FKA', 'K61AK6', 'DZ1FB1', 'YP10V5', 'SK12E6', 'BY11F4', 'HF10U7', 'AB18Y8', 'BF12B1', 'ES12G3', 'C916Z8', 'F31AK5', 'AY1173', 'BK1FK8', 'BT17R7', 'BJ13E3', 'YP10V2', 'AW1267', 'B519E8', 'K31AK0', 'ZU17R3', 'BT14R5', 'CS12G5', 'EB13E7', 'BJ13E2', 'BT17R0', 'C31AK8', 'FA1198', 'XP10V0', '8U11F0', 'SK12W6', 'B21HK0', 'HD17F9', 'F31AKX', 'ZN12A5', 'HD17FX', '8F1FK5', '8F1FK4', 'AZ1FB9', 'ZA1196', 'F31AK3', 'KY1CDX', 'ES12G9', 'G11BK2', 'BB13E7', 'L11AK9', 'S11BK2', 'B519EX', 'D31350', 'SK12W8', 'EU11F0', 'BB12E0', 'B11HKI', '801259', 'AM11H1', 'KP14T5', 'CC13C6', 'G11BK4', 'DA1AB2', '111111', '8U11FX', 'CX1261', 'ZF13C2', 'B61HK5', 'BU11FG', 'JV1ET2', 'D3135X', 'T11BK9', 'BU17R7', 'DB12E5', 'ZF13C0', 'GK12E8', '511028', 'ED1EK2', 'ZE11A4', 'BZ1HK5', 'GA17F5', 'CW1267', 'G31AKX', 'BF12K5', 'T11AK4', '8W133X', 'DW11S8', 'F11AK0', 'UF1176', 'A818Y5', 'ZU17R6', 'BU17R0', 'ZF13C4', 'CC1BR2', 'C916ZX', 'BF18B8', 'ZU14R9', 'CX1268', '8U11F3', 'C31AK4', 'FA1195', 'UF11H0', 'M11AK0', 'DX1H24', 'DB12E2', '8W1335', 'CC1BR8', 'ZN11A9', 'CG12K9', 'T11AK7', 'HD17F5', 'BZ1HK4', 'EB13E8', 'AY117X', 'AX1269', 'BF12B7', 'XP10V5', 'EX126X', '2T14R7', 'ZT17R4', 'BU14R6', 'BW12S8', 'SS1EK5', 'SS1EK7', 'A11CY2', 'ZF13C1', 'JT1233', 'AA18A8', 'B21HK2', 'CC1BR4', 'ZN11A8', 'CV12G9', 'DW12SX', 'CW1264', 'AT1237', 'BF1FKI', 'BU11FS', '151403', 'CW126X', 'BG12K4', 'FA1190', '8F1FK6', 'ZN11B0', 'ZF13CX', 'CW1268', 'M11AK4', 'BB13E9', 'EF12K7', 'A11CX6', 'A11CX0', 'EG12K0', 'J11BK7', 'BF12B4', 'BZ1HK1', 'AW12G3', 'BU14R7', 'K61AK2', '2A1197', 'G11BK1', 'EG12K5', 'B21FB8', 'EX12GO', 'BK1E80', 'EX1963', 'BB12E4', 'T11AK3', 'BU17R4', 'JZ1FB3', 'BF18B7', 'UF1179', 'DN1363', 'ZU11F5', 'SK12W9', 'T11BK8', 'A11CX1', 'S71T02', 'JM11D3', '811EB7', 'BZ1HKX', 'ZN12A2', '151517', 'B910L5', '511497', 'BW12S6', 'CX1904', 'CC1CX2', 'BJ13EX', 'EX1965', 'B31HK0', 'KZ1AK4', 'C31AK5', 'BU11FB', 'B21FB1', 'DW12S5', '011111', '511890', 'ZA119S', 'EK12G8', 'CV1F40', 'EJ13E1', '111S11', 'SK12W0', 'MD1212', 'GA17EP', 'B21HK4', 'B21HK1', 'AL1CC0', 'CU18R8', 'AA18A6', 'EX1260', 'CX1269', 'UV1826', 'AA1AB4', 'CX126X', 'ZT14R8', 'BZ1HK3', 'C31AKX', 'BZ1HK2', 'AC1DM7', '8U11F4', 'G11BK3', 'SK12FX', 'FW12G1', 'ZU11F7', 'AX1268', 'ZN1287', 'BU11FV', 'BF1FKS', 'ZN12A8', 'DN1366', 'S11AK9', 'B21HK8', 'BT123X', 'G11BK5', '8F1FK1', 'G11BKX', 'ES12G4', 'M11AK2', 'GA17HP', 'VN13G4', 'B011F6', 'B31HK4', 'EK12TX', '2U14RX', 'AA1BAB', 'B31HK5', 'B519E2', 'AS12G9', 'RC1BG7', 'B21HK6', '2R1197', '751068', 'DW11S0', 'EJ13E9', 'BF18B5', 'CX19GO', 'AE1EYX', 'Z41197', 'BU11E6', 'FA1197', 'JR14T8', 'C11BK2', 'CC1BR3', 'DW12S4', '1111W1', 'BF1FKZ', 'SK12E1', 'NZ1AK4', 'EW1268', 'C616ZX', 'FZ1FB3', '1111S1', '811HK4', '801838', 'F11AK8', 'FR1196', 'RS12P4', 'CW1266', 'HD17F1', 'VK13E6', 'ZN12E7', 'T11AK8', '511096', 'B61HKO', 'G31AK6', 'KT1231', 'EB13E6', 'DB12E0', '2A1192', 'CX190X', 'ZN12AX', '8D1FK2', 'BD1FKI', 'B31HK8', 'ZF13C7', '621017', 'HG17C1', 'TN14DX', 'ES12G2', 'BT14R3', 'M11AK5', 'C11BK7', 'ZN11A7', 'C21FB1', 'L11AK8', 'L11AK1', 'VD11E8', 'ZN12A3']
  Model_Year: ['8', 'E', 'C', 'G', 'F', '7', 'D', 'B', 'Y', 'P', 'J', 'T', '9', 'R', 'X', '2', '5', 'L', 'A', '6', 'M', 'H', 'S', '4', 'K', '3', 'W', '1', 'N', 'V']
  Plant_Code: ['3', 'K', 'U', '0', '2', 'G', 'J', 'R', '8', '7', 'C', '5', '1', '4', 'Z', '6', 'M', 'S', 'B', 'X', 'L', ' ', 'F', 'T', 'A', 'P', 'N', 'H', '9', 'V']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,E,DLX,GCC,2.0,MR0,EW12G0,8,3,009992
1,TOYOTA,FJ CRUISER,6.0,SUV,B,VXR,GCC,5.0,JTE,BU11F8,E,K,180180
2,TOYOTA,FJ CRUISER,6.0,SUV,B,TOP,GCC,NaN,JTE,BU11F8,E,K,195990
3,TOYOTA,FJ CRUISER,6.0,SUV,B,EXTREME,GCC,NaN,JTE,BU11F2,C,K,126452
4,TOYOTA,FJ CRUISER,6.0,SUV,B,BASE,GCC,5.0,JTE,BU11F5,8,K,045095
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19278,TOYOTA,TOYOTA 86,4.0,COUPE,Z,GTX,GCC,NaN,JF1,ZN12A3,G,G,025017
19279,TOYOTA,RAIZE,4.0,SUV,A,TURBO G RA,GCC,NaN,MHK,AA1BA6,R,J,112571
19280,TOYOTA,HILUX,4.0,PICKUP,E,1,GCC,NaN,MR0,EX12G3,B,2,053186
19281,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,SE,NON-GCC,NaN,4T1,BF1FK9,G,U,126846
19282,TOYOTA,AVALON,6.0,SEDAN,B,LIMITED,GCC,NaN,4T1,BK1EB4,F,U,172449

====================================================================================================
pos6: 8
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'FORTUNER', 'RUSH', 'GRANVIA', 'INNOVA', 'YARIS', 'COROLLA', 'RAV4', 'LAND CRUISER', 'CRESSIDA', 'SUPRA', '4RUNNER', 'COROLLA 1.6', 'CAMRY', 'URBAN CRUISER', 'PRADO', 'بيك اب كابينه مزدوجه', '26HX DC 4X4P2.7LAT', 'HD 4X4', 'HIACE', 'COROLLA SEDAN', 'CROWN', 'AURION', 'LAND CRUISER 70', '25 HX DC 4X4D 2.4LAT', '25 HX DC 4X4 2.7LAT', 'GLX DA (PICK UP)', 'SIERRA', 'COROLLA 1.8', 'LEVIN', 'TOYOTA SUPRA', 'TOYOTA HILUX', 'SALOON', 'SEQUOIA', '25 HX DC 4X4P 2.7LAT', '26HX DC 4X4D2.4L AT', '26 HX DC 4X4 2.4LAT', '26HX DC 4X4 D2.4LAT', 'هايلوكس', '25 HX DC 4X2 P 27L AT GLX RA/PICK UP', '26 HX DC 4X4 D 2.4L AT', '25 HX DC 4X4 P .LAT', 'TOYOTA - 26 HX DC 4X4 D 2.4L AT', '25 HX DC 4X4', 'DLX FA (PICK UP)', '26 HX DC 4X4 P 2.7LAT', 'TOYOTA COROLLA', 'HX DC 4X4 D 2.4L AT', '26 HX DC 4X4D', 'HILUX ADVENTURE', 'CELICA', 'TOYOTA RUSH', 'HAI LUX']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'PICK UP SINGLE CAB', 'MPV', 'SEDAN', 'SALOON', 'PICKUP', 'COUPE', 'PICK UP', 'HATCHBACK', 'VAN', 'PANEL VAN', 'STATION', 'COUPE/CABRIOLET', 'PICKUP DOUBLE CAB', 'MINI BUS', 'PICK-UP']
  pos4: ['B', 'D', 'E', 'K', 'H', 'Y', 'C', 'J', 'G', 'A', 'W', 'M', 'R', '8', 'T', '0', 'V', 'S', '2', '6', '5', '4', 'Z', 'N', 'F']
  trim: ['GL', 'EXR', 'EX', 'SGLX', 'GLX', 'DLX', 'PLATINUM', 'GL2', 'VXR', 'GXR', 'DLS', 'SE+', 'STD', 'GX', 'G', 'GLS', 'ADVENTURE', 'GLI', 'SE', 'STD D', 'VX2', 'VX1', 'DL', 'S', '1500', 'LE', 'SR5 (NON GCC)', 'XLI POWER OPT', 'VX', '0', 'XLI', 'TX', 'AUTOMATIC', 'TRIM', 'HILUX', 'LIMITED', 'XLE', 'GLE', 'STD (NON GCC)', 'XLI TOP', 'LUXURY', '1', 'HT SLWB', 'SLD', 'C', '10TH VICTORY EDITION', 'VX2 PLUS', 'TOP', 'GXR2', 'GR BLUE EDITION', 'BASE', 'TRD', 'A', 'GGG', 'STANDARD', 'EXECUTIVE', 'SPORT', 'AMBIENTE', 'MID', 'XLI MID', 'BLACK EDITION', 'GLI TOP', 'PICKUP', 'SR5 4X4', 'GL DECKLESS', '2', 'GL TOP', 'E', 'GRANDE', '4', 'DX', 'FLEET', 'SE T2', 'SALOON', 'GR SPORT']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MR0', 'MHF', 'MHK', 'JTN', 'MR2', 'LFM', 'WWW', 'LVG', 'MR1', 'JTM', 'MRO', 'JT2', 'JT4', 'JT3', 'MRI', 'KMH', 'MZB', 'MRD', 'JTE', '1NX', 'WMA', 'UP1', '00N', '1GN', 'NV1', 'JM3', 'WV1', 'MBJ', 'JAC', 'MHE', '55S', 'WDB', '1GT', 'LA9', 'ZE1', '090', 'JH2', 'JS2', '5TD', 'MRU', 'JTD', '1LN', '1GJ', 'RKL', 'JHD']
  VDS: ['BX8CD3', 'DX8FS9', 'DX8FS2', 'EF8BF4', 'KB8CD7', 'EF8BF2', 'HX8CD5', 'KB8CD0', 'EF8BF5', 'DX8FS5', 'EF8BF8', 'BX8CD8', 'BX8CDX', 'HX8CD4', 'YM8AP0', 'BX8CD2', 'DX8FS3', 'KB8CD4', 'HX8CD6', 'BU8FS1', 'KU8FSX', 'EF8BF3', 'KB8CD2', 'HX8CDX', 'CX8CD6', 'HX8CD7', 'HX8CD3', 'BX8CD1', 'JX8CD5', 'GX8EM3', 'DX8FS1', 'HX8CD2', 'KU8FS7', 'EF8CF1', 'KB8CD8', 'HX8CD0', 'EF8CF7', 'BU8CD2', 'DX8FS8', 'HX8CD8', 'BF8C30', 'DX8FSX', 'KB8CD3', 'EF8BF1', 'DX8FS4', 'EF8BF9', 'BU8FS5', 'KU8FS8', 'JX8CD8', 'HU8CD0', 'BU8FS2', 'JX8CD3', 'CX8CB9', 'EF8BFX', 'BX8CD7', 'KB8CD5', 'BU8CD0', 'DX8FS6', 'JX8CB7', 'HU8CD1', 'CX8EM1', 'KU8FS9', 'BX8CD6', 'JX8CD4', 'EF8CF2', 'JX8CD1', 'JX8CD9', 'JX8CD2', 'BU8FS3', 'A18097', 'KB8CDX', 'W88888', 'CX8EM5', 'KU8FS1', 'HX8CD1', 'BY80E2', 'BX8CD9', 'CX8EM3', 'KU8FS2', 'KU8FSO', 'KX8CBX', 'EF8CFX', 'DX8CD5', 'EF8CF8', 'DX8CD4', 'EF8BF7', 'KX8CB4', 'BX8CD4', 'EF8BF6', 'CX8EM9', 'DX8CD1', 'KU8FS4', 'EF8BF0', 'DX8CD7', 'KB8CD9', 'CX8EMO', 'BF8C3X', 'BX8CD0', 'JX8CD7', 'BU8FS8', 'BX8CD5', 'JX8CD0', 'BU8CD4', 'A180C1', 'CX8EM0', 'BU8CD5', 'DX8FS7', 'BF8C39', 'BU8CD6', 'BF8C34', 'KX8CB2', 'DX8F58', 'BU8CD7', 'EF8CF3', 'KU8FS0', 'CX8EM8', 'EF8CF4', 'BF8C37', 'CX8EM7', 'CX8CD3', 'BU8FSX', 'AU88JX', 'CX8EMX', 'KB8CD1', 'BU8FS9', 'JX8CD6', 'BU8CD1', 'KU8FS3', 'CX8EM4', 'EF8CF9', 'KU8FS5', 'CX8EM6', 'KB8CD6', 'DX8FS0', 'HX8CDO', 'DX8CD6', 'KU8FS6', 'CW8CD9', 'BF8C35', 'KX8CB1', 'BU8CDO', 'CX8EM2', 'BU8FS0', 'EF8BFO', 'GX8EM9', 'BU8CD9', 'EF8CF0', 'CX8GS9', 'HU8CD4', 'KX8CB7', 'BF8C31', 'BU8FS4', 'BY80E1', 'BU8FS7', 'BY80E9', 'CX8CB5', 'GX8EMX', 'KX8CB8', 'MX83EX', 'KX8CB3', 'GX8EM1', 'JX8CDX', 'KX8CD0', 'BF8C36', 'YM8AP5', 'BF8C32', 'CX8CB6', 'EF8CF6', 'GX8EM5', 'DX8CD2', 'CX8CD8', 'RN81A5', 'EF8BFZ', 'JX8CB8', 'BF8C33', 'HX8CD9', 'HB8CD2', 'EF8CF5', 'BU8CDX', 'BF8C38', 'CW8CB7', 'JA82J0', 'BY80E0', 'HN86R7', 'GX8EM2', 'BY80E6', 'DX8F5X', 'CW8CB3', 'KX8CB5', 'A180C2', 'CX8CD9', 'GX8EMI', 'HU8CD7', 'CX8CB1', 'CX8CD5', 'CX8CB0', 'HN86R1', 'A180C3', 'BU8CD3', 'GX8CD9', 'CX8CD1', 'KB8FS0', 'GN87R6', 'HU8CD3', 'CX8CBX', 'CX8CB8', 'DX8CDX', 'CX8CB3', 'DX8FSO', 'CW8CD7', 'BA8CD4', 'JT81E2', 'GX8EM0', 'GX8EMO', 'BU8FSO', 'BY80E3', 'E2815A', 'HN87R7', 'DX8CD9', 'JX8BB2', 'KX8CB0', 'YM8AP2', 'DB8CD2', 'BU8FS6', 'EF8BFI', 'HJ85J4', 'GX8EM7', 'CX8GS6', 'JX8BB9', 'DX8CD8', 'BY80E4', 'CW8CB9', 'CW8CDX', 'DB8CD0', 'BA8CD7', 'HU8CD6', 'JU8FJ2', 'EF88F5', 'A180C0', 'JX8CB3', 'CW8CB0', 'EF8CFO', 'AE82G3', 'JA81LX', 'BY80EX', 'HN86R5', 'BU8CD8', 'RN82P6', '8U8CD2', 'KX8CB9', 'WG81R1', 'BY8799', 'CX8CD0', 'CW8CD2', 'CX8CD4', 'JX8CB4', 'CX8CD2', 'T48ZZZ', 'JX8BB4', 'BE85B9', '8X8CD8', 'GX8EM8', 'GN86R6', 'CX8CB4', 'CW8CB6', 'CX8CDX', 'RN81A2', 'HN86R8', 'KX8CB6', 'MX83E7', 'BX8CDO', 'BX8C05', 'AP86C4', 'DX8CD0', 'AP86C7', 'HU8CDX', '008004', 'AU88J0', 'V18044', 'JA82J1', 'SK8KD7', '808508', 'A180C8', 'DX8CD3', 'JA81J7', 'DB8FS6', 'DB8FS4', 'A180C6', 'YM8AP7', 'BA8CD8', 'GX8EM6', 'WH8139', 'GX8EM4', 'A888J6', 'HN86RX', 'JS8CD5', 'CX8CB2', 'BY80E8', 'CX8CD7', 'DX8F52', 'YM8AP3', 'AY86C7', 'BA8CD3', 'A180C5', 'DJ81W4', 'KB8CDO', 'BX8CDE', 'AP86C3', '8U8CD9', 'EF88F2', '2882K7', 'A180CX', 'HJ85J3', 'CX8CB7', 'CW8CD4', 'HN87R1', 'CW8CB8', 'CW8CB4', 'BC81S7', '008567', 'JX8BB5', 'DX8FSB', 'DH88W4', 'AP86C6', 'JA81L5', 'EF88F0', 'JX8BB1', 'KB8CP8', 'JA81L9', 'KU8F52', 'CW8CB5', 'HB8CD9', 'DJ81W1', 'DD82A3', 'WF8HB3', 'HJ85J2', '808931', 'JA82J8', 'KX8C85', 'JX8BB7', 'CW8C86', 'CX8GS0', '658050', 'CX8C80', 'DX8F55', 'CX8GS5', 'W78CG1', 'HU8CD2', 'AU88J2', 'WG81R3', 'HB8CD5', 'DB8CD8', 'HN87R5', 'AP86C0', 'CW8CB1', 'BY8092', 'GN87R2', 'JX8CB2', 'C08RW6', 'DX8F59', 'HB8CD3', 'DH88X7', 'SJ8IVP', 'CW8CBX', 'EF8CFS', 'BA8CD1', 'DX8CDO', 'HN87R3', '508121', 'YM8AP8', '408B06', 'A180C4', 'A888J9', 'SC87C2', '808764', 'ZC8B20', 'JX8BB0', 'DJ81W2', 'JA82J9', 'BY84A4', 'DX8F51', 'JA82J5', 'HB8CD6', 'BY84A5', 'GX8CD6', 'BY80E7', 'DB8CDX', 'KU8FSG', 'HU8CD9', 'HJ85J5', 'JA82J3', 'WG81R8', 'KU8F58', 'AP86C8', 'CW8BB9', 'EF88F3', 'HN86R3', '508736', 'AX8CD9', 'JX8CB5', 'KU8F5X', 'GX8CD3', 'CX8EMI', 'AU88J9', 'CW8CD0', 'EF8BFS', 'BU8F59', 'DB8FS7', 'HN86R2', 'GN86R8', 'DX8F50', 'CX8GS2', '6N87R6', 'DE82A0', 'B28F32', 'KW8D37', 'BM82F8', 'EF88F7', 'BY8798', 'JX8CB0', 'DB8CD7', '808390', 'Z78FG6', '008983', 'HJ85JX', 'DX8F57', 'EF88F9', 'KX8CD6', 'KU8F55', 'N38ZZ6', 'HU8CD8', 'BX8CDI', 'HU8CD5', 'CW8CB2', 'AU88J6', 'BL8HE3', 'CW8CD6', 'KX8CD4', 'DB8CD6', 'CX8GSX', 'JX8BB3', 'CW8CD1', 'BA8CD9', 'A180C7', 'JX8BBX', 'FG8JP7', 'RN81A7', 'JA81J8', 'GN86R9', 'BB8CD7', 'EF8C31', 'HJ85J0', 'KX8CDX', 'KX8FS7', 'DB8CD9', 'JX8CB9', 'HJ85J6', 'GX8CD0', '808905', 'JA81L7', 'JA81J1', 'AP86C2', 'MX83E0', 'KX8CD5']
  Model_Year: ['N', 'L', 'M', 'P', 'R', 'G', 'K', 'H', 'S', 'T', 'J', '8', '1', '2', '9', '7', '5', 'X', 'F', 'W', 'B', 'Y', '3', '4', '6', 'V', 'C', 'E']
  Plant_Code: ['2', '0', 'K', '1', '8', '3', 'G', '4', '5', '9', 'U', 'E', 'Z', 'O', 'M', 'R', 'X', '7', 'C', 'S', 'B', '6', 'D', 'Y', 'W']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,B,GL,GCC,4.0,MR0,BX8CD3,N,2,843057
1,TOYOTA,FORTUNER,4.0,SUV,D,EXR,GCC,5.0,MHF,DX8FS9,L,0,103088
2,TOYOTA,FORTUNER,4.0,SUV,D,EXR,GCC,5.0,MHF,DX8FS2,M,0,111888
3,TOYOTA,RUSH,4.0,SUV,E,EX,GCC,5.0,MHK,EF8BF4,P,K,035407
4,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,K,SGLX,GCC,2.0,MR0,KB8CD7,R,1,220373
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9913,TOYOTA,HILUX,4.0,PICKUP,B,1,GCC,NaN,MR0,BX8CD0,P,2,848848
9914,TOYOTA,FORTUNER,6.0,SUV,B,VXR,GCC,NaN,MHF,BU8FS2,R,0,039310
9915,TOYOTA,RUSH,4.0,SUV,E,EX,GCC,NaN,MHK,EF8BF0,N,K,026216
9916,TOYOTA,YARIS,4.0,SEDAN,B,G,GCC,NaN,MR2,BF8C39,P,0,007706
9917,TOYOTA,HILUX,6.0,PICKUP,H,GLX,GCC,NaN,MR0,HU8CDX,K,0,071134

====================================================================================================
pos6: 3
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'AVALON', 'RAV4', 'SIENNA', 'PRIUS', 'PRADO', 'PREVIA', 'COROLLA', 'GRANVIA', 'SOLARA', 'HIGHLANDER', 'TUNDRA', 'LITEACE', 'MATRIX', 'YARIS', 'ECHO', 'ALPHARD', 'LAND CRUISER', 'HILUX', 'LAND CRUISER PRADO', 'SEQUOIA', 'TOYOTA ALTIS', 'FJ CRUISER', 'RAV 4', 'MR2', 'INNOVA', 'FORTUNER', 'TANDRA', 'HIACE', 'VENZA', 'SCION', 'CELICA', 'C-HR', 'SENA', 'TOYOTA PRADO', 'SELICA', 'SENA VAN PASSENGER', 'COROLLA 1.8', 'SIENA', 'STATION', 'LITE ACE', 'SIENNA(VAN)', 'COROLLA 1.6', 'CHR', 'VAN', 'COROLLA CROSS', 'COROLLA ', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'MPV', 'HATCHBACK', 'CONVERTIBLE', 'SALOON', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'VAN', 'CARGO VAN', 'STATION', 'COUPE', 'PICKUP', 'ESTATE', 'PICK UP SINGLE CAB', 'MINI BUS', 'REGULAR CAB', 'WINDOW VAN', 'HALF PANEL VAN', 'LIGHT VEHICLE', 'SUV- CROSSOVER']
  pos4: ['B', 'K', 'Z', 'J', 'G', 'D', 'W', 'Y', 'X', 'C', '5', '8', 'L', 'F', '2', 'R', 'E', 'S', 'M', 'A', 'H', 'P', '6', 'T', '1', 'V', '3', 'U', '0', 'N']
  trim: ['XLI', 'BASE', 'STD (NON GCC)', 'LE', 'LE (NON GCC)', 'ICONIC', 'GXR', 'GRANDE', 'TOP', 'MID', 'XLE (NON GCC)', 'EX', 'DLX', 'LIMITED (NON GCC)', 'EXR', 'VXR HEV', 'GLI', 'TX-L', 'XLE TOURING', 'VXR', 'PREMIUM', 'ADVENTURE', 'EXCLUSIVE', 'SE', 'VX', 'STD', 'C (NON GCC)', 'XLI MID', 'XLI TOP', 'ECO', 'GLI TOP', 'GL', 'GLX', 'EXR HEV', 'LIMITED', 'SE (NON GCC)', 'LE HEV', 'TX-L TOP', 'XLE', 'GLE HEV BLACK EDITION', 'TX', 'T', 'TXL2', 'DLS', 'GX', 'SED', '1', 'PW CL', 'X', 'SR5', 'SAFARI', 'GLE HEV', 'HYBRID', 'DX', 'TXL1', 'DYNAMIC', 'S', 'HYBRID (NON GCC)', 'GLE', 'LTD HEV', 'DL', '1500 CREWCAB SLE Z71', 'TXL3', 'TRD', 'SENA', 'GT', 'STANDARD', 'VX TOP LTH', 'PLATINUM', '4X4', 'COMFORT', 'EXCELLENCE', 'SU', 'MPV', 'GLS LOWLINE', 'A', 'ASAD', 'TOP LTH', 'STEALTH', 'ALTIS (NON GCC)', 'TRIM', 'SUV', 'GLI HEV', 'GLI TOP LTH', 'SL', 'GXR HEV']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['6T1', '4T1', 'JTM', '5TD', 'JTD', 'JTE', '2T3', 'JTN', '4T4', 'ZE1', '1NX', '2T1', '5TB', 'MHK', 'LFM', 'JNB', 'JM3', '4TI', 'ZAP', 'YV2', 'TNX', 'RKL', '1GC', 'RA6', 'INX', '4T3', 'STD', 'MMM', 'WD4', 'JN1', 'WMW', 'MB1', '6TI', 'STO', '5T1', 'NV1', '1FT', 'WME', 'JHD', 'LPS', 'JE3', 'JTH', 'KMJ', '611', '2TI', 'ME4', '5FP', 'NMT', 'WDD', 'LGW', 'UTD', '471', '411', 'MPA', 'GT1', 'JAM', 'JM7', 'JNK', '6TB', '1GJ', '010', 'JAA', 'STM', 'MM7', '5N1', 'AUS', '1FD', '150', 'XWB', 'MBI', 'MBT', 'JTV', 'ET1', 'J10', 'FJ4', '3T1', 'MR0', 'AE1', 'STB', 'UTM']
  VDS: ['BE32K4', 'BK36B6', 'BK31V3', 'BF3EK0', 'KK3DC1', 'BE32KX', 'BE32K3', 'KB3FUO', 'KB3FU0', 'BE33K8', 'KK3DC9', 'BU3FJ5', 'BE32K9', 'BF3EK8', 'BF32K5', 'BE32K1', 'KN3DU2', 'KK3DC2', 'BK3DB9', 'ZK31V1', 'JU3FJ3', 'BK36B7', 'BE30K8', 'BA32K0', 'BD31V3', 'KZ3DC2', 'Z13FV3', 'BD31V4', 'Z13FV8', 'BF32K2', 'GD34M6', 'DW3FV1', 'BU3FJX', 'Z13FV7', 'KK3DC5', 'BF3EK7', 'W13FVX', 'BK33V0', 'B13FV7', 'BK36B4', 'DW3FV3', 'BE32K0', 'BE33K5', 'BK31V5', 'BE33K6', 'BE32K7', 'BK36B0', 'Z13FV9', 'BU3FJ6', 'YK3DC6', 'Z13FV5', 'BR32EX', 'Z13FV0', 'BF32K1', 'BF38K9', 'Z13FV4', 'BD31V6', 'BF3EK5', 'XZ3DC8', 'BE32K8', 'BK36B9', 'CX3FJ4', 'BU3FJ0', 'BK3DB0', 'XK3DC7', 'YK3DC4', 'XK3DC6', 'XK3DC4', 'BE32K5', 'BD31V5', 'JU3FJ2', 'BK3DB5', 'BK3DB3', 'DW3FV4', 'YM3AP3', 'BK36B5', 'BD31V2', 'BU3FJ9', 'KN3DU9', 'BK32V3', 'BE30K6', 'BE32K2', 'GD34M0', 'BK36B3', 'BK3DB6', 'BE30K4', 'J13FVX', 'YK3DC7', 'YK3DC3', 'KN3DU1', 'BF3EK2', 'BD31V7', 'BE30K0', 'BU3FJ4', 'BE30KX', 'BU3FJ1', 'BK36B2', 'YK3DC8', 'KK3DC8', 'BU3FJ3', 'ZK3DC8', 'BD33V1', 'BE33K4', 'BF3EK9', 'BA32KX', 'YK3DC5', 'BE32K6', 'W13FV2', 'ZK3DC0', 'CA30P2', '513033', '8A32KX', 'KN3DU3', 'LB3CH8', 'J13FVO', 'JU3FJ6', 'XK3DCX', 'BE33K0', 'YZ3DC4', 'CX3FJ9', 'BK3DB7', 'BK36B1', 'BK3EK8', 'BR38E6', 'KK3DCX', 'BR32E4', 'KK3DC0', 'YK3DC9', 'BF32K3', 'KN3DU8', 'BK3DB2', 'BD33V4', 'YK3DC0', '8E32K9', 'Z13FV1', 'DW3FV7', 'ZD33V1', 'BD31VX', 'GD32M5', 'BD33V8', 'W13FV8', 'YZ3DCX', 'BD33V3', 'YM3AP8', 'BF32K9', 'LB3CHX', 'KB3FU5', 'LB3CH0', 'BR32E0', 'XK3DC2', 'JN3214', 'BD31V0', 'BR32E3', 'J13FV3', 'BK3DB8', 'BK3DB4', 'BR32E9', 'KN3DU6', 'Z13FVX', 'BD33V0', 'W13FV9', '5D3BV4', 'YZ3DC1', 'KN3DU0', 'BF32K8', 'J13FV0', 'YZ3DC9', 'BF32K7', 'FA38P8', 'BE30K2', 'BU3FJ7', 'BR32E2', 'BF32K4', 'BD31V1', 'BA32K8', 'BK36BX', 'BR38E8', 'BU3FJ8', 'GD32M1', 'DK3DC6', 'BE30K5', 'J13FV1', 'GD32M7', 'LB3CH5', 'BD32V9', 'BF31F9', 'JU3FJX', 'BD33V9', 'BF30K8', 'BE33K9', 'BE30K1', 'BR38E0', 'JV36F2', 'BF31F3', 'BF3EK1', 'BR32E7', 'KN3DUX', 'KR32EX', 'ZK3DC4', 'BF31V8', 'BF31F8', 'KR32E6', 'BK3DB1', 'BF38K2', 'KR30E1', 'BK3DBX', 'KB3FUX', 'ZK3DC6', 'BE30K3', 'YK3DC1', 'KZ3DC4', 'BF3EK4', 'Z13FV6', 'JK3DCX', 'YZ3DC6', 'BF30KX', 'BF38K5', 'JU3FJ9', 'BW3FVO', 'BK3EK4', 'BD31V8', 'XK3DC0', 'BU3FJ2', 'GD32MX', 'KB3FU3', 'DR32T9', 'BD31V9', 'KZ3DC1', 'W13FV1', 'YK3DCX', 'JU3FJ1', 'ZD33V3', 'BR32E8', 'KN3DU7', 'BR32E6', 'W13FV7', 'JK3DC0', 'KK3DC7', 'BE30K7', 'BR38EX', 'ZD31V7', '2K3DC3', 'BE33K1', 'KB3FU9', 'KN3DU4', 'GD34M2', 'ZK31V8', 'ZK3DC3', 'ZK31V9', 'DW3FV9', 'DK3DC7', 'BD33V6', 'KK3DC6', 'RT3412', 'KK3DC3', 'CX3FJX', 'DK3DC2', 'GK3DH4', 'BW3FV7', 'KK3DC4', 'CX3FJ3', 'YM3AP6', 'BF30K6', 'ZN3EU8', 'KZ3DC9', 'BF31F4', 'BK32V6', 'W13FV4', 'J13FV5', 'BF3EK3', 'DK3DC0', 'KN3DU5', 'BD33V5', 'BK36B8', 'BK31V9', 'JU3FJ4', 'BF3EKX', 'YM3AP2', 'LB3CH1', 'KA3DC5', 'BD35V1', 'KB3FU2', 'BR30E5', 'FA38P3', 'CX3FJ0', 'BE36KX', '543BV7', 'Z13FV2', 'BK31V6', 'BF30K0', 'ZD33V0', 'BF30K4', 'BE33K3', 'LB3CH9', 'ZK33V7', 'BF32K6', 'BF38K7', 'ZF33V6', 'YK3DC2', 'BE33K2', 'BF33V9', 'ZN3EU3', 'ZN3EU1', 'Z23FV4', 'ZK33V0', 'BR32E5', 'DK3DC3', 'ZK3DCX', 'W13FV0', 'BF3EK6', 'LB3CH6', 'B13FV9', 'KA3DC7', 'ZF33V4', 'XK3DC3', 'CX3FJ5', 'BW3FV1', 'ZK31V5', 'BF30K1', 'BX3FJ5', 'W13FV5', 'BK32V5', 'KB3FU6', 'KB3FU1', 'LB3CH3', 'KZ3DC0', 'KA3DC9', 'BX3FJ0', 'BX3FJO', 'ZN3EU7', 'BF32KX', 'R13FV1', 'ZZ3DC5', 'KR32E8', 'J13FV9', 'XK3DC1', 'KZ3DC8', 'BF38K3', 'BA30K4', '8E32KX', 'BX3FJ7', 'DZ3DC1', 'BF38K0', '8D31V8', 'JZ3DC2', 'ET3419', 'DE32K0', 'JK3DC3', 'BK32V4', 'BF30K7', 'B13FV6', 'FA38P5', 'JK3DC6', 'BB3EKX', 'CX3FJ2', '8F30K1', 'JU3FJ5', 'GD32M8', 'BW3FV6', 'BF31F7', 'BE30K9', 'BW3FV8', 'ZN3EU0', 'BW3FV9', 'ZK3DC1', 'BF31FX', 'JU3FJ7', 'SL35E6', 'BX3FJ9', 'BF38K6', 'B13FV4', 'KR32E9', 'BK33VX', 'GD32M4', 'LB3CH2', 'R43FV3', 'CX3FJ8', 'J13FV8', 'BF30K9', 'W13FV3', 'DW3FVO', 'LA3AH3', 'GD34M4', 'BF31F6', 'ZK34V4', 'BK32V8', 'R13FVO', 'JV36FX', 'BF38KX', 'BF38K4', 'CE38P0', 'BE33K7', 'KR32E7', 'XK3DC9', 'J13FV6', 'BA32K9', 'GD32M2', 'BR32E1', 'JK3DC4', 'KZ3DC6', '8E32K3', '513902', 'ZD33V4', 'BD35V4', 'BW3FV5', 'BB3EK1', 'YZ3DC7', 'BD33V2', '8D33V2', 'KA3DC3', 'BF38K8', 'MD3502', 'BR30E4', 'ZK31V6', 'BK3EK6', '2K31V6', 'GD32M6', 'BF30K2', 'BF30K3', 'BK3EK7', 'BF33V7', 'DK3DC9', 'KB3FU7', 'R13FV0', 'ZK3DC9', 'JZ3DC6', 'BU3FJO', 'BF30K5', 'W13FV6', 'BA32K5', 'JU3FJ8', 'J13FV2', 'AG30AX', 'R03FV0', '8K3687', 'GD34M9', 'BW3FVX', 'ZD32V9', 'BW3FV2', 'BK31V7', 'YZ3DC0', 'YZ3DC5', 'XK3DC5', 'ZN3EU4', 'ZD32V2', 'JK3DC7', 'BA32K7', '8E32K6', 'B13FV2', 'KR32E2', 'J13FV7', 'JK3DC1', 'DW3FV0', 'BF31F1', 'KZ3DC7', 'DW3FV5', 'JZ3DC0', 'BR30E8', 'R13FV2', '8D31V4', 'YK3DCO', 'ZN3EUX', 'BK31V8', 'BK33V1', 'DW3FV6', 'BK34V4', 'BF32V0', 'CX3FJ1', 'BF3EKO', 'ZK31V3', 'DK3DCX', 'KA3DC0', 'ZK3DC2', '5C3AV4', 'BE3EK9', 'JZ3DC4', 'BR38E1', 'DW3FV2', 'GD32M3', 'YM3APX', 'BD33VX', 'J13FV4', 'JU3FJ0', 'LA3AH6', 'BK31V4', 'BD35V2', 'ZD33V7', 'LB3CH7', 'ZT38A3', 'GZ3DHX', 'BK31V0', 'BK33V6', 'RU3417', 'BU3AE5', 'R13FV3', 'KZ3DC3', 'BF32K0', 'BK33V3', 'JZ3DC1', 'BD35V9', 'HR33NX', 'YZ3DC2', 'BK34V5', 'Z13FVO', 'BR30E1', 'BE33KX', 'GD34M3', '8K36B8', 'ZD33V8', 'BF38K1', 'KA3DC4', 'LB3CH4', 'ZE32V2', 'BD33V7', '8U3FJ4', 'ZK31V7', 'XK3DC8', 'ZF33V1', 'MA3603', 'XZ3DCT', 'SL35E2', '543AV4', 'ZK3DC7', '8K3DBX', '5D3BV9', 'PE32K6', 'ZD32V6', 'B13FV8', 'CX3FJ7', 'B13FV5', 'BK3EH0', 'ZD31V9', 'JU3FJO', 'B13FV0', 'ZZ3DCX', 'BK33V4', 'DK3DC8', 'BX3FJ1', 'BR30E7', '6D32M9', 'GD34M8', 'PG34L5', '8E32K7', 'JW30F9', 'GD34M1', 'FA38PX', 'BF33V6', 'BK31VX', 'ZD33V5', 'JW30F1', 'DW3FVX', '8E32K1', 'ET3417', 'BB3EK6', 'BB3EK5', 'BF31F5', 'BR30E3', 'DK3DC5', 'ZK3DC5', 'R43FV4', 'BK31V2', 'BA32K1', 'YM3AP5', 'KA3DC8', 'YM3AP9', 'CX3FJ6', 'YZ3DC3', 'BK34V2', 'SL35E4', 'BX3FJ2', 'BX3FJ3', 'KB3FU8', 'BK3685', '8K3685', 'KB3FU4', '8K36B5', 'RW3FV2', 'DZ3DC4', 'DW3FV8', 'DZ3DC2', '8U3FJ8', 'KV36F1', '8E32K8', 'KN3DP1', 'ZD32V8', 'ZF31V6', '8K3D89', '213FV5', 'BK32V7', 'DZ3DCX', 'ZA3BB4', 'BF31V2', 'YM3AP4', 'YM3AP1', 'BB3EK0', 'XZ3DC2', 'ZN3EU6', 'W13FVO', 'BB3EKO', 'BA32K6', 'BF33V0', 'KA3DCO', 'JK3DC9', 'EL33P9', '8R32EX', '8F32K6', 'BR38E3', 'BA32K3', '8F3EK1', 'BK35V1', 'B13FV1', '8D31V3', '8D31V7', 'FR3206', 'B13FV3', 'GD32M9', 'BK32VX', 'RW3FV0', 'GD34MX', 'LA3AH0', 'BF3EKS', 'BW3FV4', 'DZ3DC9', 'KZ3DC5', 'GD32M0', 'BX3FJ6', '8D31V1', 'BF33V4', 'R43FV5', 'BK32V9', '8K3681', 'KR32E1', 'ZZ3DC4', '2K3DC4', 'BK3EK3', 'BK33V8', 'WG3E13', 'BK33V7', 'DT3MW5', 'BD32V2', 'ZC3C52', 'ZD33V2', 'BF31F2', 'BF33V1', 'RU3413', 'DZ3DC8', 'RW3FVX', 'BK35V2', 'SD35E5', 'JW30F8', '8R32E1', 'CE38P9', '8E32K4', 'YZ3DC8', 'KA3DC1', 'RT3416', 'KA3DC2', 'AG34L4', 'ZD33V6', 'LA3AHX', 'BK33V9', 'BA32K2', 'ZN3EU9', 'R13FV8', 'KN3DUS', 'ZK31V4', 'BX3FJ8', 'BF33V2', 'KK3DCG', 'R13FV6', 'RT3413', 'R13FV9', 'BK32V0', 'ZD31V5', 'JZ3DC7', '8E32K5', 'BB3EK2', 'BK35V9', 'FA38P9', 'BA30K9', 'BR30E9', 'LB3CHO', '8K33V9', '2K31V4', 'Y23DC1', 'KN3DP7', 'BD32V5', 'GD34M7', 'R13FVX', 'BR38E2', 'DZ3DC5', 'YM3AP0', 'BB3EK8', 'KN3D00', 'ZF33V5', 'BF3EKB', 'BK3EK1', '5D3BV7', 'DK3DC4', 'RW3FV1', '803285', 'JU3FJS', 'ZF35V1', 'SS3EL5', 'ZD31V2', 'YM3AP7', '803454', '8D33V0', 'JZ3DCX', 'BR30E0', 'BA30K5', 'CA38P8', 'ZN3EU2', '213FV1', '8E30K9', 'JW30F6', 'BK3BB1', 'JK3DC8', '8F3EKX', 'B13FVX', 'JK3DC2', 'JK3DC5', 'BK33V5', 'BF33VX', 'L83CH1', 'BE38K1', 'EK31X6', 'KZ3DCX', '8F3EK3', 'ZE32V7', 'RW3FV5', 'FD3HLS', 'KN3DUO', 'RW3FV3', '8E30K7', 'BK3EHX', 'BK34VX', 'ZE32V0', 'ZD33VX', '8D31V5', '2K31V7', 'ED3KA5', 'BD32V6', 'ZZ3DC3', '8F3EK8', 'BB3EK3', 'BK31V1', '8E33K1', '8E30K3', 'JW30F7', 'ZK31V2', 'BB3EK9', 'BF31F0', '8U3FJ3', 'ZF33V2', 'RW3FV7', 'R13FV5', '8F32K7', '8D31V0', '8D35E5', 'ZD35V4', 'BX3FJ4', 'BA30K7', 'BE32KG', '8D31V9', 'DR32T0', '8U3FJX', '543AV3', 'ZE32V3', 'BW3FV0', 'CB3FV8', 'KR32E3', 'MD3501', 'ZZ3DC6', 'BU3FJI', '8F30KX', '8D33V7', '8K3684', 'AB36U5', 'LA3AH4', 'BN30F4', 'ZK31VX', 'ZK31V0', '8D33VX', 'SD35E9', 'ZZ3DC2', '8E32K2', 'FR3204', 'BK3EK5', 'JW30F3', 'BK32V1', 'RU3419', 'ZK32V3', 'KK3DCO', 'ZF33V9', 'BR30E2', 'BE3EK7', 'JU3211', 'RT3415', 'BK32V2', '8F30K7', 'KN3DP6', '813FV9', 'WA37R1', 'BE3EK5', 'AG34L8', '8K3EK1', 'ZD31V3', 'KC311A', 'R13FV4', 'XZ3DCX', 'BA32K4', 'YK3F13', 'RW3FV8', 'KV30F8', '8F3EK7', 'JN321X', 'RW3FV9', 'ZA3BB8', 'MD3524', 'DY32T7', 'MD3512', 'B13FVO', 'BK33V2', 'KR30E6', 'BK3EH5', '543AVX', '8E32K0', 'BD3173', 'ZD33V9', 'KA3DCX', '5D3BV2', 'TC31E9', 'BA30K3', '8K32V5', 'KV30F7', 'ET3413', 'BK34V8', 'GZ3DH5', 'BK35V8', 'ZZ3DC0', '2F33V5', 'LY3FX5', '213FV9', 'BD35V6', 'TC31E1', 'XZ3DC4', 'BA30K2', 'BF32V2', 'BE32KS', 'LA3AH1', 'SD35E4', 'BR30EX', 'BK3EK0', 'BF31V9', 'BW3FV3', 'JZ3DC9', 'GD34M5', 'FH3CB1', 'R13FV7', 'CB3377', 'GZ3DH4', 'AG34L2', 'KR32E0', 'ZK32V4', 'DK3DC1', 'ZF35V4', 'CB3379', 'ZD31VX', 'KK3DCI', 'BR38E9', 'JW30F2', 'K83FU8', 'BA30K8', 'BE32KT', '8U3FJ6', '5C3AV7', '8F30K0', 'Z23FV9', 'BK36BN', 'K83FU9', 'BF31V7', 'FA38P7', 'ZD32V0', 'D13FV4', '8E33K2', '543BV2', 'RW3FV4', 'XZ3DC7', 'DR32T1', '2K31V1', 'BU3FJS', '5D3BV8', 'BD32VX', 'KB3FUB', 'BF35V5', 'BF31E6', 'ET3416', '8K31V3', 'RT3417', 'YM3APO', '8F31FX', 'KN3D02', 'DZ3DC7', '5C3AV6', 'JU3FJB', 'J23DC7', 'BB3EK7', 'GZ3DH6', 'XZ3DC0', 'ZK32V8', 'BF33V5', 'KV30F3', 'ER33P0', 'W13EV6', 'J13FVI', 'PG34L8', '8D31VX', 'BR38E5', '8E30K2', 'BK3EKX', 'KV30F9', '543AV5', 'BK3EH1', '8D31V2', 'BF33V3', 'LP345X', 'ZF31V2', 'B03FVX', 'RT3410', 'KR32E4', 'BE3EK3', 'BB3EK4', 'BK3267', 'BK3DBO', '503335', 'Z23FV0', 'LA3AHO', 'Z23FVO', 'DA31A8', 'BF31V5', 'BF31FO', 'ZT34A3', 'BE3EKX', 'ZK32V7', '8F3EK4', '1E33K0', 'AG34L7', '803505', '213FV8', 'K83FU3', '8D31V6', 'WA37R7', 'BF3FK3', 'HG39K3', 'VC31F0', 'BK3681', 'ET3410', 'BE32KO', 'K83FU0', '8K31V9', 'KB3FUS', 'BF31EX', 'ET3418', 'DK3DCO', 'BD32V1', '303H66', 'ZA3EH2', '5D3BV5', '8E33K6', 'ZT34A7', 'RU3418', 'KN3DP3', '8K33V0', 'ZK33VX', 'BK35V7', 'BY30E8', 'KV32F9', 'CE38P1', 'DL39M9', 'Z13FVB', 'UN3463', 'BK3EK9', 'JW3EH0', 'KV30F2', 'JN3216', 'KN3DP9', 'BT3AB3', 'WA37RX', 'ZT34A4', 'DR32T8', '8U3FJ1', 'KV30F1', 'L83CH3', 'KV30FX', 'JZ3DC3', 'LA3AH7', 'BR38E7', 'GZ3DH2', '8E30K6', 'LA3AH2', 'ZD35V3', 'BR30E6', 'R03FV2', 'BF33V8', 'BU3EJ5', 'UN3163', '503914', '8R32E6', 'RT3813', 'FA38P1', 'B031V6', 'CA31A7', 'BF31E9', 'BD3175', '8F3EK0', 'BD32V4', 'ZD31V0', 'JM30D3', 'ZK32V9', 'BJ3355', 'WE3FN2', 'ZD31V6', '87367Z', 'GK3DH9', 'ZZ3DC7', 'ZZ3DC1', '3K32ED', 'ET3815', 'DY38T0', 'BD35V0', 'ET3411', '6D32M1', 'CA30P7', 'BK3EK2', '513821', '8F38K0', 'ZF31V9', 'CA38P9', 'BY32E5', 'ZK32V6', 'EU3FJ1', 'R43FVX', 'DK3EH7', 'ET3816', 'LY3FXX', 'ZF33V8', 'BA3BE9', 'BD31VK', 'BF31V1', 'LY3FX4', 'XZ3DC9', 'KA3DC6', 'RT3419', 'RW3FV6', '8F30K4', 'DZ3DC3', 'BT3AA3', 'KN3DP0', 'PE30K1', 'MD3517', 'KK3EH0', 'D23DC5', 'KK3EHO', 'ZK33V6', 'BA3BB0', '8D33V6', 'AG34L1', 'AG34LI', 'YK3DCI', '8U3FJ5', 'BD3371', 'BF35V4', 'AG34L3', 'EE32K0', 'KR38E0', 'Z23FV1', 'JU3218', 'K23DC3', 'RU3416', 'ZZ3DC9', 'GZ3DH3', 'ZD32VX', 'BF32X6', 'LB3CHI', '2K33V7', 'BU3FJB', 'AG34L9', 'BD32V8', '8E30K4', 'ZK33V5', 'ZF31V0', 'BK3686', 'XK3DCD', 'ET3412', 'RN3414', '803180', '8K3680', 'EZ3DC6', '2T38A8', 'ZT38A8', '8F3EK6', 'KN3DP2', 'ET3817', 'BK34V3', '8U3FJ9', '8E30KX', 'JK3EH1', 'RT3814', '213FV3', '033500', 'BD32V7', 'ZZ3DC8', 'BK35VX', 'BK35B7', 'EE32KX', 'BD32V3', 'NA3DCS', 'K23DC7', 'BA30K0', 'CX3DD5', 'KN3DP5', 'ZN3EU5', '013026', 'RT341X', '8E30K0', 'RT381X', 'ZF33VX', 'ED31V4', 'G13FV7', 'R43FV0', '8D33V8', '8K3686', 'B031V5', 'D23DC2', 'DK3EH1', 'KV30F0', 'LA3AH5', 'BE3EKZ', '8E30K8', '543BV9', '543BV8', 'JW30F5', '543BV4', 'DR32T4']
  Model_Year: ['5', '7', '6', '8', 'B', 'D', '4', 'H', 'F', 'J', '3', 'C', 'A', 'L', 'M', 'R', 'N', 'P', '9', 'S', 'E', 'G', '2', '1', 'T', 'K', 'Y', 'W', 'X']
  Plant_Code: ['X', 'U', '5', 'S', '0', '3', 'K', 'D', 'W', '8', '2', 'R', '1', 'Z', 'C', 'J', '6', '7', 'P', 'B', 'H', 'L', '4', 'T', 'V', 'A']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,GCC,4.0,6T1,BE32K4,5,X,483890
1,TOYOTA,AVALON,6.0,SEDAN,B,BASE,GCC,4.0,4T1,BK36B6,7,U,203308
2,TOYOTA,CAMRY,4.0,SEDAN,B,XLI,GCC,4.0,6T1,BE32K4,6,X,532054
3,TOYOTA,RAV4,6.0,SUV,B,STD (NON GCC),GCC,5.0,JTM,BK31V3,8,5,065132
4,TOYOTA,CAMRY,4.0,SEDAN,B,LE,GCC,4.0,4T1,BF3EK0,B,U,749116
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33492,TOYOTA,PRIUS,4.0,SEDAN,K,STD (NON GCC),NON-GCC,NaN,JTD,KN3DU9,A,0,058716
33493,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,XLI,GCC,NaN,4T1,BE32K8,6,U,721335
33494,TOYOTA,SIENNA,6.0,SUV,K,LE (NON GCC),NON-GCC,NaN,5TD,KK3DC7,G,S,742721
33495,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,1,GCC,NaN,6T1,BE32K7,6,X,544408
33496,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,GLI,GCC,NaN,6T1,BE32K8,6,X,538813

====================================================================================================
pos6: 4
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'CAMRY', 'COASTER', 'INNOVA', 'RAV4', 'SIENNA', 'AURION', 'TACOMA', 'C-HR', 'HILUX', 'TOYOTA CAMRY', 'YARIS', 'COROLLA 1.6', 'TUNDRA', 'LAND CRUISER', 'SUPRA', 'MATRIX', 'FJ CRUISER', 'LAND CRUISER PICK UP', 'HIACE', 'HIGHLANDER', 'TOYOTA TACOMA', '2009', 'SEQUOIA', 'TAKOMA', 'TOYOTA TUNDRA', 'GRANVIA', 'PRADO', 'SICION', 'TOKOMA', 'RAV 4', 'TANDRA', 'SIENNA VAN', 'FORTUNER', 'SUPRA COUPE', '25 CA SON P 2.5L AT', 'COROLLA LI', 'CORONA', 'COROLLA 1.3', 'COROLLA 1.6/SEDAN', '26 YA HB P 1.6L AT TURBO GR RA(CAR)', 'ORION', 'SCION', 'TANDRA PICK UP DOUBLE CABIN', 'COROLLA 1.8', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'BUS', 'MPV', 'SUV', 'PICKUP', 'PICK UP SINGLE CAB', 'SALOON', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'PICK UP', 'COUPE', 'MINI BUS', 'LIGHT VEHICLE', 'STATION', 'PANEL VAN', 'PICK UP DOUBLE CABIN', 'PICKUP DOUBLE CABIN', 'VAN', 'CONVERTIBLE', 'TRUCK', 'MINIVAN']
  pos4: ['B', 'F', 'X', 'D', 'Y', 'U', 'K', 'E', 'A', 'J', 'Z', 'P', 'L', 'N', '8', '0', '5', 'T', 'R', 'M', 'W', '3', 'C', '4', 'G', '9', '1', 'H']
  trim: ['XLI', 'SE+ ANNIVERSARY EDITION', 'STD', 'GLX', 'GL', 'SE+', 'GLI', 'LIMITED', 'STD (NON GCC)', 'VXR', 'BASE', 'LE', 'SPORT', 'SE', 'LE (NON GCC)', 'MID', 'VX', 'XLI TOP', 'XLI MID', 'DLX', 'GLE HEV', 'TOP', 'FLEET', 'SALOON', 'LE STD', 'EXR', 'XSE (NON GCC)', 'GLE', 'XLI POWER OPT', 'GLX SPORT Z', 'S PLUS', 'LWB HIGH ROOF', '40TH ANNIVERSARY EDITION', 'TOURING', 'XLE', 'GLE-X HEV 40TH ANNIV', 'DX', 'GX', 'LSE', 'GR', 'EX', 'EXTREME', 'E PLUS HEV', 'SR5 (NON GCC)', 'DL', 'LMV', 'LE HEV', 'LWB', 'LX AC PWR OPT', 'SWB', 'X', 'CE (NON GCC)', 'PICK UP', 'LIMITED HEV', 'HYBRID (NON GCC)', 'GL TOP', 'S', 'SGL', 'STD AC', 'SL', 'HEV', 'LUMIERE HEV', 'GXR', '4X4', 'GRANDE', 'GLI TOP', 'TRIM', 'XL', 'DLX TOP', '1', 'PREMIUM', 'PRESTIGE', 'E', 'GRANDE HEV', 'GL LIMITED', 'XLE (NON GCC)', 'GLI TOP LEATHER', 'ORION', 'BE', 'LTZ', 'GLS', '4', 'GLE-X', 'EXCLUSIVE', 'PW CL', 'PLATINUM', 'PICKUP ', 'TXR', 'SAFARI', 'CAR TRIM', 'TUNDRA', 'CTD', 'PICKUP', 'SED', '2', 'S TRD AERO PK', '40 TFSI S-LINE', 'SV', 'GRANDE HEV 40TH ANNIV', 'SR', '0', 'ST', 'SPORTS BASIC', '40TH ANNIVERSARY EDI', 'TRD SPORT', 'SE+ ANNIVERSARY EDIT']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['RKL', 'JTN', 'JTC', '6T1', 'JTD', 'MHF', '1NX', 'JTM', '2T3', '5TD', '2T1', '5TF', 'NMT', '4T1', '5YF', 'JTF', '4T4', '5TB', '1N4', '8T1', '5TE', 'JTK', 'JT4', 'JTG', 'WZ1', 'LFM', 'JTE', '3TM', 'INX', '4TA', 'GTF', 'KN9', 'SYF', '6TI', 'ZE1', 'LVG', 'MM7', '4TT', '411', '5T1', 'JT6', '5T8', 'MAT', '1FD', '213', 'JTH', 'LC0', '611', 'STD', 'GT1', 'NV1', 'STO', 'JRN', 'JTL', 'WDD', 'YV1', 'JN1', '5XX', '211', 'WDB', 'STE', 'LSJ', '471', 'EE1', '6T0', 'RKT', 'LMX', 'JTR', 'BT1', '4TI', '671', 'KMH', 'WZI', 'LHG', 'MHE', '2D4', 'JYM', 'KL5', '61L', 'JDT', 'YBL', 'WVG', 'WVW', 'W1K', '55S', 'KNM', 'JED', 'JTU', 'ST1', 'MFH', 'UTD', 'JIN', 'SMT']
  VDS: ['BZ42E7', 'BZ4HK6', 'FZ4182', 'BE42K7', 'BR42E6', 'XX43G3', 'BF4FK3', 'XX43G7', 'BE42K3', 'B24HKX', 'BE42K8', 'BE42K6', 'BE42K0', 'BC42E8', 'BU4EEX', 'BR42E1', 'BE42K9', 'BR42E0', 'BC42E2', 'BC42E0', 'DF4EV3', 'YK4DV0', 'BZ4HK8', 'BZ42E0', 'YK4CC6', 'BK42K2', 'BU4EE7', 'B24HK0', 'B24HKO', 'BV42E8', 'BZ42EX', 'UX4EN4', 'BU4EE0', 'BE42K1', 'KZ4BX5', 'BE42K4', 'BV42E6', 'BV42E1', 'BZ42E9', 'BF4FK8', 'BK40K7', 'XX43G1', 'BE46K5', 'BC42E7', 'BK4FK0', 'B14HKX', 'B24HK7', 'BU4EE1', 'BE42K2', 'EG4265', 'BV42E7', 'BU40E7', 'XX43GX', 'BF4HK2', 'BV42E0', 'BB42E6', 'XX43G0', 'AG4CK1', 'XX42G2', 'BZ4HK7', 'BE46K4', 'BF4DVX', 'XX42GX', 'BR42EX', 'BF4HK8', 'B24HK2', 'BF4HK7', 'BE46K2', 'B24HK5', 'KZ4BX7', 'BE42KX', 'BF4HK1', 'BE46K6', 'BK42K9', 'BV42E3', 'JT4K3X', 'AM4968', 'BK40K5', 'BZ42E6', 'BK40K1', 'BR42E4', 'BZ4HKX', 'BC42E9', 'BZ4HK9', 'BE46K9', 'BC42E5', 'BB42E4', 'BZ42E4', 'BV42E5', 'BT4419', 'BZ42E3', 'BZ4HK5', 'BE42K5', 'BU4EE3', 'B14HK2', 'BZ4HK1', 'BR42E7', 'KZ4BX3', 'BF4FKX', 'BL40E0', 'KK4CC3', 'XX43G9', 'ZF4DV3', 'BB42E0', 'A14CK1', 'KK4CC2', 'BZ42E8', 'B14HK3', 'B242E4', 'BC42E1', 'BU4EE4', 'BZ4HK4', 'BL4A96', 'DT4416', 'BZ4HK0', 'BZ42E5', 'BR40E9', 'BV42E2', 'KZ4BX9', 'BE46K7', 'KZ4BX0', 'A14CK7', 'BE46K8', 'PX42N6', 'KZ4BX6', 'KZ4BX8', 'BE46KX', 'B14HK7', 'LU42N7', 'BC42E6', 'BV42E9', 'AG4262', 'B14HK5', 'KK4CC5', 'BF4FK2', 'BK42KX', 'BV42EX', 'BU4EE2', 'BK46K0', 'BF4FK7', 'BR42E2', 'BZ4HK2', 'BF4DV6', 'BE46K0', 'NX4CN9', 'DT4412', 'BR42E9', 'B14HK4', 'EG4261', 'DF4EV8', 'XX43G4', 'BF4FK9', 'BR40E8', 'BF4FK4', 'BK42K3', 'BF4FK1', 'EG4264', 'UU4EN4', 'ZK4DV2', 'BZ42E1', 'FK4180', 'BZ42E2', 'BR42E3', 'BK40K4', 'YK4DV8', 'XX43G8', 'BR40E7', 'XX43G5', 'EM4963', 'BB46K2', 'BZ4HK3', 'KT4K39', 'BF4FK5', 'XX42G5', 'BR42E5', 'XX43G2', 'DT4413', 'BC42E4', 'EZ4261', 'BU40E5', 'BF4DV3', 'BF4HK6', 'EG4260', 'JK4CC5', 'BF4DV9', 'BK40K8', 'KK4CC8', 'DF4EV5', 'DF4EV4', 'AG4261', 'KK4CCX', 'BU40E8', 'XX42G1', 'BV42E4', 'BE46K3', 'KK4CC1', '8242E7', 'B242E7', 'EM4260', 'DF4EV7', 'BK46K7', 'BB42E9', 'BR40E4', 'EG4263', 'BK40K9', 'EG4269', 'AG4266', 'BZ4HKO', 'B24HK6', 'A14CK3', 'BB42E1', 'BK42K0', 'DF4EV6', 'BC42EX', 'KK4CC7', 'AG4264', 'AM4960', 'BB42EX', 'BU4EE8', 'BU4EE9', 'YK4CC1', 'B24HK3', 'BF4FK6', 'AG4263', 'DF4EV1', 'B24HK4', 'DF4EV9', 'BB46K0', 'BB42E2', 'BB46K5', 'FG4265', 'NX4CN8', 'BK40KX', 'BB42E8', 'DB4A05', 'XX42G4', 'B14HK8', 'XX42G3', 'BC42E3', 'BF4HK4', 'KK4CC4', 'KK4CC0', 'BK40K3', 'BR42E8', 'FK4181', 'BU4EE5', 'UX42NX', 'XX42G6', 'BF4HKX', 'A14CK4', 'K440F1', 'BF4DV5', 'EZ4969', 'BR40EX', 'JT4K36', 'BU4EE6', 'BB46K1', 'B242E2', 'KZ4BX1', 'KU4EE7', 'DF4EVX', 'XX42G9', 'KZ4BX2', 'BU4BF2', 'EG4267', 'BU40E0', 'BL40E8', 'BF4DV4', 'BF4HK3', 'BU40E2', 'AG4CK5', 'BK42K6', 'AG4CK0', 'LU4ENX', 'BF4FK0', 'AG4268', 'AZ4966', 'A14CK5', 'AM496X', 'BK40K0', 'JF4DV5', 'BK4FK2', 'AG4CK3', 'B14HK0', 'BB42E7', 'YK4DV5', 'NG4268', 'XX43G6', 'BE46K1', 'A14CKX', 'AG4CK6', 'A14CK9', 'BK46K3', 'BK4DV4', 'BR40E6', 'JF4DV0', 'XX42G0', 'BU40E9', 'BK4FK1', 'YK4CC0', 'YK4CC5', 'NL42N7', 'BU40E4', 'A14CK0', 'BB46K9', 'NX4CN6', 'BL40E5', 'BF4HK5', 'NL42N6', 'BF4HK0', 'DT4417', 'XX42G8', 'B242E8', 'NL42N1', 'EM4261', '8V42E6', 'AG4265', 'BR40E3', 'BL40E2', 'BR40E2', 'B14HK9', 'DF4EV0', 'BB46KX', 'DF4DV7', 'XX42G7', 'A14CK2', 'DK4DV0', 'DB4C04', 'B14HK1', 'DK4CC9', 'B14HK6', 'AG4269', 'BT4414', 'DF4EV2', 'B14HKO', 'BF4DV8', 'DT4411', 'BL40E9', 'BU40E6', 'DK4DV6', 'A14CK6', '8C42E1', 'NX4CN4', 'AM4966', 'YF4DV7', 'J44AF1', 'BK4FK8', '0J4MCD', 'DB4C07', 'BK46KX', 'BK40K6', 'BK42K7', 'B24HK9', 'BB42E3', 'BK42K8', 'EG4268', 'EM4966', 'BR40E1', 'BU4BF8', 'BK42K5', 'YK4CC8', 'BE4EE1', 'YK4CC2', 'BF4DV1', 'DT4415', 'BK40K2', 'BL40E3', 'DB4A09', 'FY4184', '824HK7', '514884', 'AG4CK2', 'EM496X', 'BF46KX', 'KK4CC6', 'BB46K3', 'DT4814', 'AM4967', 'ZF4DV8', 'XX4262', 'FY4188', 'FK4185', 'DT481X', 'BB46K4', 'TX4CN0', 'B242E6', '8242E6', 'RK4DV4', 'MU4FNX', 'BE40K1', 'BF4HKO', 'AG4CK9', 'EM4269', '8V42EX', 'FY4185', 'DF4DVX', 'BU4BF0', 'BF4DV7', 'AG4CKO', 'NX4CN2', 'A14CK8', 'BK4FK3', 'UR4DA1', 'BU40E3', 'EM4969', 'YK4CC3', 'J440F4', 'AG426X', 'EM4964', 'RK4DV0', 'BT4K39', 'AM4964', 'DK4DV9', 'FY418X', 'BB42E5', 'B24HK1', 'B242E5', 'EM4965', 'EM4264', 'BK46K5', 'BB46K8', 'RK4DV5', 'BK46K6', '8K46K6', 'BK46K4', 'BU4BF9', 'MU4FN1', 'AG4CK4', 'BB46K6', 'BK4FK4', 'AM4963', 'MU4FN3', '8E46K7', 'DK4DV2', 'EM4268', 'BB46K7', 'AG4CK7', 'YK4DV6', 'BK4FK7', 'KZ4BX4', '8846K0', '8C42E7', 'EM4968', 'EG426X', 'FK418X', 'YK4DV3', 'FK4184', 'BK46K9', 'AG4CKX', 'RK4DVX', 'NL42N2', 'AG4CK8', 'BF4HKB', 'BU4BF6', 'DT4418', 'YF4EV3', 'BT4810', 'LU4EN4', 'DK4CC5', 'DB4A04', '8V42E9', 'BU4BF1', 'KT441X', 'PX4EN2', 'FK4182', 'NX4CN3', 'ZF4DV5', 'BT4417', 'AG4267', 'BE4EE0', 'EM4961', 'BF4HK9', 'B242E1', 'YK4CCX', 'DK4DV5', 'KF4DV3', 'BL40E6', 'AF4E31', '8U4EE6', 'ZF4DVX', 'EM4960', 'KK4CC9', 'FK4187', 'TX4CN5', 'BK4FKX', 'BU40EX', 'JT4K37', 'NL42NX', 'ZF4DV4', 'BL40EX', 'FK4188', 'BR40E5', 'YF4EV4', 'AG4260', 'BK4SK4', 'NX4CNX', 'FK4186', 'YK4CC9', 'ZF4DV7', 'BK4DV0', '8K46K0', 'KZ4BXX', 'NX4CN5', 'PX42N3', 'ZF4DV0', 'BR40E0', 'BU4BF7', 'AG4CKI', 'LU4EN9', 'DF4DV4', 'JT4K35', 'EZ4967', 'BK4FK9', 'EZ4963', 'BK42K4', 'EZ4962', '8242E8', 'BU40E1', 'AM4961', 'BF4DV2', 'BK42K1', 'BK4DV9', 'FM4185', 'ES46A1', '8F4HKX', 'EM4266', 'A64261', 'NG4269', 'WF4DV6', 'FM4189', 'BK4FK5', 'BK4DV3', 'B24HK8', 'BK46K8', 'DF4DV1', 'BU4BF4', 'BT4418', 'FK4189', 'RK4DV2', 'BK4FK6', 'TX4CN7', 'BT4411', 'DB4A08', 'NX4CN0', 'ZF4DV6', 'FM418X', 'MU4FN8', 'FY4181', '8U4EE4', 'DK4DV8', '8V42E8', 'BK46K2', 'J34AF2', 'DF4DV8', 'YF4DV9', 'BK46K1', 'NG4263', 'EZ4267', 'AZ4961', 'BL40E1', 'DT4414', '374185', 'DT4817', 'A14CKO', 'BT441X', 'DK4DV3', 'BF4DV0', 'XE4FS9', '8C42E5', 'JX4CN3', 'EW41A7', 'DB4A01', 'BL40E4', 'EZ4966', 'JK4DV3', 'RF4DV5', 'JT4K38', 'EG4258', 'DF4DV6', 'FY4189', 'BT4K31', 'KU40E3', 'BT4410', 'DS43A2', 'UU4EN3', 'NG4262', 'LU42N2', 'AM4969', 'XX43GI', 'KT4K31', 'UU4EN0', 'EG4262', '8F4HK7', 'FK4183', 'KT4K35', 'BT4416', 'DF4DV9', 'PX4EN3', 'KU4EE8', 'PX4EN6', 'DT4410', 'BE40K2', 'AM4962', 'DK4DV4', 'NL42N8', 'JK4CC3', '8V42E0', 'B242E9', 'DK4DV7', '824HK5', 'WK4DVX', 'KT4K36', 'BV42ES', 'FM4184', 'BU4EET', 'DK4DVX', 'DF4DV0', 'NL42N9', '8U40E6', '8J4665', 'XX4367', 'BE42J8', 'ZF4DV1', 'DK4DV1', 'BT4K36', 'C74C40', 'DF4DV2', '8U4EE7', 'EZ4269', 'BE42KB', 'EM4267', '8K40K6', 'EW44A6', 'EM4263', '8U4EEX', 'YK4CC7', 'RF4DVX', 'ZF4DV9', 'BT48A9', 'BE42KO', 'MU4FN5', 'JT4K33', '8C42E8', 'LU4EN7', 'A64264', 'BL40E7', 'XK4DV4', 'TU4GN7', 'FY4183', '814HK4', 'FY4186', 'EZ4960', 'RK4DV3', 'XX4266', 'EC42E3', 'WF4DVX', '8V42E4', 'JU4GN1', '804733', 'DF4DV3', 'KT4K38', 'ZF4DV2', 'UU42NX', 'EM4265', 'RV42E5', '8V42E2', 'TX4CNX', 'BZ4ZEX', 'RK4DV1', 'FM4187', 'FY4182', 'K440F2', 'DB4C03', 'EG4266', 'J44AF0', 'BT4817', 'J34AF6', '8V42E7', 'YK4DV4', 'RF4DV7', 'J34AF7', 'DS41A0', '8242E4', 'DT4813', 'YK4DV7', 'KU40E4', 'BU4BF5', 'DB4A03', 'BF4HKC', 'RF4DV6', 'EE4263', 'XX42GO', 'FM4182', 'BT4814', 'YF4DV2', 'KC4BS8', 'BV42EI', 'XX4366', 'BT48A7', 'EM4967', 'NG4265', 'BT4K38', 'EZ42E9', '824HK6', '8R42E5', 'BL42E6', 'BK4DV1', 'D541A0', 'ES41A2', 'FM4183', 'A14CKB', 'EW44A1', 'EZ4964', 'AM4965', '804307', 'JX4CN1', 'BE40K3', 'AZ4964', 'XX4264', 'NX4CN1', 'YF4EV8', 'NL42N5', '8E42K5', '8C42E0', 'FM4188', 'YK4CC4', '8F4FKX', 'NG426X', 'DT4816', 'BT4819', 'BT4812', 'XX4362', 'ZE4FE1', 'TX4CN4', 'BT4412', 'BT4K34', 'KZ4DX1', '8F4HK9', 'BF4FKO', '464054', 'DT4815', 'ZF4CBX', 'BK4DV5', 'BT44A4', 'DB4A0X', 'AZ496X', 'FM4181', 'PX4EN0', '8E42KX', '8F4DV0', 'RK4DV8', 'AS47HB', '8E46K2', 'LU4EN2', 'XX4360', 'J34AFX', 'EE4261', 'JT4K30', '8C42EX', 'JK4CC4', 'BE42KS', 'XE4FSX', '804134', 'RF4DV3', 'DK4CC2', 'KT4K30', 'DB41S7', 'NL42N3', 'NG4260', 'DT4819', 'KT4410', 'GU4L3X', 'ER42E2', 'KK4DV3', 'JF4DVX', 'BT4818', 'EZ4968', 'J34AFI', 'J34AF1', 'WF4DV9', 'BT4K32', 'DB4A07', 'XX4369', '464703', 'BR43E9', 'BE4GK3', 'JT4K34', 'BZ42EZ', 'AI4CK5', 'AM4501', 'BU4BFX', 'DF4EVO', 'TX4CN2', 'AM4981', 'EE4260', 'NL42N4', 'EM4962', 'DB4A06', '8E42K3', 'BK4DV8', 'K440F8', 'JX4GN3', 'KT4217', 'BT4415', '8Z4HK3', 'DE4EV6', 'EM4262', '8E42K0', 'NX4CN7', '8C42E9', 'UX4ENX', 'KZ4BXO', 'BN4414', 'PX4ENX', 'BU4BF3', 'UU4EN1', 'DT4419', 'EW44A3', '8E42K1', 'LU4EN1', 'LU42N5', 'BE42KT', 'BU4EEJ', 'JF4DV7', 'BT4K3X', 'BT4413', '8C42E6', '944032', 'YF4EV5', 'W74U33', 'KF4DVX', 'FY4180', 'ES43A6', 'NG4266', 'TX4CN1', '8E46K6', 'BT44A2', '814HK8', 'BT4811', 'YF4DVX', 'ZU4BF5', 'WF4DV7', 'WJ4W96', '004046', '8V42E5', 'EZ496X', 'RK4DV7', '8242E3', 'YF4DV1', 'TX4CN6', 'FM4180', '504705', '824HKX', '8E46K3', 'AZ4965', 'BT4K30', 'K440F5', 'RK4DV6', '8U4EE9', 'RD4830', '8U4EE2', 'JK4CC1', '8242E1', 'DK4CC1', 'AG426U', '8E46K0', 'KU4HN3', '8E46K9', 'DF4EB5', 'XX4263', '8242E9', 'BT48A0', 'BV42EO', 'KU4EE5', '8R42E2', 'YK4DVX', 'UU4EN5', 'G14DAO', 'KU40EX', 'B242E0', '534K20', 'B242E3', 'BV4260', 'XX42GB', 'ZK4CCX', 'XX4308', 'DB4A00', 'LU42NX', 'EZ4965', '8K4FK9', 'A14AFX', 'KF4DV6', 'UU4ENG', 'BT4K35', 'NG4264', 'EM42G3', '8Z4HK2', 'XX436X', '8842E9', 'TX4CN8', 'BU4EES', 'LU4EN0', 'KF4DV1', 'EM426X', 'WF4CB8', 'MU4FN9', 'FF41CB', 'FM4186', 'PX42N5', '8E46KX', 'BZ42F1', '824HK2', 'AZ4968', '514263', 'BE40E8', 'NE4261', 'WF4DV8', 'BR4068', 'RF4DV0', 'MU4FN7', '8242EX', 'RK4DV9', 'BT481X', '8V42E1', 'UU4EN6', 'DK4CC0', '8E42K6', '804598', '124022', '8842E4', '8C42E3', '464753', 'CP4500', 'EZ4961', 'JK4CC2', '8846K5', 'BT4813', 'PX4EN8', 'FV47V6', 'EF4HKD', 'UU42N1', 'GF4JB6', '814HKX', 'PX4EN5', 'XX426X', 'PV42E2', 'AZ4967', 'GR4A69', 'KT4418', 'BE44K1', 'BE42KZ', 'WF4DV2', 'EC42E5', 'AF4E34', '8E42K8', 'DF4EUX', 'TX4CN9', 'DT4812', 'UK42AE', 'UN41B9', '804646', 'LU42N6', 'XK4DV3', 'AZ4963', 'DF4DV5', '824HK3', 'PX42N2', '8F4FK8', 'YF4DV5', 'DB4C00', 'DB4C08', 'RF4DV1', 'MU4FN2', 'KF4DV5', 'PX42N4', 'AF4E36', 'BT48A4', 'BC42EB', 'BT44A9', '8K40K3', '8E42K9', 'BT4815', 'KF4DV8', 'NL42N0', '3546FG', 'ZE4FE7', '514528', 'BC42R5', '8E42K7', 'H545G5', 'AZ4969', 'JF4DV1', 'DH4CDX', 'GF46X1', 'BT4K33', 'WK4DV1', 'AZ4960', 'DK4CC4', 'AF4CB8', 'UU4ENX', 'WF4JB1', '814HK5', 'KU40E7', 'LU42N9', 'CC42H9', 'ZE4FEX', 'YK4DV1', 'JK4CC0', 'YK4CCB', 'DB4A02', 'BK4DV2', 'A64265', 'BE40E4', '804077', 'JF4DV3', 'DT4810', 'EZ4262', 'JK4DV0', 'LU4EN8', 'BZ4HKS', 'BK4DV7', 'DT4811', 'J34AF8', 'DK4CC3', '464072', 'PX4EN4', 'XX4364', '8842E6', '8842E8', 'UX4EN5', 'DT441X', '8242E0', 'BZ4HKB', 'ES43A8', '8E42K4', 'XX48G8', 'BL42E1', 'EW44A8', 'JF4DV6', 'YF4DV0', 'UU42N9', 'NG4267', 'BE40EX', 'MU4FN6', 'T147Y6', 'K440F4', 'DK4CC6', 'BH42K5', 'BC42EJ', 'XX4303', 'ER42E9', 'LU4EN3', 'BU4EED', 'EE4269', 'TX4CN3', 'A64266', '8U4EE5', 'KU4EE9', '8842EX', '8F4HK0', 'PX4EN7', 'BT4K37', '954033', '8E42K2', '8U40E4', '8V42E3', '8U4EE0', 'BF4DVS', 'B046K9', 'LU4EN5', '954032', 'BK4FKO', '504797', 'XX4361', 'BN4416', 'YK4DV9', 'BH42K2', 'UX4EN2']
  Model_Year: ['A', 'R', 'X', '8', '9', '7', 'D', '6', 'J', 'B', 'K', 'M', 'C', 'P', 'E', 'F', '3', 'S', 'L', '5', 'N', 'H', '2', '1', 'Y', '4', 'G', 'T', 'W']
  Plant_Code: ['7', '3', '0', 'X', 'J', '4', 'Z', '9', 'D', 'W', 'S', 'C', 'R', 'U', 'P', '2', '8', '5', 'K', 'M', 'G', '1', 'A', 'V', 'L', 'B', '6', 'F', 'H', 'T']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,RKL,BZ42E7,A,7,502840
1,TOYOTA,CAMRY,6.0,SEDAN,B,SE+ ANNIVERSARY EDITION,GCC,4.0,JTN,BZ4HK6,R,3,035774
2,TOYOTA,COASTER,6.0,BUS,F,STD,GCC,2.0,JTC,FZ4182,X,0,005419
3,TOYOTA,CAMRY,4.0,SEDAN,B,GLX,GCC,4.0,6T1,BE42K7,8,X,485384
4,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,JTD,BR42E6,9,J,007251
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39712,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,GLI,GCC,NaN,6T1,BE42K1,B,X,679514
39713,TOYOTA,CAMRY HYBRID,4.0,SEDAN,B,SE,GCC,NaN,JTN,BF4HK6,J,3,014100
39714,TOYOTA,CAMRY HYBRID,4.0,SEDAN,A,XLE,GCC,NaN,JTN,A14CK5,S,3,029562
39715,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK2,R,3,034380
39716,TOYOTA,CAMRY HYBRID,6.0,SEDAN,B,SPORT,GCC,NaN,JTN,BZ4HK1,P,3,026798

====================================================================================================
pos6: 6
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'XA', 'SEQUOIA', 'FORTUNER', 'YARIS', 'RAV 4', 'FJ CRUISER', 'HIACE', 'LAND CRUISER', '2009', 'WISH', 'TACOMA', 'CAMRY', 'COROLLA', 'HAI LUX', 'COASTER', 'هاي لوكس', 'PREVIA', 'TUNDRA', 'TAKOMA', 'LAND CRUISER PICK UP', '86', 'ECHO', 'RAV4', 'هايلوكس', 'SIENNA', 'PRADO', 'PARISIENNE BROUGHAM', 'AVANZA']
  bodyType: ['PICK UP DOUBLE CAB', 'HATCHBACK', 'SUV', 'PICK UP SINGLE CAB', 'PICKUP', 'MINI BUS', 'PANEL VAN', 'MINI BUS HIGH ROOF', 'SEDAN', 'STATION', 'CARGO VAN', 'PICK UP', 'TRUCK', 'PICK UP DOUBLE CABIN', 'BUS', 'MPV', 'PICKUP DOUBLE CABIN', 'COUPE', 'SALOON']
  pos4: ['C', 'K', 'B', 'D', 'Z', '1', '2', '5', 'J', 'F', 'P', 'Y', 'N', '6', 'U', '0', '8', 'E', 'T', '9', 'V', 'A', '4']
  trim: ['GL', 'BASE', 'SR5 4X4', 'LIMITED MID', 'GXR', 'DLX', 'LIMITED 4X4', 'TOP', 'LIMITED 4X2', 'VXR', 'SR5 4X2', 'SE', 'PLATINUM', 'DX', 'DL', 'SPORT', 'EXR', 'SR5', 'DLS - STD ROOF', 'DLS', 'STD (NON GCC)', 'XLI', 'S ASF', 'STD', 'G', 'GG', 'XLI MID', '4WD', 'GLX', 'MID', 'GRANDE', 'LIMITED TOP', 'S', 'GLI', 'A', 'GL LIMITED', 'GLS', 'TX', 'LIMITED', 'XLE (NON GCC)', 'SE+', 'TX-L', 'LE (NON GCC)', 'PICK', '1', 'TRD']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['MR0', 'JTD', '5TD', 'JTF', 'MHF', 'JT4', 'MR2', 'ANE', 'ZGE', 'JN6', 'JWT', 'STD', 'JT3', '4TA', 'MRO', 'JND', '5TE', 'MR1', 'KLA', 'JTK', 'WDB', 'ZE1', '5TF', '6TD', 'UP1', 'KMH', 'NV1', 'RK4', 'KL1', 'STO', 'JNK', 'JN1', 'WMA', 'LSJ', '5T0', '1G2', 'SAL', 'GGG', 'GX9']
  VDS: ['CW6CB9', 'KT6235', 'BY64A6', 'BY64A7', 'CW6CD1', 'BY68A5', 'BY64A3', 'CX6CB3', 'KT6234', 'DM6264', 'KT6239', 'BY68A8', 'BY68A7', 'BY64AX', 'ZX69G8', 'KT6236', 'KZ6265', 'KT6233', 'BY64A1', 'KM6261', 'DX6CDX', 'BY64A4', 'ZY68A4', 'CX6CBX', 'KT6231', 'BY68A9', 'DX6CD9', 'BY67AX', 'KX6CB1', 'KT6237', 'BW6F35', 'BY68A3', 'BY68A6', 'BY64A5', 'BY64A8', 'BY68A1', '116000', 'BY64A2', 'CX6CD9', 'CX6CB4', 'CX6CD8', 'BY68A0', '216106', 'BE6DS9', 'CX6CB7', '596950', 'KT6232', 'KM6262', 'BY68A4', 'CX6CDX', 'CW6CB5', 'JX6CB8', 'ZY67AX', 'CW6CD6', 'ZX69G7', 'BE6BS3', 'ZY64A9', 'ZX69G3', 'KX6CB2', 'BY64A9', 'KT623X', 'CW6CB7', 'CW6CB3', 'BW6F36', 'BE6BS4', 'BE6BS8', 'CW6CB1', 'KX6CB4', 'JX6CB4', 'BW6F31', 'ZY68A2', 'KT6230', 'JX6CD6', 'BY68AX', 'JX6CB2', 'ZY68A1', 'CX6CB6', 'CW6CD8', 'BY64A0', 'FJ60G2', 'KX6CB6', 'PM62NX', 'BY68A2', 'BY67A6', 'ZY64A6', 'DM6262', 'YX69GX', 'FJ60G4', 'BE6BS9', 'KT6238', 'CX6CB0', 'CW6CB4', 'DX6CD6', 'ZX69G6', 'CX6CD6', 'BE6AS2', 'JX6BB0', 'JB6CD8', 'BE6BS6', 'ZY68A9', 'ZY67A5', 'CX6CD2', 'DX6CD8', 'KX6CB3', 'ZX69G4', 'JX6CB9', 'DX6CD2', 'KX6CB7', 'BW6F32', 'BW6F3X', 'CX6CD4', 'DM6261', 'BY67A4', 'CW6CD3', 'CX6CD0', 'JX6CB3', 'DZ6266', 'DM6266', 'ZX69G1', 'JX6CD1', 'CW6CD5', 'KZ6268', 'ZY64A2', 'BY67A3', 'BE6DS4', 'ZY67A8', 'FJ60G5', 'CW6CD0', 'ZY67A9', 'CW6C88', '216049', 'CW6CB8', 'CW6CDO', 'ZY68A7', 'ZX69G9', 'BE6DSX', 'CX6CB1', 'PM62N2', 'CX6CD5', 'PA69JD', 'BE6DS6', 'ZX69GX', 'DB6CD5', '216067', 'PM62N7', 'CX6CD7', 'BW6F38', 'BW6F33', 'DE6261', 'JX6CDX', 'ZY67A7', 'JX6CD4', 'JX6BB5', 'KT624X', 'CX6CD1', 'KX6CBX', 'ZY64A5', 'JX6BB6', 'DX6CD3', 'PM62N3', 'NX62N0', 'BW6F30', 'DZ6262', 'DE626X', 'KX6CB5', 'CW6CD2', 'ZY68AX', 'CX6CB9', 'BF6C3X', 'ZX69G0', 'DE6269', 'CX6CD3', 'BE6CS7', 'CW6CB0', 'BY67A5', 'DM6268', 'KZ6264', 'CW6CB6', 'DB6CD2', 'ZX69G2', 'CW6CD7', 'DM6265', 'BE6BSX', '656205', 'BE6DS2', 'BT64A1', 'KX6CB8', 'DM6263', 'BY67A7', 'JX6CD2', '2Y68A4', '506028', 'KT6249', 'BE6AS5', 'UY6F14', 'ZY68A0', 'ZY64A0', '216041', 'KZ6262', 'DX6CD4', 'DM6260', 'JU62N9', 'JX6CD7', 'DX6CD7', 'BE6DS3', 'KX6CB9', 'BY67A0', 'CW6CB2', 'DM6269', 'BE6DS5', 'CX6CB2', 'DZ6260', 'JX6CB6', '516117', '006121', 'CW6CD9', 'ZY68A8', 'BE6DS7', 'PM62N1', 'KX6CB0', 'DG61E8', 'KZ6263', 'JX6CD0', 'CX6CB8', 'ZY64A3', '806367', 'BE6BS2', 'KT6242', '8Y64A2', 'BY67A8', '656516', '2Y64AX', 'DX6CD0', '516227', 'CJ6B15', 'JX6CD8', 'DX6CD5', 'CW6CBX', 'BY64AB', 'BE6DS0', 'CW6C86', '8Y64A5', 'BE6BS7', 'JX6CB7', 'JX6CD9', 'BV61E5', 'EN61S2', 'BE6DS8', 'KZ6260', 'BE6DS1', 'T36ZZZ', 'PM62N4', '906155', 'EY64A4', 'DX6CD1', 'JX6BB2', 'JX6CB0', 'DZ626X', 'DZ6269', 'DZ6263', '506377', 'PM62N8', 'JX6CD3', 'ZY68A5', 'ZY68A3', 'ZX69G5', 'BW6F39', 'VN61F2', 'FJ60G0', 'KZ6266', 'BY67A1', 'BY67A9', 'TU62N8', 'ZY64AX', 'A16E36', 'CW6CDX', 'DM626X', 'ZY68A6', '216035', '216086', 'ZY64A7', '216088', 'BE6BS5', '656109', 'CW6CBO', 'DX6CBX', 'DX6CDO', 'KM6260', 'KM6268', '216081', '516804', '506174', '506713', 'FJ60G8', '216054', 'BW6F34', 'ZY67A4', 'CW6CD4', 'BT69Y4', 'EA6BX2', 'PM62N5', 'JX6BB7', '516589', 'BY67A2', '216087', 'BE6AS6', 'PM62N0', 'KT6245', 'JX6CBX', 'DM6267', 'FJ60GX', 'JU62NX', 'JX6CB5', 'PN62N5', '216023', 'BY68AS', 'KT6045', 'ZY64A8', 'ZY67A0', '8Y64A4', 'JX6BB8', 'ZY67A2', '456123', 'FJ60V8', 'KM6269', '066223', 'KZ626X', 'JB6CB4', 'KT6041']
  Model_Year: ['G', '6', 'C', 'B', 'F', '4', '3', '5', 'A', 'E', '8', '7', 'X', '9', 'D', 'M', 'H', 'Y', '2', 'P', '1', 'K', 'R', 'W', 'S', 'V']
  Plant_Code: ['0', 'S', '7', '5', '1', '6', '9', '2', 'Z', '3', '8', '4', 'B', 'K', 'X', 'U', 'C', 'M', 'W', 'N', 'G']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,GL,GCC,4.0,MR0,CW6CB9,G,0,001803
1,TOYOTA,XA,4.0,HATCHBACK,K,BASE,GCC,5.0,JTD,KT6235,6,0,135364
2,TOYOTA,SEQUOIA,8.0,SUV,B,SR5 4X4,GCC,5.0,5TD,BY64A6,C,S,070272
3,TOYOTA,SEQUOIA,8.0,SUV,B,SR5 4X4,GCC,5.0,5TD,BY64A7,B,S,048456
4,TOYOTA,SEQUOIA,8.0,SUV,B,SR5 4X4,GCC,5.0,5TD,BY64A7,C,S,067350
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2156,TOYOTA,XA,4.0,HATCHBACK,K,BASE,GCC,NaN,JTD,KT623X,7,0,168653
2157,TOYOTA,SEQUOIA,8.0,SUV,B,LIMITED 4X4,GCC,NaN,5TD,BY68A4,A,S,034183
2158,TOYOTA,SEQUOIA,8.0,SUV,B,SR5 4X2,GCC,NaN,5TD,BY67A3,A,S,031129
2159,TOYOTA,SEQUOIA,8.0,SUV,B,SR5 4X4,GCC,NaN,5TD,BY67A2,B,S,044066
2160,TOYOTA,SEQUOIA,8.0,SUV,B,LIMITED MID,GCC,NaN,5TD,BY68A4,C,S,057367

====================================================================================================
pos6: 5
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TUNDRA', 'FORTUNER', 'AVANZA', 'SEQUOIA', 'PREVIA', 'TACOMA', '4RUNNER', 'RAV4', 'COASTER', 'RAV 4', 'ZELAS', 'TERCEL', 'HIACE', 'SCION', '4 RUNNER', 'HILUX', 'COROLLA', 'LAND CRUISER', 'CAMRY', 'COROLLA SEDAN', 'AVALON', 'STATION', 'PRADO', 'TAKOMA', 'حافلة نقل خاص', 'TOYOTA 4RUNNER', 'C-HR', 'TOYOTA', 'VESPA VXL 150', 'VESPA VXL', 'TANDRA', 'TUNDRA (PICK UP)', 'HILUX ADVENTURE', 'FJ CRUISER']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'MPV', 'BUS', 'STATION', 'COUPE', 'PICK UP SINGLE CAB', 'SEDAN', 'PANEL VAN', 'MINI BUS', 'PICK UP', 'CARAVAN', 'HATCHBACK', 'PANEL VAN HIGH ROOF', 'PICKUP', 'SALOON', 'MOTORCYCLE', 'VAN']
  pos4: ['M', 'Y', 'K', 'D', 'A', 'G', 'U', 'E', 'C', 'B', 'H', 'N', 'P', 'R', 'F', 'J', 'W', 'L', '2', 'S', 'V', 'Z', '4', '6', '8', '1', '5', 'T']
  trim: ['STD (NON GCC)', 'GXR', 'SR5', 'SE', 'TOP', 'SR5 (NON GCC)', 'DLX', 'GL', 'LIMITED', 'EXR', 'CREWMAX CAPSTONE (NON GCC)', 'EX', 'S', '1794 EDITION (NON GCC)', 'LWB', 'LE HEV', 'T', 'SWB', 'SR', 'MID', 'STD', 'DX', '1', 'TRD', 'CTD', 'SPORT', 'GLS', 'DL', 'XLI', 'TRD OFF-ROAD', 'SR (NON GCC)', 'LE', 'GLX', 'GXR TOP', 'TC (NON GCC)', 'PLATINUM', 'LWB HIGH ROOF', 'FABRIC', 'BUS', 'SR5 4X2', 'DLS', 'TRD SPORT', 'STAN', 'LIMITED 4X4', 'SR5 4X4', 'XLI TOP', 'GLI', 'ADVENTURE', 'A', 'VX', 'GLE', 'LIMITED MID', 'GF', 'STD CARGO', 'GRANDE', 'BASE', 'STANDARD', 'PICK UP', 'E', 'XLI MID', 'G', 'PLATINUM LUXURY 4X4', 'NON GCC', 'COASTER', 'EXCLUSIVE', 'GLE HEV', 'GXR GT', 'LS', 'TRIM', 'GL LTH', 'ST', 'SE+', 'XLE', '1500', 'HYBRID (NON GCC)', '1794 EDITION (NON GC', 'CREWMAX CAPSTONE (NO']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TF', 'MHF', 'MHK', 'MR1', '5TD', 'JTN', 'JTE', '3TM', '5TB', 'STB', 'STF', 'JTG', 'SJK', 'LFM', '3TY', 'LVG', 'JTK', 'MHE', '4TA', 'JT2', 'D04', 'JN6', 'RP8', '5TE', 'ACV', 'MET', 'JT6', 'ITN', 'JT4', 'CLG', 'WDB', 'MLH', 'IG1', 'MRI', 'JTL', 'JTH', '6T1', 'WYU', 'WCY', 'MMC', 'LCO', 'NV1', 'KLI', '5T8', 'LSG', '1G6', 'RKM', 'WMA', 'ZE1', '5NF', 'WBA', '1G1', 'VF3', 'IN6', 'STY', 'MAF', 'JHM', 'ZCF', 'AVV', 'MR0', '6TF']
  VDS: ['MV5215', 'YU59G6', 'YX59G9', 'MF53F3', 'YX59G2', 'KY5F19', 'DY5G1X', 'AY5F17', 'YU59G2', 'DW5F14', 'YU59G7', 'KY5F16', 'GE52M3', 'UY5F12', 'AW5F13', 'YU59G0', 'YU59GX', 'GE52M7', 'YX59G3', 'DY5F14', 'GD52M9', 'DV5415', 'UY5F14', 'YX59GX', 'EW5F19', 'CZ5AN5', 'UY5F18', 'DY5F15', 'BU5JR8', 'YX59G8', 'AY5F19', 'AY5F11', 'AY5F14', 'HW5F15', 'UW5F17', 'KB5DB5', 'HW5F10', 'DY5F16', 'MF53F1', 'AW5F11', 'BV5416', 'CZ5AN1', 'GE52M0', 'DY5F13', 'MF5CF1', 'KY5F17', 'YX59G1', 'YX59G0', 'HY5F17', 'DZ5BN6', 'GD52M2', 'KY5F1X', 'BV5412', 'BU5JR0', 'YX59G6', 'DY5F12', 'DV5419', 'MF5BF7', 'DZ5BN2', 'YU59G9', 'AY5F1X', 'MF53F8', 'UY5F15', 'DW5F1X', 'BV5410', 'BV5417', 'KV5212', 'GD52M8', 'GE52M6', 'GE52MX', 'MF53F4', 'YX59G4', 'HY5F10', 'DM5F11', 'BU5JR2', 'GD52M4', 'GD54M8', 'UY5F13', 'DV5416', 'NC5DBX', 'MF52F5', 'PY5F19', 'MF53F5', 'MF5BF4', 'DY5F10', 'MF53F9', 'YU59G5', 'GE52M5', 'GE52M2', 'YU59G3', 'DV5815', 'DY5F17', 'YX59G7', 'GD54M6', 'KY5F13', 'KV5210', 'RY5F14', 'AW5F16', 'UW5F1X', 'DV5412', 'GD54M9', 'FK5188', 'CH5CP0', 'KN5BF7', 'GD52MX', 'MF5BF5', 'UY5F11', 'DZ5BNX', 'MF52F0', 'MF53F2', 'UY5F1X', 'MF52F2', 'BV5818', 'GD54M1', 'D156F5', 'MF53F7', 'MF5CF3', 'JA5ABX', 'UM5F16', 'DW5F12', 'AW5F19', 'GE52M4', 'FB5188', 'GE52M1', 'MF5CF2', 'WA5DB2', 'GE52M8', 'KY5F18', 'JF5C71', 'YU59G8', 'AY5F10', 'YU59G1', 'GD54M5', 'DV5816', 'KY5F14', 'UY5F10', 'CZ5AN4', 'HY5F19', 'DY5F18', 'AY5F18', 'BV5819', 'LA5DB6', 'UW5F11', 'RW5F14', 'BU5JR4', 'KY5F10', 'FB5185', 'BV5419', 'GD52M6', 'MF5CF9', 'CY5F16', 'LA5AB6', 'UW5F12', 'UN53B2', 'DY5F1X', 'FK5181', 'JU5213', 'DW5F11', 'KT5219', 'BJ53L8', 'RM5F18', 'GW5F18', '2757DX', 'DW5G1X', 'NY5F12', 'AY5F16', 'YY5G1X', 'AE54S5', 'RY5F13', 'GE52M9', 'CZ5AN8', 'DY5F19', 'GD52M0', 'BV5814', 'SZ5AN1', 'MF53F0', 'YU59G4', 'LA5AB4', 'MF5BFX', 'JF5C7X', 'MF5CF5', 'MF53F6', 'BU5JR9', 'DV541X', 'FM5189', 'MF5BF3', 'BJ53L2', 'DV5417', 'PC5DB9', 'YX59G5', 'RY5F1X', 'FB5181', 'GD54MX', 'MC5DB6', 'HY5F18', 'UM5F19', 'RM5F14', 'UM5F15', 'JA5DB5', 'DW5F17', 'MF5CF4', 'BW5F17', 'UW5F10', 'RU5JR9', 'JF5C77', 'SX5EN1', 'FK518X', 'MF5BF9', 'FY5F13', 'MA5EC2', 'FK5187', 'BJ53LX', 'MF52F4', 'GD52M3', 'DW5F18', 'JF5C74', 'AE52SX', 'AY5F13', 'NC5DB9', 'JA5EC1', 'BV5414', 'FB5187', 'BY5F17', 'MF52F8', 'BY5F12', 'MF5CF7', 'HY5F14', 'MC5DB8', 'AY5F15', 'RV5417', 'JC5DB7', 'KV5213', 'BV5418', 'HW5F13', 'BV5415', 'HY5F13', 'DV5818', 'BY5F13', 'DW5F16', 'DW5F13', 'FK5186', 'AW5F1X', 'HY5F11', 'DW5417', 'RX5GN2', 'UW5F18', 'AY5F12', 'HW5F1X', 'UY5F19', 'BV5411', 'RM5F15', 'PW5F13', 'JF5C78', 'AW5F12', 'JY5F13', 'MF5CFX', 'JF5C75', 'KV5215', 'MF5BF2', 'LA5DB5', 'MF53FO', 'DY5F11', 'BU5JR3', 'FK5180', 'MF5CF0', 'FK5185', 'DZ5BN9', 'MC5DB4', 'YX5968', 'BW5F18', 'DW5F15', 'GD52M1', 'BY5F11', 'RX5GNX', 'UY5F17', 'M45711', 'VA5BR3', 'HW5F16', 'MF5BF0', 'GY5F17', 'JA5DB8', 'DV5817', 'MF5BF1', 'VC5DB8', 'ZU5JR7', 'RY5F16', 'ZU5JR4', 'UW5F14', 'GZ5AN4', 'EV5418', 'BV541X', 'HW5F14', 'RY5F12', 'BY5F1X', 'LA5GD0', 'HY5F15', 'KU5BF6', 'HW5F18', 'DV581X', 'KU5BF5', 'RM5F12', 'GD54M7', 'FK5189', 'GD54M0', 'UW5F19', 'KV5211', 'LU5212', 'JF5C79', 'JF5C76', 'HY5F16', 'BV5413', 'MV5219', 'EW5F15', 'KY5F11', 'YU5965', 'GW5F14', 'HJ59J1', 'GE52MO', 'DV5813', 'BY5F15', 'DW5F10', 'BU5JRX', 'HW5F11', 'KV5217', 'GD54M3', 'BW5F11', 'JA5DB7', 'MY5F13', 'KV521X', 'HW5F19', 'UY5F16', 'GY5F18', 'MF53FX', 'BW5G18', 'DV5811', 'FB5182', 'UW5F15', 'EY5F11', 'RT5412', 'MF5CF6', 'BJ53L4', 'JF5C70', 'FK5182', 'FK5183', 'FB5183', 'KV5214', 'AW5F17', 'HY5F12', 'CZ5AN3', 'KN5BFX', 'FM5182', 'DV5810', 'EY5F1X', 'RT5416', 'BW5418', 'KT5218', 'MF52F7', 'RX5GN7', 'GD54M4', 'DW5F19', 'GD52M7', 'RM5F19', 'DV5418', 'DZ5BN4', 'BT5410', 'FB518X', 'BU5JR7', 'GS54M3', 'BW5412', 'KW5F16', 'AW5F15', 'MF52F3', 'FM5188', 'FM5183', 'FE52S4', 'BT5418', 'YY5G18', 'PC5DB8', 'BW5F16', 'BT5816', 'MF52F9', 'KY5G18', 'GS54M0', 'UM5F12', 'RV5415', 'ZY5G17', 'MF5CF8', 'VL52N2', 'KT5212', 'AE52S1', '415020', 'LA5DB0', 'JA5DBX', 'LA5DB3', 'DW541X', 'AW5F18', 'FB5184', 'LA5DA2', 'AZ5CN7', 'RU5JR7', 'BJ53L9', 'FY5B18', 'GD52M5', 'MF5BF6', 'VL52NX', 'GS54M5', 'KD5HN5', '6E52M1', 'LA5DB4', 'GD54M2', 'JY5G15', 'KN5BF2', 'MF52FX', 'JA5DA3', 'M85002', 'M85007', 'LC5LN2', 'KT521X', 'JC5ECX', 'UM5F17', 'KY5F15', 'RV5413', 'LU5218', 'FE53S5', 'KM5F15', 'RM5F17', 'FM5187', '6E52M0', 'CZ5AN9', 'RN50R2', 'WA5EC3', 'KB5DA2', 'DW5413', 'JW5G11', '855HZK', 'MF5CFO', 'YY5G15', 'WA5DB1', 'ZU5JR3', 'BY5G14', 'JV5217', 'JV5214', 'PC5DB0', 'PY5F17', 'LB5JN8', 'BW5G15', 'RX5GN6', 'BV5810', 'KY5G1X', '655532', 'UM5F13', 'FB5180', 'RV5814', 'CZ5AN7', 'KU5JR3', 'BV5813', 'ZU5JR9', 'CV5414', 'AW5F10', 'RU5410', 'ZY5G19', 'MC5DB5', 'PC5691', 'MV5214', 'SZ5ANX', 'CZ5AN6', 'KY5F12', 'BY5G10', 'JF5C72', 'EV5415', 'AE52S6', 'AE5256', 'RV5418', '145839', 'DV5413', 'BV5816', 'BT5416', '515001', 'CZ5ANX', 'PY5F11', 'SV541X', 'BV581X', 'BV5812', 'JA5EC5', 'BT541X', 'MC5DB1', 'UW5F13', 'ZU5JR0', 'NC5DB0', 'LA5BC7', 'BV5811', 'YU5963', 'DV5414', 'YU5967', 'JY5G1X', 'MF52F6', 'AZ5CN2', 'KY5G16', 'KN5BF0', 'FK5184', 'GS54M1', 'UU5JRX', 'CV5412', 'JY5G16', 'KW5F11', 'BY5F19', 'BY5G19', 'JW5G1X', 'MV521X', 'MV5212', 'CY5F14', 'BY5G13', 'MA5DB9', 'BY5G12', 'EY5F16', 'LU521X', 'ZU5JR6', 'MU52N0', 'DW5G10', 'KE50E2', 'KB5DA7', 'AE51S4', '6D52M5', 'PY5F13', 'DZ5BN1', 'VC5DB7', 'M85004', 'VL52N6', 'FB5186', 'KT5217', 'RZ5CN0', 'NA5DB3', 'DY5G14', 'EV5411', 'YX59C7', 'BF5C29', 'DY5G10', 'PW5F10', '535K20', '145457', 'U45454', 'AE54S0', 'LM5F10', 'FY5F12', 'FU5JR5', 'LA5DA8', 'LA5DB1', 'HW5F17', 'M85008', 'HT5236', 'BU5JR5', 'AE54S7', 'HU5JR1', 'KW5F18', 'EY5F12', 'RY5F19', 'WA5DB0', 'LU5JR8', 'MT5215', 'JV5210', 'PY5F16', 'BT5411', 'DW5G19', 'UW5F16', 'BW5F1X', 'M8500X', 'NY5F14', 'UM5F18', 'LU5F16', 'FE54S4', 'LB5JN2', 'JC5DB5', 'FM5181', 'CZ5ANO', 'CZ5AN0', 'AE53S2', 'GS54M6', 'MF53FI', 'BJ53L1', 'VC5DB1', 'ZY5G1X', 'YX5966', 'AW5F14', 'MA5DB8', 'DV5819', 'YX5960', 'UM5F11', 'BU5JR6', 'MU52N8', 'KM5F10', 'HY5F1X', 'JU5212', 'TW5F16', 'EJ5CDX', '805931', 'DZ5BN0', 'GY5F19', 'BY5F10', 'MF5BFO', 'JY5G19', 'BJ53L6', 'GS54M8', 'LB5JN6', 'MA5DBX', 'BV5815', 'BY5F14', 'GS54M4', 'GY5F1X', 'FB5189', 'RT541X', 'KV5216', 'BJ53L3', 'NU5JR3', 'NU5JR2', 'BW5G16', '6E52M2', 'DW5G17', 'BY5G11', 'LA5DB2', 'EW5F11', 'FU5JR1', 'LT521X', 'ZA5CS4', 'ME53F3', 'DV5410', 'JC5DB0', 'BY5F18', 'PY5F14', 'KU5BF9', 'CV5416', '6E52M4', '805832', 'RM5F13', '8V5414', 'PY5F10', 'JN5BF6', 'BW5F13', 'YX5906', 'RY5F18', 'RM5F1X', 'BV5817', 'AZ5CN8', 'UN53B8', 'KV5218', 'JF5C73', 'LB5JN9', 'LA5DAX', 'PC5DB6', 'EM5F18', 'AE52S0', 'KN5BF6', 'JA5DA1', 'JN5BF9', 'MU52N9', 'DW5G15', 'RV5815', 'MF52F1', 'ZY5G14', 'BW5411', 'RY5F15', 'NC5EC1', '405038', 'RY5F11', 'KY5G17', 'BJ53L7', 'MU52N4', 'KB54H1', 'WC5DB0', 'MA5ECO', 'LU5216', 'DW5G11', 'MA5EC0', 'EY5F19', '8J53L3', 'GZ5AN6', 'DW51E8', '615242', 'GS54M9', 'EM5F14', 'KW5F14', 'YX5964', 'MF5BF8', 'LA5DA7', 'NU5JR9', 'DV5812', 'CP5154', 'H25ZZZ', 'BY5G18', 'YX5969', 'BU5JR1', 'CP5156', 'VN52NX', 'YU5964', 'LA5DBX', 'GS54MX', 'GZ5AN2', 'MA5DB4', 'ZU5JR5', 'DY5G13', 'KY5G13', 'CV5417', 'FE53S2', 'BT5415', '405034', 'M85003', 'SV5413', 'SZ5AN8', 'DY5G16', 'LA5EC9', 'DZ5BN3', 'GS54M2', 'DW5416', 'YX5963', '505243', 'AF54K3', 'PC5DB7', 'MA5DB0', 'KN5BF1', '8V5418', 'KU5BF0', 'KV5219', 'NY5F17', 'PK5C54', 'DW5G13', 'CZ5AN2', 'GW5F17', 'AE52S5', 'BY5G15', 'BW5815', '415002', 'ZY5G18', 'LA5DB8', 'DZ5BN5', '6E52M3', 'RX5GN9', 'ZU5JR2', 'HW5F12', 'BY5F16', 'CY5F13', 'UM5F10', 'JC5EC3', 'FE52S8', 'DY5G18', 'JV5219', 'DW5410', 'RV5416', 'RM5F11', 'BJ53L5', 'PC5DB1', 'BW5G17', 'RU5JR0', 'LA5DA9', 'DY5G15', 'LA5DB9', '515739', 'PY5F12', 'BW5F15', 'FM5185', 'FM5184', '415036', 'BW5413', 'RV5414', '415014', 'JA5DA9', 'FE52S5', 'ZC5ST2', '405002', 'UM5F1X', 'FE52S6', 'YX59GZ', 'KB5DB8', 'WC5DB9', '415013', 'VL52N7', 'AE51S0', 'NA5DB2', 'VC5DB3', 'AA5RX7', 'AE52S3', 'DM5F18', 'YU5908', 'MA5DB5', 'L35GY8', 'AK54K5', 'KU5JR4', 'DV5411', 'LA5DA5', '805336', 'BJ53L0', 'RT5415', 'JC5DB1', 'CV5415', 'KW5F13', 'SX5EN7', 'PC5DB2', 'LA5DA0', 'CW5F12', 'JW5G18', 'FE52SX', 'MA5DB6', 'LA5AB5', 'UU5JR3', 'KE52YX', 'JU5219', 'VC5DB9', 'LA5DB7', 'KN5BF5', 'AE52S7', '505313', '415033', '805326', 'RX5GN0', 'FY5F10', 'SX5EN4', '8Y5F16', 'GY5F14', 'JA5DB6', 'YU5F17', 'JA5DB3', 'JV5218', 'JY5G18', '405006', '415010', 'JW5G14', 'KB5DB9', 'MC5DB9', 'JA5DA7', 'CV5418', 'FE54S3', 'RY5F10', 'PH5C57', 'MV5211', '6D54M7', 'RV5411', 'SX5EN0', 'GZ5AN3', 'CM5657', '525AN5', 'BT5413', 'JW5G10', 'BW5417', 'SZ5AN5', 'AJ54K5', '805485', 'MA5DB7', 'BT5412', 'C25AN3', 'NA5DB6', 'RX5GN5', 'DT5417', 'KT5215', 'MF5BFI', 'MU5JR8', 'M85000', 'WA5DB5', 'JC5DB4', 'RX5GNO', 'PC5DB5', 'NU5F10', '415029', 'BY5G16', 'SZ5AN6', 'CA50A0', 'YU5969', 'SZ5AN9', 'JV5216', 'RU541X', 'WC5EC5', 'EV5819', 'TY5F16', 'BC53L3', 'BW5414', 'DM5F16', '505003', 'ZY5G10', 'EY5F15', 'LU5213', 'RV5819', 'EM5F1X', 'NU5JR1', '415017', 'FM5180', 'ZY5G13', 'VC5DB2', 'TY5F14', 'MF5CFI', 'DN56A0', 'AX5GNX', 'JC5DB9', 'LU5F18', 'EM5F13', 'KN5BF3', '8U5CD1', 'KM5F13', 'GY5F13', 'CY5F18', 'JA5DB4', 'PY5F18', 'LA5EC5', 'MT5213', 'RV5412', 'BU5JRO', 'UM5F14', 'EM5F10', 'UU5JR5', 'RY5F17', 'DW5G14', '505046', 'KT5214', 'FY5F17', 'WA5DB4', 'BW5G14', 'BT5419', 'EY5F14', 'JY5G11', 'UY5E14', 'YX5965', 'YU5968', 'VL52N0', '505015', 'VN52N5', 'JA5DB1', 'RX5GN3', 'JV5213', 'MA5EC3', 'EU5JR1', 'JA5EC8', 'KB5DA5', 'DZ5BN7', 'RT5410', 'RV541X', 'CY5F11', 'MT5218', 'KU5BF8', 'DV5814', '405009', '6E52M8', 'GZ5AN8', 'JA5EC6', 'AE54S1', 'RV5813', 'VC5DB6', 'YX59GI', 'JT5218', 'BU5IFB', 'EW5F10', 'NC5DB3', 'CV5411', 'VL52N5', 'AP54K3', '6E52M7', 'LU5JR5', 'WA5DB9', 'KW5F10', 'PC5DB4', 'AZ5CNO', 'AZ5CN0', 'LB5JN3', 'AX5GN8', 'DZ5BN8', 'BW5G10', 'JV5211', 'VC5DB4', 'CY5F17', 'SY5F15', 'LB5JN0', 'MC5AB5', 'EV5815', '8V5416', '415030', 'TY5F11', '6D52M2', 'PU5JR6', 'AP54K2', 'KT5213', 'EY5F13', 'KB5AB0', 'LT5219', 'RX56N3', 'WC5DBX', 'GE52MB', 'SZ5AN0', 'KB5DB2', 'KM5F17', 'CY5F19', 'FY5A18', 'YX5962', 'YX50G0', 'ST5415', 'GE52MI', '8Y5619', 'CW5F1X', 'NC5DB6', 'CV52B4', 'SZ5AN3', 'CW5F17', 'PY5F1X', 'BW5419', 'BT5417', '415001', 'YX5967', 'YX59CX', 'PU5JRX', '805587', 'CV541X', 'RV5419', '8V5412', 'SZ5ANZ', '655533', 'JC5DB8', 'JA5EC4', 'RW5F10', '805065', 'BW5F10', 'CW5F14', 'CV5410', 'CY5F10', 'PU5JR3', 'LU5F14', 'RM5F10', 'KW5F1X', 'WA5DB3', 'EV5419', 'DY5G19', 'GY5F10', 'MV5213', 'NA5DBX', 'ZU5JR8', 'KM5F14', 'D258N8', 'MA5DB3', 'YX59GE', 'RV5410', 'AZ5CN5', '8J53LX', 'LV5211', 'MU5JR5', 'JV521X', 'JA5DAX', 'NA5DB1', 'RW5F17', 'MV5216', 'CY5F12', 'NA5DB7', 'MA5DB1', 'EM5F19', 'LB5JN7', 'LT5216', 'LA5DA4', 'BW5G12']
  Model_Year: ['9', 'F', 'D', 'H', '6', 'A', 'K', 'J', '7', 'C', 'M', 'E', 'B', '8', 'L', 'G', 'R', '5', 'P', 'N', 'S', 'X', '2', '3', '4', '1', 'V', 'W', 'T']
  Plant_Code: ['X', '7', '8', 'K', '0', 'S', 'A', 'M', '3', '5', '4', 'T', 'G', '1', 'Z', 'J', '6', 'V', 'L', 'U', '2', '9', 'B', 'R', 'Y', 'F', 'C']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,M,STD (NON GCC),GCC,4.0,5TF,MV5215,9,X,094001
1,TOYOTA,FORTUNER,6.0,SUV,Y,GXR,GCC,NaN,MHF,YU59G6,F,7,038129
2,TOYOTA,FORTUNER,4.0,SUV,Y,SR5,GCC,5.0,MHF,YX59G9,D,8,048149
3,TOYOTA,AVANZA,4.0,MPV,M,SE,GCC,NaN,MHK,MF53F3,H,K,015126
4,TOYOTA,FORTUNER,4.0,SUV,Y,TOP,GCC,5.0,MR1,YU59G6,6,0,006069
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10767,TOYOTA,TUNDRA,8.0,PICKUP,A,STD (NON GCC),NON-GCC,NaN,5TF,AY5F17,M,X,977224
10768,TOYOTA,FORTUNER,4.0,SUV,Y,SR5,GCC,NaN,MHF,YX59G5,8,8,009418
10769,TOYOTA,TUNDRA,6.0,PICKUP,L,1794 EDITION (NON GC,NON-GCC,NaN,5TF,LA5DB7,P,X,061169
10770,TOYOTA,TUNDRA,8.0,PICKUP,D,STD (NON GCC),NON-GCC,NaN,5TF,DW5F1X,H,X,624341
10771,TOYOTA,AVANZA,4.0,SUV,M,SE,GCC,NaN,MHK,MF5CF0,L,K,009941

====================================================================================================
pos6: B
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'COROLLA CROSS', 'SCION', 'YARIS', 'INNOVA', 'FORTUNER', 'GR86', 'LEVIN', 'HILUX', 'COROLLA', 'CAMRY', 'DAINA', 'SALOON', 'RUSH', '86', 'HIACE', 'DYNA', '2 HX DC 4X40', 'RAV4', 'GLX RA (PICK UP)', 'COASTER', 'SIENNA', '25 HX DC 4X4 PLAT GLX RA(PICK UP)', 'H 530', 'GXR RA(STATION WAGON)']
  bodyType: ['SUV', 'SUV- CROSSOVER', 'SEDAN', 'HATCHBACK', 'MPV', 'COUPE', 'PICK UP DOUBLE CAB', 'PICKUP', 'MINI BUS', 'BUS', 'STATION', 'PICK UP SINGLE CAB', 'PICK UP', 'PANEL VAN']
  pos4: ['A', 'K', 'D', 'Z', 'B', 'H', '1', 'C', '3', 'T', 'E', '2', 'G', '6', '4', 'Y', '0']
  trim: ['GXR', 'XL', 'STD (NON GCC)', 'GXR2', 'SE', 'HEV', 'VXR', 'STD', 'DLX', 'LE', 'GXR1', 'XLI MID', 'VX', 'LIMITED', 'GXR TOP', 'XLI EXECUTIVE', 'GXR SOD D/AC AW', 'GRANDE', 'GLI HEV', 'GXR4', 'XLI', 'SE+', 'GR SPORT', 'BLACK EDITION', 'GLE HEV', 'GXR-V', 'DL', 'GLI', 'EXR', 'GX', 'LEVIN', '1500', 'BASE', 'E', 'HYCROSS', 'VTX', 'VXR BASE', 'GL', 'GLX', 'GR-S', 'VIP7', 'VX2', '1', 'EX', 'ASD', 'GLE', 'GLI TOP', 'GLS', 'DLS - STD ROOF', 'XLI EXECUTIVE MR', 'XLI TOP', 'LE (NON GCC)', 'GL2', 'DX', 'YA', 'STATION']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTM', 'RKL', '3MY', 'MHF', 'JF1', 'LVG', 'WV1', 'MR0', 'YV2', 'LFP', 'LJ1', 'JTB', 'SCR', 'MHK', 'LS4', 'LGF', 'MD6', 'LSK', 'JTE', 'A25', 'LSY', '5ZT', 'MR2', 'HJ4']
  VDS: ['AUBBJ1', 'ABBBJ0', 'ABBBJ3', 'KABAGX', 'KCBAG1', 'AUBBJ2', 'ABBBJ6', 'DLBZV4', 'AUBBJ0', 'ABBBJX', 'ABBBJ9', 'ABBBJ2', 'AUBBJ4', 'ABBBJ7', 'DLBYV1', 'AUBBJ7', 'KUBAG5', 'ABBAAX', 'ABBBJ1', 'AUBBJ3', 'AABBJ0', 'AUBBJ5', 'AUBBJ6', 'ABBBJ4', 'AABBJ7', 'KUBFS2', 'ZNBB18', 'ABBBJ8', 'BPB9EX', 'KUBAGX', 'ABBBJ5', 'ZBB2K2', 'KUBAG6', 'KUBAG1', 'AUBBJ9', 'DLBYV8', 'KUBAG4', 'AABBJ3', 'AUBBJ8', 'KUBAG2', 'KBBCD8', 'AABBJX', 'DLBYV2', 'DLBYV0', 'AUBBJX', 'DLBZV0', 'KABAG0', 'KUBAG7', 'A4B2A2', 'DLBYVX', 'AABBJ6', 'B4B9EX', 'KABAG9', 'H4BCP3', 'DLBYV7', 'ABBBJO', 'KCBAG0', 'KABAG1', 'ABBAA6', 'B1B0E9', 'KUBAG9', 'KCBAG3', 'B4B9E2', 'ABBAA7', 'A4B3A9', 'A4B2A6', 'ABBAA8', 'KABAG5', 'DLBYV6', 'ABBBJI', 'BPB9E1', 'ZNBC13', 'A4B3A5', 'ABBAA5', 'AABBJ2', 'DLBYV9', 'AUBBJO', 'ABBAA9', 'A4B3AX', 'DLBYV3', 'B1B0E2', 'DLBYV5', 'DLBJV3', 'DLBJVX', 'B4B9E8', 'B4B9E1', 'KUBAG0', 'ZNBF12', 'ZNBB17', 'KABAG6', 'KABAGO', 'ABBAA2', 'B1B0E5', 'KCBAG9', 'KUBAGO', 'KUBAG8', 'ABBAA1', '1KBBC1', 'KABAG7', 'A4B3A8', 'KABAG2', 'CXBEM0', 'ZNBE12', 'KCBAG4', 'B1B0E8', 'ZNBC19', 'AABBJ1', 'BPB9E0', 'BPB9E2', 'BPB9EO', 'B4B9E6', '32BUM1', 'ZNBE14', 'KUBAG3', 'AABBJ9', 'B4B9E0', 'AABBJ5', 'BPB9E4', 'DLBZV1', 'B1B0EX', 'ABBAA0', 'KABAG8', 'ZNBF14', 'ABBAA4', 'KABAG4', 'KCBAG8', 'ABBAA3', 'TEB3NX', 'BUBFSX', 'KCBAG2', 'EFBBF7', 'B1B0E0', 'AABBJ4', 'B1B0E7', 'ZNBG14', 'AABBJ8', 'ZNBF11', 'BUBFS4', 'DLBYV4', 'ASB3R9', 'KABAG3', 'B4B9E9', 'KCBAGX', 'DLBJV8', 'B1B0E4', 'ZBB2K7', 'B4B9E7', 'BXBCD6', 'BPB9E3', '1HBJW0', 'B4B9E3', 'B4B9E4', 'AUBBJS', 'BXBCD5', 'BUBFSB', 'BUBFS9', 'DLBJV7', 'HXBCDB', 'B4B9E5', 'KCBAG7', 'A4B5A4', 'KUBFS9', 'EFBCF8', 'DXBFS8', 'B1B0E3', 'EFBCF1', 'KBBCDS', 'BUBFS1', '26BG7X', 'G4BC13', '1KBBD4', 'EFBBF4', 'DLBZV3', 'AABAJO', 'AUBB38', '66B3D9', 'KUBFS5', 'ZBB7H0', 'EFBBF5', 'B1B0E1', 'DXBCD6', '41BB42', 'BPB9E5', 'DLBZV8', 'ASB3R8', 'DLBJV4', 'BYBDE1', 'BXBCD7', 'A0B982', 'DLBZV7', 'DLBZVX', 'AUBBJB', 'YBBCA5', 'KCBAG5', 'DXBFS5', 'ABBBJB', '2SBPB2', 'AUBBJN', 'B1B0E6', 'ZNBF15', 'ZBB2KX', '38BS17', 'ZNBC1X', 'ZBB2K9', 'ZBB2K0', 'ZNBE15', 'EFBBF3', 'EFBC38', '01BUM1', '66B3D4', 'A4B3A2', 'ABBDH7', 'DLBJVO', 'DLBJV0', 'DLBJV1', 'KUBFSX']
  Model_Year: ['R', 'N', 'P', 'S', 'G', 'K', 'T', 'A', 'H', '1', 'J', 'V', 'L', '5', 'W', 'X', 'M', 'E', 'F', 'B', 'D', '7']
  Plant_Code: ['4', '0', 'Y', '9', 'G', 'X', '1', 'B', '2', '8', '6', 'C', 'K', 'F', 'D', 'H', '5', 'S', 'N']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,AUBBJ1,R,4,057596
1,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,ABBBJ0,N,4,038683
2,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,ABBBJ0,P,4,101333
3,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,ABBBJ3,P,4,058915
4,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,K,XL,GCC,NaN,RKL,KABAGX,N,0,504885
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3507,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,NaN,JTM,ABBBJ4,R,4,165569
3508,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,NaN,JTM,AUBBJ9,S,4,079917
3509,TOYOTA,LAND CRUISER,6.0,SUV,A,1,GCC,NaN,JTM,AUBBJ0,S,4,083998
3510,TOYOTA,COROLLA CROSS,4.0,SUV,K,XL,GCC,NaN,RKL,KUBAG0,R,0,504648
3511,TOYOTA,LAND CRUISER,6.0,SUV,A,1,GCC,NaN,JTM,ABBBJ6,S,4,188504

====================================================================================================
pos6: 7
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['TACOMA', 'LAND CRUISER PICK UP', 'LAND CRUISER', 'LAND CRUISER PICKUP 70', 'LAND CRUISER 70', 'COASTER', 'CAMRY', 'HILUX', 'TOYOTA LAND CRUISER', 'PREVIA', 'COROLLA', 'SUPRA', 'CROWN KLUGER', 'TUNDRA', 'LAND CRUISER PICK UP CARGO', 'TOYOTA', '25 LP SC4X44.0L MT', 'LAND CRUISER / STATION', 'LAND CRUISER SINGLE-CABIN PICK', 'HIGHLANDER', 'CRESSIDA', 'لاند كروزر', '25 LP SC 4X4 P4.0 MT', 'HIACE', '1999', 'TAKOMA', 'PICK UP CABIN', 'TACOMA (PICK UP)', 'LAND CRUISER/PICK UP CARGO', 'TAKOMA PICK UP CARGO', 'RAV4', 'LAND CRUISER/STD EX PICKUP', 'LAND CRUISER PICKUP', '26 LP SC 4X4 P4.0L AT', 'LAND CRUISER - PICK UP CARGO', 'PICKUP', 'LAND CRUISER SINGLE-CABIN PICK UP', 'CAMRY HYBRID']
  bodyType: ['PICK UP DOUBLE CAB', 'PICK UP', 'SUV', 'PICK UP SINGLE CAB', 'PICKUP', 'BUS', 'SEDAN', 'MPV', 'COUPE', 'LIGHT VEHICLE', 'STATION', 'PANEL VAN', 'AMBULANCE', 'PICKUP DOUBLE CAB']
  pos4: ['W', 'L', 'A', 'B', 'E', 'F', '8', 'K', 'C', '0', 'M', 'R', 'J', 'H', '1', 'V', 'G', 'S']
  trim: ['SR5 (NON GCC)', 'GXR', 'STD', 'VXR', 'VX', 'LX', 'LX AC PWR OPT', 'LX WINCH', 'GX', 'SC', 'HT SWB', 'EXR', 'GXR MID', 'LWB HIGH ROOF', 'GR SPORT', 'GLE', 'ST', 'GXR2', 'GXR TOP', 'VXR BASE', 'DLX', 'GLX', 'GR-S', 'STD (NON GCC)', 'HT VXR', '1', 'GXR FMST', 'XLI', 'LWB', 'STD AC', 'XLT', 'COUPE', 'GXR TOP DMST', 'GXR TOP 60TH ANNIV. XTREME', 'DX', 'SAFARI', 'GXR TOP FMST', 'HARD TOP', '1500', 'G', 'X', 'GL', 'E', '6', 'SPORT', 'LAND CRUSIER', 'XE 4WD', 'VXR TOP LTH', 'S', 'STATION1', 'VXR MID', 'GLE HEV', 'CRESSIDA', 'GLI', 'AXL ', 'SE', 'PIKUP', 'PREMIUM', 'DL', 'PICKUP', 'GXR SOD D/AC AW', 'XTREME', 'AUTOMATIC', '60TH', 'USF', '1500 CREWCAB SLE Z71', 'DLS', 'A', 'LX WIDE TYRES', 'TRIM', 'GXR GT', 'PICK UP', 'LUXURY SPORT', '4', 'BASE', 'STANDER', 'SE+', 'GR', 'SEDAN', 'DLX TOP', '10TH VICTORY EDITION', 'GXR MID XTREME', 'STANDARD', 'BLACK EDITION', 'SE T2', 'DC', 'LE PLATINUM CITY', 'TX', 'GXR MID 60TH ANNIVERSARY', 'SLT', '2', 'GXR-V', 'VXR TOP', 'SGLX', 'PREMIER']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['4TA', 'JIF', 'JTF', 'JTM', 'JTE', 'JTG', 'LVG', 'JT4', '5TE', 'UP1', 'JT2', 'LFM', 'JM3', '3TM', '1C6', 'SXV', 'RKM', 'JS1', 'JA3', 'NV1', 'WDB', '1C8', 'D02', 'JTC', 'STM', 'JH2']
  VDS: ['WN72N6', 'LU73J7', 'LJ73J1', 'AB7BJ0', 'AB7BJX', 'AB7BJ6', 'LJ71J9', 'LU73J5', 'LU73J4', 'LU73J9', 'LU73JX', 'AB7BJ7', 'BB71J0', 'LJ73J7', 'LU73J2', 'AB7BJ5', 'AB7BJ3', 'AB7BJ4', 'LJ73J9', 'LV73J7', 'LU73J1', 'AU7BJ7', 'LJ73J8', 'AU7BJ4', 'LU73J0', 'LU73J6', 'EU73J6', 'LU73J3', 'AB7BJ2', 'FU71J2', 'AU7BJ0', 'LJ73J4', 'AU7BJX', 'LJ73J5', '8V71J4', 'AB7BJ8', 'LJ73JX', 'AB7BJ9', 'LU71JX', 'FK7180', 'B674K8', 'LJ71JX', 'LJ73J2', 'FU71J8', 'AU7BJ9', 'AU7BJ1', 'FU71J7', 'AB7BJ1', 'AU7BJ8', 'LU71J1', 'LJ73J3', 'LJ73J0', 'AU7BJO', 'AU7BJ2', 'FK7183', 'FU71J3', 'AC7BJ4', 'LU73J8', 'LJ71J7', 'FU73J5', 'KW73J1', 'AB7BJS', 'AU7BJ5', 'FJ71JX', 'LJ71J3', 'LJ73J6', 'CY7AJ4', 'AU7BJ6', 'AU7BJ3', 'LJ71J2', 'WN72N2', 'EU73J2', 'CY7AJ8', 'LB71J3', '007130', 'FJ71J2', 'MA71J2', 'RU71J9', 'LJ71J0', 'LU71J4', 'LB71J5', 'MA71L5', 'RB71J7', 'AA7BJ1', 'FU71J1', 'FU73J3', 'JD7BN2', 'EB73J5', 'BV71J0', 'LU71J8', 'EB73J9', 'BU71JX', 'EU73J5', 'LU71J6', 'BU71J4', 'LJ71J5', 'LU71J3', 'LB71J8', 'WG7255', 'CY7AJ2', 'HY7AJ3', 'RV71J6', 'FU73J6', 'FU71J4', 'BU71J6', 'BU71J1', 'FU71J5', 'RU71J5', 'FU71J6', 'FE7187', 'FK7187', 'EB71J9', 'FK7182', 'RB71J0', 'KU72N2', 'RB71JO', 'LB71J4', 'LJ71J1', 'EU73JX', 'BC74K2', 'FU71J0', 'AC7BJ7', 'LU71J2', 'LJ71J4', 'BU71J7', 'RB71J6', 'LV73J9', 'KW73J7', 'EB73J4', 'AB7BJO', 'RB71J9', 'AA7BJO', 'AA7BJ0', 'RB71J8', 'FU73J1', 'BV71J9', 'LJ7336', 'AA7BJ2', 'A878J9', 'FU73JX', 'LU71J9', 'FK7188', 'EF76A0', 'CY7AJ9', 'CY7AJ3', 'FU71J9', 'FU73J2', 'MX73E3', 'LU71J5', 'MX73E9', 'LR73J0', 'MA70J6', 'EU73J0', 'AC7BJ3', 'BV71J8', 'FU73J9', 'BV71J1', 'FE7280', 'LU71J7', 'EV73JX', 'RB71J2', 'LR73JX', 'LU7331', 'CY7AJ0', 'RD7KT4', 'AA7BJ9', '107013', 'FJ71J1', 'WN72N5', 'LJ71J6', 'FJ71J6', 'BU71J5', 'FJ71J0', 'AU7BJI', 'FU73J8', 'AU78J8', 'CP7241', 'RV71JX', 'VJ73J1', 'WG725X', 'GX72AX', 'BU71J2', 'BU71J0', 'JD7BN5', 'FU71JX', 'KB71J6', 'WN72N9', 'LU71J0', 'LV73J1', 'AN74K3', 'KW73J3', 'FU73J4', 'FJ71J4', 'FE7189', 'FJ71J9', 'FR73J7', 'FJ71J7', 'RV71J4', 'A878J5', 'AA7BJ7', '807726', 'AA7BJX', 'AC7BJ0', 'CY7AJ6', 'AA7BJ5', 'EF76A1', 'CY7AJ5', 'WM72N4', 'LV73J6', 'FK718X', 'FK7186', 'FU73J7', 'SK75F3', 'LJ71J8', 'RR7GT2', 'FK7185', 'CY7AJ1', 'HY7AJ4', 'VN73K1', 'LB71J0', 'BD74K6', 'WM72NX', 'LB71J2', 'BU71J9', '1779DX', 'LV73J5', 'JD7BN8', 'AC7BJ6', 'KW71J6', 'LV73JX', 'RV71J1', 'EV73J1', 'MA71J6', 'KW73JX', 'RB71J5', 'AB7RJ4', 'LV73J4', 'FU73J0', 'RU71J3', 'WN72N4', '807674', 'AU78JX', 'AA7BJ6', 'HY7AJ6', '807611', 'FF7193', 'AU7BJT', 'MA71J9', 'AA7BJ3', 'FB7180', 'KW73J8', 'FK7184', 'RB71J3', 'AB7BJZ', 'LJ731X', 'MA71L3', 'AC7BJ9', 'LV73J8', 'LV73JO', 'LU73JO', 'LR73JO', 'RV71J9', '107305', 'FJ71J8', 'HY7AJX', 'L373J0', 'RV71J5', 'SC79M9', 'AB7BJB', 'LU7334', 'RB71J4', 'HY7AJ0', 'FJ71J3', 'LV71J9', 'BV71J4', 'WN72N0', 'BV71JX', 'A878J7', 'AU7BJS', 'FE7284', 'FK7189', 'EU73J9', '8U71J6', 'RU71J8', 'MA70L6', '807007', 'FE7186', 'KW73J0', 'LJ7335', 'WG7258', 'BC74K7', 'MA70L5', 'HY7AJ5', 'RV71J0', 'MA71J0']
  Model_Year: ['T', 'K', '1', 'N', 'R', 'P', '3', 'H', 'S', 'E', 'F', '9', '7', 'M', '8', 'A', 'G', 'C', 'Y', '2', 'J', 'L', '6', 'D', '4', 'X', '5', 'B', 'W', 'V']
  Plant_Code: ['Z', 'B', '6', '4', '8', '7', 'G', 'F', '0', '9', '5', '3', 'M', 'S', 'Y', '2', '1', 'K']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,TACOMA,6.0,PICK UP DOUBLE CAB,W,SR5 (NON GCC),GCC,4.0,4TA,WN72N6,T,Z,159758
1,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP DOUBLE CAB,L,GXR,GCC,4.0,JIF,LU73J7,K,B,011123
2,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP,L,STD,GCC,2.0,JTF,LJ73J1,1,6,005284
3,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,5.0,JTM,AB7BJ0,N,4,012534
4,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,5.0,JTM,AB7BJX,N,4,056539
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4293,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AB7BJ7,P,4,096984
4294,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AB7BJ6,N,4,052343
4295,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AU7BJ9,P,4,030611
4296,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AB7BJ5,P,4,060145
4297,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,AB7BJ0,P,4,084921

====================================================================================================
pos6: S
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'FORTUNER', 'RAV4', 'HILUX', 'AVANZA', 'TUNDRA', 'LAND CRUISER', 'TACOMA', 'COROLLA', 'CELICA', 'PRADO', 'YARIS', 'FJ CRUISER', 'RUSH', 'PREVIA', 'INNOVA', 'ZELAS', 'CAMRY HYBRID']
  bodyType: ['SEDAN', 'SUV', 'PICK UP DOUBLE CAB', 'MPV', 'COUPE', 'PICKUP']
  pos4: ['5', 'B', '7', 'D', 'M', 'U', 'K', 'Y', '6', 'L', 'Z', '2', 'E', 'G', '0', 'X', 'I', 'J']
  trim: ['STD', 'GXR', 'XLI', 'DLX', 'SE', 'VX2', 'STD (NON GCC)', 'GLS', 'GX', 'SR5 (NON GCC)', 'TOP', 'BASE', 'VX1', 'XLI EXECUTIVE', 'TX-L TOP', 'S TRD SPORT PK', 'EXR', 'S', 'DOUBLE CABIN ', 'LIMITED', 'EX', 'TX-L', 'TAXI', 'SPORT']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['6T1', 'MHF', 'JTB', 'MR0', 'MHK', 'STF', '5TF', 'MR1', 'JAC', 'RKL', 'KMF', 'JTE', 'JTD', 'MRI', 'WMA', 'JTN', 'MRO', 'JT1', 'MHP', 'JTK']
  VDS: ['53SK20', 'BUSFS1', '72SC11', '71SC10', 'DBSCD6', 'MFSCF3', '53SK10', '72SK20', '72SK10', 'MFSCF0', 'BUSFS9', 'DWSF11', 'MFSBF7', 'MFSCF6', 'UWSF16', 'BUSFS7', 'UBS25G', 'UYSF14', 'BUSFS4', 'DWSF10', 'KYSFIX', 'DZSBNO', 'UYSF18', 'YXS9G3', '64STL3', 'BUSFSX', 'BLSHE7', 'BUSFS5', 'BUSFS6', 'LMSF17', 'ZCS7JP', 'BUSFJS', 'BUSFS8', 'MFSCF7', 'LASDB9', 'BLSHE1', 'KUSFST', 'KWS236', '21SZZ5', 'BBSHE4', 'BLSHEG', 'EFSBF6', 'BUSFJ7', 'GES2M2', 'BUSCD1', 'UYSF11', '71SC18', 'UYSPII', 'UYSF10', 'BBSHEX', 'DYSF18', 'BLSHE5', 'DYSF10', 'BUSFJ4', '0YSF10', 'XKS7BP', 'EFSBF9', 'GES2M5', 'IUSFI6', 'GXSEM0', 'BUSFS2', 'JFSC78', 'DYSF1X']
  Model_Year: ['W', 'H', 'X', 'T', 'L', 'V', 'K', 'N', 'A', 'F', 'G', '2', 'C', 'J', 'D', 'P', '8', 'E', 'M', '5', 'R', '7', '1']
  Plant_Code: ['X', '0', '5', 'K', '9', '7', '8', 'U', 'L', 'A', 'S', '3']
  Serial_Number: ['350893', '030452', '191691', '342144', '357877', '176291', '027498', '342520', '336865', '339444', '010503', '171684', '168801', '170412', '910160', '353495', '164485', '910264', '166403', '345863', '174596', '176471', '187285', '179882', '168855', '357463', '003569', '351174', '910875', '037371', '173120', '165117', '343780', '342926', '339106', '337751', '342771', '910045', '198995', '357337', '337671', '192134', '349735', '343532', '910451', '192982', '148020', '161643', '001725', '910080', '361276', '338546', '153573', '004466', '348662', '418558', '352729', '001738', '193041', '156576', '172154', '156089', '339288', '156645', '342737', '100461', '359028', '356852', '173989', '227873', '177011', '357043', '910726', '032346', '349223', '337396', '360078', '339407', '354768', '348167', '349086', '175522', '336628', '443858', '910705', '910482', '181319', '174102', '344811', '337151', '336969', '006013', '361122', '348858', '910130', '083496', '339783', '361885', '358560', '171163', '358743', '166214', '355388', '039084', '353329', '169343', '346198', '353620', '049711', '172046', '346788', '337164', '338120', '352857', '085783', '180954', '359233', '340056', '356724', '192737', '360267', '198792', '178466', '488394', '006923', '346974', '169278', '177292', '354765', '193637', '337057', '174187', '187687', '342184', '121778', '342106', '347240', '337447', '348313', '350480', '910343', '351683', '174979', '340246', '346625', '339354', '358370', '180424', '035917', '336227', '200312', '357632', '001978', '036919', '014419', '360793', '171804', '188770', '169512', '174900', '339803', '187742', '107903', '029064', '349951', '357121', '361147', '361113', '171604', '338654', '340279', '082874', '358447', '176570', '039134', '179536', '344323', '360461', '346263', '091047', '010519', '910521', '358185', '168187', '181933', '910354', '033175', '344704', '234053', '177762', '170766', '178592', '357512', '336906', '341629', '339539', '337758', '181222', '910173', '353422', '173189', '358642', '088977', '342706', '360926', '347670', '171759', '910952', '337874', '910232', '177088', '067167', '346299', '357918', '357584', '336063', '361558', '349714', '192149', '910437', '171306', '357759', '193396', '340414', '356625', '910340', '337047', '358144', '351414', '348341', '172909', '910165', '071869', '910330', '209014', '910657', '350663', '176362', '220049', '357379', '349555', '359522', '020144', '361483', '361051', '171962', '193191', '910969', '042140', '336761', '036376', '357437', '096884', '360764', '172780', '157097', '910359', '359019', '341407', '345833', '350788', '177651', '347705', '342747', '359383', '343224', '355640', '910478', '359786', '165565', '193277', '348358', '360732', '345325', '337026', '174702', '910680', '014237', '096280', '237800', '175174', '095577', '111631', '344074', '080275', '348864', '383997', '174457', '236369', '180192', '168202', '357250', '358246', '967485', '341726', '118563', '350533', '357306', '910175', '339292', '179034', '179204', '654703', '344006', '172304', '355519', '493168', '344744', '166743', '359936', '337595', '340545', '350375', '346024', '167069', '035058', '336591', '158349', '350213', '033779', '351148', '349178', '170619', '340582', '168222', '175081', '165656', '349439', '359607', '191765', '357861', '175109', '341793', '346936', '337769', '347696', '361964', '348076', '357359', '910047', '032693', '348804', '910368', '338060', '356572', '222735', '347601', '360907', '166715', '034338', '350669', '173247', '347855', '358563', '338249', '067646', '157912', '273077', '349690', '231682', '910679', '168911', '348599', '353232', '348585', '166735', '354816', '910137', '341036']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,5,STD,GCC,4.0,6T1,53SK20,W,X,350893
1,TOYOTA,FORTUNER,6.0,SUV,B,GXR,GCC,5.0,MHF,BUSFS1,H,0,030452
2,TOYOTA,RAV4,4.0,SUV,7,GXR,GCC,5.0,JTB,72SC11,W,0,191691
3,TOYOTA,CAMRY,4.0,SEDAN,5,STD,GCC,4.0,6T1,53SK20,W,X,342144
4,TOYOTA,CAMRY,4.0,SEDAN,5,XLI,GCC,4.0,6T1,53SK20,X,X,357877
...,...,...,...,...,...,...,...,...,...,...,...,...,...
366,TOYOTA,CAMRY,4.0,SEDAN,5,STD,GCC,4.0,6T1,53SK20,W,X,348585
367,TOYOTA,CAMRY,4.0,SEDAN,5,STD,GCC,4.0,6T1,53SK10,V,9,166735
368,TOYOTA,CAMRY,4.0,SEDAN,5,STD,GCC,4.0,6T1,53SK20,W,X,354816
369,TOYOTA,CAMRY HYBRID,4.0,SEDAN,7,STD,GCC,NaN,6T1,72SK20,W,X,910137
370,TOYOTA,CAMRY HYBRID,4.0,SEDAN,5,STD,GCC,NaN,6T1,53SK20,W,X,341036

====================================================================================================
pos6: R
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['RAV4', 'COROLLA', 'PRIUS', 'HIGHLANDER', 'HILUX', 'FJ CRUISER', 'RAV 4', 'OTHERS', 'COROLLA 1.6', 'COROLLA 1.8', 'SCION', 'YARIS', 'CAMRY', 'HIACE', 'RAV4 LE CAR', 'LAND CRUISER', 'RAIZE', 'TOYOTA COROLLA', 'PRADO', '1.8 XS', 'TOYOTA COROLLA 1.8', 'COROLLA 1.3', 'FORTUNER']
  bodyType: ['SUV', 'SEDAN', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'SALOON', 'STATION', 'PICK UP', 'PICK UP SINGLE CAB', 'PICKUP', 'HALF PANEL VAN', 'COUPE', 'PANEL VAN']
  pos4: ['W', 'B', 'Z', 'R', 'K', 'E', 'F', 'H', 'Y', 'C', 'D', 'N', 'G', 'P', 'J', '2', 'L', '5', 'A', 'S', '8', 'M', 'V', '3', 'T', 'X']
  trim: ['LE HEV', 'S TRD SPORT PK', 'SE', 'XLI EXECUTIVE', 'SE+', 'VX', 'EXR', 'GX', 'LE', 'ICONIC', 'GXR', 'XLE', 'PLATINUM', 'ECO', 'BE', 'DLX', 'GLI', 'DYNAMIC', 'GLE HEV', 'EX', 'MID', 'LE (NON GCC)', 'STD (NON GCC)', 'STD', 'DL', 'XLI', 'LIMITED (NON GCC)', 'S', 'GA', 'EXI', '1', 'GLE HEV BLACK EDITION', 'GLE', 'TOP', 'SPORT', 'XL', 'ADVENTURE', 'GLX', 'SUPER SAFARI T1', 'E', 'SED', 'VXR', 'IM', 'HYBRID (NON GCC)']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['2T3', '2T1', '5YF', 'JTM', 'JTN', '4T3', 'JTD', '5TD', 'JAA', 'SYF', 'LWL', 'JTB', 'SMV', 'VF1', 'ZT3', 'JTJ', 'STD']
  VDS: ['W1RFV6', 'BURHE2', 'BURHE9', 'BURHE1', 'BURHE8', 'ZFREV8', 'B1RFV5', 'ZFREV4', 'BURHE5', 'REREV2', 'K4RBE5', 'BURHE0', 'RFREV8', 'RFR3V8', 'R6RFV9', 'E6RFV0', 'RFREVX', 'F1RFV7', 'EPRAE9', 'H1RFV5', 'WFREV0', 'KARFU1', 'YARAH6', 'BURHE7', 'BFREV3', 'H1RFV7', 'BURHE3', 'WFREVX', 'C1RFV8', 'YFREVX', 'BPRBE3', 'BURHE4', 'RWRFV4', 'BURHE6', 'DFREV7', 'DFREVX', 'KBRFU2', 'ZFREV9', 'WFREV6', 'H1RFV6', 'RWRFV0', 'DJREV9', 'NHR55E', 'R1RFV4', 'EPRAE5', 'EPRAE8', 'DFREV9', 'BURHEO', 'E6RFVX', 'DFREV5', 'DFREV6', 'GZRBH0', 'EPRAEX', 'EBRBE3', 'W1RFV9', 'BURHEX', 'DFREV2', 'P1RFVX', 'JJREV4', 'BPRHE5', 'DFREV4', 'RFREV1', 'ZZRFH2', 'BFREV1', 'WFREV3', 'EPRAE7', 'RJREV6', 'YFREV3', 'NFREVX', 'EBRBE1', 'HZRBH1', 'JFREV5', 'JJREV6', 'BFREV8', 'RFREV9', 'K1RFV8', 'RFREV4', 'BPRBE7', 'WFREV7', 'RFREV5', 'H1RFV3', 'BFREV9', 'WFREV5', 'FZRBH4', 'RFREV3', 'RFREV2', 'RJREV4', 'RJREV2', 'YFREV2', 'DFREV1', 'W1RFV7', 'ZFREV5', 'ZFREV6', 'P4RCE7', 'BFREVX', 'H1RFV9', 'BFREV4', 'GBRCH3', 'WFREV2', 'BFREV7', 'F1RFV0', 'YFREV5', 'WFREV1', 'DPRAE8', 'H1RFVX', 'DZRBH8', 'RFREVI', 'B6RFV7', 'RFREV6', 'EWRFV7', 'EPRAE1', 'JZRFHX', 'BPRBE2', 'BFREV6', 'K1RFVX', 'DPRAEO', 'DPRAE0', 'ZFREVX', 'ZKRFH7', 'YKRFH8', 'ZFREV7', 'ZFREV3', 'BPRHE4', 'ZFREV2', 'YFREV6', 'RWRFV8', 'ZFREV0', 'RFREV0', 'EBRBE7', 'WFREV4', 'EPRAE4', '2FREV0', 'W1RFV3', 'K1RFV4', 'BFREV5', 'DAR9K9', 'P1RFV3', 'BPRBE6', 'P1RFV1', 'EPRAE6', 'KBRFU9', 'YFREV1', 'KARFU6', 'NRRTX4', 'J1RFV8', 'KARJE0', 'L9RFU8', '5WRFV2', 'YFREV0', 'NFREV6', 'KARFU2', 'BURHET', 'NFREV7', 'HPRAE2', 'DZRFH9', 'WFREV8', 'KARFUX', 'K1RFV7', 'KARJE4', 'WFREV9', 'A1RFV4', 'H1RFV1', 'JFREV0', 'DFREV0', 'F1RFV4', 'GZRBH1', 'KARFU0', 'BFREV2', 'NFREV8', 'EPRAE3', 'E6RFV4', 'B1RFV3', 'R1RFVX', 'RWRFV7', 'EPRAE2', 'BFREVO', 'YFREV8', 'KARFU5', 'H1RFV8', 'EBRCH5', 'H1RFV4', 'W1RFVX', 'BPRHE1', 'EBRBE4', 'RFREV7', 'KARJEX', 'S4RCE4', 'KARFU7', 'EBRBE5', 'S4RCE9', 'J1RFV9', 'KARJE5', 'G1RFV9', 'ZFREV1', 'KBRFU8', 'S4RCE1', 'S4RCEI', 'ZZRAH4', 'GBRCH8', 'P1RFV7', 'EBRBE2', 'A1RFV2', 'C4RBE1', 'ZFREVO', 'KARFU4', 'P1RFV8', 'RJREV1', 'KBRFU6', 'H1RFV0', 'N1RFV8', 'KARJE2', '8URHE9', 'F1RFV5', 'R6RFV0', 'F1RFV8', 'BPRHE3', 'K1RFV3', 'BPRHE7', 'S4RCE2', 'R1RFV8', 'DWRFV8', 'DZRBH7', 'NFREV4', 'ZZRAHX', 'D1RFV8', 'KARJE3', 'MWRFV3', 'KARFP6', 'BZRFH6', 'RJREV0', 'KDRBH2', 'KARFU3', 'KBRFU4', 'B6RFV4', 'VPRAE0', 'G1RFV6', 'HPRAEX', 'G1RFV7', 'G1RFV4', 'P4RCE3', 'S4RCE8', 'RWRFVX', 'BBRCH7', 'WFREVS', '33RN85', 'C4RBE6', 'GZRBH6', 'DFREV8', 'A1RFVX', 'C1RFV7', 'ZZRFH1', 'BPRHE2', 'FPRAE3', 'DWRFV2', 'MWRFV2', 'GZRAH6', 'J1RFV2', 'JZRFH1', 'W1RFVO', 'W1RFV0', 'KARFP2', 'F1RFV3', 'DPRAE2', 'F1RFVX', 'KBRFU7', 'BPRHE6', 'LWRFV8', 'JZRFH2', 'K4RBE4', 'RWRFV1', 'C1RFVX', 'N1RFV9', 'T4RCE9', 'KARFP3', 'W1RFV4', 'KBRFU5', 'KARFU8', 'W1RFV1', 'YZRAH5', 'A1RFV5', 'KBRFU1', 'RWRFV6', 'BFREVI', 'KDRAH6', 'HPRAE1', 'WFREVO', 'EPRAE0', 'YFREV4', 'KARJE1', 'GZRAH4', 'DFREV3', 'BFREV0', 'P1RFV0', 'H1RFV2', 'ZARAH3', 'P1RFV6', 'FARAH4', 'F1RFV6', 'ZZRFH0', 'KARJE7', 'DWRFV0', 'YFREV7', 'C1RFV5', 'CIRFV7', 'JFREV1', 'BPRHE0', 'BPRHEO', 'RWRFV9', 'DPRAE1', 'K4RBEX', 'KDRAHO', 'BPRHEX', 'G1RFV1', 'R1RFV9', 'P1RFV5', '2FREV8', '8FREV1', 'BPRBE0', 'KARJE6', 'KARFU9', 'K4RBE2', 'R1RFV6', 'ZZRFH7', 'GZRAH9', 'J1RFV4', 'F1RFV2', 'EBRBEX', 'S4RCEX', 'R1RFV0', 'E6RFV9', 'K4RBE8', 'B1RFV0', 'F1RFV1', 'DPRAE7', 'N1RFV7', 'S4RCE5', 'GZRBH9', 'A1RFV6', 'GARAH7', 'F1RFV9', 'EPRAES', 'GBRCH2', 'E6RFV3', 'ZER2DG', 'GZRBH4', 'JFREV6', 'EPRAEO', 'RWRFV5', 'RJREVX', 'HZRBH0', 'C1RFV1', 'HPRAE8', 'S4RCE7', 'KKRFHX', 'K4RBE7', 'D4RBE2', 'W1RFV5', 'B1RFV9', 'KDRBH8', 'G1RFV2', 'EBRBE8', 'RWRFV2', 'NFREV5', 'WIRFV6', 'KBRFU3', 'NFREV1', 'W1RFV2', 'RJREV8', 'BBRCH6', 'YFREV9', 'K4RBE0', 'R6RFV2', 'KARFP5', 'GBRCH7', 'GBRCH5', 'DFREVO', '31RN85', 'KARJE8', 'NFREV9', 'HPRAE0', 'RWRFV3', 'RJREV9', 'DPRAE5', 'C1RFV2', 'YARAH7', 'P4RCE4', 'K1RFV6', 'K1RFV5', 'XBRCH7', 'KARJE9', 'BPRHE9', 'EWRFV1', 'R1RFV5', 'B1RFV1', 'KKRFH0', 'C1RFV0', 'K8RFU5', 'E6RFV6', 'R1RFV7', 'Y1RFV6', 'CZRAH7', 'GZRBH2', 'GZRBH8', 'DZRBH4', 'JFREV3', 'K4RBE3', 'P1RFV9', 'R1RFV1', 'G1RFV0', 'S4RCE6', 'F6RDM1', 'K4RBE1', 'KARFP4', 'BBRCH4', 'JJREV2', 'A1RFV9', 'EBRBE6', 'BPRBE9', 'B4RBE9', 'B4RBE3', 'BKRFH1', 'R1RFV2', 'KARAH2', 'P1RFV2', 'BPRHE8', 'JKRFH5', 'S4RCE3', 'KKRFH7', 'R6RFV7', 'YZRFH1', 'BPRBE8', 'P4RCE0', 'KARFP8', 'P4RCE1', 'A4RBE2', '2FREV2', 'KARFP7', 'N1RFV6', 'T4RCE7', 'A1RFV0', 'ZFREVI', 'ZZRAH5', 'D6RFV5', 'S4RCE0', 'FZRBH2', 'RJREVO', 'BURNE3', 'BURHES', 'G1RFV3', 'ZZRAH9', 'FIRFVO', 'FIRFV0', 'KDRBH6', 'LZRBHX', 'M4RCE5', 'B4RBE6', 'NPR66P', 'DJREV1', 'R6RFV8', 'DARTK7', 'KBRCH0', 'FZRBH5', 'DWRFV9', 'BJRBZ9', 'KARFP1', 'XBRCH1', 'B1RFV8', 'P4RCE9', 'B4RBE4', '8FREV7', 'MWRFV0', 'DCRFH0', 'KBRFUX', 'EBRBEB', 'C1RFV9', 'K1RFV9', 'YZRFH0', 'B1RFV6', 'P4RCE2', 'R6RFV3', 'RJREV3', 'KDRAH9', 'B6RFV2', 'DGRFH6', 'KBRFU0', 'D4RBE9', 'KDRAH8', 'W1RFVI', 'GZRBH3', 'WIRFVX', 'CZRAH0', 'K4RBE6', '2FREV9', 'J1RFV1', 'K4RBE9', 'P1RFV4', 'NFREV2', 'MWRFV7', 'ZFREVS', 'P4RCEX', 'HPRAE5', 'GZRBHX', 'BBRCH1', 'KDRAH3', 'VPRAE8', '2FREV7', 'BKRFH5', 'WIRFVI', 'EBRCHX', 'A1RFV8', '8URHE5', 'Z1RFV2', 'KZRFH4', '33RNA4']
  Model_Year: ['M', 'F', 'H', 'G', 'E', 'J', 'K', 'D', 'N', 'L', 'S', 'W', 'P', 'R', 'V', '6']
  Plant_Code: ['C', 'P', 'J', 'W', 'D', '3', 'U', 'S', '7', '5', 'L', 'B', '0', '2']

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,RAV4,4.0,SUV,W,LE HEV,GCC,5.0,2T3,W1RFV6,M,C,135629
1,TOYOTA,COROLLA,4.0,SEDAN,B,S TRD SPORT PK,GCC,4.0,2T1,BURHE2,F,C,432928
2,TOYOTA,COROLLA,4.0,SEDAN,B,SE,GCC,4.0,2T1,BURHE9,H,C,766019
3,TOYOTA,COROLLA,4.0,SEDAN,B,XLI EXECUTIVE,GCC,4.0,2T1,BURHE9,G,C,526189
4,TOYOTA,COROLLA,4.0,SEDAN,B,XLI EXECUTIVE,GCC,4.0,2T1,BURHE1,E,C,183469
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3891,TOYOTA,RAV4,4.0,SUV,B,BE,NON-GCC,NaN,2T3,BFREV7,J,W,717394
3892,TOYOTA,COROLLA,4.0,SEDAN,B,XLI EXECUTIVE,NON-GCC,NaN,5YF,BURHE9,G,P,480945
3893,TOYOTA,RAV4,4.0,SUV,R,XLE,NON-GCC,NaN,4T3,RWRFV3,N,U,066977
3894,TOYOTA,COROLLA,4.0,SEDAN,D,STD (NON GCC),NON-GCC,NaN,JTD,DPRAE2,L,J,080895
3895,TOYOTA,RAV4,4.0,SUV,A,LE HEV,NON-GCC,NaN,2T3,A1RFV2,S,W,574221

====================================================================================================
pos6: C
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'PRADO', 'CAMRY', 'COASTER', 'HILUX', 'COROLLA', 'YARIS', 'HIACE', 'RUSH', '25PR 5 DR P 2.4L AT', 'LAND CRUISER PRADO']
  bodyType: ['SUV', 'SEDAN', 'BUS', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'MINI BUS', 'PANEL VAN HIGH ROOF']
  pos4: ['A', 'B', 'C', '4', 'K', 'R', '8', 'W', 'Z', 'S', 'E', 'J']
  trim: ['EXR', 'GXR', 'ADVENTURE', 'BLACK EDITION', 'VXR', 'GXL', 'TXL1', 'GXR2', 'GLE', 'GXR TOP', 'VX', 'BUS', 'DLX', 'TX1', 'LIMITED HEV', 'GXR1', 'STD', 'XLI', 'GLX', 'BASE', 'GR SPORT', 'DL', 'GL', 'LUMIERE 40TH ANNIV', 'GX', 'VXR BASE', 'GLI HEV', 'TXL3', 'GXR3', 'GLI', 'S', 'DLS', 'YA', 'DX', 'EX', 'TXR', 'CTD', 'GLS', 'LWB HIGH ROOF', 'GXR FMST', 'SGLX', 'SE', 'LIMITED', 'ADVENTURE 1ST EDITIO', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTM', 'JTE', 'LVG', 'JTG', 'YV2', 'LA6', 'JIM', 'LEF', 'WDA', 'LET', 'LKL', 'LZZ', 'WV2', 'L3A', 'JMY', 'JL7', 'L3H']
  VDS: ['AUCBJ2', 'AUCBJ0', 'AUCBJX', 'AUCBJ6', 'AUCBJ8', 'AUCBJO', 'AUCBJ7', 'AUCBJ9', 'AACAJ8', 'ABCBJ8', 'AACAJ6', 'AACAJ3', 'ABCBJX', 'AACBJ1', 'AACAJ4', 'AUCBJ3', 'AUCBJ1', 'ABCBJ1', 'AACAJ0', 'AACAJ9', 'AUCBJ5', 'AUCBJ4', 'BACEKX', 'AACAJX', 'ABCBJ3', 'ABCBJ4', 'ABCBJ5', 'AACAJ2', 'AACAJ5', 'AACAJ1', 'ABCBJ7', 'CECB89', 'A4CFA7', 'AACAJ7', 'AACBJ3', 'AACBJX', '41CB81', 'ABCBJ6', 'ABCBJ0', 'AACBJ9', 'ABCBJ2', 'CECB85', 'A4CEA2', 'AACBJ2', 'AACAJO', 'AUCBJG', 'AFCG23', 'ABCBJ9', 'AACBJ7', 'AACBJ8', 'AUCBJS', 'AACBJ0', 'A4CFA5', 'BECEK7', 'KHCAA7', 'AECG27', 'KHCAAX', 'AFCG24', 'BACEK8', 'AECB83', 'AACBJ5', 'AECB80', 'AACBJ4', 'CECB81', 'AECG33', 'ARCAJ3', 'AACAJA', 'AKCB80', 'AECB89', 'AECB82', 'R1CS94', '8CCVD0', '8CCVD9', 'WBC7H5', 'Z1CK33', 'AACAJI', 'SRCSLA', 'KHCAA1', '8BCE1J', 'R1CS96', 'EGCBB3', 'A4CFA2', 'ABCBJO', 'J4CMA4', 'AFCG28', 'CECB82', 'AUCBJA', 'AECB85', 'AECB84', 'R1CS93', 'A4CEA8', 'J4CFC7', 'A4CFA3']
  Model_Year: ['R', 'P', 'S', 'N', 'T', '1', '4', '5', 'F', '8', '7', 'A', 'E', '9', 'B', 'M', '3']
  Plant_Code: ['4', 'K', '5', 'G', '6', 'A', 'B', 'H', 'L', 'C', 'Y', 'U', '8']
  Serial_Number: ['074994', '031169', '056767', '051723', '077267', '073797', '073350', '075972', '015269', '025479', '005003', '053496', '170120', '020413', '076349', '048168', '076166', '049307', '073640', '048708', '076527', '123339', '041233', '007895', '047500', '043582', '123707', '123690', '111774', '048161', '077487', '057447', '048175', '076503', '076092', '007794', '048794', '047516', '000237', '077919', '056796', '050062', '008711', '058495', '045304', '102923', '073097', '103562', '004396', '086671', '076169', '013293', '019888', '026893', '086973', '048965', '025083', '079233', '503053', '042562', '015324', '014189', '065529', '123486', '723488', '073154', '034723', '049756', '074531', '076543', '073789', '097391', '040086', '077625', '077162', '042768', '006973', '077970', '051065', '111104', '111085', '060508', '047904', '052021', '030317', '082782', '005398', '007075', '007365', '090129', '049212', '043045', '077950', '067911', '032379', '004657', '042209', '055191', '047233', '070572', '016365', '014680', '112216', '054397', '002696', '048398', '046025', '077471', '053908', '021682', '034357', '111250', '086595', '031112', '047355', '112330', '014427', '078474', '004832', '090571', '000263', '054882', '049461', '937204', '193275', '096404', '583652', '069721', '025992', '020013', '086676', '004141', '008888', '101391', '060505', '077787', '089489', '017199', '016801', '011099', '077481', '077961', '072758', '113497', '077418', '083965', '054537', '118135', '060060', '050419', '047216', '005133', '052142', '038531', '043240', '003744', '015043', '070005', '076946', '091881', '035983', '086600', '030437', '016431', '088699', '019989', '077121', '110245', '400120', '047473', '052248', '007165', '076149', '069121', '056103', '113240', '074086', '057050', '111078', '018511', '064520', '002282', '045184', '036550', '007126', '109325', '101750', '077616', '024272', '114244', '077800', '076541', '075185', '044241', '049209', '003974', '087256', '041453', '039326', '077627', '002513', '049995', '021059', '008851', '078088', '072353', '077614', '082586', '051359', '021627', '049239', '063361', '017145', '073940', '070400', '048801', '096240', '003170', '017375', '049473', '033094', '056058', '078119', '193381', '021774', '002784', '050666', '074996', '000990', '036171', '111899', '088561', '087424', '028645', '077450', '112072', '074422', '058234', '023107', '087752', '103835', '016085', '076846', '039828', '104998', '015168', '028965', '004390', '087422', '077153', '005844', '077022', '052155', '079081', '078934', '076714', '059138', '051071', '113205', '048430', '937066', '076526', '068245', '077484', '029157', '015887', '027968', '051859', '008566', '012428', '182469', '035036', '018042', '396543', '041306', '086513', '013413', '028468', '006227', '072506', '048517', '006287', '074625', '073087', '068099', '203496', '112205', '051227', '112090', '080206', '071536', '107502', '010769', '076547', '052730', '107625', '010733', '107708', '089755', '010445', 'N12959', '045194', '025153', '026338', '105347', '041908', '055027', '015550', '049758', '110556', '021399', '025154', '060845', '085974', '006272', '104142', '125498', '073933', '012989', '060398', '007201', '046347', '048792', '050296', '043071', '084067', '063965', '087971', '038894', '086945', '095697', '021933', '058132', '069779', '089227', '055392', '077767', '085997', '008676', '002973', '039955', '048934', '032218', '042336', '074621', '038890', '096407', '079062', '077164', '364912', '002633', '048442', '029102', '049745', '015275', '016517', '009576', '100585', '021798', '022634', '076715', '048929', '025646', '078240', '048419', '029701', '078308', '106277', '024976', '097163', '048702', '052119', '073476', '029616', '050235', '048291', '045068', '010644', '048971', '078271', '078288', '063976', '086942', '063886', '106479', '074786', '015402', '006357', '078482', '096060', '110667', '078074', '328796', '054570', '051372', '018393', '039639', '023978', '021336', '073645', '045845', '161043', '074784', '071768', '078824', '026447', '107811', '050064', '042928', '008577', '006968', '066066', '124829', '050721', '019620', '115783', 'N19197', '073799', '053594', '212572', '197914', '078639', '088840', '028623', '907312', '081471', '052234', '048674', '069730', '078685', 'N17889', '061678', '109193', '048932', '023402', '078921', '016720', '050957', '097740', '106063', '014717', '084301', '198805', '074410', '044476', '022536', '092902', '053491', '136883', '003722', '069576', '097415', '039576', '075973', '004026', '018352', '073803', '199257', '096238', '026641', '920640', '077804', '095367', '005514', '009453', '166679', '030494', '008667', '046623', '093078', '074623', '047357', '022898', '069847', '193695', '025279', '016141', '069147', '098189', '086817', '106062', '007396', '050738', '114556', '029418', '043937', '076537', '021886', '044386', '171075', '015139', '046631', '095854', '105891', '084177', '107712', '104992', '213552', '048580', '077313', '051200', '043341', '047219', '009123', '048140', '066629', '076992', '920005', '047354', '048688', '017174', '097732', '074411', '078684', '076351', '079564', '004229', '045225', '070086', '068988', '069665', '079709', '036363', '049484', '079077', '056771', '007463', '015170', '114372', '047540', '048938', '049499', '039934', '025680', '092602', '121192', '036400', '105174', '057172', '048340', '048791', '105328', '041447', '003127', '081821', '068862', '032082', '114567', '083439', '087392', '077763', '936431', '078122', '115140', '014771', '005299', '014202', '026200', '048334', '097345', '072031', '091705', '097368', '077439', '022254', '106885', '091714', '017191', '048944', '203170', '008547', 'N00827', '049241', '079230', '048144', '112248', '048382', '008519', '034094', '120841', '069858', '070232', '120853', '015329', '009252', '026087', '013948', '008731', '097854', '015000', '051776', '070340', '106246', '045739', '083238', '022189', '039399', '015749', '025981', '039211', '049704', '044381', '025884', '027837', '021646', '076163', '114699', '071289', '012207', '076698', '080588', '024138', '026974', '076154', '080910', '025287', '212159', '070578', '048424', '101562', '106275', '068697', '012189', '081626', '049653', '040726', '079361', '049488', '067917', '051075', '086780', '032093', '049623', '044818', '213153', '079220', '141608', '006469', '028263', '015407', '027994', '096063', '087878', '057832', '116821', '051705', '004945', '077256', '047268', '049214', '010120', '043713', '012531', '078447', '194163', '066498', '019701', '059563', '041141', '082243', '002191', '018181', '118119', '044056', '068385', '025683', '015927', '015991', '055873', '049127', '004435', '102272', '098040', '000382', '049238', '059502', '058975', '068902', '048389', '083773', '009225', '106383', '049003', '086509', '075180', '079546', '937221', '059942', '104651', '058021', '086440', '023961', '049210', '046217', '055031', '009443', '028533', '078442', '043238', '049730', '032421', '080578', '093409', '112084', '516737', '020073', '012299', '097428', '088584', '049271', '034998', '009223', '048922', '028343', '074533', '043330', '078686', '069275', '033185', '012969', '082797', '079857', '036023', '027306', '062285', '062497', '035841', '057860', '003735', '079545', '087104', '003438', '054567', '003101', '097871', '028502', '078284', '108878', '079847', '920982', '097381', '021429', '065940', '025895', '016505', '007120', '077619', '076359', '003857', '010001', '070409', '086672', '184984', '048908', '075184', '005750', '015224', '920037', '040305', '079374', '058253', '044932', '008605', '018100', '651575', '114561', '070235', '082619', '059568', '186234', '114837', '115339', '007304', '194618', '073091', '039499', '048597', '087142', '026000', '066238', '097741', '010288', '045367', '021221', '097889', '025096', '008430', '030487', '025688', '636369', '051189', '029585', '049192', '045847', '050014', '051120', '076677', '214252', '078617', '014309', '006634', '051188', '043585', '078273', '106295', '003683', '028479', '007724', '031630', '026079', '077485', '007807', '060630', '013351', '077020', '008531', '011732', '043157', '077431', '098981', '048162', '128556', '214495', '070491', '079392', '007031', '010547', '014271', '076134', '106777', '116945', '087002', '107032', '013717', '012505', '079704', '028461', '083262', '009693', '070537', '003649', '056461', '050379', '106694', '010060', '077750', '018649', '014871', '043413', '106963', '030927', '106090', '014903', '023275', '008299', '049691', '049498', '036954', '003777', '035120', '071771', '004219', '046734', '053730', '050154', '015907', '078678', '003242', '203188', '015913', '636368', '004111', '078440', '079235', '214497', '120510', '078450', '001086', '048296', '067602', '009286', '056077', '001338', '003924', '073643', '003529', '081956', '002279', '058614', '044949', '040767', '198456', '106473', '080763', '006291', '025975', '097709', '038480', '051301', '055390', '108791', '007531', '106786', '081305', '054007', '010824', '080584', '066169', '012613', '004897', '077421', '109770', '053902', '046096', '107962', '202462', '048890', '080948', '016618', '048167', '014710', '073633', '046341', '049200', '049445', '045674', '051829', '008634', '011743', '078801', '059640', 'A90001', '064306', '041286', '015607', '006688', '081301', '100231', '017107', '071533', '010164', '073346', '078243', '081802', '077631', '073096', '005232', '050812', '198315', '077582', '013008', '079547', '072068', '039277', '029214', '003338', '096614', '106967', '011692', '069859', '028975', '005802', '062514', '037297', '081320', '048600', '049195', '005621', '083571', '078679', '077745', '077173', '092747', '011615', '028340', '006643', '007812', '078246', '066175', '065694', '030983', '705366', '071523', '016128', '079153', '106454', '032267', '106798', '006030', '014295', '198801', '198712', '920612', '010420', '040000', '081797', '010849', '030420', '024790', '077309', '005394', '039040', '039761', '042816', '012820', '080189', '043520', '007512', '013690', '072071', '026323', '042667', '012233', '044080', '011303', '051714', '108096', '113623', '072237', '316708', '060954', '018136', '058982', '048711', '059332', '070668', '047453', '084317', '030921', '203859', '079563', 'K02371', '071535', '097103', '044767', '027231', '024584', '055541', '048690', '003408', '004459', '024424', '031836', '058379', '017938', '047786', '540053', '073090', '005067', '019508', '077282', '004972', '072765', '072945', '092925', '078083', '107887', '011628', '099878', '097550', '098039', '068909', '003432', '089025', '048654', '116037', '061060', '000401', '099527', '077255', '107881', '061190', '012029', '024417', '003835', '078920', '215836', '009821', '048153', '010710', '048925', '023011', '051488', '056331', '072949', '084314', '081803', '111897', '076500', '116713', '078300', '049009', '040316', '382656', '048267', '045310', '017541', '070708', '107645', '073475', '048694', '072398', '029893', '107985', '028405', '092029', '075211', '070845', '073089', '050880', '049754', '049626', '040510', '049487', '015194', '108366', '060846', '068684', '070411', '069046', '042857', '068961', '067770', '015635', '067080', '014521', '122947', '213485', '070231', '024572', '002437', '393919', '113615', '081814', '222446', '058137', '010631', '081801', '013161', '048440', '076827', '017326', '049452', '093608', '077965', '007937', '008782', '024918', '117419', '069431', '082222', '050961', '112204', '045098', '031541', '039776', '040537', '068247', '013001', '050967', '045979', '049485', '203969', '077964', '084158', '049202', '081440', 'NY0022', '012500', '081979', '076955', '080736', '080601', '042958', '199570', '079707', '049714', '048698', '027488', '115173', '070093', '095688', '116106', '043796', '049451', '084162', '048896', '096952', '049724', '007066', '057453', '096612', '048799', '056777', '041074', '097703', '050402', '108015', '109163', '005431', '022852', '116099', '006108', '048195', '071288', '077306', '102550', '010528', '009165', '049621', '008226', '077290', '048404', '107801', '048413', '047898', '203485', '071933', '079389', '005065', '037829', '071459', '080427', '031032', '083569', '025891', '015011', '068108', '197274', '080604', '111770', '049433', '046845', '154009', '212359', '022749', '024911', '047436', '078291', '006646', '116800', '028751', '053163', '076974', '919420', '038275', '044301', '117140', '937056', '072508', '097558', '097568', '006077', '003809', '110024', '919641', '071292', '199720', '068979', '070691', '052837', '005813', '047544', '146540', '203172', '919615', '040598', '213347', '009358', '078665', '048695', '016092', '055829', '046782', '080585', '002719', '034263', '038935', '068822', '082605', '008318', '093554', '026006', '035680', '076865', '108748', '045853', '080435', '048176', '049095', '079179', '039995', '081627', '070094', '013150', '013320', '114865', '064218', '007273', '072073', '014324', '919279', '037866', '071777', '072255', '057865', '018690', '659118', '072612', '006974', '055539', '046855', '114091', '014150', '070091', '211529', '072404', '077280', '078929', '049747', '068114', '069151', '025780', '015048', '003652', '049302', '048696', '084980', '017088', '012981', '013492', '081800', '016081', '097208', '011847', '327398', '048666', '058019', '097715', '077743', '073473', '052011', '081822', '042890', '116523', '116538', '580199', '079730', '180222', '091720', '079359', '008775', '109038', '027566', '015255', '028404', '012164', '079538', '003903', '047681', '047853', '010983', '116956', '051177', '057342', '078926', '069573', '079231', '083429', '058621', '135020', '120396', '012061', '062992', '049480', '012727', '024992', '399045', '094370', '077147', '047454', '011848', '049751', '048983', '070533', '012637', '083047', '012052', '070239', '045070', '086446', '000168', '023277', '017676', '048585', '077935', '026063', '048918', '076140', '210956', '076832', '040466', '051587', '081450', '050161', '111399', '002076', '072936', '025082', '051202', '050288', '047693', '047684', '050152', '051725', '107466', '017028', '094372', '136364', '048423', '210602', '071924', '009599', '008118']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,6.0,SUV,A,EXR,GCC,5.0,JTM,AUCBJ2,R,4,074994
1,TOYOTA,LAND CRUISER,6.0,SUV,A,EXR,GCC,5.0,JTM,AUCBJ2,P,4,031169
2,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,AUCBJ0,R,4,056767
3,TOYOTA,LAND CRUISER,6.0,SUV,A,GXR,GCC,5.0,JTM,AUCBJX,R,4,051723
4,TOYOTA,LAND CRUISER,6.0,SUV,A,EXR,GCC,5.0,JTM,AUCBJ0,S,4,077267
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,TOYOTA,LAND CRUISER,6.0,SUV,A,VXR,GCC,NaN,JTM,ABCBJ5,N,4,048423
1451,TOYOTA,LAND CRUISER,6.0,SUV,A,1,GCC,NaN,JTM,ABCBJ9,T,4,210602
1452,TOYOTA,LAND CRUISER,6.0,SUV,A,EXR,GCC,NaN,JTM,AUCBJX,R,4,071924
1453,TOYOTA,LAND CRUISER,6.0,SUV,A,1,GCC,NaN,JTM,AACBJ8,N,4,009599
1454,TOYOTA,LAND CRUISER PRADO,4.0,SUV,A,GXL,GCC,NaN,JTE,AACAJ1,S,5,008118

====================================================================================================
pos6: A
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA CROSS', 'CROWN', 'COROLLA', '86', 'CAMRY', 'COROLLA 1.3', 'BZ4X', 'HIACE', 'PRIUS', 'TOYOTA PRIUS', 'HILUX', 'SEQUOIA', 'ALPHARD', 'TACOMA', 'COROLLA 1.5', 'FORTUNER', 'PRADO', 'TOYOTA COROLLA', 'COASTER', 'LAND CRUISER', 'SIENNA', 'AVALON', 'MODEL 2022', 'HIGHLANDER', 'PREVIA', 'RAV4', 'RUSH', 'KING LONG PASSENGER', 'كورولا 1.3', 'INNOVA', 'NIO ES8', 'SCION', 'MIRAI', 'TOYOTA 86']
  bodyType: ['SUV- CROSSOVER', 'SEDAN', 'COUPE', 'SUV', 'PANEL VAN', 'PICK UP DOUBLE CAB', 'STATION', 'MPV', 'BUS', 'MINI BUS HIGH ROOF', 'CARGO VAN', 'PICK UP SINGLE CAB', 'SALOON']
  pos4: ['K', 'A', 'C', 'Z', '5', 'H', '7', 'D', 'B', '6', 'E', '1', 'J', 'F', 'G', 'P', 'L', 'Y', 'S', 'W', '2']
  trim: ['GLI', 'PREMIUM', 'XLI EXECUTIVE MR', 'XLE', 'LE', 'VTX', 'XLI MID', 'PLATINUM', 'XLI', 'GLE-X', 'SE', 'HEV GLI', 'E PLUS HEV', 'XLI EXECUTIVE HEV', 'STD (NON GCC)', 'GLE', 'XL', 'PRO', 'GTX', 'LE HEV', 'DX', 'STD', 'XLI EXECUTIVE', 'GLE-X HEV 40TH ANNIV', 'XLE HEV', 'GLI HEV', 'SEDAN', 'S', 'GL', 'DLS', 'SR5 (NON GCC)', 'VT', 'EXR', 'DL', 'HYBRID (NON GCC)', 'ADVENTURE', 'GLE HEV', 'GXR MID', 'LWB', 'SS', 'STANDARD', 'LE (NON GCC)', 'GLI MR HEV', 'DLX', 'XLI TOP', 'GXR', 'GL DECKLESS', 'ADVENTURE 1ST EDITION', 'DLS - STD ROOF', 'SE+', 'E', 'LUMIERE HEV', 'GLX', 'SPORT', 'LWB HIGH ROOF', 'EX', 'X', 'FR-S (NON GCC)', 'VX', 'GX', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['RKL', 'JTD', 'LFM', '7MU', 'JF1', 'JTB', 'LFP', 'JTN', 'JTM', '4T1', 'LXG', 'LKL', 'LZW', '7SV', '3TY', 'LSK', 'MB1', 'SAL', 'L3H', 'ZGU', 'LGF', 'LM6', '5TD', 'LET', 'LK6', 'LA6', 'LSY', 'LHP', '1GC', '4TI', 'LFZ', 'NMT', 'MHK', 'LJ1', 'YSM', 'AS3', 'JTJ']
  VDS: ['KAAAG0', 'KUAAG7', 'KAAAG9', 'ACABF5', 'AAA0C7', 'AFAAF1', 'CAAAGO', 'CAAAG0', 'KUAAG6', 'KAAAG8', 'ZNAA12', '53AEB1', 'AFAAF0', 'KAAAG3', 'KAAAG4', 'ACABF6', 'ACABFX', 'AAA0C5', 'CAABG0', 'KAAAG2', 'AAADC3', 'KAAAG6', 'H4ACP0', '53AEA1', 'CAAAG7', 'KAAAG5', '72AEB2', 'AFAAF4', 'AAA0CX', 'DAABGX', 'AAA0C6', 'AAAAF7', 'BZAHKX', 'AAA0C9', 'ASACK7', 'KCAAG8', 'AFAAF7', 'KAAAGO', 'A1ACC6', '53AEB2', 'AFAAF6', 'AXACC2', 'ACABF2', 'AAA0C8', 'KAAAG7', 'KAAAG1', 'AFAAF5', 'AAA0C4', 'AAAAG3', 'KCAAG5', 'AAAAA9', 'ZNAA13', 'DBADK5', 'AAA0C2', 'AAAAG2', 'AAAAG9', 'CPA509', 'KAAAGX', '64AEB2', 'A1ACC2', 'BZAHK1', '53AEBI', 'DAACK6', 'ACABF9', 'AAA0C1', 'ZNAA15', 'AXACC6', 'AXACC0', 'ZNAA10', 'ACAAU6', 'A1ACC0', 'AAABG0', 'AAA0C3', 'ACAAUX', 'ACABF0', 'AAAAFO', 'AAABG9', 'A1ACCO', 'EAAAGX', '1AAA66', 'CAABG9', 'CBAGA2', 'CAAGAX', 'AAABA7', 'DAACK3', 'A1ACC5', 'KCAAG9', 'AEACH7', 'AFAAF2', 'JDAHNX', 'AAAAF4', 'BZAHK4', 'AAA0C0', 'FBABG3', 'AFAAF9', 'KCAAGX', 'ZNAA14', 'AXACC5', 'KCAAG0', 'ACABF1', 'A1ACC1', 'BZAHK0', 'AAAAA2', 'G4AC10', 'AFAAF8', 'CAABG8', 'KUAAG1', 'KUAAG3', 'KUAAGB', 'CAABGX', 'ZNAA19', 'BAABG8', 'A1ACC3', 'PAAWA2', 'CAABG1', 'ACABF7', 'AAAAF2', 'AYACC6', 'AAABA9', 'AAABA2', 'CBAGA6', 'KCAAG6', 'ZNAA16', 'AFAAF3', 'ACABF8', 'BAABG5', '72AEA1', 'AAABG5', 'BAABG6', 'KCAAG4', 'AAAAG4', 'CAAAG3', 'KAAAC7', 'LSAAE4', 'KCAAG3', 'AYACC9', 'PBAJA9', 'KBAAGX', 'AYACC3', 'PBAJA1', 'KUAAG9', 'AAABG2', 'ECABA0', 'DAABG0', 'KZA006', 'AAABA6', 'ACABF3', 'AXACC9', 'AFAAFX', 'DAABG9', 'AXACCO', 'AXACC7', 'FDABB8', 'KUAAG8', 'KUAAG4', 'AAABA3', 'BZAHK9', 'BAABG0', 'AAABA4', 'BZAHK7', 'BZAHK2', 'B7A2J4', 'AAABGX', 'KUAAGX', 'AYACC7', 'DAACK8', '53AFB1', 'AFABF9', 'AAAAFX', 'YKACC0', 'KAAAGB', 'ACABF4', 'DAAAG2', 'ACAAJ4', 'AAAOC8', 'AAABA5', 'CAAAGX', 'AEAA16', 'ADAE2X', '1BAA33', 'DAACK7', 'KCAAG7', 'AAAB58', 'ZNAA1X', 'HDAAA1', 'KUAAG5', 'SFABD9', 'AAAAG7', 'AEACH0', 'AAAAG6', '11AC10', 'ZNAA17', 'AXACC3', 'AAAAF5', 'H4ACP2', 'DAACK2', 'KCAAGO', 'ZNAE17', 'WGAFP8', 'AXACCX', 'KCAAG2', 'FBABG2', 'AAAAG1', 'PAAWA5', 'EDABB3', 'CAABGO', 'CAABG7', 'SBAS3X', 'PBAJA7', 'KAAA60', '63AL59', '63AL55', 'AAABAX', 'KZABX8', 'A1ACC9', 'EFABF0', '1BAA34', 'AYACC8', 'LAAA44', 'ACABFO', '1BAA38', 'FDA882', 'FDAB82', 'AFAAFO', '1BAA37', 'AAAAF8', 'E6A3U3', 'EDABB8', 'EFAVS3', 'ZNAA18', 'BAAAG7', 'YFAG20', 'ACAAU7', 'DAABG4', 'AAAAF1', 'AXACC4', 'CAAAG5', '21AS32', 'AAAAF0', 'DFAEV9', '63AL46', 'AGACH8', 'DAACK0', 'LBACX1', 'ACAB52', 'AAAA55', 'ACAAU3', 'FBABG6']
  Model_Year: ['M', 'R', 'S', 'P', 'N', 'E', 'X', 'V', 'L', '5', 'W', 'T', 'H', 'K', 'F', 'D', 'G', 'A', 'C', '3', 'J', '8', '1']
  Plant_Code: ['0', '3', 'V', '8', '2', '4', 'A', 'U', 'C', 'X', 'T', 'E', 'H', 'M', 'S', '9', 'B', 'K', 'J', '1', 'D', 'R', 'G', 'L']
  Serial_Number: ['500885', '518858', '507269', '510240', '002936', '634083', '001582', '016446', '642961', '400827', '510417', '517358', '702115', '062137', '001671', '501187', '063188', '515509', '004016', '502853', '010314', '519883', '677109', '048508', '508295', '501374', '683409', '518597', '510923', '519688', 'A39732', '191808', '031851', '506196', '000935', '501223', '508278', '518610', '004380', '005156', '053542', '610774', '001118', '007310', '081104', '638867', '054407', '005464', '008390', '017933', '607042', '003562', '049875', '504385', '665506', '002621', '523077', '002414', '519489', '101933', '515244', '509545', '508162', '007628', '016620', '000720', '506557', '016444', '512861', '485841', '000834', '004353', '517208', '500511', '691134', '507921', '522745', '517637', '007482', '001691', '604839', '012074', '523392', '061613', '032841', '704900', '523504', '594344', '184134', '643245', '001857', '007659', '062500', '007590', '513050', '198620', '508433', '001360', '500231', '491526', '184195', '057259', '020182', '202260', '022924', '031306', '001596', '213030', '510286', '514909', '515957', '511224', '688751', '511100', '002972', '013842', '620769', '520703', '003287', '006825', '701819', '507952', '505389', '465981', '020530', '485563', '001716', '518549', '018617', '019123', '193850', '509958', '501448', '700259', '001075', '512026', '002086', '502131', '035150', '101877', '097413', '196617', '509803', '588813', '532796', '517198', '026622', '036052', '036142', '012200', '197959', '002505', '518962', '008473', '648619', '057635', '512441', '040775', '194482', '518115', '033795', '513155', '041885', '001005', '804011', '506194', '024611', '509097', '112559', '637644', '198416', '002289', '112974', '018077', '509621', '505135', '068376', '062556', '197053', '581381', '086176', '096630', '000675', '004284', '511828', '507222', '515156', '525243', '504201', '011195', '002119', '004038', '019945', '505727', '508018', '518890', '001865', '048155', '518880', '062419', '025734', '502747', '003485', '029145', '512023', '517136', '620889', '022044', '033808', '007686', '001958', '513396', '523596', '511658', '701579', '641457', '513427', '033004', '485168', '011655', '060304', '524904', '006111', '003792', '001262', '517399', '509078', '511110', '008022', '000530', '506334', '518126', '002092', '019590', '056496', '188933', '023937', '001317', '196486', '003934', '594305', '004165', '109460', '031070', '507384', '006455', '003504', '509699', '505022', '050850', '016614', '507512', '502788', '001772', '001565', '194285', '505861', '520132', '001226', '377887', '518573', '057643', '523542', '508349', '634281', '141836', '008936', '712416', '008718', '508435', '047983', '000547', '002434', '003022', '195657', '722642', '641351', '015135', '000464', '001664', '1L3073', '190788', '047819', '001514', '523850', '657590', '517753', '013657', '006372', '503280', '503887', '004575', '904769', '061595', '005833', '031037', '508469', '000963', '046467', '008119', '511269', '509478', '112239', '523028', '706400', '013716', '003916', '485843', '001458', '515859', '659374', '506577', '503428', '519375', '060850', '036416', '002672', '723758', '006794', '003619', '510536', '518917', '001575', '003848', '508190', '001139', '504875', '000273', '523825', '117983', '059492', '188746', '190900', '007074', '510179', '517305', '020414', '511638', '514105', '555352', '056565', '004971', '002015', '040566', '027962', '524761', '001103', '516328', '101111', '027269', '508963', '517411', '054417', '511889', '672701', '519827', '246591', '523147', '655966', '050288', '522929', '517465', '005614', '509552', '511764', '840944', '519001', '590506', '052235', '522423', '1D2206', '001473', '185039', '507187', '035287', '516208', '511869', '509368', '509113', '007272', '502886', '523847', '503522', '014922', '050499', '502758', '511404', '734662', '022680', '653593', '1D2256', '032526', '186353', '507421', '037056', '513579', '701022', '518709', '024438', '519776', '003081', '002940', '051686', '141403', '009728', '503668', '503277', '519031', '004485', '000968', '622237', '505385', '000115', '591581', '519760', '191373', '067132', '017711', '191997', '129473', '004243', '000670', '511565', '502866', '010243', '003459', '000386', '028330', '058691', '194826', '030093', '516507', '013279', '508822', '811783', '507418', '593272', '005212', '000533', '510517', '029154', '502797', '519679', '196223', '515673', '523032', '042705', '510473', '044641', '001964', '016394', '705092', '503222', '004063', '820701', '000455', '510837', '002526', '190533', '001487', '053963', '001678', '195887', '511810', '001117', '001567', '517312', '503923', '485935', '517993', '508089', '823661', '505849', '509024', '503497', '509687', '485015', '027949', '519873', '680826', '641886', '039700', '503733', '005632', '001973', '507166', '067589', '507293', '002707', '053889', '065221', '518200', '004589', '001593', '031279', '519128', '502679', '010468', '096394', '019459', '502310', '026351', '052317', '001097', '029141', '003971', '024449', '034796', '517824', '569502', '196471', '508895', '044450', '505836', '517065', '003881', '020391', '102050', '523160', '520303', '519094', '360155', '052486', '002199', '003371', '020851', '500626', '002394', '194176', '536187', '507363', '000444', '518882', '062480', '019124', '503305', '517068', '066558', '003606', '001021', '025726', '735457', '001008', '000348', '515076', '049765', '010087', '207022', '003006', '019658', '510935', '517269', '649884', '015265', '504863', '315776', '184430', '509712', '002054', '047600', '018707', '520409', '621836', '000137', '509506', '001856', '516762', '001727', '505031', '145207', '001389', '517649', '511175', '003767', '000416', '002065', '003446', '003700', '066952', '066962', '000793', '659672', '517642', '508182', '507428', '058214', '517185', '002323', '514042', '502041', '051565', '005325', '032028', '505027', '520278', '554982', '015961', '510641', '019712', '000928', '068255', '485261', '519629', '485319', '056392', '502768', '035719', '012325', '708780', 'N02791', '502629', '036393', '518256', '501514', '006210', '752976', '000953', '516718', '005315', '508317', '037263', '183139', '905977', '508889', '004505', '514345', '033745', '001115', '006765', '508312', '018096', '484137', '515199', '052649', '056234', '503300', '001033', '501993', '136294', '007373', '523653', '189651', '004498', '502794', '507555', '000059', '000053', '004104', '000131', '508126', '508552', '014344', '001221', '099277', '048123', '500502', '504219', '036137', '507091', '701269', '504514', '509461', '514913', '525109', '006641', '002033', '511048', '015925', '506535', '019016', '520175', '519845', '046813', '060404', '517493', '507285', '200150', '043847', '015722', '524625', '657593', '055982', '596625', '607090', '130715', '023367', '500468', '013015', '185978', '001263', '004138', '000829', '003757', '055472', '516908', '504214', '523816', '523614', '515049', '196075', '196834', '312997', '705032', '001448', '811653', '811780', '790653', '052916', '003247', '509018', '517351', '002369', '003012', '599430', '194228', '057593', '706506', '501872', '688390', 'A01516', '506173', '161426', '002858', '198543', '517349', '001530', '524644', '750937', '530570', '528887', '002785', '259579', '570803', '501409', '502842', '520945', '042777', '066055', '001056', '519933', '521073', '517827', '518373', '404531', '511841', '509115', '657241', '001011', '201188', '019806', '001150', '517003', '502762', '500579', '643823', '195769', '508974', '520178', '004570', '706707', '002765', '510993', '004357', '000392', '005280', '517506', '521493', '720184', '511155', '515650', '510652', '027341', '519671', '674712', '007526', '149515', '520902', '645798', '004170', '002916', '523940', '008933', '007433', '528891', '014974', '004372', '520679', '035931', '063895', '516868', '038320', '001152', '512631', '130118', '004232', '018133', '001412', '064270', '001022', '507662', '1A1804', '523415', '501950', '000385', '591582', '190298', '528741', '048283', '503981', '503634', '700024', '020432', '517383', '716297', '044723', '001043', '000776', '000906', '000231', '065421', '519838', '510155', '505039', '507957', '514935', '724934', '054474', '658744', '712899', '065232', '032380', '516961', '025427', '502389', '502383', '503681', '532290', '507567', '001694', '500926', '009681', '1K9135', '005845', '520097', '523462', '709169', '001185', '001155', '005068', '517415', '523135', '560333', '057519', '111674', '058438', '058419', '648508', '505488', '009289', '001091', '056001', '003797', '363376', '001198', '002108', '016575', '514684', '036559', '520069', '183648', '519908', '218202', '513441', '703557', '508428', '787701', '522387', '001883', '004602', '523801', '517631', '502350', '035708', '062496', '501964', '508395', '516357', '003734', '509745', '510388', '690803', '003807', '001156', '003222', '594359', '433370', '067815', '679630', '517447', '002791', '882808', '514318', '510301', '191156', '059606', '711415', '487878', '507934', '001616', '000357', '064882', '004418', '705505', '000178', '501281', '041946', '003108', '517380', '197683', '002214', '523560', '190426', '506571', '518329', '516982', '511494', '198214', '505963', '184921', '003234', '703274', '704500', '008733', '027440', '001433', '517354', '508350', '509894', '517331', '015353', '003775', '503800', '015510', '007467', '009025', '502247', '508225', '520739', '004764', '514333', '003560', '504206', '660140', '013484', '196914', '015670', '517688', '050212', '064041', '510971', '508073', '503463', '003959', '716837', '002510', '511027', '521788', '001603', '517015', '030814', '507539', '001046', '501204', '002642', '584139', '118997', '658724', '524248', '004127', '194937', '012940', '518385', '197944', '002036', '189665', '004157', '001000', '138103', '153103', '653496', '501619', '503622', '048231', '002046', '056509', '001244', '187174', '014008', '068486', '508982', '510254', '501273', '702431', '815325', '001017', '024850', '516871', '504904', '049815', '707826', '509749', '704680', '001726', '504889', '057004', '659145', 'N04067', '190783', '509103', '042266', '511024', '002906', '001031', '516531', '003542', '501324', '511440', '015304', '002833', '824260', '002758', '034556', '004403', '018567', '521531', '510527', '001438', '001589', '509335', '017687', '196918', '515700', '507519', '021017', '518338', '063574', '641425', '509642', '505514', '054849', '030181', '510314', '500821', '510452', '510682', '005157', '001844', '001127', '004715', '053208', '012354', '030715', '507172', '502594', '057694', '500974', '001254', '007669', '001762', '061763', '492449', '035486', '002506', '003032', '002899', '000436', '521745', '517045', '017448', '518683', '024946', '002862', '196543', '657601', '066864', '733420', '001296', '185146', '502178', '509872', '001781', '517840', '028650', '064829', '511113', '657502', '183027', '518150', '524223', '006186', '511650', 'S22323', '001941', '500800', '520073', '505178', '505264', '705631', '036350', '018290', '523403', '051058', '002471', '001766', '239763', '511039', '036242', '007230', '516898', '507760', '517321', '002450', '495135', '519659', '509589', '002077', '006958', '517671', '516802', '711281', '516736', '509090', '500478', '517389', '001526', '600911', '510291', '003511', '113886', '485856', '064751', '000102', '504366', '517953', '702021', '524147', '502838', '521144', '002743', '057712', '545785', '003603', '705369', '525059', '510613', '517528', '064316', '507716', '511506', '597378', '510090', '001086', '004376', '002754', '516843', '517408', '502048', '507256', '502033', '517655', '516607', '516985', '064723', '500921', '001604', '519795', '502722', '659183', '007853', '509609', '005868', '517157', '064895', '520416', '503891', '000607', '520488', '070740', '517606', '654427', '510014', '503438', '036469', '062187', '681195', '517181', '043683', '187583', '502082', '001520', '025981', '508912', '510049', '509120', '520948', '517726', '000991', '055621', '503386', '704267', '508947', '002468', '004620', '025882', '001817', '001203', '503702', '002610', '007191', '001390', '516773', '005189', '005199', '705646', '718410', '007011', '014983', '001406', '518071', '012821', '707394', '008996', '071620', '504625', '578410', '504370', '001635', '004860', '016315', '013492', '597232', '904643', '002539', '002974', '002301', '524285', '007254', '706397', '504767', '001835', '002599', '507049', '010248']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,K,GLI,GCC,5.0,RKL,KAAAG0,M,0,500885
1,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,K,GLI,GCC,5.0,RKL,KAAAG0,R,0,518858
2,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,K,GLI,GCC,5.0,RKL,KUAAG7,S,0,507269
3,TOYOTA,COROLLA CROSS,4.0,SUV- CROSSOVER,K,GLI,GCC,5.0,RKL,KAAAG9,P,0,510240
4,TOYOTA,CROWN,4.0,SEDAN,A,PREMIUM,GCC,4.0,JTD,ACABF5,P,3,002936
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,TOYOTA,COROLLA CROSS,4.0,SUV,K,GLI,GCC,NaN,RKL,KAAAG1,N,0,504767
1272,TOYOTA,CROWN,4.0,SEDAN,A,PLATINUM,GCC,NaN,JTD,AFAAF4,P,3,001835
1273,TOYOTA,CROWN,4.0,SEDAN,A,XLE,GCC,NaN,JTD,ACABF2,P,3,002599
1274,TOYOTA,COROLLA CROSS,4.0,SUV,K,GLI,GCC,NaN,RKL,KUAAG4,S,0,507049
1275,TOYOTA,CROWN,4.0,SEDAN,A,XLE,GCC,NaN,JTD,ACABF1,S,3,010248

====================================================================================================
pos6: T
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['PRIUS', 'FJ CRUISER', 'FORTUNER', 'LAND CRUISER', 'FLTRXS', 'CAMRY', 'RAIZE']
  bodyType: ['HATCHBACK', 'SUV', 'MOTORCYCLE', 'SEDAN', 'MPV']
  pos4: ['K', 'B', 'A', '1', 'T']
  trim: ['STD (NON GCC)', 'BASE', 'TOP', 'C (NON GCC)', 'VXR', 'EXTREME', 'ECO', 'ICONIC', 'GLE', 'DYNAMIC', 'EXR', 'LIMITED HEV', 'S', 'TURBO G RA']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTD', 'JTE', 'JN8', 'JTM', '5HD', 'MK2', 'LZY', '4T0', 'MHK']
  VDS: ['KDTB35', 'KDTB30', 'BUT1F9', 'AYT30L', 'KDTB38', 'KDTB37', 'KDTB34', 'KDTB31', 'KDTB32', 'KDTB33', 'KDTB39', 'AUTBJ4', 'KDTB3X', 'BUTTF4', 'BUTTF1', '1KTP45', 'KDTB36', 'K6T1Y6', 'TDTD69', 'BFTFK0', 'BUTTF7', 'AATBA9', 'BUTIFI']
  Model_Year: ['C', '8', '7', 'D', 'E', 'F', 'S', 'L', 'K', 'H', 'G', 'N', 'V', '9', 'P']
  Plant_Code: ['1', 'K', 'W', '4', 'B', 'N', 'U', 'J']
  Serial_Number: ['503530', '016571', '014517', '101501', '400168', '028858', '548373', '560880', '047344', '101072', '004815', '023048', '513896', '017693', '106907', '075713', '511607', '144029', '110957', '583837', '021481', '056613', '627186', '033928', '098704', '621391', '550078', '593411', '017365', '129921', '141116', '065572', '590065', '551513', '517888', '535364', '534341', '553515', '081253', '517597', '022812', '574607', '001997', '535164', '506532', '031458', '030726', '134840', '505789', '523756', '549237', '052383', '089782', '061175', '025647', '550569', '568288', '512110', '062237', '500175', '508046', '031142', '089252', '535388', '046277', '000869', '100354', '521388', '512816', '051723', '022289', '015162', '003852', '088497', '000084', '046134', '038839', '574764', '002643', '085749', '047063', '120454', '040594', '034348', '565773', '534617', '013913', '517711', '069948', '580801', '023529', '567328', '501710', '071415', '016928', '102805', '507916', '536274', '025194', '022820', '264280', '056911', '089901', '015467', '027361', '555313', '123206', '040838', '501204', '075742', '545063', '085190', '517265', '001044', '514062', '003701', '127571', '054469', '074720', '069204', '169293', '501658', '040392']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),GCC,5.0,JTD,KDTB35,C,1,503530
1,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),GCC,5.0,JTD,KDTB35,C,1,016571
2,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),GCC,5.0,JTD,KDTB30,C,1,014517
3,TOYOTA,FJ CRUISER,6.0,SUV,B,BASE,GCC,5.0,JTE,BUT1F9,8,K,101501
4,TOYOTA,FORTUNER,4.0,SUV,A,TOP,GCC,5.0,JN8,AYT30L,7,W,400168
...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,TOYOTA,PRIUS,4.0,HATCHBACK,K,C (NON GCC),GCC,5.0,JTD,KDTB37,E,1,074720
119,TOYOTA,PRIUS,4.0,HATCHBACK,K,C (NON GCC),GCC,5.0,JTD,KDTB38,E,1,069204
120,TOYOTA,FJ CRUISER,6.0,SUV,B,EXTREME,GCC,5.0,JTE,BUTIFI,D,K,169293
121,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),NON-GCC,NaN,JTD,KDTB3X,C,1,501658
122,TOYOTA,PRIUS,4.0,HATCHBACK,K,STD (NON GCC),NON-GCC,NaN,JTD,KDTB32,D,1,040392

====================================================================================================
pos6: X
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['IQ', '4RUNNER', '86', 'CAMRY', 'COROLLA', 'HIACE', 'SCION', 'AVALON', 'TOYOTA', 'HILUX', '2012', 'SIENNA', 'TOYOTA SCION', 'PRIUS', 'TOYOTA IQ', 'ZELAS', 'TOYOTA SQUIN', 'YARIS', 'COUPE', 'TOYOTA 86']
  bodyType: ['HATCHBACK', 'SUV', 'COUPE', 'SEDAN', 'MINI BUS', 'MINI BUS HIGH ROOF', 'PICK UP DOUBLE CAB', 'MPV', 'SALOON', 'PANEL VAN']
  pos4: ['J', '5', 'G', 'P', '0', 'W', 'S', 'H']
  trim: ['STD (NON GCC)', 'SR5 (NON GCC)', 'GT', 'STD', 'XLI', 'DX', '2400', 'GL', 'SE', 'DLX', 'FULL OPTION', 'DLS', 'LE (NON GCC)', 'S', 'GLS TOP', 'LS', 'N', 'MID', 'CAR TRIM', 'SGLX', 'S T1', 'GLI', 'BASE']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTN', '6T1', 'YS2', '9BS', 'WMA', '4T2', 'KNC', '1C4', 'KMF']
  VDS: ['JJXB01', 'JJXB03', 'JJXB09', 'JJXB05', 'JJXB06', '53XK20', 'JJXB04', 'G6X400', 'JJXB0X', 'JJXB02', 'P6X400', '06XZZ1', 'JJXB07', 'JJXB00', 'JJXB08', 'G4X205', '53XH10', 'WJX74A', 'SHX74C', 'WJX76A', 'HJXEN7', 'W8X7K8', 'JJX801', 'G4X20X', '06XZZX']
  Model_Year: ['D', 'C', 'E', 'W', '5', 'A', '7', 'R', 'V', 'X', 'B', 'L', 'M', 'N', 'S', '9']
  Plant_Code: ['J', 'X', '5', '3', 'P', '0', 'K', 'W', 'U']
  Serial_Number: ['022804', '019160', '022596', '030387', '024080', '027051', '651486', '026685', '026092', '026388', '316388', '023255', '013169', '011204', '557989', '027570', '020763', '027825', '602629', '025691', '011665', '021254', '027999', '024448', '018785', '015206', '025151', '030298', '015480', '023762', '016775', '029297', '013065', '724983', '025715', '035288', '028862', '028042', '652312', '019206', '021450', '028560', '018423', '017588', '542474', '491460', '009624', '016124', '019146', '030282', '035588', '438600', '014112', '011396', '016602', 'B32855', '832855', '652405', '018880', '017563', '025887', '018171', '028283', '469842', '020939', '022026', '026518', '016521', '009204', '016310', '027213', '016842', '026487', '019170', '022259', '010918', '012371', '016301', '027281', '020263', '010668', '024985', '011611', '017936', '021083', '020890', '024653', '014751', '020206', '011159', '019552', '011921', '017899', '582587', '020404', '028267', '012929', '013824', '757323', '017175', '027081', '026384', '022423', '022708', '127148', '022353', '011760', '024899', '015027', '012265', '010994', '027340', '016831']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,IQ,4.0,HATCHBACK,J,STD (NON GCC),GCC,3.0,JTN,JJXB01,D,J,022804
1,TOYOTA,IQ,4.0,HATCHBACK,J,STD (NON GCC),GCC,3.0,JTN,JJXB03,C,J,019160
2,TOYOTA,IQ,4.0,HATCHBACK,J,STD (NON GCC),GCC,3.0,JTN,JJXB09,D,J,022596
3,TOYOTA,4RUNNER,6.0,SUV,J,SR5 (NON GCC),GCC,5.0,JTN,JJXB05,E,J,030387
4,TOYOTA,IQ,4.0,HATCHBACK,J,STD (NON GCC),GCC,3.0,JTN,JJXB06,D,J,024080
...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,TOYOTA,TOYOTA IQ,4.0,HATCHBACK,J,STD (NON GCC),NON-GCC,NaN,JTN,JJXB03,C,J,015027
110,TOYOTA,TOYOTA 86,4.0,COUPE,J,STD,NON-GCC,NaN,JTN,JJXB04,C,J,012265
111,TOYOTA,TOYOTA IQ,4.0,HATCHBACK,J,STD (NON GCC),NON-GCC,NaN,JTN,JJXB07,C,J,010994
112,TOYOTA,TOYOTA IQ,4.0,HATCHBACK,J,STD (NON GCC),NON-GCC,NaN,JTN,JJXB08,E,J,027340
113,TOYOTA,TOYOTA IQ,4.0,HATCHBACK,J,STD (NON GCC),NON-GCC,NaN,JTN,JJXB09,C,J,016831

====================================================================================================
pos6: U
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'LAND CRUISER', 'YARIS', 'COASTER', 'HIACE', 'LAND CRUISER PICK UP', 'PRADO', 'CAMRY', 'RAV4']
  bodyType: ['PICK UP SINGLE CAB', 'SUV', 'HATCHBACK', 'SEDAN', 'PICK UP DOUBLE CAB', 'STATION', 'BUS', 'PANEL VAN', 'VAN', 'PICK UP', 'PICKUP']
  pos4: ['3', '1', 'K', 'J', '4', '2', 'I', 'T', 'M']
  trim: ['DLX', 'GXR', 'STD', 'TOP', 'SE TRD AERO PK', 'GX', 'SE', 'MID', 'SV', 'PREMIER', 'GL', 'DLS', '1', 'GL2', 'S', 'GLE', 'PICK UP', 'VX', 'EX', 'G', 'SE+', 'LX']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTB', 'JTD', 'VNK', 'LA7', 'LJN', 'LAZ', 'LNB', 'JT8']
  VDS: ['31UNE6', '33UNG0', '11UJ83', '11UJ80', 'KTUD36', '33UNE0', 'KTUD32', 'KTUD31', '11UJA0', 'KTUD39', '1CUG30', 'KTUD37', 'JTUD34', 'JTUD32', 'KTUD35', '41UB50', '33UNE6', 'JTUD38', 'KTUD30', '31UJ75', 'KTUD3X', 'KTUD38', 'KTUD34', 'JTUD35', '31UNE0', 'KTUD33', 'JTUD3X', 'JTUD33', '41UHB5', '11UJAO', 'JTUD36', '21UHB3', 'JTUD37', 'ITUJ80', 'TFUC57', 'TFUC51', 'TFUC5X', 'TFUC50', '31UNE2', 'TFU2K0', 'TGUB23', '31UNG0', 'JTUD31', '11UJ94', '33UNGO', '21UJ70', '1CU837', '1CU835', 'JTUD30', 'JTU031', 'MCUBK9', '33UNEQ', '1AU933']
  Model_Year: ['W', 'V', 'X', 'D', 'F', 'E', 'P', 'C', 'K', 'G', 'J', 'H', 'R', 'A', 'S']
  Plant_Code: ['0', '5', '6', 'D', 'A', '9', '7', '3', 'N', 'T', '1']
  Serial_Number: ['001590', '001175', '005601', '009889', '003099', '006173', '550619', '033800', '007109', '009228', '043793', '555467', '006444', '007650', '578318', '059581', '521233', '010081', '101231', '056545', '018728', '008626', '578026', '002630', '006649', '544262', '008563', '000125', '004931', '091903', '501058', '000385', '009252', '001831', '012006', '538187', '002939', '531283', '528508', '000995', '105563', '003920', '008646', '080511', '035514', '003243', '513854', '007235', '025763', '596488', '072165', '010248', '011385', '006059', '008953', '010734', '561069', '004974', '064950', '069376', '543223', '005157', '011745', '565253', '011130', '002148', '503164', '100612', '033348', '039204', '513167', '557264', '005282', '001512', '009387', '011773', '005503', '002641', '009961', '006808', '006374', '009240', '534349', '024164', '005795', '001660', '005355', '046579', '002357', '006733', '006790', '002388', '004250', '009981', '029845', '007885', '005662', '007138', '011578', '005028', '009334', '102877', '002541', '009645', '007271', '005958', '005045', '000700', '003811', '027802', '545702', '581079', '574587', '047728', '002036', '005760', '548342', '503012', '553585', '002871', '009253', '003421', '007482', '000169', '008968', '006908', '060969', '012227', '035874', '008395', '557097', '001427', '003012', '009268', '568745', '004459', '546851', '014911', '007644', '084873', '004117', '004916', '027480', '550461', '008460', '512549', '002266', '002321', '011375', '525281', '002747', '091539', '005491', '003546', '539106', '086396', '020315', '001307', '004735', '069214', '002600', '025953', '006469', '577730', '006973', '064459', '008396', '003281', '083756', '010411', '008231', '005697', '567830', '009838', '009336', '077219', '089606', '003975', '004109', '0S5752', '095752', '506876', '010013', '007585', '008035', '522143', '332554', '331903', '002931', '512206', '010497', '331916', '332430', '570249', '001871', '546405', '012327', '018929', '012323', '013438', '023695', '009103', '006696', '002352', '013850', '006869', '541064', '079086', '001089', '003467', '024793', '507391', '015467', '025394', '556853', '562353', '095241', '004703', '008569', '105051', '004563', '523160', '007090', '005869', '010183', '592781', '026913', '011424', '003430', '001149', '587385', '010177', '536970', '002006', '003678', '025493', '001989', '001092', '012973', '013974', '007821', '003332', '005016', '000991', '003517', '011513', '551967', '008532', '001867', '021233', '100592', '559786', '004243', '011645', '007594', '005073', '011823', '012502', '521037', '011107', '006288', '007183', '001471', '026662', '009923', '002179', '591073', '009197', '001941', '553902', '000966', '006011', '500414', '002190', '519188', '007828', '510386', '006931', '006135', '003363', '012361', '009564', '100071', '545386', '007351', '002842', '502808', '008247', '007858', '513639', '020918', '035426', '011169', '003195', '012372', '094831', '516664', '009760', '010288', '008930', '570556', '006693', '006012', '007438', '006520', '032154', '012080', '101165', '570248', '009844', '083815', '001848', '001854', '004324', '561521', '029498', '026308', '550440', '001354', '010743', '006177', '008593', '001039', '007150', '082126', '005977', '545772', '008714', '009766', '003860', '009423', '010225', '009496', '004476', '006247', '014553', '092824', '033256', '012281', '005811', '541810', '010930', '009429', '000941', '562892', '009243', '007207', '006057', '102482', '563770', '008695', '006576', '008902', '007195', '006180', '008726', '021732', '006268', '586821', '559225', '001141', '001917', '002774', '001182', '009885', '556243', '581679', '007951', '003846', '009518', '007409', '001605', '007571', '007425', '005010', '560932', '074989', '001629', '593331', '008611', '011692', '008139', '013394', '098583', '000788', '002406', '003705', '594652', '076870', '595111', '002876', '579174', '001064', '001957', '009280', '012153', '080762', '025290', '150686', '563095', '005543', '048295', '002741', '041682', '564439', '009813', '520521', '020276', '025174', '036092', '013203', '084051', '011123', '000486', '002069', '082540', '531717', '570360', '009817', '010083', '043941', '008859', '010105', '001748', '010796', '014013', '029665', '004381', '003066', '080415', '543647', '002705', '078465', '004726', '014482', '515798', '003327', '009955', '001358', '003302', '001498', '034443', '010243', '532190', '008156', '150847', '002231', '010275', '009218', '007166', '505367', '006086', '002475', '047809', '004781', '012582', '011800', '001242', '096414', '001114', '008999', '005056', '003691', '524357', '012105', '012352', '002206', '063214', '002769', '036689', '000903', '007212', '002364', '002447', '009365', '007100', '008348', '585716', '044629', '523390', '001030', '005862', '574476', '064016', '012035', '009638', '103509', '023143', '576279', '011663', '000718', '001086', '016095', '010766', '082715', '001899', '009350', '592514', '520244', '011990', '574514', '003244', '575533', '575530', '010325', '530024', '007626', '007938', '527564', '001890', '566615', '009321', '007999', '012290', '515286', '004662', '012240', '006372', '003073', '010583', '011969', '008451', '025474', '008241', '010730', '005653', '004052', '030273', '008835', '001046', '171316', '572031', '523366', '002126', '056007', '010200', '010609', '001476', '007400', '003628', '012343', '044177', '006645', '011041', '003201', '010190', '092472', '006842', '056118', '008220', '566249', '009524', '003251', '006774', '553726', '011944', '010143', '000746', '003940', '008383', '001985', '029869', '580406', '010133', '539681', '006187', '008000', '007917', '010844', '001970', '005916', '006277', '039322', '004418', '001836', '543057', '011828', '038982', '011254', '007593', '003878', '562183', '034174', '062333', '008473', '522051', '011392', '550064', '001779', '101387', '007849', '034485', '011920', '011686', '006702', '009534', '027180', '007910', '011103', '004809', '014835', '014836', '029783', '008084', '006622', '000080', '527814', '011507', '005657', '569445', '083905', '005451', '014842', '009474', '069155', '002458', '004579', '001925', '007439', '580345', '526656', '574224', '003029', '011361', '006921', '088166', '502879', '006210', '030874', '010223', '591322', '010187', '013727', '505653', '008868', '504394', '018312', '025431', '012331', '002219', '000302', '001321', '006586', '008447', '005799', '003935', '009543', '022660', '021696', '010042', '006609', '010689', '071498', '000947', '525607', '000873', '003039', '008260', '006574', '029538', '009239', '035684', '007193', '522346', '630082', '506106', '004958', '013537', '571770', '014991', '005059', '008340', '003922', '001523', '007393', '015777', '506195', '001227', '008027', '590212', '014084', '086713', '577434', '008674', '034008', '003261', '021667', '015010', '008785', '004435', '074269', '064345', '000646', '040994']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,GCC,2.0,JTB,31UNE6,W,0,001590
1,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,GCC,2.0,JTB,33UNG0,W,0,001175
2,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11UJ83,V,5,005601
3,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,STD,GCC,2.0,JTB,31UNE6,X,0,009889
4,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11UJ80,V,6,003099
...,...,...,...,...,...,...,...,...,...,...,...,...,...
713,TOYOTA,HILUX,4.0,PICKUP,3,DLX,GCC,NaN,JTB,31UNE6,W,0,004435
714,TOYOTA,YARIS,4.0,HATCHBACK,J,SE,NON-GCC,NaN,VNK,JTUD3X,H,A,074269
715,TOYOTA,YARIS,4.0,HATCHBACK,K,SE+,NON-GCC,NaN,VNK,KTUD31,G,A,064345
716,TOYOTA,LAND CRUISER PICK UP,4.0,PICKUP,3,LX,GCC,NaN,JTB,31UJ75,V,3,000646
717,TOYOTA,YARIS,4.0,HATCHBACK,K,SE+,NON-GCC,NaN,VNK,KTUD38,F,A,040994

====================================================================================================
pos6: &
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX']
  bodyType: ['PICK UP DOUBLE CAB']
  pos4: ['B']
  trim: ['GL']
  regionalSpec: ['GCC']
  WMI: ['MR0']
  VDS: ['BU&CD4']
  Model_Year: ['M']
  Plant_Code: ['0']
  Serial_Number: ['119414']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,B,GL,GCC,4.0,MR0,BU&CD4,M,0,119414

====================================================================================================
pos6: O
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'COROLLA', 'HIACE', 'TOYOTA COROLLA', 'COROLLA 1.6', 'COROLLA 1.8', 'COROLLA 1.3', 'HILUX', 'TOYOTA COROLLA 1.6', 'SUPRA']
  bodyType: ['SUV', 'SEDAN', 'PANEL VAN', 'PICK UP DOUBLE CAB', 'MINI BUS', 'SALOON', 'COUPE', 'HALF PANEL VAN']
  pos4: ['H', 'B', 'E', '8', 'J', 'D']
  trim: ['GX', 'GLI', 'XLI', 'GLI HEV', 'VX', 'GL', 'SEDAN', '2.0L', 'LIMITED', 'DL', 'S', 'LE', 'GXR', 'SE+', 'AXL ', 'DX', 'STD (NON GCC)', 'STD', 'GT SPORT', 'GXR TOP', 'EXR', 'VXR', 'GXR TOP DMST', 'SE']
  regionalSpec: ['GCC']
  WMI: ['JT3', 'RKL', 'JTE', 'JTF', 'JTM', 'MNT', 'J1G', 'WZ1', 'JTG']
  VDS: ['HTO5J8', 'BBOBE8', 'BBOBE1', 'BBOBE9', 'HTOSJX', 'BBOBEI', 'HTO5J6', 'HXO2PX', 'BBOCEO', 'EBOBEO', 'HTO5J1', 'BBOCE8', 'BBOBE7', 'BAOBE3', 'BBOCE7', 'BAOBE7', 'HJO9J0', 'BBOBE6', 'BBOBE2', 'HTO5J9', 'BDOES4', 'BAOBE8', 'BBOBE4', 'BBOBE5', 'BBOBE3', 'HXO1J1', 'HXO9J8', 'BAOBE2', '88OCEX', 'BBOBEO', 'BBOBEX', 'JXOZP1', 'HTO5J4', 'BBOCE3', 'HTO5J5', 'HTO5J3', 'HXO2P7', 'DBOE08', 'HJO9J4', 'BBOCE1', 'BBOCE6', 'HYOSJS', 'HYO5JX', 'HTO5J0', 'BAOBE5', 'HXO2P6', 'BBOCE2', 'BAOBE1', 'BBOBEG', 'BAOBEX', 'HXO2P1', 'HJO9J9', 'HXO2P0', 'HXO2PG', 'HXO2P9', 'HYO5J3', 'HUOTJI', 'HTO5J2', 'JXO2P1', 'HTO5J7', 'HTOSJ3']
  Model_Year: ['Y', 'P', 'N', 'M', '7', '9', 'R', 'L', '5', '4', 'E', 'G', 'F', 'S', '8', '2', '6', 'K', '3', 'B', 'X', 'H', '1']
  Plant_Code: ['0', '2', '5', '1', '6', '3', 'W', '4', 'O']
  Serial_Number: ['106241', '046717', '044451', '036077', '115264', '042134', '103428', '041250', '003653', '050956', '038137', '051130', '036775', '008857', '003609', '042020', '005606', '010793', '077426', '021281', '001596', '176115', '047896', '003792', '008442', '063406', '030834', '005243', '613159', '000330', '041897', '038019', '001031', '028961', '035351', '004921', '032745', '073798', '056922', '046156', '002283', '013290', '038784', '051095', '040070', '035373', '002265', '001934', '015252', '055620', '041019', '004683', '017312', '102110', '039354', '041371', '015054', '009748', '068028', '101316', '013641', '003041', '051902', '033516', '045452', '045242', '010658', '046685', '016445', '033091', '047120', '013477', '030558', '075320', '077794', '021510', '029816', '034603', '000365', '043536', '038128', '058456', '056153', '002262', '038415', '001982', '029229', '039889', '004675', '037986', '006367', '006238', '025906', '111910', '040107', '036204', 'O3S4GI', '095506', '038771', '011709', '014182', '023962', '032962', '047145', '048480', '128079', '056621', '009738', '001839', '002567', '008598', '001700', '111278', '111544', '022132', '096780', '089261', '039233']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,6.0,SUV,H,GX,GCC,5.0,JT3,HTO5J8,Y,0,106241
1,TOYOTA,COROLLA,NaN,SEDAN,B,NaN,NaN,NaN,RKL,BBOBE8,P,0,046717
2,TOYOTA,COROLLA,4.0,SEDAN,B,GLI,GCC,4.0,RKL,BBOBE1,N,0,044451
3,TOYOTA,COROLLA,4.0,SEDAN,B,XLI,GCC,4.0,RKL,BBOBE9,M,0,036077
4,TOYOTA,LAND CRUISER,6.0,SUV,H,GX,GCC,5.0,JT3,HTOSJX,Y,0,115264
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTE,HTO5J4,7,2,111544
114,TOYOTA,HIACE,4.0,MINI BUS,J,GL,GCC,4.0,JTG,JXO2P1,9,0,022132
115,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTE,HTO5J7,6,2,096780
116,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,5.0,JTE,HTOSJ3,6,2,089261
117,TOYOTA,LAND CRUISER,8.0,SUV,H,VX,GCC,NaN,JTE,HTO5J7,3,2,039233

====================================================================================================
pos6: F
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'AVALON', 'HILUX', 'YARIS', 'INNOVA', 'RAV 4', 'COROLLA', 'RUSH', 'LAND CRUISER']
  bodyType: ['MINI BUS HIGH ROOF', 'PANEL VAN', 'VAN', 'CARGO VAN', 'MINI BUS', 'PANEL VAN HIGH ROOF', 'BUS', 'SEDAN', 'PICK UP DOUBLE CAB', 'MPV', 'SUV']
  pos4: ['L', 'R', 'S', '5', '1', 'W', 'E', '2', 'B', 'A', '7']
  trim: ['GL', 'GLS', 'DLS - STD ROOF', 'GLX', 'LIMITED', 'ADVENTURE', 'E', 'DLS HIGH ROOF', 'VXR', 'DLX', 'DLS', 'STD', 'SE', 'EX', 'GXR2']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTF', 'JCB', 'LJ1', 'LCF', 'MC1', 'MC2', '8LT', 'JJ7', '1C6', 'YV2', 'LFZ', 'JTE']
  VDS: ['LMFCP4', 'RMFAP7', 'LMFCP5', 'RMFAPX', 'LMFCP8', 'RMFAP9', 'LMFCPO', 'RMFAP6', 'LMFCP2', 'RMFAPO', 'LMFCP9', 'LMFCW1', 'RMFAP4', 'LMFCP3', 'LMFCP7', 'LMFCPI', 'SMFAP6', 'LMFCP6', 'LMFCP0', 'LMFCW8', '5AFKGT', 'SMFAP7', 'LMFCPX', 'RMFAP5', 'RMFAP1', 'RMFAP8', 'SMFAP1', 'SMFAP9', 'SMFAP3', 'RMFAP2', '1KFCD3', 'LMFCP1', 'W6FY16', 'RMFAP3', 'SMFAP0', 'RMFAPS', 'RMFAP0', 'SMFAP4', 'E4FDB8', 'RMFAW7', 'LMFCW4', '21FCL5', 'SMFAPX', '2EFV4M', 'SMFAP2', 'BDF1J0', 'SRFJT9', 'AUF0A9', '73FM49', 'SMFAP5', 'SMFAPO', 'ABFAJ7', 'ABFAJ0', 'SMFAP8']
  Model_Year: ['T', 'M', 'L', 'N', 'S', 'P', 'K', 'G', 'R', '7', 'V', '2', '5', '8']
  Plant_Code: ['6', '8', '2', '1', '0', 'P', '3', 'L', 'N', 'A', 'D', 'K']
  Serial_Number: ['014263', '004491', '002137', '005894', '003669', '009494', '008563', '004741', '001451', '007561', '007574', '003469', '001376', '003891', '001267', '011598', '001013', '003022', '006534', '004051', '001037', '006003', '005107', '002619', '004208', '003538', '003227', '003967', '011470', '003953', '356515', '005661', '003805', '003690', '001523', '004731', '002888', '009065', '006866', '009944', '004772', '002689', '009578', '004708', '003195', '007687', '001839', '007436', '006955', '001300', '010681', '005933', '003937', '002392', '004960', '002630', '005188', '001676', '006113', '005092', '004525', '003013', '002842', '005293', '005355', '004074', '001181', '006711', '002065', '006834', '002909', '009740', '116113', '008538', '009180', 'Z01349', '002808', '002936', '003798', '004541', '001389', '002900', '009902', '002923', '005807', '003550', '011866', '012277', '006945', '003950', '002195', '006593', '006193', '009765', '001371', '001023', '006430', '006423', '004589', '011382', '009649', '003882', '001142', '003075', '004943', '003664', '004957', '005317', '005199', '003346', '005626', '004564', '002277', '007674', '007074', '003914', '005413', '004164', '003752', '007676', '013469', '002792', '006124', '006015', '003182', '009195', '009635', '006236', '001538', '005856', '009294', '006963', '005776', '003657', '007567', '006476', '010085', '001056', '006789', '008607', '003753', '009212', '007673', '011660', '004762', '003036', '009000', 'O04069', '008909', '003770', '003951', '002178', '002328', '008179', '012343', '001935', '005243', '007664', '003642', '004701', '007918', '009078', '006328', '012058', '008840', '004069', '009646', '011563', '009444', '002730', '001956', '003600', '006039', '007925', '007915', '003856', '003406', '004011', '004783', '005668', '004272', '013881', '003230', '014145', '142791', '003051', '005896', '002637', '003701', '004975', '004076', '008081', '012251', '009117', '005927', '001963', '003516', '003053', '001026', '009272', '002520', '006464', '006550', '002927', '005881', '010344', '006715', '003665', '006340', 'BVTASY', '004555', '001599', '010736', '010712', '003838', '005766', '008104', '001882', '005253', '004079', '006806', '006841', '009659', '005751', '001539', '003746', '014138', '001479', '006807', '004409', '009977', '011679', '002895', '009236', '211855', '003624', '009380', '003203', '011197', '006751', '003351', '006623', '004942', '005360', '004280', '003367', '003588', '004640', '005459', '009366', '004299', '007499', '006204', '004019', '009656', '001534', '005749', '007593', '008917', '004781', '656388', '001966', '001957', '005228', '010749', '004152', '001929', '005613', '004015', '009545', '002166', '006231', '011830', '009685', '014270', '009671', '012245', '009631', '003715', '011622', '006063', '009200', '011799', '006182', '006522', '009663', '002679', '006413', '003830', '011501', '002882', '003688', '003572', '003989', '009257', '011787', '007969', '002981', '005596', '002777', '002847', '012045', '009228', '035212', '003655', '002442', '003954', '004489', '002867', '002426', '002935', '002942', '004119', '001247', '004085', '003662', '003680', '003898', '009466', '003678', '001491', '002742', '003173', '005829', '003685', '006079', '003904', '003368', '007508', '011960', '004954', '037710', '004037', '005686', '007654', '008523', '003825', '003336', '006818', '009434', '012113', '005003', '009376', '005415', '001970', '003993', '005424', '005821', '001205', '005391', '005309', '003892', '005602', '002938', '005448', '005900', '005378', '008509', '006446', '004788', '006172', '006190', '006191', '006862', '001313', '001245', '009785', '004325', '007276', '004928', '005694', '003887', '005580', '013942', '003187', '002228', '005858', '003985', '011730', '003774', '003695', '005516', '002835', '003651', '007564', '005198', '007711', '006324', '002974', '001276', '001999', '009369', '001642', '008154', '003043', '003705', '006034', '009438', '003886', '008024', '003613', '006353', '003495', '006177', '005574']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,6.0,MINI BUS HIGH ROOF,L,GL,GCC,4.0,JTF,LMFCP4,T,6,014263
1,TOYOTA,HIACE,4.0,PANEL VAN,R,GL,GCC,NaN,JTF,RMFAP7,M,8,004491
2,TOYOTA,HIACE,6.0,MINI BUS HIGH ROOF,L,GL,GCC,4.0,JTF,LMFCP5,L,6,002137
3,TOYOTA,HIACE,4.0,PANEL VAN,R,GL,GCC,5.0,JTF,RMFAPX,N,8,005894
4,TOYOTA,HIACE,4.0,VAN,L,GLS,GCC,5.0,JTF,LMFCP8,M,6,003669
...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,TOYOTA,HIACE,4.0,PANEL VAN HIGH ROOF,L,GLS,GCC,5.0,JTF,LMFCP3,M,6,003613
413,TOYOTA,HIACE,6.0,MINI BUS HIGH ROOF,R,GL,GCC,NaN,JTF,RMFAPX,P,8,006353
414,TOYOTA,HIACE,4.0,PANEL VAN,R,GL,GCC,5.0,JTF,RMFAP1,L,8,003495
415,TOYOTA,HIACE,4.0,PANEL VAN,R,GL,GCC,5.0,JTF,RMFAP9,N,8,006177
416,TOYOTA,HIACE,4.0,PANEL VAN HIGH ROOF,L,GLS,GCC,5.0,JTF,LMFCP5,N,6,005574

====================================================================================================
pos6: L
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['URBAN CRUISER', 'COROLLA', 'FJ CRUISER', 'INNOVA', 'YARIS', 'FORTUNER', 'STREET TRIPLE', 'GXL RA (STATION WAGON)', 'HILUX']
  bodyType: ['SUV', 'SEDAN', 'MPV', 'MOTORCYCLE', 'WAGON', 'STATION', 'PICK UP DOUBLE CAB']
  pos4: ['Y', 'T', 'B', 'V', 'A', 'Z']
  trim: ['GL', 'GLX', 'GLI', 'BASE', 'E', 'EXR', 'DTD', 'DL']
  regionalSpec: ['GCC']
  WMI: ['MBJ', 'JTE', 'MEJ', 'W1W', 'MPJ', 'SMT', 'JHH']
  VDS: ['YMLA22', 'YMLA24', 'YMLA21', 'YMLA28', 'YMLA29', 'YMLA20', 'YMLA27', 'YMLA26', 'YMLA23', 'YMLA2X', 'YMLA25', 'TMLA21', 'BUL1F1', 'YMLAZ7', 'V0LEZ3', 'V0LEZ4', 'TTL136', 'AALAJA', 'ZCL2H9']
  Model_Year: ['R', 'S', 'T', 'P', '9', 'F', 'N', 'L', '6', 'H']
  Plant_Code: ['T', 'K', '3', 'E']
  Serial_Number: ['112408', '129782', '108222', '127756', '107436', '117974', '126445', '118082', '126281', '133127', '112187', '102745', '124502', '120840', '109595', '127481', '136704', '117860', '102586', '102641', '111847', '140197', '106488', '102622', '106715', '107444', '110407', '114731', '109156', '117279', '126586', '124862', '107684', '106803', '140975', '105042', '105440', '123360', '118186', '115508', '101671', '109070', '126410', '111438', '120561', '102178', '118720', '109271', '109101', '126684', '112620', '127693', '118239', '102830', '106081', '119592', '106804', '108624', '125863', '109022', '117850', '122106', '117851', '126099', '122706', '141500', '119495', '133251', '108814', '109972', '106107', '116273', '106600', '101975', '118676', '125972', '111197', '125450', '111140', '110574', '112027', '102724', '118288', '106694', '108539', '108090', '109023', '108071', '115048', '108591', '110846', '126040', '121873', '121784', '106574', '106756', '102277', '113522', '119669', '118681', '120593', '122160', '121116', '106554', '121887', '102232', '109246', '105134', '109499', '104882', '118489', '121210', '106848', '111793', '112256', '110429', '116362', '118102', '106096', '104746', '105887', '121666', '105975', '114213', '106797', '108808', '112128', '113613', '108375', '105092', '107390', '123170', '123711', '057696', '119737', '115009', '104803', '126073', '116503', '107804', '120053', '102568', '111593', '126251', '106257', '121336', '120035', '108006', '120023', '106284', '111097', '118325', '107772', '107110', '108738', '108828', '123779', '102419', '106565', '120893', '105653', '109279', '105056', '101537', '116531', '120298', '118228', '105513', '141930', '118523', '123538', '109729', '143885', '115836', '108449', '125418', '105370', '106830', '108868', '121105', '124905', '105199', '106667', '116131', '125758', '120708', '110709', '122195', '109518', '124139', '115549', '122547', '107580', '120939', '107396', '125584', '108996', '105009', '109457', '120688', '107104', '124248', '121132', '122144', '105032', '105204', '118430', '107044', '109134', '108363', '124907', '106411', '104982', '122508', '102519', '125358', '120182', '106264', '125697', '122731', '114976', '114618', '114934', '114856', '105769', '101843', '119309', '104970', '144549', '120973', '118004', '121991', '122755', '119366', '107691', '104960', '125384', '126749', '121048', '105673', '108216', '134070', '123973', '108477', '130306', '102317', '119080', '121926', '937952', '122865', '117824', '111922', '104807', '120879', '106712', '120133', '124300', '740401', '126171', '117727', '104814', '105787', '105423', '122434', '104891', '108015', '137790', '107271', '107450', '121081', '125991', '115094', '101969', '102261', '112403', '123607', '110967', '122449', '121726', '107215', '106567', '138230', '125276', '106422', '107599', '123919', '119196', '119983', '110259', '102507', '105102', '124710', '107968', '617240', '120285', '105418', '125182', '124096', '104954', '108299', '115325', '116203', '109250', '107152', '122129', '110997', '117011', '111106', '107015', '102462', '126545', '108679', '124382', '106317', '125305', '104862', '122820', '104992', '105317', '137455', '105182', '123058', '107167', '117773', '116930', '121249', '123487', '120935', '124416', '107782', '114875', '108483', '107222', '106214', '123881', '125076', '122359', '122533', '111528', '032287', '101104', '121349', '105746', '124893', '114569', '124354', '107065', '105740', '117143', '107153', '123214', '124572', '107989', '124547', '117215', '123722', '108228', '116688', '123720', '119634', '107055', '108153', '124814', '118584', '105565', '105310', '107711', '106522', '141824', '106911', '117120', '110808', '122397', '108073', '105777', '123313', '109294', '102209', '10771T', '106070', '107456', '117346', '131074', '114552', '107074', '110158', '123149', '142197', '119291', '109439', '109721', '120414', '118508', '117434', '113911', '104884', '121277', '108816', '140736', '120881', '122348', '007884', '117036', '124207', '118542', '106375', '124125', '106727', '100486', '121703', '107928', '126713', '101727', '119453', '105634', '117255', '122667', '121022', '117157', '116619', '106306', '116149', '108308', '142494', '105915', '124774', '119598', '108804', '106072', '123093', '120467', '102252', '121721', '107466', '120563', '121978', '120518', '116834', '122876', '106791', '108793', '108856', '108001', '119221', '107925', '123092', '124844', '121782', '118123', '115770', '101547', '104941', '114850', '102546', '107517', '105279', '107949', '123621', '122498', '106518', '124996', '125266', '107882', '115897', '124762', '116579', '105681', '123422', '107605', '121534', '124107', '108012', '120799', '123665', '108503', '122456', '106740', '123794', '107733', '112231', '107787', '123613', '108382', '124821', '128123', '123145', '107639', '115882', '122931', '107773', '136774', '107484', '116635', '102572', '105270', '124544', '106157', '122127', '120724', '100103', '121804', '121530', '110125', '114524', '107117', '108316', '123386', '119391', '136863', '121290', '117232', '107796', '107347', '115122', '122398', '118333', '107302', '105254', '121915', '124959', '120969', '108735', '106192', '108167', '105855', '107019', '102487', '102541', '108606', '108293', '123081', '107972', '117576', '119235', '106579', '125850', '101469', '124067', '106581', '106693', '124445', '123449', '120846', '101405', '106427', '106195', '121616', '121960', '108282', '107867', '108322', '111561', '117739', '122585', '121688', '107359', '106881', '107248']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GL,GCC,NaN,MBJ,YMLA22,R,T,112408
1,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,5.0,MBJ,YMLA24,S,T,129782
2,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA21,R,T,108222
3,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,5.0,MBJ,YMLA24,S,T,127756
4,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GL,GCC,5.0,MBJ,YMLA24,R,T,107436
...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA20,S,T,122585
554,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA25,S,T,121688
555,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA21,R,T,107359
556,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GL,GCC,NaN,MBJ,YMLA29,R,T,106881
557,TOYOTA,URBAN CRUISER,4.0,SUV,Y,GLX,GCC,NaN,MBJ,YMLA23,R,T,107248

====================================================================================================
pos6: I
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['AVALON', 'TOYOTA VELOZ', 'FJ CRUISER', 'CAMRY', 'HILUX', 'HIACE', 'COROLLA', 'RAIZE']
  bodyType: ['SEDAN', 'STATION', 'SUV', 'PICK UP DOUBLE CAB', 'MINI BUS HIGH ROOF', 'PICK UP SINGLE CAB']
  pos4: ['B', 'A', 'E', 'H', '8', 'T', 'C']
  trim: ['SE+', 'TOP', 'GLX', 'GL', 'GLE', 'GLI TOP', 'SE', 'XLI MID', 'LIMITED PREMIUM', 'E', 'DLX', 'XLE TOURING']
  regionalSpec: ['GCC']
  WMI: ['4T1', 'MHF', 'JTE', '1FT', '4TI', 'JTG', '211', 'JT2', 'MHK', 'MR0']
  VDS: ['BKIEB8', 'ABIBY7', 'BUIIF9', 'BFIFK3', 'EWIE58', 'BLIHKI', 'HNICPO', '8RI2E0', 'BFIFKI', '8FIFK9', 'BJI3E9', 'BDIEBX', 'TLIAK4', 'BKIEBI', 'AAIBA6', 'CXI9G4', 'BKIEBS']
  Model_Year: ['G', 'R', 'A', 'E', 'J', 'K', 'T', '2', 'C', 'H', 'Y', 'P']
  Plant_Code: ['U', '3', 'K', '6', 'C', 'J', '2']
  Serial_Number: ['221024', '084650', '087338', '773367', 'D03774', '194367', '036440', '866285', '084523', '407028', '015523', '062833', '143435', '080293', '099835', '611435', '085240']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,AVALON,6.0,SEDAN,B,SE+,GCC,4.0,4T1,BKIEB8,G,U,221024
1,TOYOTA,TOYOTA VELOZ,NaN,STATION,A,NaN,NaN,NaN,MHF,ABIBY7,R,3,084650
2,TOYOTA,FJ CRUISER,6.0,SUV,B,TOP,GCC,5.0,JTE,BUIIF9,A,K,087338
3,TOYOTA,CAMRY,4.0,SEDAN,B,GLX,GCC,4.0,4T1,BFIFK3,E,U,773367
4,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,E,GL,GCC,4.0,1FT,EWIE58,J,K,D03774
5,TOYOTA,CAMRY,4.0,SEDAN,B,GLE,GCC,4.0,4TI,BLIHKI,K,U,194367
6,TOYOTA,HIACE,6.0,MINI BUS HIGH ROOF,H,GL,GCC,4.0,JTG,HNICPO,T,6,036440
7,TOYOTA,COROLLA,4.0,SEDAN,8,GLI TOP,GCC,5.0,211,8RI2E0,2,C,866285
8,TOYOTA,CAMRY,4.0,SEDAN,B,GL,GCC,4.0,4T1,BFIFKI,C,U,084523
9,TOYOTA,CAMRY,4.0,SEDAN,8,SE,GCC,4.0,4T1,8FIFK9,H,U,407028
10,TOYOTA,COROLLA,4.0,SEDAN,B,XLI MID,GCC,4.0,JT2,BJI3E9,Y,3,015523
11,TOYOTA,AVALON,6.0,SEDAN,B,LIMITED PREMIUM,GCC,4.0,4T1,BDIEBX,J,U,062833
12,TOYOTA,CAMRY,4.0,SEDAN,T,GLE,GCC,NaN,4TI,TLIAK4,P,U,143435
13,TOYOTA,AVALON,6.0,SEDAN,B,SE+,GCC,4.0,4T1,BKIEBI,E,U,080293
14,TOYOTA,RAIZE,4.0,STATION,A,E,GCC,NaN,MHK,AAIBA6,P,J,099835
15,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,C,DLX,GCC,2.0,MR0,CXI9G4,E,2,611435
16,TOYOTA,AVALON,6.0,SEDAN,B,XLE TOURING,GCC,4.0,4T1,BKIEBS,E,U,085240

====================================================================================================
pos6: M
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'C-HR', 'PRIUS', 'HILUX', 'CAMRY', 'RAV4', 'COROLLA SEDAN / HATCH', 'YARIS', 'CHR', 'COROLLA 1.3', 'COROLLA 1.5L/HATCHBACK', 'RUSH']
  bodyType: ['SEDAN', 'SUV', 'HATCHBACK', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'STATION']
  pos4: ['E', 'B', 'D', 'K', 'S', 'F', 'T', 'V', 'C', 'A', 'L', 'P']
  trim: ['GLI', 'STD (NON GCC)', 'SE', 'XLI EXECUTIVE', 'GX', 'LE (NON GCC)', 'GLI HEV', 'XLI', 'XLI EXECUTIVE MR', 'DLX', 'S', 'GLE', 'GL', 'EXR', 'STD', 'YA', 'ABC', 'SE (NON GCC)', 'ICONIC', 'EX', 'ECO']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5YF', 'JTD', 'JTN', 'NMT', 'LVA', 'SYF', 'LHG']
  VDS: ['EPMAE0', 'BDMHE2', 'EAMDE4', 'B4MDE1', 'D4MBE8', 'EPMAE2', 'B4MDE0', 'EPMAE4', 'KHMBX3', 'B4MDE3', 'D4MBE2', 'KAMFU5', 'KHMBXX', 'S4MCE7', 'EPMAE3', 'FPMAE5', 'EPMAE7', 'DPMAE9', 'KHMBX7', 'EPMAE1', 'EPMAEX', 'EPMAE5', 'S4MCEX', 'S4MCE1', 'K4MBE8', 'KHMBX2', 'T4MCEX', 'VPMAE4', 'KHMBX5', 'EAMDE0', 'EAMDEX', 'S4MCE9', 'S4MCE4', 'S4MCE3', 'KAMFU9', 'VPMAE9', 'KAMFPX', 'B4MDE4', 'KHMBX9', 'EPMAE8', 'KHMBX8', 'KHMBX0', 'C4MBE1', 'S4MCE5', 'B4MDE2', 'B4MBE1', 'EPMAE6', 'VPMAE2', 'V2MW50', 'B4MBE8', 'S4MCE2', 'B4MDE7', 'KHMBX1', 'D4MBE1', 'EPMAE9', 'B4MBE9', 'EAMDE3', 'VPMAE1', 'B4MDE9', 'KHMBX6', 'DPMAE7', 'EAMDE7', 'D4MBE3', 'A4MBE6', 'B4MBEX', 'BAMDE8', 'B4MDEX', 'BPMBE0', 'S4MCE6', 'B4MDEI', 'KAMFU8', 'C4MBE4', 'DPMAE4', 'B4MDE8', 'V2MWB7', 'KHMBX4', 'D4MBE0', 'KAMFP0', 'EAMDE2', 'L9MFU9', 'D4MBE9', 'EAMDE6', 'KAMFUX', 'EAMDE8', 'EAMDE1', 'S4MCE0', 'DPMAE1', 'P4MCE1', 'PLM90S', 'DPMAE0', 'P4MCE8', 'B4MBE7', 'T4MCE3', 'T4MCE8', 'B4MBE5', 'T4MCE1', 'D4MBEX', 'KAMFP7', 'BPMBE1', 'KAMFU0', 'B4MDE5', 'K4MBE7', 'D4MBE6', 'VPMAE6', 'KAMFP1', 'EAMDE9', 'D4MBE7', 'B4MEE8', 'P4MCE7', 'D4MBE4', 'B4MBE6', 'VPMAE5', 'C4MBEX', 'P4MCE6', 'KAMFP2', 'EPMAEO', 'D4MBE5', 'VPMAE3', 'T4MCE5', 'EAMDE5', 'VPMAE8']
  Model_Year: ['M', 'S', 'N', 'P', 'R', 'L', 'K', 'J', '5']
  Plant_Code: ['P', '3', 'J', '1', 'R', 'A', 'C', '0']
  Serial_Number: ['184032', '026542', '055021', '293169', '052974', '114141', '273151', '179153', '033901', '171207', '006275', '079144', '148561', '105418', '139360', '327791', '065774', '079355', '302947', '130041', '215051', '018663', '026218', '022498', '189503', '267065', '304507', '203501', '152757', '049208', '088952', '143809', '165230', '039737', '212343', '070879', '267978', '105969', '185467', '022421', '051703', '204190', '217098', '356443', '234351', '064792', '162306', '348195', '104830', '212337', '084781', '329031', '141418', '151597', '175698', '028349', '046635', '095012', '142647', '067166', '044064', '032124', '347330', '208037', '149147', '214783', '173799', '082240', '004085', '147448', '008022', '093636', '146999', '194590', '100598', '348808', '192772', '136572', '121129', '183743', '009977', '116797', '067352', '001181', '068751', '234290', '143721', '196554', '362026', '114575', '094598', '231420', '235154', '047163', '044981', '508147', '072254', '218233', '110538', '183957', '184086', '151424', '008028', '019643', '069239', '166983', '136531', '238387', '154445', '177068', '279784', '125315', '154309', '227307', '267272', '170270', '286294', '177094', '004357', '206567', '199907', '155176', '223337', '018621', '105221', '231752', '214447', '193535', '225224', '259126', '253000', '033751', '004882', '026051', '182279', '348351', '121368', '202131', '156169', '221878', '183731', '160768', '196367', '214234', '145594', '221219', '148437', '165866', '177233', '194866', '091886', '210523', '138964', '182630', '078421', '001429', '017576', '217147', '184289', '090569', '124440', '172684', '104989', '063217', '016175', '337232', '187134', '262966', '167125', '021142', '026069', '068238', '124032', '075573', '129316', '203700', '005758', '214017', '048314', '006183', '173349', '143646', '392219', '013830', '177905', '236702', '138559', '131435', '157523', '117370', '178198', '296665', '207796', '022685', '070029', '522215', '206458', '135244', '030465', '141525', '106113', '203670', '043313', '038143', '220932', '153000', '193821', '144185', '077293', '141291', '518919', '000016', '170488', '231894', '070656', '062110', '184130', '221954', '089822', '274701', '240457', '241034', '153392', '015987', '177966', '155016', '187370', '220886', '182904', '161766', '163327', '504981', '183183', '076127', '174695', '119732', '080857', '191399', '140526', '255685', '176535', '069723', '211167', '139383', '190080', '166078', '204481', '034417', '332657', '210327', '102814', '274720', '033213', '152189', '005373', '016501', '154751', '248468', '114522', '172013', '137001', '274379', '165787', '334455', '336163', '248229', '133657', '113103', '309858', '198941', '194088', '132421', '135367', '191314', '004106', '004506', '234341', '179662', '179347', '012902', '107478', '158639', '197975', '160995', '090914', '179560', '149689', '174421', '123910', '117743', '323968', '163882', '246841', '184619', '207653', '108120', '112953', '161624', '094679', '127875', '109853', '131545', '258197', '192222', '151553', '165471', '009241', '006390', '080874', '271576', '302844', '243135', '342158', '180439', '060699', '212931', '119843', '216023', '286140', '106966', '178463', '140153', '140157', '155112', '181461', '239533', '171342', '277572', '159838', '234088', '042435', '177199', '225644', '035570', '118666', '214264', '175342', '072538', '148071', '175396', '105863', '187914', '180471', '333822', '098941', '209706', '328449', '022364', '103930', '040596', '131535']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,E,GLI,GCC,4.0,5YF,EPMAE0,M,P,184032
1,TOYOTA,COROLLA,4.0,SEDAN,B,GLI,GCC,4.0,JTD,BDMHE2,S,3,026542
2,TOYOTA,COROLLA,4.0,SEDAN,E,STD (NON GCC),GCC,4.0,JTD,EAMDE4,N,J,055021
3,TOYOTA,COROLLA,4.0,SEDAN,E,GLI,GCC,4.0,5YF,EPMAE0,N,P,293169
4,TOYOTA,COROLLA,4.0,SEDAN,B,GLI,GCC,4.0,5YF,B4MDE1,P,P,052974
...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,TOYOTA,COROLLA,4.0,SEDAN,E,STD (NON GCC),NON-GCC,NaN,5YF,EPMAE7,N,P,328449
348,TOYOTA,COROLLA,4.0,SEDAN,E,XLI EXECUTIVE,NON-GCC,NaN,JTD,EPMAE2,N,3,022364
349,TOYOTA,C-HR,4.0,SUV,K,GX,NON-GCC,NaN,NMT,KHMBX6,L,R,103930
350,TOYOTA,C-HR,4.0,SUV,K,STD (NON GCC),NON-GCC,NaN,NMT,KHMBX4,J,R,040596
351,TOYOTA,C-HR,4.0,SUV,K,GX,NON-GCC,NaN,NMT,KHMBX6,M,R,131535

====================================================================================================
pos6: Y
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'LAND CRUISER PRADO', 'RAV4', 'CAMRY', 'هايلوكس']
  bodyType: ['PICK UP DOUBLE CAB', 'SUV', 'PICK UP SINGLE CAB', 'PICKUP', 'PICK UP', 'SEDAN']
  pos4: ['3', 'A', '7', '1', 'J', 'D']
  trim: ['STD', 'STANDDARD', 'DLX', 'EX', 'GLE', 'DLS', 'S', 'LE']
  regionalSpec: ['GCC']
  WMI: ['JTB', 'JTE', 'L6T', '1HD', '1ST', 'WV1']
  VDS: ['33YN87', 'AAYAJO', '31YN87', '79YND1', '1YYK27', 'JBYP2X', '31YN81', 'DBYSVX', 'DBYSV3']
  Model_Year: ['V', 'T', 'S', 'P', 'M', 'F', 'D']
  Plant_Code: ['1', 'K', 'T', 'B', 'J', 'H']
  Serial_Number: ['012745', '047515', '010424', '014006', '013128', '013824', '012828', '250817', '069758', '557309', '014082', '012760', '003291', '013406', '012878', '013511', '010176', '012865', '012951', '010270', '013480', '001143', '013612', '012305', '012983', '001028', '012704', '011206', '014062', '011066', '003412', '013561', '011483', '011103']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,012745
1,TOYOTA,LAND CRUISER PRADO,6.0,SUV,A,STD,GCC,NaN,JTE,AAYAJO,T,K,047515
2,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,STD,GCC,2.0,JTB,31YN87,V,1,010424
3,TOYOTA,HILUX,0.0,PICK UP DOUBLE CAB,3,STD,GCC,NaN,JTB,33YN87,V,1,014006
4,TOYOTA,HILUX,4.0,PICKUP,3,STANDDARD,GCC,NaN,JTB,31YN87,V,1,013128
5,TOYOTA,HILUX,4.0,PICK UP,3,STD,GCC,4.0,JTB,31YN87,V,1,013824
6,TOYOTA,HILUX,4.0,PICKUP,3,DLX,GCC,NaN,JTB,31YN87,V,1,012828
7,TOYOTA,RAV4,4.0,SUV,7,EX,GCC,5.0,L6T,79YND1,S,T,250817
8,TOYOTA,CAMRY,4.0,SEDAN,1,GLE,GCC,4.0,1HD,1YYK27,P,B,069758
9,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,J,DLS,GCC,4.0,1ST,JBYP2X,M,J,557309
10,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,014082
11,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,STD,GCC,2.0,JTB,31YN87,V,1,012760
12,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,DLX,GCC,4.0,JTB,31YN81,V,1,003291
13,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,013406
14,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,012878
15,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,GCC,2.0,JTB,31YN87,V,1,013511
16,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,010176
17,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,DLX,GCC,4.0,JTB,31YN87,V,1,012865
18,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,012951
19,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,3,DLX,GCC,2.0,JTB,31YN87,V,1,010270
20,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,31YN87,V,1,013480
21,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,D,DLS,GCC,4.0,WV1,DBYSVX,F,H,001143
22,TOYOTA,HILUX,6.0,PICKUP,3,STD,GCC,NaN,JTB,31YN87,V,1,013612
23,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,012305
24,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,31YN87,V,1,012983
25,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,D,DLS,GCC,4.0,WV1,DBYSV3,D,H,001028
26,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,012704
27,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,011206
28,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,3,STD,GCC,4.0,JTB,33YN87,V,1,014062
29,TOYOTA,HILUX,4.0,PICKUP,3,DLX,GCC,NaN,JTB,31YN87,V,1,011066
30,TOYOTA,HILUX,4.0,PICKUP,3,STD,GCC,NaN,JTB,31YN81,V,1,003412
31,TOYOTA,هايلوكس,4.0,PICKUP,3,S,GCC,NaN,JTB,31YN87,V,1,013561
32,TOYOTA,HILUX,4.0,PICKUP,3,STD,GCC,NaN,JTB,33YN87,V,1,011483
33,TOYOTA,HILUX,4.0,PICKUP,3,LE,GCC,NaN,JTB,31YN87,V,1,011103

====================================================================================================
pos6: W
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'TUNDRA', 'HILUX', 'CAMRY', 'RAV4']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'SEDAN', 'PICK UP SINGLE CAB']
  pos4: ['1', 'F', 'H', 'D', 'B', 'A', 'M']
  trim: ['STD', 'GX', 'VX', 'STD (NON GCC)', 'DLX', 'GXR', 'GL', 'GLX', 'EX', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTB', '5TT', 'KN4', 'MYN', '9KM', 'YV2', 'JT8', 'LJN']
  VDS: ['11WJA0', '11WJAO', 'FBW415', '11WJAD', 'HNW6NK', 'DBWG30', 'BPWDG2', 'ASW0AX', 'MFWBY5', 'ASW0A9']
  Model_Year: ['W', '9', 'X', '5', 'F', 'S', '6', 'R']
  Plant_Code: ['8', 'X', 'B', 'K', 'J', 'L', 'N']
  Serial_Number: ['000035', '006744', '003337', '001046', '000006', '004765', '004546', '000092', '005743', '005643', '005312', '001912', '002683', '005422', '006022', '006099', '006847', '088569', '002508', '005224', '005931', '007382', '004913', '006522', '000225', '006348', '004404', '001263', '006285', '004902', '001481', '003128', '000508', '002190', '004374', '005324', '006298', '005709', '105435', '001036', '004489', '001735', 'ZNJJBQ', '000811', '005314', '000280', '001902', '002351', '007376', '004837', '000993', '003549', '004561', '001521', '004356', 'RYHD3R', '000488', '006874', '006034', '002267', '005602', '005675', '004673', '000708', '001067', '006795', '000674', '001465', '005935', '003719', '007328', '003018', '005627', '002338', '004221', '006789', '007054', '004853', '005265', '006343', '006067', '003530', '005354', '006442', '428963', '004958', '004014', '005044', '006956', '002125', '006787', '005379', '001381', '003375', '004281', '004139', '005804', '001673', '003433', '006541', '006731', '006141', '003954', '000180', '003419', '004035', '003554', '006439', '002437', '006784', '005648', '001250', '001845', '005124', '004814', '003560', '005162', '007055', '002004', '003795', '000068', '002703', '004749', '006043', '006514', '004942', '004036', '001812', '003402', '002296', '002367', '006510', '000090', '000252', '006719', '000935', '001041', '000644', '000145', '003446', '002670', '005008', '004397', '006903', '003687', '005974', '000248', '006636', '005930', '003659', '004660', '006734', '007224', '002291', '006690', '006069', '003094', '006584', '006047', '005097', '005038', '002736', '006197', '004065', '005872', '005050', '006904', '001629', '005504', '006895', '005245', '413452', '000637', '006279', '434530', '003453', '004604', '006085', '004524', '006429']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,8.0,SUV,1,STD,GCC,5.0,JTB,11WJA0,W,8,000035
1,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11WJA0,W,8,006744
2,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,5.0,JTB,11WJA0,W,8,003337
3,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11WJA0,W,8,001046
4,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11WJAO,W,8,001046
...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,TOYOTA,LAND CRUISER,6.0,SUV,1,1,GCC,NaN,JTB,11WJA0,W,8,006067
190,TOYOTA,LAND CRUISER,8.0,SUV,1,GX,NON-GCC,NaN,JTB,11WJA0,W,8,004604
191,TOYOTA,LAND CRUISER,8.0,SUV,1,GX,GCC,NaN,JTB,11WJA0,W,8,006085
192,TOYOTA,LAND CRUISER,8.0,SUV,1,1,GCC,NaN,JTB,11WJA0,W,8,004524
193,TOYOTA,LAND CRUISER,8.0,SUV,1,STD,GCC,NaN,JTB,11WJA0,W,8,006429

====================================================================================================
pos6: E
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['COROLLA', 'TERCEL', 'HIACE', 'YARIS', 'HILUX', 'COASTER', 'INNOVA', 'CAMRY', 'COROLLA 1.3', '2022', 'RAV4', 'PRADO', 'YARIS HATCHBACK', 'MR2', '4RUNNER', '900']
  bodyType: ['SEDAN', 'PANEL VAN', 'MINI BUS', 'HATCHBACK', 'PANEL VAN HIGH ROOF', 'PICK UP DOUBLE CAB', 'BUS', 'MPV', 'MINI BUS HIGH ROOF', 'PICK UP SINGLE CAB', 'SUV', 'SALOON', 'COUPE', 'STATION']
  pos4: ['5', 'B', '7', 'P', 'A', 'C', '6', 'F', 'K', '8', 'V', 'E', 'R', '4']
  trim: ['XLI', 'STD', 'DX', 'E', 'SE', 'XLI MID', 'GLS', 'GL', 'LWB', 'LIMITED', 'SPORT', 'DLX', 'GLI TOP', 'S', 'EX', 'LWB HIGH ROOF', 'DL', 'GLX', 'MID', 'GLI', 'BASE', 'SL', 'EXR', 'GLE', 'GLE HEV', 'SR5 (NON GCC)', '60TH', 'XLI TOP']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTB', 'JJ5', 'MB1', 'LFM', 'RA6', 'LVG', 'JL6', 'LJ1', 'L7X', 'LM8', 'KL3', 'JL7', 'JT8', 'JJ7', 'LPS', 'L6T', 'MBI', 'JL5', 'WMA', 'LS6', 'CM8', 'LGJ', 'JTE', 'LDP', '4T1']
  VDS: ['53EEB0', '53EL50', 'B2E6KX', '72EEB0', 'PBEJA1', 'ARE0C6', 'PAEHD1', 'BJE239', 'PAEHD5', 'CJE237', 'CGE234', 'BCE6J3', 'B2E6K5', 'PBEJA3', 'ARE2C0', '53EEA0', 'C8E2H4', 'PBEJA5', '6AE3C6', 'FPEFFV', 'APE2C8', 'CJE735', 'PBEJA0', 'ARE0C9', 'F7E692', 'CGE231', 'K6E6F1', '53EEBO', 'BCE1J7', 'B2E6K9', '72EEA0', '8CE1K7', 'VAEDE1', 'PBEJA4', 'ARE2C6', '79END0', 'BCELK4', 'PBEHD5', 'PBEFD5', 'ARE0C3', 'PBEJA6', 'ARE2C4', 'B3E6P5', 'ARE2C5', 'PBEFA6', 'BCE1KX', '72EEBO', '79END6', 'BCE1J1', 'B3E6P4', 'ARE0C2', 'ARE2C2', 'PBEWA6', 'PBEHD9', '8CE1K3', '53EE80', 'PBEFA8', 'PBEJAX', 'PBEJA8', 'CJE232', '56EZZ5', 'PAEHD8', 'ENE0R2', 'B3E6P3', '7KE438', 'E1EE03', 'ARE0C4', 'CJE235', 'ARE0C1', '79END5', 'BCE1J0', 'CJE234', 'PBEJA2', '64EEB0', 'RMEAP7', '41E969', 'BBE32K', 'CJE730', 'ARE0C0']
  Model_Year: ['W', '1', '8', '9', 'X', 'T', 'L', 'V', 'S', 'F', 'E', '7', '2', 'H', 'N', '3', 'M', 'D', 'C', 'K', 'G', 'B', 'J', 'Y', '6', 'R']
  Plant_Code: ['0', 'P', '4', '2', '3', 'U', 'G', 'K', 'D', 'A', 'L', 'H', 'T', 'R', 'E', 'M', '8', '5']
  Serial_Number: ['004584', '067448', 'B00309', '000342', '010636', '126843', '192844', '064463', '004891', '004413', '006520', '013052', '1D8092', '749415', '038096', '001655', '067863', '1D1158', '064709', '007073', '005924', '001651', 'C00044', '137134', '115494', '016226', '000936', '000974', '309873', '094256', '016206', '000828', 'ELTZ4B', '063397', '009234', '021700', '010064', '014871', '007033', '001586', '017868', '041873', '054053', '004047', '129992', '020384', '006954', '041147', '019463', '000672', '010206', '003616', '073892', '000728', '009721', '022257', '012198', '022041', 'D00066', '001512', '001164', '013093', '021113', '055725', '019131', '071279', '005322', '010474', '1E2375', '009410', '358817', '001559', '239077', '000781', '064372', '006931', '078119', '002124', '019235', '1D9016', '037120', '071574', '017040', '0B0409', '017416', '049262', '008581', '013237', '006740', '011423', '001113', '001273', '005040', '071843', '029212', '000898', '006545', '073074', '007189', '128247', '118124', '008467', '001400', '075807', '001226', '068163', '000211', 'P20607', '135683', '000894', '022807', '001697', '003997', '0A3076', '007694', '1C4988', '1C4837', '002064', '002890', '065936', '004301', '001106', '001743', '248866', '136273', '010822', '004486', '001546', '006708', '017591', 'J10030', '018385', '002380', '136396', '021874', '010065', '1N2468', '000877', 'FA9759', '002600', '00B9B7', '004852', '004400', '002585', '019903', '109061', '056975', 'BA7279', '004979', '219150', '128896', '001734', '135153', '020648', '195775', '001366', '019336', '939639', 'AA5202', '551825', 'J10021', '314568', '000968', '062850', '001098', 'M10163', '042384', '064220', '305073', '012835', '034399', '022151', '017793', '000825', '002929', '064563', '057303', '237504', '001173', '001128', '002616', '009024', '013096', '000352', '011685', '006534', '000866', '019959', '000569', '077798', '068167', '001579', '060327', '001030', '041577', '001069', '012267', '134520', '087364', '001727', '019720', '1D8292', '000282', '1E2000', '056909', '004006', '117893', 'U06881', '018333', '085014', '018968', '002145', '062511']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,GCC,4.0,JTB,53EEB0,W,0,004584
1,TOYOTA,TERCEL,4.0,SEDAN,5,STD,GCC,4.0,JTB,53EL50,W,0,067448
2,TOYOTA,HIACE,4.0,PANEL VAN,B,STD,GCC,5.0,JJ5,B2E6KX,1,P,B00309
3,TOYOTA,COROLLA,4.0,SEDAN,7,XLI,GCC,4.0,JTB,72EEB0,W,4,000342
4,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,GCC,4.0,JTB,53EEB0,W,0,010636
...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,GCC,4.0,JTB,53EEA0,V,0,018333
217,TOYOTA,COROLLA,4.0,SEDAN,A,XLI,NON-GCC,NaN,LFM,ARE0C2,8,0,085014
218,TOYOTA,YARIS,4.0,SEDAN,C,SE,NON-GCC,NaN,LVG,CJE730,E,G,018968
219,TOYOTA,COROLLA,4.0,SEDAN,5,XLI,GCC,NaN,JTB,53EEB0,W,3,002145
220,TOYOTA,COROLLA,4.0,SEDAN,A,XLI TOP,NON-GCC,NaN,LFM,ARE0C0,8,0,062511

====================================================================================================
pos6: P
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'HIACE', 'COROLLA', 'FJ CRUISER', 'INNOVA', 'RAV4']
  bodyType: ['PICK UP DOUBLE CAB', 'MINI BUS HIGH ROOF', 'PICK UP SINGLE CAB', 'SEDAN', 'SUV', 'PANEL VAN', 'MPV']
  pos4: ['J', 'Z', 'H', 'D', 'G']
  trim: ['DLX', 'GL', 'GL DECKLESS', 'SE', 'GXR', 'STD', 'DLS', 'DX', 'ADVENTURE']
  regionalSpec: ['GCC']
  WMI: ['JMY', 'JHH', 'KN3', 'RKM']
  VDS: ['JNP13V', 'ZCP2F6', 'HNP6N3', 'HAP53E', 'HAP5J1', 'DTPUKX', 'ZCP2H5', 'ZCP2F5', 'GNP03V', 'ZCP2HX', 'HNP13W', 'HAP732', 'HAP53C', 'ZCP2F2']
  Model_Year: ['5', 'P', '7', '1', 'Y', '2', 'K', 'D', '8', '6', 'M']
  Plant_Code: ['A', 'K', 'H']
  Serial_Number: ['771316', '017860', '187108', '770244', '607580', '204005', '808887', '009968', '701114', '289656', '763372', '770898', '019714', '770404', '702126', '010758', '700786', '018520', '866779', '013137', '767442', '701260']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,J,DLX,GCC,4.0,JMY,JNP13V,5,A,771316
1,TOYOTA,HIACE,6.0,MINI BUS HIGH ROOF,Z,GL,GCC,NaN,JHH,ZCP2F6,P,K,017860
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DLX,GCC,4.0,KN3,HNP6N3,7,K,187108
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DLX,GCC,4.0,KN3,HAP53E,1,K,770244
4,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DLX,GCC,4.0,KN3,HAP5J1,Y,K,607580
5,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,D,GL DECKLESS,GCC,2.0,RKM,DTPUKX,P,H,204005
6,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DLX,GCC,4.0,KN3,HAP53E,2,K,808887
7,TOYOTA,COROLLA,4.0,SEDAN,Z,SE,GCC,NaN,JHH,ZCP2H5,K,K,009968
8,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,J,GL,GCC,4.0,JMY,JNP13V,D,A,701114
9,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DLX,GCC,4.0,KN3,HNP6N3,8,K,289656
10,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DLX,GCC,4.0,KN3,HAP53E,1,K,763372
11,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,J,DLX,GCC,4.0,JMY,JNP13V,Y,A,770898
12,TOYOTA,FJ CRUISER,6.0,SUV,Z,GXR,GCC,NaN,JHH,ZCP2F5,P,K,019714
13,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,J,DLX,GCC,4.0,JMY,JNP13V,6,A,770404
14,TOYOTA,HIACE,4.0,PANEL VAN,G,STD,GCC,5.0,JMY,GNP03V,7,A,702126
15,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,Z,DLS,GCC,2.0,JHH,ZCP2HX,K,K,010758
16,TOYOTA,INNOVA,4.0,MPV,H,DX,GCC,5.0,JMY,HNP13W,D,A,700786
17,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DLX,GCC,NaN,KN3,HAP732,Y,K,018520
18,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,H,STD,GCC,2.0,KN3,HAP53C,2,K,866779
19,TOYOTA,RAV4,4.0,SUV,Z,ADVENTURE,GCC,NaN,JHH,ZCP2F2,M,K,013137
20,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,H,DLX,GCC,4.0,KN3,HAP53C,1,K,767442
21,TOYOTA,HIACE,4.0,PANEL VAN,G,STD,GCC,5.0,JMY,GNP03V,7,A,701260

====================================================================================================
pos6: K
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['SIENNA', 'LAND CRUISER', 'HILUX', 'CAMRY', 'SY150T', 'HIACE', 'AVANZA', 'INNOVA', 'RAV4', 'TOYOTA']
  bodyType: ['MPV', 'STATION', 'PICK UP DOUBLE CAB', 'SEDAN', 'MOTORCYCLE', 'PANEL VAN', 'VAN', 'SUV', 'PICKUP']
  pos4: ['B', 'K', 'Z', 'J', 'Y', 'T', 'P', 'X', 'U', 'G', 'M', 'D', 'E', '6', 'C']
  trim: ['LE (NON GCC)', 'XLE (NON GCC)', 'DLX', 'XSE', 'GLE', 'DL', 'GL', 'TX', 'STD', '1', 'GLS', 'T', 'EXR', 'GV', 'STANDARD', 'FABRIC', 'CE (NON GCC)', 'BASE', 'HEV']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['5TD', 'U8Q', 'MMB', 'LRR', 'JHH', 'LK1', 'VF3', 'STD', '25T']
  VDS: ['BRKEC5', 'KSKFC3', 'KRKEC5', 'ZCKF5Q', 'KRKEC9', 'JNK620', 'YSKFC5', 'JNK650', 'YRKEC9', 'TEKP1X', 'YSKFC3', 'ZCK1H2', 'PCKL98', 'ZCK1H9', 'JNK640', 'KRKEC3', 'KRKEC1', 'XRKEC0', 'BRKEC8', 'K5KFCX', 'KRKECX', 'KRKEC8', 'JRKEC1', 'YRKEC2', 'UCK1H0', 'GBKFWB', 'BRKEC6', 'UCK1H5', 'JRKEC5', 'KRKEC2', 'YRKEC0', 'XRKEC7', 'MCK3H2', 'YRKEC4', 'GSKFC5', 'PCKL9X', 'JNKG2Q', 'DSKFCX', 'DZK23C', 'KSKFC7', 'ENKA50', 'GJKFWC', '6JKFWC', 'KSKFC1', 'MCK3H3', 'KRKEC7', 'KRKEC0', 'GRKEC7', 'CRKEC4']
  Model_Year: ['M', 'N', 'R', '5', '4', 'P', 'H', 'G', 'X', '6', 'D', 'J', '1', '8', '9', 'S']
  Plant_Code: ['S', 'W', 'D', '6', 'K', '1', 'J', '0', '7', 'N']
  Serial_Number: ['024309', '002800', '111905', 'C7VTDF', '064148', '006556', '118758', '065305', '044196', '091684', '000037', '076538', '006958', '001410', '006440', '015385', '045711', '059026', '003229', '020494', '208041', '059815', '131629', '062221', '096947', '084767', '048782', '087713', '106185', '005263', '006105', '036467', '013606', '167082', '018242', '058786', '149491', '006478', '024941', '030241', '045697', '012470', '040180', '048748', '007041', '000120', '0393S0', '034112', '011039', '010031', '501375', '048009', '021351', '017110', '033852', '000728', '069235', '016906', '039748', '016621', '246272', '183088']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,SIENNA,6.0,MPV,B,LE (NON GCC),GCC,5.0,5TD,BRKEC5,M,S,024309
1,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),GCC,5.0,5TD,KSKFC3,M,S,002800
2,TOYOTA,SIENNA,6.0,MPV,K,XLE (NON GCC),GCC,5.0,5TD,KRKEC5,N,S,111905
3,TOYOTA,LAND CRUISER,NaN,STATION,Z,NaN,NaN,NaN,U8Q,ZCKF5Q,R,W,C7VTDF
4,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),GCC,5.0,5TD,KRKEC9,M,S,064148
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,M,DL,GCC,4.0,JHH,MCK3H3,G,K,016906
60,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),GCC,5.0,5TD,KRKEC7,M,S,039748
61,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),GCC,5.0,5TD,KRKEC0,M,S,016621
62,TOYOTA,INNOVA,4.0,MPV,G,HEV,GCC,NaN,5TD,GRKEC7,S,S,246272
63,TOYOTA,SIENNA,4.0,SUV,C,XSE,NON-GCC,NaN,5TD,CRKEC4,R,S,183088

====================================================================================================
pos6: H
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'RUSH', 'HILUX', 'RAV4', 'COASTER', 'LAND CRUISER PICK UP', 'FLHTK', 'COROLLA']
  bodyType: ['SUV', 'PICK UP DOUBLE CAB', 'PICK UP SINGLE CAB', 'BUS', 'PICK UP', 'MOTORCYCLE', 'SEDAN']
  pos4: ['H', 'E', '1', '7', 'W', 'L', 'P']
  trim: ['GXR', 'EX', 'DLS', 'DLX', 'STD', 'GLI']
  regionalSpec: ['GCC']
  WMI: ['JTM', 'MHK', 'LTA', 'KL7', 'KMJ', 'SAL', 'MC2', '5HD']
  VDS: ['HXHX01', 'EFHCF1', '12H2P3', '7LHEP2', 'WAH7JP', 'LDHAD8', 'P1HLT8', '1FHPC6', '1ZH159']
  Model_Year: ['J', 'P', 'K', 'S', '9', 'T', 'N', 'X']
  Plant_Code: ['3', 'K', '2', 'C', 'U', 'A', 'J', '8', 'S']
  Serial_Number: ['J41531', '021737', '002907', '067417', '097409', '991840', '496206', '172462', '600201', '313103']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,6.0,SUV,H,GXR,GCC,NaN,JTM,HXHX01,J,3,J41531
1,TOYOTA,RUSH,4.0,SUV,E,EX,GCC,NaN,MHK,EFHCF1,P,K,021737
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,1,DLS,GCC,4.0,LTA,12H2P3,K,2,002907
3,TOYOTA,RAV4,4.0,SUV,7,EX,GCC,5.0,KL7,7LHEP2,S,C,067417
4,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,W,DLX,GCC,4.0,KMJ,WAH7JP,9,U,097409
5,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,L,DLX,GCC,5.0,SAL,LDHAD8,T,A,991840
6,TOYOTA,COASTER,4.0,BUS,P,STD,GCC,NaN,MC2,P1HLT8,N,J,496206
7,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP,L,STD,GCC,2.0,SAL,LDHAD8,X,A,172462
8,TOYOTA,FLHTK,NaN,MOTORCYCLE,1,NaN,GCC,NaN,5HD,1FHPC6,K,8,600201
9,TOYOTA,COROLLA,4.0,SEDAN,1,GLI,GCC,NaN,5HD,1ZH159,N,S,313103

====================================================================================================
pos6: N
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['YARIS', 'HILUX', 'HIACE', 'RAV4', 'PRADO', 'SIENNA', 'CAMRY', 'ECHO', 'COASTER', 'COROLLA']
  bodyType: ['HATCHBACK', 'PICK UP DOUBLE CAB', 'PANEL VAN', 'SUV', 'MINI BUS HIGH ROOF', 'MPV', 'PICK UP SINGLE CAB', 'SEDAN', 'WINDOW VAN', 'BUS']
  pos4: ['0', 'L', 'U', '7', 'J', 'B', 'E', '5', 'Y', 'Z', '8', 'A', 'K', 'R', '2', 'S']
  trim: ['MID', 'GLX', 'GL', 'EX', 'TX-L TOP', 'DL', 'LE', 'SE', 'DLX', 'S', 'DX', 'XLI TOP', 'ST', 'STD', 'GLI']
  regionalSpec: ['NON-GCC', 'GCC']
  WMI: ['000', 'JHH', 'VF3', 'JTE', 'LVC', 'LSC', 'VR3', 'VS5', 'CPB', 'VF7', 'K1K', 'L3A', 'MC2', '1G0', 'SKF']
  VDS: ['00NCP9', 'LCN1F1', 'UCN1H5', '7JNFU6', 'JUNFJ4', 'B2NWA8', '7FNFU8', 'BBN2A2', 'E1NFJX', '7ENFUZ', '56N8U6', 'YCN1HX', 'ZCN1FX', '7ANFU0', '87N071', '7ENFU8', 'B2NBA9', '7CNFU6', 'AAN6E8', '7ANFUC', 'KFNM3X', '7ENFU9', 'R3NLT1', '2HNAG2', 'ZCN1F0', 'SJN3BC']
  Model_Year: ['1', 'P', 'K', 'F', 'D', 'S', 'L', '6', 'E', 'R', 'X', 'H']
  Plant_Code: ['9', 'K', 'J', 'S', 'G', 'N', '6', 'A', 'Y', 'T']
  Serial_Number: ['097501', '029698', '029296', '515922', '055277', '220346', '507185', '800613', '517447', '515786', 'E9FFA8', '021052', '020136', '509520', '000112', '515828', '240854', '600802', '1NW111', '506556', '690149', '503560', '065666', '6HGKKA', '020081', '103759']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,YARIS,4.0,HATCHBACK,0,MID,NON-GCC,NaN,000,00NCP9,1,9,097501
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,L,GLX,GCC,NaN,JHH,LCN1F1,P,K,029698
2,TOYOTA,HIACE,4.0,PANEL VAN,U,GL,GCC,5.0,JHH,UCN1H5,K,K,029296
3,TOYOTA,RAV4,4.0,SUV,7,EX,GCC,5.0,VF3,7JNFU6,F,J,515922
4,TOYOTA,PRADO,4.0,SUV,J,TX-L TOP,GCC,NaN,JTE,JUNFJ4,D,K,055277
5,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,B,GLX,GCC,4.0,LVC,B2NWA8,K,S,220346
6,TOYOTA,HIACE,4.0,PANEL VAN,7,GL,GCC,5.0,VF3,7FNFU8,K,J,507185
7,TOYOTA,HIACE,4.0,PANEL VAN,B,GL,GCC,4.0,LSC,BBN2A2,S,G,800613
8,TOYOTA,HIACE,4.0,PANEL VAN,E,GL,GCC,4.0,VR3,E1NFJX,L,J,517447
9,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,7,DL,GCC,4.0,VF3,7ENFUZ,F,J,515786
10,TOYOTA,SIENNA,6.0,MPV,5,LE,NON-GCC,NaN,VS5,56N8U6,L,N,E9FFA8
11,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,Y,GL,GCC,NaN,JHH,YCN1HX,L,K,021052
12,TOYOTA,CAMRY,4.0,SEDAN,Z,SE,GCC,NaN,JHH,ZCN1FX,P,K,020136
13,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,7,DLX,GCC,2.0,VF3,7ANFU0,F,J,509520
14,TOYOTA,CAMRY,4.0,SEDAN,8,S,GCC,NaN,CPB,87N071,6,6,000112
15,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,7,DLX,GCC,2.0,VF3,7ENFU8,F,J,515828
16,TOYOTA,CAMRY,4.0,SEDAN,B,S,GCC,NaN,LVC,B2NBA9,S,S,240854
17,TOYOTA,HIACE,4.0,PANEL VAN,7,DX,GCC,NaN,VF7,7CNFU6,E,J,600802
18,TOYOTA,ECHO,6.0,SEDAN,A,XLI TOP,GCC,NaN,K1K,AAN6E8,R,A,1NW111
19,TOYOTA,HIACE,4.0,PANEL VAN,7,ST,GCC,5.0,VF3,7ANFUC,K,J,506556
20,TOYOTA,RAV4,4.0,SUV,K,EX,GCC,NaN,L3A,KFNM3X,P,Y,690149
21,TOYOTA,HIACE,4.0,WINDOW VAN,7,DX,GCC,5.0,VF3,7ENFU9,F,J,503560
22,TOYOTA,COASTER,4.0,BUS,R,STD,GCC,NaN,MC2,R3NLT1,L,K,065666
23,TOYOTA,COROLLA,4.0,SEDAN,2,GLI,GCC,NaN,1G0,2HNAG2,X,S,6HGKKA
24,TOYOTA,HIACE,6.0,MINI BUS HIGH ROOF,Z,GL,GCC,NaN,JHH,ZCN1F0,P,K,020081
25,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,S,DLX,GCC,NaN,SKF,SJN3BC,H,T,103759

====================================================================================================
pos6: V
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['LAND CRUISER', 'PRADO', 'CAMRY', 'YARIS', 'TUNDRA', 'LAND CRUISER PRADO']
  bodyType: ['SUV', 'STATION', 'SEDAN', 'HATCHBACK', 'PICK UP DOUBLE CAB']
  pos4: ['1', 'L', 'B', 'A', '0']
  trim: ['GX', 'GXR', 'PRADO', 'STD', 'VX', 'GL', 'FLEET', 'BASE', 'STD (NON GCC)', 'XLT', '1']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JTB', 'JMY', 'JTD', '5TF']
  VDS: ['11VJ95', '11VJ90', 'LYV65V', 'BVV133', 'BVV923', 'AVV5F1', '0RV430']
  Model_Year: ['X', 'W', 'V', 'F', 'Y', '7', '5', '3']
  Plant_Code: ['0', 'J', '5', '9', 'F']
  Serial_Number: ['052160', '003674', '029873', '041644', '003739', '030897', '036155', '012199', '003044', '017869', '003067', '004163', '032041', '712366', '003645', '045680', '023163', '048420', '011203', '073505', '007962', '036455', '045716', '402965', '003655', '019673', '011908', '046523', '048309', 'X43833', '046417', '052937', '020266', '003188', '052947', '020695', '037543', '047390', '016264', '024280', '033295', '027875', '051705', '031105', '003154', '033412', '002588', '045964', '038445', '004128']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,X,0,052160
1,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ90,W,0,003674
2,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,029873
3,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,W,0,041644
4,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ90,W,0,003739
5,TOYOTA,PRADO,6.0,STATION,1,PRADO,GCC,NaN,JTB,11VJ95,V,0,030897
6,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,W,0,036155
7,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,012199
8,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ90,V,0,003044
9,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,NaN,JTB,11VJ95,V,0,017869
10,TOYOTA,PRADO,4.0,STATION,1,STD,GCC,NaN,JTB,11VJ90,V,0,003067
11,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,5.0,JTB,11VJ90,X,0,004163
12,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,032041
13,TOYOTA,CAMRY,4.0,SEDAN,L,GL,GCC,5.0,JMY,LYV65V,F,J,712366
14,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,NaN,JTB,11VJ90,W,0,003645
15,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,5.0,JTB,11VJ95,X,0,045680
16,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,023163
17,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,5.0,JTB,11VJ95,X,0,048420
18,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,NaN,JTB,11VJ95,V,0,011203
19,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,Y,0,073505
20,TOYOTA,YARIS,4.0,SEDAN,B,FLEET,GCC,NaN,JTD,BVV133,7,5,007962
21,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,W,0,036455
22,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,5.0,JTB,11VJ95,X,0,045716
23,TOYOTA,YARIS,4.0,HATCHBACK,B,BASE,GCC,NaN,JTD,BVV923,5,9,402965
24,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ90,W,0,003655
25,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,019673
26,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,011908
27,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,5.0,JTB,11VJ95,X,0,046523
28,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,X,0,048309
29,TOYOTA,TUNDRA,8.0,PICK UP DOUBLE CAB,A,STD (NON GCC),NON-GCC,NaN,5TF,AVV5F1,3,F,X43833
30,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,5.0,JTB,11VJ95,X,0,046417
31,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,X,0,052937
32,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,020266
33,TOYOTA,PRADO,4.0,SUV,1,GX,GCC,NaN,JTB,11VJ90,V,0,003188
34,TOYOTA,LAND CRUISER,6.0,SUV,1,STD,GCC,5.0,JTB,11VJ95,X,0,052947
35,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,020695
36,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,W,0,037543
37,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,5.0,JTB,11VJ95,X,0,047390
38,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,016264
39,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,024280
40,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,W,0,033295
41,TOYOTA,LAND CRUISER,6.0,SUV,1,GXR,GCC,5.0,JTB,11VJ95,V,0,027875
42,TOYOTA,LAND CRUISER,6.0,SUV,1,VX,GCC,5.0,JTB,11VJ95,X,0,051705
43,TOYOTA,PRADO,6.0,SUV,1,STD,GCC,NaN,JTB,11VJ95,V,0,031105
44,TOYOTA,LAND CRUISER,6.0,SUV,0,GX,GCC,5.0,JMY,0RV430,X,J,003154
45,TOYOTA,LAND CRUISER,6.0,SUV,1,GX,GCC,5.0,JTB,11VJ95,W,0,033412
46,TOYOTA,PRADO,6.0,STATION,1,XLT,GCC,NaN,JTB,11VJ90,V,0,002588
47,TOYOTA,LAND CRUISER,8.0,SUV,1,VX,GCC,NaN,JTB,11VJ95,X,0,045964
48,TOYOTA,LAND CRUISER,6.0,SUV,1,1,GCC,NaN,JTB,11VJ95,W,0,038445
49,TOYOTA,LAND CRUISER PRADO,6.0,SUV,1,NaN,GCC,NaN,JTB,11VJ90,X,0,004128

====================================================================================================
pos6: Z
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['SIENNA', 'HILUX', 'COROLLA', 'HIACE', 'HIGHLANDER', 'LAND CRUISER']
  bodyType: ['MPV', 'PICK UP DOUBLE CAB', 'SEDAN', 'MINI BUS HIGH ROOF', 'PICK UP SINGLE CAB', 'PANEL VAN', 'SUV', 'MINI BUS']
  pos4: ['D', 'W', 'C', 'B', 'S', 'Z', 'A']
  trim: ['XLE (NON GCC)', 'DLX', 'DLS', 'ADVENTURE', 'XLI MID', 'DX', 'GL', 'GR SPORT', 'LE (NON GCC)', 'DL', 'GLS', 'GLX', 'EXR', 'STD']
  regionalSpec: ['GCC']
  WMI: ['WV1', 'KNF', 'LVA', 'JTD', 'KNC', 'KMF', 'ZFC', 'JTM']
  VDS: ['DBZSV3', 'WXZ74A', 'C2ZWB5', 'C2ZWB0', 'BRZ3E7', 'WJZ74A', 'SJZ74A', 'STZ74A', 'C2ZWB6', 'ZSZ7JA', 'WJZ76A', 'C2ZWB9', 'AFZBG2', 'DBZSV4', 'ZCZ7JA', 'ZSZ7KB', 'AUZBJ7', 'WJZ72A', 'DBZSV5', 'DBZSV9']
  Model_Year: ['F', 'B', 'M', '4', 'A', 'C', 'K', 'G', 'D', 'L', 'P', 'S']
  Plant_Code: ['H', 'K', 'S', '3', 'U', '6', '4', '7']
  Serial_Number: ['001135', '590918', '220272', '021811', '100831', '001104', '539943', '527028', '441558', '011543', '769564', '368503', '021795', '210313', '538612', '001142', '633820', '021805', '752164', '029411', '815446', '001105', '001463']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,SIENNA,6.0,MPV,D,XLE (NON GCC),GCC,5.0,WV1,DBZSV3,F,H,001135
1,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,W,DLX,GCC,4.0,KNF,WXZ74A,B,K,590918
2,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,DLS,GCC,4.0,LVA,C2ZWB5,M,S,220272
3,TOYOTA,HILUX,6.0,PICK UP DOUBLE CAB,C,ADVENTURE,GCC,4.0,LVA,C2ZWB0,M,S,021811
4,TOYOTA,COROLLA,4.0,SEDAN,B,XLI MID,GCC,5.0,JTD,BRZ3E7,4,3,100831
5,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,D,DX,GCC,4.0,WV1,DBZSV3,F,H,001104
6,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,W,DLX,GCC,4.0,KNC,WJZ74A,B,K,539943
7,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,S,GL,GCC,4.0,KNC,SJZ74A,B,K,527028
8,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,S,GL,GCC,4.0,KNF,STZ74A,A,K,441558
9,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,DLS,GCC,4.0,LVA,C2ZWB6,M,S,011543
10,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,Z,GR SPORT,GCC,4.0,KMF,ZSZ7JA,C,U,769564
11,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,W,GL,GCC,2.0,KNC,WJZ76A,K,K,368503
12,TOYOTA,HIACE,4.0,PANEL VAN,C,GL,GCC,5.0,LVA,C2ZWB6,M,S,021795
13,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,C,DLS,GCC,4.0,LVA,C2ZWB9,M,S,210313
14,TOYOTA,HIGHLANDER,4.0,SUV,A,LE (NON GCC),GCC,5.0,ZFC,AFZBG2,G,6,538612
15,TOYOTA,HIACE,4.0,PANEL VAN,D,DL,GCC,5.0,WV1,DBZSV4,D,H,001142
16,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,Z,DLX,GCC,4.0,KMF,ZCZ7JA,A,U,633820
17,TOYOTA,HIACE,4.0,PANEL VAN,C,GLS,GCC,NaN,LVA,C2ZWB5,M,S,021805
18,TOYOTA,HILUX,4.0,PICK UP SINGLE CAB,Z,GLX,GCC,2.0,KMF,ZSZ7KB,L,U,752164
19,TOYOTA,LAND CRUISER,6.0,SUV,A,EXR,GCC,5.0,JTM,AUZBJ7,P,4,029411
20,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,W,GL,GCC,4.0,KNC,WJZ72A,S,7,815446
21,TOYOTA,HIACE,4.0,MINI BUS,D,STD,GCC,4.0,WV1,DBZSV5,F,H,001105
22,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,D,GLX,GCC,4.0,WV1,DBZSV9,F,H,001463

====================================================================================================
pos6: G
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['CAMRY', 'HIACE', 'LAND CRUISER PICK UP', 'PRADO', 'COROLLA', 'COASTER']
  bodyType: ['SEDAN', 'MINI BUS', 'MINI BUS HIGH ROOF', 'PICK UP', 'SUV', 'BUS']
  pos4: ['A', 'G', 'P', 'J', 'B', 'N']
  trim: ['XLI', 'GL', 'DX', 'STD', 'TX-L', 'PLATINUM', 'GLE', 'LWB']
  regionalSpec: ['NON-GCC', 'GCC']
  WMI: ['YV2', 'GGG', 'LSK', 'HJR', 'JTE', 'RKL', 'LFC', 'JL5']
  VDS: ['ASG0A9', 'GGG565', 'G5GC14', 'PBGJB2', 'JUGFJ3', 'BLGHE1', 'NNG6P5', 'B3G6P3']
  Model_Year: ['9', '2', 'F', 'R', 'D', 'J', 'P']
  Plant_Code: ['B', '2', 'A', 'K', '5', 'R']
  Serial_Number: ['538364', '222222', '210045', '380196', '062124', '260726', '004730', 'L10105']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,CAMRY,4.0,SEDAN,A,XLI,NON-GCC,NaN,YV2,ASG0A9,9,B,538364
1,TOYOTA,HIACE,4.0,MINI BUS,G,GL,GCC,NaN,GGG,GGG565,2,2,222222
2,TOYOTA,HIACE,4.0,MINI BUS HIGH ROOF,G,DX,GCC,4.0,LSK,G5GC14,F,A,210045
3,TOYOTA,LAND CRUISER PICK UP,6.0,PICK UP,P,STD,GCC,2.0,HJR,PBGJB2,R,B,380196
4,TOYOTA,PRADO,6.0,SUV,J,TX-L,GCC,NaN,JTE,JUGFJ3,D,K,062124
5,TOYOTA,COROLLA,4.0,SEDAN,B,PLATINUM,GCC,4.0,RKL,BLGHE1,J,5,260726
6,TOYOTA,CAMRY,4.0,SEDAN,N,GLE,GCC,NaN,LFC,NNG6P5,P,2,004730
7,TOYOTA,COASTER,6.0,BUS,B,LWB,GCC,NaN,JL5,B3G6P3,D,R,L10105

====================================================================================================
pos6: J
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HILUX', 'SIENNA', 'HIACE', 'COASTER', 'TUNDRA', 'COROLLA', 'LAND CRUISER', 'CROWN V', 'PICKUP', 'DYNA VAN CARGO']
  bodyType: ['PICK UP DOUBLE CAB', 'MPV', 'PANEL VAN', 'BUS', 'MINI BUS', 'SEDAN', 'SUV', 'SALOON', 'PICKUP', 'VAN', 'PICK UP']
  pos4: ['A', 'K', 'B', 'D', 'H', 'V', 'U', '5']
  trim: ['DLS', 'LE (NON GCC)', 'STD', 'GL', 'LWB', 'SR', 'DX', 'LIMITED', 'VX', 'DLX', 'PICKUP', 'GLX', 'GXR', 'DL']
  regionalSpec: ['GCC', 'NON-GCC']
  WMI: ['JHH', 'STD', 'JL5', 'ZFC', 'LGD', 'LVB', 'JJ5', 'JTE', 'JTB', 'JHG']
  VDS: ['ACJ4H1', 'KAJDC9', 'B3J6P2', 'DKJA05', 'B3J6P0', 'HEJ1F0', 'V4JBB9', 'B3J6P3', 'UFJ1H4', 'B3J6P7', 'BUJFJ7', 'B3J6P6', 'BHJ6S3', '53JSF5', 'V3JBB3', 'UFJ173', 'UFJ175', 'B3J6P5', 'V4JBB7', 'BUJFJ4', 'DKJA01']
  Model_Year: ['J', '8', '4', 'G', 'D', 'S', 'M', '6', 'F', '2', 'P', '3', 'X', 'E', 'C']
  Plant_Code: ['K', '5', 'P', '9', 'R', 'A', 'Y', '0', 'J']
  Serial_Number: ['003526', '003426', 'D01004', '003934', 'L10639', '205392', '048704', 'D01441', 'D00850', 'D03600', '008252', 'C00385', '231065', 'D00136', 'F02393', 'P25182', '134854', '002171', '005885', '004803', 'K00815', '006113', '148460', '002439']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,A,DLS,GCC,4.0,JHH,ACJ4H1,J,K,003526
1,TOYOTA,SIENNA,6.0,MPV,K,LE (NON GCC),GCC,5.0,STD,KAJDC9,8,5,003426
2,TOYOTA,HIACE,4.0,PANEL VAN,B,STD,GCC,5.0,JL5,B3J6P2,4,P,D01004
3,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,D,GL,GCC,4.0,ZFC,DKJA05,G,9,003934
4,TOYOTA,COASTER,4.0,BUS,B,LWB,GCC,NaN,JL5,B3J6P0,D,R,L10639
5,TOYOTA,TUNDRA,6.0,PICK UP DOUBLE CAB,H,SR,GCC,4.0,LGD,HEJ1F0,S,A,205392
6,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,V,DLS,GCC,4.0,LVB,V4JBB9,M,Y,048704
7,TOYOTA,COASTER,4.0,BUS,B,LWB,GCC,2.0,JL5,B3J6P2,4,P,D01441
8,TOYOTA,COASTER,4.0,BUS,B,STD,GCC,NaN,JL5,B3J6P3,4,P,D00850
9,TOYOTA,HIACE,4.0,MINI BUS,B,DX,GCC,4.0,JL5,B3J6P2,6,P,D03600
10,TOYOTA,COROLLA,4.0,SEDAN,U,LIMITED,GCC,NaN,JHH,UFJ1H4,F,K,008252
11,TOYOTA,COASTER,4.0,BUS,B,GL,GCC,NaN,JJ5,B3J6P7,2,P,C00385
12,TOYOTA,LAND CRUISER,6.0,SUV,B,VX,GCC,NaN,JTE,BUJFJ7,P,K,231065
13,TOYOTA,COASTER,4.0,BUS,B,GL,GCC,NaN,JJ5,B3J6P2,3,P,D00136
14,TOYOTA,HILUX,4.0,BUS,B,DLX,GCC,2.0,JL5,B3J6P6,8,P,F02393
15,TOYOTA,SIENNA,6.0,MPV,B,LE (NON GCC),NON-GCC,NaN,JL5,BHJ6S3,S,R,P25182
16,TOYOTA,CROWN V,6.0,SALOON,5,STD,GCC,NaN,JTB,53JSF5,X,0,134854
17,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,V,DLS,GCC,4.0,LVB,V3JBB3,F,J,002171
18,TOYOTA,PICKUP,4.0,PICKUP,U,PICKUP,GCC,NaN,JHG,UFJ173,E,K,005885
19,TOYOTA,DYNA VAN CARGO,6.0,VAN,U,STD,GCC,NaN,JHG,UFJ175,D,K,004803
20,TOYOTA,COASTER,4.0,BUS,B,LWB,GCC,NaN,JL5,B3J6P5,C,R,K00815
21,TOYOTA,HILUX,4.0,PICK UP,V,GLX,GCC,NaN,LVB,V4JBB7,M,Y,006113
22,TOYOTA,LAND CRUISER,8.0,SUV,B,GXR,GCC,NaN,JTE,BUJFJ4,J,K,148460
23,TOYOTA,HILUX,4.0,PICK UP DOUBLE CAB,D,DL,GCC,4.0,ZFC,DKJA01,G,9,002439

====================================================================================================
pos6: Q
====================================================================================================
--- Unique Values for Object Columns ---
  make: ['TOYOTA']
  model: ['HIACE', 'LAND CRUISER']
  bodyType: ['MINI BUS', 'SUV', 'PANEL VAN']
  pos4: ['J', 'H']
  trim: ['DX', 'VX', 'GLS']
  regionalSpec: ['GCC']
  WMI: ['JTG', 'JTE', 'JTF']
  VDS: ['JXQ2P1', 'HJQ8JS', 'HXQ2P9']
  Model_Year: ['8', 'G', 'F']
  Plant_Code: ['Q', 'S', '0']
  Serial_Number: ['018676', 'I49347', '098891']
----------------------------------------------------------------------------------------------------

,make,model,cylinders,bodyType,pos4,trim,regionalSpec,noOfDoors,WMI,VDS,Model_Year,Plant_Code,Serial_Number
0,TOYOTA,HIACE,4.0,MINI BUS,J,DX,GCC,4.0,JTG,JXQ2P1,8,Q,018676
1,TOYOTA,LAND CRUISER,6.0,SUV,H,VX,GCC,5.0,JTE,HJQ8JS,G,S,I49347
2,TOYOTA,HIACE,4.0,PANEL VAN,H,GLS,GCC,4.0,JTF,HXQ2P9,F,0,098891