In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"..\data\data_methaq(1.0).csv")
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan
...,...,...,...,...,...,...,...,...,...,...
1009599,LNGPCMXJ9PL305272,NaN,NaN,APULUO,APULUO AP200 4H,2023.0,Motorcycle,GCC,NaN,China
1009600,LURJAVBM8PA024843,STD,4.0,AIQAR,EQ 1,2023.0,COUPE,GCC,NaN,CHINA
1009601,7KGTC2C48NR003646,NaN,NaN,Electric Motion,ePure,2022.0,Motorcycle,GCC,NaN,AMERICA
1009602,LX6TK334XS2510023,NaN,NaN,CHANGHUA,CH150T-34,2025.0,Motorcycle,GCC,NaN,China
1009603,MI76734700,GL,4.0,MANITOU,MTX1740SLT,2015.0,HEAVY EQUIPMENT,GCC,NaN,Italy

In [3]:
data = data[data["make"] == "TOYOTA"]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan
...,...,...,...,...,...,...,...,...,...,...
241595,MR2BT9F3XE1089611,E,4.0,TOYOTA,YARIS,2014.0,SEDAN,GCC,4.0,Thailand
241596,5TDZK23C87S071537,LE (NON GCC),6.0,TOYOTA,SIENNA,2007.0,MPV,GCC,5.0,America
241597,JTEBU11F39K063774,BASE,6.0,TOYOTA,FJ CRUISER,2009.0,SUV,GCC,5.0,Japan
241598,RKLBL9HE3F5218095,SE+,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
241599,JTDBR23E733057607,XLI MID,4.0,TOYOTA,COROLLA,2003.0,Estate,GCC,5.0,Japan

In [4]:
data["WMI"] = data["chassisNumber"].str[0:3]
data["pos4"] = data["chassisNumber"].str[3]
data["pos5"] = data["chassisNumber"].str[4]
data["pos6"] = data["chassisNumber"].str[5]
data["pos7"] = data["chassisNumber"].str[6]
data["pos8"] = data["chassisNumber"].str[7]
data["Model_Year"] = data["chassisNumber"].str[9]
data["Plant_Code"] = data["chassisNumber"].str[10]
data["Serial_Number"] = data["chassisNumber"].str[11:17]

C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["WMI"] = data["chassisNumber"].str[0:3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos4"] = data["chassisNumber"].str[3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos5"] = data["chassisNumber"].str[4]
C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos6"] = data["chassisNumber"].str[5]
C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos7"] = data["chassisNumber"].str[6]
C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos8"] = data["chassisNumber"].str[7]
C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Model_Year"] = data["chassisNumber"].str[9]
C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Plant_Code"] = data["chassisNumber"].str[10]
C:\Users\Admin\AppData\Local\Temp\ipykernel_2188\3122298373.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Serial_Number"] = data["chassisNumber"].str[11:17]

In [5]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,WMI,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan,RKL,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan,JTF,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan,JTF,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan,JTF,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan,4T1,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241595,MR2BT9F3XE1089611,E,4.0,TOYOTA,YARIS,2014.0,SEDAN,GCC,4.0,Thailand,MR2,B,T,9,F,3,E,1,089611
241596,5TDZK23C87S071537,LE (NON GCC),6.0,TOYOTA,SIENNA,2007.0,MPV,GCC,5.0,America,5TD,Z,K,2,3,C,7,S,071537
241597,JTEBU11F39K063774,BASE,6.0,TOYOTA,FJ CRUISER,2009.0,SUV,GCC,5.0,Japan,JTE,B,U,1,1,F,9,K,063774
241598,RKLBL9HE3F5218095,SE+,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan,RKL,B,L,9,H,E,F,5,218095
241599,JTDBR23E733057607,XLI MID,4.0,TOYOTA,COROLLA,2003.0,Estate,GCC,5.0,Japan,JTD,B,R,2,3,E,3,3,057607

In [6]:
data_pos4A = data[data["pos4"] == "A"]
data_pos4A.head()

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,WMI,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
32,JTMAUBBJ1R4057596,GXR,6.0,TOYOTA,LAND CRUISER,2024.0,SUV,GCC,5.0,Japan,JTM,A,U,B,B,J,R,4,057596
84,JTMABBBJ0N4038683,GXR,6.0,TOYOTA,LAND CRUISER,2022.0,SUV,GCC,5.0,Japan,JTM,A,B,B,B,J,N,4,038683
151,JTMAB7BJ0N4012534,VXR,6.0,TOYOTA,LAND CRUISER,2022.0,SUV,GCC,5.0,Japan,JTM,A,B,7,B,J,N,4,012534
156,JTMAB7BJXN4056539,VXR,6.0,TOYOTA,LAND CRUISER,2022.0,SUV,GCC,5.0,JAPAN,JTM,A,B,7,B,J,N,4,056539
161,5TFAY5F17JX712542,STD (NON GCC),8.0,TOYOTA,TUNDRA,2018.0,Pick Up Double Cab,GCC,4.0,America,5TF,A,Y,5,F,1,J,X,712542