In [83]:
import pandas as pd
import glob

In [84]:
data = pd.read_csv(r"..\data\data_methaq(1.0).csv")
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,Taiwan
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,Mini Bus High Roof,GCC,4.0,Japan
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,Pick Up Double Cab,GCC,4.0,Japan
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,Non-GCC,4.0,Japan
...,...,...,...,...,...,...,...,...,...,...
1009599,LNGPCMXJ9PL305272,NaN,NaN,APULUO,APULUO AP200 4H,2023.0,Motorcycle,GCC,NaN,China
1009600,LURJAVBM8PA024843,STD,4.0,AIQAR,EQ 1,2023.0,COUPE,GCC,NaN,CHINA
1009601,7KGTC2C48NR003646,NaN,NaN,Electric Motion,ePure,2022.0,Motorcycle,GCC,NaN,AMERICA
1009602,LX6TK334XS2510023,NaN,NaN,CHANGHUA,CH150T-34,2025.0,Motorcycle,GCC,NaN,China
1009603,MI76734700,GL,4.0,MANITOU,MTX1740SLT,2015.0,HEAVY EQUIPMENT,GCC,NaN,Italy

In [85]:
import pandas as pd

data = pd.read_csv(r"../data/data_methaq(1.0).csv")

for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

       chassisNumber trim  cylinders    make    model    year  \
0  RKLBB9HE7F5115863   SE        4.0  TOYOTA  COROLLA  2015.0
1  JTFHX02POF0099797  GLX        4.0  TOYOTA    HIACE  2015.0
2  JTFHX02P7F0094323   DX        4.0  TOYOTA    HIACE  2015.0
3  JTFHXDGP7F0094373   DL        4.0  TOYOTA    HILUX  2015.0
4  4T1BG22K01U789089  XLI        4.0  TOYOTA    CAMRY  2001.0

             bodyType regionalSpec  noOfDoors  origin
0               SEDAN          GCC        4.0  TAIWAN
1  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
2  MINI BUS HIGH ROOF          GCC        4.0   JAPAN
3  PICK UP DOUBLE CAB          GCC        4.0   JAPAN
4               SEDAN      NON-GCC        4.0   JAPAN

In [86]:
data = data[data["make"] == "TOYOTA"]
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN
...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN

In [87]:
data["WMI"] = data["chassisNumber"].str[0:3]
data["pos0"] = data["chassisNumber"].str[0]
data["pos1"] = data["chassisNumber"].str[1]
data["pos2"] = data["chassisNumber"].str[2]
data["pos4"] = data["chassisNumber"].str[3]
data["pos5"] = data["chassisNumber"].str[4]
data["pos6"] = data["chassisNumber"].str[5]
data["pos7"] = data["chassisNumber"].str[6]
data["pos8"] = data["chassisNumber"].str[7]
data["Model_Year"] = data["chassisNumber"].str[9]
data["Plant_Code"] = data["chassisNumber"].str[10]
data["Serial_Number"] = data["chassisNumber"].str[11:17]

In [88]:
data

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos1,pos2,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
0,RKLBB9HE7F5115863,SE,4.0,TOYOTA,COROLLA,2015.0,SEDAN,GCC,4.0,TAIWAN,...,K,L,B,B,9,H,E,F,5,115863
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,T,F,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,T,F,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,T,F,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,T,1,B,G,2,2,K,1,U,789089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,R,0,H,U,8,C,D,K,0,071134
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,T,M,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,T,M,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,T,E,A,A,C,A,J,S,5,008118
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,H,F,B,2,9,F,3,M,2,123579

In [89]:
data_pos4A = data[data["pos1"] == "T"]
data_pos4A

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos1,pos2,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
1,JTFHX02POF0099797,GLX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,T,F,H,X,0,2,P,F,0,099797
2,JTFHX02P7F0094323,DX,4.0,TOYOTA,HIACE,2015.0,MINI BUS HIGH ROOF,GCC,4.0,JAPAN,...,T,F,H,X,0,2,P,F,0,094323
3,JTFHXDGP7F0094373,DL,4.0,TOYOTA,HILUX,2015.0,PICK UP DOUBLE CAB,GCC,4.0,JAPAN,...,T,F,H,X,D,G,P,F,0,094373
4,4T1BG22K01U789089,XLI,4.0,TOYOTA,CAMRY,2001.0,SEDAN,NON-GCC,4.0,JAPAN,...,T,1,B,G,2,2,K,1,U,789089
5,JTMHT09J7A5049335,VX,8.0,TOYOTA,LAND CRUISER,2010.0,SUV,GCC,5.0,JAPAN,...,T,M,H,T,0,9,J,A,5,049335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922347,6T1BF9FK4DX474261,S,4.0,TOYOTA,CAMRY HYBRID,2013.0,SEDAN,GCC,NaN,NaN,...,T,1,B,F,9,F,K,D,X,474261
922349,6T1BE32K86X538813,GLI,4.0,TOYOTA,CAMRY HYBRID,2006.0,SEDAN,GCC,NaN,NaN,...,T,1,B,E,3,2,K,6,X,538813
922351,JTMABBBJ6S4188504,1,6.0,TOYOTA,LAND CRUISER,2025.0,SUV,GCC,NaN,NaN,...,T,M,A,B,B,B,J,S,4,188504
922352,JTMHX01J3M4222343,GXR,8.0,TOYOTA,LAND CRUISER,2021.0,SUV,GCC,NaN,NaN,...,T,M,H,X,0,1,J,M,4,222343
922353,JTEAACAJ1S5008118,GXL,4.0,TOYOTA,LAND CRUISER PRADO,2025.0,SUV,GCC,NaN,NaN,...,T,E,A,A,C,A,J,S,5,008118

In [90]:
print(data['pos1'].unique())

['K' 'T' 'R' 'B' 'H' 'I' 'N' 'E' 'D' 'G' 'Z' 'V' 'M' 'C' 'Y' 'J' 'F' '0'
 'X' 'P' 'L' 'S' '3' 'W' 'A' 'U' 'O' '9' '1' '8' '7' '2' '6' '5' '4']

In [91]:
print(data['trim'].nunique())

482

In [92]:
print(data['trim'].unique())

['SE' 'GLX' 'DX' 'DL' 'XLI' 'VX' 'MID' 'DLX' 'VXR' 'FABRIC' 'E' 'TOP'
 'EXTREME' 'GL' 'LE' 'BASE' 'S' 'FLEET' 'STD (NON GCC)' 'GXR' 'EXR'
 'SE+ ANNIVERSARY EDITION' 'GL2' 'SR5' 'STD' 'XLI MID' 'LE (NON GCC)'
 'SE+' 'GLI' 'SR5 (NON GCC)' 'TX' 'LIMITED' 'XLE (NON GCC)'
 'SE TRD AERO PK' 'EX' 'ICONIC' 'VX MID' 'LE HEV' 'SGLX' 'PW CL' 'GX'
 'XLE' 'SPORT' 'G' 'GRANDE' 'GR' 'XLI TOP' 'S TRD SPORT PK' 'S+' 'PRO' 'C'
 'XLI RB' 'LIMITED PREMIUM' 'GLE' 'XLI EXECUTIVE' 'GLS' 'PLATINUM'
 'DLX TOP' 'TURBO G RA' 'LIMITED (NON GCC)' 'SR5 4X4' 'VXR HEV' 'GLE HEV'
 'SAFARI' 'LX' 'PREMIUM' 'GXR TOP 60TH ANNIV. XTREME' 'CE (NON GCC)'
 'GLI HEV' 'XLI EXECUTIVE MR' 'XL' 'GXR TOP' 'VXR BASE' 'LX AC PWR OPT'
 'LX WINCH' 'TX-L' 'XLE TOURING' 'GXR GT' 'DLS' 'VXR TOP' 'SC'
 'GLE-X HEV 40TH ANNIV' 'SALOON' nan 'ADVENTURE'
 'CREWMAX CAPSTONE (NON GCC)' '4' 'LE STD' 'LIMITED MID' 'EXCLUSIVE'
 'GX TOP' 'TX-L TOP' 'GLI TOP' 'GXR MID' 'XSE (NON GCC)' 'BLACK EDITION'
 'DX H/R W/B' 'PICKUP' 'C (NON GCC)' 'XLI POWER OPT' '1' 'GLX SPORT Z'
 'S PLUS' 'VTX' 'GXL' 'HT SWB' 'ECO' 'GX MID' 'GXR2' 'LWB HIGH ROOF'
 'STATION' '1794 EDITION (NON GCC)' '40TH ANNIVERSARY EDITION' 'TOURING'
 'HEV' 'GLI TOP LTH' 'PS PW CL' 'SL' 'LIMITED 4X4' 'GR SPORT' 'STD D'
 'TXL1' 'LWB' 'DLS - STD ROOF' 'EXR HEV' '1000' 'SU' 'LSE' 'BE' 'GLE-X'
 'GT' 'T' '100' 'SWB' 'SE (NON GCC)' 'SR' 'GTX' 'CTD' 'TXL3'
 'GR TAN EDITION' 'TRIM' 'SEDAN' 'NA' 'ST' 'E PLUS HEV' '1.8'
 'LIMITED 4X2' 'VX TOP LTH' 'XTREME' 'VX2' 'STANDARD' 'SV' 'SR5 4X2'
 'S T1' 'VX1' 'STD  (NON GCC)' 'GXR FMST' 'HEV GLI' '00' 'GXR1'
 'SUPER SAFARI T1' 'DYNAMIC' 'XLI EXECUTIVE HEV' 'GR-S' 'FJ STD'
 'GR BLUE EDITION' 'TRD' 'YX' 'GXR TOP DMST' 'LMV' 'HT VXR' '1500 REG/CAB'
 'H' 'LIMITED TRD SPORT PK' 'LS' 'VXR TOP LTH' 'VIOS' 'TXR' 'XLE HEV'
 'TOP LTH' 'STD AC' 'XLT' 'LEATHER' 'PICK UP' 'COUPE' '1500' 'X'
 'TRD OFF-ROAD' 'BUS' 'GLE HEV BLACK EDITION' 'Y PLUS' 'SR (NON GCC)'
 'TERIM' 'BSE' 'SED' 'TRX' '2' 'TX1' 'VAN' 'GXR SOD D/AC AW'
 'TC (NON GCC)' 'SALON' 'LIMITED HEV' 'TXL2' 'GXR4' 'GXR TOP FMST'
 'GT SPORT' 'CAR TRIM' 'CLASSIC' 'HARD TOP' 'GL TOP' 'HYBRID (NON GCC)'
 'XSE' 'GRD' 'STD NON GCC' 'L' 'GL LIMITED' 'DF' 'JAC' 'SD' '0' 'SGL'
 'STDD' '2400' 'GRANDE HEV 40TH ANNIV' 'XE' 'AIR' 'W' 'SUV' 'TRD SPORT'
 'STANDDARD' 'STANDER' 'AXL ' 'XLI - AW' 'TURBO G' 'GXR-V' 'STAN'
 'XLI 1.8L' 'VT' 'GA' 'XLI ' 'CLASSIC EX' 'M' 'GXR+' '2.0L' '25HX' 'DY'
 'SALOO' 'PREMIER' 'GXR3' 'FD' 'XT' '6' 'ALTIS' 'A' 'GLX TOP'
 'SE TRD SPORT PK' 'GRANDE LTH' 'AUTOMATIC' 'LUMIERE HEV' 'AUTOMATIC '
 '90' 'LEVIN' 'HILUX' 'AXE ' 'EXI' 'LAND CRUSIER' '4X4' 'XE 4WD' 'HE'
 'LUX' 'LDS' 'P' 'STATION1' 'LU' 'D' 'PIC UP' 'GXR MID 60TH ANNIV. XTREME'
 'F' 'VXR MID' 'TOYOTA' 'EX TOP' 'S ASF' 'ROYAL' 'GL DECKLESS' 'CRESSIDA'
 '000' 'GT PREMIUM' 'COM' 'STANDAR' 'HYBRID' 'LUXURY' 'GF' 'HT SLWB'
 'CABRIO' 'S (NON GCC)' 'ADVENTTURE' 'STD CARGO' 'SA' 'HYCROSS' 'J+' 'GG'
 'LXI' 'STATION ' 'SLD' 'HIGH DELUX' 'ALTAS' 'PRESTIGE' 'Y'
 'LUMIERE 40TH ANNIV' 'GRANDE HEV' 'TZ' '1.5L' 'PIKUP' 'PRADO' '60TH'
 'LTD HEV' 'PICK UP ' '10TH VICTORY EDITION' 'WISH' 'STAND' 'TL' 'STE'
 'CE' 'LIMITED TRD AERO PK' 'SS' 'VX2 PLUS' 'OTHER' 'FULL OPTION'
 'FR-S (NON GCC)' 'VXR TOP XTREME' 'TT' '4WD' 'GLI TOP LEATHER' 'XLI+'
 'AT' 'LI' 'AST' 'GXL 1ST EDITION' 'USF' '0000' 'DLS HIGH ROOF'
 '1500 CREWCAB SLE Z71' 'ORION' 'SXT' 'STANDERD' 'STD ( NON GCC )' 'RVI'
 'VX-L MID' 'GGG' 'GLS TOP' 'COMFORT' 'TR' 'GLX HIGHLINE' 'ES' 'ZX' 'MPV'
 'VIP7' 'LTZ' '-' 'PE' '45' 'LIMITED TOP' 'EXECUTIVE'
 'PLATINUM LUXURY 4X4' '1.5' 'GCC' ' ' 'N' '5' 'SDT' 'NON GCC' 'MIDLINE'
 'GLI MR HEV' 'SENA' 'KD' 'GTS' 'LONG RANGE' 'LX WIDE TYRES' 'SPORTS' 'RS'
 'COASTER' 'GLS MIDLINE' 'S T2 TOP' 'AMBIENTE' '1.4' 'TRT' 'VX-L TOP'
 'PICKUP ' 'EXI A/W' 'GLI-2.0 LAUTOMATIC' 'ATLIS' 'LUXURY SPORT' 'GV'
 'ADVENTURE 1ST EDITION' 'DDFG' 'STC' 'ASD' 'ALIS' 'AA' 'AMG' 'STERLING'
 'S 1.3L' 'S LIMITED EDITION' 'SL+' 'SL W/SR' 'YA' 'SE TITANIUM'
 'EXCELLENCE' 'XI' 'GLX PREMIUM' 'TUNDRA' 'PERFORMANCE' 'STR' '5.0L'
 'GLS LOWLINE' '1.3' 'ABC' 'DOUBLE CABIN ' 'XR' 'GL LTH' 'DTD'
 'ROYAL EDITION' 'VS' 'ASAD' 'COROLLA' 'LT' 'SW' 'VTI E' 'AS' 'FL ' 'GC'
 'GXR MID XTREME' 'MID 1.3 L' '00000' 'LW' 'STEALTH' 'STD ' 'XLI 1.8'
 'ALTIS (NON GCC)' 'SE T1' 'SAT' 'S TRD AERO PK' '40 TFSI S-LINE'
 'PREMIUM PLUS' 'SE T2' 'DC' 'RUSH' 'DTS' 'LE PLATINUM CITY'
 'GLS HIGHLINE' 'PICK' 'GXR MID 60TH ANNIVERSARY' 'SALLON' 'GK' 'STILAR'
 'R' 'SLT' 'SINGLE CABIN' 'SXT TOP SUN ROOF NAV DVD' 'VTI' 'CARRERA GTS'
 'EX MID' 'MANUAL' 'TRTIM' 'CC' 'TAXI' 'WHITE' 'IM' 'DT' 'TRS' 'GXR HEV'
 'LE TITANIUM' 'STV' 'SPORTS BASIC' 'ADVENTURE 1ST EDITIO'
 '40TH ANNIVERSARY EDI' 'GXR TOP 60TH ANNIV. ' '1794 EDITION (NON GC'
 'XLI HEV' 'SE+ ANNIVERSARY EDIT' 'CREWMAX CAPSTONE (NO' 'MT']

In [93]:
print(data['bodyType'].unique())

['SEDAN' 'MINI BUS HIGH ROOF' 'PICK UP DOUBLE CAB' 'SUV' 'HATCHBACK'
 'PICK UP SINGLE CAB' 'PANEL VAN' 'BUS' 'MPV' 'ESTATE' 'PICK UP' 'VAN'
 'MINI BUS' 'COUPE' 'SUV- CROSSOVER' 'PICKUP' 'SALOON' 'STATION'
 'PANEL VAN HIGH ROOF' 'HALF PANEL VAN' 'CONVERTIBLE' 'CARGO VAN'
 'MINIVAN' 'MINI BUS SEMI HIGH ROOF' 'PICKUP DOUBLE CABIN' 'LIGHT VEHICLE'
 'CARAVAN' 'TANKER' 'PICKUP TRUCK' 'CAR' 'MOTORCYCLE'
 'PICKUP SINGLE CABIN' 'PICKUP DOUBLE CAB' 'TRUCK' 'PICK UP DOUBLE CABIN'
 'COUPE/CABRIOLET' 'FORKLIFT' 'AMBULANCE' 'REGULAR CAB' 'WINDOW VAN'
 'WAGON' 'STATION WAGON' 'PICK-UP']

In [94]:
print(data['bodyType'].nunique())

43

In [95]:
print(data['WMI'].unique())

['RKL' 'JTF' '4T1' 'JTM' 'JTD' 'MR0' 'JTE' 'MR2' '6T1' '4B0' '5TF' 'MHF'
 'JTN' 'JTC' 'JTG' '5TD' '4TA' 'JIF' 'MHK' 'MRO' 'MR1' '1NX' 'EE1' '2T3'
 'JT3' 'JT2' 'ADT' 'ZGE' 'WZ1' 'NV1' '2T1' 'LVG' 'NMT' 'WDB' 'NCP' '5YF'
 'JT4' 'RZN' '2TR' 'FJ6' 'ACV' 'CE1' '4T4' 'JTB' 'LFM' '3TM' 'JF1' 'JZX'
 '5TB' '7MU' 'AE1' 'ZE1' 'MBJ' 'J00' '3MY' 'ANE' 'SXV' '1N4' '8T1' 'FJ7'
 '4T3' '5TE' 'JTK' 'YN8' 'ZZE' 'SXA' 'ZRE' 'UP1' 'KMF' 'FZJ' 'EL5' 'STB'
 'ZSG' 'MV1' 'JNK' 'SDY' 'T30' 'VNK' 'WWW' 'XXX' 'JD4' 'JT6' 'STF' 'HDJ'
 'JZA' 'SJK' 'AVV' 'GX7' '3TY' ' JT' 'LFP' 'JAA' 'JMY' 'JJ5' 'JT1' 'LA7'
 'WV1' 'YV2' 'LSJ' 'MHE' 'RZH' 'INX' 'JN8' 'BU8' 'MOD' 'JNB' 'JTV' 'ZFA'
 'D04' 'JHG' '1GC' 'FJ4' 'JN6' 'JN1' 'JZS' '2NR' 'SYF' 'GTF' 'BU2' 'NSP'
 'TCS' 'ACA' 'ASV' 'KN9' '137' '4TI' 'LZC' 'LVC' 'HZJ' '6TI' '2CN' 'JWT'
 'S00' 'MB1' 'RN3' ' MR' 'JM3' 'V98' 'RN1' 'KNC' 'JTP' 'EE9' 'MM7' 'STD'
 'YS2' 'RX8' 'FJ8' 'SHT' 'EP9' 'NON' 'LXG' 'ZAP' 'JCB' '010' 'TGN' 'LHA'
 'MA1' '000' 'HAR' 'GZG' 'UZJ' 'ME4' 'JHE' '4TT' '411' 'RP8' 'U8Q' 'ITG'
 'JP1' 'LGW' 'JHH' 'RA6' 'EXY' 'MMM' '5T1' 'GX8' 'MRD' 'MAF' 'JT0' 'RN8'
 'TNX' 'YN5' 'LWL' 'LA6' 'MA3' 'WDD' '9BS' '2FU' 'GSV' 'KNF' 'AGH' 'NNN'
 '5T8' 'RKI' 'MMB' 'GX9' 'JDA' 'WBW' '57W' 'MRI' 'LTA' 'UZS' 'SW2' 'LFV'
 'JTH' 'JHF' 'WMA' 'JL6' 'LVA' 'GX1' 'MAT' 'LKL' 'LZW' 'MX3' 'AW1' 'WGT'
 'AAP' '7SV' 'VF3' 'WGL' 'MCX' '5TT' 'KN3' '1FD' '300' 'KMH' 'TLA' 'MZB'
 'JND' 'DAR' 'MET' 'EZC' '213' 'AFE' 'LIU' '5FP' 'MD2' 'GS1' 'FJ5' 'ITN'
 '6B2' '2C4' 'JZZ' 'LTV' ' 2T' 'CLG' 'MIT' 'LRR' 'LJ1' '2GN' '1D7' 'JIM'
 'LCF' 'L7X' 'JTS' 'M0D' 'LEF' 'S01' 'GRS' '2GC' 'BB5' 'LC0' 'LN8' 'KMJ'
 '1FT' '611' 'MLH' 'LN1' 'UAE' 'JAC' '3N6' 'WD4' 'LSK' '5HD' 'IG1' 'AE9'
 'WMW' 'TMH' 'JH4' 'KLA' 'WKD' 'GT1' 'MD6' '2AZ' 'UCF' 'MS1' 'MNT' '123'
 '914' 'YU8' 'MCV' 'LK1' 'KPD' 'STO' 'JTL' 'JT8' 'FE6' 'RKM' 'RX7' 'FH1'
 'SCR' 'WDA' '418' 'LZZ' 'WYU' 'WCY' '41B' 'RNZ' 'KL7' 'MMC' 'LM8' '00N'
 '1GN' '6TE' '1GD' 'LJN' 'GGG' 'JRN' 'KPB' 'FDZ' '4T2' 'LET' 'WAU' 'KL3'
 'KN4' 'TA4' '22E' '1Z3' 'JT5' 'WME' 'UTG' 'L70' '3N1' 'JL5' 'JL7' 'JHD'
 'YN6' 'LCO' 'RCK' 'JTZ' 'LSC' 'SAL' 'MH3' 'JTO' 'ZFC' 'LPS' 'N1N' 'JD2'
 '1GT' '1C6' 'VR3' 'T2W' 'ROB' 'MYN' 'TCL' '6TT' 'LS4' 'JJ7' 'WD8' 'YV1'
 'KLI' 'VS5' '419' 'LVV' 'MFH' 'L3H' 'KGJ' 'HJN' 'HH3' 'ZGU' 'JE3' 'RJ7'
 '5XX' 'KLB' 'JN2' 'L6T' 'J1G' 'WZI' 'BU9' 'MAU' 'EP8' 'FDH' 'LSG' 'JS1'
 'JHM' '6TD' '2TI' 'JSA' '3GY' '1G6' '211' 'JYA' '9KM' 'MC1' 'AR2' '5NM'
 'RZB' 'JIN' 'JIG' 'AYH' '1HD' 'IFZ' 'JA3' 'LGD' 'MKB' '1C4' '1ST' 'LVB'
 'VLU' 'JNC' 'LGF' 'WGY' 'MEJ' 'KNR' '5NF' 'SMV' 'WBA' 'RK4' 'MDH' 'STE'
 'KL1' 'MX8' '55S' '6TB' 'LM6' '422' 'LSF' 'D06' 'MBI' '608' '471' 'MC2'
 'S71' 'SCP' 'MKH' 'RX3' 'JTJ' 'HFY' 'CT1' 'RLB' '2HN' '454' '6T0' 'RKT'
 '3ZR' 'WGM' 'MK2' '1GJ' 'UTD' '5T0' '5N1' 'D0N' 'RN5' 'M0T' 'RKE' 'LMX'
 '1G1' 'LK6' 'JTR' 'YAR' 'BT1' 'AT1' 'SC7' '4F4' 'AC4' 'UND' 'ARO' '8LT'
 'K00' 'LA9' 'MPA' 'P01' 'ZVG' '671' '1TF' '1N6' 'CTF' 'W1W' 'LSY' '1TG'
 '1N1' 'TZA' 'LHP' 'JAM' 'K4T' 'ERE' '3D7' 'MPJ' '2ZR' 'IN6' 'HHF' '5AL'
 'MP2' 'NU4' 'JM7' 'LZY' '4TB' 'F20' '22R' 'ITD' 'HA2' '1C8' 'LAZ' '090'
 'INB' 'INR' 'W11' 'CPB' 'RF1' 'KNA' '180' 'JH2' 'STY' '074' 'JS2' 'SMT'
 'BB4' 'ST1' 'LHG' 'WV2' 'VF1' 'STM' 'PAR' '2D4' 'W01' 'T14' 'JYM' 'RX6'
 ' AN' 'AHT' 'RN4' '3TD' 'D02' 'J1D' 'SB1' 'L3A' 'VF7' 'VG4' 'MRU' 'P0T'
 'JTU' 'POT' 'KL5' 'ZCF' 'K1K' 'ZT3' 'LFZ' '2T8' '105' '61L' 'JTA' 'JDT'
 'ITE' 'TDK' 'LS6' 'T1B' '5GT' 'RN9' 'M0F' 'AUS' 'Z51' 'VF6' 'SAX' '150'
 'RF5' 'LVM' 'VZE' 'CM8' 'LBB' 'XWB' '501' 'L11' 'HJR' '2AR' '4T0' 'YBL'
 'MHM' '1G0' 'WB1' '6TF' '1V2' '425' '1HG' '1G2' '111' 'MOC' 'FE4' 'WVG'
 'A25' 'YU6' 'WVW' 'LVZ' '25T' 'LGJ' 'HA9' 'LFB' 'LNB' 'W1K' '474' '174'
 'KNM' 'BU6' 'DYK' 'YSM' 'JED' '1GR' '1LN' 'MB0' 'JFP' 'MBT' 'UFY' 'GXS'
 '5ZT' '3GN' 'VCK' 'WP0' 'VZN' 'ZWE' 'TEL' 'TEH' 'AS3' 'ET1' 'TB1' 'XZU'
 'V10' 'MFF' 'GTY' 'ENV' 'J10' 'BU1' '3T1' 'MHP' 'LFC' 'AW5' 'RN2' '1TM'
 'HJ4' 'BKL' 'K20' 'SKF' 'LDP' '24T' 'MRC' 'UTM' 'JNE' 'MS8' 'AE8' 'F2J'
 'GA7']

In [96]:
print(data['WMI'].nunique())

649

In [97]:
filtered_data = data[data['pos1'] == 'T']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2 origin               model
1       TOYOTA  JTF    J    T    F  JAPAN               HIACE
2       TOYOTA  JTF    J    T    F  JAPAN               HIACE
3       TOYOTA  JTF    J    T    F  JAPAN               HILUX
4       TOYOTA  4T1    4    T    1  JAPAN               CAMRY
5       TOYOTA  JTM    J    T    M  JAPAN        LAND CRUISER
...        ...  ...  ...  ...  ...    ...                 ...
922347  TOYOTA  6T1    6    T    1    NaN        CAMRY HYBRID
922349  TOYOTA  6T1    6    T    1    NaN        CAMRY HYBRID
922351  TOYOTA  JTM    J    T    M    NaN        LAND CRUISER
922352  TOYOTA  JTM    J    T    M    NaN        LAND CRUISER
922353  TOYOTA  JTE    J    T    E    NaN  LAND CRUISER PRADO

[179760 rows x 7 columns]

In [98]:
filtered_data = data[data['pos1'] != 'T']
filtered_data[['make', 'WMI', 'pos0','pos1', 'pos2', 'origin', 'model']]

          make  WMI pos0 pos1 pos2    origin          model
0       TOYOTA  RKL    R    K    L    TAIWAN        COROLLA
7       TOYOTA  MR0    M    R    0  THAILAND          HILUX
11      TOYOTA  MR2    M    R    2  THAILAND          YARIS
15      TOYOTA  MR0    M    R    0  THAILAND          HILUX
17      TOYOTA  RKL    R    K    L    TAIWAN        COROLLA
...        ...  ...  ...  ...  ...       ...            ...
922339  TOYOTA  VNK    V    N    K       NaN          YARIS
922344  TOYOTA  RKL    R    K    L       NaN  COROLLA CROSS
922348  TOYOTA  MHK    M    H    K       NaN         AVANZA
922350  TOYOTA  MR0    M    R    0       NaN          HILUX
922354  TOYOTA  MHF    M    H    F       NaN          YARIS

[67560 rows x 7 columns]

In [99]:
data[['make', 'pos0', 'origin']]

          make pos0  origin
0       TOYOTA    R  TAIWAN
1       TOYOTA    J   JAPAN
2       TOYOTA    J   JAPAN
3       TOYOTA    J   JAPAN
4       TOYOTA    4   JAPAN
...        ...  ...     ...
922350  TOYOTA    M     NaN
922351  TOYOTA    J     NaN
922352  TOYOTA    J     NaN
922353  TOYOTA    J     NaN
922354  TOYOTA    M     NaN

[247320 rows x 3 columns]

In [ ]:

origin_map = {
    '1': 'USA', '4': 'USA', '5': 'USA',
    '2': 'Canada',
    '3': 'Mexico',
    'J': 'Japan',
    'K': 'Korea',
    'S': 'UK',
    'W': 'Germany',
    'Z': 'Italy',
    'Y': 'Sweden/Finland',
    'L': 'China',
    'M': 'India',
    'V': 'France/Spain'
}

,chassisNumber,trim,cylinders,make,model,year,bodyType,regionalSpec,noOfDoors,origin,...,pos1,pos2,pos4,pos5,pos6,pos7,pos8,Model_Year,Plant_Code,Serial_Number
3024,RKLBB0BE7N0041036,XLI,4.0,TOYOTA,COROLLA,2022.0,SEDAN,GCC,NaN,NaN,...,K,L,B,B,0,B,E,N,0,041036
3273,MHFDX8FS6N0120773,EXR,4.0,TOYOTA,FORTUNER,2022.0,SUV,GCC,NaN,NaN,...,H,F,D,X,8,F,S,N,0,120773
5328,MR0CW12G4E0033636,DL,4.0,TOYOTA,HILUX,2014.0,PICK UP DOUBLE CAB,GCC,4.0,NaN,...,R,0,C,W,1,2,G,E,0,033636
11023,MHFKU8FS3L0181351,GXR,6.0,TOYOTA,FORTUNER,2020.0,SUV,GCC,NaN,NaN,...,H,F,K,U,8,F,S,L,0,181351
18168,MHFCX8EM0J0110510,SE,4.0,TOYOTA,INNOVA,2018.0,MPV,GCC,NaN,NaN,...,H,F,C,X,8,E,M,J,0,110510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922339,VNKKTUD38FA040994,SE+,4.0,TOYOTA,YARIS,2015.0,HATCHBACK,NON-GCC,NaN,NaN,...,N,K,K,T,U,D,3,F,A,040994
922344,RKLKUBAG0R0504648,XL,4.0,TOYOTA,COROLLA CROSS,2024.0,SUV,GCC,NaN,NaN,...,K,L,K,U,B,A,G,R,0,504648
922348,MHKMF5CF0LK009941,SE,4.0,TOYOTA,AVANZA,2020.0,SUV,GCC,NaN,NaN,...,H,K,M,F,5,C,F,L,K,009941
922350,MR0HU8CDXK0071134,GLX,6.0,TOYOTA,HILUX,2019.0,PICKUP,GCC,NaN,NaN,...,R,0,H,U,8,C,D,K,0,071134
922354,MHFB29F34M2123579,E,4.0,TOYOTA,YARIS,2021.0,SEDAN,GCC,NaN,NaN,...,H,F,B,2,9,F,3,M,2,123579