In [20]:
import pandas as pd

In [21]:
data = pd.read_csv('../Data/correctly_merged 1.csv')
data

,Unnamed: 0,chassisNumber,year,make,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,make_grouped,model_final,bodyType_raw,body_type_conflict,trim_raw,color_raw,model_final_raw
0,0,RKLBB9HE7F5115863,2015.0,TOYOTA,SE,SEDAN,GCC,4.0,SILVER,Taiwan,1000.0,5,TOYOTA,COROLLA,SEDAN,True,SE,silver,COROLLA
1,1,JTFHX02POF0099797,2015.0,TOYOTA,GLX,MINI BUS,GCC,4.0,WHITE,Japan,2000.0,15,TOYOTA,HIACE,Mini Bus High Roof,True,GLX,white,HIACE
2,2,JTFHX02P7F0094323,2015.0,TOYOTA,DX,MINI BUS,GCC,4.0,WHITE,Japan,1837.0,15,TOYOTA,HIACE,Mini Bus High Roof,True,DX,white,HIACE
3,3,JTFHXDGP7F0094373,2015.0,TOYOTA,DL,PICKUP,GCC,4.0,WHITE,Japan,1837.0,5,TOYOTA,HILUX,Pick Up Double Cab,False,DL,white,HILUX
4,4,4T1BG22K01U789089,2001.0,TOYOTA,XLI,SEDAN,Non-GCC,4.0,BROWN / BEIGE,USA,1481.0,5,TOYOTA,CAMRY,SEDAN,True,XLI,brown and beige,CAMRY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995042,995042,HY2PEAND0PB000238,2023.0,BIMOTA,NaN,MOTORCYCLE,GCC,NaN,GREEN / BLACK,China,250.0,2,BIMOTA,AYED250N 3,Motorcycle,False,NaN,green and black,AYED250N 3
995043,995043,LNGPCMXJ9PL305272,2023.0,APULUO,NaN,MOTORCYCLE,GCC,NaN,BLACK,China,150.0,2,APULUO,AP200 4H,Motorcycle,False,NaN,black,AP200 4H
995044,995044,LURJAVBM8PA024843,2023.0,CHERY,STD,COUPE,GCC,4.0,BLUE,China,NaN,2,CHERY,EQ 1,COUPE,False,STD,blue,EQ 1
995045,995045,7KGTC2C48NR003646,2022.0,ELECTRIC MOTION,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,USA,450.0,2,ELECTRIC MOTION,EPURE,Motorcycle,False,NaN,gray and black,EPURE
995046,995046,LX6TK334XS2510023,2025.0,CHANGHUA,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,China,150.0,2,CHANGHUA,CH150T-34,Motorcycle,False,NaN,gray and black,CH150T-34

In [23]:
data = data.drop(columns=['make', 'trim', 'bodyType', 'cylinders', 'color'])

In [24]:
data

,Unnamed: 0,chassisNumber,year,regionalSpec,origin,weightInKg,noOfPassengers,make_grouped,model_final,bodyType_raw,body_type_conflict,trim_raw,color_raw,model_final_raw
0,0,RKLBB9HE7F5115863,2015.0,GCC,Taiwan,1000.0,5,TOYOTA,COROLLA,SEDAN,True,SE,silver,COROLLA
1,1,JTFHX02POF0099797,2015.0,GCC,Japan,2000.0,15,TOYOTA,HIACE,Mini Bus High Roof,True,GLX,white,HIACE
2,2,JTFHX02P7F0094323,2015.0,GCC,Japan,1837.0,15,TOYOTA,HIACE,Mini Bus High Roof,True,DX,white,HIACE
3,3,JTFHXDGP7F0094373,2015.0,GCC,Japan,1837.0,5,TOYOTA,HILUX,Pick Up Double Cab,False,DL,white,HILUX
4,4,4T1BG22K01U789089,2001.0,Non-GCC,USA,1481.0,5,TOYOTA,CAMRY,SEDAN,True,XLI,brown and beige,CAMRY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995042,995042,HY2PEAND0PB000238,2023.0,GCC,China,250.0,2,BIMOTA,AYED250N 3,Motorcycle,False,NaN,green and black,AYED250N 3
995043,995043,LNGPCMXJ9PL305272,2023.0,GCC,China,150.0,2,APULUO,AP200 4H,Motorcycle,False,NaN,black,AP200 4H
995044,995044,LURJAVBM8PA024843,2023.0,GCC,China,NaN,2,CHERY,EQ 1,COUPE,False,STD,blue,EQ 1
995045,995045,7KGTC2C48NR003646,2022.0,GCC,USA,450.0,2,ELECTRIC MOTION,EPURE,Motorcycle,False,NaN,gray and black,EPURE
995046,995046,LX6TK334XS2510023,2025.0,GCC,China,150.0,2,CHANGHUA,CH150T-34,Motorcycle,False,NaN,gray and black,CH150T-34

In [26]:
data = data.drop(columns=['body_type_conflict'])

In [27]:
data

,Unnamed: 0,chassisNumber,year,regionalSpec,origin,weightInKg,noOfPassengers,make_grouped,model_final,bodyType_raw,trim_raw,color_raw,model_final_raw
0,0,RKLBB9HE7F5115863,2015.0,GCC,Taiwan,1000.0,5,TOYOTA,COROLLA,SEDAN,SE,silver,COROLLA
1,1,JTFHX02POF0099797,2015.0,GCC,Japan,2000.0,15,TOYOTA,HIACE,Mini Bus High Roof,GLX,white,HIACE
2,2,JTFHX02P7F0094323,2015.0,GCC,Japan,1837.0,15,TOYOTA,HIACE,Mini Bus High Roof,DX,white,HIACE
3,3,JTFHXDGP7F0094373,2015.0,GCC,Japan,1837.0,5,TOYOTA,HILUX,Pick Up Double Cab,DL,white,HILUX
4,4,4T1BG22K01U789089,2001.0,Non-GCC,USA,1481.0,5,TOYOTA,CAMRY,SEDAN,XLI,brown and beige,CAMRY
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995042,995042,HY2PEAND0PB000238,2023.0,GCC,China,250.0,2,BIMOTA,AYED250N 3,Motorcycle,NaN,green and black,AYED250N 3
995043,995043,LNGPCMXJ9PL305272,2023.0,GCC,China,150.0,2,APULUO,AP200 4H,Motorcycle,NaN,black,AP200 4H
995044,995044,LURJAVBM8PA024843,2023.0,GCC,China,NaN,2,CHERY,EQ 1,COUPE,STD,blue,EQ 1
995045,995045,7KGTC2C48NR003646,2022.0,GCC,USA,450.0,2,ELECTRIC MOTION,EPURE,Motorcycle,NaN,gray and black,EPURE
995046,995046,LX6TK334XS2510023,2025.0,GCC,China,150.0,2,CHANGHUA,CH150T-34,Motorcycle,NaN,gray and black,CH150T-34

In [28]:
data = data.to_csv("../Data/Cleaned.csv")