In [1]:
import pandas as pd

In [2]:
df_final = pd.read_csv("../Data/data_final_price/final.csv")

In [3]:
df_final

,chassisNumber,year,make,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,make_grouped,model_final,bodyType_raw,body_type_conflict,trim_raw,color_raw
0,RKLBB9HE7F5115863,2015.0,TOYOTA,SE,SEDAN,GCC,4.0,SILVER,Taiwan,1000.0,5,TOYOTA,COROLLA,SEDAN,True,SE,silver
1,JTFHX02POF0099797,2015.0,TOYOTA,GLX,MINI BUS,GCC,4.0,WHITE,Japan,2000.0,15,TOYOTA,HIACE,Mini Bus High Roof,True,GLX,white
2,JTFHX02P7F0094323,2015.0,TOYOTA,DX,MINI BUS,GCC,4.0,WHITE,Japan,1837.0,15,TOYOTA,HIACE,Mini Bus High Roof,True,DX,white
3,JTFHXDGP7F0094373,2015.0,TOYOTA,DL,PICKUP,GCC,4.0,WHITE,Japan,1837.0,5,TOYOTA,HILUX,Pick Up Double Cab,False,DL,white
4,4T1BG22K01U789089,2001.0,TOYOTA,XLI,SEDAN,Non-GCC,4.0,BROWN / BEIGE,USA,1481.0,5,TOYOTA,CAMRY,SEDAN,True,XLI,brown and beige
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995042,HY2PEAND0PB000238,2023.0,BIMOTA,NaN,MOTORCYCLE,GCC,NaN,GREEN / BLACK,China,250.0,2,BIMOTA,AYED250N 3,Motorcycle,False,NaN,green and black
995043,LNGPCMXJ9PL305272,2023.0,APULUO,NaN,MOTORCYCLE,GCC,NaN,BLACK,China,150.0,2,APULUO,AP200 4H,Motorcycle,False,NaN,black
995044,LURJAVBM8PA024843,2023.0,CHERY,STD,COUPE,GCC,4.0,BLUE,China,NaN,2,CHERY,EQ 1,COUPE,False,STD,blue
995045,7KGTC2C48NR003646,2022.0,ELECTRIC MOTION,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,USA,450.0,2,ELECTRIC MOTION,EPURE,Motorcycle,False,NaN,gray and black
995046,LX6TK334XS2510023,2025.0,CHANGHUA,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,China,150.0,2,CHANGHUA,CH150T-34,Motorcycle,False,NaN,gray and black

In [4]:
df_final.columns

Index(['chassisNumber', 'year', 'make', 'trim', 'bodyType', 'regionalSpec',
       'cylinders', 'color', 'origin', 'weightInKg', 'noOfPassengers',
       'make_grouped', 'model_final', 'bodyType_raw', 'body_type_conflict',
       'trim_raw', 'color_raw'],
      dtype='object')

In [5]:
df_final = df_final.drop(columns = ["bodyType_raw", "body_type_conflict", "trim_raw", "color_raw", "make_grouped"])

In [6]:
df_final

,chassisNumber,year,make,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,model_final
0,RKLBB9HE7F5115863,2015.0,TOYOTA,SE,SEDAN,GCC,4.0,SILVER,Taiwan,1000.0,5,COROLLA
1,JTFHX02POF0099797,2015.0,TOYOTA,GLX,MINI BUS,GCC,4.0,WHITE,Japan,2000.0,15,HIACE
2,JTFHX02P7F0094323,2015.0,TOYOTA,DX,MINI BUS,GCC,4.0,WHITE,Japan,1837.0,15,HIACE
3,JTFHXDGP7F0094373,2015.0,TOYOTA,DL,PICKUP,GCC,4.0,WHITE,Japan,1837.0,5,HILUX
4,4T1BG22K01U789089,2001.0,TOYOTA,XLI,SEDAN,Non-GCC,4.0,BROWN / BEIGE,USA,1481.0,5,CAMRY
...,...,...,...,...,...,...,...,...,...,...,...,...
995042,HY2PEAND0PB000238,2023.0,BIMOTA,NaN,MOTORCYCLE,GCC,NaN,GREEN / BLACK,China,250.0,2,AYED250N 3
995043,LNGPCMXJ9PL305272,2023.0,APULUO,NaN,MOTORCYCLE,GCC,NaN,BLACK,China,150.0,2,AP200 4H
995044,LURJAVBM8PA024843,2023.0,CHERY,STD,COUPE,GCC,4.0,BLUE,China,NaN,2,EQ 1
995045,7KGTC2C48NR003646,2022.0,ELECTRIC MOTION,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,USA,450.0,2,EPURE
995046,LX6TK334XS2510023,2025.0,CHANGHUA,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,China,150.0,2,CH150T-34

In [7]:
df_final = df_final.rename(columns = {"model_final" : "model"})

In [8]:
df_final

,chassisNumber,year,make,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,model
0,RKLBB9HE7F5115863,2015.0,TOYOTA,SE,SEDAN,GCC,4.0,SILVER,Taiwan,1000.0,5,COROLLA
1,JTFHX02POF0099797,2015.0,TOYOTA,GLX,MINI BUS,GCC,4.0,WHITE,Japan,2000.0,15,HIACE
2,JTFHX02P7F0094323,2015.0,TOYOTA,DX,MINI BUS,GCC,4.0,WHITE,Japan,1837.0,15,HIACE
3,JTFHXDGP7F0094373,2015.0,TOYOTA,DL,PICKUP,GCC,4.0,WHITE,Japan,1837.0,5,HILUX
4,4T1BG22K01U789089,2001.0,TOYOTA,XLI,SEDAN,Non-GCC,4.0,BROWN / BEIGE,USA,1481.0,5,CAMRY
...,...,...,...,...,...,...,...,...,...,...,...,...
995042,HY2PEAND0PB000238,2023.0,BIMOTA,NaN,MOTORCYCLE,GCC,NaN,GREEN / BLACK,China,250.0,2,AYED250N 3
995043,LNGPCMXJ9PL305272,2023.0,APULUO,NaN,MOTORCYCLE,GCC,NaN,BLACK,China,150.0,2,AP200 4H
995044,LURJAVBM8PA024843,2023.0,CHERY,STD,COUPE,GCC,4.0,BLUE,China,NaN,2,EQ 1
995045,7KGTC2C48NR003646,2022.0,ELECTRIC MOTION,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,USA,450.0,2,EPURE
995046,LX6TK334XS2510023,2025.0,CHANGHUA,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,China,150.0,2,CH150T-34

In [9]:
col_to_move = df_final.pop('model')

df_final.insert(3, 'model', col_to_move)

In [10]:
df_final

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,RKLBB9HE7F5115863,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,Taiwan,1000.0,5
1,JTFHX02POF0099797,2015.0,TOYOTA,HIACE,GLX,MINI BUS,GCC,4.0,WHITE,Japan,2000.0,15
2,JTFHX02P7F0094323,2015.0,TOYOTA,HIACE,DX,MINI BUS,GCC,4.0,WHITE,Japan,1837.0,15
3,JTFHXDGP7F0094373,2015.0,TOYOTA,HILUX,DL,PICKUP,GCC,4.0,WHITE,Japan,1837.0,5
4,4T1BG22K01U789089,2001.0,TOYOTA,CAMRY,XLI,SEDAN,Non-GCC,4.0,BROWN / BEIGE,USA,1481.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...
995042,HY2PEAND0PB000238,2023.0,BIMOTA,AYED250N 3,NaN,MOTORCYCLE,GCC,NaN,GREEN / BLACK,China,250.0,2
995043,LNGPCMXJ9PL305272,2023.0,APULUO,AP200 4H,NaN,MOTORCYCLE,GCC,NaN,BLACK,China,150.0,2
995044,LURJAVBM8PA024843,2023.0,CHERY,EQ 1,STD,COUPE,GCC,4.0,BLUE,China,NaN,2
995045,7KGTC2C48NR003646,2022.0,ELECTRIC MOTION,EPURE,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,USA,450.0,2
995046,LX6TK334XS2510023,2025.0,CHANGHUA,CH150T-34,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,China,150.0,2

In [11]:
df_final.to_csv("../Data/data_final_price/final_clean.csv", index=False)

In [12]:
df = pd.read_csv("../Data/data_final_price/final_clean.csv")

In [13]:
df_price = pd.read_csv("../Data/data_final_price/df.csv")

C:\Users\Admin\AppData\Local\Temp\ipykernel_1524\618505555.py:1: DtypeWarning: Columns (5,6,22,23,25,26,44,50,53,54,56,57,64,65,67,68,69,72,73,74,75) have mixed types. Specify dtype option on import or set low_memory=False.
  df_price = pd.read_csv("../Data/data_final_price/df.csv")

In [14]:
match_cols = [
    "chassisNumber",
    "year",
    "make",
    "model"
]

# Convert all match columns to string
for col in match_cols:
    df[col] = df[col].astype(str).str.strip().str.upper()
    df_price[col] = df_price[col].astype(str).str.strip().str.upper()

# Remove duplicate vehicle definitions from df_price
price_lookup = (
    df_price[match_cols + ["price"]]
    .drop_duplicates(subset=match_cols, keep="first")
)

# Merge price
df = df.merge(
    price_lookup,
    on=match_cols,
    how="left"
)

print("Matched:", df["price"].notna().sum())
print("Missing:", df["price"].isna().sum())

Matched: 234802
Missing: 760245

In [15]:
df

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,price
0,RKLBB9HE7F5115863,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,Taiwan,1000.0,5,NaN
1,JTFHX02POF0099797,2015.0,TOYOTA,HIACE,GLX,MINI BUS,GCC,4.0,WHITE,Japan,2000.0,15,NaN
2,JTFHX02P7F0094323,2015.0,TOYOTA,HIACE,DX,MINI BUS,GCC,4.0,WHITE,Japan,1837.0,15,NaN
3,JTFHXDGP7F0094373,2015.0,TOYOTA,HILUX,DL,PICKUP,GCC,4.0,WHITE,Japan,1837.0,5,NaN
4,4T1BG22K01U789089,2001.0,TOYOTA,CAMRY,XLI,SEDAN,Non-GCC,4.0,BROWN / BEIGE,USA,1481.0,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995042,HY2PEAND0PB000238,2023.0,BIMOTA,AYED250N 3,NaN,MOTORCYCLE,GCC,NaN,GREEN / BLACK,China,250.0,2,NaN
995043,LNGPCMXJ9PL305272,2023.0,APULUO,AP200 4H,NaN,MOTORCYCLE,GCC,NaN,BLACK,China,150.0,2,NaN
995044,LURJAVBM8PA024843,2023.0,CHERY,EQ 1,STD,COUPE,GCC,4.0,BLUE,China,NaN,2,NaN
995045,7KGTC2C48NR003646,2022.0,ELECTRIC MOTION,EPURE,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,USA,450.0,2,NaN
995046,LX6TK334XS2510023,2025.0,CHANGHUA,CH150T-34,NaN,MOTORCYCLE,GCC,NaN,GREY / BLACK,China,150.0,2,NaN

In [16]:
df["price"].isnull().sum()

np.int64(760245)

In [17]:
df.to_csv("../Data/data_final_price/final_clean_price.csv", index=False)