In [20]:
import pandas as pd

In [ ]:
df = pd.read_csv("../Data/lookup_data.csv")

In [22]:
df

           chassisNumber        make   model    year    trim     price
0      JN8BY2NY3P9415755      NISSAN  PATROL    2023   SE T2  132200.0
1       KY60332617543125      NISSAN  PATROL    2006   HT GL   24800.0
2       KY60332617543125      NISSAN  PATROL    2006     NaN       0.0
3                    NaN      NISSAN  PATROL  2025.0  PRO 4X  191900.0
4      JN10UGY60Z0097117      NISSAN  PATROL    1996     STD       0.0
...                  ...         ...     ...     ...     ...       ...
69472  ME4KC311GJ8346376       HONDA     NaN    2018     NaN       0.0
69473  ME4KC40A4TA005771       HONDA     NaN    2026     NaN       0.0
69474  1HFSC47FX6A504064       HONDA     NaN    2006     NaN       0.0
69475  WV1DAZSV9GH003041  VOLKSWAGEN     NaN    2016     NaN       0.0
69476  LRW3E7ES9RC964797         NaN     NaN     NaN     NaN       0.0

[69477 rows x 6 columns]

In [23]:
df.isnull().sum()

chassisNumber    5573
make               17
model              11
year                5
trim             7552
price              61
dtype: int64

In [24]:
df = df.dropna(subset=["price"])

In [25]:
df.isnull().sum()

chassisNumber    5573
make               17
model              11
year                5
trim             7509
price               0
dtype: int64

In [26]:
df

           chassisNumber        make   model    year    trim     price
0      JN8BY2NY3P9415755      NISSAN  PATROL    2023   SE T2  132200.0
1       KY60332617543125      NISSAN  PATROL    2006   HT GL   24800.0
2       KY60332617543125      NISSAN  PATROL    2006     NaN       0.0
3                    NaN      NISSAN  PATROL  2025.0  PRO 4X  191900.0
4      JN10UGY60Z0097117      NISSAN  PATROL    1996     STD       0.0
...                  ...         ...     ...     ...     ...       ...
69472  ME4KC311GJ8346376       HONDA     NaN    2018     NaN       0.0
69473  ME4KC40A4TA005771       HONDA     NaN    2026     NaN       0.0
69474  1HFSC47FX6A504064       HONDA     NaN    2006     NaN       0.0
69475  WV1DAZSV9GH003041  VOLKSWAGEN     NaN    2016     NaN       0.0
69476  LRW3E7ES9RC964797         NaN     NaN     NaN     NaN       0.0

[69416 rows x 6 columns]

In [27]:
df["make"].unique()

array(['NISSAN', 'NISSAN071244AA', 'TOYOTA', 'Toyota', 'TOYOTA2100875058',
       'MERCEDES BENZ', 'Ford', 'FORD', 'LAND ROVER', 'Land Rover',
       'RANGE  ROVER ', 'GREAT WALL', 'MITSUBISHI', 'GMC', 'CHEVROLET',
       'Nissan', nan, 'Hyundai', 'HYUNDAI', 'AVANTY', 'HONDA', 'PORSCHE',
       'Porsche', 'BAJAJ', 'Honda', 'BMW', 'JAC', 'CHANGAN', 'TOYOTAالمـ',
       'TOYOTA12024631', 'JEEP', 'VOLKSWAGEN', 'FORD2140777009',
       ' MITSUBISHI', 'DODGE', 'MAZDA', 'MG', 'Mazda', 'POLESTAR', 'KAMA',
       'LEXUS', 'Mitsubishi', 'ISUZU', 'Lexus', 'KIA', 'RAM', 'INFINITI',
       'KIA ', 'MERCEDES-BENZ', 'LYNK & CO', 'Kia', 'KIA41964', 'MINI',
       'Jeep', 'SUZUKI', 'HYUNDAI2120117999', 'Infiniti', 'AUDI', 'Audi',
       'ROLLS ROYCE', 'FIAT', 'LINCOLN', 'BENTLEY', 'Fiat', 'TANK',
       'Lincoln', 'Royal Enfield', 'CADILLAC', 'CHRYSLER', 'HINO',
       'BENDA', 'HINO ', 'HUMMER', 'ABARTH', 'DEEPAL', 'PEUGEOT',
       'ASHOK LEYLAND', 'FORD ', 'CHERVOLET', 'TESLA', 'Tesla', 'KAIYI',
       'BAIC', 'Domy', 'VOLVO', 'Volvo', 'JMC', 'EICHER', 'FOTON',
       'DONGFENG', 'ESHER', 'TATA', 'DAIHATSU', 'TATA ', 'NISSEN',
       'DATSUN', 'GENESIS', 'RENAULT', 'Chevrolet', 'Volkswagen', 'AUDI ',
       'Peugeot', 'Dodge', 'Jaguar', 'JAGUAR', 'Bentley', 'GEELY', 'HO',
       'SERES', 'ROEWE', 'RABDAN', 'DODGE ', 'FAW', 'Cadillac', 'Mini',
       'SANYA', 'Polaris', 'Indian', 'Harley-Davidson', 'CHANGHUA',
       'SHARMAX', 'HUAIHAI', 'VICTORY', 'Vespa', 'FERRARI', 'Triumph',
       'HERO', 'MASERATI', 'Bajaj', 'Maserati', 'TESLA2130144264',
       'SLINGSHOT', 'JETOUR', 'SMART', 'BYD', 'Kawasaki', 'CHERY',
       'BUICK', 'BUGATTI', 'Geely', 'SKODA', 'HAVAL', 'audi', 'ROCKY',
       'EXEED', 'Suzuki', 'SSANGYONG', 'SUBARU', 'Yamaha', 'YAMAHA',
       'vanderhall', 'LONSIN', 'VESPA ', 'SAIMO', 'Subaru', 'MCLAREN',
       'MAXUS', 'Maxus', 'UNICORN', 'JIDU', 'Daihatsu', 'ROX', 'JIYUE',
       'POLARIS', 'Chrysler', 'AITO', 'polaris', 'LAMBORGHINI',
       'Lamborghini', 'TVS', 'CMC', 'TYANMA', ' CAN-AM',
       'BLUE BAIRD VISION', 'HONGQI', 'ALFA ROMEO', 'FOLONY', 'AYED',
       'UNKNOWN', 'SHRMAX', 'NWONE', 'GAC', 'AVATR', 'OMODA', 'LUXGEN',
       'Hummer', 'sanya', 'SANIYA', 'SY', 'Sanya', 'SYM', 'Rolls Royce',
       'SANYOU', 'sanya ', 'MOTORCYCLE SANYA', 'SANYA ', 'Renault',
       'MINI COUPE', 'LEADING', 'DFSK', 'SLING SHOT', 'Escher', 'JAECOO',
       'BRILLIANCE', 'SLING', 'POL', 'Scorpa', 'NETA', 'AEOLUS', 'NIO',
       'IVECO', 'MHERO', 'BAOJUN', 'MV', 'MERCURY', 'Hero', 'ZHENGZHOU ',
       'Great Wall', 'STD', 'ZNA', 'Ducati', 'LIFAN', 'TRD', 'Exeed',
       'Ferrari', 'CHERY ', 'UAZ', 'LANCIA', 'OPEL', 'KAWASAKI',
       'FORTHING', 'CFMoto', 'LEADING IDEAL', 'FORCE', 'ASTON MARTIN',
       'MAHINDRA', 'MAHINDRA ', 'SCION', 'LEOPARD', 'Kymco', 'Hino',
       'BESTUNE', 'CITROEN', 'Citroen', 'Alfa Romeo', 'VESPA', 'HIPHI',
       'AL DAMANI', 'LYKAN', 'MANN', 'SAAB', 'Skoda', 'FOZO',
       'LYNK and CO', 'DONGFENG-AEOLUS', 'SEAT', 'SANDSTORM', 'Aprilia',
       'baja', 'YAMAH', 'DONGFENG-XIAOKA', 'DEXER', 'Tata', 'VOYAH',
       'VICTORIA ', 'SCANIA', 'vespa', 'Victory', 'MV Agusta', 'VICTORIA',
       'ACURA', 'KAOE K1', 'BMWb', 'SOUEAST', 'Yamaha ', 'ZEEKR', 'XAOMI',
       'XIAOMI', 'INEOS ', 'AM', 'CAN', 'CAN AM', 'INEOS', 'HARLEY',
       'HARLEY ', 'KAN M', 'CAN-AM', 'CAN AM ', 'Harley-Davidson200',
       'Aston Martin', 'CAN -AM ', 'RANGE ROVER', 'CAN AM SPYDER',
       'LOTUS', 'LI AUTO', 'LIXIANG', 'VANDERHALL', 'KING LONG',
       'Husqvarna', ' VANDERHALL   ', 'TRUMPCHI', 'BIUE BAIRD', 'TGB',
       'VANDER', ' TGB', 'DONGFENG Eπ', 'Beta', 'KTM', 'DONGFENG eπ',
       'Buell', 'Smart', 'XPENG', 'TGA', 'LiveWire', 'Seat', 'yamaha',
       'SATURN', 'BLUEBIRD', 'LIFAN ', 'BAW', 'CHERY - ICAR', 'CHANGHUA ',
       'CH', 'Harley', 'Maclaren', 'ZONSEN', 'Isuzu', 'HUAIHAI ', 'baw',
       'Zongshen', 'Voge', 'Montesa', 'PONTIAC', 'Mercury',
       'RANGE  ROVER', 'IM', 'ZXAUTO', 'BYD - YANGWANG', 'AVENGER',
       'SHARAMAX', 'tv', 'PONICA', 'BYD - DENZA', 'DUTSUN', 'GR', 'POWER',
       'Gas Gas', 'VGV', 'RIVIAN', 'Harley Davidson', 'Piaggio',
       'TVS APACHE RTR160 4V', 'ZX AUTO', 'GRAND TIGER', ' YAMAHA',
       'Victoria ', 'MAEXTRO ', 'MAEXTRO', 'VANDERHALL ', 'ITALJET',
       'Yadea', 'LEAPMOTOR', 'Moto Guzzi', 'DELTA', 'HARLEY DAVIDSON',
       'YAHAMA', 'MERCEDES', 'Sherco', 'NEW', 'Benelli', 'KB', 'SKYWELL',
       'LEAPMOTORS', 'HART FORD', 'BENELLI TNT 150', 'DAT', 'LUCID',
       'SHARM', 'LI', 'VINFAST', 'SHARMAX ', 'Li AUTO', 'MAYBACH', 'Opel',
       'WULING', 'BORGWARD', 'LADA', 'CFMOTO', 'ASHOK', 'RIDDARA',
       'ADMIRAL', 'SANYAN', 'PEMBLETON', 'SLINGSHOT ', 'ASHOK ', 'ZOTYE',
       'HARLEY DAVIDSCN03', 'LIXIANG ', 'INDIAN  MOTORCYCLE', 'FLONY',
       'MOTO MORNI', 'ARIEL', ' POWEREAGLE', 'ATOM', 'HH', 'SHA',
       'PONTIAC ', 'FACTORY FIVE GTM ', 'DELOREAN', 'JANNARELLY',
       'PONTICA', 'TR', 'Haojue', 'POWEREAGLE', 'AVALON', 'del', 'CBF',
       'XCMG', 'XIAOM', ' ZHENGZHOU', 'CHAMP ZXMOTO', 'VENIC', 'LIEBHERR',
       'ATF ', 'PHONIX', 'ZNEN', 'LIEBHERR LTM', 'CATERHAM', 'MOTORCYCLE',
       'A', 'ATF', 'AYED ', 'DORCEN', 'AFTEK', 'SAME', 'PROTON', 'Buick',
       'VOLG', 'CHAMP', 'SAMSUNG', 'DAEWOO', 'Lotus', 'TRIUMPH', 'GEO',
       'KOASKO 0', 'HAR', 'Hyosung', 'PAGANI', 'EQUATION', 'FACTORY FIVE',
       'PREVOST', 'SANY', 'RANRANGE ROVER', 'IND', 'YAMAHA YZF',
       'CF MOTO 700 CL X', 'OCC', 'Sharmax Fx200', 'ARI', 'AIQAR',
       'DAYUN', 'SHANG JAN', 'MORGAN', 'VOLTAMP', 'SANAYA', 'ZONTES',
       'HYCAN', 'QINGLING', 'TAM', 'MOCK', 'CP', 'GPX', 'WIESMANN',
       'PLYMOUTH', 'SAIC', 'ECOWAY', 'Mahindra', 'AYED AYED', 'MAC',
       'ZHENGZHOU', 'BUICK SKYLARK', 'SINOTRUK', 'JINBEI', 'SWM', 'DAF',
       'ROYAL ALLOY', 'KIMMCO', 'CATERPILLAR ', 'GUNAU', 'EMPALA',
       'GWM - WEY', 'ESCHER', 'DBR', 'NIU', 'MAN', 'Electric Motion',
       'OLDSMOBILE', 'CHANGHUA - MAX180', 'SPYDER', 'CHERY - iCAR',
       'AGUSTA', 'SILNGSHOT', 'Lip Motor', 'FANTIC', 'MANITOU', 'KOASKO',
       'vgv', 'RADAR', 'G10', 'kove', 'BAOJUN YEP', 'JOYLONG',
       'GRAND TIGER ', 'ARCFOX', 'ZENIN', 'SPIDER', 'Zhengzhou', 'VIC',
       'empala', 'APULUO', 'KOENIGSEGG', 'PADAR', 'SOUO', 'CF MOTO',
       'KGM', 'DEXR', 'CHANGUA', 'VAN', 'PAGANI ', 'RANGE', 'LONCIN',
       'ATV', 'ZNIN', 'TRALER', 'LX', 'APACHE', 'SWIFT', 'YBR 125',
       'KAWAZAKI', 'LIEBHERR LTM 1200', 'Zero', 'CARBODIES',
       'DAEWOO 106 BF', 'CAN -AM', 'HIGER', 'MERCEDES ', 'T7',
       'AYED BIKE', 'Bimota', 'S Y', 'NIXYA', 'FARIZON', 'JCB', 'ZAMIYAD',
       'HS', 'GRA', 'PUYUAN', 'hig'], dtype=object)

In [28]:
df = df[df["price"] != 0]

In [29]:
df

,chassisNumber,make,model,year,trim,price
0,JN8BY2NY3P9415755,NISSAN,PATROL,2023,SE T2,132200.0
1,KY60332617543125,NISSAN,PATROL,2006,HT GL,24800.0
3,NaN,NISSAN,PATROL,2025.0,PRO 4X,191900.0
6,Z8NTANY62DS001475,NISSAN,PATROL,2013,LE T1 +,55600.0
9,JN8AY2NY0R9500597,NISSAN,PATROL,2024,LE T1,151900.0
...,...,...,...,...,...,...
69451,LDP95H962SY852430,VOYAH,TAISHAN,2025.0,STD (NON GCC),280000.0
69454,JN6BE6CS9S9440417,NISSAN,URVAN/VAN,2025,S,93450.0
69455,JN1HZ14S1FX072936,NISSAN,NISSAN Z 370,2024.0,GL,14200.0
69457,7KGTC2C14NR003567,NISSAN,VANDERHALL CARM,2022,NaN,16100.0
69466,LM8F7E692NA041147,TOYOTA,NaN,2022,SE,36400.0

In [30]:
df.isnull().sum()

chassisNumber    5572
make                0
model               1
year                0
trim              125
price               0
dtype: int64

In [31]:
df[df["price"] == 0]

Empty DataFrame
Columns: [chassisNumber, make, model, year, trim, price]
Index: []

In [32]:
df = df.dropna(subset=["trim"])

In [33]:
df

,chassisNumber,make,model,year,trim,price
0,JN8BY2NY3P9415755,NISSAN,PATROL,2023,SE T2,132200.0
1,KY60332617543125,NISSAN,PATROL,2006,HT GL,24800.0
3,NaN,NISSAN,PATROL,2025.0,PRO 4X,191900.0
6,Z8NTANY62DS001475,NISSAN,PATROL,2013,LE T1 +,55600.0
9,JN8AY2NY0R9500597,NISSAN,PATROL,2024,LE T1,151900.0
...,...,...,...,...,...,...
69450,JN1AS44D1TW054706,NISSAN,SX 240 COUPE,1996,GF,74400.0
69451,LDP95H962SY852430,VOYAH,TAISHAN,2025.0,STD (NON GCC),280000.0
69454,JN6BE6CS9S9440417,NISSAN,URVAN/VAN,2025,S,93450.0
69455,JN1HZ14S1FX072936,NISSAN,NISSAN Z 370,2024.0,GL,14200.0
69466,LM8F7E692NA041147,TOYOTA,NaN,2022,SE,36400.0

In [34]:
df.isnull().sum()

chassisNumber    5572
make                0
model               1
year                0
trim                0
price               0
dtype: int64

In [35]:
df[df["model"].isna()]

           chassisNumber    make model  year trim    price
69466  LM8F7E692NA041147  TOYOTA   NaN  2022   SE  36400.0

In [38]:
df.loc[69466, "model"] = "Camry"

In [39]:
df.loc[69466]

chassisNumber    LM8F7E692NA041147
make                        TOYOTA
model                        Camry
year                          2022
trim                            SE
price                      36400.0
Name: 69466, dtype: object

In [40]:
df

,chassisNumber,make,model,year,trim,price
0,JN8BY2NY3P9415755,NISSAN,PATROL,2023,SE T2,132200.0
1,KY60332617543125,NISSAN,PATROL,2006,HT GL,24800.0
3,NaN,NISSAN,PATROL,2025.0,PRO 4X,191900.0
6,Z8NTANY62DS001475,NISSAN,PATROL,2013,LE T1 +,55600.0
9,JN8AY2NY0R9500597,NISSAN,PATROL,2024,LE T1,151900.0
...,...,...,...,...,...,...
69450,JN1AS44D1TW054706,NISSAN,SX 240 COUPE,1996,GF,74400.0
69451,LDP95H962SY852430,VOYAH,TAISHAN,2025.0,STD (NON GCC),280000.0
69454,JN6BE6CS9S9440417,NISSAN,URVAN/VAN,2025,S,93450.0
69455,JN1HZ14S1FX072936,NISSAN,NISSAN Z 370,2024.0,GL,14200.0
69466,LM8F7E692NA041147,TOYOTA,Camry,2022,SE,36400.0

In [41]:
df.isnull().sum()

chassisNumber    5572
make                0
model               0
year                0
trim                0
price               0
dtype: int64

In [43]:
df["make"].unique()

array(['NISSAN', 'NISSAN071244AA', 'TOYOTA', 'Toyota', 'TOYOTA2100875058',
       'MERCEDES BENZ', 'FORD', 'Ford', 'LAND ROVER', 'Land Rover',
       'GREAT WALL', 'MITSUBISHI', 'GMC', 'CHEVROLET', 'Nissan',
       'Hyundai', 'HYUNDAI', 'AVANTY', 'HONDA', 'PORSCHE', 'Honda', 'BMW',
       'CHANGAN', 'TOYOTAالمـ', 'TOYOTA12024631', 'JEEP', 'VOLKSWAGEN',
       'FORD2140777009', 'DODGE', 'MAZDA', 'MG', 'Mazda', 'ISUZU',
       'LEXUS', 'Mitsubishi', 'Lexus', 'KIA', 'RAM', 'INFINITI', 'KIA ',
       'MERCEDES-BENZ', 'LYNK & CO', 'Kia', 'KIA41964', 'MINI', 'Jeep',
       'SUZUKI', 'HYUNDAI2120117999', 'Infiniti', 'AUDI', 'Audi', 'FIAT',
       'LINCOLN', 'BENTLEY', 'TANK', 'Lincoln', 'CADILLAC', 'CHRYSLER',
       'HINO', 'HINO ', 'PEUGEOT', 'ASHOK LEYLAND', 'FORD ', 'CHERVOLET',
       'TESLA', 'Tesla', 'KAIYI', 'BAIC', 'VOLVO', 'Volvo', 'DONGFENG',
       'JMC', 'RENAULT', 'Volkswagen', 'AUDI ', 'Peugeot', 'JAGUAR',
       'Chevrolet', 'GEELY', 'Dodge', 'SERES', 'ROEWE', 'DODGE ', 'Mini',
       'ROLLS ROYCE', 'JAC', 'MASERATI', 'Maserati', 'TESLA2130144264',
       'JETOUR', 'SMART', 'BYD', 'CHERY', 'SKODA', 'Geely', 'HAVAL',
       'DAIHATSU', 'EXEED', 'GENESIS', 'Suzuki', 'SUBARU', 'Cadillac',
       'Subaru', 'MCLAREN', 'MAXUS', 'JIDU', 'ROX', 'JIYUE', 'Porsche',
       'Chrysler', 'LAMBORGHINI', 'CMC', 'HONGQI', 'ALFA ROMEO', 'GAC',
       'HUMMER', 'AVATR', 'OMODA', 'Renault', 'JAECOO', 'NIO', 'IVECO',
       'MHERO', 'BAOJUN', 'MERCURY', 'ZNA', 'Exeed', 'FERRARI', 'CHERY ',
       'LANCIA', 'OPEL', 'FORTHING', 'ABARTH', 'FORCE', 'ASTON MARTIN',
       'MAHINDRA', 'MAHINDRA ', 'LEOPARD', 'BUGATTI', 'BESTUNE',
       'CITROEN', 'Citroen', 'VICTORY', 'HIPHI', 'Skoda', 'LYNK and CO',
       'DONGFENG-AEOLUS', 'SEAT', 'AEOLUS', 'Maxus', 'TATA', 'ACURA',
       'UAZ', 'DEEPAL', 'VOYAH', 'RABDAN', 'SOUEAST', 'ZEEKR', 'XAOMI',
       'XIAOMI', 'POLESTAR', 'INEOS ', 'INEOS', 'RANGE ROVER', 'LOTUS',
       'Aston Martin', 'LI AUTO', 'KING LONG', 'LEADING IDEAL',
       'DONGFENG Eπ', 'AITO', 'DONGFENG eπ', 'XPENG', 'SATURN', 'BAW',
       'FOTON', 'CHERY - ICAR', 'SAAB', 'SSANGYONG', 'baw', 'PONTIAC',
       'BUICK', 'ZXAUTO', 'BYD - YANGWANG', 'LUXGEN', 'BYD - DENZA',
       'VGV', 'RIVIAN', 'MAEXTRO ', 'MAEXTRO', 'LEAPMOTOR', 'SKYWELL',
       'LEAPMOTORS', 'DFSK', 'DONGFENG-XIAOKA', 'LUCID', 'LI', 'MAYBACH',
       'Opel', 'WULING', 'BORGWARD', 'LADA', 'RIDDARA', 'AL DAMANI',
       'ZOTYE', 'PONTICA', 'BRILLIANCE', 'CATERHAM', 'PROTON', 'DATSUN',
       'PAGANI', 'PREVOST', 'KTM', 'FAW', 'MORGAN', 'DORCEN', 'SANDSTORM',
       'HYCAN', 'QINGLING', 'TAM', 'VINFAST', 'SAIC', 'LYKAN', 'SINOTRUK',
       'JINBEI', 'GWM - WEY', 'CHERY - iCAR', 'vgv', 'BAOJUN YEP',
       'ARCFOX', 'PADAR', 'PAGANI ', 'MERCEDES ', 'JCB', 'hig'],
      dtype=object)