In [1]:
import pandas as pd

In [2]:
# 1. Load your dataset (replace with your actual file path/method)
df = pd.read_csv("../Data/final_clean_ShortVIN.csv")

In [3]:
df

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,4B0189130,1993.0,TOYOTA,COROLLA,LE,SEDAN,GCC,4.0,WHITE,JAPAN,1100.0,5.0
1,EE1004019201,1993.0,TOYOTA,COROLLA,LE,SEDAN,GCC,4.0,WHITE,JAPAN,1100.0,5.0
2,ZGE216016857,2010.0,TOYOTA,RAV4,BASE,SUV,GCC,4.0,GREY,JAPAN,1890.0,5.0
3,NV18008048,2005.0,TOYOTA,CAMRY,XLI,SEDAN,GCC,4.0,BLACK,JAPAN,1400.0,5.0
4,NV18056527,2004.0,TOYOTA,CAMRY,GLI,SEDAN,GCC,4.0,WHITE,JAPAN,1600.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
13268,4520016452,1978.0,NaN,CRANE/MAN26280,CTTO CRANE/MAN26280,VAN,GCC,6.0,WHITE,GERMANY,1600.0,3.0
13269,344870M169272,1970.0,OLDSMOBILE,NaN,STD,COUPE,GCC,8.0,WHITE,USA,1402.0,5.0
13270,FK415KB30502,1996.0,NaN,NaN,GLE,TRUCK,GCC,4.0,YELLOW,JAPAN,5000.0,2.0
13271,SG20J014379,2015.0,YAMAHA,MAJESTY,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,200.0,1.0
13272,MI76734700,2015.0,MANITOU,MTX1740SLT,GL,HEAVY EQUIPMENT,GCC,4.0,GREY,ITALY,12000.0,1.0

In [4]:
# 2. Define your 4 priority columns
priority_cols = ["year", "make", "model", "trim"]

In [5]:
# 3. Drop duplicates based ONLY on those 4 columns, keeping the first occurrence
df_cleaned = df.drop_duplicates(subset=priority_cols, keep="first")

In [6]:
# 4. Save or view your cleaned dataset
df_cleaned

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,4B0189130,1993.0,TOYOTA,COROLLA,LE,SEDAN,GCC,4.0,WHITE,JAPAN,1100.0,5.0
2,ZGE216016857,2010.0,TOYOTA,RAV4,BASE,SUV,GCC,4.0,GREY,JAPAN,1890.0,5.0
3,NV18008048,2005.0,TOYOTA,CAMRY,XLI,SEDAN,GCC,4.0,BLACK,JAPAN,1400.0,5.0
4,NV18056527,2004.0,TOYOTA,CAMRY,GLI,SEDAN,GCC,4.0,WHITE,JAPAN,1600.0,5.0
5,NV18087272,2005.0,TOYOTA,CAMRY,GLI,SEDAN,GCC,4.0,SILVER,JAPAN,1200.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
13267,2S87U8N135556,1978.0,NaN,NaN,BASE,COUPE,GCC,8.0,GOLDEN,CANADA,1780.0,4.0
13268,4520016452,1978.0,NaN,CRANE/MAN26280,CTTO CRANE/MAN26280,VAN,GCC,6.0,WHITE,GERMANY,1600.0,3.0
13269,344870M169272,1970.0,OLDSMOBILE,NaN,STD,COUPE,GCC,8.0,WHITE,USA,1402.0,5.0
13270,FK415KB30502,1996.0,NaN,NaN,GLE,TRUCK,GCC,4.0,YELLOW,JAPAN,5000.0,2.0
13272,MI76734700,2015.0,MANITOU,MTX1740SLT,GL,HEAVY EQUIPMENT,GCC,4.0,GREY,ITALY,12000.0,1.0

In [7]:
df_cleaned.to_csv("../Data/final_clean_ShortVIN_lookup_data.csv", index=False)