## noOfPaasengers

In [118]:
import pandas as pd
import numpy as np

In [119]:
df = pd.read_csv("../Data/ShortVIN.csv")

In [120]:
df

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_class,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against
0,4B0189130,1993.0,TOYOTA,COROLLA,LE,SEDAN,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
1,EE1004019201,1993.0,TOYOTA,COROLLA,LE,SEDAN,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
2,ZGE216016857,2010.0,TOYOTA,RAV4,BASE,SUV,GCC,4.0,GREY,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
3,NV18008048,2005.0,TOYOTA,CAMRY,XLI,SEDAN,GCC,4.0,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
4,NV18056527,2004.0,TOYOTA,CAMRY,GLI,SEDAN,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13268,4520016452,1978.0,NaN,CRANE/MAN26280,CTTO CRANE/MAN26280,VAN,GCC,6.0,WHITE,GERMANY,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13269,344870M169272,1970.0,OLDSMOBILE,NaN,STD,COUPE,GCC,8.0,WHITE,USA,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13270,FK415KB30502,1996.0,NaN,NaN,GLE,TRUCK,GCC,4.0,YELLOW,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13271,SG20J014379,2015.0,IM,MAJESTY,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13272,MI76734700,2015.0,MANITOU,MTX1740SLT,GL,HEAVY EQUIPMENT,GCC,4.0,GREY,ITALY,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
df.columns

Index(['chassisNumber', 'year', 'make', 'model', 'trim', 'bodyType',
       'regionalSpec', 'cylinders', 'color', 'origin', 'weightInKg',
       'noOfPassengers', 'make_raw', 'model_raw', 'bodyType_raw', 'trim_raw',
       'color_raw', 'origin_raw', 'cylinders_raw', 'weightInKg_raw',
       'year_raw', 'year_suspicious', 'chassis_class', 'chassis_era_flag',
       'chassis_wmi_flag', 'vin_class', 'vin_confidence', 'vin_score',
       'vin_wmi_make', 'vin_decoded_years', 'vin_evidence_for',
       'vin_evidence_against'],
      dtype='object')

In [122]:
df["noOfPassengers"]

0        5.0
1        5.0
2        5.0
3        5.0
4        5.0
        ...
13268    3.0
13269    5.0
13270    2.0
13271    1.0
13272    1.0
Name: noOfPassengers, Length: 13273, dtype: float64

In [123]:
df["noOfPassengers"].isnull().sum()

np.int64(3)

In [124]:
df[df["noOfPassengers"].isna()]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_class,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against
1258,3005075-AE,2007.0,TOYOTA,CAMRY,NaN,SEDAN,NaN,NaN,SILVER,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
10832,KHT361HAKU000355,2019.0,HYUNDAI,VELOSTER,NaN,HATCHBACK,NaN,NaN,BLUE,SOUTH KOREA,...,malformed_vin_candidate,NaN,NaN,UNCERTAIN,0.873,2.0,NaN,NaN,All chars in valid VIN charset (no I/O/Q) | Se...,Position 10 'U' is NOT a valid VIN year code |...
10881,INKM4GB9PF023045,2023.0,MERCEDES-BENZ,NaN,NaN,NaN,NaN,NaN,NaN,GERMANY,...,malformed_vin_candidate,NaN,NaN,UNCERTAIN,0.982,0.0,NaN,1985/2015,Position 10 'F' is valid year code → 1985/2015...,Contains VIN-banned chars: ['I'] | Position 9 ...

In [125]:
df["noOfPassengers"] = df["noOfPassengers"].fillna(5)

In [126]:
df["noOfPassengers"].isnull().sum()

np.int64(0)

In [127]:
df["noOfPassengers"].dtype

dtype('float64')

In [128]:
df["noOfPassengers"] = df["noOfPassengers"].astype("int64")

In [129]:
df["noOfPassengers"]

0        5
1        5
2        5
3        5
4        5
        ..
13268    3
13269    5
13270    2
13271    1
13272    1
Name: noOfPassengers, Length: 13273, dtype: int64

In [130]:
df[(df["bodyType"].str.lower() == "sedan") & (df["noOfPassengers"] != 5)]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_class,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against
6,NCP420128409,2008.0,TOYOTA,YARIS,STD,SEDAN,GCC,0.0,SILVER,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
51,ZGE216068889,2014.0,TOYOTA,WISH,STD,SEDAN,GCC,4.0,GREY,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
80,NV18075956,2006.0,TOYOTA,CAMRY,BASE,SEDAN,GCC,4.0,SILVER,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
129,ZE15054762,2005.0,TOYOTA,COROLLA,S,SEDAN,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
135,ZRE1425231364,2012.0,TOYOTA,COROLLA,STD,SEDAN,GCC,4.0,SILVER,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12931,6Y82G437965,1966.0,LINCOLN,CONTINENTAL,PREMIER LWB,SEDAN,GCC,8.0,BLUE,USA,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13221,HLS30151947,1973.0,DATSUN,Z 240,A,SEDAN,GCC,6.0,WHITE,JAPAN,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13232,HLS30296080,1976.0,DATSUN,ZX280,S,SEDAN,GCC,4.0,ORANGE,USA,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13240,HLC110011196,1977.0,DATSUN,SKYLINE,STD,SEDAN,GCC,6.0,BLACK,JAPAN,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13254,HLS3018349,1971.0,NaN,NaN,S,SEDAN,GCC,4.0,BLUE,JAPAN,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN

In [131]:
df.loc[(df["bodyType"].str.lower() == "sedan") & (df["noOfPassengers"] != 5), "noOfPassengers"] = 5

In [132]:
df[(df["bodyType"].str.lower() == "sedan") & (df["noOfPassengers"] != 5)]

Empty DataFrame
Columns: [chassisNumber, year, make, model, trim, bodyType, regionalSpec, cylinders, color, origin, weightInKg, noOfPassengers, make_raw, model_raw, bodyType_raw, trim_raw, color_raw, origin_raw, cylinders_raw, weightInKg_raw, year_raw, year_suspicious, chassis_class, chassis_era_flag, chassis_wmi_flag, vin_class, vin_confidence, vin_score, vin_wmi_make, vin_decoded_years, vin_evidence_for, vin_evidence_against]
Index: []

[0 rows x 32 columns]

In [133]:
df["noOfPassengers"].unique()

array([   5,    2,    3,    8,    6,    7,    4,   11,    9,   20,  430,
         12,   84,   30,   10,    1,   26,   17,   50, 1599,   15, 1000,
       3000,  280,   13,    0,  100, 1500,   29,   67])

In [134]:
df[df["noOfPassengers"] > 1000]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_class,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against
6918,HR31153974,1988.0,NISSAN,SKYLINE,4,COUPE,GCC,4.0,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
9555,FE434EA60032,1991.0,MITSUBISHI,CANTER,STD,PICKUP,GCC,8.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
11883,SDYOE263385,1997.0,MAZDA,NaN,STD,PICKUP,GCC,4.0,RED,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
11884,SDYOE2603385,1997.0,MAZDA,NaN,STD,PICKUP,GCC,4.0,RED,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
df[(df["make"] == "TOYOTA") & (df["model"] == "86")]

Empty DataFrame
Columns: [chassisNumber, year, make, model, trim, bodyType, regionalSpec, cylinders, color, origin, weightInKg, noOfPassengers, make_raw, model_raw, bodyType_raw, trim_raw, color_raw, origin_raw, cylinders_raw, weightInKg_raw, year_raw, year_suspicious, chassis_class, chassis_era_flag, chassis_wmi_flag, vin_class, vin_confidence, vin_score, vin_wmi_make, vin_decoded_years, vin_evidence_for, vin_evidence_against]
Index: []

[0 rows x 32 columns]

In [136]:
df["noOfPassengers"].value_counts()

noOfPassengers
5       8923
3       1396
2       1251
7        841
4        378
8        215
1        120
6         82
9         20
84        10
0          6
26         5
1000       3
11         2
17         2
15         2
1500       2
30         2
10         2
430        1
20         1
12         1
50         1
1599       1
280        1
3000       1
13         1
100        1
29         1
67         1
Name: count, dtype: int64

In [137]:
df[(df["noOfPassengers"] > 10) & (df["bodyType"] != "BUS")]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_class,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against
963,RZH1150000963,1994.0,TOYOTA,HIACE,STD,VAN,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
1928,SXA100047214,1994.0,TOYOTA,NaN,XLI,SUV,GCC,4.0,GREY,USA,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
2380,RZH1140006208,1991.0,TOYOTA,HIACE,DLX,VAN,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
6323,ANE120065466,2007.0,TOYOTA,WISH,W,STATION WAGON,GCC,4.0,GREY,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
6879,KY60810802,1995.0,NISSAN,NaN,SAT,SUV,GCC,6.0,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
6918,HR31153974,1988.0,NISSAN,SKYLINE,4,COUPE,GCC,4.0,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
7208,UFGD21402760,1986.0,NISSAN,NaN,STE,PICKUP,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
7295,T30JA5G037157,2006.0,NISSAN,X-TRAIL,S,STATION WAGON,GCC,4.0,GREY,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
7753,WGY60322637,1996.0,NISSAN,PATROL,SAFARI T1,SUV,GCC,6.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
8207,KY60319251,1991.0,NISSAN,PATROL,C,SUV,GCC,6.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
8818,WGY60380725,1994.0,NISSAN,PATROL,SAFARI T1,SUV,GCC,6.0,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
9194,BNR34402620,2002.0,NISSAN,SKYLINE,1000,COUPE,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
9555,FE434EA60032,1991.0,MITSUBISHI,CANTER,STD,PICKUP,GCC,8.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
9752,200B4355,2014.0,MITSUBISHI,DELICA,STD,VAN,GCC,4.0,SILVER,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
10004,FE434EA61911,1992.0,MITSUBISHI,CANTER,STD,TRUCK,GCC,4.0,BLUE,UAE,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
10017,FH100HA30272,1992.0,MITSUBISHI,NaN,STD,TRUCK,GCC,4.0,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
11258,CP51A103633,2005.0,SUZUKI,SKYWAVE,NaN,MOTORCYCLE,GCC,NaN,SILVER,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
11883,SDYOE263385,1997.0,MAZDA,NaN,STD,PICKUP,GCC,4.0,RED,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
11884,SDYOE2603385,1997.0,MAZDA,NaN,STD,PICKUP,GCC,4.0,RED,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13197,4G13SPY33512,2016.0,CMC,VERYCA,S,VAN,GCC,4.0,WHITE,TAIWAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN

In [138]:
df.loc[(df["noOfPassengers"] > 10) & (df["bodyType"] != "BUS"), "noOfPassengers"] = np.nan

In [139]:
df["noOfPassengers"].isnull().sum()

np.int64(20)

## year

In [140]:
df["year"].isnull().sum()

np.int64(0)

In [141]:
df["year"].dtype

dtype('float64')

In [142]:
df["year"] = df["year"].astype("int64")

In [143]:
df["year"].dtype

dtype('int64')

## origin

In [144]:
df["origin"]

0          JAPAN
1          JAPAN
2          JAPAN
3          JAPAN
4          JAPAN
          ...
13268    GERMANY
13269        USA
13270      JAPAN
13271      JAPAN
13272      ITALY
Name: origin, Length: 13273, dtype: object

In [145]:
df["origin"].isnull().sum()

np.int64(979)

In [146]:
df["origin"].unique()

array(['JAPAN', 'THAILAND', 'ITALY', 'TAIWAN', 'USA', nan, 'INDONESIA',
       'CANADA', 'INDIA', 'UAE', 'AFGHANISTAN', 'AUSTRALIA',
       'SOUTH KOREA', 'ROMANIA', 'UK', 'MOROCCO', 'MEXICO', 'GERMANY',
       'SPAIN', 'CHINA', 'SLOVAKIA', 'PAPUA NEW GUINEA', 'JAMAICA',
       'YEMEN', 'OMAN', 'NETHERLANDS', 'TURKEY', 'SWEDEN', 'CAMEROON',
       'GREECE', 'BAHRAIN', 'COLOMBIA', 'JORDAN', 'BRAZIL', 'PAKISTAN',
       'FRANCE'], dtype=object)

## weightInKg

In [147]:
df["weightInKg"]

0         1100.0
1         1100.0
2         1890.0
3         1400.0
4         1600.0
          ...
13268    14600.0
13269     1402.0
13270     5000.0
13271        NaN
13272    12000.0
Name: weightInKg, Length: 13273, dtype: float64

In [148]:
df["weightInKg"].isnull().sum()

np.int64(3004)

In [149]:
df[df["weightInKg"] > 10000]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_class,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against
170,NCP1507010684,2014,TOYOTA,YARIS,SE,SEDAN,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
485,ZE15048989,2006,TOYOTA,AVALON,TOP,SEDAN,GCC,6.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
532,ZRE1424412049,2013,TOYOTA,COROLLA,XLI,SEDAN,GCC,4.0,SILVER,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
796,ZGE216051656,2013,TOYOTA,RAV4,EX,SUV,GCC,4.0,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
2251,ANE120013199,2003,TOYOTA,WISH,SE,SUV,GCC,4.0,BLUE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
2668,ACV405014469,2008,TOYOTA,CAMRY,XLI,SEDAN,GCC,4.0,SILVER,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
5586,NV18061843,2005,TOYOTA,CAMRY,GLI,SEDAN,GCC,4.0,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
9105,C11EHW000401,2007,NISSAN,TIIDA,S,HATCHBACK,GCC,4.0,YELLOW,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
9889,00K20221588,1979,MITSUBISHI,FUSO,STD,HEAVY EQUIPMENT,GCC,4.0,BLUE,JAPAN,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
10797,RH031002131,2020,HONDA,CBR650R,NaN,MOTORCYCLE,GCC,NaN,BLACK,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
10835,G4NBEU827587,2015,HYUNDAI,ELANTRA,GL,SEDAN,GCC,4.0,WHITE,SOUTH KOREA,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
10854,794089,2003,MERCEDES-BENZ,NaN,STD,TRUCK,GCC,4.0,WHITE,SWEDEN,...,needs_manual_review,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
10855,794513,2003,MERCEDES-BENZ,NaN,STD,TRUCK,GCC,4.0,WHITE,GERMANY,...,needs_manual_review,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
11285,EZC21S023530,2008,SUZUKI,SWIFT,GA,HATCHBACK,GCC,4.0,GREY,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
11445,EZC21S006456,2006,SUZUKI,SWIFT,ST,HATCHBACK,GCC,4.0,WHITE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
11835,EZC21S003835,2006,SUZUKI,SWIFT,GA,HATCHBACK,GCC,4.0,BLUE,JAPAN,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13209,BFH106043,2006,ASHOK LEYLAND,ASHOK LEYLAND,STD,BUS,GCC,6.0,WHITE,INDIA,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13268,4520016452,1978,NaN,CRANE/MAN26280,CTTO CRANE/MAN26280,VAN,GCC,6.0,WHITE,GERMANY,...,valid_short_chassis,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN
13272,MI76734700,2015,MANITOU,MTX1740SLT,GL,HEAVY EQUIPMENT,GCC,4.0,GREY,ITALY,...,valid_short_chassis,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
df["bodyType"].unique()

array(['SEDAN', 'SUV', 'PICKUP DOUBLE CAB', 'PICKUP SINGLE CAB',
       'STATION WAGON', 'HATCHBACK', 'PICKUP', 'MPV', 'COUPE', 'VAN',
       'PANEL VAN', 'TANKER', 'CONVERTIBLE', 'BUS', 'FORKLIFT', 'TRUCK',
       'SINGLE CABIN LONG CHASSIS', 'HEAVY EQUIPMENT', 'MOTORCYCLE',
       'MINI BUS', nan, 'PICK UP EXT CAB'], dtype=object)

In [153]:
# 1. Sedans / Hatchbacks / Coupes shouldn't exceed ~3,500 kg (or ~7,500 lbs)
passenger_cars = ['SEDAN', 'HATCHBACK', 'COUPE', 'CONVERTIBLE', 'STATION WAGON']
df.loc[df['bodyType'].isin(passenger_cars) & (df['weightInKg'] > 4000), 'weightInKg'] = np.nan

# 2. SUVs / MPVs / Vans shouldn't exceed ~4,500 kg (or ~10,000 lbs)
large_personal = ['SUV', 'MPV', 'VAN', 'PANEL VAN', 'PICKUP', 'PICKUP DOUBLE CAB', 'PICKUP SINGLE CAB', 'PICK UP EXT CAB']
df.loc[df['bodyType'].isin(large_personal) & (df['weightInKg'] > 5000), 'weightInKg'] = np.nan

# 3. Heavy commercial vehicles can easily be over 10k. Set a realistic roof for them (e.g., 40,000 kg empty)
heavy_vehicles = ['BUS', 'MINI BUS', 'TRUCK', 'TANKER', 'HEAVY EQUIPMENT', 'FORKLIFT', 'SINGLE CABIN LONG CHASSIS']
df.loc[df['bodyType'].isin(heavy_vehicles) & (df['weightInKg'] > 45000), 'weightInKg'] = np.nan

In [154]:
df["weightInKg"].isnull().sum()

np.int64(3026)

In [157]:
df[df["weightInKg"] < 200]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against,weight
92,SDY0E2601433,1999,TOYOTA,HILUX,DLX,PICKUP DOUBLE CAB,GCC,4.0,BLUE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,NV18076703,2005,TOYOTA,CAMRY,XLI,SEDAN,GCC,4.0,BLACK,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,ANE120030348,2005,TOYOTA,RAV4,TOP,SUV,GCC,4.0,GOLDEN,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,ZRE1725581822,2015,TOYOTA,COROLLA,GLI,SEDAN,GCC,4.0,RED,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
394,NCP919064752,2010,TOYOTA,COROLLA,GLI TOP,SEDAN,GCC,4.0,GREY,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13181,ZX636J005781,2024,KAWASAKI,NINJA ZX-6R,NaN,MOTORCYCLE,GCC,NaN,BLUE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13183,ZXT00W011017,2017,KAWASAKI,NINJA 650,NaN,MOTORCYCLE,GCC,NaN,SILVER,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13190,ER650HA52947,2022,KAWASAKI,NINJA,NaN,MOTORCYCLE,GCC,NaN,GREEN,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13191,VBB2T160023,1963,VESPA,PIAGGIO,NaN,MOTORCYCLE,GCC,NaN,WHITE,ITALY,...,pre_vin,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13244,RN693002371,2023,NaN,MT-09,NaN,MOTORCYCLE,NaN,NaN,BLACK,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [158]:
# 1. Sedans / Hatchbacks / Coupes (Fixes entries less than 600 kg)
passenger_cars = ['SEDAN', 'HATCHBACK', 'COUPE', 'CONVERTIBLE', 'STATION WAGON']
df.loc[df['bodyType'].isin(passenger_cars) & ((df['weightInKg'] > 4000) | (df['weightInKg'] < 600)), 'weightInKg'] = np.nan

# 2. SUVs / MPVs / Vans / Pickups (Fixes entries less than 1,000 kg)
large_personal = ['SUV', 'MPV', 'VAN', 'PANEL VAN', 'PICKUP', 'PICKUP DOUBLE CAB', 'PICKUP SINGLE CAB', 'PICK UP EXT CAB']
df.loc[df['bodyType'].isin(large_personal) & ((df['weightInKg'] > 5000) | (df['weightInKg'] < 1000)), 'weightInKg'] = np.nan

# 3. Heavy Commercial Vehicles (Fixes entries less than 2,500 kg)
heavy_vehicles = ['BUS', 'MINI BUS', 'TRUCK', 'TANKER', 'HEAVY EQUIPMENT', 'FORKLIFT', 'SINGLE CABIN LONG CHASSIS']
df.loc[df['bodyType'].isin(heavy_vehicles) & ((df['weightInKg'] > 45000) | (df['weightInKg'] < 2500)), 'weightInKg'] = np.nan

# 4. Fill all these new NaN values with the proper median for each body type
df['weightInKg'] = df.groupby('bodyType')['weightInKg'].transform(lambda x: x.fillna(x.median()))

In [163]:
df[df["weightInKg"] < 100]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against,weight
10407,SD101100264,2024,HONDA,AFRICA TWIN,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10431,SC471510004,2009,HONDA,GOLD WING,NaN,MOTORCYCLE,GCC,NaN,BLACK,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10480,JB021011258,2020,HONDA,NaN,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10527,JHC905710870,2005,HONDA,C90,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10569,JB051003289,2024,HONDA,MONKEY,NaN,MOTORCYCLE,GCC,NaN,BLACK,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10666,JB021007686,2022,HONDA,MONKEY,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10697,JB031008214,2022,HONDA,NaN,NaN,MOTORCYCLE,GCC,NaN,SILVER,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10728,MF081014560,2014,HONDA,FORZA,NaN,MOTORCYCLE,GCC,NaN,GREY,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10811,JF311011610,2017,HONDA,NaN,NaN,MOTORCYCLE,GCC,NaN,SILVER,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11134,CJ46A113400,2016,SUZUKI,NaN,NaN,MOTORCYCLE,GCC,NaN,BLACK,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11347,GX72B101045,2015,SUZUKI,GSX-R1300,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11551,CP52A102086,2020,SUZUKI,SKY WAVE,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13164,ZXT40A010486,2020,BAJAJ,NINJA,NaN,MOTORCYCLE,GCC,NaN,WHITE,CHINA,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [164]:
# Add MOTORCYCLE to your cleaning pipeline
# Min threshold: 50 kg (accounts for small electric/petrol mopeds)
# Max threshold: 500 kg (accounts for heavy cruisers/touring bikes; anything above is an error)
df.loc[(df['bodyType'] == 'MOTORCYCLE') & ((df['weightInKg'] > 500) | (df['weightInKg'] < 50)), 'weightInKg'] = np.nan

# Re-run your group median fill to cleanly fix the newly flagged motorcycle NaNs
df['weightInKg'] = df.groupby('bodyType')['weightInKg'].transform(lambda x: x.fillna(x.median()))

In [166]:
df[df["weightInKg"] < 100]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,...,chassis_era_flag,chassis_wmi_flag,vin_class,vin_confidence,vin_score,vin_wmi_make,vin_decoded_years,vin_evidence_for,vin_evidence_against,weight
10407,SD101100264,2024,HONDA,AFRICA TWIN,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10431,SC471510004,2009,HONDA,GOLD WING,NaN,MOTORCYCLE,GCC,NaN,BLACK,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10480,JB021011258,2020,HONDA,NaN,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10527,JHC905710870,2005,HONDA,C90,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10569,JB051003289,2024,HONDA,MONKEY,NaN,MOTORCYCLE,GCC,NaN,BLACK,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10666,JB021007686,2022,HONDA,MONKEY,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10697,JB031008214,2022,HONDA,NaN,NaN,MOTORCYCLE,GCC,NaN,SILVER,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10728,MF081014560,2014,HONDA,FORZA,NaN,MOTORCYCLE,GCC,NaN,GREY,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10811,JF311011610,2017,HONDA,NaN,NaN,MOTORCYCLE,GCC,NaN,SILVER,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11134,CJ46A113400,2016,SUZUKI,NaN,NaN,MOTORCYCLE,GCC,NaN,BLACK,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11347,GX72B101045,2015,SUZUKI,GSX-R1300,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11551,CP52A102086,2020,SUZUKI,SKY WAVE,NaN,MOTORCYCLE,GCC,NaN,WHITE,JAPAN,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13164,ZXT40A010486,2020,BAJAJ,NINJA,NaN,MOTORCYCLE,GCC,NaN,WHITE,CHINA,...,chassis_suspect_modern,NaN,NOT_CHECKED,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [167]:
df.to_csv("../Data/ShortVIN_cleaned.csv", index=False)