In [35]:
import pandas as pd
import datetime
import numpy as np

In [36]:
df = pd.read_csv("data/drivearabia_toyota_prices_newest_final.csv")

In [37]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at
0,toyota-86,2014,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z
1,toyota-86,2014,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z
2,toyota-86,2014,TRD,149000,150000,149500,"AED 149,000 - 150,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z
3,toyota-86,2015,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z
4,toyota-86,2015,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z
...,...,...,...,...,...,...,...,...,...,...
884,toyota-yaris-sedan,2023,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:41:58Z
885,toyota-yaris-sedan,2025,1.5L I4 E FWD,63900,64000,63950,"AED 63,900 - 64,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z
886,toyota-yaris-sedan,2025,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z
887,toyota-yaris-sedan,2026,E,64900,65000,64950,"AED 64,900 - 65,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z
888,toyota-yaris-sedan,2026,G,74900,75000,74950,"AED 74,900 - 75,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z

In [38]:
current_year = datetime.datetime.now().year
df["car_age"] = current_year - df["year"]

In [39]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at,car_age
0,toyota-86,2014,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12
1,toyota-86,2014,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12
2,toyota-86,2014,TRD,149000,150000,149500,"AED 149,000 - 150,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12
3,toyota-86,2015,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11
4,toyota-86,2015,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11
...,...,...,...,...,...,...,...,...,...,...,...
884,toyota-yaris-sedan,2023,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:41:58Z,3
885,toyota-yaris-sedan,2025,1.5L I4 E FWD,63900,64000,63950,"AED 63,900 - 64,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1
886,toyota-yaris-sedan,2025,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1
887,toyota-yaris-sedan,2026,E,64900,65000,64950,"AED 64,900 - 65,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0
888,toyota-yaris-sedan,2026,G,74900,75000,74950,"AED 74,900 - 75,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0

In [40]:
TOYOTA_DEPRECIATION_RATES = {

    # Economy Cars
    "toyota-yaris": 0.09,
    "toyota-yaris-sedan": 0.09,
    "toyota-raize": 0.09,
    "toyota-avanza": 0.10,
    "toyota-rush": 0.09,
    "toyota-veloz": 0.09,
    "toyota-liteace": 0.10,

    # Compact Sedans / Hatchbacks
    "toyota-corolla": 0.07,
    "toyota-corolla-cross": 0.07,
    "toyota-c-hr": 0.08,
    "toyota-urban-cruiser": 0.08,

    # Mid-Size Sedans
    "toyota-camry": 0.08,
    "toyota-aurion": 0.09,
    "toyota-avalon": 0.08,
    "toyota-crown": 0.07,

    # MPV / Van
    "toyota-innova": 0.07,
    "toyota-granvia": 0.08,
    "toyota-previa": 0.08,
    "toyota-hiace": 0.06,

    # SUVs
    "toyota-rav-4": 0.06,
    "toyota-fortuner": 0.05,
    "toyota-highlander": 0.06,
    "toyota-sequoia": 0.06,

    # Pickup Trucks
    "toyota-hilux": 0.05,
    "toyota-land-cruiser-pickup": 0.04,

    # Land Cruiser Family
    "toyota-land-cruiser": 0.04,
    "toyota-land-cruiser-gr-sport": 0.04,
    "toyota-land-cruiser-70": 0.03,
    "toyota-land-cruiser-prado": 0.05,
    "toyota-land-cruiser-prado-swb": 0.05,

    # Off-Road
    "toyota-fj-cruiser": 0.05,

    # Sports Cars
    "toyota-86": 0.08,
    "toyota-gr86": 0.08,
    "toyota-supra": 0.07,
    "toyota-gr-corolla": 0.07,
    "toyota-gr-yaris": 0.06,
}

In [41]:
df["depreciation_rate"] = (
    df["model_slug"]
    .map(TOYOTA_DEPRECIATION_RATES)
    .fillna(0.08)
)

df["estimated_value"] = (
    df["price_avg_aed"]
    * ((1 - df["depreciation_rate"]) ** df["car_age"])
)

In [42]:
def depreciation_factor(age, rate):
    if age <= 3:
        return (1 - rate * 1.3) ** age
    else:
        first_3 = (1 - rate * 1.3) ** 3
        remaining = (1 - rate) ** (age - 3)
        return first_3 * remaining

In [43]:
df["estimated_value"] = df.apply(
    lambda x: x["price_avg_aed"] *
    depreciation_factor(
        x["car_age"],
        x["depreciation_rate"]
    ),
    axis=1
)

In [44]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at,car_age,depreciation_rate,estimated_value
0,toyota-86,2014,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,33929.695594
1,toyota-86,2014,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,40722.427445
2,toyota-86,2014,TRD,149000,150000,149500,"AED 149,000 - 150,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,50775.670584
3,toyota-86,2015,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,0.08,36880.103907
4,toyota-86,2015,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,0.08,44263.508093
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,toyota-yaris-sedan,2023,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:41:58Z,3,0.09,50912.015369
885,toyota-yaris-sedan,2025,1.5L I4 E FWD,63900,64000,63950,"AED 63,900 - 64,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,0.09,56467.850000
886,toyota-yaris-sedan,2025,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,0.09,65297.850000
887,toyota-yaris-sedan,2026,E,64900,65000,64950,"AED 64,900 - 65,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,0.09,64950.000000
888,toyota-yaris-sedan,2026,G,74900,75000,74950,"AED 74,900 - 75,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,0.09,74950.000000

In [45]:
df.isnull().sum()

model_slug           0
year                 0
trim_name            0
price_min_aed        0
price_max_aed        0
price_avg_aed        0
price_raw            0
currency             0
url                  0
scraped_at           0
car_age              0
depreciation_rate    0
estimated_value      0
dtype: int64

In [46]:
CURRENT_YEAR = 2026

DEPR_RATES = {
    'toyota-86': 0.105,
    'toyota-aurion': 0.10,
    'toyota-avalon': 0.10,
    'toyota-avanza': 0.09,
    'toyota-c-hr': 0.09,
    'toyota-camry': 0.105,
    'toyota-corolla': 0.10,
    'toyota-corolla-cross': 0.115,
    'toyota-crown': 0.13,
    'toyota-fj-cruiser': 0.075,
    'toyota-fortuner': 0.09,
    'toyota-gr-corolla': 0.10,
    'toyota-gr-yaris': 0.095,
    'toyota-gr86': 0.13,
    'toyota-granvia': 0.09,
    'toyota-hiace': 0.095,
    'toyota-highlander': 0.105,
    'toyota-hilux': 0.075,
    'toyota-innova': 0.10,
    'toyota-land-cruiser': 0.10,
    'toyota-land-cruiser-70': 0.08,
    'toyota-land-cruiser-gr-sport': 0.095,
    'toyota-land-cruiser-pickup': 0.09,
    'toyota-land-cruiser-prado': 0.10,
    'toyota-land-cruiser-prado-swb': 0.10,
    'toyota-liteace': 0.095,
    'toyota-previa': 0.125,
    'toyota-raize': 0.115,
    'toyota-rav-4': 0.105,
    'toyota-rush': 0.10,
    'toyota-sequoia': 0.105,
    'toyota-supra': 0.08,
    'toyota-urban-cruiser': 0.125,
    'toyota-veloz': 0.115,
    'toyota-yaris': 0.095,
    'toyota-yaris-sedan': 0.095,
}

df['car_age'] = CURRENT_YEAR - df['year']

def calc_depr(row):
    slug = row['model_slug']
    if slug not in DEPR_RATES:
        return np.nan
    rate = DEPR_RATES[slug]
    age = row['car_age']
    if age <= 0:
        return round(row['price_avg_aed'], 0)
    return round(row['price_avg_aed'] * ((1 - rate) ** age), 0)

df['depreciated_value'] = df.apply(calc_depr, axis=1)

In [47]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at,car_age,depreciation_rate,estimated_value,depreciated_value
0,toyota-86,2014,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,33929.695594,26390.0
1,toyota-86,2014,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,40722.427445,31673.0
2,toyota-86,2014,TRD,149000,150000,149500,"AED 149,000 - 150,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,50775.670584,39493.0
3,toyota-86,2015,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,0.08,36880.103907,29486.0
4,toyota-86,2015,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,0.08,44263.508093,35389.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,toyota-yaris-sedan,2023,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:41:58Z,3,0.09,50912.015369,54813.0
885,toyota-yaris-sedan,2025,1.5L I4 E FWD,63900,64000,63950,"AED 63,900 - 64,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,0.09,56467.850000,57875.0
886,toyota-yaris-sedan,2025,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,0.09,65297.850000,66925.0
887,toyota-yaris-sedan,2026,E,64900,65000,64950,"AED 64,900 - 65,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,0.09,64950.000000,64950.0
888,toyota-yaris-sedan,2026,G,74900,75000,74950,"AED 74,900 - 75,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,0.09,74950.000000,74950.0

In [48]:
df["depreciated_value"]

0      26390.0
1      31673.0
2      39493.0
3      29486.0
4      35389.0
        ...
884    54813.0
885    57875.0
886    66925.0
887    64950.0
888    74950.0
Name: depreciated_value, Length: 889, dtype: float64

In [49]:
df["depreciated_value"] = df["depreciated_value"].astype("int64")

In [50]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at,car_age,depreciation_rate,estimated_value,depreciated_value
0,toyota-86,2014,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,33929.695594,26390
1,toyota-86,2014,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,40722.427445,31673
2,toyota-86,2014,TRD,149000,150000,149500,"AED 149,000 - 150,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,0.08,50775.670584,39493
3,toyota-86,2015,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,0.08,36880.103907,29486
4,toyota-86,2015,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,0.08,44263.508093,35389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,toyota-yaris-sedan,2023,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:41:58Z,3,0.09,50912.015369,54813
885,toyota-yaris-sedan,2025,1.5L I4 E FWD,63900,64000,63950,"AED 63,900 - 64,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,0.09,56467.850000,57875
886,toyota-yaris-sedan,2025,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,0.09,65297.850000,66925
887,toyota-yaris-sedan,2026,E,64900,65000,64950,"AED 64,900 - 65,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,0.09,64950.000000,64950
888,toyota-yaris-sedan,2026,G,74900,75000,74950,"AED 74,900 - 75,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,0.09,74950.000000,74950

In [ ]:
df.to_csv('data/drivearabia_toyota_prices_with_depreciation.csv', index=False)