In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/drivearabia_nissan_prices.csv')

In [3]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at
0,nissan-370z,2013,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:54Z
1,nissan-370z,2013,manual,144000,145000,144500,"AED 144,000 - 145,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:54Z
2,nissan-370z,2014,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:56Z
3,nissan-370z,2014,manual,144000,145000,144500,"AED 144,000 - 145,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:56Z
4,nissan-370z,2015,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:58Z
...,...,...,...,...,...,...,...,...,...,...
760,nissan-z,2024,3.0T I6 auto RWD,205000,206000,205500,"AED 205,000 - 206,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:22Z
761,nissan-z,2025,3.0T I6 manual RWD,215900,216000,215950,"AED 215,900 - 216,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:24Z
762,nissan-z,2025,3.0T I6 auto RWD,221900,222000,221950,"AED 221,900 - 222,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:24Z
763,nissan-z,2026,manual,215900,216000,215950,"AED 215,900 - 216,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:26Z
764,nissan-z,2026,auto,221900,222000,221950,"AED 221,900 - 222,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:26Z

In [4]:
CURRENT_YEAR = 2026

DEPR_RATES = {
    'nissan-patrol-safari': 0.10,
    'nissan-xterra': 0.11,
    'nissan-patrol-pickup': 0.11,
    'nissan-navara': 0.11,
    'nissan-urvan': 0.11,
    'nissan-gt-r': 0.13,
    'nissan-pickup': 0.12,
    'nissan-patrol': 0.13,
    'nissan-370z': 0.13,
    'nissan-tiida': 0.13,
    'nissan-x-trail': 0.13,
    'nissan-sunny': 0.14,
    'nissan-juke': 0.14,
    'nissan-kicks': 0.14,
    'nissan-sentra': 0.15,
    'nissan-altima': 0.15,
    'nissan-altima-coupe': 0.15,
    'nissan-pathfinder': 0.15,
    'nissan-maxima': 0.15,
    'nissan-z': 0.15,
    'nissan-patrol-pro-4x': 0.13,
    'nissan-patrol-nismo': 0.13,
    'nissan-magnite': 0.14,
}

df['car_age'] = CURRENT_YEAR - df['year']

def calc_depr(row):
    slug = row['model_slug']
    if slug not in DEPR_RATES:
        return np.nan
    rate = DEPR_RATES[slug]
    age = row['car_age']
    if age <= 0:
        return round(row['price_avg_aed'], 0)
    return round(row['price_avg_aed'] * ((1 - rate) ** age), 0)

df['depreciated_value'] = df.apply(calc_depr, axis=1)

In [5]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at,car_age,depreciated_value
0,nissan-370z,2013,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:54Z,13,23557.0
1,nissan-370z,2013,manual,144000,145000,144500,"AED 144,000 - 145,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:54Z,13,23638.0
2,nissan-370z,2014,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:56Z,12,27077.0
3,nissan-370z,2014,manual,144000,145000,144500,"AED 144,000 - 145,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:56Z,12,27171.0
4,nissan-370z,2015,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:58Z,11,31122.0
...,...,...,...,...,...,...,...,...,...,...,...,...
760,nissan-z,2024,3.0T I6 auto RWD,205000,206000,205500,"AED 205,000 - 206,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:22Z,2,148474.0
761,nissan-z,2025,3.0T I6 manual RWD,215900,216000,215950,"AED 215,900 - 216,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:24Z,1,183558.0
762,nissan-z,2025,3.0T I6 auto RWD,221900,222000,221950,"AED 221,900 - 222,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:24Z,1,188658.0
763,nissan-z,2026,manual,215900,216000,215950,"AED 215,900 - 216,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:26Z,0,215950.0
764,nissan-z,2026,auto,221900,222000,221950,"AED 221,900 - 222,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:26Z,0,221950.0

In [6]:
df.isnull().sum()

model_slug           0
year                 0
trim_name            0
price_min_aed        0
price_max_aed        0
price_avg_aed        0
price_raw            0
currency             0
url                  0
scraped_at           0
car_age              0
depreciated_value    0
dtype: int64

In [7]:
df["depreciated_value"] = df["depreciated_value"].astype("int64")

In [8]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at,car_age,depreciated_value
0,nissan-370z,2013,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:54Z,13,23557
1,nissan-370z,2013,manual,144000,145000,144500,"AED 144,000 - 145,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:54Z,13,23638
2,nissan-370z,2014,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:56Z,12,27077
3,nissan-370z,2014,manual,144000,145000,144500,"AED 144,000 - 145,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:56Z,12,27171
4,nissan-370z,2015,auto,139000,149000,144000,"AED 139,000 - 149,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:12:58Z,11,31122
...,...,...,...,...,...,...,...,...,...,...,...,...
760,nissan-z,2024,3.0T I6 auto RWD,205000,206000,205500,"AED 205,000 - 206,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:22Z,2,148474
761,nissan-z,2025,3.0T I6 manual RWD,215900,216000,215950,"AED 215,900 - 216,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:24Z,1,183558
762,nissan-z,2025,3.0T I6 auto RWD,221900,222000,221950,"AED 221,900 - 222,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:24Z,1,188658
763,nissan-z,2026,manual,215900,216000,215950,"AED 215,900 - 216,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:26Z,0,215950
764,nissan-z,2026,auto,221900,222000,221950,"AED 221,900 - 222,000",AED,https://www.drivearabia.com/carprices/uae/niss...,2026-06-12T10:36:26Z,0,221950

In [9]:
df.to_csv('data/drivearabia_nissan_prices_with_depreciation.csv', index=False)