## 1

In [1]:
import pandas as pd
import datetime
import numpy as np

In [2]:
df = pd.read_csv("data/drivearabia_toyota_prices_newest_final.csv")

In [3]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at
0,toyota-86,2014,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z
1,toyota-86,2014,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z
2,toyota-86,2014,TRD,149000,150000,149500,"AED 149,000 - 150,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z
3,toyota-86,2015,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z
4,toyota-86,2015,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z
...,...,...,...,...,...,...,...,...,...,...
884,toyota-yaris-sedan,2023,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:41:58Z
885,toyota-yaris-sedan,2025,1.5L I4 E FWD,63900,64000,63950,"AED 63,900 - 64,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z
886,toyota-yaris-sedan,2025,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z
887,toyota-yaris-sedan,2026,E,64900,65000,64950,"AED 64,900 - 65,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z
888,toyota-yaris-sedan,2026,G,74900,75000,74950,"AED 74,900 - 75,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z

In [4]:
df.isnull().sum()

model_slug       0
year             0
trim_name        0
price_min_aed    0
price_max_aed    0
price_avg_aed    0
price_raw        0
currency         0
url              0
scraped_at       0
dtype: int64

In [5]:
CURRENT_YEAR = 2026

DEPR_RATES = {
    'toyota-86': 0.12,
    'toyota-aurion': 0.12,
    'toyota-avalon': 0.12,
    'toyota-avanza': 0.11,
    'toyota-c-hr': 0.11,
    'toyota-camry': 0.12,
    'toyota-corolla': 0.12,
    'toyota-corolla-cross': 0.13,
    'toyota-crown': 0.15,
    'toyota-fj-cruiser': 0.09,
    'toyota-fortuner': 0.11,
    'toyota-gr-corolla': 0.12,
    'toyota-gr-yaris': 0.11,
    'toyota-gr86': 0.15,
    'toyota-granvia': 0.11,
    'toyota-hiace': 0.11,
    'toyota-highlander': 0.12,
    'toyota-hilux': 0.09,
    'toyota-innova': 0.12,
    'toyota-land-cruiser': 0.12,
    'toyota-land-cruiser-70': 0.10,
    'toyota-land-cruiser-gr-sport': 0.11,
    'toyota-land-cruiser-pickup': 0.11,
    'toyota-land-cruiser-prado': 0.12,
    'toyota-land-cruiser-prado-swb': 0.12,
    'toyota-liteace': 0.11,
    'toyota-previa': 0.14,
    'toyota-raize': 0.13,
    'toyota-rav-4': 0.12,
    'toyota-rush': 0.12,
    'toyota-sequoia': 0.12,
    'toyota-supra': 0.10,
    'toyota-urban-cruiser': 0.14,
    'toyota-veloz': 0.13,
    'toyota-yaris': 0.11,
    'toyota-yaris-sedan': 0.11,
}

df['car_age'] = CURRENT_YEAR - df['year']

def calc_depr(row):
    slug = row['model_slug']
    if slug not in DEPR_RATES:
        return np.nan
    rate = DEPR_RATES[slug]
    age = row['car_age']
    if age <= 0:
        return round(row['price_avg_aed'], 0)
    return round(row['price_avg_aed'] * ((1 - rate) ** age), 0)

df['depreciated_value'] = df.apply(calc_depr, axis=1)

In [6]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at,car_age,depreciated_value
0,toyota-86,2014,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,21546.0
1,toyota-86,2014,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,25859.0
2,toyota-86,2014,TRD,149000,150000,149500,"AED 149,000 - 150,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,32243.0
3,toyota-86,2015,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,24484.0
4,toyota-86,2015,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,29385.0
...,...,...,...,...,...,...,...,...,...,...,...,...
884,toyota-yaris-sedan,2023,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:41:58Z,3,52132.0
885,toyota-yaris-sedan,2025,1.5L I4 E FWD,63900,64000,63950,"AED 63,900 - 64,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,56916.0
886,toyota-yaris-sedan,2025,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,65816.0
887,toyota-yaris-sedan,2026,E,64900,65000,64950,"AED 64,900 - 65,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,64950.0
888,toyota-yaris-sedan,2026,G,74900,75000,74950,"AED 74,900 - 75,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,74950.0

In [7]:
df["depreciated_value"]

0      21546.0
1      25859.0
2      32243.0
3      24484.0
4      29385.0
        ...
884    52132.0
885    56916.0
886    65816.0
887    64950.0
888    74950.0
Name: depreciated_value, Length: 889, dtype: float64

In [8]:
df["depreciated_value"] = df["depreciated_value"].astype("int64")

In [9]:
df

,model_slug,year,trim_name,price_min_aed,price_max_aed,price_avg_aed,price_raw,currency,url,scraped_at,car_age,depreciated_value
0,toyota-86,2014,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,21546
1,toyota-86,2014,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,25859
2,toyota-86,2014,TRD,149000,150000,149500,"AED 149,000 - 150,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:36Z,12,32243
3,toyota-86,2015,GT/GTX MT,94900,104900,99900,"AED 94,900 - 104,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,24484
4,toyota-86,2015,VT/VTX AT,114900,124900,119900,"AED 114,900 - 124,900",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:13:38Z,11,29385
...,...,...,...,...,...,...,...,...,...,...,...,...
884,toyota-yaris-sedan,2023,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:41:58Z,3,52132
885,toyota-yaris-sedan,2025,1.5L I4 E FWD,63900,64000,63950,"AED 63,900 - 64,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,56916
886,toyota-yaris-sedan,2025,1.5 I4 G FWD,73900,74000,73950,"AED 73,900 - 74,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:01Z,1,65816
887,toyota-yaris-sedan,2026,E,64900,65000,64950,"AED 64,900 - 65,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,64950
888,toyota-yaris-sedan,2026,G,74900,75000,74950,"AED 74,900 - 75,000",AED,https://www.drivearabia.com/carprices/uae/toyo...,2026-06-12T08:42:03Z,0,74950

In [10]:
df.to_csv('data/drivearabia_toyota_prices_with_depreciation.csv', index=False)

## 2

### TOYOTA

In [13]:
import pandas as pd
import numpy as np

# ============================================================
# CONFIG
# ============================================================

CURRENT_YEAR = 2026

# Load Toyota dataset
df = pd.read_csv("data/drivearabia_toyota_prices_newest_final.csv")

# Load depreciation rates dataset
dep_df = pd.read_csv("data/annual_dep_rate.csv")

# ============================================================
# CLEAN DATA
# ============================================================

# Clean depreciation file
dep_df["make"] = dep_df["make"].astype(str).str.strip().str.upper()
dep_df["model"] = dep_df["model"].astype(str).str.strip().str.upper()

# ============================================================
# MODEL MAPPING
# ============================================================

MODEL_MAPPING = {
    "toyota-86": "86",
    "toyota-aurion": "AURION",
    "toyota-avalon": "AVALON",
    "toyota-avanza": "AVANZA",
    "toyota-c-hr": "C-HR",
    "toyota-camry": "CAMRY",
    "toyota-corolla": "COROLLA",
    "toyota-corolla-cross": "COROLLA CROSS",
    "toyota-crown": "CROWN",
    "toyota-fj-cruiser": "FJ CRUISER",
    "toyota-fortuner": "FORTUNER",
    "toyota-gr-corolla": "GR COROLLA",
    "toyota-gr-yaris": "GR YARIS",
    "toyota-gr86": "GR86",
    "toyota-granvia": "GRANVIA",
    "toyota-hiace": "HIACE",
    "toyota-highlander": "HIGHLANDER",
    "toyota-hilux": "HILUX",
    "toyota-innova": "INNOVA",
    "toyota-land-cruiser": "LAND CRUISER",
    "toyota-land-cruiser-70": "LAND CRUISER 70",
    "toyota-land-cruiser-gr-sport": "LAND CRUISER GR SPORT",
    "toyota-land-cruiser-pickup": "LAND CRUISER PICKUP",
    "toyota-land-cruiser-prado": "LAND CRUISER PRADO",
    "toyota-land-cruiser-prado-swb": "LAND CRUISER PRADO",
    "toyota-liteace": "LITEACE",
    "toyota-previa": "PREVIA",
    "toyota-raize": "RAIZE",
    "toyota-rav-4": "RAV4",
    "toyota-rush": "RUSH",
    "toyota-sequoia": "SEQUOIA",
    "toyota-supra": "SUPRA",
    "toyota-urban-cruiser": "URBAN CRUISER",
    "toyota-veloz": "VELOZ",
    "toyota-yaris": "YARIS",
    "toyota-yaris-sedan": "YARIS"
}

# ============================================================
# PREPARE TOYOTA DATA
# ============================================================

df["make"] = "TOYOTA"

df["model_name"] = (
    df["model_slug"]
    .map(MODEL_MAPPING)
    .astype(str)
    .str.upper()
)

# ============================================================
# CREATE DEPRECIATION LOOKUP
# ============================================================

dep_lookup = (
    dep_df.groupby(["make", "model"])["annual_dep_rate"]
    .mean()
    .reset_index()
)

# ============================================================
# MERGE DEPRECIATION RATES
# ============================================================

df = df.merge(
    dep_lookup,
    left_on=["make", "model_name"],
    right_on=["make", "model"],
    how="left"
)

# ============================================================
# CALCULATE CAR AGE
# ============================================================

df["car_age"] = CURRENT_YEAR - df["year"]

# Prevent negative ages
df["car_age"] = df["car_age"].clip(lower=0)

# ============================================================
# CALCULATE DEPRECIATED VALUE
# ============================================================

def calc_depreciated_value(row):

    rate = row["annual_dep_rate"]

    if pd.isna(rate):
        return np.nan

    age = row["car_age"]

    if age == 0:
        return round(row["price_avg_aed"], 0)

    depreciated_value = (
        row["price_avg_aed"] *
        ((1 - rate) ** age)
    )

    return round(depreciated_value, 0)

df["depreciated_value"] = df.apply(
    calc_depreciated_value,
    axis=1
)

# ============================================================
# OPTIONAL CHECKS
# ============================================================

print("Total Rows:", len(df))
print("Matched Depreciation Rates:", df["annual_dep_rate"].notna().sum())
print("Missing Depreciation Rates:", df["annual_dep_rate"].isna().sum())

# Show unmatched models
missing_models = (
    df[df["annual_dep_rate"].isna()]
    ["model_slug"]
    .drop_duplicates()
    .tolist()
)

print("\nUnmatched Models:")
print(missing_models)

# ============================================================
# SAVE OUTPUT
# ============================================================

df.to_csv(
    "data/drivearabia_toyota_prices_with_depreciation_aanual_rate.csv",
    index=False
)

print("\nDone!")
print("Saved as: drivearabia_toyota_prices_with_depreciation.csv")

Total Rows: 889
Matched Depreciation Rates: 867
Missing Depreciation Rates: 22

Unmatched Models:
['toyota-gr-corolla', 'toyota-gr-yaris', 'toyota-land-cruiser-gr-sport', 'toyota-land-cruiser-pickup']

Done!
Saved as: drivearabia_toyota_prices_with_depreciation.csv