In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../Data/df_.csv")
data

C:\Users\Admin\AppData\Local\Temp\ipykernel_10508\3550776980.py:1: DtypeWarning: Columns (5,6,22,23,25,26,44,50,53,54,56,57,64,65,67,68,69,72,73,74,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../Data/df_.csv")

,_id,make,model,trim,bodyType,cylinders,year,insureType,chassisNumber,price,...,carImages,tradeLicenseName,autoDataResponse,mortgageDocumentDate,bodyTypeCode,vehicleMileage,ocrRCVerified,ocrVCCVerified,ocrNCCVerified,ocrPassingPaperVerified
0,{'$oid': '68592fc0f32ddc587c27aafb'},TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,thirdparty,JTFHX02P7F0094323,48400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '685935005d8bb5f0ab18a181'},TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,thirdparty,JTFHX02P7F0094323,48400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '685944995d8bb5f0ab18bafc'},TOYOTA,HILUX,DL,Pick Up Double Cab,4.0,2015,comprehensive,JTFHXDGP7F0094373,37800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '68596237e6bdae3db611dab9'},INFINITI,QX50,LUXE STYLE,SUV,4.0,2024,thirdparty,JN1ASNYC3PU200564,142000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '685bb1456ce98addfc08ed19'},BMW,420I,M SPORT PREMIUM,COUPE,4.0,2024,thirdparty,WBA11AP04RCR41747,156500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1674107,{'$oid': '6a193215019e32974c5e3521'},TOYOTA,HILUX,SGLX,Pick Up Double Cab,4.0,2024.0,comprehensive,NaN,86400.0,...,[],NaN,"{'vinDecoding': {'admeid': 34857, 'description...",NaN,NaN,1.0,False,False,False,False
1674108,{'$oid': '6a19321b019e32974c5e355d'},MG,GT,LUXURY,SEDAN,4.0,2022.0,comprehensive,NaN,37810.0,...,[],NaN,NaN,NaN,NaN,1.0,False,False,False,False
1674109,{'$oid': '6a19324e7ecc40bc38f32d6a'},HYUNDAI,TUCSON,GL,SUV,4.0,2020.0,comprehensive,NaN,38880.0,...,[],NaN,"{'vinDecoding': {'admeid': 25968, 'description...",NaN,NaN,1.0,False,False,False,False
1674110,{'$oid': '6a1932558c9b2a52642e77d1'},FORTHING,T5 EVO,EXCLUSIVE,SUV,4.0,2024.0,comprehensive,LMXA14AFXRZ354445,64644.0,...,[],NaN,"{'make': 'FORTHING', 'model': 'T5 EVO', 'year'...",NaN,NaN,NaN,False,False,False,False
1674111,{'$oid': '6a193265019e32974c5e35d2'},NISSAN,PATROL,SUPER SAFARI HT,SUV,6.0,2020.0,comprehensive,NaN,139175.0,...,[],NaN,"{'vinDecoding': {'admeid': 25961, 'description...",NaN,NaN,1.0,False,False,False,False

In [3]:
data = data[["chassisNumber", "make", "model", "trim", "bodyType", "cylinders", "year", "origin","weightInKg", "color", "noOfPassengers", "price"]]

In [4]:
data

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price
0,JTFHX02P7F0094323,TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,Japan,1837.0,white,15.0,48400.0
1,JTFHX02P7F0094323,TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,Japan,1837.0,white,15.0,48400.0
2,JTFHXDGP7F0094373,TOYOTA,HILUX,DL,Pick Up Double Cab,4.0,2015,Japan,1837.0,white,5.0,37800.0
3,JN1ASNYC3PU200564,INFINITI,QX50,LUXE STYLE,SUV,4.0,2024,Mexico,1898.0,grey,5.0,142000.0
4,WBA11AP04RCR41747,BMW,420I,M SPORT PREMIUM,COUPE,4.0,2024,Germany,1525.0,black,4.0,156500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1674107,NaN,TOYOTA,HILUX,SGLX,Pick Up Double Cab,4.0,2024.0,Japan,3000.0,NaN,5.0,86400.0
1674108,NaN,MG,GT,LUXURY,SEDAN,4.0,2022.0,China,3000.0,NaN,5.0,37810.0
1674109,NaN,HYUNDAI,TUCSON,GL,SUV,4.0,2020.0,Korea,3000.0,NaN,5.0,38880.0
1674110,LMXA14AFXRZ354445,FORTHING,T5 EVO,EXCLUSIVE,SUV,4.0,2024.0,CHINA,1715.0,grey,5.0,64644.0
1674111,NaN,NISSAN,PATROL,SUPER SAFARI HT,SUV,6.0,2020.0,Japan,3000.0,NaN,5.0,139175.0

In [5]:


for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

C:\Users\Admin\AppData\Local\Temp\ipykernel_10508\3846488023.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

       chassisNumber      make  model             trim            bodyType  \
0  JTFHX02P7F0094323    TOYOTA  HIACE               DX  MINI BUS HIGH ROOF
1  JTFHX02P7F0094323    TOYOTA  HIACE               DX  MINI BUS HIGH ROOF
2  JTFHXDGP7F0094373    TOYOTA  HILUX               DL  PICK UP DOUBLE CAB
3  JN1ASNYC3PU200564  INFINITI   QX50       LUXE STYLE                 SUV
4  WBA11AP04RCR41747       BMW   420I  M SPORT PREMIUM               COUPE

  cylinders  year   origin  weightInKg  color  noOfPassengers     price
0       4.0  2015    JAPAN      1837.0  WHITE            15.0   48400.0
1       4.0  2015    JAPAN      1837.0  WHITE            15.0   48400.0
2       4.0  2015    JAPAN      1837.0  WHITE             5.0   37800.0
3       4.0  2024   MEXICO      1898.0   GREY             5.0  142000.0
4       4.0  2024  GERMANY      1525.0  BLACK             4.0  156500.0

In [6]:
data

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price
0,JTFHX02P7F0094323,TOYOTA,HIACE,DX,MINI BUS HIGH ROOF,4.0,2015,JAPAN,1837.0,WHITE,15.0,48400.0
1,JTFHX02P7F0094323,TOYOTA,HIACE,DX,MINI BUS HIGH ROOF,4.0,2015,JAPAN,1837.0,WHITE,15.0,48400.0
2,JTFHXDGP7F0094373,TOYOTA,HILUX,DL,PICK UP DOUBLE CAB,4.0,2015,JAPAN,1837.0,WHITE,5.0,37800.0
3,JN1ASNYC3PU200564,INFINITI,QX50,LUXE STYLE,SUV,4.0,2024,MEXICO,1898.0,GREY,5.0,142000.0
4,WBA11AP04RCR41747,BMW,420I,M SPORT PREMIUM,COUPE,4.0,2024,GERMANY,1525.0,BLACK,4.0,156500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1674107,NaN,TOYOTA,HILUX,SGLX,PICK UP DOUBLE CAB,4.0,2024.0,JAPAN,3000.0,NaN,5.0,86400.0
1674108,NaN,MG,GT,LUXURY,SEDAN,4.0,2022.0,CHINA,3000.0,NaN,5.0,37810.0
1674109,NaN,HYUNDAI,TUCSON,GL,SUV,4.0,2020.0,KOREA,3000.0,NaN,5.0,38880.0
1674110,LMXA14AFXRZ354445,FORTHING,T5 EVO,EXCLUSIVE,SUV,4.0,2024.0,CHINA,1715.0,GREY,5.0,64644.0
1674111,NaN,NISSAN,PATROL,SUPER SAFARI HT,SUV,6.0,2020.0,JAPAN,3000.0,NaN,5.0,139175.0

In [7]:
data = data.loc[data['make'].map(data['make'].value_counts()).sort_values(ascending=False).index]

In [8]:
data.drop_duplicates(subset=['chassisNumber'], keep='first', inplace=True)

In [9]:
data["chassis_len"] = data["chassisNumber"].str.len()

is_standard = (data["chassis_len"] == 17) 
data = data[is_standard]
data

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price,chassis_len
0,JTFHX02P7F0094323,TOYOTA,HIACE,DX,MINI BUS HIGH ROOF,4.0,2015,JAPAN,1837.0,WHITE,15.0,48400.0,17.0
2,JTFHXDGP7F0094373,TOYOTA,HILUX,DL,PICK UP DOUBLE CAB,4.0,2015,JAPAN,1837.0,WHITE,5.0,37800.0,17.0
1674082,JTDBR23E743091273,TOYOTA,COROLLA,XLI,SEDAN,4.0,2004.0,JAPAN,1025.0,MAROON,5.0,3500.0,17.0
35,JTDBR23E733057607,TOYOTA,COROLLA,XLI,SEDAN,4.0,2003,JAPAN,1100.0,WHITE,5.0,3000.0,17.0
32,RKLBL9HE3F5218095,TOYOTA,COROLLA,SE+,SEDAN,4.0,2015,TAIWAN,1400.0,SILVER,5.0,24500.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
421129,57XAARFA3H8121499,NaN,SLING SHOT,NaN,MOTORCYCLE,NaN,2017,USA,500.0,ORANGE AND BLACK,2.0,0.0,17.0
857642,7KGTC2C43NR004073,NaN,CARMEL,NaN,MOTORCYCLE,NaN,2022,CHINA,400.0,GRAY AND BLACK,2.0,0.0,17.0
1466591,KMHLN4TB8NU216T80,NaN,NaN,NaN,SEDAN,4.0,NaN,NaN,1.0,NaN,4.0,100000.0,17.0
1518848,TZ220XYF3G5001767,NaN,NaN,NaN,SEDAN,NaN,NaN,NaN,1.0,NaN,4.0,100000.0,17.0
1603160,JTJPD7CX954001287,NaN,NaN,NaN,SEDAN,NaN,NaN,NaN,1.0,NaN,4.0,100000.0,17.0

In [10]:
data.head()

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price,chassis_len
0,JTFHX02P7F0094323,TOYOTA,HIACE,DX,MINI BUS HIGH ROOF,4.0,2015,JAPAN,1837.0,WHITE,15.0,48400.0,17.0
2,JTFHXDGP7F0094373,TOYOTA,HILUX,DL,PICK UP DOUBLE CAB,4.0,2015,JAPAN,1837.0,WHITE,5.0,37800.0,17.0
1674082,JTDBR23E743091273,TOYOTA,COROLLA,XLI,SEDAN,4.0,2004.0,JAPAN,1025.0,MAROON,5.0,3500.0,17.0
35,JTDBR23E733057607,TOYOTA,COROLLA,XLI,SEDAN,4.0,2003,JAPAN,1100.0,WHITE,5.0,3000.0,17.0
32,RKLBL9HE3F5218095,TOYOTA,COROLLA,SE+,SEDAN,4.0,2015,TAIWAN,1400.0,SILVER,5.0,24500.0,17.0

In [11]:
data.to_csv("../Data/df__.csv", index=False)