In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../Data/df_.csv")
data

C:\Users\Admin\AppData\Local\Temp\ipykernel_14568\3550776980.py:1: DtypeWarning: Columns (6,25,26,44,64,65,67,68,69) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../Data/df_.csv")

,_id,make,model,trim,bodyType,cylinders,year,insureType,chassisNumber,price,...,carImages,tradeLicenseName,autoDataResponse,mortgageDocumentDate,bodyTypeCode,vehicleMileage,ocrRCVerified,ocrVCCVerified,ocrNCCVerified,ocrPassingPaperVerified
0,{'$oid': '68592fc0f32ddc587c27aafb'},TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,thirdparty,JTFHX02P7F0094323,48400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '685935005d8bb5f0ab18a181'},TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,thirdparty,JTFHX02P7F0094323,48400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '685944995d8bb5f0ab18bafc'},TOYOTA,HILUX,DL,Pick Up Double Cab,4.0,2015,comprehensive,JTFHXDGP7F0094373,37800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '68596237e6bdae3db611dab9'},INFINITI,QX50,LUXE STYLE,SUV,4.0,2024,thirdparty,JN1ASNYC3PU200564,142000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '685bb1456ce98addfc08ed19'},BMW,420I,M SPORT PREMIUM,COUPE,4.0,2024,thirdparty,WBA11AP04RCR41747,156500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545766,{'$oid': '695b4f43bdc8aedbe0f991eb'},HONDA,ACCORD,LX,SEDAN,4.0,2015,comprehensive,LUCCR2626F3412739,30555.0,...,[],NaN,"{'make': 'HONDA', 'model': 'ACCORD', 'year': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
545767,{'$oid': '695b4f437788260f978b08b8'},TOYOTA,COROLLA,XLI,SEDAN,4.0,2007,thirdparty,JTDBR22E770294249,8300.0,...,[],NaN,"{'make': 'TOYOTA', 'model': 'COROLLA', 'year':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
545768,{'$oid': '695b4f4f895b880bf8233793'},JETOUR,T2,LUX,SUV,4.0,2024,comprehensive,HEVPBECB2RB421697,99655.0,...,[],ABDUL RAOUF ABDUL AZEEZ TR CO L.L.C SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
545769,{'$oid': '695b4f51895b880bf8233850'},PEUGEOT,3008,ACTIVE,SUV,4.0,2020,comprehensive,VF3M45GY4LS010883,32970.0,...,[],NaN,"{'make': 'PEUGEOT', 'model': '3008', 'year': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
545770,{'$oid': '695b4f56895b880bf82338c4'},TOYOTA,FJ CRUISER,GXR,SUV,6.0,2021,comprehensive,JTEBU11F7MK259693,120645.0,...,[],NaN,"{'make': 'TOYOTA', 'model': 'FJ CRUISER', 'yea...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data = data[["chassisNumber", "make", "model", "trim", "bodyType", "cylinders", "year", "origin","weightInKg", "color", "noOfPassengers", "price"]]

In [4]:
data

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price
0,JTFHX02P7F0094323,TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,Japan,1837.0,white,15.0,48400.0
1,JTFHX02P7F0094323,TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,Japan,1837.0,white,15.0,48400.0
2,JTFHXDGP7F0094373,TOYOTA,HILUX,DL,Pick Up Double Cab,4.0,2015,Japan,1837.0,white,5.0,37800.0
3,JN1ASNYC3PU200564,INFINITI,QX50,LUXE STYLE,SUV,4.0,2024,Mexico,1898.0,grey,5.0,142000.0
4,WBA11AP04RCR41747,BMW,420I,M SPORT PREMIUM,COUPE,4.0,2024,Germany,1525.0,black,4.0,156500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
545766,LUCCR2626F3412739,HONDA,ACCORD,LX,SEDAN,4.0,2015,CHINA,1300.0,white,5.0,30555.0
545767,JTDBR22E770294249,TOYOTA,COROLLA,XLI,SEDAN,4.0,2007,JAPAN,1200.0,white,5.0,8300.0
545768,HEVPBECB2RB421697,JETOUR,T2,LUX,SUV,4.0,2024,CHINA,1500.0,black,5.0,99655.0
545769,VF3M45GY4LS010883,PEUGEOT,3008,ACTIVE,SUV,4.0,2020,FRANCE,1900.0,gray and black,5.0,32970.0
545770,JTEBU11F7MK259693,TOYOTA,FJ CRUISER,GXR,SUV,6.0,2021,Japan,NaN,white,5.0,120645.0

In [5]:


for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

C:\Users\Admin\AppData\Local\Temp\ipykernel_14568\3846488023.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

       chassisNumber      make  model             trim            bodyType  \
0  JTFHX02P7F0094323    TOYOTA  HIACE               DX  MINI BUS HIGH ROOF
1  JTFHX02P7F0094323    TOYOTA  HIACE               DX  MINI BUS HIGH ROOF
2  JTFHXDGP7F0094373    TOYOTA  HILUX               DL  PICK UP DOUBLE CAB
3  JN1ASNYC3PU200564  INFINITI   QX50       LUXE STYLE                 SUV
4  WBA11AP04RCR41747       BMW   420I  M SPORT PREMIUM               COUPE

   cylinders  year   origin  weightInKg  color  noOfPassengers     price
0        4.0  2015    JAPAN      1837.0  WHITE            15.0   48400.0
1        4.0  2015    JAPAN      1837.0  WHITE            15.0   48400.0
2        4.0  2015    JAPAN      1837.0  WHITE             5.0   37800.0
3        4.0  2024   MEXICO      1898.0   GREY             5.0  142000.0
4        4.0  2024  GERMANY      1525.0  BLACK             4.0  156500.0

In [6]:
data

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price
0,JTFHX02P7F0094323,TOYOTA,HIACE,DX,MINI BUS HIGH ROOF,4.0,2015,JAPAN,1837.0,WHITE,15.0,48400.0
1,JTFHX02P7F0094323,TOYOTA,HIACE,DX,MINI BUS HIGH ROOF,4.0,2015,JAPAN,1837.0,WHITE,15.0,48400.0
2,JTFHXDGP7F0094373,TOYOTA,HILUX,DL,PICK UP DOUBLE CAB,4.0,2015,JAPAN,1837.0,WHITE,5.0,37800.0
3,JN1ASNYC3PU200564,INFINITI,QX50,LUXE STYLE,SUV,4.0,2024,MEXICO,1898.0,GREY,5.0,142000.0
4,WBA11AP04RCR41747,BMW,420I,M SPORT PREMIUM,COUPE,4.0,2024,GERMANY,1525.0,BLACK,4.0,156500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
545766,LUCCR2626F3412739,HONDA,ACCORD,LX,SEDAN,4.0,2015,CHINA,1300.0,WHITE,5.0,30555.0
545767,JTDBR22E770294249,TOYOTA,COROLLA,XLI,SEDAN,4.0,2007,JAPAN,1200.0,WHITE,5.0,8300.0
545768,HEVPBECB2RB421697,JETOUR,T2,LUX,SUV,4.0,2024,CHINA,1500.0,BLACK,5.0,99655.0
545769,VF3M45GY4LS010883,PEUGEOT,3008,ACTIVE,SUV,4.0,2020,FRANCE,1900.0,GRAY AND BLACK,5.0,32970.0
545770,JTEBU11F7MK259693,TOYOTA,FJ CRUISER,GXR,SUV,6.0,2021,JAPAN,NaN,WHITE,5.0,120645.0

In [7]:
data = data.loc[data['make'].map(data['make'].value_counts()).sort_values(ascending=False).index]

In [8]:
data.drop_duplicates(subset=['chassisNumber'], keep='first', inplace=True)

In [9]:
data["chassis_len"] = data["chassisNumber"].str.len()

is_standard = (data["chassis_len"] == 17) 
data = data[is_standard]
data

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price,chassis_len
545751,MR0FX22G091017515,TOYOTA,HILUX,DLX,PICK UP DOUBLE CAB,4.0,2009,THAILAND,1600.0,WHITE,5.0,21000.0,17.0
545745,JTEGD52M48A004201,TOYOTA,PREVIA,GL,MPV,6.0,2008,JAPAN,1000.0,WHITE,7.0,14000.0,17.0
545744,JTMAUBBJ2S4107332,TOYOTA,LAND CRUISER,GXR2,SUV,6.0,2025,JAPAN,NaN,WHITE,7.0,215900.0,17.0
30,5TDZK23C87S071537,TOYOTA,SIENNA,LE (NON GCC),MPV,6.0,2007,AMERICA,1600.0,WHITE,8.0,13000.0,17.0
29,JTEBU11F39K063774,TOYOTA,FJ CRUISER,BASE,SUV,6.0,2009,JAPAN,2000.0,GREY,5.0,29100.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452581,MALC741C6JM063605,HYUNDAI2120117999,ACCENT,GL,SEDAN,4.0,2018,INDIA,1100.0,BROWN,5.0,22995.0,17.0
267973,LZBTX9C73P1000180,NaN,FX 200,NaN,MOTORCYCLE,NaN,2023,CHINA,150.0,SILVER RED WHITE BLACK,2.0,0.0,17.0
316780,LRW3E7ES9RC964797,NaN,NaN,NaN,SEDAN,NaN,NaN,UAE,1700.0,GRAY AND BLACK,3.0,0.0,17.0
364898,METM85002S3003418,NaN,VESPA VXL 150,NaN,MOTORCYCLE,NaN,2025,INDIA,150.0,RED,2.0,0.0,17.0
421129,57XAARFA3H8121499,NaN,SLING SHOT,NaN,MOTORCYCLE,NaN,2017,USA,500.0,ORANGE AND BLACK,2.0,0.0,17.0

In [10]:
data.head()

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price,chassis_len
545751,MR0FX22G091017515,TOYOTA,HILUX,DLX,PICK UP DOUBLE CAB,4.0,2009,THAILAND,1600.0,WHITE,5.0,21000.0,17.0
545745,JTEGD52M48A004201,TOYOTA,PREVIA,GL,MPV,6.0,2008,JAPAN,1000.0,WHITE,7.0,14000.0,17.0
545744,JTMAUBBJ2S4107332,TOYOTA,LAND CRUISER,GXR2,SUV,6.0,2025,JAPAN,NaN,WHITE,7.0,215900.0,17.0
30,5TDZK23C87S071537,TOYOTA,SIENNA,LE (NON GCC),MPV,6.0,2007,AMERICA,1600.0,WHITE,8.0,13000.0,17.0
29,JTEBU11F39K063774,TOYOTA,FJ CRUISER,BASE,SUV,6.0,2009,JAPAN,2000.0,GREY,5.0,29100.0,17.0

In [11]:
data.to_csv("../Data/df__.csv", index=False)

In [16]:
data = data.loc[data['model'].map(data['model'].value_counts()).sort_values(ascending=False).index]

In [17]:
data

,chassisNumber,make,model,trim,bodyType,cylinders,year,origin,weightInKg,color,noOfPassengers,price,chassis_len
104,4T1BF1FK2GU959033,TOYOTA,CAMRY,SE,SEDAN,4.0,2016,AUSTRALIA,1100.0,PEARL WHITE,5.0,37800.0,17.0
545617,6T1BF4FK1FX532784,TOYOTA,CAMRY,LIMITED,SEDAN,4.0,2015,AUSTRALIA,1485.0,PEARL WHITE,5.0,33400.0,17.0
65,JTNBZ4HK6R3035774,TOYOTA,CAMRY,SE+ ANNIVERSARY EDITION,SEDAN,6.0,2024,JAPAN,1620.0,SILVER,5.0,103700.0,17.0
545644,4T1BE46K77U562096,TOYOTA,CAMRY,GLI,SEDAN,4.0,2007,AMERICA,1600.0,GREEN,5.0,9700.0,17.0
545646,JTNB14HKOP3183813,TOYOTA,CAMRY,SE,SEDAN,4.0,2023,JAPAN,1520.0,WHITE,5.0,75500.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93935,JN100KY60Z0860741,NISSAN,NaN,0,SUV,6.0,1997,JAPAN,NaN,WHITE,5.0,0.0,17.0
157181,1HFSC47A37A600818,HONDA,NaN,NaN,MOTORCYCLE,NaN,2007,AMERICA,360.0,WHITE,2.0,0.0,17.0
261594,ME4KC401CLA014664,HONDA,NaN,NaN,MOTORCYCLE,NaN,2020,INDIA,100.0,BLACK,2.0,0.0,17.0
537043,ME4KC40A4TA005771,HONDA,NaN,NaN,MOTORCYCLE,NaN,2026,INDIA,NaN,BLACK,1.0,0.0,17.0
316780,LRW3E7ES9RC964797,NaN,NaN,NaN,SEDAN,NaN,NaN,UAE,1700.0,GRAY AND BLACK,3.0,0.0,17.0