In [63]:
import pandas as pd

In [64]:
data = pd.read_csv(r'../Data/toyota_valuation.csv')
data

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,1000.0,5.0
1,TOYOTA,HIACE,GLX,MINI BUS,GCC,4.0,WHITE,JAPAN,2000.0,2.0
2,TOYOTA,HIACE,DX,MINI BUS,GCC,4.0,WHITE,JAPAN,1837.0,15.0
3,TOYOTA,HILUX,DL,PICKUP DOUBLE CAB,GCC,4.0,WHITE,JAPAN,1837.0,5.0
4,TOYOTA,CAMRY,XLI,SEDAN,NON-GCC,4.0,BROWN AND BEIGE,USA,1481.0,5.0
...,...,...,...,...,...,...,...,...,...,...
239209,TOYOTA,HILUX,GLX,PICKUP,GCC,6.0,WHITE/PEARLS,INDIA,NaN,5.0
239210,TOYOTA,LAND CRUISER,NaN,SUV,GCC,6.0,BLACK,JAPAN,NaN,7.0
239211,TOYOTA,LAND CRUISER,GXR,SUV,GCC,8.0,WHITE/PEARLS,JAPAN,NaN,8.0
239212,TOYOTA,LAND CRUISER,GXL,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,7.0
239213,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,INDIA,NaN,5.0

In [65]:
print(data['model'].unique())

['COROLLA' 'HIACE' 'HILUX' 'CAMRY' 'LAND CRUISER' 'YARIS' 'FJ CRUISER'
 'RAV4' 'TUNDRA' 'AVALON' 'FORTUNER' 'COASTER' 'INNOVA' 'SIENNA' 'TACOMA'
 'RUSH' 'PRIUS' 'AVANZA' 'SEQUOIA' 'SUPRA' 'AURION' 'ECHO' 'PREVIA' 'BZ4X'
 'C-HR' 'XA' 'GRANVIA' 'VELOZ' 'RAIZE' 'IQ' 'CROWN' '86' '4RUNNER'
 'URBAN CRUISER' 'SCION' 'HIGHLANDER' nan 'DYNA' 'TERCEL' 'LITEACE'
 'MATRIX' 'ZELAS' 'ALPHARD' 'CRESSIDA' 'BZ3X' 'RUMION' 'MR2' 'WISH'
 'VENZA' 'CELICA' 'T100' 'ALLION' 'VIOS' 'CORONA' 'WIGO' 'DYNA VAN CARGO'
 'MIRAI']

In [66]:
print(data['model'].nunique())

56

In [67]:
print(data['trim'].unique())

['SE' 'GLX' 'DX' 'DL' 'XLI' 'VX' 'MID' 'DLX' 'VXR' 'FABRIC' 'E' 'TOP'
 'EXTREME' 'GL' 'BASE' 'S' 'FLEET' 'STD' 'GXR' 'EXR' 'GL2' 'SR5' 'LE'
 'LE (NON GCC)' 'GLI' 'TX' 'LIMITED' 'XLE (NON GCC)' 'EX' 'ICONIC'
 'VX MID' 'LE HEV' 'SGLX' 'PW CL' 'GX' 'XLE' 'SPORT' 'G' 'GRANDE' 'GR'
 'S TRD SPORT PK' 'S+' 'PRO' 'GLE' 'GLS' 'PLATINUM' 'DLX TOP' 'TURBO G RA'
 'VXR HEV' 'GLE HEV' 'SAFARI' 'LX' 'CE (NON GCC)' 'GLI HEV' 'PREMIUM' 'XL'
 'LX AC PWR OPT' 'LX WINCH' 'TX-L' 'XLE TOURING' 'DLS' 'OTHER'
 'GLE-X HEV 40TH ANNIV' nan 'ADVENTURE' 'CREWMAX CAPSTONE (NON GCC)'
 'LIMITED MID' 'TX-L TOP' 'EXCLUSIVE' 'XSE (NON GCC)' 'BLACK EDITION'
 'DX H/R W/B' 'C (NON GCC)' 'GLX SPORT Z' 'S PLUS' 'VTX' 'GXL' 'HT SWB'
 'ECO' 'GX MID' 'LWB HIGH ROOF' '1794 EDITION (NON GCC)'
 '40TH ANNIVERSARY EDITION' 'TOURING' 'HEV' 'PS PW CL' 'GR SPORT' 'LWB'
 'EXR HEV' 'BE' 'GT' 'SWB' 'SR' 'GTX' 'VX2' 'STANDARD' 'VX1' 'DYNAMIC'
 'FJ STD' 'YX' 'STD AC' 'GLE HEV BLACK EDITION' 'Y PLUS' 'XTREME'
 'HARD TOP' 'HYBRID (NON GCC)' 'TRD SPORT']

In [68]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
import numpy as np

# 1. Load the 'year' column from aligned toyota.csv
print("Loading year column from aligned toyota.csv...")
try:
    toyota_orig = pd.read_csv('../Data/toyota.csv')
    data['year'] = toyota_orig['year']
except Exception as e:
    print(f"Error loading year from toyota.csv: {e}")
    try:
        data['year'] = pd.read_csv('../Data/toyota_cleaned.csv')['year']
    except Exception as e2:
        print(f"Error loading year from toyota_cleaned.csv: {e2}")

# Fill missing years with 2026.0 (baseline for new cars)
data['year'] = pd.to_numeric(data['year'], errors='coerce').fillna(2026.0)

# 2. Scrape base MSRP from the official website
scraped_cache = {}

def get_toyota_msrp(model):
    if pd.isna(model):
        return None
    
    model_name = str(model).upper().strip()
    if model_name in scraped_cache:
        return scraped_cache[model_name]
    
    # Mapping from database model name to URL slug
    slug_mapping = {
        "LAND CRUISER": "land-cruiser",
        "LAND CRUISER PRADO": "prado",
        "PRADO": "prado",
        "URBAN CRUISER": "urban-cruiser",
        "C-HR": "c-hr",
        "BZ4X": "bz4x",
        "GRANVIA": "granvia",
        "RAIZE": "raize",
        "VELOZ": "veloz",
        "HIACE": "hiace",
        "COASTER": "coaster",
        "LITEACE": "liteace",
        "INNOVA": "innova",
    }
    
    model_slug = slug_mapping.get(model_name, model_name.lower().replace(" ", "-"))
    url = f"https://www.toyota.ae/en/new-cars/{model_slug}/"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, "html.parser")
            
            # Check PriceRange class first
            price_range_tag = soup.find(class_=re.compile("(?i)PriceRange"))
            if price_range_tag:
                text = price_range_tag.get_text()
                match = re.search(r"([\d,]+)", text)
                if match:
                    price_val = int(match.group(1).replace(",", ""))
                    scraped_cache[model_name] = price_val
                    return price_val
            
            # Fallback to PriceDetails or PriceRange tags
            price_details_tags = soup.find_all(class_=re.compile("(?i)(PriceDetails|PriceRange)"))
            for tag in price_details_tags:
                text = tag.get_text()
                numbers = [int(num.replace(",", "")) for num in re.findall(r"\b\d{2,3},\d{3}\b", text)]
                if numbers:
                    price_val = max(numbers)
                    scraped_cache[model_name] = price_val
                    return price_val
    except Exception as e:
        print(f"Failed to scrape for {model}: {e}")
        
    scraped_cache[model_name] = None
    return None

# Fallbacks for all model lines (ensures trusted historical/baseline prices)
base_fallbacks = {
    "COROLLA": 76900,
    "CAMRY": 122900,
    "YARIS": 64900,
    "FORTUNER": 128900,
    "LAND CRUISER": 239900,
    "HILUX": 115900,
    "HIACE": 99900,
    "RAV4": 105900,
    "VELOZ": 81900,
    "URBAN CRUISER": 79900,
    "SUPRA": 238900,
    "INNOVA": 126900,
    "HIGHLANDER": 205900,
    "CROWN": 199900,
    "RAIZE": 63900,
    "RUSH": 71900,
    "COASTER": 218900,
    "GRANVIA": 216900,
    "LITEACE": 69900,
    "PRADO": 199900,
    "LAND CRUISER PRADO": 199900,
    "AVALON": 145000,
    "TUNDRA": 195000,
    "SIENNA": 180000,
    "TACOMA": 150000,
    "PRIUS": 115000,
    "AVANZA": 68000,
    "SEQUOIA": 240000,
    "AURION": 120000,
    "ECHO": 45000,
    "PREVIA": 130000,
    "BZ4X": 189900,
    "C-HR": 95000,
    "XA": 50000,
    "IQ": 55000,
    "86": 162900,
    "4RUNNER": 160000,
    "SCION": 70000,
    "SOLARA": 85000,
    "DYNA": 110000,
    "TERCEL": 40000,
    "MATRIX": 65000,
    "ZELAS": 95000,
    "ALPHARD": 250000,
    "CRESSIDA": 35000,
    "BZ3X": 140000,
    "RUMION": 85000,
    "MR2": 110000,
    "WISH": 80000,
    "VENZA": 135000,
    "CELICA": 90000,
    "T100": 70000,
    "ALLION": 75000,
    "VIOS": 70000,
    "WIGO": 45000,
    "MIRAI": 220000
}

# Define Trim Premiums
TRIM_PREMIUMS = {
    "GLI": 7000,
    "SE": 12000,
    "GLX": 12000,
    "GLE": 7000,
    "G": 9000,
    "LIMITED": 25000,
    "SPORT": 15000,
    "XLE": 20000,
    "XSE": 25000,
    "PLATINUM": 30000,
    "TOP": 18000,
    "GXR": 34000,
    "VXR": 67000,
    "VX": 30000,
    "ZX": 159000,
    "GR": 159000,
    "ADVENTURE": 33000,
    "EXR": 15000,
    "SR5": 20000,
    "TRD": 25000,
    "STD": 0,
    "DX": 0,
    "DLX": 5000,
    "GL": 5000,
}

def calculate_ex_showroom_price(model, trim, year):
    m_name = str(model).upper().strip()
    t_name = str(trim).upper().strip()
    
    base_price = get_toyota_msrp(m_name)
    if base_price is None:
        base_price = base_fallbacks.get(m_name, base_fallbacks.get("COROLLA"))
        
    premium = TRIM_PREMIUMS.get(t_name, 0)
    new_price = base_price + premium
    
    y_val = float(year) if not pd.isna(year) else 2026.0
    age = max(0.0, 2026.0 - y_val)
    
    # GCC annual depreciation (12% per year)
    depreciated_price = new_price * ((1.0 - 0.12) ** age)
    return max(depreciated_price, min(2000.0, new_price * 0.05))

# 3. Create unique vehicles and calculate current_msrp and price
print("Calculating MSRP and prices for unique combinations...")
unique_df = (
    data[["make", "model", "trim", "year"]]
    .fillna({"model": "UNKNOWN", "trim": "UNKNOWN", "year": 2026.0})
    .drop_duplicates()
)

# Apply scraping for base MSRP
unique_df["current_msrp"] = unique_df["model"].apply(get_toyota_msrp)

# Handle fallbacks for current_msrp
unique_df["current_msrp"] = unique_df.apply(
    lambda r: r["current_msrp"] if r["current_msrp"] is not None else base_fallbacks.get(str(r["model"]).upper().strip(), base_fallbacks.get("COROLLA")),
    axis=1
)

# Apply price calculation on the unique dataframe
unique_df["price"] = unique_df.apply(
    lambda r: calculate_ex_showroom_price(r["model"], r["trim"], r["year"]), 
    axis=1
)

# Merge back while preserving all existing columns
print("Merging calculated prices back into the main DataFrame...")
if "current_msrp" in data.columns:
    data = data.drop(columns=["current_msrp"])
if "price" in data.columns:
    data = data.drop(columns=["price"])

data = data.merge(
    unique_df,
    on=["make", "model", "trim", "year"],
    how="left"
)

# Save updated dataset to CSV
output_path = r"../Data/toyota_valuation.csv"
data.to_csv(output_path, index=False)
print(f"Saved updated dataset to {output_path}")

# 4. Group by model, trim, and year, and store as data_new
data_new = data.dropna(subset=["model"]).groupby(["model", "trim", "year"])["price"].first().reset_index()

'\n======================================================================'

'MODEL: 4RUNNER'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,4RUNNER,LIMITED,SUV,GCC,6.0,GRAY AND BLACK,JAPAN,2100.0,5.0
1,TOYOTA,4RUNNER,LIMITED,SUV,GCC,6.0,WHITE,JAPAN,1600.0,5.0
2,TOYOTA,4RUNNER,LIMITED,SUV,GCC,6.0,BLACK AND RED,JAPAN,1800.0,5.0
3,TOYOTA,4RUNNER,SR5,SUV,GCC,6.0,SILVER,JAPAN,2033.0,5.0
4,TOYOTA,4RUNNER,SR5,SUV,GCC,8.0,WHITE,JAPAN,1800.0,5.0
...,...,...,...,...,...,...,...,...,...,...
265,TOYOTA,4RUNNER,SR5,SUV,GCC,6.0,SILVER,JAPAN,900.0,5.0
266,TOYOTA,4RUNNER,LIMITED,SUV,GCC,6.0,WHITE,JAPAN,1500.0,5.0
267,TOYOTA,4RUNNER,SR5,SUV,NON-GCC,4.0,WHITE,JAPAN,NaN,5.0
268,TOYOTA,4RUNNER,SR5,SUV,NON-GCC,6.0,BLUE,JAPAN,NaN,5.0
269,TOYOTA,4RUNNER,SR5,SUV,NON-GCC,6.0,RED,JAPAN,NaN,7.0

'Rows: 270'

'\n======================================================================'

'MODEL: 86'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,86,STD,COUPE,GCC,4.0,NaN,JAPAN,3000.0,4.0
1,TOYOTA,86,STD,COUPE,GCC,4.0,GOLDEN,JAPAN,1041.0,4.0
2,TOYOTA,86,STD,COUPE,GCC,4.0,ORANGE,JAPAN,1240.0,4.0
3,TOYOTA,86,VTX,COUPE,GCC,4.0,WHITE,JAPAN,1251.0,4.0
4,TOYOTA,86,STD,COUPE,GCC,4.0,WHITE,JAPAN,1200.0,4.0
...,...,...,...,...,...,...,...,...,...,...
291,TOYOTA,86,VTX,COUPE,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,4.0
292,TOYOTA,86,STD,COUPE,NON-GCC,4.0,WHITE,JAPAN,NaN,4.0
293,TOYOTA,86,GT,COUPE,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,4.0
294,TOYOTA,86,STD,COUPE,GCC,4.0,RED,JAPAN,NaN,4.0
295,TOYOTA,86,GTX,COUPE,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,4.0

'Rows: 296'

'\n======================================================================'

'MODEL: ALLION'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,ALLION,NaN,SEDAN,NON-GCC,4.0,WHITE,CHINA,NaN,5.0
1,TOYOTA,ALLION,LE,SEDAN,GCC,4.0,WHITE,CHINA,1600.0,5.0

'Rows: 2'

'\n======================================================================'

'MODEL: ALPHARD'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,WHITE,JAPAN,NaN,6.0
1,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,1850.0,7.0
2,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,1800.0,5.0
3,TOYOTA,ALPHARD,SE,MPV,GCC,4.0,BLACK,JAPAN,2630.0,6.0
4,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,SILVER,USA,65.0,5.0
5,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,WHITE / BLACK,JAPAN,NaN,5.0
6,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,PEARL WHITE,JAPAN,1000.0,7.0
7,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,1950.0,6.0
8,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,1800.0,5.0
9,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,1850.0,7.0
10,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,1910.0,7.0
11,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,1800.0,5.0
12,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,WHITE PEARL,JAPAN,2000.0,7.0
13,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,1800.0,5.0
14,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,NaN,6.0
15,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,2200.0,7.0
16,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,BLACK,JAPAN,2000.0,7.0
17,TOYOTA,ALPHARD,LIMITED,MPV,GCC,6.0,PEARL WHITE,JAPAN,1950.0,5.0

'Rows: 18'

'\n======================================================================'

'MODEL: AURION'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,AURION,MID,SEDAN,GCC,6.0,SILVER,AUSTRALIA,1600.0,5.0
1,TOYOTA,AURION,MID,SEDAN,GCC,6.0,BLACK,AUSTRALIA,1200.0,5.0
2,TOYOTA,AURION,SPORT,SEDAN,GCC,6.0,BLACK,AUSTRALIA,1100.0,5.0
3,TOYOTA,AURION,TOP,SEDAN,GCC,6.0,BLACK,AUSTRALIA,1600.0,4.0
4,TOYOTA,AURION,MID,SEDAN,GCC,6.0,WHITE,AUSTRALIA,2000.0,5.0
...,...,...,...,...,...,...,...,...,...,...
979,TOYOTA,AURION,MID,SEDAN,GCC,6.0,WHITE,NaN,NaN,5.0
980,TOYOTA,AURION,SPORT,SEDAN,GCC,6.0,WHITE/PEARLS,NaN,NaN,5.0
981,TOYOTA,AURION,MID,SEDAN,GCC,6.0,WHITE/PEARLS,NaN,NaN,5.0
982,TOYOTA,AURION,MID,SEDAN,GCC,6.0,WHITE,NaN,NaN,5.0
983,TOYOTA,AURION,SE,SEDAN,GCC,6.0,WHITE/PEARLS,NaN,NaN,5.0

'Rows: 984'

'\n======================================================================'

'MODEL: AVALON'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,AVALON,BASE,SEDAN,GCC,6.0,MAROON,USA,1375.0,5.0
1,TOYOTA,AVALON,XLE,SEDAN,GCC,6.0,BLACK,USA,1350.0,5.0
2,TOYOTA,AVALON,LIMITED,SEDAN,GCC,6.0,PEARL WHITE,USA,1373.0,5.0
3,TOYOTA,AVALON,LIMITED,SEDAN,NON-GCC,6.0,WHITE,USA,1200.0,5.0
4,TOYOTA,AVALON,TOP,SEDAN,GCC,6.0,WHITE,USA,1600.0,5.0
...,...,...,...,...,...,...,...,...,...,...
4552,TOYOTA,AVALON,LIMITED,SEDAN,GCC,6.0,WHITE/PEARLS,USA,NaN,5.0
4553,TOYOTA,AVALON,BASE,SEDAN,GCC,4.0,WHITE,USA,NaN,5.0
4554,TOYOTA,AVALON,LIMITED,SEDAN,GCC,6.0,WHITE/PEARLS,USA,NaN,5.0
4555,TOYOTA,AVALON,BASE,SEDAN,NON-GCC,6.0,GRAY,USA,NaN,5.0
4556,TOYOTA,AVALON,LIMITED,SEDAN,GCC,6.0,WHITE/PEARLS,USA,NaN,5.0

'Rows: 4557'

'\n======================================================================'

'MODEL: AVANZA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,AVANZA,SE,MPV,GCC,4.0,NaN,INDIA,3000.0,7.0
1,TOYOTA,AVANZA,SE,MPV,GCC,4.0,WHITE,INDIA,1100.0,7.0
2,TOYOTA,AVANZA,SE,MPV,GCC,4.0,BEIGE,INDIA,2000.0,7.0
3,TOYOTA,AVANZA,SE,MPV,GCC,4.0,SILVER,INDIA,1170.0,7.0
4,TOYOTA,AVANZA,SE,MPV,GCC,4.0,WHITE,INDIA,1170.0,7.0
...,...,...,...,...,...,...,...,...,...,...
1513,TOYOTA,AVANZA,NaN,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
1514,TOYOTA,AVANZA,SE,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
1515,TOYOTA,AVANZA,NaN,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
1516,TOYOTA,AVANZA,SE,SUV,GCC,4.0,SILVER,INDIA,NaN,7.0
1517,TOYOTA,AVANZA,SE,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0

'Rows: 1518'

'\n======================================================================'

'MODEL: BZ3X'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,BZ3X,OTHER,SUV,GCC,0.0,GREY,CHINA,1000.0,5.0
1,TOYOTA,BZ3X,STD,SUV,GCC,0.0,WHITE,CHINA,NaN,5.0

'Rows: 2'

'\n======================================================================'

'MODEL: BZ4X'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,BLACK,CHINA,1600.0,5.0
1,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,BLACK / GREY,CHINA,1600.0,5.0
2,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,LEAD,CHINA,1600.0,5.0
3,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,GREY,JAPAN,NaN,5.0
4,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,WHITE / BLACK,CHINA,1700.0,5.0
5,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,GRAY AND BLACK,CHINA,1400.0,5.0
6,TOYOTA,BZ4X,PRO,SUV,NON-GCC,6.0,WHITE,CHINA,1400.0,5.0
7,TOYOTA,BZ4X,PRO,SUV,NON-GCC,0.0,WHITE / BLACK,CHINA,1600.0,5.0
8,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,WHITE,CHINA,1100.0,5.0
9,TOYOTA,BZ4X,PRO,SUV,GCC,4.0,SILVER,CHINA,1600.0,5.0
10,TOYOTA,BZ4X,NaN,SEDAN,NON-GCC,6.0,GRAY AND BLACK,CHINA,1100.0,5.0
11,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,GRAY AND BLACK,CHINA,1450.0,5.0
12,TOYOTA,BZ4X,BASE,WAGON,GCC,0.0,GRAY AND BLACK,CHINA,1600.0,5.0
13,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,GREY,CHINA,1600.0,5.0
14,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,GREY,CHINA,1600.0,5.0
15,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,BLACK,CHINA,1400.0,5.0
16,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,WHITE / BLACK,CHINA,1450.0,5.0
17,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,WHITE / BLACK,CHINA,1630.0,5.0
18,TOYOTA,BZ4X,PRO,SUV,NON-GCC,0.0,WHITE,CHINA,1400.0,5.0
19,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,GREY,CHINA,1400.0,5.0
20,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,WHITE,CHINA,1600.0,5.0
21,TOYOTA,BZ4X,NaN,WAGON,GCC,4.0,GREY,CHINA,2000.0,5.0
22,TOYOTA,BZ4X,PRO,SUV,NON-GCC,0.0,WHITE,CHINA,1600.0,5.0
23,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,WHITE / BLACK,CHINA,1600.0,5.0
24,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,GRAY AND BLACK,CHINA,1500.0,5.0
25,TOYOTA,BZ4X,PRO,SUV,NON-GCC,0.0,WHITE,CHINA,1500.0,5.0
26,TOYOTA,BZ4X,STD,WAGON,GCC,6.0,BLACK,CHINA,1600.0,5.0
27,TOYOTA,BZ4X,PRO,SUV,GCC,0.0,WHITE / BLACK,CHINA,1600.0,5.0

'Rows: 28'

'\n======================================================================'

'MODEL: C-HR'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,C-HR,VX,SUV,GCC,4.0,WHITE / BLACK,TURKEY,1460.0,5.0
1,TOYOTA,C-HR,VX,SUV,GCC,4.0,NaN,JAPAN,3000.0,5.0
2,TOYOTA,C-HR,VX,SUV,GCC,4.0,WHITE PEARL,TURKEY,1460.0,5.0
3,TOYOTA,C-HR,VX,SUV,GCC,4.0,WHITE / BLACK,TURKEY,1460.0,5.0
4,TOYOTA,C-HR,VX,SUV,GCC,4.0,NaN,JAPAN,3000.0,5.0
...,...,...,...,...,...,...,...,...,...,...
409,TOYOTA,C-HR,VX,SUV,GCC,4.0,WHITE/PEARLS,NaN,NaN,5.0
410,TOYOTA,C-HR,VX,SUV,GCC,4.0,GRAY,NaN,NaN,5.0
411,TOYOTA,C-HR,VX,SUV,GCC,4.0,WHITE/BLACK,NaN,NaN,5.0
412,TOYOTA,C-HR,VX,SUV,GCC,4.0,WHITE/BLACK,NaN,NaN,5.0
413,TOYOTA,C-HR,GX,SUV,NON-GCC,4.0,GRAY,NaN,NaN,5.0

'Rows: 414'

'\n======================================================================'

'MODEL: CAMRY'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,CAMRY,XLI,SEDAN,NON-GCC,4.0,BROWN AND BEIGE,USA,1481.0,5.0
1,TOYOTA,CAMRY,GL,SEDAN,GCC,4.0,WHITE,AUSTRALIA,1600.0,5.0
2,TOYOTA,CAMRY,XLI,SEDAN,GCC,4.0,BLACK AND SILVER,AUSTRALIA,1100.0,4.0
3,TOYOTA,CAMRY,S,SEDAN,GCC,4.0,WHITE,AUSTRALIA,1920.0,5.0
4,TOYOTA,CAMRY,XLI,SEDAN,GCC,4.0,GOLDEN,AUSTRALIA,1600.0,5.0
...,...,...,...,...,...,...,...,...,...,...
51765,TOYOTA,CAMRY,XLE,SEDAN,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,5.0
51766,TOYOTA,CAMRY,SPORT,SEDAN,GCC,6.0,WHITE/PEARLS,JAPAN,NaN,5.0
51767,TOYOTA,CAMRY,SPORT,SEDAN,GCC,6.0,WHITE/PEARLS,JAPAN,NaN,5.0
51768,TOYOTA,CAMRY,S,SEDAN,GCC,4.0,SILVER,NaN,NaN,5.0
51769,TOYOTA,CAMRY,GLI,SEDAN,GCC,4.0,WHITE,NaN,NaN,5.0

'Rows: 51770'

'\n======================================================================'

'MODEL: CELICA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,CELICA,STD,HATCHBACK,GCC,4.0,GREEN,JAPAN,NaN,4.0
1,TOYOTA,CELICA,STD,COUPE,GCC,4.0,BLACK AND RED,JAPAN,1250.0,4.0
2,TOYOTA,CELICA,GT,COUPE,GCC,4.0,BLACK AND RED,JAPAN,1100.0,2.0
3,TOYOTA,CELICA,SE,COUPE,GCC,4.0,SILVER,JAPAN,NaN,2.0
4,TOYOTA,CELICA,STD,COUPE,GCC,4.0,BLACK,JAPAN,1600.0,4.0
5,TOYOTA,CELICA,GT,COUPE,NON-GCC,4.0,BLACK,JAPAN,NaN,4.0
6,TOYOTA,CELICA,GT,COUPE,NON-GCC,4.0,BLACK/SILVER,JAPAN,NaN,5.0

'Rows: 7'

'\n======================================================================'

'MODEL: COASTER'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,COASTER,STD,BUS,GCC,6.0,WHITE AND BLUE,JAPAN,3000.0,25.0
1,TOYOTA,COASTER,LWB HIGH ROOF,BUS,GCC,4.0,WHITE,JAPAN,2000.0,26.0
2,TOYOTA,COASTER,LWB HIGH ROOF,BUS,GCC,4.0,WHITE,JAPAN,3100.0,30.0
3,TOYOTA,COASTER,LWB,BUS,GCC,6.0,WHITE,JAPAN,3100.0,30.0
4,TOYOTA,COASTER,LWB HIGH ROOF,BUS,GCC,4.0,WHITE,JAPAN,2280.0,30.0
...,...,...,...,...,...,...,...,...,...,...
546,TOYOTA,COASTER,GLS,BUS,GCC,4.0,WHITE,JAPAN,3200.0,30.0
547,TOYOTA,COASTER,LWB,BUS,GCC,4.0,WHITE,JAPAN,1740.0,30.0
548,TOYOTA,COASTER,SWB,BUS,GCC,4.0,NaN,JAPAN,3000.0,5.0
549,TOYOTA,COASTER,SWB,BUS,GCC,4.0,WHITE,JAPAN,NaN,30.0
550,TOYOTA,COASTER,SWB,BUS,GCC,4.0,BROWN AND BEIGE,SOUTH KOREA,2800.0,26.0

'Rows: 551'

'\n======================================================================'

'MODEL: COROLLA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,1000.0,5.0
1,TOYOTA,COROLLA,XLI,SEDAN,GCC,4.0,SILVER,JAPAN,1100.0,5.0
2,TOYOTA,COROLLA,XLI,SEDAN,GCC,4.0,GREY,TAIWAN,1100.0,5.0
3,TOYOTA,COROLLA,XLI,SEDAN,GCC,4.0,SILVER,JAPAN,1100.0,5.0
4,TOYOTA,COROLLA,XLI,SEDAN,GCC,4.0,BLACK,JAPAN,1200.0,5.0
...,...,...,...,...,...,...,...,...,...,...
39047,TOYOTA,COROLLA,XLI,SEDAN,GCC,4.0,SILVER,JAPAN,NaN,5.0
39048,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,NaN,5.0
39049,TOYOTA,COROLLA,NaN,SEDAN,GCC,4.0,WHITE,TAIWAN,NaN,5.0
39050,TOYOTA,COROLLA,XLI,SEDAN,GCC,4.0,BLUE,JAPAN,NaN,5.0
39051,TOYOTA,COROLLA,XL,SUV,GCC,4.0,WHITE,TAIWAN,NaN,5.0

'Rows: 39052'

'\n======================================================================'

'MODEL: CORONA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,CORONA,S,SEDAN,GCC,4.0,WHITE,TAIWAN,900.0,5.0

'Rows: 1'

'\n======================================================================'

'MODEL: CRESSIDA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,CRESSIDA,STD,SEDAN,GCC,0.0,SILVER,JAPAN,1501.0,5.0
1,TOYOTA,CRESSIDA,OTHER,SEDAN,GCC,6.0,GRAY AND BLACK,JAPAN,1400.0,5.0
2,TOYOTA,CRESSIDA,STANDARD,SEDAN,GCC,6.0,BLUE,JAPAN,900.0,5.0
3,TOYOTA,CRESSIDA,OTHER,SEDAN,GCC,6.0,SILVER,JAPAN,1600.0,5.0
4,TOYOTA,CRESSIDA,NaN,SEDAN,NON-GCC,6.0,WHITE,JAPAN,NaN,5.0

'Rows: 5'

'\n======================================================================'

'MODEL: CROWN'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,CROWN,PREMIUM,SEDAN,GCC,4.0,WHITE,JAPAN,1100.0,5.0
1,TOYOTA,CROWN,XLE,SEDAN,GCC,4.0,WHITE PEARL,JAPAN,1720.0,5.0
2,TOYOTA,CROWN,PLATINUM,SEDAN,GCC,4.0,BLACK,JAPAN,1720.0,5.0
3,TOYOTA,CROWN,PREMIUM,SEDAN,GCC,4.0,WHITE,JAPAN,1600.0,5.0
4,TOYOTA,CROWN,XLE,SEDAN,GCC,4.0,WHITE,JAPAN,1100.0,5.0
...,...,...,...,...,...,...,...,...,...,...
207,TOYOTA,CROWN,XLE,SEDAN,GCC,4.0,WHITE,JAPAN,NaN,5.0
208,TOYOTA,CROWN,PLATINUM,SEDAN,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,5.0
209,TOYOTA,CROWN,PLATINUM,SEDAN,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,5.0
210,TOYOTA,CROWN,XLE,SEDAN,GCC,4.0,WHITE,JAPAN,NaN,5.0
211,TOYOTA,CROWN,XLE,SEDAN,GCC,4.0,WHITE,JAPAN,NaN,5.0

'Rows: 212'

'\n======================================================================'

'MODEL: DYNA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,DYNA,STD,PICKUP,GCC,4.0,WHITE,JAPAN,2250.0,3.0
1,TOYOTA,DYNA,NaN,PICKUP,GCC,8.0,WHITE,JAPAN,2000.0,3.0
2,TOYOTA,DYNA,STD,PICKUP,GCC,4.0,WHITE,JAPAN,2150.0,3.0
3,TOYOTA,DYNA,STD,PICKUP,GCC,4.0,WHITE,JAPAN,2000.0,3.0
4,TOYOTA,DYNA,OTHER,PICKUP,GCC,4.0,WHITE,JAPAN,2500.0,3.0
5,TOYOTA,DYNA,STD,PICKUP,GCC,4.0,WHITE,JAPAN,2741.0,3.0
6,TOYOTA,DYNA,NaN,PICKUP,GCC,8.0,WHITE,JAPAN,2000.0,2.0
7,TOYOTA,DYNA,NaN,PICKUP,GCC,4.0,WHITE,JAPAN,2250.0,3.0
8,TOYOTA,DYNA,S,PICKUP,GCC,4.0,WHITE,JAPAN,NaN,2.0
9,TOYOTA,DYNA,STD,TRUCK,GCC,4.0,WHITE,JAPAN,2500.0,3.0
10,TOYOTA,DYNA,STD,TRUCK,GCC,6.0,WHITE,JAPAN,2000.0,3.0
11,TOYOTA,DYNA,S,PICKUP,GCC,4.0,WHITE,JAPAN,2500.0,3.0
12,TOYOTA,DYNA,STD,PICKUP,GCC,4.0,WHITE,JAPAN,2200.0,2.0

'Rows: 13'

'\n======================================================================'

'MODEL: DYNA VAN CARGO'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,DYNA VAN CARGO,STD,VAN,GCC,6.0,WHITE,JAPAN,2000.0,3.0

'Rows: 1'

'\n======================================================================'

'MODEL: ECHO'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,ECHO,XLI,SEDAN,GCC,4.0,BLUE,JAPAN,900.0,5.0
1,TOYOTA,ECHO,XLI,SEDAN,GCC,4.0,SILVER,JAPAN,1252.0,5.0
2,TOYOTA,ECHO,XLI,SEDAN,GCC,4.0,RED,JAPAN,1014.0,5.0
3,TOYOTA,ECHO,XLI,SEDAN,GCC,4.0,BLACK,JAPAN,1150.0,5.0
4,TOYOTA,ECHO,XLI,SEDAN,GCC,4.0,WHITE,JAPAN,1100.0,5.0
...,...,...,...,...,...,...,...,...,...,...
695,TOYOTA,ECHO,PS PW CL,SEDAN,GCC,4.0,SILVER,JAPAN,NaN,5.0
696,TOYOTA,ECHO,PS PW CL,SEDAN,GCC,4.0,WHITE,JAPAN,NaN,5.0
697,TOYOTA,ECHO,XLI,SEDAN,GCC,4.0,BEIGE,JAPAN,NaN,5.0
698,TOYOTA,ECHO,PS PW CL,SEDAN,GCC,4.0,SILVER,JAPAN,NaN,5.0
699,TOYOTA,ECHO,PS PW CL,SEDAN,GCC,4.0,RED,JAPAN,NaN,5.0

'Rows: 700'

'\n======================================================================'

'MODEL: FJ CRUISER'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,FJ CRUISER,VXR,SUV,GCC,6.0,GREY,JAPAN,1600.0,5.0
1,TOYOTA,FJ CRUISER,TOP,SUV,GCC,6.0,NaN,JAPAN,3000.0,5.0
2,TOYOTA,FJ CRUISER,EXTREME,SUV,GCC,6.0,NaN,JAPAN,3000.0,5.0
3,TOYOTA,FJ CRUISER,BASE,SUV,GCC,6.0,WHITE AND SILVER,JAPAN,2000.0,5.0
4,TOYOTA,FJ CRUISER,EXTREME,SUV,GCC,6.0,WHITE & GREY,JAPAN,1600.0,5.0
...,...,...,...,...,...,...,...,...,...,...
2950,TOYOTA,FJ CRUISER,GXR,SUV,GCC,6.0,WHITE,JAPAN,NaN,5.0
2951,TOYOTA,FJ CRUISER,BASE,SUV,GCC,4.0,BLACK,JAPAN,NaN,5.0
2952,TOYOTA,FJ CRUISER,ADVENTURE,SUV,GCC,6.0,WHITE/BEIGE,JAPAN,NaN,5.0
2953,TOYOTA,FJ CRUISER,VXR,SUV,GCC,6.0,WHITE,JAPAN,NaN,5.0
2954,TOYOTA,FJ CRUISER,FJ STD,SUV,GCC,6.0,BEIGE,JAPAN,NaN,5.0

'Rows: 2955'

'\n======================================================================'

'MODEL: FORTUNER'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,FORTUNER,GXR,SUV,GCC,6.0,NaN,INDIA,3000.0,7.0
1,TOYOTA,FORTUNER,EXR,SUV,GCC,4.0,PEARL WHITE,INDIA,1600.0,7.0
2,TOYOTA,FORTUNER,SR5,SUV,GCC,4.0,WHITE PEARL,INDIA,2010.0,7.0
3,TOYOTA,FORTUNER,EXR,SUV,GCC,4.0,WHITE,INDIA,2000.0,7.0
4,TOYOTA,FORTUNER,TOP,SUV,GCC,4.0,BLACK,INDIA,2000.0,7.0
...,...,...,...,...,...,...,...,...,...,...
5334,TOYOTA,FORTUNER,GXR,SUV,GCC,6.0,WHITE,INDIA,NaN,7.0
5335,TOYOTA,FORTUNER,GXR,SUV,GCC,6.0,WHITE/PEARLS,INDIA,NaN,7.0
5336,TOYOTA,FORTUNER,SR5,SUV,GCC,6.0,WHITE,INDIA,NaN,7.0
5337,TOYOTA,FORTUNER,VXR,SUV,GCC,6.0,GRAY,INDIA,NaN,7.0
5338,TOYOTA,FORTUNER,SR5,SUV,GCC,4.0,WHITE,INDIA,NaN,8.0

'Rows: 5339'

'\n======================================================================'

'MODEL: GRANVIA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,GRANVIA,PLATINUM,MPV,GCC,6.0,WHITE,JAPAN,1800.0,6.0
1,TOYOTA,GRANVIA,PREMIUM,MPV,GCC,6.0,BLACK,JAPAN,1700.0,6.0
2,TOYOTA,GRANVIA,PREMIUM,MPV,GCC,6.0,BLACK,JAPAN,2000.0,6.0
3,TOYOTA,GRANVIA,PLATINUM,MPV,GCC,6.0,GREEN AND BLACK,JAPAN,NaN,6.0
4,TOYOTA,GRANVIA,PREMIUM,MPV,GCC,6.0,BLACK,JAPAN,2500.0,6.0
...,...,...,...,...,...,...,...,...,...,...
83,TOYOTA,GRANVIA,PREMIUM,MPV,GCC,6.0,BLACK,JAPAN,2000.0,6.0
84,TOYOTA,GRANVIA,PREMIUM,MPV,GCC,6.0,BLACK,JAPAN,2440.0,6.0
85,TOYOTA,GRANVIA,PREMIUM,MPV,GCC,6.0,BLACK,JAPAN,NaN,6.0
86,TOYOTA,GRANVIA,PREMIUM,MPV,GCC,6.0,BLACK,JAPAN,NaN,6.0
87,TOYOTA,GRANVIA,PREMIUM,SUV,GCC,6.0,BLACK,JAPAN,NaN,6.0

'Rows: 88'

'\n======================================================================'

'MODEL: HIACE'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,HIACE,GLX,MINI BUS,GCC,4.0,WHITE,JAPAN,2000.0,2.0
1,TOYOTA,HIACE,DX,MINI BUS,GCC,4.0,WHITE,JAPAN,1837.0,15.0
2,TOYOTA,HIACE,GL,VAN,GCC,4.0,WHITE,JAPAN,1800.0,3.0
3,TOYOTA,HIACE,GL,VAN,GCC,4.0,WHITE,JAPAN,1500.0,2.0
4,TOYOTA,HIACE,GL,VAN,GCC,4.0,WHITE,JAPAN,1800.0,12.0
...,...,...,...,...,...,...,...,...,...,...
11743,TOYOTA,HIACE,GL,MINI BUS,GCC,4.0,WHITE,JAPAN,1700.0,13.0
11744,TOYOTA,HIACE,GL,MINI BUS,GCC,4.0,WHITE,JAPAN,1708.0,12.0
11745,TOYOTA,HIACE,GL,MINI BUS,GCC,4.0,WHITE,JAPAN,1500.0,13.0
11746,TOYOTA,HIACE,GL,MINI BUS,GCC,4.0,WHITE,JAPAN,1650.0,13.0
11747,TOYOTA,HIACE,GL,VAN,GCC,6.0,WHITE,JAPAN,2000.0,6.0

'Rows: 11748'

'\n======================================================================'

'MODEL: HIGHLANDER'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,HIGHLANDER,VXR,SUV,GCC,4.0,PEARL WHITE,USA,1730.0,7.0
1,TOYOTA,HIGHLANDER,VXR,SUV,GCC,4.0,GRAY AND BLACK,USA,1600.0,7.0
2,TOYOTA,HIGHLANDER,GXR,SUV,GCC,4.0,BLACK,USA,NaN,7.0
3,TOYOTA,HIGHLANDER,GXR,SUV,GCC,4.0,BLUE,USA,1500.0,7.0
4,TOYOTA,HIGHLANDER,VXR,SUV,GCC,4.0,SILVER,USA,2009.0,7.0
...,...,...,...,...,...,...,...,...,...,...
515,TOYOTA,HIGHLANDER,GXR,SUV,GCC,4.0,WHITE,USA,NaN,7.0
516,TOYOTA,HIGHLANDER,VXR,SUV,GCC,4.0,WHITE/PEARLS,USA,NaN,7.0
517,TOYOTA,HIGHLANDER,VXR,SUV,GCC,4.0,BLACK,USA,NaN,7.0
518,TOYOTA,HIGHLANDER,VXR,SUV,GCC,4.0,WHITE/PEARLS,USA,NaN,7.0
519,TOYOTA,HIGHLANDER,VXR,SUV,GCC,4.0,WHITE/PEARLS,USA,NaN,7.0

'Rows: 520'

'\n======================================================================'

'MODEL: HILUX'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,HILUX,DL,PICKUP DOUBLE CAB,GCC,4.0,WHITE,JAPAN,1837.0,5.0
1,TOYOTA,HILUX,DLX,PICKUP SINGLE CAB,GCC,4.0,WHITE,INDIA,1800.0,3.0
2,TOYOTA,HILUX,GL,PICKUP DOUBLE CAB,GCC,4.0,WHITE,INDIA,1600.0,6.0
3,TOYOTA,HILUX,GL,PICKUP DOUBLE CAB,GCC,4.0,WHITE,INDIA,1600.0,6.0
4,TOYOTA,HILUX,GL2,PICKUP DOUBLE CAB,GCC,4.0,WHITE,INDIA,1655.0,5.0
...,...,...,...,...,...,...,...,...,...,...
17330,TOYOTA,HILUX,LX,PICKUP,GCC,4.0,BEIGE,JAPAN,NaN,2.0
17331,TOYOTA,HILUX,DLX TOP,PICKUP,GCC,4.0,WHITE,INDIA,NaN,5.0
17332,TOYOTA,HILUX,NaN,PICKUP,GCC,4.0,WHITE,JAPAN,NaN,5.0
17333,TOYOTA,HILUX,NaN,PICKUP,GCC,4.0,SILVER,INDIA,NaN,5.0
17334,TOYOTA,HILUX,GLX,PICKUP,GCC,6.0,WHITE/PEARLS,INDIA,NaN,5.0

'Rows: 17335'

'\n======================================================================'

'MODEL: INNOVA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,INNOVA,GL,MPV,GCC,4.0,WHITE,INDIA,1650.0,8.0
1,TOYOTA,INNOVA,GL,MPV,GCC,4.0,BLACK,INDIA,1600.0,8.0
2,TOYOTA,INNOVA,GL,MPV,GCC,4.0,WHITE,INDIA,2000.0,8.0
3,TOYOTA,INNOVA,GL,MPV,GCC,4.0,WHITE,INDIA,2000.0,8.0
4,TOYOTA,INNOVA,GL,MPV,GCC,4.0,GOLD & BLACK,INDIA,1200.0,8.0
...,...,...,...,...,...,...,...,...,...,...
2682,TOYOTA,INNOVA,HEV,SUV,GCC,4.0,BLACK,INDIA,NaN,8.0
2683,TOYOTA,INNOVA,SE,SUV,GCC,4.0,WHITE,INDIA,NaN,8.0
2684,TOYOTA,INNOVA,DX,SUV,GCC,4.0,GRAY,INDIA,NaN,8.0
2685,TOYOTA,INNOVA,HEV,SUV,GCC,4.0,WHITE,INDIA,NaN,8.0
2686,TOYOTA,INNOVA,HEV,SUV,GCC,4.0,WHITE/PEARLS,INDIA,NaN,8.0

'Rows: 2687'

'\n======================================================================'

'MODEL: IQ'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,IQ,STD,HATCHBACK,GCC,4.0,SILVER,JAPAN,1100.0,5.0
1,TOYOTA,IQ,STD,HATCHBACK,GCC,4.0,MAROON,JAPAN,NaN,4.0
2,TOYOTA,IQ,STD,HATCHBACK,GCC,4.0,BLUE,JAPAN,900.0,5.0
3,TOYOTA,IQ,STD,HATCHBACK,GCC,4.0,GRAY AND BLACK,JAPAN,950.0,5.0
4,TOYOTA,IQ,STD,HATCHBACK,GCC,4.0,SILVER,JAPAN,1100.0,5.0
...,...,...,...,...,...,...,...,...,...,...
68,TOYOTA,IQ,STD,HATCHBACK,NON-GCC,4.0,VIOLET,JAPAN,NaN,4.0
69,TOYOTA,IQ,STD,HATCHBACK,NON-GCC,4.0,WHITE,JAPAN,NaN,4.0
70,TOYOTA,IQ,STD,HATCHBACK,NON-GCC,4.0,SILVER,JAPAN,NaN,4.0
71,TOYOTA,IQ,STD,HATCHBACK,NON-GCC,4.0,SILVER,JAPAN,NaN,2.0
72,TOYOTA,IQ,STD,HATCHBACK,NON-GCC,4.0,ORANGE,JAPAN,NaN,4.0

'Rows: 73'

'\n======================================================================'

'MODEL: LAND CRUISER'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,LAND CRUISER,VX,SUV,GCC,8.0,PEARL WHITE,JAPAN,3260.0,8.0
1,TOYOTA,LAND CRUISER,GXR,SUV,GCC,6.0,WHITE PEARL,JAPAN,2000.0,8.0
2,TOYOTA,LAND CRUISER,GXR,SUV,GCC,6.0,PEARL WHITE,JAPAN,NaN,7.0
3,TOYOTA,LAND CRUISER,GXR,SUV,GCC,6.0,PEARL WHITE,JAPAN,2000.0,8.0
4,TOYOTA,LAND CRUISER,VX,SUV,GCC,8.0,WHITE PEARL,JAPAN,2000.0,8.0
...,...,...,...,...,...,...,...,...,...,...
40923,TOYOTA,LAND CRUISER,VX,SUV,GCC,8.0,SILVER,JAPAN,NaN,8.0
40924,TOYOTA,LAND CRUISER,VX,SUV,GCC,8.0,WHITE/PEARLS,JAPAN,NaN,8.0
40925,TOYOTA,LAND CRUISER,NaN,SUV,GCC,6.0,BLACK,JAPAN,NaN,7.0
40926,TOYOTA,LAND CRUISER,GXR,SUV,GCC,8.0,WHITE/PEARLS,JAPAN,NaN,8.0
40927,TOYOTA,LAND CRUISER,GXL,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,7.0

'Rows: 40928'

'\n======================================================================'

'MODEL: LITEACE'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,LITEACE,GL,VAN,GCC,4.0,PINK,INDIA,1240.0,2.0
1,TOYOTA,LITEACE,STD,VAN,GCC,4.0,WHITE,INDIA,NaN,5.0
2,TOYOTA,LITEACE,STD,VAN,GCC,4.0,WHITE,INDIA,1240.0,5.0
3,TOYOTA,LITEACE,GL,VAN,GCC,4.0,BLUE,INDIA,1240.0,2.0
4,TOYOTA,LITEACE,GL,VAN,GCC,4.0,WHITE,INDIA,1650.0,2.0
...,...,...,...,...,...,...,...,...,...,...
132,TOYOTA,LITEACE,STD,VAN,GCC,4.0,WHITE,INDIA,1240.0,2.0
133,TOYOTA,LITEACE,STD,VAN,GCC,4.0,NaN,INDIA,3000.0,2.0
134,TOYOTA,LITEACE,STD,VAN,GCC,4.0,WHITE,INDIA,1500.0,5.0
135,TOYOTA,LITEACE,STD,VAN,GCC,4.0,WHITE,INDIA,1240.0,3.0
136,TOYOTA,LITEACE,STD,VAN,GCC,4.0,WHITE,INDIA,NaN,5.0

'Rows: 137'

'\n======================================================================'

'MODEL: MATRIX'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,BLUE,CANADA,1270.0,5.0
1,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,1200.0,5.0
2,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,1500.0,5.0
3,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,1301.0,5.0
4,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,1100.0,5.0
5,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,WHITE,CANADA,1600.0,5.0
6,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,BLACK,CANADA,1100.0,5.0
7,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,RED,CANADA,1545.0,5.0
8,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,GREY,CANADA,1200.0,5.0
9,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,1350.0,5.0
10,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,WHITE,CANADA,1350.0,5.0
11,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,WHITE,CANADA,1100.0,5.0
12,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,1270.0,5.0
13,TOYOTA,MATRIX,STD,SEDAN,GCC,4.0,SILVER,CANADA,1100.0,5.0
14,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,BLUE,CANADA,1650.0,5.0
15,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,BLUE,CANADA,1400.0,5.0
16,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,GREY,CANADA,1600.0,5.0
17,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,GRAY AND BLACK,CANADA,1100.0,5.0
18,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,BLACK,CANADA,1400.0,5.0
19,TOYOTA,MATRIX,STD,SUV,GCC,4.0,SILVER,CANADA,1270.0,5.0
20,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,WHITE,CANADA,1200.0,5.0
21,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,1500.0,5.0
22,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,1500.0,5.0
23,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,SILVER,CANADA,NaN,5.0
24,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,BLACK,CANADA,1500.0,5.0
25,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,BEIGE,CANADA,1200.0,5.0
26,TOYOTA,MATRIX,STD,HATCHBACK,GCC,4.0,WHITE,CANADA,1500.0,5.0

'Rows: 27'

'\n======================================================================'

'MODEL: MIRAI'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,MIRAI,LE,SEDAN,GCC,4.0,WHITE,JAPAN,1555.0,5.0

'Rows: 1'

'\n======================================================================'

'MODEL: MR2'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,MR2,PREMIUM,COUPE,GCC,4.0,WHITE,JAPAN,950.0,2.0
1,TOYOTA,MR2,STD,COUPE,GCC,4.0,WHITE,JAPAN,1500.0,2.0
2,TOYOTA,MR2,GLX,COUPE,GCC,4.0,RED,JAPAN,1000.0,2.0
3,TOYOTA,MR2,STD,COUPE,GCC,6.0,GREEN,JAPAN,3770.0,5.0

'Rows: 4'

'\n======================================================================'

'MODEL: PREVIA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,PREVIA,SE,MPV,GCC,4.0,PEARL WHITE,JAPAN,1720.0,7.0
1,TOYOTA,PREVIA,DLX,MPV,GCC,4.0,GRAY AND BLACK,JAPAN,2000.0,8.0
2,TOYOTA,PREVIA,DLX,MPV,GCC,4.0,PEARL WHITE,JAPAN,2000.0,8.0
3,TOYOTA,PREVIA,GL,MPV,GCC,6.0,PEARL WHITE,JAPAN,1400.0,7.0
4,TOYOTA,PREVIA,DLX,MPV,GCC,4.0,GREY,JAPAN,2000.0,8.0
...,...,...,...,...,...,...,...,...,...,...
2028,TOYOTA,PREVIA,GL,SUV,GCC,4.0,WHITE,JAPAN,NaN,8.0
2029,TOYOTA,PREVIA,DLX,SUV,GCC,4.0,WHITE,JAPAN,NaN,8.0
2030,TOYOTA,PREVIA,S,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,8.0
2031,TOYOTA,PREVIA,SE,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,8.0
2032,TOYOTA,PREVIA,GL,SUV,NON-GCC,4.0,SILVER,JAPAN,NaN,7.0

'Rows: 2033'

'\n======================================================================'

'MODEL: PRIUS'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,PRIUS,ICONIC,HATCHBACK,GCC,4.0,WHITE,JAPAN,1200.0,5.0
1,TOYOTA,PRIUS,ICONIC,HATCHBACK,GCC,4.0,WHITE,JAPAN,1200.0,5.0
2,TOYOTA,PRIUS,STD,HATCHBACK,GCC,4.0,BLACK,JAPAN,1200.0,5.0
3,TOYOTA,PRIUS,STD,HATCHBACK,GCC,4.0,BLACK,JAPAN,1300.0,5.0
4,TOYOTA,PRIUS,STD,HATCHBACK,GCC,4.0,SILVER,JAPAN,1200.0,5.0
...,...,...,...,...,...,...,...,...,...,...
1545,TOYOTA,PRIUS,ICONIC,SEDAN,GCC,4.0,GRAY,JAPAN,NaN,5.0
1546,TOYOTA,PRIUS,STD,HATCHBACK,NON-GCC,4.0,RED,JAPAN,NaN,5.0
1547,TOYOTA,PRIUS,ICONIC,HATCHBACK,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,5.0
1548,TOYOTA,PRIUS,ICONIC,SEDAN,GCC,4.0,WHITE,JAPAN,NaN,5.0
1549,TOYOTA,PRIUS,STD,SEDAN,NON-GCC,4.0,SILVER,JAPAN,NaN,5.0

'Rows: 1550'

'\n======================================================================'

'MODEL: RAIZE'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,RAIZE,TURBO G RA,SUV,GCC,3.0,WHITE / BLACK,INDIA,1040.0,5.0
1,TOYOTA,RAIZE,TURBO G RA,SUV,GCC,3.0,BLACK AND SILVER,INDIA,1040.0,5.0
2,TOYOTA,RAIZE,E,SUV,GCC,3.0,BLACK,INDIA,2630.0,5.0
3,TOYOTA,RAIZE,E,SUV,GCC,3.0,NaN,INDIA,3000.0,5.0
4,TOYOTA,RAIZE,TURBO G RA,SUV,GCC,3.0,NaN,INDIA,3000.0,5.0
...,...,...,...,...,...,...,...,...,...,...
824,TOYOTA,RAIZE,TURBO G RA,SUV,GCC,4.0,WHITE/BLACK,INDIA,NaN,5.0
825,TOYOTA,RAIZE,TURBO G RA,SUV,GCC,4.0,BLACK/SILVER,INDIA,NaN,5.0
826,TOYOTA,RAIZE,TURBO G RA,SUV,GCC,4.0,WHITE/BLACK,INDIA,NaN,5.0
827,TOYOTA,RAIZE,TURBO G RA,SUV,GCC,4.0,BLUE,INDIA,NaN,5.0
828,TOYOTA,RAIZE,TURBO G RA,SUV,GCC,4.0,WHITE/BLACK,INDIA,NaN,5.0

'Rows: 829'

'\n======================================================================'

'MODEL: RAV4'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,RAV4,FABRIC,SUV,GCC,4.0,RED,JAPAN,900.0,5.0
1,TOYOTA,RAV4,STD,SUV,GCC,6.0,WHITE,JAPAN,NaN,5.0
2,TOYOTA,RAV4,GXR,SUV,GCC,4.0,PLATINUM BRONZE,JAPAN,1498.0,5.0
3,TOYOTA,RAV4,LE HEV,SUV,GCC,4.0,GRAY AND BLACK,CANADA,1590.0,5.0
4,TOYOTA,RAV4,EX,SUV,GCC,4.0,BLACK,JAPAN,1540.0,5.0
...,...,...,...,...,...,...,...,...,...,...
11979,TOYOTA,RAV4,LE HEV,SUV,NON-GCC,4.0,BLACK,CANADA,NaN,5.0
11980,TOYOTA,RAV4,EX,SUV,GCC,4.0,SILVER,JAPAN,NaN,5.0
11981,TOYOTA,RAV4,NaN,SUV,NON-GCC,4.0,WHITE,JAPAN,NaN,5.0
11982,TOYOTA,RAV4,VXR,SUV,GCC,4.0,WHITE,JAPAN,NaN,5.0
11983,TOYOTA,RAV4,EX,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,5.0

'Rows: 11984'

'\n======================================================================'

'MODEL: RUMION'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,RUMION,STD,MPV,GCC,4.0,WHITE,JAPAN,1600.0,7.0
1,TOYOTA,RUMION,STD,MPV,GCC,4.0,WHITE,JAPAN,2000.0,7.0

'Rows: 2'

'\n======================================================================'

'MODEL: RUSH'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,RUSH,EX,SUV,GCC,4.0,WHITE,INDIA,1500.0,7.0
1,TOYOTA,RUSH,EX,SUV,GCC,4.0,WHITE,INDIA,1600.0,7.0
2,TOYOTA,RUSH,EX,SUV,GCC,4.0,WHITE,INDIA,1300.0,7.0
3,TOYOTA,RUSH,EX,SUV,GCC,4.0,RED,INDIA,1450.0,7.0
4,TOYOTA,RUSH,EX,SUV,GCC,4.0,WHITE,INDIA,1800.0,7.0
...,...,...,...,...,...,...,...,...,...,...
2404,TOYOTA,RUSH,GX,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
2405,TOYOTA,RUSH,GX,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
2406,TOYOTA,RUSH,EX,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
2407,TOYOTA,RUSH,GX,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
2408,TOYOTA,RUSH,EX,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0

'Rows: 2409'

'\n======================================================================'

'MODEL: SCION'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,SCION,STD,SEDAN,GCC,4.0,SILVER,MEXICO,1350.0,5.0
1,TOYOTA,SCION,STD,SEDAN,NON-GCC,4.0,WHITE,JAPAN,1200.0,5.0
2,TOYOTA,SCION,STD,SEDAN,GCC,4.0,BLUE,MEXICO,100.0,5.0
3,TOYOTA,SCION,OTHER,HATCHBACK,GCC,4.0,SILVER,JAPAN,1000.0,5.0
4,TOYOTA,SCION,OTHER,HATCHBACK,GCC,4.0,BLACK,JAPAN,1200.0,5.0
5,TOYOTA,SCION,NaN,COUPE,GCC,4.0,BLUE,JAPAN,850.0,4.0
6,TOYOTA,SCION,STD,SEDAN,GCC,4.0,RED,JAPAN,950.0,5.0
7,TOYOTA,SCION,STD,SEDAN,GCC,4.0,GREY,MEXICO,1520.0,5.0
8,TOYOTA,SCION,OTHER,COUPE,GCC,0.0,MAROON,JAPAN,1500.0,4.0
9,TOYOTA,SCION,STD,SEDAN,GCC,4.0,SILVER,GERMANY,1000.0,5.0
10,TOYOTA,SCION,STD,WAGON,GCC,4.0,BLACK,JAPAN,1600.0,5.0
11,TOYOTA,SCION,STD,SEDAN,GCC,4.0,GRAY AND BLACK,JAPAN,1210.0,5.0
12,TOYOTA,SCION,STD,SEDAN,GCC,4.0,SILVER,JAPAN,1450.0,5.0
13,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,BLUE,JAPAN,1456.0,5.0
14,TOYOTA,SCION,S,COUPE,GCC,4.0,GRAY AND BLACK,JAPAN,850.0,4.0
15,TOYOTA,SCION,STD,SEDAN,GCC,4.0,GREY,MEXICO,1200.0,5.0
16,TOYOTA,SCION,OTHER,COUPE,GCC,4.0,BLACK,JAPAN,1100.0,4.0
17,TOYOTA,SCION,STD,SEDAN,GCC,4.0,WHITE AND BLUE,JAPAN,1250.0,5.0
18,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,BLACK,JAPAN,1250.0,5.0
19,TOYOTA,SCION,STD,SEDAN,GCC,4.0,SILVER,MEXICO,1100.0,5.0
20,TOYOTA,SCION,STD,SEDAN,GCC,4.0,GREEN,JAPAN,1100.0,5.0
21,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,SILVER,JAPAN,1400.0,5.0
22,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,GREEN / SILVER,JAPAN,1200.0,5.0
23,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,PEARL WHITE,JAPAN,1100.0,5.0
24,TOYOTA,SCION,STD,SEDAN,GCC,4.0,BLACK,JAPAN,NaN,5.0
25,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,WHITE,JAPAN,1300.0,5.0
26,TOYOTA,SCION,STD,SEDAN,GCC,4.0,BLUE,MEXICO,1100.0,5.0
27,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,WHITE,JAPAN,1300.0,5.0
28,TOYOTA,SCION,STD,SEDAN,GCC,4.0,BLACK,JAPAN,NaN,5.0
29,TOYOTA,SCION,STD,SEDAN,GCC,4.0,BLACK,JAPAN,1200.0,5.0
30,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,BLACK,JAPAN,NaN,21.0
31,TOYOTA,SCION,STD,SEDAN,GCC,4.0,BLACK,MEXICO,1520.0,5.0
32,TOYOTA,SCION,STD,SEDAN,GCC,4.0,SILVER,JAPAN,1100.0,5.0
33,TOYOTA,SCION,LE,HATCHBACK,GCC,4.0,GOLDEN,JAPAN,1328.0,5.0
34,TOYOTA,SCION,STD,SEDAN,GCC,4.0,GRAY AND BLACK,MEXICO,1600.0,5.0
35,TOYOTA,SCION,STD,SEDAN,GCC,4.0,SILVER,MEXICO,1200.0,5.0
36,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,BLACK,JAPAN,1200.0,5.0
37,TOYOTA,SCION,OTHER,COUPE,GCC,4.0,BLACK,JAPAN,1200.0,4.0
38,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,BLUE,JAPAN,1100.0,5.0
39,TOYOTA,SCION,STD,COUPE,GCC,4.0,BLACK,JAPAN,965.0,4.0
40,TOYOTA,SCION,STD,HATCHBACK,NON-GCC,4.0,NaN,JAPAN,3000.0,5.0
41,TOYOTA,SCION,STD,HATCHBACK,NON-GCC,4.0,NaN,JAPAN,3000.0,5.0
42,TOYOTA,SCION,STD,SEDAN,GCC,4.0,GREY,MEXICO,1520.0,5.0
43,TOYOTA,SCION,STD,SEDAN,GCC,4.0,BLUE,JAPAN,1254.0,5.0
44,TOYOTA,SCION,STD,HATCHBACK,GCC,4.0,GRAY AND BLACK,JAPAN,1968.0,5.0
45,TOYOTA,SCION,BASE,HATCHBACK,GCC,4.0,BLACK,JAPAN,900.0,4.0

'Rows: 46'

'\n======================================================================'

'MODEL: SEQUOIA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,SEQUOIA,SR5,SUV,GCC,8.0,WHITE,USA,1810.0,8.0
1,TOYOTA,SEQUOIA,SR5,SUV,GCC,8.0,WHITE,USA,2000.0,8.0
2,TOYOTA,SEQUOIA,SR5,SUV,GCC,8.0,SILVER,USA,2001.0,8.0
3,TOYOTA,SEQUOIA,SR5,SUV,GCC,8.0,WHITE,USA,2000.0,8.0
4,TOYOTA,SEQUOIA,LIMITED MID,SUV,GCC,8.0,WHITE,USA,2000.0,8.0
...,...,...,...,...,...,...,...,...,...,...
1046,TOYOTA,SEQUOIA,PLATINUM,SUV,NON-GCC,8.0,WHITE,USA,NaN,8.0
1047,TOYOTA,SEQUOIA,LIMITED,SUV,GCC,8.0,WHITE/PEARLS,USA,NaN,8.0
1048,TOYOTA,SEQUOIA,SR5,SUV,GCC,8.0,WHITE/PEARLS,USA,NaN,7.0
1049,TOYOTA,SEQUOIA,SR5,SUV,GCC,8.0,BLACK,USA,NaN,8.0
1050,TOYOTA,SEQUOIA,LIMITED MID,SUV,GCC,8.0,BEIGE,USA,NaN,8.0

'Rows: 1051'

'\n======================================================================'

'MODEL: SIENNA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,SIENNA,LE (NON GCC),MPV,NON-GCC,6.0,SILVER,USA,1800.0,8.0
1,TOYOTA,SIENNA,LE (NON GCC),MPV,GCC,6.0,WHITE,USA,1500.0,7.0
2,TOYOTA,SIENNA,XLE (NON GCC),MPV,GCC,6.0,GOLDEN,USA,2000.0,8.0
3,TOYOTA,SIENNA,XLE (NON GCC),MPV,GCC,6.0,SILVER,USA,2150.0,7.0
4,TOYOTA,SIENNA,LE (NON GCC),MPV,GCC,6.0,WHITE,USA,1409.0,8.0
...,...,...,...,...,...,...,...,...,...,...
6836,TOYOTA,SIENNA,LE (NON GCC),SUV,NON-GCC,6.0,GRAY,USA,NaN,7.0
6837,TOYOTA,SIENNA,CE (NON GCC),SUV,NON-GCC,6.0,GRAY,USA,NaN,7.0
6838,TOYOTA,SIENNA,CE (NON GCC),SUV,NON-GCC,6.0,GOLDEN,USA,NaN,7.0
6839,TOYOTA,SIENNA,NaN,SUV,NON-GCC,6.0,WHITE,USA,NaN,8.0
6840,TOYOTA,SIENNA,LE (NON GCC),SUV,NON-GCC,6.0,GRAY,USA,NaN,8.0

'Rows: 6841'

'\n======================================================================'

'MODEL: SUPRA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,SUPRA,GR,COUPE,GCC,6.0,WHITE,GERMANY,1600.0,2.0
1,TOYOTA,SUPRA,GR,COUPE,GCC,6.0,GREY,GERMANY,1600.0,2.0
2,TOYOTA,SUPRA,GR,COUPE,GCC,6.0,GREY,GERMANY,1580.0,2.0
3,TOYOTA,SUPRA,GR,COUPE,GCC,6.0,WHITE,GERMANY,1600.0,2.0
4,TOYOTA,SUPRA,GR,COUPE,GCC,6.0,RED,GERMANY,1570.0,2.0
...,...,...,...,...,...,...,...,...,...,...
214,TOYOTA,SUPRA,GR,COUPE,GCC,6.0,RED,GERMANY,NaN,2.0
215,TOYOTA,SUPRA,NaN,COUPE,NON-GCC,6.0,BLUE,JAPAN,NaN,4.0
216,TOYOTA,SUPRA,GR,COUPE,GCC,6.0,WHITE/BLACK,GERMANY,NaN,2.0
217,TOYOTA,SUPRA,GR,COUPE,GCC,6.0,GRAY,GERMANY,NaN,2.0
218,TOYOTA,SUPRA,NaN,COUPE,GCC,6.0,GRAY,GERMANY,NaN,2.0

'Rows: 219'

'\n======================================================================'

'MODEL: T100'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,T100,STANDARD,PICKUP,GCC,4.0,RED,JAPAN,1600.0,3.0
1,TOYOTA,T100,NaN,PICKUP,GCC,4.0,WHITE,JAPAN,1650.0,3.0

'Rows: 2'

'\n======================================================================'

'MODEL: TACOMA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,TACOMA,SR5,PICKUP DOUBLE CAB,GCC,6.0,GOLDEN,USA,1200.0,5.0
1,TOYOTA,TACOMA,STD,PICKUP,GCC,6.0,SILVER,USA,1500.0,5.0
2,TOYOTA,TACOMA,SR5,PICKUP DOUBLE CAB,GCC,6.0,GRAY AND BLACK,MEXICO,1690.0,5.0
3,TOYOTA,TACOMA,SR5,PICKUP DOUBLE CAB,GCC,6.0,GREY,USA,2850.0,5.0
4,TOYOTA,TACOMA,SR5,PICKUP DOUBLE CAB,GCC,6.0,BLACK,USA,1600.0,5.0
...,...,...,...,...,...,...,...,...,...,...
473,TOYOTA,TACOMA,SR5,PICKUP,NON-GCC,6.0,SILVER,MEXICO,NaN,5.0
474,TOYOTA,TACOMA,STD,PICKUP,NON-GCC,4.0,WHITE,USA,NaN,3.0
475,TOYOTA,TACOMA,STD,PICKUP,GCC,6.0,GRAY,USA,NaN,4.0
476,TOYOTA,TACOMA,SR5,PICKUP,NON-GCC,6.0,SILVER,MEXICO,NaN,5.0
477,TOYOTA,TACOMA,SR5,PICKUP,NON-GCC,6.0,GRAY,MEXICO,NaN,5.0

'Rows: 478'

'\n======================================================================'

'MODEL: TERCEL'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,WHITE,JAPAN,1000.0,5.0
1,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,MAROON,JAPAN,1100.0,5.0
2,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,SILVER,JAPAN,1000.0,5.0
3,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,SILVER,JAPAN,1600.0,5.0
4,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,BLACK,JAPAN,1000.0,5.0
...,...,...,...,...,...,...,...,...,...,...
79,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,GREEN,JAPAN,1046.0,5.0
80,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,WHITE,JAPAN,53333.0,5.0
81,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,WHITE,JAPAN,NaN,5.0
82,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,GREEN,JAPAN,NaN,5.0
83,TOYOTA,TERCEL,STD,SEDAN,GCC,4.0,RED,JAPAN,NaN,5.0

'Rows: 84'

'\n======================================================================'

'MODEL: TUNDRA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,TUNDRA,STD,PICKUP DOUBLE CAB,GCC,8.0,WHITE,USA,2000.0,2.0
1,TOYOTA,TUNDRA,STD,PICKUP DOUBLE CAB,GCC,8.0,GREY,USA,2000.0,5.0
2,TOYOTA,TUNDRA,STD,PICKUP DOUBLE CAB,GCC,8.0,WHITE,USA,2000.0,5.0
3,TOYOTA,TUNDRA,STD,PICKUP DOUBLE CAB,GCC,8.0,GRAY AND BLACK,USA,2242.0,5.0
4,TOYOTA,TUNDRA,STD,PICKUP DOUBLE CAB,GCC,8.0,WHITE,USA,1500.0,5.0
...,...,...,...,...,...,...,...,...,...,...
4334,TOYOTA,TUNDRA,STD,PICKUP,NON-GCC,8.0,WHITE/BLACK,USA,NaN,5.0
4335,TOYOTA,TUNDRA,STD,PICKUP,NON-GCC,8.0,WHITE,USA,NaN,6.0
4336,TOYOTA,TUNDRA,STD,PICKUP,NON-GCC,8.0,BLACK,USA,NaN,5.0
4337,TOYOTA,TUNDRA,OTHER,PICKUP,NON-GCC,6.0,GREEN,USA,NaN,5.0
4338,TOYOTA,TUNDRA,STD,PICKUP,NON-GCC,8.0,WHITE,USA,NaN,5.0

'Rows: 4339'

'\n======================================================================'

'MODEL: URBAN CRUISER'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,URBAN CRUISER,GL,SUV,GCC,4.0,NaN,INDIA,3000.0,5.0
1,TOYOTA,URBAN CRUISER,GLX,SUV,GCC,4.0,WHITE & BLACK,INDIA,2400.0,5.0
2,TOYOTA,URBAN CRUISER,GLX,SUV,GCC,4.0,NaN,INDIA,3000.0,5.0
3,TOYOTA,URBAN CRUISER,GLX,SUV,GCC,4.0,WHITE / BLACK,INDIA,1205.0,5.0
4,TOYOTA,URBAN CRUISER,GL,SUV,GCC,4.0,WHITE / BLACK,INDIA,1700.0,5.0
...,...,...,...,...,...,...,...,...,...,...
546,TOYOTA,URBAN CRUISER,GLX,SUV,GCC,4.0,WHITE/BLACK,INDIA,NaN,5.0
547,TOYOTA,URBAN CRUISER,GLX,SUV,GCC,4.0,SILVER,INDIA,NaN,5.0
548,TOYOTA,URBAN CRUISER,GLX,SUV,GCC,4.0,BLACK/SILVER,INDIA,NaN,5.0
549,TOYOTA,URBAN CRUISER,GL,SUV,GCC,4.0,WHITE/BLACK,INDIA,NaN,5.0
550,TOYOTA,URBAN CRUISER,GLX,SUV,GCC,4.0,BLACK/SILVER,INDIA,NaN,5.0

'Rows: 551'

'\n======================================================================'

'MODEL: VELOZ'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,VELOZ,GX,SUV,GCC,4.0,NaN,INDIA,3000.0,5.0
1,TOYOTA,VELOZ,GX,SUV,GCC,4.0,WHITE PEARL,INDIA,1195.0,6.0
2,TOYOTA,VELOZ,GX,SUV,GCC,4.0,WHITE PEARL,INDIA,1195.0,7.0
3,TOYOTA,VELOZ,GX,SUV,GCC,4.0,PEARL WHITE,INDIA,1195.0,8.0
4,TOYOTA,VELOZ,GX,SUV,GCC,4.0,GREY,INDIA,1195.0,7.0
...,...,...,...,...,...,...,...,...,...,...
601,TOYOTA,VELOZ,GX,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
602,TOYOTA,VELOZ,GX,SUV,GCC,4.0,SILVER,INDIA,NaN,7.0
603,TOYOTA,VELOZ,GX,SUV,GCC,4.0,SILVER,INDIA,NaN,5.0
604,TOYOTA,VELOZ,GX,SUV,GCC,4.0,WHITE,INDIA,NaN,7.0
605,TOYOTA,VELOZ,GX,SUV,NON-GCC,4.0,WHITE/PEARLS,INDIA,NaN,7.0

'Rows: 606'

'\n======================================================================'

'MODEL: VENZA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,VENZA,STD,WAGON,GCC,6.0,BLACK,USA,1900.0,5.0
1,TOYOTA,VENZA,STD,SUV,GCC,4.0,GRAY AND BLACK,USA,1600.0,5.0
2,TOYOTA,VENZA,STD,SUV,GCC,6.0,BROWN,USA,1600.0,5.0
3,TOYOTA,VENZA,OTHER,WAGON,GCC,4.0,RED,USA,2000.0,5.0

'Rows: 4'

'\n======================================================================'

'MODEL: VIOS'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,VIOS,STD,SEDAN,GCC,4.0,WHITE,INDIA,1168.0,5.0

'Rows: 1'

'\n======================================================================'

'MODEL: WIGO'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,WIGO,S,HATCHBACK,GCC,4.0,RED,INDIA,1400.0,5.0

'Rows: 1'

'\n======================================================================'

'MODEL: WISH'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,WISH,STD,HATCHBACK,GCC,0.0,BLACK,ITALY,1500.0,7.0
1,TOYOTA,WISH,OTHER,WAGON,GCC,0.0,WHITE,ITALY,NaN,7.0
2,TOYOTA,WISH,OTHER,MPV,GCC,4.0,SILVER,JAPAN,NaN,7.0

'Rows: 3'

'\n======================================================================'

'MODEL: XA'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,WHITE PEARL,JAPAN,1100.0,5.0
1,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,GREEN AND BLACK,JAPAN,1300.0,5.0
2,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,SILVER,JAPAN,1100.0,5.0
3,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,BLUE,JAPAN,1100.0,5.0
4,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,GREEN,JAPAN,1100.0,5.0
...,...,...,...,...,...,...,...,...,...,...
535,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,BLUE,JAPAN,NaN,5.0
536,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,5.0
537,TOYOTA,XA,BASE,HATCHBACK,NON-GCC,4.0,WHITE,JAPAN,NaN,5.0
538,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,SILVER,JAPAN,NaN,5.0
539,TOYOTA,XA,BASE,HATCHBACK,GCC,4.0,WHITE,JAPAN,NaN,5.0

'Rows: 540'

'\n======================================================================'

'MODEL: YARIS'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,YARIS,MID,HATCHBACK,GCC,4.0,WHITE,JAPAN,NaN,5.0
1,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,INDIA,NaN,5.0
2,TOYOTA,YARIS,FLEET,SEDAN,GCC,4.0,SILVER,JAPAN,1000.0,5.0
3,TOYOTA,YARIS,SE,HATCHBACK,GCC,4.0,WHITE,INDIA,1100.0,5.0
4,TOYOTA,YARIS,SE,SEDAN,GCC,4.0,NaN,INDIA,3000.0,5.0
...,...,...,...,...,...,...,...,...,...,...
23243,TOYOTA,YARIS,MID,HATCHBACK,GCC,4.0,PEARLS,JAPAN,NaN,5.0
23244,TOYOTA,YARIS,BASE,HATCHBACK,GCC,4.0,BLACK,JAPAN,NaN,5.0
23245,TOYOTA,YARIS,SE,HATCHBACK,GCC,4.0,WHITE,INDIA,NaN,5.0
23246,TOYOTA,YARIS,SE,HATCHBACK,NON-GCC,4.0,BLACK,FRANCE,NaN,5.0
23247,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,INDIA,NaN,5.0

'Rows: 23248'

'\n======================================================================'

'MODEL: ZELAS'

,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,TOYOTA,ZELAS,MID,COUPE,GCC,4.0,WHITE,JAPAN,1080.0,5.0
1,TOYOTA,ZELAS,SPORT,COUPE,GCC,4.0,GREY,JAPAN,1459.0,5.0
2,TOYOTA,ZELAS,MID,COUPE,GCC,4.0,BLACK AND SILVER,JAPAN,1200.0,5.0
3,TOYOTA,ZELAS,SPORT,COUPE,GCC,4.0,GRAY AND BLACK,JAPAN,1499.0,5.0
4,TOYOTA,ZELAS,SPORT,COUPE,GCC,4.0,SILVER,JAPAN,1200.0,5.0
...,...,...,...,...,...,...,...,...,...,...
87,TOYOTA,ZELAS,SPORT,COUPE,GCC,4.0,SILVER,JAPAN,1223.0,5.0
88,TOYOTA,ZELAS,SPORT,COUPE,GCC,4.0,BLACK,JAPAN,NaN,5.0
89,TOYOTA,ZELAS,MID,COUPE,GCC,4.0,MAROON,JAPAN,NaN,5.0
90,TOYOTA,ZELAS,STD,HATCHBACK,GCC,4.0,GRAY,JAPAN,NaN,5.0
91,TOYOTA,ZELAS,MID,COUPE,GCC,4.0,BLUE,JAPAN,NaN,5.0

'Rows: 92'

In [ ]:
data_new