In [2]:
import pandas as pd

In [3]:
data = pd.read_csv(r'../Data/toyota_valuation.csv')
data

,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,1000.0,5.0
1,2015.0,TOYOTA,HIACE,GLX,MINI BUS,GCC,4.0,WHITE,JAPAN,2000.0,2.0
2,2015.0,TOYOTA,HIACE,DX,MINI BUS,GCC,4.0,WHITE,JAPAN,1837.0,15.0
3,2015.0,TOYOTA,HILUX,DL,PICKUP DOUBLE CAB,GCC,4.0,WHITE,JAPAN,1837.0,5.0
4,2001.0,TOYOTA,CAMRY,XLI,SEDAN,NON-GCC,4.0,BROWN AND BEIGE,USA,1481.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
239209,2019.0,TOYOTA,HILUX,GLX,PICKUP,GCC,6.0,WHITE/PEARLS,INDIA,NaN,5.0
239210,2025.0,TOYOTA,LAND CRUISER,NaN,SUV,GCC,6.0,BLACK,JAPAN,NaN,7.0
239211,2021.0,TOYOTA,LAND CRUISER,GXR,SUV,GCC,8.0,WHITE/PEARLS,JAPAN,NaN,8.0
239212,2025.0,TOYOTA,LAND CRUISER,GXL,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,7.0
239213,2021.0,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,INDIA,NaN,5.0

In [4]:
print(data['model'].unique())

['COROLLA' 'HIACE' 'HILUX' 'CAMRY' 'LAND CRUISER' 'YARIS' 'FJ CRUISER'
 'RAV4' 'TUNDRA' 'AVALON' 'FORTUNER' 'COASTER' 'INNOVA' 'SIENNA' 'TACOMA'
 'RUSH' 'PRIUS' 'AVANZA' 'SEQUOIA' 'SUPRA' 'AURION' 'ECHO' 'PREVIA' 'BZ4X'
 'C-HR' 'XA' 'GRANVIA' 'VELOZ' 'RAIZE' 'IQ' 'FJ' 'CROWN' '86' '4RUNNER'
 'URBAN CRUISER' 'SCION' 'HIGHLANDER' 'OTHERS' 'DYNA' 'LAND CRUISE'
 'TERCEL' 'LITEACE' 'MATRIX' 'RAV 4' 'GR86' 'LEVIN' 'ZELAS' 'ALPHARD'
 'TOYOTA VELOZ' 'T 300' '4 RUNNER' 'CRESSIDA' 'CROWN KLUGER' nan 'TAKOMA'
 'TOYOTA PRIUS' 'TOYOTA ALTIS' 'ALTIS' 'استیشن' 'BZ3X'
 'بيك اب كابينه مزدوجه' '26HX DC 4X4P2.7LAT' 'SALOON' 'PICK UP' 'RUMION'
 'MR2' 'TOYOTA' 'WISH' '25 LP SC4X44.0L MT' 'TANDRA' 'BZ 4' 'STATION'
 'HAI LUX' 'VENZA' '25 HX DC 4X4D 2.4LAT' 'TOKOMA' '25 LP SC 4X4 P4.0 MT'
 'CELICA' 'T 100' 'حافلة نقل خاص' '25 HX DC 4X4 2.7LAT' 'GLX DA (PICK UP)'
 'RUNNER' 'ALLION' 'VIOS' 'TOYOTA SCION' 'TOYOTA 4RUNNER' 'TOYOTA IQ'
 'PICK UP CABIN' 'TOYOTA SUPRA' '2 HX DC 4X40' 'FRONTLANDER'
 '25 CA SON P 2.5L AT' '25 HX DC 4X4P 2.7LAT' 'GLX RA (PICK UP)' 'CORONA'
 '26 YA HB P 1.6L AT TURBO GR RA(CAR)' '26HX DC 4X4D2.4L AT' 'SIENA'
 '26 HX DC 4X4 2.4LAT' '26HX DC 4X4 D2.4LAT' 'CHR'
 '25 HX DC 4X2 P 27L AT GLX RA/PICK UP' 'GXL RA (STATION WAGON)'
 '25PR 5 DR P 2.4L AT' '26HX DC 4X4 PLAT' '2 HX DC 4X4 P 2.7LAT'
 '26 HX DC 4X4 D 2.4L AT' '25 HX DC 4X4 P .LAT'
 'TOYOTA - 26 HX DC 4X4 D 2.4L AT' '25 HX DC 4X4' 'DLX FA (PICK UP)'
 '26 HX DC 4X4 P 2.7LAT' 'WIGO' 'T100' 'كورولا' 'TAKOMA PICK UP CARGO'
 'HX DC 4X4 D 2.4L AT' '26 HX DC 4X4D' '25 HX DC 4X4 PLAT GLX RA(PICK UP)'
 'TANDRA PICK UP DOUBLE CABIN' 'H 530' 'CROWN V' 'VAN' 'PICKUP'
 'TOYOTA RUSH' 'MIRAI' 'HI ACE' '26 LP SC 4X4 P4.0L AT' 'COUPE'
 'GXR RA(STATION WAGON)' 'TOYOTA 86']

In [5]:
print(data['model'].nunique())

131

In [6]:
print(data['trim'].unique())

['SE' 'GLX' 'DX' 'DL' 'XLI' 'VX' 'MID' 'DLX' 'VXR' 'FABRIC' 'E' 'TOP'
 'EXTREME' 'GL' 'BASE' 'S' 'FLEET' 'STD' 'GXR' 'EXR' 'GL2' 'SR5' 'LE'
 'LE (NON GCC)' 'GLI' 'TX' 'LIMITED' 'XLE (NON GCC)' 'EX' 'ICONIC'
 'VX MID' 'LE HEV' 'SGLX' 'PW CL' 'GX' 'XLE' 'SPORT' 'G' 'GRANDE' 'GR'
 'S TRD SPORT PK' 'S+' 'PRO' 'GLE' 'GLS' 'PLATINUM' 'DLX TOP' 'TURBO G RA'
 'VXR HEV' 'GLE HEV' 'SAFARI' 'LX' 'CE (NON GCC)' 'GLI HEV' 'PREMIUM' 'XL'
 'LX AC PWR OPT' 'LX WINCH' 'TX-L' 'XLE TOURING' 'DLS' 'OTHER'
 'GLE-X HEV 40TH ANNIV' nan 'ADVENTURE' 'CREWMAX CAPSTONE (NON GCC)'
 'LIMITED MID' 'TX-L TOP' 'EXCLUSIVE' 'XSE (NON GCC)' 'BLACK EDITION'
 'DX H/R W/B' 'C (NON GCC)' 'GLX SPORT Z' 'S PLUS' 'VTX' 'GXL' 'HT SWB'
 'ECO' 'GX MID' 'LWB HIGH ROOF' '1794 EDITION (NON GCC)'
 '40TH ANNIVERSARY EDITION' 'TOURING' 'HEV' 'PS PW CL' 'GR SPORT' 'LWB'
 'EXR HEV' 'BE' 'GT' 'SWB' 'SR' 'GTX' 'VX2' 'STANDARD' 'VX1' 'DYNAMIC'
 'FJ STD' 'YX' 'STD AC' 'GLE HEV BLACK EDITION' 'Y PLUS' 'XTREME'
 'HARD TOP' 'HYBRID (NON GCC)' 'TRD SPORT']

In [7]:
data = data.loc[data['make'].map(data['make'].value_counts()).sort_values(ascending=False).index]

In [8]:
data

,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,1000.0,5.0
1,2015.0,TOYOTA,HIACE,GLX,MINI BUS,GCC,4.0,WHITE,JAPAN,2000.0,2.0
2,2015.0,TOYOTA,HIACE,DX,MINI BUS,GCC,4.0,WHITE,JAPAN,1837.0,15.0
3,2015.0,TOYOTA,HILUX,DL,PICKUP DOUBLE CAB,GCC,4.0,WHITE,JAPAN,1837.0,5.0
4,2001.0,TOYOTA,CAMRY,XLI,SEDAN,NON-GCC,4.0,BROWN AND BEIGE,USA,1481.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
239209,2019.0,TOYOTA,HILUX,GLX,PICKUP,GCC,6.0,WHITE/PEARLS,INDIA,NaN,5.0
239210,2025.0,TOYOTA,LAND CRUISER,NaN,SUV,GCC,6.0,BLACK,JAPAN,NaN,7.0
239211,2021.0,TOYOTA,LAND CRUISER,GXR,SUV,GCC,8.0,WHITE/PEARLS,JAPAN,NaN,8.0
239212,2025.0,TOYOTA,LAND CRUISER,GXL,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,7.0
239213,2021.0,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,INDIA,NaN,5.0