In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = pd.read_csv(r"../data/data_methaq(2.0).csv")

for col in data.columns:
    if data[col].dtype == "object":
        data[col] = [x.upper() if isinstance(x, str) else x for x in data[col]]

print(data.head())

       chassisNumber    year    make    model trim            bodyType  \
0  RKLBB9HE7F5115863  2015.0  TOYOTA  COROLLA   SE               SEDAN
1  JTFHX02POF0099797  2015.0  TOYOTA    HIACE  GLX  MINI BUS HIGH ROOF
2  JTFHX02P7F0094323  2015.0  TOYOTA    HIACE   DX  MINI BUS HIGH ROOF
3  JTFHXDGP7F0094373  2015.0  TOYOTA    HILUX   DL  PICK UP DOUBLE CAB
4  4T1BG22K01U789089  2001.0  TOYOTA    CAMRY  XLI               SEDAN

  regionalSpec  cylinders            color  origin  weightInKg  noOfPassengers
0          GCC        4.0           SILVER  TAIWAN      1000.0             5.0
1          GCC        4.0            WHITE   JAPAN      2000.0             2.0
2          GCC        4.0            WHITE   JAPAN      1837.0            15.0
3          GCC        4.0            WHITE   JAPAN      1837.0             5.0
4      NON-GCC        4.0  BROWN AND BEIGE   JAPAN      1481.0             5.0

In [3]:
data = data[data["make"] == "TOYOTA"]
data

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,RKLBB9HE7F5115863,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,1000.0,5.0
1,JTFHX02POF0099797,2015.0,TOYOTA,HIACE,GLX,MINI BUS HIGH ROOF,GCC,4.0,WHITE,JAPAN,2000.0,2.0
2,JTFHX02P7F0094323,2015.0,TOYOTA,HIACE,DX,MINI BUS HIGH ROOF,GCC,4.0,WHITE,JAPAN,1837.0,15.0
3,JTFHXDGP7F0094373,2015.0,TOYOTA,HILUX,DL,PICK UP DOUBLE CAB,GCC,4.0,WHITE,JAPAN,1837.0,5.0
4,4T1BG22K01U789089,2001.0,TOYOTA,CAMRY,XLI,SEDAN,NON-GCC,4.0,BROWN AND BEIGE,JAPAN,1481.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,2019.0,TOYOTA,HILUX,GLX,PICKUP,GCC,6.0,WHITE/PEARLS,NaN,NaN,5.0
922351,JTMABBBJ6S4188504,2025.0,TOYOTA,LAND CRUISER,1,SUV,GCC,6.0,BLACK,NaN,NaN,7.0
922352,JTMHX01J3M4222343,2021.0,TOYOTA,LAND CRUISER,GXR,SUV,GCC,8.0,WHITE/PEARLS,NaN,NaN,8.0
922353,JTEAACAJ1S5008118,2025.0,TOYOTA,LAND CRUISER PRADO,GXL,SUV,GCC,4.0,WHITE/PEARLS,NaN,NaN,7.0
922354,MHFB29F34M2123579,2021.0,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,NaN,NaN,5.0

In [4]:
data["chassis_len"] = data["chassisNumber"].str.len()
data["pos10"] = data["chassisNumber"].str[9]

is_standard = (data["chassis_len"] == 17) & (~data["pos10"].isin(['I', 'O', 'Q', 'U', 'Z', '0']))
data = data[is_standard]
data

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,chassis_len,pos10
0,RKLBB9HE7F5115863,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,1000.0,5.0,17,F
1,JTFHX02POF0099797,2015.0,TOYOTA,HIACE,GLX,MINI BUS HIGH ROOF,GCC,4.0,WHITE,JAPAN,2000.0,2.0,17,F
2,JTFHX02P7F0094323,2015.0,TOYOTA,HIACE,DX,MINI BUS HIGH ROOF,GCC,4.0,WHITE,JAPAN,1837.0,15.0,17,F
3,JTFHXDGP7F0094373,2015.0,TOYOTA,HILUX,DL,PICK UP DOUBLE CAB,GCC,4.0,WHITE,JAPAN,1837.0,5.0,17,F
4,4T1BG22K01U789089,2001.0,TOYOTA,CAMRY,XLI,SEDAN,NON-GCC,4.0,BROWN AND BEIGE,JAPAN,1481.0,5.0,17,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
922350,MR0HU8CDXK0071134,2019.0,TOYOTA,HILUX,GLX,PICKUP,GCC,6.0,WHITE/PEARLS,NaN,NaN,5.0,17,K
922351,JTMABBBJ6S4188504,2025.0,TOYOTA,LAND CRUISER,1,SUV,GCC,6.0,BLACK,NaN,NaN,7.0,17,S
922352,JTMHX01J3M4222343,2021.0,TOYOTA,LAND CRUISER,GXR,SUV,GCC,8.0,WHITE/PEARLS,NaN,NaN,8.0,17,M
922353,JTEAACAJ1S5008118,2025.0,TOYOTA,LAND CRUISER PRADO,GXL,SUV,GCC,4.0,WHITE/PEARLS,NaN,NaN,7.0,17,S
922354,MHFB29F34M2123579,2021.0,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,NaN,NaN,5.0,17,M

In [5]:
# 1. World Manufacturer Identifier (WMI)
data["WMI"] = data["chassisNumber"].str[0:3]
data["pos1"] = data["chassisNumber"].str[0]
data["pos2"] = data["chassisNumber"].str[1]
data["pos3"] = data["chassisNumber"].str[2]

# 2. Vehicle Descriptor Section (VDS)
data["VDS"] = data["chassisNumber"].str[3:9]  # Standard VIN uses positions 4-9 (index 3:9)
data["pos4"] = data["chassisNumber"].str[3]
data["pos5"] = data["chassisNumber"].str[4]
data["pos6"] = data["chassisNumber"].str[5]
data["pos7"] = data["chassisNumber"].str[6]
data["pos8"] = data["chassisNumber"].str[7]
data["pos9"] = data["chassisNumber"].str[8]  # Check Digit

# 3. Vehicle Identifier Section (VIS)
data["VIS"] = data["chassisNumber"].str[9:17]  # Standard VIN uses positions 10-17 (index 9:17)
data["Model_Year"] = data["chassisNumber"].str[9]  # Model Year
data["Plant_Code"] = data["chassisNumber"].str[10]  # Plant Code

# 4. Production Serial Number (Last 6 digits of VIS)
data["Serial_Number"] = data["chassisNumber"].str[11:17]

C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["WMI"] = data["chassisNumber"].str[0:3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos1"] = data["chassisNumber"].str[0]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos2"] = data["chassisNumber"].str[1]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos3"] = data["chassisNumber"].str[2]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["VDS"] = data["chassisNumber"].str[3:9]  # Standard VIN uses positions 4-9 (index 3:9)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos4"] = data["chassisNumber"].str[3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos5"] = data["chassisNumber"].str[4]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos6"] = data["chassisNumber"].str[5]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos7"] = data["chassisNumber"].str[6]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos8"] = data["chassisNumber"].str[7]
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["pos9"] = data["chassisNumber"].str[8]  # Check Digit
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["VIS"] = data["chassisNumber"].str[9:17]  # Standard VIN uses positions 10-17 (index 9:17)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Model_Year"] = data["chassisNumber"].str[9]  # Model Year
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Plant_Code"] = data["chassisNumber"].str[10]  # Plant Code
C:\Users\Admin\AppData\Local\Temp\ipykernel_18300\2869652748.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Serial_Number"] = data["chassisNumber"].str[11:17]

In [6]:
import pandas as pd
import numpy as np

# ==========================================================
# EXACT MODEL MAPPINGS
# ==========================================================
MODEL_MAPPING = {

    # Arabic
    "كامري": "CAMRY",
    "كامرى": "CAMRY",
    "هاي لوكس": "HILUX",
    "هايلوكس": "HILUX",
    "لاند كروزر": "LAND CRUISER",
    "كورولا 1.3": "COROLLA",
    "كورولا 1.8": "COROLLA",
    "برادو": "LAND CRUISER",
    "بريفيا": "PREVIA",
    "افنزا": "AVANZA",
    "تاكوما": "TACOMA",

    # Typos / aliases
    "MR 2": "MR2",
    "SELICA": "CELICA",
    "SICION": "SCION",
    "SQUIN": "SEQUOIA",
    "DAINA": "DYNA",
    "LITE ACE": "LITEACE",
    "FORERUNNER": "4RUNNER",
    "BZ46": "BZ4X",

    # Sienna variants
    "SIENNA VAN": "SIENNA",
    "SIENNA(VAN)": "SIENNA",
    "SENA VAN PASSENGER": "SIENNA",

    # Supra
    "SUPRA COUPE": "SUPRA",

    # Misc
    "1.8 XS": "PRIUS",
    "SOLARA": "CAMRY",
    "DYNA VAN CARGO": "DYNA",
}


# ==========================================================
# INVALID VALUES
# ==========================================================
INVALID_MODELS = {

    # Years
    "2024", "2023", "2022",
    "2016", "2014", "2012",
    "2009", "2008",
    "1999", "1998",
    "MODEL 2022",

    # Missing
    "NAN",
    "",

    # Non-Toyota vehicles
    "JUSTIN BIEBER X VESPA 150 E5 GSO (SCOOTER)",
    "VESPA VXL",
    "VESPA VXL 150",
    "KING LONG PASSENGER",
    "NIO ES8",
    "MT 03",
    "STREET TRIPLE",
    "FLHTK",
    "FLTRXS",
    "GL770ULTRA",
    "SY150T",
    "KS01",
    "U7",
    "900",
    "H3",
    "ORION",
    "SPINA",
    "STANZA",
    "SIERRA",
    "PARISIENNE BROUGHAM",

    # Garbage
    "HD 4X4",
    "GRAND DELUX"
}


# ==========================================================
# KEYWORD NORMALIZATION
# ==========================================================
def keyword_model(x):

    if pd.isna(x):
        return np.nan

    x = str(x).upper().strip()

    if "COROLLA" in x:
        return "COROLLA"

    if "CAMRY" in x or "SOLARA" in x:
        return "CAMRY"

    if "HILUX" in x:
        return "HILUX"

    if "LAND CRUISER" in x or "PRADO" in x:
        return "LAND CRUISER"

    if "HIACE" in x:
        return "HIACE"

    if "YARIS" in x:
        return "YARIS"

    if "RAV4" in x:
        return "RAV4"

    if "TACOMA" in x:
        return "TACOMA"

    if "TUNDRA" in x:
        return "TUNDRA"

    if "SIENNA" in x or "SENA" in x:
        return "SIENNA"

    if "SELICA" in x:
        return "CELICA"

    if "MR 2" in x:
        return "MR2"

    if "LITE ACE" in x:
        return "LITEACE"

    if "SICION" in x:
        return "SCION"

    if "SQUIN" in x:
        return "SEQUOIA"

    if "DAINA" in x:
        return "DYNA"

    if "FORERUNNER" in x:
        return "4RUNNER"

    if "BZ46" in x:
        return "BZ4X"

    return x


# ==========================================================
# CLEAN FUNCTION
# ==========================================================
def clean_model_column(data: pd.DataFrame,
                       model_col: str = "model") -> pd.DataFrame:

    data = data.copy()

    # Normalize text
    data[model_col] = (
        data[model_col]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    # Exact replacements
    data[model_col] = data[model_col].replace(MODEL_MAPPING)

    # Keyword replacements
    data[model_col] = data[model_col].apply(keyword_model)

    # Remove invalid models
    data.loc[
        data[model_col].isin(INVALID_MODELS),
        model_col
    ] = np.nan

    return data


# ==========================================================
# APPLY
# ==========================================================
data = clean_model_column(data, model_col="model")

# Show cleaned models
print(sorted(data["model"].dropna().unique()))

['2 HX DC 4X4 P 2.7LAT', '2 HX DC 4X40', '25 CA SON P 2.5L AT', '25 HX DC 4X2 P 27L AT GLX RA/PICK UP', '25 HX DC 4X4', '25 HX DC 4X4 2.7LAT', '25 HX DC 4X4 P .LAT', '25 HX DC 4X4 PLAT GLX RA(PICK UP)', '25 HX DC 4X4D 2.4LAT', '25 HX DC 4X4P 2.7LAT', '25 LP SC 4X4 P4.0 MT', '25 LP SC4X44.0L MT', '25PR 5 DR P 2.4L AT', '26 HX DC 4X4 2.4LAT', '26 HX DC 4X4 D 2.4L AT', '26 HX DC 4X4 P 2.7LAT', '26 HX DC 4X4D', '26 LP SC 4X4 P4.0L AT', '26 YA HB P 1.6L AT TURBO GR RA(CAR)', '26HX DC 4X4 D2.4LAT', '26HX DC 4X4 PLAT', '26HX DC 4X4D2.4L AT', '26HX DC 4X4P2.7LAT', '4 RUNNER', '4RUNNER', '86', 'ALLION', 'ALPHARD', 'ALTIS', 'AURION', 'AVALON', 'AVANZA', 'BZ 4', 'BZ3X', 'BZ4X', 'C-HR', 'CAMRY', 'CELICA', 'CHR', 'COASTER', 'COROLLA', 'CORONA', 'COUPE', 'CRESSIDA', 'CROWN', 'CROWN KLUGER', 'CROWN V', 'DLX FA (PICK UP)', 'DYNA', 'ECHO', 'FJ', 'FJ CRUISER', 'FORTUNER', 'FRONTLANDER', 'GLX DA (PICK UP)', 'GLX RA (PICK UP)', 'GR86', 'GRANVIA', 'GXL RA (STATION WAGON)', 'GXR RA(STATION WAGON)', 'H 530', 'HAI LUX', 'HI ACE', 'HIACE', 'HIGHLANDER', 'HILUX', 'HX DC 4X4 D 2.4L AT', 'INNOVA', 'IQ', 'LAND CRUISE', 'LAND CRUISER', 'LEVIN', 'LITEACE', 'MATRIX', 'MIRAI', 'MR2', 'OTHERS', 'PICK UP', 'PICK UP CABIN', 'PICKUP', 'PREVIA', 'PRIUS', 'RAIZE', 'RAV 4', 'RAV4', 'RUMION', 'RUNNER', 'RUSH', 'SALOON', 'SCION', 'SEQUOIA', 'SIENA', 'SIENNA', 'STATION', 'SUPRA', 'T 100', 'T 300', 'T100', 'TACOMA', 'TAKOMA', 'TAKOMA PICK UP CARGO', 'TANDRA', 'TANDRA PICK UP DOUBLE CABIN', 'TERCEL', 'TOKOMA', 'TOYOTA', 'TOYOTA - 26 HX DC 4X4 D 2.4L AT', 'TOYOTA 4RUNNER', 'TOYOTA 86', 'TOYOTA ALTIS', 'TOYOTA IQ', 'TOYOTA PRIUS', 'TOYOTA RUSH', 'TOYOTA SCION', 'TOYOTA SUPRA', 'TOYOTA VELOZ', 'TUNDRA', 'URBAN CRUISER', 'VAN', 'VELOZ', 'VENZA', 'VIOS', 'WIGO', 'WISH', 'XA', 'YARIS', 'ZELAS', 'استیشن', 'بيك اب كابينه مزدوجه', 'حافلة نقل خاص', 'كورولا']

In [7]:
print(", ".join(map(str, data['model'].unique())))

COROLLA, HIACE, HILUX, CAMRY, LAND CRUISER, YARIS, FJ CRUISER, RAV4, TUNDRA, AVALON, FORTUNER, COASTER, INNOVA, SIENNA, TACOMA, RUSH, PRIUS, AVANZA, SEQUOIA, SUPRA, AURION, ECHO, PREVIA, BZ4X, C-HR, XA, GRANVIA, VELOZ, RAIZE, IQ, FJ, CROWN, 86, 4RUNNER, URBAN CRUISER, SCION, HIGHLANDER, OTHERS, DYNA, LAND CRUISE, TERCEL, LITEACE, MATRIX, RAV 4, GR86, LEVIN, ZELAS, ALPHARD, TOYOTA VELOZ, T 300, 4 RUNNER, CRESSIDA, CROWN KLUGER, nan, TAKOMA, TOYOTA PRIUS, TOYOTA ALTIS, ALTIS, استیشن, BZ3X, بيك اب كابينه مزدوجه, 26HX DC 4X4P2.7LAT, SALOON, PICK UP, RUMION, MR2, TOYOTA, WISH, 25 LP SC4X44.0L MT, TANDRA, BZ 4, STATION, HAI LUX, VENZA, 25 HX DC 4X4D 2.4LAT, TOKOMA, 25 LP SC 4X4 P4.0 MT, CELICA, T 100, حافلة نقل خاص, 25 HX DC 4X4 2.7LAT, GLX DA (PICK UP), RUNNER, ALLION, VIOS, TOYOTA SCION, TOYOTA 4RUNNER, TOYOTA IQ, PICK UP CABIN, TOYOTA SUPRA, 2 HX DC 4X40, FRONTLANDER, 25 CA SON P 2.5L AT, 25 HX DC 4X4P 2.7LAT, GLX RA (PICK UP), CORONA, 26 YA HB P 1.6L AT TURBO GR RA(CAR), 26HX DC 4X4D2.4L AT, SIENA, 26 HX DC 4X4 2.4LAT, 26HX DC 4X4 D2.4LAT, CHR, 25 HX DC 4X2 P 27L AT GLX RA/PICK UP, GXL RA (STATION WAGON), 25PR 5 DR P 2.4L AT, 26HX DC 4X4 PLAT, 2 HX DC 4X4 P 2.7LAT, 26 HX DC 4X4 D 2.4L AT, 25 HX DC 4X4 P .LAT, TOYOTA - 26 HX DC 4X4 D 2.4L AT, 25 HX DC 4X4, DLX FA (PICK UP), 26 HX DC 4X4 P 2.7LAT, WIGO, T100, كورولا, TAKOMA PICK UP CARGO, HX DC 4X4 D 2.4L AT, 26 HX DC 4X4D, 25 HX DC 4X4 PLAT GLX RA(PICK UP), TANDRA PICK UP DOUBLE CABIN, H 530, CROWN V, VAN, PICKUP, TOYOTA RUSH, MIRAI, HI ACE, 26 LP SC 4X4 P4.0L AT, COUPE, GXR RA(STATION WAGON), TOYOTA 86

In [8]:
print(data['model'].nunique())

131

In [9]:
BODY_TYPE_MAPPING = {
    # Sedan
    "SALOON": "SEDAN",

    # SUV
    "SUV- CROSSOVER": "SUV",

    # Coupe
    "COUPE/CABRIOLET": "COUPE",

    # Wagon
    "ESTATE": "WAGON",
    "STATION": "WAGON",

    # MPV
    "MINIVAN": "MPV",

    # Vans
    "WINDOW VAN": "VAN",
    "PANEL VAN": "VAN",
    "PANEL VAN HIGH ROOF": "VAN",
    "HALF PANEL VAN": "VAN",
    "CARGO VAN": "VAN",
    "CARAVAN": "VAN",

    # Mini Bus
    "MINI BUS HIGH ROOF": "MINI BUS",
    "MINI BUS SEMI HIGH ROOF": "MINI BUS",

    # Pickup General
    "PICK UP": "PICKUP",
    "PICK-UP": "PICKUP",
    "PICKUP TRUCK": "PICKUP",

    # Pickup Single Cab
    "PICK UP SINGLE CAB": "PICKUP SINGLE CAB",
    "PICKUP SINGLE CABIN": "PICKUP SINGLE CAB",

    # Pickup Double Cab
    "PICK UP DOUBLE CAB": "PICKUP DOUBLE CAB",
    "PICK UP DOUBLE CABIN": "PICKUP DOUBLE CAB",
    "PICKUP DOUBLE CABIN": "PICKUP DOUBLE CAB",

    # Truck
    "LIGHT VEHICLE": "TRUCK",
}


def clean_body_type(data: pd.DataFrame,
                    column: str = "bodyType") -> pd.DataFrame:

    data = data.copy()

    data[column] = (
        data[column]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    data[column] = data[column].replace(BODY_TYPE_MAPPING)

    return data


# Apply
data = clean_body_type(data, "bodyType")

print(data["bodyType"].value_counts())

bodyType
SEDAN                108384
SUV                   67920
HATCHBACK             13545
PICKUP DOUBLE CAB     13249
MPV                   12906
PICKUP SINGLE CAB      7998
MINI BUS               6416
VAN                    5437
PICKUP                 1891
COUPE                   647
BUS                     581
WAGON                   194
CONVERTIBLE              24
TRUCK                    10
MOTORCYCLE                9
AMBULANCE                 2
REGULAR CAB               1
Name: count, dtype: int64

In [10]:
print(data['origin'].unique())

['TAIWAN' 'JAPAN' 'THAILAND' 'AUSTRALIA' 'AMERICA' 'UNITED STATES'
 'INDONESIA' 'USA' 'CANADA' 'GERMANY' 'AUSTRIA' 'CHINA' 'TURKEY'
 'UNITED STATES VIRGIN' 'MEXICO' 'REPUBLIC OF TURKIYE' 'SPAIN' 'INDIA'
 'SOUTH KOREA' 'UNITED KINGDOM' 'UAE' nan 'TAHITIAN'
 'UNITED STATES VIRGIN ISLANDS' 'UNITED ARAB EMIRATES' 'YEMEN'
 'UNITED NATIONS' 'ANDORRA' '000' 'POLAND' 'IRAN' 'FRANCE' 'تايلاند'
 'AMERICAN SAMOA' 'GUAM (USA)' 'PAPUA NEW GUINEA' 'SUDAN' 'GREECE'
 'TALWAN' 'JINDONESIA' '00' 'SWEDEN' '0' 'EMIRATES' 'AFGHANISTAN' 'GCC'
 'تايلند' 'TAIWAN (CHINESE TAIPEI FOR IOC)' 'INDIAN' 'OTHERS'
 'NEW ZEALAND' 'تركيا' 'JAPAN ' 'PAKISTAN' 'NAYON' 'استراليا' 'GUINEA'
 'UNKNOWN' 'JAMERICA' 'U.S.A' 'TABUN' 'MACAU' 'US' 'LIGHT VEHICLE'
 'NORTH AMERICA' 'EGYPT' 'ESTONIA' 'SOUTH AFRICA' 'ITALY' 'JPAN' 'DUBAI'
 'الولايات المتحدة' 'اليابان' 'G' 'HUNGARY' 'BAIWAN' 'JAPAM' 'ANGUILLA'
 'TAIWAN (CHINESE TAIPEI)' 'NON GCC' 'SAUDI ARABIA' 'LIWAN' 'A'
 'USA MINOR OUTLYING ISLANDS' 'KOREA' 'TAIWAN (PROVINCE OF CHINA)'
 'آتيانیان' 'SYRIA' '4' 'ASIAN' 'GREAT BRITAIN' 'REPUBLIC OF SOUTH KOREA'
 'TUVALU' 'NEW GUINEA' 'HAILAND' 'CAMEROON' 'J' 'THE THAILAND' 'JAMAICA'
 'MOROCCO' 'TANZANIA' 'KENYA' 'BELGIUM' 'SUD' 'الريان' 'NORTH KOREA'
 'ORIGIN' 'AMERICAN' 'N AMERICAN COUNTRIES' 'MYANMAR' 'MAE' 'D' 'HAQUARI'
 'امريكا' 'AUSTRALLA' 'CAPAN' 'LEBANON' 'JAPANE' 'JAPANN' 'TOYOTA' 'GHANA'
 '1' 'PHILIPPINES' 'JAPA' 'RUSSIA' '11' 'EUROPEAN UNION' 'FAUSTRALIA'
 'HONDURAS' 'TAI' 'JORDAN' 'SLOVAKIA' 'SILVER' 'JARAN' 'PARAGUAY' 'TAIMAN'
 'SOUTH AMERICAN' 'VIRGIN ISLANDS (USA)' 'S' 'JERSEY' 'BANGLADESH'
 'AMERICA ' 'THALLAND' 'LIBYA' 'SAPAN' 'UMM AL QUWAIN'
 'ANTIGUA AND BARBUDA' 'J. PAN' 'LADIR' 'PORTUGAL' 'ETHIOPIA' 'TAINAN'
 'FRANCE (EUROPEAN PROVINCE)' 'CAMBODIA' 'FIJI' 'HINA' 'تايون' 'TNIYON'
 'KOREA SOUTH' 'OMAN' '17750' 'تایلاند' 'KOSOVO' 'FINDONESIA' 'TAILAND'
 'QATAR' 'UNITED KINGDOM (GREAT BRITAIN)' 'MALAYSIA' 'الصين' 'NORWAY'
 'JAE']

In [11]:
origin_mapping = {
    "1": "USA",
    "4": "USA",
    "5": "USA",
    "2": "CANADA",
    "3": "MEXICO",
    "J": "JAPAN",
    "K": "SOUTH KOREA",
    "W": "GERMANY",
    "Z": "ITALY",
    "S": "UNITED KINGDOM",
    "Y": "SWEDEN / FINLAND",
    "L": "CHINA",
    "M": "INDIA",
    "V": "FRANCE / SPAIN",
    "T": "SWITZERLAND",
    "R": "TAIWAN",
    "9": "BRAZIL"
}

In [12]:
import pandas as pd
import numpy as np

# ==========================================================
# POSITION 1 (WMI REGION) → ORIGIN
# ==========================================================
origin_mapping = {
    "1": "USA",
    "4": "USA",
    "5": "USA",
    "2": "CANADA",
    "3": "MEXICO",
    "J": "JAPAN",
    "K": "SOUTH KOREA",
    "W": "GERMANY",
    "Z": "ITALY",
    "S": "UNITED KINGDOM",
    "Y": "SWEDEN / FINLAND",
    "L": "CHINA",
    "M": "INDIA",
    "V": "FRANCE / SPAIN",
    "T": "SWITZERLAND",
    "R": "TAIWAN",
    "9": "BRAZIL"
}

# Normalize pos1
data["pos1"] = (
    data["pos1"]
    .astype(str)
    .str.upper()
    .str.strip()
)

# Normalize origin
data["origin"] = (
    data["origin"]
    .astype(str)
    .str.upper()
    .str.strip()
)

# Create origin from pos1
data["origin_from_pos1"] = data["pos1"].map(origin_mapping)

# Use pos1-derived origin whenever available
data["origin"] = (
    data["origin_from_pos1"]
    .combine_first(data["origin"])
)

# Remove helper column
data.drop(columns=["origin_from_pos1"], inplace=True)

# Optional: remove garbage values
invalid_origin = {
    "0", "00", "000",
    "1", "4", "11",
    "UNKNOWN",
    "OTHERS",
    "NAN",
    "TOYOTA"
}

data.loc[data["origin"].isin(invalid_origin), "origin"] = np.nan

# Check results
print(sorted(data["origin"].dropna().unique()))
print(data["origin"].value_counts(dropna=False))

['AMERICA', 'ASIAN', 'AUSTRALIA', 'AUSTRALLA', 'AUSTRIA', 'BRAZIL', 'CANADA', 'CHINA', 'D', 'EGYPT', 'ESTONIA', 'FAUSTRALIA', 'FRANCE / SPAIN', 'GCC', 'GERMANY', 'GREAT BRITAIN', 'INDIA', 'INDONESIA', 'ITALY', 'J', 'JAPAN', 'KOREA', 'LADIR', 'MACAU', 'MEXICO', 'MOROCCO', 'NEW ZEALAND', 'ORIGIN', 'REPUBLIC OF SOUTH KOREA', 'REPUBLIC OF TURKIYE', 'SOUTH AFRICA', 'SOUTH KOREA', 'SPAIN', 'SUDAN', 'SWEDEN', 'SWEDEN / FINLAND', 'SWITZERLAND', 'TAIWAN', 'THAILAND', 'TURKEY', 'UAE', 'UNITED ARAB EMIRATES', 'UNITED KINGDOM', 'UNITED STATES', 'USA', 'استراليا']
origin
JAPAN                      114906
USA                         37856
INDIA                       37747
AUSTRALIA                   23170
TAIWAN                      17105
CANADA                       4607
NaN                          1472
CHINA                         751
MEXICO                        313
GERMANY                       275
TURKEY                        245
UNITED KINGDOM                126
FRANCE / SPAIN                119
ITALY                         100
SOUTH KOREA                    89
REPUBLIC OF TURKIYE            79
SWEDEN / FINLAND               49
AMERICA                        48
UNITED STATES                  36
AUSTRIA                        31
UAE                            24
SPAIN                           8
INDONESIA                       8
THAILAND                        7
ESTONIA                         5
UNITED ARAB EMIRATES            4
استراليا                        4
GCC                             3
ASIAN                           3
BRAZIL                          3
NEW ZEALAND                     2
MOROCCO                         2
AUSTRALLA                       2
EGYPT                           2
SWITZERLAND                     1
SWEDEN                          1
SOUTH AFRICA                    1
ORIGIN                          1
J                               1
D                               1
FAUSTRALIA                      1
GREAT BRITAIN                   1
SUDAN                           1
MACAU                           1
LADIR                           1
REPUBLIC OF SOUTH KOREA         1
KOREA                           1
Name: count, dtype: int64

In [13]:
print(data['origin'].unique())

['TAIWAN' 'JAPAN' 'USA' 'INDIA' 'AUSTRALIA' 'CANADA' 'GERMANY' 'CHINA'
 'TURKEY' 'MEXICO' 'REPUBLIC OF TURKIYE' 'UNITED STATES' 'ITALY' 'SPAIN'
 'SOUTH KOREA' 'UNITED KINGDOM' 'FRANCE / SPAIN' 'UAE' 'SWEDEN / FINLAND'
 'INDONESIA' 'AMERICA' 'AUSTRIA' nan 'NEW ZEALAND' 'استراليا'
 'SWITZERLAND' 'BRAZIL' 'ESTONIA' 'SOUTH AFRICA' 'GCC' 'SWEDEN' 'THAILAND'
 'UNITED ARAB EMIRATES' 'EGYPT' 'ASIAN' 'J' 'MOROCCO' 'ORIGIN' 'D'
 'AUSTRALLA' 'FAUSTRALIA' 'GREAT BRITAIN' 'SUDAN' 'MACAU' 'LADIR'
 'REPUBLIC OF SOUTH KOREA' 'KOREA']

In [14]:
print(data['trim'].unique())

['SE' 'GLX' 'DX' 'DL' 'XLI' 'VX' 'MID' 'DLX' 'VXR' 'FABRIC' 'E' 'TOP'
 'EXTREME' 'GL' 'BASE' 'S' 'FLEET' 'STD (NON GCC)' 'GXR' 'EXR'
 'SE+ ANNIVERSARY EDITION' 'GL2' 'SR5' 'STD' 'LE' 'XLI MID' 'LE (NON GCC)'
 'SE+' 'GLI' 'SR5 (NON GCC)' 'TX' 'LIMITED' 'XLE (NON GCC)'
 'SE TRD AERO PK' 'EX' 'ICONIC' 'VX MID' 'LE HEV' 'SGLX' 'PW CL' 'GX'
 'XLE' 'SPORT' 'G' 'GRANDE' 'GR' 'XLI TOP' 'S TRD SPORT PK' 'S+' 'PRO'
 'XLI RB' 'LIMITED PREMIUM' 'GLE' 'XLI EXECUTIVE' 'GLS' 'PLATINUM'
 'DLX TOP' 'TURBO G RA' 'LIMITED (NON GCC)' 'SR5 4X4' 'VXR HEV' 'GLE HEV'
 'SAFARI' 'LX' 'GXR TOP 60TH ANNIV. XTREME' 'CE (NON GCC)' 'GLI HEV'
 'PREMIUM' 'XLI EXECUTIVE MR' 'XL' 'GXR TOP' 'VXR BASE' 'LX AC PWR OPT'
 'LX WINCH' 'TX-L' 'XLE TOURING' 'GXR GT' 'DLS' 'VXR TOP' 'SC'
 'GLE-X HEV 40TH ANNIV' 'SALOON' nan 'ADVENTURE'
 'CREWMAX CAPSTONE (NON GCC)' 'LE STD' 'LIMITED MID' 'GX TOP' 'TX-L TOP'
 'GLI TOP' 'EXCLUSIVE' 'XSE (NON GCC)' 'BLACK EDITION' 'DX H/R W/B'
 'C (NON GCC)' 'XLI POWER OPT' 'GLX SPORT Z' 'S PLUS' 'VTX' 'GXL' 'HT SWB'
 'GXR MID' 'ECO' 'GX MID' 'GXR2' 'LWB HIGH ROOF' '1794 EDITION (NON GCC)'
 '40TH ANNIVERSARY EDITION' 'TOURING' 'HEV' 'GLI TOP LTH' 'PS PW CL'
 'LIMITED 4X4' 'GR SPORT' 'STD D' 'TXL1' 'LWB' 'DLS - STD ROOF' 'EXR HEV'
 'LSE' 'BE' 'GLE-X' 'GT' 'T' 'SWB' 'SE (NON GCC)' 'SR' 'GTX' 'TXL3'
 'GR TAN EDITION' 'ST' 'E PLUS HEV' '1.8' 'LIMITED 4X2' 'VX TOP LTH' 'VX2'
 'STANDARD' 'SV' 'SR5 4X2' 'VX1' 'GXR FMST' 'HEV GLI' 'GXR1' 'DYNAMIC'
 'XLI EXECUTIVE HEV' '1' 'GR-S' 'FJ STD' 'GR BLUE EDITION' 'TRD' 'YX'
 'GXR TOP DMST' 'LMV' 'CTD' 'HT VXR' 'LIMITED TRD SPORT PK' 'VXR TOP LTH'
 'TXR' 'XLE HEV' 'STD AC' 'XLT' 'COUPE' '1500' 'X' 'TRD OFF-ROAD' 'BUS'
 'GLE HEV BLACK EDITION' 'Y PLUS' 'SR (NON GCC)' 'STATION' 'PICK UP' 'TX1'
 'SEDAN' 'GXR SOD D/AC AW' 'TC (NON GCC)' 'LIMITED HEV' 'SL' 'XTREME'
 'TXL2' 'GXR4' 'GXR TOP FMST' 'GT SPORT' 'HARD TOP' 'HYBRID (NON GCC)'
 'GL TOP' 'XSE' 'GRD' 'L' 'SGL' 'SED' '2400' 'GRANDE HEV 40TH ANNIV' 'AIR'
 'TRD SPORT' 'STANDDARD' '0' 'AXL ' 'XLI - AW' 'TURBO G' 'GXR-V' 'STAN'
 'VT' 'GA' 'GXR+' '2.0L' '25HX' 'PREMIER' 'GXR3' '6' 'SE TRD SPORT PK'
 'AUTOMATIC' 'LUMIERE HEV' 'STANDER' 'TRIM' 'LEVIN' 'HILUX' 'EXI'
 'LAND CRUSIER' '4X4' 'XE 4WD' 'A' 'STATION1' 'GXR MID 60TH ANNIV. XTREME'
 'VXR MID' 'PICKUP' 'S ASF' 'GL DECKLESS' 'CRESSIDA' 'LS' 'HYBRID'
 'LUXURY' 'GF' 'HT SLWB' 'CABRIO' 'ADVENTTURE' 'STD CARGO' 'HYCROSS' 'GG'
 'STATION ' 'SLD' 'C' 'PRESTIGE' 'Y' 'LUMIERE 40TH ANNIV' 'GRANDE HEV'
 'PIKUP' 'PRADO' 'LTD HEV' '10TH VICTORY EDITION' 'ROYAL' 'GL LIMITED'
 'CE' 'LIMITED TRD AERO PK' 'SS' 'VX2 PLUS' 'FULL OPTION' 'VXR TOP XTREME'
 '4WD' 'GLI TOP LEATHER' '60TH' 'AT' 'GXL 1ST EDITION' 'USF'
 'DLS HIGH ROOF' '1500 CREWCAB SLE Z71' 'ORION' 'STANDERD' 'VX-L MID'
 'GGG' 'GLS TOP' 'COMFORT' 'MPV' 'VIP7' 'LTZ' '45' 'LIMITED TOP'
 'EXECUTIVE' 'STD  (NON GCC)' '4' 'PLATINUM LUXURY 4X4' 'N' 'NON GCC'
 'GLI MR HEV' 'SENA' 'CAR TRIM' 'LX WIDE TYRES' 'SPORTS' 'COASTER'
 'S T2 TOP' 'AMBIENTE' 'VX-L TOP' 'PICKUP ' 'LUXURY SPORT' 'GV'
 'ADVENTURE 1ST EDITION' 'ASD' 'AA' 'AMG' 'YA' 'TR' 'EXCELLENCE' 'SU'
 'GLX PREMIUM' 'ZX' 'TUNDRA' 'GLS LOWLINE' 'SUPER SAFARI T1' 'ABC'
 'DOUBLE CABIN ' 'GL LTH' 'DTD' 'ROYAL EDITION' '2' 'ASAD' 'LXI' '1.5'
 'GC' 'GXR MID XTREME' '90' 'TOP LTH' 'STEALTH' 'ALTIS (NON GCC)' 'H'
 'S TRD AERO PK' '40 TFSI S-LINE' 'SUV' 'SE T2' 'FR-S (NON GCC)' 'DC'
 'LE PLATINUM CITY' 'PICK' 'GXR MID 60TH ANNIVERSARY' 'SLT' 'SINGLE CABIN'
 'S T1' 'VTI' 'CARRERA GTS' 'EX MID' 'TRTIM' 'VAN' 'XLI ' 'TAXI' 'COM'
 'IM' 'GXR HEV' '1000' 'SPORTS BASIC' 'ADVENTURE 1ST EDITIO'
 '40TH ANNIVERSARY EDI' 'GXR TOP 60TH ANNIV. ' '1794 EDITION (NON GC'
 'XLI HEV' 'SE+ ANNIVERSARY EDIT' 'CREWMAX CAPSTONE (NO']

In [15]:
import pandas as pd
import numpy as np

# ==========================================================
# TRIM NORMALIZATION
# ==========================================================

TRIM_MAPPING = {
    # XLI
    "XLI MID": "XLI",
    "XLI TOP": "XLI",
    "XLI RB": "XLI",
    "XLI EXECUTIVE": "XLI",
    "XLI EXECUTIVE MR": "XLI",
    "XLI EXECUTIVE HEV": "XLI HEV",
    "XLI POWER OPT": "XLI",
    "XLI 1.8L": "XLI",
    "XLI 1.8": "XLI",
    "XLI+": "XLI",
    "XLI - AW": "XLI",
    "XLI ": "XLI",

    # GLI
    "GLI TOP": "GLI",
    "GLI TOP LTH": "GLI",
    "GLI TOP LEATHER": "GLI",
    "GLI HEV": "GLI HEV",
    "HEV GLI": "GLI HEV",
    "GLI MR HEV": "GLI HEV",

    # GXR
    "GXR TOP": "GXR",
    "GXR MID": "GXR",
    "GXR1": "GXR",
    "GXR2": "GXR",
    "GXR3": "GXR",
    "GXR4": "GXR",
    "GXR+": "GXR",
    "GXR GT": "GXR",
    "GXR FMST": "GXR",
    "GXR TOP FMST": "GXR",
    "GXR MID XTREME": "GXR",
    "GXR TOP XTREME": "GXR",
    "GXR MID 60TH ANNIV. XTREME": "GXR",
    "GXR MID 60TH ANNIVERSARY": "GXR",
    "GXR TOP 60TH ANNIV. XTREME": "GXR",
    "GXR TOP 60TH ANNIV.": "GXR",
    "GXR TOP 60TH ANNIV": "GXR",
    "GXR TOP DMST": "GXR",
    "GXR SOD D/AC AW": "GXR",
    "GXR-V": "GXR",
    "GXR HEV": "GXR HEV",

    # VXR
    "VXR BASE": "VXR",
    "VXR MID": "VXR",
    "VXR TOP": "VXR",
    "VXR TOP LTH": "VXR",
    "HT VXR": "VXR",
    "VXR HEV": "VXR HEV",

    # LE
    "LE STD": "LE",
    "LE TITANIUM": "LE",
    "LE PLATINUM CITY": "LE",
    "LE HEV": "LE HEV",

    # SE
    "SE+": "SE",
    "SE (NON GCC)": "SE",
    "SE TRD SPORT PK": "SE",
    "SE TRD AERO PK": "SE",
    "SE T1": "SE",
    "SE T2": "SE",
    "SE+ ANNIVERSARY EDITION": "SE",
    "SE+ ANNIVERSARY EDIT": "SE",
    "SE TITANIUM": "SE",

    # SR5
    "SR5 4X2": "SR5",
    "SR5 4X4": "SR5",
    "SR5 (NON GCC)": "SR5",

    # LIMITED
    "LIMITED PREMIUM": "LIMITED",
    "LIMITED TOP": "LIMITED",
    "LIMITED HEV": "LIMITED HEV",
    "LIMITED 4X2": "LIMITED",
    "LIMITED 4X4": "LIMITED",
    "LIMITED (NON GCC)": "LIMITED",
    "LIMITED TRD SPORT PK": "LIMITED",
    "LIMITED TRD AERO PK": "LIMITED",

    # GRANDE
    "GRANDE LTH": "GRANDE",
    "GRANDE HEV": "GRANDE HEV",
    "GRANDE HEV 40TH ANNIV": "GRANDE HEV",

    # ALTIS
    "ATLIS": "ALTIS",
    "ALIS": "ALTIS",
    "ALTAS": "ALTIS",

    # SAFARI
    "SUPER SAFARI T1": "SAFARI",

    # ADVENTURE
    "ADVENTTURE": "ADVENTURE",
    "ADVENTURE 1ST EDITION": "ADVENTURE",
    "ADVENTURE 1ST EDITIO": "ADVENTURE",

    # GR
    "GR-S": "GR SPORT",
    "GR BLUE EDITION": "GR SPORT",
    "GR TAN EDITION": "GR SPORT",

    # TX
    "TXL1": "TX-L",
    "TXL2": "TX-L",
    "TXL3": "TX-L",
    "TXR": "TX",

    # Common spelling fixes
    "STANDDARD": "STANDARD",
    "STANDER": "STANDARD",
    "STANDERD": "STANDARD",
    "STANDAR": "STANDARD",
    "STDD": "STD",
    "STD NON GCC": "STD",
    "STD ( NON GCC )": "STD",
    "STD  (NON GCC)": "STD",
    "STD (NON GCC)": "STD",
    "LEATHER": "PREMIUM",
    "FULL OPTION": "PREMIUM",
    "TOP LTH": "PREMIUM",
}

# ==========================================================
# INVALID VALUES
# ==========================================================

INVALID_TRIMS = {
    "NAN", "", "-", " ", "0", "00", "000", "0000", "00000",
    "1", "2", "4", "5", "6", "45", "90", "100", "1000",
    "1500", "2400",
    "1.3", "1.4", "1.5", "1.8", "2.0L", "5.0L",
    "4X4", "4WD",
    "AUTOMATIC", "AUTOMATIC ",
    "MANUAL",
    "NON GCC",
    "GCC",
    "TRIM",
    "TERIM",
    "TRTIM",
    "CAR TRIM",
    "OTHER"
}

# Models accidentally present in trim column
MODEL_LEAKAGE = {
    "COROLLA",
    "HILUX",
    "TUNDRA",
    "PRADO",
    "LAND CRUSIER",
    "LAND CRUISER",
    "COASTER",
    "RUSH",
    "VIOS",
    "WISH",
    "TOYOTA"
}

# ==========================================================
# CLEAN FUNCTION
# ==========================================================

def clean_trim(data: pd.DataFrame,
               column: str = "trim",
               rare_threshold: int = 20) -> pd.DataFrame:

    data = data.copy()

    data[column] = (
        data[column]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    # Apply mappings
    data[column] = data[column].replace(TRIM_MAPPING)

    # Remove invalid trims
    data.loc[
        data[column].isin(INVALID_TRIMS),
        column
    ] = np.nan

    # Remove model leakage
    data.loc[
        data[column].isin(MODEL_LEAKAGE),
        column
    ] = np.nan

    # Group rare trims
    trim_counts = data[column].value_counts()

    rare_trims = trim_counts[
        trim_counts < rare_threshold
    ].index

    data.loc[
        data[column].isin(rare_trims),
        column
    ] = "OTHER"

    return data


# ==========================================================
# APPLY
# ==========================================================

data = clean_trim(
    data,
    column="trim",
    rare_threshold=20
)

print(f"Unique Trims: {data['trim'].nunique()}")

print(
    data["trim"]
    .value_counts(dropna=False)
    .head(100)
)

Unique Trims: 106
trim
XLI                 39147
SE                  20221
GXR                 15444
GL                  15111
BASE                13364
                    ...
HYBRID (NON GCC)       31
HARD TOP               30
GTX                    29
BLACK EDITION          29
STANDARD               29
Name: count, Length: 100, dtype: int64

In [16]:
data = data[["year","make", "model", 'trim', 'bodyType', 'regionalSpec', "cylinders", 'color', 'origin', 'weightInKg', "noOfPassengers"]]

In [17]:
data

,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,1000.0,5.0
1,2015.0,TOYOTA,HIACE,GLX,MINI BUS,GCC,4.0,WHITE,JAPAN,2000.0,2.0
2,2015.0,TOYOTA,HIACE,DX,MINI BUS,GCC,4.0,WHITE,JAPAN,1837.0,15.0
3,2015.0,TOYOTA,HILUX,DL,PICKUP DOUBLE CAB,GCC,4.0,WHITE,JAPAN,1837.0,5.0
4,2001.0,TOYOTA,CAMRY,XLI,SEDAN,NON-GCC,4.0,BROWN AND BEIGE,USA,1481.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
922350,2019.0,TOYOTA,HILUX,GLX,PICKUP,GCC,6.0,WHITE/PEARLS,INDIA,NaN,5.0
922351,2025.0,TOYOTA,LAND CRUISER,NaN,SUV,GCC,6.0,BLACK,JAPAN,NaN,7.0
922352,2021.0,TOYOTA,LAND CRUISER,GXR,SUV,GCC,8.0,WHITE/PEARLS,JAPAN,NaN,8.0
922353,2025.0,TOYOTA,LAND CRUISER,GXL,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,7.0
922354,2021.0,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,INDIA,NaN,5.0

In [18]:
data.to_csv("../Data/toyota_valuation.csv", index=False)

In [23]:
import pandas as pd
import re
import asyncio
from playwright.async_api import async_playwright


async def get_toyota_msrp(model: str):
    try:
        model_slug = (
            str(model)
            .strip()
            .lower()
            .replace("&", "and")
            .replace("/", "-")
            .replace(" ", "-")
        )

        url = f"https://www.drivearabia.com/carprices/uae/toyota/"

        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            page = await browser.new_page()

            await page.goto(url, timeout=60000)
            await page.wait_for_timeout(5000)

            text = await page.locator("body").inner_text()

            await browser.close()

        prices = re.findall(r"AED\s*([\d,]+)", text)

        if prices:
            return int(prices[0].replace(",", ""))

    except Exception as e:
        print(f"Failed for {model}: {e}")

    return None


async def add_prices():

    unique_df = (
        data[["make", "model", "trim"]]
        .fillna("UNKNOWN")
        .drop_duplicates()
        .reset_index(drop=True)
    )

    msrp_list = []

    for _, row in unique_df.iterrows():

        if str(row["make"]).upper() == "TOYOTA":
            price = await get_toyota_msrp(row["model"])
        else:
            price = None

        msrp_list.append(price)

    unique_df["current_msrp"] = msrp_list

    return data.merge(
        unique_df,
        on=["make", "model", "trim"],
        how="left"
    )


# Jupyter Notebook
data = await add_prices()

print(data.head())

Failed for COROLLA:
Failed for HIACE:
Failed for HIACE:
Failed for HILUX:
Failed for CAMRY:
Failed for LAND CRUISER:
Failed for YARIS:
Failed for HILUX:
Failed for COROLLA:
Failed for FJ CRUISER:
Failed for RAV4:
Failed for YARIS:
Failed for FJ CRUISER:
Failed for FJ CRUISER:
Failed for CAMRY:
Failed for HILUX:
Failed for FJ CRUISER:
Failed for CAMRY:
Failed for HIACE:
Failed for YARIS:
Failed for TUNDRA:
Failed for AVALON:
Failed for LAND CRUISER:
Failed for FORTUNER:
Failed for FORTUNER:
Failed for CAMRY:
Failed for HILUX:
Failed for FORTUNER:
Failed for COASTER:
Failed for RAV4:
Failed for CAMRY:
Failed for YARIS:
Failed for CAMRY:
Failed for RAV4:
Failed for INNOVA:
Failed for SIENNA:
Failed for CAMRY:
Failed for TACOMA:
Failed for LAND CRUISER:
Failed for CAMRY:
Failed for SIENNA:
Failed for RUSH:
Failed for YARIS:
Failed for PRIUS:
Failed for CAMRY:
Failed for YARIS:
Failed for AVANZA:
Failed for FORTUNER:
Failed for LAND CRUISER:
Failed for RAV4:
Failed for HILUX:
Failed for CAMRY:
Failed for LAND CRUISER:
Failed for RAV4:
Failed for RAV4:
Failed for HIACE:
Failed for FJ CRUISER:
Failed for COROLLA:
Failed for LAND CRUISER:
Failed for AVALON:
Failed for AVALON:
Failed for LAND CRUISER:
Failed for SEQUOIA:
Failed for RAV4:
Failed for RAV4:
Failed for COROLLA:
Failed for CAMRY:
Failed for LAND CRUISER:
Failed for CAMRY:
Failed for HILUX:
Failed for PRIUS:
Failed for LAND CRUISER:
Failed for COROLLA:
Failed for AVALON:
Failed for RAV4:
Failed for SUPRA:
Failed for AURION:
Failed for ECHO:
Failed for YARIS:
Failed for COROLLA:
Failed for YARIS:
Failed for PREVIA:
Failed for BZ4X:
Failed for COROLLA:
Failed for TACOMA:
Failed for HIACE:
Failed for YARIS:
Failed for CAMRY:
Failed for C-HR:
Failed for PREVIA:
Failed for HILUX:
Failed for XA:
Failed for GRANVIA:
Failed for VELOZ:
Failed for HILUX:
Failed for RAIZE:
Failed for SIENNA:
Failed for RAV4:
Failed for AURION:
Failed for RAV4:
Failed for RAV4:
Failed for RAV4:
Failed for HIACE:
Failed for IQ:
Failed for FORTUNER:
Failed for RAIZE:
Failed for INNOVA:
Failed for CAMRY:
Failed for PREVIA:
Failed for LAND CRUISER:
Failed for LAND CRUISER:
Failed for FJ:
Failed for CAMRY:
Failed for COROLLA:
Failed for CROWN:
Failed for RAV4:
Failed for COROLLA:
Failed for 86:
Failed for CROWN:
Failed for LAND CRUISER:
Failed for LAND CRUISER:
Failed for LAND CRUISER:
Failed for AURION:
Failed for AVALON:
Failed for 4RUNNER:
Failed for HILUX:
Failed for LAND CRUISER:
Failed for CAMRY:
Failed for COROLLA:
Failed for COROLLA:
Failed for LAND CRUISER:
Failed for HILUX:
Failed for TUNDRA:
Failed for SIENNA:
Failed for RUSH:
Failed for SEQUOIA:
Failed for GRANVIA:
Failed for URBAN CRUISER:
Failed for AVALON:
Failed for SCION:
Failed for LAND CRUISER:
Failed for AURION:
Failed for RAV4:
Failed for URBAN CRUISER:
Failed for CAMRY:
Failed for YARIS:
Failed for AVALON:
Failed for CAMRY:
Failed for LAND CRUISER:
Failed for HIACE:
Failed for PREVIA:
Failed for PRIUS:
Failed for HIGHLANDER:
Failed for OTHERS:
Failed for SEQUOIA:
Failed for DYNA:
Failed for CAMRY:
Failed for CAMRY:
Failed for LAND CRUISE:
Failed for 86:
Failed for LAND CRUISER:
Failed for LAND CRUISER:
Failed for CROWN:
Failed for HILUX:
Failed for PRIUS:
Failed for HIGHLANDER:
Failed for LAND CRUISER:
Failed for 4RUNNER:
Failed for COASTER:
Failed for TERCEL:
Failed for TUNDRA:
Failed for CAMRY:
Failed for AURION:
Failed for INNOVA:
Failed for CAMRY:
Failed for LITEACE:
Failed for RAV4:
Failed for ECHO:
Failed for COROLLA:
Failed for LITEACE:
Failed for SEQUOIA:
Failed for LAND CRUISER:
Failed for MATRIX:
Failed for INNOVA:
Failed for FORTUNER:
Failed for COASTER:
Failed for HIACE:
Failed for RAV4:
Failed for HILUX:
Failed for HIACE:
Failed for RAV4:
Failed for CAMRY:
Failed for 86:
Failed for RAV 4:
Failed for AVALON:
Failed for GR86:
Failed for LAND CRUISER:
Failed for LEVIN:
Failed for C-HR:
Failed for COASTER:
Failed for SIENNA:
Failed for RAIZE:
Failed for TUNDRA:
Failed for ZELAS:
Failed for 86:
Failed for SUPRA:
Failed for LAND CRUISER:
Failed for ALPHARD:
Failed for YARIS:
Failed for HIGHLANDER:
Failed for FORTUNER:
Failed for SEQUOIA:
Failed for TACOMA:
Failed for CAMRY:
Failed for SEQUOIA:
Failed for FORTUNER:
Failed for COROLLA:
Failed for LAND CRUISER:
Failed for TOYOTA VELOZ:
Failed for VELOZ:
Failed for FJ CRUISER:
Failed for PRIUS:
Failed for SEQUOIA:
Failed for COASTER:
Failed for RAV 4:
Failed for HIGHLANDER:
Failed for RAV 4:
Failed for AVALON:
Failed for FJ CRUISER:
Failed for INNOVA:
Failed for TACOMA:
Failed for YARIS:
Failed for 86:
Failed for T 300:
Failed for YARIS:
Failed for 4 RUNNER:
Failed for ZELAS:
Failed for RAIZE:
Failed for COASTER:
Failed for LAND CRUISER:
Failed for HIGHLANDER:
Failed for COASTER:
Failed for PRIUS:
Failed for COASTER:
Failed for COROLLA:
Failed for FORTUNER:
Failed for INNOVA:
Failed for SUPRA:
Failed for RAV 4:
Failed for CRESSIDA:
Failed for COROLLA:
Failed for LAND CRUISER:
Failed for C-HR:
Failed for SUPRA:
Failed for HILUX:
Failed for HILUX:
Failed for HIGHLANDER:
Failed for CROWN KLUGER:
Failed for 4RUNNER:
Failed for COASTER:
Failed for HIGHLANDER:
Failed for HIGHLANDER:
Failed for YARIS:
Failed for TUNDRA:
Failed for YARIS:
Failed for LAND CRUISER:
Failed for UNKNOWN:
Failed for FJ CRUISER:
Failed for PREVIA:
Failed for TAKOMA:
Failed for PRIUS:
Failed for SIENNA:
Failed for UNKNOWN:
Failed for RAV 4:
Failed for SCION:
Failed for TOYOTA PRIUS:
Failed for FJ CRUISER:
Failed for TOYOTA ALTIS:
Failed for HIACE:
Failed for ALTIS:
Failed for LAND CRUISER:
Failed for استیشن:
Failed for HIGHLANDER:
Failed for INNOVA:
Failed for 4RUNNER:
Failed for HIACE:
Failed for HIGHLANDER:
Failed for SIENNA:
Failed for HIGHLANDER:
Failed for SEQUOIA:
Failed for LAND CRUISER:
Failed for UNKNOWN:
Failed for SCION:
Failed for SIENNA:
Failed for BZ3X:
Failed for HIGHLANDER:
Failed for ALPHARD:
Failed for FORTUNER:
Failed for 4RUNNER:
Failed for AVANZA:
Failed for HILUX:
Failed for OTHERS:
Failed for INNOVA:
Failed for بيك اب كابينه مزدوجه:
Failed for 26HX DC 4X4P2.7LAT:
Failed for RUSH:
Failed for IQ:
Failed for RAIZE:
Failed for COROLLA:
Failed for RAV 4:
Failed for 86:
Failed for RAV4:
Failed for INNOVA:
Failed for SALOON:
Failed for PICK UP:
Failed for CAMRY:
Failed for CAMRY:
Failed for RUMION:
Failed for MR2:
Failed for TOYOTA:
Failed for LAND CRUISER:
Failed for SUPRA:
Failed for WISH:
Failed for 25 LP SC4X44.0L MT:
Failed for RAIZE:
Failed for LAND CRUISER:
Failed for AVALON:
Failed for UNKNOWN:
Failed for UNKNOWN:
Failed for DYNA:
Failed for BZ3X:
Failed for SEQUOIA:
Failed for TAKOMA:
Failed for TANDRA:
Failed for CROWN:
Failed for COROLLA:
Failed for LAND CRUISER:
Failed for SEQUOIA:
Failed for RUSH:
Failed for BZ 4:
Failed for COASTER:
Failed for 4 RUNNER:
Failed for 4RUNNER:
Failed for STATION:
Failed for DYNA:
Failed for SIENNA:
Failed for LAND CRUISER:
Failed for TUNDRA:
Failed for AURION:
Failed for SEQUOIA:
Failed for HIGHLANDER:
Failed for CRESSIDA:
Failed for SEQUOIA:
Failed for AVALON:
Failed for SALOON:
Failed for YARIS:
Failed for HAI LUX:
Failed for YARIS:
Failed for HIGHLANDER:
Failed for SEQUOIA:
Failed for TAKOMA:
Failed for UNKNOWN:
Failed for AVANZA:
Failed for SIENNA:
Failed for HILUX:
Failed for WISH:
Failed for UNKNOWN:
Failed for VENZA:
Failed for 25 HX DC 4X4D 2.4LAT:
Failed for HILUX:
Failed for COASTER:
Failed for CAMRY:
Failed for YARIS:
Failed for TAKOMA:
Failed for HIACE:
Failed for MR2:
Failed for BZ 4:
Failed for TOKOMA:
Failed for RAV4:
Failed for TOYOTA:
Failed for IQ:
Failed for 25 LP SC 4X4 P4.0 MT:
Failed for CELICA:
Failed for HIACE:
Failed for UNKNOWN:
Failed for GRANVIA:
Failed for T 100:
Failed for SIENNA:
Failed for TANDRA:
Failed for HIGHLANDER:
Failed for UNKNOWN:
Failed for MR2:
Failed for RAV 4:
Failed for HIACE:
Failed for COASTER:
Failed for INNOVA:
Failed for HIGHLANDER:
Failed for GR86:
Failed for AURION:
Failed for AURION:
Failed for حافلة نقل خاص:
Failed for CROWN:
Failed for 25 HX DC 4X4 2.7LAT:
Failed for GLX DA (PICK UP):
Failed for RUNNER:
Failed for TOYOTA:
Failed for 4 RUNNER:
Failed for 25 HX DC 4X4 2.7LAT:
Failed for COROLLA:
Failed for ALLION:
Failed for SCION:
Failed for CRESSIDA:
Failed for VIOS:
Failed for TACOMA:
Failed for RAV4:
Failed for TOYOTA SCION:
Failed for TOYOTA 4RUNNER:
Failed for CAMRY:
Failed for TOYOTA IQ:
Failed for 4 RUNNER:
Failed for TOYOTA:
Failed for PRIUS:
Failed for CELICA:
Failed for SIENNA:
Failed for SIENNA:
Failed for FORTUNER:
Failed for UNKNOWN:
Failed for PRIUS:
Failed for TOYOTA:
Failed for 4RUNNER:
Failed for RAV 4:
Failed for COASTER:
Failed for COROLLA:
Failed for TOYOTA IQ:
Failed for PICK UP CABIN:
Failed for TACOMA:
Failed for TOYOTA SUPRA:
Failed for HILUX:
Failed for 2 HX DC 4X40:
Failed for LAND CRUISER:
Failed for FRONTLANDER:
Failed for HILUX:
Failed for 25 CA SON P 2.5L AT:
Failed for SALOON:
Failed for RAV4:
Failed for TACOMA:
Failed for 25 HX DC 4X4P 2.7LAT:
Failed for DYNA:
Failed for GLX RA (PICK UP):
Failed for TOYOTA 4RUNNER:
Failed for HILUX:
Failed for HAI LUX:
Failed for RAV4:
Failed for AVALON:
Failed for AVANZA:
Failed for CORONA:
Failed for 26 YA HB P 1.6L AT TURBO GR RA(CAR):
Failed for CAMRY:
Failed for 26HX DC 4X4D2.4L AT:
Failed for SIENA:
Failed for STATION:
Failed for TERCEL:
Failed for 26 HX DC 4X4 2.4LAT:
Failed for 26HX DC 4X4 D2.4LAT:
Failed for HIGHLANDER:
Failed for CHR:
Failed for FORTUNER:
Failed for 25 HX DC 4X2 P 27L AT GLX RA/PICK UP:
Failed for PREVIA:
Failed for LAND CRUISER:
Failed for GXL RA (STATION WAGON):
Failed for 25PR 5 DR P 2.4L AT:
Failed for 26HX DC 4X4 PLAT:
Failed for 2 HX DC 4X4 P 2.7LAT:
Failed for TACOMA:
Failed for 26 HX DC 4X4 D 2.4L AT:
Failed for 25 HX DC 4X4 P .LAT:
Failed for TOYOTA - 26 HX DC 4X4 D 2.4L AT:
Failed for 25 HX DC 4X4:
Failed for DLX FA (PICK UP):
Failed for 26 HX DC 4X4 P 2.7LAT:
Failed for WIGO:
Failed for 4RUNNER:
Failed for LITEACE:
Failed for UNKNOWN:
Failed for UNKNOWN:
Failed for T100:
Failed for كورولا:
Failed for TAKOMA PICK UP CARGO:
Failed for HX DC 4X4 D 2.4L AT:
Failed for SEQUOIA:
Failed for SIENNA:
Failed for 26 HX DC 4X4D:
Failed for UNKNOWN:
Failed for CELICA:
Failed for TANDRA:
Failed for SCION:
Failed for URBAN CRUISER:
Failed for 25 HX DC 4X4 PLAT GLX RA(PICK UP):
Failed for RAV4:
Failed for DLX FA (PICK UP):
Failed for FJ CRUISER:
Failed for SUPRA:
Failed for TANDRA PICK UP DOUBLE CABIN:
Failed for CHR:
Failed for TUNDRA:
Failed for H 530:
Failed for CROWN V:
Failed for TAKOMA:
Failed for TUNDRA:
Failed for TACOMA:
Failed for VENZA:
Failed for VAN:
Failed for ALLION:
Failed for PICKUP:
Failed for TOYOTA RUSH:
Failed for LAND CRUISER:
Failed for LAND CRUISER:
Failed for PRIUS:
Failed for HILUX:
Failed for TOYOTA IQ:
Failed for LAND CRUISER:
Failed for MIRAI:
Failed for TOYOTA VELOZ:
Failed for TAKOMA:
Failed for AVALON:
Failed for HI ACE:
Failed for TOYOTA:
Failed for 26 LP SC 4X4 P4.0L AT:
Failed for SEQUOIA:
Failed for BZ4X:
Failed for COUPE:
Failed for HAI LUX:
Failed for SCION:
Failed for GXR RA(STATION WAGON):
Failed for RAV 4:
Failed for TOYOTA:
Failed for TOYOTA 86:
Failed for SUPRA:
Failed for FORTUNER:
Failed for INNOVA:
Failed for TOYOTA 86:
Failed for AVANZA:
Failed for 4 RUNNER:
Failed for TOYOTA 86:
Failed for TACOMA:
Failed for PRIUS:
Failed for ZELAS:
Failed for TOYOTA 86:
Failed for TOYOTA 86:
Failed for CRESSIDA:

MergeError: Passing 'suffixes' which cause duplicate columns {'current_msrp_x'} is not allowed.

In [20]:
data

,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,current_msrp
0,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,SILVER,TAIWAN,1000.0,5.0,None
1,2015.0,TOYOTA,HIACE,GLX,MINI BUS,GCC,4.0,WHITE,JAPAN,2000.0,2.0,None
2,2015.0,TOYOTA,HIACE,DX,MINI BUS,GCC,4.0,WHITE,JAPAN,1837.0,15.0,None
3,2015.0,TOYOTA,HILUX,DL,PICKUP DOUBLE CAB,GCC,4.0,WHITE,JAPAN,1837.0,5.0,None
4,2001.0,TOYOTA,CAMRY,XLI,SEDAN,NON-GCC,4.0,BROWN AND BEIGE,USA,1481.0,5.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...
239209,2019.0,TOYOTA,HILUX,GLX,PICKUP,GCC,6.0,WHITE/PEARLS,INDIA,NaN,5.0,None
239210,2025.0,TOYOTA,LAND CRUISER,NaN,SUV,GCC,6.0,BLACK,JAPAN,NaN,7.0,NaN
239211,2021.0,TOYOTA,LAND CRUISER,GXR,SUV,GCC,8.0,WHITE/PEARLS,JAPAN,NaN,8.0,None
239212,2025.0,TOYOTA,LAND CRUISER,GXL,SUV,GCC,4.0,WHITE/PEARLS,JAPAN,NaN,7.0,None
239213,2021.0,TOYOTA,YARIS,E,SEDAN,GCC,4.0,WHITE,INDIA,NaN,5.0,None