In [1]:
import pandas as pd

df = pd.read_csv("vin_data_grouped.csv")

In [2]:
df.shape

(995047, 13)

In [9]:
df["make"].nunique()

217

In [12]:
# 1. Group models by make into a list of unique values
grouped = df.dropna(subset=["make", "model"]).groupby("make")["model"].unique()

# 2. Print the Make, then loop through its sorted models
for make, models in sorted(grouped.items()):
    print(f"\n=== {make} ===")
    for model in sorted(models):
        print(f"  - {model}")

=== ABARTH ===
  - 124 SPIDER
  - 2024
  - 330-25
  - 595
  - 675SR
  - 695
  - ES 3
  - PARTNER

=== ACURA ===
  - ACURA LX
  - INTEGRA
  - RDX
  - RSX
  - TL
  - TLX

=== AFTEK ===
  - TR170

=== AITO ===
  - DRAGSTER
  - M7
  - M9

=== AL DAMANI ===
  - DMV 300

=== ALFA ROMEO ===
  - 147
  - 156
  - 159
  - 4C
  - ALFA ROMEO 4C
  - BRERA
  - GIULIA
  - GIULIETTA
  - GTV
  - Giulia
  - H9
  - MITO
  - STELVIO
  - TONALE

=== APULUO ===
  - APULUO AP200 4H

=== ARI ===
  - ATOM

=== ASHOK LEYLAND ===
  -  PARTNER
  - 2013
  - 2021
  - 2022
  - 2024
  - ASHOK LEYLAND
  - ASHOK LEYLAND FA
  - FALCON
  - LEYLAND
  - LIGHT TRUCK
  - OUSTER
  - OYSTER
  - PARTNER
  - SCHOOL BUS

=== ASTON MARTIN ===
  - DB11
  - DB12
  - DB9
  - DBS
  - DBX
  - DBX 707
  - DBX707
  - RAPIDE
  - RAPIDE S
  - VALHALLA
  - VALOUR
  - VANQUISH
  - VANTAGE
  - VIRAGE
  - Vanquish
  - Vantage

=== AUDI ===
  - 100
  - 2006
  - 2012
  - A 8
  - A1
  - A3
  - A4
  - A5
  - A6
  - A7
  - A8
  - AUDI RS Q8
  - E TRON
  - E-TRON
  - E-TRON GT
  - Q2
  - Q3
  - Q3 SPORTBACK
  - Q4
  - Q4 E TRON
  - Q5
  - Q6 E-TRON
  - Q7
  - Q8
  - Q8 E-TRON
  - R8
  - RS 3 SPORTBACK HATCHBACK
  - RS 5
  - RS E-TRON GT
  - RS Q8
  - RS3
  - RS4
  - RS5
  - RS6
  - RS7
  - RSQ 8
  - RSQ3
  - RSQ8
  - S3
  - S4
  - S5
  - S6
  - S7
  - S8
  - SQ5
  - SQ6 E-TRON
  - SQ7
  - SQ8
  - TT

=== AYED ===
  - 2023
  - AYED 250 H7
  - AYED 250H 7 RST250
  - AYED BIKE AYED250
  - AYED BIKE AYED250N
  - AYED250H 7 RS
  - AYED250N 3 G
  - BIKE 150T FORCE
  - D250N

=== BAIC ===
  - A1
  - A115
  - A520T
  - BJ 40
  - BJ30
  - BJ30E
  - BJ40
  - BJ40 C
  - BJ40 PLUS
  - BJ40 PRO
  - BJ40L
  - BJ40PRO
  - BJ60
  - BJ80
  - BJJ40 PLUS
  - GRAND TIGER
  - KENBO S6
  - MONGOOSE 270
  - U5 PLUS
  - US PLUS
  - VESPA VXL
  - X35
  - X55
  - X65
  - X7

=== BAJAJ ===
  - 100
  - 100CT
  - 125CC
  - 150
  - 150 CC
  - 150 CC/MOTORCYCLE
  - 150/MOTORCYCLE
  - 150BM
  - 150CC
  - 150CC DELIVERY BIKE
  - 150CE
  - 159CC
  - 15M. OF PASS.
  - 180
  - 180 CC
  - 180CC
  - 2007
  - 2008
  - 2009
  - 200CC
  - 2012
  - 2013
  - 2014
  - 2015
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021
  - 2022
  - 2023
  - 2024
  - 2025
  - 2026
  - 220
  - 220 CC
  - 220CC
  - 250
  - 50 CC/MOTORCYCLE DELIVERY
  - ACCORD
  - AP200 4H
  - APACHE 160
  - AVENGER
  - AVENGER 220
  - AVENGER 220 CC
  - AVENGER 220 CC CRUISE
  - Avenger 160
  - Avenger 220
  - B 150
  - BAJAJ
  - BAJAJ - 150
  - BAJAJ 100CT
  - BAJAJ 150
  - BAJAJ 150 CC
  - BAJAJ 150BM
  - BAJAJ 150CC
  - BAJAJ 180 CC
  - BAJAJ 180CC
  - BAJAJ 200CC
  - BAJAJ 220 CC
  - BAJAJ 220CC
  - BAJAJ AVENGER
  - BAJAJ BALZAR
  - BAJAJ C 150
  - BAJAJ DISCOVER
  - BAJAJ MINI 150
  - BAJAJ PULSAR 150
  - BAJAJ-220CC
  - BAJAJA
  - BAJAL 15M.
  - BALZAR
  - BK9E
  - BM 150
  - BM150CC
  - BOXER
  - BULSAR
  - C 150
  - C 180
  - C 200
  - C 220
  - CC 200
  - CC 220
  - CC150
  - CITY 100
  - CNI 180
  - CS 220
  - CT 100
  - CT 110
  - DELIVERY MOTORCYCLE
  - DISCOVER
  - DOMINAR
  - DOMINAR 400
  - DOMINAR 400CC
  - DOMINOR
  - DOMINOR 400CC
  - FLHTCUI
  - GALAXY M13 5G
  - GRS 4531
  - MI SI 150
  - MI SI 180
  - MI TE 100
  - MINI 150
  - MINI C 150
  - MODEL 180
  - MODEL 2011
  - MODEL 2020
  - MODEL 2021
  - MODEL 2026
  - MOTORCYCLE
  - NCE UP
  - OTHERS
  - P150
  - POLSAR
  - PU
  - PUL.SAP. 150
  - PULS R 220CC
  - PULSAR
  - PULSAR 150
  - PULSAR 180
  - PULSAR 1800C
  - PULSAR 180C
  - PULSAR 180CC
  - PULSAR 200C
  - PULSAR 200CC
  - PULSAR 220
  - PULSAR 220C
  - PULSAR 220CC
  - PULSAR 80CC
  - PULSAR RS200
  - Platina 100
  - Pulsar 125
  - Pulsar 150
  - Pulsar 180
  - Pulsar 220F
  - Pulsar N250
  - Pulsar NS200
  - RH1250S/MOTORCYCLE
  - RS 660
  - SISU 180
  - SIXTIES 175
  - SLINGSHOT
  - STAR HLX150
  - SY150T
  - TV BAJAJ 220 CC
  - UNICORN
  - VANDER HILL
  - VELAIC
  - VENTURE
  - YZF R1
  - bmw
  - اف اكس 150 الترا
  - افينجر
  - بولسار
  - دراجة نارية
  - دراجة ناريه
  - سي 150
  - سي تي 100
  - مي سي 150
  - ميتي 100

=== BAOJUN ===
  - 2024
  - YEP/STATION

=== BAW ===
  - 212
  - 212(4WD)
  - M7

=== BENDA ===
  - 300
  - 450
  - 700

=== BENELLI ===
  - 302R
  - SPEED STORM
  - TNT 125
  - TNT 150
  - TNT15
  - TNT150
  - TRK 502
  - TRK502

=== BENTLEY ===
  - ARNAGE
  - AZURE
  - Arnage
  - Azure
  - BENTAYGA
  - BENTLEY GT
  - BROOKLANDS
  - BrookLands
  - CONTINENTAL
  - CONTINENTAL GT
  - Continental
  - ELGHT
  - FLYING SPUR
  - Flying Spur
  - GT
  - MULLINER
  - MULSANNE
  - TURBO

=== BETA ===
  - BEN P 6

=== BIMOTA ===
  - AYED250N 3

=== BLUE BIRD ===
  - VISION

=== BMW ===
  - 1 SERIES
  - 1 SERIES M COUPE
  - 1000 CC
  - 1000RR
  - 1000XR
  - 116I
  - 116i
  - 118 D
  - 118I
  - 118i
  - 120 COUPE
  - 1200 K
  - 1200K
  - 120I
  - 120i
  - 125I
  - 125i
  - 1300 GS
  - 1300RS
  - 135I
  - 135i
  - 14 EDRIVE 40
  - 15
  - 150 CC
  - 1M
  - 2012
  - 2021
  - 2022
  - 2023
  - 2024
  - 218 I GRAND
  - 218I ACTIVE TOURER
  - 218I GRAN COUP
  - 218I GRAN COUPE
  - 218i
  - 218i ACTIVE TOURER
  - 218i GRAN COUPE
  - 220
  - 220D
  - 220I
  - 220i
  - 225I ACTIVE TOURER
  - 225i ACTIVE TOURER
  - 228
  - 228I
  - 228I GRAN COUPE
  - 228i
  - 230I
  - 235
  - 235I
  - 3 SERIES
  - 316
  - 316I
  - 316i
  - 318
  - 318CI
  - 318Ci
  - 318I
  - 318i
  - 320
  - 320 I
  - 320 K
  - 320 SEDAN
  - 320 T
  - 3201
  - 32011
  - 320Ci
  - 320D
  - 320I
  - 320LI
  - 320i
  - 323
  - 323I
  - 323i
  - 325
  - 325 I
  - 325CI
  - 325Ci
  - 325I
  - 325XI
  - 325i
  - 328
  - 328 I
  - 328I
  - 328i
  - 330
  - 330 CI COUPE
  - 330 I
  - 330 IA
  - 330CI
  - 330Ci
  - 330E
  - 330I
  - 330i
  - 335
  - 335Ci
  - 335I
  - 335i
  - 340I
  - 340I M XDRIVE
  - 340i
  - 4 SERIES
  - 420 D
  - 420I
  - 420I
  - 420I GRAN COUPE
  - 420i
  - 428 GC
  - 428I
  - 428I GRAN COUPE
  - 428i
  - 430I
  - 430I GRAN COUPE
  - 430i
  - 435I
  - 435I GRAN COUPE
  - 435i
  - 440
  - 440I
  - 440I GRAN COUPE
  - 440i
  - 5 SERIES
  - 5 SERIES GT
  - 5 Series GT
  - 500CC
  - 520
  - 5201
  - 520D
  - 520I
  - 520i
  - 523I
  - 523i
  - 525
  - 525 1
  - 525 I
  - 5251
  - 525I
  - 525i
  - 528
  - 528 I
  - 5281
  - 528I
  - 528i
  - 530
  - 530E
  - 530I
  - 530Li
  - 530e
  - 530i
  - 535
  - 535I
  - 535i
  - 540
  - 540I
  - 540i
  - 545I
  - 550I
  - 550i
  - 6 SERIES
  - 6 SERIES GT
  - 630I
  - 630i
  - 635
  - 635 CSI
  - 635 Csi
  - 640
  - 640I
  - 640I GRAN COUPE
  - 640i
  - 640i GRAN COUPE
  - 645 CI
  - 645CI
  - 645Ci
  - 645i
  - 650
  - 650 F
  - 650I
  - 650I GRAN COUPE
  - 650i
  - 650i GRAN COUPE
  - 690 ENDURO
  - 7 SERIES
  - 7 SERIES 750I XDRIVE
  - 728I
  - 728IL
  - 730
  - 730I
  - 730LI
  - 730Li
  - 730i
  - 735I
  - 735LI
  - 735Li
  - 735i
  - 740
  - 740 I
  - 740 IA
  - 740 IAL
  - 7401
  - 740I
  - 740LI
  - 740LT
  - 740Li
  - 740i
  - 745I
  - 745LI
  - 745i
  - 750
  - 750 IA
  - 750 IAL
  - 750I
  - 750LI
  - 750Li
  - 750i
  - 760I
  - 760L
  - 760LI
  - 800MT
  - 840
  - 840CI
  - 840Ci
  - 840I
  - 840I GRAN COUPE
  - 840i
  - 840i GRAN COUPE
  - 850CI
  - 850Ci
  - ACTIVE HYBRID 7
  - AL E 750
  - ALPINA
  - AR NAET
  - B3
  - BMW
  - BMW 1000XR
  - BMW 120
  - BMW 1300 G S
  - BMW 1300 GS
  - BMW 15
  - BMW 230
  - BMW 235
  - BMW 318
  - BMW 320
  - BMW 3201
  - BMW 320I
  - BMW 323
  - BMW 323 TA
  - BMW 325
  - BMW 3251
  - BMW 328
  - BMW 330
  - BMW 330 CI
  - BMW 3301
  - BMW 330I
  - BMW 420
  - BMW 5 SERIES M6
  - BMW 520
  - BMW 523
  - BMW 525
  - BMW 525 T
  - BMW 5251
  - BMW 528
  - BMW 530
  - BMW 530 I
  - BMW 535
  - BMW 5351
  - BMW 535I
  - BMW 540
  - BMW 5501
  - BMW 550I
  - BMW 635
  - BMW 645
  - BMW 740
  - BMW 740LI
  - BMW 750
  - BMW 760
  - BMW 760LI
  - BMW AR NAET
  - BMW F 800 GS
  - BMW I5
  - BMW K 1600 B
  - BMW K1600B
  - BMW M 1000 RR
  - BMW M 235
  - BMW R 12
  - BMW R 1200
  - BMW R 1200 GS
  - BMW R 1200 GSADV
  - BMW R 1250 GS
  - BMW R 1250 R
  - BMW R 1300 GS
  - BMW R 18
  - BMW R NINET
  - BMW R1200RT
  - BMW R1250GS
  - BMW S 1000 RR
  - BMW X5
  - BMW Z3
  - BMW Z4
  - BMWR1250GS
  - C 400 GT
  - C 400 X
  - C 600
  - C 650
  - C 650 GT
  - C400GT
  - C400X
  - C650GT
  - CAR
  - CE 04
  - E 323
  - E 328
  - EDAN
  - F 800 GS
  - F 800 R
  - F 850 GS
  - F 900
  - F 900 GS
  - F 900 R
  - F 900 XR
  - F650GS
  - F7
  - F750GS
  - F800GS
  - F800GT
  - F800R
  - F800S
  - F850GS
  - F900 GS
  - F900R
  - F900XR
  - FLSTC
  - G 1250 GS
  - G 1300 GS
  - G 310 R
  - G310 GS
  - G310GS
  - G310R
  - G650 GS
  - HARLEY DAVIDSON
  - HERITAGE SOFTAIL
  - HP4
  - HYBRID 7
  - I3
  - I4 GRAN COUPE
  - I5
  - I7
  - I8
  - IQ
  - IX
  - IX 3
  - IX1
  - IX2
  - IX3
  - K 160 GTL
  - K 1600
  - K 1600 B
  - K 1600 GT
  - K 1600 GTL
  - K1200LT
  - K1200S
  - K1600B
  - K1600GT
  - K1600GTL
  - LI 750
  - M 1000 R
  - M 1000 RR
  - M 1000 XR
  - M 1000XR
  - M 235
  - M 235i
  - M 3
  - M 5
  - M135I
  - M2
  - M2
  - M2351
  - M235I
  - M235I GRAN COUPE
  - M235i GRAN COUPE
  - M240I
  - M240i
  - M3
  - M340I
  - M340i
  - M4
  - M4 COMPETITION
  - M440I
  - M440I GRAN COUPE
  - M5
  - M550I
  - M6
  - M6 GRAN COUPE
  - M760LI
  - M8
  - M8 GRAN COUPE
  - M8501
  - M850I
  - M850I GRAN COUPE
  - M850i
  - M850i GRAN COUPE
  - MBR 1300 GSA TRIPLE
  - MINI COUNTRYMAN
  - MOTOR CYCLE
  - MOTORCYCLE
  - R 1150 GS
  - R 12
  - R 12 (MOTORCYCLE)
  - R 1200
  - R 1200 GS
  - R 1200 GSADV
  - R 1200 RS
  - R 1250 GS
  - R 1250 R
  - R 1300 GS
  - R 1300 GS ADVENTURE
  - R 18
  - R 800
  - R NINET
  - R1200 GS
  - R1200C
  - R1200GS
  - R1200GS MOTORCYCLE
  - R1200GS RALLY
  - R1250
  - R1250 GS
  - R1250GS
  - R1250GS ADVENTURE
  - R12G S
  - R1300 GS
  - R1300GS
  - R9T
  - S 1000
  - S 1000 R
  - S 1000 RR
  - S1000
  - S1000 R
  - S1000ORR
  - S1000R
  - S1000RR
  - S1000RR (MOTORCYCLE)
  - S1000XR
  - SCOMADI 2001
  - SLING SHOT
  - SLINGS
  - SLINGSHOT SLINGS
  - SY150T
  - TRANS
  - UNKNOWN
  - VESPA
  - VESPA VXL
  - VESPA VXL 150
  - X 5
  - X 6
  - X1
  - X2
  - X3
  - X4
  - X5
  - X5 M
  - X6
  - X6 M
  - X7
  - XM
  - Z 3
  - Z1
  - Z3
  - Z4
  - Z8
  - i4 GRAN COUPE
  - i5
  - i7
  - iX
  - iX1
  - iX2
  - آي 330
  - اف 650 جي اس

=== BORGWARD ===
  - BX5
  - BX7
  - QUADSTER MOTORCYCLE

=== BRILLIANCE ===
  - 2007
  - FRV CROSS
  - H530
  - JINBEI
  - RANGE ROVER VOGUE
  - V5

=== BUELL ===
  - Lightning XB12S

=== BUGATTI ===
  - CHIRON
  - ENCORE
  - VEYRON

=== BUICK ===
  - ENCLAVE
  - PARK AVENUE
  - REGAL
  - RIVIERA

=== BYD ===
  - 2023
  - 2024
  - ATTO 3
  - ATTO3
  - B5
  - B8 JEEP
  - BYD
  - BYD SEAL
  - BYD SONG PLUS
  - C 11
  - D & N
  - D9
  - DENZA N9
  - DESTROYAR 05
  - DESTROYER 05
  - DOLPHIN
  - F3
  - FANGCHENGBAO 5
  - FORMULA LEOPARD
  - FORMULA LEOPARD S
  - HAN
  - HAN L
  - KUBBA
  - LBRD
  - LEOPARD
  - LEOPARD - 8
  - LEOPARD 05
  - LEOPARD 3
  - LEOPARD 5
  - LEOPARD 7
  - LEOPARD 7 (2WD)
  - LEOPARD 7 (4WD)
  - LEOPARD 7(2WD)
  - LEOPARD 7(4WD)
  - LEOPARD 7/STATION
  - LEOPARD 8
  - LEOPARD S/STATION
  - LEOPARD TAI3
  - N9
  - QIN
  - QIN L
  - QIN L DM
  - QIN PLUS
  - QIN PLUS(2WD)
  - QIN PRO
  - S6
  - SEA LION
  - SEA LION 07
  - SEA LION 07EV
  - SEAGULL
  - SEAL
  - SEAL 05
  - SEAL 06
  - SEAL 07
  - SEAL 50
  - SEAL 7
  - SEALION
  - SEALION 06
  - SEALION 7
  - SEALION 7 AWD
  - SEALION 7 RWD
  - SEALION 8
  - SEL 50
  - SHARK
  - SHARK (PICK UP)
  - SHARK 6
  - SLINGSHOT
  - SONG
  - SONG (2WD)
  - SONG FLAGSHIP
  - SONG L
  - SONG L/STATION
  - SONG PLUS
  - SONG PLUS DM
  - SONG PLUS EV
  - SONG PRO
  - T5DM
  - T5DM FORTUNE (HYBRID)
  - TANG
  - TI7 (STATION WAGON)
  - U8
  - UNKNOWN
  - VAN
  - XIA
  - XIA STATION
  - YUAN PLUS
  - YUAN UP

=== CADILLAC ===
  - 1984
  - 2013
  - ATS
  - BLS
  - BROGH
  - BROGHAM
  - BROUGHAM
  - BROUGHTAM
  - BROYGAM
  - BROYGHAM
  - CADILLAC
  - CADILLAC BROUGH
  - CADILLAC CEVEL
  - CADILLAC ELDORADO
  - CATERA
  - CEVEL
  - CT4
  - CT5
  - CT6
  - CTS
  - CTS-V
  - DEVILLE
  - DEVILLE/COUPE
  - DHS
  - DTS
  - De Ville
  - ELDORADO
  - ELDORADO / COUPE
  - ELDORADO/COUPE
  - ESCALADE
  - ESCALADE ESV
  - ESCALD/PICK UP DOUBLE CABIN
  - Escalade
  - FLAT WOOD
  - FLAT WOOD SEDAN
  - FLEETWOOD
  - Fleetwood
  - IQ
  - LYRIQ
  - OTHERS
  - SEVILLE
  - SRX
  - STS
  - STS-V
  - XLR
  - XT4
  - XT5
  - XT6
  - XTS

=== CAN-AM ===
  - CAN
  - CAN-AM SPYDERRT-S
  - CANYON REDR
  - RYKER
  - SPYDER
  - SS MAVR MAX XRS
  - SSV

=== CATERHAM ===
  - SEVEN

=== CATERPILLAR ===
  - 422 F

=== CFMOTO ===
  - 150NK
  - 150SC
  - 2025
  - 45 SR
  - 450 CLC
  - 450 MT
  - 450M
  - 450NK
  - 450SR
  - 650GT
  - 650NK
  - 675NK
  - 675SR
  - 700CL - X
  - 700CL-X
  - 800
  - 800MT
  - 800NK
  - ATHENA
  - CABALLERO DELUXE
  - CF 600
  - CF 650
  - CF MOTO 650
  - CF250T6A
  - MOTOR CYCLE 300CC
  - RYKER
  - SPYDER
  - SS450

=== CHAMP ===
  - 500RR

=== CHANGAN ===
  - 07
  - 11
  - 12
  - 2022
  - 2024
  - 2025
  - 35
  - 5028SC
  - ALSVIN
  - AVATAR
  - AVATAR 07
  - AVATAR 11
  - AVATAR 12
  - AVATR 12
  - BENBEN E STAR
  - CH150T-34
  - CHANGAN
  - CM 10
  - CS 35
  - CS 95
  - CS35
  - CS35 PLU
  - CS35 PLUS
  - CS55
  - CS55 PLUS
  - CS55 PLUSE
  - CS75
  - CS75 (4WD)
  - CS75 PLUS
  - CS85
  - CS95
  - DEEPAL
  - DEEPAL S05
  - DEEPAL S09
  - E STAR
  - EADO
  - EADO PLUS
  - EM80
  - FAIRUZA
  - FENGJING
  - G318
  - HAOLV R
  - HAOLV RV
  - HUNTER
  - HUNTER/MOTER HOME
  - JEEP
  - K50
  - MDX
  - MINIEV
  - MOTORCYCLE
  - OTHERS
  - OUSHAN
  - Q5
  - QIYUAN
  - QIYUAN Q05
  - QNE 07
  - QNE 07/SEDAN
  - ROCKY
  - S05
  - S07
  - S09
  - SC6406AAD6(VAN)
  - UNI K
  - UNI T
  - UNI Y
  - UNI-K
  - UNI-T
  - UNI-V
  - UNIK
  - UNIT
  - UNIV
  - UNIVERSAL
  - VAN
  - X5
  - X5 PLUS
  - سي اس 35

=== CHANGHUA ===
  - 750 CC
  - CH150
  - CH150T-34
  - MAX PRO
  - MAX180 (MOTORCYCLE)
  - MOTORCYCLE

=== CHERY ===
  - 03
  - 03T
  - 2025
  - 7
  - ARIIZO 3
  - ARRIZO
  - ARRIZO 3
  - ARRIZO 5
  - ARRIZO 6 PRO
  - ARRIZO 7
  - ARRIZO 8
  - ARRIZO 8 PRO
  - ARRIZO5
  - ARRIZO7
  - BUS
  - C5
  - CHERY
  - CHERY TIGGO
  - E5
  - EASTAR
  - EQ 1
  - ES
  - ET
  - EXEED LX
  - EXEED RX
  - ICAR 03
  - ICAR V23
  - ICAR V23(2WD)
  - ICAR V27
  - J5
  - J7
  - JAECOO J5 (2WD)
  - JAECOO J7
  - KARRY
  - LEPAS L6
  - LX
  - MY26RX T41 PHEV
  - NISSAN TIIDA
  - P 5
  - R 7
  - RELY RB (PICK UP)
  - ROCKY
  - RX
  - RX 2.0 T
  - RX PHEV
  - TIGGO
  - TIGGO 3
  - TIGGO 4 PRO
  - TIGGO 5
  - TIGGO 7
  - TIGGO 7 PRO
  - TIGGO 7 PRO MAX
  - TIGGO 8
  - TIGGO 8 PRO
  - TIGGO 8 PRO MAX
  - TIGGO 9
  - TIGGO8FL (4WD)
  - TXL
  - UNKNOWN
  - V23
  - V27
  - VX
  - iCAR

=== CHEVROLET ===
  - 1998
  - 2002
  - 2003
  - 2007
  - 2010
  - 2013
  - ABIQA
  - ALKAMENOS SINGLE-C
  - ASTRO
  - AVALANCHE
  - AVEO
  - Astro
  - Avalanche
  - Aveo
  - BLAZER
  - BOLT EV
  - Blazer
  - C 10
  - C-10
  - C/K 1500
  - C10
  - C20
  - C5500
  - CAMAR
  - CAMARO
  - CAMARO LTZ
  - CAMARO SS
  - CAPRI
  - CAPRICE
  - CAPRICE CLASSIC
  - CAPRICE CLASSIC SEDAN
  - CAPRICE LS
  - CAPRICE SS
  - CAPRICE SS SEDAN
  - CAPTIVA
  - CAVALIER
  - CHEVROLET
  - CHEVROLET BLAZER
  - CHEVROLET CHEVY
  - CHEVROLET EL CAMI
  - CHEVROLET EXPRESS
  - CHEVROLET LAUGH
  - CHEVY
  - COLORADO
  - CORVETTE
  - CRUIZ
  - CRUZE
  - Camaro
  - Caprice
  - Captiva
  - Colorado
  - Corvette
  - DAIMLER DOUBLE
  - DEFENDER
  - ENVOY
  - EPICA
  - EQUINOX
  - EXPRESS
  - EXPRESS VAN PASSENGER
  - Epica
  - Equinox
  - G20 (VAN)
  - GMT 400
  - GROOVE
  - Groove
  - IMPALA
  - Impala
  - LACETTI
  - LAF
  - LUMINA
  - LUV
  - LUV/PICK UP DOUBLE CABIN
  - Lumina
  - MALIBU
  - MALIBU 400
  - MALIBU SEDAN
  - MENLO
  - MODEL 2017
  - Malibu
  - NINJA 300
  - OPTRA
  - Optra
  - S 10
  - S 10 PICK UP CARGO
  - S10
  - SAVANA
  - SELVERADO
  - SIERRA
  - SILVER
  - SILVERADO
  - SILVERADO K3500
  - SILVERADO PICK UP DOUBLE
  - SLINGSHOT
  - SMB
  - SONEK SEDAN
  - SONIC
  - SONIC LS
  - SPARK
  - SPARK EUV
  - SSR
  - SUBURBAN
  - SUPER 800 - 3
  - SUPERBAN
  - Silverado
  - Sonic
  - Spark
  - Suburban
  - TAHOE
  - TAHOE K1500 (4WD)
  - TRAILBLAZER
  - TRAVERSE
  - TRAVERSE STATION
  - TRAX
  - TRAX LS
  - TRAX LT
  - TRAX RS
  - Tahoe
  - Tracker
  - Trailblazer
  - Traverse
  - UNKNOWN
  - UPLANDER
  - VENTURE
  - VOLT

=== CHRYSLER ===
  - 200
  - 200C
  - 300
  - 300 C
  - 300 SEDAN
  - 300/SEDAN
  - 300C
  - 300S
  - C 300
  - C 300 SEDAN
  - CHRYSLER 300
  - CHRYSLER TWON ANC
  - CROSSFIRE
  - FIFTH AVENUE
  - GRAND VOYAGER
  - NEON
  - PACIFICA
  - PROWLER
  - PT CRUISER
  - Pacifica
  - S 300
  - SEBRING
  - TOWN AND COUNTRY
  - VOYAGER

=== CITROEN ===
  - 2CV6
  - BERLINGO
  - C-ELYSEE
  - C3
  - C3 AIRCROSS
  - C4
  - C4 AIRCROSS
  - C4 GRAND PICASSO
  - C4X
  - C5
  - C5 AIRCROSS
  - CITROEN C1
  - CITROEN C2
  - CITROEN C3
  - CITROEN C5
  - DS
  - DS3
  - DS5
  - JUMPY
  - JUMPY PANEL VAN XL
  - SPACETOURER

=== CMC ===
  - 2010
  - 2013
  - 7Z
  - CPC
  - D260
  - D260 PANEL VAN
  - D270
  - PANEL
  - PANEL VAN
  - VAN CARGO
  - VERICA
  - VERYCA
  - Z7
  - فان شحن

=== DAEWOO ===
  - 090 BS
  - 106 BF
  - DAEWOO 106 BF
  - K6EGF
  - LESTAR
  - NOVUS7542

=== DAF ===
  - XF105.410

=== DAIHATSU ===
  - 1992
  - 1999
  - 20000
  - 2001
  - 2005
  - 2007
  - 2008
  - CHARADE
  - D
  - DAIHATSU
  - DAIHATSU DELTA
  - DAIHATSU FEROZA
  - DAIHATSU TERIOS
  - DALTA
  - DELTA
  - GRAN MAX
  - GRAN MOVE
  - GRAND MAX
  - GRAND MAX VAN CARGO
  - Grand Max
  - MATERIA
  - ROCKY
  - SIRION
  - TERIOS
  - Terios
  - YRV
  - delta

=== DATSUN ===
  - 280
  - DATSUN ZX 280
  - ZX 280
  - ZX 280 COUPE
  - ZX 300

=== DELOREAN ===
  - DELOREAN

=== DFSK ===
  - 2022
  - 35C VAN CARGO
  - C31
  - C32
  - C35
  - DFSK
  - E5 PLUS
  - FENGON 500
  - FENGON 580
  - FENGON 600
  - FENGON C31
  - FENGON C32
  - FENGON GLORY
  - FENGON GLORY 580
  - FENGON GLORY 600
  - FENGON GLORY IX7
  - FENGON IX5
  - PICK UP 32
  - V21

=== DODGE ===
  - 1500
  - AVENGER
  - CALIBER
  - CARAVAN
  - CHALLENGER
  - CHARGER
  - CHARGER R
  - Caliber
  - Challenger
  - Charger
  - DAKOTA
  - DART
  - DODGE DURANGO
  - DODGE GRAND
  - DODGE GRAND CARAVAN
  - DODGE JOURNEY
  - DODGE RAM
  - DURANGO
  - Dart
  - Durango
  - GRAND CARAVAN
  - HORNET GT
  - JOURNEY
  - MAGNUM
  - NEON
  - NITRO
  - Neon
  - Nitro
  - RAM
  - RAM
  - RAM 1500
  - RAM 1500/PICK UP DOUBLE CABIN
  - RAM 2500
  - RAM 2500/PICK UP DOUBLE CABIN
  - RAM PROMASTER
  - RAM SINGLE-CABIN PICK
  - Ram
  - SPRINTER
  - STEALTH
  - VIPER
  - Viper
  - X7

=== DONGFENG ===
  - 007
  - 2022
  - 2024
  - 2025
  - 7
  - 817
  - A X 7
  - AX7
  - C35
  - CAPTAIN E
  - DFH 1180
  - DONGFENG DOLLICA
  - DONGFENG HERO
  - DOUBLE CABIN PICK UP
  - DREAMER
  - EICHER PRO 2000
  - FORTHING T5
  - FORTHING T5 HEV
  - FREE
  - K33 513
  - K33-561
  - K33-56B
  - LIGHT PICKUP
  - M 5
  - M HERO 917
  - M-HERO M817
  - M5
  - MAGE
  - MHERO M817
  - P16
  - P16 121/PICK UP DOUBLE CABIN
  - P16-111
  - P16-121
  - P16.111
  - PICK UP
  - S7
  - SHINE
  - SHINE MAX
  - T5 EVO
  - T5 HEV
  - TRANSPORTER T5
  - U-TOUR
  - V9
  - VESPA 150
  - Z9
  - Z9 PICK UP
  - ZN1032UCM5A

=== DORCEN ===
  - DOMY X7
  - Domy X7
  - G70S

=== DUCATI ===
  -  MONSTER
  - DEVILLE
  - DIAVEL
  - DIAVEL1260S
  - DUCATI
  - DUCATI 400 CC
  - DUCATI 899
  - DUCATI DIAVEL
  - DUCATI MONSTER
  - DUCATI PANIGALE
  - DUCATI PANIGALE 959
  - DUCATI PANIGALE V2
  - DUCATI SCRAMBLER
  - DesertX
  - Diavel 1260
  - HYPERMOTARD
  - HYPERMOTARD SP
  - MONSTER
  - MONSTER 821
  - MULTISTRADA
  - Monster
  - Monster 1200
  - Monster 821
  - Multistrada V2
  - PANIGALE
  - PANIGALE 959
  - PANIGALE V4R
  - Panigale V2
  - Panigale V4
  - RYKER
  - SCRAMBLER FULL
  - SUPERBIKE848
  - Streetfighter V2
  - Streetfighter V4
  - X DIAVEL S

=== ECOWAY ===
  - CPX110
  - H 9 PRO

=== EICHER ===
  - 1040
  - 1060
  - 1060 G
  - 2006
  - PRO 2065XP
  - SKY LINE

=== ELECTRIC MOTION ===
  - ePure

=== EMPALA ===
  - EM 01
  - EM 01 (ELECTRIC BIKE)
  - EM01

=== FANTIC ===
  - CABALLERO / MOTORCYC

=== FARIZON ===
  - SUPERVAN

=== FAW ===
  - B70
  - B70S
  - BESTUNE T99
  - BESTURN B50
  - BESTURN X40
  - CA3182P
  - CA7188A
  - E-QM5
  - EHS9
  - F7
  - H5

In [14]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(df[["make", "model"]].drop_duplicates())

                     make                                        model
0                  TOYOTA                                      COROLLA
1                  TOYOTA                                        HIACE
3                  TOYOTA                                        HILUX
4                  TOYOTA                                        CAMRY
5                  TOYOTA                                 LAND CRUISER
6                  TOYOTA                                        YARIS
9                  TOYOTA                                   FJ CRUISER
10                 TOYOTA                                         RAV4
24                 TOYOTA                                       TUNDRA
25                 TOYOTA                                       AVALON
27                 TOYOTA                                     FORTUNER
35                 TOYOTA                                      COASTER
48                 TOYOTA                                       INNOVA
49                 TOYOTA                                       SIENNA
62                 TOYOTA                                       TACOMA
63                 TOYOTA                                        PRADO
67                 TOYOTA                         LAND CRUISER PICK UP
73                 TOYOTA                                         RUSH
75                 TOYOTA                                        PRIUS
80                 TOYOTA                                       AVANZA
150                TOYOTA                                      SEQUOIA
192                TOYOTA                                        SUPRA
198                TOYOTA                                       AURION
203                TOYOTA                                         ECHO
223                TOYOTA                                       PREVIA
235                TOYOTA                                         BZ4X
236                TOYOTA                                     LITE ACE
238                TOYOTA                                COROLLA CROSS
277                TOYOTA                                         C-HR
309                TOYOTA                                           XA
312                TOYOTA                                      GRANVIA
319                TOYOTA                                        VELOZ
333                TOYOTA                                        RAIZE
420                TOYOTA                                           iQ
493                TOYOTA                                 TOYOTA CAMRY
528                TOYOTA                       LAND CRUISER PICKUP 70
551                TOYOTA                                           FJ
563                TOYOTA                                        CROWN
583                TOYOTA                                           86
724                TOYOTA                                      4RUNNER
804                TOYOTA                                  COROLLA 1.6
1002               TOYOTA                                URBAN CRUISER
1054               TOYOTA                                        SCION
1432               TOYOTA                                       SOLARA
1484               TOYOTA                                           IQ
1510               TOYOTA                                   HIGHLANDER
1524               TOYOTA                                       OTHERS
1612               TOYOTA                                         DYNA
1784               TOYOTA                                  LAND CRUISE
1864               TOYOTA                              LAND CRUISER 70
2156               TOYOTA                                       TERCEL
2719               TOYOTA                                      LITEACE
3105               TOYOTA                                       MATRIX
3964               TOYOTA                                        RAV 4
4084               TOYOTA                                         GR86
4157               TOYOTA                                        LEVIN
4531               TOYOTA                                        ZELAS
4883               TOYOTA                                      ALPHARD
7438               TOYOTA                                 TOYOTA VELOZ
9524               TOYOTA                                        T 300
10263              TOYOTA                                     4 RUNNER
10556              TOYOTA                          TOYOTA LAND CRUISER
12564              TOYOTA                                  COROLLA 1.3
13355              TOYOTA                           LAND CRUISER PRADO
13819              TOYOTA                                     CRESSIDA
15573              TOYOTA                             LAND CRUISER VXR
17649              TOYOTA                                 CROWN KLUGER
19957              TOYOTA                                         2023
20488              TOYOTA                                       بريفيا
20843              TOYOTA                                       TAKOMA
22023              TOYOTA                                         2009
22759              TOYOTA                                        كامري
22851              TOYOTA                                 TOYOTA PRIUS
23102              TOYOTA                                 TOYOTA ALTIS
23342              TOYOTA                                  COROLLA 1.8
23646              TOYOTA                                        ALTIS
23701              TOYOTA                                      HAIULUX
26149              TOYOTA                                       استیشن
27490              TOYOTA                               TOYOTA ALPHARD
28419              TOYOTA                               TOYOTA COROLLA
29420              TOYOTA                                TOYOTA TACOMA
30103              TOYOTA   JUSTIN BIEBER X VESPA 150 E5 GSO (SCOOTER)
32595              TOYOTA                                         BZ3X
34238              TOYOTA                                COROLLA SEDAN
34758              TOYOTA                         بيك اب كابينه مزدوجه
34860              TOYOTA                           26HX DC 4X4P2.7LAT
36686              TOYOTA                                  COROLLA 1.5
36819              TOYOTA                   LAND CRUISER PICK UP CARGO
39477              TOYOTA                                       SALOON
39749              TOYOTA                                      PICK UP
40823              TOYOTA                                       RUMION
41084              TOYOTA                                          MR2
42092              TOYOTA                                       TOYOTA
42485              TOYOTA                                TOYOTA PREVIA
43857              TOYOTA                                         WISH
43898              TOYOTA                           25 LP SC4X44.0L MT
45155              TOYOTA                                       HD 4X4
45816              TOYOTA                                       FLTRXS
46493              TOYOTA                                        DAINA
48958              TOYOTA                                       TANDRA
50038              TOYOTA                       LAND CRUISER / STATION
51410              TOYOTA                                         BZ 4
51867              TOYOTA               LAND CRUISER SINGLE-CABIN PICK
51893              TOYOTA                                       SY150T
54330              TOYOTA                                      STATION
55325              TOYOTA                                TOYOTA TUNDRA
58567              TOYOTA                                      HAI LUX
59587              TOYOTA                                     هاي لوكس
60425              TOYOTA                                          NaN
63139              TOYOTA                                     HILUX RE
64425              TOYOTA                                         KS01
64561              TOYOTA                                        VENZA
64732              TOYOTA                         25 HX DC 4X4D 2.4LAT
69365              TOYOTA                                         MR 2
69902              TOYOTA                                   لاند كروزر
70143              TOYOTA                                   كورولا 1.8
70609              TOYOTA                                       SICION
70741              TOYOTA                                        MT 03
70976              TOYOTA                                       TOKOMA
76409              TOYOTA                                         2022
77421              TOYOTA                         25 LP SC 4X4 P4.0 MT
77426              TOYOTA                                       CELICA
79506              TOYOTA                                         2016
80409              TOYOTA                                        T 100
82205              TOYOTA                                         2012
87376              TOYOTA                           TOYOTA COROLLA 1.6
89374              TOYOTA                                       ALFARD
89550              TOYOTA                                     PRADO GX
89967              TOYOTA                                         1999
91234              TOYOTA                                حافلة نقل خاص
93366              TOYOTA                                 TOYOTA PRADO
93971              TOYOTA                                       HIACE
94040              TOYOTA                          25 HX DC 4X4 2.7LAT
94775              TOYOTA                             GLX DA (PICK UP)
95443              TOYOTA                                       RUNNER
99779              TOYOTA                                  GRAND DELUX
100693             TOYOTA                                       ALLION
103087             TOYOTA                                         VIOS
103983             TOYOTA                                   SIENNA VAN
107953             TOYOTA                                 TOYOTA SCION
108961             TOYOTA                               TOYOTA 4RUNNER
111402             TOYOTA                                         SENA
114167             TOYOTA                                    TOYOTA IQ
114309             TOYOTA                                       SIERRA
116844             TOYOTA                                       SELICA
117226             TOYOTA                                        راف ٤
117384             TOYOTA                           SENA VAN PASSENGER
118421             TOYOTA                            COROLLA 1.6/SEDAN
119964             TOYOTA                                   MODEL 2022
121809             TOYOTA                                         2014
128406             TOYOTA                              LAND CRUISER GX
129588             TOYOTA                                PICK UP CABIN
130240             TOYOTA                                 TOYOTA SUPRA
131268             TOYOTA                                         1998
132258             TOYOTA                                 TOYOTA HILUX
134869             TOYOTA                                  SUPRA COUPE
136279             TOYOTA                                 2 HX DC 4X40
139359             TOYOTA                             TACOMA (PICK UP)
139368             TOYOTA                                   HI S COACH
139417             TOYOTA                   LAND CRUISER/PICK UP CARGO
140500             TOYOTA                                  FRONTLANDER
143227             TOYOTA                        COROLLA SEDAN / HATCH
143289             TOYOTA                          25 CA SON P 2.5L AT
143808             TOYOTA                                STREET TRIPLE
143873             TOYOTA                                         AQUA
144977             TOYOTA                                VESPA VXL 150
145508             TOYOTA                                       GS 300
147307             TOYOTA                         25 HX DC 4X4P 2.7LAT
148418             TOYOTA                                   COROLLA LI
148581             TOYOTA                             GLX RA (PICK UP)
149543             TOYOTA                                    VESPA VXL
151726             TOYOTA                                      هايلوكس
153325             TOYOTA                                 TOYOTA HIACE
153355             TOYOTA                                        افنزا
153396             TOYOTA                                       CORONA
153452             TOYOTA                             LAND CRUISER GXR
153567             TOYOTA                                        FLHTK
153858             TOYOTA          26 YA HB P 1.6L AT TURBO GR RA(CAR)
154317             TOYOTA                          26HX DC 4X4D2.4L AT
154993             TOYOTA                                  RAV4 LE CAR
155925             TOYOTA                                 TOYOTA SQUIN
157173             TOYOTA                                        SIENA
157653             TOYOTA                           TOYOTA COROLLA 2.0
159013             TOYOTA                          26 HX DC 4X4 2.4LAT
159397             TOYOTA                          26HX DC 4X4 D2.4LAT
160028             TOYOTA                                       STANZA
160065             TOYOTA                                          CHR
161528             TOYOTA                             TUNDRA (PICK UP)
161906             TOYOTA         25 HX DC 4X2 P 27L AT GLX RA/PICK UP
163940             TOYOTA                       GXL RA (STATION WAGON)
163990             TOYOTA                          25PR 5 DR P 2.4L AT
164218             TOYOTA                             26HX DC 4X4 PLAT
164433             TOYOTA                         2 HX DC 4X4 P 2.7LAT
164708             TOYOTA                                       تاكوما
164806             TOYOTA                                        كامرى
165131             TOYOTA                       26 HX DC 4X4 D 2.4L AT
165143             TOYOTA                          25 HX DC 4X4 P .LAT
165641             TOYOTA              TOYOTA - 26 HX DC 4X4 D 2.4L AT
166080             TOYOTA                                        SPINA
166082             TOYOTA                              YARIS HATCHBACK
166701             TOYOTA                                 25 HX DC 4X4
166725             TOYOTA                             DLX FA (PICK UP)
167024             TOYOTA                        26 HX DC 4X4 P 2.7LAT
167360             TOYOTA                          KING LONG PASSENGER
167387             TOYOTA                                         WIGO
170288             TOYOTA                                           R1
171080             TOYOTA                                         2024
171261             TOYOTA                                  SIENNA(VAN)
171526             TOYOTA                                           U7
171551             TOYOTA                                         T100
171870             TOYOTA                              HILUX ADVENTURE
172127             TOYOTA                                       كورولا
172213             TOYOTA                         TAKOMA PICK UP CARGO
172395             TOYOTA                          HX DC 4X4 D 2.4L AT
172916             TOYOTA                                   GL770ULTRA
173200             TOYOTA                                26 HX DC 4X4D
174043             TOYOTA                                        ORION
175486             TOYOTA                                   كورولا 1.3
177452             TOYOTA                                        برادو
177495             TOYOTA            25 HX DC 4X4 PLAT GLX RA(PICK UP)
179288             TOYOTA                          PARISIENNE BROUGHAM
180754             TOYOTA                       COROLLA 1.5L/HATCHBACK
181793             TOYOTA                  TANDRA PICK UP DOUBLE CABIN
185238             TOYOTA                                        H 530
185537             TOYOTA                                         2008
185587             TOYOTA                               TOYOTA CENTURY
185640             TOYOTA                                      CROWN V
186727             TOYOTA                                      NIO ES8
188213             TOYOTA                                       RAFF 4
188981             TOYOTA                                          900
189478             TOYOTA                                          VAN
191953             TOYOTA                                       PICKUP
191998             TOYOTA                                  TOYOTA RUSH
192045             TOYOTA                               DYNA VAN CARGO
195435             TOYOTA                                           H3
198225             TOYOTA                   LAND CRUISER/STD EX PICKUP
198800             TOYOTA                          LAND CRUISER PICKUP
201313             TOYOTA                                   FORERUNNER
206547             TOYOTA                                 TOYOTA YARIS
206692             TOYOTA                                 CAMRY HYBRID
207060             TOYOTA                                        MIRAI
210368             TOYOTA                                       1.8 XS
212611             TOYOTA                           TOYOTA COROLLA 1.8
214434             TOYOTA                                       HI ACE
217493             TOYOTA                        26 LP SC 4X4 P4.0L AT
220632             TOYOTA                 LAND CRUISER - PICK UP CARGO
220848             TOYOTA                                         BZ46
223186             TOYOTA                                        COUPE
225945             TOYOTA                                           EQ
228594             TOYOTA                                     COROLLA
229886             TOYOTA                        GXR RA(STATION WAGON)
230166             TOYOTA                                 CAMRY SOLARA
231042             TOYOTA                                      CENTURY
232239             TOYOTA            LAND CRUISER SINGLE-CABIN PICK UP
234731             NISSAN                                        TIIDA
234733             NISSAN                                       ARMADA
234734             NISSAN                                       PATROL
234735             NISSAN                                        URVAN
234737             NISSAN                                       ALTIMA
234739             NISSAN                                      X TRAIL
234740             NISSAN                                        SUNNY
234741             NISSAN                                        KICKS
234743             NISSAN                                       SENTRA
234749             NISSAN                                      PICK UP
234751             NISSAN                                        QUEST
234755             NISSAN                                         JUKE
234758             NISSAN                                   PATHFINDER
234761             NISSAN                                        MICRA
234784             NISSAN                                      X TERRA
234785             NISSAN                                       NAVARA
234797             NISSAN                                      QASHQAI
234802             NISSAN                                       MAXIMA
234831             NISSAN                               PATROL PICK UP
234836             NISSAN                                        ROGUE
234845             NISSAN                                        VERSA
235005             NISSAN                                       NISSAN
235051             NISSAN                                         GT-R
235189             NISSAN                                       MURANO
235421             NISSAN                                        300ZX
235528             NISSAN                                        ROUGE

In [11]:
df[df["model"] == "JUSTIN BIEBER"]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,make_grouped
989070,ZAPMD121XP5001024,2023.0,PIAGGIO,JUSTIN BIEBER,NaN,Motorcycle,GCC,NaN,white,Italy,115.0,2.0,PIAGGIO

In [15]:
df_clean = df.copy()

df_clean["model_original"] = df_clean["model"]

df_clean["model"] = (
    df_clean["model"]
    .astype(str)
    .str.upper()
    .str.strip()
)

In [10]:
makes_array = sorted(df['model'].dropna().unique())

for model in makes_array:
    print(model)

  160
 1290
 300
 APACHE RTR160
 DAILY
 KB
 LT-06
 MONSTER
 PARTNER
 REWARD NPR
 STREET GLIDE
 Y Z F 690
 YZF R7
 ZX 300
#1
$350
$400
$430
$500
$550
0
0.60
0.60 G
001
007
009
01
01 LS AUTO LEV
03
03T
05
06
07
08
09
090 BS
1
1 SERIES
1 SERIES M COUPE
1.8 XS
100
100 HONDA
1000
1000 CC
1000 MOTORCYCLE
1000CC
1000RR
1000XR
1000Z
100CT
101
1040
1040BUFAY
106 BF
1060
1060 G
11
110
1100CC
116I
116i
118 D
118I
118i
12
120 COUPE
1200
1200 K
1200GX
1200K
120I
120i
1222
124 SPIDER
125
125 CC
125 Duke
125 H
125 HK/MOTORCYCLE
125CC
125I
125MS
125i
1290
1290 Super Adventure
1290 Super Duke R
12CILINDRI
1300 CC
1300 GS
1300 GSX
1300CC
1300RS
1313
135I
135i
14 EDRIVE 40
147
15
15 250
150
150 CB
150 CC
150 CC/MOTORCYCLE
150 ES GSO
150/MOTORCYCLE
1500
150BM
150CC
150CC DELIVERY BIKE
150CE
150NK
150SC
150T
156
159
159CC
15M. OF PASS.
160
160 HONDA UNICORN
160 UNICORN
1600
1618
1618C
1622
1627
1735
175
175 ME ULTRA
175 SHARMAX - STREET BIKE
180
180 CC
1800
1800 GL
180CC
1823
1828
1831
1831LS
1832
1845
1848
190 E
1900
1922
1922 MERCEDES
1929
1938
1978
1982
1983
1984
1986
1987
1988
1989
1991
1992
1994
1995
1996
1997
1998
1999
1M
2
2 HX DC 4X4 P 2.7LAT
2 HX DC 4X40
200
200 CLA
200 CLC
200 DUKE
200 Duke
2000
20000
2001
2002
2003
2004
2005
2006
2007
2008
2009
200C
200CC
200T
200ZX (CAR)
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2031
206
207
208
212
212(4WD)
2150
218 I GRAND
218I ACTIVE TOURER
218I GRAN COUP
218I GRAN COUPE
218i
218i ACTIVE TOURER
218i GRAN COUPE
220
220 C
220 CC
220CC
220D
220I
220i
2219
225
225I ACTIVE TOURER
225i ACTIVE TOURER
228
228I
228I GRAN COUPE
228i
230
230 CLK
230GE
230I
235
235I
2400
2400 PICK UP CARGO
240GD
240SX
2410
2435
25 CA SON P 2.5L AT
25 HX DC 4X2 P 27L AT GLX RA/PICK UP
25 HX DC 4X4
25 HX DC 4X4 2.7LAT
25 HX DC 4X4 P .LAT
25 HX DC 4X4 PLAT GLX RA(PICK UP)
25 HX DC 4X4D 2.4LAT
25 HX DC 4X4P 2.7LAT
25 LP SC 4X4 P4.0 MT
25 LP SC4X44.0L MT
250
250 CC
250 Duke
250 SX-F
2500
250CC
2538
2540
2543
2544
25PR 5 DR P 2.4L AT
26 HX DC 4X4 2.4LAT
26 HX DC 4X4 D 2.4L AT
26 HX DC 4X4 P 2.7LAT
26 HX DC 4X4D
26 LP SC 4X4 P4.0L AT
26 YA HB P 1.6L AT TURBO GR RA(CAR)
260 E
2628
263-18
2631
2636
2638
2641
2641 DRINKING WATER TANK
2644
26HX DC 4X4 D2.4LAT
26HX DC 4X4 PLAT
26HX DC 4X4D2.4L AT
26HX DC 4X4P2.7LAT
2700
280
280 CE
280 GE
280GE
280ZX
296
296 GTB
2CV6
2GX
3
3 SERIES
3 SPORT
3 WHEELER
30-380
300
300 C
300 G
300 GE
300 GLK
300 PICK UP CARGO
300 R
300 SE
300 SEDAN
300 SERIES 716 LWB
300 ZX
300/SEDAN
3000 GT
3000GT
3008
300C
300E
300S
300ZX
301
302R
307
308
316
316I
316i
318
318CI
318Ci
318I
318i
320
320 I
320 K
320 SEDAN
320 T
3201
32011
320Ci
320D
320I
320LI
320i
323
323I
323i
325
325 I
325CI
325Ci
325I
325XI
325i
328
328 I
328I
328i
330
330 CI COUPE
330 I
330 IA
330-25
330CI
330Ci
330E
330I
330i
3331 45
3331 MERCEDES
3348
335
335Ci
335I
335i
340I
340I M XDRIVE
340i
348 TS
35
350
350 SHARMAX - SHARMAX FX
3500
3500HD
350CC
350Z
3538
35C VAN CARGO
35EX
35M
360
360 MODENA
37 G
370Z
370Z COUPE
37G
37M
380
380SL
3848
390
390 Adventure
390 DUKE
390 Duke
4
4 RUNNER
4 Runner
4 SERIES
400 GLE
400 MERCEDES
4000
400CC
4031
407
408
40Q
420
420 D
420 SEL
420I
420I
420I GRAN COUPE
420i
422 F
428 GC
428I
428I GRAN COUPE
428i
43 C
430
430I
430I GRAN COUPE
430i
435I
435I GRAN COUPE
435i
440
440I
440I GRAN COUPE
440i
44629
45 SR
450
450 CLC
450 MT
450 RALLY
450 SX-F
450M
450NK
450SR
458
458 ITALIA
460
460 LS
488 GTB
488 PISTA
488 SPIDER
4C
4RUNNER
5
5 SERIES
5 SERIES GT
5 Series GT
50 CC/MOTORCYCLE DELIVERY
50 QX
500
500 DOLCE VITAL
500 SEC
500 SEL
500 SERIES GH
500 SLC
5000 U
5008
500CC
500L
500RR
500SL
500X
5028SC
508
50C15
512
512 TR
520
5201
520D
520I
520i
523I
523i
525
525 1
525 I
5251
525I
525i
528
528 I
5281
528I
528i
530
530E
530I
530Li
530e
530i
535
535I
535i
540
540I
540i
545I
55 E
550
550I
550i
5550
560
560 SE
560 SEL
560 SL
560SL
56M
57
570GT
570S
595
599
6
6 SERIES
6 SERIES GT
6 ULTRA
600
600 CBR
600LT
607
612
62
62 S
626
630I
630i
635
635 CSI
635 Csi
640
640I
640I GRAN COUPE
640i
640i GRAN COUPE
645 CI
645CI
645Ci
645i
650
650 F
650CC
650GT
650I
650I GRAN COUPE
650NK
650S
650i
650i GRAN COUPE
675LT
675NK
675SR
6798KLQ
690
690 Duke
690 ENDURO
695
6H
7
7 SERIES
7 SERIES 750I XDRIVE
70
700
700CL - X
700CL-X
70C15H
711
714
718 BOXSTER
718 CAYMAN
718 SPYDER
720S
728I
728IL
730
730I
730LI
730Li
730i
735I
735LI
735Li
735i
740
740 I
740 IA
740 IAL
7401
740I
740LI
740LT
740Li
740i
745I
745LI
745i
750
750 CC
750 GSX
750 IA
750 IAL
750 XG
750I
750LI
750Li
750S
750i
760I
760L
760LI
765LT
790 DUKE
7X
7X EM(2WD)
7Z
8
8 TGB BK
800
800 ZR
800MT
800NK
80QX
812
812 GTS
817
840
840CI
840Ci
840I
840I GRAN COUPE
840i
840i GRAN COUPE
850CI
850Ci
850MANA
86
890
890 Adventure
9
9 3
9-3
9-5
900
911
944
960
964
993
9X
9X ULTRA
A
A 180
A 200
A 220
A 250
A 30 AMG
A 45 AMG
A 8
A X 7
A-CLASS
A-CLASS 250
A1
A115
A160
A180
A180 L
A200
A220
A250
A3
A35 AMG
A4
A45
A5
A520T
A6
A7
A8
ABARTH 595
ABARTH 695
ABIQA
ACADIA
ACADIA DENALI
ACCENT
ACCORD
ACCORD COUPE
ACCORD CROSSTOUR
ACEMAN
ACTIVE HYBRID 7
ACTIVIA
ACTROS
ACTYON
ACURA
ACURA CSX
ACURA LX
ADAMAS
ADMIRAL
ADV 150
ADV 160
ADV 350
ADV350(MOTORCYCLE)
ADV750T
ADV750T GS
ADVENTURE
ADVENTURE (MOTORCYCLE)
ADVENTURE 890
ADVENTURER
AERIO
AERO 8
AERO CITY COACH
AEROSPACE
AF 150
AF 150 CB
AF 160
AF 160 CB
AF 160 UNICORN PC
AFRICA TWIN
AFRICATWIN
AION
AION Y
AIR
AIR SAPPHIR
AIRTREK
AIRTREK HARDCORE
AK
AL E 750
ALFA ROMEO 4C
ALFARD
ALHAMBRA
ALKAMENOS SINGLE-C
ALLION
ALPHARD
ALPINA
ALPINE
ALSVIN
ALTEA
ALTIAMA
ALTIMA
ALTIMA 2.5
ALTIMA SE
ALTIMA SV
ALTIS
ALTO
AMAROK
AMG GT
AMG ONE
AN 125
AN 125 HK
AN125HK
AN650K9
ANTARA
AP200 4H
APACHE
APACHE 160
APACHE RR 310
APACHE RR 310 EU
APACHE RTR
APACHE RTR 149
APACHE RTR 160
APACHE RTR 160 4 TD FD SL
APACHE RTR 160 4V
APACHE RTR 180
APACHE RTR160
APACHE RTR160 4V
APACHE RTR180
APACHE RTR200
APPACHE
APPACHE 180
APRILIA 750
APULUO AP200 4H
APV
AQUA
AR 125
AR 280
AR 300
AR NAET
ARF 50
ARIIZO 3
ARIYA
ARKANA
ARMADA
ARNAGE
ARRIZO
ARRIZO 3
ARRIZO 5
ARRIZO 6 PRO
ARRIZO 7
ARRIZO 8
ARRIZO 8 PRO
ARRIZO5
ARRIZO7
ARTEON
ARTURA
AS 300
AS 500
ASHOK LEYLAND
ASHOK LEYLAND FA
ASTRA
ASTRI 200
ASTRO
ASX
ATF110  G5
ATHENA
ATLAAS
ATLAAS/STATION
ATLAS
ATLAS CROSS
ATLAS CROSS SPORT
ATOM
ATOS
ATOS PRIME
ATS
ATTACKER/PICK UP DOUBLE CABIN
ATTO 3
ATTO3
ATTRAGE
AUDI RS Q8
AUMARK
AUMARK CHASSIS
AUR PY
AURION
AUV
AVALANCHE
AVALON
AVANTE
AVANTY
AVANZA
AVATAR
AVATAR 07
AVATAR 11
AVATAR 12
AVATR 12
AVENGER
AVENGER 220
AVENGER 220 CC
AVENGER 220 CC CRUISE
AVENIS
AVENTADOR
AVEO
AVIATOR
AX 100
AX7
AYED 250 H7
AYED 250H 7 RST250
AYED BIKE AYED250
AYED BIKE AYED250N
AYED250H 7 RS
AYED250H7
AYED250N 3
AYED250N 3 G
AYED250N 3GP
AZERA
AZKARRA
AZURE
Acadia
Accent
Accord
Accord Crosstour
Acura
Address 110
Africa Twin CRF1100L
Altima
Alto
Apache RR 310
Apache RTR 160
Apache RTR 200
Armada
Arnage
Arteon
Astra
Astro
Attrage
Aurion
Avalanche
Avalon
Avenger 160
Avenger 220
Aventador
Aveo
Azera
Azure
B 150
B 180
B 2000
B 2200
B F 125
B1025
B105
B12
B150
B160
B170
B180
B200
B200 (HATCHBACK)
B2000
B2200
B2300
B250 E
B2500
B3
B3000
B5
B70
B70S
B8 JEEP
B9R
BA
BAJA
BAJAJ
BAJAJ - 150
BAJAJ 100CT
BAJAJ 150
BAJAJ 150 CC
BAJAJ 150BM
BAJAJ 150CC
BAJAJ 180 CC
BAJAJ 180CC
BAJAJ 200CC
BAJAJ 220 CC
BAJAJ 220CC
BAJAJ AVENGER
BAJAJ BALZAR
BAJAJ C 150
BAJAJ DISCOVER
BAJAJ MINI 150
BAJAJ PULSAR 150
BAJAJ-220CC
BAJAJA
BAJAL 15M.
BALENO
BALZAR
BARCHETTA
BEDFORD
BEET
BEETLE
BEN P 6
BENBEN E STAR
BENTAYGA
BENTLEY
BENTLEY GT
BENZ-S560
BERLINGO
BESTUNE T99
BESTURN B50
BESTURN X40
BF 150
BF 150 M
BH 330
BIKE
BIKE 150T FORCE
BIKE MTOT
BJ 40
BJ 6549 C 5
BJ1078
BJ30
BJ30E
BJ40
BJ40 C
BJ40 PLUS
BJ40 PRO
BJ40L
BJ40PRO
BJ41896 AUMAN GTL E
BJ5039
BJ5039-C5
BJ60
BJ6549 C5
BJ6549-C5
BJ65496 VIEW CS2 HR
BJ80
BJJ40 PLUS
BK8E
BK9E
BLAZER
BLS
BLUEBIRD
BM 150
BM150CC
BMW
BMW 1000XR
BMW 120
BMW 1300 G S
BMW 1300 GS
BMW 15
BMW 230
BMW 235
BMW 318
BMW 320
BMW 3201
BMW 320I
BMW 323
BMW 323 TA
BMW 325
BMW 3251
BMW 328
BMW 330
BMW 330 CI
BMW 3301
BMW 330I
BMW 420
BMW 5 SERIES M6
BMW 520
BMW 523
BMW 525
BMW 525 T
BMW 5251
BMW 528
BMW 530
BMW 530 I
BMW 535
BMW 5351
BMW 535I
BMW 540
BMW 5501
BMW 550I
BMW 635
BMW 645
BMW 740
BMW 740LI
BMW 750
BMW 760
BMW 760LI
BMW AR NAET
BMW F 800 GS
BMW I5
BMW K 1600 B
BMW K1600B
BMW M 1000 RR
BMW M 235
BMW R 12
BMW R 1200
BMW R 1200 GS
BMW R 1200 GSADV
BMW R 1250 GS
BMW R 1250 R
BMW R 1300 GS
BMW R 18
BMW R NINET
BMW R1200RT
BMW R1250GS
BMW S 1000 RR
BMW X5
BMW Z3
BMW Z4
BMWR1250GS
BOARDWALK
BOLT
BOLT EV
BOMBKORN 160
BONGO
BONGO 3
BONGO III
BONGO PICK UP CARGO
BONGO PICK UP TRUCK
BONGO SINGLE-CABIN PICKUP
BONGO T
BONGO/PICK UP CARGO
BONGO/SINGLE-CABIN PICK UP
BONNEVILLE
BONNEVILLE BOBBER (MOTORCYCLE)
BORA
BORREGO
BOULEVARD
BOULEVARD 250
BOXER
BOXER FT35
BOXER/VAN CARGO
BOXSTER
BOXSTER COUPE
BREAKOUT
BRERA
BROGH
BROGHAM
BRONCO
BRONCO SPORT
BROOKLANDS
BROUGHAM
BROUGHTAM
BROYGAM
BROYGHAM
BRUTALE
BRUTALE DRA
BRZ
BT 50
BT-50
BULSAR
BUNICORN
BURGMAN
BURGMAN/MOTORCYCLE
BUS
BX5
BX7
BYD
BYD SEAL
BYD SONG PLUS
BZ 4
BZ3X
BZ46
BZ4X
Baleno
Beetle
Blazer
Bolt
Bonneville T100
Boxter
Breakout
BrookLands
Bullet 350
C
C 10
C 1025MY
C 11
C 150
C 16
C 160
C 180
C 1845
C 200
C 220
C 230
C 250
C 280
C 300
C 300 SEDAN
C 300/SEDAN
C 320
C 350
C 400
C 400 GT
C 400 X
C 43 AMG
C 600
C 63
C 63 AMG
C 650
C 650 GT
C B R 500
C BR 500
C KVJB 4
C MAX SEL
C-10
C-CLASS
C-ELYSEE
C-HR
C/K
C/K 1500
C01
C1 VAN PASSENGER
C10
C11
C12
C15
C16
C16 EV 520 PREMIUM
C1600
C160M
C160MY
C180
C180 K
C20
C200
C200 K
C220
C230
C230 K
C240
C250
C260L
C280
C2S W
C3
C3 AIRCROSS
C30
C300
C31
C32
C320
C35
C350
C4
C4 AIRCROSS
C4 GRAND PICASSO
C40
C400
C400GT
C400X
C43 AMG
C450
C450 AMG
C4X
C5
C5 AIRCROSS
C55 AMG
C5500
C63 AMG
C63S AMG
C650GT
C70
C835 AM
CA3182P
CA7188A
CABALLERO / MOTORCYC
CABALLERO DELUXE
CABALLERO RALLY
CABSTAR
CADDY
CADDY HATCHBACK
CADENZA
CADILLAC
CADILLAC BROUGH
CADILLAC CEVEL
CADILLAC ELDORADO
CALIBER
CALIBRO
CALIFORNIA
CAMAR
CAMARO
CAMARO LTZ
CAMARO SS
CAMRY
CAMRY HYBRID
CAMRY SOLARA
CAN
CAN-AM SPYDERRT-S
CANT
CANTER
CANTER
CANTER PICK UP CAR
CANTER PICK UP CARGO
CANTER PICKUP
CANTER PICKUP CRANE
CANTER/BICK UP FRZ
CANYON
CANYON REDR
CAPRI
CAPRICE
CAPRICE CLASSIC
CAPRICE CLASSIC SEDAN
CAPRICE LS
CAPRICE SS
CAPRICE SS SEDAN
CAPTAIN E
CAPTIVA
CAPTUR
CAR
CARAVAN
CARAVELLE
CARENS
CARGO
CARGO 4135
CARGO VAN
CARMEL
CARNIVAL
CARRERA GT
CARROT ABYEI
CARRY
CASCADA
CASPER
CATERA
CAVALIER
CAYENNE
CAYENNE COUPE
CAYENNE GTS
CAYMAN
CB
CB 1000
CB 1000R
CB 1300
CB 160
CB 300 R
CB 650CC
CB 750
CB SHINE
CB UNICORN
CB UNICORN 160
CB1000
CB1000R
CB1100
CB1100 RS
CB125F
CB1300
CB160
CB160R
CB190X
CB200X
CB250
CB300F
CB300R
CB500
CB500F
CB500X
CBF
CBF 125
CBF 125 M
CBF 125M
CBF 150
CBF 150 M
CBF 150 MA
CBF 150M
CBF 150MA
CBF 160
CBF 160 UNICORN
CBF 16025MY
CBF 16025Y
CBF 16026MY
CBF 160F
CBF 180
CBF-160
CBF125
CBF150
CBF1505
CBF150MA
CBF150MA UNICORN (MOTORCYCLE)
CBF150S
CBF160
CBF160 26MY
CBF160 UNICORN
CBF16026
CBF16026MY
CBF16026Y
CBF1606MY
CBF160F
CBR
CBR 1000
CBR 1000 R 7
CBR 1000 RA
CBR 1000RA
CBR 1000RR
CBR 1000RRB
CBR 1100
CBR 125
CBR 250
CBR 300
CBR 300R
CBR 500
CBR 600
CBR 900
CBR1000
CBR1000RA
CBR1000RR
CBR1000RR7
CBR1000RR8
CBR125R
CBR250R
CBR300R
CBR500R
CBR600RR
CBR600RR6
CBR650
CBR650RACT(MOTORCYCLE)
CBX 250
CBX250
CBX250 TW
CBX250 TWISTER
CBX250W
CBX750P2H
CC
CC 200
CC 220
CC150
CC650
CE 04
CE300
CEDREC
CEDRICK
CEF150
CELERIO
CELICA
CENTENNIAL
CENTRA
CENTURY
CERATO
CERATO KOUP
CEVEL
CF 1000
CF 1600
CF 600
CF 650
CF MOTO 650
CF250T6A
CG 125
CH150
CH150T-34
CHAIRMAN
CHALLENGER
CHANGAN
CHANGHUA CH150
CHARADE
CHARGER
CHARGER R
CHERO
CHEROKEE
CHERY
CHERY TIGGO
CHEVROLET
CHEVROLET BLAZER
CHEVROLET CHEVY
CHEVROLET EL CAMI
CHEVROLET EXPRESS
CHEVROLET LAUGH
CHEVY
CHIEF
CHIEFTAIN
CHIEFTAIN 1400
CHIRON
CHR
CHRYSLER 300
CHRYSLER TWON ANC
CIAZ
CINGIN
CITI
CITROEN C1
CITROEN C2
CITROEN C3
CITROEN C5
CITY
CITY 100
CITYRAY
CIVIC
CIVIC 150
CIVIC COUPE
CIVIC/COUPE
CIVILIAN
CL 500
CL 550
CL 600
CL 63
CL-CLASS
CL500
CL55 AMG
CL550
CL600
CL63 AMG
CL65 AMG
CLA 180
CLA 200
CLA 220 D
CLA 250
CLA 35
CLA 35 AMG
CLA 45
CLA 45 AMG
CLA-CLASS
CLA180
CLA200
CLA250
CLA35 AMG
CLA45
CLA45 AMG
CLASSIC
CLASSIC 50
CLASSIC 500
CLC 200
CLC180K
CLC200K
CLC230
CLC250
CLC350
CLE-CLASS
CLE200
CLE300
CLE450
CLE53 AMG
CLIO
CLK
CLK 200
CLK 240
CLK 320
CLK200 K
CLK230 K
CLK240
CLK280
CLK320
CLK350
CLK500
CLK55 AMG
CLK63 AMG
CLS 300
CLS 350
CLS 400
CLS 450
CLS 500
CLS 53 AMG
CLS 550
CLS 63 AMG
CLS-CLASS
CLS350
CLS400
CLS450
CLS450
CLS500
CLS53 AMG
CLS55 AMG
CLS550
CLS63 AMG
CLUBMAN
CM 10
CMX
CMX 500
CMX1100
CMX500
CMX500A
CMX500AS
CMX500AT (MOTORCYCLE)
CMX500S
CN 3
CNI 180
CO 180I MOTORCYCLE
COASTER
COBBER COOPER
COBBER/CLUBMAN/SEDAN
COBBER/COOPER/COUPE
COBRA
COLD WING
COLORADO
COMMANDER
COMPASS
CONTINENTAL
CONTINENTAL GT
CONTINENTAL GT 650
COOLRAY
COOPER
COOPER CLUBMAN
COOPER COUNTRYMAN
COOPER COUPE
COOPER ROADSTER
COOPER S
COOPER S COUNTRYMAN
COOPER SE HARDTOP
COOPERS
COOPERT
CORNICHE
COROLLA
COROLLA
COROLLA 1.3
COROLLA 1.5
COROLLA 1.5L/HATCHBACK
COROLLA 1.6
COROLLA 1.6/SEDAN
COROLLA 1.8
COROLLA CROSS
COROLLA LI
COROLLA SEDAN
COROLLA SEDAN / HATCH
CORONA
CORSA
CORSAIR
CORSAR
CORVETTE
COUNTACH
COUNTRYMAN
COUNTY
COUNTY/SCHOOL BUS
COUPE
CPC
CPF
CPX110
CR-V
CR-X
CR-Z
CRAFTER
CRAVAN MISTUBISHI
CRESSIDA
CRETA
CRF
CRF 1100DL4T GS
CRF 450X
CRF1100 A3T GS
CRF1100CC
CRF1100DL4T
CRF250L
CRF300RALLY
CROSS
CROSS 225
CROSS CO
CROSS COUNTRY
CROSS RO
CROSS VICTORY
CROSSFIRE
CROSSLAND
CROSSLAND X
CROSSTOUR
CROSSTREK
CROWN
CROWN KLUGER
CROWN V
CROWN VICTORIA
CROX
CRUIZ
CRUZE
CRV
CRX
CRZ
CS 220
CS 35
CS 95
CS35
CS35 PLU
CS35 PLUS
CS55
CS55 PLUS
CS55 PLUSE
CS75
CS75 (4WD)
CS75 PLUS
CS85
CS95
CSX1300
CT 100
CT 110
CT 200H
CT125
CT200H
CT4
CT5
CT6
CTS
CTS-V
CUBE
CUBE 150
CULLINAN
CUSTOM 1000 R
CV3
CX 3
CX 5
CX-3
CX-30
CX-5
CX-60
CX-7
CX-9
CX-90
CYBER TRUCK
CYBERSTER
CYBERTRUCK
CYBERTRUCK DUAL MOTOR NEW
CYCLE
Cadenza
Caliber
Camaro
Canter
Caprice
Captiva
Carens
Carnival
Carrera
Cayenne
Cayman
Cedric
Celica
Cerato
Challenger
Charger
Cherokee
Chieftain
Ciaz
City
Citycom 300
Civic
Classic 350
Classic 500
Clio
Colorado
Commander
Compass
Continental
Cooper
Corolla
Corsa
Corvette
Cressida
Creta
Crosair
Cross Roads
Crown
Crown Victoria
D
D & N
D 150
D 240
D 2500
D MAX
D MAX SINGLE-CABIN PICK
D-MAX
D150
D250N
D260
D260 PANEL VAN
D270
D50
D60
D60 MAX
D9
D90
D90 MAX
DAEWOO 106 BF
DAIHATSU
DAIHATSU DELTA
DAIHATSU FEROZA
DAIHATSU TERIOS
DAILY
DAIMLER DOUBLE
DAINA
DAKOTA
DALTA
DARGO
DARK HORSE
DARKHORSE
DART
DASHING
DATSUN
DATSUN 280 ZX
DATSUN ZX 280
DAVIDSON
DAWN
DAWN COUPE
DAYTONA 675
DAYTONA S
DAYTONA SP3
DB11
DB12
DB6OBL
DB9
DBS
DBX
DBX 707
DBX707
DEEPAL
DEEPAL S05
DEEPAL S09
DEER
DEFENDER
DEFENDER 110
DEFENDER 110 S
DEFENDER 110 V8 ULTIMATE EDITION PS25(4WD)
DEFENDER 130
DEFENDER 90
DEFENDER 90 X-DYNAMIC SE
DEFENDER DOUBLE CABIN
DEFENDER STATION
DEFENDER/STATION
DEFENDER110
DEKTE PICK UP TRUCK
DELIVERY BIKE
DELIVERY MOTORCYCLE
DELOREAN
DELTA
DELTRO
DELUXE
DENZA N9
DESTINATOR
DESTROYAR 05
DESTROYER 05
DETRA
DETRA 300
DETRO
DEVENDER
DEVENDR
DEVENDR SINGLE-CABIN PICK UP
DEVILLE
DEVILLE/COUPE
DEXER
DEXER SINGLE-CABIN PICK UP
DFH 1180
DFSK
DHS
DIAVEL
DIAVEL1260S
DIESEL
DIESEL NU 41 H5
DIESEL TFA
DIESEL UD
DIMALER
DISCO
DISCOVER
DISCOVERY
DISCOVERY SPORT
DISEL
DLX FA (PICK UP)
DMAX
DMV 300
DOBLO
DODGE DURANGO
DODGE GRAND
DODGE GRAND CARAVAN
DODGE JOURNEY
DODGE RAM
DOKKER
DOLPHIN
DOMINAR
DOMINAR 400
DOMINAR 400CC
DOMINOR
DOMINOR 400CC
DOMY X7
DONGFENG DOLLICA
DONGFENG HERO
DOUBLE CABIN PICK UP
DOUBLE CABIN PICKUP
DR 650
DR-Z400SMRLMS
DR160
DR650SEM5
DR650SEM6
DRAGSTER
DREAMER
DS
DS250RL
DS250RL (V-STROM SX)
DS3
DS5
DS525X
DT 175
DT175
DTS
DUCATI
DUCATI 1100
DUCATI 400 CC
DUCATI 899
DUCATI DIAVEL
DUCATI MONSTER
DUCATI PANIGALE
DUCATI PANIGALE 959
DUCATI PANIGALE V2
DUCATI SCRAMBLER
DUCATO
DUKE
DUKE 390CC
DUKE 690
DUKE250
DUMP TRUCK
DURANGO
DUSTER
DUTRO
DX 5
DX3
DX5
DX7
DX8S
DY400 F
DYNA
DYNA VAN CARGO
DZIRE
Dart
Dashing
De Ville
Defender
DesertX
Destini 125
Diavel 1260
Domy X7
Durango
Duster
Dzire
E 18-150
E 200
E 2008
E 240
E 250
E 300
E 320
E 323
E 328
E 350
E 350 MOTOR HOME
E 400
E 420
E 430
E 450
E 450 MOTOR HOME
E 50
E 500
E 500 AMG
E 53
E 53 AM
E 53 HYBRID 4MATIC+ SEDAN
E 55
E 55 AMG
E 550
E 63
E 63 AMG
E NS1
E STAR
E TRON
E UP
E-350
E-450
E-CLASS
E-NP1
E-NS1
E-PACE
E-QM5
E-TRON
E-TRON GT
E190
E200
E2000
E220
E220 D
E220D
E230
E240
E25
E250
E260
E260L
E280
E300
E3000
E30X
E320
E350
E400
E420
E43 AMG
E430
E450
E450 ENTEGRA ODYSSEY
E450 SUPER DUTY (MOTORHOME)
E450 THOR MOTOR COACH FREEDOM ELITE
E450 THOR MOTOR COACH MAGNITUDE GRAND R36
E5
E5 PLUS
E500
E53 AMG
E55 AMG
E55 SEDAN
E550
E63
E63 AMG
EADO
EADO PLUS
EANMOK
EASTAR
EC 250
EC 7
EC01
EC6
EC7
ECHO
ECHO VAN CARGO
ECLIPSE
ECLIPSE CROSS
ECO 150
ECO 150 CARGO
ECONOLINE
ECONOLINE (MOTORHOME)
ECONOLINE E350 SUPERDUTY (MOTORHOME)
ECOSPORT
EDAN
EDGE
EECO
EHS9
EICHER PRO 2000
EL8
ELANTRA
ELDORADO
ELDORADO / COUPE
ELDORADO/COUPE
ELECTRA GLIDE
ELECTRA GLIDE ULTRA LIMITED
ELECTRAGLIDE
ELECTRIC BIKE
ELEMENT
ELETRE
ELF
ELF / BOX
ELF PICK UP CARGO
ELF/PICK UP CARGO
ELF5
ELGHT
ELISE
EM 01
EM 01 (ELECTRIC BIKE)
EM GRAND
EM01
EM80
EMGRAND
EMGRAND 1.5D GS
EMGRAND 7
EMGRAND EC7
EMGRAND EC8
EMGRAND EX7
EMGRAND GC6
EMGRAND GS
EMGRAND GS
EMGRAND GT
EMGRAND X7 SPO
EMGRAND X7 SPORT
EMIRA
EMKOO
EMKOO HYBRID
EMPOW
EN 125
EN 125-2 A
ENCLAVE
ENCORE
ENDURO
ENDURO 2
ENDURO 250
ENDURO 300
ENP1
ENP2
ENS USTATION
ENS1
ENVISION
ENVOY
EOS
EPICA
EQ
EQ 1
EQ900
EQA 250
EQA 260
EQA 350
EQA 350 4M
EQB 260
EQB 350
EQB 350 4M
EQC 350
EQC 400
EQC 400 4M
EQE
EQE 300
EQE 350
EQE 350 PLUS
EQE 350+
EQE 500
EQE 53 4M
EQS
EQS 450
EQS 450 PLUS
EQS 450+
EQS 53 AMG
EQS 580
EQS 580 4M
EQUINOX
EQUUS
EQV 300
EQV300
ERTIGA
ERTIGA GLX AT
ES
ES 250
ES 3
ES 300
ES 300H
ES 330
ES 350
ES 400
ES200
ES250
ES300
ES300 H
ES300H
ES300h
ES330
ES350
ES6
ES8
ESCALADE
ESCALADE ESV
ESCALD/PICK UP DOUBLE CABIN
ESCAPE
ESCORT
ESPIRT
ESTELAR
ET
ET 5
ET5
ET9
EUROSPACE
EV5
EV6
EV9
EVEREST
EVOLUTION
EVORA
EX 37
EX30
EX35
EX37
EX400C
EX5
EX7 SPORT
EXCURSION
EXEED LX
EXEED RX
EXEO
EXIGE
EXPEDITION
EXPEDITION   EL
EXPEDITION MAX LIMITED 4WD
EXPENG G6
EXPERT
EXPLORER
EXPLORER SPORT TRAC
EXPRESS
EXPRESS EX(VAN)
EXPRESS VAN PASSENGER
Echo
EcoSport
Edge
Eeco
Electra Glide
Enduro 300
Envoy
Eos
Epica
Equinox
Ertiga
Escalade
Escape
Escort
Everest
Evora
Expedition
Explorer
F
F 150 PICK UP DOUBLE CABIN
F 150 RAPTOR SHELBY
F 150 VAN DOUBLE CABIN
F 250
F 250 (PICK UP)
F 250/PICK UP DOUBLE CABIN
F 430
F 450
F 530 (MOTORHOME)
F 599
F 800 GS
F 800 R
F 850 GS
F 900
F 900 GS
F 900 R
F 900 XR
F-150
F-250
F-250 PICKUP
F-350
F-450
F-550
F-PACE
F-TYPE
F02
F02 (ELECTRIC BIKE)
F02 (ELECTRIC LOAD BIKE)
F02 ELECTRIC
F02/ELECTRIC
F12
F12 Berlinetta
F150
F250 PICK UP
F3
F355
F4 1000
F430
F53
F550
F575
F575M
F599
F600
F600 ENTEGRA ESTEEM
F600 ENTEGRA ESTEEM XL 33F (MOTORHOME)
F650
F650GS
F7
F700
F750GS
F8 TRIBUTO
F800GS
F800GT
F800R
F800S
F850GS
F900 GS
F900R
F900XR
FABIA
FAEZB 150
FAIRBIRD
FAIRUZA
FALCON
FAN
FANGCHENGBAO 5
FATBOY
FC-49
FCH 5022 XXYD
FD 25 NT
FEJER
FENGJING
FENGON 500
FENGON 580
FENGON 600
FENGON C31
FENGON C32
FENGON GLORY
FENGON GLORY 580
FENGON GLORY 600
FENGON GLORY IX7
FENGON IX5
FERRARI
FERRARI 296 GTS
FERRARI 348
FERRARI 458
FERRARI 550
FERRARI 612 COUPE
FERRARI F355
FERRARI MONZA SP1
FERRARI SUPERFAST
FF
FH
FH 12
FH 440
FH 460
FH12
FH12 420
FH13
FH200LC
FH400
FH440
FHD
FIAT
FIAT 500
FIAT 500 DOLCE VITA
FIAT FIORINO
FIAT SPIDER 661
FIAT595
FIDDLE III 200
FIESTA
FIFTH AVENUE
FIGO
FIORINO
FIORINO VAN CARGO
FIREBIRD
FIT
FIVE HUNDRED
FJ
FJ CRUISER
FJ Cruiser
FJR1300
FJS400D
FL220
FLAT WOOD
FLAT WOOD SEDAN
FLEETWOOD
FLEX
FLFB
FLHCS
FLHR
FLHRC
FLHT
FLHTCUI
FLHTK
FLHTK (MOTORCYCLE)
FLHTP
FLHX
FLHXS
FLORID
FLS
FLSTC
FLSTC103
FLSTF
FLSTFB 103
FLSTNI (MOTORCYCLE)
FLSTSE
FLTRK
FLTRU
FLTRUSE
FLTRX
FLTRXS
FLTRXSE
FLTRXSTSE
FLUENCE
FLYING SPUR
FM 10
FM12
FM460
FM9 HORSE
FO2 ELECTRIC
FOCUS
FORD
FORD E-450
FORD FUSION
FORD SUPER DUTY
FORERUNNER
FORESTER
FORMENTOR
FORMULA LEOPARD
FORMULA LEOPARD S
FORT-WO
FORTE
FORTE COUPE
FORTHING T5
FORTHING T5 HEV
FORTIS
FORTUNER
FORTWO
FORTÉ
FORZA 300
FOTON
FOZO
FREE
FREELANDER
FREESTAR
FRONTIER
FRONTIER/PICK UP DOUBLE CABIN
FRONTLANDER
FRONX
FRR
FRV CROSS
FSR
FTR 1200
FTR 1200S
FULLBACK
FUSION
FUSO
FUSO BA

In [23]:
import re
import numpy as np
def basic_model_clean(x):
    if pd.isna(x):
        return np.nan

    x = str(x).upper().strip()

    # normalize separators
    x = re.sub(r'[-_/]+', ' ', x)

    # remove repeated spaces
    x = re.sub(r'\s+', ' ', x)

    return x.strip()

In [24]:
df_clean["model"] = df_clean["model"].apply(basic_model_clean)

In [25]:
import re

arabic_models = (
    df_clean[
        df_clean["model"].fillna("").apply(
            lambda x: bool(re.search(r'[\u0600-\u06FF]', str(x)))
        )
    ]
    [["make","model"]]
    .drop_duplicates()
    .sort_values(["make","model"])
)

arabic_models

           make                             model
951032    BAJAJ                  اف اكس 150 الترا
949637    BAJAJ                            افينجر
949434    BAJAJ                            بولسار
949321    BAJAJ                       دراجة نارية
949927    BAJAJ                       دراجة ناريه
...         ...                               ...
59587    TOYOTA                          هاي لوكس
151726   TOYOTA                           هايلوكس
988910      TVS                 اباشي ار تي ار 20
988764      TVS  ستار اتش ال اكس في اس 1 تي في اس
976114  VICTORY                        سيكتيس 175

[100 rows x 2 columns]

In [26]:
year_models = df_clean[
    df_clean["model"].str.fullmatch(r"(19|20)\d{2}", na=False)
]

year_models[["make","model"]].value_counts()

make     model
PEUGEOT  2008     153
BAJAJ    2024      35
HONDA    2017      27
         2018      18
         2023      17
                 ...
MAN      2000       1
GMC      1999       1
POLARIS  2022       1
BAOJUN   2024       1
TOYOTA   2004       1
Name: count, Length: 272, dtype: int64

In [27]:
df_clean.loc[
    df_clean["model"].str.fullmatch(r"(19|20)\d{2}", na=False),
    "model"
] = np.nan

In [28]:
model_counts = (
    df_clean["model"]
    .value_counts()
)

model_counts.tail(500)

model
HINO 300 VAN CARGO    1
HINO CHASSIS TRUCK    1
DETRA                 1
HINO,300              1
HINO WU410            1
                     ..
SX 1000               1
AYED250N 3            1
APULUO AP200 4H       1
EQ 1                  1
EPURE                 1
Name: count, Length: 500, dtype: int64

In [29]:
model_counts[
    model_counts <= 3
]

model
CROWN KLUGER       3
TOYOTA TACOMA      3
MR2                3
WISH               3
BZ 4               3
                  ..
SX 1000            1
AYED250N 3         1
APULUO AP200 4H    1
EQ 1               1
EPURE              1
Name: count, Length: 3355, dtype: int64

In [30]:
df_clean[
    df_clean["model"] == "CHALLENGER"
][["make","model"]]

                     make       model
754370               FORD  CHALLENGER
897193              DODGE  CHALLENGER
897201              DODGE  CHALLENGER
897202              DODGE  CHALLENGER
897204              DODGE  CHALLENGER
...                   ...         ...
985390              DODGE  CHALLENGER
985391              DODGE  CHALLENGER
985397              DODGE  CHALLENGER
992690  INDIAN MOTORCYCLE  CHALLENGER
992721  INDIAN MOTORCYCLE  CHALLENGER

[1769 rows x 2 columns]

In [31]:
make_models = (
    df_clean.groupby("make")["model"]
    .unique()
)