In [8]:
import pandas as pd

df = pd.read_csv("../../vin-sphere test/data_methaq(2.0).csv")

In [9]:
df.shape

(1009604, 12)

In [10]:
df.dtypes

chassisNumber         str
year              float64
make                  str
model                 str
trim                  str
bodyType              str
regionalSpec          str
cylinders         float64
color                 str
origin                str
weightInKg        float64
noOfPassengers    float64
dtype: object

In [11]:
df.isnull().sum()

chassisNumber          0
year                  11
make                  11
model                 13
trim               19411
bodyType               1
regionalSpec         283
cylinders          18687
color              63616
origin             85061
weightInKg        102248
noOfPassengers         7
dtype: int64

In [12]:
df[['make','model','trim','bodyType','regionalSpec']].nunique()

make             466
model           6403
trim            3256
bodyType         128
regionalSpec       2
dtype: int64

In [13]:


print(*df['bodyType'].unique(), sep='\n')

SEDAN
Mini Bus High Roof
Pick Up Double Cab
SUV
HATCHBACK
Pick Up Single Cab
Panel Van
BUS
MPV
Estate
Pick Up
VAN
Mini Bus
COUPE
Van
SUV- CROSSOVER
PICKUP
SALOON
Sedan
Station
Saloon
Panel Van High Roof
Pickup
Hatchback
MINI BUS
PICK UP SINGLE CAB
Half Panel Van
PICK UP DOUBLE CAB
CONVERTIBLE
PANEL VAN
Coupe
CARGO VAN
MINIVAN
Mini Bus Semi High Roof
Pickup Double Cabin
Bus
PICK UP
Light Vehicle
CARAVAN
TANKER
PICKUP TRUCK
Car
Motorcycle
Pickup Single Cabin
Minivan
Pickup Double Cab
Truck
Pick Up Double Cabin
COUPE/CABRIOLET
Forklift
Ambulance
Regular Cab
Window Van
MINI BUS HIGH ROOF
MOTORCYCLE
STATION
Wagon
Station Wagon
PICK-UP
PanelVan Wide Body High Roof
LIGHT VEHICLE
Refrigerator
Pick-Up
TRUCK
Pick Up Double C
Van Cargo
Pick-Up with crane
Truck with Crane
Water Tank
Sports Car
Station Light
Sedan Light Vehicle
Mini Bus LWB Wide Body HR
Diesel Tanker
sedan
coupe
SINGLE CABIN LONG CHASSIS
SINGLE CABIN LONG CARGO
Pick Up LWB
SINGLE CABIN STD CHASSIS
PICK UP DOUBLE CAB LONG BOX
PICK-UP WITH BOX
COACH
Dump Truck
Mitsubishi
REGULAR CAB
HEAVY EQUIPMENT
Pickup Refrigerator
Heavy Truck
CROSSOVER
Van Passenger
PICK UP DOUBLE CABIN
Mini Van
Mobile Workshop
WAGON
Pick Up Cargo
VAN PASSENGER
SUV COUPE
Mini Bus LWB
SPORTS CAR
MINI VAN
Convertible
Caravan
nan
PICK UP EXT CAB
SUV- COMPACT
Targa
VAN CARGO
SUV CONVERTIBLE
SWB VAN
LWB VAN
Hard Top
Pick-Up with Box
PICK UP CARGO
HARD TOP
JEEP WRANGLER
Crane
Pick Up Double
SPORTBACK
VAN 4.5 TON
LONG VAN
MINI
Truck with Box
Locomotive
FORK LIFT
Pickup with Box
Cargo Van
Excavator
Trailer

In [14]:
pd.set_option("display.max_rows", None)

In [15]:
df.shape

(1009604, 12)

In [16]:
long_chassis_df = df[df['chassisNumber'].astype(str).str.replace(r'\s+', '', regex=True).str.len() > 17]

In [17]:
df = df.drop(index=long_chassis_df.index)

In [26]:
df.shape

(995062, 12)

In [19]:
df = df[df['chassisNumber'].astype(str).str.replace(r'\s+', '', regex=True).str.len() >= 17]

In [20]:
df[df['bodyType'] == 'Light Vehicle']

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
41955,JTNBZ4HK7N3023062,2012.0,TOYOTA,CAMRY,NaN,Light Vehicle,NaN,NaN,white pearl,JAPAN,1630.0,5.0
73247,JTFLU733196053119,2009.0,TOYOTA,LAND CRUISER,NaN,Light Vehicle,NaN,NaN,silver,Japan,1000.0,3.0
122415,JT152EEA100287105,1996.0,TOYOTA,COROLLA 1.6/SEDAN,NaN,Light Vehicle,NaN,NaN,red,Japan,1100.0,4.0
139398,WZIDB4A03LW033661,2020.0,TOYOTA,SUPRA COUPE,NaN,Light Vehicle,NaN,NaN,gray and black,Austria,1570.0,2.0
195455,JTNYM3AP2P8002523,2023.0,TOYOTA,VAN,NaN,Light Vehicle,NaN,NaN,black,JAPAN,2440.0,6.0
201367,JTJHK31U102001109,2022.0,TOYOTA,LAND CRUISER,NaN,Light Vehicle,NaN,NaN,white,JAPAN,2000.0,7.0
215938,JTMHY05J6M4100065,2021.0,TOYOTA,LAND CRUISER,NaN,Light Vehicle,NaN,NaN,white pearl,Japan,2590.0,8.0
227205,JTDBW9232A1191208,2010.0,TOYOTA,YARIS,NaN,Light Vehicle,NaN,NaN,gray and black,JAPAN,900.0,5.0
248512,JN8AY2NY4F9118505,2015.0,NISSAN,PATROL,NaN,Light Vehicle,NaN,NaN,black,Japan,2150.0,8.0
277163,JN6FE54852X401040,2002.0,NISSAN,URVAN/COACH,NaN,Light Vehicle,NaN,NaN,white,Japan,2000.0,12.0
383064,WBAKRO104HOW31291,2008.0,NISSAN,PATROL SUPER SA,NaN,Light Vehicle,NaN,NaN,white,JAPAN,1800.0,7.0
385627,3N8AP6BA8SL385567,2025.0,NISSAN,KICKS,NaN,Light Vehicle,NaN,NaN,black,MEXICO,1350.0,5.0
425423,MNTBDOES3G6630716,2016.0,NISSAN,NAVARA,NaN,Light Vehicle,NaN,NaN,white,Thailand,2200.0,5.0
537758,MMBJNK340GH005409,2016.0,MITSUBISHI,200,NaN,Light Vehicle,NaN,NaN,white,THAILAND,1600.0,1.0
548308,JE3AB36AXHU715639,2017.0,MITSUBISHI,LANCER,NaN,Light Vehicle,NaN,NaN,gray and black,Japan,1310.0,5.0
552025,JA3AW86VX8U043266,2008.0,MITSUBISHI,LANCER EVOLUTION,NaN,Light Vehicle,NaN,NaN,maroon,Japan,1100.0,5.0
614859,KMJWA37JBAU169508,2010.0,HYUNDAI,STARKS,NaN,Light Vehicle,NaN,NaN,silver,South Korea,1600.0,10.0
700055,WDD2211561A008241,2006.0,MERCEDES BENZ,S350,NaN,Light Vehicle,NaN,NaN,gray and black,Germany,1955.0,5.0
740454,6G1EK52827L875838,2007.0,CHEVROLET,LUMINA,NaN,Light Vehicle,NaN,NaN,white,Australia,1720.0,5.0
794990,WBA3B5G67ENS10088,2014.0,BMW,328,NaN,Light Vehicle,NaN,NaN,black,Germany,NaN,NaN
799181,WBA23EHOXPCM38824,2023.0,BMW,BMW 740,NaN,Light Vehicle,NaN,NaN,green and white,United States,1800.0,5.0
799586,WBS41AZ040CM88996,2023.0,BMW,M4,NaN,Light Vehicle,NaN,NaN,black,Germany,2000.0,2.0
800618,WBA71AGOXPWX92881,2023.0,BMW,5201,NaN,Light Vehicle,NaN,NaN,white,Austria,1615.0,5.0
801958,WBABS51080EH36590,2003.0,BMW,330 CI COUPE,NaN,Light Vehicle,NaN,NaN,white,Germany,1600.0,5.0
861486,LVUDB2182PF022834,2023.0,JETOUR,X70,NaN,Light Vehicle,NaN,NaN,white,China,2100.0,7.0
882495,JNKBY1AP8HM340020,2017.0,INFINITI,Q70/SEDAN,NaN,Light Vehicle,NaN,NaN,gray and black,JAPAN,1600.0,5.0
906164,LCOFD1C40S5384246,2025.0,BYD,LEOPARD 5,NaN,Light Vehicle,NaN,NaN,black,China,2800.0,5.0
907572,LCOFD1C42S5245557,2025.0,BYD,LEOPARD 5,NaN,Light Vehicle,NaN,NaN,black,China,1600.0,5.0
909789,LGXCE4CB6S0586521,2025.0,BYD,SONG PLUS,NaN,Light Vehicle,NaN,NaN,gray and black,China,1400.0,5.0
910361,LCOFD1C46S5284409,2025.0,BYD,LEOPARD 5,NaN,Light Vehicle,NaN,NaN,black,CHINA,2500.0,5.0
925131,WAUAYABX3BB069743,2011.0,AUDI,A1,NaN,Light Vehicle,NaN,NaN,brown,Belgium,1300.0,4.0
954376,L6T716228HN407654,2017.0,GEELY,EX7 SPORT,NaN,Light Vehicle,NaN,NaN,white,CHINA,1200.0,4.0
990703,HH415QPA24J601986,2025.0,VICTORY,V2,NaN,Light Vehicle,NaN,NaN,white,China,1700.0,5.0
1004305,JHHZCNIH2KK010517,2019.0,HINO,300 PICK UP CARGO,NaN,Light Vehicle,NaN,NaN,white,Japan,2400.0,4.0

In [21]:
summary = (
    df.groupby(['make', 'model', 'trim', 'noOfPassengers', 'cylinders', 'weightInKg'])
      .agg(
          unique_body_types=('bodyType', 'nunique'),
          body_types=('bodyType', lambda x: list(sorted(set(x))))
      )
      .reset_index()
)

# Filter for conflicts (Make sure there is no comma at the end of this line!)
summary = summary[summary['unique_body_types'] > 1]

# Display the DataFrame
summary

                 make                   model                         trim  \
8              ABARTH                     595                 COMPETIZIONE
13             ABARTH                     595                 COMPETIZIONE
41             ABARTH                     695                      TURISMO
219     ASHOK LEYLAND           ASHOK LEYLAND                          STD
270     ASHOK LEYLAND                 PARTNER                          STD
342      ASTON MARTIN                 VANTAGE                     ROADSTER
425              AUDI                      A3                      35 TFSI
442              AUDI                      A3                      35 TFSI
666              AUDI                      A4                       S-Line
739              AUDI                      A4                       S-Line
802              AUDI                      A5                      35 TFSI
810              AUDI                      A5                      40 TFSI
815              AUDI                      A5                      40 TFSI
816              AUDI                      A5                      40 TFSI
821              AUDI                      A5                      40 TFSI
843              AUDI                      A5               40 TFSI S-LINE
850              AUDI                      A5               40 TFSI S-LINE
875              AUDI                      A5               40 TFSI S-LINE
884              AUDI                      A5               45 TFSI S-LINE
898              AUDI                      A5               45 TFSI S-LINE
908              AUDI                      A5                       S-Line
914              AUDI                      A5                       S-Line
915              AUDI                      A5                       S-Line
923              AUDI                      A5                       S-Line
924              AUDI                      A5                       S-Line
930              AUDI                      A5                       S-Line
933              AUDI                      A5                       S-Line
963              AUDI                      A5                          STD
965              AUDI                      A5                          STD
969              AUDI                      A5                          STD
972              AUDI                      A5                          STD
973              AUDI                      A5                          STD
979              AUDI                      A5                          STD
980              AUDI                      A5                          STD
996              AUDI                      A5                          STD
1631             AUDI                      Q2                      35 TFSI
1824             AUDI                      Q5                      40 TFSI
2396             AUDI                      Q8                      55 TFSI
2499             AUDI                     RS3                          STD
2502             AUDI                     RS3                          STD
2503             AUDI                     RS3                          STD
2507             AUDI                     RS3                          STD
2513             AUDI                     RS3                          STD
2516             AUDI                     RS3                          STD
2524             AUDI                     RS3                          STD
2594             AUDI                      S3                          STD
2598             AUDI                      S3                          STD
2600             AUDI                      S3                          STD
2602             AUDI                      S3                          STD
2604             AUDI                      S3                          STD
2611             AUDI                      S3                          STD
2617             AUDI                      S3                          STD
2618             AUDI                      S3                          STD
2628             AUDI                      S3                          STD
2634             AUDI                      S3                          STD
2641             AUDI                      S3                          STD
2665             AUDI                      S5                          STD
2668             AUDI                      S5                          STD
2829             AUDI                      TT               45 TFSI S-LINE
2873             AUDI                      TT                          STD
2961            AVATR                      12                STD (NON GCC)
2962            AVATR                      12                STD (NON GCC)
2963            AVATR                      12                STD (NON GCC)
2964            AVATR                      12                STD (NON GCC)
2967            AVATR                      12                STD (NON GCC)
2969            AVATR                      12                STD (NON GCC)
3433          BENTLEY             CONTINENTAL                           GT
3499          BENTLEY             CONTINENTAL                GT SUPERSPORT
3500          BENTLEY             CONTINENTAL                GT SUPERSPORT
3501          BENTLEY             CONTINENTAL                GT SUPERSPORT
3642          BENTLEY             FLYING SPUR                          W12
3958              BMW                    220I                          STD
4284              BMW                    320I                          STD
4288              BMW                    320I                          STD
4292              BMW                    320I                          STD
4310              BMW                    320I                          STD
4345              BMW                    320I                          STD
4353              BMW                    320I                          STD
4378              BMW                    320i                          STD
4450              BMW                    325I                          STD
4486              BMW                    325I                          STD
4492              BMW                    325i                          STD
4567              BMW                    328I                          STD
4706              BMW                    330I                          STD
4775              BMW                    335I                          STD
4829              BMW                    420I                      M SPORT
4839              BMW                    420I                      M SPORT
4847              BMW                    420I                      M SPORT
4849              BMW                    420I                      M SPORT
4851              BMW                    420I                      M SPORT
4901              BMW                    420I                  SPORTS LINE
4903              BMW                    420I                  SPORTS LINE
4907              BMW                    420I                  SPORTS LINE
4921              BMW                    420I                  SPORTS LINE
5009              BMW                    428I                   SPORT LINE
5011              BMW                    428I                  SPORTS LINE
5039              BMW                    430I                      M SPORT
5042              BMW                    430I                      M SPORT
5043              BMW                    430I                      M SPORT
5046              BMW                    430I                      M SPORT
5050              BMW                    430I                      M SPORT
5052              BMW                    430I                      M SPORT
5058              BMW                    430I                      M SPORT
5065              BMW                    430I                      M SPORT
5067              BMW                    430I                      M SPORT
5070              BMW                    430I                      M SPORT
5072              BMW                    430I                      M SPORT
5075              BMW                    430I                      M SPORT
5078              BMW                    430I                      M SPORT
5079              BMW                    430I                      M SPORT
5080              BMW                    430I                      M SPORT
5084              BMW                    430I                      M SPORT
5085              BMW                    430I                      M SPORT
5121              BMW                    435I                      M Sport
5122              BMW                    435I                      M Sport
5123              BMW                    435I                      M Sport
5125              BMW                    435I                      M Sport
5133              BMW                    435I                      M Sport
5137              BMW                    435I                      M Sport
5164              BMW                    440I                      M SPORT
5167              BMW                    440I                      M SPORT
5557              BMW                    525I                          STD
5638              BMW                    528I                       LUXURY
6071              BMW                    640I                          STD
6150              BMW                    650I                      M SPORT
6163              BMW                    650I                     M SPORTS
6169              BMW                    650I                          STD
6173              BMW                    650I                          STD
6188              BMW                    650I                          STD
6732              BMW                   750LI                    EXCLUSIVE
6833              BMW                   750LI                XDRIVE LUXURY
6952              BMW                    840I                      M SPORT
6982              BMW                  ALPINA                           B6
7052              BMW                 BMW 530                          STD
7102              BMW           I4 GRAN COUPE                    EDRIVE 35
7304              BMW                      M3                          STD
7366              BMW                      M4                  COMPETITION
7386              BMW                      M4                           CS
7397              BMW                      M4                M COMPETITION
7412              BMW                      M4                          STD
7427              BMW                   M440I                       XDRIVE
7440              BMW                   M440I                       XDRIVE
7441              BMW                   M440I                       XDRIVE
7443              BMW                   M440I                       XDRIVE
7491              BMW                      M5                          STD
7526              BMW                      M6                          STD
7531              BMW                      M8                M COMPETITION
7537              BMW                      M8                M COMPETITION
7550              BMW                   M850I                       xDrive
7551              BMW                   M850I                       xDrive
7552              BMW                   M850I                       xDrive
7554              BMW                   M850I                       xDrive
7557              BMW                   M850I                       xDrive
7562              BMW                   M850I                       xDrive
7564              BMW                   M850I                       xDrive
7565              BMW                   M850I                       xDrive
7567              BMW                   M850I                       xDrive
7649              BMW                      X1           XDRIVE 20i M SPORT
7798              BMW                      X3                           SI
7956              BMW                      X4           XDRIVE 28I M SPORT
8820              BMW                      X6                35i EXECUTIVE
8943              BMW                      X6                        M 50i
8994              BMW                      X6                   XDRIVE 50i
9002              BMW                      X6                   XDRIVE 50i
9166              BMW                      X6          XDRIVE50i EXCLUSIVE
9173              BMW                    X6 M                          STD
9176              BMW                    X6 M                          STD
9349              BMW                      Z4                        25 Si
9366              BMW                      Z4                          STD
9384              BMW                      Z4                   sDrive 20i
9389              BMW                      Z4           sDrive 20i M SPORT
9573              BYD                     HAN                      PREMIUM
9587              BYD                     HAN                      PREMIUM
9695              BYD               LEOPARD 5                STD (NON GCC)
9699              BYD               LEOPARD 5                STD (NON GCC)
9700              BYD               LEOPARD 5                STD (NON GCC)
9783              BYD               LEOPARD 7               STD  (NON GCC)
9888              BYD               LEOPARD 8                 DELUX (NGCC)
10058             BYD                QIN PLUS                      PREMIUM
10092             BYD                SEA LION                          STD
10227             BYD                  SONG L                STD (NON GCC)
10266             BYD               SONG PLUS                          FWD
10277             BYD               SONG PLUS                          FWD
10459        CADILLAC                     ATS                          STD
10467        CADILLAC                     ATS                          STD
10468        CADILLAC                     ATS                          STD
10470        CADILLAC                     ATS                          STD
10472        CADILLAC                     ATS                          STD
10474        CADILLAC                     ATS                          STD
10476        CADILLAC                     ATS                          STD
10481        CADILLAC                     ATS                          STD
10484        CADILLAC                     ATS                          STD
10523        CADILLAC                     CT4                       LUXURY
10624        CADILLAC                     CT6                     PLATINUM
10697        CADILLAC                     CTS                       LUXURY
10743        CADILLAC                     CTS                          STD
10749        CADILLAC                     CTS                          STD
10750        CADILLAC                     CTS                          STD
10785        CADILLAC                 DEVILLE                          STD
10949        CADILLAC                ESCALADE                     PLATINUM
11255        CADILLAC                ESCALADE                          STD
11259        CADILLAC                ESCALADE                          STD
11358        CADILLAC               FLAT WOOD                          STD
11703         CHANGAN                  ALSVIN                      ADVANCE
11786         CHANGAN               CS35 PLUS                      LIMITED
12312           CHERY                   TIGGO                          STD
12354           CHERY                 TIGGO 7                       LUXURY
12532       CHEVROLET                   ASTRO                          STD
12548       CHEVROLET                   ASTRO                          STD
12556       CHEVROLET                   ASTRO                          STD
12592       CHEVROLET               AVALANCHE                      LT  Z71
12698       CHEVROLET                    AVEO                         BASE
12712       CHEVROLET                    AVEO                           LS
12718       CHEVROLET                    AVEO                           LS
12722       CHEVROLET                    AVEO                           LS
12725       CHEVROLET                    AVEO                           LS
12732       CHEVROLET                    AVEO                           LS
12740       CHEVROLET                    AVEO                           LS
12742       CHEVROLET                    AVEO                           LS
12749       CHEVROLET                    AVEO                           LS
12757       CHEVROLET                    AVEO                           LS
12761       CHEVROLET                    AVEO                           LS
12762       CHEVROLET                    AVEO                           LS
12765       CHEVROLET                    AVEO                           LS
12766       CHEVROLET                    AVEO                           LS
12770       CHEVROLET                    AVEO                           LS
12772       CHEVROLET                    AVEO                           LS
12776       CHEVROLET                    AVEO                           LT
12778       CHEVROLET                    AVEO                           LT
12949       CHEVROLET                  CAMARO                           LT
12950       CHEVROLET                  CAMARO                           LT
12952       CHEVROLET                  CAMARO                           LT
12955       CHEVROLET                  CAMARO                           LT
12960       CHEVROLET                  CAMARO                           LT
12963       CHEVROLET                  CAMARO                           LT
12969       CHEVROLET                  CAMARO                           LT
12983       CHEVROLET                  CAMARO                           LT
12987       CHEVROLET                  CAMARO                           LT
12989       CHEVROLET                  CAMARO                           LT
12993       CHEVROLET                  CAMARO                           LT
12994       CHEVROLET                  CAMARO                           LT
12995       CHEVROLET                  CAMARO                           LT
13008       CHEVROLET                  CAMARO                           LT
13016       CHEVROLET                  CAMARO                           LT
13023       CHEVROLET                  CAMARO                           LT
13025       CHEVROLET                  CAMARO                           LT
13072       CHEVROLET                  CAMARO                          LT2
13082       CHEVROLET                  CAMARO                          LT2
13167       CHEVROLET                  CAMARO                           SS
13173       CHEVROLET                  CAMARO                           SS
13177       CHEVROLET                  CAMARO                           SS
13178       CHEVROLET                  CAMARO                           SS
13181       CHEVROLET                  CAMARO                           SS
13183       CHEVROLET                  CAMARO                           SS
13192       CHEVROLET                  CAMARO                           SS
13193       CHEVROLET                  CAMARO                           SS
13194       CHEVROLET                  CAMARO                           SS
13200       CHEVROLET                  CAMARO                           SS
13206       CHEVROLET                  CAMARO                           SS
13214       CHEVROLET                  CAMARO                           SS
13219       CHEVROLET                  CAMARO                           SS
13230       CHEVROLET                  CAMARO                           SS
13231       CHEVROLET                  CAMARO                           SS
13232       CHEVROLET                  CAMARO                           SS
13235       CHEVROLET                  CAMARO                           SS

In [22]:
sorted(df['year'].unique())

[np.float64(1946.0),
 np.float64(1948.0),
 np.float64(1951.0),
 np.float64(1962.0),
 np.float64(1965.0),
 np.float64(1966.0),
 np.float64(1971.0),
 np.float64(1972.0),
 np.float64(1974.0),
 np.float64(1975.0),
 np.float64(1977.0),
 np.float64(1978.0),
 np.float64(1979.0),
 np.float64(1980.0),
 np.float64(1981.0),
 np.float64(1982.0),
 np.float64(1983.0),
 np.float64(1984.0),
 np.float64(1985.0),
 np.float64(1986.0),
 np.float64(1987.0),
 np.float64(1988.0),
 np.float64(1989.0),
 np.float64(1990.0),
 np.float64(1991.0),
 np.float64(1992.0),
 np.float64(1993.0),
 np.float64(1994.0),
 np.float64(1995.0),
 np.float64(1996.0),
 np.float64(1997.0),
 np.float64(1998.0),
 np.float64(1999.0),
 np.float64(2000.0),
 np.float64(2001.0),
 np.float64(2002.0),
 np.float64(2003.0),
 np.float64(2004.0),
 np.float64(2005.0),
 np.float64(2006.0),
 np.float64(2007.0),
 np.float64(2008.0),
 np.float64(2009.0),
 np.float64(2010.0),
 np.float64(2011.0),
 np.float64(2012.0),
 np.float64(2013.0),
 np.float64(2014.0),
 np.float64(2015.0),
 np.float64(2016.0),
 np.float64(2017.0),
 np.float64(2018.0),
 np.float64(2019.0),
 np.float64(2020.0),
 np.float64(2021.0),
 np.float64(2022.0),
 np.float64(2023.0),
 np.float64(2024.0),
 np.float64(2025.0),
 np.float64(2026.0),
 np.float64(nan),
 np.float64(2027.0),
 np.float64(2028.0)]

In [27]:
df.drop(index=df[df['year'] == 1946].index, inplace=True)
df.drop(index=df[df['year'] == 1948].index, inplace=True)
df.drop(index=df[df['year'] == 1951].index, inplace=True)

year complete, only 2027 and 2028 remains.

VIN number is also cleaned

In [25]:
df['make'].value_counts().sort_index()

make
 VANDERHALL                1
 ZHENGZHOU                 1
A                          1
ABARTH                   273
ACURA                     10
ADMIRAL                    1
AEOLUS                    58
AFTEK                      6
AIQAR                      1
AITO                      27
AL DAMANI                 18
ALFA ROMEO               249
AM                         1
APACHE                     1
APULUO                     1
ARI                        1
ASHOK                      1
ASHOK LEYLAND             88
ASTON MARTIN             117
AUDI                    5705
AUDI                       6
AVATR                    204
AVENGER                    2
AYED                       8
AYED                       1
AYED AYED                  1
AYED BIKE                  1
Alfa Romeo                 4
Aprilia                   54
Aston Martin               8
Audi                     282
BAIC                     739
BAJAJ                   1871
BAOJUN                     1
BAOJUN YEP                 1
BAW                       23
BENDA                      3
BENTLEY                 1076
BESTUNE                  478
BIUE BAIRD                 1
BMW                    14902
BMWb                       1
BORGWARD                  23
BRILLIANCE                16
BUGATTI                   34
BUICK                      3
BYD                     5400
BYD - DENZA               82
BYD - YANGWANG            34
Bajaj                    358
Benelli                   11
Bentley                   38
Beta                       1
Bimota                     1
Buell                      1
Buick                      1
CADILLAC                3082
CAN                        2
CAN -AM                    1
CAN AM                     1
CAN AM                     1
CAN AM SPYDER              1
CAN-AM                     6
CATERHAM                   2
CATERPILLAR                1
CF MOTO                    1
CF MOTO 700 CL X           1
CFMOTO                     3
CFMoto                    41
CH                         1
CHAMP                      1
CHANGAN                 3851
CHANGHUA                   4
CHANGHUA                   1
CHANGHUA - MAX180          1
CHANGUA                    1
CHERVOLET                 23
CHERY                    653
CHERY - ICAR             131
CHERY - iCAR               1
CHEVROLET              26721
CHRYSLER                 853
CITROEN                  120
CMC                       91
Cadillac                 132
Chevrolet               1373
Chrysler                  42
Citroen                    4
DAEWOO                     5
DAEWOO 106 BF              1
DAF                        1
DAIHATSU                1382
DATSUN                     5
DEEPAL                   112
DELOREAN                   1
DELTA                      1
DEXER                      1
DFSK                     195
DODGE                   5994
DODGE                      1
DONGFENG                  47
DONGFENG Eπ                5
DONGFENG eπ                1
DONGFENG-AEOLUS           43
DONGFENG-XIAOKA            3
DORCEN                     6
Daihatsu                  20
Dodge                    343
Ducati                    60
ECOWAY                     2
EICHER                     4
EMPALA                     2
EQUATION                   1
ESCHER                     2
EXEED                    477
Electric Motion            1
Exeed                     20
FANTIC                     1
FARIZON                    1
FAW                        6
FERRARI                  387
FIAT                     376
FLONY                      1
FOLONY                     6
FORCE                      2
FORD                   25273
FORD                      19
FORTHING                 116
FOTON                     67
Ferrari                   25
Fiat                      41
Ford                     891
G10                        1
GAC                     1519
GEELY                   2445
GENESIS                 1204
GMC                    14470
GRAND TIGER                1
GRAND TIGER                1
GREAT WALL               663
GUNAU                      2
GWM - WEY                  1
Gas Gas                    2
Geely                     79
Great Wall                36
HAR                        1
HARLEY                     5
HARLEY                     1
HARLEY DAVIDSON            3
HART FORD                  1
HAVAL                   1239
HERO                    1045
HH                         1
HIGER                      1
HINO                     146
HIPHI                      2
HO                         1
HONDA                  50697
HONGQI                   535
HS                         1
HUAIHAI                    7
HUMMER                   425
HYCAN                      2
HYUNDAI                43481
HYUNDAI2120117999          1
Haojue                    14
Harley Davidson            1
Harley-Davidson          392
Hero                      14
Hino                       1
Honda                   1535
Hummer                     7
Husqvarna                  5
Hyosung                    2
Hyundai                 1362
INDIAN  MOTORCYCLE         1
INEOS                     78
INEOS                      5
INFINITI                8889
ISUZU                   1766
ITALJET                    1
IVECO                     34
Indian                    49
Infiniti                 299
Isuzu                      4
JAC                     1729
JAECOO                    32
JAGUAR                  1182
JCB                        1
JEEP                    9277
JETOUR                  8259
JIDU                      15
JINBEI                     1
JIYUE                      1
JMC                       26
JOYLONG                    1
Jaguar                    26
Jeep                     261
KAIYI                    107
KAMA                       1
KAN M                      1
KAOE K1                    1
KAWASAKI                   1
KAWAZAKI                   1
KIA                    33720
KIA                       23
KIA41964                   1
KIMMCO                     1
KING LONG                 19
KOASKO                     1
KOASKO 0                   1
KOENIGSEGG                 1
KTM                       62
Kawasaki                 223
Kia                     1128
Kymco                      6
LADA                      15
LAMBORGHINI              539
LANCIA                     1
LAND ROVER             14720
LEADING                    1
LEADING IDEAL             37
LEAPMOTOR                  4
LEAPMOTORS                11
LEOPARD                    1
LEXUS                  63008
LI                        31
LI AUTO                    8
LIEBHERR                   1
LIFAN                     16
LINCOLN                 2197
LIXIANG                    2
LONSIN                     1
LOTUS                     44
LUCID                      4
LUXGEN                     4
LX                         1
LYKAN                      1
LYNK & CO                 66
Lamborghini               13
Land Rover               524
Lexus                   2158
Li AUTO                    2
Lincoln                   80
Lip Motor                  1
LiveWire                   3
Lotus                      3
MAC                        1
MAEXTRO                    8
MAEXTRO                    1
MAHINDRA                  38
MAHINDRA                   2
MAN                        1
MANN                       1
MASERATI                 662
MAXUS                    504
MAYBACH                    5
MAZDA                   8997
MCLAREN                   78
MERCEDES                   1
MERCEDES BENZ          34015
MERCEDES-BENZ           1508
MERCURY                  185
MG                      7394
MHERO                      1
MINI                    2643
MINI COUPE                 1
MITSUBISHI             49615
MOCK                       1
MORGAN                     6
MV                         1
MV Agusta                  5
Maclaren                   2
Mahindra                   2
Maserati                  38
Maxus                     16
Mazda                    355
Mercury                    6
Mini                     150
Mitsubishi               869
Montesa                    1
Moto Guzzi                 6
NETA                       2
NIO                       24
NISSAN                203010
NISSEN                     1
Nissan                  6425
OCC                        1
OMODA                      3
OPEL                     218
Opel                       5
PADAR                      1
PAGANI                     3
PEMBLETON                  1
PEUGEOT                 2650
POL                        1
POLARIS                    5
POLESTAR                  83
PONTIAC                   10
PONTICA                    1
PORSCHE                 4246
POWER                      1
POWEREAGLE                14
PREVOST                    1
PROTON                     4
PUYUAN                     1
Peugeot                   54
Piaggio                   13
Polaris                  131
Porsche                  138
QINGLING                   4
RABDAN                   216
RAM                     2172
RANGE  ROVER               1
RANGE ROVER                3
RENAULT                 5272
RIDDARA                   15
RIVIAN                    25
ROCKY                      1
ROLLS ROYCE             1135
ROX                     2709
ROYAL ALLOY                1
Renault                  103
Rolls Royce               20
Royal Enfield             58
SAAB                      14
SAIC                       2
SAIMO                      1
SAMSUNG                    1
SANDSTORM                  3
SANIYA                     1
SANY                       1
SANYA                    169
SANYA                      1
SANYOU                     1
SATURN                     3
SCANIA                     2
SCION                      3
SEAT                      65
SERES                     47
SHANG JAN                  1
SHARAMAX                   3
SHARMAX                  132
SHARMAX                    2
SHARMAX ENDURO 2           1
SILNGSHOT                  1
SINOTRUK                   1
SKODA                    797
SKYWELL                   10
SLING SHOT                 1
SLINGSHOT                  4
SMART                     77
SOUEAST                  115
SOUO                       1
SPYDER                     1
SSANGYONG                 22
STD                        1
SUBARU                   657
SUZUKI                 11684
SWIFT                      1
SWM                        1
SYM                       18
Sanya                      5
Scorpa                     1
Sherco                     5
Skoda                     46
Smart                      8
Subaru                    45
Suzuki                   359
T7                         1
TAM                        2
TANK                     465
TATA                      74
TESLA                  12081
TESLA2130144264            1
TGB                        5
TOYOTA                234731
TOYOTA2100875058           1
TRALER                     1
TRD                        1
TRIUMPH                    1
TRUMPCHI                   3
TVS                      184
TYANMA                     1
Tata                       1
Tesla                    833
Toyota                  5166
Triumph                   33
UAZ                       13
UNICORN                    2
UNKNOWN                    1
VANDER                     1
VANDERHALL                 9
VANDERHALL                 2
VESPA                     32
VESPA                      2
VGV                        3
VICTORIA                   5
VICTORIA                   1
VICTORY                  569
VINFAST                    3
VOLG                       1
VOLKSWAGEN             10425
VOLTAMP                    7
VOLVO                    994
VOYAH                     95
Vespa                    200
Victoria                   1
Victory                   15
Volkswagen               532
Volvo                     34
WIESMANN                   3
WULING                     5
XAOMI                     84
XCMG                       1
XIAOMI                    21
XPENG                     57
YAHAMA                     2
YAMAH                      1
YAMAHA                     5
YBR 125                    1
Yadea                      2
Yamaha                   345
Yamaha                     1
ZAMIYAD                    1
ZEEKR                    233
ZENIN                      1
ZHENGZHOU                  1
ZHENGZHOU                  1
ZNA                       90
ZNIN                       1
ZONSEN                     5
ZONTES                     1
ZOTYE                     11
ZX AUTO                    1
ZXAUTO                     5
Zero                       1
Zongshen                   7
baja                       1
baw                        1
empala                     1
hig                        1
kove                       1
polaris                    1
vanderhall                 1
vespa                      1
Name: count, dtype: int64

In [39]:
df["make"] = df["make"].str.upper().str.strip()

In [40]:
df["make"] = df["make"].str.strip()

In [43]:
digit_makes = (
    df[df["make"].str.contains(r"\d", na=False)]["make"]
    .value_counts()
)

print(digit_makes)

Series([], Name: count, dtype: int64)

In [42]:
import re

def remove_trailing_numbers(x):
    match = re.match(r"([A-Z\s\-]+)", str(x))
    return match.group(1).strip() if match else x

df["make"] = df["make"].apply(remove_trailing_numbers)

In [44]:
make_mapping = {
    "NISSEN": "NISSAN",
    "CHERVOLET": "CHEVROLET",
    "YAHAMA": "YAMAHA",
    "KAWAZAKI": "KAWASAKI",
    "MERCEDES-BENZ": "MERCEDES BENZ",
    "LEAPMOTORS": "LEAPMOTOR",
    "XAOMI": "XIAOMI",
}

In [45]:
df["make"] = df["make"].replace(make_mapping)

In [59]:
cols = [
    "make",
    "model",
    "trim",
    "chassisNumber",
]

df[df["make"] == "BAOJUN YEP"][cols].head(20)

               make        model trim      chassisNumber
1009481  BAOJUN YEP  YEP/STATION  STD  LK6ADAE26SG000080

In [53]:
from rapidfuzz import process

makes = df["make"].unique()

for make in makes:
    matches = process.extract(
        make,
        makes,
        limit=5
    )

    print(make, matches)

TOYOTA [('TOYOTA', 100.0, 0), ('A', 90.0, 265), ('T', 90.0, 274), ('TAM', 72.0, 202), ('TANK', 60.00000000000001, 58)]
NISSAN [('NISSAN', 100.0, 1), ('A', 90.0, 265), ('SANY', 77.14285714285715, 296), ('SSANGYONG', 72.0, 122), ('NIO', 72.0, 125)]
LEXUS [('LEXUS', 100.0, 2), ('DONGFENG-AEOLUS', 67.5, 117), ('LI', 60.00000000000001, 123), ('LX', 60.00000000000001, 301), ('HS', 60.00000000000001, 319)]
MITSUBISHI [('MITSUBISHI', 100.0, 3), ('HIG', 72.0, 258), ('MG', 60.00000000000001, 20), ('MINI', 60.00000000000001, 30), ('TVS', 60.00000000000001, 73)]
HONDA [('HONDA', 100.0, 4), ('A', 90.0, 265), ('HO', 90.0, 312), ('DAF', 72.0, 226), ('HYUNDAI', 66.66666666666667, 5)]
HYUNDAI [('HYUNDAI', 100.0, 5), ('A', 90.0, 265), ('ARI', 72.0, 303), ('HONDA', 66.66666666666667, 4), ('AUDI', 60.00000000000001, 23)]
KIA [('KIA', 100.0, 6), ('A', 90.0, 265), ('SUZUKI', 72.0, 14), ('KAWASAKI', 72.0, 68), ('KAIYI', 72.0, 87)]
MERCEDES BENZ [('MERCEDES BENZ', 100.0, 7), ('MERCEDES', 90.0, 255), ('MHERO', 67.5, 323), ('MERCURY', 65.45454545454547, 77), ('BENDA', 64.125, 203)]
CHEVROLET [('CHEVROLET', 100.0, 8), ('CH', 90.0, 285), ('CHERY', 72.0, 54), ('MHERO', 72.0, 323), ('HERO', 67.5, 44)]
FORD [('FORD', 100.0, 9), ('HART FORD', 90.0, 270), ('FORTHING', 77.14285714285715, 78), ('FORCE', 66.66666666666667, 196), ('BORGWARD', 60.00000000000001, 127)]
TESLA [('TESLA', 100.0, 10), ('A', 90.0, 265), ('T', 90.0, 274), ('MONTESA', 66.66666666666667, 221), ('TVS', 60.00000000000001, 73)]
BMW [('BMW', 100.0, 11), ('BMWB', 85.71428571428572, 262), ('BAW', 66.66666666666667, 132), ('BIMOTA', 60.00000000000001, 335), ('GWM - WEY', 57.0, 243)]
GMC [('GMC', 100.0, 12), ('G', 90.0, 271), ('MCLAREN', 72.0, 95), ('GAC', 66.66666666666667, 37), ('CMC', 66.66666666666667, 89)]
LAND ROVER [('LAND ROVER', 100.0, 13), ('RANGE ROVER', 76.19047619047619, 185), ('RANGE  ROVER', 72.72727272727273, 330), ('LIFAN', 67.5, 120), ('LADA', 67.5, 128)]
SUZUKI [('SUZUKI', 100.0, 14), ('ISUZU', 72.72727272727273, 34), ('KIA', 72.0, 6), ('LI', 60.00000000000001, 123), ('UAZ', 60.00000000000001, 144)]
VOLKSWAGEN [('VOLKSWAGEN', 100.0, 15), ('VOLG', 77.14285714285715, 214), ('VOLVO', 67.5, 45), ('LUXGEN', 60.00000000000001, 158), ('SWM', 60.00000000000001, 242)]
JETOUR [('JETOUR', 100.0, 16), ('T', 90.0, 274), ('JEEP', 60.00000000000001, 18), ('LEAPMOTOR', 60.00000000000001, 142), ('LIP MOTOR', 60.00000000000001, 293)]
MAZDA [('MAZDA', 100.0, 17), ('A', 90.0, 265), ('DAF', 72.0, 226), ('MAC', 72.0, 228), ('MAN', 72.0, 290)]
JEEP [('JEEP', 100.0, 18), ('DEEPAL', 67.5, 82), ('JETOUR', 60.00000000000001, 16), ('BAOJUN YEP', 60.00000000000001, 257), ('JAECOO', 51.42857142857142, 111)]
INFINITI [('INFINITI', 100.0, 19), ('T', 90.0, 274), ('MINI', 67.5, 30), ('ZNIN', 67.5, 277), ('HINO', 60.00000000000001, 80)]
MG [('MG', 100.0, 20), ('XCMG', 90.0, 240), ('G', 90.0, 271), ('MITSUBISHI', 60.00000000000001, 3), ('MERCEDES BENZ', 60.00000000000001, 7)]
BYD [('BYD', 100.0, 21), ('BYD - DENZA', 90.0, 93), ('BYD - YANGWANG', 90.0, 113), ('HARLEY-DAVIDSON', 60.00000000000001, 63), ('RABDAN', 60.00000000000001, 66)]
DODGE [('DODGE', 100.0, 22), ('G', 90.0, 271), ('DONGFENG', 61.53846153846154, 110), ('DONGFENG-AEOLUS', 60.00000000000001, 117), ('DONGFENG E', 60.00000000000001, 145)]
AUDI [('AUDI', 100.0, 23), ('A', 90.0, 265), ('CADILLAC', 67.5, 29), ('LEADING IDEAL', 67.5, 121), ('LEADING', 67.5, 207)]
RENAULT [('RENAULT', 100.0, 24), ('A', 90.0, 265), ('T', 90.0, 274), ('ZNA', 60.00000000000001, 88), ('SEAT', 54.54545454545454, 107)]
CHANGAN [('CHANGAN', 100.0, 25), ('A', 90.0, 265), ('G', 90.0, 271), ('CH', 90.0, 285), ('CHANGUA', 85.71428571428572, 314)]
PORSCHE [('PORSCHE', 100.0, 26), ('CH', 90.0, 285), ('POL', 72.0, 333), ('FORCE', 66.66666666666667, 196), ('DORCEN', 61.53846153846154, 177)]
PEUGEOT [('PEUGEOT', 100.0, 27), ('G', 90.0, 271), ('T', 90.0, 274), ('OPEL', 60.00000000000001, 69), ('PREVOST', 57.14285714285714, 272)]
ROX [('ROX', 100.0, 28), ('ROLLS ROYCE', 72.0, 43), ('ROYAL ENFIELD', 72.0, 105), ('MAEXTRO', 72.0, 166), ('ROYAL ALLOY', 72.0, 246)]
CADILLAC [('CADILLAC', 100.0, 29), ('A', 90.0, 265), ('JAC', 72.0, 36), ('GAC', 72.0, 37), ('CAN', 72.0, 217)]
MINI [('MINI', 100.0, 30), ('MINI COUPE', 90.0, 310), ('LAMBORGHINI', 77.14285714285715, 59), ('INFINITI', 67.5, 19), ('INDIAN', 67.5, 104)]
GEELY [('GEELY', 100.0, 31), ('G', 90.0, 271), ('MG', 60.00000000000001, 20), ('DEEPAL', 54.54545454545454, 82), ('GWM - WEY', 51.42857142857142, 243)]
RAM [('RAM', 100.0, 32), ('SHARAMAX', 90.0, 206), ('A', 90.0, 265), ('AM', 90.0, 331), ('RABDAN', 72.0, 66)]
LINCOLN [('LINCOLN', 100.0, 33), ('LI', 90.0, 123), ('HINO', 67.5, 80), ('LYNK', 60.00000000000001, 102), ('NIO', 60.00000000000001, 125)]
ISUZU [('ISUZU', 100.0, 34), ('SUZUKI', 72.72727272727273, 14), ('LI', 60.00000000000001, 123), ('UAZ', 60.00000000000001, 144), ('SUBARU', 54.54545454545454, 51)]
BAJAJ [('BAJAJ', 100.0, 35), ('A', 90.0, 265), ('BAJA', 88.88888888888889, 307), ('BAW', 72.0, 132), ('JAC', 60.00000000000001, 36)]
JAC [('JAC', 100.0, 36), ('A', 90.0, 265), ('CADILLAC', 72.0, 29), ('JAGUAR', 72.0, 42), ('JAECOO', 72.0, 111)]
GAC [('GAC', 100.0, 37), ('A', 90.0, 265), ('G', 90.0, 271), ('CADILLAC', 72.0, 29), ('ACURA', 72.0, 140)]
DAIHATSU [('DAIHATSU', 100.0, 38), ('A', 90.0, 265), ('T', 90.0, 274), ('DAF', 72.0, 226), ('DATSUN', 71.42857142857143, 126)]
HAVAL [('HAVAL', 100.0, 39), ('A', 90.0, 265), ('HAR', 72.0, 320), ('HARLEY-DAVIDSON', 60.00000000000001, 63), ('LI', 60.00000000000001, 123)]
BENTLEY [('BENTLEY', 100.0, 40), ('T', 90.0, 274), ('BETA', 67.5, 248), ('BESTUNE', 57.14285714285714, 55), ('BENELLI', 57.14285714285714, 143)]
GENESIS [('GENESIS', 100.0, 41), ('G', 90.0, 271), ('MG', 60.00000000000001, 20), ('HS', 60.00000000000001, 319), ('BENELLI', 57.14285714285714, 143)]
JAGUAR [('JAGUAR', 100.0, 42), ('A', 90.0, 265), ('G', 90.0, 271), ('JAC', 72.0, 36), ('ARI', 72.0, 303)]
ROLLS ROYCE [('ROLLS ROYCE', 100.0, 43), ('ROX', 72.0, 28), ('HERO', 60.00000000000001, 44), ('ZOTYE', 60.00000000000001, 137), ('FORCE', 60.00000000000001, 196)]
HERO [('HERO', 100.0, 44), ('MHERO', 88.88888888888889, 323), ('SHERCO', 80.0, 151), ('EICHER', 77.14285714285715, 163), ('ESCHER', 77.14285714285715, 224)]
VOLVO [('VOLVO', 100.0, 45), ('VOLKSWAGEN', 67.5, 15), ('VOLG', 66.66666666666667, 214), ('MV', 60.00000000000001, 280), ('HO', 60.00000000000001, 312)]
BAIC [('BAIC', 100.0, 46), ('A', 90.0, 265), ('SAIC', 75.0, 209), ('BIUE BAIRD', 73.28571428571429, 241), ('MAYBACH', 67.5, 181)]
CHRYSLER [('CHRYSLER', 100.0, 47), ('CH', 90.0, 285), ('CHERY', 80.0, 54), ('HERO', 60.00000000000001, 44), ('CHERY - ICAR', 60.00000000000001, 76)]
SKODA [('SKODA', 100.0, 48), ('A', 90.0, 265), ('DAF', 72.0, 226), ('HS', 60.00000000000001, 319), ('AM', 60.00000000000001, 331)]
HONGQI [('HONGQI', 100.0, 49), ('G', 90.0, 271), ('HO', 90.0, 312), ('HYOSUNG', 61.53846153846154, 194), ('HERO', 60.00000000000001, 44)]
VICTORY [('VICTORY', 100.0, 50), ('T', 90.0, 274), ('VICTORIA', 80.0, 157), ('AITO', 67.5, 116), ('MV', 60.00000000000001, 280)]
SUBARU [('SUBARU', 100.0, 51), ('A', 90.0, 265), ('BAW', 60.00000000000001, 132), ('UAZ', 60.00000000000001, 144), ('SOUO', 60.00000000000001, 295)]
GREAT WALL [('GREAT WALL', 100.0, 52), ('SEAT', 67.5, 107), ('MG', 60.00000000000001, 20), ('RAM', 60.00000000000001, 32), ('LI', 60.00000000000001, 123)]
MASERATI [('MASERATI', 100.0, 53), ('A', 90.0, 265), ('T', 90.0, 274), ('MAC', 72.0, 228), ('MAN', 72.0, 290)]
CHERY [('CHERY', 100.0, 54), ('CHERY - ICAR', 90.0, 76), ('CH', 90.0, 285), ('CHRYSLER', 80.0, 47), ('EICHER', 72.72727272727273, 163)]
BESTUNE [('BESTUNE', 100.0, 55), ('T', 90.0, 274), ('BETA', 67.5, 248), ('SATURN', 61.53846153846154, 193), ('NETA', 60.00000000000001, 225)]
EXEED [('EXEED', 100.0, 56), ('DEXER', 60.0, 267), ('AYED AYED', 57.0, 231), ('MERCEDES BENZ', 54.0, 7), ('MERCEDES', 54.0, 255)]
MAXUS [('MAXUS', 100.0, 57), ('A', 90.0, 265), ('MAC', 72.0, 228), ('MAN', 72.0, 290), ('MASERATI', 67.5, 53)]
TANK [('TANK', 100.0, 58), ('A', 90.0, 265), ('T', 90.0, 274), ('TYANMA', 67.5, 199), ('TOYOTA', 60.00000000000001, 0)]
LAMBORGHINI [('LAMBORGHINI', 100.0, 59), ('AM', 90.0, 331), ('MINI', 77.14285714285715, 30), ('NIO', 72.0, 125), ('HINO', 67.5, 80)]
FIAT [('FIAT', 100.0, 60), ('A', 90.0, 265), ('T', 90.0, 274), ('DAIHATSU', 67.5, 38), ('VINFAST', 67.5, 208)]
HUMMER [('HUMMER', 100.0, 61), ('MERCEDES BENZ', 60.00000000000001, 7), ('HERO', 60.00000000000001, 44), ('HH', 60.00000000000001, 259), ('CH', 60.00000000000001, 285)]
YAMAHA [('YAMAHA', 100.0, 62), ('YAMAH', 90.9090909090909, 329), ('A', 90.0, 265), ('AM', 90.0, 331), ('HAR', 72.0, 320)]
HARLEY-DAVIDSON [('HARLEY-DAVIDSON', 100.0, 63), ('HARLEY DAVIDSON', 93.33333333333333, 216), ('HARLEY', 90.0, 175), ('HAR', 90.0, 320), ('SCION', 67.5, 171)]
FERRARI [('FERRARI', 100.0, 64), ('A', 90.0, 265), ('ARI', 90.0, 303), ('RAM', 60.00000000000001, 32), ('LI', 60.00000000000001, 123)]
ALFA ROMEO [('ALFA ROMEO', 100.0, 65), ('MHERO', 67.5, 323), ('ROX', 60.00000000000001, 28), ('RAM', 60.00000000000001, 32), ('HERO', 60.00000000000001, 44)]
RABDAN [('RABDAN', 100.0, 66), ('A', 90.0, 265), ('RAM', 72.0, 32), ('CAN', 72.0, 217), ('MAN', 72.0, 290)]
DFSK [('DFSK', 100.0, 67), ('SKYWELL', 60.00000000000001, 139), ('DAF', 57.14285714285714, 226), ('MERCEDES', 51.42857142857142, 255), ('KOASKO', 51.42857142857142, 283)]
KAWASAKI [('KAWASAKI', 100.0, 68), ('A', 90.0, 265), ('KIA', 72.0, 6), ('KAMA', 67.5, 180), ('SAIC', 67.5, 209)]
OPEL [('OPEL', 100.0, 69), ('MINI COUPE', 67.5, 310), ('PEUGEOT', 60.00000000000001, 27), ('LI', 60.00000000000001, 123), ('LX', 60.00000000000001, 301)]
AVATR [('AVATR', 100.0, 70), ('A', 90.0, 265), ('T', 90.0, 274), ('TRD', 72.0, 334), ('ARI', 60.00000000000001, 303)]
ZEEKR [('ZEEKR', 100.0, 71), ('ZERO', 66.66666666666667, 297), ('DEXER', 60.0, 267), ('EICHER', 54.54545454545454, 163), ('ESCHER', 54.54545454545454, 224)]
ABARTH [('ABARTH', 100.0, 72), ('A', 90.0, 265), ('T', 90.0, 274), ('MAYBACH', 61.53846153846154, 181), ('BAW', 60.00000000000001, 132)]
TVS [('TVS', 100.0, 73), ('T', 90.0, 274), ('MITSUBISHI', 60.00000000000001, 3), ('TESLA', 60.00000000000001, 10), ('DAIHATSU', 60.00000000000001, 38)]
VESPA [('VESPA', 100.0, 74), ('A', 90.0, 265), ('TVS', 60.00000000000001, 73), ('MV', 60.00000000000001, 280), ('AM', 60.00000000000001, 331)]
POLARIS [('POLARIS', 100.0, 75), ('A', 90.0, 265), ('ARI', 90.0, 303), ('POL', 90.0, 333), ('POLESTAR', 66.66666666666667, 90)]
CHERY - ICAR [('CHERY - ICAR', 100.0, 76), ('CHERY', 90.0, 54), ('CH', 90.0, 285), ('EICHER', 72.0, 163), ('ESCHER', 72.0, 224)]
MERCURY [('MERCURY', 100.0, 77), ('MERCEDES BENZ', 65.45454545454547, 7), ('MG', 60.00000000000001, 20), ('MV', 60.00000000000001, 280), ('AM', 60.00000000000001, 331)]
FORTHING [('FORTHING', 100.0, 78), ('G', 90.0, 271), ('T', 90.0, 274), ('FORD', 77.14285714285715, 9), ('HINO', 67.5, 80)]
SOUEAST [('SOUEAST', 100.0, 79), ('A', 90.0, 265), ('T', 90.0, 274), ('SOUO', 77.14285714285715, 295), ('SEAT', 72.72727272727273, 107)]
HINO [('HINO', 100.0, 80), ('LINCOLN', 67.5, 33), ('LAMBORGHINI', 67.5, 59), ('FORTHING', 67.5, 78), ('MAHINDRA', 67.5, 114)]
SANYA [('SANYA', 100.0, 81), ('SANIYA', 90.9090909090909, 254), ('A', 90.0, 265), ('SANY', 88.88888888888889, 296), ('SCANIA', 72.72727272727273, 223)]
DEEPAL [('DEEPAL', 100.0, 82), ('A', 90.0, 265), ('LEADING IDEAL', 72.0, 121), ('JEEP', 67.5, 18), ('EMPALA', 66.66666666666667, 234)]
VOYAH [('VOYAH', 100.0, 83), ('A', 90.0, 265), ('ROYAL ENFIELD', 60.00000000000001, 105), ('ROYAL ALLOY', 60.00000000000001, 246), ('HH', 60.00000000000001, 259)]
CITROEN [('CITROEN', 100.0, 84), ('T', 90.0, 274), ('AITO', 67.5, 116), ('SCION', 66.66666666666667, 171), ('ROX', 60.00000000000001, 28)]
ASTON MARTIN [('ASTON MARTIN', 100.0, 85), ('SMART', 72.0, 94), ('GAS GAS', 68.4, 229), ('AITO', 67.5, 116), ('MASERATI', 64.28571428571429, 53)]
SHARMAX [('SHARMAX', 100.0, 86), ('SHARAMAX', 93.33333333333333, 206), ('A', 90.0, 265), ('SHARMAX ENDURO', 90.0, 309), ('HAR', 90.0, 320)]
KAIYI [('KAIYI', 100.0, 87), ('A', 90.0, 265), ('KIA', 72.0, 6), ('LI', 60.00000000000001, 123), ('ARI', 60.00000000000001, 303)]
ZNA [('ZNA', 100.0, 88), ('A', 90.0, 265), ('BYD - DENZA', 72.0, 93), ('HUSQVARNA', 72.0, 173), ('ZAMIYAD', 72.0, 282)]
CMC [('CMC', 100.0, 89), ('MCLAREN', 72.0, 95), ('GMC', 66.66666666666667, 12), ('JMC', 66.66666666666667, 124), ('MAC', 66.66666666666667, 228)]
POLESTAR [('POLESTAR', 100.0, 90), ('A', 90.0, 265), ('T', 90.0, 274), ('POL', 90.0, 333), ('ARI', 72.0, 303)]
XIAOMI [('XIAOMI', 100.0, 91), ('A', 90.0, 265), ('KIA', 60.00000000000001, 6), ('MINI', 60.00000000000001, 30), ('RAM', 60.00000000000001, 32)]
ASHOK LEYLAND [('ASHOK LEYLAND', 100.0, 92), ('ASHOK', 90.0, 232), ('HO', 90.0, 312), ('GAS GAS', 68.4, 229), ('LADA', 67.5, 128)]
BYD - DENZA [('BYD - DENZA', 100.0, 93), ('BYD', 90.0, 21), ('ZNA', 72.0, 88), ('BYD - YANGWANG', 64.0, 113), ('BENDA', 60.00000000000001, 203)]
SMART [('SMART', 100.0, 94), ('A', 90.0, 265), ('T', 90.0, 274), ('ASTON MARTIN', 72.0, 85), ('SYM', 72.0, 133)]
MCLAREN [('MCLAREN', 100.0, 95), ('MACLAREN', 93.33333333333333, 237), ('A', 90.0, 265), ('GMC', 72.0, 12), ('CMC', 72.0, 89)]
INEOS [('INEOS', 100.0, 96), ('HINO', 66.66666666666667, 80), ('LI', 60.00000000000001, 123), ('NIO', 60.00000000000001, 125), ('WIESMANN', 60.00000000000001, 210)]
LOTUS [('LOTUS', 100.0, 97), ('T', 90.0, 274), ('DONGFENG-AEOLUS', 67.5, 117), ('TVS', 60.00000000000001, 73), ('LI', 60.00000000000001, 123)]
FOTON [('FOTON', 100.0, 98), ('T', 90.0, 274), ('CFMOTO', 72.72727272727273, 112), ('FOLONY', 72.72727272727273, 165), ('PROTON', 72.72727272727273, 183)]
AEOLUS [('AEOLUS', 100.0, 99), ('DONGFENG-AEOLUS', 90.0, 117), ('A', 90.0, 265), ('AYED', 60.00000000000001, 156), ('HS', 60.00000000000001, 319)]
TATA [('TATA', 100.0, 100), ('A', 90.0, 265), ('T', 90.0, 274), ('TOYOTA', 60.00000000000001, 0), ('MV AGUSTA', 60.00000000000001, 174)]
KTM [('KTM', 100.0, 101), ('T', 90.0, 274), ('TAM', 66.66666666666667, 202), ('MG', 60.00000000000001, 20), ('KYMCO', 60.00000000000001, 167)]
LYNK [('LYNK', 100.0, 102), ('LYKAN', 66.66666666666667, 205), ('LINCOLN', 60.00000000000001, 33), ('LI', 60.00000000000001, 123), ('LX', 60.00000000000001, 301)]
XPENG [('XPENG', 100.0, 103), ('G', 90.0, 271), ('DONGFENG', 67.5, 110), ('MG', 60.00000000000001, 20), ('LX', 60.00000000000001, 301)]
INDIAN [('INDIAN', 100.0, 104), ('A', 90.0, 265), ('INDIAN  MOTORCYCLE', 90.0, 299), ('CAN', 72.0, 217), ('MAN', 72.0, 290)]
ROYAL ENFIELD [('ROYAL ENFIELD', 100.0, 105), ('ROX', 72.0, 28), ('ROCKY', 67.5, 256), ('HERO', 60.00000000000001, 44), ('VOYAH', 60.00000000000001, 83)]
SERES [('SERES', 100.0, 106), ('MERCEDES', 61.53846153846154, 255), ('CHRYSLER', 60.00000000000001, 47), ('HS', 60.00000000000001, 319), ('MERCEDES BENZ', 57.0, 7)]
SEAT [('SEAT', 100.0, 107), ('A', 90.0, 265), ('T', 90.0, 274), ('SATURN', 77.14285714285715, 193), ('SOUEAST', 72.72727272727273, 79)]
APRILIA [('APRILIA', 100.0, 108), ('LI', 90.0, 123), ('A', 90.0, 265), ('KIA', 72.0, 6), ('RIVIAN', 61.53846153846154, 129)]
DUCATI [('DUCATI', 100.0, 109), ('A', 90.0, 265), ('T', 90.0, 274), ('BUGATTI', 61.53846153846154, 118), ('LI', 60.00000000000001, 123)]
DONGFENG [('DONGFENG', 100.0, 110), ('DONGFENG E', 95.0, 145), ('DONGFENG-AEOLUS', 90.0, 117), ('DONGFENG-XIAOKA', 90.0, 189), ('G', 90.0, 271)]
JAECOO [('JAECOO', 100.0, 111), ('A', 90.0, 265), ('JAC', 72.0, 36), ('DAEWOO', 66.66666666666667, 187), ('GAC', 60.00000000000001, 37)]
CFMOTO [('CFMOTO', 100.0, 112), ('CF MOTO', 92.3076923076923, 279), ('T', 90.0, 274), ('FOTON', 72.72727272727273, 98), ('MOTO GUZZI', 72.0, 159)]
BYD - YANGWANG [('BYD - YANGWANG', 100.0, 113), ('BYD', 90.0, 21), ('GWM - WEY', 85.5, 243), ('CHANGAN', 64.28571428571429, 25), ('BYD - DENZA', 64.0, 93)]
MAHINDRA [('MAHINDRA', 100.0, 114), ('A', 90.0, 265), ('RAM', 72.0, 32), ('MAC', 72.0, 228), ('MAN', 72.0, 290)]
IVECO [('IVECO', 100.0, 115), ('LI', 60.00000000000001, 123), ('LIVEWIRE', 60.00000000000001, 213), ('HO', 60.00000000000001, 312), ('INEOS', 60.0, 96)]
AITO [('AITO', 100.0, 116), ('A', 90.0, 265), ('T', 90.0, 274), ('VICTORY', 67.5, 50), ('CITROEN', 67.5, 84)]
DONGFENG-AEOLUS [('DONGFENG-AEOLUS', 100.0, 117), ('AEOLUS', 90.0, 99), ('DONGFENG', 90.0, 110), ('DONGFENG E', 80.0, 145), ('DONGFENG-XIAOKA', 73.33333333333334, 189)]
BUGATTI [('BUGATTI', 100.0, 118), ('A', 90.0, 265), ('G', 90.0, 271), ('T', 90.0, 274), ('DUCATI', 61.53846153846154, 109)]
TRIUMPH [('TRIUMPH', 100.0, 119), ('T', 90.0, 274), ('TRUMPCHI', 80.0, 212), ('TRD', 72.0, 334), ('HH', 60.00000000000001, 259)]
LIFAN [('LIFAN', 100.0, 120), ('LI', 90.0, 123), ('A', 90.0, 265), ('BRILLIANCE', 72.0, 135), ('CAN', 72.0, 217)]
LEADING IDEAL [('LEADING IDEAL', 100.0, 121), ('LEADING', 90.0, 207), ('DEEPAL', 72.0, 82), ('AUDI', 67.5, 23), ('LADA', 67.5, 128)]
SSANGYONG [('SSANGYONG', 100.0, 122), ('SANYOU', 75.00000000000001, 264), ('NISSAN', 72.0, 1), ('SANYA', 72.0, 81), ('SANY', 67.5, 296)]
LI [('LI', 100.0, 123), ('LINCOLN', 90.0, 33), ('APRILIA', 90.0, 108), ('LIFAN', 90.0, 120), ('BRILLIANCE', 90.0, 135)]
JMC [('JMC', 100.0, 124), ('MCLAREN', 72.0, 95), ('GMC', 66.66666666666667, 12), ('JAC', 66.66666666666667, 36), ('CMC', 66.66666666666667, 89)]
NIO [('NIO', 100.0, 125), ('NISSAN', 72.0, 1), ('LAMBORGHINI', 72.0, 59), ('AL DAMANI', 72.0, 131), ('PIAGGIO', 72.0, 138)]
DATSUN [('DATSUN', 100.0, 126), ('A', 90.0, 265), ('T', 90.0, 274), ('DAF', 72.0, 226), ('DAIHATSU', 71.42857142857143, 38)]
BORGWARD [('BORGWARD', 100.0, 127), ('A', 90.0, 265), ('G', 90.0, 271), ('TRD', 72.0, 334), ('FORD', 60.00000000000001, 9)]
LADA [('LADA', 100.0, 128), ('A', 90.0, 265), ('LAND ROVER', 67.5, 13), ('RABDAN', 67.5, 66), ('ASHOK LEYLAND', 67.5, 92)]
RIVIAN [('RIVIAN', 100.0, 129), ('A', 90.0, 265), ('CAN', 72.0, 217), ('MAN', 72.0, 290), ('ARI', 72.0, 303)]
KING LONG [('KING LONG', 100.0, 130), ('KIA', 72.0, 6), ('QINGLING', 70.58823529411764, 195), ('MG', 60.00000000000001, 20), ('HONGQI', 60.00000000000001, 49)]
AL DAMANI [('AL DAMANI', 100.0, 131), ('MAN', 90.0, 290), ('AM', 90.0, 331), ('NIO', 72.0, 125), ('MINI', 67.5, 30)]
BAW [('BAW', 100.0, 132), ('A', 90.0, 265), ('BAJAJ', 72.0, 35), ('BAOJUN YEP', 72.0, 257), ('BAOJUN', 72.0, 294)]
SYM [('SYM', 100.0, 133), ('SMART', 72.0, 94), ('SWM', 66.66666666666667, 242), ('MG', 60.00000000000001, 20), ('YAMAHA', 60.00000000000001, 62)]
RIDDARA [('RIDDARA', 100.0, 134), ('A', 90.0, 265), ('RAM', 72.0, 32), ('ARI', 72.0, 303), ('DAF', 60.00000000000001, 226)]
BRILLIANCE [('BRILLIANCE', 100.0, 135), ('LI', 90.0, 123), ('LIFAN', 72.0, 120), ('YBR', 72.0, 325), ('RIVIAN', 62.5, 129)]
JIDU [('JIDU', 100.0, 136), ('JIYUE', 66.66666666666667, 192), ('DUCATI', 60.00000000000001, 109), ('JINBEI', 60.00000000000001, 247), ('LEADING IDEAL', 57.0, 121)]
ZOTYE [('ZOTYE', 100.0, 137), ('T', 90.0, 274), ('ZONTES', 72.72727272727273, 201), ('ROLLS ROYCE', 60.00000000000001, 43), ('AYED AYED', 57.0, 231)]
PIAGGIO [('PIAGGIO', 100.0, 138), ('A', 90.0, 265), ('G', 90.0, 271), ('NIO', 72.0, 125), ('PAGANI', 61.53846153846154, 191)]
SKYWELL [('SKYWELL', 100.0, 139), ('DFSK', 60.00000000000001, 67), ('LI', 60.00000000000001, 123), ('SYM', 60.00000000000001, 133), ('LX', 60.00000000000001, 301)]
ACURA [('ACURA', 100.0, 140), ('A', 90.0, 265), ('RAM', 72.0, 32), ('JAC', 72.0, 36), ('GAC', 72.0, 37)]
SAAB [('SAAB', 100.0, 141), ('A', 90.0, 265), ('SANYA', 66.66666666666667, 81), ('ABARTH', 60.00000000000001, 72), ('SANDSTORM', 60.00000000000001, 188)]
LEAPMOTOR [('LEAPMOTOR', 100.0, 142), ('LIP MOTOR', 77.77777777777779, 293), ('CFMOTO', 65.45454545454547, 112), ('FORD', 60.00000000000001, 9), ('JETOUR', 60.00000000000001, 16)]
BENELLI [('BENELLI', 100.0, 143), ('LI', 90.0, 123), ('BUELL', 66.66666666666667, 239), ('BETA', 60.00000000000001, 248), ('BENTLEY', 57.14285714285714, 40)]
UAZ [('UAZ', 100.0, 144), ('A', 90.0, 265), ('CHANGHUA', 72.0, 186), ('CHANGUA', 72.0, 314), ('SUZUKI', 60.00000000000001, 14)]

In [54]:
review_df = (
    df["make"]
    .value_counts()
    .reset_index()
)

review_df.columns = ["make", "count"]

In [55]:
review_df["needs_review"] = False

In [56]:
review_df.loc[
    review_df["make"].str.contains(r"\d"),
    "needs_review"
] = True

review_df.loc[
    review_df["count"] < 10,
    "needs_review"
] = True

In [57]:
df['make'].value_counts().sort_index()

make
A                          1
ABARTH                   273
ACURA                     10
ADMIRAL                    1
AEOLUS                    58
AFTEK                      6
AIQAR                      1
AITO                      27
AL DAMANI                 18
ALFA ROMEO               253
AM                         1
APACHE                     1
APRILIA                   54
APULUO                     1
ARI                        1
ASHOK                      1
ASHOK LEYLAND             88
ASTON MARTIN             125
AUDI                    5993
AVATR                    204
AVENGER                    2
AYED                       9
AYED AYED                  1
AYED BIKE                  1
BAIC                     739
BAJA                       1
BAJAJ                   2229
BAOJUN                     1
BAOJUN YEP                 1
BAW                       24
BENDA                      3
BENELLI                   11
BENTLEY                 1114
BESTUNE                  478
BETA                       1
BIMOTA                     1
BIUE BAIRD                 1
BMW                    14902
BMWB                       1
BORGWARD                  23
BRILLIANCE                16
BUELL                      1
BUGATTI                   33
BUICK                      4
BYD                     5400
BYD - DENZA               82
BYD - YANGWANG            34
CADILLAC                3214
CAN                        2
CAN -AM                    1
CAN AM                     2
CAN AM SPYDER              1
CAN-AM                     6
CATERHAM                   2
CATERPILLAR                1
CF MOTO                    2
CFMOTO                    44
CH                         1
CHAMP                      1
CHANGAN                 3851
CHANGHUA                   5
CHANGHUA - MAX             1
CHANGUA                    1
CHERY                    653
CHERY - ICAR             132
CHEVROLET              28116
CHRYSLER                 895
CITROEN                  124
CMC                       91
DAEWOO                     6
DAF                        1
DAIHATSU                1402
DATSUN                     5
DEEPAL                   112
DELOREAN                   1
DELTA                      1
DEXER                      1
DFSK                     195
DODGE                   6338
DONGFENG                  47
DONGFENG E                 6
DONGFENG-AEOLUS           43
DONGFENG-XIAOKA            3
DORCEN                     6
DUCATI                    60
ECOWAY                     2
EICHER                     4
ELECTRIC MOTION            1
EMPALA                     3
EQUATION                   1
ESCHER                     2
EXEED                    497
FANTIC                     1
FARIZON                    1
FAW                        6
FERRARI                  412
FIAT                     417
FLONY                      1
FOLONY                     6
FORCE                      2
FORD                   26183
FORTHING                 116
FOTON                     67
G                          1
GAC                     1519
GAS GAS                    2
GEELY                   2524
GENESIS                 1204
GMC                    14470
GRAND TIGER                2
GREAT WALL               699
GUNAU                      2
GWM - WEY                  1
HAOJUE                    14
HAR                        1
HARLEY                     6
HARLEY DAVIDSON            4
HARLEY-DAVIDSON          392
HART FORD                  1
HAVAL                   1239
HERO                    1059
HH                         1
HIG                        1
HIGER                      1
HINO                     147
HIPHI                      2
HO                         1
HONDA                  52232
HONGQI                   535
HS                         1
HUAIHAI                    7
HUMMER                   432
HUSQVARNA                  5
HYCAN                      2
HYOSUNG                    2
HYUNDAI                44844
INDIAN                    49
INDIAN  MOTORCYCLE         1
INEOS                     83
INFINITI                9188
ISUZU                   1770
ITALJET                    1
IVECO                     34
JAC                     1729
JAECOO                    32
JAGUAR                  1208
JCB                        1
JEEP                    9538
JETOUR                  8259
JIDU                      15
JINBEI                     1
JIYUE                      1
JMC                       26
JOYLONG                    1
KAIYI                    107
KAMA                       1
KAN M                      1
KAOE K                     1
KAWASAKI                 225
KIA                    34872
KIMMCO                     1
KING LONG                 19
KOASKO                     2
KOENIGSEGG                 1
KOVE                       1
KTM                       62
KYMCO                      6
LADA                      15
LAMBORGHINI              552
LANCIA                     1
LAND ROVER             15244
LEADING                    1
LEADING IDEAL             37
LEAPMOTOR                 15
LEOPARD                    1
LEXUS                  65166
LI                        31
LI AUTO                   10
LIEBHERR                   1
LIFAN                     16
LINCOLN                 2277
LIP MOTOR                  1
LIVEWIRE                   3
LIXIANG                    2
LONSIN                     1
LOTUS                     47
LUCID                      4
LUXGEN                     4
LX                         1
LYKAN                      1
LYNK                      66
MAC                        1
MACLAREN                   2
MAEXTRO                    9
MAHINDRA                  42
MAN                        1
MANN                       1
MASERATI                 700
MAXUS                    520
MAYBACH                    5
MAZDA                   9352
MCLAREN                   78
MERCEDES                   1
MERCEDES BENZ          35523
MERCURY                  191
MG                      7394
MHERO                      1
MINI                    2793
MINI COUPE                 1
MITSUBISHI             50484
MOCK                       1
MONTESA                    1
MORGAN                     6
MOTO GUZZI                 6
MV                         1
MV AGUSTA                  5
NETA                       2
NIO                       24
NISSAN                209436
OCC                        1
OMODA                      3
OPEL                     223
PADAR                      1
PAGANI                     3
PEMBLETON                  1
PEUGEOT                 2704
PIAGGIO                   13
POL                        1
POLARIS                  137
POLESTAR                  83
PONTIAC                   10
PONTICA                    1
PORSCHE                 4384
POWER                      1
POWEREAGLE                14
PREVOST                    1
PROTON                     4
PUYUAN                     1
QINGLING                   4
RABDAN                   216
RAM                     2172
RANGE  ROVER               1
RANGE ROVER                3
RENAULT                 5375
RIDDARA                   15
RIVIAN                    25
ROCKY                      1
ROLLS ROYCE             1155
ROX                     2709
ROYAL ALLOY                1
ROYAL ENFIELD             58
SAAB                      14
SAIC                       2
SAIMO                      1
SAMSUNG                    1
SANDSTORM                  3
SANIYA                     1
SANY                       1
SANYA                    175
SANYOU                     1
SATURN                     3
SCANIA                     2
SCION                      3
SCORPA                     1
SEAT                      65
SERES                     47
SHANG JAN                  1
SHARAMAX                   3
SHARMAX                  134
SHARMAX ENDURO             1
SHERCO                     5
SILNGSHOT                  1
SINOTRUK                   1
SKODA                    843
SKYWELL                   10
SLING SHOT                 1
SLINGSHOT                  4
SMART                     85
SOUEAST                  115
SOUO                       1
SPYDER                     1
SSANGYONG                 22
STD                        1
SUBARU                   702
SUZUKI                 12043
SWIFT                      1
SWM                        1
SYM                       18
T                          1
TAM                        2
TANK                     465
TATA                      75
TESLA                  12915
TGB                        5
TOYOTA                239898
TRALER                     1
TRD                        1
TRIUMPH                   34
TRUMPCHI                   3
TVS                      184
TYANMA                     1
UAZ                       13
UNICORN                    2
UNKNOWN                    1
VANDER                     1
VANDERHALL                13
VESPA                    235
VGV                        3
VICTORIA                   7
VICTORY                  584
VINFAST                    3
VOLG                       1
VOLKSWAGEN             10957
VOLTAMP                    7
VOLVO                   1028
VOYAH                     95
WIESMANN                   3
WULING                     5
XCMG                       1
XIAOMI                   105
XPENG                     57
YADEA                      2
YAMAH                      1
YAMAHA                   353
YBR                        1
ZAMIYAD                    1
ZEEKR                    233
ZENIN                      1
ZERO                       1
ZHENGZHOU                  3
ZNA                       90
ZNIN                       1
ZONGSHEN                   7
ZONSEN                     5
ZONTES                     1
ZOTYE                     11
ZX AUTO                    1
ZXAUTO                     5
Name: count, dtype: int64

In [61]:
make_counts = df["make"].value_counts()

review = make_counts.reset_index()
review.columns = ["make","count"]

review["single_char"] = review["make"].str.len() <= 2

review["contains_dash"] = review["make"].str.contains("-", regex=False)

review["contains_number"] = review["make"].str.contains(r"\d", regex=True)

review["rare"] = review["count"] <= 5

review[
    review["single_char"]
    | review["contains_number"]
    | review["rare"]
].sort_values("count")

,make,count,single_char,contains_dash,contains_number,rare
223,KAMA,1,False,False,False,True
225,TYANMA,1,False,False,False,True
226,SAMSUNG,1,False,False,False,True
224,JIYUE,1,False,False,False,True
227,ZONTES,1,False,False,False,True
286,CAN AM SPYDER,1,False,False,False,True
285,UNKNOWN,1,False,False,False,True
284,CH,1,True,False,False,True
283,JOYLONG,1,False,False,False,True
282,ZAMIYAD,1,False,False,False,True
281,DELOREAN,1,False,False,False,True
280,MV,1,True,False,False,True
279,FANTIC,1,False,False,False,True
278,ZNIN,1,False,False,False,True
277,SPYDER,1,False,False,False,True
276,KOENIGSEGG,1,False,False,False,True
275,T,1,True,False,False,True
274,SWIFT,1,False,False,False,True
273,PREVOST,1,False,False,False,True
272,G,1,True,False,False,True
271,HART FORD,1,False,False,False,True
270,KAOE K,1,False,False,False,True
269,ITALJET,1,False,False,False,True
268,DEXER,1,False,False,False,True
267,PADAR,1,False,False,False,True
266,A,1,True,False,False,True
265,SANYOU,1,False,False,False,True
264,SILNGSHOT,1,False,False,False,True
263,BMWB,1,False,False,False,True
262,POWER,1,False,False,False,True
261,APACHE,1,False,False,False,True
260,HH,1,True,False,False,True
259,HIG,1,False,False,False,True
258,BAOJUN YEP,1,False,False,False,True
257,ROCKY,1,False,False,False,True
256,MERCEDES,1,False,False,False,True
255,SANIYA,1,False,False,False,True
254,VANDER,1,False,False,False,True
253,MANN,1,False,False,False,True
252,SINOTRUK,1,False,False,False,True
251,LIEBHERR,1,False,False,False,True
250,BETA,1,False,False,False,True
249,JINBEI,1,False,False,False,True
248,ROYAL ALLOY,1,False,False,False,True
247,SAIMO,1,False,False,False,True
246,GWM - WEY,1,False,True,False,True
245,SWM,1,False,False,False,True
244,BIUE BAIRD,1,False,False,False,True
243,XCMG,1,False,False,False,True
242,BUELL,1,False,False,False,True
241,DELTA,1,False,False,False,True
240,CATERPILLAR,1,False,False,False,True
239,ASHOK,1,False,False,False,True
238,AYED AYED,1,False,False,False,True
237,KIMMCO,1,False,False,False,True
236,MAC,1,False,False,False,True
235,STD,1,False,False,False,True
234,DAF,1,False,False,False,True
233,MONTESA,1,False,False,False,True
232,MOCK,1,False,False,False,True
231,VOLG,1,False,False,False,True
230,LEADING,1,False,False,False,True
229,LYKAN,1,False,False,False,True
228,SCORPA,1,False,False,False,True
288,SHANG JAN,1,False,False,False,True
289,MAN,1,False,False,False,True
290,CHAMP,1,False,False,False,True
287,SLING SHOT,1,False,False,False,True
291,ZX AUTO,1,False,False,False,True
318,HS,1,True,False,False,True
317,LANCIA,1,False,False,False,True
316,FLONY,1,False,False,False,True
315,ZENIN,1,False,False,False,True
314,KOVE,1,False,False,False,True
313,CHANGUA,1,False,False,False,True
312,CAN -AM,1,False,True,False,True
311,HO,1,True,False,False,True
310,PUYUAN,1,False,False,False,True
309,MINI COUPE,1,False,False,False,True
308,SHARMAX ENDURO,1,False,False,False,True
307,EQUATION,1,False,False,False,True
306,BAJA,1,False,False,False,True
337,ELECTRIC MOTION,1,False,False,False,True
336,AIQAR,1,False,False,False,True
335,APULUO,1,False,False,False,True
334,BIMOTA,1,False,False,False,True
333,TRD,1,False,False,False,True
332,POL,1,False,False,False,True
331,KAN M,1,False,False,False,True
330,AM,1,True,False,False,True
329,RANGE ROVER,1,False,False,False,True
328,YAMAH,1,False,False,False,True
327,JCB,1,False,False,False,True
326,TRALER,1,False,False,False,True
325,PEMBLETON,1,False,False,False,True
324,YBR,1,False,False,False,True
323,LONSIN,1,False,False,False,True
322,MHERO,1,False,False,False,True
321,AYED BIKE,1,False,False,False,True
320,FARIZON,1,False,False,False,True
319,HAR,1,False,False,False,True
302,ARI,1,False,False,False,True
301,OCC,1,False,False,False,True
300,LX,1,True,False,False,True
299,ADMIRAL,1,False,False,False,True
298,INDIAN MOTORCYCLE,1,False,False,False,True
297,CHANGHUA - MAX,1,False,True,False,True
296,ZERO,1,False,False,False,True
295,SANY,1,False,False,False,True
294,SOUO,1,False,False,False,True
293,BAOJUN,1,False,False,False,True
292,LIP MOTOR,1,False,False,False,True
303,LEOPARD,1,False,False,False,True
304,HIGER,1,False,False,False,True
305,PONTICA,1,False,False,False,True
206,SAIC,2,False,False,False,True
205,TAM,2,False,False,False,True
215,GAS GAS,2,False,False,False,True
220,CATERHAM,2,False,False,False,True
222,KOASKO,2,False,False,False,True
208,YADEA,2,False,False,False,True
209,CAN,2,False,False,False,True
210,AVENGER,2,False,False,False,True
221,CF MOTO,2,False,False,False,True
219,GUNAU,2,False,False,False,True
218,LIXIANG,2,False,False,False,True
217,MACLAREN,2,False,False,False,True
216,UNICORN,2,False,False,False,True
213,ESCHER,2,False,False,False,True
214,NETA,2,False,False,False,True
212,SCANIA,2,False,False,False,True
207,ECOWAY,2,False,False,False,True
202,FORCE,2,False,False,False,True
201,HYOSUNG,2,False,False,False,True
203,GRAND TIGER,2,False,False,False,True
211,CAN AM,2,False,False,False,True
200,HIPHI,2,False,False,False,True
204,HYCAN,2,False,False,False,True
190,PAGANI,3,False,False,False,True
191,SATURN,3,False,False,False,True
188,SANDSTORM,3,False,False,False,True
189,DONGFENG-XIAOKA,3,False,True,False,True
185,VGV,3,False,False,False,True
184,OMODA,3,False,False,False,True
199,EMPALA,3,False,False,False,True
198,ZHENGZHOU,3,False,False,False,True
197,LIVEWIRE,3,False,False,False,True
196,TRUMPCHI,3,False,False,False,True
192,BENDA,3,False,False,False,True
193,SHARAMAX,3,False,False,False,True
194,VINFAST,3,False,False,False,True
195,WIESMANN,3,False,False,False,True
187,RANGE ROVER,3,False,False,False,True
186,SCION,3,False,False,False,True
177,LUXGEN,4,False,False,False,True
176,BUICK,4,False,False,False,True
179,SLINGSHOT,4,False,False,False,True
178,EICHER,4,False,False,False,True
181,LUCID,4,False,False,False,True
180,PROTON,4,False,False,False,True
183,HARLEY DAVIDSON,4,False,False,False,True
182,QINGLING,4,False,False,False,True
167,SHERCO,5,False,False,False,True
166,DATSUN,5,False,False,False,True
171,HUSQVARNA,5,False,False,False,True
170,WULING,5,False,False,False,True
169,ZXAUTO,5,False,False,False,True
168,TGB,5,False,False,False,True
173,ZONSEN,5,False,False,False,True
172,MV AGUSTA,5,False,False,False,True
175,CHANGHUA,5,False,False,False,True
174,MAYBACH,5,False,False,False,True
120,LI,31,True,False,False,False
20,MG,7394,True,False,False,False

In [ ]:
model_to_make = {
    "MINI COUPE": "MINI",
    "UNICORN": "HONDA",          # verify from model column first
    "YBR": "YAMAHA",             # Yamaha YBR series
    "TRD": "TOYOTA",             # Toyota Racing Development
    "SPYDER": "CAN-AM",          # Can-Am Spyder
    "SHARMAX ENDURO": "SHARMAX",
    "CHANGHUA - MAX": "CHANGHUA",
    "BAOJUN YEP": "BAOJUN",
    "GRAND TIGER":"ZXAUTO"
}

In [69]:
df["make"] = df["make"].replace(model_to_make)

In [64]:
harley_mapping = {
    "HARLEY": "HARLEY-DAVIDSON",
    "HARLEY DAVIDSON": "HARLEY-DAVIDSON",
}

In [71]:
indian_mapping = {
    "INDIAN": "INDIAN MOTORCYCLE"
}

In [72]:
canam_mapping = {
    "CAN -AM": "CAN-AM",
    "CAN AM": "CAN-AM",
    "CAN AM SPYDER": "CAN-AM",
}

In [73]:
zx_mapping = {
    "ZX AUTO": "ZXAUTO"
}

In [74]:
typo_mapping = {
    "CHANGUA": "CHANGHUA",
    "MACLAREN": "MCLAREN",
    "PONTICA": "PONTIAC",
    "YAMAH": "YAMAHA",
    "ZONSEN": "ZONGSHEN",
}

In [76]:
suspects = [
    "A","AM","CH","G","HAR",
    "HH","HO","HS","LX",
    "MAC","MV","OCC","POL","T"
]

df[df["make"].isin(suspects)][
    ["chassisNumber","make","model","trim"]
].head(100)

             chassisNumber make          model trim
1009426  1M2K197C07M035792  MAC       MR 688 S  MAC
1009484  LAEE1CCJ5PMB00166   HH   HUAIHAI HHFL  NaN
1009493  MZG23EBEFR1000254    A          TR170  NaN
1009501  MC221FCL081159418    G             60  STD
1009504  LZYTATE63R1000210    T  YUTONG LUXURY   L1
1009510  57WMD2C62FM100101   MV              1  STD
1009521  LX6TK334XS2510037   CH      CH150T-34  NaN
1009548  19UDE2F83NA002601   LX       ACURA LX    S
1009549  1Z9SCV2G16M170436  OCC   ZERO GRAVITY  NaN
1009561  ME4KC315EKA038528   HO        UNICORN  NaN
1009573  LEPH4ACE8K1A88753   HS         HONGQL   HS
1009574  MEG1GX4N6CN303538  HAR          FXDBI  NaN
1009589  3JB2HEH16NJ002503   AM          RYKER  NaN
1009595  57XAARHB8M8145586  POL     SLING SHOT  NaN

In [77]:
land_rover_mapping = {
    "RANGE ROVER": "LAND ROVER",
    "RANGE  ROVER": "LAND ROVER",
}

In [78]:
all_mappings = {
    # models in make
    "MINI COUPE": "MINI",
    "UNICORN": "HONDA",
    "YBR": "YAMAHA",
    "TRD": "TOYOTA",
    "GRAND TIGER":"ZXAUTO",
    "SPYDER": "CAN-AM",
    "SHARMAX ENDURO": "SHARMAX",
    "CHANGHUA - MAX": "CHANGHUA",
    "BAOJUN YEP": "BAOJUN",

    # brand variants
    "HARLEY": "HARLEY-DAVIDSON",
    "HARLEY DAVIDSON": "HARLEY-DAVIDSON",
    "INDIAN": "INDIAN MOTORCYCLE",
    "CAN -AM": "CAN-AM",
    "CAN AM": "CAN-AM",
    "CAN AM SPYDER": "CAN-AM",
    "ZX AUTO": "ZXAUTO",

    # typos
    "CHANGUA": "CHANGHUA",
    "MACLAREN": "MCLAREN",
    "PONTICA": "PONTIAC",
    "YAMAH": "YAMAHA",
    "ZONSEN": "ZONGSHEN",

    # rover
    "RANGE ROVER": "LAND ROVER",
    "RANGE  ROVER": "LAND ROVER",
}

df["make"] = df["make"].replace(all_mappings)

In [82]:
additional_mapping = {
    "LX": "ACURA",          # confirmed Acura ILX
    "CH": "CHANGHUA",       # confirmed
    "T": "YUTONG",          # confirmed
}

In [85]:
drop_makes = [
    "A",
    "G",
    "OCC",
    "MV"
]

In [86]:
df = df[~df["make"].isin(drop_makes)]

In [88]:
final_mapping = {
    # abbreviations
    "HAR": "HARLEY-DAVIDSON",
    "HO": "HONDA",
    "HS": "HONGQI",
    "HH": "HUAIHAI",
    "POL": "POLARIS",
    "AM": "CAN-AM",
    "MAC": "MACK",
    "CH": "CHANGHUA",
    "T": "YUTONG",
    "LX": "ACURA",

    # brand variants
    "HARLEY": "HARLEY-DAVIDSON",
    "HARLEY DAVIDSON": "HARLEY-DAVIDSON",
    "INDIAN": "INDIAN MOTORCYCLE",
    "CAN -AM": "CAN-AM",
    "CAN AM": "CAN-AM",
    "CAN AM SPYDER": "CAN-AM",
    "ZX AUTO": "ZXAUTO",

    # model names in make column
    "MINI COUPE": "MINI",
    "UNICORN": "HONDA",
    "YBR": "YAMAHA",
    "TRD": "TOYOTA",
    "SPYDER": "CAN-AM",
    "SHARMAX ENDURO": "SHARMAX",
    "CHANGHUA - MAX": "CHANGHUA",
    "BAOJUN YEP": "BAOJUN",

    # typos
    "CHANGUA": "CHANGHUA",
    "MACLAREN": "MCLAREN",
    "PONTICA": "PONTIAC",
    "YAMAH": "YAMAHA",
    "ZONSEN": "ZONGSHEN",

    # rover
    "RANGE ROVER": "LAND ROVER",
    "RANGE  ROVER": "LAND ROVER",

    # mercedes
    "MERCEDES": "MERCEDES BENZ"
}

In [93]:
make_mapping = {

    # ===== Abbreviations / Truncated Makes =====
    "HAR": "HARLEY-DAVIDSON",
    "HO": "HONDA",
    "HS": "HONGQI",
    "HH": "HUAIHAI",
    "POL": "POLARIS",
    "AM": "CAN-AM",
    "MAC": "MACK",
    "CH": "CHANGHUA",
    "T": "YUTONG",
    "LX": "ACURA",

    # ===== Brand Variants =====
    "HARLEY": "HARLEY-DAVIDSON",
    "HARLEY DAVIDSON": "HARLEY-DAVIDSON",

    "INDIAN": "INDIAN MOTORCYCLE",

    "CAN -AM": "CAN-AM",
    "CAN AM": "CAN-AM",
    "CAN AM SPYDER": "CAN-AM",

    "ZX AUTO": "ZXAUTO",

    "MERCEDES": "MERCEDES BENZ",

    # ===== Models Stored as Makes =====
    "MINI COUPE": "MINI",

    "UNICORN": "HONDA",

    "YBR": "YAMAHA",

    "TRD": "TOYOTA",

    "SPYDER": "CAN-AM",

    "SHARMAX ENDURO": "SHARMAX",

    "CHANGHUA - MAX": "CHANGHUA",

    "BAOJUN YEP": "BAOJUN",

    "LEOPARD": "BYD - LEOPARD",

    # ===== Typos =====
    "CHANGUA": "CHANGHUA",

    "MACLAREN": "MCLAREN",

    "PONTICA": "PONTIAC",

    "YAMAH": "YAMAHA",

    "ZONSEN": "ZONGSHEN",

    "LIP MOTOR": "LEAPMOTOR",

    # ===== Manufacturer/Sub-brand Normalization =====
    "RANGE ROVER": "LAND ROVER",
    "RANGE  ROVER": "LAND ROVER",

    "LIXIANG": "LI AUTO",

    "LYNK": "LYNK & CO",
}

In [94]:
df["make"] = df["make"].replace(make_mapping)

df = df[~df["make"].isin(drop_makes)]

In [96]:
make_counts = df["make"].value_counts()

rare_makes = make_counts[make_counts <= 5]

print(rare_makes.sort_values())

make
KAMA                  1
JIYUE                 1
TYANMA                1
SAMSUNG               1
ZONTES                1
SCORPA                1
LYKAN                 1
LEADING               1
VOLG                  1
MOCK                  1
MONTESA               1
DAF                   1
STD                   1
MACK                  1
KIMMCO                1
AYED AYED             1
ADMIRAL               1
INDIAN  MOTORCYCLE    1
ZERO                  1
SANY                  1
SOUO                  1
CHAMP                 1
MAN                   1
SHANG JAN             1
SLING SHOT            1
UNKNOWN               1
JOYLONG               1
ZAMIYAD               1
DELOREAN              1
FANTIC                1
ZNIN                  1
KOENIGSEGG            1
YUTONG                1
SWIFT                 1
PREVOST               1
HART FORD             1
KAOE K                1
ITALJET               1
DEXER                 1
PADAR                 1
SANYOU                1
SILNGSHOT             1
BMWB                  1
POWER                 1
APACHE                1
HIG                   1
ROCKY                 1
SANIYA                1
VANDER                1
MANN                  1
SINOTRUK              1
LIEBHERR              1
BETA                  1
JINBEI                1
ROYAL ALLOY           1
SAIMO                 1
GWM - WEY             1
SWM                   1
BIUE BAIRD            1
XCMG                  1
BUELL                 1
DELTA                 1
CATERPILLAR           1
ASHOK                 1
ARI                   1
BYD - LEOPARD         1
HIGER                 1
BAJA                  1
EQUATION              1
PUYUAN                1
KOVE                  1
ZENIN                 1
FLONY                 1
LANCIA                1
FARIZON               1
AYED BIKE             1
MHERO                 1
LONSIN                1
PEMBLETON             1
TRALER                1
APULUO                1
BIMOTA                1
ELECTRIC MOTION       1
AIQAR                 1
KAN M                 1
JCB                   1
KOASKO                2
CF MOTO               2
SCANIA                2
AVENGER               2
BAOJUN                2
CATERHAM              2
GUNAU                 2
GAS GAS               2
NETA                  2
ESCHER                2
SAIC                  2
HYCAN                 2
TAM                   2
YADEA                 2
ECOWAY                2
FORCE                 2
HYOSUNG               2
HIPHI                 2
CAN                   2
BENDA                 3
SCION                 3
PAGANI                3
WIESMANN              3
DONGFENG-XIAOKA       3
SANDSTORM             3
VGV                   3
TRUMPCHI              3
EMPALA                3
SHARAMAX              3
SATURN                3
VINFAST               3
OMODA                 3
LIVEWIRE              3
ZHENGZHOU             3
LUCID                 4
EICHER                4
QINGLING              4
BUICK                 4
LUXGEN                4
SLINGSHOT             4
PROTON                4
MV AGUSTA             5
DATSUN                5
SHERCO                5
HUSQVARNA             5
MAYBACH               5
WULING                5
TGB                   5
Name: count, dtype: int64

In [104]:
drop_makes = [
    "A",
    "G",
    "OCC",
    "MOCK",
    "STD",
    "UNKNOWN",
    "POWER",
    "EQUATION",
    "TRALER"
]

df = df[~df["make"].isin(drop_makes)]

In [103]:
final_cleanup = {
    "LEADING IDEAL": "LI AUTO",

    "CF MOTO": "CFMOTO",

    "KIMMCO": "KYMCO",

    "SILNGSHOT": "SLINGSHOT",

    "MANN": "MAN",

    "DELTA": "DAIHATSU",
}

In [105]:
import json

with open("make_mapping.json", "w") as f:
    json.dump(make_mapping, f, indent=4)

In [ ]:
with open("dropped_makes.json", "w") as f:
    json.dump(drop_makes, f, indent=4)

In [107]:
make_counts = df["make"].value_counts()

print("Unique makes:", len(make_counts))
print()
print(make_counts.tail(50))

Unique makes: 295

make
SANIYA                1
ROCKY                 1
HIG                   1
APACHE                1
BMWB                  1
SILNGSHOT             1
SANYOU                1
PADAR                 1
DEXER                 1
ITALJET               1
KAOE K                1
HART FORD             1
PREVOST               1
SWIFT                 1
YUTONG                1
KOENIGSEGG            1
ZNIN                  1
FANTIC                1
DELOREAN              1
ZAMIYAD               1
JOYLONG               1
SLING SHOT            1
SHANG JAN             1
MAN                   1
CHAMP                 1
SOUO                  1
SANY                  1
ZERO                  1
INDIAN  MOTORCYCLE    1
ADMIRAL               1
ARI                   1
BYD - LEOPARD         1
HIGER                 1
BAJA                  1
PUYUAN                1
KOVE                  1
ZENIN                 1
FLONY                 1
LANCIA                1
FARIZON               1
AYED BIKE             1
MHERO                 1
LONSIN                1
PEMBLETON             1
JCB                   1
KAN M                 1
BIMOTA                1
APULUO                1
AIQAR                 1
ELECTRIC MOTION       1
Name: count, dtype: int64

In [109]:
make_mapping = {

    # =========================
    # Abbreviations / Truncations
    # =========================
    "HAR": "HARLEY-DAVIDSON",
    "HO": "HONDA",
    "HS": "HONGQI",
    "HH": "HUAIHAI",
    "POL": "POLARIS",
    "AM": "CAN-AM",
    "MAC": "MACK",
    "CH": "CHANGHUA",
    "T": "YUTONG",
    "LX": "ACURA",

    # =========================
    # Brand Variants
    # =========================
    "HARLEY": "HARLEY-DAVIDSON",
    "HARLEY DAVIDSON": "HARLEY-DAVIDSON",

    "INDIAN": "INDIAN MOTORCYCLE",

    "CAN -AM": "CAN-AM",
    "CAN AM": "CAN-AM",
    "CAN AM SPYDER": "CAN-AM",

    "ZX AUTO": "ZXAUTO",

    "MERCEDES": "MERCEDES BENZ",

    "LEADING IDEAL": "LI AUTO",
    "LIXIANG": "LI AUTO",

    "LYNK": "LYNK & CO",

    # =========================
    # Models Stored as Makes
    # =========================
    "MINI COUPE": "MINI",

    "UNICORN": "HONDA",

    "YBR": "YAMAHA",

    "TRD": "TOYOTA",

    "SPYDER": "CAN-AM",

    "SHARMAX ENDURO": "SHARMAX",

    "CHANGHUA - MAX": "CHANGHUA",

    "BAOJUN YEP": "BAOJUN",

    "LEOPARD": "BYD - LEOPARD",

    # =========================
    # Typos
    # =========================
    "CHANGUA": "CHANGHUA",

    "MACLAREN": "MCLAREN",

    "PONTICA": "PONTIAC",

    "YAMAH": "YAMAHA",

    "ZONSEN": "ZONGSHEN",

    "LIP MOTOR": "LEAPMOTOR",

    "KIMMCO": "KYMCO",

    "SILNGSHOT": "SLINGSHOT",

    "SLING SHOT": "SLINGSHOT",

    # =========================
    # Manufacturer/Sub-brand Normalization
    # =========================
    "RANGE ROVER": "LAND ROVER",
    "RANGE  ROVER": "LAND ROVER",

    "DELTA": "DAIHATSU",

    # =========================
    # Single-row Verified Cases
    # =========================
    "BMWB": "VESPA",
}

In [110]:
drop_makes = [
    "A",
    "G",
    "OCC",
    "MOCK",
    "STD",
    "UNKNOWN",
    "POWER",
    "EQUATION",
    "TRALER"
]

In [111]:
df["make"] = df["make"].replace(make_mapping)

df = df[~df["make"].isin(drop_makes)]

In [112]:
before = df["make"].nunique()

df["make"] = df["make"].str.strip()

after = df["make"].nunique()

print("Unique makes:", after)

Unique makes: 289

In [114]:
df.to_csv("vehicles_cleaned.csv", index=False)

In [129]:
df[df["make"]=="BIUE BAIRD"][
    ["chassisNumber","make","model","trim"]
].head(20)

             chassisNumber        make   model trim
1009445  1BAKGCKA69F258846  BIUE BAIRD  VISION    4

In [120]:
pd.set_option("display.max_rows", None)

In [123]:
extra_mapping = {
    "CF MOTO": "CFMOTO",
    "INDIAN  MOTORCYCLE": "INDIAN MOTORCYCLE",
    "MANN": "MAN",
}

In [132]:
remaining = [
    "LI",
    "LEADING",
    "CAN",
    "AYED AYED",
    "AYED BIKE",
    "BIUE BAIRD",
    "CF MOTO",
    "INDIAN  MOTORCYCLE",
    "MANN"
]

df[df["make"].isin(remaining)]["make"].value_counts()

make
LI                    31
CAN                    2
CF MOTO                2
LEADING                1
AYED AYED              1
BIUE BAIRD             1
MANN                   1
INDIAN  MOTORCYCLE     1
AYED BIKE              1
Name: count, dtype: int64

In [134]:
df["make"] = (
    df["make"]
    .astype(str)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [138]:
remaining = [
    "LI",
    "LEADING",
    "CAN",
    "AYED AYED",
    "AYED BIKE",
    "BIUE BAIRD",
    "CF MOTO",
    "MANN"
]

df[df["make"].isin(remaining)]["make"].value_counts()

Series([], Name: count, dtype: int64)

In [137]:
last_mapping = {
    "LI": "LI AUTO",
    "LEADING": "LI AUTO",

    "CAN": "CAN-AM",

    "AYED AYED": "AYED",
    "AYED BIKE": "AYED",

    "BIUE BAIRD": "BLUE BIRD",

    "CF MOTO": "CFMOTO",

    "MANN": "MAN",
}

df["make"] = df["make"].replace(last_mapping)

In [139]:
df["make"] = (
    df["make"]
    .astype(str)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [141]:
print(df["make"].isna().sum())

10

In [140]:
list(df['make'].unique())

['TOYOTA',
 'NISSAN',
 'LEXUS',
 'MITSUBISHI',
 'HONDA',
 'HYUNDAI',
 'KIA',
 'MERCEDES BENZ',
 'CHEVROLET',
 'FORD',
 'TESLA',
 'BMW',
 'GMC',
 'LAND ROVER',
 'SUZUKI',
 'VOLKSWAGEN',
 'JETOUR',
 'MAZDA',
 'JEEP',
 'INFINITI',
 'MG',
 'BYD',
 'DODGE',
 'AUDI',
 'RENAULT',
 'CHANGAN',
 'PORSCHE',
 'PEUGEOT',
 'ROX',
 'CADILLAC',
 'MINI',
 'GEELY',
 'RAM',
 'LINCOLN',
 'ISUZU',
 'BAJAJ',
 'JAC',
 'GAC',
 'DAIHATSU',
 'HAVAL',
 'BENTLEY',
 'GENESIS',
 'JAGUAR',
 'ROLLS ROYCE',
 'HERO',
 'VOLVO',
 'BAIC',
 'CHRYSLER',
 'SKODA',
 'HONGQI',
 'VICTORY',
 'SUBARU',
 'GREAT WALL',
 'MASERATI',
 'CHERY',
 'BESTUNE',
 'EXEED',
 'MAXUS',
 'TANK',
 'LAMBORGHINI',
 'FIAT',
 'HUMMER',
 'YAMAHA',
 'HARLEY-DAVIDSON',
 'FERRARI',
 'ALFA ROMEO',
 'RABDAN',
 'DFSK',
 'KAWASAKI',
 'OPEL',
 'AVATR',
 'ZEEKR',
 'ABARTH',
 'TVS',
 'VESPA',
 'POLARIS',
 'CHERY - ICAR',
 'MERCURY',
 'FORTHING',
 'SOUEAST',
 'HINO',
 'SANYA',
 'DEEPAL',
 'VOYAH',
 'CITROEN',
 'ASTON MARTIN',
 'SHARMAX',
 'KAIYI',
 'ZNA',
 'CMC',
 'POLESTAR',
 'XIAOMI',
 'ASHOK LEYLAND',
 'BYD - DENZA',
 'SMART',
 'MCLAREN',
 'INEOS',
 'LOTUS',
 'FOTON',
 'AEOLUS',
 'TATA',
 'KTM',
 'LYNK & CO',
 'XPENG',
 'INDIAN MOTORCYCLE',
 'ROYAL ENFIELD',
 'SERES',
 'SEAT',
 'APRILIA',
 'DUCATI',
 'DONGFENG',
 'JAECOO',
 'CFMOTO',
 'BYD - YANGWANG',
 'MAHINDRA',
 'IVECO',
 'AITO',
 'DONGFENG-AEOLUS',
 'BUGATTI',
 'TRIUMPH',
 'LIFAN',
 'LI AUTO',
 'SSANGYONG',
 'JMC',
 'NIO',
 'DATSUN',
 'BORGWARD',
 'LADA',
 'RIVIAN',
 'KING LONG',
 'AL DAMANI',
 'BAW',
 'SYM',
 'RIDDARA',
 'BRILLIANCE',
 'JIDU',
 'ZOTYE',
 'PIAGGIO',
 'SKYWELL',
 'ACURA',
 'SAAB',
 'LEAPMOTOR',
 'BENELLI',
 'UAZ',
 'DONGFENG E',
 nan,
 'PONTIAC',
 'HAOJUE',
 'HUAIHAI',
 'POWEREAGLE',
 'SHERCO',
 'TGB',
 'ZXAUTO',
 'BUICK',
 'AYED',
 'VICTORIA',
 'LUXGEN',
 'MOTO GUZZI',
 'FAW',
 'ZONGSHEN',
 'VANDERHALL',
 'EICHER',
 'OMODA',
 'FOLONY',
 'MAEXTRO',
 'KYMCO',
 'VGV',
 'CAN-AM',
 'SLINGSHOT',
 'SCION',
 'WULING',
 'HUSQVARNA',
 'MV AGUSTA',
 'DORCEN',
 'MORGAN',
 'VOLTAMP',
 'KAMA',
 'MAYBACH',
 'AFTEK',
 'PROTON',
 'LUCID',
 'CHANGHUA',
 'DAEWOO',
 'SANDSTORM',
 'DONGFENG-XIAOKA',
 'HIPHI',
 'PAGANI',
 'JIYUE',
 'SATURN',
 'HYOSUNG',
 'QINGLING',
 'FORCE',
 'HYCAN',
 'TYANMA',
 'SAMSUNG',
 'ZONTES',
 'TAM',
 'BENDA',
 'SCORPA',
 'LYKAN',
 'SHARAMAX',
 'VINFAST',
 'SAIC',
 'WIESMANN',
 'ECOWAY',
 'TRUMPCHI',
 'LIVEWIRE',
 'VOLG',
 'YADEA',
 'AVENGER',
 'MONTESA',
 'ZHENGZHOU',
 'SCANIA',
 'ESCHER',
 'NETA',
 'DAF',
 'MACK',
 'GAS GAS',
 'ASHOK',
 'CATERPILLAR',
 'EMPALA',
 'BUELL',
 'XCMG',
 'BLUE BIRD',
 'SWM',
 'GWM - WEY',
 'GUNAU',
 'SAIMO',
 'ROYAL ALLOY',
 'JINBEI',
 'BETA',
 'LIEBHERR',
 'SINOTRUK',
 'CATERHAM',
 'MAN',
 'VANDER',
 'SANIYA',
 'ROCKY',
 'BAOJUN',
 'HIG',
 'APACHE',
 'SANYOU',
 'PADAR',
 'DEXER',
 'ITALJET',
 'KAOE K',
 'HART FORD',
 'PREVOST',
 'SWIFT',
 'YUTONG',
 'KOENIGSEGG',
 'ZNIN',
 'FANTIC',
 'DELOREAN',
 'ZAMIYAD',
 'KOASKO',
 'JOYLONG',
 'SHANG JAN',
 'CHAMP',
 'SOUO',
 'SANY',
 'ZERO',
 'ADMIRAL',
 'ARI',
 'BYD - LEOPARD',
 'HIGER',
 'BAJA',
 'PUYUAN',
 'KOVE',
 'ZENIN',
 'FLONY',
 'LANCIA',
 'FARIZON',
 'MHERO',
 'LONSIN',
 'PEMBLETON',
 'JCB',
 'KAN M',
 'BIMOTA',
 'APULUO',
 'AIQAR',
 'ELECTRIC MOTION']

make cleaned

In [143]:
garbage_models = {
    "UNKNOWN",
    "OTHERS",
    "MODEL",
    "LIGHT VEHICLE",
    "MOTORCYCLE",
    "TRANS",
    "SALON",
    "SALOON",
    "STATION",
    "COUPE",
    "VAN",
    "PICK UP",
    "PICKUP",
    "HATCHBACK",
}

In [144]:
df = df[~df["model"].str.upper().isin(garbage_models)]

In [145]:
df = df[
    ~df["model"]
      .astype(str)
      .str.fullmatch(r"(19|20)\d{2}")
]

In [146]:
makes = sorted(
    df["make"].dropna().unique(),
    key=len,
    reverse=True
)

pattern = "^(" + "|".join(
    re.escape(x)
    for x in makes
) + r")\s+"

df["model"] = (
    df["model"]
      .str.upper()
      .str.replace(pattern, "", regex=True)
      .str.strip()
)

In [147]:
toyota_mapping = {
    "RAV 4": "RAV4",
    "RAFF 4": "RAV4",

    "TAKOMA": "TACOMA",
    "TOKOMA": "TACOMA",

    "HAI LUX": "HILUX",
    "HAIULUX": "HILUX",

    "LAND CRUISE": "LAND CRUISER",

    "LAND CRUISER PICKUP": "LAND CRUISER PICK UP",
    "LAND CRUISER PICKUP 70": "LAND CRUISER PICK UP",

    "HI ACE": "HIACE",

    "IQ": "iQ",
}

In [148]:
nissan_mapping = {
    "X TRAIL": "X-TRAIL",
    "XTRAIL": "X-TRAIL",

    "XTERRA": "X-TERRA",
    "X TERRA": "X-TERRA",

    "ROUGE": "ROGUE",
    "ROGIE": "ROGUE",

    "TIDA": "TIIDA",
    "TIDAS": "TIIDA",

    "ALTIAMA": "ALTIMA",
}

In [149]:
lexus_mapping = {
    "LS 460": "LS460",
    "LS 430": "LS430",

    "IS 250": "IS250",
    "IS 300": "IS300",
    "IS 350": "IS350",

    "RX 350": "RX350",
    "RX 450H": "RX450H",

    "NX 350": "NX350",
    "NX 350H": "NX350H",
}

In [150]:
honda_mapping = {
    "HONDA UNICORN": "UNICORN",
    "UNICORN 160": "UNICORN",
    "UNICORN MOTORCYCLE": "UNICORN",
    "UNICORN -160": "UNICORN",
    "UNICORN MOTORCYCLE DELIVERY": "UNICORN",

    "UNIKORN": "UNICORN",
    "UNICON": "UNICORN",
    "UNICCRN": "UNICORN",
    "UNICRON": "UNICORN",
    "YUNICORN": "UNICORN",
}

In [151]:
def inspect_make(make_name):

    subset = df[df["make"] == make_name]

    return (
        subset["model"]
        .value_counts()
        .head(200)
    )

inspect_make("TOYOTA")

model
CAMRY                                         50399
COROLLA                                       38093
LAND CRUISER                                  32192
YARIS                                         23276
HILUX                                         16722
RAV4                                          12266
HIACE                                         11762
PRADO                                          7813
SIENNA                                         6837
FORTUNER                                       5342
AVALON                                         4557
TUNDRA                                         4333
FJ CRUISER                                     2955
INNOVA                                         2687
RUSH                                           2409
PREVIA                                         2040
PRIUS                                          1585
AVANZA                                         1519
CAMRY HYBRID                                   1380
SEQUOIA                                        1051
AURION                                          985
COROLLA CROSS                                   875
RAIZE                                           829
LAND CRUISER PICKUP 70                          722
ECHO                                            700
VELOZ                                           606
LAND CRUISER PICK UP                            583
COASTER                                         554
URBAN CRUISER                                   551
XA                                              540
HIGHLANDER                                      517
TACOMA                                          457
C-HR                                            415
86                                              276
4RUNNER                                         259
SUPRA                                           218
CROWN                                           212
LITEACE                                         136
LAND CRUISER PRADO                              124
LAND CRUISER 70                                  95
ZELAS                                            92
GRANVIA                                          89
RAV 4                                            86
TERCEL                                           84
IQ                                               76
LEVIN                                            53
SCION                                            46
COROLLA 1.6                                      39
ALPHARD                                          37
MATRIX                                           27
BZ4X                                             24
SOLARA                                           24
GR86                                             21
COROLLA 1.3                                      21
TAKOMA                                           19
COROLLA 1.8                                      19
4 RUNNER                                         11
TOYOTA                                            8
DYNA                                              7
COROLLA SEDAN                                     7
DAINA                                             6
TANDRA                                            6
CELICA                                            6
CRESSIDA                                          5
هايلوكس                                           5
VENZA                                             4
لاند كروزر                                        4
CROWN KLUGER                                      3
ALTIS                                             3
MR2                                               3
WISH                                              3
BZ 4                                              3
HAI LUX                                           3
CHR                                               3
LITE ACE                                          2
كامري                                             2
BZ3X                                              2
LAND CRUISER PICK UP CARGO                        2
RUMION                                            2
LAND CRUISER SINGLE-CABIN PICK                    2
25 HX DC 4X4 2.7LAT                               2
GLX DA (PICK UP)                                  2
ALLION                                            2
COROLLA 1.6/SEDAN                                 2
VXL 150                                           2
26HX DC 4X4 PLAT                                  2
DLX FA (PICK UP)                                  2
WIGO                                              2
HILUX ADVENTURE                                   2
CENTURY                                           2
FJ                                                1
LAND CRUISE                                       1
T 300                                             1
LAND CRUISER VXR                                  1
بريفيا                                            1
HAIULUX                                           1
استیشن                                            1
JUSTIN BIEBER X VESPA 150 E5 GSO (SCOOTER)        1
بيك اب كابينه مزدوجه                              1
26HX DC 4X4P2.7LAT                                1
COROLLA 1.5                                       1
25 LP SC4X44.0L MT                                1
HD 4X4                                            1
FLTRXS                                            1
LAND CRUISER / STATION                            1
SY150T                                            1
هاي لوكس                                          1
HILUX RE                                          1
KS01                                              1
25 HX DC 4X4D 2.4LAT                              1
MR 2                                              1
كورولا 1.8                                        1
SICION                                            1
MT 03                                             1
TOKOMA                                            1
25 LP SC 4X4 P4.0 MT                              1
T 100                                             1
ALFARD                                            1
PRADO GX                                          1
حافلة نقل خاص                                     1
RUNNER                                            1
GRAND DELUX                                       1
VIOS                                              1
SIENNA VAN                                        1
SENA                                              1
SIERRA                                            1
SELICA                                            1
راف ٤                                             1
SENA VAN PASSENGER                                1
MODEL 2022                                        1
LAND CRUISER GX                                   1
PICK UP CABIN                                     1
SUPRA COUPE                                       1
2 HX DC 4X40                                      1
TACOMA (PICK UP)                                  1
HI S COACH                                        1
LAND CRUISER/PICK UP CARGO                        1
FRONTLANDER                                       1
COROLLA SEDAN / HATCH                             1
25 CA SON P 2.5L AT                               1
STREET TRIPLE                                     1
AQUA                                              1
GS 300                                            1
25 HX DC 4X4P 2.7LAT                              1
COROLLA LI                                        1
GLX RA (PICK UP)                                  1
VXL                                               1
افنزا                                             1
CORONA                                            1
LAND CRUISER GXR                                  1
FLHTK                                             1
26 YA HB P 1.6L AT TURBO GR RA(CAR)               1
26HX DC 4X4D2.4L AT                               1
RAV4 LE CAR                                       1
SQUIN                                             1
SIENA                                             1
COROLLA 2.0                                       1
26 HX DC 4X4 2.4LAT                               1
26HX DC 4X4 D2.4LAT                               1
STANZA                                            1
TUNDRA (PICK UP)                                  1
25 HX DC 4X2 P 27L AT GLX RA/PICK UP              1
GXL RA (STATION WAGON)                            1
25PR 5 DR P 2.4L AT                               1
2 HX DC 4X4 P 2.7LAT                              1
تاكوما                                            1
كامرى                                             1
26 HX DC 4X4 D 2.4L AT                            1
25 HX DC 4X4 P .LAT                               1
- 26 HX DC 4X4 D 2.4L AT                          1
SPINA                                             1
YARIS HATCHBACK                                   1
25 HX DC 4X4                                      1
26 HX DC 4X4 P 2.7LAT                             1
PASSENGER                                         1
R1                                                1
SIENNA(VAN)                                       1
U7                                                1
T100                                              1
كورولا                                            1
TAKOMA PICK UP CARGO                              1
HX DC 4X4 D 2.4L AT                               1
GL770ULTRA                                        1
26 HX DC 4X4D                                     1
ORION                                             1
كورولا 1.3                                        1
برادو                                             1
25 HX DC 4X4 PLAT GLX RA(PICK UP)                 1
PARISIENNE BROUGHAM                               1
COROLLA 1.5L/HATCHBACK                            1
TANDRA PICK UP DOUBLE CABIN                       1
H 530                                             1
CROWN V                                           1
ES8                                               1
RAFF 4                                            1
900                                               1
DYNA VAN CARGO                                    1
H3                                                1
LAND CRUISER/STD EX PICKUP                        1
LAND CRUISER PICKUP                               1
Name: count, dtype: int64

In [152]:
arabic_model_mapping = {

    # Toyota
    "كامري": "CAMRY",
    "كامرى": "CAMRY",

    "كورولا": "COROLLA",
    "كورولا 1.3": "COROLLA 1.3",
    "كورولا 1.8": "COROLLA 1.8",

    "هايلوكس": "HILUX",

    "لاند كروزر": "LAND CRUISER",

    "برادو": "PRADO",

    "تاكوما": "TACOMA",

    "افنزا": "AVANZA",

    "راف ٤": "RAV4",

    # Nissan
    "صني": "SUNNY",
    "صني 1.3": "SUNNY 1.3",
    "صني 1.4": "SUNNY 1.4",
    "صني 1.5": "SUNNY 1.5",
    "صني 1.6": "SUNNY 1.6",

    "سيفليان": "CIVILIAN",

    # Lexus
    "جي اس 430": "GS430",
    "ال اس 430": "LS430",
    "لي اس 300": "LS300",
}

In [153]:
df["model"] = df["model"].replace(arabic_model_mapping)

In [162]:
arabic_review = (
    df[
        df["model"]
        .astype("string[python]")
        .str.contains(r'[\u0600-\u06FF]', regex=True, na=False)
    ]["model"]
    .value_counts()
    .reset_index()
)

arabic_review.columns = ["arabic_model", "count"]

arabic_review

                        arabic_model  count
0                         سيكتيس 175      2
1   ستار اتش ال اكس في اس 1 تي في اس      2
2                       يونيكورن 180      1
3                           پولیگورن      1
4                       تي ان تي 150      1
5                              مولدا      1
6                              ايفنت      1
7                          اتش دي 65      1
8                              يونجو      1
9                         اتيجو 1725      1
10                            في 250      1
11                            في 230      1
12                            آي 330      1
13                       ني ام جراند      1
14                         مي سي 150      1
15                          ميتي 100      1
16                            سي 150      1
17                  اف اكس 150 الترا      1
18                   اس واي 15 تي يو      1
19                     اس اكس ال 150      1
20                     اس ولی 150 تے      1
21                     اس واي 150 تي      1
22                      سي 2 اس دبلي      1
23                         می سی 125      1

In [158]:
arabic_model_mapping = {

    # Honda Unicorn
    "يونيكورن": "UNICORN",
    "يونيكورن 160": "UNICORN 160",
    "يونيكورن-160": "UNICORN 160",
    "يونيكورت 160": "UNICORN 160",
    "يوليكورن 160": "UNICORN 160",
    "يونيكونت 160": "UNICORN 160",
    "يونيكون 160": "UNICORN 160",
    "نيكورن 160": "UNICORN 160",
    "یونیکورن": "UNICORN",

    # Honda CBF
    "سي بي اف 150": "CBF150",
    "سی بی اف 150": "CBF150",
    "اف 150 سي بي": "CBF150",
    "بی اف 150": "CBF150",
    "بي اف 150": "CBF150",

    "سی بی اف 160": "CBF160",
    "سی بی اف 160 ی": "CBF160",
    "سي بي اف 160 يـ": "CBF160",
    "سي بي اف 160 يونيكورن": "CBF160 UNICORN",

    # Honda
    "جي ال 1800": "GL1800",
    "كوندا جي ال 1800": "GL1800",
    "شادو": "SHADOW",
    "سي جي 125": "CG125",

    # Toyota
    "هاي لوكس": "HILUX",
    "بريفيا": "PREVIA",

    # Mercedes
    "ام ال 350": "ML350",

    # Lexus
    "ال اس 350": "LS350",

    # BMW
    "اف 650 جي اس": "F650GS",

    # Suzuki
    "جي اس اكس ار 1000": "GSX-R1000",

    # Renault
    "ماستر": "MASTER",

    # Changan
    "سي اس 35": "CS35",

    # Bajaj
    "بولسار": "PULSAR",
    "افينجر": "AVENGER",
    "سي تي 100": "CT100",

    # Apache
    "اباشي ار تي ار 20": "APACHE RTR 200",

    # Great Wall
    "وينجل": "WINGLE",
}

In [159]:
drop_models = [
    "دراجة ناريه",
    "دراجة نارية",
    "دراجة توصيل طلبات",
    "دراجة توصيل الباي",

    "بيك اب شحن",
    "بيك آب شحن",
    "بيك اب کابینه مزدوجه",
    "بيك اب كابينه مزدوجه",
    "بيك اب كابينة واحدة",

    "فان شحن",

    "استیشن",
    "كوبيه",

    "حافلة نقل خاص",
]

In [160]:
df["model"] = df["model"].replace(arabic_model_mapping)

In [161]:
df = df[~df["model"].isin(drop_models)]

In [169]:
import re

review = (
    df[
        df["model"].fillna("").astype(str).apply(
            lambda x: bool(re.search(r'[\u0600-\u06FF]', x))
        )
    ][["make", "model"]]
    .drop_duplicates()
    .sort_values(["make", "model"])
)

review

                  make                             model
965158           BAJAJ                  اف اكس 150 الترا
965082           BAJAJ                            سي 150
963526           BAJAJ                         مي سي 150
964955           BAJAJ                          ميتي 100
796925             BMW                            آي 330
1006611          FOTON                      سي 2 اس دبلي
953022           GEELY                       ني ام جراند
607656           HONDA                      تي ان تي 150
612223           HONDA                             مولدا
587758           HONDA                      يونيكورن 180
598226           HONDA                          پولیگورن
652800         HYUNDAI                         اتش دي 65
613011         HYUNDAI                             ايفنت
659708             KIA                             يونجو
692837   MERCEDES BENZ                        اتيجو 1725
720032   MERCEDES BENZ                            في 230
696585   MERCEDES BENZ                            في 250
1004556          SANYA                     اس واي 150 تي
1004495          SANYA                     اس ولی 150 تے
1008728            SYM                         می سی 125
1003202            TVS  ستار اتش ال اكس في اس 1 تي في اس
1003575          VESPA                     اس اكس ال 150
1003430          VESPA                   اس واي 15 تي يو
990363         VICTORY                        سيكتيس 175

In [171]:
remaining_arabic_mapping = {

    # BAJAJ
    "اف اكس 150 الترا": "BOXER 150",
    "سي 150": "CT150",
    "مي سي 150": "MC150",
    "ميتي 100": "MATE 100",

    # BMW
    "آي 330": "I330",

    # FOTON
    "سي 2 اس دبلي": "C2SW",

    # GEELY
    "ني ام جراند": "EMGRAND",

    # HONDA
    "تي ان تي 150": "TNT150",
    "مولدا": "MULDA",
    "يونيكورن 180": "UNICORN 180",
    "پولیگورن": "POLYGON",

    # HYUNDAI
    "اتش دي 65": "HD65",
    "ايفنت": "AVANTE",      # Hyundai Avante

    # KIA
    "يونجو": "BONGO",       # likely Kia Bongo

    # MERCEDES
    "اتيجو 1725": "ATEGO 1725",
    "في 230": "V230",
    "في 250": "V250",

    # SANYA
    "اس واي 150 تي": "SY150T",
    "اس ولی 150 تے": "SY150T",

    # SYM
    "می سی 125": "MC125",

    # TVS
    "ستار اتش ال اكس في اس 1 تي في اس": "STAR HLX VS",

    # VESPA
    "اس اكس ال 150": "SXL150",
    "اس واي 15 تي يو": "SY15TU",

    # VICTORY
    "سيكتيس 175": "CITIS 175",
}

In [173]:
high_confidence = {
    "اتش دي 65": "HD65",
    "ايفنت": "AVANTE",
    "ني ام جراند": "EMGRAND",
    "اتيجو 1725": "ATEGO 1725",
    "في 230": "V230",
    "في 250": "V250",
    "يونيكورن 180": "UNICORN 180",
    "اس واي 150 تي": "SY150T",
    "اس ولی 150 تے": "SY150T",
    "اس اكس ال 150": "SXL150",
}

In [175]:
toyota_mapping = {
    "RAV 4": "RAV4",
    "RAFF 4": "RAV4",

    "TAKOMA": "TACOMA",
    "TOKOMA": "TACOMA",

    "HAIULUX": "HILUX",
    "HAI LUX": "HILUX",

    "LAND CRUISE": "LAND CRUISER",

    "LAND CRUISER PRADO": "PRADO",

    "LAND CRUISER VXR": "LAND CRUISER",
    "LAND CRUISER GX": "LAND CRUISER",
    "LAND CRUISER GXR": "LAND CRUISER",

    "HI ACE": "HIACE",

    "ALFARD": "ALPHARD",

    "BZ 4": "BZ4X",
    "BZ46": "BZ4X",

    "FJ": "FJ CRUISER",

    "SIENA": "SIENNA",
    "SENA": "SIENNA",
}

In [176]:
nissan_mapping = {
    "X TRAIL": "X-TRAIL",
    "XTRAIL": "X-TRAIL",

    "XTERRA": "X-TERRA",
    "X TERRA": "X-TERRA",

    "ROUGE": "ROGUE",
    "ROGIE": "ROGUE",

    "MORANOA": "MURANO",

    "TIDA": "TIIDA",
    "TIDAS": "TIIDA",

    "ALTIAMA": "ALTIMA",

    "CENTRA": "SENTRA",
}

In [177]:
lexus_mapping = {
    "LS 460": "LS460",
    "LS460L": "LS460",

    "LS 430": "LS430",

    "IS 250": "IS250",
    "IS 300": "IS300",
    "IS 350": "IS350",

    "RX 350": "RX350",
    "RX 450 H": "RX450H",
    "RX 450H": "RX450H",

    "NX 350": "NX350",
    "NX 350 H": "NX350H",
    "NX350H": "NX350H",

    "GX 460": "GX460",
    "GX 470": "GX470",

    "ES 350": "ES350",
    "ES 300H": "ES300H",
}

In [178]:
unicorn_variants = [
    "UNICORN",
    "UNCORN",
    "UNIKORN",
    "UNICON",
    "UNICCRN",
    "UNICRON",
    "YUNICORN",
    "JNICORN",
    "UNICORN -160",
    "UNICORN MOTORCYCLE",
    "UNICORN MOTORCYCLE DELIVERY",
    "CB UNICORN",
]

In [179]:
df = df[~df["model"].str.contains(
    r"(4X4|4X2|GLX|GXR|LP|HX|DC|SC)",
    case=False,
    na=False
)]

C:\Users\Admin\AppData\Local\Temp\ipykernel_6200\1935934668.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df = df[~df["model"].str.contains(

In [182]:
toyota_mapping = {

    # spelling fixes
    "TAKOMA": "TACOMA",
    "TOKOMA": "TACOMA",

    "HAIULUX": "HILUX",
    "HAI LUX": "HILUX",

    "RAV 4": "RAV4",
    "RAFF 4": "RAV4",

    "LAND CRUISE": "LAND CRUISER",

    "HI ACE": "HIACE",

    "ALFARD": "ALPHARD",

    "MR 2": "MR2",

    "SELICA": "CELICA",

    "TANDRA": "TUNDRA",

    "CHR": "C-HR",

    "SIENA": "SIENNA",
    "SENA": "SIENNA",

    "4 RUNNER": "4RUNNER",

    "BZ 4": "BZ4X",
    "BZ46": "BZ4X",

    "FJ": "FJ CRUISER",

    "LAND CRUISER PRADO": "PRADO",
}

In [183]:
toyota_drop = [
    "TOYOTA",

    "LAND CRUISER GX",
    "LAND CRUISER GXR",
    "LAND CRUISER VXR",

    "LAND CRUISER / STATION",
    "LAND CRUISER/PICK UP CARGO",
    "LAND CRUISER PICK UP CARGO",
    "LAND CRUISER - PICK UP CARGO",

    "PICK UP CABIN",
    "PASSENGER",

    "COROLLA SEDAN",
    "COROLLA SEDAN / HATCH",

    "SIENNA VAN",
    "SIENNA(VAN)",
    "SENA VAN PASSENGER",

    "TUNDRA (PICK UP)",
    "TACOMA (PICK UP)",
    "TAKOMA PICK UP CARGO",
]

In [184]:
land_cruiser_mapping = {
    "LAND CRUISER PICKUP": "LAND CRUISER",
    "LAND CRUISER PICK UP": "LAND CRUISER",
    "LAND CRUISER PICKUP 70": "LAND CRUISER",
    "LAND CRUISER 70": "LAND CRUISER",
    "LAND CRUISER SINGLE-CABIN PICK": "LAND CRUISER",
    "LAND CRUISER SINGLE-CABIN PICK UP": "LAND CRUISER",
    "LAND CRUISER/STD EX PICKUP": "LAND CRUISER",
}

In [185]:
contamination = [
    "FLTRXS",
    "FLHTK",
    "GL770ULTRA",
    "STREET TRIPLE",
    "VXL 150",
    "GS 300",
    "R1",
    "MT 03",
    "ES8",
    "H3",
    "U7",
    "900",
    "EQ",
    "ORION",
]

In [188]:
toyota = df[df["make"] == "TOYOTA"]

toyota["model"].value_counts().head(200)

model
CAMRY                                  50402
COROLLA                                38094
LAND CRUISER                           32196
YARIS                                  23276
HILUX                                  16728
RAV4                                   12267
HIACE                                  11762
PRADO                                   7814
SIENNA                                  6837
FORTUNER                                5342
AVALON                                  4557
TUNDRA                                  4333
FJ CRUISER                              2955
INNOVA                                  2687
RUSH                                    2409
PREVIA                                  2041
PRIUS                                   1585
AVANZA                                  1520
CAMRY HYBRID                            1380
SEQUOIA                                 1051
AURION                                   985
COROLLA CROSS                            875
RAIZE                                    829
LAND CRUISER PICKUP 70                   722
ECHO                                     700
VELOZ                                    606
LAND CRUISER PICK UP                     583
COASTER                                  554
URBAN CRUISER                            551
XA                                       540
HIGHLANDER                               517
TACOMA                                   458
C-HR                                     415
86                                       276
4RUNNER                                  259
SUPRA                                    218
CROWN                                    212
LITEACE                                  136
LAND CRUISER PRADO                       124
LAND CRUISER 70                           95
ZELAS                                     92
GRANVIA                                   89
RAV 4                                     86
TERCEL                                    84
IQ                                        76
LEVIN                                     53
COROLLA 1.6                               39
MATRIX                                    27
BZ4X                                      24
SOLARA                                    24
COROLLA 1.3                               22
GR86                                      21
COROLLA 1.8                               20
TAKOMA                                    19
4 RUNNER                                  11
TOYOTA                                     8
DYNA                                       7
COROLLA SEDAN                              7
DAINA                                      6
TANDRA                                     6
CELICA                                     6
CRESSIDA                                   5
VENZA                                      4
CROWN KLUGER                               3
ALTIS                                      3
MR2                                        3
WISH                                       3
BZ 4                                       3
HAI LUX                                    3
CHR                                        3
LITE ACE                                   2
BZ3X                                       2
LAND CRUISER PICK UP CARGO                 2
RUMION                                     2
LAND CRUISER SINGLE-CABIN PICK             2
ALLION                                     2
COROLLA 1.6/SEDAN                          2
VXL 150                                    2
DLX FA (PICK UP)                           2
WIGO                                       2
HILUX ADVENTURE                            2
CENTURY                                    2
FJ                                         1
LAND CRUISE                                1
T 300                                      1
LAND CRUISER VXR                           1
HAIULUX                                    1
COROLLA 1.5                                1
FLTRXS                                     1
LAND CRUISER / STATION                     1
SY150T                                     1
HILUX RE                                   1
KS01                                       1
MR 2                                       1
SICION                                     1
MT 03                                      1
TOKOMA                                     1
T 100                                      1
ALFARD                                     1
PRADO GX                                   1
RUNNER                                     1
GRAND DELUX                                1
VIOS                                       1
SIENNA VAN                                 1
SENA                                       1
SIERRA                                     1
SELICA                                     1
SENA VAN PASSENGER                         1
MODEL 2022                                 1
LAND CRUISER GX                            1
PICK UP CABIN                              1
SUPRA COUPE                                1
TACOMA (PICK UP)                           1
HI S COACH                                 1
LAND CRUISER/PICK UP CARGO                 1
FRONTLANDER                                1
COROLLA SEDAN / HATCH                      1
25 CA SON P 2.5L AT                        1
STREET TRIPLE                              1
AQUA                                       1
GS 300                                     1
COROLLA LI                                 1
VXL                                        1
CORONA                                     1
FLHTK                                      1
26 YA HB P 1.6L AT TURBO GR RA(CAR)        1
RAV4 LE CAR                                1
SQUIN                                      1
SIENA                                      1
COROLLA 2.0                                1
STANZA                                     1
TUNDRA (PICK UP)                           1
GXL RA (STATION WAGON)                     1
25PR 5 DR P 2.4L AT                        1
SPINA                                      1
YARIS HATCHBACK                            1
PASSENGER                                  1
R1                                         1
SIENNA(VAN)                                1
U7                                         1
T100                                       1
TAKOMA PICK UP CARGO                       1
GL770ULTRA                                 1
ORION                                      1
PARISIENNE BROUGHAM                        1
COROLLA 1.5L/HATCHBACK                     1
TANDRA PICK UP DOUBLE CABIN                1
H 530                                      1
CROWN V                                    1
ES8                                        1
RAFF 4                                     1
900                                        1
DYNA VAN CARGO                             1
H3                                         1
LAND CRUISER/STD EX PICKUP                 1
LAND CRUISER PICKUP                        1
FORERUNNER                                 1
MIRAI                                      1
1.8 XS                                     1
HI ACE                                     1
LAND CRUISER - PICK UP CARGO               1
BZ46                                       1
EQ                                         1
CAMRY SOLARA                               1
LAND CRUISER SINGLE-CABIN PICK UP          1
Name: count, dtype: int64

In [190]:
toyota_mapping = {

    # Spelling
    "TAKOMA": "TACOMA",
    "TOKOMA": "TACOMA",

    "HAIULUX": "HILUX",
    "HAI LUX": "HILUX",

    "LAND CRUISE": "LAND CRUISER",

    "HI ACE": "HIACE",

    "ALFARD": "ALPHARD",

    "TANDRA": "TUNDRA",

    "CHR": "C-HR",

    "SIENA": "SIENNA",
    "SENA": "SIENNA",

    "4 RUNNER": "4RUNNER",

    "BZ 4": "BZ4X",
    "BZ46": "BZ4X",

    "FJ": "FJ CRUISER",

    "DAINA": "DYNA",

    "RAFF 4": "RAV4",

    "RUNNER": "4RUNNER",
    "FORERUNNER": "4RUNNER",
}

In [191]:
toyota_merge = {

    "LAND CRUISER PRADO": "PRADO",

    "LAND CRUISER PICKUP": "LAND CRUISER",
    "LAND CRUISER PICK UP": "LAND CRUISER",
    "LAND CRUISER PICKUP 70": "LAND CRUISER",
    "LAND CRUISER 70": "LAND CRUISER",
    "LAND CRUISER SINGLE-CABIN PICK": "LAND CRUISER",
    "LAND CRUISER SINGLE-CABIN PICK UP": "LAND CRUISER",
    "LAND CRUISER/STD EX PICKUP": "LAND CRUISER",

    "COROLLA SEDAN": "COROLLA",
    "COROLLA SEDAN / HATCH": "COROLLA",

    "YARIS HATCHBACK": "YARIS",

    "TUNDRA (PICK UP)": "TUNDRA",

    "TACOMA (PICK UP)": "TACOMA",

    "SIENNA VAN": "SIENNA",
    "SIENNA(VAN)": "SIENNA",
    "SENA VAN PASSENGER": "SIENNA",

    "CAMRY SOLARA": "SOLARA",
}

In [192]:
toyota["model"] = toyota["model"].str.replace(
    r"^COROLLA\s+\d\.\d.*$",
    "COROLLA",
    regex=True
)

In [195]:
toyota_keep_mapping = {

    # Land Cruiser trims
    "LAND CRUISER GX": "LAND CRUISER",
    "LAND CRUISER VXR": "LAND CRUISER",

    # Prado trim
    "PRADO GX": "PRADO",

    # RAV4 trim
    "RAV4 LE CAR": "RAV4",

    # Tundra body style
    "TANDRA PICK UP DOUBLE CABIN": "TUNDRA",

    # Tacoma body style
    "TAKOMA PICK UP CARGO": "TACOMA",

    # Corolla trim
    "COROLLA LI": "COROLLA",

    # Sienna variants
    "HI S COACH": "HIACE",   # verify this row
}

In [197]:
suspects = [
    "FLTRXS","FLHTK","GL770ULTRA",
    "STREET TRIPLE","R1","MT 03",
    "ES8","GS 300"
]

toyota[
    toyota["model"].isin(suspects)
][["chassisNumber","model","make"]]

            chassisNumber          model    make
47535   5HD1KTP45LB627186         FLTRXS  TOYOTA
73263   MH3RH21B2PK002165          MT 03  TOYOTA
148622  SMTTTL1366E617240  STREET TRIPLE  TOYOTA
150374  JTHBH96S605018468         GS 300  TOYOTA
158658  5HD1FHPC6K8600201          FLHTK  TOYOTA
175861  JYARN221000008731             R1  TOYOTA
178556  LBBP99006PBF55801     GL770ULTRA  TOYOTA
192653  LJ1E6A3U3PG584139            ES8  TOYOTA

In [194]:
toyota[toyota["model"].isin([
    "KS01","T 300","T100","SQUIN",
    "SPINA","SIERRA","PARISIENNE BROUGHAM",
    "CROWN V","1.8 XS"
])]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,engine_variant,clean_model
10007,LZC1215CXP0000390,2023.0,TOYOTA,T 300,ADVENTURE,Station,GCC,0.0,white,CHINA,1600.0,5.0,NaN,T 300
66743,LHA022GD1RB007135,2024.0,TOYOTA,KS01,EX,Station,GCC,0.0,white,China,1500.0,5.0,NaN,KS01
118180,1GTW78CG1C1181220,2012.0,TOYOTA,SIERRA,A,MPV,GCC,4.0,black,AMERICA,1800.0,7.0,NaN,SIERRA
161083,JTNJJXB01CJ020890,2012.0,TOYOTA,SQUIN,STD,Coupe,GCC,4.0,orange,JAPAN,900.0,4.0,NaN,SQUIN
171529,4T3ZF13C13U519169,2003.0,TOYOTA,SPINA,STD,Station,GCC,4.0,golden,Japan,NaN,7.0,NaN,SPINA
177161,JT4JM11D3V0017737,1997.0,TOYOTA,T100,0,Pickup,GCC,4.0,white,Japan,1650.0,3.0,NaN,T100
185055,1G2BT69Y4GX228925,1986.0,TOYOTA,PARISIENNE BROUGHAM,XLI,SALOON,GCC,4.0,brown,United States,1500.0,5.0,NaN,PARISIENNE BROUGHAM
191548,JTB53JSF5X0134854,1999.0,TOYOTA,CROWN V,STD,SALOON,GCC,6.0,white,JAPAN,1600.0,5.0,NaN,CROWN V
216771,2T18URHE9JC056480,2018.0,TOYOTA,1.8 XS,S,Sedan,GCC,4.0,black,CANADA,1400.0,6.0,1.8,1.8 XS

In [189]:
import pandas as pd

toyota["engine_variant"] = toyota["model"].str.extract(
    r'(\d\.\d)'
)

toyota["clean_model"] = toyota["model"].str.replace(
    r'\s+\d\.\d.*$',
    '',
    regex=True
)

toyota[["model", "clean_model", "engine_variant"]].head()

     model clean_model engine_variant
0  COROLLA     COROLLA            NaN
1    HIACE       HIACE            NaN
2    HIACE       HIACE            NaN
3    HILUX       HILUX            NaN
4    CAMRY       CAMRY            NaN

In [198]:
df["model"] = (
    df["model"]
    .astype(str)
    .str.upper()
    .str.strip()
)

In [199]:
df["model"] = (
    df["model"]
    .str.replace(r"\s+", " ", regex=True)
)

In [200]:
model_counts = df["model"].value_counts()

rare_models = model_counts[model_counts == 1]

print(len(rare_models))

2089

In [201]:
review = pd.DataFrame({
    "model": df["model"].value_counts().index,
    "count": df["model"].value_counts().values
})

In [203]:
drop_models = [
    "",
    "NONE",
    "MODEL 2009",
    "MODEL 2013",
    "MODEL 2019",
    "MODEL 2020",
    "MODEL 2022",
    "PASSENGER",
    "SEDAN",
    "MOTOR CYCLE",
    "DELIVERY BIKE",
]

In [204]:
model_counts = df["model"].value_counts()

review = model_counts[
    model_counts <= 5
].index.tolist()

In [205]:
df_clean = df.copy()

In [206]:
import numpy as np

df_clean["model"] = (
    df_clean["model"]
    .astype(str)
    .str.upper()
    .str.strip()
)

# normalize spaces
df_clean["model"] = (
    df_clean["model"]
    .str.replace(r"\s+", " ", regex=True)
)

# convert empty strings to NaN
df_clean["model"] = (
    df_clean["model"]
    .replace(["", "NAN", "NONE"], np.nan)
)

In [207]:
make_names = set(
    df_clean["make"]
    .dropna()
    .astype(str)
    .str.upper()
    .unique()
)

mask = df_clean["model"].isin(make_names)

print("Rows affected:", mask.sum())

df_clean.loc[mask, "model"] = np.nan

Rows affected: 4896

In [208]:
df_clean.loc[
    df_clean["model"].str.match(r"^MODEL\s+\d{4}$", na=False),
    "model"
] = np.nan

In [209]:
toyota_mapping = {
    "RAV 4": "RAV4",
    "RAFF 4": "RAV4",

    "TAKOMA": "TACOMA",
    "TOKOMA": "TACOMA",

    "HAIULUX": "HILUX",
    "HAI LUX": "HILUX",

    "LAND CRUISE": "LAND CRUISER",

    "HI ACE": "HIACE",

    "ALFARD": "ALPHARD",

    "TANDRA": "TUNDRA",

    "CHR": "C-HR",

    "SIENA": "SIENNA",
    "SENA": "SIENNA",

    "4 RUNNER": "4RUNNER",

    "BZ 4": "BZ4X",
    "BZ46": "BZ4X",

    "MR 2": "MR2",

    "SELICA": "CELICA",

    "FJ": "FJ CRUISER",

    "RUNNER": "4RUNNER",
    "FORERUNNER": "4RUNNER",

    "DAINA": "DYNA"
}

df_clean["model"] = df_clean["model"].replace(toyota_mapping)

In [210]:
lexus_mapping = {
    "LS460": "LS 460",
    "LS460L": "LS 460",
    "LS 460 L": "LS 460",

    "LS430": "LS 430",

    "RX350": "RX 350",
    "RX350L": "RX 350",
    "RX350H": "RX 350",

    "RX450H": "RX 450H",
    "RX 450 H": "RX 450H",

    "NX350": "NX 350",
    "NX350H": "NX 350H",
    "NX 350 H": "NX 350H",

    "IS250": "IS 250",
    "IS300": "IS 300",
    "IS350": "IS 350",

    "GX460": "GX 460",
    "GX470": "GX 470",

    "ES350": "ES 350",
    "ES300H": "ES 300H",
}

df_clean["model"] = df_clean["model"].replace(lexus_mapping)

In [211]:
unicorn_patterns = [
    "UNICORN",
    "UNIKORN",
    "UNICON",
    "UNICRON",
    "UNICCRN",
    "UNICRN",
    "UNIRON",
    "YUNICORN",
    "JNICORN",
    "YULIKORN",
    "YULICORN",
    "BUNICORN",
    "PUNICORN",
]

for pattern in unicorn_patterns:
    df_clean.loc[
        df_clean["model"].str.contains(pattern, na=False),
        "model"
    ] = "UNICORN"

In [212]:
registration_like = df_clean[
    df_clean["model"].str.contains(
        r"(AT|MT|4X4|4WD|PICK UP CARGO|STATION WAGON)",
        na=False
    )
]

registration_like["model"].value_counts().head(100)

C:\Users\Admin\AppData\Local\Temp\ipykernel_6200\2663747287.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_clean["model"].str.contains(

model
PATROL                                 49172
SONATA                                 11789
PATHFINDER                              7352
ATTRAGE                                 2997
CERATO                                  1676
PASSAT                                  1252
PATROL PICK UP                           852
NAVIGATOR                                341
ATS                                      289
GLADIATOR                                191
CERATO KOUP                              149
NATIVA                                   137
ATTO 3                                   131
QUATTROPORTE                             128
AVIATOR                                  119
PLATINA 100                              115
MATRIX                                   105
PATRIOT                                   62
MATERIA                                   62
FAT BOY                                   45
PATROL GLV                                38
ATLAS                                     37
DESTINATOR                                34
MT-09                                     14
MT-125                                    12
MT-07                                     11
PATROL GL                                  9
ATLAS CROSS SPORT                          9
DUCATO                                     7
MT07                                       7
MT-10                                      7
AFRICATWIN                                 5
ATTO3                                      5
MT-03                                      5
MTN690A                                    5
FAT BOB                                    5
BONGO/PICK UP CARGO                        4
MT09                                       4
PATROL SUPER SAFARI                        3
MT                                         3
PATROL GLV/STATION                         3
CANTER PICK UP CARGO                       3
ATOS PRIME                                 3
800MT                                      3
MX-5 MIATA                                 3
CATERA                                     3
FLAT WOOD                                  3
PASSAT CC                                  3
MTT890GT                                   3
AVATAR 12                                  3
300 PICK UP CARGO                          3
LAND CRUISER PICK UP CARGO                 2
PICK UP CARGO                              2
HARLEY DAVIDSON FAT                        2
STATELINE                                  2
NC750XAT GS                                2
ATOS                                       2
HD 46 PICK UP CARGO                        2
BONGO PICK UP CARGO                        2
MTN 890                                    2
WATER TANK                                 2
HATCHBACK                                  2
SONG L/STATION                             2
GREATWALL TANK                             2
MT 09                                      2
450 MT                                     2
PATRIOT (4WD)                              2
LAND CRUISER / STATION                     1
MT 03                                      1
LAND CRUISER/PICK UP CARGO                 1
COROLLA SEDAN / HATCH                      1
25 CA SON P 2.5L AT                        1
26 YA HB P 1.6L AT TURBO GR RA(CAR)        1
GXL RA (STATION WAGON)                     1
25PR 5 DR P 2.4L AT                        1
YARIS HATCHBACK                            1
TAKOMA PICK UP CARGO                       1
COROLLA 1.5L/HATCHBACK                     1
LAND CRUISER - PICK UP CARGO               1
PATROL GL V                                1
ROGUE (4WD)                                1
PATROL/STATION                             1
2400 PICK UP CARGO                         1
PATROLYYYY                                 1
PATHFINDER AWD                             1
TIIDA HATCHBACK                            1
PATROL SE                                  1
VAN 3S4DRSRMT U11A(VAN)                    1
PATROL SUPER SA                            1
JUKE STATION                               1
PATROL XE                                  1
/ PATROL / STATION                         1
NX 350 H STATION                           1
PAJERO STATION                             1
ENS USTATION                               1
HR (4WD)                                   1
NC750XAT                                   1
CMX500AT (MOTORCYCLE)                      1
NC750XAT 2GS                               1
PORTER/PICK UP CARGO                       1
Name: count, dtype: int64

In [ ]:
rare_models = (
    df_clean["model"]
    .value_counts()
    .reset_index()
)

rare_models.columns = ["model", "count"]

rare_models[rare_models["count"] <= 5]

In [214]:
print(df["model"].nunique())

4884

In [215]:
print(df_clean["model"].nunique())

4711

In [216]:
(
    df_clean["model"]
    .value_counts()
    .head(20)
)

model
CAMRY           50403
PATROL          49172
ALTIMA          42065
COROLLA         38094
LAND CRUISER    32197
SUNNY           28077
YARIS           23276
TIIDA           16894
HILUX           16733
CIVIC           16333
ACCORD          14743
LS 430          13227
RAV4            12354
SONATA          11789
HIACE           11763
CANTER          11057
SENTRA          10897
PAJERO           9384
LX570            9015
PRADO            7814
Name: count, dtype: int64

In [ ]:
rare_models[rare_models["count"] <= 5]

In [218]:
df_clean["model"].nunique()

4711

In [219]:
df_clean["model"].value_counts().head(100)

model
CAMRY                50403
PATROL               49172
ALTIMA               42065
COROLLA              38094
LAND CRUISER         32197
SUNNY                28077
YARIS                23276
TIIDA                16894
HILUX                16733
CIVIC                16333
ACCORD               14743
LS 430               13227
RAV4                 12354
SONATA               11789
HIACE                11763
CANTER               11057
SENTRA               10897
PAJERO                9384
LX570                 9015
PRADO                 7814
ES 350                7566
PATHFINDER            7352
X TRAIL               7019
MODEL 3               7008
SIENNA                6839
SIERRA                6787
OPTIMA                6693
LANCER EX             6685
ELANTRA               6672
SPORTAGE              6535
UNICORN               6478
IS 250                6306
RANGE ROVER           5649
TUCSON                5364
MAXIMA                5359
FORTUNER              5342
LANCER                5307
KICKS                 5180
MODEL Y               5125
VERSA                 4953
ROGUE                 4803
T2                    4666
AVALON                4557
URVAN                 4555
ACCENT                4478
ARMADA                4366
TUNDRA                4339
CR-V                  4278
LS 460                4258
SANTA FE              4071
RANGE ROVER SPORT     3976
L200                  3960
RX 350                3900
TAHOE                 3758
EXPLORER              3716
YUKON                 3654
MUSTANG               3493
SILVERADO             3446
F-150                 3400
WRANGLER              3382
GS350                 3274
CAPTIVA               3249
CHARGER               3227
EDGE                  3157
3                     3001
ATTRAGE               2997
FJ CRUISER            2956
C200                  2877
IMPALA                2866
E300                  2853
GOLF                  2829
CITY                  2784
MALIBU                2706
INNOVA                2687
C300                  2670
X TERRA               2615
6                     2588
SORENTO               2519
GRAND CHEROKEE        2496
LX470                 2466
IS 300                2422
RUSH                  2409
DEFENDER 110          2304
ASX                   2238
CAYENNE               2238
JUKE                  2223
RIO                   2188
H1                    2185
S500                  2141
1500                  2132
NAVARA                2076
FOCUS                 2070
OUTLANDER             2069
DUSTER                2052
PREVIA                2041
VELOSTER              2019
CRUZE                 2019
X5                    2017
01                    2007
G63 AMG               1983
Name: count, dtype: int64

In [ ]:
rare_models = (
    df_clean["model"]
    .value_counts()
    .reset_index()
)

rare_models.columns = ["model", "count"]

rare_models[rare_models["count"] <= 5]

In [220]:
df_clean[
    df_clean["model"].str.contains(r"\d", na=False)
]["model"].value_counts().head(200)

model
LS 430                    13227
RAV4                      12354
LX570                      9015
ES 350                     7566
MODEL 3                    7008
IS 250                     6306
T2                         4666
LS 460                     4258
L200                       3960
RX 350                     3900
F-150                      3400
GS350                      3274
3                          3001
C200                       2877
E300                       2853
C300                       2670
6                          2588
LX470                      2466
IS 300                     2422
DEFENDER 110               2304
H1                         2185
S500                       2141
1500                       2132
X5                         2017
01                         2007
G63 AMG                    1983
E350                       1677
K5                         1427
QX80                       1427
IS 350                     1338
GS300                      1229
LEOPARD 8                  1224
CLA250                     1182
5                          1119
X6                         1103
Q50                        1085
S550                       1069
ES300                      1060
LS400                      1052
CX-9                       1046
FX35                       1034
520I                       1005
QX60                        958
CS35 PLUS                   923
GX 460                      900
X70 PLUS                    896
S350                        885
ID 4 CROZZ                  857
E200                        854
LX600                       843
Q7                          843
CX-5                        799
QX56                        783
530I                        779
911                         758
LEOPARD 7                   755
RX5                         745
E2000                       742
GLC300                      724
LAND CRUISER PICKUP 70      722
QX50                        696
A6                          659
Q5                          655
2                           632
500                         612
IS200T                      602
J7                          586
320I                        571
CLS350                      566
QX70                        561
A3                          555
A8                          554
LEOPARD 5                   551
A4                          543
ES300 H                     542
300C                        517
3008                        509
C250                        505
750LI                       488
S3                          484
K3                          483
X4                          483
NX200T                      475
7                           468
PULSAR 150                  466
RX8                         465
740LI                       462
ID 6 CROZZ                  460
H9                          458
ML350                       454
POLESTONE 01                430
X7                          426
A5                          424
RX 450H                     411
G500                        402
A220                        399
G80                         397
730LI                       393
A250                        384
S400                        384
CS85                        375
G37                         371
300                         367
CBF160                      362
GS8                         359
UX200                       355
T60                         354
GS430                       353
330I                        353
I10                         350
GL500                       347
318I                        347
RX330                       331
X3                          322
GLC200                      321
NX300                       319
150 CC                      319
JS4                         315
A200                        314
CS95                        314
GLE450                      312
ES250                       310
HUNK 150                    309
DEFENDER 90                 307
EX35                        303
523I                        300
GLC250                      293
G25                         291
X1                          284
G70                         281
G35                         279
Q3                          279
GV70                        278
86                          276
X90 PLUS                    275
E320                        273
A7                          273
4RUNNER                     272
Q70                         271
XC90                        271
S560                        270
NX 350                      269
H6                          268
208                         265
E280                        257
GLE350                      250
370Z                        245
E500                        244
XC60                        244
E400                        243
CX-30                       242
GLE53 AMG                   241
S63 AMG                     241
Q8                          237
SX4                         233
H2                          233
E-NS1                       232
535I                        229
CLS500                      228
GLA250                      228
420I                        227
GS3                         225
GLE43 AMG                   221
C63 AMG                     219
H3                          218
GLS450                      212
CX-3                        211
HS5                         211
T77                         211
430I                        209
V250                        208
528I                        207
X2                          205
595                         203
GV80                        201
GSX 1300                    197
RX5 PLUS                    195
C350                        191
XT5                         191
FX50                        188
RC350                       187
C200 K                      186
JS6                         185
X70S                        183
E250                        180
X70                         177
I30                         176
CBR125R                     175
740I                        174
L300                        172
PULSAR 180CC                168
GX 470                      167
E63 AMG                     167
E450                        167
M4                          166
E240                        165
323                         165
GS3 EMZOOM                  164
GRAND I10                   163
C43 AMG                     163
Name: count, dtype: int64

In [221]:
df_clean["model_length"] = df_clean["model"].str.len()

df_clean.sort_values(
    "model_length",
    ascending=False
)[["make", "model"]].head(100)

                    make                                        model
953912             GEELY  LONG RANGE STARBUCKS V7 SMATE EDITION (VAN)
826764        LAND ROVER   DEFENDER 110 V8 ULTIMATE EDITION PS25(4WD)
775390              FORD    E450 THOR MOTOR COACH MAGNITUDE GRAND R36
1009082          POLARIS      TWC-25, 2.0,A,LE SLINGSHOT 10 AUTODRIVE
773373              FORD       F600 ENTEGRA ESTEEM XL 33F (MOTORHOME)
758781              FORD         ECONOLINE E350 SUPERDUTY (MOTORHOME)
158958            TOYOTA          26 YA HB P 1.6L AT TURBO GR RA(CAR)
761759              FORD          E450 THOR MOTOR COACH FREEDOM ELITE
239051            TOYOTA            LAND CRUISER SINGLE-CABIN PICK UP
1003204              TVS             ستار اتش ال اكس في اس 1 تي في اس
1003202              TVS             ستار اتش ال اكس في اس 1 تي في اس
773587              FORD             RAPTOR F-150 PICKUP DOUBLE CABIN
773739              FORD             RAPTOR F-150 PICKUP DOUBLE CABIN
105877            TOYOTA               LAND CRUISER SINGLE-CABIN PICK
833073            SUZUKI               GSX1300R HAYABUSA (MOTORCYCLE)
1008233          TRIUMPH               BONNEVILLE BOBBER (MOTORCYCLE)
838104            SUZUKI               GSX1300R HAYABUSA (MOTORCYCLE)
53808             TOYOTA               LAND CRUISER SINGLE-CABIN PICK
1004278             HINO                HINO/300/FOODSTUFF FRIDGE VAN
995319              TANK                ATTACKER/PICK UP DOUBLE CABIN
277512            NISSAN                FRONTIER/PICK UP DOUBLE CABIN
1007556         DONGFENG                 P16 121/PICK UP DOUBLE CABIN
826802        LAND ROVER                 DEVENDR SINGLE-CABIN PICK UP
227253            TOYOTA                 LAND CRUISER - PICK UP CARGO
756065              FORD                  RAPTOR PICK UP DOUBLE CABIN
998571   HARLEY-DAVIDSON                  ELECTRA GLIDE ULTRA LIMITED
815956               GMC                  SIERRA SINGLE-CABIN PICK UP
867307             MAZDA                  P 2200/PICK UP DOUBLE CABIN
187615            TOYOTA                  TANDRA PICK UP DOUBLE CABIN
816175               GMC                  SIERRA SINGLE-CABIN PICK UP
992024        GREAT WALL                  WINGLE/PICK UP DOUBLE CABIN
1008637        KING LONG                  KING LONG/XMQ5030/VAN CARGO
630568           HYUNDAI                  PORTER/FOODSTUFF FRIDGE VAN
811278               GMC                  SIERRA PICK UP DOUBLE CABIN
991696        GREAT WALL                  WINGLE/SINGLE-CABIN PICK UP
816701               GMC                  SIERRA PICK UP DOUBLE CABIN
760295              FORD                  E450 SUPER DUTY (MOTORHOME)
769121              FORD                  RANGER PICK UP DOUBLE CABIN
773088              FORD                  RANGER PICK UP DOUBLE CABIN
771932              FORD                  E450 SUPER DUTY (MOTORHOME)
351587            NISSAN                   TITAN PICK UP DOUBLE CABIN
952672             GEELY                   STARRAY 2.0TD GF PLUS(4WD)
761518              FORD                   F 250/PICK UP DOUBLE CABIN
204390            TOYOTA                   LAND CRUISER/STD EX PICKUP
656583               KIA                   BONGO/SINGLE-CABIN PICK UP
189115            TOYOTA                   LAND CRUISER PICK UP CARGO
38241             TOYOTA                   LAND CRUISER PICK UP CARGO
144113            TOYOTA                   LAND CRUISER/PICK UP CARGO
762510              FORD                   F 150 PICK UP DOUBLE CABIN
812952               GMC                   DEXER SINGLE-CABIN PICK UP
965520               JAC                   HFC 1061 K / PICK UP CARGO
772027              FORD                   EXPEDITION MAX LIMITED 4WD
1006792             TATA                   XENON/SINGLE-CABIN PICK UP
520839        MITSUBISHI                    L 200 SINGLE CABIN PICKUP
1009503            SWIFT                    175 SHARMAX - STREET BIKE
804235               GMC                    SIERRA PICK UP DOUBLE CAB
706885     MERCEDES BENZ                    E 53 HYBRID 4MATIC+ SEDAN
1009086           ZXAUTO                    TERRALORD GASOLINE PICKUP
520841        MITSUBISHI                    L 200 SINGLE CABIN PICKUP
784686             TESLA                    CYBERTRUCK DUAL MOTOR NEW
964067             BAJAJ                    50 CC/MOTORCYCLE DELIVERY
916626             DODGE                    1500/PICK UP DOUBLE CABIN
677551               KIA                    BONGO SINGLE-CABIN PICKUP
913063             DODGE                    1500/PICK UP DOUBLE CABIN
808320               GMC                    SIERRA PICK UP DOUBLE CAB
911540             DODGE                    2500/PICK UP DOUBLE CABIN
1005618            KAIYI                    KYD3000D1 (ELECTRIC BIKE)
1009062       POWEREAGLE                     F02 (ELECTRIC LOAD BIKE)
962460             ISUZU                     NMR LIGHT DUTY (PICK UP)
961582             ISUZU                     NLR LIGHT DUTY PICK (UP)
1009390         SHARAMAX                     350 SHARMAX - SHARMAX FX
715065     MERCEDES BENZ                     2641 DRINKING WATER TANK
926994              AUDI                     RS 3 SPORTBACK HATCHBACK
831333        LAND ROVER                     DEFENDER 90 X-DYNAMIC SE
736223         CHEVROLET                     LUV/PICK UP DOUBLE CABIN
443379            NISSAN                     NVARA / PICK UP DOUBLE C
1009278          VOLTAMP                     VTP11000 (ELECTRIC BIKE)
816102               GMC                     NKR PICK UP DOUBLE CABIN
1009376         SHARAMAX                     350 SHARMAX - SHARMAX FX
730387         CHEVROLET                     SILVERADO PICK UP DOUBLE
814950               GMC                     NKR PICK UP DOUBLE CABIN
1009520          JOYLONG                     HKL 6480 C/VAN PASSENGER
1008617           RIVIAN                      RTT ADVENTURE (PICK UP)
842837            SUZUKI                      GSX1300RRQ (MOTORCYCLE)
361676            NISSAN                      VAN 3S4DRSRMT U11A(VAN)
1009490        SLINGSHOT                      GCINGEROY ELINGSHOT SLR
963094             ISUZU                      D MAX SINGLE-CABIN PICK
998415   HARLEY-DAVIDSON                      SPORTSTER CUSTOM XL 883
841418            SUZUKI                      SUZUKI/650CC/MOTORCYCLE
833393            SUZUKI                      GSX R1000R (MOTORCYCLE)
76401             TOYOTA                       LAND CRUISER PICKUP 70
5107              TOYOTA                       LAND CRUISER PICKUP 70
45984             TOYOTA                       LAND CRUISER PICKUP 70
136151            TOYOTA                       LAND CRUISER PICKUP 70
840201            SUZUKI                       GSX R1000 (MOTORCYCLE)
180530            TOYOTA                       LAND CRUISER PICKUP 70
16402             TOYOTA                       LAND CRUISER PICKUP 70
91663             TOYOTA                       LAND CRUISER PICKUP 70
91633             TOYOTA                       LAND CRUISER PICKUP 70
173332            TOYOTA                       LAND CRUISER PICKUP 70

In [223]:
df_clean.groupby("make")["model"].nunique().sort_values(ascending=False)

make
MERCEDES BENZ        562
HONDA                360
BMW                  344
SUZUKI               245
NISSAN               171
LEXUS                147
TOYOTA               142
HYUNDAI              109
BAJAJ                104
YAMAHA               101
KIA                  100
FORD                  99
CHEVROLET             88
HARLEY-DAVIDSON       88
BYD                   73
MITSUBISHI            70
VOLKSWAGEN            64
INFINITI              62
KAWASAKI              59
SHARMAX               54
FERRARI               51
MAZDA                 51
CHANGAN               51
AUDI                  46
ISUZU                 45
GMC                   44
GEELY                 39
CADILLAC              38
VESPA                 38
CHERY                 37
LAND ROVER            37
MG                    37
VOLVO                 36
VICTORY               36
HERO                  35
JAC                   34
TVS                   33
DONGFENG              30
ROYAL ENFIELD         29
GREAT WALL            28
RENAULT               28
GAC                   26
KTM                   26
CFMOTO                26
BAIC                  25
PEUGEOT               25
DODGE                 25
FOTON                 24
APRILIA               24
DUCATI                24
TRIUMPH               23
PORSCHE               23
MINI                  23
JAGUAR                22
CHRYSLER              22
FIAT                  22
LINCOLN               22
JETOUR                20
CITROEN               19
HINO                  18
TATA                  17
MAXUS                 17
DFSK                  17
ROLLS ROYCE           16
SANYA                 16
JEEP                  15
SKODA                 14
DAIHATSU              14
ASTON MARTIN          14
MCLAREN               14
OPEL                  13
HONGQI                12
ALFA ROMEO            12
HAVAL                 12
TESLA                 12
BENTLEY               12
ROX                   11
INDIAN MOTORCYCLE     11
SUBARU                11
CMC                   11
SYM                   10
LYNK & CO             10
ZEEKR                 10
GENESIS               10
LAMBORGHINI            9
EXEED                  9
SMART                  9
AVATR                  8
KING LONG              8
AYED                   8
BENELLI                8
JMC                    8
NIO                    8
MASERATI               8
IVECO                  8
LI AUTO                7
ABARTH                 7
BESTUNE                7
SOUEAST                7
CAN-AM                 7
ASHOK LEYLAND          7
MOTO GUZZI             6
ACURA                  6
KYMCO                  6
ZONGSHEN               6
POWEREAGLE             6
XPENG                  6
LOTUS                  6
PIAGGIO                6
KAIYI                  6
SSANGYONG              6
POLARIS                6
VOLTAMP                5
ZXAUTO                 5
LIFAN                  5
VANDERHALL             5
CHANGHUA               5
SEAT                   5
DAEWOO                 5
POLESTAR               5
MERCURY                5
MV AGUSTA              5
XIAOMI                 5
ZOTYE                  5
MORGAN                 5
LEAPMOTOR              5
SAAB                   5
FORTHING               5
BRILLIANCE             4
BUICK                  4
QINGLING               4
RABDAN                 4
RAM                    4
RIVIAN                 4
CHERY - ICAR           4
SHERCO                 4
FAW                    4
DATSUN                 4
DONGFENG-AEOLUS        4
TANK                   4
TGB                    4
BYD - DENZA            4
DEEPAL                 4
HUSQVARNA              4
PONTIAC                4
AEOLUS                 4
LADA                   3
AITO                   3
WULING                 3
VINFAST                3
MAYBACH                3
JAECOO                 3
HUMMER                 3
PROTON                 3
BORGWARD               3
BENDA                  3
WIESMANN               3
VICTORIA               3
TRUMPCHI               3
VOYAH                  3
SLINGSHOT              3
SERES                  3
EMPALA                 3
EICHER                 3
BUGATTI                3
BAW                    3
DONGFENG-XIAOKA        2
DORCEN                 2
GAS GAS                2
GUNAU                  2
LIVEWIRE               2
YADEA                  2
KOASKO                 2
OMODA                  2
HYOSUNG                2
HUAIHAI                2
HIPHI                  2
LUCID                  2
ZNA                    2
MAHINDRA               2
SAIC                   2
RIDDARA                2
PAGANI                 2
DONGFENG E             2
VGV                    2
ECOWAY                 2
SHARAMAX               2
ESCHER                 2
FOLONY                 2
SCANIA                 2
UAZ                    2
AFTEK                  1
AIQAR                  1
LYKAN                  1
LUXGEN                 1
KAN M                  1
KOVE                   1
KOENIGSEGG             1
MAN                    1
ZHENGZHOU              1
YUTONG                 1
ZAMIYAD                1
ZERO                   1
ZENIN                  1
ZNIN                   1
AVENGER                1
XCMG                   1
AL DAMANI              1
ARI                    1
ASHOK                  1
APACHE                 1
APULUO                 1
BYD - LEOPARD          1
HAOJUE                 1
PUYUAN                 1
GWM - WEY              1
PREVOST                1
INEOS                  1
PADAR                  1
FORCE                  1
HYCAN                  1
JIYUE                  1
MHERO                  1
MONTESA                1
HIG                    1
NETA                   1
HIGER                  1
PEMBLETON              1
JCB                    1
ITALJET                1
JINBEI                 1
JIDU                   1
LANCIA                 1
JOYLONG                1
LIEBHERR               1
ZONTES                 1
MAEXTRO                1
MACK                   1
ROYAL ALLOY            1
ELECTRIC MOTION        1
SCION                  1
HART FORD              1
SAMSUNG                1
SANIYA                 1
BETA                   1
DAF                    1
SINOTRUK               1
SKYWELL                1
SCORPA                 1
SANYOU                 1
SATURN                 1
SHANG JAN              1
FANTIC                 1
FARIZON                1
FLONY                  1
SANDSTORM              1
SANY                   1
CATERHAM               1
BUELL                  1
BYD - YANGWANG         1
VOLG                   1
BAOJUN                 1
SWIFT                  1
BAJA                   1
SOUO                   1
CHAMP                  1
CATERPILLAR            1
TAM                    1
ADMIRAL                1
VANDER                 1
BIMOTA                 1
BLUE BIRD              1
TYANMA                 1
KAMA                   0
ROCKY                  0
DELOREAN               0
Name: model, dtype: int64

In [ ]:
model_counts = (
    df_clean
    .groupby(["make","model"])
    .size()
    .reset_index(name="count")
)

model_counts.sort_values("count")

In [ ]:
model_counts[model_counts["count"] == 1]

In [226]:
toyota = df_clean[df_clean["make"] == "TOYOTA"]

toyota["model"].value_counts().head(100)

model
CAMRY                             50402
COROLLA                           38094
LAND CRUISER                      32197
YARIS                             23276
HILUX                             16732
RAV4                              12354
HIACE                             11763
PRADO                              7814
SIENNA                             6839
FORTUNER                           5342
AVALON                             4557
TUNDRA                             4339
FJ CRUISER                         2956
INNOVA                             2687
RUSH                               2409
PREVIA                             2041
PRIUS                              1585
AVANZA                             1520
CAMRY HYBRID                       1380
SEQUOIA                            1051
AURION                              985
COROLLA CROSS                       875
RAIZE                               829
LAND CRUISER PICKUP 70              722
ECHO                                700
VELOZ                               606
LAND CRUISER PICK UP                583
COASTER                             554
URBAN CRUISER                       551
XA                                  540
HIGHLANDER                          517
TACOMA                              478
C-HR                                418
86                                  276
4RUNNER                             272
SUPRA                               218
CROWN                               212
LITEACE                             136
LAND CRUISER PRADO                  124
LAND CRUISER 70                      95
ZELAS                                92
GRANVIA                              89
TERCEL                               84
IQ                                   76
LEVIN                                53
COROLLA 1.6                          39
BZ4X                                 28
MATRIX                               27
SOLARA                               24
COROLLA 1.3                          22
GR86                                 21
COROLLA 1.8                          20
DYNA                                 13
COROLLA SEDAN                         7
CELICA                                7
CRESSIDA                              5
MR2                                   4
VENZA                                 4
CROWN KLUGER                          3
ALTIS                                 3
WISH                                  3
LITE ACE                              2
BZ3X                                  2
LAND CRUISER PICK UP CARGO            2
RUMION                                2
LAND CRUISER SINGLE-CABIN PICK        2
ALLION                                2
COROLLA 1.6/SEDAN                     2
VXL 150                               2
DLX FA (PICK UP)                      2
WIGO                                  2
HILUX ADVENTURE                       2
CENTURY                               2
T 300                                 1
LAND CRUISER VXR                      1
COROLLA 1.5                           1
FLTRXS                                1
LAND CRUISER / STATION                1
SY150T                                1
HILUX RE                              1
KS01                                  1
SICION                                1
MT 03                                 1
T 100                                 1
ALPHARD                               1
PRADO GX                              1
GRAND DELUX                           1
VIOS                                  1
SIENNA VAN                            1
SIERRA                                1
SENA VAN PASSENGER                    1
LAND CRUISER GX                       1
PICK UP CABIN                         1
SUPRA COUPE                           1
TACOMA (PICK UP)                      1
HI S COACH                            1
LAND CRUISER/PICK UP CARGO            1
FRONTLANDER                           1
COROLLA SEDAN / HATCH                 1
25 CA SON P 2.5L AT                   1
Name: count, dtype: int64

In [229]:
toyota["vds"] = toyota["chassisNumber"].astype(str).str[3:8]

In [230]:
toyota.groupby("vds")["model"].nunique().sort_values(ascending=False)

vds
LJ73J    10
LU73J    10
JJXB0     8
BT441     5
AG34L     5
EF8BF     5
NX22N     5
PBEJA     5
A180C     5
M8500     5
JX02P     5
ZD31V     4
AACAJ     4
AAAAA     4
FU71J     4
BU71J     4
BT14R     4
BR32E     4
BR22E     4
BL9HE     4
BB0BE     4
71SC1     4
LB71J     4
LJ71J     4
KARJE     4
LU71J     4
11111     4
A14CK     4
A4DAA     4
ZU14R     4
A4B3A     3
AA9AJ     3
14252     3
ZF13C     3
B519E     3
B3J6P     3
BB02E     3
BB9HE     3
BC42E     3
BBOBE     3
BD1FK     3
79END     3
BE32K     3
BF0JE     3
BE6DS     3
BE6BS     3
BF9FK     3
BG22K     3
BJ53L     3
PAEHD     3
PX4EN     3
PX22P     3
PM62N     3
BPB9E     3
BM99J     3
BT481     3
BU25J     3
BU17R     3
BU14R     3
BU9FJ     3
BU3FJ     3
BV71J     3
BX9FJ     3
BZ42E     3
MF53F     3
21608     3
MX83E     3
MX73E     3
MU4FN     3
NM92N     3
NX4CN     3
1BAA3     3
CECB8     3
CX3FJ     3
D3135     3
CZ5AN     3
DR32T     3
EX19G     3
FM518     3
FM418     3
ML110     3
FK418     3
GE52M     3
44925     3
HX02P     3
K4MBE     3
KARFP     3
KD3B3     3
TX22N     3
VB9E7     3
VL52N     3
11VJ9     3
KK3DC     3
KHMBX     3
KRKEC     3
KR30E     3
KW73J     3
ZCP2F     3
ZU5JR     3
00000     3
A4CFA     3
YK3DC     3
YMLA2     3
ACAAU     3
ZA3BB     2
ZA22C     2
10252     2
ZCP2H     2
AL29J     2
AG4CK     2
ARE0C     2
AP86C     2
15100     2
14270     2
UCK1H     2
TX4CN     2
8L9HE     2
8W23E     2
AE52S     2
AFAAF     2
KN36U     2
KU4EE     2
KT9F3     2
KX6CB     2
KW923     2
L11AK     2
KZ3DC     2
A11CX     2
A4GF5     2
ZCN1F     2
ZCK1H     2
ZK31V     2
ZFREV     2
ZK22C     2
889HE     2
880CE     2
UU4EN     2
VB9E6     2
V0LEZ     2
W13FV     2
WA37R     2
12005     2
12003     2
12001     2
WG81R     2
XE4FS     2
KC20F     2
KK4CC     2
KDTB3     2
KT441     2
KSKFC     2
KR32E     2
JM11D     2
JU3FJ     2
JU9FJ     2
JX8CB     2
K61AK     2
K43BE     2
JY5G1     2
KAMFU     2
KAAAG     2
KB8CD     2
KB20U     2
32BUM     2
31UJ7     2
KCAAG     2
UF117     2
UX4EN     2
H4ACP     2
GZ3DH     2
HD17F     2
HJ09J     2
HG17C     2
HT05J     2
HP10V     2
HN9CP     2
HN87R     2
HN86R     2
HU09J     2
HW2ZZ     2
J13FV     2
JA82J     2
JK3DC     2
JNK64     2
LV73J     2
LU733     2
MD351     2
MD121     2
MC13F     2
MA71J     2
MF929     2
FU73J     2
FR320     2
G11BK     2
G11AK     2
FY418     2
G4X20     2
GJKFW     2
GP21A     2
GN87R     2
EW23E     2
FB518     2
F1RFV     2
FE728     2
FE718     2
FE52S     2
46470     2
FK518     2
LDHAD     2
LB5JN     2
LA5DB     2
LU4EN     2
LU42N     2
LMFCP     2
M11AK     2
LY3FX     2
DB4A0     2
DBZSV     2
DK3EH     2
DF9EV     2
DF4EV     2
DP21A     2
DN136     2
DW12S     2
DW11S     2
DZ5BN     2
DY5G1     2
EF88F     2
EG22K     2
ES12G     2
ER23E     2
EW44A     2
BY879     2
BY80E     2
C916Z     2
C2ZWB     2
C11BK     2
C11AK     2
BZRFH     2
CAABG     2
CJE23     2
CS18Z     2
CX9FJ     2
CX9CD     2
CX8CD     2
50975     2
D3DF6     2
DB0G0     2
BU8CD     2
BU4EE     2
BV42E     2
BW22E     2
BW12S     2
BX8CD     2
BZ4HK     2
BZ28E     2
21610     2
21606     2
21604     2
MU52N     2
PAAWA     2
P6X40     2
1201D     2
1CU83     2
RX12P     2
SS1EK     2
17100     2
BKRFH     2
BPMBE     2
BN95J     2
BT123     2
BR38E     2
BR23E     2
BU11F     2
53SK2     2
53EL5     2
53EEA     2
53AEB     2
53AEA     2
BT9F3     2
BK1EB     2
BK4FK     2
BK46K     2
BK40K     2
BK3EK     2
BK36B     2
BL29J     2
PG34L     2
PCKL9     2
PBEHD     2
PBEFA     2
PBAJA     2
PX42N     2
RC1BG     2
R1CS9     2
RX5GN     2
BF31E     2
BF30K     2
BF23K     2
BF22K     2
BF1FK     2
BF9HK     2
BF9EV     2
BF4HK     2
BF4FK     2
BF3EK     2
BH9FJ     2
BH42K     2
BG28K     2
BG23K     2
BG21K     2
BK1FK     2
BC74K     2
BBOCE     2
BD31V     2
7ENFU     2
7ANFU     2
72SK2     2
BE42K     2
BE40K     2
BE33K     2
BE30K     2
BE6AS     2
66B3D     2
BE46K     2
BF38K     2
BF32K     2
BF31F     2
B29HK     2
B24HK     2
B19HK     2
B14HK     2
B4B9E     2
B3FE1     2
B31HK     2
BA02E     2
BA01E     2
B61HK     2
BAOBE     2
80001     2
BB46K     2
BB3EK     2
BB13E     2
BCE1J     2
AF4E3     2
AECB8     2
AEACH     2
WN72N     2
XZ3DC     2
XX43G     2
AP22C     2
AN95J     2
AU25J     2
ASW0A     2
ASB3R     2
AS02D     2
AS02A     2
B11HK     2
AZ5CN     2
B2E6K     2
8URHE     2
8U40E     2
8U3FJ     2
95403     2
94403     2
91903     2
8X9FJ     2
ACABF     2
A4B2A     2
A4CEA     2
AAABG     2
AAA0C     2
ABBBJ     2
AB1BY     2
ZN3EU     2
ZBB2K     2
8CE1K     2
8CCVD     2
8R22E     2
XX42G     2
YH20V     2
YD3EV     2
YZRFH     2
YZ3DC     2
ZN128     2
ZK3DC     2
06XZZ     2
ZT14R     2
ZNBF1     2
ZU17R     2
ZZRFH     2
ZK23C     2
ZNBB1     1
00ACV     1
00968     1
00943     1
00898     1
00856     1
00800     1
00713     1
00612     1
01111     1
01302     1
01BUM     1
02290     1
022GD     1
03350     1
042TN     1
06622     1
0B9CB     1
0J4MC     1
ZNAA1     1
ZNAE1     1
ZK32V     1
ZK33V     1
ZK34V     1
ZK4CC     1
8622K     1
8628K     1
87367     1
87N07     1
8808E     1
8842E     1
8846K     1
88OCE     1
8A02E     1
8A08E     1
80890     1
80893     1
ZU4BF     1
ZV42E     1
ZX69G     1
ZY0CC     1
8A32K     1
8B9HE     1
8BCE1     1
8C42E     1
8D1FK     1
8D31V     1
8D33V     1
8D35E     1
8E30K     1
8E32K     1
8E33K     1
8E42K     1
824HK     1
829F3     1
829HK     1
855HZ     1
8F22K     1
8F28K     1
8F30K     1
8F31F     1
8F32K     1
8F38K     1
8F3EK     1
8F4DV     1
8F4FK     1
8F4HK     1
8F9C3     1
8F9EV     1
8F9FK     1
8F9HK     1
8A13E     1
8A23C     1
8G22K     1
8J466     1
8J53L     1
8K1E8     1
8K1FK     1
8K22C     1
8K31V     1
8K32V     1
8K33V     1
8K368     1
8K36B     1
8K3D8     1
8K3DB     1
8K3EK     1
8E46K     1
8F1FK     1
8K40K     1
8K46K     1
8K4FK     1
8L0HE     1
8L29J     1
8N95J     1
8R23E     1
8R32E     1
8R42E     1
8RI2E     1
8T923     1
8T9F3     1
8U11F     1
8U25J     1
8FIFK     1
8FREV     1
91902     1
91908     1
93220     1
95021     1
8U4EE     1
8U5CD     1
8U71J     1
8U8CD     1
8V42E     1
8V541     1
8V71J     1
8W123     1
8W133     1
8W923     1
8W933     1
8W9F3     1
A11CY     1
A14AF     1
A16E3     1
A1809     1
A1ACC     1
A1RFV     1
A22EZ     1
A22NE     1
8X8CD     1
8Y561     1
8Y5F1     1
8Y64A     1
8Z4HK     1
90615     1
91900     1
91901     1
80943     1
80950     1
80951     1
80986     1
80987     1
81018     1
811EB     1
811HK     1
813FV     1
814HK     1
819F3     1
819HK     1
8242E     1
80473     1
80506     1
A11AK     1
AABAJ     1
A4B5A     1
A4DAC     1
A4DBA     1
A4DF5     1
A4DMA     1
A4MBE     1
A4RBE     1
A6426     1
A818Y     1
A878J     1
A888J     1
AA18A     1
9FD8T     1
A0B98     1
80907     1
AB1BA     1
AB36U     1
AB7BJ     1
AB7RJ     1
ABBAA     1
AA1AB     1
AA1BA     1
AA5RX     1
AA7BJ     1
AAAA5     1
AAAAF     1
AAAAG     1
AAAB5     1
AAABA     1
AAADC     1
AAAOC     1
AC1DM     1
AC22C     1
AC7BJ     1
ACAAJ     1
ACAB5     1
ACABA     1
ACABB     1
ACJ4H     1
AABBJ     1
AACBJ     1
AAIBA     1
AALAJ     1
AAN6E     1
AATBA     1
AAYAJ     1
AB18Y     1
AE07B     1
AE09B     1
AE09E     1
AE09V     1
AE09W     1
AE1BY     1
AE1EY     1
AE2KP     1
AE51S     1
AE525     1
AE53S     1
ABBDH     1
ABCBJ     1
ABFAJ     1
ABIBY     1
AC11R     1
80558     1
80583     1
80593     1
80636     1
80700     1
80761     1
80767     1
80772     1
80839     1
80850     1
80876     1
80183     1
801FK     1
AE00E     1
AE04B     1
AE04E     1
AE54S     1
AE82G     1
AE94A     1
AE94K     1
AEAA1     1
AECG2     1
AECG3     1
AF047     1
AF4CB     1
AF54K     1
AFABF     1
AFCG2     1
AE00B     1
80532     1
80533     1
80548     1
AR9AJ     1
ARCAJ     1
ARE2C     1
AFZBG     1
AG20A     1
AG30A     1
AG426     1
AGACH     1
AGNAC     1
AI4CK     1
AJ54K     1
AK54K     1
AKCB8     1
AL1CC     1
AM11H     1
AM29J     1
ASACK     1
ASG0A     1
AT123     1
AT2MV     1
AU78J     1
AU7BJ     1
AU88J     1
AM2AH     1
AM450     1
AM496     1
AM498     1
AN74K     1
AP54K     1
AP90A     1
APE2C     1
AR05Y     1
AUTBJ     1
AUZBJ     1
AVV5F     1
AW126     1
AW12G     1
AW5F1     1
AX126     1
AX12G     1
AX5GN     1
AX8CD     1
AXACC     1
AY117     1
AS123     1
AS12G     1
AS14U     1
AS47H     1
AY86C     1
AYACC     1
AYT30     1
AZ1FB     1
AZ496     1
B0111     1
B011F     1
B025J     1
B031V     1
B03FV     1
B046K     1
B13FV     1
AUBB3     1
AUBBJ     1
AUCBJ     1
AUF0A     1
80251     1
80274     1
80281     1
80282     1
80318     1
80328     1
80345     1
80350     1
80407     1
80413     1
80430     1
80459     1
80464     1
7JNFU     1
7KE43     1
AY5F1     1
B4MDE     1
B4MEE     1
B4RBE     1
B19F3     1
B1B0E     1
B1DWA     1
B1RFV     1
B21FB     1
B21HK     1
B23HK     1
B242E     1
B28F3     1
B29F3     1
B29M3     1
AY2NY     1
80233     1
BA03E     1
BA05E     1
BA0BE     1
BA13E     1
BA1HK     1
BA22C     1
BA23C     1
BA244     1
B2NBA     1
B2NWA     1
B308E     1
B30BE     1
B30EE     1
B3E6P     1
B3G6P     1
B4MBE     1
BA3BB     1
BA3BE     1
BA8CD     1
BAAAG     1
BAABG     1
BACEK     1
BADBA     1
BAMDE     1
BAYV5     1
BB03E     1
BB08E     1
B622K     1
B674K     1
B6RFV     1
B7A2J     1
B89HE     1
80000     1
80003     1
80008     1
80015     1
80025     1
80042     1
80054     1
80063     1
80078     1
80095     1
80097     1
80125     1
72AEA     1
72AEB     1
BA30K     1
BA32K     1
BCE1K     1
BCE6J     1
BCELK     1
BB0BB     1
BB0CE     1
BB12E     1
BB3JE     1
BB42E     1
BB71J     1
BB8CD     1
BB9BE     1
BB9JE     1
BBBEX     1
BBDEE     1
BA2A9     1
7LHEP     1
BD337     1
BD33V     1
BD35V     1
BD74K     1
BD9EV     1
BD9FJ     1
BDF1J     1
BDIEB     1
BBE32     1
BBN2A     1
BBRCH     1
BBSHE     1
BC11E     1
BC42R     1
BC53L     1
BC81S     1
72EEB     1
72SC1     1
72SK1     1
72SV1     1
73FM4     1
75106     1
79YND     1
7CNFU     1
7FNFU     1
65910     1
65933     1
BD0FA     1
BD1EB     1
BD23S     1
BD317     1
BD32V     1
BF0BE     1
BF12B     1
BF12K     1
BDMHE     1
BDOES     1
BE23K     1
BE24K     1
BE36K     1
BE38K     1
BE3EK     1
BE40E     1
BE42J     1
BE42k     1
BE44K     1
BD0CT     1
72EEA     1
6H20V     1
6JKFW     1
6N87R     1
6W923     1
71000     1
715C1     1
61524     1
62101     1
BE4EE     1
BE4GK     1
BE6CS     1
BE85B     1
BE9B3     1
BE9FK     1
BE9HE     1
BECEK     1
BF9C3     1
BF9FR     1
BF18B     1
BF28B     1
BF28K     1
BF31V     1
BF32V     1
BF32X     1
BF33V     1
BF35V     1
65934     1
6AE3C     1
6D32M     1
6D52M     1
6D54M     1
6E52M     1
BFREV     1
BFTFK     1
BG12K     1
BG17K     1
BH2AW     1
BH96S     1
BHJ6S     1
BJ13E     1
BF3FK     1
BF3HK     1
BF3JE     1
BF46K     1
BF4DV     1
BF5C2     1
BF6C3     1
BF8C3     1
63AL5     1
64AEB     1
64EEB     1
64STL     1
65200     1
65203     1
65204     1
65213     1
65553     1
65610     1
65620     1
65651     1
65805     1
53XK2     1
543AV     1
BFIFK     1
BK4DV     1
BJ18U     1
BJ22K     1
BJ335     1
BJE23     1
BJI3E     1
BJRBZ     1
BK1E8     1
BK22C     1
BK23C     1
BK262     1
BK29J     1
BK31V     1
BK326     1
BF9JE     1
63AL4     1
BL4A9     1
BL8HE     1
BL9HF     1
BLGHE     1
BLIHK     1
BLSHE     1
BK32V     1
BK33V     1
BK34V     1
BK35B     1
BK35V     1
BK368     1
BK3BB     1
BK3DB     1
BK3EH     1
BK42K     1
BM82F     1
BN30F     1
BN36F     1
BN441     1
BPRBE     1
BPRHE     1
BPWDG     1
BR12E     1
BR18E     1
BK4SK     1
BKIEB     1
BL00E     1
BL0HE     1
BL293     1
BL40E     1
BL42E     1
54EEA     1
56EZZ     1
56N8U     1
58557     1
59695     1
5AFKG     1
5C3AV     1
5D3BV     1
5DDDD     1
5WRFV     1
5X23P     1
60019     1
60023     1
52EEB     1
52ZEB     1
BM29J     1
BT69Y     1
BT903     1
BT923     1
BR22F     1
BR28E     1
BR30E     1
BR406     1
BR40E     1
BR42E     1
BR43E     1
BR9FJ     1
BRKEC     1
BRZ3E     1
BT05Y     1
BM000     1
543BV     1
BU253     1
BU258     1
BU26J     1
BU29J     1
BU300     1
BT17R     1
BT223     1
BT2MW     1
BT3AA     1
BT3AB     1
BT44A     1
BT48A     1
BT4K3     1
BT541     1
BT581     1
BT64A     1
535K2     1
53AFB     1
53EE8     1
53EEB     1
53JSF     1
53SK1     1
53SV2     1
53XH1     1
51426     1
51452     1
BT9K3     1
BU&CD     1
BU01F     1
BU11E     1
BU11J     1
BU250     1
BV426     1
BV541     1
BV581     1
BV61E     1
BU3AE     1
BU3EJ     1
BU40E     1
BU4BF     1
BU585     1
BU5IF     1
BU5JR     1
BU8F5     1
BU8FS     1
BUBFS     1
BUIIF     1
534K2     1
BW541     1
BW581     1
BW5F1     1
BW5G1     1
BW6F3     1
BW923     1
BUJFJ     1
BUL1F     1
BURHE     1
BURNE     1
BUSCD     1
BUSFJ     1
BUSFS     1
BUT1F     1
BUTIF     1
BUTTF     1
BXBCD     1
BY11F     1
BY30E     1
BY32E     1
BY5F1     1
BY5G1     1
BY64A     1
BY67A     1
BVV13     1
BVV92     1
BW023     1
BW123     1
BW133     1
BW1GG     1
BW23E     1
BW3FV     1
51622     1
51658     1
51680     1
51908     1
51940     1
51972     1
525AN     1
52AEA     1
52EEA     1
50871     1
50873     1
BW9F3     1
BW9F4     1
BX3FJ     1
BX8C0     1
BX9F1     1
BY809     1
BY84A     1
BY99J     1
BYBDE     1
BZ1FB     1
BZ1HK     1
BZ42F     1
BZ4ZE     1
BZ9F3     1
BZAHK     1
BW933     1
51488     1
51500     1
51573     1
51611     1
51620     1
CBAGA     1
CC13C     1
CC1BR     1
CC1CX     1
C08RW     1
C1RFV     1
C21FB     1
C25AN     1
C31AK     1
C4MBE     1
C4RBE     1
C616Z     1
C618X     1
C74C4     1
C8E2H     1
BY68A     1
CIRFV     1
CJ6B1     1
CJE73     1
CK12G     1
CL968     1
CA217     1
CA21A     1
CA30P     1
CA31A     1
CA38P     1
CA50A     1
CAAAG     1
CAAGA     1
CB09J     1
CB337     1
CB3FV     1
CU09J     1
CU18R     1
CU1BR     1
CU923     1
CV12G     1
CV1F4     1
CV52B     1
CC42H     1
CDUD2     1
CE22P     1
CE38P     1
CF22P     1
CF28P     1
CG12K     1
CGE23     1
CH5CP     1
CW8C8     1
CW8CB     1
CW8CD     1
CW9CB     1
CW9CD     1
CX0CD     1
CX126     1
CX12G     1
CM565     1
CP450     1
CP515     1
CP724     1
CPA50     1
CRKEC     1
CS12G     1
CT05J     1
CX6CB     1
CX6CD     1
CX8C8     1
CX8CB     1
CX8EM     1
CX8GS     1
CX9C8     1
CX9CB     1
CV541     1
CW126     1
CW12G     1
CW5F1     1
CW6C8     1
CW6CB     1
CW6CD     1
CW8BB     1
51102     1
51109     1
51116     1
51147     1
51149     1
51189     1
51211     1
51267     1
51303     1
51382     1
51390     1
50287     1
50296     1
CX196     1
CX19G     1
CX3DD     1
CXBEM     1
CXI9G     1
CY5F1     1
CY7AJ     1
CZRAH     1
D13FV     1
D156F     1
D1RFV     1
D23DC     1
D258N     1
D2DF6     1
D4MBE     1
D4RBE     1
CX190     1
50954     1
51067     1
DBR22     1
D541A     1
D6RFV     1
D89CD     1
DA1AB     1
DA31A     1
DAAAG     1
DAABG     1
DAACK     1
DAR9K     1
DARTK     1
DB0A0     1
DB0AO     1
DB0C0     1
DB0E0     1
DB12E     1
DF4DV     1
DF4EB     1
DB21B     1
DB24B     1
DB2A0     1
DB2C0     1
DB41S     1
DB4C0     1
DB6CD     1
DB8CD     1
DB8FS     1
DB9CB     1
DB9CD     1
DBADK     1
DBE32     1
DBOE0     1
DK3DC     1
DK4CC     1
DK4DV     1
DBSCD     1
DBWG3     1
DBYSV     1
DCRFH     1
DD21A     1
DD22S     1
DD23S     1
DD2EY     1
DD82A     1
DE32K     1
DE4EV     1
DE626     1
DE82A     1
DM626     1
DN56A     1
DPMAE     1
DPRAE     1
DS41A     1
DS43A     1
DF4EU     1
DFAEV     1
DFREV     1
DG61E     1
DGRFH     1
DH4CD     1
DH88W     1
DH88X     1
DJ81W     1
DJREV     1
DTPUK     1
DU09J     1
DU09T     1
DV09J     1
DV541     1
DV581     1
DW3FV     1
DW51E     1
DW541     1
DKJA0     1
DKW9D     1
DL25R     1
DL39M     1
DLBJV     1
DLBYV     1
DM5F1     1
DX1H2     1
DX226     1
DX22G     1
DX6CB     1
DX6CD     1
DX8CD     1
DX8F5     1
DX8FS     1
DX9CB     1
DX9CD     1
DXBCD     1
DSKFC     1
DT3MW     1
DT441     1
DT481     1
DT541     1
DY5F1     1
DYSF1     1
DZ1FB     1
DZ3DC     1
DZ626     1
DZK23     1
DZRBH     1
DZRFH     1
DZSBN     1
E1EE0     1
E1NFJ     1
DW5F1     1
DW5G1     1
DW923     1
DWRFV     1
DWSF1     1
E6A3U     1
E6RFV     1
E8017     1
EA6BX     1
EAAAG     1
EAMDE     1
EB02E     1
EB0BE     1
EB13E     1
EB71J     1
EB73J     1
EBOBE     1
EBRBE     1
DXBFS     1
DY32T     1
DY38T     1
50470     1
50479     1
50500     1
50501     1
50504     1
50524     1
50531     1
50602     1
50617     1
50637     1
50671     1
50812     1
45612     1
46405     1
E29F3     1
E4FDB     1
EC42E     1
ECABA     1
ED1EK     1
ED31V     1
ED3KA     1
ED9HP     1
EDABB     1
EE32K     1
EE426     1
EE9HE     1
EF12K     1
EF4HK     1
EF76A     1
E2815     1
50333     1
50391     1
EF8C3     1
EF8CF     1
EF9FK     1
EFABF     1
EFAVS     1
EFBBF     1
EFBC3     1
EFBCF     1
EFHCF     1
EFSBF     1
EG12K     1
EG21K     1
EG23K     1
EG425     1
EG426     1
EBRCH     1
EGCBB     1
EJ13E     1
EJ5CD     1
EK12G     1
EK12T     1
EK19T     1
EL33P     1
EM426     1
EM42G     1
EM496     1
EM5F1     1
EN61S     1
ENE0R     1
ENKA5     1
EPMAE     1
EPRAE     1
EWIE5     1
EWRFV     1
ER21E     1
ER22E     1
ER33P     1
ER42E     1
ES41A     1
ES43A     1
ES46A     1
ET341     1
ET381     1
ET923     1
ET9F3     1
EU11F     1
EU3FJ     1
EU5JR     1
EZ28E     1
EZ3DC     1
EZ426     1
EZ42E     1
EU73J     1
EV541     1
EV581     1
EV73J     1
EW126     1
EW12G     1
EW1EP     1
EW21A     1
EW22E     1
EW41A     1
EW5F1     1
EW923     1
FA903     1
FARAH     1
FB718     1
FBABG     1
FBW41     1
EX120     1
EX126     1
EX12G     1
EX196     1
EX1E6     1
EX22G     1
EX28E     1
EX91G     1
EY5F1     1
EY64A     1
EZ20E     1
FDABB     1
FE22P     1
FE53S     1
FE54S     1
FF22P     1
FF41C     1
FF719     1
FG15T     1
EZ496     1
F11AK     1
F11BK     1
F31AK     1
F6RDM     1
F7D19     1
FA119     1
FA38P     1
50012     1
50017     1
50018     1
50061     1
50090     1
50189     1
50229     1
50237     1
50258     1
408B0     1
41500     1
FC24H     1
FC518     1
FD3HL     1
FDA88     1
FDAB8     1
FG426     1
FG8JP     1
FH3CB     1
FIRFV     1
FJ60G     1
FJ60V     1
FJ71J     1
FK122     1
FK718     1
FP14F     1
FP518     1
FPEFF     1
46407     1
46475     1
472AX     1
4E181     1
G13FV     1
G14DA     1
G1RFV     1
FPMAE     1
FPRAE     1
FR119     1
FR226     1
FR22G     1
FR73J     1
FU5JR     1
FV47V     1
FW12G     1
FX00G     1
FX02P     1
FX226     1
FX22C     1
GARAH     1
GBKFW     1
GBRCH     1
GD20V     1
GD21A     1
GD32M     1
FX22G     1
FX22P     1
FY5A1     1
FY5B1     1
FY5F1     1
FZ1FB     1
FZ29G     1
FZ418     1
FZRBH     1
G0EE9     1
GG25K     1
GGG56     1
GH20V     1
GJ211     1
GK12E     1
GK13E     1
GK26H     1
G31AK     1
G4AC1     1
G4BC1     1
G5GC1     1
G622K     1
G6X40     1
GA17E     1
GA17F     1
GA17H     1
GS54M     1
GSKFC     1
GU09J     1
GU4L3     1
GW5F1     1
GX72A     1
GX8CD     1
GX8EM     1
GXSEM     1
GD34M     1
GD52M     1
GD54M     1
GE17F     1
GES2M     1
GF46X     1
GF4JB     1
GZRAH     1
GZRBH     1
H0093     1
H009J     1
H109J     1
H1RFV     1
H25ZZ     1
H3093     1
H309J     1
H4BCP     1
H545G     1
GN86R     1
GNP03     1
GP10V     1
GR4A6     1
GRKEC     1
HAP5J     1
HAP73     1
HB10V     1
HB8CD     1
HB9CP     1
HC05J     1
HD20V     1
HD21A     1
HD23S     1
HDAAA     1
HEJ1F     1
HF10U     1
HG09G     1
GY5F1     1
GZ1FB     1
GZ5AN     1
41502     1
41503     1
41504     1
41BB4     1
41CB8     1
41E96     1
41UB5     1
41UHB     1
42010     1
42014     1
42015     1
42018     1
33YN8     1
35000     1
HA3CD     1
HAP53     1
HT093     1
HG39K     1
HH20V     1
HJ01J     1
HJ05J     1
HJ08J     1
HJ091     1
HJ093     1
HJ0SJ     1
HJ59J     1
HJ85J     1
HJO9J     1
HJQ8J     1
HJXEN     1
HK31U     1
41501     1
HU5JR     1
HU8CD     1
HUD3J     1
HUD9J     1
HUOTJ     1
HV01J     1
HNICP     1
HNP13     1
HNP6N     1
HNW6N     1
HPRAE     1
HR33N     1
HS02P     1
HT051     1
HT053     1
HT06J     1
HX02J     1
HX05J     1
HX07P     1
HX091     1
HX093     1
HX09J     1
HX0IJ     1
HT09J     1
HT0SJ     1
HT523     1
HTO5J     1
HTOSJ     1
HU01J     1
HU08J     1
HU091     1
HU093     1
HXO2P     1

In [231]:
df_clean["vds"] = (
    df_clean["chassisNumber"]
    .astype(str)
    .str[3:8]
)

In [232]:
(
    df_clean[df_clean["make"] == "TOYOTA"]
    .groupby("vds")["model"]
    .nunique()
    .sort_values(ascending=False)
)

vds
LJ73J    10
LU73J    10
JJXB0     8
BT441     5
AG34L     5
EF8BF     5
NX22N     5
PBEJA     5
A180C     5
M8500     5
JX02P     5
ZD31V     4
AACAJ     4
AAAAA     4
FU71J     4
BU71J     4
BT14R     4
BR32E     4
BR22E     4
BL9HE     4
BB0BE     4
71SC1     4
LB71J     4
LJ71J     4
KARJE     4
LU71J     4
11111     4
A14CK     4
A4DAA     4
ZU14R     4
A4B3A     3
AA9AJ     3
14252     3
ZF13C     3
B519E     3
B3J6P     3
BB02E     3
BB9HE     3
BC42E     3
BBOBE     3
BD1FK     3
79END     3
BE32K     3
BF0JE     3
BE6DS     3
BE6BS     3
BF9FK     3
BG22K     3
BJ53L     3
PAEHD     3
PX4EN     3
PX22P     3
PM62N     3
BPB9E     3
BM99J     3
BT481     3
BU25J     3
BU17R     3
BU14R     3
BU9FJ     3
BU3FJ     3
BV71J     3
BX9FJ     3
BZ42E     3
MF53F     3
21608     3
MX83E     3
MX73E     3
MU4FN     3
NM92N     3
NX4CN     3
1BAA3     3
CECB8     3
CX3FJ     3
D3135     3
CZ5AN     3
DR32T     3
EX19G     3
FM518     3
FM418     3
ML110     3
FK418     3
GE52M     3
44925     3
HX02P     3
K4MBE     3
KARFP     3
KD3B3     3
TX22N     3
VB9E7     3
VL52N     3
11VJ9     3
KK3DC     3
KHMBX     3
KRKEC     3
KR30E     3
KW73J     3
ZCP2F     3
ZU5JR     3
00000     3
A4CFA     3
YK3DC     3
YMLA2     3
ACAAU     3
ZA3BB     2
ZA22C     2
10252     2
ZCP2H     2
AL29J     2
AG4CK     2
ARE0C     2
AP86C     2
15100     2
14270     2
UCK1H     2
TX4CN     2
8L9HE     2
8W23E     2
AE52S     2
AFAAF     2
KN36U     2
KU4EE     2
KT9F3     2
KX6CB     2
KW923     2
L11AK     2
KZ3DC     2
A11CX     2
A4GF5     2
ZCN1F     2
ZCK1H     2
ZK31V     2
ZFREV     2
ZK22C     2
889HE     2
880CE     2
UU4EN     2
VB9E6     2
V0LEZ     2
W13FV     2
WA37R     2
12005     2
12003     2
12001     2
WG81R     2
XE4FS     2
KC20F     2
KK4CC     2
KDTB3     2
KT441     2
KSKFC     2
KR32E     2
JM11D     2
JU3FJ     2
JU9FJ     2
JX8CB     2
K61AK     2
K43BE     2
JY5G1     2
KAMFU     2
KAAAG     2
KB8CD     2
KB20U     2
32BUM     2
31UJ7     2
KCAAG     2
UF117     2
UX4EN     2
H4ACP     2
GZ3DH     2
HD17F     2
HJ09J     2
HG17C     2
HT05J     2
HP10V     2
HN9CP     2
HN87R     2
HN86R     2
HU09J     2
HW2ZZ     2
J13FV     2
JA82J     2
JK3DC     2
JNK64     2
LV73J     2
LU733     2
MD351     2
MD121     2
MC13F     2
MA71J     2
MF929     2
FU73J     2
FR320     2
G11BK     2
G11AK     2
FY418     2
G4X20     2
GJKFW     2
GP21A     2
GN87R     2
EW23E     2
FB518     2
F1RFV     2
FE728     2
FE718     2
FE52S     2
46470     2
FK518     2
LDHAD     2
LB5JN     2
LA5DB     2
LU4EN     2
LU42N     2
LMFCP     2
M11AK     2
LY3FX     2
DB4A0     2
DBZSV     2
DK3EH     2
DF9EV     2
DF4EV     2
DP21A     2
DN136     2
DW12S     2
DW11S     2
DZ5BN     2
DY5G1     2
EF88F     2
EG22K     2
ES12G     2
ER23E     2
EW44A     2
BY879     2
BY80E     2
C916Z     2
C2ZWB     2
C11BK     2
C11AK     2
BZRFH     2
CAABG     2
CJE23     2
CS18Z     2
CX9FJ     2
CX9CD     2
CX8CD     2
50975     2
D3DF6     2
DB0G0     2
BU8CD     2
BU4EE     2
BV42E     2
BW22E     2
BW12S     2
BX8CD     2
BZ4HK     2
BZ28E     2
21610     2
21606     2
21604     2
MU52N     2
PAAWA     2
P6X40     2
1201D     2
1CU83     2
RX12P     2
SS1EK     2
17100     2
BKRFH     2
BPMBE     2
BN95J     2
BT123     2
BR38E     2
BR23E     2
BU11F     2
53SK2     2
53EL5     2
53EEA     2
53AEB     2
53AEA     2
BT9F3     2
BK1EB     2
BK4FK     2
BK46K     2
BK40K     2
BK3EK     2
BK36B     2
BL29J     2
PG34L     2
PCKL9     2
PBEHD     2
PBEFA     2
PBAJA     2
PX42N     2
RC1BG     2
R1CS9     2
RX5GN     2
BF31E     2
BF30K     2
BF23K     2
BF22K     2
BF1FK     2
BF9HK     2
BF9EV     2
BF4HK     2
BF4FK     2
BF3EK     2
BH9FJ     2
BH42K     2
BG28K     2
BG23K     2
BG21K     2
BK1FK     2
BC74K     2
BBOCE     2
BD31V     2
7ENFU     2
7ANFU     2
72SK2     2
BE42K     2
BE40K     2
BE33K     2
BE30K     2
BE6AS     2
66B3D     2
BE46K     2
BF38K     2
BF32K     2
BF31F     2
B29HK     2
B24HK     2
B19HK     2
B14HK     2
B4B9E     2
B3FE1     2
B31HK     2
BA02E     2
BA01E     2
B61HK     2
BAOBE     2
80001     2
BB46K     2
BB3EK     2
BB13E     2
BCE1J     2
AF4E3     2
AECB8     2
AEACH     2
WN72N     2
XZ3DC     2
XX43G     2
AP22C     2
AN95J     2
AU25J     2
ASW0A     2
ASB3R     2
AS02D     2
AS02A     2
B11HK     2
AZ5CN     2
B2E6K     2
8URHE     2
8U40E     2
8U3FJ     2
95403     2
94403     2
91903     2
8X9FJ     2
ACABF     2
A4B2A     2
A4CEA     2
AAABG     2
AAA0C     2
ABBBJ     2
AB1BY     2
ZN3EU     2
ZBB2K     2
8CE1K     2
8CCVD     2
8R22E     2
XX42G     2
YH20V     2
YD3EV     2
YZRFH     2
YZ3DC     2
ZN128     2
ZK3DC     2
06XZZ     2
ZT14R     2
ZNBF1     2
ZU17R     2
ZZRFH     2
ZK23C     2
ZNBB1     1
00ACV     1
00968     1
00943     1
00898     1
00856     1
00800     1
00713     1
00612     1
01111     1
01302     1
01BUM     1
02290     1
022GD     1
03350     1
042TN     1
06622     1
0B9CB     1
0J4MC     1
ZNAA1     1
ZNAE1     1
ZK32V     1
ZK33V     1
ZK34V     1
ZK4CC     1
8622K     1
8628K     1
87367     1
87N07     1
8808E     1
8842E     1
8846K     1
88OCE     1
8A02E     1
8A08E     1
80890     1
80893     1
ZU4BF     1
ZV42E     1
ZX69G     1
ZY0CC     1
8A32K     1
8B9HE     1
8BCE1     1
8C42E     1
8D1FK     1
8D31V     1
8D33V     1
8D35E     1
8E30K     1
8E32K     1
8E33K     1
8E42K     1
824HK     1
829F3     1
829HK     1
855HZ     1
8F22K     1
8F28K     1
8F30K     1
8F31F     1
8F32K     1
8F38K     1
8F3EK     1
8F4DV     1
8F4FK     1
8F4HK     1
8F9C3     1
8F9EV     1
8F9FK     1
8F9HK     1
8A13E     1
8A23C     1
8G22K     1
8J466     1
8J53L     1
8K1E8     1
8K1FK     1
8K22C     1
8K31V     1
8K32V     1
8K33V     1
8K368     1
8K36B     1
8K3D8     1
8K3DB     1
8K3EK     1
8E46K     1
8F1FK     1
8K40K     1
8K46K     1
8K4FK     1
8L0HE     1
8L29J     1
8N95J     1
8R23E     1
8R32E     1
8R42E     1
8RI2E     1
8T923     1
8T9F3     1
8U11F     1
8U25J     1
8FIFK     1
8FREV     1
91902     1
91908     1
93220     1
95021     1
8U4EE     1
8U5CD     1
8U71J     1
8U8CD     1
8V42E     1
8V541     1
8V71J     1
8W123     1
8W133     1
8W923     1
8W933     1
8W9F3     1
A11CY     1
A14AF     1
A16E3     1
A1809     1
A1ACC     1
A1RFV     1
A22EZ     1
A22NE     1
8X8CD     1
8Y561     1
8Y5F1     1
8Y64A     1
8Z4HK     1
90615     1
91900     1
91901     1
80943     1
80950     1
80951     1
80986     1
80987     1
81018     1
811EB     1
811HK     1
813FV     1
814HK     1
819F3     1
819HK     1
8242E     1
80473     1
80506     1
A11AK     1
AABAJ     1
A4B5A     1
A4DAC     1
A4DBA     1
A4DF5     1
A4DMA     1
A4MBE     1
A4RBE     1
A6426     1
A818Y     1
A878J     1
A888J     1
AA18A     1
9FD8T     1
A0B98     1
80907     1
AB1BA     1
AB36U     1
AB7BJ     1
AB7RJ     1
ABBAA     1
AA1AB     1
AA1BA     1
AA5RX     1
AA7BJ     1
AAAA5     1
AAAAF     1
AAAAG     1
AAAB5     1
AAABA     1
AAADC     1
AAAOC     1
AC1DM     1
AC22C     1
AC7BJ     1
ACAAJ     1
ACAB5     1
ACABA     1
ACABB     1
ACJ4H     1
AABBJ     1
AACBJ     1
AAIBA     1
AALAJ     1
AAN6E     1
AATBA     1
AAYAJ     1
AB18Y     1
AE07B     1
AE09B     1
AE09E     1
AE09V     1
AE09W     1
AE1BY     1
AE1EY     1
AE2KP     1
AE51S     1
AE525     1
AE53S     1
ABBDH     1
ABCBJ     1
ABFAJ     1
ABIBY     1
AC11R     1
80558     1
80583     1
80593     1
80636     1
80700     1
80761     1
80767     1
80772     1
80839     1
80850     1
80876     1
80183     1
801FK     1
AE00E     1
AE04B     1
AE04E     1
AE54S     1
AE82G     1
AE94A     1
AE94K     1
AEAA1     1
AECG2     1
AECG3     1
AF047     1
AF4CB     1
AF54K     1
AFABF     1
AFCG2     1
AE00B     1
80532     1
80533     1
80548     1
AR9AJ     1
ARCAJ     1
ARE2C     1
AFZBG     1
AG20A     1
AG30A     1
AG426     1
AGACH     1
AGNAC     1
AI4CK     1
AJ54K     1
AK54K     1
AKCB8     1
AL1CC     1
AM11H     1
AM29J     1
ASACK     1
ASG0A     1
AT123     1
AT2MV     1
AU78J     1
AU7BJ     1
AU88J     1
AM2AH     1
AM450     1
AM496     1
AM498     1
AN74K     1
AP54K     1
AP90A     1
APE2C     1
AR05Y     1
AUTBJ     1
AUZBJ     1
AVV5F     1
AW126     1
AW12G     1
AW5F1     1
AX126     1
AX12G     1
AX5GN     1
AX8CD     1
AXACC     1
AY117     1
AS123     1
AS12G     1
AS14U     1
AS47H     1
AY86C     1
AYACC     1
AYT30     1
AZ1FB     1
AZ496     1
B0111     1
B011F     1
B025J     1
B031V     1
B03FV     1
B046K     1
B13FV     1
AUBB3     1
AUBBJ     1
AUCBJ     1
AUF0A     1
80251     1
80274     1
80281     1
80282     1
80318     1
80328     1
80345     1
80350     1
80407     1
80413     1
80430     1
80459     1
80464     1
7JNFU     1
7KE43     1
AY5F1     1
B4MDE     1
B4MEE     1
B4RBE     1
B19F3     1
B1B0E     1
B1DWA     1
B1RFV     1
B21FB     1
B21HK     1
B23HK     1
B242E     1
B28F3     1
B29F3     1
B29M3     1
AY2NY     1
80233     1
BA03E     1
BA05E     1
BA0BE     1
BA13E     1
BA1HK     1
BA22C     1
BA23C     1
BA244     1
B2NBA     1
B2NWA     1
B308E     1
B30BE     1
B30EE     1
B3E6P     1
B3G6P     1
B4MBE     1
BA3BB     1
BA3BE     1
BA8CD     1
BAAAG     1
BAABG     1
BACEK     1
BADBA     1
BAMDE     1
BAYV5     1
BB03E     1
BB08E     1
B622K     1
B674K     1
B6RFV     1
B7A2J     1
B89HE     1
80000     1
80003     1
80008     1
80015     1
80025     1
80042     1
80054     1
80063     1
80078     1
80095     1
80097     1
80125     1
72AEA     1
72AEB     1
BA30K     1
BA32K     1
BCE1K     1
BCE6J     1
BCELK     1
BB0BB     1
BB0CE     1
BB12E     1
BB3JE     1
BB42E     1
BB71J     1
BB8CD     1
BB9BE     1
BB9JE     1
BBBEX     1
BBDEE     1
BA2A9     1
7LHEP     1
BD337     1
BD33V     1
BD35V     1
BD74K     1
BD9EV     1
BD9FJ     1
BDF1J     1
BDIEB     1
BBE32     1
BBN2A     1
BBRCH     1
BBSHE     1
BC11E     1
BC42R     1
BC53L     1
BC81S     1
72EEB     1
72SC1     1
72SK1     1
72SV1     1
73FM4     1
75106     1
79YND     1
7CNFU     1
7FNFU     1
65910     1
65933     1
BD0FA     1
BD1EB     1
BD23S     1
BD317     1
BD32V     1
BF0BE     1
BF12B     1
BF12K     1
BDMHE     1
BDOES     1
BE23K     1
BE24K     1
BE36K     1
BE38K     1
BE3EK     1
BE40E     1
BE42J     1
BE42k     1
BE44K     1
BD0CT     1
72EEA     1
6H20V     1
6JKFW     1
6N87R     1
6W923     1
71000     1
715C1     1
61524     1
62101     1
BE4EE     1
BE4GK     1
BE6CS     1
BE85B     1
BE9B3     1
BE9FK     1
BE9HE     1
BECEK     1
BF9C3     1
BF9FR     1
BF18B     1
BF28B     1
BF28K     1
BF31V     1
BF32V     1
BF32X     1
BF33V     1
BF35V     1
65934     1
6AE3C     1
6D32M     1
6D52M     1
6D54M     1
6E52M     1
BFREV     1
BFTFK     1
BG12K     1
BG17K     1
BH2AW     1
BH96S     1
BHJ6S     1
BJ13E     1
BF3FK     1
BF3HK     1
BF3JE     1
BF46K     1
BF4DV     1
BF5C2     1
BF6C3     1
BF8C3     1
63AL5     1
64AEB     1
64EEB     1
64STL     1
65200     1
65203     1
65204     1
65213     1
65553     1
65610     1
65620     1
65651     1
65805     1
53XK2     1
543AV     1
BFIFK     1
BK4DV     1
BJ18U     1
BJ22K     1
BJ335     1
BJE23     1
BJI3E     1
BJRBZ     1
BK1E8     1
BK22C     1
BK23C     1
BK262     1
BK29J     1
BK31V     1
BK326     1
BF9JE     1
63AL4     1
BL4A9     1
BL8HE     1
BL9HF     1
BLGHE     1
BLIHK     1
BLSHE     1
BK32V     1
BK33V     1
BK34V     1
BK35B     1
BK35V     1
BK368     1
BK3BB     1
BK3DB     1
BK3EH     1
BK42K     1
BM82F     1
BN30F     1
BN36F     1
BN441     1
BPRBE     1
BPRHE     1
BPWDG     1
BR12E     1
BR18E     1
BK4SK     1
BKIEB     1
BL00E     1
BL0HE     1
BL293     1
BL40E     1
BL42E     1
54EEA     1
56EZZ     1
56N8U     1
58557     1
59695     1
5AFKG     1
5C3AV     1
5D3BV     1
5DDDD     1
5WRFV     1
5X23P     1
60019     1
60023     1
52EEB     1
52ZEB     1
BM29J     1
BT69Y     1
BT903     1
BT923     1
BR22F     1
BR28E     1
BR30E     1
BR406     1
BR40E     1
BR42E     1
BR43E     1
BR9FJ     1
BRKEC     1
BRZ3E     1
BT05Y     1
BM000     1
543BV     1
BU253     1
BU258     1
BU26J     1
BU29J     1
BU300     1
BT17R     1
BT223     1
BT2MW     1
BT3AA     1
BT3AB     1
BT44A     1
BT48A     1
BT4K3     1
BT541     1
BT581     1
BT64A     1
535K2     1
53AFB     1
53EE8     1
53EEB     1
53JSF     1
53SK1     1
53SV2     1
53XH1     1
51426     1
51452     1
BT9K3     1
BU&CD     1
BU01F     1
BU11E     1
BU11J     1
BU250     1
BV426     1
BV541     1
BV581     1
BV61E     1
BU3AE     1
BU3EJ     1
BU40E     1
BU4BF     1
BU585     1
BU5IF     1
BU5JR     1
BU8F5     1
BU8FS     1
BUBFS     1
BUIIF     1
534K2     1
BW541     1
BW581     1
BW5F1     1
BW5G1     1
BW6F3     1
BW923     1
BUJFJ     1
BUL1F     1
BURHE     1
BURNE     1
BUSCD     1
BUSFJ     1
BUSFS     1
BUT1F     1
BUTIF     1
BUTTF     1
BXBCD     1
BY11F     1
BY30E     1
BY32E     1
BY5F1     1
BY5G1     1
BY64A     1
BY67A     1
BVV13     1
BVV92     1
BW023     1
BW123     1
BW133     1
BW1GG     1
BW23E     1
BW3FV     1
51622     1
51658     1
51680     1
51908     1
51940     1
51972     1
525AN     1
52AEA     1
52EEA     1
50871     1
50873     1
BW9F3     1
BW9F4     1
BX3FJ     1
BX8C0     1
BX9F1     1
BY809     1
BY84A     1
BY99J     1
BYBDE     1
BZ1FB     1
BZ1HK     1
BZ42F     1
BZ4ZE     1
BZ9F3     1
BZAHK     1
BW933     1
51488     1
51500     1
51573     1
51611     1
51620     1
CBAGA     1
CC13C     1
CC1BR     1
CC1CX     1
C08RW     1
C1RFV     1
C21FB     1
C25AN     1
C31AK     1
C4MBE     1
C4RBE     1
C616Z     1
C618X     1
C74C4     1
C8E2H     1
BY68A     1
CIRFV     1
CJ6B1     1
CJE73     1
CK12G     1
CL968     1
CA217     1
CA21A     1
CA30P     1
CA31A     1
CA38P     1
CA50A     1
CAAAG     1
CAAGA     1
CB09J     1
CB337     1
CB3FV     1
CU09J     1
CU18R     1
CU1BR     1
CU923     1
CV12G     1
CV1F4     1
CV52B     1
CC42H     1
CDUD2     1
CE22P     1
CE38P     1
CF22P     1
CF28P     1
CG12K     1
CGE23     1
CH5CP     1
CW8C8     1
CW8CB     1
CW8CD     1
CW9CB     1
CW9CD     1
CX0CD     1
CX126     1
CX12G     1
CM565     1
CP450     1
CP515     1
CP724     1
CPA50     1
CRKEC     1
CS12G     1
CT05J     1
CX6CB     1
CX6CD     1
CX8C8     1
CX8CB     1
CX8EM     1
CX8GS     1
CX9C8     1
CX9CB     1
CV541     1
CW126     1
CW12G     1
CW5F1     1
CW6C8     1
CW6CB     1
CW6CD     1
CW8BB     1
51102     1
51109     1
51116     1
51147     1
51149     1
51189     1
51211     1
51267     1
51303     1
51382     1
51390     1
50287     1
50296     1
CX196     1
CX19G     1
CX3DD     1
CXBEM     1
CXI9G     1
CY5F1     1
CY7AJ     1
CZRAH     1
D13FV     1
D156F     1
D1RFV     1
D23DC     1
D258N     1
D2DF6     1
D4MBE     1
D4RBE     1
CX190     1
50954     1
51067     1
DBR22     1
D541A     1
D6RFV     1
D89CD     1
DA1AB     1
DA31A     1
DAAAG     1
DAABG     1
DAACK     1
DAR9K     1
DARTK     1
DB0A0     1
DB0AO     1
DB0C0     1
DB0E0     1
DB12E     1
DF4DV     1
DF4EB     1
DB21B     1
DB24B     1
DB2A0     1
DB2C0     1
DB41S     1
DB4C0     1
DB6CD     1
DB8CD     1
DB8FS     1
DB9CB     1
DB9CD     1
DBADK     1
DBE32     1
DBOE0     1
DK3DC     1
DK4CC     1
DK4DV     1
DBSCD     1
DBWG3     1
DBYSV     1
DCRFH     1
DD21A     1
DD22S     1
DD23S     1
DD2EY     1
DD82A     1
DE32K     1
DE4EV     1
DE626     1
DE82A     1
DM626     1
DN56A     1
DPMAE     1
DPRAE     1
DS41A     1
DS43A     1
DF4EU     1
DFAEV     1
DFREV     1
DG61E     1
DGRFH     1
DH4CD     1
DH88W     1
DH88X     1
DJ81W     1
DJREV     1
DTPUK     1
DU09J     1
DU09T     1
DV09J     1
DV541     1
DV581     1
DW3FV     1
DW51E     1
DW541     1
DKJA0     1
DKW9D     1
DL25R     1
DL39M     1
DLBJV     1
DLBYV     1
DM5F1     1
DX1H2     1
DX226     1
DX22G     1
DX6CB     1
DX6CD     1
DX8CD     1
DX8F5     1
DX8FS     1
DX9CB     1
DX9CD     1
DXBCD     1
DSKFC     1
DT3MW     1
DT441     1
DT481     1
DT541     1
DY5F1     1
DYSF1     1
DZ1FB     1
DZ3DC     1
DZ626     1
DZK23     1
DZRBH     1
DZRFH     1
DZSBN     1
E1EE0     1
E1NFJ     1
DW5F1     1
DW5G1     1
DW923     1
DWRFV     1
DWSF1     1
E6A3U     1
E6RFV     1
E8017     1
EA6BX     1
EAAAG     1
EAMDE     1
EB02E     1
EB0BE     1
EB13E     1
EB71J     1
EB73J     1
EBOBE     1
EBRBE     1
DXBFS     1
DY32T     1
DY38T     1
50470     1
50479     1
50500     1
50501     1
50504     1
50524     1
50531     1
50602     1
50617     1
50637     1
50671     1
50812     1
45612     1
46405     1
E29F3     1
E4FDB     1
EC42E     1
ECABA     1
ED1EK     1
ED31V     1
ED3KA     1
ED9HP     1
EDABB     1
EE32K     1
EE426     1
EE9HE     1
EF12K     1
EF4HK     1
EF76A     1
E2815     1
50333     1
50391     1
EF8C3     1
EF8CF     1
EF9FK     1
EFABF     1
EFAVS     1
EFBBF     1
EFBC3     1
EFBCF     1
EFHCF     1
EFSBF     1
EG12K     1
EG21K     1
EG23K     1
EG425     1
EG426     1
EBRCH     1
EGCBB     1
EJ13E     1
EJ5CD     1
EK12G     1
EK12T     1
EK19T     1
EL33P     1
EM426     1
EM42G     1
EM496     1
EM5F1     1
EN61S     1
ENE0R     1
ENKA5     1
EPMAE     1
EPRAE     1
EWIE5     1
EWRFV     1
ER21E     1
ER22E     1
ER33P     1
ER42E     1
ES41A     1
ES43A     1
ES46A     1
ET341     1
ET381     1
ET923     1
ET9F3     1
EU11F     1
EU3FJ     1
EU5JR     1
EZ28E     1
EZ3DC     1
EZ426     1
EZ42E     1
EU73J     1
EV541     1
EV581     1
EV73J     1
EW126     1
EW12G     1
EW1EP     1
EW21A     1
EW22E     1
EW41A     1
EW5F1     1
EW923     1
FA903     1
FARAH     1
FB718     1
FBABG     1
FBW41     1
EX120     1
EX126     1
EX12G     1
EX196     1
EX1E6     1
EX22G     1
EX28E     1
EX91G     1
EY5F1     1
EY64A     1
EZ20E     1
FDABB     1
FE22P     1
FE53S     1
FE54S     1
FF22P     1
FF41C     1
FF719     1
FG15T     1
EZ496     1
F11AK     1
F11BK     1
F31AK     1
F6RDM     1
F7D19     1
FA119     1
FA38P     1
50012     1
50017     1
50018     1
50061     1
50090     1
50189     1
50229     1
50237     1
50258     1
408B0     1
41500     1
FC24H     1
FC518     1
FD3HL     1
FDA88     1
FDAB8     1
FG426     1
FG8JP     1
FH3CB     1
FIRFV     1
FJ60G     1
FJ60V     1
FJ71J     1
FK122     1
FK718     1
FP14F     1
FP518     1
FPEFF     1
46407     1
46475     1
472AX     1
4E181     1
G13FV     1
G14DA     1
G1RFV     1
FPMAE     1
FPRAE     1
FR119     1
FR226     1
FR22G     1
FR73J     1
FU5JR     1
FV47V     1
FW12G     1
FX00G     1
FX02P     1
FX226     1
FX22C     1
GARAH     1
GBKFW     1
GBRCH     1
GD20V     1
GD21A     1
GD32M     1
FX22G     1
FX22P     1
FY5A1     1
FY5B1     1
FY5F1     1
FZ1FB     1
FZ29G     1
FZ418     1
FZRBH     1
G0EE9     1
GG25K     1
GGG56     1
GH20V     1
GJ211     1
GK12E     1
GK13E     1
GK26H     1
G31AK     1
G4AC1     1
G4BC1     1
G5GC1     1
G622K     1
G6X40     1
GA17E     1
GA17F     1
GA17H     1
GS54M     1
GSKFC     1
GU09J     1
GU4L3     1
GW5F1     1
GX72A     1
GX8CD     1
GX8EM     1
GXSEM     1
GD34M     1
GD52M     1
GD54M     1
GE17F     1
GES2M     1
GF46X     1
GF4JB     1
GZRAH     1
GZRBH     1
H0093     1
H009J     1
H109J     1
H1RFV     1
H25ZZ     1
H3093     1
H309J     1
H4BCP     1
H545G     1
GN86R     1
GNP03     1
GP10V     1
GR4A6     1
GRKEC     1
HAP5J     1
HAP73     1
HB10V     1
HB8CD     1
HB9CP     1
HC05J     1
HD20V     1
HD21A     1
HD23S     1
HDAAA     1
HEJ1F     1
HF10U     1
HG09G     1
GY5F1     1
GZ1FB     1
GZ5AN     1
41502     1
41503     1
41504     1
41BB4     1
41CB8     1
41E96     1
41UB5     1
41UHB     1
42010     1
42014     1
42015     1
42018     1
33YN8     1
35000     1
HA3CD     1
HAP53     1
HT093     1
HG39K     1
HH20V     1
HJ01J     1
HJ05J     1
HJ08J     1
HJ091     1
HJ093     1
HJ0SJ     1
HJ59J     1
HJ85J     1
HJO9J     1
HJQ8J     1
HJXEN     1
HK31U     1
41501     1
HU5JR     1
HU8CD     1
HUD3J     1
HUD9J     1
HUOTJ     1
HV01J     1
HNICP     1
HNP13     1
HNP6N     1
HNW6N     1
HPRAE     1
HR33N     1
HS02P     1
HT051     1
HT053     1
HT06J     1
HX02J     1
HX05J     1
HX07P     1
HX091     1
HX093     1
HX09J     1
HX0IJ     1
HT09J     1
HT0SJ     1
HT523     1
HTO5J     1
HTOSJ     1
HU01J     1
HU08J     1
HU091     1
HU093     1
HXO2P     1

In [233]:
(
    df_clean
    .groupby(["make", "vds"])["model"]
    .nunique()
    .sort_values(ascending=False)
)

make               vds
HONDA              KC09C    29
BAJAJ              A11CX    29
HONDA              KC40G    27
MERCEDES BENZ      22117    26
                   14005    21
HERO               KCS26    20
SUZUKI             GR7MA    20
HONDA              KC40A    19
                   KC206    19
MERCEDES BENZ      22017    17
VESPA              M8500    17
BAJAJ              A12DZ    16
SUZUKI             DM11G    16
BYD                C76C4    16
SUZUKI             CK111    16
MERCEDES BENZ      BA48D    16
BYD                C74C4    16
HONDA              KC203    15
BYD                CH4CD    15
SUZUKI             GX72B    15
                   GX72A    15
                   EJ11E    15
BYD                FD1C4    14
FORD               XE4FN    14
MERCEDES BENZ      22016    14
SANYA              PCKL9    13
SUZUKI             GT78A    13
FORD               XE4FS    13
LEXUS              GL46F    13
MERCEDES BENZ      22205    13
                   23047    13
MITSUBISHI         B3J6P    13
SUZUKI             ED13B    12
HYUNDAI            GA17F    12
MERCEDES BENZ      10704    12
                   20304    12
HYUNDAI            FF41C    12
MERCEDES BENZ      21207    11
NISSAN             UZD1H    11
MERCEDES BENZ      3G4EB    11
CHANGAN            ASE2E    11
HONDA              M8500    11
MERCEDES BENZ      12906    11
                   21637    11
TVS                37DE7    11
YAMAHA             RM32E    11
MERCEDES BENZ      46327    10
SUZUKI             ED24F    10
MERCEDES BENZ      WF4KB    10
BYD                FD4C4    10
SUZUKI             GN7EA    10
MERCEDES BENZ      12603    10
SUZUKI             GT77A    10
ROX                ABBHK    10
HONDA              SC68H    10
MERCEDES BENZ      21007    10
                   CA39E    10
JETOUR             DB21B    10
YAMAHA             RM38E    10
MERCEDES BENZ      16687    10
NISSAN             HZ14S    10
TOYOTA             LJ73J    10
MERCEDES BENZ      22218    10
TOYOTA             LU73J    10
MERCEDES BENZ      21308    10
                   17145    10
HONDA              SC79M    10
SUZUKI             GN7FA    10
ISUZU              JP24F    10
YAMAHA             DG01X    10
HONDA              RH218    10
MERCEDES BENZ      20405     9
HONDA              SC68G     9
GMC                GC34M     9
MERCEDES BENZ      22115     9
PORSCHE            ZZZ98     9
HONDA              KC20C     9
BAJAJ              DHDJZ     9
VOLKSWAGEN         VB9E6     9
HONDA              SC47F     9
MAZDA              UN236     9
MERCEDES BENZ      22217     9
HONDA              SC795     9
CADILLAC           DW51Y     9
BAJAJ              DHDKZ     9
CHERY              DC21B     9
HONDA              KC20F     9
KAWASAKI           ZXT00     9
SUZUKI             EA12B     9
                   VY53A     9
                   GR7KA     9
HONDA              PCK20     9
MERCEDES BENZ      V0LEZ     9
HONDA              SC793     8
MERCEDES BENZ      PK4JA     8
ROYAL ENFIELD      U5S5F     8
LEXUS              BN36F     8
HONDA              KC20D     8
BYD                CE4CB     8
MERCEDES BENZ      12604     8
                   46323     8
MAXUS              G4BC1     8
MERCEDES BENZ      44781     8
LEXUS              BN30F     8
TVS                25AF4     8
TOYOTA             JJXB0     8
LEXUS              BA1D2     8
KIA                WJ272     8
BAJAJ              A11CY     8
CHERY              DB21B     8
MERCEDES BENZ      21107     8
                   17044     8
BYD                CF4CD     8
SUZUKI             A1111     8
LEXUS              DU46F     8
                   BARBZ     8
HONDA              KC20E     8
BAJAJ              A13EZ     8
HYUNDAI            JA17B     8
MERCEDES BENZ      20202     8
NISSAN             AE2KP     8
BAIC               RCFBK     8
NISSAN             0WGY6     8
BAJAJ              A11CZ     8
LAND ROVER         EA7BE     8
HARLEY-DAVIDSON    1LC31     8
FOTON              C2ZWB     8
LEXUS              HW31U     8
LAND ROVER         LAAA4     7
MERCEDES BENZ      12402     7
CHANGAN            ASE2A     7
CADILLAC           DW547     7
PEUGEOT            E1NFJ     7
MERCEDES BENZ      21006     7
HONDA              MC350     7
NISSAN             PCF0H     7
                   PBF0H     7
HONDA              SC47H     7
AYED               PEAND     7
FOTON              B2NWA     7
HONDA              PC569     7
                   SC68L     7
FORD               7W2B6     7
LEXUS              BW1GG     7
MERCEDES BENZ      14007     7
                   12602     7
HONDA              PCKL9     7
BAJAJ              A21BX     7
MERCEDES BENZ      12403     7
                   93016     7
YAMAHA             SJ18K     7
CHRYSLER           CCAAG     7
HONDA              TX9B9     7
MERCEDES BENZ      46324     7
BMW                0E210     7
                   VH150     7
TVS                25AE3     7
MERCEDES BENZ      WF6EB     7
HARLEY-DAVIDSON    4LE21     7
LYNK & CO          79END     7
INFINITI           BY1AP     7
CHANGAN            CME0Z     7
MERCEDES BENZ      21537     7
FORD               WE3FS     7
SUZUKI             TCJC9     7
LAND ROVER         LDHAD     7
                   EA7BU     7
MERCEDES BENZ      UG8CB     7
NISSAN             BE6AS     7
SUZUKI             GN7DA     7
HARLEY-DAVIDSON    1KEL1     7
NISSAN             BJ1CP     7
FORD               XE45S     7
CHERY              DB24B     7
INFINITI           AL0MM     7
SUZUKI             CL111     7
BAJAJ              A12DY     7
HONDA              JB058     7
SUZUKI             CY111     7
FORD               WE3FN     7
HYUNDAI            GE17F     7
HONDA              SC470     7
VOLVO              AG20A     6
KIA                LM415     6
NISSAN             00KY6     6
VOLVO              A4DAA     6
                   A4CFA     6
DAIHATSU           UV182     6
MERCEDES BENZ      ZF0EB     6
HONDA              SC47G     6
                   A11CX     6
AUDI               ZZZF2     6
HONDA              KC201     6
JAC                2EKR2     6
MERCEDES BENZ      22006     6
                   21937     6
                   ZF4FB     6
                   21738     6
POWEREAGLE         TBC02     6
MERCEDES BENZ      DA5HB     6
CHRYSLER           CCAFJ     6
                   CCAGG     6
BMW                0M110     6
HINO               UF11H     6
MERCEDES BENZ      RN41H     6
CHEVROLET          FG15T     6
HARLEY-DAVIDSON    4LE2C     6
LAND ROVER         EA6BU     6
VOLVO              ASG0A     6
NISSAN             CZ14S     6
HYUNDAI            WA37J     6
MERCEDES BENZ      CA39D     6
JETOUR             PBGFB     6
KIA                HNP6N     6
MERCEDES BENZ      46326     6
                   WF4JB     6
BMW                FR110     6
MERCEDES BENZ      21306     6
NISSAN             BBAB1     6
SUZUKI             GW71A     6
MITSUBISHI         B3E6P     6
HARLEY-DAVIDSON    1KTP1     6
JETOUR             DD24B     6
HYUNDAI            FH41E     6
LAND ROVER         GA2EF     6
JAC                66B3D     6
BMW                0D500     6
LEXUS              BH68X     6
MERCEDES BENZ      29237     6
SUZUKI             EJ11B     6
HONDA              KC097     6
BAJAJ              A13EY     6
MITSUBISHI         BHJ6S     6
YAMAHA             RG092     6
BMW                KB810     6
MERCEDES BENZ      LJ9BB     6
                   DF7DE     6
BMW                NA510     6
KIA                MB5C1     6
HYUNDAI            GA17C     6
                   LB81C     6
ISUZU              KP34T     6
AUDI               ZZZF1     6
BMW                0E610     6
BAJAJ              A12DX     6
SUZUKI             CW111     6
HONDA              KC20B     6
BAJAJ              A22EX     6
MERCEDES BENZ      22105     6
MAZDA              NA351     6
SUZUKI             C4111     6
HONDA              PC44U     6
VOLVO              RTY0A     6
MERCEDES BENZ      ZF8DB     6
ISUZU              JP24T     6
SHARMAX            TX9A2     6
KIA                FT4DE     6
MERCEDES BENZ      95016     5
NISSAN             BT05Y     5
HONDA              KC401     5
NISSAN             BJ1CR     5
BMW                11AV0     5
HONDA              P7900     5
NISSAN             BE6DS     5
LEXUS              BC11A     5
DODGE              RDGBG     5
NISSAN             BDAB1     5
MERCEDES BENZ      11838     5
NISSAN             AS5MV     5
MERCEDES BENZ      3G4FB     5
BMW                05240     5
TOYOTA             AG34L     5
ISUZU              KP34H     5
CHERY              MCWEY     5
BMW                6B210     5
NISSAN             AS44D     5
                   AN08W     5
MAXUS              G5GC1     5
MERCEDES BENZ      23245     5
KTM                JPJ40     5
YAMAHA             RJ16E     5
CHRYSLER           RC1BG     5
BMW                0M210     5
                   0M310     5
NISSAN             ADGD2     5
LEXUS              CE1D2     5
HARLEY-DAVIDSON    1KHC1     5
MERCEDES BENZ      22206     5
HONDA              37DE7     5
BAIC               RCFDK     5
HONDA              RH093     5
MITSUBISHI         FE635     5
HONDA              SC47L     5
CHEVROLET          JD5SB     5
BMW                0P210     5
MITSUBISHI         HNP13     5
HONDA              KC093     5
KTM                JGJ40     5
HONDA              RH108     5
ISUZU              LP445     5
VOLVO              A4DBA     5
MERCEDES BENZ      ZF6GB     5
HONDA              KC191     5
BMW                0E230     5
MERCEDES BENZ      YC7HJ     5
VOLVO              A4B3A     5
VOLTAMP            DZM0E     5
VOLKSWAGEN         ZZZ7H     5
KIA                MG4C7     5
MERCEDES BENZ      YC7GJ     5
GMC                EK19T     5
VOLKSWAGEN         VB9E7     5
                   JE2CA     5
INFINITI           CV6FE     5
CADILLAC           DW52P     5
MERCEDES BENZ      YC7EF     5
CADILLAC           DW54E     5
JETOUR             PBGGB     5
VICTORY            TEKP1     5
                   FDABB     5
LEXUS              BJ46G     5
MERCEDES BENZ      YC6BJ     5
BYD                F74C4     5
BMW                AM310     5
MERCEDES BENZ      WG3E1     5
TVS                37AR1     5
CHEVROLET          GG29U     5
BMW                VB550     5
ISUZU              JP23G     5
                   JP23T     5
INFINITI           AZ2ND     5
                   AZ2NF     5
MERCEDES BENZ      21736     5
                   WF0EB     5
TOYOTA             PBEJA     5
ISUZU              JP24H     5
TOYOTA             NX22N     5
                   M8500     5
MERCEDES BENZ      16798     5
HARLEY-DAVIDSON    4CR2C     5
LAND ROVER         E3ERU     5
LEXUS              YARBZ     5
KTM                V3940     5
HONDA              GE886     5
MERCEDES BENZ      SJ5CB     5
BAJAJ              A67MX     5
INFINITI           AZ2NY     5
GMC                V2LEC     5
MERCEDES BENZ      PK3JA     5
LAND ROVER         EA8BU     5
TOYOTA             JX02P     5
KAWASAKI           EXKG1     5
TOYOTA             EF8BF     5
MERCEDES BENZ      FA68F     5
TOYOTA             BT441     5
MERCEDES BENZ      EJ71X     5
                   ED6EB     5
TOYOTA             A180C     5
XIAOMI             M3A08     5
LEXUS              B21B1     5
BAJAJ              DHJCZ     5
HARLEY-DAVIDSON    4NCGC     5
HONDA              KC209     5
SUZUKI             NF4HG     5
GREAT WALL         CA237     5
AUDI               ZZZF5     5
GMC                W78CG     5
MERCEDES BENZ      21105     5
SUZUKI             GT78B     5
PORSCHE            ZZZ99     5
MERCEDES BENZ      CB5EE     5
SUZUKI             GT76A     5
YAMAHA             DM12Y     5
HONDA              SC790     5
                   PCLLY     5
KIA                BA244     5
MERCEDES BENZ      DA5GB     5
NISSAN             PAEHD     5
LEXUS              BE1KS     5
AUDI               VB9G3     5
NISSAN             PBEJA     5
CHERY              DD24B     5
BMW                AM510     5
NISSAN             M8500     5
AUDI               ZZZGY     5
BMW                AA210     5
MERCEDES BENZ      20538     5
                   BF4DB     5
NISSAN             DY11S     5
MERCEDES BENZ      21209     5
NISSAN             CZ04S     5
GEELY              7964Z     5
LEXUS              BK1GG     5
HONDA              SC474     5
KAWASAKI           EX8B1     5
CITROEN            VLAHX     5
INFINITI           BJ0HR     5
SUZUKI             DM11H     5
MERCEDES BENZ      21205     5
                   BA45A     5
HYUNDAI            WBX7K     5
FORD               MJP2B     5
HONDA              JC36P     5
SUZUKI             DM11B     5
MERCEDES BENZ      20498     5
CHRYSLER           CCACG     5
NISSAN             CBGD2     5
CMC                CP515     5
SUZUKI             CV111     5
MERCEDES BENZ      20374     5
LAND ROVER         EP7RU     5
MERCEDES BENZ      95053     5
MAZDA              UN202     5
HONDA              AAPFA     5
MERCEDES BENZ      21106     5
SUZUKI             CF4CA     5
HONDA              KC311     5
NISSAN             CC13C     5
SUZUKI             BM111     5
NISSAN             BT2MU     5
GREAT WALL         DC618     5
SUBARU             BP98E     5
JAC                1KDBD     5
SHARMAX            PCLLY     5
HONDA              KC315     5
BAJAJ              PCKL9     5
GREAT WALL         CA217     5
INFINITI           AY1AP     5
FERRARI            FD60B     5
TVS                34KE6     5
MERCEDES BENZ      20504     4
                   20936     4
FORD               FW1RG     4
MERCEDES BENZ      21027     4
                   21304     4
KIA                FU615     4
BYD                CD4C4     4
MERCEDES BENZ      21935     4
DODGE              RDGCG     4
BYD                CE4CC     4
AUDI               ZZZFW     4
MERCEDES BENZ      22007     4
                   22119     4
HYUNDAI            HD17F     4
AUDI               ZZZFY     4
MERCEDES BENZ      22216     4
                   22298     4
                   22316     4
                   25338     4
LEAPMOTOR          93AN9     4
MERCEDES BENZ      25736     4
HYUNDAI            ZSX7K     4
                   HG17C     4
BMW                0G410     4
MERCEDES BENZ      3F4GB     4
CHEVROLET          BL52P     4
MERCEDES BENZ      65540     4
                   65841     4
                   7X8KB     4
                   95020     4
HONDA              RH233     4
MERCEDES BENZ      9HPAD     4
                   AF8HB     4
BMW                0J510     4
MERCEDES BENZ      DA5JB     4
                   CB54E     4
HONDA              DG01X     4
MERCEDES BENZ      DF5GE     4
                   DF7CE     4
                   EG2BB     4
                   FD8KB     4
                   GF4HB     4
                   GJ8JB     4
                   HF8JB     4
HONDA              PDLRS     4
MERCEDES BENZ      HF9AB     4
                   JK7DA     4
                   KHCAA     4
                   LJ6FB     4
CHERY              MCWBT     4
MERCEDES BENZ      SJ4GB     4
                   UG8DB     4
                   UG7JB     4
                   UG8FB     4
                   UG8GB     4
                   WH5AB     4
YAMAHA             RN79E     4
MERCEDES BENZ      WF4CB     4
                   WJ8HB     4
                   WG2E1     4
                   ZF4KB     4
                   ZG8AB     4
MG                 A24W9     4
                   A36U3     4
                   W94U9     4
MINI               81BR0     4
                   YX1A0     4
MITSUBISHI         BHH1A     4
                   CUK1L     4
                   JNK62     4
                   GS41L     4
HONDA              SC68N     4
MITSUBISHI         JNP13     4
NISSAN             0HGZ3     4
                   0UGY6     4
BMW                11AK0     4
                   11AL0     4
NISSAN             A4B2A     4
YAMAHA             RM39B     4
NISSAN             A4B3A     4
                   AG34L     4
BMW                7F210     4
NISSAN             AT2MV     4
                   BE6CS     4
                   BL4DV     4
INFINITI           CV6AP     4
NISSAN             BY2NY     4
BAJAJ              37DE7     4
NISSAN             BW12S     4
                   BZ4EH     4
                   CBAN1     4
JETOUR             DB218     4
DONGFENG           29H92     4
NISSAN             CC11C     4
                   DD23S     4
                   DW12S     4
                   FN61C     4
                   TBSY6     4
HARLEY-DAVIDSON    1KELC     4
JETOUR             DB24B     4
ISUZU              JP14K     4
NISSAN             UYD1H     4
YAMAHA             KE129     4
INFINITI           AZ2NC     4
                   AZ2NE     4
RENAULT            8SRB4     4
ROYAL ENFIELD      FDP20     4
SHARMAX            NAZ50     4
KAWASAKI           EXGJ1     4
BAJAJ              A22EY     4
HARLEY-DAVIDSON    1KZF1     4
CADILLAC           AD478     4
BMW                BS510     4
                   VD310     4
SHARMAX            TX9C7     4
                   JCNL0     4
BAJAJ              A55FX     4
SMART              45133     4
SUZUKI             DM11A     4
LAND ROVER         LDHAV     4
SUZUKI             EJ11D     4
BMW                GL410     4
LAND ROVER         EA6BE     4
BMW                HN810     4
BAJAJ              DDDUZ     4
HARLEY-DAVIDSON    1LC3C     4
SUZUKI             GR7LA     4
LEXUS              53UF2     4
SUZUKI             JDT08     4
LAND ROVER         EA6BX     4
SUZUKI             NG4BB     4
                   PCJK6     4
BAJAJ              DHDHZ     4
SUZUKI             RFL61     4
HARLEY-DAVIDSON    1LP31     4
SUZUKI             SP46D     4
TATA               44925     4
TOYOTA             11111     4
                   71SC1     4
                   A4DAA     4
                   A14CK     4
                   AACAJ     4
                   AAAAA     4
ISUZU              DL34P     4
TOYOTA             BB0BE     4
LEXUS              BC96S     4
TOYOTA             BR32E     4
                   BL9HE     4
DFSK               A53P9     4
TOYOTA             BR22E     4
                   BT14R     4
                   BU71J     4
HONDA              TC2C3     4
                   ZE4F5     4
HARLEY-DAVIDSON    1KVP4     4
TOYOTA             FU71J     4
LAND ROVER         LHABE     4
TOYOTA             KARJE     4
                   LJ71J     4
                   LU71J     4
KIA                FU415     4
LAND ROVER         LHABN     4
TOYOTA             LB71J     4
HONDA              RS185     4
BMW                BF410     4
TOYOTA             ZD31V     4
                   ZU14R     4
HARLEY-DAVIDSON    1YGK4     4
VESPA              0000J     4
VICTORY            BTNPP     4
                   DW36N     4
BMW                1J710     4
VICTORY            EDABB     4
                   MCKBE     4
VOLKSWAGEN         447AU     4
INFINITI           CY01E     4
HONDA              KC404     4
                   KC406     4
VOLKSWAGEN         CAZSE     4
FORD               TK3SU     4
VOLKSWAGEN         DBZSV     4
                   DH4CD     4
HONDA              TNKP2     4
VOLKSWAGEN         KR2CA     4
                   ZBB2K     4
                   ZZZ1J     4
VOLVO              A4B2A     4
                   A4CEA     4
                   A4CMA     4
                   A4DMA     4
                   AS02A     4
HONDA              SD15G     4
VOLVO              ASW0A     4
                   J1G1A     4
HONDA              PC56U     4
FORD               FF6LT     4
BMW                KA410     4
ISUZU              LP34H     4
LAND ROVER         EJ7EX     4
                   EJEEX     4
KAWASAKI           ZXCM1     4
CHEVROLET          DL34P     4
KIA                DN413     4
EXEED              DD24B     4
YAMAHA             RM06E     4
JETOUR             PBGJB     4
KIA                GN418     4
JETOUR             F4J16     4
HONDA              TEKP1     4
DFSK               A42F9     4
INFINITI           CS1MU     4
HONGQI             H4ACP     4
HONDA              GK588     4
HYUNDAI            WBH7J     4

In [234]:
df_clean.columns.tolist()

['chassisNumber',
 'year',
 'make',
 'model',
 'trim',
 'bodyType',
 'regionalSpec',
 'cylinders',
 'color',
 'origin',
 'weightInKg',
 'noOfPassengers',
 'model_length',
 'vds']

In [235]:
toyota = df_clean[df_clean["make"] == "TOYOTA"]

toyota.groupby("vds")["model"].nunique().sort_values(ascending=False)

vds
LJ73J    10
LU73J    10
JJXB0     8
BT441     5
AG34L     5
EF8BF     5
NX22N     5
PBEJA     5
A180C     5
M8500     5
JX02P     5
ZD31V     4
AACAJ     4
AAAAA     4
FU71J     4
BU71J     4
BT14R     4
BR32E     4
BR22E     4
BL9HE     4
BB0BE     4
71SC1     4
LB71J     4
LJ71J     4
KARJE     4
LU71J     4
11111     4
A14CK     4
A4DAA     4
ZU14R     4
A4B3A     3
AA9AJ     3
14252     3
ZF13C     3
B519E     3
B3J6P     3
BB02E     3
BB9HE     3
BC42E     3
BBOBE     3
BD1FK     3
79END     3
BE32K     3
BF0JE     3
BE6DS     3
BE6BS     3
BF9FK     3
BG22K     3
BJ53L     3
PAEHD     3
PX4EN     3
PX22P     3
PM62N     3
BPB9E     3
BM99J     3
BT481     3
BU25J     3
BU17R     3
BU14R     3
BU9FJ     3
BU3FJ     3
BV71J     3
BX9FJ     3
BZ42E     3
MF53F     3
21608     3
MX83E     3
MX73E     3
MU4FN     3
NM92N     3
NX4CN     3
1BAA3     3
CECB8     3
CX3FJ     3
D3135     3
CZ5AN     3
DR32T     3
EX19G     3
FM518     3
FM418     3
ML110     3
FK418     3
GE52M     3
44925     3
HX02P     3
K4MBE     3
KARFP     3
KD3B3     3
TX22N     3
VB9E7     3
VL52N     3
11VJ9     3
KK3DC     3
KHMBX     3
KRKEC     3
KR30E     3
KW73J     3
ZCP2F     3
ZU5JR     3
00000     3
A4CFA     3
YK3DC     3
YMLA2     3
ACAAU     3
ZA3BB     2
ZA22C     2
10252     2
ZCP2H     2
AL29J     2
AG4CK     2
ARE0C     2
AP86C     2
15100     2
14270     2
UCK1H     2
TX4CN     2
8L9HE     2
8W23E     2
AE52S     2
AFAAF     2
KN36U     2
KU4EE     2
KT9F3     2
KX6CB     2
KW923     2
L11AK     2
KZ3DC     2
A11CX     2
A4GF5     2
ZCN1F     2
ZCK1H     2
ZK31V     2
ZFREV     2
ZK22C     2
889HE     2
880CE     2
UU4EN     2
VB9E6     2
V0LEZ     2
W13FV     2
WA37R     2
12005     2
12003     2
12001     2
WG81R     2
XE4FS     2
KC20F     2
KK4CC     2
KDTB3     2
KT441     2
KSKFC     2
KR32E     2
JM11D     2
JU3FJ     2
JU9FJ     2
JX8CB     2
K61AK     2
K43BE     2
JY5G1     2
KAMFU     2
KAAAG     2
KB8CD     2
KB20U     2
32BUM     2
31UJ7     2
KCAAG     2
UF117     2
UX4EN     2
H4ACP     2
GZ3DH     2
HD17F     2
HJ09J     2
HG17C     2
HT05J     2
HP10V     2
HN9CP     2
HN87R     2
HN86R     2
HU09J     2
HW2ZZ     2
J13FV     2
JA82J     2
JK3DC     2
JNK64     2
LV73J     2
LU733     2
MD351     2
MD121     2
MC13F     2
MA71J     2
MF929     2
FU73J     2
FR320     2
G11BK     2
G11AK     2
FY418     2
G4X20     2
GJKFW     2
GP21A     2
GN87R     2
EW23E     2
FB518     2
F1RFV     2
FE728     2
FE718     2
FE52S     2
46470     2
FK518     2
LDHAD     2
LB5JN     2
LA5DB     2
LU4EN     2
LU42N     2
LMFCP     2
M11AK     2
LY3FX     2
DB4A0     2
DBZSV     2
DK3EH     2
DF9EV     2
DF4EV     2
DP21A     2
DN136     2
DW12S     2
DW11S     2
DZ5BN     2
DY5G1     2
EF88F     2
EG22K     2
ES12G     2
ER23E     2
EW44A     2
BY879     2
BY80E     2
C916Z     2
C2ZWB     2
C11BK     2
C11AK     2
BZRFH     2
CAABG     2
CJE23     2
CS18Z     2
CX9FJ     2
CX9CD     2
CX8CD     2
50975     2
D3DF6     2
DB0G0     2
BU8CD     2
BU4EE     2
BV42E     2
BW22E     2
BW12S     2
BX8CD     2
BZ4HK     2
BZ28E     2
21610     2
21606     2
21604     2
MU52N     2
PAAWA     2
P6X40     2
1201D     2
1CU83     2
RX12P     2
SS1EK     2
17100     2
BKRFH     2
BPMBE     2
BN95J     2
BT123     2
BR38E     2
BR23E     2
BU11F     2
53SK2     2
53EL5     2
53EEA     2
53AEB     2
53AEA     2
BT9F3     2
BK1EB     2
BK4FK     2
BK46K     2
BK40K     2
BK3EK     2
BK36B     2
BL29J     2
PG34L     2
PCKL9     2
PBEHD     2
PBEFA     2
PBAJA     2
PX42N     2
RC1BG     2
R1CS9     2
RX5GN     2
BF31E     2
BF30K     2
BF23K     2
BF22K     2
BF1FK     2
BF9HK     2
BF9EV     2
BF4HK     2
BF4FK     2
BF3EK     2
BH9FJ     2
BH42K     2
BG28K     2
BG23K     2
BG21K     2
BK1FK     2
BC74K     2
BBOCE     2
BD31V     2
7ENFU     2
7ANFU     2
72SK2     2
BE42K     2
BE40K     2
BE33K     2
BE30K     2
BE6AS     2
66B3D     2
BE46K     2
BF38K     2
BF32K     2
BF31F     2
B29HK     2
B24HK     2
B19HK     2
B14HK     2
B4B9E     2
B3FE1     2
B31HK     2
BA02E     2
BA01E     2
B61HK     2
BAOBE     2
80001     2
BB46K     2
BB3EK     2
BB13E     2
BCE1J     2
AF4E3     2
AECB8     2
AEACH     2
WN72N     2
XZ3DC     2
XX43G     2
AP22C     2
AN95J     2
AU25J     2
ASW0A     2
ASB3R     2
AS02D     2
AS02A     2
B11HK     2
AZ5CN     2
B2E6K     2
8URHE     2
8U40E     2
8U3FJ     2
95403     2
94403     2
91903     2
8X9FJ     2
ACABF     2
A4B2A     2
A4CEA     2
AAABG     2
AAA0C     2
ABBBJ     2
AB1BY     2
ZN3EU     2
ZBB2K     2
8CE1K     2
8CCVD     2
8R22E     2
XX42G     2
YH20V     2
YD3EV     2
YZRFH     2
YZ3DC     2
ZN128     2
ZK3DC     2
06XZZ     2
ZT14R     2
ZNBF1     2
ZU17R     2
ZZRFH     2
ZK23C     2
ZNBB1     1
00ACV     1
00968     1
00943     1
00898     1
00856     1
00800     1
00713     1
00612     1
01111     1
01302     1
01BUM     1
02290     1
022GD     1
03350     1
042TN     1
06622     1
0B9CB     1
0J4MC     1
ZNAA1     1
ZNAE1     1
ZK32V     1
ZK33V     1
ZK34V     1
ZK4CC     1
8622K     1
8628K     1
87367     1
87N07     1
8808E     1
8842E     1
8846K     1
88OCE     1
8A02E     1
8A08E     1
80890     1
80893     1
ZU4BF     1
ZV42E     1
ZX69G     1
ZY0CC     1
8A32K     1
8B9HE     1
8BCE1     1
8C42E     1
8D1FK     1
8D31V     1
8D33V     1
8D35E     1
8E30K     1
8E32K     1
8E33K     1
8E42K     1
824HK     1
829F3     1
829HK     1
855HZ     1
8F22K     1
8F28K     1
8F30K     1
8F31F     1
8F32K     1
8F38K     1
8F3EK     1
8F4DV     1
8F4FK     1
8F4HK     1
8F9C3     1
8F9EV     1
8F9FK     1
8F9HK     1
8A13E     1
8A23C     1
8G22K     1
8J466     1
8J53L     1
8K1E8     1
8K1FK     1
8K22C     1
8K31V     1
8K32V     1
8K33V     1
8K368     1
8K36B     1
8K3D8     1
8K3DB     1
8K3EK     1
8E46K     1
8F1FK     1
8K40K     1
8K46K     1
8K4FK     1
8L0HE     1
8L29J     1
8N95J     1
8R23E     1
8R32E     1
8R42E     1
8RI2E     1
8T923     1
8T9F3     1
8U11F     1
8U25J     1
8FIFK     1
8FREV     1
91902     1
91908     1
93220     1
95021     1
8U4EE     1
8U5CD     1
8U71J     1
8U8CD     1
8V42E     1
8V541     1
8V71J     1
8W123     1
8W133     1
8W923     1
8W933     1
8W9F3     1
A11CY     1
A14AF     1
A16E3     1
A1809     1
A1ACC     1
A1RFV     1
A22EZ     1
A22NE     1
8X8CD     1
8Y561     1
8Y5F1     1
8Y64A     1
8Z4HK     1
90615     1
91900     1
91901     1
80943     1
80950     1
80951     1
80986     1
80987     1
81018     1
811EB     1
811HK     1
813FV     1
814HK     1
819F3     1
819HK     1
8242E     1
80473     1
80506     1
A11AK     1
AABAJ     1
A4B5A     1
A4DAC     1
A4DBA     1
A4DF5     1
A4DMA     1
A4MBE     1
A4RBE     1
A6426     1
A818Y     1
A878J     1
A888J     1
AA18A     1
9FD8T     1
A0B98     1
80907     1
AB1BA     1
AB36U     1
AB7BJ     1
AB7RJ     1
ABBAA     1
AA1AB     1
AA1BA     1
AA5RX     1
AA7BJ     1
AAAA5     1
AAAAF     1
AAAAG     1
AAAB5     1
AAABA     1
AAADC     1
AAAOC     1
AC1DM     1
AC22C     1
AC7BJ     1
ACAAJ     1
ACAB5     1
ACABA     1
ACABB     1
ACJ4H     1
AABBJ     1
AACBJ     1
AAIBA     1
AALAJ     1
AAN6E     1
AATBA     1
AAYAJ     1
AB18Y     1
AE07B     1
AE09B     1
AE09E     1
AE09V     1
AE09W     1
AE1BY     1
AE1EY     1
AE2KP     1
AE51S     1
AE525     1
AE53S     1
ABBDH     1
ABCBJ     1
ABFAJ     1
ABIBY     1
AC11R     1
80558     1
80583     1
80593     1
80636     1
80700     1
80761     1
80767     1
80772     1
80839     1
80850     1
80876     1
80183     1
801FK     1
AE00E     1
AE04B     1
AE04E     1
AE54S     1
AE82G     1
AE94A     1
AE94K     1
AEAA1     1
AECG2     1
AECG3     1
AF047     1
AF4CB     1
AF54K     1
AFABF     1
AFCG2     1
AE00B     1
80532     1
80533     1
80548     1
AR9AJ     1
ARCAJ     1
ARE2C     1
AFZBG     1
AG20A     1
AG30A     1
AG426     1
AGACH     1
AGNAC     1
AI4CK     1
AJ54K     1
AK54K     1
AKCB8     1
AL1CC     1
AM11H     1
AM29J     1
ASACK     1
ASG0A     1
AT123     1
AT2MV     1
AU78J     1
AU7BJ     1
AU88J     1
AM2AH     1
AM450     1
AM496     1
AM498     1
AN74K     1
AP54K     1
AP90A     1
APE2C     1
AR05Y     1
AUTBJ     1
AUZBJ     1
AVV5F     1
AW126     1
AW12G     1
AW5F1     1
AX126     1
AX12G     1
AX5GN     1
AX8CD     1
AXACC     1
AY117     1
AS123     1
AS12G     1
AS14U     1
AS47H     1
AY86C     1
AYACC     1
AYT30     1
AZ1FB     1
AZ496     1
B0111     1
B011F     1
B025J     1
B031V     1
B03FV     1
B046K     1
B13FV     1
AUBB3     1
AUBBJ     1
AUCBJ     1
AUF0A     1
80251     1
80274     1
80281     1
80282     1
80318     1
80328     1
80345     1
80350     1
80407     1
80413     1
80430     1
80459     1
80464     1
7JNFU     1
7KE43     1
AY5F1     1
B4MDE     1
B4MEE     1
B4RBE     1
B19F3     1
B1B0E     1
B1DWA     1
B1RFV     1
B21FB     1
B21HK     1
B23HK     1
B242E     1
B28F3     1
B29F3     1
B29M3     1
AY2NY     1
80233     1
BA03E     1
BA05E     1
BA0BE     1
BA13E     1
BA1HK     1
BA22C     1
BA23C     1
BA244     1
B2NBA     1
B2NWA     1
B308E     1
B30BE     1
B30EE     1
B3E6P     1
B3G6P     1
B4MBE     1
BA3BB     1
BA3BE     1
BA8CD     1
BAAAG     1
BAABG     1
BACEK     1
BADBA     1
BAMDE     1
BAYV5     1
BB03E     1
BB08E     1
B622K     1
B674K     1
B6RFV     1
B7A2J     1
B89HE     1
80000     1
80003     1
80008     1
80015     1
80025     1
80042     1
80054     1
80063     1
80078     1
80095     1
80097     1
80125     1
72AEA     1
72AEB     1
BA30K     1
BA32K     1
BCE1K     1
BCE6J     1
BCELK     1
BB0BB     1
BB0CE     1
BB12E     1
BB3JE     1
BB42E     1
BB71J     1
BB8CD     1
BB9BE     1
BB9JE     1
BBBEX     1
BBDEE     1
BA2A9     1
7LHEP     1
BD337     1
BD33V     1
BD35V     1
BD74K     1
BD9EV     1
BD9FJ     1
BDF1J     1
BDIEB     1
BBE32     1
BBN2A     1
BBRCH     1
BBSHE     1
BC11E     1
BC42R     1
BC53L     1
BC81S     1
72EEB     1
72SC1     1
72SK1     1
72SV1     1
73FM4     1
75106     1
79YND     1
7CNFU     1
7FNFU     1
65910     1
65933     1
BD0FA     1
BD1EB     1
BD23S     1
BD317     1
BD32V     1
BF0BE     1
BF12B     1
BF12K     1
BDMHE     1
BDOES     1
BE23K     1
BE24K     1
BE36K     1
BE38K     1
BE3EK     1
BE40E     1
BE42J     1
BE42k     1
BE44K     1
BD0CT     1
72EEA     1
6H20V     1
6JKFW     1
6N87R     1
6W923     1
71000     1
715C1     1
61524     1
62101     1
BE4EE     1
BE4GK     1
BE6CS     1
BE85B     1
BE9B3     1
BE9FK     1
BE9HE     1
BECEK     1
BF9C3     1
BF9FR     1
BF18B     1
BF28B     1
BF28K     1
BF31V     1
BF32V     1
BF32X     1
BF33V     1
BF35V     1
65934     1
6AE3C     1
6D32M     1
6D52M     1
6D54M     1
6E52M     1
BFREV     1
BFTFK     1
BG12K     1
BG17K     1
BH2AW     1
BH96S     1
BHJ6S     1
BJ13E     1
BF3FK     1
BF3HK     1
BF3JE     1
BF46K     1
BF4DV     1
BF5C2     1
BF6C3     1
BF8C3     1
63AL5     1
64AEB     1
64EEB     1
64STL     1
65200     1
65203     1
65204     1
65213     1
65553     1
65610     1
65620     1
65651     1
65805     1
53XK2     1
543AV     1
BFIFK     1
BK4DV     1
BJ18U     1
BJ22K     1
BJ335     1
BJE23     1
BJI3E     1
BJRBZ     1
BK1E8     1
BK22C     1
BK23C     1
BK262     1
BK29J     1
BK31V     1
BK326     1
BF9JE     1
63AL4     1
BL4A9     1
BL8HE     1
BL9HF     1
BLGHE     1
BLIHK     1
BLSHE     1
BK32V     1
BK33V     1
BK34V     1
BK35B     1
BK35V     1
BK368     1
BK3BB     1
BK3DB     1
BK3EH     1
BK42K     1
BM82F     1
BN30F     1
BN36F     1
BN441     1
BPRBE     1
BPRHE     1
BPWDG     1
BR12E     1
BR18E     1
BK4SK     1
BKIEB     1
BL00E     1
BL0HE     1
BL293     1
BL40E     1
BL42E     1
54EEA     1
56EZZ     1
56N8U     1
58557     1
59695     1
5AFKG     1
5C3AV     1
5D3BV     1
5DDDD     1
5WRFV     1
5X23P     1
60019     1
60023     1
52EEB     1
52ZEB     1
BM29J     1
BT69Y     1
BT903     1
BT923     1
BR22F     1
BR28E     1
BR30E     1
BR406     1
BR40E     1
BR42E     1
BR43E     1
BR9FJ     1
BRKEC     1
BRZ3E     1
BT05Y     1
BM000     1
543BV     1
BU253     1
BU258     1
BU26J     1
BU29J     1
BU300     1
BT17R     1
BT223     1
BT2MW     1
BT3AA     1
BT3AB     1
BT44A     1
BT48A     1
BT4K3     1
BT541     1
BT581     1
BT64A     1
535K2     1
53AFB     1
53EE8     1
53EEB     1
53JSF     1
53SK1     1
53SV2     1
53XH1     1
51426     1
51452     1
BT9K3     1
BU&CD     1
BU01F     1
BU11E     1
BU11J     1
BU250     1
BV426     1
BV541     1
BV581     1
BV61E     1
BU3AE     1
BU3EJ     1
BU40E     1
BU4BF     1
BU585     1
BU5IF     1
BU5JR     1
BU8F5     1
BU8FS     1
BUBFS     1
BUIIF     1
534K2     1
BW541     1
BW581     1
BW5F1     1
BW5G1     1
BW6F3     1
BW923     1
BUJFJ     1
BUL1F     1
BURHE     1
BURNE     1
BUSCD     1
BUSFJ     1
BUSFS     1
BUT1F     1
BUTIF     1
BUTTF     1
BXBCD     1
BY11F     1
BY30E     1
BY32E     1
BY5F1     1
BY5G1     1
BY64A     1
BY67A     1
BVV13     1
BVV92     1
BW023     1
BW123     1
BW133     1
BW1GG     1
BW23E     1
BW3FV     1
51622     1
51658     1
51680     1
51908     1
51940     1
51972     1
525AN     1
52AEA     1
52EEA     1
50871     1
50873     1
BW9F3     1
BW9F4     1
BX3FJ     1
BX8C0     1
BX9F1     1
BY809     1
BY84A     1
BY99J     1
BYBDE     1
BZ1FB     1
BZ1HK     1
BZ42F     1
BZ4ZE     1
BZ9F3     1
BZAHK     1
BW933     1
51488     1
51500     1
51573     1
51611     1
51620     1
CBAGA     1
CC13C     1
CC1BR     1
CC1CX     1
C08RW     1
C1RFV     1
C21FB     1
C25AN     1
C31AK     1
C4MBE     1
C4RBE     1
C616Z     1
C618X     1
C74C4     1
C8E2H     1
BY68A     1
CIRFV     1
CJ6B1     1
CJE73     1
CK12G     1
CL968     1
CA217     1
CA21A     1
CA30P     1
CA31A     1
CA38P     1
CA50A     1
CAAAG     1
CAAGA     1
CB09J     1
CB337     1
CB3FV     1
CU09J     1
CU18R     1
CU1BR     1
CU923     1
CV12G     1
CV1F4     1
CV52B     1
CC42H     1
CDUD2     1
CE22P     1
CE38P     1
CF22P     1
CF28P     1
CG12K     1
CGE23     1
CH5CP     1
CW8C8     1
CW8CB     1
CW8CD     1
CW9CB     1
CW9CD     1
CX0CD     1
CX126     1
CX12G     1
CM565     1
CP450     1
CP515     1
CP724     1
CPA50     1
CRKEC     1
CS12G     1
CT05J     1
CX6CB     1
CX6CD     1
CX8C8     1
CX8CB     1
CX8EM     1
CX8GS     1
CX9C8     1
CX9CB     1
CV541     1
CW126     1
CW12G     1
CW5F1     1
CW6C8     1
CW6CB     1
CW6CD     1
CW8BB     1
51102     1
51109     1
51116     1
51147     1
51149     1
51189     1
51211     1
51267     1
51303     1
51382     1
51390     1
50287     1
50296     1
CX196     1
CX19G     1
CX3DD     1
CXBEM     1
CXI9G     1
CY5F1     1
CY7AJ     1
CZRAH     1
D13FV     1
D156F     1
D1RFV     1
D23DC     1
D258N     1
D2DF6     1
D4MBE     1
D4RBE     1
CX190     1
50954     1
51067     1
DBR22     1
D541A     1
D6RFV     1
D89CD     1
DA1AB     1
DA31A     1
DAAAG     1
DAABG     1
DAACK     1
DAR9K     1
DARTK     1
DB0A0     1
DB0AO     1
DB0C0     1
DB0E0     1
DB12E     1
DF4DV     1
DF4EB     1
DB21B     1
DB24B     1
DB2A0     1
DB2C0     1
DB41S     1
DB4C0     1
DB6CD     1
DB8CD     1
DB8FS     1
DB9CB     1
DB9CD     1
DBADK     1
DBE32     1
DBOE0     1
DK3DC     1
DK4CC     1
DK4DV     1
DBSCD     1
DBWG3     1
DBYSV     1
DCRFH     1
DD21A     1
DD22S     1
DD23S     1
DD2EY     1
DD82A     1
DE32K     1
DE4EV     1
DE626     1
DE82A     1
DM626     1
DN56A     1
DPMAE     1
DPRAE     1
DS41A     1
DS43A     1
DF4EU     1
DFAEV     1
DFREV     1
DG61E     1
DGRFH     1
DH4CD     1
DH88W     1
DH88X     1
DJ81W     1
DJREV     1
DTPUK     1
DU09J     1
DU09T     1
DV09J     1
DV541     1
DV581     1
DW3FV     1
DW51E     1
DW541     1
DKJA0     1
DKW9D     1
DL25R     1
DL39M     1
DLBJV     1
DLBYV     1
DM5F1     1
DX1H2     1
DX226     1
DX22G     1
DX6CB     1
DX6CD     1
DX8CD     1
DX8F5     1
DX8FS     1
DX9CB     1
DX9CD     1
DXBCD     1
DSKFC     1
DT3MW     1
DT441     1
DT481     1
DT541     1
DY5F1     1
DYSF1     1
DZ1FB     1
DZ3DC     1
DZ626     1
DZK23     1
DZRBH     1
DZRFH     1
DZSBN     1
E1EE0     1
E1NFJ     1
DW5F1     1
DW5G1     1
DW923     1
DWRFV     1
DWSF1     1
E6A3U     1
E6RFV     1
E8017     1
EA6BX     1
EAAAG     1
EAMDE     1
EB02E     1
EB0BE     1
EB13E     1
EB71J     1
EB73J     1
EBOBE     1
EBRBE     1
DXBFS     1
DY32T     1
DY38T     1
50470     1
50479     1
50500     1
50501     1
50504     1
50524     1
50531     1
50602     1
50617     1
50637     1
50671     1
50812     1
45612     1
46405     1
E29F3     1
E4FDB     1
EC42E     1
ECABA     1
ED1EK     1
ED31V     1
ED3KA     1
ED9HP     1
EDABB     1
EE32K     1
EE426     1
EE9HE     1
EF12K     1
EF4HK     1
EF76A     1
E2815     1
50333     1
50391     1
EF8C3     1
EF8CF     1
EF9FK     1
EFABF     1
EFAVS     1
EFBBF     1
EFBC3     1
EFBCF     1
EFHCF     1
EFSBF     1
EG12K     1
EG21K     1
EG23K     1
EG425     1
EG426     1
EBRCH     1
EGCBB     1
EJ13E     1
EJ5CD     1
EK12G     1
EK12T     1
EK19T     1
EL33P     1
EM426     1
EM42G     1
EM496     1
EM5F1     1
EN61S     1
ENE0R     1
ENKA5     1
EPMAE     1
EPRAE     1
EWIE5     1
EWRFV     1
ER21E     1
ER22E     1
ER33P     1
ER42E     1
ES41A     1
ES43A     1
ES46A     1
ET341     1
ET381     1
ET923     1
ET9F3     1
EU11F     1
EU3FJ     1
EU5JR     1
EZ28E     1
EZ3DC     1
EZ426     1
EZ42E     1
EU73J     1
EV541     1
EV581     1
EV73J     1
EW126     1
EW12G     1
EW1EP     1
EW21A     1
EW22E     1
EW41A     1
EW5F1     1
EW923     1
FA903     1
FARAH     1
FB718     1
FBABG     1
FBW41     1
EX120     1
EX126     1
EX12G     1
EX196     1
EX1E6     1
EX22G     1
EX28E     1
EX91G     1
EY5F1     1
EY64A     1
EZ20E     1
FDABB     1
FE22P     1
FE53S     1
FE54S     1
FF22P     1
FF41C     1
FF719     1
FG15T     1
EZ496     1
F11AK     1
F11BK     1
F31AK     1
F6RDM     1
F7D19     1
FA119     1
FA38P     1
50012     1
50017     1
50018     1
50061     1
50090     1
50189     1
50229     1
50237     1
50258     1
408B0     1
41500     1
FC24H     1
FC518     1
FD3HL     1
FDA88     1
FDAB8     1
FG426     1
FG8JP     1
FH3CB     1
FIRFV     1
FJ60G     1
FJ60V     1
FJ71J     1
FK122     1
FK718     1
FP14F     1
FP518     1
FPEFF     1
46407     1
46475     1
472AX     1
4E181     1
G13FV     1
G14DA     1
G1RFV     1
FPMAE     1
FPRAE     1
FR119     1
FR226     1
FR22G     1
FR73J     1
FU5JR     1
FV47V     1
FW12G     1
FX00G     1
FX02P     1
FX226     1
FX22C     1
GARAH     1
GBKFW     1
GBRCH     1
GD20V     1
GD21A     1
GD32M     1
FX22G     1
FX22P     1
FY5A1     1
FY5B1     1
FY5F1     1
FZ1FB     1
FZ29G     1
FZ418     1
FZRBH     1
G0EE9     1
GG25K     1
GGG56     1
GH20V     1
GJ211     1
GK12E     1
GK13E     1
GK26H     1
G31AK     1
G4AC1     1
G4BC1     1
G5GC1     1
G622K     1
G6X40     1
GA17E     1
GA17F     1
GA17H     1
GS54M     1
GSKFC     1
GU09J     1
GU4L3     1
GW5F1     1
GX72A     1
GX8CD     1
GX8EM     1
GXSEM     1
GD34M     1
GD52M     1
GD54M     1
GE17F     1
GES2M     1
GF46X     1
GF4JB     1
GZRAH     1
GZRBH     1
H0093     1
H009J     1
H109J     1
H1RFV     1
H25ZZ     1
H3093     1
H309J     1
H4BCP     1
H545G     1
GN86R     1
GNP03     1
GP10V     1
GR4A6     1
GRKEC     1
HAP5J     1
HAP73     1
HB10V     1
HB8CD     1
HB9CP     1
HC05J     1
HD20V     1
HD21A     1
HD23S     1
HDAAA     1
HEJ1F     1
HF10U     1
HG09G     1
GY5F1     1
GZ1FB     1
GZ5AN     1
41502     1
41503     1
41504     1
41BB4     1
41CB8     1
41E96     1
41UB5     1
41UHB     1
42010     1
42014     1
42015     1
42018     1
33YN8     1
35000     1
HA3CD     1
HAP53     1
HT093     1
HG39K     1
HH20V     1
HJ01J     1
HJ05J     1
HJ08J     1
HJ091     1
HJ093     1
HJ0SJ     1
HJ59J     1
HJ85J     1
HJO9J     1
HJQ8J     1
HJXEN     1
HK31U     1
41501     1
HU5JR     1
HU8CD     1
HUD3J     1
HUD9J     1
HUOTJ     1
HV01J     1
HNICP     1
HNP13     1
HNP6N     1
HNW6N     1
HPRAE     1
HR33N     1
HS02P     1
HT051     1
HT053     1
HT06J     1
HX02J     1
HX05J     1
HX07P     1
HX091     1
HX093     1
HX09J     1
HX0IJ     1
HT09J     1
HT0SJ     1
HT523     1
HTO5J     1
HTOSJ     1
HU01J     1
HU08J     1
HU091     1
HU093     1
HXO2P     1

In [236]:
(
    toyota.groupby("vds")["model"]
    .nunique()
    .value_counts()
    .sort_index()
)

model
0        2
1     2137
2      288
3       74
4       19
5        8
8        1
10       2
Name: count, dtype: int64

In [237]:
vds_purity = (
    toyota.groupby("vds")["model"]
    .nunique()
    .sort_values(ascending=False)
)

vds_purity.head(20)

vds
LJ73J    10
LU73J    10
JJXB0     8
BT441     5
AG34L     5
EF8BF     5
NX22N     5
PBEJA     5
A180C     5
M8500     5
JX02P     5
ZD31V     4
AACAJ     4
AAAAA     4
FU71J     4
BU71J     4
BT14R     4
BR32E     4
BR22E     4
BL9HE     4
Name: model, dtype: int64

In [238]:
bad_vds = vds_purity.index[0]

toyota[
    toyota["vds"] == bad_vds
]["model"].value_counts()

model
LAND CRUISER                      224
LAND CRUISER PICKUP 70            209
LAND CRUISER PICK UP              145
HILUX                              30
TUNDRA                              2
LAND CRUISER SINGLE-CABIN PICK      2
PICK UP CABIN                       1
RAV4                                1
LAND CRUISER/STD EX PICKUP          1
LAND CRUISER PICKUP                 1
Name: count, dtype: int64

In [239]:
toyota.groupby("vds")["trim"].nunique()

vds
00000     4
0000E     1
0000J     1
00098     1
000F2     1
000F9     1
000NC     1
000NN     1
00112     1
00260     1
00404     1
00612     1
00713     1
00800     1
00856     1
00898     1
00943     1
00968     1
00ACV     1
00KY6     1
00NCP     1
01035     1
01053     1
01098     1
01111     1
01302     1
01BUM     1
02290     1
022GD     1
03350     1
042TN     1
06622     1
06XZZ     2
0B9CB     1
0J4MC     1
0JX6C     1
0L000     1
0RV43     1
0SJ80     1
0X22G     1
0YSF1     1
10000     1
10007     1
10015     1
10030     1
10031     1
10252     3
10276     1
10701     1
10730     1
11005     1
11111     4
1111S     1
1111W     1
111S1     1
11AC1     1
11UJ8     7
11UJ9     1
11UJA     4
11VJ9     7
11WJA     4
12000     1
12001     2
12003     2
12004     1
12005     2
12007     1
1201D     2
1202F     1
1215C     1
12402     1
12H2P     1
14244     1
14252     3
14270     4
14545     1
14583     1
15002     1
15070     1
15100     2
15140     2
15151     1
17100     3
17255     1
17256     1
17257     1
17500     1
1779D     1
1AAA6     1
1AU93     1
1BAA3     3
1BURH     2
1CU83     3
1CUG3     1
1E33K     1
1F009     1
1FHPC     0
1HBJW     1
1KBBC     1
1KBBD     1
1KFCD     1
1KTP4     0
1L1HE     1
1N1EN     1
1YYK2     1
1ZH15     1
21090     1
213FV     3
21602     1
21603     1
21604     3
21605     1
21606     2
21608     3
21610     2
21AS3     1
21FCL     1
21SZZ     1
21UHB     1
21UJ7     1
22205     1
22206     1
25000     2
26BG7     1
2757D     1
2882K     1
2A119     1
2A22C     2
2A23C     2
2A29C     2
2EFV4     1
2F33V     1
2F9EV     3
2FREV     4
2HNAG     1
2K22C     1
2K23C     1
2K29C     1
2K31V     2
2K33V     1
2K3DC     1
2R119     1
2S010     1
2S011     1
2S012     1
2SBPB     1
2T14R     1
2T38A     1
2U14R     1
2Y64A     1
2Y68A     1
303H6     1
31RN8     2
31UJ7     3
31UNE     2
31UNG     2
31YN8     5
32BUM     4
33DVC     1
33RN8     2
33RNA     1
33UNE     2
33UNG     1
33YN8     1
35000     1
3546F     1
37418     1
37DE7     1
38122     1
38132     1
38BS1     1
3B007     1
3DXS5     1
3G22K     1
3K32E     1
3R22E     1
40420     1
40500     2
40503     2
408B0     1
41500     2
41501     2
41502     1
41503     1
41504     1
41BB4     1
41CB8     1
41E96     1
41UB5     1
41UHB     1
42010     1
42014     1
42015     1
42018     1
44925     4
45612     1
46405     1
46407     1
46470     2
46475     1
472AX     1
4E181     1
50012     1
50017     1
50018     2
50061     1
50090     1
50189     1
50229     1
50237     1
50258     1
50287     1
50296     1
50333     1
50391     1
50470     1
50479     1
50500     1
50501     1
50504     1
50524     1
50531     1
50602     1
50617     1
50637     1
50671     1
50812     1
50871     1
50873     1
50954     1
50975     2
51067     1
51102     1
51109     1
51116     1
51147     1
51149     1
51189     1
51211     1
51267     1
51303     1
51382     1
51390     1
51426     1
51452     1
51488     1
51500     1
51573     1
51611     1
51620     1
51622     1
51658     1
51680     1
51908     1
51940     1
51972     1
525AN     1
52AEA     1
52EEA     0
52EEB     1
52ZEB     1
534K2     1
535K2     1
53AEA     3
53AEB     3
53AFB     1
53EE8     1
53EEA     2
53EEB     1
53EL5     1
53JSF     1
53SK1     2
53SK2     2
53SV2     1
53XH1     1
53XK2     2
543AV     3
543BV     2
54EEA     1
56EZZ     1
56N8U     1
58557     1
59695     1
5AFKG     1
5C3AV     1
5D3BV     3
5DDDD     1
5WRFV     1
5X23P     3
60019     1
60023     1
61524     1
62101     1
63AL4     1
63AL5     1
64AEB     2
64EEB     1
64STL     1
65200     1
65203     1
65204     1
65213     1
65553     1
65610     1
65620     1
65651     1
65805     1
65910     1
65933     1
65934     1
66B3D     2
6AE3C     1
6D32M     1
6D52M     1
6D54M     1
6E52M     2
6H20V     1
6JKFW     1
6N87R     1
6W923     1
71000     1
715C1     1
71SC1    24
72AEA     3
72AEB     3
72EEA     1
72EEB     2
72SC1     2
72SK1     1
72SK2     2
72SV1     1
73FM4     1
75106     1
79END     2
79YND     1
7ANFU     2
7CNFU     1
7ENFU     3
7FNFU     1
7JNFU     1
7KE43     1
7LHEP     1
80000     1
80001     2
80003     1
80008     1
80015     1
80025     1
80042     1
80054     1
80063     1
80078     1
80095     1
80097     1
80125     1
80183     1
801FK     1
80233     1
80251     1
80274     1
80281     1
80282     1
80318     1
80328     1
80345     1
80350     1
80407     1
80413     1
80430     1
80459     1
80464     1
80473     1
80506     1
80532     1
80533     1
80548     1
80558     1
80583     1
80593     1
80636     1
80700     1
80761     1
80767     1
80772     1
80839     1
80850     1
80876     1
80890     1
80893     1
80907     1
80943     1
80950     1
80951     1
80986     1
80987     1
81018     1
811EB     1
811HK     2
813FV     1
814HK     3
819F3     1
819HK     1
8242E     1
824HK     5
829F3     3
829HK     2
855HZ     1
8622K     3
8628K     1
87367     1
87N07     1
8808E     1
880CE     2
8842E     1
8846K     2
889HE     4
88OCE     1
8A02E     2
8A08E     1
8A13E     1
8A23C     1
8A32K     1
8B9HE     1
8BCE1     1
8C42E     2
8CCVD     2
8CE1K     2
8D1FK     2
8D31V     3
8D33V     3
8D35E     1
8E30K     4
8E32K     4
8E33K     2
8E42K     6
8E46K     4
8F1FK     7
8F22K     2
8F28K     1
8F30K     3
8F31F     1
8F32K     2
8F38K     1
8F3EK     4
8F4DV     1
8F4FK     2
8F4HK     3
8F9C3     1
8F9EV     2
8F9FK     7
8F9HK     3
8FIFK     1
8FREV     1
8G22K     2
8J466     1
8J53L     1
8K1E8     2
8K1FK     1
8K22C     1
8K31V     2
8K32V     1
8K33V     1
8K368     3
8K36B     1
8K3D8     1
8K3DB     1
8K3EK     1
8K40K     1
8K46K     2
8K4FK     1
8L0HE     1
8L29J     2
8L9HE     6
8N95J     1
8R22E     2
8R23E     4
8R32E     3
8R42E     2
8RI2E     1
8T923     2
8T9F3     3
8U11F     5
8U25J     1
8U3FJ     5
8U40E     2
8U4EE     2
8U5CD     0
8U71J     1
8U8CD     2
8URHE     2
8V42E     1
8V541     1
8V71J     1
8W123     1
8W133     3
8W23E     4
8W923     4
8W933     1
8W9F3     1
8X8CD     1
8X9FJ     2
8Y561     1
8Y5F1     1
8Y64A     3
8Z4HK     2
90615     1
91900     1
91901     2
91902     2
91903     2
91908     1
93220     1
94403     2
95021     1
95403     2
9FD8T     1
A0B98     1
A11AK     1
A11CX     2
A11CY     1
A14AF     1
A14CK     9
A16E3     1
A1809     1
A180C    10
A1ACC     4
A1RFV     3
A22EZ     1
A22NE     1
A4B2A     2
A4B3A     6
A4B5A     1
A4CEA     2
A4CFA     3
A4DAA     3
A4DAC     1
A4DBA     1
A4DF5     1
A4DMA     1
A4GF5     3
A4MBE     1
A4RBE     1
A6426     2
A818Y     1
A878J     1
A888J     2
AA18A     2
AA1AB     1
AA1BA     6
AA5RX     1
AA7BJ     3
AA9AJ     7
AAA0C     7
AAAA5     1
AAAAA     4
AAAAF     2
AAAAG     3
AAAB5     1
AAABA     3
AAABG     3
AAADC     1
AAAOC     1
AABAJ     1
AABBJ     6
AACAJ    10
AACBJ     4
AAIBA     1
AALAJ     1
AAN6E     1
AATBA     1
AAYAJ     1
AB18Y     1
AB1BA     3
AB1BY     3
AB36U     1
AB7BJ    10
AB7RJ     1
ABBAA     4
ABBBJ    14
ABBDH     1
ABCBJ     9
ABFAJ     1
ABIBY     0
AC11R     1
AC1DM     2
AC22C     2
AC7BJ     2
ACAAJ     1
ACAAU     4
ACAB5     1
ACABA     1
ACABB     1
ACABF     4
ACJ4H     1
ADAE2     1
AE00B     3
AE00E     2
AE04B     4
AE04E     3
AE07B     1
AE09B     4
AE09E     2
AE09V     3
AE09W     2
AE1BY     1
AE1EY     1
AE2KP     1
AE51S     1
AE525     1
AE52S     3
AE53S     1
AE54S     2
AE82G     1
AE94A     1
AE94K     1
AEAA1     1
AEACH     2
AECB8     4
AECG2     1
AECG3     1
AF047     1
AF4CB     1
AF4E3     4
AF54K     1
AFAAF     3
AFABF     1
AFCG2     3
AFZBG     1
AG20A     1
AG30A     1
AG34L     7
AG426     3
AG4CK     8
AGACH     1
AGNAC     1
AI4CK     1
AJ54K     1
AK54K     1
AKCB8     1
AL1CC     5
AL29J     3
AM11H     2
AM29J     2
AM2AH     1
AM450     1
AM496     1
AM498     1
AN74K     1
AN95J     3
AP22C     5
AP54K     2
AP86C     4
AP90A     1
APE2C     1
AR05Y     1
AR9AJ     1
ARCAJ     1
ARE0C     5
ARE2C     1
AS02A     2
AS02D     2
AS123     1
AS12G     1
AS14U     1
AS47H     1
ASACK     1
ASB3R     2
ASG0A     1
ASW0A     2
AT123     1
AT2MV     1
AU25J     2
AU78J     2
AU7BJ     8
AU88J     5
AUBB3     1
AUBBJ    16
AUCBJ    11
AUF0A     1
AUTBJ     1
AUZBJ     1
AVV5F     1
AW126     1
AW12G     3
AW5F1     1
AX126     2
AX12G     2
AX5GN     1
AX8CD     1
AXACC     2
AY117     3
AY2NY     1
AY5F1     1
AY86C     1
AYACC     4
AYT30     1
AZ1FB     1
AZ496     2
AZ5CN     2
B0111     1
B011F     1
B025J     1
B031V     1
B03FV     1
B046K     1
B11HK     6
B13FV     5
B14HK     5
B19F3     2
B19HK     5
B1B0E     6
B1DWA     1
B1RFV     3
B21FB     3
B21HK     3
B23HK     1
B242E     1
B24HK     4
B28F3     1
B29F3     8
B29HK    10
B29M3     1
B2E6K     3
B2NBA     1
B2NWA     1
B308E     1
B30BE     4
B30EE     5
B31HK     2
B3E6P     2
B3FE1     2
B3G6P     1
B3J6P     5
B4B9E     3
B4MBE     3
B4MDE     5
B4MEE     1
B4RBE     2
B519E     3
B61HK     4
B622K     3
B674K     1
B6RFV     1
B7A2J     1
B89HE     1
BA01E     3
BA02E     9
BA03E     2
BA05E     3
BA0BE     7
BA13E     3
BA1HK     1
BA22C     2
BA23C     2
BA244     1
BA2A9     1
BA30K     3
BA32K     4
BA3BB     1
BA3BE     2
BA8CD     1
BAAAG     1
BAABG     1
BACEK     2
BADBA     1
BAMDE     1
BAOBE     3
BAYV5     1
BB02E     9
BB03E     1
BB08E     1
BB0BB     1
BB0BE    17
BB0CE     5
BB12E     3
BB13E     3
BB3EK     5
BB3JE     1
BB42E     1
BB46K     3
BB71J     1
BB8CD     1
BB9BE     1
BB9HE    19
BB9JE     1
BBBEX     2
BBDEE     1
BBE32     1
BBN2A     1
BBOBE    11
BBOCE     3
BBRCH     2
BBSHE     2
BC11E     1
BC42E     8
BC42R     1
BC53L     1
BC74K     2
BC81S     1
BCE1J     4
BCE1K     1
BCE6J     1
BCELK     1
BD0CT     1
BD0FA     1
BD1EB     7
BD1FK     8
BD23S     1
BD317     1
BD31V     9
BD32V     2
BD337     1
BD33V     4
BD35V     2
BD74K     1
BD9EV     1
BD9FJ     1
BDF1J     1
BDIEB     1
BDMHE     1
BDOES     1
BE23K     3
BE24K     1
BE30K     8
BE32K    12
BE33K     4
BE36K     1
BE38K     2
BE3EK     2
BE40E     1
BE40K     3
BE42J     1
BE42K    13
BE42k     1
BE44K     1
BE46K     4
BE4EE     2
BE4GK     1
BE6AS     2
BE6BS     7
BE6CS     1
BE6DS     6
BE85B     1
BE9B3     2
BE9FK     3
BE9HE     1
BECEK     1
BF0BE     3
BF0JE     4
BF12B     1
BF12K     3
BF18B     2
BF1FK     8
BF22K     5
BF23K     2
BF28B     3
BF28K     3
BF30K     7
BF31E     2
BF31F     2
BF31V     1
BF32K     8
BF32V     1
BF32X     1
BF33V     1
BF35V     1
BF38K     4
BF3EK     8
BF3FK     1
BF3HK     1
BF3JE     1
BF46K     1
BF4DV     2
BF4FK     8
BF4HK     5
BF5C2     1
BF6C3     1
BF8C3     1
BF9C3     5
BF9EV     7
BF9FK    13
BF9FR     1
BF9HK     4
BF9JE     6
BFIFK     2
BFREV     4
BFTFK     1
BG12K     6
BG17K     1
BG21K     1
BG22K    10
BG23K     4
BG28K     5
BH2AW     1
BH42K     3
BH96S     1
BH9FJ     3
BHJ6S     1
BJ13E     2
BJ18U     1
BJ22K     1
BJ335     1
BJ53L     3
BJE23     1
BJI3E     1
BJRBZ     1
BK1E8     1
BK1EB     7
BK1FK     7
BK22C     1
BK23C     1
BK262     1
BK29J     1
BK31V     3
BK326     1
BK32V     2
BK33V     3
BK34V     3
BK35B     1
BK35V     2
BK368     2
BK36B     8
BK3BB     1
BK3DB     4
BK3EH     2
BK3EK     3
BK40K     7
BK42K     3
BK46K     5
BK4DV     2
BK4FK     5
BK4SK     1
BKIEB     2
BKRFH     2
BL00E     1
BL0HE     1
BL293     1
BL29J     5
BL40E     1
BL42E     2
BL4A9     1
BL8HE     1
BL9HE    17
BL9HF     1
BLGHE     1
BLIHK     1
BLSHE     2
BM000     1
BM29J     2
BM82F     1
BM99J     5
BN30F     1
BN36F     1
BN441     2
BN95J     4
BPB9E     6
BPMBE     2
BPRBE     2
BPRHE     4
BPWDG     1
BR12E     2
BR18E     1
BR22E    10
BR22F     1
BR23E    10
BR28E     1
BR30E     3
BR32E    11
BR38E     5
BR406     1
BR40E     1
BR42E     4
BR43E     1
BR9FJ     1
BRKEC     2
BRZ3E     1
BT05Y     1
BT123     5
BT14R     7
BT17R     4
BT223     1
BT2MW     1
BT3AA     1
BT3AB     1
BT441    10
BT44A     3
BT481     6
BT48A     3
BT4K3     3
BT541     1
BT581     1
BT64A     1
BT69Y     1
BT903     3
BT923     6
BT9F3    13
BT9K3     1
BU&CD     1
BU01F     1
BU11E     1
BU11F    10
BU11J     1
BU14R    11
BU17R     4
BU250     1
BU253     2
BU258     1
BU25J     8
BU26J     1
BU29J     1
BU300     1
BU3AE     1
BU3EJ     1
BU3FJ    15
BU40E     1
BU4BF     3
BU4EE     5
BU585     2
BU5IF     1
BU5JR     4
BU71J     6
BU8CD     8
BU8F5     1
BU8FS     4
BU9FJ    10
BUBFS     2
BUIIF     1
BUJFJ     2
BUL1F     1
BURHE     9
BURNE     1
BUSCD     1
BUSFJ     2
BUSFS     3
BUT1F     1
BUTIF     1
BUTTF     2
BV426     1
BV42E     6
BV541     1
BV581     1
BV61E     1
BV71J     5
BVV13     1
BVV92     1
BW023     1
BW123     3
BW12S     3
BW133     3
BW1GG     1
BW22E     3
BW23E     9
BW3FV     5
BW541     1
BW581     1
BW5F1     1
BW5G1     4
BW6F3     1
BW923     8
BW933     2
BW9F3     3
BW9F4     1
BX3FJ     4
BX8C0     1
BX8CD    13
BX9F1     1
BX9FJ    10
BXBCD     2
BY11F     2
BY30E     1
BY32E     1
BY5F1     1
BY5G1     6
BY64A     7
BY67A     4
BY68A     6
BY809     1
BY80E     7
BY84A     2
BY879     2
BY99J     1
BYBDE     1
BZ1FB     7
BZ1HK     3
BZ28E     2
BZ42E     4
BZ42F     1
BZ4HK    20
BZ4ZE     1
BZ9F3     1
BZAHK     7
BZRFH     2
C08RW     1
C11AK     9
C11BK     1
C1RFV     3
C21FB     1
C25AN     1
C2ZWB     4
C31AK     2
C4MBE     3
C4RBE     1
C616Z     2
C618X     1
C74C4     1
C8E2H     1
C916Z     2
CA217     2
CA21A     1
CA30P     1
CA31A     1
CA38P     2
CA50A     1
CAAAG     1
CAABG     2
CAAGA     1
CB09J     3
CB337     3
CB3FV     1
CBAGA     2
CC13C     1
CC1BR     3
CC1CX     1
CC42H     1
CDUD2     1
CE22P     1
CE38P     2
CECB8     5
CF22P     2
CF28P     1
CG12K     1
CGE23     2
CH5CP     1
CIRFV     1
CJ6B1     1
CJE23     3
CJE73     2
CK12G     1
CL968     1
CM565     1
CP450     1
CP515     3
CP724     1
CPA50     1
CRKEC     1
CS12G     1
CS18Z     2
CT05J     1
CU09J     3
CU18R     1
CU1BR     5
CU923     2
CV12G     1
CV1F4     1
CV52B     1
CV541     1
CW126     3
CW12G     8
CW5F1     1
CW6C8     2
CW6CB     1
CW6CD     2
CW8BB     2
CW8C8     1
CW8CB     4
CW8CD     2
CW9CB     2
CW9CD     1
CX0CD     1
CX126     3
CX12G     6
CX190     1
CX196     1
CX19G     7
CX3DD     1
CX3FJ     4
CX6CB     3
CX6CD     3
CX8C8     1
CX8CB     4
CX8CD     4
CX8EM     7
CX8GS     2
CX9C8     1
CX9CB     8
CX9CD     8
CX9FJ     4
CXBEM     1
CXI9G     1
CY5F1     1
CY7AJ     2
CZ5AN     9
CZRAH     2
D13FV     1
D156F     1
D1RFV     1
D23DC     1
D258N     1
D2DF6     1
D3135     6
D3DF6     2
D4MBE     7
D4RBE     1
D541A     1
D6RFV     1
D89CD     1
DA1AB     1
DA31A     1
DAAAG     1
DAABG     2
DAACK     3
DAR9K     1
DARTK     1
DB0A0     2
DB0AO     1
DB0C0     2
DB0E0     4
DB0G0     2
DB12E     2
DB21B     1
DB24B     1
DB2A0     1
DB2C0     2
DB41S     1
DB4A0     1
DB4C0     1
DB6CD     1
DB8CD     2
DB8FS     2
DB9CB     4
DB9CD     8
DBADK     1
DBE32     1
DBOE0     1
DBR22     1
DBSCD     1
DBWG3     1
DBYSV     1
DBZSV     5
DCRFH     1
DD21A     1
DD22S     1
DD23S     1
DD2EY     1
DD82A     1
DE32K     1
DE4EV     1
DE626     2
DE82A     1
DF4DV     3
DF4EB     1
DF4EU     1
DF4EV     5
DF9EV     6
DFAEV     1
DFREV     5
DG61E     1
DGRFH     1
DH4CD     1
DH88W     1
DH88X     1
DJ81W     2
DJREV     2
DK3DC     4
DK3EH     2
DK4CC     1
DK4DV     2
DKJA0     2
DKW9D     1
DL25R     1
DL39M     1
DLBJV     1
DLBYV     3
DM5F1     1
DM626     2
DN136     2
DN56A     1
DP21A     3
DPMAE     3
DPRAE     4
DR32T     3
DS41A     1
DS43A     1
DSKFC     1
DT3MW     1
DT441     1
DT481     1
DT541     1
DTPUK     1
DU09J    10
DU09T     1
DV09J     1
DV541     1
DV581     1
DW11S     2
DW12S     4
DW3FV     6
DW51E     1
DW541     1
DW5F1     1
DW5G1     3
DW923     1
DWRFV     2
DWSF1     1
DX1H2     1
DX226     2
DX22G     7
DX6CB     1
DX6CD     3
DX8CD     4
DX8F5     5
DX8FS     8
DX9CB     1
DX9CD     8
DXBCD     1
DXBFS     1
DY32T     1
DY38T     1
DY5F1     1
DY5G1     4
DYSF1     1
DZ1FB     1
DZ3DC     2
DZ5BN     2
DZ626     2
DZK23     1
DZRBH     3
DZRFH     1
DZSBN     1
E1EE0     1
E1NFJ     1
E2815     1
E29F3     1
E4FDB     1
E6A3U     1
E6RFV     2
E8017     1
EA6BX     1
EAAAG     1
EAMDE     3
EB02E     2
EB0BE     1
EB13E     2
EB71J     3
EB73J     2
EBOBE     1
EBRBE     1
EBRCH     1
EC42E     1
ECABA     1
ED1EK     1
ED31V     1
ED3KA     1
ED9HP     1
EDABB     2
EE32K     1
EE426     1
EE9HE     1
EF12K     2
EF4HK     1
EF76A     2
EF88F     4
EF8BF     7
EF8C3     1
EF8CF     2
EF9FK     2
EFABF     1
EFAVS     1
EFBBF     2
EFBC3     1
EFBCF     2
EFHCF     1
EFSBF     2
EG12K     1
EG21K     1
EG22K     5
EG23K     2
EG425     1
EG426     3
EGCBB     1
EJ13E     2
EJ5CD     1
EK12G     1
EK12T     1
EK19T     1
EL33P     1
EM426     2
EM42G     1
EM496     2
EM5F1     1
EN61S     1
ENE0R     1
ENKA5     1
EPMAE     5
EPRAE     2
ER21E     1
ER22E     2
ER23E     6
ER33P     1
ER42E     1
ES12G     2
ES41A     1
ES43A     1
ES46A     1
ET341     1
ET381     1
ET923     1
ET9F3     1
EU11F     3
EU3FJ     1
EU5JR     1
EU73J     3
EV541     1
EV581     1
EV73J     2
EW126     2
EW12G     8
EW1EP     1
EW21A     2
EW22E     1
EW23E     5
EW41A     1
EW44A     4
EW5F1     1
EW923     2
EWIE5     1
EWRFV     1
EX120     1
EX126     3
EX12G     8
EX196     2
EX19G     6
EX1E6     1
EX22G     1
EX28E     1
EX91G     1
EY5F1     1
EY64A     1
EZ20E     3
EZ28E     4
EZ3DC     1
EZ426     2
EZ42E     1
EZ496     2
F11AK     3
F11BK     1
F1RFV     3
F31AK     5
F6RDM     1
F7D19     1
F7E69     1
FA119     1
FA38P     1
FA903     1
FARAH     1
FB518     7
FB718     1
FBABG     3
FBW41     1
FC24H     1
FC518     1
FD3HL     1
FDA88     1
FDAB8     1
FDABB     1
FE22P     1
FE52S     2
FE53S     1
FE54S     1
FE718     2
FE728     2
FF22P     1
FF41C     1
FF719     1
FG15T     1
FG426     1
FG8JP     2
FH3CB     1
FIRFV     1
FJ60G     2
FJ60V     1
FJ71J     5
FK122     1
FK418     7
FK518     6
FK718     3
FM418     6
FM518    10
FP14F     1
FP518     2
FPEFF     1
FPMAE     1
FPRAE     1
FR119     2
FR226     2
FR22G     5
FR320     3
FR73J     1
FU5JR     1
FU71J    12
FU73J     3
FV47V     1
FW12G     1
FX00G     1
FX02P     1
FX226     3
FX22C     2
FX22G     9
FX22P     1
FY418     7
FY5A1     1
FY5B1     1
FY5F1     1
FZ1FB     2
FZ29G     1
FZ418     1
FZRBH     3
G0EE9     1
G11AK     6
G11BK     1
G13FV     1
G14DA     1
G1RFV     2
G31AK     1
G4AC1     1
G4BC1     1
G4X20     2
G5GC1     1
G622K     1
G6X40     1
GA17E     1
GA17F     2
GA17H     1
GARAH     1
GBKFW     1
GBRCH     3
GD20V     2
GD21A     1
GD32M     2
GD34M     2
GD52M     2
GD54M     4
GE17F     1
GE52M     6
GES2M     1
GF46X     1
GF4JB     1
GG25K     1
GGG56     1
GH20V     1
GJ211     1
GJKFW     2
GK12E     1
GK13E     2
GK26H     1
GN86R     1
GN87R     4
GNP03     1
GP10V     4
GP21A     2
GR4A6     1
GRKEC     1
GS54M     2
GSKFC     1
GU09J     2
GU4L3     1
GW5F1     1
GX72A     1
GX8CD     1
GX8EM     4
GXSEM     1
GY5F1     1
GZ1FB     1
GZ3DH     2
GZ5AN     1
GZRAH     2
GZRBH     5
H0093     1
H009J     2
H109J     1
H1RFV     3
H25ZZ     1
H3093     1
H309J     1
H4ACP     2
H4BCP     1
H545G     1
HA3CD     1
HAP53     2
HAP5J     1
HAP73     1
HB10V     1
HB8CD     2
HB9CP     1
HC05J     2
HD17F     4
HD20V     2
HD21A     1
HD23S     1
HDAAA     1
HEJ1F     1
HF10U     1
HG09G     1
HG17C     3
HG39K     1
HH20V     6
HJ01J     8
HJ05J     1
HJ08J     2
HJ091     2
HJ093     4
HJ09J     9
HJ0SJ     1
HJ59J     1
HJ85J     4
HJO9J     2
HJQ8J     1
HJXEN     2
HK31U     0
HN86R     3
HN87R     4
HN9CP     8
HNICP     1
HNP13     1
HNP6N     1
HNW6N     1
HP10V     7
HPRAE     2
HR33N     1
HS02P     3
HT051     3
HT053     6
HT05J    16
HT06J     1
HT093     4
HT09J    13
HT0SJ     3
HT523     1
HTO5J     3
HTOSJ     2
HU01J     5
HU08J     1
HU091     3
HU093     6
HU09J    16
HU5JR     1
HU8CD     6
HUD3J     1
HUD9J     1
HUOTJ     1
HV01J     3
HV05J     1
HV09J     5
HW21A     1
HW2ZZ     2
HW31U     1
HW5F1     1
HX013     1
HX01J     8
HX02J     1
HX02P    16
HX05J     6
HX07P     1
HX091     1
HX093     2
HX09J     7

In [240]:
toyota.groupby("vds")["bodyType"].nunique()

vds
00000     4
0000E     1
0000J     1
00098     1
000F2     1
000F9     1
000NC     1
000NN     1
00112     1
00260     1
00404     1
00612     1
00713     1
00800     1
00856     1
00898     1
00943     1
00968     1
00ACV     1
00KY6     1
00NCP     1
01035     1
01053     1
01098     1
01111     1
01302     1
01BUM     1
02290     1
022GD     1
03350     1
042TN     1
06622     1
06XZZ     2
0B9CB     1
0J4MC     1
0JX6C     1
0L000     1
0RV43     1
0SJ80     1
0X22G     1
0YSF1     1
10000     1
10007     1
10015     1
10030     1
10031     1
10252     1
10276     1
10701     1
10730     1
11005     1
11111     4
1111S     1
1111W     1
111S1     1
11AC1     1
11UJ8     2
11UJ9     1
11UJA     1
11VJ9     2
11WJA     1
12000     1
12001     1
12003     2
12004     1
12005     2
12007     1
1201D     1
1202F     1
1215C     1
12402     1
12H2P     1
14244     1
14252     2
14270     3
14545     1
14583     1
15002     1
15070     1
15100     2
15140     2
15151     1
17100     2
17255     1
17256     1
17257     1
17500     1
1779D     1
1AAA6     1
1AU93     1
1BAA3     3
1BURH     1
1CU83     3
1CUG3     1
1E33K     1
1F009     1
1FHPC     1
1HBJW     1
1KBBC     1
1KBBD     1
1KFCD     1
1KTP4     1
1L1HE     1
1N1EN     1
1YYK2     1
1ZH15     1
21090     1
213FV     2
21602     1
21603     1
21604     3
21605     1
21606     2
21608     2
21610     1
21AS3     1
21FCL     1
21SZZ     1
21UHB     2
21UJ7     1
22205     1
22206     1
25000     1
26BG7     1
2757D     1
2882K     1
2A119     1
2A22C     1
2A23C     1
2A29C     1
2EFV4     1
2F33V     1
2F9EV     1
2FREV     1
2HNAG     1
2K22C     1
2K23C     1
2K29C     1
2K31V     1
2K33V     1
2K3DC     1
2R119     1
2S010     1
2S011     1
2S012     1
2SBPB     1
2T14R     1
2T38A     1
2U14R     1
2Y64A     1
2Y68A     1
303H6     1
31RN8     1
31UJ7     4
31UNE     3
31UNG     1
31YN8     5
32BUM     2
33DVC     1
33RN8     2
33RNA     1
33UNE     3
33UNG     1
33YN8     3
35000     1
3546F     1
37418     1
37DE7     1
38122     1
38132     1
38BS1     1
3B007     1
3DXS5     1
3G22K     1
3K32E     1
3R22E     1
40420     1
40500     1
40503     1
408B0     1
41500     1
41501     1
41502     1
41503     1
41504     1
41BB4     1
41CB8     1
41E96     1
41UB5     1
41UHB     1
42010     1
42014     1
42015     1
42018     1
44925     3
45612     1
46405     1
46407     1
46470     2
46475     1
472AX     1
4E181     1
50012     1
50017     1
50018     1
50061     1
50090     1
50189     1
50229     1
50237     1
50258     1
50287     1
50296     1
50333     1
50391     1
50470     1
50479     1
50500     1
50501     1
50504     1
50524     1
50531     1
50602     1
50617     1
50637     1
50671     1
50812     1
50871     1
50873     1
50954     1
50975     1
51067     1
51102     1
51109     1
51116     1
51147     1
51149     1
51189     1
51211     1
51267     1
51303     1
51382     1
51390     1
51426     1
51452     1
51488     1
51500     1
51573     1
51611     1
51620     1
51622     1
51658     1
51680     1
51908     1
51940     1
51972     1
525AN     1
52AEA     1
52EEA     1
52EEB     1
52ZEB     1
534K2     1
535K2     1
53AEA     3
53AEB     2
53AFB     1
53EE8     1
53EEA     3
53EEB     1
53EL5     1
53JSF     1
53SK1     2
53SK2     1
53SV2     1
53XH1     1
53XK2     1
543AV     1
543BV     1
54EEA     1
56EZZ     1
56N8U     1
58557     1
59695     1
5AFKG     1
5C3AV     1
5D3BV     1
5DDDD     1
5WRFV     1
5X23P     3
60019     1
60023     1
61524     1
62101     1
63AL4     1
63AL5     1
64AEB     1
64EEB     1
64STL     1
65200     1
65203     1
65204     1
65213     1
65553     1
65610     1
65620     1
65651     1
65805     1
65910     1
65933     1
65934     1
66B3D     2
6AE3C     1
6D32M     1
6D52M     2
6D54M     1
6E52M     1
6H20V     1
6JKFW     1
6N87R     1
6W923     1
71000     1
715C1     1
71SC1     3
72AEA     2
72AEB     1
72EEA     1
72EEB     1
72SC1     1
72SK1     2
72SK2     1
72SV1     1
73FM4     1
75106     1
79END     3
79YND     1
7ANFU     2
7CNFU     1
7ENFU     3
7FNFU     1
7JNFU     1
7KE43     1
7LHEP     1
80000     2
80001     2
80003     1
80008     1
80015     1
80025     1
80042     1
80054     1
80063     1
80078     1
80095     1
80097     1
80125     1
80183     1
801FK     1
80233     1
80251     1
80274     1
80281     1
80282     1
80318     1
80328     1
80345     1
80350     1
80407     1
80413     1
80430     1
80459     1
80464     1
80473     1
80506     1
80532     1
80533     1
80548     1
80558     1
80583     1
80593     1
80636     1
80700     1
80761     1
80767     1
80772     1
80839     1
80850     1
80876     1
80890     1
80893     1
80907     1
80943     1
80950     1
80951     1
80986     1
80987     1
81018     1
811EB     1
811HK     1
813FV     1
814HK     2
819F3     1
819HK     1
8242E     1
824HK     2
829F3     4
829HK     1
855HZ     1
8622K     1
8628K     1
87367     1
87N07     1
8808E     1
880CE     2
8842E     1
8846K     1
889HE     2
88OCE     1
8A02E     1
8A08E     1
8A13E     1
8A23C     1
8A32K     1
8B9HE     1
8BCE1     1
8C42E     1
8CCVD     2
8CE1K     2
8D1FK     1
8D31V     1
8D33V     1
8D35E     1
8E30K     2
8E32K     1
8E33K     2
8E42K     2
8E46K     1
8F1FK     1
8F22K     2
8F28K     1
8F30K     1
8F31F     1
8F32K     1
8F38K     1
8F3EK     1
8F4DV     1
8F4FK     1
8F4HK     2
8F9C3     1
8F9EV     1
8F9FK     2
8F9HK     2
8FIFK     1
8FREV     1
8G22K     1
8J466     1
8J53L     1
8K1E8     2
8K1FK     1
8K22C     1
8K31V     1
8K32V     1
8K33V     1
8K368     1
8K36B     1
8K3D8     1
8K3DB     1
8K3EK     1
8K40K     1
8K46K     1
8K4FK     1
8L0HE     1
8L29J     1
8L9HE     2
8N95J     1
8R22E     2
8R23E     2
8R32E     1
8R42E     1
8RI2E     1
8T923     2
8T9F3     2
8U11F     1
8U25J     1
8U3FJ     2
8U40E     1
8U4EE     1
8U5CD     1
8U71J     1
8U8CD     1
8URHE     2
8V42E     1
8V541     2
8V71J     1
8W123     1
8W133     1
8W23E     2
8W923     2
8W933     1
8W9F3     1
8X8CD     1
8X9FJ     1
8Y561     1
8Y5F1     1
8Y64A     2
8Z4HK     1
90615     1
91900     2
91901     2
91902     2
91903     2
91908     1
93220     1
94403     3
95021     1
95403     2
9FD8T     1
A0B98     1
A11AK     1
A11CX     1
A11CY     1
A14AF     1
A14CK     2
A16E3     1
A1809     1
A180C     4
A1ACC     1
A1RFV     1
A22EZ     1
A22NE     1
A4B2A     2
A4B3A     2
A4B5A     1
A4CEA     2
A4CFA     3
A4DAA     3
A4DAC     1
A4DBA     1
A4DF5     1
A4DMA     1
A4GF5     3
A4MBE     1
A4RBE     1
A6426     1
A818Y     1
A878J     2
A888J     1
AA18A     1
AA1AB     1
AA1BA     1
AA5RX     1
AA7BJ     1
AA9AJ     1
AAA0C     2
AAAA5     1
AAAAA     3
AAAAF     1
AAAAG     1
AAAB5     1
AAABA     2
AAABG     2
AAADC     1
AAAOC     1
AABAJ     1
AABBJ     1
AACAJ     1
AACBJ     1
AAIBA     1
AALAJ     1
AAN6E     1
AATBA     1
AAYAJ     1
AB18Y     1
AB1BA     1
AB1BY     3
AB36U     1
AB7BJ     1
AB7RJ     1
ABBAA     2
ABBBJ     2
ABBDH     1
ABCBJ     1
ABFAJ     1
ABIBY     1
AC11R     1
AC1DM     2
AC22C     1
AC7BJ     1
ACAAJ     1
ACAAU     2
ACAB5     1
ACABA     1
ACABB     1
ACABF     1
ACJ4H     1
ADAE2     1
AE00B     1
AE00E     1
AE04B     1
AE04E     1
AE07B     1
AE09B     1
AE09E     1
AE09V     1
AE09W     1
AE1BY     1
AE1EY     1
AE2KP     1
AE51S     1
AE525     1
AE52S     2
AE53S     1
AE54S     1
AE82G     1
AE94A     1
AE94K     1
AEAA1     1
AEACH     2
AECB8     2
AECG2     1
AECG3     1
AF047     1
AF4CB     1
AF4E3     4
AF54K     1
AFAAF     1
AFABF     1
AFCG2     2
AFZBG     1
AG20A     1
AG30A     1
AG34L     4
AG426     4
AG4CK     1
AGACH     1
AGNAC     1
AI4CK     1
AJ54K     1
AK54K     1
AKCB8     1
AL1CC     1
AL29J     1
AM11H     1
AM29J     1
AM2AH     1
AM450     1
AM496     2
AM498     1
AN74K     1
AN95J     2
AP22C     1
AP54K     2
AP86C     2
AP90A     1
APE2C     1
AR05Y     1
AR9AJ     1
ARCAJ     1
ARE0C     2
ARE2C     1
AS02A     2
AS02D     2
AS123     1
AS12G     1
AS14U     1
AS47H     1
ASACK     1
ASB3R     2
ASG0A     1
ASW0A     2
AT123     1
AT2MV     1
AU25J     1
AU78J     2
AU7BJ     1
AU88J     2
AUBB3     1
AUBBJ     2
AUCBJ     1
AUF0A     1
AUTBJ     1
AUZBJ     1
AVV5F     1
AW126     2
AW12G     4
AW5F1     2
AX126     2
AX12G     3
AX5GN     1
AX8CD     1
AXACC     1
AY117     2
AY2NY     1
AY5F1     2
AY86C     1
AYACC     2
AYT30     1
AZ1FB     1
AZ496     2
AZ5CN     1
B0111     1
B011F     1
B025J     1
B031V     1
B03FV     1
B046K     1
B11HK     1
B13FV     1
B14HK     3
B19F3     2
B19HK     1
B1B0E     1
B1DWA     1
B1RFV     1
B21FB     1
B21HK     3
B23HK     1
B242E     1
B24HK     1
B28F3     1
B29F3     4
B29HK     2
B29M3     1
B2E6K     2
B2NBA     1
B2NWA     1
B308E     1
B30BE     1
B30EE     1
B31HK     1
B3E6P     1
B3FE1     2
B3G6P     1
B3J6P     3
B4B9E     1
B4MBE     1
B4MDE     1
B4MEE     1
B4RBE     1
B519E     1
B61HK     1
B622K     1
B674K     1
B6RFV     1
B7A2J     1
B89HE     1
BA01E     2
BA02E     2
BA03E     2
BA05E     1
BA0BE     3
BA13E     1
BA1HK     1
BA22C     2
BA23C     2
BA244     1
BA2A9     1
BA30K     1
BA32K     1
BA3BB     1
BA3BE     1
BA8CD     3
BAAAG     1
BAABG     1
BACEK     1
BADBA     1
BAMDE     1
BAOBE     3
BAYV5     1
BB02E     3
BB03E     1
BB08E     1
BB0BB     1
BB0BE     4
BB0CE     1
BB12E     1
BB13E     2
BB3EK     1
BB3JE     1
BB42E     1
BB46K     1
BB71J     1
BB8CD     1
BB9BE     1
BB9HE     2
BB9JE     1
BBBEX     1
BBDEE     1
BBE32     1
BBN2A     1
BBOBE     4
BBOCE     2
BBRCH     1
BBSHE     1
BC11E     1
BC42E     2
BC42R     1
BC53L     1
BC74K     2
BC81S     1
BCE1J     2
BCE1K     1
BCE6J     1
BCELK     1
BD0CT     1
BD0FA     1
BD1EB     1
BD1FK     1
BD23S     1
BD317     1
BD31V     3
BD32V     1
BD337     1
BD33V     1
BD35V     1
BD74K     1
BD9EV     1
BD9FJ     1
BDF1J     1
BDIEB     1
BDMHE     1
BDOES     1
BE23K     1
BE24K     1
BE30K     1
BE32K     3
BE33K     1
BE36K     1
BE38K     2
BE3EK     1
BE40E     1
BE40K     2
BE42J     1
BE42K     3
BE42k     1
BE44K     1
BE46K     2
BE4EE     1
BE4GK     1
BE6AS     3
BE6BS     6
BE6CS     1
BE6DS     5
BE85B     1
BE9B3     1
BE9FK     1
BE9HE     1
BECEK     2
BF0BE     2
BF0JE     2
BF12B     1
BF12K     1
BF18B     2
BF1FK     2
BF22K     2
BF23K     1
BF28B     1
BF28K     1
BF30K     2
BF31E     2
BF31F     3
BF31V     1
BF32K     2
BF32V     1
BF32X     1
BF33V     1
BF35V     1
BF38K     1
BF3EK     2
BF3FK     1
BF3HK     1
BF3JE     1
BF46K     1
BF4DV     1
BF4FK     3
BF4HK     2
BF5C2     1
BF6C3     1
BF8C3     1
BF9C3     1
BF9EV     2
BF9FK     3
BF9FR     1
BF9HK     2
BF9JE     2
BFIFK     1
BFREV     1
BFTFK     1
BG12K     3
BG17K     1
BG21K     1
BG22K     2
BG23K     1
BG28K     1
BH2AW     1
BH42K     2
BH96S     1
BH9FJ     1
BHJ6S     1
BJ13E     1
BJ18U     1
BJ22K     1
BJ335     1
BJ53L     2
BJE23     1
BJI3E     1
BJRBZ     1
BK1E8     1
BK1EB     3
BK1FK     1
BK22C     2
BK23C     2
BK262     1
BK29J     1
BK31V     1
BK326     1
BK32V     1
BK33V     1
BK34V     1
BK35B     1
BK35V     1
BK368     1
BK36B     2
BK3BB     1
BK3DB     1
BK3EH     1
BK3EK     1
BK40K     2
BK42K     1
BK46K     1
BK4DV     1
BK4FK     1
BK4SK     1
BKIEB     1
BKRFH     1
BL00E     1
BL0HE     1
BL293     1
BL29J     1
BL40E     1
BL42E     1
BL4A9     1
BL8HE     1
BL9HE     4
BL9HF     1
BLGHE     1
BLIHK     1
BLSHE     1
BM000     1
BM29J     1
BM82F     1
BM99J     2
BN30F     1
BN36F     1
BN441     2
BN95J     1
BPB9E     1
BPMBE     2
BPRBE     1
BPRHE     1
BPWDG     1
BR12E     2
BR18E     1
BR22E     4
BR22F     1
BR23E     4
BR28E     1
BR30E     1
BR32E     5
BR38E     4
BR406     1
BR40E     2
BR42E     1
BR43E     1
BR9FJ     1
BRKEC     1
BRZ3E     1
BT05Y     1
BT123     1
BT14R     2
BT17R     2
BT223     1
BT2MW     1
BT3AA     1
BT3AB     1
BT441     9
BT44A     2
BT481     3
BT48A     1
BT4K3     2
BT541     2
BT581     1
BT64A     1
BT69Y     1
BT903     2
BT923     2
BT9F3     5
BT9K3     1
BU&CD     1
BU01F     1
BU11E     1
BU11F     2
BU11J     1
BU14R     3
BU17R     2
BU250     1
BU253     1
BU258     1
BU25J     1
BU26J     1
BU29J     1
BU300     1
BU3AE     1
BU3EJ     1
BU3FJ     1
BU40E     2
BU4BF     1
BU4EE     2
BU585     1
BU5IF     1
BU5JR     1
BU71J     6
BU8CD     4
BU8F5     1
BU8FS     1
BU9FJ     1
BUBFS     2
BUIIF     1
BUJFJ     1
BUL1F     1
BURHE     4
BURNE     1
BUSCD     1
BUSFJ     1
BUSFS     1
BUT1F     1
BUTIF     1
BUTTF     1
BV426     1
BV42E     2
BV541     2
BV581     2
BV61E     1
BV71J     4
BVV13     1
BVV92     1
BW023     1
BW123     1
BW12S     2
BW133     1
BW1GG     1
BW22E     2
BW23E     5
BW3FV     1
BW541     1
BW581     1
BW5F1     2
BW5G1     1
BW6F3     2
BW923     3
BW933     2
BW9F3     2
BW9F4     1
BX3FJ     1
BX8C0     1
BX8CD     7
BX9F1     1
BX9FJ     1
BXBCD     2
BY11F     1
BY30E     1
BY32E     1
BY5F1     2
BY5G1     2
BY64A     1
BY67A     1
BY68A     1
BY809     1
BY80E     3
BY84A     1
BY879     2
BY99J     1
BYBDE     1
BZ1FB     2
BZ1HK     1
BZ28E     2
BZ42E     3
BZ42F     1
BZ4HK     5
BZ4ZE     1
BZ9F3     1
BZAHK     1
BZRFH     1
C08RW     1
C11AK     2
C11BK     1
C1RFV     1
C21FB     1
C25AN     1
C2ZWB     2
C31AK     1
C4MBE     1
C4RBE     1
C616Z     1
C618X     1
C74C4     1
C8E2H     1
C916Z     1
CA217     1
CA21A     1
CA30P     1
CA31A     1
CA38P     1
CA50A     1
CAAAG     1
CAABG     2
CAAGA     1
CB09J     1
CB337     1
CB3FV     1
CBAGA     1
CC13C     1
CC1BR     1
CC1CX     1
CC42H     1
CDUD2     1
CE22P     1
CE38P     1
CECB8     2
CF22P     1
CF28P     2
CG12K     1
CGE23     2
CH5CP     1
CIRFV     1
CJ6B1     1
CJE23     2
CJE73     1
CK12G     1
CL968     1
CM565     1
CP450     1
CP515     1
CP724     1
CPA50     1
CRKEC     1
CS12G     2
CS18Z     2
CT05J     1
CU09J     1
CU18R     1
CU1BR     2
CU923     2
CV12G     1
CV1F4     1
CV52B     1
CV541     1
CW126     2
CW12G     5
CW5F1     1
CW6C8     2
CW6CB     2
CW6CD     1
CW8BB     2
CW8C8     1
CW8CB     4
CW8CD     2
CW9CB     2
CW9CD     2
CX0CD     1
CX126     2
CX12G     4
CX190     1
CX196     1
CX19G     4
CX3DD     1
CX3FJ     1
CX6CB     2
CX6CD     1
CX8C8     1
CX8CB     3
CX8CD     3
CX8EM     2
CX8GS     1
CX9C8     1
CX9CB     5
CX9CD     7
CX9FJ     1
CXBEM     1
CXI9G     1
CY5F1     2
CY7AJ     1
CZ5AN     6
CZRAH     1
D13FV     1
D156F     1
D1RFV     1
D23DC     1
D258N     1
D2DF6     1
D3135     3
D3DF6     1
D4MBE     2
D4RBE     1
D541A     1
D6RFV     1
D89CD     2
DA1AB     1
DA31A     1
DAAAG     1
DAABG     1
DAACK     1
DAR9K     1
DARTK     1
DB0A0     1
DB0AO     1
DB0C0     1
DB0E0     1
DB0G0     2
DB12E     1
DB21B     1
DB24B     1
DB2A0     1
DB2C0     1
DB41S     1
DB4A0     2
DB4C0     1
DB6CD     1
DB8CD     2
DB8FS     1
DB9CB     2
DB9CD     3
DBADK     1
DBE32     1
DBOE0     1
DBR22     1
DBSCD     1
DBWG3     1
DBYSV     1
DBZSV     4
DCRFH     1
DD21A     1
DD22S     1
DD23S     1
DD2EY     1
DD82A     1
DE32K     1
DE4EV     1
DE626     1
DE82A     1
DF4DV     1
DF4EB     1
DF4EU     1
DF4EV     3
DF9EV     2
DFAEV     1
DFREV     1
DG61E     1
DGRFH     1
DH4CD     1
DH88W     1
DH88X     1
DJ81W     1
DJREV     1
DK3DC     2
DK3EH     1
DK4CC     1
DK4DV     1
DKJA0     1
DKW9D     1
DL25R     1
DL39M     1
DLBJV     1
DLBYV     2
DM5F1     1
DM626     2
DN136     2
DN56A     1
DP21A     1
DPMAE     1
DPRAE     1
DR32T     5
DS41A     1
DS43A     1
DSKFC     1
DT3MW     1
DT441     2
DT481     1
DT541     1
DTPUK     1
DU09J     1
DU09T     1
DV09J     1
DV541     2
DV581     2
DW11S     2
DW12S     2
DW3FV     2
DW51E     1
DW541     1
DW5F1     2
DW5G1     1
DW923     1
DWRFV     1
DWSF1     1
DX1H2     1
DX226     2
DX22G     6
DX6CB     1
DX6CD     2
DX8CD     3
DX8F5     1
DX8FS     3
DX9CB     2
DX9CD     5
DXBCD     1
DXBFS     1
DY32T     1
DY38T     1
DY5F1     2
DY5G1     1
DYSF1     1
DZ1FB     1
DZ3DC     2
DZ5BN     2
DZ626     5
DZK23     1
DZRBH     1
DZRFH     1
DZSBN     1
E1EE0     1
E1NFJ     1
E2815     1
E29F3     1
E4FDB     1
E6A3U     1
E6RFV     1
E8017     1
EA6BX     1
EAAAG     1
EAMDE     1
EB02E     1
EB0BE     1
EB13E     1
EB71J     2
EB73J     1
EBOBE     1
EBRBE     1
EBRCH     1
EC42E     1
ECABA     1
ED1EK     1
ED31V     1
ED3KA     1
ED9HP     1
EDABB     1
EE32K     1
EE426     1
EE9HE     1
EF12K     1
EF4HK     1
EF76A     2
EF88F     3
EF8BF     3
EF8C3     1
EF8CF     1
EF9FK     1
EFABF     1
EFAVS     1
EFBBF     1
EFBC3     1
EFBCF     1
EFHCF     1
EFSBF     1
EG12K     1
EG21K     1
EG22K     2
EG23K     1
EG425     1
EG426     3
EGCBB     1
EJ13E     1
EJ5CD     1
EK12G     1
EK12T     1
EK19T     1
EL33P     1
EM426     2
EM42G     1
EM496     3
EM5F1     2
EN61S     1
ENE0R     1
ENKA5     1
EPMAE     1
EPRAE     2
ER21E     1
ER22E     3
ER23E     4
ER33P     1
ER42E     1
ES12G     4
ES41A     1
ES43A     1
ES46A     1
ET341     2
ET381     1
ET923     1
ET9F3     1
EU11F     1
EU3FJ     1
EU5JR     1
EU73J     1
EV541     1
EV581     1
EV73J     1
EW126     2
EW12G     3
EW1EP     1
EW21A     1
EW22E     1
EW23E     4
EW41A     1
EW44A     2
EW5F1     1
EW923     2
EWIE5     1
EWRFV     1
EX120     2
EX126     2
EX12G     4
EX196     2
EX19G     7
EX1E6     1
EX22G     2
EX28E     1
EX91G     1
EY5F1     1
EY64A     1
EZ20E     2
EZ28E     3
EZ3DC     1
EZ426     2
EZ42E     1
EZ496     3
F11AK     1
F11BK     1
F1RFV     1
F31AK     1
F6RDM     1
F7D19     1
F7E69     1
FA119     1
FA38P     2
FA903     1
FARAH     1
FB518     3
FB718     1
FBABG     2
FBW41     1
FC24H     1
FC518     1
FD3HL     1
FDA88     1
FDAB8     1
FDABB     1
FE22P     1
FE52S     2
FE53S     1
FE54S     1
FE718     3
FE728     2
FF22P     1
FF41C     1
FF719     1
FG15T     1
FG426     1
FG8JP     1
FH3CB     1
FIRFV     1
FJ60G     1
FJ60V     1
FJ71J     1
FK122     1
FK418     3
FK518     2
FK718     1
FM418     4
FM518     4
FP14F     1
FP518     2
FPEFF     1
FPMAE     1
FPRAE     1
FR119     4
FR226     1
FR22G     4
FR320     2
FR73J     1
FU5JR     1
FU71J     3
FU73J     1
FV47V     1
FW12G     1
FX00G     1
FX02P     1
FX226     2
FX22C     2
FX22G     5
FX22P     1
FY418     3
FY5A1     1
FY5B1     1
FY5F1     1
FZ1FB     1
FZ29G     1
FZ418     1
FZRBH     1
G0EE9     1
G11AK     1
G11BK     1
G13FV     1
G14DA     1
G1RFV     1
G31AK     1
G4AC1     1
G4BC1     1
G4X20     2
G5GC1     1
G622K     1
G6X40     1
GA17E     1
GA17F     2
GA17H     1
GARAH     1
GBKFW     1
GBRCH     1
GD20V     1
GD21A     1
GD32M     3
GD34M     2
GD52M     2
GD54M     3
GE17F     1
GE52M     3
GES2M     1
GF46X     1
GF4JB     1
GG25K     1
GGG56     1
GH20V     1
GJ211     1
GJKFW     2
GK12E     1
GK13E     1
GK26H     1
GN86R     2
GN87R     2
GNP03     1
GP10V     2
GP21A     1
GR4A6     1
GRKEC     1
GS54M     2
GSKFC     1
GU09J     1
GU4L3     1
GW5F1     1
GX72A     1
GX8CD     1
GX8EM     2
GXSEM     1
GY5F1     1
GZ1FB     1
GZ3DH     2
GZ5AN     1
GZRAH     1
GZRBH     1
H0093     1
H009J     1
H109J     1
H1RFV     1
H25ZZ     1
H3093     1
H309J     1
H4ACP     1
H4BCP     1
H545G     1
HA3CD     1
HAP53     2
HAP5J     1
HAP73     1
HB10V     1
HB8CD     2
HB9CP     2
HC05J     1
HD17F     2
HD20V     1
HD21A     1
HD23S     1
HDAAA     1
HEJ1F     1
HF10U     1
HG09G     1
HG17C     2
HG39K     1
HH20V     2
HJ01J     1
HJ05J     1
HJ08J     1
HJ091     1
HJ093     1
HJ09J     2
HJ0SJ     1
HJ59J     1
HJ85J     1
HJO9J     1
HJQ8J     1
HJXEN     1
HK31U     1
HN86R     1
HN87R     2
HN9CP     8
HNICP     1
HNP13     1
HNP6N     1
HNW6N     1
HP10V     3
HPRAE     1
HR33N     1
HS02P     4
HT051     1
HT053     1
HT05J     2
HT06J     1
HT093     1
HT09J     2
HT0SJ     1
HT523     1
HTO5J     1
HTOSJ     1
HU01J     2
HU08J     1
HU091     1
HU093     1
HU09J     2
HU5JR     1
HU8CD     3
HUD3J     1
HUD9J     1
HUOTJ     1
HV01J     1
HV05J     1
HV09J     1
HW21A     1
HW2ZZ     2
HW31U     1
HW5F1     2
HX013     1
HX01J     2
HX02J     1
HX02P    18
HX05J     2
HX07P     1
HX091     1
HX093     1
HX09J     1

In [241]:
(
    toyota.groupby("vds")["model"]
    .nunique()
    .value_counts()
    .sort_index()
)

model
0        2
1     2137
2      288
3       74
4       19
5        8
8        1
10       2
Name: count, dtype: int64

In [242]:
vds_model_count = (
    toyota.groupby("vds")["model"]
    .nunique()
)

problem_vds = vds_model_count[vds_model_count > 1]

problem_vds.sort_values(ascending=False).head(20)

vds
LU73J    10
LJ73J    10
JJXB0     8
NX22N     5
M8500     5
JX02P     5
A180C     5
PBEJA     5
AG34L     5
EF8BF     5
BT441     5
AAAAA     4
AACAJ     4
11111     4
ZD31V     4
BU71J     4
FU71J     4
A14CK     4
KARJE     4
LJ71J     4
Name: model, dtype: int64

In [243]:
worst_vds = problem_vds.sort_values(ascending=False).index[0]

toyota[
    toyota["vds"] == "LU73J"
][["model","year","trim","bodyType"]].value_counts()

model                         year    trim                      bodyType
LAND CRUISER PICKUP 70        2016.0  EXR                       Pick Up               105
LAND CRUISER PICK UP          2014.0  LX WINCH                  Pick Up Double Cab     97
LAND CRUISER PICKUP 70        2022.0  LX                        Pick Up Single Cab     68
LAND CRUISER PICK UP          2013.0  LX WINCH                  Pick Up                65
                              2012.0  LX AC PWR OPT             Pick Up                53
LAND CRUISER PICKUP 70        2021.0  GXR                       Pick Up Double Cab     52
LAND CRUISER PICK UP          2011.0  LX                        Pick Up                38
                              2015.0  STD AC                    Pick Up                36
LAND CRUISER PICKUP 70        2019.0  LX                        Pick Up Single Cab     34
                              2018.0  VXR                       Pick Up                34
LAND CRUISER PICK UP          2012.0  LX AC PWR OPT             Pick Up Double Cab     30
LAND CRUISER PICKUP 70        2021.0  HARD TOP                  Pick Up Single Cab     28
                              2025.0  LX                        Pick Up Single Cab     27
                              2020.0  LX                        Pick Up Single Cab     24
                              2010.0  LX                        Pick Up                24
                              2024.0  LX                        Pick Up Single Cab     18
LAND CRUISER PICK UP          2015.0  LX WINCH                  Pick Up Double Cab     16
LAND CRUISER PICKUP 70        2023.0  LX                        Pick Up Single Cab     14
LAND CRUISER                  2010.0  GXR                       Pickup                 13
LAND CRUISER PICKUP 70        2016.0  GXR                       Pick Up Double Cab     12
LAND CRUISER                  2010.0  GXR                       SUV                    11
LAND CRUISER PICK UP          2015.0  LX AC PWR OPT             Pick Up                 6
LAND CRUISER                  2017.0  EXR                       SUV                     6
LAND CRUISER PICKUP 70        2021.0  SC                        Pick Up Single Cab      5
LAND CRUISER                  2011.0  GXR                       SUV                     5
                              2017.0  EXR                       Pickup                  4
                              2011.0  G                         SUV                     4
HILUX                         2010.0  DLX                       Pick Up Double Cab      4
LAND CRUISER PICK UP          2015.0  LX WINCH                  Pick Up                 3
                              2006.0  STD                       Pick Up                 3
LAND CRUISER                  2015.0  LX                        Pickup                  3
                              2010.0  GXR TOP                   Pickup                  3
                                      STD                       Pickup                  3
                              2015.0  GX                        SUV                     3
                              2010.0  GXR TOP                   SUV                     3
                              2015.0  GX                        Pickup                  3
                              2017.0  GXR                       Pickup                  3
                              2011.0  GXR                       Pickup                  3
LAND CRUISER PICK UP          2019.0  GXR                       Pick Up Double Cab      2
                              2014.0  LX AC PWR OPT             Pick Up Double Cab      2
LAND CRUISER PICKUP 70        2017.0  EXR                       Pick Up                 2
LAND CRUISER                  2010.0  GXR FMST                  Pickup                  2
                              2015.0  EXR                       SUV                     2
                              2016.0  STD                       SUV                     2
                              2010.0  GL                        Pickup                  2
                              2015.0  STD                       Pickup                  2
                              2010.0  VX                        SUV                     2
LAND CRUISER PICKUP 70        2018.0  LX                        Pick Up Single Cab      2
LAND CRUISER PICK UP          2017.0  GXR                       Pick Up Double Cab      1
                              2025.0  GXR                       Pick Up Double Cab      1
LAND CRUISER                  2016.0  STD                       Pickup                  1
                              2013.0  GXR                       SUV                     1
                              2010.0  1                         Pickup                  1
TACOMA                        2017.0  SR5 (NON GCC)             Pick Up Double Cab      1
LAND CRUISER                  2015.0  STD                       PICKUP                  1
                              2010.0  VXR                       SUV                     1
                              2016.0  LX                        Pickup                  1
LAND CRUISER PICK UP CARGO    2015.0  X                         PICKUP                  1
HILUX                         2011.0  DLX                       Pick Up Double Cab      1
LAND CRUISER                  2010.0  SC                        Pick Up Single Cab      1
LAND CRUISER PICK UP          2014.0  LX WINCH                  PICK UP SINGLE CAB      1
TUNDRA                        2016.0  STD (NON GCC)             Pick Up Double Cab      1
LAND CRUISER                  2010.0  GXR                       PICK UP SINGLE CAB      1
                              2011.0  SAFARI                    SUV                     1
                              2010.0  SAFARI                    SUV                     1
                              2017.0  PIKUP                     SUV                     1
                              2016.0  EXR                       SUV                     1
                              2015.0  PREMIUM                   SUV                     1
                                      GXR                       SUV                     1
PREVIA                        2016.0  SE                        MPV                     1
LAND CRUISER                  2021.0  VXR                       SUV                     1
LAND CRUISER PICKUP 70        2025.0  GXR                       Pick Up Double Cab      1
LAND CRUISER                  2015.0  PICKUP                    Pickup                  1
                                      XTREME                    SUV                     1
                                      60TH                      SUV                     1
TUNDRA                        2010.0  STD (NON GCC)             Pick Up Double Cab      1
HILUX                         2010.0  GL                        Pick Up Double Cab      1
LAND CRUISER                  2017.0  XTREME                    PICKUP                  1
HILUX                         2015.0  DLS                       Pick Up Double Cab      1
LAND CRUISER                  2017.0  A                         Pickup                  1
                              2018.0  STD                       PICKUP                  1
                              2017.0  station1                  Pickup                  1
                              2011.0  TRIM                      Pickup                  1
                              2010.0  GXR FMST                  SUV                     1
LAND CRUISER/PICK UP CARGO    2010.0  STANDER                   PICKUP                  1
HILUX                         2010.0  GXR                       PICK UP SINGLE CAB      1
LAND CRUISER                  2017.0  XTREME                    SUV                     1
                              2010.0  SEDAN                     Pickup                  1
                              2006.0  STD                       Pickup                  1
                              2010.0  DLX TOP                   Pickup                  1
                              2017.0  STD                       Pickup                  1
                              2010.0  GXR                       PICKUP                  1
                              2015.0  60TH                      PICKUP                  1
LAND CRUISER PICKUP 70        2022.0  SC                        Pick Up Single Cab      1
LAND CRUISER                  2011.0  GXR MID XTREME            Pickup                  1
HILUX                         2016.0  DLS                       Pick Up Double Cab      1
LAND CRUISER                  2011.0  G                         Pickup                  1
                              2015.0  VXR                       Pickup                  1
                              2010.0  TX                        PICKUP                  1
                              2011.0  GXR MID 60th ANNIVERSARY  SUV                     1
                              2015.0  EXR                       PICK UP SINGLE CAB      1
                                      STD                       SUV                     1
LAND CRUISER PICKUP 70        2020.0  HARD TOP                  Pick Up Double Cab      1
LAND CRUISER                  2010.0  STD (NON GCC)             Pickup                  1
LAND CRUISER PICKUP 70        2008.0  LX                        Pick Up                 1
LAND CRUISER PICK UP          2015.0  TRIM                      PICKUP                  1
LAND CRUISER                  2016.0  GXR                       Pickup                  1
                              2011.0  SE T2                     Pickup                  1
LAND CRUISER - PICK UP CARGO  2010.0  LX                        Pick Up                 1
LAND CRUISER                  2010.0  LE PLATINUM CITY          Pickup                  1
LAND CRUISER PICKUP 70        2016.0  EXR                       PICK UP SINGLE CAB      1
LAND CRUISER                  2016.0  EXR                       PICK UP SINGLE CAB      1
                              2010.0  VXR TOP                   Pickup                  1
LAND CRUISER PICK UP          2015.0  1                         PICKUP                  1
                              2010.0  STANDARD                  PICKUP                  1
LAND CRUISER                  2021.0  EXR                       SUV                     1
Name: count, dtype: int64

In [244]:
toyota[
    toyota["vds"].isin(
        vds_model_count[vds_model_count == 0].index
    )
]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers,model_length,vds
62636,LM8F7E692NA041147,2022.0,TOYOTA,NaN,SE,Hatchback,GCC,4.0,blue,CHINA,2000.0,5.0,NaN,F7E69
124018,LK6ADAE2XNB037263,2022.0,TOYOTA,NaN,GLI,Coupe,GCC,4.0,green and black,CHINA,1600.0,4.0,NaN,ADAE2

In [245]:
df_clean["model_family"] = df_clean["model"]

In [246]:
toyota_family_map = {
    "LAND CRUISER PICKUP 70": "LAND CRUISER 70",
    "LAND CRUISER PICK UP": "LAND CRUISER 70",
    "LAND CRUISER PICKUP": "LAND CRUISER 70",
    "LAND CRUISER PICK UP CARGO": "LAND CRUISER 70",
    "LAND CRUISER/PICK UP CARGO": "LAND CRUISER 70",
    "LAND CRUISER - PICK UP CARGO": "LAND CRUISER 70",
    "LAND CRUISER SINGLE-CABIN PICK UP": "LAND CRUISER 70",
    "LAND CRUISER SINGLE-CABIN PICK": "LAND CRUISER 70",
}

In [247]:
df_clean["model_family"] = (
    df_clean["model_family"]
    .replace(toyota_family_map)
)

In [248]:
df_clean["model_family"] = (
    df_clean["model_family"]
    .replace({
        "LAND CRUISER PRADO": "PRADO"
    })
)

In [250]:
(
    df_clean.groupby("vds")["model_family"]
    .nunique()
    .value_counts()
    .sort_index()
)

model_family
0       130
1     15757
2      2611
3       773
4       340
5       205
6       120
7        70
8        49
9        42
10       35
11       13
12       13
13        9
14       12
15        1
16        7
17        9
18        1
19        1
20        2
21        3
24        2
27        2
31        1
38        2
40        1
Name: count, dtype: int64

In [251]:
toyota = df_clean[df_clean["make"] == "TOYOTA"]

before = (
    toyota.groupby("vds")["model"]
    .nunique()
)

after = (
    toyota.groupby("vds")["model_family"]
    .nunique()
)

print("Before")
print(before.value_counts().sort_index())

print("\nAfter")
print(after.value_counts().sort_index())

Before
model
0        2
1     2137
2      288
3       74
4       19
5        8
8        1
10       2
Name: count, dtype: int64

After
model_family
0       2
1    2144
2     290
3      71
4      13
5       8
6       1
7       1
8       1
Name: count, dtype: int64

In [252]:
body_words = [
    "PICK",
    "CAB",
    "CARGO",
    "SEDAN",
    "HATCH",
    "WAGON",
    "VAN"
]

body_models = df_clean[
    df_clean["model_family"].str.contains(
        "|".join(body_words),
        case=False,
        na=False
    )
]

body_models["model_family"].value_counts().head(100)

model_family
URVAN                               4555
AVANZA                              1520
AVANTE                              1014
PATROL PICK UP                       852
LEVANTE                              185
SAVANA                               100
OKAVANGO                              95
VANTAGE                               35
GRAND CARAVAN                         32
SPACE WAGON                           29
GRAND WAGONEER                        23
MULTIVAN                              21
VANQUISH                              15
GRANCABRIO                            12
WAGONEER                               8
COROLLA SEDAN                          7
LS 460 L/SEDAN                         4
AVANTY                                 4
BONGO/PICK UP CARGO                    4
CARAVAN                                4
URVAN/VAN                              3
PICKUP SINGLE CABIN                    3
SUNNY/SEDAN                            3
CANTER PICK UP CARGO                   3
C 300 SEDAN                            3
3 SEDAN                                3
EXPRESS EX(VAN)                        3
PARTNER VAN CARGO                      3
NPR LIGHT DUTY PICK UP                 3
300 PICK UP CARGO                      3
COROLLA 1.6/SEDAN                      2
DLX FA (PICK UP)                       2
PICK UP CARGO                          2
L 200 SINGLE CABIN PICKUP              2
SEDAN                                  2
HD 46 PICK UP CARGO                    2
PORTER II (PICK UP)                    2
K 4/SEDAN                              2
BONGO PICK UP CARGO                    2
RANGER PICK UP DOUBLE CABIN            2
RAPTOR F-150 PICKUP DOUBLE CABIN       2
SIERRA PICK UP DOUBLE CAB              2
PICKUP                                 2
SIERRA PICK UP DOUBLE CABIN            2
NKR PICK UP DOUBLE CABIN               2
SIERRA SINGLE-CABIN PICK UP            2
HATCHBACK                              2
SHARK (PICK UP)                        2
1500/PICK UP DOUBLE CABIN              2
DOUBLE CABIN PICKUP                    2
T8 PRO EURO5 (PICK UP)                 2
Z9 PICK UP                             2
DOUBLE CABIN PICK UP                   2
CARGO                                  2
SIENNA VAN                             1
SENA VAN PASSENGER                     1
PICK UP CABIN                          1
TACOMA (PICK UP)                       1
COROLLA SEDAN / HATCH                  1
TUNDRA (PICK UP)                       1
GXL RA (STATION WAGON)                 1
YARIS HATCHBACK                        1
SIENNA(VAN)                            1
TAKOMA PICK UP CARGO                   1
COROLLA 1.5L/HATCHBACK                 1
TANDRA PICK UP DOUBLE CABIN            1
DYNA VAN CARGO                         1
LAND CRUISER/STD EX PICKUP             1
PICK UP                                1
PICKUP CARGO                           1
URVAN/COACH                            1
FRONTIER/PICK UP DOUBLE CABIN          1
2400 PICK UP CARGO                     1
CABSTAR                                1
QUEST (VAN)                            1
URBAN VAN                              1
TIIDA HATCHBACK                        1
TITAN PICK UP DOUBLE CABIN             1
VAN 3S4DRSRMT U11A(VAN)                1
NVARA / PICK UP DOUBLE C               1
NVARA PICK UP DOUBLE C                 1
L 300 VAN CARGO                        1
CANTER PICKUP                          1
L200 PICK UP                           1
PICK UP SINGLE CABIN                   1
PICK UP DOUBLE CABIN                   1
SINGLE CABIN                           1
CRAVAN MISTUBISHI                      1
CANTER PICKUP CRANE                    1
CANTER PICK UP CAR                     1
CABALLERO RALLY                        1
GRANDEUR SEDAN                         1
PORTER/FOODSTUFF FRIDGE VAN            1
PORTER/PICK UP CARGO                   1
STARKS VAN PASSENGER                   1
H 100 PICK UP CARGO                    1
GRAND YUOR / SEDAN                     1
GRAND STAREX(VAN)                      1
GRANDYUOR / SEDAN                      1
PORTER DOUBLE CABIN                    1
Name: count, dtype: int64

In [253]:
body_models = df_clean[
    df_clean["model_family"].str.contains(
        r"PICK|CAB|CARGO|SEDAN|HATCH|WAGON|VAN",
        case=False,
        na=False
    )
]

(
    body_models["model_family"]
    .value_counts()
    .head(200)
)

model_family
URVAN                                          4555
AVANZA                                         1520
AVANTE                                         1014
PATROL PICK UP                                  852
LEVANTE                                         185
SAVANA                                          100
OKAVANGO                                         95
VANTAGE                                          35
GRAND CARAVAN                                    32
SPACE WAGON                                      29
GRAND WAGONEER                                   23
MULTIVAN                                         21
VANQUISH                                         15
GRANCABRIO                                       12
WAGONEER                                          8
COROLLA SEDAN                                     7
LS 460 L/SEDAN                                    4
AVANTY                                            4
BONGO/PICK UP CARGO                               4
CARAVAN                                           4
URVAN/VAN                                         3
PICKUP SINGLE CABIN                               3
SUNNY/SEDAN                                       3
CANTER PICK UP CARGO                              3
C 300 SEDAN                                       3
3 SEDAN                                           3
EXPRESS EX(VAN)                                   3
PARTNER VAN CARGO                                 3
NPR LIGHT DUTY PICK UP                            3
300 PICK UP CARGO                                 3
COROLLA 1.6/SEDAN                                 2
DLX FA (PICK UP)                                  2
PICK UP CARGO                                     2
L 200 SINGLE CABIN PICKUP                         2
SEDAN                                             2
HD 46 PICK UP CARGO                               2
PORTER II (PICK UP)                               2
K 4/SEDAN                                         2
BONGO PICK UP CARGO                               2
RANGER PICK UP DOUBLE CABIN                       2
RAPTOR F-150 PICKUP DOUBLE CABIN                  2
SIERRA PICK UP DOUBLE CAB                         2
PICKUP                                            2
SIERRA PICK UP DOUBLE CABIN                       2
NKR PICK UP DOUBLE CABIN                          2
SIERRA SINGLE-CABIN PICK UP                       2
HATCHBACK                                         2
SHARK (PICK UP)                                   2
1500/PICK UP DOUBLE CABIN                         2
DOUBLE CABIN PICKUP                               2
T8 PRO EURO5 (PICK UP)                            2
Z9 PICK UP                                        2
DOUBLE CABIN PICK UP                              2
CARGO                                             2
SIENNA VAN                                        1
SENA VAN PASSENGER                                1
PICK UP CABIN                                     1
TACOMA (PICK UP)                                  1
COROLLA SEDAN / HATCH                             1
TUNDRA (PICK UP)                                  1
GXL RA (STATION WAGON)                            1
YARIS HATCHBACK                                   1
SIENNA(VAN)                                       1
TAKOMA PICK UP CARGO                              1
COROLLA 1.5L/HATCHBACK                            1
TANDRA PICK UP DOUBLE CABIN                       1
DYNA VAN CARGO                                    1
LAND CRUISER/STD EX PICKUP                        1
PICK UP                                           1
PICKUP CARGO                                      1
URVAN/COACH                                       1
FRONTIER/PICK UP DOUBLE CABIN                     1
2400 PICK UP CARGO                                1
CABSTAR                                           1
QUEST (VAN)                                       1
URBAN VAN                                         1
TIIDA HATCHBACK                                   1
TITAN PICK UP DOUBLE CABIN                        1
VAN 3S4DRSRMT U11A(VAN)                           1
NVARA / PICK UP DOUBLE C                          1
NVARA PICK UP DOUBLE C                            1
L 300 VAN CARGO                                   1
CANTER PICKUP                                     1
L200 PICK UP                                      1
PICK UP SINGLE CABIN                              1
PICK UP DOUBLE CABIN                              1
SINGLE CABIN                                      1
CRAVAN MISTUBISHI                                 1
CANTER PICKUP CRANE                               1
CANTER PICK UP CAR                                1
CABALLERO RALLY                                   1
GRANDEUR SEDAN                                    1
PORTER/FOODSTUFF FRIDGE VAN                       1
PORTER/PICK UP CARGO                              1
STARKS VAN PASSENGER                              1
H 100 PICK UP CARGO                               1
GRAND YUOR / SEDAN                                1
GRAND STAREX(VAN)                                 1
GRANDYUOR / SEDAN                                 1
PORTER DOUBLE CABIN                               1
PORTER 2 (PICK UP)                                1
BONGO/SINGLE-CABIN PICK UP                        1
KIA/KS/SEDAN                                      1
KIA/K 4/SEDAN                                     1
STD EX PICKUP                                     1
BONGO PICK UP TRUCK                               1
SEDONA VAN                                        1
BONGO SINGLE-CABIN PICKUP                         1
K 7/SEDAN                                         1
K 5/SEDAN                                         1
4000 VAN CARGO                                    1
S 600 SEDAN                                       1
B200 (HATCHBACK)                                  1
S 500/SEDAN                                       1
C 300/SEDAN                                       1
E 53 HYBRID 4MATIC+ SEDAN                         1
E55 SEDAN                                         1
CAPRICE CLASSIC SEDAN                             1
CAPRICE SS SEDAN                                  1
SILVERADO PICK UP DOUBLE                          1
S 10 PICK UP CARGO                                1
SONEK SEDAN                                       1
LUV/PICK UP DOUBLE CABIN                          1
G20 (VAN)                                         1
EXPRESS VAN PASSENGER                             1
MALIBU SEDAN                                      1
RAPTOR PICK UP DOUBLE CABIN                       1
MAVERIK PICK UP DOUBLE                            1
F250 PICK UP                                      1
F 250/PICK UP DOUBLE CABIN                        1
F 250 (PICK UP)                                   1
F 150 PICK UP DOUBLE CABIN                        1
F-250 PICKUP                                      1
F 150 VAN DOUBLE CABIN                            1
CARGO 4135                                        1
320 SEDAN                                         1
VANDURA                                           1
SIERRA PICKUP                                     1
SAVANA(VAN)                                       1
DEXER SINGLE-CABIN PICK UP                        1
DEFENDER DOUBLE CABIN                             1
DEVENDR SINGLE-CABIN PICK UP                      1
VANVAN                                            1
VAN VAN                                           1
ECHO VAN CARGO                                    1
GOLF HATCHBACK                                    1
CADDY HATCHBACK                                   1
VANAGON                                           1
MULTIVAN COMFORTLINE                              1
P 2200/PICK UP DOUBLE CABIN                       1
Q70/SEDAN                                         1
G 25 S/SEDAN                                      1
TI7 (STATION WAGON)                               1
2500/PICK UP DOUBLE CABIN                         1
SINGLE-CABIN PICK                                 1
RS 3 SPORTBACK HATCHBACK                          1
QNE 07/SEDAN                                      1
BOXER/VAN CARGO                                   1
FLAT WOOD SEDAN                                   1
COBBER/CLUBMAN/SEDAN                              1
LONG RANGE STARBUCKS V7 SMATE EDITION (VAN)       1
RAM PICKUP 15                                     1
NLR LIGHT DUTY PICK (UP)                          1
NPR/CABIN CHASSIS                                 1
ELF PICK UP CARGO                                 1
ELF/PICK UP CARGO                                 1
DEKTE PICK UP TRUCK                               1
NPR PICK UP CARGO                                 1
NMR LIGHT DUTY (PICK UP)                          1
NHR/PICK UP CARGO                                 1
NPR/STD SE PICKUP                                 1
NMR PICK UP CARGO                                 1
PICKUP DOUBLE CABIN                               1
D MAX SINGLE-CABIN PICK                           1
HFC 1061 K / PICK UP CARGO                        1
N65 PICK UP CARGO                                 1
GA3S SEDAN                                        1
GRAND MAX VAN CARGO                               1
ECO 150 CARGO                                     1
300 SEDAN                                         1
300/SEDAN                                         1
WINGLE/SINGLE-CABIN PICK UP                       1
WINGLE/PICK UP DOUBLE CABIN                       1
LEVANTE GRANLUSSO(4WD)                            1
RELY RB (PICK UP)                                 1
ATTACKER/PICK UP DOUBLE CABIN                     1
FIORINO VAN CARGO                                 1
35C VAN CARGO                                     1
PICK UP 32                                        1
HINO/300/FOODSTUFF FRIDGE VAN                     1
HINO/300/VAN CARGO                                1
JUMPY PANEL VAN XL                                1
D260 PANEL VAN                                    1
VAN CARGO                                         1
PANEL VAN                                         1
C1 VAN PASSENGER                                  1
VAN MT DIESEL                                     1
ULTRA 81439 VAN CARGO                             1
XENON/SINGLE-CABIN PICK UP                        1
P16 121/PICK UP DOUBLE CABIN                      1
Name: count, dtype: int64

In [254]:
{
    "COROLLA SEDAN": "COROLLA",
    "YARIS HATCHBACK": "YARIS",
    "TIIDA HATCHBACK": "TIIDA",
    "SUNNY/SEDAN": "SUNNY",
    "SIENNA VAN": "SIENNA",
    "SIENNA(VAN)": "SIENNA",
}

{'COROLLA SEDAN': 'COROLLA',
 'YARIS HATCHBACK': 'YARIS',
 'TIIDA HATCHBACK': 'TIIDA',
 'SUNNY/SEDAN': 'SUNNY',
 'SIENNA VAN': 'SIENNA',
 'SIENNA(VAN)': 'SIENNA'}

In [255]:
import numpy as np

drop_models = [
    "SEDAN",
    "HATCHBACK",
    "PICKUP",
    "PICK UP",
    "PICK UP CARGO",
    "DOUBLE CABIN PICKUP",
    "DOUBLE CABIN PICK UP",
    "CARGO",
    "SINGLE CABIN",
]

df_clean["model_family"] = (
    df_clean["model_family"]
    .replace(drop_models, np.nan)
)

In [256]:
(
    df_clean["model_family"]
    .value_counts()
    .loc[lambda x: x <= 5]
    .sort_values()
)

model_family
03T                                            1
S2000 GL                                       1
SX 1000                                        1
UN125NEZMS AVENIS                              1
GSX R 750 L 6                                  1
GSX 250                                        1
G                                              1
DS250RL (V-STROM SX)                           1
GRAND VITA                                     1
VZ 800 LI                                      1
G S X 1000RZAM1                                1
UN125NE                                        1
GT1258CD                                       1
1300 CC                                        1
GIXER                                          1
GSX150RFM                                      1
FXDBI                                          1
ZN150T27                                       1
RALLY 450                                      1
SPYDERRT-S                                     1
VANET                                          1
ENDURO2                                        1
TRANS AM                                       1
6798KLQ                                        1
ATOM                                           1
C KVJB 4                                       1
MAX180 (MOTORCYCLE)                            1
SR/S                                           1
AYED250N 3                                     1
EQ 1                                           1
EPURE                                          1
CF 600                                         1
ADVENTURER                                     1
/ 1000CC                                       1
RISING R7                                      1
LUXURY                                         1
175 SHARMAX - STREET BIKE                      1
KINGKONG (PICKUP)                              1
GCINGEROY ELINGSHOT SLR                        1
KLQ6600                                        1
YEP/STATION                                    1
EC 250                                         1
EM01                                           1
NJ 1022                                        1
SITRAK (TRACTOR)                               1
LTM1100                                        1
BEN P 6                                        1
SY6483A3                                       1
SV 110                                         1
KV 100 QL                                      1
KV100 L                                        1
1060 G                                         1
LIGHTNING XB12S                                1
L9MAX                                          1
EM 01                                          1
422 F                                          1
212(4WD)                                       1
BIKE 150T FORCE                                1
KIMMCO                                         1
MR 688 S                                       1
XF105.410                                      1
1040                                           1
450                                            1
CPX110                                         1
VTP1100                                        1
VTP11000 (ELECTRIC BIKE)                       1
62 S                                           1
01 LS AUTO LEV                                 1
410                                            1
SS MAVR MAX XRS                                1
ZONSEN - CUBE                                  1
2410                                           1
DAYTONA 675                                    1
H 9 PRO                                        1
263-18                                         1
VF6                                            1
IMLS6                                          1
VF8                                            1
675NK                                          1
ZT703                                          1
AERO 8                                         1
G70S                                           1
ZONSEN CUBE 150                                1
ELISE                                          1
100P                                           1
1040BUFAY                                      1
ZONDA                                          1
GT 250 RC                                      1
GT650                                          1
HIPHIX                                         1
090 BS                                         1
NOVUS7542                                      1
LESTAR                                         1
MAX PRO                                        1
K6EGF                                          1
GRAVITY                                        1
AYED250H 7 RS                                  1
BESTURN B50                                    1
250 H7                                         1
PERSONA                                        1
GEN-2                                          1
ELECTRIC BIKE                                  1
VTP 1100                                       1
SVARTPILEN 250                                 1
BRUTALE                                        1
BRUTALE DRA                                    1
3 WHEELER                                      1
SUPERSPORT                                     1
PLUS4                                          1
IDEAL GOLD                                     1
KAIJIE                                         1
F4 1000                                        1
TERRALORD GASOLINE PICKUP                      1
REGAL                                          1
8 TGB BK                                       1
MV                                             1
NORDEN 901                                     1
VGV/U 75 PLUS                                  1
CANYON REDR                                    1
450 RALLY                                      1
SSV                                            1
AK                                             1
LIKE                                           1
SKY LINE                                       1
VENICE (MOTORCYCLE)                            1
1060                                           1
PRO 2065XP                                     1
V 70                                           1
TRK502                                         1
TNT15                                          1
SPEED STORM                                    1
D250N                                          1
MEGA                                           1
ZN125T 27                                      1
V7 SPECIAL                                     1
BIKE AYED250N                                  1
V7 STONE                                       1
CA3182P                                        1
CALIBRO                                        1
STELVIO E5                                     1
250H 7 RST250                                  1
V85TT                                          1
GRANDLION                                      1
PARK AVENUE                                    1
SIXTIES 30                                     1
MAXSYM 400                                     1
WOLF200                                        1
TWC-25, 2.0,A,LE SLINGSHOT 10 AUTODRIVE        1
RIVIERA                                        1
BK8E                                           1
F02 (ELECTRIC LOAD BIKE)                       1
FO2 ELECTRIC                                   1
F02/ELECTRIC                                   1
F02 ELECTRIC                                   1
HHFL 150 CC                                    1
F02                                            1
GRAND PRIX                                     1
FAIRBIRD                                       1
CV3                                            1
TNT 125                                        1
VESTA                                          1
QUADSTER MOTORCYCLE                            1
280                                            1
302R                                           1
C 160                                          1
44629                                          1
TL                                             1
X 7                                            1
850MANA                                        1
APRILIA SX                                     1
X10 350                                        1
DESTINI 125                                    1
XPULSE 200                                     1
SIXTIES 150                                    1
MAX 400                                        1
می سی 125                                      1
STREET TR                                      1
SPEED 400                                      1
BONNEVILLE                                     1
U                                              1
CROX                                           1
SU 7                                           1
SU7 ULTRA                                      1
Y6101XMQ                                       1
XM6128                                         1
CARGO VAN                                      1
XMQ 6858                                       1
KING LONG/XMQ5030/VAN CARGO                    1
PASSANGER                                      1
R1S                                            1
RTT ADVENTURE (PICK UP)                        1
R 1 S                                          1
TRIDENT                                        1
TIGER 900                                      1
ENCORE                                         1
ZX 280 COUPE                                   1
JX1059TG25                                     1
ET9                                            1
JX 1032                                        1
VIGUS                                          1
VIGUS PLUS                                     1
ET 5                                           1
ES6                                            1
SY412C-8                                       1
CHAIRMAN                                       1
KP200                                          1
KP150                                          1
KP150F                                         1
CABALLERO DELUXE                               1
700CL-X                                        1
45 SR                                          1
TRUMP,01                                       1
ROCKET                                         1
GTS 310E5 GSO                                  1
GTV 310E                                       1
TRIPLE1050                                     1
BONNEVILLE T100                                1
TIGER                                          1
XL 150                                         1
TIGER 900 RALLY PRO                            1
SPEED                                          1
TIGER 800CC                                    1
150VXL                                         1
BONNEVILLE BOBBER (MOTORCYCLE)                 1
P16.111                                        1
K33 513                                        1
M HERO 917                                     1
X-TYPE                                         1
SHINE MAX                                      1
YETI 2015                                      1
C15                                            1
70C15H                                         1
380                                            1
30-380                                         1
FC-49                                          1
E 18-150                                       1
50C15                                          1
CF MOTO 650                                    1
CF250T6A                                       1
SS450                                          1
STREETFIGHTER V4                               1
MULTISTRADA V2                                 1
400 CC                                         1
800                                            1
650NK                                          1
MOTOR CYCLE 300CC                              1
450M                                           1
450 CLC                                        1
ATHENA                                         1
CF 650                                         1
J5 (2WD)                                       1
LIGHT PICKUP                                   1
A X 7                                          1
CAPTAIN E                                      1
DOLLICA                                        1
ZN1032UCM5A                                    1
AR 125                                         1
TUONO 660                                      1
RST 322                                        1
K33-561                                        1
817                                            1
P16-121                                        1
TRANSPORTER T5                                 1
P16 121/PICK UP DOUBLE CABIN                   1
P16-111                                        1
M-HERO M817                                    1
DFH 1180                                       1
T5                                             1
HYPERMOTARD SP                                 1
STREETFIGHTER V2                               1
HYPERMOTARD                                    1
PANIGALE V4R                                   1
HUNTER 35                                      1
METEOR 3                                       1
METEOR                                         1
X DIAVEL S                                     1
899                                            1
DIAVEL1260S                                    1
SUPERBIKE848                                   1
TUONO                                          1
RST 240 AYED250H                               1
RSV 1000 R                                     1
RSV4 1000                                      1
TUONO 125                                      1
RSV 4 1100                                     1
TUONO V4 1100                                  1
AYED250H7                                      1
CHIEFTAIN 1400                                 1
DUKE250                                        1
ADVENTURE 890                                  1
DUKE 390CC                                     1
SR 150                                         1
EXEO                                           1
ALHAMBRA                                       1
CLASSIC 50                                     1
SUPER METEOR                                   1
HIMALAYAN 411                                  1
ME                                             1
BIKE                                           1
GU                                             1
INT                                            1
MOTOR BIKE 350CC                               1
XE215G                                         1
HIMALAYAN 450                                  1
ULTRA 81439 VAN CARGO                          1
NOVOUS                                         1
TASHOK LEYLAND FALCON                          1
SUPER METEOR 650                               1
CONTINENTAL GT 650                             1
VINTAGE                                        1
INDIAN CHIEF                                   1
SPRINGFIELD                                    1
FTR 1200S                                      1
DARKHORSE                                      1
EXPENG G6                                      1
P7                                             1
G3                                             1
LYNK CO                                        1
9                                              1
DUKE 690                                       1
TUNLAND BJ1037                                 1
C1 VAN PASSENGER                               1
BJ6549 C5                                      1
250 DUKE                                       1
DUKE                                           1
690                                            1
ADVENTURE                                      1
RC 200                                         1
250 SX-F                                       1
890                                            1
GC6                                            1
890 ADVENTUR                                   1
AXLE                                           1
XENON/SINGLE-CABIN PICK UP                     1
608                                            1
TATA/1618/BUS                                  1
LIGHT TRUCK                                    1
MY22                                           1
R                                              1
1618C                                          1
1316                                           1
1316-55                                        1
INDIGO                                         1
PRIMA                                          1
PRO 2000                                       1
BJ41896 AUMAN GTL E                            1
VAN MT DIESEL                                  1
BJ1078                                         1
C2S W                                          1
BJ 6549 C 5                                    1
BJ6549-C5                                      1
BJ5039                                         1
RR 801V U                                      1
FH200LC                                        1
RST                                            1
TOANO                                          1
سي 2 اس دبلي                                   1
TXIOMARK                                       1
AUV                                            1
ESPIRT                                         1
SPEEDTRAIL                                     1
FORT-WO                                        1
AS2                                            1
SMART/4-2/COUPE                                1
ELF5                                           1
B8 JEEP                                        1
FA                                             1
OUSTER                                         1
RR 551 ULTRA                                   1
FX200                                          1
CUSTOM 1000 R                                  1
PANEL VAN                                      1
VERICA                                         1
CPC                                            1
VAN CARGO                                      1
D260 PANEL VAN                                 1
7Z                                             1
PANEL                                          1
YUMSUN                                         1
KYD3000D1                                      1
KYD3000D1 (ELECTRIC BIKE)                      1
X3 PRO (2WD)                                   1
NX150                                          1
STREET BIKE 175 ME                             1
JUMPY                                          1
C4 GRAND PICASSO                               1
2CV6                                           1
770                                            1
GL770 ULTRA                                    1
AYED250N 3GP                                   1
GL250                                          1
TERRIN                                         1
RR301 UL                                       1
RST 322 ULTRA                                  1
RST200 ULTRA                                   1
RST 750 ULTRA                                  1
VESPIA 150                                     1
ULTRA                                          1
P451                                           1
FX350                                          1
WU 410 L                                       1
300 SERIES 716 LWB                             1
WU410                                          1
VESPIRO 150                                    1
SHARMAX/RR 661                                 1
GL570 ULTRA                                    1
FX200 (MOTORCYCLE)                             1

In [257]:
import re

def looks_like_code(x):
    x = str(x)

    return (
        len(x) >= 6
        and any(c.isdigit() for c in x)
        and any(c.isalpha() for c in x)
        and re.fullmatch(r"[A-Z0-9\-\s]+", x)
    )

In [258]:
suspects = (
    df_clean["model_family"]
    .value_counts()
    .reset_index()
)

suspects.columns = ["model_family", "count"]

suspects = suspects[
    suspects["count"] <= 5
]

suspects.sort_values("model_family")

                                     model_family  count
2153                                           #1      3
3230                                         $350      1
3178                                         $400      1
3105                                         $430      1
2302                                         $500      2
2313                                         $550      2
3872                                        - 150      1
3059                            - EMZOOM 1.5TG GS      1
3779                                      - JISHI      1
3774                             - JISHI 01 (2WD)      1
1693                                    - SIXTIES      5
3780                                         / 01      1
4624                                     / 1000CC      1
2801                           / PATROL / STATION      1
2037                                            0      3
4127                                         0.60      1
1926                                       0.60 G      3
4622                               01 LS AUTO LEV      1
4668                                          03T      1
2633                                           05      2
2162                                           06      3
2594                                           07      2
1893                                           08      4
4599                                       090 BS      1
3398                                     1 SERIES      1
3443                             1 SERIES M COUPE      1
2736                                       1.8 XS      1
1700                                         10 G      5
2486                                          100      2
2922                                    100 HONDA      1
1625                                         1000      5
3423                                      1000 CC      1
1955                              1000 MOTORCYCLE      3
2917                                       1000CC      1
3365                                       1000RR      1
1809                                       1000XR      4
4190                                        1000Z      1
4605                                         100P      1
2420                                          101      2
4628                                         1040      1
4604                                    1040BUFAY      1
2679                                       106 BF      2
4564                                         1060      1
4638                                       1060 G      1
1946                                         1100      3
4078                                       1100CC      1
3434                                        118 D      1
2411                                          120      2
3386                                    120 COUPE      1
3432                                       1200 K      1
1920                                       1200GX      3
3435                                        1200K      1
3199                                         1222      1
2107                                   124 SPIDER      3
2161                                     125 DUKE      3
3576                                        125 H      1
3513                            125 HK/MOTORCYCLE      1
1937                                        125CC      3
2967                                        125MS      1
1887                                         1290      4
2629                         1290 SUPER ADVENTURE      2
1888                            1290 SUPER DUKE R      4
2570                                   12CILINDRI      2
3604                                      1300 CC      1
2390                                     1300 G S      2
2382                                      1300 GS      2
3507                                     1300 GSX      1
3463                                       1300RS      1
3106                                         1313      1
4349                                         1316      1
4348                                      1316-55      1
3456                                 14 EDRIVE 40      1
4177                                          147      1
2389                                           15      2
2836                                       15 250      1
2865                                       150 CB      1
2507                            150 CC/MOTORCYCLE      2
4242                                   150 ES GSO      1
2649                                      150 VXL      2
3865                               150/MOTORCYCLE      1
2483                    1500/PICK UP DOUBLE CABIN      2
2508                                        150BM      2
3880                          150CC DELIVERY BIKE      1
3858                                        150CE      1
1901                                        150NK      4
2605                                         150T      2
4467                                       150VXL      1
2126                                          156      3
1866                                          159      4
3874                                        159CC      1
2506                                15M. OF PASS.      2
2925                                         1600      1
2626                                         1618      2
4350                                        1618C      1
3183                                         1622      1
3264                                         1627      1
3175                                         1735      1
2115                                          175      3
2612                                 175 ME ULTRA      2
4653                    175 SHARMAX - STREET BIKE      1
2083                                          180      3
2996                                         1800      1
2984                                       1800CC      1
3206                                         1823      1
3243                                         1828      1
3251                                         1831      1
3131                                       1831LS      1
3307                                         1832      1
3160                                         1845      1
1981                                         1848      3
3092                                1922 MERCEDES      1
3022                                           20      1
3218                                      200 CLA      1
3195                                      200 CLC      1
1891                                     200 DUKE      4
3918                                        20000      1
1850                                         200C      4
2813                                         200T      1
2834                                  200ZX (CAR)      1
2867                                         2027      1
4633                                     212(4WD)      1
2909                                         2150      1
3372                                  218 I GRAND      1
3232                                        220 C      1
3868                                220 CC CRUISE      1
3646                                         2200      1
3437                                         220D      1
3123                                         2219      1
2215                                          225      2
2021                           225I ACTIVE TOURER      3
3431                                          228      1
2351                                          230      2
3122                                      230 CLK      1
3117                                        230GE      1
2009                                          235      3
3370                                         235I      1
2758                                          240      1
2754                           2400 PICK UP CARGO      1
3171                                        240GD      1
4618                                         2410      1
1974                                         2435      3
2708                          25 CA SON P 2.5L AT      1
1957                                       250 CC      3
4366                                     250 DUKE      1
4559                                       250 H7      1
4361                                     250 SX-F      1
3720                    2500/PICK UP DOUBLE CABIN      1
4233                                        250CC      1
4549                                250H 7 RST250      1
2332                                         2538      2
2359                                         2540      2
3182                                         2543      1
3147                                         2544      1
2719                          25PR 5 DR P 2.4L AT      1
2712          26 YA HB P 1.6L AT TURBO GR RA(CAR)      1
3233                                        260 E      1
3104                                         2628      1
4615                                       263-18      1
2344                                         2631      2
3138                                         2636      1
2318                                         2638      2
3101                                         2641      1
3226                     2641 DRINKING WATER TANK      1
2345                                         2644      2
1964                                         2700      3
4495                                          280      1
2315                                       280 CE      2
3220                                       280 GE      1
2743                                       280 ZX      1
3236                                        280GE      1
2203                                        280ZX      2
2122                                      296 GTB      3
4176                                      296 GTS      1
4271                                         2CV6      1
3808                                          2GX      1
2046                                      3 SEDAN      3
3368                                     3 SERIES      1
3657                                      3 SPORT      1
4583                                    3 WHEELER      1
4456                                       30-380      1
3216                                        300 G      1
3176                                       300 GE      1
1978                                      300 GLK      3
2147                            300 PICK UP CARGO      3
3151                                        300 R      1
3201                                       300 SE      1
3992                                    300 SEDAN      1
4256                           300 SERIES 716 LWB      1
2054                                       300 ZX      3
3994                                    300/SEDAN      1
2861                                      3000 GT      1
2241                                       3000GT      2
3093                                         300E      1
4526                                         302R      1
3017                                        30DF7      1
1799                                          316      4
2399                                          318      2
3429                                        320 K      1
3461                                    320 SEDAN      1
3371                                        320 T      1
1657                                         3201      5
3388                                        32011      1
1664                                        320CI      5
3400                                        320LI      1
3454                                       323 TA      1
3451                                        325 I      1
3440                                         3251      1
3405                                        325XI      1
2376                                        328 I      2
1803                                          330      4
3452                                       330 CI      1
3458                                 330 CI COUPE      1
3446                                        330 I      1
3360                                       330 IA      1
4218                                       330-25      1
2018                                         3301      3
2409                                         330E      2
3146                                      3331 45      1
3246                                3331 MERCEDES      1
1651                                         3348      5
2013                                          335      3
1800                                        335CI      4
3367                                340I M XDRIVE      1
4167                                          348      1
4166                                       348 TS      1
4663                                           35      1
2685                     350 SHARMAX - SHARMAX FX      2
2350                                         3500      2
3652                                       3500 T      1
3474                                       3500HD      1
2637                                        350CC      2
3234                                         3538      1
4181                                35C VAN CARGO      1
3667                                         35EX      1
3665                                          35M      1
2123                                   360 MODENA      3
3072                                         3600      1
1830                                         37 G      4
2787                                   370Z COUPE      1
2049                                          37M      3
4457                                          380      1
2358                                         3848      2
1630                                          390      5
2630                                390 ADVENTURE      2
4688                                          3CX      1
3375                                     4 SERIES      1
2154                                          4-2      3
2990                                          400      1
4415                                       400 CC      1
2314                                      400 GLE      2
3188                                 400 MERCEDES      1
3087                               4000 VAN CARGO      1
3540                                        400CC      1
1979                                         4031      3
3670                                          40Q      1
4621                                          410      1
3441                                        420 D      1
3249                                      420 SEL      1
4634                                        422 F      1
2405                                       428 GC      2
3235                                         43 C      1
2343                                          430      2
3420                                          440      1
4524                                        44629      1
4447                                        45 SR      1
4627                                          450      1
4442                                      450 CLC      1
2645                                       450 MT      2
4570                                    450 RALLY      1
2631                                     450 SX-F      2
4443                                         450M      1
2171                                        450NK      3
1865                                          458      4
3042                                        46 HD      1
2812                                          460      1
2220                                       460 LS      2
2124                                           4C      3
2385                                  5 SERIES GT      2
3466                                  5 SERIES M6      1
3656                                        50 BT      1
3863                    50 CC/MOTORCYCLE DELIVERY      1
1679                                        50 QX      5
4055                               500 DOLCE VITA      1
4062                              500 DOLCE VITAL      1
3181                                      500 SEC      1
3127                                      500 SEL      1
4249                                500 SERIES GH      1
3204                                      500 SLC      1
3198                                       5000 U      1
2407                                        500CC      2
4059                                         500L      1
4665                                        500RR      1
1785                                        500SL      4
4453                                        50C15      1
4170                                          512      1
4168                                       512 TR      1
1659                                          520      5
3450                                         5201      1
3382                                         520D      1
3357                                          523      1
1808                                          525      4
3364                                        525 1      1
1802                                        525 I      4
3352                                        525 T      1
1662                                         5251      5
2026                                          528      3
1797                                        528 I      4
2393                                         5281      2
3465                                        530 I      1
2378                                         530E      2
3459                                        530LI      1
1812                                          535      4
3379                                         5351      1
3406                                         545I      1
3169                                         55 E      1
2471                                          550      2
3374                                         5501      1
3165                                         5550      1
3177                                       560 SE      1
1640                                      560 SEL      5
1995                                        560SL      3
3661                                          56M      1
1992                                           57      3
2619                                        570GT      2
4164                                          599      1
3363                                     6 SERIES      1
3354                                  6 SERIES GT      1
2863                                      600 CBR      1
2622                                        600LT      2
3769                                          607      1
4355                                          608      1
4173                                    612 COUPE      1
2627                                          613      2
2676                                           62      2
4591                                         62 S      1
2394                                          635      2
2022                                      635 CSI      3
3353                                          640      1
2388                                          645      2
2387                                       645 CI      2
3383                                         645I      1
3418                                        650 F      1
3536                                        650CC      1
2172                                        650GT      3
2386                              650I GRAN COUPE      2
4445                                        650NK      1
2620                                        675LT      2
4611                                        675NK      1
2141                                        675SR      3

In [259]:
suspects["contains_slash"] = suspects["model_family"].str.contains("/")
suspects["contains_paren"] = suspects["model_family"].str.contains(r"\(")
suspects["starts_digit"] = suspects["model_family"].str.match(r"^\d")
suspects["long_name"] = suspects["model_family"].str.len() > 20

In [261]:
df.columns

Index(['chassisNumber', 'year', 'make', 'model', 'trim', 'bodyType',
       'regionalSpec', 'cylinders', 'color', 'origin', 'weightInKg',
       'noOfPassengers'],
      dtype='str')

In [262]:
make_model_counts = (
    df.groupby(["make", "model"])
      .size()
      .reset_index(name="count")
)

In [263]:
rare_pairs = make_model_counts[
    make_model_counts["count"] <= 5
].sort_values(["make", "count"])

rare_pairs.head(200)

              make                      model  count
0           ABARTH                 124 SPIDER      1
1           ABARTH                     330-25      1
3           ABARTH                      675SR      1
5           ABARTH                       ES 3      1
6           ABARTH                    PARTNER      1
8            ACURA                         LX      1
11           ACURA                         TL      1
7            ACURA                    INTEGRA      2
9            ACURA                        RDX      2
10           ACURA                        RSX      2
12           ACURA                        TLX      3
13         ADMIRAL                        225      1
16          AEOLUS                   PRO 2000      1
15          AEOLUS                       MAGE      2
19           AIQAR                       EQ 1      1
20            AITO                   DRAGSTER      1
21            AITO                         M7      3
24      ALFA ROMEO                        147      1
32      ALFA ROMEO                         H9      1
28      ALFA ROMEO                      BRERA      2
31      ALFA ROMEO                        GTV      2
25      ALFA ROMEO                        156      3
27      ALFA ROMEO                         4C      3
33      ALFA ROMEO                       MITO      3
26      ALFA ROMEO                        159      4
36          APACHE                     RTR160      1
37         APRILIA                        150      1
38         APRILIA                        750      1
39         APRILIA                     AR 125      1
40         APRILIA                  AYED250H7      1
41         APRILIA             CHIEFTAIN 1400      1
42         APRILIA                       CUBE      1
43         APRILIA                  GP 881 UL      1
44         APRILIA            HARLEY DAVIDSON      1
46         APRILIA                     RS 660      1
47         APRILIA           RST 240 AYED250H      1
48         APRILIA                    RST 322      1
49         APRILIA                     RST200      1
50         APRILIA                 RSV 1000 R      1
51         APRILIA                 RSV 4 1100      1
52         APRILIA                  RSV4 1000      1
53         APRILIA                 SIXTIES 17      1
54         APRILIA                     SPYDER      1
55         APRILIA                     SR 150      1
58         APRILIA                      TUONO      1
59         APRILIA                  TUONO 125      1
60         APRILIA                  TUONO 660      1
61         APRILIA              TUONO V4 1100      1
57         APRILIA                       TANK      2
56         APRILIA                     SX 125      4
62          APULUO                   AP200 4H      1
63             ARI                       ATOM      1
64           ASHOK                    LEYLAND      1
65   ASHOK LEYLAND                         FA      1
68   ASHOK LEYLAND                LIGHT TRUCK      1
69   ASHOK LEYLAND                     OUSTER      1
70   ASHOK LEYLAND                     OYSTER      5
77    ASTON MARTIN                    DBX 707      1
81    ASTON MARTIN                   VALHALLA      1
82    ASTON MARTIN                     VALOUR      1
85    ASTON MARTIN                     VIRAGE      2
80    ASTON MARTIN                   RAPIDE S      3
78    ASTON MARTIN                     DBX707      4
86            AUDI                        100      1
87            AUDI                        A 8      1
100           AUDI               Q3 SPORTBACK      1
102           AUDI                  Q4 E TRON      1
104           AUDI                  Q6 E-TRON      1
107           AUDI                  Q8 E-TRON      1
109           AUDI   RS 3 SPORTBACK HATCHBACK      1
110           AUDI                       RS 5      1
118           AUDI                      RSQ 8      1
128           AUDI                 SQ6 E-TRON      1
114           AUDI                        RS4      2
95            AUDI                     E TRON      3
112           AUDI                      RS Q8      3
116           AUDI                        RS6      3
129           AUDI                        SQ7      3
111           AUDI               RS E-TRON GT      4
97            AUDI                  E-TRON GT      5
135          AVATR                     AVATAR      1
136          AVATR                  AVATAR 07      1
137          AVATR                  AVATAR 11      1
139          AVATR                       JEEP      1
140          AVATR                        MDX      1
132          AVATR                         07      2
138          AVATR                  AVATAR 12      3
141        AVENGER                        220      2
142           AYED                     250 H7      1
143           AYED              250H 7 RST250      1
144           AYED              AYED250H 7 RS      1
145           AYED               AYED250N 3 G      1
146           AYED            BIKE 150T FORCE      1
148           AYED              BIKE AYED250N      1
149           AYED                      D250N      1
147           AYED               BIKE AYED250      3
150           BAIC                         A1      1
152           BAIC                      A520T      1
153           BAIC                      BJ 40      1
154           BAIC                       BJ30      1
164           BAIC                 BJJ40 PLUS      1
165           BAIC                GRAND TIGER      1
166           BAIC                   KENBO S6      1
167           BAIC               MONGOOSE 270      1
169           BAIC                    US PLUS      1
173           BAIC                        X65      1
170           BAIC                        VXL      2
151           BAIC                       A115      5
175           BAJA                       MT09      1
176          BAJAJ                      - 150      1
177          BAJAJ                        100      1
179          BAJAJ                      125CC      1
183          BAJAJ             150/MOTORCYCLE      1
186          BAJAJ        150CC DELIVERY BIKE      1
187          BAJAJ                      150CE      1
188          BAJAJ                      159CC      1
197          BAJAJ              220 CC CRUISE      1
199          BAJAJ                        250      1
200          BAJAJ  50 CC/MOTORCYCLE DELIVERY      1
201          BAJAJ                     ACCORD      1
202          BAJAJ                   AP200 4H      1
204          BAJAJ                      B 150      1
206          BAJAJ                BAJAJ-220CC      1
207          BAJAJ                     BAJAJA      1
208          BAJAJ                 BAJAL 15M.      1
210          BAJAJ                       BK9E      1
212          BAJAJ                    BM150CC      1
213          BAJAJ                        BMW      1
215          BAJAJ                     BULSAR      1
218          BAJAJ                      C 200      1
219          BAJAJ                      C 220      1
220          BAJAJ                     CC 200      1
223          BAJAJ                   CITY 100      1
224          BAJAJ                    CNI 180      1
225          BAJAJ                     CS 220      1
228          BAJAJ                      CT100      1
231          BAJAJ                DOMINAR 400      1
233          BAJAJ                    DOMINOR      1
234          BAJAJ              DOMINOR 400CC      1
235          BAJAJ                    FLHTCUI      1
236          BAJAJ              GALAXY M13 5G      1
237          BAJAJ                   GRS 4531      1
238          BAJAJ                       HILL      1
239          BAJAJ                  MI SI 150      1
240          BAJAJ                  MI SI 180      1
241          BAJAJ                  MI TE 100      1
242          BAJAJ                   MINI 150      1
243          BAJAJ                  MODEL 180      1
244          BAJAJ                 MODEL 2011      1
245          BAJAJ                 MODEL 2020      1
246          BAJAJ                 MODEL 2021      1
247          BAJAJ                 MODEL 2026      1
248          BAJAJ                     NCE UP      1
249          BAJAJ                       P150      1
252          BAJAJ                         PU      1
253          BAJAJ               PUL.SAP. 150      1
254          BAJAJ               PULS R 220CC      1
259          BAJAJ               PULSAR 1800C      1
262          BAJAJ                PULSAR 200C      1
268          BAJAJ                PULSAR 80CC      1
269          BAJAJ                PULSAR N250      1
271          BAJAJ               PULSAR RS200      1
272          BAJAJ         RH1250S/MOTORCYCLE      1
273          BAJAJ                     RS 660      1
274          BAJAJ                   SISU 180      1
275          BAJAJ                SIXTIES 175      1
276          BAJAJ                  SLINGSHOT      1
277          BAJAJ                STAR HLX150      1
279          BAJAJ            TV BAJAJ 220 CC      1
280          BAJAJ                    UNICORN      1
281          BAJAJ                     VELAIC      1
282          BAJAJ                    VENTURE      1
283          BAJAJ                     YZF R1      1
284          BAJAJ           اف اكس 150 الترا      1
285          BAJAJ                     سي 150      1
286          BAJAJ                  مي سي 150      1
287          BAJAJ                   ميتي 100      1
182          BAJAJ          150 CC/MOTORCYCLE      2
184          BAJAJ                      150BM      2
189          BAJAJ              15M. OF PASS.      2
190          BAJAJ                        160      2
217          BAJAJ                      C 180      2
230          BAJAJ                    DOMINAR      2
251          BAJAJ                     POLSAR      2
264          BAJAJ                 PULSAR 220      2
270          BAJAJ               PULSAR NS200      2
278          BAJAJ                     SY150T      2
191          BAJAJ                        180      3
209          BAJAJ                     BALZAR      3
211          BAJAJ                     BM 150      3
214          BAJAJ                      BOXER      3
222          BAJAJ                      CC150      3
227          BAJAJ                     CT 110      3
232          BAJAJ              DOMINAR 400CC      3
267          BAJAJ                PULSAR 220F      3
229          BAJAJ        DELIVERY MOTORCYCLE      4
195          BAJAJ                        220      5
221          BAJAJ                     CC 220      5
265          BAJAJ                PULSAR 220C      5
288         BAOJUN                YEP/STATION      1

In [265]:
df_clean = df.copy()

In [266]:
df_clean["model_family"] = df_clean["model"]

In [267]:
df.groupby("make")["model"].nunique().sort_values(ascending=False).head(30)

make
MERCEDES BENZ      564
HONDA              420
BMW                346
SUZUKI             249
NISSAN             177
LEXUS              167
TOYOTA             165
HYUNDAI            112
BAJAJ              112
YAMAHA             102
KIA                101
FORD               101
CHEVROLET           91
HARLEY-DAVIDSON     89
BYD                 75
MITSUBISHI          71
VOLKSWAGEN          65
INFINITI            63
KAWASAKI            60
CHANGAN             54
SHARMAX             54
FERRARI             52
MAZDA               52
AUDI                46
ISUZU               46
GMC                 45
GEELY               39
CADILLAC            39
VESPA               39
MG                  39
Name: model, dtype: int64

In [268]:
(
    df.groupby(["make", "model"])
      .size()
      .reset_index(name="count")
      .query("count <= 5")
      .sort_values(["make", "count"])
)

                   make                                        model  count
0                ABARTH                                   124 SPIDER      1
1                ABARTH                                       330-25      1
3                ABARTH                                        675SR      1
5                ABARTH                                         ES 3      1
6                ABARTH                                      PARTNER      1
8                 ACURA                                           LX      1
11                ACURA                                           TL      1
7                 ACURA                                      INTEGRA      2
9                 ACURA                                          RDX      2
10                ACURA                                          RSX      2
12                ACURA                                          TLX      3
13              ADMIRAL                                          225      1
16               AEOLUS                                     PRO 2000      1
15               AEOLUS                                         MAGE      2
19                AIQAR                                         EQ 1      1
20                 AITO                                     DRAGSTER      1
21                 AITO                                           M7      3
24           ALFA ROMEO                                          147      1
32           ALFA ROMEO                                           H9      1
28           ALFA ROMEO                                        BRERA      2
31           ALFA ROMEO                                          GTV      2
25           ALFA ROMEO                                          156      3
27           ALFA ROMEO                                           4C      3
33           ALFA ROMEO                                         MITO      3
26           ALFA ROMEO                                          159      4
36               APACHE                                       RTR160      1
37              APRILIA                                          150      1
38              APRILIA                                          750      1
39              APRILIA                                       AR 125      1
40              APRILIA                                    AYED250H7      1
41              APRILIA                               CHIEFTAIN 1400      1
42              APRILIA                                         CUBE      1
43              APRILIA                                    GP 881 UL      1
44              APRILIA                              HARLEY DAVIDSON      1
46              APRILIA                                       RS 660      1
47              APRILIA                             RST 240 AYED250H      1
48              APRILIA                                      RST 322      1
49              APRILIA                                       RST200      1
50              APRILIA                                   RSV 1000 R      1
51              APRILIA                                   RSV 4 1100      1
52              APRILIA                                    RSV4 1000      1
53              APRILIA                                   SIXTIES 17      1
54              APRILIA                                       SPYDER      1
55              APRILIA                                       SR 150      1
58              APRILIA                                        TUONO      1
59              APRILIA                                    TUONO 125      1
60              APRILIA                                    TUONO 660      1
61              APRILIA                                TUONO V4 1100      1
57              APRILIA                                         TANK      2
56              APRILIA                                       SX 125      4
62               APULUO                                     AP200 4H      1
63                  ARI                                         ATOM      1
64                ASHOK                                      LEYLAND      1
65        ASHOK LEYLAND                                           FA      1
68        ASHOK LEYLAND                                  LIGHT TRUCK      1
69        ASHOK LEYLAND                                       OUSTER      1
70        ASHOK LEYLAND                                       OYSTER      5
77         ASTON MARTIN                                      DBX 707      1
81         ASTON MARTIN                                     VALHALLA      1
82         ASTON MARTIN                                       VALOUR      1
85         ASTON MARTIN                                       VIRAGE      2
80         ASTON MARTIN                                     RAPIDE S      3
78         ASTON MARTIN                                       DBX707      4
86                 AUDI                                          100      1
87                 AUDI                                          A 8      1
100                AUDI                                 Q3 SPORTBACK      1
102                AUDI                                    Q4 E TRON      1
104                AUDI                                    Q6 E-TRON      1
107                AUDI                                    Q8 E-TRON      1
109                AUDI                     RS 3 SPORTBACK HATCHBACK      1
110                AUDI                                         RS 5      1
118                AUDI                                        RSQ 8      1
128                AUDI                                   SQ6 E-TRON      1
114                AUDI                                          RS4      2
95                 AUDI                                       E TRON      3
112                AUDI                                        RS Q8      3
116                AUDI                                          RS6      3
129                AUDI                                          SQ7      3
111                AUDI                                 RS E-TRON GT      4
97                 AUDI                                    E-TRON GT      5
135               AVATR                                       AVATAR      1
136               AVATR                                    AVATAR 07      1
137               AVATR                                    AVATAR 11      1
139               AVATR                                         JEEP      1
140               AVATR                                          MDX      1
132               AVATR                                           07      2
138               AVATR                                    AVATAR 12      3
141             AVENGER                                          220      2
142                AYED                                       250 H7      1
143                AYED                                250H 7 RST250      1
144                AYED                                AYED250H 7 RS      1
145                AYED                                 AYED250N 3 G      1
146                AYED                              BIKE 150T FORCE      1
148                AYED                                BIKE AYED250N      1
149                AYED                                        D250N      1
147                AYED                                 BIKE AYED250      3
150                BAIC                                           A1      1
152                BAIC                                        A520T      1
153                BAIC                                        BJ 40      1
154                BAIC                                         BJ30      1
164                BAIC                                   BJJ40 PLUS      1
165                BAIC                                  GRAND TIGER      1
166                BAIC                                     KENBO S6      1
167                BAIC                                 MONGOOSE 270      1
169                BAIC                                      US PLUS      1
173                BAIC                                          X65      1
170                BAIC                                          VXL      2
151                BAIC                                         A115      5
175                BAJA                                         MT09      1
176               BAJAJ                                        - 150      1
177               BAJAJ                                          100      1
179               BAJAJ                                        125CC      1
183               BAJAJ                               150/MOTORCYCLE      1
186               BAJAJ                          150CC DELIVERY BIKE      1
187               BAJAJ                                        150CE      1
188               BAJAJ                                        159CC      1
197               BAJAJ                                220 CC CRUISE      1
199               BAJAJ                                          250      1
200               BAJAJ                    50 CC/MOTORCYCLE DELIVERY      1
201               BAJAJ                                       ACCORD      1
202               BAJAJ                                     AP200 4H      1
204               BAJAJ                                        B 150      1
206               BAJAJ                                  BAJAJ-220CC      1
207               BAJAJ                                       BAJAJA      1
208               BAJAJ                                   BAJAL 15M.      1
210               BAJAJ                                         BK9E      1
212               BAJAJ                                      BM150CC      1
213               BAJAJ                                          BMW      1
215               BAJAJ                                       BULSAR      1
218               BAJAJ                                        C 200      1
219               BAJAJ                                        C 220      1
220               BAJAJ                                       CC 200      1
223               BAJAJ                                     CITY 100      1
224               BAJAJ                                      CNI 180      1
225               BAJAJ                                       CS 220      1
228               BAJAJ                                        CT100      1
231               BAJAJ                                  DOMINAR 400      1
233               BAJAJ                                      DOMINOR      1
234               BAJAJ                                DOMINOR 400CC      1
235               BAJAJ                                      FLHTCUI      1
236               BAJAJ                                GALAXY M13 5G      1
237               BAJAJ                                     GRS 4531      1
238               BAJAJ                                         HILL      1
239               BAJAJ                                    MI SI 150      1
240               BAJAJ                                    MI SI 180      1
241               BAJAJ                                    MI TE 100      1
242               BAJAJ                                     MINI 150      1
243               BAJAJ                                    MODEL 180      1
244               BAJAJ                                   MODEL 2011      1
245               BAJAJ                                   MODEL 2020      1
246               BAJAJ                                   MODEL 2021      1
247               BAJAJ                                   MODEL 2026      1
248               BAJAJ                                       NCE UP      1
249               BAJAJ                                         P150      1
252               BAJAJ                                           PU      1
253               BAJAJ                                 PUL.SAP. 150      1
254               BAJAJ                                 PULS R 220CC      1
259               BAJAJ                                 PULSAR 1800C      1
262               BAJAJ                                  PULSAR 200C      1
268               BAJAJ                                  PULSAR 80CC      1
269               BAJAJ                                  PULSAR N250      1
271               BAJAJ                                 PULSAR RS200      1
272               BAJAJ                           RH1250S/MOTORCYCLE      1
273               BAJAJ                                       RS 660      1
274               BAJAJ                                     SISU 180      1
275               BAJAJ                                  SIXTIES 175      1
276               BAJAJ                                    SLINGSHOT      1
277               BAJAJ                                  STAR HLX150      1
279               BAJAJ                              TV BAJAJ 220 CC      1
280               BAJAJ                                      UNICORN      1
281               BAJAJ                                       VELAIC      1
282               BAJAJ                                      VENTURE      1
283               BAJAJ                                       YZF R1      1
284               BAJAJ                             اف اكس 150 الترا      1
285               BAJAJ                                       سي 150      1
286               BAJAJ                                    مي سي 150      1
287               BAJAJ                                     ميتي 100      1
182               BAJAJ                            150 CC/MOTORCYCLE      2
184               BAJAJ                                        150BM      2
189               BAJAJ                                15M. OF PASS.      2
190               BAJAJ                                          160      2
217               BAJAJ                                        C 180      2
230               BAJAJ                                      DOMINAR      2
251               BAJAJ                                       POLSAR      2
264               BAJAJ                                   PULSAR 220      2
270               BAJAJ                                 PULSAR NS200      2
278               BAJAJ                                       SY150T      2
191               BAJAJ                                          180      3
209               BAJAJ                                       BALZAR      3
211               BAJAJ                                       BM 150      3
214               BAJAJ                                        BOXER      3
222               BAJAJ                                        CC150      3
227               BAJAJ                                       CT 110      3
232               BAJAJ                                DOMINAR 400CC      3
267               BAJAJ                                  PULSAR 220F      3
229               BAJAJ                          DELIVERY MOTORCYCLE      4
195               BAJAJ                                          220      5
221               BAJAJ                                       CC 220      5
265               BAJAJ                                  PULSAR 220C      5
288              BAOJUN                                  YEP/STATION      1
290                 BAW                                     212(4WD)      1
291                 BAW                                           M7      1
292               BENDA                                          300      1
293               BENDA                                          450      1
294               BENDA                                          700      1
295             BENELLI                                         302R      1
296             BENELLI                                  SPEED STORM      1
297             BENELLI                                      TNT 125      1
299             BENELLI                                        TNT15      1
302             BENELLI                                       TRK502      1
298             BENELLI                                      TNT 150      2
300             BENELLI                                       TNT150      2
301             BENELLI                                      TRK 502      2
309             BENTLEY                                        ELGHT      1
312             BENTLEY                                     MULLINER      1
314             BENTLEY                                        TURBO      1
311             BENTLEY                                           GT      2
306             BENTLEY                                   BROOKLANDS      4
304             BENTLEY                                        AZURE      5
317             BESTUNE                                      NAT E05      1
316             BESTUNE                                         B70S      3
322                BETA                                      BEN P 6      1
323              BIMOTA                                   AYED250N 3      1
324           BLUE BIRD                                       VISION      1
325                 BMW                                     1 SERIES      1
326                 BMW                             1 SERIES M COUPE      1
327                 BMW                                      1000 CC      1
328                 BMW                                       1000RR      1
331                 BMW                                        118 D      1
334                 BMW                                    120 COUPE      1
335                 BMW                                       1200 K      1
336                 BMW                                        1200K      1
341                 BMW                                       1300RS      1
343                 BMW                                 14 EDRIVE 40      1
345                 BMW                                       150 CC      1
347                 BMW                                  218 I GRAND      1
352                 BMW                                          220      1
353                 BMW                                         220D      1
356                 BMW                                          228      1
359                 BMW                                          230      1
362                 BMW                                         235I      1
363                 BMW                                     3 SERIES      1
371                 BMW                                        320 K      1
372                 BMW                                    320 SEDAN      1
373                 BMW                                        320 T      1
375                 BMW                                        32011      1
379                 BMW                                        320LI      1
381                 BMW                                       323 TA      1
384                 BMW                                        325 I      1
385                 BMW                                         3251      1
388                 BMW                                        325XI      1
393                 BMW                                       330 CI      1
394                 BMW                                 330 CI COUPE      1
395                 BMW                                        330 I      1
396                 BMW                                       330 IA      1
405                 BMW                                340I M XDRIVE      1
406                 BMW                                     4 SERIES      1
408                 BMW                                        420 D      1
418                 BMW                                          440      1
423                 BMW                                  5 SERIES M6      1
424                 BMW                                        500CC      1
426                 BMW                                         5201      1

In [269]:
# Models appearing under multiple makes

model_make_count = (
    df.groupby("model")["make"]
      .nunique()
      .sort_values(ascending=False)
)

model_make_count[model_make_count > 1]

model
150                    10
SLINGSHOT               9
500                     7
IQ                      7
VXL                     6
ROCKY                   6
300                     6
SY150T                  6
3                       5
7                       5
350                     5
900                     5
01                      5
5                       5
SLING SHOT              5
MAGE                    4
150 CC                  4
SIXTIES 17              4
SIXTIES 175             4
MOTOR CYCLE             4
1                       4
RYKER                   4
VISION                  4
VXL 150                 4
700                     4
750                     4
HARLEY DAVIDSON         4
LX                      4
250                     4
X7                      4
VENICE                  4
GT                      4
SPYDER                  4
650                     4
007                     3
- SIXTIES               3
0                       3
695                     3
0.60 G                  3
X                       3
VESPA                   3
E 350                   3
FLHTK                   3
CH150T-34               3
BUS                     3
C5                      3
CC150                   3
LAGUNA                  3
L6                      3
HUNTER                  3
GS 300                  3
G70                     3
2500                    3
H9                      3
HERO                    3
125 CC                  3
CUBE                    3
CHALLENGER              3
TRAVELLER               3
DT175                   3
DRAGSTER                3
220                     3
200                     3
SIXTIES                 3
PARTNER                 3
SHINE                   3
SIERRA                  3
160                     3
NINJA 300               3
NKR                     3
NONE                    3
S07                     3
S                       3
RST200                  3
RICH                    3
SLINGS                  3
S7                      3
S5                      3
1000                    3
03                      2
ZNA                     2
Z9                      2
Z                       2
YZFR7                   2
YZF R7                  2
YZF R6                  2
YZF R3                  2
YZF R1                  2
XL 883 N                2
XL                      2
XA                      2
1000 MOTORCYCLE         2
ZX 300                  2
600                     2
6                       2
595                     2
57                      2
550                     2
530                     2
500CC                   2
430                     2
420                     2
4                       2
390                     2
ZX6R                    2
SAVANA                  2
S6                      2
S3                      2
S09                     2
S06                     2
S05                     2
S 300                   2
RTR160 4V               2
RTR160                  2
RSX                     2
RST 422 ULTRA           2
RS 660                  2
ROSA                    2
RH1250S                 2
RANGE ROVER VOGUE       2
RADAR                   2
R1                      2
QY50K                   2
QX 56                   2
Q5                      2
PICKUP SINGLE CABIN     2
2                       2
PICKUP                  2
PICK UP CARGO           2
SLR                     2
SIXTIES 300             2
SILVERADO               2
SILVER                  2
SEVEN                   2
1500                    2
SEDAN                   2
PANIGALE                2
ONE                     2
NTORQ 125               2
NHR                     2
NEON                    2
MUSTANG                 2
MTN 890                 2
MT09                    2
MT-09                   2
207                     2
MODEL 2022              2
MODEL 2020              2
ML350                   2
MATRIX                  2
MAGNUM                  2
M8                      2
M7                      2
M5                      2
M4                      2
M3                      2
M 5                     2
M 3                     2
225                     2
LS350                   2
LS 460                  2
LIBERTY                 2
LF1502                  2
LF 150 2                2
LEYLAND                 2
LEOPARD 5               2
L9                      2
JX3043XSG2              2
JEEP                    2
J7                      2
J5                      2
230                     2
124 SPIDER              2
100                     2
SZ 150                  2
SUPERBAN                2
SUBURBAN                2
STREET TRIPLE           2
STREET BIKE 175         2
STREET                  2
STAR HLX150             2
SPRINTER                2
SPORTAGE                2
1300CC                  2
SMART                   2
INTEGRA                 2
I5                      2
I30                     2
HURACAN                 2
HIM                     2
HILUX                   2
HATCHBACK               2
HARLEY DAVIDSON FAT     2
HARLEY DAVIDSON F       2
H7                      2
H3                      2
H2                      2
H1                      2
GX460                   2
GV80                    2
GV70                    2
GTV                     2
GTS 300                 2
GTS                     2
GS5                     2
GS4                     2
GS300                   2
GS3                     2
GRS 4531                2
GRAND                   2
GP 881 UL               2
G90                     2
G80                     2
G318                    2
FRONTIER                2
FREELANDER              2
FREE                    2
FOZO                    2
FORTWO                  2
FLTRXS                  2
250 CC                  2
FLHTCUI                 2
FH                      2
F7                      2
F150                    2
EXPRESS                 2
EV                      2
ET5                     2
ES8                     2
ES                      2
EQ900                   2
ENVOY                   2
ENDURO 300              2
ENDURO 250              2
ENCLAVE                 2
ECHO                    2
EC7                     2
EC6                     2
E5                      2
E450                    2
E350                    2
E250                    2
E 450                   2
DEXER                   2
DEVILLE                 2
DELTA                   2
DELIVERY MOTORCYCLE     2
DELIVERY BIKE           2
DEFENDER                2
UNICORN                 2
U7                      2
TURBO                   2
TRUCK                   2
TRANSIT                 2
TIIDA                   2
THUNDERBIRD             2
THRUXTON                2
T60                     2
T5 HEV                  2
T 300                   2
125CC                   2
125                     2
DARK HORSE              2
CRUZE                   2
COUNTRYMAN              2
CONTINENTAL             2
CH150                   2
CAMRY                   2
CARMEL                  2
CARAVAN                 2
CANTER                  2
323                     2
C35                     2
C200                    2
C 300 SEDAN             2
C11                     2
C 300                   2
C 220                   2
C 200                   2
C 180                   2
C 16                    2
BOXER                   2
BMW                     2
BK9E                    2
BA                      2
B200                    2
AX7                     2
AVENGER                 2
X6                      2
X5                      2
VX                      2
VULCAN 1700             2
VULCAN                  2
VOGUE                   2
VICTORY                 2
VESPITO                 2
1100                    2
VENTURE                 2
AP200 4H                2
ALTIMA                  2
A1                      2
ACCORD                  2
A                       2
911                     2
750 CC                  2
800MT                   2
3500                    2
675SR                   2
ZX 280                  2
                        2
Name: make, dtype: int64

In [270]:
suspect_models = (
    df.groupby("model")["make"]
      .nunique()
      .loc[lambda x: x >= 3]
      .index
)

df[df["model"].isin(suspect_models)] \
    .sort_values(["model", "make"]) \
    [["make", "model"]] \
    .drop_duplicates()

                      make            model
972843               HONDA        - SIXTIES
1003456              VESPA        - SIXTIES
1008710            VICTORY        - SIXTIES
989462               SKODA                0
837582              SUZUKI                0
1003453              VESPA                0
594084               HONDA           0.60 G
645273             HYUNDAI           0.60 G
350069              NISSAN           0.60 G
1007571           DONGFENG              007
1008992         DONGFENG E              007
1002713              ZEEKR              007
808081                 GMC               01
1008849               JIDU               01
1009334              JIYUE               01
1007039          LYNK & CO               01
944114                 ROX               01
972238               HONDA                1
897607                  MG                1
1009577              MHERO                1
944146                 ROX                1
573510               HONDA             1000
1002161           KAWASAKI             1000
997958              YAMAHA             1000
563342               HONDA           125 CC
1009193              KYMCO           125 CC
1008727                SYM           125 CC
1007415            APRILIA              150
963442               BAJAJ              150
769958                FORD              150
1009500          HART FORD              150
568057               HONDA              150
686896                 KIA              150
266744              NISSAN              150
1004434              SANYA              150
1003407              VESPA              150
1005022              VOYAH              150
963358               BAJAJ           150 CC
791779                 BMW           150 CC
595114               HONDA           150 CC
463651               LEXUS           150 CC
964063               BAJAJ              160
566192               HONDA              160
1003213                TVS              160
988113            CHRYSLER              200
520723          MITSUBISHI              200
368210              NISSAN              200
1009398            AVENGER              220
963382               BAJAJ              220
792763                 BMW              220
965145               BAJAJ              250
998457     HARLEY-DAVIDSON              250
572303               HONDA              250
834267              SUZUKI              250
912963               DODGE             2500
810593                 GMC             2500
957270                 RAM             2500
992032          GREAT WALL                3
863740               MAZDA                3
891099                  MG                3
1005905           POLESTAR                3
783167               TESLA                3
1009374              BENDA              300
988120            CHRYSLER              300
991625          GREAT WALL              300
1004271               HINO              300
693156       MERCEDES BENZ              300
994979                TANK              300
769379                FORD              350
456133               LEXUS              350
695471       MERCEDES BENZ              350
891109                  MG              350
1007298      ROYAL ENFIELD              350
1007035          LYNK & CO                5
865317               MAZDA                5
891084                  MG                5
1001229             RABDAN                5
1007231              SERES                5
997045                FIAT              500
775416                FORD              500
991752          GREAT WALL              500
691139       MERCEDES BENZ              500
1007229      ROYAL ENFIELD              500
841106              SUZUKI              500
994980                TANK              500
802619                 BMW              650
561159               HONDA              650
834828              SUZUKI              650
1008941             YAMAHA              650
1002929             ABARTH              695
997072                FIAT              695
417792              NISSAN              695
1007558           DONGFENG                7
954038               GEELY                7
891075                  MG                7
1009172              OMODA                7
1007207              SERES                7
1009371              BENDA              700
1004317               HINO              700
589696               HONDA              700
995004                TANK              700
1007395            APRILIA              750
789878                 BMW              750
564868               HONDA              750
832890              SUZUKI              750
1002150           KAWASAKI              900
1009373              LYKAN              900
1007032          LYNK & CO              900
1008923               SAAB              900
194949              TOYOTA              900
993069               CHERY              BUS
1008632          KING LONG              BUS
1006788               TATA              BUS
1005105            CITROEN               C5
985147                HERO               C5
1009156              OMODA               C5
963839               BAJAJ            CC150
1009080                TGB            CC150
997924              YAMAHA            CC150
934336             CHANGAN        CH150T-34
1009293           CHANGHUA        CH150T-34
461462               LEXUS        CH150T-34
910627               DODGE       CHALLENGER
766227                FORD       CHALLENGER
1007160  INDIAN MOTORCYCLE       CHALLENGER
1007425            APRILIA             CUBE
253110              NISSAN             CUBE
1009140           ZONGSHEN             CUBE
1007943               AITO         DRAGSTER
1009496            ITALJET         DRAGSTER
1009219          MV AGUSTA         DRAGSTER
608298               HONDA            DT175
836415              SUZUKI            DT175
997856              YAMAHA            DT175
751251                FORD            E 350
497069               LEXUS            E 350
699892       MERCEDES BENZ            E 350
998310     HARLEY-DAVIDSON            FLHTK
593483               HONDA            FLHTK
158658              TOYOTA            FLHTK
978044             GENESIS              G70
646414             HYUNDAI              G70
313769              NISSAN              G70
966981                 GAC           GS 300
452717               LEXUS           GS 300
150374              TOYOTA           GS 300
977679             BENTLEY               GT
755561                FORD               GT
1006408            MCLAREN               GT
891077                  MG               GT
1000009         ALFA ROMEO               H9
975705               HAVAL               H9
989763              HONGQI               H9
1007397            APRILIA  HARLEY DAVIDSON
799846                 BMW  HARLEY DAVIDSON
998300     HARLEY-DAVIDSON  HARLEY DAVIDSON
998857              SUZUKI  HARLEY DAVIDSON
1007576           DONGFENG             HERO
984438                HERO             HERO
571413               HONDA             HERO
934634             CHANGAN           HUNTER
984419                HERO           HUNTER
1008979                UAZ           HUNTER
793169                 BMW               IQ
949179            CADILLAC               IQ
614737             HYUNDAI               IQ
452700               LEXUS               IQ
951622                MINI               IQ
1009211              SCION               IQ
430                 TOYOTA               IQ
953747               GEELY               L6
1009379            LI AUTO               L6
960624             LINCOLN               L6
931260             RENAULT           LAGUNA
1008240            TRIUMPH           LAGUNA
1009154         VANDERHALL           LAGUNA
1009548              ACURA               LX
992885               CHERY               LX
993997               EXEED               LX
1003451              VESPA               LX
1006703             AEOLUS             MAGE
1007570           DONGFENG             MAGE
1009466         DONGFENG E             MAGE
1008074    DONGFENG-AEOLUS             MAGE
797986                 BMW      MOTOR CYCLE
1009427            GAS GAS      MOTOR CYCLE
612221               HONDA      MOTOR CYCLE
832620              SUZUKI      MOTOR CYCLE
748861           CHEVROLET        NINJA 300
1002064           KAWASAKI        NINJA 300
840205              SUZUKI        NINJA 300
806632                 GMC              NKR
961802               ISUZU              NKR
1008451                JMC              NKR
596637               HONDA             NONE
1009475      MERCEDES BENZ             NONE
892832                  MG             NONE
1003189             ABARTH          PARTNER
1006152      ASHOK LEYLAND          PARTNER
941457             PEUGEOT          PARTNER
246488              NISSAN             RICH
1009527          ZHENGZHOU             RICH
1005694                ZNA             RICH
933369             CHANGAN            ROCKY
970084            DAIHATSU            ROCKY
994470               EXEED            ROCKY
576133               HONDA            ROCKY
258937              NISSAN            ROCKY
1009479              ROCKY            ROCKY
1007377            APRILIA           RST200
972329               HONDA           RST200
1009403           SHARAMAX           RST200
1009181             CAN-AM            RYKER
1007690             CFMOTO            RYKER
1007438             DUCATI            RYKER
1009594              KAN M            RYKER
711386       MERCEDES BENZ                S
1009440               NETA                S
306274              NISSAN                S
936631             CHANGAN              S07
1004736             DEEPAL              S07
1004157            SOUEAST              S07
922421                AUDI               S5
502466               LEXUS               S5
1007205              SERES               S5
922367                AUDI               S7
1004042           FORTHING               S7
965331                 JAC               S7
1006679             AEOLUS            SHINE
1007581           DONGFENG            SHINE
1008052    DONGFENG-AEOLUS            SHINE
735467           CHEVROLET           SIERRA
803204                 GMC           SIERRA
118180              TOYOTA           SIERRA
772314                FORD          SIXTIES
1009094           VICTORIA          SIXTIES
990673             VICTORY          SIXTIES
1007414            APRILIA       SIXTIES 17
666359                 KIA       SIXTIES 17
1009568           VICTORIA       SIXTIES 17
1008754            VICTORY       SIXTIES 17
963448               BAJAJ      SIXTIES 175
502046               LEXUS      SIXTIES 175
1009124           VICTORIA      SIXTIES 175
990421             VICTORY      SIXTIES 175
796690                 BMW       SLING SHOT
971700               HONDA       SLING SHOT
265285              NISSAN       SLING SHOT
1003589            POLARIS       SLING SHOT
1009372             SCORPA       SLING SHOT
1008998                NaN       SLING SHOT
793788                 BMW           SLINGS
1009196          SLINGSHOT           SLINGS
1009415            VINFAST           SLINGS
1000682              BAJAJ        SLINGSHOT
910428                 BYD        SLINGSHOT
728055           CHEVROLET        SLINGSHOT
575108               HONDA        SLINGSHOT
625190             HYUNDAI        SLINGSHOT
1002056           KAWASAKI        SLINGSHOT
1003590            POLARIS        SLINGSHOT
1005912           POLESTAR        SLINGSHOT
999048              SUZUKI        SLINGSHOT
1007385            APRILIA           SPYDER
1009188             CAN-AM           SPYDER
1007697             CFMOTO           SPYDER
1005484            SHARMAX           SPYDER
963440               BAJAJ           SY150T
800198                 BMW           SY150T
1009474             SANIYA           SY150T
1004417              SANYA           SY150T
1009492             SANYOU           SY150T
53836               TOYOTA           SY150T
772104                FORD        TRAVELLER
856103              JETOUR        TRAVELLER
941631             PEUGEOT        TRAVELLER
998476     HARLEY-DAVIDSON           VENICE
998991              SUZUKI           VENICE
1009145         VANDERHALL           VENICE
1003507              VESPA           VENICE
789333                 BMW            VESPA
971867               HONDA            VESPA
1008881            PIAGGIO            VESPA
1009445          BLUE BIRD           VISION
278812              NISSAN           VISION
1009471             VANDER           VISION
990307             VICTORY           VISION
987054                BAIC              VXL
788575                 BMW              VXL
593552               HONDA              VXL
154521              TOYOTA              VXL
1003393              VESPA              VXL
990831             VICTORY              VXL
795431                 BMW          VXL 150
586616               HONDA          VXL 150
149833              TOYOTA          VXL 150
1003389              VESPA          VXL 150
1009001                NaN          VXL 150
998381     HARLEY-DAVIDSON                X
778264               TESLA                X
1002700              ZEEKR                X
986472                BAIC               X7
788277                 BMW               X7
916625               DODGE               X7
1005591              KAIYI               X7

In [271]:
bad_model_patterns = [
    r'^\d+$',            # 150, 300, 500
    r'^\d+\s*CC$',       # 150 CC
    r'^MODEL\s+\d+$',    # MODEL 2022
    r'^PICK',
    r'^SEDAN$',
    r'^HATCHBACK$',
    r'^BUS$',
    r'^TRUCK$',
]

In [272]:
# Find models appearing under 5+ makes

suspects = (
    df.groupby("model")["make"]
      .nunique()
      .reset_index(name="make_count")
      .query("make_count >= 5")
      .sort_values("make_count", ascending=False)
)

suspects

           model  make_count
96           150          10
4000   SLINGSHOT           9
397          500           7
2636          IQ           7
4182      SY150T           6
3654       ROCKY           6
237          300           6
4598         VXL           6
310          350           5
21            01           5
231            3           5
390            5           5
577          900           5
500            7           5
3997  SLING SHOT           5

In [273]:
suspects = [
    "150",
    "SLINGSHOT",
    "500",
    "IQ",
    "SY150T",
    "ROCKY",
    "300",
    "VXL",
    "350",
    "01",
    "3",
    "5",
    "900",
    "7",
    "SLING SHOT"
]

for m in suspects:
    print("\n" + "="*80)
    print(m)
    print(
        df_clean[df_clean["model"] == m]["make"]
        .value_counts()
    )

================================================================================
150
make
BAJAJ        32
VESPA        13
HONDA         2
SANYA         2
NISSAN        1
KIA           1
FORD          1
VOYAH         1
APRILIA       1
HART FORD     1
Name: count, dtype: int64

================================================================================
SLINGSHOT
make
POLARIS      105
HONDA          2
HYUNDAI        1
CHEVROLET      1
BYD            1
SUZUKI         1
BAJAJ          1
KAWASAKI       1
POLESTAR       1
Name: count, dtype: int64

================================================================================
500
make
FIAT             336
TANK             263
MERCEDES BENZ      6
GREAT WALL         4
FORD               1
SUZUKI             1
ROYAL ENFIELD      1
Name: count, dtype: int64

================================================================================
IQ
make
TOYOTA      76
SCION        3
LEXUS        1
HYUNDAI      1
BMW          1
CADILLAC     1
MINI         1
Name: count, dtype: int64

================================================================================
SY150T
make
SANYA     78
BAJAJ      2
TOYOTA     1
BMW        1
SANIYA     1
SANYOU     1
Name: count, dtype: int64

================================================================================
ROCKY
make
DAIHATSU    38
NISSAN       2
HONDA        1
CHANGAN      1
EXEED        1
ROCKY        1
Name: count, dtype: int64

================================================================================
300
make
TANK             197
HINO              96
CHRYSLER          47
MERCEDES BENZ     21
GREAT WALL         5
BENDA              1
Name: count, dtype: int64

================================================================================
VXL
make
VESPA      21
BMW         5
BAIC        2
TOYOTA      1
HONDA       1
VICTORY     1
Name: count, dtype: int64

================================================================================
350
make
MG               61
MERCEDES BENZ     4
LEXUS             1
FORD              1
ROYAL ENFIELD     1
Name: count, dtype: int64

================================================================================
01
make
ROX          1986
JIDU           15
LYNK & CO       3
GMC             2
JIYUE           1
Name: count, dtype: int64

================================================================================
3
make
MAZDA         2814
MG             180
POLESTAR         4
TESLA            2
GREAT WALL       1
Name: count, dtype: int64

================================================================================
5
make
MG           1097
SERES          17
MAZDA           2
RABDAN          2
LYNK & CO       1
Name: count, dtype: int64

================================================================================
900
make
LYNK & CO    42
TOYOTA        1
KAWASAKI      1
SAAB          1
LYKAN         1
Name: count, dtype: int64

================================================================================
7
make
MG          456
SERES         6
DONGFENG      4
GEELY         1
OMODA         1
Name: count, dtype: int64

================================================================================
SLING SHOT
make
POLARIS    27
NISSAN      2
BMW         1
HONDA       1
SCORPA      1
Name: count, dtype: int64

In [274]:
df_clean[df_clean["model"] == "VXL"][
    ["make","model","trim"]
].head(50)

            make model trim
154521    TOYOTA   VXL  NaN
593552     HONDA   VXL  NaN
788575       BMW   VXL  NaN
793811       BMW   VXL  NaN
795733       BMW   VXL  NaN
801173       BMW   VXL  NaN
801380       BMW   VXL  NaN
987054      BAIC   VXL  NaN
987213      BAIC   VXL  NaN
990831   VICTORY   VXL  NaN
1003393    VESPA   VXL  NaN
1003402    VESPA   VXL  NaN
1003442    VESPA   VXL  NaN
1003449    VESPA   VXL  NaN
1003465    VESPA   VXL  NaN
1008231    VESPA   VXL  NaN
1008234    VESPA   VXL  NaN
1008235    VESPA   VXL  NaN
1008239    VESPA   VXL  NaN
1008242    VESPA   VXL  NaN
1008246    VESPA   VXL  NaN
1008258    VESPA   VXL  NaN
1008262    VESPA   VXL  NaN
1008264    VESPA   VXL  NaN
1008270    VESPA   VXL  NaN
1008275    VESPA   VXL  NaN
1008280    VESPA   VXL  NaN
1008281    VESPA   VXL  NaN
1008285    VESPA   VXL  NaN
1009362    VESPA   VXL  NaN
1009457    VESPA   VXL  NaN

In [276]:
df_clean["vds"] = (
    df_clean["chassisNumber"]
    .astype(str)
    .str[3:8]
)

In [277]:
df_clean[df_clean["model"] == "VXL"][
    ["make", "year", "vds", "bodyType"]
].sort_values("make")

            make    year    vds    bodyType
987054      BAIC  2025.0  M8500  MOTORCYCLE
987213      BAIC  2025.0  M8500  MOTORCYCLE
788575       BMW  2025.0  M8500  MOTORCYCLE
793811       BMW  2025.0  M8500  MOTORCYCLE
795733       BMW  2025.0  M8500  MOTORCYCLE
801173       BMW  2025.0  M8500  MOTORCYCLE
801380       BMW  2025.0  M8500  MOTORCYCLE
593552     HONDA  2025.0  M8500  Motorcycle
154521    TOYOTA  2025.0  M8500  MOTORCYCLE
1003393    VESPA  2025.0  M8500  MOTORCYCLE
1003402    VESPA  2025.0  M8500  MOTORCYCLE
1003442    VESPA  2025.0  M8500  MOTORCYCLE
1003449    VESPA  2025.0  M8500  MOTORCYCLE
1003465    VESPA  2025.0  M8500  MOTORCYCLE
1008231    VESPA  2025.0  M8500  MOTORCYCLE
1008234    VESPA  2025.0  M8500  MOTORCYCLE
1008235    VESPA  2025.0  M8500  MOTORCYCLE
1008239    VESPA  2025.0  M8500  MOTORCYCLE
1008242    VESPA  2025.0  M8500  MOTORCYCLE
1008246    VESPA  2025.0  M8500  MOTORCYCLE
1008258    VESPA  2025.0  M8500  MOTORCYCLE
1008262    VESPA  2025.0  M8500  MOTORCYCLE
1008264    VESPA  2025.0  M8500  MOTORCYCLE
1008270    VESPA  2025.0  M8500  MOTORCYCLE
1008275    VESPA  2025.0  M8500  MOTORCYCLE
1008280    VESPA  2025.0  M8500  MOTORCYCLE
1008281    VESPA  2025.0  M8500  MOTORCYCLE
1008285    VESPA  2025.0  M8500  MOTORCYCLE
1009362    VESPA  2025.0  M8500  MOTORCYCLE
1009457    VESPA  2025.0  M8500  MOTORCYCLE
990831   VICTORY  2025.0  M8500  MOTORCYCLE

In [278]:
keep_vxl_makes = [
    "VESPA"
]

In [279]:
review_vxl_makes = [
    "TOYOTA",
    "BMW",
    "HONDA",
    "BAIC",
    "VICTORY"
]

In [280]:
(
    df_clean[df_clean["model"] == "VXL"]
    .groupby("make")
    .agg({
        "chassisNumber":"count",
        "bodyType":"nunique",
        "year":"nunique"
    })
)

         chassisNumber  bodyType  year
make
BAIC                 2         1     1
BMW                  5         1     1
HONDA                1         1     1
TOYOTA               1         1     1
VESPA               21         1     1
VICTORY              1         1     1

In [281]:
df_clean[df_clean["model"] == "VXL"][
    ["make","year","bodyType","chassisNumber"]
].sort_values("make")

            make    year    bodyType      chassisNumber
987054      BAIC  2025.0  MOTORCYCLE  METM85007S3003446
987213      BAIC  2025.0  MOTORCYCLE  METM85002S3003466
788575       BMW  2025.0  MOTORCYCLE  METM85000S3003630
793811       BMW  2025.0  MOTORCYCLE  METM8500253003435
795733       BMW  2025.0  MOTORCYCLE  METM85003S3003427
801173       BMW  2025.0  MOTORCYCLE  METM85002S3003676
801380       BMW  2025.0  MOTORCYCLE  METM85005S3003686
593552     HONDA  2025.0  Motorcycle  METM85007S3003110
154521    TOYOTA  2025.0  MOTORCYCLE  METM85007S3003432
1003393    VESPA  2025.0  MOTORCYCLE  METM85003S3003301
1003402    VESPA  2025.0  MOTORCYCLE  METM85001S3003653
1003442    VESPA  2025.0  MOTORCYCLE  METM85009S3003464
1003449    VESPA  2025.0  MOTORCYCLE  METM85000S3003403
1003465    VESPA  2025.0  MOTORCYCLE  METM8500XS3003375
1008231    VESPA  2025.0  MOTORCYCLE  METM85005S3003672
1008234    VESPA  2025.0  MOTORCYCLE  METM85002S3003628
1008235    VESPA  2025.0  MOTORCYCLE  METM85007S3003656
1008239    VESPA  2025.0  MOTORCYCLE  METM85004S3003629
1008242    VESPA  2025.0  MOTORCYCLE  METM85009S3003402
1008246    VESPA  2025.0  MOTORCYCLE  METM85000S3003434
1008258    VESPA  2025.0  MOTORCYCLE  METM85007S3003415
1008262    VESPA  2025.0  MOTORCYCLE  METM85004S3003632
1008264    VESPA  2025.0  MOTORCYCLE  METM85001S3003684
1008270    VESPA  2025.0  MOTORCYCLE  METM85006S3003650
1008275    VESPA  2025.0  MOTORCYCLE  METM85002S3003662
1008280    VESPA  2025.0  MOTORCYCLE  METM8500XS3003425
1008281    VESPA  2025.0  MOTORCYCLE  METM85008S3003374
1008285    VESPA  2025.0  MOTORCYCLE  METM85006S3003437
1009362    VESPA  2025.0  MOTORCYCLE  METM85006S3003390
1009457    VESPA  2025.0  MOTORCYCLE  METM85004S3003663
990831   VICTORY  2025.0  MOTORCYCLE  METM85000S3003692

In [ ]:
vxl_rows = df_clean[df_clean["model"] == "VXL"]

vxl_rows["make"].value_counts()

make
VESPA      21
BMW         5
BAIC        2
TOYOTA      1
HONDA       1
VICTORY     1
Name: count, dtype: int64

In [283]:
vxl_rows["wmi"] = vxl_rows["chassisNumber"].str[:3]

vxl_rows.groupby(["wmi","make"]).size()

wmi  make
MET  BAIC        2
     BMW         5
     HONDA       1
     TOYOTA      1
     VESPA      21
     VICTORY     1
dtype: int64

In [285]:
df_clean.loc[bad_vxl, "make"] = "VESPA"

In [284]:
bad_vxl = (
    (df_clean["model"] == "VXL") &
    (df_clean["make"] != "VESPA")
)

In [286]:
df_clean["wmi"] = df_clean["chassisNumber"].str[:3]

In [287]:
wmi_make = (
    df_clean.groupby("wmi")["make"]
    .nunique()
    .sort_values(ascending=False)
)

In [288]:
met = df_clean[df_clean["chassisNumber"].str[:3] == "MET"]

met["make"].value_counts()

make
VESPA      150
HONDA       39
TOYOTA      15
NISSAN      12
BAJAJ        8
APRILIA      5
BMW          4
PIAGGIO      4
HYUNDAI      1
KIA          1
AUDI         1
VICTORY      1
ABARTH       1
VOYAH        1
VINFAST      1
Name: count, dtype: int64

In [289]:
met["model"].value_counts().head(50)

model
VXL 150                 48
VXL                     31
PRIMAVERA 150           23
150                     17
SPRINT 150              17
ACCORD                  12
CAMRY                    8
ALTIMA                   7
CITY                     6
UNICORN                  5
SPA VXL 150              5
COROLLA                  3
PULSAR 125               3
LX150                    3
SXL 150                  3
COROLLA SEDAN            2
SUNNY                    2
CBR125R                  2
VESPA                    2
PULSAR 150               2
PLATINA 100              2
PIAGGIO                  2
GTS 300                  2
VXL150                   2
150 VXL                  2
LIBERTY 150              2
PATROL                   1
SENTRA                   1
UNICORN MOTORCYCLE       1
2027                     1
UNCORN                   1
UNIRON                   1
CB125F                   1
UNI CORN 160             1
UNICON                   1
UNICORN 160              1
AVANTE                   1
A3                       1
150 CC                   1
GOLD WING GL1800         1
CB1000R                  1
K1                       1
595                      1
LX                       1
0                        1
VESPAPK 50               1
VX                       1
VESPA/150/MOTORCYCLE     1
اس اكس ال 150            1
SR 150                   1
Name: count, dtype: int64

In [290]:
df_clean["wmi"] = df_clean["chassisNumber"].str[:3]

wmi_quality = (
    df_clean.groupby("wmi")["make"]
    .nunique()
    .sort_values(ascending=False)
)

wmi_quality.head(50)

wmi
LK1    17
57X    17
MET    15
ZAP    14
LRR    13
JYA    12
LJN    11
MB1    11
7KG    11
JHH    11
WWW    11
WDB    11
ZDM    10
MD6    10
JN1    10
L6T    10
LBB    10
VBK    10
JKA     9
SMT     9
LGW     9
JDA     9
LX6     9
SAL     9
LDP     9
2BX     9
5HD     9
YV2     9
WB1     9
LZB     9
1HD     9
LFZ     8
JTN     8
56K     8
KMH     8
JS1     8
LCE     8
HG6     8
HLX     8
HY2     8
WMA     8
JH2     8
000     8
LK6     7
LSJ     7
ZD4     7
ME3     7
JKB     7
HJ4     7
LA4     7
Name: make, dtype: int64

In [291]:
bad_wmis = wmi_quality[wmi_quality > 1]

bad_wmis

wmi
LK1    17
57X    17
MET    15
ZAP    14
LRR    13
JYA    12
LJN    11
MB1    11
7KG    11
JHH    11
WWW    11
WDB    11
ZDM    10
MD6    10
JN1    10
L6T    10
LBB    10
VBK    10
JKA     9
SMT     9
LGW     9
JDA     9
LX6     9
SAL     9
LDP     9
2BX     9
5HD     9
YV2     9
WB1     9
LZB     9
1HD     9
LFZ     8
JTN     8
56K     8
KMH     8
JS1     8
LCE     8
HG6     8
HLX     8
HY2     8
WMA     8
JH2     8
000     8
LK6     7
LSJ     7
ZD4     7
ME3     7
JKB     7
HJ4     7
LA4     7
LC0     7
MAT     7
MC2     7
MD2     7
LXY     7
111     6
ZFA     6
LS6     6
LNN     6
LTA     6
JAA     6
L7G     6
LA7     6
LEF     6
RKM     6
L3A     6
RFC     6
KNC     6
KMF     6
JTH     6
3JB     6
1G6     6
LFP     6
2C3     6
LET     6
WVW     6
ME4     6
1G1     6
LJ1     6
1GC     6
LVT     6
WMW     6
LMG     6
P01     5
GGG     5
JAM     5
1C6     5
9BS     5
JN6     5
WBA     5
1G4     5
KNA     5
VF7     5
LXG     5
2CN     5
MLH     5
ML5     5
LF3     5
LFV     5
JH4     5
JD4     5
WME     5
WDD     5
WP0     5
LXE     5
LKL     5
LVV     5
LSG     5
ZCF     5
ZFC     5
WV1     5
WDA     5
VF1     5
RP8     5
SCB     5
1G2     5
LGJ     5
LZW     5
LVU     4
3N1     4
1GT     4
LM8     4
WJM     4
JHD     4
LNB     4
1FT     4
ZGU     4
LSY     4
LSK     4
LSF     4
LRS     4
1GD     4
LVM     4
LWL     4
LZS     4
UAE     4
VF3     4
ME1     4
MBL     4
JNC     4
JN8     4
JTG     4
JTD     4
9KM     4
JT8     4
W09     4
VR3     4
KL3     4
KL4     4
1V2     4
KM4     4
MMM     4
LD3     4
MM7     4
KNM     4
LFC     4
LFB     4
KMT     4
MH3     4
RF5     4
RFB     4
L4H     4
2C4     4
HL4     4
5VP     4
L4U     4
ZA9     4
2GC     4
LA6     4
MZG     4
LVB     4
YBL     4
YS2     4
YSM     4
LVA     4
JD2     4
1C3     4
JCB     4
JAC     4
1C4     3
1C8     3
XLE     3
H84     3
HA9     3
HJN     3
HJR     3
137     3
ZAC     3
IGN     3
L5Y     3
5NT     3
5TD     3
NNN     3
L8Y     3
LAE     3
LB7     3
LC6     3
MHK     3
MPA     3
5N1     3
LCR     3
KNR     3
KPD     3
L1N     3
RA6     3
L3H     3
3C6     3
3GC     3
3GN     3
MEG     3
36N     3
5FP     3
KMJ     3
6T1     3
RX1     3
SKF     3
KN3     3
KN4     3
KND     3
KNF     3
KNH     3
JTJ     3
JTK     3
SQR     3
KL5     3
LGD     3
LGX     3
LHG     3
55S     3
MC1     3
VF6     3
VSS     3
W00     3
JT1     3
JT6     3
1GK     3
1N4     3
W0L     3
W1K     3
1GY     3
JMY     3
JN0     3
JNB     3
JNK     3
LZZ     3
MA1     3
MA3     3
LJ7     3
LJ8     3
JL5     3
JL6     3
JL7     3
JM1     3
JM3     3
JM7     3
1LN     3
1G8     3
1GJ     3
LLC     3
LLV     3
LVC     3
3VW     3
JHF     3
1GN     3
WD3     3
WD8     3
WDC     3
WF0     3
JHM     3
CAT     3
CPB     3
1D7     3
1FD     3
WV2     3
19U     3
JE4     3
LMX     3
LRW     3
LSC     3
LSV     3
LUR     3
ZCG     3
ZFF     3
ZFM     3
ZS1     3
0FM     2
0D8     2
ZAR     2
16Y     2
16N     2
16K     2
16C     2
HLH     2
HJA     2
FK1     2
FZJ     2
ZZE     2
ZSG     2
123     2
LV7     2
LV5     2
LUX     2
4JG     2
4F4     2
LS5     2
LS4     2
LPS     2
LNG     2
LNA     2
LMW     2
LM6     2
3N6     2
LW4     2
LVZ     2
LVS     2
454     2
3WV     2
4T3     2
LKI     2
LJU     2
LJD     2
5AL     2
MB8     2
MAJ     2
MAF     2
LZY     2
LY0     2
3N8     2
MDH     2
MBI     2
3MZ     2
3MY     2
3KP     2
3GY     2
3GT     2
LHP     2
LHA     2
LGV     2
LGT     2
LGF     2
5GT     2
5GA     2
LGA     2
3C4     2
36K     2
2T2     2
MH1     2
MF3     2
MEH     2
MEC     2
3GK     2
3D7     2
LCO     2
5NI     2
5N3     2
MZB     2
MV1     2
MP3     2
MNT     2
MMB     2
MLE     2
ML0     2
MK2     2
MHY     2
MHF     2
5J8     2
LBP     2
LBE     2
LB3     2
LAL     2
L6X     2
R3R     2
2GT     2
2GN     2
2GB     2
2G1     2
2FM     2
QJ1     2
PKA     2
2ME     2
2HN     2
2HG     2
NM0     2
L6W     2
5XX     2
5TF     2
5TE     2
5NP     2
5NM     2
5XY     2
L55     2
2D4     2
RKT     2
RGT     2
RFH     2
RFG     2
RA5     2
R6W     2
L2C     2
KPB     2
KPA     2
KMU     2
SNI     2
SN1     2
SJN     2
SJK     2
SC8     2
SBE     2
SAX     2
SAJ     2
SA9     2
2FA     2
6GI     2
KLT     2
KLI     2
KLA     2
8AW     2
KL7     2
UNI     2
U5Y     2
TMB     2
TMA     2
TGK     2
TG1     2
TFC     2
TC4     2
270     2
26C     2
SXA     2
SNT     2
KL1     2
KL0     2
JYM     2
JWT     2
JTS     2
JTM     2
JTF     2
JTE     2
JTB     2
AAA     2
JT5     2
JT4     2
JT3     2
JSA     2
JS2     2
AMD     2
JNT     2
JNS     2
JNR     2
1N1     2
1ME     2
W0D     2
VXE     2
VSE     2
VFT     2
VF9     2
203     2
JNL     2
JNI     2
JNE     2
JNA     2
JN3     2
JMT     2
ASG     2
AS3     2
WBW     2
WAW     2
WAU     2
W45     2
W1W     2
W1N     2
W11     2
W10     2
1N6     2
1GI     2
1GB     2
1G5     2
1HT     2
1HG     2
1HF     2
JMH     2
JMB     2
JJ7     2
JJ5     2
CA4     2
1CB     2
WIK     2
WFO     2
WDF     2
WD4     2
WD0     2
JHE     2
JF2     2
JF1     2
JE3     2
D12     2
D04     2
JDI     2
JD3     2
1BA     2
19X     2
WPO     2
1F6     2
1D4     2
1CK     2
YV3     2
YV1     2
WWG     2
WVG     2
1CA     2
JAL     2
JA3     2
INB     2
IGK     2
IGI     2
IGC     2
ET1     2
IG1     2
IC6     2
ZRE     2
015     2
010     2
ZJT     2
 JT     2
Name: make, dtype: int64

In [292]:
wmi_make_breakdown = (
    df_clean.groupby(["wmi","make"])
    .size()
    .reset_index(name="count")
    .sort_values(["wmi","count"], ascending=[True,False])
)

In [293]:
df_clean["wmi"] = df_clean["chassisNumber"].str[:3]

(
    df_clean.groupby("wmi")["make"]
    .nunique()
    .sort_values(ascending=False)
    .head(100)
)

wmi
LK1    17
57X    17
MET    15
ZAP    14
LRR    13
JYA    12
LJN    11
MB1    11
7KG    11
JHH    11
WWW    11
WDB    11
ZDM    10
MD6    10
JN1    10
L6T    10
LBB    10
VBK    10
JKA     9
SMT     9
LGW     9
JDA     9
LX6     9
SAL     9
LDP     9
2BX     9
5HD     9
YV2     9
WB1     9
LZB     9
1HD     9
LFZ     8
JTN     8
56K     8
KMH     8
JS1     8
LCE     8
HG6     8
HLX     8
HY2     8
WMA     8
JH2     8
000     8
LK6     7
LSJ     7
ZD4     7
ME3     7
JKB     7
HJ4     7
LA4     7
LC0     7
MAT     7
MC2     7
MD2     7
LXY     7
111     6
ZFA     6
LS6     6
LNN     6
LTA     6
JAA     6
L7G     6
LA7     6
LEF     6
RKM     6
L3A     6
RFC     6
KNC     6
KMF     6
JTH     6
3JB     6
1G6     6
LFP     6
2C3     6
LET     6
WVW     6
ME4     6
1G1     6
LJ1     6
1GC     6
LVT     6
WMW     6
LMG     6
P01     5
GGG     5
JAM     5
1C6     5
9BS     5
JN6     5
WBA     5
1G4     5
KNA     5
VF7     5
LXG     5
2CN     5
MLH     5
ML5     5
LF3     5
LFV     5
JH4     5
Name: make, dtype: int64

In [202]:
list(df['model'].unique())

['COROLLA',
 'HIACE',
 'HILUX',
 'CAMRY',
 'LAND CRUISER',
 'YARIS',
 'FJ CRUISER',
 'RAV4',
 'TUNDRA',
 'AVALON',
 'FORTUNER',
 'COASTER',
 'INNOVA',
 'SIENNA',
 'TACOMA',
 'PRADO',
 'LAND CRUISER PICK UP',
 'RUSH',
 'PRIUS',
 'AVANZA',
 'SEQUOIA',
 'SUPRA',
 'AURION',
 'ECHO',
 'PREVIA',
 'BZ4X',
 'LITE ACE',
 'COROLLA CROSS',
 'C-HR',
 'XA',
 'GRANVIA',
 'VELOZ',
 'RAIZE',
 'IQ',
 'LAND CRUISER PICKUP 70',
 'FJ',
 'CROWN',
 '86',
 '4RUNNER',
 'COROLLA 1.6',
 'URBAN CRUISER',
 'SOLARA',
 'HIGHLANDER',
 'DYNA',
 'LAND CRUISE',
 'LAND CRUISER 70',
 'TERCEL',
 'LITEACE',
 'MATRIX',
 'RAV 4',
 'GR86',
 'LEVIN',
 'ZELAS',
 'T 300',
 '4 RUNNER',
 'COROLLA 1.3',
 'LAND CRUISER PRADO',
 'CRESSIDA',
 'LAND CRUISER VXR',
 'CROWN KLUGER',
 'TAKOMA',
 'ALTIS',
 'COROLLA 1.8',
 'HAIULUX',
 'BZ3X',
 'COROLLA SEDAN',
 'COROLLA 1.5',
 'LAND CRUISER PICK UP CARGO',
 'RUMION',
 'MR2',
 'TOYOTA',
 'WISH',
 'FLTRXS',
 'DAINA',
 'TANDRA',
 'LAND CRUISER / STATION',
 'BZ 4',
 'LAND CRUISER SINGLE-CABIN PICK',
 'SY150T',
 'HAI LUX',
 nan,
 'HILUX RE',
 'KS01',
 'VENZA',
 'MR 2',
 'SICION',
 'MT 03',
 'TOKOMA',
 'CELICA',
 'T 100',
 'ALFARD',
 'PRADO GX',
 'RUNNER',
 'GRAND DELUX',
 'ALLION',
 'VIOS',
 'SIENNA VAN',
 'SENA',
 'SIERRA',
 'SELICA',
 'SENA VAN PASSENGER',
 'COROLLA 1.6/SEDAN',
 'MODEL 2022',
 'LAND CRUISER GX',
 'PICK UP CABIN',
 'SUPRA COUPE',
 'TACOMA (PICK UP)',
 'HI S COACH',
 'LAND CRUISER/PICK UP CARGO',
 'FRONTLANDER',
 'COROLLA SEDAN / HATCH',
 '25 CA SON P 2.5L AT',
 'STREET TRIPLE',
 'AQUA',
 'VXL 150',
 'GS 300',
 'COROLLA LI',
 'VXL',
 'CORONA',
 'FLHTK',
 '26 YA HB P 1.6L AT TURBO GR RA(CAR)',
 'RAV4 LE CAR',
 'SQUIN',
 'SIENA',
 'COROLLA 2.0',
 'STANZA',
 'CHR',
 'TUNDRA (PICK UP)',
 'GXL RA (STATION WAGON)',
 '25PR 5 DR P 2.4L AT',
 'SPINA',
 'YARIS HATCHBACK',
 'DLX FA (PICK UP)',
 'PASSENGER',
 'WIGO',
 'R1',
 'SIENNA(VAN)',
 'U7',
 'T100',
 'HILUX ADVENTURE',
 'TAKOMA PICK UP CARGO',
 'GL770ULTRA',
 'ORION',
 'PARISIENNE BROUGHAM',
 'COROLLA 1.5L/HATCHBACK',
 'TANDRA PICK UP DOUBLE CABIN',
 'H 530',
 'CENTURY',
 'CROWN V',
 'ES8',
 'RAFF 4',
 '900',
 'DYNA VAN CARGO',
 'H3',
 'LAND CRUISER/STD EX PICKUP',
 'LAND CRUISER PICKUP',
 'FORERUNNER',
 'CAMRY HYBRID',
 'MIRAI',
 '1.8 XS',
 'HI ACE',
 'LAND CRUISER - PICK UP CARGO',
 'BZ46',
 'EQ',
 'CAMRY SOLARA',
 'LAND CRUISER SINGLE-CABIN PICK UP',
 'TIIDA',
 'ARMADA',
 'PATROL',
 'URVAN',
 'ALTIMA',
 'X TRAIL',
 'SUNNY',
 'KICKS',
 'SENTRA',
 'QUEST',
 'JUKE',
 'PATHFINDER',
 'MICRA',
 'X TERRA',
 'NAVARA',
 'QASHQAI',
 'MAXIMA',
 'PATROL PICK UP',
 'ROGUE',
 'VERSA',
 'NISSAN',
 'GT-R',
 'MURANO',
 '300ZX',
 'ROUGE',
 'FRONTIER',
 '370Z',
 'ROGUE SPORT',
 'TITAN',
 'PATROL GLV',
 'PRIMERA',
 'PATROL SUPER SAFARI',
 'PICK UP CARGO',
 'MAGNITE',
 'RICH',
 'NP300',
 'Z',
 'CIVILIAN',
 'TEANA',
 'SUNNY 1.5',
 'ZX 300',
 'X-TRAIL',
 'SUNNY 1.3',
 '350Z',
 'PATROL GL V',
 'CUBE',
 'ZX 280',
 '2400',
 'KI',
 'ROGUE (4WD)',
 'UD',
 'ROCKY',
 '280 ZX',
 'URVAN/VAN',
 'SUNNY 1.6',
 'NISSEN DIESEL NU 41',
 'PICK UP',
 'MORANOA',
 'PICKUP CARGO',
 'SLING SHOT',
 'NP 300',
 '150',
 'PATROL/STATION',
 'PK',
 'D 2500',
 'CEDRICK',
 'NV',
 'URVAN/COACH',
 'FRONTIER/PICK UP DOUBLE CABIN',
 'VISION',
 'ZHENGZHOU',
 'KICKS 20SVUPPER',
 'ENCLAVE',
 'DISEL',
 '2400 PICK UP CARGO',
 'ZX 300/COUPE',
 'LEAF',
 'NV3500',
 'PATROLYYYY',
 '280ZX',
 'XTERRA',
 'CABSTAR',
 '1200GX',
 'DIESEL',
 '240',
 'ARIYA',
 'TC',
 'ZX 300 COUPE',
 'TIDA',
 'QUEST (VAN)',
 'SUNNY 1.4',
 'QX 56',
 'URBAN VAN',
 'TERRANO',
 'ZD 300',
 'DIESEL UD',
 'BLUEBIRD',
 'MAXIMA G 30',
 'NX 350 H',
 'X-TERRA',
 'SKYLINE',
 'S',
 'PK 210',
 'SAXUS',
 'ROSA',
 'VOGUE',
 'Z COUPE',
 'SILVIA S15',
 'ALTIMA SE',
 'DIESEL NU 41 H5',
 'PATHFINDER AWD',
 'V7 SPECIAL SILVER',
 'PATROL GL',
 'G70',
 'TIDAS',
 'TIDA SE',
 'SUNNY 1.8',
 'TIIDA HATCHBACK',
 'PATROL SE',
 'N6',
 'INFINITE',
 'XL 883 N',
 'MAX 180',
 'CENTRA',
 'CEDREC',
 'GLORIA',
 'LKE 210',
 'DIESEL NU 41 H 5',
 'MAXSMA',
 'GL - E',
 'SX 240 COUPE',
 '240SX',
 'CARM',
 '225',
 '0.60 G',
 'TITAN PICK UP DOUBLE CABIN',
 'VAN 3S4DRSRMT U11A(VAN)',
 'E25',
 '200',
 'MT',
 'ROGIE',
 '370Z COUPE',
 'PICKUP SINGLE CABIN',
 'N7',
 'ALTIAMA',
 'ZNA',
 'TRUCK',
 'SX 240',
 'PATROL SUPER SA',
 'PATROL GLV/STATION',
 'DATSUN',
 'MUNARO',
 'JUKE STATION',
 'XTRAIL',
 'ROGUE - 2019',
 'DIESEL TFA',
 'DIESEL PK21',
 'SUNNY/SEDAN',
 '695',
 'ALTIMA SV',
 'NISSEN DIESEL UD',
 'NU 41 H 5',
 'KICKS S',
 'PATROL XE',
 '/ PATROL / STATION',
 'CANTER',
 'GEN',
 'VICTORY',
 'NX',
 'NVARA / PICK UP DOUBLE C',
 'NVARA PICK UP DOUBLE C',
 'ALTIMA 2.5',
 'LX570',
 'ES350',
 'LS460',
 'LS430',
 'IS250',
 'IS200T',
 'LX470',
 'NX350',
 'RX450',
 'NX200T',
 'RX350',
 'IS350',
 'IS300',
 'ES300 H',
 'CT200H',
 'GS350',
 'LS400',
 'ES300',
 'RX330',
 'LX600',
 'GX460',
 'LS 460',
 'UX300H',
 'UX200',
 'LS500',
 'LS 430',
 'GS430',
 'GS300',
 'IS 350',
 'RC350',
 'RX450H',
 'GS400',
 'GS450H',
 'NX300',
 'LS 600 HL',
 'RX350 L',
 'GS460',
 'GS200T',
 'LS600H',
 'LS350',
 'RX 450 H',
 'ES250',
 'RX 400H',
 'LS 400',
 'LX700H',
 'IS 300',
 'RC300',
 'LC500',
 'GS250',
 'IS F',
 'RX300',
 'NX 350H',
 'RX400H',
 'NX 450H',
 'RC F',
 'LX 570',
 '',
 'ES 350',
 '460 LS',
 'NX 300',
 'GX470',
 'ML350',
 'IS 500',
 'NX 200T',
 'IS 250',
 'HS 250H',
 'GS 430',
 'NX250',
 'ES 300H',
 'RX 350',
 'RX350H',
 'IS300C',
 'NX 300H',
 'LS500H',
 'GS 350',
 'IS250C',
 'LC 500',
 'LS 460 L',
 'UX 250H',
 'LX 450',
 'RX500H',
 'UX250H',
 'GS F',
 'NX 350 H STATION',
 'ES200',
 'GS 400',
 'G450',
 'LS600H L',
 'RC 300',
 'ES330',
 'RC200T',
 'LX 600',
 '350',
 'IS 200T',
 'RX 300',
 'GX 470',
 'ES 300',
 'LM 350H',
 'GS 450 H',
 'RX 450H',
 'IS 200',
 'NX 200 T',
 'RX450H L',
 'IS200',
 'LM 300H',
 'GX550',
 'LS 460 L/SEDAN',
 'GS 200 T',
 'LM350H',
 'HE IS 330',
 'CH150T-34',
 'NX300H',
 '460',
 '200T',
 '150 CC',
 'LC500H',
 'LX 700 H',
 'GS 450H',
 'IS 300H',
 'GS 460',
 'NX200',
 'LS 600H L',
 'CT 200H',
 'LS300',
 'TX350',
 'RX350L',
 'RX 400 H',
 'NSX',
 'NX 350',
 'HS250H',
 'ES300H',
 'IS500',
 'NX 450 H',
 'LX 470',
 'RX400',
 'RC 200T',
 'MODEL 2009',
 'ES 400',
 'ES 250',
 'LX 350',
 'LEXUS',
 'UX 300 H',
 'RX270',
 'LFA',
 'LS 600 H',
 'LS460L',
 'E 350',
 'AS 300',
 'UX 200',
 'NIAS 350',
 'GX 460',
 '200ZX (CAR)',
 'SIXTIES 175',
 'S5',
 'HARLEY DAVIDSON FAT',
 'RX 2.0',
 '15 250',
 'ES',
 'LS EP',
 'RX 200T',
 'LANCER EX',
 'ATTRAGE',
 'L200',
 'GALANT',
 'OUTLANDER',
 'PAJERO',
 'LANCER',
 'L300',
 'MIRAGE',
 'XPANDER',
 'ASX',
 'MONTERO SPORT',
 'GRANDIS',
 'LANCER FORTIS',
 'ECLIPSE',
 'FUSO ROSA',
 'XPANDER CROSS',
 'PAJERO SPORT',
 'FUSO CANTER',
 'FUSO',
 'ECLIPSE CROSS',
 'NATIVA',
 'SPACE WAGON',
 'DESTINATOR',
 'ROZA/COACH',
 'FUSO BA',
 'FH',
 'PAJERO IO',
 'L 300 VAN CARGO',
 'OUTLANDER SPORT',
 'L 200',
 'MITSUBISHI',
 'KAB 3',
 'FOZO',
 'ROSA W',
 'ROZA',
 'BA',
 'ROZA SW',
 'FUZO',
 'CANTER PICKUP',
 'L200 PICK UP',
 'L 300',
 'MAGNA',
 'L 200 SINGLE CABIN PICKUP',
 'FORTIS',
 'MONTERO',
 'PICK UP SINGLE CABIN',
 'PICK UP DOUBLE CABIN',
 'OUTLANDER PHEV',
 'CANTER/BICK UP FRZ',
 'CANTER PICK UP CARGO',
 'CANT',
 '3000GT',
 'ROSA LW',
 'SINGLE CABIN',
 'RVR',
 'CRAVAN MISTUBISHI',
 'FUSO FK260',
 'GT 3000',
 'PAJERO STATION',
 'CANTER PICKUP CRANE',
 'ASTRI 200',
 'LANCER EVOLUTION',
 'MONTE',
 'CANTER PICK UP CAR',
 'EVOLUTION',
 '3000 GT',
 'CIVIC',
 'ACCORD',
 'UNICORN 160',
 'CITY',
 'CR-V',
 'UNICORN',
 'RIDGELINE',
 'CBR650',
 'GOLDWING',
 'GL1800',
 'CBF 160',
 'CBR600RR6',
 'E-NS1',
 '1800 GL',
 'UNCORN',
 'JAZZ',
 'UNICORN 16',
 '650',
 'HRV',
 'PILOT',
 'ODYSSEY',
 'ACCORD COUPE',
 'STATELINE',
 'INSIGHT',
 'CBF 150',
 'CBF160',
 'ZR-V',
 'CBF',
 'AFRICATWIN',
 'UNIKORN',
 'FIT',
 'GL 1800',
 'ODYSSEY J',
 'VALKYRE',
 'UNICORN 166',
 '600 CBR',
 'CMX1100',
 'HONDA',
 'TRANSIT',
 'X ADV 750',
 'S7(2WD)',
 'GOLD WING',
 'CBF 150 MA',
 'CBF160 UNICORN',
 'MRV',
 'CBR125R',
 'UNICORN MOTORCYCLE',
 'UNICON',
 'CRV',
 '150 CB',
 'YUNICORN',
 'CBF16026MY',
 'UNICORN 180',
 'CBF 150M',
 'CBX250 TWISTER',
 'SHADOW',
 'CBF 16025Y',
 'CBF160F',
 'C BR 500',
 'ADV 150',
 'REBEL',
 'CBF 16026MY',
 'UNICCRN',
 '125CC',
 '2027',
 'LEGEND',
 'CBF150S',
 'FLHCS',
 'AFRICA TWIN',
 'GOLDWING TOUR AUTO',
 'CBF150',
 'ACCORD CROSSTOUR',
 'FD 25 NT',
 'SILVERWING',
 'ST 1300',
 'CBF150MA',
 'MONKEY Z 125 M',
 '125 CC',
 'CBR 1000RRB',
 'YUNICORN 160',
 'CBR 300R',
 'CMX 500',
 'MA150 CB',
 'RH1250S',
 '600',
 '160 HONDA UNICORN',
 'YULIKORN',
 'SHADOW VT750C',
 'ENS USTATION',
 'CR-X',
 'NC700X',
 'CYCLE',
 'JNICORN 160',
 'UNICORN 100',
 'UNIKORN 160',
 'CBR',
 'CBR 1100',
 '750',
 'CBR 600',
 'PCX 150',
 'CBR 1000 RA',
 'ACURA',
 'UNICORN - 160',
 'CBR250R',
 'CB160',
 'THONDA',
 'UNICORN MOTORCYCLE DELIVERY',
 'UNICORN CBF',
 'CBX750P2H',
 'YULIKORN 160',
 'E-NP1',
 'CB 1000',
 '160',
 'CBF 150MA',
 'INTEGRA',
 'GOLD WING GL1800',
 'CR-Z',
 'CBR 250',
 'CB125F',
 'MONKEY Z1',
 'DELIVERY MOTORCYCLE',
 'CRF1100CC',
 'GROM125',
 'HRV AWD LX',
 'NC750XAFGS46',
 'UNICORNP160',
 'CB500',
 'CBX250W',
 'CB1000',
 'CBF 16025MY',
 'CBF 160 UNICORN',
 'NC750XAS',
 '160 UNICORN',
 'HONDA-250',
 'BF 150',
 'PASSPORT',
 'XADV',
 'MONKEY',
 'CBR1000',
 'UNIQUE 160',
 'CBF 125M',
 'CBF 125 M',
 'MONKEY Z125M',
 '1300CC',
 'CITI',
 'VTR',
 'UNICORN 10',
 'MONKEY Z125',
 'NINED POE',
 'AF 160 CB',
 'CBR 1000RA',
 'AF 160',
 'CBF 150 M',
 'MONKEY Z125 M',
 'HERO',
 'CBF125',
 'PRELUDE',
 'VT750',
 'CARROT ABYEI',
 '1100',
 'GL 1806/MOTORCYCLE',
 'GROM',
 '250',
 'UNICORN T',
 'HR (4WD)',
 'CMX500AS',
 'HONOR X9C',
 'CB300R',
 'CRF',
 '1000',
 'ADV750T GS',
 'CBF16026Y',
 'YZF R7',
 'GL1500',
 'TRID',
 'CBF-160',
 'CPF',
 'CBF 125',
 'CBX250',
 'CBR 300',
 'AF 150',
 'ELEMENT',
 'CMX500A',
 'SLINGSHOT',
 'C B R 500',
 'TV1300',
 'MUNICORN 160',
 'S2000',
 'NC 700XM',
 'CBF 160F',
 'CB 650CC',
 'VFR 800',
 'YZF R3',
 'CBR 900',
 'MAD',
 '2150',
 'GOLDEN 1',
 'CRF 1100DL4T GS',
 'NC750 INTEGRA',
 'CB500F',
 'CBR600RR',
 'UNICORN 150',
 'UNICORN -160',
 'UNICORNS!',
 'UNICRN',
 'CG125',
 'MODEL 2020',
 'CBF16026',
 'UNICRON',
 'CIVIC/COUPE',
 'CMX500S',
 'CG 125',
 'VULCAN',
 'GOLDWING TOUR',
 '750 CC',
 'GL1800A',
 'C160M',
 'UNICO',
 '1000CC',
 'NC750XAT',
 'UNIRON',
 'CB190X',
 'C1600',
 'CBR1000RA',
 'PB 250',
 '100 HONDA',
 'MSX 125 E',
 'CBR1000RR8',
 'X ADV',
 'HR-V',
 'UNICORN 160 CBF',
 'CBR500R',
 '1600',
 'CF 1600',
 '390',
 'ST 1100',
 'UNICCRN 160',
 'GL',
 'NC750XF',
 'CRF1100 A3T GS',
 'CBF150MA UNICORN (MOTORCYCLE)',
 'C200',
 'UNICON 160',
 'UNI160BSVI',
 'CB 160',
 'NC750XAFGS36',
 'CMX500AT (MOTORCYCLE)',
 'TRIGGER',
 'C160MY',
 'GL1800XS 2GS',
 'CBF 180',
 'CRF1100DL4T',
 'VF',
 'CB SHINE',
 'PHONDA',
 'XAF 750 NC',
 'TAIGER',
 'CB1100 RS',
 'CBR 1000',
 'NC750XAT 2GS',
 'CIVIC 150',
 'CB500X',
 'NC750XAT GS',
 'UN.CORN',
 'FORZA 300',
 'ACTIVIA',
 'CRF 450X',
 'ENS1',
 'UNI CORN 160',
 'يونيكورن 180',
 'VT',
 'FJS400D',
 'UNICORN 167',
 'VFR',
 'CBR 1000RR',
 'CBF 150S',
 'YZFR7',
 'CINGIN',
 'B F 125',
 'SUPER CUB',
 'CB',
 '700',
 'MSX125',
 'KC20',
 'VENICE/MOTORCYCLE',
 'STAR HLX',
 'PRIPY',
 'CBR650RACT(MOTORCYCLE)',
 'FLTRXSE',
 'UNICORN PISO',
 'PCX150',
 'GVX 20',
 'CT125',
 'VTX1300',
 'CB 1300',
 'SEDAN',
 'CB 300 R',
 'CB UNICORN 160',
 'CBR1000RR',
 'CB 1000R',
 'YULICORN',
 'Z125 MA',
 'CB1000R',
 'CMX',
 'CF 1000',
 'GL1800 (MOTORCYCLE)',
 'RTR 149',
 'MX500',
 'HIM',
 'ARF 50',
 'TIGGER',
 'CBF160 26MY',
 '125MS',
 'NC 750 SD',
 'UNICORN QVN 1250',
 'CROSSTOUR',
 'CBR 500',
 'CMX500',
 'CB1300',
 'BUNICORN',
 '1000 MOTORCYCLE',
 'ADV750T',
 'NONE',
 'AF 150 CB',
 'GL 1500',
 'X ADV 25MY',
 'ENP2',
 'GTS 300',
 'GL1800 D',
 'JNICORN',
 'DELIVERY BIKE',
 'CBX 250',
 'پولیگورن',
 'VTX',
 'ORN 160',
 'CRF300RALLY',
 'HONDA/250/MOTORCYCLE',
 'MONDA UNICORN',
 'CBX250 TW',
 'CB250',
 'CBR 1000 R 7',
 '1800CC',
 'MODEL 2019',
 'CB200X',
 'UNIC ORN 160',
 'VALKRIE',
 'COLD WING',
 'AF 160 UNICORN PC',
 'CABALLERO RALLY',
 'PUNICORN',
 'MODEL 2013',
 '400',
 'CEF150',
 'CSX',
 'CB 750',
 'BOMBKORN 160',
 'CRX',
 'CB1100',
 '1800',
 'UNICORN P160',
 'CBF1606MY',
 'CB300F',
 'B1025',
 'CBF1505',
 'ADV 160',
 'BF 150 M',
 'PB 150',
 'UNICORN 160HCDA',
 'YUNICORN 180',
 'CBR1000RR7',
 'تي ان تي 150',
 'G. V. W.',
 'DT175',
 'CIVIC COUPE',
 'ADV350(MOTORCYCLE)',
 'ADV 350',
 'MONKY',
 '250 CC',
 'UNICORK 160',
 'PONDA ACTIVA 125 21D',
 'CB UNICORN',
 'X-ADV 25MY',
 'CRZ',
 'C 1025MY',
 'B105',
 'GPX DEMON150GR F1',
 'MOTOR CYCLE',
 'مولدا',
 'CB160R',
 'SANTA CRUZ',
 'ACCENT',
 'SONATA',
 'TUCSON',
 'ELANTRA',
 'SANTA FE',
 'CRETA',
 'GENESIS',
 'VELOSTER',
 'H1',
 'KONA',
 'PALISADE',
 'AVANTE',
 'STARIA',
 'AZERA',
 'IONIQ 5',
 'GRAND STAREX',
 'VERACRUZ',
 'I10',
 'GRAND I10',
 'GETZ',
 'GRANDEUR',
 'I30',
 '30DF7',
 'VENUE',
 'GALLOPER',
 'PORTER',
 'TRAJET',
 'ايفنت',
 'HD65',
 'GV70',
 'I20',
 'H-65D',
 'GRAND SANTA FE',
 'HD 46',
 'HD 65',
 'CASPER',
 'GRANDEUR SEDAN',
 'STAREX',
 'SANTEVY',
 'I40',
 'GRAND CRETA',
 'COUNTY',
 'ATOS',
 'IONIQ',
 'HD 46 PICK UP CARGO',
 ...]