In [3]:
import pandas as pd

df = pd.read_csv("vehicles_cleaned.csv")

In [4]:
df

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
0,RKLBB9HE7F5115863,2015.0,TOYOTA,COROLLA,SE,SEDAN,GCC,4.0,silver,Taiwan,1000.0,5.0
1,JTFHX02POF0099797,2015.0,TOYOTA,HIACE,GLX,Mini Bus High Roof,GCC,4.0,white,Japan,2000.0,2.0
2,JTFHX02P7F0094323,2015.0,TOYOTA,HIACE,DX,Mini Bus High Roof,GCC,4.0,white,Japan,1837.0,15.0
3,JTFHXDGP7F0094373,2015.0,TOYOTA,HILUX,DL,Pick Up Double Cab,GCC,4.0,white,Japan,1837.0,5.0
4,4T1BG22K01U789089,2001.0,TOYOTA,CAMRY,XLI,SEDAN,Non-GCC,4.0,brown and beige,Japan,1481.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995045,HY2PEAND0PB000238,2023.0,BIMOTA,AYED250N 3,NaN,Motorcycle,GCC,NaN,green and black,China,250.0,2.0
995046,LNGPCMXJ9PL305272,2023.0,APULUO,APULUO AP200 4H,NaN,Motorcycle,GCC,NaN,black,China,150.0,2.0
995047,LURJAVBM8PA024843,2023.0,AIQAR,EQ 1,STD,COUPE,GCC,4.0,blue,CHINA,NaN,2.0
995048,7KGTC2C48NR003646,2022.0,ELECTRIC MOTION,ePure,NaN,Motorcycle,GCC,NaN,gray and black,AMERICA,450.0,2.0
995049,LX6TK334XS2510023,2025.0,CHANGHUA,CH150T-34,NaN,Motorcycle,GCC,NaN,gray and black,China,150.0,2.0

In [5]:
short_chassis_df = df[df['chassisNumber'].astype(str).str.replace(r'\s+', '', regex=True).str.len() < 17]

In [6]:
short_chassis_df

Empty DataFrame
Columns: [chassisNumber, year, make, model, trim, bodyType, regionalSpec, cylinders, color, origin, weightInKg, noOfPassengers]
Index: []

In [7]:
df['year'].unique()

array([2015., 2001., 2010., 2011., 2008., 2006., 2014., 2005., 2026.,
       2012., 2017., 2022., 2016., 2013., 2009., 2007., 2020., 2024.,
       2023., 1999., 2019., 2004., 2018., 2021., 1998., 2002., 2000.,
       2003., 2025., 1997., 1993., 1991., 1987., 1994., 1996., 1992.,
       1990., 1995., 1962., 1979.,   nan, 1989., 2027., 1986., 1988.,
       1984., 1983., 1985., 1981., 1980., 1982., 1978., 1977., 1971.,
       1965., 1975., 1972., 1974., 2028., 1966.])

In [8]:
df["make"].value_counts().loc[
    ["AYED",
"AYED AYED",
"AYED BIKE",
"BIUE BAIRD",
"DEXER",
"EMPALA",
"ESCHER",
"FLONY",
"FOLONY",
"GUNAU",
"HIG",
"KAN M",
"KAOE K",
"KOASKO",
"PADAR",
"POWEREAGLE",
"PUYUAN",
"SAIMO",
"SANIYA",
"SANYA",
"SANYOU",
"SHANG JAN",
"TYANMA",
"VANDER",
"VOLG",
"ZENIN"]
]

make
AYED            9
AYED AYED       1
AYED BIKE       1
BIUE BAIRD      1
DEXER           1
EMPALA          3
ESCHER          2
FLONY           1
FOLONY          6
GUNAU           2
HIG             1
KAN M           1
KAOE K          1
KOASKO          2
PADAR           1
POWEREAGLE     14
PUYUAN          1
SAIMO           1
SANIYA          1
SANYA         175
SANYOU          1
SHANG JAN       1
TYANMA          1
VANDER          1
VOLG            1
ZENIN           1
Name: count, dtype: int64

In [9]:
df[df["make"].isin(["SWIFT"])]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
994965,L7GPCLLY5S1227807,2025.0,SWIFT,175 SHARMAX - STREET BIKE,NaN,Motorcycle,GCC,NaN,gray and black,China,20.0,2.0

In [11]:
df_clean = df.copy()

In [12]:
suspects = [
    "HIG",
    "VOLG",
    "VANDER",
    "TYANMA",
    "KAN M",
    "KAOE K",
    "SHANG JAN",
    "SANIYA",
    "SANYA"
]

df_clean[
    df_clean["make"].isin(suspects)
][[
    "make",
    "model",
    "bodyType",
    "year",
    "chassisNumber"
]]

             make    model    bodyType    year      chassisNumber
989972      SANYA   SY150T  Motorcycle  2023.0  LK1PCKL91P1000023
989973      SANYA   SY150T  Motorcycle  2024.0  LK1PCKL97R1000689
989974      SANYA   SY150T  Motorcycle  2023.0  LK1PCKL97P1001015
989975      SANYA  SY1509F  Motorcycle  2026.0  LK1PCKL94T1002097
989976      SANYA     150T  Motorcycle  2023.0  LK1PCKL9XP1000053
...           ...      ...         ...     ...                ...
994950        HIG  KLQ6600         Van  2025.0  LKL1AAA64SA811720
994962     KAOE K     2015      Pickup  2015.0  LLTAN12FXFM030078
994983  SHANG JAN       35     Station  2016.0  L55A3ADE56A000066
995034      SANYA   SY150T  Motorcycle  2023.0  LK1PCKL93N1000103
995042      KAN M    RYKER  Motorcycle  2019.0  3JB2FEG10KJ002208

[183 rows x 5 columns]

In [17]:
print(
    df_clean[
        df_clean["make"].isin(suspects)
    ][[
        "make",
        "model",
        "bodyType",
        "year",
        "chassisNumber"
    ]].to_string()
)

             make                model    bodyType    year      chassisNumber
989972      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL91P1000023
989973      SANYA               SY150T  Motorcycle  2024.0  LK1PCKL97R1000689
989974      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL97P1001015
989975      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL94T1002097
989976      SANYA                 150T  Motorcycle  2023.0  LK1PCKL9XP1000053
989977      SANYA               OTHERS  Motorcycle  2022.0  LK1PCKL91M1001460
989978      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL94T1001578
989979      SANYA               SY150T  Motorcycle  2023.0  LKIPCKL9XP1001641
989980      SANYA              SY1509F  Motorcycle  2022.0  LK1PCKL99M1001349
989981      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL95P1000722
989982      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL92P1000712
989983      SANYA              SY 150T  Motorcycle  2026.0  LK1PCKL91T1001554
989984      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL96T1002053
989985      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL94P1000940
989986      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL96N1000127
989987      SANYA               SY150T  Motorcycle  2021.0  LK1PCKL91M1000146
989988      SANYA               SY150T  Motorcycle  2025.0  LK1PCKL96S1002116
989989      SANYA                  150  Motorcycle  2023.0  LK1PCKL96P1000616
989990      SANYA                SY150  MOTORCYCLE  2023.0  LK1PCKL98P1000309
989991      SANYA              SY1509F  Motorcycle  2022.0  LK1PCKL94M1001341
989992      SANYA               SY150T  MOTORCYCLE  2023.0  LK1PCKL96P1001667
989993      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL97T1002076
989994      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL97T1002062
989995      SANYA              SY1509F  Motorcycle  2021.0  LK1PCKL9XM1000517
989996      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL95T1002111
989997      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL91P1000717
989998      SANYA               SY1507  Motorcycle  2021.0  LK1PCKL94M1000111
989999      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL92P1001651
990000      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL97P1001662
990001      SANYA                 2023  Motorcycle  2023.0  LK1PCKL95P1000154
990002      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL98T1002037
990003      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL98T1002104
990004      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL92T1002048
990005      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL94T1002083
990006      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL98T1002121
990007      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL98P1000679
990008      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL91T1002039
990009      SANYA              SY1509F  Motorcycle  2025.0  LK1PCKL90S1000989
990010      SANYA              SY1509F  Motorcycle  2023.0  LK1PCKL99N1000087
990011      SANYA           ATF110  G5  Motorcycle  2023.0  LK1PCKL94N1000496
990012      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL92T1002079
990013      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL95T1001900
990014      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL96T1002070
990015      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL9XT1002041
990016      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL94T1002116
990017      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL98T1001941
990018      SANYA              SY1509F  Motorcycle  2025.0  LK1PCKL97S1000293
990019      SANYA             SY 1509F  Motorcycle  2026.0  LK1PCKL90T1001884
990020      SANYA             SY 1509F  Motorcycle  2026.0  LK1PCKL97T1002109
990021      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL94T1001869
990022      SANYA               SY150T  Motorcycle  2022.0  LK1PCKL9XM1000632
990023      SANYA               SY150T  Motorcycle  2025.0  LK1PCKL98S1000500
990024      SANYA               SY150T  Motorcycle  2024.0  LK1PCKL97R1000076
990025      SANYA               SY 150  MOTORCYCLE  2023.0  LK1PCKL91P1000135
990026      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL93T1002043
990027      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL96T1002084
990028      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL96T1002120
990029      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL95T1002044
990030      SANYA               SY150T  Motorcycle  2025.0  LK1PCKL95S1000857
990031      SANYA               OTHERS  Motorcycle  2023.0  LK1PCKL94N1000269
990032      SANYA               SY150T  Motorcycle  2025.0  LK1PCKL96S1001967
990033      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL96T1002117
990034      SANYA                SY150  Motorcycle  2022.0  LK1PCKL98M1000970
990035      SANYA              SY1509F  Motorcycle  2022.0  LK1PCKL9XM1001568
990036      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL9XT1001875
990037      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL93T1001488
990038      SANYA                SY110  Motorcycle  2023.0  LK1XCHL20N1000002
990039      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL99T1001415
990040      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL99T1002046
990041      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL97P1000964
990042      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL98P1000441
990043      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL91T1002106
990044      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL98P1000794
990045      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL98P1000763
990046      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL92T1002034
990047      SANYA               SY150T  MOTORCYCLE  2023.0  LK1PCKL96P1001426
990048      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL9XP1001641
990049      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL94T1001757
990050      SANYA        اس ولی 150 تے  Motorcycle  2021.0  LK1PCKL94M1000142
990051      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL93P1000539
990052      SANYA                SY150  Motorcycle  2021.0  LK1PCKL9XM1000176
990053      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL95T1000987
990054      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL93T1002110
990055      SANYA            SANYA 150  Motorcycle  2024.0  LK1PCKL98R1000555
990056      SANYA               SY150T  Motorcycle  2024.0  LK1PCKL98R1000703
990057      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL95T1002092
990058      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL90T1002078
990059      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL9XT1002055
990060      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL98T1002054
990061      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL99P1001629
990062      SANYA               SY150T  Motorcycle  2021.0  LK1PCKL98L1000028
990063      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL92T1001918
990064      SANYA               SY150T  Motorcycle  2023.0  LKIPCKL92N1000500
990065      SANYA              SY1509F  Motorcycle  2023.0  LK1PCKL99N1000008
990066      SANYA               SY150T  Motorcycle  2022.0  LK1PCKL96M1000613
990067      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL95P1000686
990068      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL9XP1000571
990069      SANYA               SY150T  Motorcycle  2021.0  LK1PCKL93M1000245
990070      SANYA               SY150T  Motorcycle  2022.0  LK1PCKL97M1001480
990071      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL98T1002085
990072      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL9XP1000800
990073      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL92P1001665
990074      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL92P1001634
990075      SANYA               SY150T  Motorcycle  2025.0  LK1PCKL97S1000763
990076      SANYA               SY15UT  Motorcycle  2021.0  LK1PCKL16L1043471
990077      SANYA               SY150T  Motorcycle  2025.0  LK1PCKL96S1002102
990078      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL94P1000677
990079      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL98P1001671
990080      SANYA               SY150T  Motorcycle  2021.0  LK1PCKL93M1000455
990081      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL9XT1002105
990082      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL90T1002064
990083      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL93T1002074
990084      SANYA               SY150T  Motorcycle  2024.0  LK1PCKL90R1000095
990085      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL97N1000542
990086      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL92T1002065
990087      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL93T1002107
990088      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL97T1002093
990089      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL98T1001826
990090      SANYA                 150T  Motorcycle  2025.0  LK1PCKL98S1000044
990091      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL93P1000783
990092      SANYA              SY 150T  Motorcycle  2023.0  LK1PCKL94N1000773
990093      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL91T1001649
990094      SANYA              SY1509F  Motorcycle  2023.0  LK1PCKL9XP1000909
990095      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL96T1002537
990096      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL97T1002045
990097      SANYA               SY150T  Motorcycle  2022.0  LK1PCKL97M1001320
990098      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL9XP1001123
990099      SANYA               SY150T  Motorcycle  2024.0  LK1PCKL93R1000740
990100      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL9XT1002119
990101      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL93T1002088
990102      SANYA               SY150T  Motorcycle  2024.0  LK1PCKL12R1000285
990103      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL91P1000796
990104      SANYA              SY1509F  Motorcycle  2023.0  LK1PCKL99P1001159
990105      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL93P1000699
990106      SANYA               OTHERS  Motorcycle  2025.0  LK1PCKL97S1000777
990107      SANYA              SY1509F  Motorcycle  2021.0  LK1PCKL90M1000297
990108      SANYA              SY1509F  Motorcycle  2023.0  LK1PCKL98N1000906
990109      SANYA                 S150  Motorcycle  2024.0  LK1PCKL95R1000206
990110      SANYA              SY1509F  Motorcycle  2024.0  LKIPCKL99R1000127
990111      SANYA        اس واي 150 تي  Motorcycle  2024.0  LK1PCKL19R1000249
990112      SANYA               SY150T  Motorcycle  2022.0  LKIPCKL95N1000877
990113      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL97T1001901
990114      SANYA               SY150T  Motorcycle  2025.0  LK1PCKL97S1000035
990115      SANYA               SY150T  Motorcycle  2024.0  LK1PCKL95R1000688
990116      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL95P1001661
990117      SANYA               SY150T  Motorcycle  2024.0  LK1PCKL94R1000634
990118      SANYA                SY150  Motorcycle  2021.0  LK1PCKL95M1000232
990119      SANYA               SY150T  Motorcycle  2022.0  LK1PCKL95N1000877
990120      SANYA               SY150T  Motorcycle  2022.0  LK1PCKL96M1000661
990121      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL90T1002047
990122      SANYA              SY1509F  Motorcycle  2021.0  LK1PCKL93M1000343
990123      SANYA               SY150T  MOTORCYCLE  2023.0  LK1PCKL96P1001670
990124      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL95T1002061
990125      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL91T1002073
990126      SANYA               SY150T  Motorcycle  2021.0  LK1PCKL90M1000087
990127      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL92T1001661
990128      SANYA              SY1509F  Motorcycle  2022.0  LK1PCKL90M1001322
990129      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL9XN1000583
990130      SANYA              SY1509F  Motorcycle  2023.0  LK1PCKL91N1000889
990131      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL90T1001920
990132      SANYA              SY1509F  Motorcycle  2026.0  LK1PCKL92T1002115
990133      SANYA             SY 150 T  Motorcycle  2021.0  LK1PCKL9XM1000436
990134      SANYA               SY150T  Motorcycle  2021.0  LK1PCKL96M1000093
990135      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL96P1000759
990136      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL98P1001556
990137      SANYA              SY1509F  Motorcycle  2023.0  LK1PCKL93N1000022
990138      SANYA              SY 150T  Motorcycle  2025.0  LK1PCKL90S1002063
990139      SANYA               SY150T  Motorcycle  2026.0  LK1PCKL98T1001020
990140      SANYA              SY 150T  Motorcycle  2025.0  LK1PCKL90S1002015
994781      SANYA              SY 150T  Motorcycle  2025.0  LK1PCKL91S1002086
994791      SANYA               SY150T  Motorcycle  2025.0  LK1PCKL95S1002057
994796      SANYA              SY 150T  Motorcycle  2025.0  LK1PCKL9XS1002085
994805      SANYA              SY 150T  Motorcycle  2025.0  LK1PCKL99S1002093
994806      SANYA              SY 150T  Motorcycle  2025.0  LK1PCKL95S1001958
994835     TYANMA  PICKUP SINGLE CABIN      Pickup  2007.0  LHA1201D57A005733
994866       VOLG                 2410       Sedan  2007.0  X9631020071404653
994941     VANDER               VISION  Motorcycle  2022.0  7KGTC2V11NR003667
994943     SANIYA               SY150T  Motorcycle  2023.0  LK1PCKL98P1000598
994950        HIG              KLQ6600         Van  2025.0  LKL1AAA64SA811720
994962     KAOE K                 2015      Pickup  2015.0  LLTAN12FXFM030078
994983  SHANG JAN                   35     Station  2016.0  L55A3ADE56A000066
995034      SANYA               SY150T  Motorcycle  2023.0  LK1PCKL93N1000103
995042      KAN M                RYKER  Motorcycle  2019.0  3JB2FEG10KJ002208

In [85]:
cleanup = {
    "AYED AYED": "AYED",
    "AYED BIKE": "AYED",
    "BIUE BAIRD": "BLUE BIRD",
    "FLONY": "FOLONY",
    "CF MOTO": "CFMOTO",
    "LEADING": "LI AUTO",
    "CAN": "CAN-AM",
    "AVENGER": "BAJAJ",
    "APACHE": "TVS",
    "ASHOK": "ASHOK LEYLAND",
    "ADMIRAL": "ZXAUTO",
    "DEXER": "GMC",
    "ESCHER": "EICHER",
    "KOASKO": "KAWASAKI",
    "PADAR": "GEELY",
    "SANYOU": "SANYA",
    "SANIYA": "SANYA",
    "VANDER": "VANDERHALL",
    "ROCKY": "DAIHATSU",
    "BAJA": "YAMAHA",
    "KAN M": "CAN-AM",
    "SHANG JAN": "CHANGAN",
    "ZENIN": "ZNEN",
    "HIG": "HIGER",
    "VOLG": "VOLGA",
    "GUNAU": "GONOW",
    "BYD - LEOPARD": "BYD"
}

In [20]:
df_clean = df_clean[df_clean["make"] != "KAOE K"]

In [84]:
drop_makes = [
    "KAOE K",
    "PUYUAN"
]

In [87]:
make_cleanup = {}

make_cleanup.update({
    "GUNAU": "GONOW",
    "VOLG": "VOLGA",

    "ZENIN": "ZNEN",

    "AYED AYED": "AYED",
    "AYED BIKE": "AYED",

    "BIUE BAIRD": "BLUE BIRD",

    "FLONY": "FOLONY",

    "CF MOTO": "CFMOTO",

    "LEADING": "LI AUTO",
    "LI": "LI AUTO",

    "CAN": "CAN-AM",
    "KAN M": "CAN-AM",

    "APACHE": "TVS",
    "AVENGER": "BAJAJ",
    "BAJA": "YAMAHA",

    "ASHOK": "ASHOK LEYLAND",

    "ADMIRAL": "ZXAUTO",

    "DEXER": "GMC",

    "ESCHER": "EICHER",

    "KOASKO": "KAWASAKI",

    "PADAR": "GEELY",

    "SANYOU": "SANYA",
    "SANIYA": "SANYA",

    "SHANG JAN": "CHANGAN",

    "VANDER": "VANDERHALL",

    "ROCKY": "DAIHATSU",

    "INDIAN  MOTORCYCLE": "INDIAN MOTORCYCLE",

    "MANN": "MAN",

    "HART FORD": "HARTFORD",

    "BYD - LEOPARD": "BYD",
})

In [47]:
make_counts = df_clean["make"].value_counts()

make_counts[make_counts <= 3]

make
OMODA                 3
VGV                   3
SCION                 3
SANDSTORM             3
DONGFENG-XIAOKA       3
PAGANI                3
SATURN                3
BENDA                 3
SHARAMAX              3
VINFAST               3
WIESMANN              3
TRUMPCHI              3
LIVEWIRE              3
ZHENGZHOU             3
EMPALA                3
HIPHI                 2
HYOSUNG               2
FORCE                 2
HYCAN                 2
TAM                   2
SAIC                  2
ECOWAY                2
YADEA                 2
CAN                   2
AVENGER               2
SCANIA                2
ESCHER                2
NETA                  2
GAS GAS               2
GUNAU                 2
CATERHAM              2
BAOJUN                2
CF MOTO               2
KOASKO                2
KAMA                  1
JIYUE                 1
TYANMA                1
SAMSUNG               1
ZONTES                1
SCORPA                1
LYKAN                 1
LEADING               1
VOLG                  1
MONTESA               1
DAF                   1
MACK                  1
AYED AYED             1
ASHOK                 1
CATERPILLAR           1
BUELL                 1
XCMG                  1
BIUE BAIRD            1
SWM                   1
GWM - WEY             1
SAIMO                 1
ROYAL ALLOY           1
JINBEI                1
BETA                  1
LIEBHERR              1
SINOTRUK              1
MANN                  1
VANDER                1
SANIYA                1
ROCKY                 1
HIG                   1
APACHE                1
SANYOU                1
PADAR                 1
DEXER                 1
ITALJET               1
HART FORD             1
PREVOST               1
SWIFT                 1
YUTONG                1
KOENIGSEGG            1
ZNIN                  1
FANTIC                1
DELOREAN              1
ZAMIYAD               1
JOYLONG               1
SHANG JAN             1
MAN                   1
CHAMP                 1
SOUO                  1
SANY                  1
ZERO                  1
INDIAN  MOTORCYCLE    1
ADMIRAL               1
ARI                   1
BYD - LEOPARD         1
HIGER                 1
BAJA                  1
PUYUAN                1
KOVE                  1
ZENIN                 1
FLONY                 1
LANCIA                1
FARIZON               1
AYED BIKE             1
MHERO                 1
LONSIN                1
PEMBLETON             1
JCB                   1
KAN M                 1
BIMOTA                1
APULUO                1
AIQAR                 1
ELECTRIC MOTION       1
Name: count, dtype: int64

In [48]:
suspects = [
    "MANN",
    "HART FORD",
    "CHAMP",
    "SANY",
    "KAMA",
    "SAMSUNG",
]

In [49]:
df_clean[df_clean["make"].isin(suspects)][
    ["make","model","bodyType","year","chassisNumber"]
]

             make          model           bodyType    year      chassisNumber
994744       KAMA           KAMA  Pickup Double Cab  2016.0  LWU2DM2C1GKM00012
994841    SAMSUNG         SV 110             Pickup  2000.0  KNR1L1HEBYT004117
994938       MANN           2000              TRUCK  2000.0  WMAL90ZZZYY055936
994963  HART FORD       MINI 150         Motorcycle  2024.0  RGTRB06A0RT040039
994986      CHAMP          500RR         Motorcycle  2026.0  LY0GCT101SD700020
994996       SANY  SANY STC1000C    HEAVY EQUIPMENT  2023.0  LFCNPG6P7J2029081

In [88]:
df_clean["make"] = df_clean["make"].replace(make_cleanup)

In [89]:
df_clean = df_clean[
    ~df_clean["make"].isin([
        "KAOE K",
        "PUYUAN"
    ])
]

In [50]:
drop_makes.append("SAMSUNG")

In [90]:
df_clean["make"].nunique()

262

In [91]:
df_clean["make"].value_counts().tail(50)

make
SAMSUNG            1
ZONTES             1
SCORPA             1
LYKAN              1
VOLGA              1
MONTESA            1
DAF                1
MACK               1
CATERPILLAR        1
BUELL              1
XCMG               1
BLUE BIRD          1
SWM                1
GWM - WEY          1
SAIMO              1
ROYAL ALLOY        1
JINBEI             1
BETA               1
LIEBHERR           1
SINOTRUK           1
HIG                1
ITALJET            1
HARTFORD           1
PREVOST            1
SWIFT              1
YUTONG             1
KOENIGSEGG         1
ZNIN               1
FANTIC             1
DELOREAN           1
ZAMIYAD            1
JOYLONG            1
CHAMP              1
SOUO               1
SANY               1
ZERO               1
ARI                1
HIGER              1
KOVE               1
ZNEN               1
LANCIA             1
FARIZON            1
MHERO              1
LONSIN             1
PEMBLETON          1
JCB                1
BIMOTA             1
APULUO             1
AIQAR              1
ELECTRIC MOTION    1
Name: count, dtype: int64

In [92]:
make_cleanup = {
    "GUNAU": "GONOW",
    "VOLG": "VOLGA",
    "ZENIN": "ZNEN",

    "AYED AYED": "AYED",
    "AYED BIKE": "AYED",

    "BIUE BAIRD": "BLUE BIRD",

    "FLONY": "FOLONY",

    "CF MOTO": "CFMOTO",

    "LEADING": "LI AUTO",
    "LI": "LI AUTO",

    "CAN": "CAN-AM",
    "KAN M": "CAN-AM",

    "APACHE": "TVS",
    "AVENGER": "BAJAJ",
    "BAJA": "YAMAHA",

    "ASHOK": "ASHOK LEYLAND",

    "ADMIRAL": "ZXAUTO",

    "DEXER": "GMC",

    "ESCHER": "EICHER",

    "KOASKO": "KAWASAKI",

    "PADAR": "GEELY",

    "SANYOU": "SANYA",
    "SANIYA": "SANYA",

    "SHANG JAN": "CHANGAN",

    "VANDER": "VANDERHALL",

    "ROCKY": "DAIHATSU",

    "INDIAN  MOTORCYCLE": "INDIAN MOTORCYCLE",

    "MANN": "MAN",

    "HART FORD": "HARTFORD",

    "HIG": "HIGER",

    "BYD - LEOPARD": "BYD",
}

df_clean["make"] = df_clean["make"].replace(make_cleanup)

In [93]:
drop_makes = [
    "KAOE K",
    "PUYUAN",
]

df_clean = df_clean[
    ~df_clean["make"].isin(drop_makes)
]

In [94]:
df_clean = df_clean[df_clean["make"] != "SAMSUNG"]

In [109]:
additional_cleanup = {
    "ZNIN": "ZNEN",
    "ZAMIYAD": "ZAMYAD",

    "AIQAR": "CHERY",
    "CHERY - ICAR": "CHERY",

    "BYD - DENZA": "BYD",
    "BYD - YANGWANG": "BYD",
    "BYD - LEOPARD": "BYD",

    "SOUO": "GWM",
    "GWM - WEY": "GWM",
    "GREAT WALL": "GWM",
}

df_clean["make"] = df_clean["make"].replace(additional_cleanup)

In [126]:
final_makes = sorted(df_clean["make"].dropna().unique())

print(f"Unique makes: {len(final_makes)}")

for make in final_makes:
    print(make)

Unique makes: 253
ABARTH
ACURA
AEOLUS
AFTEK
AITO
AL DAMANI
ALFA ROMEO
APRILIA
APULUO
ARI
ASHOK LEYLAND
ASTON MARTIN
AUDI
AVATR
AYED
BAIC
BAJAJ
BAOJUN
BAW
BENDA
BENELLI
BENTLEY
BESTUNE
BETA
BIMOTA
BLUE BIRD
BMW
BORGWARD
BRILLIANCE
BUELL
BUGATTI
BUICK
BYD
CADILLAC
CAN-AM
CATERHAM
CATERPILLAR
CFMOTO
CHAMP
CHANGAN
CHANGHUA
CHERY
CHEVROLET
CHRYSLER
CITROEN
CMC
DAEWOO
DAF
DAIHATSU
DATSUN
DEEPAL
DELOREAN
DFSK
DODGE
DONGFENG
DONGFENG E
DONGFENG-AEOLUS
DONGFENG-XIAOKA
DORCEN
DUCATI
ECOWAY
EICHER
ELECTRIC MOTION
EMPALA
EXEED
FANTIC
FARIZON
FAW
FERRARI
FIAT
FOLONY
FORCE
FORD
FORTHING
FOTON
GAC
GAS GAS
GEELY
GENESIS
GMC
GONOW
GWM
HAOJUE
HARLEY-DAVIDSON
HARTFORD
HAVAL
HERO
HIGER
HINO
HIPHI
HONDA
HONGQI
HUAIHAI
HUMMER
HUSQVARNA
HYCAN
HYOSUNG
HYUNDAI
INDIAN MOTORCYCLE
INEOS
INFINITI
ISUZU
ITALJET
IVECO
JAC
JAECOO
JAGUAR
JCB
JEEP
JETOUR
JIDU
JINBEI
JIYUE
JMC
JOYLONG
KAIYI
KAMA
KAWASAKI
KIA
KING LONG
KOENIGSEGG
KOVE
KTM
KYMCO
LADA
LAMBORGHINI
LANCIA
LAND ROVER
LEAPMOTOR
LEXUS
LI AUTO
LIEBHERR
LIFAN
LINCOLN
LIVEWIRE
LONSIN
LOTUS
LUCID
LUXGEN
LYKAN
LYNK & CO
MACK
MAEXTRO
MAHINDRA
MAN
MASERATI
MAXUS
MAYBACH
MAZDA
MCLAREN
MERCEDES BENZ
MERCURY
MG
MHERO
MINI
MITSUBISHI
MONTESA
MORGAN
MOTO GUZZI
MV AGUSTA
NETA
NIO
NISSAN
OMODA
OPEL
PAGANI
PEMBLETON
PEUGEOT
PIAGGIO
POLARIS
POLESTAR
PONTIAC
PORSCHE
POWEREAGLE
PREVOST
PROTON
QINGLING
RABDAN
RAM
RENAULT
RIDDARA
RIVIAN
ROLLS ROYCE
ROX
ROYAL ALLOY
ROYAL ENFIELD
SAAB
SAIC
SAIMO
SANDSTORM
SANY
SANYA
SATURN
SCANIA
SCION
SCORPA
SEAT
SERES
SHARAMAX
SHARMAX
SHERCO
SINOTRUK
SKODA
SKYWELL
SLINGSHOT
SMART
SOUEAST
SSANGYONG
SUBARU
SUZUKI
SWIFT
SWM
SYM
TAM
TANK
TATA
TESLA
TGB
TOYOTA
TRIUMPH
TRUMPCHI
TVS
TYANMA
UAZ
VANDERHALL
VESPA
VGV
VICTORIA
VICTORY
VINFAST
VOLGA
VOLKSWAGEN
VOLTAMP
VOLVO
VOYAH
WIESMANN
WULING
XCMG
XIAOMI
XPENG
YADEA
YAMAHA
YUTONG
ZAMYAD
ZEEKR
ZERO
ZHENGZHOU
ZNA
ZNEN
ZONGSHEN
ZONTES
ZOTYE
ZXAUTO

In [111]:
check = [
    "ZNIN",
    "ZAMIYAD",
    "AIQAR",
    "CHERY - ICAR",
    "BYD - DENZA",
    "BYD - YANGWANG",
    "BYD - LEOPARD",
    "SOUO",
    "GWM - WEY",
]

df_clean[df_clean["make"].isin(check)]["make"].value_counts()

Series([], Name: count, dtype: int64)

In [124]:
df[df["make"] == "SHARMAX"]

,chassisNumber,year,make,model,trim,bodyType,regionalSpec,cylinders,color,origin,weightInKg,noOfPassengers
991005,HG6PDMRV3RW000068,2023.0,SHARMAX,GL 250,NaN,Motorcycle,GCC,NaN,white and blue,China,220.0,2.0
991006,LBBPAB004PBF55729,2023.0,SHARMAX,RST 422 ULTRA,NaN,Motorcycle,GCC,NaN,black,China,150.0,2.0
991007,LXENAZ502SA000042,2025.0,SHARMAX,GP451,NaN,Motorcycle,GCC,NaN,black,CHINA,NaN,2.0
991008,LBBPCD005SBH60569,2025.0,SHARMAX,GP,NaN,Motorcycle,GCC,NaN,black,China,250.0,2.0
991009,LXYJCNL04S0654778,2025.0,SHARMAX,ENDURO,NaN,Motorcycle,GCC,NaN,black,China,NaN,2.0
991010,L7GPDPLDXP1154197,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,grey,China,200.0,2.0
991011,LXYJCNL03P0410384,2023.0,SHARMAX,ENDURO 250,NaN,Motorcycle,GCC,NaN,black and silver,China,170.0,2.0
991012,LBBPC2007TBJ07731,2026.0,SHARMAX,RR 801,NaN,MOTORCYCLE,GCC,NaN,black,United Arab Emirates,100.0,1.0
991013,LBBPC2001TBJ07725,2026.0,SHARMAX,RR 801 V,NaN,Motorcycle,GCC,NaN,gray and black,CHINA,NaN,1.0
991014,LZBTX9C79S1000063,2025.0,SHARMAX,FX200 (MOTORCYCLE),NaN,Motorcycle,GCC,NaN,blue,CHINA,150.0,2.0
991015,LBBP66107PBF56347,2023.0,SHARMAX,GL570 ULTRA,NaN,Motorcycle,GCC,NaN,black,China,220.0,2.0
991016,LZBTX9B90S1003663,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,red,China,NaN,2.0
991017,LRSJCNLR8P0D19774,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,grey,China,220.0,2.0
991018,L7GPCLLY5S1227791,2025.0,SHARMAX,STREET BIKE 175,NaN,Motorcycle,GCC,NaN,gray and black,China,150.0,2.0
991019,LXYJCNL08S0654752,2025.0,SHARMAX,ENDURO 250,NaN,Motorcycle,GCC,NaN,black and red,China,190.0,2.0
991020,LXYJCNL06S0654720,2025.0,SHARMAX,ENDURO,NaN,Motorcycle,GCC,NaN,red,China,151.0,2.0
991021,LXYJDSL02P0414695,2023.0,SHARMAX,GL 400,NaN,Motorcycle,GCC,NaN,gray and black,China,250.0,2.0
991022,LZBTX9C71S1000185,2025.0,SHARMAX,FX 200,NaN,Motorcycle,GCC,NaN,blue,China,135.0,2.0
991023,LZBTX9C70S1000145,2025.0,SHARMAX,FX 200,NaN,Motorcycle,GCC,NaN,black,China,NaN,150.0
991024,HA9TX9A25S1MAN059,2025.0,SHARMAX,VESPITO,NaN,Motorcycle,GCC,NaN,green and white,China,150.0,1.0
991025,HA9TX9A2XS1MAN056,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,green and white,China,150.0,2.0
991026,LXYJCNL05P0410385,2023.0,SHARMAX,SHARMAX ENDURO 2,NaN,Motorcycle,GCC,NaN,black,China,170.0,2.0
991027,L7GPCLLY9S1227826,2025.0,SHARMAX,SHARMAX STREET BIKE 175,NaN,Motorcycle,GCC,NaN,gray and black,China,150.0,2.0
991028,YY2V67MR25J171272,2026.0,SHARMAX,SHARMAX/RR 661,NaN,Motorcycle,GCC,NaN,green,CHINA,160.0,2.0
991029,HA9TX9A2XS1MAN011,2025.0,SHARMAX,VESPIRO 150,NaN,Motorcycle,GCC,NaN,white,China,150.0,2.0
991030,LXYJCNL01P0410383,2023.0,SHARMAX,ENDURO,NaN,Motorcycle,GCC,NaN,black and silver,China,150.0,2.0
991031,HA9TX9A28S1MAN041,2025.0,SHARMAX,VESPITE,NaN,Motorcycle,GCC,NaN,white,China,NaN,2.0
991032,L7GPCLLY9S1227843,2025.0,SHARMAX,175 ME ULTRA,NaN,MOTORCYCLE,GCC,NaN,black,United Arab Emirates,NaN,2.0
991033,LRSJCNLR3P0D19830,2023.0,SHARMAX,ENDURO 300,NaN,Motorcycle,GCC,NaN,black,China,150.0,2.0
991034,HG6PDV5D6SW000333,2025.0,SHARMAX,CUSTOM 1000 R,NaN,Motorcycle,GCC,NaN,grey,China,280.0,1.0
991035,L8YVDSAA2TY010016,2026.0,SHARMAX,SPYDER,NaN,Motorcycle,GCC,NaN,green,China,100.0,2.0
991036,L7GPCLLYXS1227852,2025.0,SHARMAX,STREET BIKE,NaN,Motorcycle,GCC,NaN,silver,CHINA,NaN,2.0
991037,LXENAZ504SA000026,2025.0,SHARMAX,GP451,NaN,Motorcycle,GCC,NaN,black,CHINA,NaN,2.0
991038,LZBTX9C78S1000183,2025.0,SHARMAX,FX200,NaN,Motorcycle,GCC,NaN,blue,CHINA,150.0,2.0
991039,LBBPCD005RBG74172,2024.0,SHARMAX,GP 881 UL,NaN,Motorcycle,GCC,NaN,black and red,China,140.0,2.0
991040,HA9TX9A23S1MAN061,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,green and white,China,124.0,2.0
991041,L7GPCLLYXS1227821,2025.0,SHARMAX,STREET BIKE 175,NaN,Motorcycle,GCC,NaN,gray and black,China,250.0,2.0
991042,LBBPAU004PBF55774,2023.0,SHARMAX,RR 551 ULTRA,NaN,Motorcycle,GCC,NaN,brown,China,250.0,2.0
991043,LBBPT3007SBH59224,2025.0,SHARMAX,FX350,NaN,MOTORCYCLE,GCC,NaN,black,China,NaN,2.0
991044,HA9TX9A2XS1MAN073,2025.0,SHARMAX,VESPITE,NaN,MOTORCYCLE,GCC,NaN,black,United Arab Emirates,100.0,1.0
991045,LXYJCNLOOP0410424,2023.0,SHARMAX,SHARMAX ENDURO,NaN,Motorcycle,GCC,NaN,black,China,170.0,2.0
991046,LXYJCNL09P0410373,2023.0,SHARMAX,ENDURO 2,NaN,Motorcycle,GCC,NaN,black and red,China,220.0,2.0
991047,LBBL17007PBF55090,2023.0,SHARMAX,NX 150,NaN,Motorcycle,GCC,NaN,green,China,150.0,2.0
991048,LXENAZ500SA000010,2025.0,SHARMAX,GP451,NaN,Motorcycle,GCC,NaN,black,CHINA,-1.0,1.0
991049,HA9TX9A23S1MAN013,2025.0,SHARMAX,VESPITO 150,NaN,Motorcycle,GCC,NaN,white,CHINA,NaN,2.0
991050,HG6PDMRVXSW000106,2025.0,SHARMAX,GL 250,NaN,Motorcycle,GCC,NaN,silver / grey,China,120.0,2.0
991051,L7GPCLLY8S1227834,2025.0,SHARMAX,175 ME ULTRA,NaN,Motorcycle,GCC,NaN,silver,China,150.0,2.0
991052,LBBP66105SBH62551,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,grey,CHINA,NaN,2.0
991053,HA9TX9A25S1MAN031,2025.0,SHARMAX,VESPITE,NaN,MOTORCYCLE,GCC,NaN,black,China,100.0,1.0
991054,LZBTX9C77P1000215,2023.0,SHARMAX,FX 200,NaN,Motorcycle,GCC,NaN,blue,China,150.0,2.0
991055,HA9TX9A26S1MAN085,2025.0,SHARMAX,Vespito,NaN,Motorcycle,GCC,NaN,beige,China,150.0,2.0
991056,LBBPAB008PBF55703,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,black,China,250.0,2.0
991057,HA9TX9A2XS1MAN025,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,white,China,NaN,2.0
991058,LXENAZ507SA000019,2025.0,SHARMAX,GP451,NaN,Motorcycle,GCC,NaN,black,CHINA,1.0,2.0
991059,LRSJCNLRXP0D19792,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,gray and black,China,210.0,2.0
991060,HG6PDMCC7RW000016,2024.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,black,CHINA,150.0,2.0
991061,LXYJDSL07P0414661,2023.0,SHARMAX,GL 400,NaN,Motorcycle,GCC,NaN,gray and black,China,200.0,2.0
991062,LBBPC2005TBJ07744,2026.0,SHARMAX,RR 801 V,NaN,MOTORCYCLE,GCC,NaN,gray and black,CHINA,NaN,2.0
991063,LRSJCNLR9P0D19847,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,gray and black,China,150.0,2.0
991064,LBBPT3000SBH59226,2024.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,black,CHINA,NaN,2.0
991065,LXYJCNL02S0654746,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,red,China,NaN,1.0
991066,L7GPCLLY8S1227820,2025.0,SHARMAX,STREET BIKE 175,NaN,Motorcycle,GCC,NaN,gray and black,China,175.0,2.0
991067,L7GPCLLY1S1227819,2025.0,SHARMAX,SHARMAX STREET BIKE 175,NaN,Motorcycle,GCC,NaN,gray and black,China,150.0,2.0
991068,LBBL17007PBF55056,2023.0,SHARMAX,NX 150,NaN,Motorcycle,GCC,NaN,blue,China,150.0,2.0
991069,LXENAZ501SA000047,2025.0,SHARMAX,GP 451,NaN,Motorcycle,GCC,NaN,black,China,250.0,2.0
991070,LXYJCNL07S0654726,2025.0,SHARMAX,ENDURO,NaN,Motorcycle,GCC,NaN,red,China,NaN,1.0
991071,LBBPAB006PBF55702,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,orange and black,China,224.0,2.0
991072,HA9TX9A27S1MAN015,2025.0,SHARMAX,VESPITO,NaN,Motorcycle,GCC,NaN,white,China,650.0,2.0
991073,LXENAZ504SA000043,2025.0,SHARMAX,P451,NaN,Motorcycle,GCC,NaN,black,CHINA,NaN,1.0
991074,LBBL9600XPBF61792,2023.0,SHARMAX,FX150 ULTRA,NaN,Motorcycle,GCC,NaN,silver red white black,China,150.0,2.0
991075,LBBPCD007SBH60556,2025.0,SHARMAX,ULTRA,NaN,Motorcycle,GCC,NaN,black and red,CHINA,NaN,2.0
991076,LZBTX9B99S1003662,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,red,China,120.0,2.0
991077,HA9TX9A28S1MAN069,2025.0,SHARMAX,VESPIA 150,NaN,Motorcycle,GCC,NaN,beige,China,150.0,2.0
991078,HG6PDMRV1SW000124,2025.0,SHARMAX,GL250 (MOTORCYCLE),NaN,MOTORCYCLE,GCC,NaN,silver,China,NaN,2.0
991079,HA9TX9A27S1MAN063,2025.0,SHARMAX,VESPITE,NaN,Motorcycle,GCC,NaN,green and white,China,1.0,2.0
991080,LXYJCNL02S0654715,2025.0,SHARMAX,ENDURO,NaN,Motorcycle,GCC,NaN,red,China,NaN,1.0
991081,LBBL96000PBF61798,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,black and red,China,150.0,2.0
991082,HA9TX9A20S1MAN065,2025.0,SHARMAX,VESPITO,NaN,Motorcycle,GCC,NaN,green and white,China,NaN,1.0
991083,LBBP81007PBF56377,2023.0,SHARMAX,RST 750 ULTRA,NaN,Motorcycle,GCC,NaN,black,China,NaN,1.0
991084,LXYJCNL0XS0654803,2024.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,black and silver,CHINA,150.0,2.0
991085,L8YKDSPK6SY016564,2024.0,SHARMAX,SPYDER,NaN,Motorcycle,GCC,NaN,blue,China,NaN,3.0
991086,HG6PDLRS6RW000145,2023.0,SHARMAX,RST200 ULTRA,NaN,Motorcycle,GCC,NaN,black,China,2.0,2.0
991087,ZDMM511AACB062978,2013.0,SHARMAX,DUCATI 1100,NaN,Motorcycle,GCC,NaN,black,Italy,250.0,2.0
991088,LZBTX9C70S1000033,2025.0,SHARMAX,FX 200,NaN,Motorcycle,GCC,NaN,red,China,130.0,2.0
991089,LBBPC2007TBJ07745,2026.0,SHARMAX,RR 801 V,NaN,MOTORCYCLE,GCC,NaN,gray and black,CHINA,173.0,1.0
991090,HG6PDMRV6RW000095,2023.0,SHARMAX,2023,NaN,Motorcycle,GCC,NaN,black and silver,CHINA,210.0,2.0
991091,LZBTX9C70P1000170,2023.0,SHARMAX,FX 200,NaN,Motorcycle,GCC,NaN,silver red white black,China,150.0,2.0
991092,LBBN64005PBF55730,2023.0,SHARMAX,RST 322 ULTRA,NaN,MOTORCYCLE,GCC,NaN,black,CHINA,NaN,2.0
991093,HG6PDMRV1SW000110,2025.0,SHARMAX,GL 250,NaN,Motorcycle,GCC,NaN,silver,China,200.0,2.0
991094,LXYJCNL06S0654801,2025.0,SHARMAX,ENDURO,NaN,Motorcycle,GCC,NaN,silver,CHINA,175.0,2.0
991095,HA9TX9A27S1MAN029,2025.0,SHARMAX,VESPITO 150,NaN,Motorcycle,GCC,NaN,beige,China,130.0,2.0
991096,HG6PDMCC1RW000013,2023.0,SHARMAX,RR301 UL,NaN,Motorcycle,GCC,NaN,black,China,250.0,2.0
991097,LZBTX9C74S1000164,2025.0,SHARMAX,FX 200,NaN,Motorcycle,GCC,NaN,black and red,China,150.0,2.0
991098,L7GPCLLY9S1227857,2025.0,SHARMAX,TERRIN,NaN,MOTORCYCLE,GCC,NaN,silver,CHINA,1000.0,2.0
991099,LBBL96001PBF61809,2023.0,SHARMAX,FX150 ULTRA,NaN,Motorcycle,GCC,NaN,gray and black,China,150.0,2.0
991100,HG6PDMRV3SW000125,2025.0,SHARMAX,GL250,NaN,Motorcycle,GCC,NaN,silver,China,150.0,1.0
991101,LXENAZ50XSA000029,2025.0,SHARMAX,GP451,NaN,MOTORCYCLE,GCC,NaN,black,China,174.0,2.0
991102,LXYJCNL03S0654724,2025.0,SHARMAX,ENDURO,NaN,Motorcycle,GCC,NaN,red,CHINA,200.0,1.0
991103,LXENAZ507SA000070,2025.0,SHARMAX,GP451,NaN,Motorcycle,GCC,NaN,black,CHINA,NaN,2.0
991104,HY2PEAND9PB000478,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,black and red,China,150.0,2.0
991105,L8YPDTPJ9TY010004,2026.0,SHARMAX,RR,NaN,Motorcycle,GCC,NaN,green,CHINA,200.0,2.0
991106,LXENAZ508SA000031,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,black,CHINA,NaN,1.0
991107,HY2PEAND5PB000171,2023.0,SHARMAX,AYED250N 3GP,NaN,Motorcycle,GCC,NaN,black and red,China,150.0,2.0
991108,HG6PDMCC5RW000031,2024.0,SHARMAX,RR301 ULTRA,NaN,Motorcycle,GCC,NaN,green,CHINA,100.0,2.0
991109,LBBP99003PBF55822,2023.0,SHARMAX,GL770 ULTRA,NaN,Motorcycle,GCC,NaN,black and silver,China,250.0,2.0
991110,LBBL17008PBF55065,2023.0,SHARMAX,NX 150,NaN,Motorcycle,GCC,NaN,green and black,China,150.0,2.0
991111,LBBP99004PBF55814,2023.0,SHARMAX,SHARMAX 770,NaN,Motorcycle,GCC,NaN,black,CHINA,150.0,2.0
991112,L76PDPLD7P1154206,2023.0,SHARMAX,GL 250,NaN,Motorcycle,GCC,NaN,silver,CHINA,NaN,2.0
991113,LBBL96006PBF61806,2023.0,SHARMAX,RST,NaN,Motorcycle,GCC,NaN,gray and black,CHINA,100.0,1.0
991114,HG6PDMRV5SW000112,2025.0,SHARMAX,GL 250,NaN,Motorcycle,GCC,NaN,black and silver,China,150.0,2.0
991115,LZBTX9B90S1002416,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,green,China,NaN,2.0
991116,L7GPDPLD7P1154206,2023.0,SHARMAX,GL 250,NaN,Motorcycle,GCC,NaN,silver,CHINA,150.0,2.0
991117,LZBTX9C71P1000159,2023.0,SHARMAX,FH200LC,NaN,Motorcycle,GCC,NaN,black and red,CHINA,140.0,2.0
991118,HG6PDMCC5RW000032,2024.0,SHARMAX,RR301 ULTRA,NaN,Motorcycle,GCC,NaN,green,CHINA,100.0,2.0
991119,LXYJCNL01S0654771,2025.0,SHARMAX,ENDURO 250,NaN,Motorcycle,GCC,NaN,black and silver,China,170.0,2.0
991120,L7GPCLLY3S1227806,2025.0,SHARMAX,SHARMAX STREET BIKE 175,NaN,Motorcycle,GCC,NaN,gray and black,China,150.0,2.0
991121,LXYJCNL08P0410414,2023.0,SHARMAX,ENDURO 250,NaN,Motorcycle,GCC,NaN,black and silver,China,220.0,2.0
991122,HG6PDMRV4SW000134,2025.0,SHARMAX,GL250 (MOTORCYCLE),NaN,Motorcycle,GCC,NaN,blue,China,NaN,2.0
991123,LBBPC2007RBH15129,2024.0,SHARMAX,SHARMAX RR 801V U,NaN,Motorcycle,GCC,NaN,black,China,300.0,2.0
991124,LXENAZ509SA000040,2025.0,SHARMAX,GP 451,NaN,Motorcycle,GCC,NaN,black,China,250.0,2.0
991125,HG6PDMRV2RW000076,2023.0,SHARMAX,GL 250,NaN,Motorcycle,GCC,NaN,black,China,150.0,2.0
991126,LBBPCD005RBG74169,2024.0,SHARMAX,GP 881 UL,NaN,Motorcycle,GCC,NaN,black and red,China,250.0,2.0
991127,L7GPCLLY2S1227859,2025.0,SHARMAX,STREET BIKE,NaN,Motorcycle,GCC,NaN,silver,CHINA,NaN,2.0
991128,HG6PDMRV8SW000119,2025.0,SHARMAX,GL250 (MOTORCYCLE),NaN,MOTORCYCLE,GCC,NaN,silver,China,148.0,2.0
991129,YY2V67MR25J171271,2026.0,SHARMAX,RR,NaN,Motorcycle,GCC,NaN,green,CHINA,NaN,2.0
991130,LZBTX9B95S1003657,2025.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,red,China,2.0,2.0
991131,LBBN64004PBF55749,2023.0,SHARMAX,FX150 ULT,NaN,Motorcycle,GCC,NaN,blue,CHINA,234.0,1.0
991132,L7GPCLLY6S1227802,2025.0,SHARMAX,STREET BIKE 175 ME,NaN,Motorcycle,GCC,NaN,gray and black,CHINA,NaN,2.0
991133,HG6PDMRVXSW000123,2025.0,SHARMAX,GL250 (MOTORCYCLE),NaN,Motorcycle,GCC,NaN,silver,China,NaN,2.0
991134,HA9TX9A20S1MAN017,2025.0,SHARMAX,VESPITO,NaN,Motorcycle,GCC,NaN,white,China,NaN,1.0
991135,HA9TX9A28S1MAN072,2025.0,SHARMAX,VESPITO,NaN,Motorcycle,GCC,NaN,green and white,China,NaN,2.0
991136,QJ157FMJB13543241,2023.0,SHARMAX,NX150,NaN,Motorcycle,GCC,NaN,blue,CHINA,150.0,2.0
994782,HA9TX9A21S1MAN026,2025.0,SHARMAX,VESPITO 150,NaN,Motorcycle,GCC,NaN,white,China,130.0,2.0
994803,HA9TX9A26S1MAN023,2025.0,SHARMAX,VESPITO 150,NaN,Motorcycle,GCC,NaN,beige,China,140.0,2.0
995009,LXYJCNLOXP0410401,2023.0,SHARMAX,SHARMAX ENDURO2,NaN,Motorcycle,GCC,NaN,black and silver,China,150.0,2.0

In [125]:
from make_grouping import apply_grouping, grouping_report

# Apply — creates a new column, never overwrites the original
df_clean["make_grouped"] = apply_grouping(df_clean["make"])

# See a full consolidation report with row counts
grouping_report(df_clean["make"], df_clean["make_grouped"])

============================================================
  Make consolidation report
  253 makes  →  217 makes  (−36)
============================================================

Groups merged:

  CHANGAN (4168 rows total)
    ← AVATR (204), DEEPAL (112)
  CHERY (1318 rows total)
    ← EXEED (497), JAECOO (32), OMODA (3)
  DONGFENG (368 rows total)
    ← AEOLUS (58), DONGFENG E (6), DONGFENG-AEOLUS (43), DONGFENG-XIAOKA (3), FORTHING (116), VOYAH (95)
  FAW (1020 rows total)
    ← BESTUNE (478), HONGQI (536)
  GAC (1524 rows total)
    ← HYCAN (2), TRUMPCHI (3)
  GEELY (3982 rows total)
    ← LOTUS (47), LYNK & CO (66), POLESTAR (83), VOLVO (1028), ZEEKR (233)
  GWM (2405 rows total)
    ← HAVAL (1239), TANK (465)
  HARLEY-DAVIDSON (406 rows total)
    ← LIVEWIRE (3)
  JIYUE (16 rows total)
    ← JIDU (15)
  KTM (69 rows total)
    ← GAS GAS (2), HUSQVARNA (5)
  MERCEDES BENZ (35529 rows total)
    ← MAYBACH (5)
  PIAGGIO (309 rows total)
    ← APRILIA (54), MOTO GUZZI (6), VESPA (236)
  POLARIS (144 rows total)
    ← SLINGSHOT (6)
  SAIC (7921 rows total)
    ← MAXUS (520), MG (7394), WULING (5)
  SHARMAX (138 rows total)
    ← SHARAMAX (3)
  TOYOTA (239902 rows total)
    ← SCION (3)

Unchanged makes: 201
============================================================

In [127]:
df_clean["make"] = apply_grouping(df_clean["make"])
df_clean.to_csv("vin_data_grouped.csv", index=False)

In [23]:
makes_array = sorted(df['make'].dropna().unique())

for make in makes_array:
    print(make)

ABARTH
ACURA
ADMIRAL
AEOLUS
AFTEK
AIQAR
AITO
AL DAMANI
ALFA ROMEO
APACHE
APRILIA
APULUO
ARI
ASHOK
ASHOK LEYLAND
ASTON MARTIN
AUDI
AVATR
AVENGER
AYED
AYED AYED
AYED BIKE
BAIC
BAJA
BAJAJ
BAOJUN
BAW
BENDA
BENELLI
BENTLEY
BESTUNE
BETA
BIMOTA
BIUE BAIRD
BMW
BORGWARD
BRILLIANCE
BUELL
BUGATTI
BUICK
BYD
BYD - DENZA
BYD - LEOPARD
BYD - YANGWANG
CADILLAC
CAN
CAN-AM
CATERHAM
CATERPILLAR
CF MOTO
CFMOTO
CHAMP
CHANGAN
CHANGHUA
CHERY
CHERY - ICAR
CHEVROLET
CHRYSLER
CITROEN
CMC
DAEWOO
DAF
DAIHATSU
DATSUN
DEEPAL
DELOREAN
DEXER
DFSK
DODGE
DONGFENG
DONGFENG E
DONGFENG-AEOLUS
DONGFENG-XIAOKA
DORCEN
DUCATI
ECOWAY
EICHER
ELECTRIC MOTION
EMPALA
ESCHER
EXEED
FANTIC
FARIZON
FAW
FERRARI
FIAT
FLONY
FOLONY
FORCE
FORD
FORTHING
FOTON
GAC
GAS GAS
GEELY
GENESIS
GMC
GREAT WALL
GUNAU
GWM - WEY
HAOJUE
HARLEY-DAVIDSON
HART FORD
HAVAL
HERO
HIG
HIGER
HINO
HIPHI
HONDA
HONGQI
HUAIHAI
HUMMER
HUSQVARNA
HYCAN
HYOSUNG
HYUNDAI
INDIAN  MOTORCYCLE
INDIAN MOTORCYCLE
INEOS
INFINITI
ISUZU
ITALJET
IVECO
JAC
JAECOO
JAGUAR
JCB
JEEP
JETOUR
JIDU
JINBEI
JIYUE
JMC
JOYLONG
KAIYI
KAMA
KAN M
KAOE K
KAWASAKI
KIA
KING LONG
KOASKO
KOENIGSEGG
KOVE
KTM
KYMCO
LADA
LAMBORGHINI
LANCIA
LAND ROVER
LEADING
LEAPMOTOR
LEXUS
LI
LI AUTO
LIEBHERR
LIFAN
LINCOLN
LIVEWIRE
LONSIN
LOTUS
LUCID
LUXGEN
LYKAN
LYNK & CO
MACK
MAEXTRO
MAHINDRA
MAN
MANN
MASERATI
MAXUS
MAYBACH
MAZDA
MCLAREN
MERCEDES BENZ
MERCURY
MG
MHERO
MINI
MITSUBISHI
MONTESA
MORGAN
MOTO GUZZI
MV AGUSTA
NETA
NIO
NISSAN
OMODA
OPEL
PADAR
PAGANI
PEMBLETON
PEUGEOT
PIAGGIO
POLARIS
POLESTAR
PONTIAC
PORSCHE
POWEREAGLE
PREVOST
PROTON
PUYUAN
QINGLING
RABDAN
RAM
RENAULT
RIDDARA
RIVIAN
ROCKY
ROLLS ROYCE
ROX
ROYAL ALLOY
ROYAL ENFIELD
SAAB
SAIC
SAIMO
SAMSUNG
SANDSTORM
SANIYA
SANY
SANYA
SANYOU
SATURN
SCANIA
SCION
SCORPA
SEAT
SERES
SHANG JAN
SHARAMAX
SHARMAX
SHERCO
SINOTRUK
SKODA
SKYWELL
SLINGSHOT
SMART
SOUEAST
SOUO
SSANGYONG
SUBARU
SUZUKI
SWIFT
SWM
SYM
TAM
TANK
TATA
TESLA
TGB
TOYOTA
TRIUMPH
TRUMPCHI
TVS
TYANMA
UAZ
VANDER
VANDERHALL
VESPA
VGV
VICTORIA
VICTORY
VINFAST
VOLG
VOLKSWAGEN
VOLTAMP
VOLVO
VOYAH
WIESMANN
WULING
XCMG
XIAOMI
XPENG
YADEA
YAMAHA
YUTONG
ZAMIYAD
ZEEKR
ZENIN
ZERO
ZHENGZHOU
ZNA
ZNIN
ZONGSHEN
ZONTES
ZOTYE
ZXAUTO