In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data/depreciation_all_models.csv")

In [4]:
df

,make,model,n,distinct_years,annual_dep_rate,method
0,NISSAN,PATROL,552,37,0.060469,fit_high
1,TOYOTA,CAMRY,457,34,0.115771,fit_high
2,TOYOTA,LAND CRUISER,405,34,0.101259,fit_high
3,TOYOTA,COROLLA,354,34,0.107918,fit_high
4,FORD,F-150,298,28,0.130870,fit_high
...,...,...,...,...,...,...
3348,XPENG,P7,1,1,0.052096,brand_fallback
3349,Yamaha,250 CC,1,1,0.119558,global_fallback
3350,Yamaha,DT175,1,1,0.119558,global_fallback
3351,Yamaha,XSR900,1,1,0.119558,global_fallback
3352,Yamaha,Y Z F 690,1,1,0.119558,global_fallback

In [5]:
df.isnull().sum()

make               0
model              0
n                  0
distinct_years     0
annual_dep_rate    0
method             0
dtype: int64

In [6]:
df["method"].unique()

array(['fit_high', 'fit_medium', 'fit_low', 'brand_fallback',
       'global_fallback'], dtype=object)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3353 entries, 0 to 3352
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   make             3353 non-null   object
 1   model            3353 non-null   object
 2   n                3353 non-null   int64
 3   distinct_years   3353 non-null   int64
 4   annual_dep_rate  3353 non-null   float64
 5   method           3353 non-null   object
dtypes: float64(1), int64(2), object(3)
memory usage: 157.3+ KB

In [8]:
df["method"].value_counts()

method
brand_fallback     1371
fit_low            1023
fit_medium          534
fit_high            324
global_fallback     101
Name: count, dtype: int64

In [9]:
df

,make,model,n,distinct_years,annual_dep_rate,method
0,NISSAN,PATROL,552,37,0.060469,fit_high
1,TOYOTA,CAMRY,457,34,0.115771,fit_high
2,TOYOTA,LAND CRUISER,405,34,0.101259,fit_high
3,TOYOTA,COROLLA,354,34,0.107918,fit_high
4,FORD,F-150,298,28,0.130870,fit_high
...,...,...,...,...,...,...
3348,XPENG,P7,1,1,0.052096,brand_fallback
3349,Yamaha,250 CC,1,1,0.119558,global_fallback
3350,Yamaha,DT175,1,1,0.119558,global_fallback
3351,Yamaha,XSR900,1,1,0.119558,global_fallback
3352,Yamaha,Y Z F 690,1,1,0.119558,global_fallback

In [10]:
df[["make", "model", "annual_dep_rate"]]

        make         model  annual_dep_rate
0     NISSAN        PATROL         0.060469
1     TOYOTA         CAMRY         0.115771
2     TOYOTA  LAND CRUISER         0.101259
3     TOYOTA       COROLLA         0.107918
4       FORD         F-150         0.130870
...      ...           ...              ...
3348   XPENG            P7         0.052096
3349  Yamaha        250 CC         0.119558
3350  Yamaha         DT175         0.119558
3351  Yamaha        XSR900         0.119558
3352  Yamaha     Y Z F 690         0.119558

[3353 rows x 3 columns]

In [11]:
df[["make", "model", "annual_dep_rate"]].to_csv("data/annual_dep_rate.csv", index=False)